### ISSUE TITLE
Add support for AS OF queries for MySQL tables (dolt syntax)

### ISSUE THREAD

**Issue by chrisfw** [StarRocks/starrocks#10004]
## Feature request

**I am attempting to use doltdb, a mysql compatible database that supports SQL 2011 versioning via AS OF queries, etc., but the StarRocks parser does not recognize the syntax**

```
MySQL [enquesta]> select * from TAXDISTRICTEXT as of 'etnrfadqtc9fnils5371sjngu561g991';
ERROR 1064 (HY000): Syntax error in line 1:
...from TAXDISTRICTEXT as of 'etnrfadqtc9fnils5371sjngu56...

MySQL [enquesta]> select * from TAXDISTRICTEXT as of TIMESTAMP('2022-08-14');
ERROR 1064 (HY000): Syntax error in line 1:
select * from TAXDISTRICTEXT as of TIMESTAMP('2022-08-14')
```

**Describe the solution you'd like**
Provide the ability for MySQL tables to be created where the AS OF syntax is supported, perhaps through a property specification in the CREATE TABLE DDL.
 
**Describe alternatives you've considered**
Creating views in dolt for each day that encapsulate the AS OF query.  This is not a great option though.

**Comment by fulghum** [comment]
This feature made it out in the [StarRocks 2.5.2 release](https://github.com/StarRocks/starrocks/releases/tag/2.5.2) 🎉  Thank you StarRocks team!! 🙏
