### ISSUE TITLE
Support CDC

### ISSUE THREAD

**Issue by zengjinbo** [StarRocks/starrocks#10007]
可以使用 Flink CDC 获取实时变更数据

**Comment by chrisfw** [comment]
Does starrocks already support change data capture via the flink connector?  I too would like to understand the best way to connect a data pipeline driven by CDC to a starrocks database.

Thanks in advance,
Chris Whelan

**Comment by jaogoy** [comment]
@zengjinbo 可以看 https://docs.starrocks.io/zh-cn/latest/loading/Flink_cdc_load

@chrisfw Refer to https://docs.starrocks.io/en-us/latest/loading/Flink_cdc_load

**Comment by chrisfw** [comment]
Thank you @jaogoy

**Comment by zengjinbo** [comment]
希望实现的是starrocks支持CDC功能，能通过Flink等方式，实时读取starrocks的数据变化

**Comment by jaogoy** [comment]
@zengjinbo Currently, StarRocks doesn't support CDC binlog to let Flink read, But, you can use Flink source connector to read StarRocks data.

**Comment by zengjinbo** [comment]
所以希望能加入binlog机制或者提供一个可以用flink等 CDC读取的方式，也可以是提供一个实时推送到kafka的组件，可以让下游系统实时感知数据变化
