### ISSUE TITLE
Routine Load Running Error [failed to get partition meta: Local: Timed out]

### ISSUE THREAD

**Issue by shshenhua** [StarRocks/starrocks#10065]
### Steps to reproduce the behavior (Required)
1. create routine load 
CREATE ROUTINE LOAD routine_load_Test1 ON Table1
COLUMNS TERMINATED BY ",",
COLUMNS (c1,c2,c3,c4,c5)
PROPERTIES
(
    "format"="json",
    "max_error_number"="1000"
)
FROM KAFKA
(
    "kafka_broker_list"= "kafkahost:9092",
    "kafka_topic" = "topic1",
    "property.group.id" = "group1"
);

2.show routine load \G
3. resume routine load for routine_load_Test1 

### Expected behavior (Required)
routine load status is running 

### Real behavior (Required)
routine load status is PAUSED
ReasonOfStateChanged: ErrorReason{errCode = 4, msg='Job failed to fetch all current partition with error [failed to send proxy request to TNetworkAddress(hostname:behost, port:8060) err failed to send proxy request to TNetworkAddress(hostname:behost, port:8060) err [failed to get partition meta: Local: Timed out]]'}

![image](https://user-images.githubusercontent.com/16952962/184828631-98218e49-f6d7-43d8-85d7-cf411ed0d605.png)

3. be error massage
 W0816 15:49:44.400926 39686 data_consumer.cpp:322] failed to get partition meta: Local: Timed out

### StarRocks version (Required)
main branch，latest code  error
I test version-2.3.0  is  success

**Comment by rickif** [comment]
This is fixed by https://github.com/StarRocks/starrocks/pull/10001.

**Comment by rickif** [comment]
@shshenhua Could please check with the new version ?

**Comment by shshenhua** [comment]
this error is solved
W0816 15:49:44.400926 39686 data_consumer.cpp:322] failed to get partition meta: Local: Timed out

but now a new problem
The row is out of partition ranges. Please add a new partition.. Row: [xxx, 'xxx', '1', xxx 'F', 0]
table has 5 column and routine load column also 5 column，error massage has 6 column

when I create table with 6 column，and routine load with 6 coulmn， error message has 7 column

**Comment by shshenhua** [comment]
@rickif

**Comment by rickif** [comment]
Is the destination a primary key table?

**Comment by shshenhua** [comment]
yes  it is primary key table

**Comment by rickif** [comment]
The primary key table would add a internal operation column, so the error message contains 6 columns.
This has no effect on your data loading.

**Comment by shshenhua** [comment]
ok thx

**Comment by jaogoy** [comment]
> ReasonOfStateChanged

So, what's the error message, or just some info logs?
We should fix the inappropriate log message if it's just a normal loading to Primary Key table.

**Comment by shshenhua** [comment]
Error message is :
ErrorLogUrls: http://xxx:port/api/_load_error_log?file=error_log_993fa4f1995e4c4d_8cdfe76941655990,
Error: The row is out of partition ranges. Please add a new partition.. Row: [6836723, 'M5044864513', '1', 2022-08-22, 'F', NULL, 0]

kafka_table has 0 rows
mysql> select * from  kafka_table  limit 10;
Empty set (0.01 sec)

@jaogoy @rickif

**Comment by shshenhua** [comment]
error message is 
Error: The row is out of partition ranges. Please add a new partition.. Row: [4410368, 'M104208237', '1', 2022-08-22, 'F', 0]

and kafka_table has 0 rows
mysql> select * from kafka_table ;
Empty set (0.01 sec)

create kafka_table sql:
CREATE TABLE `kafka_table` (
  `c1` int(11) NOT NULL COMMENT "",
  `c2` varchar(50) NOT NULL COMMENT "",
  `c3` varchar(10) NOT NULL COMMENT "",
  `c4` date NOT NULL COMMENT "",
  `c5` varchar(10) NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(`c1`, `c2`, `c3`, `c4`)
COMMENT "OLAP"
PARTITION BY RANGE(`c4`)
(PARTITION p20220818 VALUES [('2022-08-18'), ('2022-08-19')),
PARTITION p20220819 VALUES [('2022-08-19'), ('2022-08-20')),
PARTITION p20220820 VALUES [('2022-08-20'), ('2022-08-21')))
DISTRIBUTED BY HASH(`c1`) BUCKETS 10 
PROPERTIES (
"replication_num" = "1",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-1",
"dynamic_partition.end" = "1",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "10",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);  

routine load sql:
CREATE ROUTINE LOAD routine_loadtest ON kafka_table
COLUMNS TERMINATED BY ",",
COLUMNS (c1,c2,c3,c4,c5)
PROPERTIES
(
    "format"="json",
    "max_error_number"="1000"
)
FROM KAFKA
(
    "kafka_broker_list"= "kafkahost:9092",
    "kafka_topic" = "topic",
    "property.group.id" = "testgroup"
);

@rickif @jaogoy
