### ISSUE TITLE
【statistics】histogram_sample_ratio error

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#10104]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
 CREATE TABLE `aggregate_table_with_null` ( `k1` date, `k2` datetime, `k3` char(20), `k4` varchar(20), `k5` boolean, `v1` bigint sum, `v2` bigint sum, `v3` bigint sum, `v4` bigint max, `v5` largeint max, `v6` float min, `v7` double min, `v8` decimal(27,9) sum ) ENGINE=OLAP AGGREGATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`) COMMENT "OLAP" DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3 PROPERTIES ( "replication_num" = "3", "storage_format" = "v2" );
```
2. INSERT INTO '....'
```
curl --location-trusted -u root: -T /home/disk4/lvchenyang/code/StarRocksTest/lib/../common/data/basic_types_data -XPUT -H label:stream_load_1660094546355 http://ip:port/api/lcy/aggregate_table_with_null/_stream_load
```
3. analyze
```
analyze table aggregate_table_with_null update histogram on k2
```
4. SELECT  '....'
```SHOW HISTOGRAM META;```
### Expected behavior (Required)
histogram_sample_ratio=0.1
### Real behavior (Required)
histogram_sample_ratio=0.09999085
![image](https://user-images.githubusercontent.com/57162397/185054950-a075a6bb-7fd9-459f-9abc-8678a7bd00e0.png)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 4062096 |
+----------------------+
```

**Comment by HangyuanLiu** [comment]
https://github.com/StarRocks/starrocks/pull/10130

**Comment by lvchenyang-maker** [comment]
![image](https://user-images.githubusercontent.com/57162397/188262250-eb75af31-6cd6-4a41-af3a-4224b7c50c4e.png)
