### ISSUE TITLE
ARRAY_DISTINCT(ARRAY_AGG(xxx))  在insert into语句里会出问题

### ISSUE THREAD

**Issue by delpan7** [StarRocks/starrocks#10117]
### Steps to reproduce the behavior (Required)
1. select ms.member_id, ms.media_id, a.product_ids, last_active_time, created_at, NOW() 
from ad_member_statistic as ms inner join (select member_id, ARRAY_DISTINCT(ARRAY_AGG(product_id)) AS product_ids from ad_business_action_logs where event IN (482, 728) AND member_id< 1201089057 group by member_id) as a ON a.member_id=ms.member_id;   可以执行成功
2. insert into ad_member_statistic
select ms.member_id, ms.media_id, a.product_ids, last_active_time, created_at, NOW() 
from ad_member_statistic as ms inner join (select member_id, ARRAY_DISTINCT(ARRAY_AGG(product_id)) AS product_ids from ad_business_action_logs where event IN (482, 728) AND member_id< 1201089057 group by member_id) as a ON a.member_id=ms.member_id;  报    ERROR 1064 (HY000): Vectorized engine does not support the operator, node_type: 5

### Expected behavior (Required)
返回插入条数

### Real behavior (Required)
ERROR 1064 (HY000): Vectorized engine does not support the operator, node_type: 5
### StarRocks version (Required)
 - v2.2.4

**Comment by kangkaisen** [comment]
@delpan7 please send the create table sql, thanks.

**Comment by delpan7** [comment]
CREATE TABLE ad_member_statistic
(
    `member_id` int NOT NULL DEFAULT '0' COMMENT '用户id',
    `media_id` int NOT NULL DEFAULT '0' COMMENT '媒体id',
    product_ids STRING  NOT NULL DEFAULT '' COMMENT '用户参与的产品ID列表',
    last_active_time DateTime COMMENT '最后活跃时间',
    created_at DateTime COMMENT '创建时间',
    updated_at DateTime COMMENT '更新时间'
)
PRIMARY KEY (member_id)
DISTRIBUTED BY HASH(member_id) BUCKETS 8
PROPERTIES(
    "replication_num" = "2"
);


create table ad_business_action_logs
(
    created_at              DateTime NOT NULL COMMENT '事件时间',
    event                   smallint NOT NULL DEFAULT "0" COMMENT '事件类型',
    media_id                int NOT NULL DEFAULT "0" COMMENT '媒体ID',
    business_id             int NOT NULL DEFAULT "0" COMMENT '业务ID',
    member_id               int NOT NULL DEFAULT "0" COMMENT 'VIP号',

    reg_day                 smallint NOT NULL DEFAULT "0" COMMENT '用户注册天数',
    daily_group_id          int NOT NULL DEFAULT "0" COMMENT '用户日常组',
    platform                tinyint NOT NULL DEFAULT '3' COMMENT '支持平台[1、IOS，2、Android，3、Web]',

    media_owner_id          int NOT NULL DEFAULT "0" COMMENT '媒体主ID',
    agent_id                int NOT NULL DEFAULT "0" COMMENT '代理商ID',

    advert_id               int NOT NULL DEFAULT "0" COMMENT '广告ID',
    product_id              int NOT NULL DEFAULT "0" COMMENT '产品ID',
    advertiser_id           int NOT NULL DEFAULT "0" COMMENT '游戏厂商ID'
)
PRIMARY KEY (created_at, event, media_id, business_id)
PARTITION BY RANGE(created_at) (
    START ("2019-01-01") END ("2022-08-01") EVERY (INTERVAL 1 MONTH)
)
DISTRIBUTED BY HASH(media_id) BUCKETS 4
PROPERTIES(
    "replication_num" = "2",
    "dynamic_partition.enable" = "true",
    "dynamic_partition.time_unit" = "MONTH",
    "dynamic_partition.end" = "3",
    "dynamic_partition.prefix" = "p",
    "dynamic_partition.buckets" = "4"
);

**Comment by trueeyu** [comment]
should use array_join to cast `array` to `string`

```
insert into ad_member_statistic
select ms.member_id, ms.media_id, a.product_ids, last_active_time, created_at, NOW()
from ad_member_statistic as ms inner join (select member_id, ARRAY_JOIN(ARRAY_DISTINCT(ARRAY_AGG(product_id)), ",") AS product_ids from ad_business_action_logs where event IN (482, 728) AND member_id< 1201089057 group by member_id) as a ON a.member_id=ms.member_id; 
```

**Comment by delpan7** [comment]
确实是类型不一致的问题，谢谢
