### ISSUE TITLE
Shouldn't timeout or OOM when pipeline_dop or is parallel_fragment_exec_instance_num very large

### ISSUE THREAD

**Issue by kangkaisen** [StarRocks/starrocks#10157]
for TPC-H SF500 Q2, varying pipeline_dop from 1 to 10 and parallel_fragment_exec_instance_num from 1 to 10, there are some timeout and OOM.

(4,2) means as follows:

```
set session pipeline_dop=4;                         
set session parallel_fragment_exec_instance_num = 2;
```

|    | (1,1)       | (2,1)       | (3,1)       | (4,1)       | (5,1)       | (6,1)       | (7,1)       | (8,1)       | (9,1)       | (10,1)   |
| -- | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- | -------- |
| q2 |       2,456 |       1,381 |       1,604 |       1,247 |       1,209 |       1,230 |       1,231 |       1,218 |         734 |  timeout |

|    | (1,2)       | (2,2)       | (3,2)       | (4,2)       | (5,2)    |
| -- | ----------- | ----------- | ----------- | ----------- | -------- |
| q2 |       1,869 |       1,344 |       1,517 |       1,156 |  timeout |

|    | (1,3)       | (2,3)       | (3,3)       | (4,3)    |
| -- | ----------- | ----------- | ----------- | -------- |
| q2 |       1,224 |       1,082 |         996 |  timeout |

|    | (1,4)       | (2,4)       | (3,4) |
| -- | ----------- | ----------- | ----- |
| q2 |       1,869 |       1,044 |  OOM  |

|    | (1,5)       | (2,5)    |
| -- | ----------- | -------- |
| q2 |       1,285 |  timeout |

|    | (1,6)       | (2,6)    |
| -- | ----------- | -------- |
| q2 |       1,406 |  timeout |

|    | (1,7)       | (2,7)    |
| -- | ----------- | -------- |
| q2 |       1,220 |  timeout |

|    | (1,8)       | (2,8) |
| -- | ----------- | ----- |
| q2 |       1,194 |  OOM  |

|    | (1,9)       | (2,9) |
| -- | ----------- | ----- |
| q2 |       1,085 |  OOM  |

|    | (1,10) |
| -- | ------ |
| q2 |  OOM   |

1. At least, we shouldn't timeout when (10, 1), we should fix it.
2. For the (1,10), I think we shouldn't OOM, we should fix it.

**Comment by kangkaisen** [comment]
@ZiheLiu please fix the timeout issue.  @stdpain please fix the OOM issue

**Comment by stdpain** [comment]
I can't reproduce this case in my environment (1FE 4BE 32GB 14cpu)
maybe more information is needed.

**Comment by dbjoa** [comment]
> I can't reproduce this case in my environment (1FE 4BE 64GB 14cpu Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz) maybe more information is needed.

Have you tried to run the query just after `analyze table ...`?

**Comment by dbjoa** [comment]
Here is the profile result captured while running `q2` just after `analyze table ...`:
```
 ==========
 Properties
 ==========
 Session
               Host: cde-new-cluster1-3
          Boot Time: 2022. 6. 8 오전 10:14:58
         Begin Time: 2022. 8. 23 오후 8:09:25
           End Time: 2022. 8. 23 오후 8:09:58

 Configuration
 A sample is taken every 10.0ms (CPU Time).
  Record Callstacks: true
 Monitor Process Exits: true
 Allow Power Management: false
 Gather Kernel Symbols: true
     Profile Driver: rrprofile
 Profile Driver per-CPU Buffer Size: 192.00KB
 Profile Driver Event Buffer Multiple: 0x
 Profile Driver Event Buffer Watershed: 25%
      Notify Driver: rrnotify
 Notify Driver Buffer: 1.00MB
 Notify Driver Buffer Watershed: 25%

 Software
        Application: Zoom 3.3.3
  Application Build: 1 (x86-64)
                 OS: CentOS Linux release 7.9.2009 (Core) 3.10.0-1160.el7.x86_64
           OS Build: #1 SMP Mon Oct 19 16:18:59 UTC 2020 (x86_64)
    Virtual Machine: No

 Hardware
          Processor: 48 x 3.10GHz Intel Haswell
             Memory: 125.64GB
            Machine: Supermicro X10DRi

 ========================================
 Hotspot - Process 'starrocks_be [30018]'
 ========================================
       Total Time (%)        Self Time (%) Symbol                                                                                     Size                                          Module
    5.2min    (21.8%)    5.2min    (21.8%) void starrocks::vectorized::JoinHashMap<(starrocks::PrimitiveType)25, starrocks::vectorized::JoinBuildFunc<(starrocks::PrimitiveType)25>, starrocks::vectorized::JoinProbeFunc<(starrocks::PrimitiveType)25> >::_probe_from_ht<false>(starrocks::RuntimeState*, std::vector<long, std::allocator<long> > const&, std::vector<long, std::allocator<long> > const&) [clone .isra.0]       320B                                    starrocks_be
    4.1min    (17.0%)    4.1min    (17.0%) void starrocks::vectorized::JoinHashMap<(starrocks::PrimitiveType)7, starrocks::vectorized::FixedSizeJoinBuildFunc<(starrocks::PrimitiveType)7>, starrocks::vectorized::FixedSizeJoinProbeFunc<(starrocks::PrimitiveType)7> >::_probe_from_ht<true>(starrocks::RuntimeState*, std::vector<__int128, std::allocator<__int128> > const&, std::vector<__int128, std::allocator<__int128> > const&)     1.42KB                                    starrocks_be
  2.3min       (9.5%)  1.7min       (7.1%) starrocks::vectorized::FixedLengthColumnBase<long>::append_selective(starrocks::vectorized::Column const&, unsigned int const*, unsigned int, unsigned int)       192B                                    starrocks_be
  1.4min       (5.6%)  1.3min       (5.6%) LZ4_compress_fast_extState                                                              11.25KB                                    starrocks_be
  1.1min       (4.6%)  1.1min       (4.5%) starrocks::vectorized::FixedSizeJoinProbeFunc<(starrocks::PrimitiveType)7>::lookup_init(starrocks::vectorized::JoinHashTableItems const&, starrocks::vectorized::HashTableProbeState*)     2.19KB                                    starrocks_be
 59.5sec       (4.1%) 59.5sec       (4.1%) starrocks::vectorized::FixedLengthColumnBase<long>::serialize_batch_at_interval(unsigned char*, unsigned long, unsigned long, unsigned long, unsigned long)        48B                                    starrocks_be
 57.1sec       (4.0%) 57.1sec       (4.0%) __memset_sse2                                                                              352B                                    libc-2.17.so
 51.9sec       (3.6%) 51.9sec       (3.6%) LZ4_decompress_safe                                                                      2.66KB                                    starrocks_be
    4.6min    (19.2%) 49.5sec       (3.4%) starrocks::pipeline::ExchangeSinkOperator::push_chunk(starrocks::RuntimeState*, std::shared_ptr<starrocks::vectorized::Chunk> const&)     3.98KB                                    starrocks_be
 44.0sec       (3.0%) 44.0sec       (3.0%) __memcpy_ssse3_back                                                                     10.69KB                                    libc-2.17.so
 16.7sec       (1.2%) 16.7sec       (1.2%) starrocks::vectorized::FixedLengthColumnBase<long>::fnv_hash(unsigned int*, unsigned int, unsigned int) const     3.06KB                                    starrocks_be
 15.4sec       (1.1%) 15.4sec       (1.1%) copy_user_enhanced_fast_string                                                              32B                                         vmlinux
 12.3sec       (0.9%) 12.3sec       (0.9%) __libc_malloc                                                                              320B                                    starrocks_be
 33.7sec       (2.3%) 12.1sec       (0.8%) <Unknown Symbol>                                                                                                                      <Unknown>
 12.1sec       (0.8%) 12.1sec       (0.8%) sysret_check                                                                               255B                                         vmlinux
 20.3sec       (1.4%) 10.5sec       (0.7%) starrocks::pipeline::PipelineDriverPoller::run_internal()                                5.98KB                                    starrocks_be
    3.5min    (14.5%)  8.2sec       (0.6%) starrocks::pipeline::ExchangeSinkOperator::Channel::add_rows_selective(starrocks::vectorized::Chunk*, int, unsigned int const*, unsigned int, unsigned int, starrocks::RuntimeState*)     1.64KB                                    starrocks_be
  7.8sec       (0.5%)  7.8sec       (0.5%) TCMallocImplementation::GetAllocatedSize(void const*)                                      304B                                    starrocks_be
  7.0sec       (0.5%)  7.0sec       (0.5%) clock_gettime                                                                            1.33KB                                            vdso
   18.2min    (75.8%)  6.5sec       (0.4%) starrocks::pipeline::PipelineDriver::process(starrocks::RuntimeState*, int)              5.25KB                                    starrocks_be
 12.0sec       (0.8%)  6.2sec       (0.4%) tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned int, int)       336B                                    starrocks_be
  6.3sec       (0.4%)  5.8sec       (0.4%) find_busiest_group                                                                       2.39KB                                         vmlinux
  5.8sec       (0.4%)  5.8sec       (0.4%) std::vector<long, std::allocator<long> >::_M_fill_insert(__gnu_cxx::__normal_iterator<long*, std::vector<long, std::allocator<long> > >, unsigned long, long const&)     1.28KB                                    starrocks_be
  5.5sec       (0.4%)  5.5sec       (0.4%) __GI___pthread_mutex_lock                                                                  396B                              libpthread-2.17.so
  4.8sec       (0.3%)  4.8sec       (0.3%) std::vector<long, std::allocator<long> >::_M_default_append(unsigned long)                 416B                                    starrocks_be
  4.3sec       (0.3%)  4.3sec       (0.3%) starrocks::DataStreamRecvr::has_output_for_pipeline(int) const                             336B                                    starrocks_be
  4.2sec       (0.3%)  4.2sec       (0.3%) __GI___pthread_mutex_unlock                                                                148B                              libpthread-2.17.so
  1.4min       (5.9%)  4.1sec       (0.3%) starrocks::vectorized::Chunk::append_selective(starrocks::vectorized::Chunk const&, unsigned int const*, unsigned int, unsigned int)       128B                                    starrocks_be
  1.6sec       (0.1%)  1.6sec       (0.1%) starrocks::pipeline::SinkBuffer::is_full() const                                           432B                                    starrocks_be
  5.8sec       (0.4%)  3.8sec       (0.3%) memcpy_toiovec                                                                             176B                                         vmlinux
  1.7sec       (0.1%)  1.5sec       (0.1%) void starrocks::vectorized::RuntimeBloomFilter<(starrocks::PrimitiveType)6>::t_evaluate<true>(starrocks::vectorized::Column*, starrocks::vectorized::JoinRuntimeFilter::RunningContext*) const     1.33KB                                    starrocks_be
  3.6sec       (0.2%)  3.6sec       (0.2%) system_call_after_swapgs                                                                   314B                                         vmlinux
  7.1sec       (0.5%)  3.6sec       (0.2%) try_to_wake_up                                                                             912B                                         vmlinux
  4.4sec       (0.3%)  3.4sec       (0.2%) tcmalloc::CentralFreeList::ReleaseToSpans(void*)                                           384B                                    starrocks_be
  3.0sec       (0.2%)  3.0sec       (0.2%) idle_cpu                                                                                    80B                                         vmlinux
```

**Comment by kangkaisen** [comment]
[query dump.pdf](https://github.com/StarRocks/starrocks/files/9437391/query.dump.pdf)

**Comment by kyuhomania** [comment]
{"statement":"--Q2
select /* TPC-H Q2 */
    s_acctbal,
    s_name,
    n_name,
    p_partkey,
    p_mfgr,
    s_address,
    s_phone,
    s_comment
from
    part,
    supplier,
    partsupp,
    nation,
    region
where
    p_partkey = ps_partkey
    and s_suppkey = ps_suppkey
    and p_size = 38
    and p_type like '%STEEL'
    and s_nationkey = n_nationkey
    and n_regionkey = r_regionkey
    and r_name = 'ASIA'
    and ps_supplycost = (
        select
            min(ps_supplycost)
        from
            partsupp,
            supplier,
            nation,
            region
        where
            p_partkey = ps_partkey
            and s_suppkey = ps_suppkey
            and s_nationkey = n_nationkey
            and n_regionkey = r_regionkey
            and r_name = 'ASIA'
    )
order by
    s_acctbal desc,
    n_name,
    s_name,
    p_partkey
limit 100;
","table_meta":{"tpch.nation":"CREATE TABLE `nation` (
  `n_nationkey` int(11) NOT NULL COMMENT "",
  `n_name` char(25) NOT NULL COMMENT "",
  `n_regionkey` int(11) NOT NULL COMMENT "",
  `n_comment` varchar(152) NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`n_nationkey`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`n_nationkey`) BUCKETS 1 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);","tpch.part":"CREATE TABLE `part` (
  `p_partkey` bigint(20) NOT NULL COMMENT "",
  `p_name` varchar(55) NOT NULL COMMENT "",
  `p_mfgr` char(25) NOT NULL COMMENT "",
  `p_brand` char(10) NOT NULL COMMENT "",
  `p_type` varchar(25) NOT NULL COMMENT "",
  `p_size` bigint(20) NOT NULL COMMENT "",
  `p_container` char(10) NOT NULL COMMENT "",
  `p_retailprice` decimal64(15, 2) NOT NULL COMMENT "",
  `p_comment` varchar(23) NOT NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`p_partkey`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`p_partkey`) BUCKETS 24 
PROPERTIES (
"replication_num" = "1",
"colocate_with" = "group_tpch_500p",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);","tpch.partsupp":"CREATE TABLE `partsupp` (
  `ps_partkey` bigint(20) NOT NULL COMMENT "",
  `ps_suppkey` bigint(20) NOT NULL COMMENT "",
  `ps_availqty` bigint(20) NOT NULL COMMENT "",
  `ps_supplycost` decimal64(15, 2) NOT NULL COMMENT "",
  `ps_comment` varchar(199) NOT NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`ps_partkey`, `ps_suppkey`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`ps_partkey`) BUCKETS 24 
PROPERTIES (
"replication_num" = "1",
"colocate_with" = "group_tpch_500p",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);","tpch.region":"CREATE TABLE `region` (
  `r_regionkey` bigint(20) NOT NULL COMMENT "",
  `r_name` char(25) NOT NULL COMMENT "",
  `r_comment` varchar(152) NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`r_regionkey`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`r_regionkey`) BUCKETS 1 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);","tpch.supplier":"CREATE TABLE `supplier` (
  `s_suppkey` bigint(20) NOT NULL COMMENT "",
  `s_name` char(25) NOT NULL COMMENT "",
  `s_address` varchar(40) NOT NULL COMMENT "",
  `s_nationkey` bigint(20) NOT NULL COMMENT "",
  `s_phone` char(15) NOT NULL COMMENT "",
  `s_acctbal` decimal64(15, 2) NOT NULL COMMENT "",
  `s_comment` varchar(101) NOT NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`s_suppkey`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`s_suppkey`) BUCKETS 12 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);"},
"table_row_count":{"tpch.nation":{"nation":25},
"tpch.part":{"part":100000000},
"tpch.partsupp":{"partsupp":400000000},
"tpch.region":{"region":5},
"tpch.supplier":{"supplier":5000000}},
"session_variables":"{"enable_resource_group":false,
"codegen_level":0,
"cbo_cte_reuse":false,
"character_set_connection":"utf8",
"cbo_use_correlated_join_estimate":true,
"enable_insert_strict":true,
"join_implementation_mode":"hash",
"tx_isolation":"REPEATABLE-READ",
"wait_timeout":28800,
"cbo_cte_reuse_rate":1.2,
"foreign_key_checks":true,
"character_set_results":"utf8",
"enable_global_runtime_filter":true,
"forward_to_master":false,
"cbo_enable_low_cardinality_optimize":true,
"new_planner_optimize_timeout":3000,
"force_schedule_local":false,
"cbo_enable_greedy_join_reorder":true,
"prefer_join_method":"broadcast",
"load_mem_limit":0,
"profiling":false,
"sql_safe_updates":0,
"global_runtime_filter_probe_min_size":102400,
"enable_vectorized_engine":true,
"query_delivery_timeout":300,
"net_write_timeout":60,
"collation_database":"utf8_general_ci",
"hash_join_push_down_right_table":true,
"new_planner_agg_stage":0,
"collation_connection":"utf8_general_ci",
"resource_group":"",
"broadcast_row_limit":15000000,
"exec_mem_limit":107374182400,
"cbo_max_reorder_node_use_dp":10,
"disable_join_reorder":false,
"is_report_success":false,
"enable_hive_column_stats":true,
"enable_groupby_use_output_alias":false,
"net_buffer_length":16384,
"query_timeout":300,
"cbo_max_reorder_node":50,
"max_execution_time":3000000,
"runtime_filter_scan_wait_time":20,
"SQL_AUTO_IS_NULL":false,
"event_scheduler":"OFF",
"disable_streaming_preaggregations":false,
"chunk_size":4096,
"disable_bucket_join":false,
"runtime_join_filter_push_down_limit":1024000,
"global_runtime_filter_probe_min_selectivity":0.5,
"query_mem_limit":0,
"enable_tablet_internal_parallel":true,
"enable_filter_unused_columns_in_scan_stage":true,
"div_precision_increment":4,
"auto_increment_increment":1,
"sql_mode_v2":32,
"character_set_client":"utf8",
"autocommit":true,
"enable_column_expr_predicate":true,
"pipeline_profile_level":1,
"parallel_fragment_exec_instance_num":10,
"max_scan_key_num":-1,
"net_read_timeout":60,
"streaming_preaggregation_mode":"auto",
"storage_engine":"olap",
"enable_optimizer_trace_log":false,
"cbo_enable_dp_join_reorder":true,
"tx_visible_wait_timeout":10,
"cbo_max_reorder_node_use_exhaustive":4,
"enable_sql_digest":false,
"profile_timeout":2,
"pipeline_dop":1,
"enable_query_dump":false,
"single_node_exec_plan":false,
"global_runtime_filter_build_max_size":67108864,
"sql_select_limit":9223372036854775807,
"statistic_collect_parallel":24,
"query_cache_type":0,
"disable_colocate_join":false,
"max_pushdown_conditions_per_column":-1,
"enable_exchange_pass_through":true,
"enable_predicate_reorder":false,
"workgroup_id":0,
"transmission_compression_type":"LZ4",
"enable_vectorized_insert":true,
"interactive_timeout":3600,
"enable_spilling":false,
"batch_size":0,
"cbo_enable_replicated_join":true,
"max_allowed_packet":1048576,
"enable_cbo":true,
"collation_server":"utf8_general_ci",
"time_zone":"Asia/Seoul",
"character_set_server":"utf8",
"enable_pipeline":true,
"cbo_use_nth_exec_plan":0,
"rewrite_count_distinct_to_bitmap_hll":true,
"parallel_exchange_instance_num":-1,
"allow_default_partition":false}",
"column_statistics":{"tpch.nation":{"n_nationkey":"[-Infinity, Infinity, 0.0, 1.0, 1.0] UNKNOWN",
"n_regionkey":"[-Infinity, Infinity, 0.0, 1.0, 1.0] UNKNOWN", "n_name":"[-Infinity, Infinity, 0.0, 1.0, 1.0] UNKNOWN"},
"tpch.part":{"p_partkey":"[-Infinity, Infinity, 0.0, 1.0, 1.0] UNKNOWN",
"p_type":"[-Infinity, Infinity, 0.0, 1.0, 1.0] UNKNOWN",
"p_mfgr":"[-Infinity, Infinity, 0.0, 1.0, 1.0] UNKNOWN",
"p_size":"[-Infinity, Infinity, 0.0, 1.0, 1.0] UNKNOWN"},
"tpch.partsupp":{"ps_suppkey":"[-Infinity, Infinity, 0.0, 1.0, 1.0] UNKNOWN",
"ps_partkey":"[-Infinity, Infinity, 0.0, 1.0, 1.0] UNKNOWN",
"ps_supplycost":"[-Infinity, Infinity, 0.0, 1.0, 1.0] UNKNOWN"},
"tpch.region":{"r_regionkey":"[-Infinity, Infinity, 0.0, 1.0, 1.0] UNKNOWN",
"r_name":"[-Infinity, Infinity, 0.0, 1.0, 1.0] UNKNOWN"},
"tpch.supplier":{"s_comment":"[-Infinity, Infinity, 0.0, 1.0, 1.0] UNKNOWN",
"s_phone":"[-Infinity, Infinity, 0.0, 1.0, 1.0] UNKNOWN",
"s_nationkey":"[-Infinity, Infinity, 0.0, 1.0, 1.0] UNKNOWN",
"s_name":"[-Infinity, Infinity, 0.0, 1.0, 1.0] UNKNOWN",
"s_address":"[-Infinity, Infinity, 0.0, 1.0, 1.0] UNKNOWN",
"s_acctbal":"[-Infinity, Infinity, 0.0, 1.0, 1.0] UNKNOWN",
"s_suppkey":"[-Infinity, Infinity, 0.0, 1.0, 1.0] UNKNOWN"}},
"be_number":3,
"exception":[],
"version":"2.3.1",
"commit_version":"fe5d830"}

**Comment by stdpain** [comment]
I reproduced the OOM problem.
env: 1FE 3BE  64G TPCH-1T 16c

1. ./bin/stop_fe.sh 
2. ./bin/start_fe.sh --daemon

by default: (DOP=0, fragment=1)
```
ERROR 1064 (HY000): Memory of process exceed limit. try consume:0 Used: 30332316040, Limit: 53711837060. Mem usage has exceed the limit of BE
```

**Comment by ZiheLiu** [comment]
I reproduced the timeout problem.
- env: 1 FE, 3 BE (each with 16GB RAMD and 16 cores), TPCH-1T.

After restarting FE or analyzing table, the first Q2 will be timeout. The reason is that table analysis information are fetched by FE after the first query running, and the plan of the first query is not well.

@dbjoa @kyuhomania Except the first query after restarting FE or analyzing table, is non-first Q2 still timeout or OOM?
And do you `analyze full table` again after each q2 running? (We only need analyze tables once, regardless of restarting FE)

**Comment by kyuhomania** [comment]
> Except the first query after restarting FE or analyzing table, is non-first Q2 still timeout or OOM?
When I tested on the 12 BE nodes environment(i3en.3xlarge X 12EA) with 10TB data, I saw the OOM. The OOM occurred with a random query. The query stopped with OOM can finish with the result next trial. I think it is a different reason from the first Q2 issue.

> And do you `analyze full table` again after each q2 running? (We only need analyze tables once, regardless of restarting FE)
We mean `the first q2 query` is the first trial just after `analyze full table` or `analyze table`. `Non-first q2 query` is all trials after `the first q2 query`.

**Comment by ZiheLiu** [comment]
> |      | (1,1) | (2,1) | (3,1) | (4,1) | (5,1) | (6,1) | (7,1) | (8,1) | (9,1) | (10,1)  |
> | ---- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ------- |
> | q2   | 2,456 | 1,381 | 1,604 | 1,247 | 1,209 | 1,230 | 1,231 | 1,218 | 734   | timeout |
>
> |      | (1,2) | (2,2) | (3,2) | (4,2) | (5,2)   |
> | ---- | ----- | ----- | ----- | ----- | ------- |
> | q2   | 1,869 | 1,344 | 1,517 | 1,156 | timeout |
>
> |      | (1,3) | (2,3) | (3,3) | (4,3)   |
> | ---- | ----- | ----- | ----- | ------- |
> | q2   | 1,224 | 1,082 | 996   | timeout |
>
> ...

@kyuhomania @dbjoa  As for the above test result, which of the following ways do you use to execute `analyze [full] table`?
- `analyze [full] table` only once at first. Then set `(pipeline_dop, parallel_fragment_exec_instance_num)` to each pair of values, and execute `Q2`.
- For each pair value of `(pipeline_dop, parallel_fragment_exec_instance_num)`, `analyze [full] table` again, and then execute `Q2`.

**Comment by kangkaisen** [comment]
The root cause is same with https://github.com/StarRocks/starrocks/issues/10141
