### ISSUE TITLE
CSV 看起来只是简单的按分隔符分割了

### ISSUE THREAD

**Issue by tbyes** [StarRocks/starrocks#10166]
### Steps to reproduce the behavior (Required)
1. 通过Golang的 csv.Writer 生成一份 csv 文件。数据包括逗号，双引号等等
2. 通过 Stream Load 的方式，导入CSV结构的数据
3. 报错
Error: Value count does not match column count. Expect 20, but got 42. Row: 2022-08-17 15:00:00,t1,,commodity-interfaces,10.246.228.47,queryAdminSpu,mysql,t1-dal.shizhuang-inc.com:3307,CommodityPropertyValueMapper.selectList,commodity_query,commodity_property_value,select,"SELECT id, source, source_id, property_type, value_type\n\t, property_id, name, value, level, end_value\n\t, custom_value, image_url, sort, definition_id, show_value\n\t, is_support_search, create_time, modify_time, language, translate_value\n\t, translate_name, translate_custom_value, special_model\nFROM commodity_property_value\nWHERE source_id IN (?)\n\tAND property_type <> ?\n\tAND source = ?",8,0,0,23690415,1564037,55521178,1660718388636

### Expected behavior (Required)
1. 按照 RFC 4180（https://www.ietf.org/rfc/rfc4180.txt）的规范正确解析数据

### Real behavior (Required)
1. 看起来只是按逗号做了简单分割

虽然CSV不像JSON有什么严格的规范标准，但是多数大项目还是会遵守RFC 4180（https://www.ietf.org/rfc/rfc4180.txt）来做好转义符的解析

虽然Starrocks也支持给定多个字符来做分隔符，但这样有几个问题：
1. 需要自己处理转义，因为不可能保证的正文一定不包含分隔符，只能说实际效果还行。不严谨。
2. 比如Golang，原生csv.Writer不支持指定多个字符来做为分割符，那还得自己实现一套，虽然也不难，但已经有标准库了对吧？
3. 如果能保持CSV格式上兼容一致的，同时也支持更高的能力（如多个字符），个人觉得这样的方式可能是比较好的产品方案

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.0.x

**Comment by trueeyu** [comment]
Very good proposal, let's study this problem，and then give you an answer.

**Comment by howrocks** [comment]
https://github.com/StarRocks/starrocks/pull/16536/files solved this issue.
