### ISSUE TITLE
alias cannot be resolved in projection

### ISSUE THREAD

**Issue by fzhedu** [StarRocks/starrocks#10242]
## Enhancement
```
mysql> select siteid +1 as a, a - pv as b from test.t;
ERROR 1064 (HY000): Column 'a' cannot be resolved
```

**Comment by imay** [comment]
@fzhedu 
when I try this query in postgresql, alias in select list is not used by other select item. it will be considered as a column reference.

**Comment by fzhedu** [comment]
some other databases may support use previous generated columns (alias) in later expressions, like Clickhouse.
