### ISSUE TITLE
[Docs] The return type of DATE_SUB is wrong

### ISSUE THREAD

**Issue by jaogoy** [StarRocks/starrocks#10258]
File: [/docs/sql-reference/sql-functions/date-time-functions/date_sub.md](https://docs.starrocks.com/en-us/latest/sql-reference/sql-functions/date-time-functions/date_sub)

1. The return type of `DATE_SUB` is `INT` in the docs. It's wrong.
2. The data type of the first parameter of `DATE_ADD` and `DATE_SUB` should support both DATE and DATETIME, not only DATETIME. 
> maybe we should check the detail.

**Comment by evelynzhaojie** [comment]
fixed in #3614
