### ISSUE TITLE
Use query sql instead of 'show proc "/xxxx"', in order to filter,aggregate or join

### ISSUE THREAD

**Issue by 5herhom** [StarRocks/starrocks#10296]
In clickhouse, there is a database named "system", user can use "select" to query metrics in ck. In order to query metrics by user define, can starrocks support the feature?

**Comment by jaogoy** [comment]
Did you mean the information_schema or other others?
What's the metrics you want to be implemented firstly?

**Comment by 5herhom** [comment]
> Did you mean the information_schema or other others? What's the metrics you want to be implemented firstly?

One situation is :
I want get the replica num or replica size of table per backend node with ip. I should query many sql :` show proc '/dbs/${dbId}'`、`show proc '/dbs/${dbId}/${tblId}/partitions'`、`show proc '/dbs/${dbId}/${tblId}/partitions/${partitionId}'`、` show proc '/dbs/${dbId}/${tblId}/partitions/${partitionId}/${indexId}'`、`show proc '/backends'` . And join or aggregate the result of them by code like java. If they can be joined by col, it can be released by sql without other language.
