### ISSUE TITLE
starrocks是不是有兼容性问题

### ISSUE THREAD

**Issue by mobile664042** [StarRocks/starrocks#10349]
### Steps to reproduce the behavior (Required)
1. 按照你们的官方文档进行安装be, 提示starrocks_be: 无法执行二进制文件
2. 我的系统是centos7, aarch64芯片(苹果电脑下的虚拟linux系统)。

### Expected behavior (Required)
能否正常安装starRocks？

### Real behavior (Required)
![image](https://user-images.githubusercontent.com/1433479/186126501-9762bee5-be3f-4c38-9e84-f87a539d5be8.png)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by chaoyli** [comment]
@mobile664042 The arrch64 should use the ARM version.

**Comment by mobile664042** [comment]
你这个arm version没找到，按文档https://docs.starrocks.com/zh-cn/latest/administration/Build_in_docker， 编译报错：

![image](https://user-images.githubusercontent.com/1433479/188871985-6a5eedc7-f125-4495-8822-71726226bc99.png)

![image](https://user-images.githubusercontent.com/1433479/188872069-0dd93b04-6c22-4f1b-849f-a191f30765de.png)

**Comment by mobile664042** [comment]
![image](https://user-images.githubusercontent.com/1433479/189042390-a6e9e8b2-ca66-4c1f-a315-518a41ce0ae7.png)
编译一直报错
