### ISSUE TITLE
编译BE节点出现如下报错，麻烦哪位大佬回答一下，谢谢

### ISSUE THREAD

**Issue by easymanlo** [StarRocks/starrocks#1041]
![image](https://user-images.githubusercontent.com/48037566/140269051-b92cca77-5a2b-46e2-b4e8-092c14de74de.png)

**Comment by chaoyli** [comment]
The boost library is missed. You can use the docker to compile the StarRocks.
https://github.com/StarRocks/docs/blob/main/development/Build_in_docker.md
