### ISSUE TITLE
[computer node K8S] build.sh execution error

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#10585]
### Steps to reproduce the behavior (Required)
1. 构建cn节点镜像
```
git clone https://github.com/StarRocks/starrocks
cd $your_path/starrocks/docker
./build.sh -b main
```
![A4OyNU7ZxA](https://user-images.githubusercontent.com/57162397/187373093-fd4f866e-d6e4-44e3-83c0-bfafdc77460d.jpg)

### Expected behavior (Required)
build success
### Real behavior (Required)
build failed
should comment these lines of the Dockerfile
![image](https://user-images.githubusercontent.com/57162397/187373462-e9d5ad66-18af-4bfc-8845-6fb1afeafcde.png)

**Comment by shileifu** [comment]
yes, you are right. the script should adapt to the version branch.
