### ISSUE TITLE
[computer node K8S]operator deployment failure

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#10608]
### Steps to reproduce the behavior (Required)
Deploying K8S successfully
1. git clone https://github.com/StarRocks/starrocks
2. cd $your_code_path/starrocks-kubernetes-operator
3. cd deploy
4. kubectl apply -f starrocks.com_computenodegroups.yaml
5. kubectl apply -f namespace.yaml
6. kubectl apply -f leader_election_role.yaml
7. kubectl apply -f role.yaml
8. kubectl apply -f role_binding.yaml
9. kubectl apply -f leader_election_role_binding.yaml
10. kubectl apply -f service_account.yaml
11. update the image in manager.yaml  to an Operator image
12. kubectl apply -f manager.yaml 
13. kubectl get pod -n starrocks

### Expected behavior (Required)
Running
### Real behavior (Required)
ErrImagePull
![image](https://user-images.githubusercontent.com/57162397/187440213-b687f893-2ef2-4478-9583-eab2af054f73.png)

**Comment by shileifu** [comment]
image pull timeout, cn-operrator image is not pushed to dockerhub.io. ignore the issue, please write to the operator depository. please close it.
