### ISSUE TITLE
[computer node K8S] Fe has no K8S deployed

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#10617]
### Steps to reproduce the behavior (Required)
Deploying K8S successfully

1. deploy cn cluster
2. cd examples/cn
3. kubectl apply -f fe-account.yaml
4. kubectl apply -f cn-config.yaml
5. kubectl apply -f cn.yaml

### Expected behavior (Required)
apply cn.yaml success
### Real behavior (Required)
![image](https://user-images.githubusercontent.com/57162397/187578131-9e5fc27a-af12-4845-98b6-ea7987ce42df.png)

operator should notice that FE is not deployed and prompt

**Comment by shileifu** [comment]
we will add the feature in the next version.
