### ISSUE TITLE
Provide a new function to select bitmap as a base64 string

### ISSUE THREAD

**Issue by JackeyLee007** [StarRocks/starrocks#10641]
## Feature request

**Is your feature request related to a problem? Please describe.**
We have a label system which uses bitmap heavily. The label system has some downstream systems which also require processing the bitmaps, but outside the starrocks. For example, the label system produces a few customer groups in the form of bitmaps, and the following downstream systems will judge if their customers are in the groups, or get an intersection between their own groups and the bitmaps.

We know that starrocks could explode the bitmaps into strings or multiple records, but it’s not feasible to our scenario. The watershed lies in the amount. The label system could produce 10k+ bitmaps every day, each of them could have millions of customers. It means there would be hundreds of billions of data each day. That is too much and not acceptable.

**Describe the solution you'd like**
One solution we figured out is that serializing the bitmaps to **base64** strings, exporting to hive, and also, we provide some hive/spark UDF to deserialize the base64 strings back to bitmaps again. Then the following downstream systems could use the bitmaps, although indirectly. 

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by jaogoy** [comment]
Do you mean that bitmap_to_string is not feasible to you ?
What's the reason? Is the performance not good enough, or is it complex to load those data into hive/spark? or ...

**Comment by JackeyLee007** [comment]
Just too much data. As I said, if I have 10k+ bitmaps, each contains millions element, the total data size is overwhelming. 
Even for one bitmap, the bitmap_to_string result is also too long to handle. So, we think the base64 of a bitmap is the most consize form for storage and processing outside starrocks.
