### ISSUE TITLE
[export] row count error when export to oss concurrently

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#10797]
### Steps to reproduce the behavior (Required)
http://39.101.206.100:8090/view/Daily/job/master_release/1263/testReport/junit/test_export_duppartbl_cols_to_oss/TestExportDupParTblColsToOSS/test_duppartbl_cols_export_task_without_broker/

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE b438184 |
+----------------------+
1 row in set (0.01 sec)
```

**Comment by xiaoyong-z** [comment]
https://github.com/StarRocks/StarRocksTest/compare/master...xiaoyong-z:fix-export-remove-same-repo-bug?expand=1

**Comment by xiaoyong-z** [comment]
Two concurrent running test case may delete duppartblcols_exp_oss_multiexp dir concurrently

**Comment by xiaoyong-z** [comment]
https://github.com/StarRocks/StarRocksTest/pull/1043
