### ISSUE TITLE
[computer node K8S] install controller_gen failed

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#10817]
### Steps to reproduce the behavior (Required)
gopath add file pkg,src,bin
export GO111MODULE=on
1. go env -w GOPROXY=[https://goproxy.cn,direct]
2. go install [sigs.k8s.io/controller-tools/cmd/controller-gen@v0.8.0]
![gVvJ0jipCe](https://user-images.githubusercontent.com/57162397/188259774-dffa8de6-c46a-48c6-ad2c-44caa11e909e.jpg)

### Expected behavior (Required)
install controller_gen success
### Real behavior (Required)
![jnqVoE4xZI](https://user-images.githubusercontent.com/57162397/188259715-2c7605ab-aa2a-4c0a-8938-7d56935f7772.jpg)

https://github.com/kubernetes-sigs/controller-tools/issues/643

**Comment by shileifu** [comment]
please write on operator depository.
