### ISSUE TITLE
create table failed when partition column case different from table column

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#10831]
### Steps to reproduce the behavior (Required)
```
CREATE TABLE t1 (
    A1 TINYINT,
    A2 DATE
) ENGINE=OLAP
DUPLICATE KEY(A1)
COMMENT "OLAP"
PARTITION BY RANGE (a2) (
START ("1970-01-01") END ("2022-09-01") EVERY (INTERVAL 1 year)
)
DISTRIBUTED BY HASH(A1) BUCKETS 20;
```

### Expected behavior (Required)
`create ok`
### Real behavior (Required)
`ERROR 1064 (HY000): Partition column[a2] does not exist in column list.`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.4-RELEASE 14a4718 |
+----------------------------+
```

**Comment by chaoyli** [comment]
The column is case sensitive.

**Comment by colorfulu** [comment]
> The column is case sensitive.

It's case insensitive in starrocks.
