### ISSUE TITLE
can i use StarRocks to do the ETL

### ISSUE THREAD

**Issue by VENSCC** [StarRocks/starrocks#10868]
just like the clickhouse:
  CREATE MATERIALIZED VIEW table_a TO table_b AS SELECT FROM table_c
In other words：
CREATE TRIGGER trigger_name ...

can i do this with Starrocks ?

**Comment by imay** [comment]
Yes we do support materialized view, this will be released in version 2.4

**Comment by VENSCC** [comment]
that would be nice
