### ISSUE TITLE
broker table , external hdfs table, can not select, what operations can be put on the broker table

### ISSUE THREAD

**Issue by sevenseablue** [StarRocks/starrocks#1087]
我建了一个外表， hdfs的外表， broker引擎， 不可以select， load， 请问能做什么操作。

`CREATE EXTERNAL TABLE tb_student_hdfs (
    name string,
    age INT,
    enter_school_date DATE
)
ENGINE=broker
PROPERTIES (
    "broker_name" = "broker1",
    "path" = "hdfs://127.0.0.1:9000/user/wdw/hive/warehouse/starrocks_test.db/tb_student_parquet",
    "format" = "parquet"
)
BROKER PROPERTIES (
    "timeout" = "3600"
)

mysql> select * from tb_student_hdfs limit 1;
ERROR 1064 (HY000): unsupported scan table type: BROKER
`

select can not be used, 
load data infile, 不可以load data in table

请问这个外表broker表可以做什么操作

**Comment by imay** [comment]
Broker Table is not supported any more. Instead you can create a hive external table. You can refer to documents about Hive External Table.

By the way, Broker table should be disabled when creating table. @Astralidea Can you handle it?

**Comment by Astralidea** [comment]
Yes. I'll see it.

**Comment by imay** [comment]
> Yes. I'll see it.

Thanks @Astralidea , I have assigned this issue to you.

**Comment by sevenseablue** [comment]
> Broker Table is not supported any more. Instead you can create a hive external table. You can refer to documents about Hive External Table.
> 
> By the way, Broker table should be disabled when creating table. @Astralidea Can you handle it?

谢谢， 原来是不再支持了， （doc里还有这个 https://docs.starrocks.com/zh-cn/main/using_starrocks/External_table）。
