### ISSUE TITLE
Increase naming length limit to 128 characters 

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks#10928]
## Increase naming length limit to 128 characters 
We have use cases that have table or column names greater than the 64 characters limit.
The [restriction](https://docs.starrocks.com/en-us/latest/reference/System_limit#system-limit) makes it's hard for us to adopt Starrocks in our production.

**Comment by imay** [comment]
https://github.com/StarRocks/starrocks/pull/10005 
Will this meet your requirements?

**Comment by dengliu** [comment]
> #10005 Will this meet your requirements?

Yes. Thanks for the quick reply. 
Look forward to this feature.
