### ISSUE TITLE
ERROR in hive parquet boolean column query

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#1095]
### Steps to reproduce the behavior (Required)
1. CREATE  HIVE TABLE  AND INIT DATA:
    create table hive_hdfs_parquet(
 col_tinyint tinyint comment "column tinyint"
,col_smallint smallint comment "column smallint"
,col_int int comment "column int"
,col_integer integer comment "column integer"
,col_bigint bigint comment "column bigint"
,col_float float comment "column float"
,col_double double comment "column double"
,col_double_precision double precision comment "column double precision"
,col_decimal decimal comment "column decimal"
--,col_numeric numeric comment "column numeric"
,col_timestamp timestamp comment "column timestamp"
,col_date date comment "column date"
,col_string string comment "column string"
,col_varchar varchar(100) comment "column varchar"
,col_binary binary comment "column binary"
,col_char char(100) comment "column char"
,col_boolean boolean comment "column boolean"
,col_array array<int> comment "column array"
)
clustered by(col_int) sorted by(col_int) into 32 buckets
row format delimited fields terminated by ','
stored as parquet;
insert into hive_hdfs_parquet select 1,1,1,1,1,1.001,10.1,110.1,1110.1,'2021-10-30 12:10:23','2021-10-30','hello world','hi hello','1110001010101011001001','nihao',true,array(1,10,100);
2. CREATE HIVE EXTERNAL TABLE:
create external resource hive_resource_1635837105500 PROPERTIES("type" = "hive","hive.metastore.uris" = "thrift://172.26.92.141:9083");
  create external table ex_hive_tbl2 (                 
 col_tinyint tinyint comment "column tinyint"                 ,
 col_smallint smallint comment "column smallint"                 ,
 col_int int comment "column int"                 ,
 col_integer integer comment "column integer"                 ,
 col_bigint bigint comment "column bigint"                 ,
 col_float float comment "column float"                 ,
 col_double double comment "column double"                 ,
 col_double_precision double comment "column double precision"                 ,
 col_decimal decimal comment "column decimal"                 ,
 col_timestamp datetime comment "column timestamp"                 ,
 col_date date comment "column date"                 ,
 col_string varchar(100) comment "column string"                 ,
 col_varchar varchar(100) comment "column varchar"                 ,
 col_binary varchar(100) comment "column binary"                 ,
 col_char char(100) comment "column char"                 ,
 col_boolean boolean comment "column boolean"             )         
   ENGINE=hive         
   properties (             
    "resource" = "hive_resource_1635837105500",             
    "table" = "hive_hdfs_parquet",             
    "database" = "hive_extbl_test_1636019895543");
3. QUERY HIVE EXTERNAL TABLE:
mysql> select * from ex_hive_tbl2;

### Expected behavior (Required)
query correct

### Real behavior (Required)
error:
mysql> select * from ex_hive_tbl2;
ERROR 1064 (HY000): parquet column reader: not supported convert from parquet `BOOLEAN` to `BOOL`

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 1.19.1

**Comment by caneGuy** [comment]
duplicated with #1200
