### ISSUE TITLE
broker load导入 load一直是0% 没有报错信息

### ISSUE THREAD

**Issue by LeoLiang666** [StarRocks/starrocks#11011]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

2.3.0

[图片]
DATA INFILE("hdfs://10.0.80.11:8020/user/hive/warehouse/dwd.db/evt_norm_acc_entr/*/*")
file_path:
文件路径，可以指定到一个文件，也可以用 * 通配符指定某个目录下的所有文件。通配符必须匹配到文件，而不能是目录。
因为文件路径/evt_norm_acc_entr/*/* 包含了目录。
运行没有返回报错信息，需要改进。

**Comment by LeoLiang666** [comment]
![image](https://user-images.githubusercontent.com/32983112/189077706-90cbe373-3339-4939-a048-c811d6806076.png)

**Comment by LeoLiang666** [comment]
![image](https://user-images.githubusercontent.com/32983112/189077932-6836be14-3f38-42e2-bc33-0b0dd1c16188.png)

**Comment by trueeyu** [comment]
The currently released version has only two states of 0% and 100%. Main already supports dynamic display of progress
