### ISSUE TITLE
【statistics】The HLL value of double data type changes

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#11012]
### Steps to reproduce the behavior (Required)
```
nosetests-3.4 -s --with-xunit --xunit-file=./result/test_manual_full_statistics_py_TestManualFullStatistics_test_statistics_broker_load.xml --verbose case/system_case/test_dql/test_statistics/test_manual_full_statistics.py:TestManualFullStatistics.test_statistics_broker_load --nologcapture
```

### Expected behavior (Required)
[64, 65187, 65683, 66126, 64907, 66342, 4, 8, 2, 257, 65596, 65394, 66220] 
### Real behavior (Required)
[64, 65187, 65683, 66150, 64907, 66342, 4, 8, 2, 257, 65596, 65394, 66220]
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 1beb02f |
+----------------------+
```

**Comment by xiaoyong-z** [comment]
https://github.com/StarRocks/StarRocksTest/pull/1073
https://github.com/StarRocks/StarRocksTest/pull/1071
https://github.com/StarRocks/StarRocksTest/pull/1059
https://github.com/StarRocks/StarRocksTest/pull/1051
