### ISSUE TITLE
Cant Filter Chinese

### ISSUE THREAD

**Issue by HelloSrauker** [StarRocks/starrocks#11047]
I konw a regexp [\u4e00-\u9fa5]  can match only Chinese
but in starrocks it not works.   who can i regexp only match Chiense?

I try  [^\x00-\xff] ,but it match not only Chinese.

### Steps to reproduce the behavior (Required)
1.
 `CREATE TABLE IF NOT EXISTS test02 (
    k1 VARCHAR(100),
    k2 VARCHAR(100)
)
DUPLICATE KEY(k1)
DISTRIBUTED BY HASH(k1) BUCKETS 1
PROPERTIES(
"replication_num" = "1"
);
`

2.
`insert into test02 (k1,k2) values("k1","hello");
insert into test02 (k1,k2) values("k2","123");
insert into test02 (k1,k2) values("k3","你好啊");
insert into test02 (k1,k2) values("k4","123你好啊Hello");
insert into test02 (k1,k2) values("k5","오늘 날씨 정말 좋아요");
insert into test02 (k1,k2) values("k6","开心");
insert into test02 (k1,k2) values("k7","    1233");
insert into test02 (k1,k2) values("k8","    wdsa1gtrew");
insert into test02 (k1,k2) values("k9","wdsa1gtrew");
insert into test02 (k1,k2) values("k10","helo world");`

3. 
`select * from test02 where regexp(k2,"[\u4e00-\u9fa5]");
select * from test02 where regexp(k2,"[\\u4e00-\\u9fa5]");`

### Expected behavior (Required)
Only Match Chinese
### Real behavior (Required)
Not Only Match Chinese & ERROR 1064 (HY000): Invalid regex expression: [\u4e00-\u9fa5]: '\u' at index 1 not supported in a character class.
### StarRocks version (Required)
starrocks v2.2.5

**Comment by jaogoy** [comment]
Will StarRocks use unicode to store Chinese chars in memory, or use UTF8 to store bytes of Chinese chars in memory?
