### ISSUE TITLE
Inconsistent log prompt

### ISSUE THREAD

**Issue by TTTTzz** [StarRocks/starrocks#11119]
### Steps to reproduce the behavior (Required)
CREATE TABLE `tablename` (
  `department_id` int(11) NOT NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(`department_id`)
DISTRIBUTED BY HASH(`department_id`) BUCKETS 1 
PROPERTIES (
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);

### Expected behavior (Required)
ERROR 1064 (HY000): Failed to find enough host in all backends. need: 3, Current alive backend is [10002]
### Real behavior (Required)
fe.log:
2022-09-13 13:58:19,564 WARN (statistics meta manager|23) [StatisticsMetaManager.createTable():169] Failed to create tableFailed to find enough host in all backends. need: 1, Current alive backend is [10002]，
### StarRocks version (Required)
use 2.3.0 on Docker

**Comment by NoSadness** [comment]
Add "replication_num" = "1" in PROPERTIES，you only have one BE node, the replication_num default is 3。

**Comment by TTTTzz** [comment]
I find the text description in fe.log is inconsistent with that in mysqlreport 
fe.log should be 'need:3'
