### ISSUE TITLE
Flink 1.15 + SR 2.3.1 + old connector: query where k0 = 1, error

### ISSUE THREAD

**Issue by huoyue-git** [StarRocks/starrocks#11129]
### Steps to reproduce the behavior (Required)
sr
1. CREATE TABLE '...'
 CREATE TABLE `duplicate_table_decimal_v3_with_null_flink` ( k0 int, v1 date, v2 datetime, v3 char(20), v4 varchar(20), v5 string, v6 boolean, v7 tinyint , v8 smallint , v9 int , v10 bigint , v11 largeint , v12 float , v13 double , v14 decimal(27,9) , v15 decimal32(9,5), v16 decimal64(18,10), v17 decimal128(38,18) ) ENGINE=OLAP DUPLICATE KEY(k0) COMMENT "OLAP" DISTRIBUTED BY HASH(k0) BUCKETS 3 PROPERTIES ( "replication_num" = "3" );
  insert into duplicate_table_decimal_v3_with_null_flink values  (1,'2021-12-31','2020-04-15 08:05:01','abcde','abcde','abcde','1','11','111','111','1111','11111','111.115','111.11111','11111.1111','1111.11111','111.11111','1111.1111111'),(2,'2022-01-01','2020-04-15 08:07:02','aaaaa','aaaaaa','aaaaaa','0','22','222','222','2222','22222','222.115','222.14159','22222.111','2222.11111','2222.1111','2222.1111'),(3,'2023-12-31','2020-04-15 08:09:03','bbbbb','bbbbbb','bbbbbb','1','33','333','333','3333','33333','333.115','333.14159','33333.111','3333.11111','3333.1112','3333.2222'),(4,'2024-01-01','2020-04-15 08:11:15','ccccc','cccccc','cccccc','0','44','444','444','4444','44444','444.115','444.14159','44444.111','4444.11111','4444.1123','4444.3333'),(5,'2024-01-01','2020-04-15 08:13:16','abcde','abcde','abcde','0','11','111','111','1111','11111','111.115','111.11111','11111.1111','1111.11111','111.11111','1111.1111111'),(6,'2021-12-31','2020-04-15 08:17:36','eeeee','eeeeee','eeeeee','0','66','666','666','6666','66666','666.115','666.14159','66666.111','6666.11111','6666.1111','6666.1111');
flink
2. CREATE TABLE AND SELECT '....'
CREATE TABLE `duplicate_table_select` (
k0 int, v1 date, v2 timestamp, v3 char(20), v4 varchar(20), v5 string, v6 boolean, v7 tinyint , v8 smallint , v9 int , v10 bigint , v11 string, v12 float , v13 double , v14 decimal(27,9) ,  v15 decimal(9,5), v16  decimal(18,10), v17  decimal(38,18)
        ) with (
           'connector' = 'starrocks',
           'scan-url' = 'xxx.xx.xx.xxx:xxxx',
           'jdbc-url' = 'jdbc:mysql://xxx.xx.xx.xxx:xxxx',
           'username' = 'root',
           'password' = '',
           'database-name' = 'test_hy',
           'table-name' = 'duplicate_table_decimal_v3_with_null_flink',
           'scan.connect.timeout-ms' = '60000'
        )

select * from duplicate_table_select where k0 = 1

### Expected behavior (Required)
The result is correct
### Real behavior (Required)
Flink SQL> select * from duplicate_table_select where k0 = 1;
[ERROR] Could not execute SQL statement. Reason:
java.lang.RuntimeException: Can not find StarRocks column data column name is -> [v11]

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| 2.3.1 fe5d830     |
+-------------------+
1 row in set (0.01 sec)

**Comment by banmoy** [comment]
It's the problem of connector, and has been fixed inhttps://github.com/StarRocks/starrocks-connector-for-apache-flink/pull/122
