### ISSUE TITLE
Support vertical compaction

### ISSUE THREAD

**Issue by wyb** [StarRocks/starrocks#1112]
## Feature request

**Is your feature request related to a problem? Please describe.**

The original compaction implementation is based on segment merge on the entire row. 
In the case of a large number of columns, it will be slower and take up a lot of memory (64k page for each column and segment)

**Describe the solution you'd like**

Introduce vertical compaction.
First merge the key columns, and record the row source mask.
Then merge the non-key columns according to the row source mask. Non-key columns can be divided into multiple column groups.

**Describe alternatives you've considered**

**Additional context**

**Comment by imay** [comment]
@wyb
