### ISSUE TITLE
Flink 1.15 + SR 2.3.1 + old connector:StarRocks type can not convert to flink type

### ISSUE THREAD

**Issue by huoyue-git** [StarRocks/starrocks#11139]
### Steps to reproduce the behavior (Required)
1. SR
CREATE TABLE `duplicate_table_decimal_v3_with_null_flink` ( k0 int, v1 date, v2 datetime, v3 char(20), v4 varchar(20), v5 string, v6 boolean, v7 tinyint , v8 smallint , v9 int , v10 bigint , v11 largeint , v12 float , v13 double , v14 decimal(27,9) , v15 decimal32(9,5), v16 decimal64(18,10), v17 decimal128(38,18) ) ENGINE=OLAP DUPLICATE KEY(k0) COMMENT
"OLAP" DISTRIBUTED BY HASH(k0) BUCKETS 3 PROPERTIES ( "replication_num" = "3" );
insert into duplicate_table_decimal_v3_with_null_flink values  (1,'2021-12-31','2021-12-31 23:59:59','beijingaergertte','haidiansdvgerwwge','tcafvergtrwhtwrht','1','100','100','100','100','100','-3.115','-3.14159','11.1111','12.11111','13.1111','14.11111'), (2,'2022-01-01','2022-01-01 00:00:01','beijing','haidian','asfarewgeragergre','0','110','200','200','200','200','4.115','4.14159','21.1111','22.11111','23.1111','24.1111')(2,'2023-01-01','2023-01-01 00:00:01','dsfewgr','rgergh','ergtrhrtw','0','120','200','300','300','300','5.115','5.14159','31.1111','32.11111','33.1111','34.1111') ;

2. FLINK
CREATE TABLE `duplicate_table_character_to_string` (
    k0 int, v3 string, v4 string, v5 string) with (
           'connector' = 'starrocks',
           'scan-url' = 'xxx.xx.xx.xxx:xxxx',
           'jdbc-url' = 'jdbc:mysql://xxx.xx.xx.xxx:xxxx',
           'username' = 'root',
           'password' = '',
           'database-name' = 'test_hy',
           'table-name' = 'duplicate_table_decimal_v3_with_null_flink'
        )

select k0, v3 from duplicate_table_character_to_string;

CREATE TABLE `duplicate_table_character_to_varchar` (
    k0 int, v3 varchar(20), v4 varchar(20), v5 varchar(20)) with (
           'connector' = 'starrocks',
           'scan-url' = 'xxx.xx.xx.xxx:xxxx',
           'jdbc-url' = 'jdbc:mysql://xxx.xx.xx.xxx:xxxx',
           'username' = 'root',
           'password' = '',
           'database-name' = 'test_hy',
           'table-name' = 'duplicate_table_decimal_v3_with_null_flink'
        );

select k0, v3 from duplicate_table_character_to_varchar;

CREATE TABLE `duplicate_table_character_to_char` (
    k0 int, v3 char(20), v4 char(20), v5 char(20)) with (
           'connector' = 'starrocks',
           'scan-url' = 'xxx.xx.xx.xxx:xxxx',
           'jdbc-url' = 'jdbc:mysql://xxx.xx.xx.xxx:xxxx',
           'username' = 'root',
           'password' = '',
           'database-name' = 'test_hy',
           'table-name' = 'duplicate_table_decimal_v3_with_null_flink'
        );

select k0, v4 from duplicate_table_character_to_char;
select k0, v5 from duplicate_table_character_to_char;

### Expected behavior (Required)
query sucess
### Real behavior (Required)
Flink SQL> select k0, v3 from duplicate_table_character_to_string;
[ERROR] Could not execute SQL statement. Reason:
java.lang.RuntimeException: StarRocks type can not convert to flink type, starrocks type is -> [CHAR] flink type is -> [VARCHAR]

Flink SQL> select k0, v3 from duplicate_table_character_to_varchar;
[ERROR] Could not execute SQL statement. Reason:
java.lang.RuntimeException: StarRocks type can not convert to flink type, starrocks type is -> [CHAR] flink type is -> [VARCHAR]

Flink SQL> select k0, v4 from duplicate_table_character_to_char;
[ERROR] Could not execute SQL statement. Reason:
java.lang.RuntimeException: StarRocks type can not convert to flink type, starrocks type is -> [VARCHAR] flink type is -> [CHAR]

Flink SQL> select k0, v5 from duplicate_table_character_to_char;
[ERROR] Could not execute SQL statement. Reason:
java.lang.RuntimeException: StarRocks type can not convert to flink type, starrocks type is -> [VARCHAR] flink type is -> [CHAR]
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| 2.3.1 https://github.com/StarRocks/starrocks/commit/fe5d8308fc3b9d0621b0e428d9515f8e40e62321 |
+-------------------+
1 row in set (0.01 sec)

**Comment by banmoy** [comment]
The exceptions are expected because table schemas  between StarRocks and Flink mismatch. According to the [doc](https://docs.starrocks.io/zh-cn/latest/loading/Flink-connector-starrocks#flink-%E4%B8%8E-starrocks-%E7%9A%84%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B%E6%98%A0%E5%B0%84%E5%85%B3%E7%B3%BB), Flink table `duplicate_table_character_to_string` should be created like 
`CREATE TABLE duplicate_table_character_to_char (
        k0 int, 
        v3 char(20),
        v4 varchar(20),
        v5 string
 ) with (
        xxxx
)`.
