### ISSUE TITLE
Fields are incomplete when queried using Navicat

### ISSUE THREAD

**Issue by along163** [StarRocks/starrocks#11144]
### Steps to reproduce the behavior (Required)
当字段超过一定长度时，查询结果显示出来的字段不完整，使用mysql客户端或者DataGrip时没有这个问题。

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by jaogoy** [comment]
So, is it a bug of Navicat?
Maybe you can check the Navicat's manual.
