### ISSUE TITLE
[statistics]set statistic_collect_concurrency failed

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#11226]
### Steps to reproduce the behavior (Required)
1. 
```
admin set frontend config ("statistic_collect_concurrency"="2");
admin show frontend config like "%statistic_collect_concurrency%";
```
2. 
```
cd /home/disk1/sr/qa_test_branch_02/fe
bin/stop_fe.sh --daemon
bin/start_fe.sh --daemon
```
3
```
admin show frontend config like "%statistic_collect_concurrency%";
```
![image](https://user-images.githubusercontent.com/57162397/190305159-8dcfb192-1bf8-4f13-bb56-de03a23006c8.png)

### Expected behavior (Required)
set statistic_collect_concurrency success
### Real behavior (Required)
set statistic_collect_concurrency failed
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.4-RELEASE 6825b2b |
+----------------------------+
```

**Comment by HangyuanLiu** [comment]
set statistic_collect_concurrency should restart fe
