### ISSUE TITLE
Can't use "((?!where).)*" to to prohibit SQL statements with where

### ISSUE THREAD

**Issue by Pslydhh** [StarRocks/starrocks#1138]
When use sqlblacklist, we Can't use "((?!where).)*" to to prohibit SQL statements with where.

https://github.com/StarRocks/starrocks/pull/1139

**Comment by fzhedu** [comment]
"((?!where).)*" is a wrong way to prohibit SQL statements with where, please directly use ( where ).

![4fc02b6c-58a7-4341-ad4f-a747022ad451](https://user-images.githubusercontent.com/6490813/211461076-177b75a0-5eab-448e-869a-500ff7b2a3c3.jpeg)
![20230110-121113](https://user-images.githubusercontent.com/6490813/211461215-b972f389-a339-44c8-af2f-bad647057a65.png)
