### ISSUE TITLE
Doc  Error：Replica Management 404

### ISSUE THREAD

**Issue by mklzl** [StarRocks/starrocks#114]
link : https://docs.dorisdb.com/zh-cn/master/administration/Rplica
 404 error

**Comment by Dshadowzh** [comment]
Thanks for reporting, we'll fix it ASAP.

**Comment by mklzl** [comment]
DDL 404 error :https://docs.dorisdb.com/zh-cn/master/reference/DDL

**Comment by wangsimo0** [comment]
please check this: https://docs.starrocks.com/zh-cn/main/administration/Replica
