### ISSUE TITLE
Support for more complex refresh syntax

### ISSUE THREAD

**Issue by Astralidea** [StarRocks/starrocks#11445]
We want to support partial partitions for flushing. Because the appearance may not be able to perceive the information such as the version of the partition, the high probability may be a full refresh.
At the same time, we'd better support a forced refresh statement to prevent some problems with smart refresh.

## Feature request

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by QingdongZeng3** [comment]
Please assign this issue to me
