### ISSUE TITLE
Task Framework supported execution progress.

### ISSUE THREAD

**Issue by Astralidea** [StarRocks/starrocks#11441]
Task currently supports CTAS and materialized views, which are essentially insert overwrite tasks, so we can best display the progress for long execution time, so that the user has a tone of execution completion time, so that the user experience is better.
## Feature request

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by smartlxh** [comment]
please assign this to me
