### ISSUE TITLE
Fe Core Class Missing: com.starrocks.analysis.SqlParser and com.starrocks.analysis.SqlScanner

### ISSUE THREAD

**Issue by mklzl** [StarRocks/starrocks#116]
com/starrocks/load/loadv2/BulkLoadJob.java need  these two files ，but I can't find it in the source code .
And another file not found  ----> com.starrocks.thrift.TUniqueId  thrift package not found

**Comment by kangkaisen** [comment]
You could refer to https://gist.github.com/kangkaisen/0253df91661c9b14471250e26934ef57

Intall protobuf and thrift firstly,

run 
```
cd ~/git/starrocks/gensrc/; make clean && make; cd ~/git/starrocks/fe/; mvn install -DskipTests;
```

**Comment by mklzl** [comment]
ok ，thank you.
