### ISSUE TITLE
Support automatic adjustment of the number of Compaction threads

### ISSUE THREAD

**Issue by trueeyu** [StarRocks/starrocks#1160]
## Enhancement

The current number of compaction threads is related to the number of disks. When there are too many disks, the number of compaction threads is too large and takes up a lot of memory. It should support adjusting the number of compaction threads according to the current compaction memory usage.

**Comment by jaogoy** [comment]
Shell we support a adjustable max thread num according to the memory usage or just give a fix max thread num.
