### ISSUE TITLE
Get error when trying to compile StarRocks

### ISSUE THREAD

**Issue by zhenxiao** [StarRocks/starrocks#11611]
## General Question

Hi,

I am getting the following error when trying to build StarRocks from github master, no code change:

home/zluo/code/starrocks/be/src/agent/agent_server.cpp:26:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
Any help are appreciated

**Comment by imay** [comment]
How about using our dev-env image to compile?
https://hub.docker.com/repository/docker/starrocks/dev-env

**Comment by zhenxiao** [comment]
could not use the image for my working environment.
Any potential reason? What's the minimum g++ version requirement?

**Comment by imay** [comment]
We use 10.3.0, you can try it.

**Comment by zhenxiao** [comment]
thank you, @imay 
use g++ 10.3.0 and gcc 10.3.0, still compilation error:
src/formats/CMakeFiles/Formats.dir/build.make:327: recipe for target 'src/formats/CMakeFiles/Formats.dir/parquet/column_chunk_reader.cpp.o' failed
make[2]: *** [src/formats/CMakeFiles/Formats.dir/parquet/column_chunk_reader.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/zluo/code/starrocks/be/../gensrc/build/gen_cpp/segment.pb.h:35,
                 from /home/zluo/code/starrocks/be/src/storage/types.h:32,
                 from /home/zluo/code/starrocks/be/src/column/field.h:12,
                 from /home/zluo/code/starrocks/be/src/column/schema.h:8,
                 from /home/zluo/code/starrocks/be/src/column/chunk.h:12,
                 from /home/zluo/code/starrocks/be/src/formats/parquet/file_reader.h:8,
                 from /home/zluo/code/starrocks/be/src/formats/parquet/file_reader.cpp:3:
/home/zluo/code/starrocks/be/../gensrc/build/gen_cpp/olap_common.pb.h:229:13: error: In the GNU C Library, "major" is defined
 by <sys/sysmacros.h>. For historical compatibility, it is
 currently defined by <sys/types.h> as well, but we plan to
 remove this soon. To use "major", include <sys/sysmacros.h>
 directly. If you did not intend to use a system-defined macro
 "major", you should undefine it after including <sys/types.h>. [-Werror]
  229 |   ::PROTOBUF_NAMESPACE_ID::int64 major() const;
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                                                                                                                                     
In file included from /home/zluo/code/starrocks/be/../gensrc/build/gen_cpp/segment.pb.h:35,
                 from /home/zluo/code/starrocks/be/src/storage/types.h:32,
                 from /home/zluo/code/starrocks/be/src/column/field.h:12,
                 from /home/zluo/code/starrocks/be/src/column/schema.h:8,
                 from /home/zluo/code/starrocks/be/src/column/chunk.h:12,
                 from /home/zluo/code/starrocks/be/src/formats/parquet/file_reader.h:8,
                 from /home/zluo/code/starrocks/be/src/formats/parquet/file_reader.cpp:3:
/home/zluo/code/starrocks/be/../gensrc/build/gen_cpp/olap_common.pb.h:242:13: error: In the GNU C Library, "minor" is defined
 by <sys/sysmacros.h>. For historical compatibility, it is
 currently defined by <sys/types.h> as well, but we plan to
 remove this soon. To use "minor", include <sys/sysmacros.h>
 directly. If you did not intend to use a system-defined macro
 "minor", you should undefine it after including <sys/types.h>. [-Werror]
  242 |   ::PROTOBUF_NAMESPACE_ID::int64 minor() const;
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                                                                                                                                     
/home/zluo/code/starrocks/be/../gensrc/build/gen_cpp/olap_common.pb.h:639:13: error: In the GNU C Library, "major" is defined
 by <sys/sysmacros.h>. For historical compatibility, it is
 currently defined by <sys/types.h> as well, but we plan to
 remove this soon. To use "major", include <sys/sysmacros.h>
 directly. If you did not intend to use a system-defined macro
 "major", you should undefine it after including <sys/types.h>. [-Werror]
  639 | inline ::PROTOBUF_NAMESPACE_ID::int64 EditVersionPB::major() const {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                                                                                                                
/home/zluo/code/starrocks/be/../gensrc/build/gen_cpp/olap_common.pb.h:667:13: error: In the GNU C Library, "minor" is defined
 by <sys/sysmacros.h>. For historical compatibility, it is
 currently defined by <sys/types.h> as well, but we plan to
 remove this soon. To use "minor", include <sys/sysmacros.h>
 directly. If you did not intend to use a system-defined macro
 "minor", you should undefine it after including <sys/types.h>. [-Werror]
  667 | inline ::PROTOBUF_NAMESPACE_ID::int64 EditVersionPB::minor() const {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     

Any hints?

**Comment by imay** [comment]
Could you provide more info?
You CPU type, OS version? And have you compiled the thirdparty-depency?

**Comment by zhenxiao** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

36 core:
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
stepping	: 4
microcode	: 0x2006c0a
cpu MHz		: 1524.423
cache size	: 25344 KB
physical id	: 0
siblings	: 36
core id		: 17
cpu cores	: 18
apicid		: 35
initial apicid	: 35
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips	: 5999.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

yes, compiling thirdparty
