### ISSUE TITLE
ALTER MATERIALIZED VIEW statement will change

### ISSUE THREAD

**Issue by wuliLSF** [StarRocks/starrocks#11632]
### Steps to reproduce the behavior (Required)
1.
CREATE TABLE goods(
    item_id1          INT,
    item_name         STRING,
    price             FLOAT
) DISTRIBUTED BY HASH(item_id1)
PROPERTIES (
 "replication_num" = "1"
);

CREATE TABLE order_list(
    order_id          INT,
    client_id         INT,
    item_id2          INT,
    order_date        DATE
) DISTRIBUTED BY HASH(order_id)
PROPERTIES (
 "replication_num" = "1"
);

2.
CREATE MATERIALIZED VIEW order_mv
DISTRIBUTED BY HASH(`order_id`) BUCKETS 12
REFRESH ASYNC START('2022-09-26 11:03:00') EVERY (interval 1 day)
AS SELECT
    order_list.order_id,
    sum(goods.price) as total
FROM order_list INNER JOIN goods ON goods.item_id1 = order_list.item_id2
GROUP BY order_id;

3.
![图片](https://user-images.githubusercontent.com/45867247/192188185-58dc4645-f59e-47bc-950b-aecf12370c6b.png)

4.
ALTER MATERIALIZED VIEW order_mv REFRESH ASYNC EVERY(INTERVAL 2 DAY);

5.
MySQL [test]> show create table order_mv;
CREATE MATERIALIZED VIEW order_mv
DISTRIBUTED BY HASH(order_id) BUCKETS 12
REFRESH ASYNC START('2022-09-26 11:09:23') EVERY (interval 2 day)
AS SELECT
order_list.order_id,
sum(goods.price) as total
FROM order_list INNER JOIN goods ON goods.item_id1 = order_list.item_id2
GROUP BY order_id;

### Expected behavior (Required)
MySQL [test]> show create table order_mv;
CREATE MATERIALIZED VIEW order_mv
DISTRIBUTED BY HASH(order_id) BUCKETS 12
REFRESH ASYNC START('2022-09-26 11:03:00') EVERY (interval 2 day)
AS SELECT
order_list.order_id,
sum(goods.price) as total
FROM order_list INNER JOIN goods ON goods.item_id1 = order_list.item_id2
GROUP BY order_id;

### Real behavior (Required)
MySQL [test]> show create table order_mv;
CREATE MATERIALIZED VIEW order_mv
DISTRIBUTED BY HASH(order_id) BUCKETS 12
REFRESH ASYNC START('2022-09-26 11:09:23') EVERY (interval 2 day)
AS SELECT
order_list.order_id,
sum(goods.price) as total
FROM order_list INNER JOIN goods ON goods.item_id1 = order_list.item_id2
GROUP BY order_id;

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 2.4

**Comment by Astralidea** [comment]
This is not actually a bug. By default, if START is not written, START is the current time. You can use ALTER MATERIALIZED VIEW order_mv REFRESH ASYNC START('2022-09-26 11:03:00') EVERY(INTERVAL 2 DAY); to specify the time, but this time cannot specify the past time.
There is also a problem here because this omitted syntax is easy to mislead users. You can see if you want to make ALTER not omit START.

**Comment by wuliLSF** [comment]
First, START is not specified in the syntax section of the document, and second, when START is not set, it should be the original value rather than the current time.

**Comment by Astralidea** [comment]
hi @wuliLSF 
For your case, do you hope that after the alter, that is, 1days->2days, this schedule is not expected to be executed again immediately, but I just modified it and calculated the next execution according to my previous time. time?

**Comment by blackstar-baba** [comment]
Some logics in PR https://github.com/StarRocks/starrocks/pull/12460:
1. If mv start time <= current time，task run once immediately
2. If mv start time > current time, task waiting to be scheduled

**Comment by wuliLSF** [comment]
> hi @wuliLSF For your case, do you hope that after the alter, that is, 1days->2days, this schedule is not expected to be executed again immediately, but I just modified it and calculated the next execution according to my previous time. time?
Yes, I think so.
