### ISSUE TITLE
really need hadoop 3.3 ?

### ISSUE THREAD

**Issue by darionyaphet** [StarRocks/starrocks#1168]
## General Question

when I try to run `download-thirdparty.sh`, I found it download the `hadoop` release package and it almost 400+ MB.

Do we really need it? Or just the hadoop client ? thanks

**Comment by imay** [comment]
StarRocks needs libhdfs to access data in HDFS.
Do you have any good idea?

**Comment by darionyaphet** [comment]
I guess it's for downloading HDFS's data?
