### ISSUE TITLE
add grammar for ALTER TABLE COMMENT 

### ISSUE THREAD

**Issue by winfys** [StarRocks/starrocks#11707]
## Feature request
Starrocks has the following problems:

1、 Cannot modify the comment of an existing table 
2、Modify column comment is too heavy 

I want to add the grammar of ALTER Table Comment:

  1、Change the tb1's comment to tb1_comment
          `ALTER TABLE tb1 MODIFY COMMENT "tb1_comment";`
  2、Change the tb1's col1 comment to col1_comment
           `ALTER TABLE tb1 MODIFY COLUMN col1 COMMENT "col1_comment";`

**Comment by chaoyli** [comment]
@winfys OK, we can add the feature ASAP.
