### ISSUE TITLE
Support RCFile for data load and query

### ISSUE THREAD

**Issue by chen9t** [StarRocks/starrocks#11769]
## Feature request
We have a lot of Hive tables with RCFile format, but StarRocks only supports CSV, ORC and PARQUET with spark/broker load. Our user can't load data with RCFile format.
Meanwhile, our user might query RCFile in the future. So it could be a good improvement from usability side if StarRocks can support RCFile for data load and query.

RCFile format scan can be supported from BE side, which will accomplish both of the requirements. But we need to support data load with a time limit. Maybe the task can be splitted into 2 sub-tasks:
1. Spark load support RCFile;
2. BE RCFile support natively.

Following are out thoughts:

### For data load 
@wangshisan

#### RcFileReader
RCFile SDK. Got the ability of reading from local/hdfs RCFile, and write to a output stream for upper layer;
#### RcFileChunkReader
Consume data stream from `RcFileReader`, and converter RCFile stream into StarRocks chunks, several type converters and predicate push down should be included.
#### RcFileScanner
Inherit from `FileScanner`, and implement the following methods:
```
    Status open() override;
    StatusOr<ChunkPtr> get_next() override;
    void close() override;
```
With this implementation, we can load RCFile data from broker load.
#### HdfsRcFileScanner
Inherit from `HdfsScanner`, and implement the following methods:
```
    Status do_open(RuntimeState* runtime_state) override;
    void do_close(RuntimeState* runtime_state) noexcept override;
    Status do_get_next(RuntimeState* runtime_state, ChunkPtr* chunk) override;
    Status do_init(RuntimeState* runtime_state, const HdfsScannerParams& scanner_params) override;
```
With this implementation, we can query external Hive table with RCFile format.

**Comment by wangshisan** [comment]
@wyb Is there any reference to guide user load data in RCFile format with broker load?

**Comment by wyb** [comment]
> @wyb Is there any reference to guide user load data in RCFile format with broker load?

Not supported in broker load.

**Comment by wangshisan** [comment]
> 

Sorry, it's Spark load, is there any refence?

**Comment by wangshisan** [comment]
> > @wyb Is there any reference to guide user load data in RCFile format with broker load?
> 
> Not supported in broker load.


Sorry, it's Spark load, is there any refernce?

**Comment by wyb** [comment]
> > > @wyb Is there any reference to guide user load data in RCFile format with broker load?
> > 
> > 
> > Not supported in broker load.
> 
> Sorry, it's Spark load, is there any refernce?

https://docs.starrocks.io/zh-cn/latest/loading/SparkLoad#%E5%88%9B%E5%BB%BA%E5%AF%BC%E5%85%A5%E4%BB%BB%E5%8A%A1
示例3

**Comment by wangshisan** [comment]
> > > > @wyb Is there any reference to guide user load data in RCFile format with broker load?
> > > 
> > > 
> > > Not supported in broker load.
> > 
> > 
> > Sorry, it's Spark load, is there any refernce?
> 
> https://docs.starrocks.io/zh-cn/latest/loading/SparkLoad#%E5%88%9B%E5%BB%BA%E5%AF%BC%E5%85%A5%E4%BB%BB%E5%8A%A1 示例3

Yeah, I see. Implemented in method _loadDataFromHiveTable_ . Great! Let me have a test.

**Comment by xiaoyong-z** [comment]
> https://docs.starrocks.io/zh-cn/latest/loading/SparkLoad#%E5%88%9B%E5%BB%BA%E5%AF%BC%E5%85%A5%E4%BB%BB%E5%8A%A1

https://github.com/StarRocks/starrocks/pull/622

**Comment by xiaoyong-z** [comment]
pr #622 add parquet/orc file load support for spark load

**Comment by wangshisan** [comment]
Tested, we can load RFFile format table by leverage Spark load.

**Comment by jaogoy** [comment]
@chen9t so, is it OK for you to load RCfile data using Spark Load
