### ISSUE TITLE
Data isolation cannot be achieved in multi-tenant scenarios

### ISSUE THREAD

**Issue by Aload** [StarRocks/starrocks#11788]
Hello, I found that multiple field partitions cannot be realized in the whole partition in the use, so I would like to ask how to achieve single-table and multi-tenant data isolation in the whole data layer when multi-tenant access is implemented. At present, I have checked the pipe network and found that the permission can only be table level, so in the case of multi-tenant, multiple tables or multiple libraries are needed. This does not work well in the entire data layer and can be very difficult to handle if there are small or large tenants.

**Comment by Dshadowzh** [comment]
You can create several view for each tenant, and grant different privilege to different users. 
We may implement row access policy for this requirement in the future.

**Comment by Aload** [comment]
> You can create several view for each tenant, and grant different privilege to different users. We may implement row access policy for this requirement in the future.

OK ，tks
