### ISSUE TITLE
query return empty set in where expression which is a not equal compare

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#1179]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `test_duplicate_table_with_null` (
  `k1` date NULL COMMENT "",
  `k2` datetime NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`k1`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`) BUCKETS 3 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "V2"
);
2. INSERT INTO test_duplicate_table_with_null values ("2020-06-23", "2020-06-23 00:00:02");
3. select * from test_duplicate_table_with_null;
+------------+---------------------+
| k1         | k2                  |
+------------+---------------------+
| 2020-06-23 | 2020-06-23 00:00:02 |
+------------+---------------------+
4. select * from test_duplicate_table_with_null where k2 != "2020-06-23 00:00:61";

### Expected behavior (Required)
+------------+---------------------+
| k1         | k2                  |
+------------+---------------------+
| 2020-06-23 | 2020-06-23 00:00:02 |
+------------+---------------------+
### Real behavior (Required)
mysql> select * from test_duplicate_table_with_null where k2 != "2020-06-23 00:00:61";
Empty set

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 1.19

**Comment by kangkaisen** [comment]
This issue isn't a bug. "2020-06-23 00:00:61" is an invalid datetime, in StarRocks, we will convert "2020-06-23 00:00:61" to null, all k2 data != null will get null, so the query result is empty
