### ISSUE TITLE
support ipv4 type

### ISSUE THREAD

**Issue by zddr** [StarRocks/starrocks#11842]
## Enhancement
I met a requirement before, similar to 
'select * from xxx where ip between 192.168.1.1 and 192.168.1.255'. 
Because starrocks does not support ip types at present, I have to select elasticsearch, so I want to add an ip type to help people with similar needs. 
Now I have finished some work, and can insert and query the range.
<img width="927" alt="image" src="https://user-images.githubusercontent.com/17589039/192991468-5594bf56-410b-4b25-8dc1-56ffafef2df3.png">

**Comment by Dshadowzh** [comment]
Thanks for contribution. You can create a PR for it.

**Comment by jaogoy** [comment]
@wangsimo0 may have a look?
