### ISSUE TITLE
Hope to add cdc function

### ISSUE THREAD

**Issue by Mile-Z** [StarRocks/starrocks#11853]
It is hoped that starrocks can add support for flink cdc and maxwell, or can provide related components for monitoring changes, so that data can be synchronized in real time. Currently, for the data in starrocks, there is a need to calculate and write to es, which is difficult to achieve in real time.

**Comment by chaoyli** [comment]
@Mile-Z Do you meaning the binlog integrated in the StarRocks to CDC ?
