### ISSUE TITLE
Datax mysqlsqlreader multi-node read, high availability configuration

### ISSUE THREAD

**Issue by Mile-Z** [StarRocks/starrocks#11878]
Datax's mysqlreader is always connected to a single node and can only be configured with one jdbc address. There may be fe hangs due to ha restart, causing the master to drift to other power-savings, and datax's mapping file address is unavailable, which is fatal in a production environment. It is recommended that starrocks officially develop a new reader plugin, which can configure multi-node parallel reading. Like flink-connector, it can also ensure high availability. After master drift, it will not affect script execution.

**Comment by chaoyli** [comment]
@Mile-Z good suggestions. Could you give a more detailed message about your case? You can connect me with WeChat(chaoy-li) or email(lichaoyong158@gmail.com)
