### ISSUE TITLE
The filter condition does not take effect when show alter table rollup

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#1187]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE  t1 (a int,b int)
        DISTRIBUTED BY HASH(a,b) 
        BUCKETS 3 
        PROPERTIES ("replication_num" = "1","storage_format" = "v2"
2. CREATE MATERIALIZED VIEW mv1 as select a,b from t1;
    CREATE MATERIALIZED VIEW mv2 as select a,b from t1;
3. show alter table rollup limit 1;

### Expected behavior (Required)
1 row result
### Real behavior (Required)
2 rows result
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
1.19.1

**Comment by chaoyli** [comment]
The limit is not used in `show alter table rollup` statement.

**Comment by jaogoy** [comment]
> 

So, What's the conclusion?
Produce error message when 'limit statement' is used or give a warning or ...
