### ISSUE TITLE
can‘t hit materialized view when use left join

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#1189]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `duplicate_table_with_null` (
    `k1`  date,
    `k2`  datetime,
    `k3`  char(20),
    `k4`  varchar(20),
    `k5`  boolean,
    `k6`  tinyint,
    `k7`  smallint,
    `k8`  int,
    `k9`  bigint,
    `k10` largeint,
    `k11` float,
    `k12` double,
    `k13` decimal(27,9)
) ENGINE=OLAP
DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`, `k2`, `k3`) BUCKETS 3
PROPERTIES (
    "replication_num" = "1",
    "storage_format" = "v2"
);
CREATE TABLE `duplicate_table_without_null` (
    `k1`  date NOT NULL,
    `k2`  datetime NOT NULL,
    `k3`  char(20) NOT NULL,
    `k4`  varchar(20) NOT NULL,
    `k5`  boolean NOT NULL,
    `k6`  tinyint NOT NULL,
    `k7`  smallint NOT NULL,
    `k8`  int NOT NULL,
    `k9`  bigint NOT NULL,
    `k10` largeint NOT NULL,
    `k11` float NOT NULL,
    `k12` double NOT NULL,
    `k13` decimal(27,9) NOT NULL
) ENGINE=OLAP
DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3
PROPERTIES (
    "replication_num" = "1",
    "storage_format" = "v2"
);

2. CREATE MATERIALIZED VIEW mv3 AS SELECT 
        k1, k2, k3 FROM duplicate_table_with_null;
3.explain SELECT * from duplicate_table_without_null t1 inner join 
                      (select k1,k2,k3 from duplicate_table_with_null) t2 on t1.k1=t2.k1

### Expected behavior (Required)
rollup: mv3
### Real behavior (Required)
rollup: duplicate_table_with_null
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
1.19.1

**Comment by imay** [comment]
@HangyuanLiu Could you please handle this issue?
