### ISSUE TITLE
[Enhancement] Add backpressure to write pipeline if apply cannot catch up

### ISSUE THREAD

**Issue by decster** [StarRocks/starrocks#11893]
## Enhancement
Currently, primary key table apply process(index update/delvec generation) is done asynchronously, if write throughput is too large, apply process may never catch up. This phenomenon started to occur after the persistence index was introduced, because persistence index is much slower than in-memory index. 
When in-memory index is used, it can catch up write throughput in most cases.
When persistence index is used, l1 index flush takes too much time, so apply takes lot of time, especially for large batch loads.
Possible ideas to address this issue:
* some form of sync apply
* add some backpressure mechanism to slow down write when apply cannot catch up
* optimize persistence index performance

**Comment by decster** [comment]
For now, a reasonable write throughput would be ~20-50K/core/second

**Comment by jaogoy** [comment]
Is it good to use a LOADING mode for good loading performance?
In LOADING mode, we can use much memory in loading thread, and other optimization.
