### ISSUE TITLE
Reason: there is a row couldn't find a partition. src line: []; 

### ISSUE THREAD

**Issue by liaooo** [StarRocks/starrocks#1192]
When i import data from HDFS into StarRocks. I encountered the following exception:
`Reason: there is a row couldn't find a partition. src line: []; `

However, there is only one record in HDFS, and each column has a value.

Does anyone have the same problem?

**Comment by imay** [comment]
This is because there is no partition for this record.
You can check you table partition's range and record's value.

**Comment by liaooo** [comment]
> This is because there is no partition for this record. You can check you table partition's range and record's value.

Thanks! I checked the table partition earlier, but checked the wrong table.

**Comment by imay** [comment]
OK, I will close this issue.
