### ISSUE TITLE
Error of the equals operator on array

### ISSUE THREAD

**Issue by catchex** [StarRocks/starrocks#11944]
### Steps to reproduce the behavior (Required)
```sql
select [1,2,3] = [1, 2, 3];
```

### Expected behavior (Required)
```
true/1
```

### Real behavior (Required)
```
SQL 错误 [1064] [42000]: binary type ARRAY<tinyint(4)> with type double is invalid.
```

### StarRocks version (Required)
 - Version: 2.3.2 dbc89ae

**Comment by catchex** [comment]
I want to group by a array column, and join sub query with array column as a condition, it is not a binary operation, only a compare operation, give me a help, please

**Comment by stdpain** [comment]
may be you can convert array to string and compare by string

**Comment by catchex** [comment]
@stdpain `has`, `has_any`, `has_all` functions in clickhouse. can they are applied on json array in starrocks

**Comment by jaogoy** [comment]
@wangsimo0 We can hava look some new array functions, such as array_contains_all(arr1, arr2), array_contains_any(arr1, arr2)

**Comment by catchex** [comment]
@jaogoy In StarRocks, json arrays and arrays can have the same functionality or behavior applied, their syntax or functions can be different, currently the contains_all or contains_any functions cannot be applied on json array, the functions of json type could not be help me.

**Comment by catchex** [comment]
thx, In StarRocks 2.4-rc, I can cast json as array<any>, and json array column can be compared on join conditions.
array_contains_all, array_contains_any functions can cover my features. This issue can be closed.
```sql
select cast(parse_json('[1, 2, 3]') AS ARRAY<INT>);
```
```sql
select parse_json('[1, 2, 3]') = parse_json('[1, 2, 3]')
```
