### ISSUE TITLE
How can I cast array to json array

### ISSUE THREAD

**Issue by catchex** [StarRocks/starrocks#11954]
StarRocks does not yet support binary operation on array type, and how can i cast a array column to json array type

**Comment by jaogoy** [comment]
There are no such functions recently.
Maybe we should provide such convertion in future, or provide a function cast(Array as STRING), then we can convert JSON array formatted String to JSON array.

**Comment by catchex** [comment]
This feature can be implemented by https://github.com/StarRocks/starrocks/issues/11944, thx
