### ISSUE TITLE
[materialized] hit materialized  view

### ISSUE THREAD

**Issue by joyceapp** [StarRocks/starrocks#11962]
### Steps to reproduce the behavior (Required)
step 1:
 create table if not exists duplicate_table ( c1  DATE, c2  DATETIME, c3  VARCHAR(100), c4  CHAR(100), c5  BOOLEAN, c6  TINYINT, c7  SMALLINT, c8  INT, c9  BIGINT, c10 LARGEINT, c11 FLOAT, c12 DOUBLE, c13 DECIMAL(27,9), c14 JSON ) duplicate key (c1, c2, c3, c4, c5, c6, c7, c8) DISTRIBUTED BY HASH(c1) BUCkETS 3 PROPERTIES ( "replication_num" = "1" );
step 2:
insert into duplicate_table values ('2020-07-02','2021-12-31 23:59:59','beijingaergertte','haidiansdvgerwwge','1','-9','-768','214743648','33720364775808','170141183469231731687303715884105728','-3.115','-3.14159','111111111111111111.111111111','{"a":"b"}'),
                ('2020-07-20','2021-12-31 23:59:59','beijing','haidiansdvgerwwge','0','34','68','-214483648','-922337206854775808','1701411469231731687303715884105728','-3.115','-3.141','111111111111111111.111111111','{"a":"b"}'),
                ('2020-08-20','2021-12-31 23:59:59','beiaergertte','haidiansdvgerwwge','1','8','32767','-214748648','-92233724775808','1701411869231731687303715884105728','-3.115','-3.141','111111111111111111.111111111','{"a":"b"}'),
                ('2020-08-23','2021-12-31 23:59:59','aergertte','haidiansdvgerwwge','0','0','-32768','-214748368','-92233720368508','1701411834604692317303715884105728','-3.115','-3.141','111111111111111111.111111111','{"a":"b"}')
    ;

step 3:
create materialized view mv_1 as select c7 from duplicate_table group by c7,c8;
step 4:
explain select c7 from duplicate_table where c7 between 0 and 100 group by c7,c8;

### StarRocks version (Required)
 MAIN-RELEASE 2ac5807

**Comment by ABingHuang** [comment]
the reason is that rewrite requires query's group by columns c7, c8 must be the output of mv, but c8 is not an output column of mv_1. so it can not be rewritten in current version materialized view.
it will be solved in multi-table materialized view.

**Comment by ABingHuang** [comment]
BTW, recording the related code here: MaterializedViewRule.checkGrouping
