### ISSUE TITLE
When creating a hive resource, the validity of the properties is not strict enough

### ISSUE THREAD

**Issue by gengjun-git** [StarRocks/starrocks#1196]
### Steps to reproduce the behavior (Required)
```shell
mysql> create external resource hive_resource PROPERTIES ("type" = "hive","type" = "hive","hive.metastore.uris" = "thrift://172.26.92.141:abc");
Query OK, 0 rows affected (0.00 sec)
```

### Expected behavior (Required)
Should check the property validity

### StarRocks version (Required)
- 1.19

**Comment by miomiocat** [comment]
i would like to solve this problem

**Comment by imay** [comment]
@miomiocat Thank you
I will assign this to you.

**Comment by miomiocat** [comment]
created a PR #1568 to resolve this issue. 

@gengjun-git PTAL
