### ISSUE TITLE
tiemstamp converting issue

### ISSUE THREAD

**Issue by Aload** [StarRocks/starrocks#12036]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Expected behavior (Required)
When I use Timestamp 13 bits converted to timestamp time type (eg:2022-10-10 18:37:04.112), write to build table using Datetime, write to null value.

` receive_time = Timestamp.valueOf(LocalDateTime
        .ofInstant(Instant.ofEpochMilli(tmpNode.get("receive_time").asLong), ZoneId.systemDefault()))`

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by jaogoy** [comment]
@Aload Can you give more information here?

**Comment by Aload** [comment]
When I use this timestamp (12 bits) to convert to a time type (2022-02-06xxxx :xx:xx.xxx), I store it in starrocket and write all to null
`val receive_time = Timestamp.valueOf(LocalDateTime .ofInstant(Instant.ofEpochMilli(tmpNode.get("receive_time").asLong), ZoneId.systemDefault()))`

**Comment by mofeiatwork** [comment]
Please describe the problem in SQL, cause StarRocks only accepts SQL as input.

**Comment by Aload** [comment]
> Please describe the problem in SQL, cause StarRocks only accepts SQL as input.

![bcb29aea6ded90a255dc6ae454fd389](https://user-images.githubusercontent.com/13082598/220001517-1c0b91e2-0e5e-46e2-a1b3-937a52b95e21.png)
