### ISSUE TITLE
V2.5 Release Plan

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#12064]
## New Features

1. Hudi connector：
   - Support Merge-On-Read(MOR) table

2. External table：
   - Support local cache to improve query speed on hot data
   - Support creating materialized view on external table, including materialized views that involves multiple internal and external tables
   - Hive external table support struct and map data format 

3. Support conditional update, you can specify a timestamp column to ensure that newer data is not overwritten by older data because of out-of-order data in the ingestion pipeline

4. Decouple sort key from primary key: support specifying non-primary key column as sort key

5. Support query cache at tablet level, which improve high concurrent query capability through caching of intermediate results

6. Support data ingestion from Apache Pulsar using routine load

7. Support configuring table's write quorum rule to meet the import requirements of different scenarios 

8. Support zstd, snappy, zlib compression algorithms in storage engine

9. Support query queue for concurrent queries workload

10. Support user-defined variables

11. Support lambda expression and several high-order SQL functions, including `array_map`, `array_filter`, `array_sum`, `array_sortby`

12. Support window function `qualify` 

13. Support using `uuid()`, `uuid_numeric()` as default values for columns

### Improvements

1. Improve metadata access speed for Iceberg and Hive Catalog

2. Improvements in multi-table materialized view
   - Support query rewrite for multi-table materialized views, related queries will automatically hit the view to speed up
   - Support creating new materialized views on top of single-table and multi-table materialized view 
   
3. Support automatically choosing the number of tablets at table creation

4. Improvements in data ingestion
   - Improve the overall ingest performance by 1X
   - Support broker load without deploying a broker when only one deployment of each hdfs and kerberos exist
   - Improve broker load performance for ingestion of large number of small ORC files
   - Support priority queue in broker load
   - Improve memory usage in ingestion to primary key table

5. Improve log readability  

6. Improve Pipeline engine performance 

7. Improve information_schema tables, including `tables` table, `columns` table, and add a new table `table_config`

8. Improvements in backup and restore
   - Support backup restore on database level 
   - Support performing backup and restore on primary key table
   - Improve the performance of backup to S3 and OSS 

9. Improvements in functions
   - Add parameters in `time_slice` to calculate the start and end points of the input time intervals 
   - Support strict incremental mode in `window_funnel`

**Comment by koqiui** [comment]
Won't support TIME type column?

**Comment by wangsimo0** [comment]
> In 2.5-rc document https://docs.starrocks.io/en-us/2.5/table_design/Materialized_view,
> 
> > Currently, only single-table materialized views are supported. No multi-table joins.
> 
> Where can I find the latest document about multi-table materialized view?

@choleraehyq Hi, please refer to this article https://docs.starrocks.io/en-us/2.5/using_starrocks/Materialized_view This is a bug in documentation, thank you a lot for pointing this out.

**Comment by choleraehyq** [comment]
> > In 2.5-rc document https://docs.starrocks.io/en-us/2.5/table_design/Materialized_view,
> > > Currently, only single-table materialized views are supported. No multi-table joins.
> > 
> > 
> > Where can I find the latest document about multi-table materialized view?
> 
> @choleraehyq Hi, please refer to this article https://docs.starrocks.io/en-us/2.5/using_starrocks/Materialized_view This is a bug in documentation, the page you provide should not exist anymore, thank you a lot for pointing this out.

@wangsimo0 Thank you. Is multi-table materialized view feature open-sourced?

**Comment by wangsimo0** [comment]
> > > In 2.5-rc document https://docs.starrocks.io/en-us/2.5/table_design/Materialized_view,
> > > > Currently, only single-table materialized views are supported. No multi-table joins.
> > > 
> > > 
> > > Where can I find the latest document about multi-table materialized view?
> > 
> > 
> > @choleraehyq Hi, please refer to this article https://docs.starrocks.io/en-us/2.5/using_starrocks/Materialized_view This is a bug in documentation, the page you provide should not exist anymore, thank you a lot for pointing this out.
> 
> @wangsimo0 Thank you. Is multi-table materialized view feature open-sourced?

@choleraehyq Sure, the code is already in the repo :) you can try it, the newest version is 2.5-rc03. Can be downloaded herehttps://www.starrocks.io/download/community
