### ISSUE TITLE
TPCDS query 05/66/84 with hive external table return error

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#1207]
### Steps to reproduce the behavior (Required)
1. testing environment:
qa_test_master
use hive_ex_tpcds_1t_orc;

2. perform tpcds query 84:
select  c_customer_id as customer_id
       , coalesce(c_last_name,'') || ', ' || coalesce(c_first_name,'') as customername
 from customer
     ,customer_address
     ,customer_demographics
     ,household_demographics
     ,income_band
     ,store_returns
 where ca_city	        =  'Edgewood'
   and c_current_addr_sk = ca_address_sk
   and ib_lower_bound   >=  38128
   and ib_upper_bound   <=  38128 + 50000
   and ib_income_band_sk = hd_income_band_sk
   and cd_demo_sk = c_current_cdemo_sk
   and hd_demo_sk = c_current_hdemo_sk
   and sr_cdemo_sk = cd_demo_sk
 order by c_customer_id
 limit 100;

### Expected behavior (Required)
Returns the correct result set

### Real behavior (Required)
ERROR 1064 (HY000): Operand '(coalesce(`default_cluster:test_hive_hdfs_orc_tpcds1t_1636615764417`.`customer`.`c_last_name`, '')) OR (', ')' part of predicate 'coalesce(`default_cluster:test_hive_hdfs_orc_tpcds1t_1636615764417`.`customer`.`c_last_name`, '')' should return type 'BOOLEAN' but returns type 'varchar(-1)'.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN bfe6488   |
+-------------------+
1 row in set (0.01 sec)

**Comment by kangkaisen** [comment]
Please set sqlMode =2 and try again.
