### ISSUE TITLE
BE crash when JDK version not equals to 1.8

### ISSUE THREAD

**Issue by 5herhom** [StarRocks/starrocks#12075]
version: 2.2.2   ; Fe num:3 ; Be num: 15

A sql used udf-ifNull() has been running normally. After I implement a java udf named nvl(), which has the same function with ifNull(), I replace the ifNull() with nvl() in the sql. Two backends shut down, everytime  I run the new sql with java udf. But when I change the udf back to ifNull(), the sql is normal again.

**Comment by 5herhom** [comment]
Addition. To be compatible with different type. It is implemented in all type parameters.
![image](https://user-images.githubusercontent.com/35916131/195286354-414d647a-6056-4146-8b39-00fee142b06b.png)

**Comment by stdpain** [comment]
can you provide a mini reprodce case?

**Comment by stdpain** [comment]
if be shutdown. you can provide the log in be.out

**Comment by 5herhom** [comment]
> if be shutdown. you can provide the log in be.out
There is no special log in be.
They are restart in 14:54:02 by auto script. The log before 14:54:02 is below.

One is:
![ecf0e58f75631454a79028801323903](https://user-images.githubusercontent.com/35916131/195291147-3a586597-2f9e-41e3-9146-ad56aecf09fa.jpg)

Another is:
![1341c8ba21bd5a6bc81f1cc7574907b](https://user-images.githubusercontent.com/35916131/195291187-a88e4b35-04d3-458d-8c51-fecc7f8785cd.jpg)

**Comment by stdpain** [comment]
there are no any output in be/log/be.out ?

**Comment by 5herhom** [comment]
> can you provide a mini reproduce case?

The nvl is implemented in nvl.zip.
[nvl.zip](https://github.com/StarRocks/starrocks/files/9763059/nvl.zip)
The create func sql is in create.sql in sql.zip.
The query cause be shut down is in query.sql in sql.zip.
[sql.zip](https://github.com/StarRocks/starrocks/files/9763093/sql.zip)

**Comment by 5herhom** [comment]
> there are no any output in be/log/be.out ?

Sorry, i give the log for be.Warning
be.out is below:
[be.out.log](https://github.com/StarRocks/starrocks/files/9763227/be.out.log)
[be (1).out.log](https://github.com/StarRocks/starrocks/files/9763228/be.1.out.log)

**Comment by stdpain** [comment]
> java/lang/NoClassDefFoundError: java/lang/Object
what's the version for your JDK ?

**Comment by 5herhom** [comment]
> > java/lang/NoClassDefFoundError: java/lang/Object
> 
> what's the version for your JDK ?
I saw be has default jvm lib in start_be.sh, so it didn't config $JAVA_HOME when start.
![image](https://user-images.githubusercontent.com/35916131/195301407-23debd01-5a4a-4b54-924b-8784c893cd45.png)

**Comment by 5herhom** [comment]
> > java/lang/NoClassDefFoundError: java/lang/Object
> 
> what's the version for your JDK ?

I found the problem it indeed because of the java config. When $JAVA_HOME="", the problem will accur.

**Comment by 5herhom** [comment]
> > > java/lang/NoClassDefFoundError: java/lang/Object
> > 
> > 
> > what's the version for your JDK ?
> 
> I found the problem it indeed because of the java config. When $JAVA_HOME="", the problem will accur.

The backends didn't config jre on purpose. 2 backends hasn't jre which cause the problem. 
I think it is not reasonable to shut down be, because of udf. It should be check before failure accurs.

**Comment by stdpain** [comment]
> I think it is not reasonable to shut down be, because of udf. It should be check before failure accurs.

**Comment by 5herhom** [comment]
> > I think it is not reasonable to shut down be, because of udf. It should be check before failure accurs.
> 
> you are right. we will improve this behavior

Thank you for your guidance.
