### ISSUE TITLE
Be crash when invalid json

### ISSUE THREAD

**Issue by goodqiang** [StarRocks/starrocks#12113]
### Steps to reproduce the behavior (Required)
1.  CREATE TABLE `test_a` (
  `dt` date NOT NULL COMMENT "",
  `logtime` datetime NOT NULL COMMENT "",
  `m2` varchar(128) NULL COMMENT "",
  `version` varchar(128) NULL COMMENT "",
  `action` varchar(64) NOT NULL COMMENT "",
  `src` varchar(32) NULL COMMENT "",
  `arr_type` varchar(128) NULL COMMENT "",
  `mid` varchar(64) NULL COMMENT "",
  `ip` varchar(64) NULL COMMENT "",
  `push_id` varchar(64) NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`dt`, `logtime`, `m2`, `version`, `action`, `src`, `arr_type`, `mid`, `ip`, `push_id`)
COMMENT "OLAP"
PARTITION BY RANGE(`dt`)
(PARTITION p20221005 VALUES [('2022-10-05'), ('2022-10-06')),
PARTITION p20221006 VALUES [('2022-10-06'), ('2022-10-07'))
DISTRIBUTED BY HASH(`dt`, `m2`) BUCKETS 10 
PROPERTIES (
"replication_num" = "1",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-30",
"dynamic_partition.end" = "3",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "16",
"dynamic_partition.replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
2.执行stream load
curl --location-trusted -u root:  'http://XXX/api/test/test_a/_stream_load' -X PUT -H "jsonpaths: [\"$.date\",\"$.t\",\"$.m2\",\"$.ver\",\"$.act\",\"$.src\",\"$.arr_type\",\"$.mid\",\"$.ip\",\"$.id\"]" -H "columns: dt,logtime,m2,version,action,src,arr_type,mid,ip,push_id" -H 'format: json' -H 'max_filter_ratio:0.2'  -T a.json
3.json数据如下
[{"t":"2022-10-11 18:08:01","cls"{"t":"2022-10-11 21:26:46","cls":"Tcvkn","ip":"10.173.229.95","m2":"0adae75c0f34ae64c4d1fca459e649e4616049422b7e","mid":"0b7a0d99c43c31259ec6a4200f99b646","ver":"3.1.0.2250","id":"142612","act":"request","trk":"","src":"onekeynet","arr_type":"", "date":"2022-10-11"}\n411.0.0.11413.1.0.2250
### Expected behavior (Required)
be服务正常，过滤该行数据
### Real behavior (Required)
be crash
![image](https://user-images.githubusercontent.com/86873587/195519673-20317d8a-f413-4abe-a090-adb8796df0f9.png)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.1.12

**Comment by goodqiang** [comment]
can I try？

**Comment by rickif** [comment]
@goodqiang Hi, could you plz check the steps to reproduce the problem? I've got a different result from yours.

**Comment by rickif** [comment]
![image](https://user-images.githubusercontent.com/16649269/196848753-bc25a50b-29cb-430f-acc1-51a3a7a4e4bd.png)

**Comment by goodqiang** [comment]
> @goodqiang Hi, could you plz check the steps to reproduce the problem? I've got a different result from yours.

Which version do you use？

**Comment by rickif** [comment]
> > @goodqiang Hi, could you plz check the steps to reproduce the problem? I've got a different result from yours.
> 
> Which version do you use？

2.1.12, as the version you provided.

**Comment by goodqiang** [comment]
> > > @goodqiang Hi, could you plz check the steps to reproduce the problem? I've got a different result from yours.
> > 
> > 
> > Which version do you use？
> 
> 2.1.12, as the version you provided.

> Our version adds this patch on the basis of 2.1.12, https://github.com/StarRocks/starrocks/pull/10838

**Comment by rickif** [comment]
Could please provide a repo of your codes so that I could dig into it?

**Comment by goodqiang** [comment]
> Could please provide a repo of your codes so that I could dig into it?
I changed these two files json_ scanner. cpp and json_ functions. cpp, I  send these two files to you

**Comment by rickif** [comment]
Sorry for the late response.
I think this PR may be better. PTAL. @goodqiang 
https://github.com/StarRocks/starrocks/pull/12850
