### ISSUE TITLE
starrocks 1.17.1  upgrade 1.19.1,  execute sql error 

### ISSUE THREAD

**Issue by yuanjianfaith** [StarRocks/starrocks#1218]
### Steps to reproduce the behavior (Required)
```
INSERT INTO dw_staff_daily_eu_statistics
        SELECT 	b.corp_id,b.staff_ext_id,
        STR_TO_DATE(DATE_FORMAT('2021-11-10 00:00:00','%Y-%m-%d'),'%Y-%m-%d') as date,
        b.eu_total_cnt,
        IFNULL(a.new_contact_cnt,0) as new_contact_cnt,
        IFNULL(c.outflow_cnt,0) as outflow_cnt, 
        IFNULL(a.new_contact_cnt,0)-IFNULL(c.outflow_cnt,0) 	as net_growth_cnt,
        NOW() as  created_at,
        NOW() as  updated_at
        from
        (
            SELECT  a.corp_id,a.staff_ext_id ,COUNT(DISTINCT a.external_user_ext_id, a.staff_ext_id) as eu_total_cnt  from  
            ods_staff_external_user_relation   as a
            join 
            ods_staff as b
            on 
            a.corp_id = b.corp_id
	    and
	    a.staff_ext_id = b.ext_id	
            WHERE   a.createtime <  '2021-11-11 00:00:00'  
            and
            (
            (a.deleted = 0)
            or
            (a.deleted = 1 and a.deleted_at > '2021-11-11 00:00:00' )
            )
            and 
            b.status = 1 and b.ia_authorized = 1
            GROUP BY a.corp_id,a.staff_ext_id 
        )
        as b
        LEFT JOIN
        (
            SELECT  corp_id,staff_ext_id ,COUNT(DISTINCT external_user_ext_id, staff_ext_id)   as  new_contact_cnt from  
            ods_staff_external_user_relation   WHERE createtime >  '2021-11-10 00:00:00'and  createtime <  '2021-11-11 00:00:00'
            and
            (
            (deleted = 0)
            or
            (deleted = 1 and deleted_at > '2021-11-11 00:00:00' )
            )
            GROUP BY corp_id,staff_ext_id  
        ) as a
        on  a.corp_id = b.corp_id and a.staff_ext_id = b.staff_ext_id
        left join
        (
            SELECT corp_id,staff_ext_id ,COUNT(DISTINCT external_user_ext_id, staff_ext_id)  as outflow_cnt 
            from ods_external_user_outflow_record  
            WHERE created_at >  '2021-11-10 00:00:00' and created_at <  '2021-11-11 00:00:00'
            GROUP BY corp_id,staff_ext_id 
        ) as c
        on  b.corp_id = c.corp_id and b.staff_ext_id = c.staff_ext_id
```

### Expected behavior (Required)

error info
1064 - expr's type is not same with slot's, Time: 0.084000s

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 1.19.1

**Comment by kangkaisen** [comment]
@yuanjianfaith Hi, could you give me the create table sql?

**Comment by yuanjianfaith** [comment]
> @yuanjianfaith Hi, could you give me the create table sql?

CREATE TABLE `dw_staff_daily_eu_statistics` (
  `corp_id` bigint(20) NOT NULL COMMENT "",
  `staff_ext_id` varchar(64) NOT NULL COMMENT "",
  `date` datetime NULL COMMENT "",
  `eu_total_cnt` int(11) NULL COMMENT "",
  `new_contact_cnt` int(11) NULL COMMENT "",
  `outflow_cnt` int(11) NULL COMMENT "",
  `net_growth_cnt` int(11) NULL COMMENT "",
  `created_at` datetime NULL COMMENT "",
  `updated_at` datetime NULL COMMENT ""
) ENGINE=OLAP 
UNIQUE KEY(`corp_id`, `staff_ext_id`, `date`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`corp_id`, `staff_ext_id`) BUCKETS 10 
PROPERTIES (
"replication_num" = "2",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);

CREATE TABLE `ods_staff_external_user_relation` (
  `id` bigint(20) NULL COMMENT "",
  `corp_id` bigint(20) NULL COMMENT "",
  `staff_ext_id` varchar(64) NULL COMMENT "",
  `createtime` datetime NULL COMMENT "",
  `external_user_ext_id` varchar(64) NULL COMMENT "",
  `remark` varchar(65533) NULL COMMENT "",
  `state` varchar(65533) NULL COMMENT "",
  `delete_by` varchar(64) NULL COMMENT "",
  `updated_at` datetime NULL COMMENT "",
  `deleted` tinyint(4) NULL COMMENT "",
  `deleted_at` datetime NULL COMMENT ""
) ENGINE=OLAP 
UNIQUE KEY(`id`, `corp_id`, `staff_ext_id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`corp_id`, `staff_ext_id`) BUCKETS 30 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);


CREATE TABLE `ods_staff` (
  `id` bigint(20) NULL COMMENT "",
  `corp_id` bigint(20) NULL COMMENT "",
  `ext_id` varchar(100) NULL COMMENT "",
  `status` int(11) NULL COMMENT "",
  `ia_authorized` tinyint(4) NULL COMMENT "",
  `mobile` bigint(20) NULL COMMENT ""
) ENGINE=OLAP 
UNIQUE KEY(`id`, `corp_id`, `ext_id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`corp_id`, `ext_id`) BUCKETS 8 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);


CREATE TABLE `ods_external_user_outflow_record` (
  `id` int(11) NOT NULL COMMENT "",
  `corp_id` bigint(20) NULL COMMENT "",
  `staff_ext_id` varchar(64) NOT NULL COMMENT "",
  `created_at` datetime NULL COMMENT "",
  `external_user_ext_id` varchar(64) NULL COMMENT "",
  `keep_time` int(11) NULL COMMENT "",
  `updated_at` datetime NULL COMMENT "",
  `add_time` datetime NULL COMMENT ""
) ENGINE=OLAP 
UNIQUE KEY(`id`, `corp_id`, `staff_ext_id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`corp_id`, `staff_ext_id`) BUCKETS 20 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);

**Comment by yuanjianfaith** [comment]
@kangkaisen

**Comment by kangkaisen** [comment]
> @kangkaisen

Thank you, we will handle this issue.
