### ISSUE TITLE
Supports streaming data writing

### ISSUE THREAD

**Issue by melin** [StarRocks/starrocks#12255]
StarRocks 自身不包含流失数据接入，需要依赖flink，能否自身包含流失数据接入，类似clickhouse，risingwave？更加方便用户使用，避免依赖太多中间件。
![image](https://user-images.githubusercontent.com/1145830/196321789-a850283b-fad8-444a-b1eb-07a83077ef17.png)

**Comment by imay** [comment]
Now StarRocks can ingest data form Kafka, Pulsa directly. What source do you want to load to starrocks directly?

**Comment by melin** [comment]
cdc data。
Implement CDC data synchronization on Debezium Server
https://debezium.io/documentation/reference/2.0/operations/debezium-server.html

imay ***@***.***> 于2022年10月18日周二 11:44写道：

**Comment by melin** [comment]
不依赖flink cdc同步mysql，oracle 等数据到starrocks

melin li ***@***.***> 于2022年10月18日周二 13:40写道：

**Comment by vkingnew** [comment]
redpandata support please
https://github.com/redpanda-data/redpanda
