### ISSUE TITLE
2.1.10 olap_scan_io 线程占用CPU过高,重启之后下去了，可是过会又上来了

### ISSUE THREAD

**Issue by zck573693104** [StarRocks/starrocks#12299]
![645e4967b8b82fb9b2ce48d3c548d83](https://user-images.githubusercontent.com/17779352/196618210-1691ba00-7ff1-46e9-8105-f944c59c8780.jpg)
![image](https://user-images.githubusercontent.com/17779352/196618300-8ec1d579-62d8-406b-9e56-57918affc6e6.png)

**Comment by mofeiatwork** [comment]
Please describe the workload and metric to help use diagnose the issue.
