### ISSUE TITLE
[Bug] BE crash in ExportSink::open_file_writer if broker not exists

### ISSUE THREAD

**Issue by decster** [StarRocks/starrocks#12301]
```
        FsBroker broker = Catalog.getCurrentCatalog().getBrokerMgr().getAnyBroker(brokerDesc.getName());
        if (broker != null) { // not set broker_addresses here
            tExportSink.addToBroker_addresses(new TNetworkAddress(broker.ip, broker.port));
        }


        } else {
            const TNetworkAddress& broker_addr = _t_export_sink.broker_addresses[0]; // NPE here
            BrokerFileSystem fs_broker(broker_addr, _t_export_sink.properties, timeout_ms);
            ASSIGN_OR_RETURN(output_file, fs_broker.new_writable_file(options, file_path));
            break;
        }

```

**Comment by Linkerist** [comment]
leave a question open(TODO):
if broker is not null, broker_addresses should not be null,
https://github.com/StarRocks/starrocks/blob/4cb16e95870e25ecb42fc8b547879b47d115cd0d/fe/fe-core/src/main/java/com/starrocks/planner/ExportSink.java#L88-L91
if broker is null, should throw an AnalysisException.
https://github.com/StarRocks/starrocks/blob/4cb16e95870e25ecb42fc8b547879b47d115cd0d/fe/fe-core/src/main/java/com/starrocks/analysis/ExportStmt.java#L202-L205
which mean if broker_addresses is null, there must be an AnalysisException throwed in fe, that is error should be reported in fe earlier, the fact is not so.

![img_v2_71cf8537-4c28-40d5-85b0-2347ab692d0g](https://user-images.githubusercontent.com/16617323/197785459-9dcce528-b7e2-4a60-aab0-552b41acbf77.jpg)
