### ISSUE TITLE
Speed up multi-column query by z-order indexing

### ISSUE THREAD

**Issue by tianhui5** [StarRocks/starrocks#1235]
## Feature request

**Is your feature request related to a problem? Please describe.**
  When there is more than one column, the file pruning by zonemap can be very useless.
  For example, if there is a table contains two columns: a, b. The range value of a and b is [0, 9]. There are 100 rows stored in this table. If we sort the data by a, b. and store them into 10 files evenly. The first file contains a with 0 all , b with range [0, 9]. The second file contains a with 1 all , b with range [0, 9]. And so on. Therefore, when query: select * from table where b = 2 without column a filter. The query can not use the min-max of column b.

**Describe the solution you'd like**
  I think the solution can only be mixing up multi-column indexs. I think the z-ordering index can be a proper solution. Because this kind of index has already been used by Impala and behaved well. 
  Although the z-order index is a compromise solution, I think it can fit in most situations and behave better than the orgin index.

**Describe alternatives you've considered**
The helbert index is likely to have better performance. Maybe I'll consider to develop it in next move.

**Additional context**
![image](https://user-images.githubusercontent.com/15223868/141428299-7c2da0d7-d347-4cd6-9df4-250269855f66.png)

**Comment by imay** [comment]
This feature will be very very useful for many StarRocks users.
I'm looking forward to this detailed design document.

**Comment by chaoyli** [comment]
Good Job. This feature will cover the rowset read/write logic and compaction logic.
For duplicate-key table, the related file is the following.
```
storage/vectorized/delta_writer.cpp
storage/vectorized/memtable.cpp
storage/vectorized/compaction.cpp
storage/short_key_index.cpp
storage/short_key_index.h
```

For primary-key table, the related file is the following.
```
storage/primary_key_encoder.h
storage/tablet_updates.cpp
storage/tablet_updates.h
```

**Comment by caneGuy** [comment]
@imay @chaoyli plz assign this to me thanks

**Comment by caneGuy** [comment]
we would like to implement this feature

**Comment by mxdzs0612** [comment]
Interested in this work too.

**Comment by caneGuy** [comment]
great @mxdzs0612
