### ISSUE TITLE
[Community + P1] 按照升级步骤， stop cluster while集群失败（由于pid文件被移除）

### ISSUE THREAD

**Issue by huangfeng1993** [StarRocks/starrocks#12364]
<img width="801" alt="image" src="https://user-images.githubusercontent.com/8199608/197127383-5f98cf82-f17c-41a6-88ae-03622482d47f.png">

完全按照上诉步骤，由于pid文件在bin目录，被mv到其他目录， 从而stop不掉集群。建议加个mv bin.bak/be.pid bin的操作。
fe升级类似。

**Comment by jaogoy** [comment]
@yongbingwang have a look

**Comment by evelynzhaojie** [comment]
please submit this issue in the docs.zh-cn repo，thanks, https://github.com/StarRocks/docs.zh-cn/issues
