### ISSUE TITLE
InPredicate of JSON is not supported

### ISSUE THREAD

**Issue by yangwei-parachute** [StarRocks/starrocks#12380]
when I use a json type column, happened :SQL 错误 [1064] [42000]: InPredicate of JSON is not supported
1. Example--json_data   is  a  json type  column

1)failed sql
select * from push_event_vip_traffic_json	
WHERE 	jSON_QUERY(json_data,'$.brandInner') in ('牛栏山Inner','振坤记Inner','牛栏山');

2)success sql
select * from push_event_vip_traffic_json e
    where
		(case when event_code = 'BROWSE' THEN JSON_QUERY(json_data ,'$.brandInner')
			  when event_code = 'CLICK' THEN brand end 
			  IN ('牛栏山Inner','振坤记Inner','牛栏山'));

 Could u help me ? how i fixed the failed sql run?

**Comment by imay** [comment]
Could you try to cast JSON to a string?

**Comment by yangwei-parachute** [comment]
My mistake, jSON_QUERY retrun a json type result. when i use 'case when then',it seems to auto cast to a string,  thanks very much.
