### ISSUE TITLE
Stream loading json error with Chinese content

### ISSUE THREAD

**Issue by catchex** [StarRocks/starrocks#12402]
When the data type is an array, if I encode it as ascii or plaintext, it will display garbled characters.
But cast it into Array<VARCHAR>, it works fine

```json
{..., "educations_majorNames": ["国际经济与贸易"], ...}
```

```json
{..., "educations_majorNames": ["\u5de5\u4e1a\u4e0e\u6c11\u7528\u5efa\u7b51"], ...}
```

<img width="688" alt="image" src="https://user-images.githubusercontent.com/875473/197469270-28f4018f-70dd-4592-9302-9d0da0a5e3ca.png">

**Comment by jaogoy** [comment]
StarRocks only supports UTF8.
@Pslydhh , can you check it why it works when casted.
