### ISSUE TITLE
Why integer should be enclosed by quotation when been inserted?

### ISSUE THREAD

**Issue by gaoge1116** [StarRocks/starrocks#1241]
![image](https://user-images.githubusercontent.com/32026308/141443428-7d8941bc-d3e7-4b2e-a86e-2990120d0ca6.png)
![image](https://user-images.githubusercontent.com/32026308/141443597-5599dd19-62d1-48e1-a2b8-e64362808024.png)
表结构：
![image](https://user-images.githubusercontent.com/32026308/141443813-9414788e-4060-42ab-9d3f-1580c693b902.png)

**Comment by Dshadowzh** [comment]
@gaoge1116  We can't reproduce the problem, could you offer StarRocks's version by `select current_version();` ?

**Comment by Linkerist** [comment]
> @gaoge1116 We can't reproduce the problem, could you offer StarRocks's version by `select current_version();` ?

Can you provide a specific SQL to reproduce this?

**Comment by gaoge1116** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "StarRocks/starrocks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月16日(星期二) 晚上9:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [StarRocks/starrocks] 主键表int类型字段插入数值需要引号，否则无法写入 (Issue #1241)





  
@gaoge1116 We can't reproduce the problem, could you offer StarRocks's version by select current_version(); ?
  
Can you provide a specific SQL to reproduce this?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
