### ISSUE TITLE
编译“starrocks/thirdparty/src/curl-7.79.0/lib” 发生的错误

### ISSUE THREAD

**Issue by mouse-dg** [StarRocks/starrocks#12414]
## General Question

通过使用 https://github.com/amosbird/ldb_toolchain_gen 这工具提供的编译环境编译STARROCKS
提示了如下错误：
--------------------------------------------------------------------------------------------------------------------
Making all in lib
make[1]: 进入目录“/opt/doris/starrocks/thirdparty/src/curl-7.79.0/lib”
make  all-am
make[2]: 进入目录“/opt/doris/starrocks/thirdparty/src/curl-7.79.0/lib”
  CC       libcurl_la-easy.lo
  CC       libcurl_la-hostip4.lo
  CC       libcurl_la-hostip6.lo
  CC       libcurl_la-hostsyn.lo
  CC       libcurl_la-hsts.lo
  CC       libcurl_la-http.lo
  CC       libcurl_la-http2.lo
cc1: warning: command-line option ‘-Wno-class-memaccess’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-Wno-class-memaccess’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-Wno-class-memaccess’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-Wno-class-memaccess’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-Wno-class-memaccess’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-Wno-class-memaccess’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-Wno-class-memaccess’ is valid for C++/ObjC++ but not for C
easy.c:103:23: error: ‘strdup’ undeclared here (not in a function); did you mean ‘strcmp’?
  103 | #define system_strdup strdup
      |                       ^~~~~~
easy.c:117:59: note: in expansion of macro ‘system_strdup’
  117 | curl_strdup_callback Curl_cstrdup = (curl_strdup_callback)system_strdup;
      |                                                           ^~~~~~~~~~~~~
hostip4.c: In function ‘Curl_ipv4_resolve_r’:
hostip4.c:245:39: error: invalid application of ‘sizeof’ to incomplete type ‘struct hostent_data’
  245 |      (sizeof(struct hostent) + sizeof(struct hostent_data))) {
      |                                       ^~~~~~
hostip4.c:252:11: warning: implicit declaration of function ‘gethostbyname_r’; did you mean ‘gethostbyname’? [-Wimplicit-function-declaration]
  252 |     res = gethostbyname_r(hostname,
      |           ^~~~~~~~~~~~~~~
      |           gethostbyname
make[2]: *** [libcurl_la-easy.lo] 错误 1
make[2]: *** 正在等待未完成的任务....
make[2]: *** [libcurl_la-hostip4.lo] 错误 1
make[2]: 离开目录“/opt/doris/starrocks/thirdparty/src/curl-7.79.0/lib”
make[1]: *** [all] 错误 2
make[1]: 离开目录“/opt/doris/starrocks/thirdparty/src/curl-7.79.0/lib”
make: *** [all-recursive] 错误 1
--------------------------------------------------------------------------------------------------------------------
有人遇到过这个错误么？

**Comment by chaoyli** [comment]
@mouse-dg 
<img width="728" alt="image" src="https://user-images.githubusercontent.com/44767902/198156876-edb3356d-bfdc-471f-ac78-855f14122e10.png">

**Comment by mouse-dg** [comment]
通过使用 https://github.com/amosbird/ldb_toolchain_gen 这工具提供的编译环境编译STARROCKS
 编译 curl两个参数
    export CPPFLAGS="-O3 -fno-omit-frame-pointer -fPIC -g -I${TP_INCLUDE_DIR}"
    export  CFLAGS="-O3 -fno-omit-frame-pointer -std=c99 -fPIC -g -D_POSIX_C_SOURCE=199309L -isystem 


/starrocks/thirdparty/build-thirdparty.sh
# curl
build_curl() {
    check_if_source_exist $CURL_SOURCE
    cd $TP_SOURCE_DIR/$CURL_SOURCE
    export CPPFLAGS="-O3 -fno-omit-frame-pointer -fPIC -g -I${TP_INCLUDE_DIR}"
    export  CFLAGS="-O3 -fno-omit-frame-pointer -std=c99 -fPIC -g -D_POSIX_C_SOURCE=199309L -isystem /opt/doris/starrocks/thirdparty/installed/include -Werror-implicit-function-declaration  -Wenum-conversion"
    #unset CPPFLAGS
    LDFLAGS="-L${TP_LIB_DIR}" LIBS="-lcrypto -lssl -ldl" \
    ./configure --prefix=$TP_INSTALL_DIR --disable-shared --enable-static  \
    --without-librtmp --with-ssl=${TP_INSTALL_DIR} --without-libidn2 --without-libgsasl --disable-ldap --enable-ipv6
    #echo "./configure --prefix=$TP_INSTALL_DIR --disable-shared --enable-static --without-librtmp --with-ssl=${TP_INSTALL_DIR} --without-libidn2 --without-libgsasl --disable-ldap --enable-ipv6"
    #echo "$LDFLAGS"
    #echo "$TP_SOURCE_DIR/$CURL_SOURCE"
    #echo "$CXXFLAGS"
    #echo "$CPPFLAGS"
    #echo "$CFLAGS"
    make -j$PARALLEL
    #make
    make install
    export CPPFLAGS="-O3 -fno-omit-frame-pointer -Wno-class-memaccess -fPIC -g -I${TP_INCLUDE_DIR}"
    export CFLAGS="-O3 -fno-omit-frame-pointer -std=c99 -fPIC -g -D_POSIX_C_SOURCE=199309L -I${TP_INCLUDE_DIR}"
}

**Comment by chaoyli** [comment]
@mouse-dg What's the operation system? Ubuntu or Centos. You can add me WeChat(chaoy-li) to discuss

**Comment by mouse-dg** [comment]
@chaoyli 
operation system: CENTOS7, 3.10.0-1160.49.1.el7.x86_64
CPU
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                24
On-line CPU(s) list:   0-23
Thread(s) per core:    2
Core(s) per socket:    6
座：                 2
NUMA 节点：         2
厂商 ID：           GenuineIntel
CPU 系列：          6
型号：              63
型号名称：        Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
步进：              2
CPU MHz：             1200.146
CPU max MHz:           3200.0000
CPU min MHz:           1200.0000
BogoMIPS：            4799.98
虚拟化：           VT-x
L1d 缓存：          32K
L1i 缓存：          32K
L2 缓存：           256K
L3 缓存：           15360K
NUMA 节点0 CPU：    0,2,4,6,8,10,12,14,16,18,20,22
NUMA 节点1 CPU：    1,3,5,7,9,11,13,15,17,19,21,23
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb invpcid_single ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat pln pts md_clear spec_ctrl intel_stibp flush_l1d

**Comment by chaoyli** [comment]
@mouse-dg You can download the latest upstream main branch. We have addressed many problems with the compiling. 
I have tested it in my operation system. It's OK. 

```
sh build-thirdparty.sh
```

```
Linux starrocks-sandbox04 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

processor	: 103
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
stepping	: 7
microcode	: 0x5002f01
cpu MHz		: 3200.073
cache size	: 36608 KB
physical id	: 1
siblings	: 52
core id		: 29
cpu cores	: 26
apicid		: 123
initial apicid	: 123
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_ppin intel_pt ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities
bogomips	: 5006.63
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```

**Comment by mouse-dg** [comment]
总结：
1、如果通过使用 https://github.com/amosbird/ldb_toolchain_gen 这工具提供的编译环境编译STARROCKS，而不是DOCKER环境编译，直接 sh build-thirdparty.sh 编译到 curl时候，就好出现上文所说错误。

# curl
build_curl() {
    check_if_source_exist $CURL_SOURCE
    cd $TP_SOURCE_DIR/$CURL_SOURCE

    LDFLAGS="-L${TP_LIB_DIR}" LIBS="-lssl -lcrypto -ldl" \
    ./configure --prefix=$TP_INSTALL_DIR --disable-shared --enable-static \
    --without-librtmp --with-ssl=${TP_INSTALL_DIR} --without-libidn2 --without-libgsasl --disable-ldap --enable-ipv6
    make -j$PARALLEL
    make install
}

2、摸索出来的编译参数是：

build_curl()  需要增加两行：
export CPPFLAGS="-O3 -fno-omit-frame-pointer -fPIC -g -I${TP_INCLUDE_DIR}"
export CFLAGS="-O3 -fno-omit-frame-pointer -std=c99 -fPIC -g -D_POSIX_C_SOURCE=199309L -isystem


vi build-thirdparty.sh

变更后：
build_curl() {
check_if_source_exist $CURL_SOURCE
cd $TP_SOURCE_DIR/$CURL_SOURCE
export CPPFLAGS="-O3 -fno-omit-frame-pointer -fPIC -g -I${TP_INCLUDE_DIR}"
export CFLAGS="-O3 -fno-omit-frame-pointer -std=c99 -fPIC -g -D_POSIX_C_SOURCE=199309L -isystem /opt/doris/starrocks/thirdparty/installed/include -Werror-implicit-function-declaration -Wenum-conversion"
#unset CPPFLAGS
LDFLAGS="-L${TP_LIB_DIR}" LIBS="-lcrypto -lssl -ldl"
./configure --prefix=$TP_INSTALL_DIR --disable-shared --enable-static
--without-librtmp --with-ssl=${TP_INSTALL_DIR} --without-libidn2 --without-libgsasl --disable-ldap --enable-ipv6
make -j$PARALLEL
#make
make install
export CPPFLAGS="-O3 -fno-omit-frame-pointer -Wno-class-memaccess -fPIC -g -I${TP_INCLUDE_DIR}"
export CFLAGS="-O3 -fno-omit-frame-pointer -std=c99 -fPIC -g -D_POSIX_C_SOURCE=199309L -I${TP_INCLUDE_DIR}"
}

这样的话，用 https://github.com/amosbird/ldb_toolchain_gen 这工具提供的编译环境编译STARROCKS 就可以通过。

**Comment by chaoyli** [comment]
@mouse-dg I build from scratch, not in Docker. It's OK. So the reason may be the header conflict with ${TP_INCLUDE_DIR} and system in your centos?
