### ISSUE TITLE
希望可以支持Kerberos认证的多个集群链接

### ISSUE THREAD

**Issue by yxh11028** [StarRocks/starrocks#12427]
问题描述：
当StarRocks2.3 在配置连接上带有Kerberos认证的CDH5集群（版本为hive1.1.0-cdh5）后，无法连接其他Hadoop集群的hive，版本为hive2.1.1-CDH6，报错提示：ERROR 1064 (JU000): get jove table from meta store failed: Unable to instantiate com.starrocks.external.hive.HiveMetaStoreThriftClient
将StarRocks对CDH5集群的Kerberos相关配置文件删除后，可以正常链接CDH6集群的hive（CDH6未配置Kerberos）
建议解决方案：
建议Starrocks可以对外部连接资源的认证配置管理粒度更加细化，以每个resource为单位进行管理，而不是全局控制；比如可以在CREATE RESOURCE的PROPERTIES的参数中去配置相关krb5.conf的路径以及其他accessKeyId内容，来控制这个RESOURCE的连接信息。

**Comment by Dshadowzh** [comment]
We are working on this feature, maybe in next two versions.
