### ISSUE TITLE
[Community-P1] apache spark 批量导入文档中 相关系统配置 处内容和参数配置内容不一致

### ISSUE THREAD

**Issue by Zhangruichao** [StarRocks/starrocks#12450]
截图：
![image](https://user-images.githubusercontent.com/12271586/197687753-364ef8c7-5156-41b3-a312-612efc7ed2b3.png)
问题描述：
如上图，配置项（enable-spark-load）并不能直接复制到fe.conf文件中，建议改成例如：enable_spark_load 这种格式，可直接使用。

**Comment by evelynzhaojie** [comment]
please submit this issue in the docs.zh-cn repo，https://github.com/StarRocks/docs.zh-cn/issues

**Comment by Zhangruichao** [comment]
> please submit this issue in the docs.zh-cn repo，https://github.com/StarRocks/docs.zh-cn/issues
ok
