### ISSUE TITLE
com.starrocks.analysis.SqlParser不是抽象的, 并且未覆盖java_cup.runtime.lr_parser中的抽象方法do_action

### ISSUE THREAD

**Issue by damobao** [StarRocks/starrocks#12521]
## General Question
Starrocks版本：2.3.3
我用Maven已经编译成功了，但在IDEA里通过StarRocksFE启动FE的时候，控制台却抛出这个异常：
com.starrocks.analysis.SqlParser不是抽象的, 并且未覆盖java_cup.runtime.lr_parser中的抽象方法do_action(int,java_cup.runtime.lr_parser,java.util.Stack,int)

这个类是根据语法文件自动生成的，这是一个bug吗？我改如何解决它？

**Comment by mofeiatwork** [comment]
We don't use the CUP parser anymore in the latest version, you don't need to worry about it.
