### ISSUE TITLE
starrocks don't support substring_index which mysql did

### ISSUE THREAD

**Issue by Panzervid** [StarRocks/starrocks#12532]
starrocks-client：
```
mysql> select substring_index(substring_index('name(10)', '(', -1), ')', `1)；`
ERROR 1064 (HY000): No matching function with signature: substring_index(varchar(-1), varchar(-1), tinyint(4)).
```

**Comment by wangsimo0** [comment]
https://dev.mysql.com/doc/refman/5.6/en/string-functions.html#function_substring-index
Returns the substring from string

**Comment by wangsimo0** [comment]
@selectbook hi could you please reply here so I can assign this to you?

**Comment by selectbook** [comment]
Could you please assign substring_index to me? thx!

**Comment by leiyang0324** [comment]
@kateshaowanjou Could you please assign substring_index to me? thx!

**Comment by kateshaowanjou** [comment]
Hi @leiyang0324, are you still working on this issue? Please let me know if you need any help. Thanks!
