### ISSUE TITLE
starrocks 2.3.3 broker load fail

### ISSUE THREAD

**Issue by Mile-Z** [StarRocks/starrocks#12558]
starrocks version is 2.3.3, hadoop version is 3.3.4, load data from hdfs broker into sr, appear
![Pasted Graphic](https://user-images.githubusercontent.com/91326053/198206183-cdc5ca52-9cdf-4132-8414-2a5b9adc4397.png)
Error, check the data is normal, the data source is snappy compression in orc format, the previous version is normal, there is a problem after upgrading to 2.3.3, there is no compressed data load in pure orc format, my previous test passed, this compressed The data was tested by an official partner of the community, and it failed. If the number of columns is too small, it will not only fail, but also cause be to hang directly (randomly). It seems that there is some problem with the snappy compression format support. I hope the official small My partner can test it, my table building statement, load template and data are put here, thank you.

CREATE TABLE `rdr_admission_SMH` (
  `USUBJID` varchar(255) NOT NULL COMMENT "患者标识",
  `VISITNUM` varchar(255) NOT NULL COMMENT "就诊标识",
  `ETLDTC` datetime REPLACE_IF_NOT_NULL NULL COMMENT "数据抽取时间",
  `ADINDTC` datetime REPLACE_IF_NOT_NULL NULL COMMENT "入院时间",
  `MHDGNAM_SOURCE` varchar(32) REPLACE_IF_NOT_NULL NULL COMMENT "疾病名称 l2 溯源原文位置",
  `MHDGNAM_SEARCH_CODE` int(11) REPLACE_IF_NOT_NULL NULL COMMENT "疾病名称 hvd搜索码",
  `MHDGNAM` varchar(1000) REPLACE_IF_NOT_NULL NULL COMMENT "疾病名称",
  `MHDGDUR` float REPLACE_IF_NOT_NULL NULL COMMENT "疾病持续时间",
  `MHSRNAM_SOURCE` varchar(32) REPLACE_IF_NOT_NULL NULL COMMENT "手术名称 l2 溯源原文位置",
  `MHSRNAM` varchar(1000) REPLACE_IF_NOT_NULL NULL COMMENT "手术名称",
  `MHSRDTC` date REPLACE_IF_NOT_NULL NULL COMMENT "手术日期",
  `MHHSNAM_SOURCE` varchar(32) REPLACE_IF_NOT_NULL NULL COMMENT "有害物质名称 l2 溯源原文位置",
  `MHHSNAM_SEARCH_CODE` int(11) REPLACE_IF_NOT_NULL NULL COMMENT "有害物质名称 hvd搜索码",
  `MHHSNAM` varchar(1000) REPLACE_IF_NOT_NULL NULL COMMENT "有害物质名称",
  `MHCTDUR` varchar(20) REPLACE_IF_NOT_NULL NULL COMMENT "接触时长",
  `MHCTYP_SEARCH_CODE` int(11) REPLACE_IF_NOT_NULL NULL COMMENT "接触类型 hvd搜索码",
  `MHCTYP` varchar(20) REPLACE_IF_NOT_NULL NULL COMMENT "接触类型"
) ENGINE=OLAP 
AGGREGATE KEY(`USUBJID`, `VISITNUM`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`USUBJID`) BUCKETS 128 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"

LOAD LABEL import_label_rdr_admission_SMH_2022_10_26_17_41_45_2de117c79cc54cf9a750d0b30ecffbb3_0
(
    DATA INFILE("file:/data/wr/rdr/part-00000-6446f876-b438-491a-a48c-06c05cf68b98-c000.snappy.orc")
    INTO TABLE rdr_admission_SMH
    (MHPDN, MHPDN_SOURCE, ADINDTC, MHHTNYN, MHHTNYN_SOURCE, MHPSHYN, MHPSHYN_SOURCE, MHHBYN, MHHBYN_SOURCE, VISITNUM, MHCHDYN, MHCHDYN_SOURCE, USUBJID, MHDGNAM, MHDGNAM_SOURCE, MHDGNAM_SEARCH_CODE, MHAYYN, MHAYYN_SOURCE, MHDMYN, MHDMYN_SOURCE, ETLDTC, MINSTID)
    SET
    (
        MHPDN=MHPDN,
        MHPDN_SOURCE=MHPDN_SOURCE,
        ADINDTC=ADINDTC,
        MHHTNYN=MHHTNYN,
        MHHTNYN_SOURCE=MHHTNYN_SOURCE,
        MHPSHYN=MHPSHYN,
        MHPSHYN_SOURCE=MHPSHYN_SOURCE,
        MHHBYN=MHHBYN,
        MHHBYN_SOURCE=MHHBYN_SOURCE,
        VISITNUM=VISITNUM,
        MHCHDYN=MHCHDYN,
        MHCHDYN_SOURCE=MHCHDYN_SOURCE,
        USUBJID=USUBJID,
        MHDGNAM=MHDGNAM,
        MHDGNAM_SOURCE=MHDGNAM_SOURCE,
        MHDGNAM_SEARCH_CODE=MHDGNAM_SEARCH_CODE,
        MHAYYN=MHAYYN,
        MHAYYN_SOURCE=MHAYYN_SOURCE,
        MHDMYN=MHDMYN,
        MHDMYN_SOURCE=MHDMYN_SOURCE,
        ETLDTC=ETLDTC,
        MINSTID=MINSTID
    )
)
WITH BROKER broker1
(
    "username"="root",
    "password"="root"
)
PROPERTIES
(
    "timeout"="3600",
    "max_filter_ratio"="0"
);
[part-00000-6446f876-b438-491a-a48c-06c05cf68b98-c000.snappy.orc.zip](https://github.com/StarRocks/starrocks/files/9876313/part-00000-6446f876-b438-491a-a48c-06c05cf68b98-c000.snappy.orc.zip)

**Comment by jaogoy** [comment]
@Mile-Z What's the metter, isn't it a problem?

**Comment by Mile-Z** [comment]
An issue has been reraised, the broker load statement is written incorrectly
