### ISSUE TITLE
Forgot to remove the skipped tablet from the queue of  trash sweep

### ISSUE THREAD

**Issue by sduzh** [StarRocks/starrocks#126]
Should rewrite the following line of code to `it = _shutdown_tablets.erase(it);`
https://github.com/StarRocks/starrocks/blob/97dc13906433c9af2f3bc9d8be7fc8eaaa4879c8/be/src/storage/tablet_manager.cpp#L1047

**Comment by luyou86** [comment]
could you assign it to me?
