### ISSUE TITLE
Add `RowCount` column in the output of `SHOW DATA FROM DBNAME;`

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks#12615]
## Feature request

**Is your feature request related to a problem? Please describe.**
Add `RowCount` column in the output of `SHOW DATA FROM DBNAME;`

**Describe the solution you'd like**
Would like to see the `RowCount` in the output of `SHOW DATA FROM DBNAME;`
We already have it in the output of `SHOW DATA FROM DBNAME.TABLENAME;`
![image](https://user-images.githubusercontent.com/5108773/198383241-39c9deed-d8b4-499f-b388-e1ebb283dd48.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by imay** [comment]
Good point. I think this will be helpful

**Comment by dengliu** [comment]
any update on this issue?
Thank you!
