### ISSUE TITLE
hive外部表偶发查询失败

### ISSUE THREAD

**Issue by Cherry-Puppy** [StarRocks/starrocks#12636]
<img width="601" alt="wecom-temp-60962-97b05ac2ab6157f28bba7db4220ae438" src="https://user-images.githubusercontent.com/46736583/198520385-412966ff-d04a-4904-ad45-a3a316e00421.png">
版本 2.2
问题应该是获取hdfs文件时，此时这个文件已经到回收站了。但是sr获取了第一个hdfs-client对象。此处为bug

**Comment by stephen-shelby** [comment]
you can use the "refresh external table <table_name> partition(xxx)". ref:https://docs.starrocks.io/zh-cn/latest/data_source/External_table#%E6%89%8B%E5%8A%A8%E6%9B%B4%E6%96%B0%E5%85%83%E6%95%B0%E6%8D%AE%E7%BC%93%E5%AD%98
