### ISSUE TITLE
创建物化视图导致整个FE启动不了

### ISSUE THREAD

**Issue by GitHub-19** [StarRocks/starrocks#12644]
### Steps to reproduce the behavior (Required)

CREATE MATERIALIZED VIEW IF NOT EXISTS data_center.k1_k2
AS
select p_brand,p_color from part
;
![image](https://user-images.githubusercontent.com/55374958/198541028-93481583-efdc-4d5f-b64d-6c3b25b6ab80.png)

### StarRocks version (Required)
 - 2.3

**Comment by Astralidea** [comment]
Hi @GitHub-19 
this already fixed in #10423
you could upgrade to the latest 2.3.3 to fix this issue.
