### ISSUE TITLE
split query two part

### ISSUE THREAD

**Issue by huangfeng1993** [StarRocks/starrocks#12689]
### Steps to reproduce the behavior (Required)
select 'sdf\'', 'sd;f';

### Expected b
![image](https://user-images.githubusercontent.com/8199608/198917705-e3910f86-bffa-42ca-a8d4-dfe28e268b3a.png)
ehavior (Required)

### Real behavior (Required)
![image](https://user-images.githubusercontent.com/8199608/198917734-20d207c1-4b3a-4e4c-97a9-25cc3d6b30c9.png)

rootcause: com.starrocks.sql.parser.SqlParser#splitSQL split query two part.
and in master branch, starrocks has used antlr parser to split statement.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.3

**Comment by huangfeng1993** [comment]
I am not sure there is new problem, if I just cherry pick 1ece18e. I tend to fix it in splitquery.

**Comment by mofeiatwork** [comment]
In MySQL syntax, the single-quote `'` could be escaped with `''`, so the right syntax should be `select 'sdf''', 'sd;f';`

I tested it on branch-2.4, it works as expected.

`
