### ISSUE TITLE
Installation configuration is too bloated

### ISSUE THREAD

**Issue by carr123** [StarRocks/starrocks#1269]
程序安装部署太臃肿。 建议用rust 或者golang 重构.

The program is too bloated for installation and deployment. Recommend refactoring with rust or golang.

**Comment by imay** [comment]
Firstly thanks for your feedback. Can you tell us in detail the points you want to improve?

**Comment by carr123** [comment]
@imay hi, you can offer docker image to make deployment simpler.
i only care about deployment, not compiling in docker.

**Comment by imay** [comment]
> @imay hi, you can offer docker image to make deployment simpler. i only care about deployment, not compiling in docker.

@carr123 
OK, I got you.
Now we have provide StarRocks binary to install. Could you tell me the scenarios where the binary can not satisfy you and you need a docker image?

**Comment by carr123** [comment]
@imay  hi, please help me.

i deploy starrocks on a clean ubuntu18.04 server.
when i run start_fe.sh, it says JAVA_HOME is not set. so i installed java and set JAVA_HOME env.

#apt install default-jre
#java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)

i successfully deployed FE 3-node  cluster.

then i deploy BE on the same server nodes. and fail to start BE node.
there is no data in storage directory, and no error info in log/be.out
the BE process is fail to start, i only see the FE process.

run the following can see the error info:
#bin/start_be.sh
bin/start_be.sh: line 114: 27318 Illegal instruction     (core dumped) ${STARROCKS_HOME}/lib/starrocks_be "$@" >> $LOG_DIR/be.out 2>&1 < /dev/null

**Comment by imay** [comment]
> @imay hi, please help me.
> 
> i deploy StarRocks-1.19.1 on a clean ubuntu18.04 server. when i run start_fe.sh, it says JAVA_HOME is not set. so i installed java and set JAVA_HOME env.
> 
> #apt install default-jre #java --version openjdk 11.0.11 2021-04-20 OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04) OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
> 
Better to use oracle JDK instead of OpenJDK.

> i successfully deployed FE 3-node cluster.
> 
> then i deploy BE on the same server nodes. and fail to start BE node. there is no data in storage directory, and no error info in log/be.out the BE process is fail to start, i only see the FE process.
> 
> run the following can see the error info: #bin/start_be.sh bin/start_be.sh: line 114: 27318 Illegal instruction (core dumped) ${STARROCKS_HOME}/lib/starrocks_be "$@" >> $LOG_DIR/be.out 2>&1 < /dev/null

It seems that your machine don't support `AVX2` instruction. You have two options:
1. you can build StarRocks yourself without AVX2
2. you can find another machine with AVX2 to install backend.

**Comment by carr123** [comment]
thanks for your help. 
i'm not familiar with java, however i can search how to install oracle JDK from the internet.
and i will try to build my own version without AVX2.
that would be a long journey to get a running cluster. that's what i mean at first.
