### ISSUE TITLE
Bothering open source community problems...

### ISSUE THREAD

**Issue by dragonly** [StarRocks/starrocks#127]
Hi StarRocks developers!
I'm an average developer from the open source community. Just before I am about to take a look at those issues and try to make some contribution, I found a very confusing article which seems to point out some very bad open source behaviors.
I just want to make things clear, and everyone believe in the spirit of open source happy. Thanks!

ref: https://mp.weixin.qq.com/s?__biz=Mzg5MDEyODc1OA==&mid=2247498504&idx=1&sn=d6723f7d4fb92f45060c2e7311c2633f

**Comment by JmPotato** [comment]
If the content of the article is true, it really hurts the feelings of all the friends in the open-source community 😅.

**Comment by jyz0309** [comment]
If the content of this article is true, LB(Bad)TM🤨🤨

**Comment by dragonly** [comment]
Here's another article, which stands on the side of Apache Doris.

ref: https://mp.weixin.qq.com/s/cOCGREc6KHPS0JpYdXekXw

**Comment by r-asou** [comment]
For Java program, everything comes from JDK. Can I think all Java program copy the JDK? Time will give us the truth of this thing.

**Comment by dragonly** [comment]
> For Java program, everything comes from JDK. Can I think all Java program copy the JDK?

Of course NOT! First of all, JDK is really a complicated name which may refer to a lot of entities. Let’s say we are talking about the well known Java SE Development Kit from Oracle. It’s a bunch of tools (like compilers) and SDK (libraries) with its own license. You can legally derive your own work with APIs from the SDK.

IMHO, it has NOTHING to do with what we are discussing in this issue.

**Comment by satanson** [comment]
@dragonly @JmPotato Welcome! My lovely friends from PingCAP, the code tells the truth.

**Comment by JmPotato** [comment]
> @dragonly @JmPotato Welcome! My lovely friends from PingCAP, the code tells the truth. Both StarRocks and TiFlash do well in OLAP domain, I hope both of us can make a great progress in OLAP.

Well, the problem here obviously is **not only** about the source code, it's more about the code of conduct your guys believe in, which is the **true code** that tells people the truth. If you keep hamster wheeling these words rather than facing these questions directly, I think that's what does the biggest disservice to the truth and the community.

**Comment by dragonly** [comment]
If I understand correctly, people in StarRocks team decided to ignore the question, and close this issue for energy saving.

I am sad about the result, and hope you do well in the right direction. Good luck.
