### ISSUE TITLE
limit by syntax

### ISSUE THREAD

**Issue by alanpaulkwan** [StarRocks/starrocks#12743]
Per Slack messages with Chun zhao, Clickhouse supports the following syntax:

`select * from db.table order by stockid, ret desc limit 5 by stockid`

This would return the top 5 ordered by ret descending for each group. If I have 4000 stocks it returns 4000x5 results (or less if a stock has fewer than 5)

The equivalent syntax in window function terms would be

`select stockid,field1,field2,field3...field_last from (select *,row_number() over (partition by permno order by ret desc) as rank from db.table ) where rank<=5`

**Comment by mofeiatwork** [comment]
Maybe we could add a new syntax for it, and translate it into the window function at the back.
