### ISSUE TITLE
[lambda]array_map function error in external table

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#12767]
### Steps to reproduce the behavior (Required)
1. CREATE catalog '...'
```
create external catalog hive_catalog_2e3394f0_59b2_11ed_91ff_00163e0e550b PROPERTIES("type" = "hive","hive.metastore.uris" = "thrift://ip:port");
```
2. SELECT  '....'
```
select col_int,array_map(x ->to_days(x),col_array_datetime) from hive_catalog_2e3394f0_59b2_11ed_91ff_00163e0e550b.hive_extbl_test_array.hive_hdfs_array_base order by col_int;
```
### Expected behavior (Required)
null
### Real behavior (Required)
3652425
![37b84a74-49df-4a39-a3ae-0842349bcd9f](https://user-images.githubusercontent.com/57162397/199180063-c6848ea8-2f3b-4ccb-8571-45374cbfd1e0.jpeg)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE c1b178c |
+----------------------+
```

**Comment by fzhedu** [comment]
cannot insert the invalid timestamp `:000-01-01 00:00:00`.

**Comment by zombee0** [comment]
the reason is that the data in hive may be illegal，I'll fix it.

**Comment by zombee0** [comment]
The original reason is hive deal datetime in a specific way, we are same with Trino, and don't need fix it
