### ISSUE TITLE
decimal(19,4) to decimal128(19,4)

### ISSUE THREAD

**Issue by yangwei-parachute** [StarRocks/starrocks#12775]
when i create table , it auto change decimal(19,4) to decimal128(19,4),how can i avoid this. we do not want to change
column type.

1)create table sql 
create table test1 (
 `id` bigint ,
 `money` decimal(19,4)
)
primary key (id)
distributed by hash(`id`) buckets 20

2)show create table test1
CREATE TABLE `test1` (
  `id` bigint(20) NOT NULL COMMENT "",
  `money` decimal128(19, 4) NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(`id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id`) BUCKETS 20 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);

**Comment by imay** [comment]
Yeah, Decimal128 is one representation of decimal. You can use it as you want to.
This is a problem showing users decimal128; we will fix it later.

**Comment by yangwei-parachute** [comment]
thanks, decimalV2 show decimal,its nice

**Comment by jaogoy** [comment]
@imay @yangwei-parachute  So, it this a problem? If it is, this issue should be opened to fix.
