### ISSUE TITLE
[bug] regexp_replace function do not return the expect result

### ISSUE THREAD

**Issue by pingchangxin1** [StarRocks/starrocks#12771]
### Steps to reproduce the behavior (Required)
 I use the SQL follow to replace the Chinese character，but it does not return the expect result
~~~
SELECT regexp_replace('123v 中文abc 中文', '[\u4e00-\u9fa5]', '*');
~~~

### Expected behavior (Required)
~~~
123v **abc **
~~~
### Real behavior (Required)
~~~
***v 中文*** 中文
~~~

it is strange why the  Chinese character not replaced and  character “v” reserved ?

### StarRocks version (Required)

StarRocks 2.1.11

**Comment by mofeiatwork** [comment]
I tested it on 2.4 version, it works as expected. Maybe some bugs in old version.
