### ISSUE TITLE
[lambda]array_map result error

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#12787]
### Steps to reproduce the behavior (Required)
1. 
```
select array_map(x ->truncate(x,1),[1]);
select array_map(x ->truncate(x,1),[1.1]);
select array_map(x ->truncate(x,1),[1,1.2]);
```
### Expected behavior (Required)
[1]
### Real behavior (Required)
ERROR 1064 (HY000): Decimal32/64/128 is not supported in current version
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE c1b178c |
+----------------------+
```

**Comment by fzhedu** [comment]
this is resulted from
https://github.com/StarRocks/starrocks/blob/2da6924fb42a56696608bb1283e013a630c2d7cb/fe/fe-core/src/main/java/com/starrocks/catalog/ArrayType.java#L21-L26

this is by design, not a bug.
