### ISSUE TITLE
Chinese Pinyin sorting is not supported

### ISSUE THREAD

**Issue by ShubaoYang** [StarRocks/starrocks#12785]
I want to sort data by a Chinese column, like Chinese name.

It will be sorted with ascii , not Chinese Pinyin。

There is an example for this:
![20221101-161853](https://user-images.githubusercontent.com/41741864/199191458-d88662a0-fed8-4607-8fdd-f94c282c6006.jpg)

**Comment by mofeiatwork** [comment]
That's a big feature called collation, we need to make a plan for it.
