### ISSUE TITLE
The message of Show Load is not friendly when the loading data does not match its filed type

### ISSUE THREAD

**Issue by jaogoy** [StarRocks/starrocks#12886]
### Steps to reproduce the behavior (Required)
The column type in the table is JSON, while the corresponding loading data is not a JSON-formatted string.
When a Routine Load job is created, the `Message` of Show Routine Load is:
`previous task aborted because of Unsupported CSV type JSON`
It's not friendly to user to know the real reason.

### Expected behavior (Required)
It could be `previous task aborted because of Unsupported data when loading into a JSON type column, the data is :'xxxx'`

### StarRocks version (Required)
2.3.0

**Comment by rickif** [comment]
Please assign this to me.
