### ISSUE TITLE
When Data Model is not Duplicate Key Model, error adding an array type column

### ISSUE THREAD

**Issue by Alittleben** [StarRocks/starrocks#12896]
### Steps to reproduce the behavior (Required)

CREATE TABLE `test_add_array_column`
(
    `col1` varchar(65533) not NULL COMMENT "",
    `col2` bigint(20)     NULL COMMENT "",
    `col3` varchar(65533) NULL COMMENT "",
    `arr1` ARRAY< varchar (65533)> NULL
) ENGINE = OLAP PRIMARY  KEY(`col1`)
DISTRIBUTED BY HASH(`col1`) BUCKETS 3
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);

INSERT INTO test_add_array_column
WITH LABEL insert_load_test_add_array_column
VALUES
    ("did_001", 12455566, "#en.wikipedia",  ["apple", "orange", "pear"]),
    ("did_002", 12455566, "#ca.wikipedia",  []);

ALTER TABLE test_add_array_column
    ADD COLUMN arr2 ARRAY< varchar (65533)>;

### Expected behavior (Required)
Expected add column is ok

### Real behavior (Required)
Error mesage: [42000][1064] ARRAY<VARCHAR(65533)>must be used in DUP_KEYS

### StarRocks version (Required)
2.3.0

**Comment by mofeiatwork** [comment]
Array type could only be used in duplicated table right now.
