### ISSUE TITLE
The segment file is incomplete due to machine restart

### ISSUE THREAD

**Issue by guanxianchun** [StarRocks/starrocks#12919]
### starrocks version
 starrocks version is 2.3

###starrocks cluster 
starrocks cluster is 3 BE and 3 FE, the tablet has three copies.

###The operation is as follows: 
1. 10:47:48 Starts to restart the machine
2. 11:22:05 compaction error detected. the warning message is follows: 

W1101 11:22:05.131323  4095 beta_rowset.cpp:83] Fail to open /opt/starrocks-2.3/starrocks/be/storage/data/10/11151/241126670/0200000003bd24360c424577199e9016576ed62af7092ba8_0.dat: Corruption: Bad segment file /opt/starrocks-2.3/starrocks/be/storage/data/10/11151/241126670/0200000003bd24360c424577199e9016576ed62af7092ba8_0.dat: magic number not match
W1101 11:22:05.131369  4095 compaction.cpp:68] fail to get segment iterator num. tablet=11151, err=Corruption: Bad segment file /opt/starrocks-2.3/starrocks/be/storage/data/10/11151/241126670/0200000003bd24360c424577199e9016576ed62af7092ba8_0.dat: magic number not match
W1101 11:22:05.131377  4095 storage_engine.cpp:685] failed to init vectorized base compaction. res=Corruption: Bad segment file /opt/starrocks-2.3/starrocks/be/storage/data/10/11151/241126670/0200000003bd24360c424577199e9016576ed62af7092ba8_0.dat: magic number not match

3. Checking File Information

$ ls -lh |grep 0200000003bd24360c424577199e9016576ed62af7092ba8_0
-rw-r--r-- 1 root root  16M Nov  1 10:48 0200000003bd24360c424577199e9016576ed62af7092ba8_0.dat

**Comment by trueeyu** [comment]
https://github.com/StarRocks/starrocks/pull/12343 the pr fix it
