### ISSUE TITLE
Compatibility of mysql with powerbi(COM_FIELD_LIST)

### ISSUE THREAD

**Issue by chaoyangqi** [StarRocks/starrocks#1295]
## Feature request

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chaoyangqi** [comment]
There are some protocol compatibility issues when interfacing the product with powerbi：COM_FIELD_LIST

**Comment by imay** [comment]
@chaoyangqi 
Thanks for your issue. Could you please provide more information to reproduce it?
