### ISSUE TITLE
WIDTH_BUCKET function support

### ISSUE THREAD

**Issue by vkingnew** [StarRocks/starrocks#12990]
>function **width_bucket** had supported by oracle and postgresql,hive,sparksql,impala,snowflake and databricks.
please add the same name function and have the same feature.
please refer to:
https://www.postgresql.org/docs/15/functions-math.html
https://docs.snowflake.com/en/sql-reference/functions/width_bucket.html

**Comment by wangsimo0** [comment]
@TBCCC hi could you please reply here so I can assign this to you~?

**Comment by wangsimo0** [comment]
## syntax
```
WIDTH_BUCKET( <expr> , <min_value> , <max_value> , <num_buckets> )
```

## arguments
1. expr: a numeric value
2. min/max value: numeric value, cannot be equal, while min value can be greater than max value.
3. num_buckets: must greater than 0. 

## notice
1. when the expression is less than lower bound of the bucket, return 0
2. when the expression is greater than upper bound of the bucket, return bucket_num+1

**Comment by vkingnew** [comment]
go on developing

**Comment by arsenalzp** [comment]
Hello,
Any progress here? I would like to try.
