### ISSUE TITLE
datax插件database属性不起作用

### ISSUE THREAD

**Issue by undeadwing** [StarRocks/starrocks#1300]
反馈一个datax插件的问题
datax如果jdbcurl配置成xxx.xxx.xxx.xxx:9030/testa,   那么执行presql时，只能执行testa数据库下的表，无法处理别的库的表，database属性配置无效，看源码database属性只在http写入时使用
我认为这里配置database应该在jdbc和http使用时都起作用，现在是有歧义的

**Comment by Dshadowzh** [comment]
JdbcUrl is used for preSQL/postSQL only, you can execute preSQL in one database and then load to another, I think it's not bad to separate two parameters.   @hffariel
