### ISSUE TITLE
function GROUP_CONCAT not full compatible for the mysql

### ISSUE THREAD

**Issue by vkingnew** [StarRocks/starrocks#13002]
current version:2.4.0
 https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html#function_group-concat
>GROUP_CONCAT([DISTINCT] expr [,expr ...]
             [ORDER BY {unsigned_integer | col_name | expr}
                 [ASC | DESC] [,col_name ...]]
             [SEPARATOR str_val])
1. can't support distinct
2. can't support  order by 
3. can't support separator
here is an example by starRocks, the data use the classic oracle's scott data example.
>mysql> select deptno,group_concat(ename) names,group_concat( job) jobs from emp group by deptno;
+--------+-------------------------------------------+--------------------------------------------------------+
| deptno | names                                     | jobs                                                   |
+--------+-------------------------------------------+--------------------------------------------------------+
|     10 | CLARK, KING, MILLER                       | MANAGER, PRESIDENT, CLERK                              |
|     20 | FORD, JONES, SCOTT, SMITH, ADAMS          | ANALYST, MANAGER, ANALYST, CLERK, CLERK                |
|     30 | JAMES, WARD, MARTIN, TURNER, BLAKE, ALLEN | CLERK, SALESMAN, SALESMAN, SALESMAN, MANAGER, SALESMAN |
+--------+-------------------------------------------+--------------------------------------------------------+
3 rows in set (0.04 sec)
![image](https://user-images.githubusercontent.com/5238970/200135037-972759dc-33a2-47b4-8c38-fe35e1a43993.png)

MySQL version:
>
mysql> select deptno,group_concat(ename) names,group_concat(distinct job order by job asc separator '-') jobs from emp group by deptno;
+--------+--------------------------------------+-------------------------+
| deptno | names                                | jobs                    |
+--------+--------------------------------------+-------------------------+
|     10 | CLARK,KING,MILLER                    | CLERK-MANAGER-PRESIDENT |
|     20 | SMITH,JONES,SCOTT,ADAMS,FORD         | ANALYST-CLERK-MANAGER   |
|     30 | ALLEN,WARD,MARTIN,BLAKE,TURNER,JAMES | CLERK-MANAGER-SALESMAN  |
+--------+--------------------------------------+-------------------------+
3 rows in set (0.00 sec)

![image](https://user-images.githubusercontent.com/5238970/200135010-5a0df96b-b134-403e-83bb-8fe415a7a68a.png)

**Comment by wangsimo0** [comment]
thanks that's very detailed. really appreciate it

**Comment by jiugem** [comment]
Very good question, hope StarRocks support soon
