### ISSUE TITLE
BE crash with insert into in ASAN build_type

### ISSUE THREAD

**Issue by wangruin** [StarRocks/starrocks#1301]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `test` (   `id_int` int(11) NOT NULL COMMENT "",   `id_double` double NOT NULL COMMENT "",   `id_varchar` varchar(100) NOT NULL COMMENT "",   `id_datetime` datetime NOT NULL COMMENT "",   `id_decimal` decimal128(20, 3) NOT NULL COMMENT "" ) ENGINE=OLAP DUPLICATE KEY(`id_int`) DISTRIBUTED BY HASH(`id_int`) BUCKETS 1;
2. insert som data;
3. insert into test select * from test;

### Expected behavior (Required)
Insert data successfully

### Real behavior (Required)
ERROR 1064 (HY000): Execute timeout

Here are the be.WARNING:
W1116 14:14:59.013700 20553 utils.cpp:90] Fail to get master client from cache. host= port=0 code=THRIFT_RPC_ERROR
W1116 14:14:59.015879 20553 task_worker_pool.cpp:1147] Fail to report task to :0, err=-1
W1116 14:16:48.918080 22481 utils.cpp:90] Fail to get master client from cache. host= port=0 code=THRIFT_RPC_ERROR
W1116 14:16:48.925887 22481 task_worker_pool.cpp:1147] Fail to report task to :0, err=-1
F1116 14:17:18.926105 22291 segment_iterator.cpp:536] Check failed: false column was not dict encode, but segment_iterator has a global dict map

Here are the be.out:
*** Check failure stack trace: ***
    @          0x87c751d  google::LogMessage::Fail()
    @          0x87c97f9  google::LogMessage::SendToLog()
    @          0x87c7099  google::LogMessage::Flush()
    @          0x87c9df9  google::LogMessageFatal::~LogMessageFatal()
    @          0x7a2c07b  starrocks::vectorized::SegmentIterator::_init_column_iterators()
    @          0x7a2a537  starrocks::vectorized::SegmentIterator::_init()
    @          0x7a30ce2  starrocks::vectorized::SegmentIterator::do_get_next()
    @          0x40c8e88  starrocks::vectorized::ChunkIterator::get_next()
    @          0x489099d  starrocks::SegmentIteratorWrapper::do_get_next()
    @          0x40c8e88  starrocks::vectorized::ChunkIterator::get_next()
    @          0x432fb16  starrocks::vectorized::TimedChunkIterator::do_get_next()
    @          0x40c8e88  starrocks::vectorized::ChunkIterator::get_next()
    @          0x4326fdd  starrocks::vectorized::TabletReader::do_get_next()
    @          0x40c8e88  starrocks::vectorized::ChunkIterator::get_next()
    @          0x62f59ba  starrocks::vectorized::TabletScanner::get_chunk()
    @          0x5a03775  starrocks::vectorized::OlapScanNode::_scanner_thread()
    @          0x5a097d4  _ZZN9starrocks10vectorized12OlapScanNode15_submit_scannerEPNS0_13TabletScannerEbENKUlvE_clEv
    @          0x5a0d56a  _ZSt13__invoke_implIvRZN9starrocks10vectorized12OlapScanNode15_submit_scannerEPNS1_13TabletScannerEbEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @          0x5a0d40b  _ZSt10__invoke_rIvRZN9starrocks10vectorized12OlapScanNode15_submit_scannerEPNS1_13TabletScannerEbEUlvE_JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EES8_E4typeEOS9_DpOSA_
    @          0x5a0d273  _ZNSt17_Function_handlerIFvvEZN9starrocks10vectorized12OlapScanNode15_submit_scannerEPNS2_13TabletScannerEbEUlvE_E9_M_invokeERKSt9_Any_data
    @          0x3acd1fa  std::function<>::operator()()
    @          0x48f4650  starrocks::PriorityThreadPool::work_thread()
    @          0x491d55d  std::__invoke_impl<>()
    @          0x491d39d  std::__invoke<>()
    @          0x491d347  _ZNKSt12_Mem_fn_baseIMN9starrocks18PriorityThreadPoolEFviELb1EEclIJRPS1_RiEEEDTcl8__invokedtdefpT6_M_pmfspcl7forwardIT_Efp_EEEDpOS9_
    @          0x491d2f8  std::__invoke_impl<>()
    @          0x491d24f  _ZSt10__invoke_rIvRSt7_Mem_fnIMN9starrocks18PriorityThreadPoolEFviEEJRPS2_RiEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESB_E4typeEOSC_DpOSD_
    @          0x491c028  _ZNSt12_Bind_resultIvFSt7_Mem_fnIMN9starrocks18PriorityThreadPoolEFviEEPS2_iEE6__callIvJEJLm0ELm1EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @          0x4919372  std::_Bind_result<>::operator()<>()
    @          0x4917ffa  boost::detail::thread_data<>::run()
    @          0x8775757  thread_proxy
    @     0x7f27bb315e65  start_thread

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 branch-2.0 `be897f6` ASAN

**Comment by stdpain** [comment]
It may be caused by low cardinality optimize, please assign to me

**Comment by wangruin** [comment]
@stdpain ok

**Comment by stdpain** [comment]
It seems a FE problems @kangkaisen
