### ISSUE TITLE
BE crash with select from hive external table stored as parquet

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#1302]
### Steps to reproduce the behavior (Required)
1. CREATE HIVE TABLE:
create table hive_hdfs_parquet(
 col_tinyint tinyint comment "column tinyint"
,col_smallint smallint comment "column smallint"
,col_int int comment "column int"
,col_integer integer comment "column integer"
,col_bigint bigint comment "column bigint"
,col_float float comment "column float"
,col_double double comment "column double"
,col_double_precision double precision comment "column double precision"
,col_decimal decimal comment "column decimal"
,col_timestamp timestamp comment "column timestamp"
,col_date date comment "column date"
,col_string string comment "column string"
,col_varchar varchar(100) comment "column varchar"
,col_binary binary comment "column binary"
,col_char char(100) comment "column char"
,col_boolean boolean comment "column boolean"
,col_array array<int> comment "column array"
)
clustered by(col_int) sorted by(col_int) into 32 buckets
row format delimited fields terminated by ','
stored as parquet;

2. INSERT INTO hive table:
insert into hive_hdfs_parquet select 1,1,1,1,1,1.001,10.1,110.1,1110.1,'2021-10-30 12:10:23','2021-10-30','hello world','hi hello','1110001010101011001001','nihao',true,array(1,10,100);
insert into hive_hdfs_parquet select 2,2,2,2,2,2.001,20.1,210.1,2110.2,'2021-02-01 12:10:23','2021-02-01','hello world','hi hello','1110001010101011001001','nihao',true,array(2,20,200);
insert into hive_hdfs_parquet select 3,3,3,3,3,3.001,30.1,310.1,3110.1,'2021-03-01 12:10:23','2021-03-01','hello world','hi abc','1110001010101011001001','nihao',true,array(3,30,300);
insert into hive_hdfs_parquet select 4,4,4,4,4,4.001,40.1,410.1,4110.2,'2021-04-01 12:10:23','2021-04-01','hello world','hi','1110001010101011001001','nihao',true,array(4,40,400);
insert into hive_hdfs_parquet select 13,null,13,13,13,13.001,130.1,1310.1,null,'2021-01-02 12:10:23','2021-01-02',null,'hi',null,null,null,array(13,130,1300);

3. CREATE HIVE EXTERNAL TABLE:
 create external table ex_hive_tbl1 (             
  col_tinyint tinyint not null comment "column tinyint"             ,
  col_smallint smallint null comment "column smallint"             ,
  col_date date null comment "partition by column"             ,
  col_boolean boolean null comment "column boolean")         
  ENGINE=hive         
  properties (             
   "resource" = "hive_resource",             
   "table" = "hive_hdfs_parquet",             
   "database" = "tn_test");

4. SELECT HIVE EXTERNAL TABLE, BE coredump:
mysql> select * from ex_hive_tbl1 order by col_tinyint desc limit 3;
ERROR 1064 (HY000): rpc failed, host:********

### Expected behavior (Required)
returns the right result

### Real behavior (Required)
BE coredump:
Core was generated by `/home/disk1/dorisdb/qa_test_master/be/lib/starrocks_be'.
Program terminated with signal 11, Segmentation fault.
#0  0x000000000237ddae in starrocks::parquet::IntToIntConverter<int, signed char>::convert(std::shared_ptr<starrocks::vectorized::Column> const&, starrocks::vectorized::Column*)
    ()
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 elfutils-libelf-0.176-2.el7.x86_64 elfutils-libs-0.176-2.el7.x86_64 glibc-2.17-307.el7.1.x86_64 java-1.8.0-openjdk-headless-1.8.0.262.b10-0.el7_8.x86_64 libattr-2.4.46-13.el7.x86_64 libcap-2.22-10.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libstdc++-4.8.5-39.el7.x86_64 systemd-libs-219-67.el7_7.4.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt
#0  0x000000000237ddae in starrocks::parquet::IntToIntConverter<int, signed char>::convert(std::shared_ptr<starrocks::vectorized::Column> const&, starrocks::vectorized::Column*)
    ()
#1  0x000000000237da23 in starrocks::parquet::ScalarColumnReader::prepare_batch(unsigned long*, starrocks::parquet::ColumnContentType, starrocks::vectorized::Column*) ()
#2  0x0000000002375432 in starrocks::parquet::GroupReader::_read(unsigned long*) ()
#3  0x0000000002375988 in starrocks::parquet::GroupReader::get_next(std::shared_ptr<starrocks::vectorized::Chunk>*, unsigned long*) ()
#4  0x000000000230fb3f in starrocks::parquet::FileReader::get_next(std::shared_ptr<starrocks::vectorized::Chunk>*) ()
#5  0x00000000022f61c5 in starrocks::vectorized::HdfsParquetScanner::do_get_next(starrocks::RuntimeState*, std::shared_ptr<starrocks::vectorized::Chunk>*) ()
#6  0x00000000022f652a in starrocks::vectorized::HdfsScanner::get_next(starrocks::RuntimeState*, std::shared_ptr<starrocks::vectorized::Chunk>*) ()
#7  0x0000000002277831 in starrocks::vectorized::HdfsScanNode::_scanner_thread(starrocks::vectorized::HdfsScanner*) ()
#8  0x0000000001ac334d in starrocks::PriorityThreadPool::work_thread(int) ()
#9  0x00000000033c6857 in thread_proxy ()
#10 0x00007f8901c5cea5 in start_thread () from /lib64/libpthread.so.0
#11 0x00007f89010618dd in clone () from /lib64/libc.so.6
(gdb)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN be897f6   |
+-------------------+
1 row in set (0.01 sec)

**Comment by caneGuy** [comment]
i would like to solve this problem @tiannan-sr @chaoyli

**Comment by stdpain** [comment]
I have reproduced it. It seems caused by nullable column process

**Comment by stdpain** [comment]
This is because the properties of the columns in the hive table are nullable but the schema in starrocks is non-nullable.

We need to check the properties of the hive outer table, if the mapped table in starrocks is non-nullable, then it must be non-nullable in hive. This needs to be implemented by FE

Also need to implement the logic for handling non-nullable columns in BE
