### ISSUE TITLE
 NTH_VALUE windows function  support

### ISSUE THREAD

**Issue by vkingnew** [StarRocks/starrocks#13021]
NTH_VALUE function not support

https://dev.mysql.com/doc/refman/8.0/en/window-function-descriptions.html
https://dev.mysql.com/doc/refman/8.0/en/window-function-descriptions.html#function_nth-value
the standard Windows function current not support as fellowing：
CUME_DIST()
NTH_VALUE()
PERCENT_RANK()

and **medium()** function in the windows function

**Comment by wangsimo0** [comment]
@amorynan hi amorynan could you please reply here so I can assign this to you?

**Comment by wangsimo0** [comment]
For CUME_DIST,  here is the standard definition
> If CUME_DIST is specified, then the relative rank of a row R is defined as NP/NR, where NP is defined to be the number of rows preceding or peer with R in the window ordering of the window partition of R and NR is defined to be the number of rows in the window partition of R. 
For CUME_DIST there is no other parameters needed. And also it is pretty clear in MySQL. https://dev.mysql.com/doc/refman/8.0/en/window-function-descriptions.html#function_cume-dist

```
mysql> SELECT
         val,
         ROW_NUMBER()   OVER w AS 'row_number',
         CUME_DIST()    OVER w AS 'cume_dist',
         PERCENT_RANK() OVER w AS 'percent_rank'
       FROM numbers
       WINDOW w AS (ORDER BY val);
+------+------------+--------------------+--------------+
| val  | row_number | cume_dist          | percent_rank |
+------+------------+--------------------+--------------+
|    1 |          1 | 0.2222222222222222 |            0 |
|    1 |          2 | 0.2222222222222222 |            0 |
|    2 |          3 | 0.3333333333333333 |         0.25 |
|    3 |          4 | 0.6666666666666666 |        0.375 |
|    3 |          5 | 0.6666666666666666 |        0.375 |
|    3 |          6 | 0.6666666666666666 |        0.375 |
|    4 |          7 | 0.8888888888888888 |         0.75 |
|    4 |          8 | 0.8888888888888888 |         0.75 |
|    5 |          9 |                  1 |            1 |
+------+------------+--------------------+--------------+
```

**Comment by wangsimo0** [comment]
For nth_value, here is the standard syntax
```
  NTH_VALUE ( <value expression>, <nth row>)
      [ FROM {FIRST | LAST} ] [{ IGNORE | RESPECT } NULLS ]
      OVER ([PARTITION BY] ORDER BY)
```

there are two necessary parameters. 

## 1. from first/last (optional)
this defines the direction is whether from the beginning or the ending of the ordered list. If this is not specified, the default is first.

for example: 

```
create table windowtest (col1 int, col2 int);
insert into windowtest values (1,11),(1,12),(1,13),(2,21),(2,22),(2,23);
```

```
 select * from windowtest;
+------+------+
| col1 | col2 |
+------+------+
|    1 |   11 |
|    1 |   12 |
|    1 |   13 |
|    2 |   21 |
|    2 |   22 |
|    2 |   23 |
+------+------+
```

```
SELECT
    col1,
    NTH_VALUE(col2, 1) OVER (PARTITION BY col1 ORDER BY col2) AS col2
FROM windowtest;

+------+------+
| col1 | col2 |
+------+------+
|    1 |   11 |
|    1 |   11 |
|    1 |   11 |
|    2 |   21 |
|    2 |   21 |
|    2 |   21 |
+------+------+

SELECT
    col1,
    NTH_VALUE(col2, 1) FROM LAST OVER (PARTITION BY col1 ORDER BY col2) AS col2
FROM windowtest;

+------+------+
| col1 | col2 |
+------+------+
|    1 |   13 |
|    1 |   13 |
|    1 |   13 |
|    2 |   23 |
|    2 |   23 |
|    2 |   23 |
+------+------+

```

## 2. ignore/respect nulls
this is a more common parameter. The default is respect nulls/

for example

```
+------+------+
| col1 | col2 |
+------+------+
|    1 |   11 |
|    1 |   12 |
|    1 |   null|
|    2 |   21 |
|    2 |   22 |
|    2 |   23 |
+------+------+

SELECT
    col1,
    NTH_VALUE(col2, 1) FROM LAST RESPECT NULLS OVER (PARTITION BY col1 ORDER BY col2) AS col2
FROM windowtest;

+------+------+
| col1 | col2 |
+------+------+
|    1 |   null |
|    1 |   null |
|    1 |   null |
|    2 |   23 |
|    2 |   23 |
|    2 |   23 |
+------+------+

SELECT
    col1,
    NTH_VALUE(col2, 1) FROM LAST IGNORE NULLS OVER (PARTITION BY col1 ORDER BY col2) AS col2
FROM windowtest;

+------+------+
| col1 | col2 |
+------+------+
|    1 |   12 |
|    1 |   12 |
|    1 |   12 |
|    2 |   23 |
|    2 |   23 |
|    2 |   23 |
+------+------+


## other notice

```
<nth value function> ::=
  NTH_VALUE ( <value expression>, <nth row>)
      [ FROM {FIRST | LAST} ] [{ IGNORE | RESPECT } NULLS ]
```

1. the `nth_row` must be positive integer.
2. if the `nth_row` is bigger than count(value), returns null. like in the example above

```
SELECT
    col2,
    NTH_VALUE(col2, 5) OVER (PARTITION BY col1 ORDER BY col2) AS col2
FROM windowtest;

+------+------+
| col1 | col2 |
+------+------+
|    1 |   null |
|    1 |   null |
|    1 |   null |
|    2 |   null |
|    2 |   null |
|    2 |   null |
+------+------+

```

3. partition by is optional. order by is compulsive.

**Comment by kateshaowanjou** [comment]
@Moonm3n  Can you make a comment here？So I can assign this to you?

**Comment by Moonm3n** [comment]
> @Moonm3n Can you make a comment here？So I can assign this to you?

Sure, I'd like to take on the CUME_DIST issue. Looking forward to working on it!

**Comment by byrantwithyou** [comment]
Hi @kateshaowanjou . Could you assign the NTH_VALUE issue to me? I'm also happy to take other window functions after this one.

**Comment by Moonm3n** [comment]
> Hi @kateshaowanjou . Could you assign the PERCENT_RANK issue to me? I'm also happy to take other window functions after this one.

I may be mistaken, but it seems that the PERCENT_RANK issue is very similar to the CUME_DIST issue. The only difference is that when calculating the PERCENT_RANK, we need to subtract 1. Perhaps I can solve both issues at the same time. If not, we are likely to write some duplicate and conflicting code. Alternatively, would you like to explore a different issue? Thank you kindly.

**Comment by byrantwithyou** [comment]
Yes, that's reasonable

**Comment by byrantwithyou** [comment]
> > Hi @kateshaowanjou . Could you assign the PERCENT_RANK issue to me? I'm also happy to take other window functions after this one.
> 
> I may be mistaken, but it seems that the PERCENT_RANK issue is very similar to the CUME_DIST issue. The only difference is that when calculating the PERCENT_RANK, we need to subtract 1. Perhaps I can solve both issues at the same time. If not, we are likely to write some duplicate and conflicting code. Alternatively, would you like to explore a different issue? Thank you kindly.

Agree

**Comment by kateshaowanjou** [comment]
@Moonm3n @byrantwithyou  CUME_DIST & PERCENT_RANK can be viewed as different issues so I can assign these 2 issues to different people. But I think you've resolved the conflict already, very happy to see you've worked it out. Please feel free to let me know how I can help!

**Comment by vendanner** [comment]
Hi @kateshaowanjou . Could you assign the NTH_VALUE issue to me
