### ISSUE TITLE
sr don't support makedate

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#13051]
sr don't support makedate, which can calculate a date by year and day of year values. 
To be more specific:
Returns a date, given year and day-of-year values. dayofyear must be greater than 0 or the result is NULL. The result is also NULL if either argument is NULL.

mysql> SELECT MAKEDATE(2011,31), MAKEDATE(2011,32);
        -> '2011-01-31', '2011-02-01'
mysql> SELECT MAKEDATE(2011,365), MAKEDATE(2014,365);
        -> '2011-12-31', '2014-12-31'
mysql> SELECT MAKEDATE(2011,0);
        -> NULL

**Comment by wangsimo0** [comment]
@mchades hi could you please reply to this issue so I can assign it to you?

**Comment by mchades** [comment]
> @mchades hi could you please reply to this issue so I can assign it to you?

ok

**Comment by zhangruchubaba** [comment]
@wangsimo0  Is this task not handled yet? If so, you can assign it to me.

**Comment by zhangruchubaba** [comment]
@kateshaowanjou   thank u

**Comment by zhangruchubaba** [comment]
The first parameter: the value range of year is [0,9999]
The second parameter: the value range of date_of_year is (0,365|366]--the year of the returned date is consistent with the first parameter
If the parameters do not meet the above range, the return result is null
