### ISSUE TITLE
/api/transaction/begin  2.4.0版本开启一个新事务

### ISSUE THREAD

**Issue by liquan00759** [StarRocks/starrocks#13077]
curl --user root:wq00759 -H "label:test_11111" -H "db:test" -H "table:car_status" -XPUT http://10.246.96.35:8030/api/transaction/begin   这样执行操作，无任何返回值，请教各位大佬时什么情况呢
![image](https://user-images.githubusercontent.com/60721993/200458067-b338ab69-6e1d-4648-b742-b9b8023ea72c.png)

**Comment by imay** [comment]
> 

You can get detailed information by executing with `-v` option like `curl -v`

**Comment by liquan00759** [comment]
> > 
> 
> You can get detailed information by executing with `-v` option like `curl -v`

加上-v 是这样，我换成be:8040 可以成功 ，不知道什么原因

**Comment by jaogoy** [comment]
@meegoo can have a look.

**Comment by meegoo** [comment]
@liquan00759 using POST method
