### ISSUE TITLE
test starRocks error in Debian 9 linux 4.14

### ISSUE THREAD

**Issue by BanBuDu0** [StarRocks/starrocks#131]
hi, I run cmd `sh ./run-ut.sh --be --run` in my Debian 9 linux 4.14.
And got the error `./run-ut.sh: 19: set: Illegal option -o pipefail`

**Comment by stdpain** [comment]
you could try to use 
```
bash ./run-ut.sh --be --run
```

**Comment by BanBuDu0** [comment]
> you could try to use
> 
> ```
> bash ./run-ut.sh --be --run
> ```

i run this command and see `Python 2.7.13` in new line..

**Comment by stdpain** [comment]
@BanBuDu0 
sorry
try to use 
```
bash ./run-ut.sh --run
```

**Comment by BanBuDu0** [comment]
I know why i get `./run-ut.sh: 19: set: Illegal option -o pipefail` error.
the reason is debian default shell is dash rather bash.
Solution:
1. run `sudo dpkg-reconfigure dash`
2. select **No**

**Comment by BanBuDu0** [comment]
I change shell from dash to bash,
but whatever i run `bash ./run-ut.sh --run` or `sh ./run-ut.sh --be --run`, I got `Python 2.7.13` output..

**Comment by stdpain** [comment]
you could comment this line in ./run-ut.sh
> # set -eo pipefail
and execute bash  ./run-ut.sh --run

it was because the shell command was terminated early with an error

**Comment by stdpain** [comment]
I advise execute this command and paste the log
```
bash -x  ./run-ut.sh --run
```

I think may be some dependency is wrong

**Comment by BanBuDu0** [comment]
> bash -x  ./run-ut.sh --run

yes, the command shows 
`Error: mvn is not found` QAQ

**Comment by stdpain** [comment]
@BanBuDu0 Hi !
Are you willing to submit Pull Request to provide more friendly error message in Debian 9?

**Comment by BanBuDu0** [comment]
> @BanBuDu0 Hi !
> Are you willing to submit Pull Request to provide more friendly error message in Debian 9?

thanks, but I am not good at shell langunge. (ㄒoㄒ)
