### ISSUE TITLE
ERROR 1064 (HY000): fetch es table [test_index] metadata failure: index[test_index] not found

### ISSUE THREAD

**Issue by kobebryantlin0** [StarRocks/starrocks#13148]
### Steps to reproduce the behavior (Required)

query es data in sr failed. 

PS: the es index can be queried normally in es,  but failed query by sr.

when I work around by drop table and recreate table, query is correct. I want to know why this happened?

### Expected behavior (Required)
success 
### Real behavior (Required)
ERROR 1064 (HY000): fetch es table [test_index] metadata failure: index[test_index] not found

### StarRocks version (Required)
2.1.3

**Comment by Smith-Cruise** [comment]
I think this bug is fixed by https://github.com/StarRocks/starrocks/pull/11612.

You can cherry-pick by yourself.

**Comment by kobebryantlin0** [comment]
您好，我是林恩伟，你发的邮件我已经收到。

**Comment by kobebryantlin0** [comment]
We repeated the problem in the test environment and found that the reason was that the includeTypeName field was still true when our ES6. x version was restarted.  I commit pull requests in [#13995](https://github.com/StarRocks/starrocks/pull/13995)
