### ISSUE TITLE
Support CTE(common table expression) reuse

### ISSUE THREAD

**Issue by Seaven** [StarRocks/starrocks#1318]
CTE (Common Table Expressions): Common Table Expression, represents a set of temporary data sheets, and the SQL 1999 standard is introduced, which can appear in SELECT, UPDATE, INSERT, and DELETE statements, and its role is:

* Simplify complex SQL, improve SQL readability
* Avoid repeating the expression / data of multiple references, improve performance

like:
```
WITH v as (
    SELECT ibrand, icurrentprice, max(iunits) m
    FROM item
    WHERE icolor = ’red’
    GROUP BY ibrand, icurrentprice)
SELECT * FROM v 
WHERE m < 100 AND v.icurrentprice IN (
    SELECT min(icurrentprice)
    FROM v 
    WHERE m > 5); 
```

 Currently, starrocks only support inline CTE into query, we will support CTE reuse for starrocks, it's can improve performance for most queries with CTE, there is TODOs for the feature.
TODOs:

- [x]  Support CTE analyze on optimizer
- [x]  Support CTE prune rule
- [x]  Support CTE inline rule in RuleRewrite phase
- [x]  Support CTE execute on BE
- [x]  Support CTE cost on optimizer

**Comment by imay** [comment]
@Seaven 
Could you provide some design details about this feature?
Then you can let all the people know how to do it. And people who is interested can participate in discussions and development together.
