### ISSUE TITLE
Hive external table query failed: parquet column reader

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#1321]
### Steps to reproduce the behavior (Required)
1. create hive table stored as parquet, and insert one row data:
create table hive_hdfs_parquet(
 col_tinyint tinyint comment "column tinyint"
,col_smallint smallint comment "column smallint"
,col_int int comment "column int"
,col_integer integer comment "column integer"
,col_bigint bigint comment "column bigint"
,col_float float comment "column float"
,col_double double comment "column double"
,col_double_precision double precision comment "column double precision"
,col_decimal decimal comment "column decimal"
,col_timestamp timestamp comment "column timestamp"
,col_date date comment "column date"
,col_string string comment "column string"
,col_varchar varchar(100) comment "column varchar"
,col_binary binary comment "column binary"
,col_char char(100) comment "column char"
,col_boolean boolean comment "column boolean"
,col_array array<int> comment "column array"
)
clustered by(col_int) sorted by(col_int) into 32 buckets
row format delimited fields terminated by ','
stored as parquet;
insert into hive_hdfs_parquet select 1,1,1,1,1,1.001,10.1,110.1,1110.1,'2021-10-30 12:10:23','2021-10-30','hello world','hi hello','1110001010101011001001','nihao',true,array(1,10,100);

2. alter hive table change column col_date to varchar(100) datatype, and insert one row data:
alter table hive_hdfs_parquet CHANGE COLUMN col_date col_date varchar(100);
insert into hive_hdfs_parquet select 14,14,14,14,14,14.001,140.1,1410.1,14110.2,'2021-02-02 12:10:23','2022-01-02','hello world','hi','1110001010101011001001','new insert data',true,array(14,140,1400);

3. create hive external table:
create external table ex_hive_tbl_rfsh_new (         
 col_int int         ,
 col_float float         ,
 col_date varchar(100)         ,
 col_boolean boolean         ,
 col_char char(100)         ,
 col_decimal decimal)         
 ENGINE=hive         
 properties (             
  "resource" = "hive_resource",             
  "table" = "hive_hdfs_parquet",             
  "database" = "tn_test");

4. select hive external table failed:
mysql> select * from ex_hive_tbl_rfsh_new;
ERROR 1064 (HY000): parquet column reader: not supported convert from parquet `INT32` to `VARCHAR`

### Expected behavior (Required)
return the right result

### Real behavior (Required)
mysql> select * from ex_hive_tbl_rfsh_new;
ERROR 1064 (HY000): parquet column reader: not supported convert from parquet `INT32` to `VARCHAR`

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN be897f6   |
+-------------------+
1 row in set (0.00 sec)

**Comment by dirtysalt** [comment]
We don't support alter type of column.
