### ISSUE TITLE
[function] need to support bitwise shift function

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#13221]
## Feature request
1. bit_shiftleft: Arithmetic shift left
```
SELECT bit_shiftleft(2, 1);
 4
```

2. bit_shfitright: Arithmetic  shift right
```
SELECT bit_shfitright(4, 1);
 2
```

3. bit_shiftright_logic: logic shift right
```
SELECT bit_shiftright_logic(4, 1);
 2
```

**Comment by wangsimo0** [comment]
@sparklezzz could you please add a comment here so I can assign this issue to you

**Comment by sparklezzz** [comment]
here
