### ISSUE TITLE
[function]strcmp need to be suppported

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#13246]
[STRCMP()](https://dev.mysql.com/doc/refman/5.6/en/string-comparison-functions.html#function_strcmp) returns 0 if the strings are the same, -1 if the first argument is smaller than the second according to the current sort order, and 1 otherwise.
```
mysql> SELECT STRCMP('text', 'text2');
        -> -1
mysql> SELECT STRCMP('text2', 'text');
        -> 1
mysql> SELECT STRCMP('text', 'text');
        -> 0
```

**Comment by wangsimo0** [comment]
@tomscut hi could you please reply to this issue so I can assign it to you?

**Comment by tomscut** [comment]
Hi @wangsimo0 , please assign this to me. Thank you.
