### ISSUE TITLE
[function] sr already support bunch of trigonometric functions, still need sinh, cosh, tanh

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#13298]
trigonometric functions
sinh
cosh 
tanh

![image](https://user-images.githubusercontent.com/48942089/201330524-0c3aa498-89b8-4fec-af16-b33a88b3c2fd.png)

**Comment by wangsimo0** [comment]
@tomscut hi could you please reply to this issue so I can assign it to you?

**Comment by tomscut** [comment]
Hi @wangsimo0 , please assign this to me. Thank you~

**Comment by wangsimo0** [comment]
@tomscut done :) btw I find out that impala has the similar function. https://impala.apache.org/docs/build/html/topics/impala_math_functions.html#math_functions__sinh
Just for your reference ~

**Comment by tomscut** [comment]
> @tomscut done :) btw I find out that impala has the similar function. https://impala.apache.org/docs/build/html/topics/impala_math_functions.html#math_functions__sinh Just for your reference ~

Thanks a lot.

**Comment by wangsimo0** [comment]
@tomscut Hi tomscut, thanks for contributing! Really appreciate it. Could you please add the document for others to learn this function better?
