### ISSUE TITLE
[function] need format to compare two strings

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#13304]
Formats the number X to a format like '#,###,###.##', rounded to D decimal places, and returns the result as a string. If D is 0, the result has no decimal point or fractional part.

please refer to   https://dev.mysql.com/doc/refman/5.6/en/string-functions.html#function_format 

mysql> SELECT FORMAT(12332.123456, 4);
        -> '12,332.1235'
mysql> SELECT FORMAT(12332.1,4);
        -> '12,332.1000'
mysql> SELECT FORMAT(12332.2,0);
        -> '12,332'

**Comment by wangsimo0** [comment]
@mchades hi could you please reply to this issue so I can assign it to you?

**Comment by mchades** [comment]
> @mchades hi could you please reply to this issue so I can assign it to you?

OK, I will do this

**Comment by iiiuwioajdks** [comment]
I see the assign of this issue has been a while, can I also try to complete this, I want some simple issue to cut into starrocks to learn better @wangsimo0

**Comment by kateshaowanjou** [comment]
@iiiuwioajdks Hi buddy, are you still working on this issue？ If you have any questions, feel free to join WeChat for discussion: https://ma3you.com/articles_qrcode_show/b12e90J.png?le_time=220907203008013206

**Comment by Jin-H** [comment]
@kateshaowanjou I want to try this task, can you assign it to me?

**Comment by LakshmiGayathri19** [comment]
@wangsimo0 Could you please assign this to me, I would like to contribute to this project.
Thanks in advance

**Comment by wangsimo0** [comment]
sorry for the delay. @Jin-H @LakshmiGayathri19 hi are you still have interest to try this task? sorry again for the delay

**Comment by Jin-H** [comment]
@wangsimo0 Plz assign it to me, thanks.

**Comment by silly-carbon** [comment]
hi @wangsimo0 
Is anyone still working on this? If no, please re-assign it to me and I will start implementing it now

**Comment by Jin-H** [comment]
Sorry, I originally planned to deal with it in these two weeks, but I have been busy with work recently and have not had time to do this task. At present, I don’t expect to start doing it until after New Year’s Day in 2024. If you particularly want to try this task, Then do it. @silly-carbon

**Comment by silly-carbon** [comment]
> Sorry, I originally planned to deal with it in these two weeks, but I have been busy with work recently and have not had time to do this task. At present, I don’t expect to start doing it until after New Year’s Day in 2024. If you particularly want to try this task, Then do it. @silly-carbon

@Jin-H thanks mate, OK I'll implement this
