### ISSUE TITLE
[information_schema]normal table information error

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#13310]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
 CREATE TABLE t1 ( c1 int NOT NULL, c2 bitmap BITMAP_UNION NOT NULL ) DISTRIBUTED BY HASH(`c1`) BUCKETS 2 PROPERTIES ( "replication_num" = "3" );
```
2.SELECT  '....'
```
select * from information_schema.tables_config where TABLE_SCHEMA='test_info_tables_conf_88520a70_61cd_11ed_b091_00163e0e550b' and TABLE_NAME='t1';
```
### Expected behavior (Required)
TABLE_MODEL=def
PRIMARY_KEY=def
PARTITION_KEY=def
PROPERTIES should be equal to reality
### Real behavior (Required)
AGG_KEYS
![image](https://user-images.githubusercontent.com/57162397/201361660-194ec100-36f8-4e15-a410-26ed95d874e0.png)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE e21cd48 |
+----------------------+
```

**Comment by waittttting** [comment]
DONE
