### ISSUE TITLE
Support floating IP in docker environment

### ISSUE THREAD

**Issue by itweixiang** [StarRocks/starrocks#1332]
## Enhancement
前置条件：集群基于k8s容器化部署，重启节点会导致IP更变
期待结果：选举算法兼容浮动IP变更的场景

步骤：
1、集群正常启动，并初始化
2、集群某节点宕机，但被k8s重新调度重启，IP发生了变更
3、宕机重启后，获取的新IP 和 本机硬盘存储的IP 不一致，启动报错

下图可以看到，集群存储的信息，强依赖于IP。
![图片](https://user-images.githubusercontent.com/40189074/142129132-79c40b69-7330-4d36-b132-2c90bb55cf0f.png)

**Comment by Dshadowzh** [comment]
Yes, current metadata management is based on IP addresses. We'll consider this scenario.

**Comment by itweixiang** [comment]
Thanks for your reply



and I wish to know of update time of  the function , raft algorithm and your say metadata management







At 2021-11-17 14:02:18, "Dshadowzh" ***@***.***> wrote:

Yes, current metadata management is based on IP addresses. We'll consider this scenario.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
