### ISSUE TITLE
storage_cooldown_time not effective

### ISSUE THREAD

**Issue by BruceYu-D20** [StarRocks/starrocks#13327]
2.3.3 version，hdd is the default storage.The storage medium of the table is ssd，I modify the storage_cooldown_time of the table , but no automatic transfer of data after expiration。
table properties：
![企业微信截图_16683896229615](https://user-images.githubusercontent.com/68089615/201557343-d6129055-eb7a-434d-bc0f-d14d5cef6a9a.png)
alter sql and after the coolown time, the partition's information：
![企业微信截图_1668389657316](https://user-images.githubusercontent.com/68089615/201557389-549dab9a-02a8-4548-9f3e-cf511ac1a78e.png)
The disk usage has not changed on the monitoring：
![企业微信截图_16683897089019](https://user-images.githubusercontent.com/68089615/201557458-fe396d92-ecea-45bc-b910-62195a131f9d.png)

**Comment by chaoyli** [comment]
@BruceYu-D20 Have you configured the disk to be an SSD in be.conf. There may be no SSD disk in the cluster.

**Comment by jaogoy** [comment]
But, we really need to optimize the usability of storage medium.
