### ISSUE TITLE
Starrocks for enduser analytics

### ISSUE THREAD

**Issue by sridhard** [StarRocks/starrocks#13321]
Hi,

1. Can we use starrocks for enduser analytics? Example: In a education website, we want to show the performance report of the student in a exam (Show report to the student). Like we want to show the marks scored by topic, time taken based on difficulty level, compare student score to the topper score etc. We can have more than 10000 users taking test any time. So the star rocks concurrency should be more than 10000 users

2. Can we use starrocks to get the user list in drill down reporting. For example suppose we are selling a course. The course can have paid or free users. In starrocks we find the total paid and free users every day and display to admin. When the admin want to get more details about the free users(Like list of free users and their email and mobile number) can we retrieve the list of users and show to admin? is this a proper usecase? Because starrocks is optimised for analytics/aggregations.

Thanks

**Comment by jaogoy** [comment]
1. It depends on your total data size and query data size, if data size of every query is not big, It can supports up to 10k concurrency. But, in your situation, will every user do a query per second?
2. I think your data won't be too much, will it be larger than 10M records a day? If not, you can almost do whatever analytics you want.

**Comment by sridhard** [comment]
thanks a lot
