### ISSUE TITLE
Cannot update array of array in broker load

### ISSUE THREAD

**Issue by sxhysj** [StarRocks/starrocks#13331]
### Steps to reproduce the behavior (Required)
We have a large table with 1000 columns. When we used broker load to update 40 columns of it, in which inlcudes array of array, then the process failed, showing the following error message:

ErrorMsg: type: ETL_RUN_FAIL; msg_Cannot cast '<slot 4>' from VARCHAR to ARRAY<VARCHAR(100)>

### Expected behavior (Required)

Expected the array of array to be sucessfully imported without errors.

### Real behavior (Required)

ErrorMsg: type: ETL_RUN_FAIL; msg_Cannot cast '<slot 4>' from VARCHAR to ARRAY<VARCHAR(100)>

### StarRocks version (Required)
2.3

My question is:
1. Does starrocks support array of array updating?
2. Is there any configuration that need to adjusted before loading array of array?

**Comment by chaoyli** [comment]
It has been addressed in 2.3.3. @sxhysj , which version do you install?

**Comment by jaogoy** [comment]
@chaoyli Does SR support loading data of Array of Array?

**Comment by chaoyli** [comment]
@jaogoy It's array<string> not array<array>
