### ISSUE TITLE
[Bug] Docker compilation issue

### ISSUE THREAD

**Issue by hzh0425** [StarRocks/starrocks#13346]
Hi, teams!
When I use Docker to compile the source code(using build.sh), I have the following problem  (thirdparty -- 'aws-sdk-cpp')
Is there any solution?
Docker image is: 'docker pull starrocks/dev-env:main'

![image](https://user-images.githubusercontent.com/58988019/201617457-fc1f6f1e-dcd6-4438-9638-07cfeacdc3a5.png)

**Comment by wangruin** [comment]
Please check if you are using the latest main image of https://hub.docker.com/r/starrocks/dev-env/tags which DIGEST value is a8b7a32747bf
```
[]# docker images --digests | grep main
starrocks/dev-env           main                    sha256:a8b7a32747bf549ca2082b8e15dc2c48e084b3fde5b0b87574f3a8a7041e7435   df8b9a9c4490   5 days ago          9.57GB
```
In addition, if you use other `registry-mirrors` in `/etc/docker/daemon.json`, you need to remove it and restart docker before executing `docker pull starrocks/dev-env:main`

**Comment by hzh0425** [comment]
@wangruin Thinks, As you said, I can compile successfully after using the latest image
