### ISSUE TITLE
The performance of Scan S3/OSS is slow

### ISSUE THREAD

**Issue by chaoyli** [StarRocks/starrocks#1336]
We test the scan performance of S3/OSS using TPC-H.
The scale is 100. And the data is stored as the ORC format using snappy compression.

Environment:
   AWS m5.4xlarge (16vcpu, 8core, 64G)

**Comment by chaoyli** [comment]
<div class="okr-block-clipboard" data-okr="%7B%22okrDelta%22%3A%5B%7B%22lineType%22%3A%22unsupport%22%2C%22lineOptions%22%3A%7B%7D%2C%22lineContent%22%3A%5B%5D%7D%5D%2C%22businessKey%22%3A%22lark-doc%22%7D"></div><div data-zone-id="0" data-line-index="0" style="white-space: pre;">

QUERY | Starrocks HDFS(单位：second) | Starrocks S3(单位：second) | Presto s3(单位: second) | ratio (Starrocks S3 / Starrocks hdfs) | ratio (Starrocks S3 / Presto S3)
-- | -- | -- | -- | -- | --
Q1 | 10.12 | 27.08 | 12 | 2.7 | 2.3
Q2 | 0.72 | 7.97 | 4 | 11.1 | 2.0
Q3 | 6.06 | 25.38 | 11 | 4.2 | 2.3
Q4 | 3.29 | 9.42 | 8 | 2.7 | 1.2
Q5 | 6.94 | 27.65 | 16 | 4.0 | 1.7
Q6 | 2.35 | 21.12 | 4 | 9.0 | 5.3
Q7 | 4.25 | 28.09 | 13 | 6.6 | 2.2
Q8 | 4.73 | 31.94 | 14 | 6.8 | 2.3
Q9 | 21.69 | 50.67 | 25 | 2.3 | 2.0
Q10 | 7.87 | 31.25 | 10 | 4.0 | 3.1
Q11 | 0.79 | 6.31 | 4 | 8.0 | 1.6
Q12 | 3.74 | 12.86 | 7 | 3.4 | 1.8
Q13 | 8.70 | 19.34 | 11 | 2.2 | 1.8
Q14 | 3.18 | 25.69 | 4 | 8.1 | 6.4
Q15 | 5.19 | 45.05 | 8 | 8.7 | 5.6
Q16 | 1.75 | 3.67 | 4 | 2.1 | 0.9
Q17 | 5.02 | 33.44 | 33 | 6.7 | 1.0
Q18 | 51.78 | 70.33 | 53 | 1.4 | 1.3
Q19 | 3.45 | 27.72 | 7 | 8.0 | 4.0
Q20 | 2.68 | 22.58 | 10 | 8.0 | 2.3
Q21 | 12.61 | 36.40 | 34 | 2.9 | 1.1
Q22 | 2.02 | 5.95 | 4 | 2.9 | 1.5

</div>

**Comment by miomiocat** [comment]
I will resolve this problem

**Comment by miomiocat** [comment]
Current progress in details:

The query time difference mainly comes from libhdfs `hdfsRead` calls in https://github.com/StarRocks/starrocks/blob/main/be/src/env/env_hdfs.cpp#L56.

for example, print log about this method call：
```
// hdfs read:
I1207 20:40:25.904878 25494 env_hdfs.cpp:44] xxxx read_at_internal: start file_name: hdfs://xxx/user/hive/warehouse/tpch_100_orc_hdfs.db/lineitem/000015_0 offset: 114238149 res 4396345
I1207 20:40:25.907514 25494 env_hdfs.cpp:72] xxxx read_at_internal: end file_name: hdfs://xxx/user/hive/warehouse/tpch_100_orc_hdfs.db/lineitem/000015_0 offset: 114238149 res 4396345
// 907514-904878=2636
I1207 20:40:25.909313 25494 env_hdfs.cpp:44] xxxx read_at_internal: start file_name: hdfs://xxx/user/hive/warehouse/tpch_100_orc_hdfs.db/lineitem/000015_0 offset: 124431953 res 5559794
I1207 20:40:25.912453 25494 env_hdfs.cpp:72] xxxx read_at_internal: end file_name: hdfs://xxx/user/hive/warehouse/tpch_100_orc_hdfs.db/lineitem/000015_0 offset: 124431953 res 5559794
// 912453-909313=3140
I1207 20:40:25.913574 25494 env_hdfs.cpp:44] xxxx read_at_internal: start file_name: hdfs://xxx/user/hive/warehouse/tpch_100_orc_hdfs.db/lineitem/000015_0 offset: 129991747 res 1411797
I1207 20:40:25.914671 25494 env_hdfs.cpp:72] xxxx read_at_internal: end file_name: hdfs://xxx/user/hive/warehouse/tpch_100_orc_hdfs.db/lineitem/000015_0 offset: 129991747 res 1411797
// 914671-913574=1097

// oss read:
I1207 20:33:29.061149  3340 env_hdfs.cpp:44] xxxx read_at_internal: start file_name: oss://xxx/warehouse/tpch_flat_orc_100.db/lineitem/000015_0 offset: 114238149 res 4396345
I1207 20:33:29.257539  3340 env_hdfs.cpp:72] xxxx read_at_internal: end file_name: oss://xxx/warehouse/tpch_flat_orc_100.db/lineitem/000015_0 offset: 114238149 res 4396345
// 257539-061149=196390
I1207 20:33:29.259924  3340 env_hdfs.cpp:44] xxxx read_at_internal: start file_name: oss://xxx/warehouse/tpch_flat_orc_100.db/lineitem/000015_0 offset: 124431953 res 5559794
I1207 20:33:29.559684  3340 env_hdfs.cpp:72] xxxx read_at_internal: end file_name: oss://xxx/warehouse/tpch_flat_orc_100.db/lineitem/000015_0 offset: 124431953 res 5559794
// 559684-259924=299760
I1207 20:33:29.560891  3340 env_hdfs.cpp:44] xxxx read_at_internal: start file_name: oss://xxx/warehouse/tpch_flat_orc_100.db/lineitem/000015_0 offset: 129991747 res 1411797
I1207 20:33:29.617296  3340 env_hdfs.cpp:72] xxxx read_at_internal: end file_name: oss://xxx/warehouse/tpch_flat_orc_100.db/lineitem/000015_0 offset: 129991747 res 1411797
// 617296-560891=56405

```

Currently I will commit a PR to partially improve this problem by the following method:
1. make scanner concurrency parameter configable.
2. use hdfsPreadFully rather than hdfsRead for s3/oss to reduce the amount of JNI array allocations, refer to: https://github.com/apache/impala/commit/89b9c93c7ac5f3eb19977290ba5115547120a0a3
3. upgrade oss sdk version.

In the next step I will consider the following possible solutions:
1. try to use native sdk to avoid JNI.
2. data cache for s3/oss, refer to https://github.com/apache/impala/commit/2ece4c9b2e114a5e8873c5ac69e75b84c62bf5bd
