### ISSUE TITLE
Error log about broker

### ISSUE THREAD

**Issue by cliffzhan** [StarRocks/starrocks#1343]
If boot broker service  by root ,it seems everything's ok,when i start  a broker plan ,the broker log notice that
Permission denied: user=root, access=READ, inode="/user/hive/xx/xx/xxx/xxx=xx/part-00005-875acf23-bc34-4986-81aa-6aa3b7a5841c.c000":hive:hive:-rwxrwx--x
In fact,after reboot broker service  by normal user,it can work correctly,but the error message make me think that the hdfs permissions may be wrong.

**Comment by chaoyli** [comment]
This is the permission problem and you should check your HDFS permission.
