### ISSUE TITLE
User defined UDAF function query error

### ISSUE THREAD

**Issue by gaoy121** [StarRocks/starrocks#13469]
### Steps to reproduce the behavior (Required)
1.Function Description
group by之后，将字段合并为一个STRING

2. Statement of table creation
CREATE TABLE table1
(
    id INT DEFAULT '10',
    name STRING ,
    number BIGINT
)
PRIMARY KEY (id)
DISTRIBUTED BY HASH(id) BUCKETS 8
PROPERTIES("replication_num" = "1");

3. Write data
insert into table1 values(1,'zhangsan',100),(2,'zhangsan',100),(3,'zhangsan',100),(4,'lisi',100),(5,'lisi',100)

4.Create UDAF Function
CREATE AGGREGATE FUNCTION my_udaf_1(BIGINT)
RETURNS STRING
PROPERTIES
(
    "symbol" = "com.starrocks.udf.UDAFArray",
    "type" = "StarrocksJar",
    "file" = "file:///opt/software/starrocks-udf-1.0-SNAPSHOT-jar-with-dependencies.jar"
);

5. Query statement
select name,my_udaf_1(number) from table1 group by name

### Expected behavior (Required)
Query Result
![image](https://user-images.githubusercontent.com/55279192/202114877-ad1ee6bb-2386-4a81-a6cb-5443216102ea.png)

### Real behavior (Required)
public class UDAFArray {
    public static class State {
        List<Long> datas = new ArrayList<>();
        public int serializeLength() {
            String collect = datas.stream().map(String::valueOf).collect(Collectors.joining(","));
            return collect.getBytes(StandardCharsets.UTF_8).length;
        }
    }

    public State create() {
        return new State();
    }

    public void destroy(State state) {
    }

    public final void update(State state, Long val) {
        if (val != null) {
            state.datas.add(val);
        }
    }

    public void serialize(State state, java.nio.ByteBuffer buff) {
        String collect = state.datas.stream().map(String::valueOf).collect(Collectors.joining(","));
        buff.put(collect.getBytes(StandardCharsets.UTF_8));
    }

    public void merge(State state, java.nio.ByteBuffer buffer) {
        buffer.flip();
        byte[] bytes = new byte[buffer.limit()];
        buffer.get(bytes);
        String collect = new String(bytes,StandardCharsets.UTF_8);
        if(!collect.isEmpty()) {
            state.datas.addAll(Stream.of(collect.split(",")).map(Long::valueOf).collect(Collectors.toList()));
        }
    }

    public String finalize(State state) {
        return state.datas.stream().map(String::valueOf).collect(Collectors.joining(","));
    }
}

### StarRocks version (Required)
2.4.0-RC01 8c452bf

**Comment by ltylty** [comment]
这个问题解决了吗？  如果返回数据字节数不是固定的，应该如何处理serializeLength？

**Comment by gaoy121** [comment]
> 这个问题解决了吗？ 如果返回数据字节数不是固定的，应该如何处理serializeLength？

我的处理方式是 把长度和内容都写到buffer里，长度是用int写入的，所以serializeLength这里就固定写了4
![image](https://user-images.githubusercontent.com/55279192/223341677-072cbf5b-c096-4797-a039-8616aa5ff6e6.png)
![image](https://user-images.githubusercontent.com/55279192/223342096-46d3eeba-66f5-4816-ba19-5087ba825866.png)
