### ISSUE TITLE
[Docs] These SQL block code need be in unified format: one line for each configuration item, and indent

### ISSUE THREAD

**Issue by jaogoy** [StarRocks/starrocks#13467]
File: [/docs/using_starrocks/External_table.md](https://docs.starrocks.io/en-us/latest/using_starrocks/External_table)

see:
`CREATE EXTERNAL RESOURCE "iceberg0"`  and `CREATE EXTERNAL RESOURCE "iceberg1"`
shoule be same as `CREATE EXTERNAL RESOURCE "hive0"`

**Comment by evelynzhaojie** [comment]
fixed https://docs.starrocks.io/en-us/latest/data_source/External_table#deprecated-iceberg-external-table
