### ISSUE TITLE
[sqlancer] result set correctness

### ISSUE THREAD

**Issue by dulong41** [StarRocks/starrocks#13550]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

```sql
DROP DATABASE IF EXISTS w11;
CREATE DATABASE w11;
USE w11;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 VARCHAR(41) NOT NULL,c_0_1 DATETIME NOT NULL,c_0_2 BOOLEAN NOT NULL,c_0_3 VARCHAR(11) NOT NULL,c_0_4 DATE NOT NULL,c_0_5 TINYINT NOT NULL,c_0_6 DATETIME NOT NULL,c_0_7 BOOLEAN NOT NULL,c_0_8 DATE NOT NULL,c_0_9 DATE NOT NULL,c_0_10 BOOLEAN NOT NULL,c_0_11 BIGINT NOT NULL,c_0_12 ARRAY<STRING> NOT NULL,c_0_13 FLOAT NOT NULL, INDEX index1_c_0_0(`c_0_0`) USING BITMAP) PRIMARY KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5,c_0_6,c_0_7,c_0_8,c_0_9,c_0_10,c_0_11) PARTITION BY RANGE(c_0_1) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 949 day)) DISTRIBUTED BY HASH (c_0_7,c_0_4,c_0_0,c_0_5,c_0_8,c_0_9,c_0_2,c_0_10,c_0_11,c_0_1,c_0_6) BUCKETS 3 properties("replication_num"="3", "bloom_filter_columns"="c_0_11") ;
CREATE TABLE t1 (c_1_0 DATE NULL ) UNIQUE KEY (c_1_0) DISTRIBUTED BY HASH (c_1_0) BUCKETS 3 properties("replication_num"="3") ;
DELETE FROM t1 WHERE c_1_0 IS NULL;
INSERT INTO t1 VALUES ('2010-01-16'), ('2010-01-24'), (NULL);
INSERT INTO t1 VALUES ('2010-01-16'), ('2010-01-06');
INSERT INTO t1 VALUES ('2010-01-09');
INSERT INTO t1 VALUES ('2010-01-29'), ('2010-01-11'), ('2010-01-17'), ('2010-01-31');
CREATE MATERIALIZED VIEW v0 AS SELECT t0_138.c_0_2, t0_138.c_0_4, MIN(t0_138.c_0_0) , MAX(t0_138.c_0_1) , MIN(t0_138.c_0_3) , MIN(t0_138.c_0_5) , MAX(t0_138.c_0_6) , MIN(t0_138.c_0_7) , MIN(t0_138.c_0_8) , MIN(t0_138.c_0_9) , MIN(t0_138.c_0_10) , MAX(t0_138.c_0_11) , SUM(t0_138.c_0_13)  FROM t0 AS t0_138 GROUP BY t0_138.c_0_2, t0_138.c_0_4 ORDER BY t0_138.c_0_2, t0_138.c_0_4;
CREATE MATERIALIZED VIEW v0 AS SELECT t1_141.c_1_0 FROM t1 AS t1_141;
INSERT INTO t1 VALUES ('2010-01-14'), ('2010-01-10');
INSERT INTO t0 VALUES ('', '2010-01-26 08:00:14', true, '', '2010-01-28', 4, '2010-01-28 08:00:14', true, '2010-01-23', '2010-01-11', true, 0, ["", "vUL", "8", "AmL", "", "q16", "", "OxAL", "", "", "i", "4", "s", "Cl3w0bd4", ""], 0.07328808191089442);


```

### Expected behavior (Required)
all empty set

### Real behavior (Required)

MySQL [w11]> SELECT t0_144.c_0_0 FROM t0 AS t0_144;
+-------+
| c_0_0 |
+-------+
|       |
+-------+
1 row in set (0.00 sec)

MySQL [w11]> SELECT t0_144.c_0_0 FROM t0 AS t0_144 WHERE EXISTS (SELECT subt1.c_1_0 FROM  (SELECT t0_144.c_0_0, t0_144.c_0_1, t0_144.c_0_2, t0_144.c_0_3, t0_144.c_0_4, t0_144.c_0_5, t0_144.c_0_6, t0_144.c_0_7, t0_144.c_0_8, t0_144.c_0_9, t0_144.c_0_10, t0_144.c_0_11, t0_144.c_0_13 FROM t0 AS t0_144 WHERE  ( ADDDATE('1970-01-10 08:52:18', -1464752314)  ) <= ( t0_144.c_0_6 )  ORDER BY ((t0_144.c_0_0) IS NULL)) subt0 RIGHT SEMI JOIN (SELECT t1_145.c_1_0 FROM t1 AS t1_145) subt1 ON subt0.c_0_1 = subt1.c_1_0 AND subt0.c_0_1 = subt1.c_1_0 AND subt0.c_0_8 >= subt1.c_1_0 AND subt0.c_0_8 <= subt1.c_1_0 WHERE (NOT ( ( '1969-12-29' ) != ( t0_144.c_0_8 ) )))  UNION ALL SELECT t0_144.c_0_0 FROM t0 AS t0_144 WHERE (NOT (EXISTS (SELECT subt1.c_1_0 FROM  (SELECT t0_144.c_0_0, t0_144.c_0_1, t0_144.c_0_2, t0_144.c_0_3, t0_144.c_0_4, t0_144.c_0_5, t0_144.c_0_6, t0_144.c_0_7, t0_144.c_0_8, t0_144.c_0_9, t0_144.c_0_10, t0_144.c_0_11, t0_144.c_0_13 FROM t0 AS t0_144 WHERE  ( ADDDATE('1970-01-10 08:52:18', -1464752314)  ) <= ( t0_144.c_0_6 )  ORDER BY ((t0_144.c_0_0) IS NULL)) subt0 RIGHT SEMI JOIN (SELECT t1_145.c_1_0 FROM t1 AS t1_145) subt1 ON subt0.c_0_1 = subt1.c_1_0 AND subt0.c_0_1 = subt1.c_1_0 AND subt0.c_0_8 >= subt1.c_1_0 AND subt0.c_0_8 <= subt1.c_1_0 WHERE (NOT ( ( '1969-12-29' ) != ( t0_144.c_0_8 ) ))) )) UNION ALL SELECT t0_144.c_0_0 FROM t0 AS t0_144 WHERE ((EXISTS (SELECT subt1.c_1_0 FROM  (SELECT t0_144.c_0_0, t0_144.c_0_1, t0_144.c_0_2, t0_144.c_0_3, t0_144.c_0_4, t0_144.c_0_5, t0_144.c_0_6, t0_144.c_0_7, t0_144.c_0_8, t0_144.c_0_9, t0_144.c_0_10, t0_144.c_0_11, t0_144.c_0_13 FROM t0 AS t0_144 WHERE  ( ADDDATE('1970-01-10 08:52:18', -1464752314)  ) <= ( t0_144.c_0_6 )  ORDER BY ((t0_144.c_0_0) IS NULL)) subt0 RIGHT SEMI JOIN (SELECT t1_145.c_1_0 FROM t1 AS t1_145) subt1 ON subt0.c_0_1 = subt1.c_1_0 AND subt0.c_0_1 = subt1.c_1_0 AND subt0.c_0_8 >= subt1.c_1_0 AND subt0.c_0_8 <= subt1.c_1_0 WHERE (NOT ( ( '1969-12-29' ) != ( t0_144.c_0_8 ) ))) ) IS NULL);
Empty set (0.03 sec)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
MySQL [w11]> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.4-RELEASE 7b1a08e |
+----------------------------+
1 row in set (0.00 sec)

**Comment by liuyehcf** [comment]
Canno reproduce this problem with the specified version in single node cluster and 3 node cluster.

**Comment by liuyehcf** [comment]
Different client display different message when result is empty
* For mysql, `Empty set`
* For mycli, `0 rows`
