### ISSUE TITLE
Hive metadata synchronization in database level

### ISSUE THREAD

**Issue by JohnYan2017** [StarRocks/starrocks#1356]
目前starrocks使用的hdfs连接hive， 但是无法获取hive的元数据，hive外表的建立还需要手工写sql， 
能否使用hiveserver2连接， 类似于一些BI工具， 可以很多方便的管理hive元数据
同时starocks可以考虑基于hive元数据做可视化建表的支持，
这对于用户体验可能会更好些

**Comment by chaoyli** [comment]
Can I trouble you to describe the question in English? @JohnYan2017

**Comment by caneGuy** [comment]
cc @Ielihs @miomiocat
