### ISSUE TITLE
Official ARM Docker Image Request

### ISSUE THREAD

**Issue by tomtom215** [StarRocks/starrocks#13628]
## Feature request

Official Arm Docker Image & Docker Compose Documentation

**Is your feature request related to a problem? Please describe.**
Yes, I am unable to do local development on Apple M1/2 machines using the [official Docker](https://registry.hub.docker.com/r/starrocks/dev-env/tags)

**Describe the solution you'd like**
An official image for ARM architecture

**Describe alternatives you've considered**
Compiling it ourselves is not really efficient for local development and quick changes

**Comment by chaoyli** [comment]
@tomtom215 Good suggestions. I can discuss this with our team.

**Comment by hicder** [comment]
@chaoyli do you know what's stopping us from compiling for M1?  is it the custom vectorized code, or some libraries?

**Comment by fernee** [comment]
I had just built my own [arm docker image](https://hub.docker.com/repository/docker/fernee/star-rocks)

**Comment by imay** [comment]
https://hub.docker.com/r/starrocks/allin1-ubuntu
@tomtom215 Now all the images support ARM architecture, you can download as you need.

**Comment by tomtom215** [comment]
> https://hub.docker.com/r/starrocks/allin1-ubuntu
> 
> @tomtom215 Now all the images support ARM architecture, you can download as you need.

Thank you!!
