### ISSUE TITLE
show progress of a query

### ISSUE THREAD

**Issue by alanpaulkwan** [StarRocks/starrocks#13633]
It is common to have a query progress bar in most modern SQL languages. Please provide one! Clickhouse has this feature, Impala, DuckDB, etc. 

There's no way to tell how long a query is going to take, even via SHOW PROCESSLIST. It's kind of fund to watch :-)

**Comment by mofeiatwork** [comment]
Well, that's a feature of database client, ClickHouse has their own client so it could display the progress.

Right now we have no plan to develop our own client, but we're considering enhance the `show proc 'current_queries'` to display the progress of query.

**Comment by alanpaulkwan** [comment]
Is there some way I can access that metadata now? In Clickhouse it would be based on something like read_bytes

**Comment by vkingnew** [comment]
this is a good features. in deed many databases return the query time. postgresql support too

**Comment by mofeiatwork** [comment]
> 

An example:

```sql
MySQL root@127.0.0.1:ssb_100g> show proc '/current_queries';
+--------------------------------------+--------------+----------+------+-----------+--------------+----------------+----------+
| QueryId                              | ConnectionId | Database | User | ScanBytes | ProcessRows  | CPUCostSeconds | ExecTime |
+--------------------------------------+--------------+----------+------+-----------+--------------+----------------+----------+
| ea862856-7397-11ed-b351-00163e1f2aee | 102121       | ssb_100g | root | 5.42 MB   | 1420608 Rows | 93.92 Seconds  | 31987    |
+--------------------------------------+--------------+----------+------+-----------+--------------+----------------+----------+
```

**Comment by alanpaulkwan** [comment]
Would it be possible to estimate progress (even if inexact)?
