### ISSUE TITLE
DBT Integration - Roadmap to Production?

### ISSUE THREAD

**Issue by tomtom215** [StarRocks/starrocks#13630]
## Feature request
DBT Integration is crucial for us to  consider stackrocks for production use.

**Is your feature request related to a problem? Please describe.**

Opening an issue in this repo to draw attention to my issue over in this repo that doesn't seem to get many commits since the initial pushes
https://github.com/StarRocks/dbt-starrocks/issues/14

**Describe the solution you'd like**

Production grade dbt-starrocks adapter that keeps current with DBT core releases

**Describe alternatives you've considered**

Opening an issue and starring the starrocks DBT repo

**Additional context**

Please close as soon as someone picks up the issue in the dbt-starrocks repo to reduce duplicates.

Thank you!

**Comment by imay** [comment]
@tomtom215 It's already there. You can find StarRocks DBT connector in [dbt-connector](https://github.com/StarRocks/starrocks/tree/main/contrib/dbt-connector). 
You can test it and feel free to give us any feedback.

**Comment by tomtom215** [comment]
Thanks!
