### ISSUE TITLE
arraySort Function enhancement

### ISSUE THREAD

**Issue by liuzhimin1996** [StarRocks/starrocks#13662]
sr arraySort function is too simple
I want to sort the array by other dimensions
similar to clickhouse

For path analysis, visual inspection still lacks many functions. Take your time, one by one

**Comment by mofeiatwork** [comment]
Please describe the requirement by priority and in detail, so that we could schedule the development.

**Comment by liuzhimin1996** [comment]
OK, I try to describe my needs and examples in English
Usually, examples of arrays look like  ['logout','recharge','login','killboss']
But in fact, the business order cannot be excluded for specific strings
So I want to sort an array by another array
similar ['logout','recharge','login','killboss'] [4,2,1,3]
SELECT arraySort((x, y) -> y, ['logout','recharge','login','killboss'] [4,2,1,3) as res;
Output the sorting result of the first array according to the sorting of the second array
arraySort([func,] arr, …)
My example is that this writing method is actually clickhouse. I hope the official can seriously consider whether such a function can be available

**Comment by wangsimo0** [comment]
Hi, we will enhance this function in version 2.5. You can use the branch-2.5 or main.
