### ISSUE TITLE
need arrayCompact function similar to the clickhouse

### ISSUE THREAD

**Issue by liuzhimin1996** [StarRocks/starrocks#13663]
For path analysis，I need an array adjacent de duplication function, similar to the clickhouse arrayCompact function

**Comment by chaoyli** [comment]
@liuzhimin1996 Could you give an example or use case?

**Comment by wangsimo0** [comment]
@liuzhimin1996 https://docs.starrocks.io/en-us/latest/sql-reference/sql-functions/array-functions/array_distinct please try this one. we support it in version 2.2
