### ISSUE TITLE
cpu memory and network cost weights

### ISSUE THREAD

**Issue by to-be-snail** [StarRocks/starrocks#137]
> public static double getRealCost(CostEstimate costEstimate) {
        double cpuCostWeight = 0.5;
        double memoryCostWeight = 2;
        double networkCostWeight = 1.5;
        return costEstimate.getCpuCost() * cpuCostWeight +
                costEstimate.getMemoryCost() * memoryCostWeight +
                costEstimate.getNetworkCost() * networkCostWeight;
    }

why memory weights most in starrocks' cost model?

**Comment by Seaven** [comment]
In our test case, memory copy will take up most of the time. By the way, this is just experiences, do you have any good suggestions?
