### ISSUE TITLE
[sqlsmith] asan be crash

### ISSUE THREAD

**Issue by dulong41** [StarRocks/starrocks#13747]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

```sql
select  
  ref_0.cd_dep_college_count as c0, 
  ref_1.P_BRAND as c1, 
  ref_0.cd_credit_rating as c2, 
  ref_2.R_REGIONKEY as c3, 
  case when ref_0.cd_dep_count <= ref_0.cd_dep_count then ref_2.R_COMMENT else ref_2.R_COMMENT end
     as c4, 
  44 as c5, 
  ref_2.R_REGIONKEY as c6, 
  ref_2.R_COMMENT as c7, 
  ref_1.P_BRAND as c8, 
  instr(
    cast(ref_0.cd_credit_rating as VARCHAR),
    cast(ref_0.cd_gender as VARCHAR)) as c9, 
  substr(
    cast(ref_0.cd_gender as VARCHAR),
    cast(ref_1.P_SIZE as INT),
    cast(unix_timestamp() as INT)) as c10, 
  e() as c11, 
  ref_1.P_MFGR as c12, 
  ref_1.P_COMMENT as c13, 
  ref_1.P_PARTKEY as c14, 
  ref_1.P_NAME as c15, 
  ref_0.cd_demo_sk as c16, 
  ref_2.R_COMMENT as c17, 
  case when ref_1.P_TYPE = ref_0.cd_gender then ref_1.P_CONTAINER else ref_1.P_CONTAINER end
     as c18, 
  ref_2.R_COMMENT as c19, 
  ref_2.R_NAME as c20, 
  
    count(
      cast(ref_0.cd_demo_sk as INT)) over (partition by ref_2.R_NAME order by ref_0.cd_purchase_estimate) as c21, 
  98 as c22, 
  case when true then pi() else pi() end
     as c23, 
  ref_2.R_NAME as c24, 
  ref_1.P_PARTKEY as c25, 
  71 as c26, 
  ref_2.R_REGIONKEY as c27, 
  cast(nullif(cast(nullif(case when true then ref_0.cd_gender else ref_0.cd_gender end
        ,
      ref_2.R_COMMENT) as VARCHAR),
    ref_1.P_TYPE) as VARCHAR) as c28, 
  length(
    cast(case when true then ref_1.P_MFGR else ref_1.P_MFGR end
       as VARCHAR)) as c29, 
  cast(nullif(13,
    
      max(
        cast(ref_0.cd_dep_count as INT)) over (partition by ref_1.P_RETAILPRICE order by ref_1.P_CONTAINER)) as INT) as c30, 
  ref_2.R_REGIONKEY as c31, 
  ref_2.R_NAME as c32, 
  ref_1.P_SIZE as c33, 
  unix_timestamp() as c34, 
  ref_2.R_NAME as c35, 
  ref_1.P_NAME as c36, 
  pi() as c37, 
  ref_1.P_COMMENT as c38
from 
  sqlsmith.tpcds_100g_customer_demographics as ref_0
      left join sqlsmith.tpch_100g_part as ref_1
      on (ref_0.cd_demo_sk = ref_1.P_PARTKEY )
    left join sqlsmith.tpch_100g_region as ref_2
    on (ref_1.P_CONTAINER = ref_2.R_NAME )
where ref_1.P_COMMENT > ref_1.P_NAME
limit 70;
```

### Expected behavior (Required)
no error

### Real behavior (Required)
ERROR 1064 (HY000): rpc failed, host: 172.26.92.201'

be.out:
==7532==ERROR: AddressSanitizer: new-delete-type-mismatch on 0x6210006fcd00 in thread T273 (pip_wg_executor):
  object passed to delete has wrong type:
  size of the allocated type:   4090 bytes;
  size of the deallocated type: 4106 bytes.
    #0 0x8ca9277 in operator delete(void*, unsigned long) ../../.././libsanitizer/asan/asan_new_delete.cpp:172
    #1 0x8da224e in __gnu_cxx::new_allocator<unsigned char>::deallocate(unsigned char*, unsigned long) /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/ext/new_allocator.h:133
    #2 0x8e7f51a in starrocks::raw::RawAllocator<unsigned char, 16ul, std::allocator<unsigned char> >::deallocate(unsigned char*, unsigned long) /root/starrocks/be/src/util/raw_container.h:53
    #3 0x8e7a0db in std::allocator_traits<starrocks::raw::RawAllocator<unsigned char, 16ul, std::allocator<unsigned char> > >::deallocate(starrocks::raw::RawAllocator<unsigned char, 16ul, std::allocator<unsigned char> >&, unsigned char*, unsigned long) /usr/include/c++/10.3.0/bits/alloc_traits.h:341
    #4 0x8e74b87 in std::_Vector_base<unsigned char, starrocks::raw::RawAllocator<unsigned char, 16ul, std::allocator<unsigned char> > >::_M_deallocate(unsigned char*, unsigned long) /usr/include/c++/10.3.0/bits/stl_vector.h:354
    #5 0x8e6f401 in std::_Vector_base<unsigned char, starrocks::raw::RawAllocator<unsigned char, 16ul, std::allocator<unsigned char> > >::~_Vector_base() /usr/include/c++/10.3.0/bits/stl_vector.h:335
    #6 0x8e69c63 in std::vector<unsigned char, starrocks::raw::RawAllocator<unsigned char, 16ul, std::allocator<unsigned char> > >::~vector() /usr/include/c++/10.3.0/bits/stl_vector.h:683
    #7 0xce78835 in void starrocks::raw::make_room_pad16<unsigned char>(std::vector<unsigned char, std::allocator<unsigned char> >*, unsigned long) /root/starrocks/be/src/util/raw_container.h:159
    #8 0xce67b70 in deserialize /root/starrocks/be/src/serde/column_array_serde.cpp:168
    #9 0xce6163a in do_visit<unsigned char> /root/starrocks/be/src/serde/column_array_serde.cpp:658
    #10 0xce5e7e8 in visit /root/starrocks/be/src/column/column_visitor_adapter.h:105
    #11 0x8ea0470 in starrocks::vectorized::ColumnFactory<starrocks::vectorized::FixedLengthColumnBase<unsigned char>, starrocks::vectorized::FixedLengthColumn<unsigned char>, starrocks::vectorized::Column>::accept_mutable(starrocks::ColumnVisitorMutable*) /root/starrocks/be/src/column/column.h:439
    #12 0xce5ce89 in starrocks::serde::ColumnArraySerde::deserialize(unsigned char const*, starrocks::vectorized::Column*, bool, int) /root/starrocks/be/src/serde/column_array_serde.cpp:705
    #13 0xce5a5eb in deserialize /root/starrocks/be/src/serde/column_array_serde.cpp:385
    #14 0xce5c0c7 in do_visit /root/starrocks/be/src/serde/column_array_serde.cpp:623
    #15 0xce5e3e4 in visit /root/starrocks/be/src/column/column_visitor_adapter.h:143
    #16 0x9aac7c6 in starrocks::vectorized::ColumnFactory<starrocks::vectorized::Column, starrocks::vectorized::NullableColumn, starrocks::vectorized::Column>::accept_mutable(starrocks::ColumnVisitorMutable*) /root/starrocks/be/src/column/column.h:439
    #17 0xce5ce89 in starrocks::serde::ColumnArraySerde::deserialize(unsigned char const*, starrocks::vectorized::Column*, bool, int) /root/starrocks/be/src/serde/column_array_serde.cpp:705
    #18 0x10765672 in starrocks::serde::ProtobufChunkDeserializer::deserialize(std::basic_string_view<char, std::char_traits<char> >, long*) /root/starrocks/be/src/serde/protobuf_serde.cpp:227
    #19 0xed4e141 in starrocks::DataStreamRecvr::SenderQueue::_deserialize_chunk(starrocks::ChunkPB const&, starrocks::vectorized::Chunk*, starrocks::faststring*) /root/starrocks/be/src/runtime/sender_queue.cpp:91
    #20 0xed541aa in starrocks::DataStreamRecvr::PipelineSenderQueue::get_chunk(starrocks::vectorized::Chunk**, int) /root/starrocks/be/src/runtime/sender_queue.cpp:420
    #21 0xeb97864 in starrocks::DataStreamRecvr::get_chunk_for_pipeline(std::unique_ptr<starrocks::vectorized::Chunk, std::default_delete<starrocks::vectorized::Chunk> >*, int) /root/starrocks/be/src/runtime/data_stream_recvr.cpp:259
    #22 0xa18db37 in starrocks::pipeline::ExchangeSourceOperator::pull_chunk(starrocks::RuntimeState*) /root/starrocks/be/src/exec/pipeline/exchange/exchange_source_operator.cpp:35
    #23 0x91711cd in starrocks::pipeline::PipelineDriver::process(starrocks::RuntimeState*, int) /root/starrocks/be/src/exec/pipeline/pipeline_driver.cpp:226
    #24 0x1002bb47 in starrocks::pipeline::GlobalDriverExecutor::_worker_thread() /root/starrocks/be/src/exec/pipeline/pipeline_driver_executor.cpp:125
    #25 0x1002a531 in operator() /root/starrocks/be/src/exec/pipeline/pipeline_driver_executor.cpp:55
    #26 0x10032a13 in __invoke_impl<void, starrocks::pipeline::GlobalDriverExecutor::initialize(int)::<lambda()>&> /usr/include/c++/10.3.0/bits/invoke.h:60
    #27 0x10032112 in __invoke_r<void, starrocks::pipeline::GlobalDriverExecutor::initialize(int)::<lambda()>&> /usr/include/c++/10.3.0/bits/invoke.h:110
    #28 0x10031536 in _M_invoke /usr/include/c++/10.3.0/bits/std_function.h:291
    #29 0x8e2aeaf in std::function<void ()>::operator()() const /usr/include/c++/10.3.0/bits/std_function.h:622
    #30 0xf07bbc1 in starrocks::FunctionRunnable::run() /root/starrocks/be/src/util/threadpool.cpp:44
    #31 0xf0789c3 in starrocks::ThreadPool::dispatch_thread() /root/starrocks/be/src/util/threadpool.cpp:515
    #32 0xf0945cf in void std::__invoke_impl<void, void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>(std::__invoke_memfun_deref, void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&) /usr/include/c++/10.3.0/bits/invoke.h:73
    #33 0xf093f28 in std::__invoke_result<void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>::type std::__invoke<void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>(void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&) /usr/include/c++/10.3.0/bits/invoke.h:95
    #34 0xf09331f in void std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) /usr/include/c++/10.3.0/functional:416
    #35 0xf091c81 in void std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>::operator()<, void>() /usr/include/c++/10.3.0/functional:499
    #36 0xf08ece5 in void std::__invoke_impl<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>(std::__invoke_other, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&) /usr/include/c++/10.3.0/bits/invoke.h:60
    #37 0xf08c649 in std::enable_if<is_invocable_r_v<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>, void>::type std::__invoke_r<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>(std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&) /usr/include/c++/10.3.0/bits/invoke.h:110
    #38 0xf0886b2 in std::_Function_handler<void (), std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()> >::_M_invoke(std::_Any_data const&) /usr/include/c++/10.3.0/bits/std_function.h:291
    #39 0x8e2aeaf in std::function<void ()>::operator()() const /usr/include/c++/10.3.0/bits/std_function.h:622
    #40 0xf06304a in starrocks::Thread::supervise_thread(void*) /root/starrocks/be/src/util/thread.cpp:326
    #41 0x7f3092388ea4 in start_thread (/lib64/libpthread.so.0+0x7ea4)
    #42 0x7f3087a6eb0c in clone (/lib64/libc.so.6+0xfeb0c)

0x6210006fcd00 is located 0 bytes inside of 4090-byte region [0x6210006fcd00,0x6210006fdcfa)
allocated by thread T273 (pip_wg_executor) here:
    #0 0x8ca8457 in operator new(unsigned long) ../../.././libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x8e13468 in __gnu_cxx::new_allocator<unsigned char>::allocate(unsigned long, void const*) /usr/include/c++/10.3.0/ext/new_allocator.h:115
    #2 0x8e131c1 in std::allocator_traits<std::allocator<unsigned char> >::allocate(std::allocator<unsigned char>&, unsigned long) /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/alloc_traits.h:460
    #3 0x8e123cf in std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_M_allocate(unsigned long) /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/stl_vector.h:346
    #4 0x8e10c38 in std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_M_create_storage(unsigned long) /usr/include/c++/10.3.0/bits/stl_vector.h:361
    #5 0x8e0f926 in std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_Vector_base(unsigned long, std::allocator<unsigned char> const&) /usr/include/c++/10.3.0/bits/stl_vector.h:305
    #6 0x8e35f84 in std::vector<unsigned char, std::allocator<unsigned char> >::vector(unsigned long, unsigned char const&, std::allocator<unsigned char> const&) /usr/include/c++/10.3.0/bits/stl_vector.h:524
    #7 0x8feeb55 in starrocks::vectorized::FixedLengthColumnBase<unsigned char>::FixedLengthColumnBase(unsigned long, unsigned char) /root/starrocks/be/src/column/fixed_length_column_base.h:46
    #8 0x9aaa841 in starrocks::vectorized::ColumnFactory<starrocks::vectorized::FixedLengthColumnBase<unsigned char>, starrocks::vectorized::FixedLengthColumn<unsigned char>, starrocks::vectorized::Column>::ColumnFactory<unsigned long const&, unsigned char const&>(unsigned long const&, unsigned char const&) /root/starrocks/be/src/column/column.h:401
    #9 0x9aa9b9e in starrocks::vectorized::FixedLengthColumn<unsigned char>::FixedLengthColumn(unsigned long, unsigned char) /root/starrocks/be/src/column/fixed_length_column.h:17
    #10 0xfd83c5f in void __gnu_cxx::new_allocator<starrocks::vectorized::FixedLengthColumn<unsigned char> >::construct<starrocks::vectorized::FixedLengthColumn<unsigned char>, unsigned long&, unsigned char const&>(starrocks::vectorized::FixedLengthColumn<unsigned char>*, unsigned long&, unsigned char const&) /usr/include/c++/10.3.0/ext/new_allocator.h:150
    #11 0xfd816b0 in void std::allocator_traits<std::allocator<starrocks::vectorized::FixedLengthColumn<unsigned char> > >::construct<starrocks::vectorized::FixedLengthColumn<unsigned char>, unsigned long&, unsigned char const&>(std::allocator<starrocks::vectorized::FixedLengthColumn<unsigned char> >&, starrocks::vectorized::FixedLengthColumn<unsigned char>*, unsigned long&, unsigned char const&) /usr/include/c++/10.3.0/bits/alloc_traits.h:512
    #12 0xfd7ccd6 in std::_Sp_counted_ptr_inplace<starrocks::vectorized::FixedLengthColumn<unsigned char>, std::allocator<starrocks::vectorized::FixedLengthColumn<unsigned char> >, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<unsigned long&, unsigned char const&>(std::allocator<starrocks::vectorized::FixedLengthColumn<unsigned char> >, unsigned long&, unsigned char const&) /usr/include/c++/10.3.0/bits/shared_ptr_base.h:551
    #13 0xfd79c17 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<starrocks::vectorized::FixedLengthColumn<unsigned char>, std::allocator<starrocks::vectorized::FixedLengthColumn<unsigned char> >, unsigned long&, unsigned char const&>(starrocks::vectorized::FixedLengthColumn<unsigned char>*&, std::_Sp_alloc_shared_tag<std::allocator<starrocks::vectorized::FixedLengthColumn<unsigned char> > >, unsigned long&, unsigned char const&) /usr/include/c++/10.3.0/bits/shared_ptr_base.h:682
    #14 0xfd77991 in std::__shared_ptr<starrocks::vectorized::FixedLengthColumn<unsigned char>, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<starrocks::vectorized::FixedLengthColumn<unsigned char> >, unsigned long&, unsigned char const&>(std::_Sp_alloc_shared_tag<std::allocator<starrocks::vectorized::FixedLengthColumn<unsigned char> > >, unsigned long&, unsigned char const&) /usr/include/c++/10.3.0/bits/shared_ptr_base.h:1371
    #15 0xfd769bf in std::shared_ptr<starrocks::vectorized::FixedLengthColumn<unsigned char> >::shared_ptr<std::allocator<starrocks::vectorized::FixedLengthColumn<unsigned char> >, unsigned long&, unsigned char const&>(std::_Sp_alloc_shared_tag<std::allocator<starrocks::vectorized::FixedLengthColumn<unsigned char> > >, unsigned long&, unsigned char const&) /usr/include/c++/10.3.0/bits/shared_ptr.h:408
    #16 0xfd749fb in std::shared_ptr<starrocks::vectorized::FixedLengthColumn<unsigned char> > std::allocate_shared<starrocks::vectorized::FixedLengthColumn<unsigned char>, std::allocator<starrocks::vectorized::FixedLengthColumn<unsigned char> >, unsigned long&, unsigned char const&>(std::allocator<starrocks::vectorized::FixedLengthColumn<unsigned char> > const&, unsigned long&, unsigned char const&) /usr/include/c++/10.3.0/bits/shared_ptr.h:860
    #17 0xfd73827 in std::shared_ptr<starrocks::vectorized::FixedLengthColumn<unsigned char> > std::make_shared<starrocks::vectorized::FixedLengthColumn<unsigned char>, unsigned long&, unsigned char const&>(unsigned long&, unsigned char const&) /usr/include/c++/10.3.0/bits/shared_ptr.h:876
    #18 0xfd70faa in std::shared_ptr<starrocks::vectorized::FixedLengthColumn<unsigned char> > starrocks::vectorized::ColumnFactory<starrocks::vectorized::FixedLengthColumnBase<unsigned char>, starrocks::vectorized::FixedLengthColumn<unsigned char>, starrocks::vectorized::Column>::create<unsigned long&, unsigned char const&>(unsigned long&, unsigned char const&) /root/starrocks/be/src/column/column.h:410
    #19 0xfd6b184 in starrocks::vectorized::ColumnHelper::create_column(starrocks::TypeDescriptor const&, bool, bool, unsigned long) /root/starrocks/be/src/column/column_helper.cpp:280
    #20 0x107652a5 in starrocks::serde::ProtobufChunkDeserializer::deserialize(std::basic_string_view<char, std::char_traits<char> >, long*) /root/starrocks/be/src/serde/protobuf_serde.cpp:217
    #21 0xed4e141 in starrocks::DataStreamRecvr::SenderQueue::_deserialize_chunk(starrocks::ChunkPB const&, starrocks::vectorized::Chunk*, starrocks::faststring*) /root/starrocks/be/src/runtime/sender_queue.cpp:91
    #22 0xed541aa in starrocks::DataStreamRecvr::PipelineSenderQueue::get_chunk(starrocks::vectorized::Chunk**, int) /root/starrocks/be/src/runtime/sender_queue.cpp:420
    #23 0xeb97864 in starrocks::DataStreamRecvr::get_chunk_for_pipeline(std::unique_ptr<starrocks::vectorized::Chunk, std::default_delete<starrocks::vectorized::Chunk> >*, int) /root/starrocks/be/src/runtime/data_stream_recvr.cpp:259
    #24 0xa18db37 in starrocks::pipeline::ExchangeSourceOperator::pull_chunk(starrocks::RuntimeState*) /root/starrocks/be/src/exec/pipeline/exchange/exchange_source_operator.cpp:35
    #25 0x91711cd in starrocks::pipeline::PipelineDriver::process(starrocks::RuntimeState*, int) /root/starrocks/be/src/exec/pipeline/pipeline_driver.cpp:226
    #26 0x1002bb47 in starrocks::pipeline::GlobalDriverExecutor::_worker_thread() /root/starrocks/be/src/exec/pipeline/pipeline_driver_executor.cpp:125
    #27 0x1002a531 in operator() /root/starrocks/be/src/exec/pipeline/pipeline_driver_executor.cpp:55
    #28 0x10032a13 in __invoke_impl<void, starrocks::pipeline::GlobalDriverExecutor::initialize(int)::<lambda()>&> /usr/include/c++/10.3.0/bits/invoke.h:60
    #29 0x10032112 in __invoke_r<void, starrocks::pipeline::GlobalDriverExecutor::initialize(int)::<lambda()>&> /usr/include/c++/10.3.0/bits/invoke.h:110

Thread T273 (pip_wg_executor) created by T0 here:
    #0 0x8c52152 in __interceptor_pthread_create ../../.././libsanitizer/asan/asan_interceptors.cpp:214
    #1 0xf06249e in starrocks::Thread::start_thread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()> const&, unsigned long, scoped_refptr<starrocks::Thread>*) /root/starrocks/be/src/util/thread.cpp:281
    #2 0xf07f1c2 in starrocks::Status starrocks::Thread::create<void (starrocks::ThreadPool::*)(), starrocks::ThreadPool*>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void (starrocks::ThreadPool::* const&)(), starrocks::ThreadPool* const&, scoped_refptr<starrocks::Thread>*) /root/starrocks/be/src/util/thread.h:55
    #3 0xf079c61 in starrocks::ThreadPool::create_thread() /root/starrocks/be/src/util/threadpool.cpp:566
    #4 0xf0767b1 in starrocks::ThreadPool::do_submit(std::shared_ptr<starrocks::Runnable>, starrocks::ThreadPoolToken*, starrocks::ThreadPool::Priority) /root/starrocks/be/src/util/threadpool.cpp:415
    #5 0xf07546d in starrocks::ThreadPool::submit(std::shared_ptr<starrocks::Runnable>, starrocks::ThreadPool::Priority) /root/starrocks/be/src/util/threadpool.cpp:332
    #6 0xf07560e in starrocks::ThreadPool::submit_func(std::function<void ()>, starrocks::ThreadPool::Priority) /root/starrocks/be/src/util/threadpool.cpp:336
    #7 0x1002a97a in starrocks::pipeline::GlobalDriverExecutor::initialize(int) /root/starrocks/be/src/exec/pipeline/pipeline_driver_executor.cpp:55
    #8 0xeaabcc3 in starrocks::ExecEnv::_init(std::vector<starrocks::StorePath, std::allocator<starrocks::StorePath> > const&) /root/starrocks/be/src/runtime/exec_env.cpp:194
    #9 0xeaa9aab in starrocks::ExecEnv::init(starrocks::ExecEnv*, std::vector<starrocks::StorePath, std::allocator<starrocks::StorePath> > const&) /root/starrocks/be/src/runtime/exec_env.cpp:126
    #10 0x8ce8f90 in main /root/starrocks/be/src/service/starrocks_main.cpp:278
    #11 0x7f3087992554 in __libc_start_main (/lib64/libc.so.6+0x22554)

SUMMARY: AddressSanitizer: new-delete-type-mismatch ../../.././libsanitizer/asan/asan_new_delete.cpp:172 in operator delete(void*, unsigned long)
==7532==HINT: if you don't care about these errors you may set ASAN_OPTIONS=new_delete_type_mismatch=0
==7532==ABORTING

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+-------------------------+
| current_version()       |
+-------------------------+
| BRANCH-2.5-ASAN 7d36d91 |
+-------------------------+
1 row in set (0.01 sec)

**Comment by dulong41** [comment]
another sql can trigger crash:

```sql
select  
  4 as c0, 
  case when true then ref_2.d_current_year else ref_2.d_current_year end
     as c1, 
  ref_0.d_dow as c2, 
  ref_2.d_moy as c3, 
  ref_1.c1 as c4, 
  
    sum(
      cast(cast(null as DOUBLE) as DOUBLE)) over (partition by ref_2.d_following_holiday order by ref_0.d_date_sk) as c5, 
  ref_1.c2 as c6, 
  ref_2.d_following_holiday as c7, 
  ref_2.d_following_holiday as c8, 
  ref_2.d_same_day_ly as c9, 
  ref_0.d_current_day as c10, 
  cast(coalesce(case when ref_2.d_current_quarter >= ref_0.d_current_day then ref_2.d_current_quarter else ref_2.d_current_quarter end
      ,
    ref_2.d_date_id) as VARCHAR) as c11, 
  ref_1.c2 as c12, 
  ref_0.d_date as c13, 
  ref_0.d_dow as c14, 
  ref_2.d_weekend as c15, 
  e() as c16, 
  
    sum(
      cast(cast(nullif(cast(null as DOUBLE),
        cast(null as DOUBLE)) as DOUBLE) as DOUBLE)) over (partition by ref_0.d_last_dom order by ref_1.c2) as c17
from 
  sqlsmith.tpcds_100g_date_dim as ref_0
      right join sqlsmith.t1 as ref_1
      on (ref_0.d_quarter_seq = ref_1.c1 )
    inner join sqlsmith.tpcds_100g_date_dim as ref_2
    on (ref_1.c1 = ref_2.d_date_sk )
where (ref_2.d_quarter_seq > ref_2.d_month_seq) 
  and (ref_2.d_date_id < ref_0.d_current_month)
limit 76;
```

**Comment by fzhedu** [comment]
https://github.com/StarRocks/starrocks/pull/13722, after cherry-pick, pls check it again.
