### ISSUE TITLE
Enhance show materialized view

### ISSUE THREAD

**Issue by mofeiatwork** [StarRocks/starrocks#13929]
## Enhancement

Add several fields in `show materialized view` command:
1. `last_refresh_time`: to measure the freshness of this materialized view
2. `last_refresh_duration`: to measure the cost of refresh
3. `last_refresh_rows`: to measure the cost of refresh
4. `is_active`: whether the MV is active
5. `inactive_reason`: why this MV is not active? 

Current result:
![image](https://user-images.githubusercontent.com/96611012/203491579-bf797abf-b1e3-47fd-b13d-643902ac4c22.png)

**Comment by Astralidea** [comment]
In my personal opinion, 1 and 2 are best placed in the Task framework, which can be called last_schdule_time and last_schdule_duration, and 3 may be placed in the show MV.

**Comment by 241600489** [comment]
can I pick ?

**Comment by mofeiatwork** [comment]
> 

Sure, welcome for contribution. 

You could give a basic proposal for this feature, and it needs to be confirmed by our product team. This proposal should includes how to use this feature, and the implementation sketch.

After that, I think we could discuss further on the code.
