### ISSUE TITLE
stream-load and flink-connector-sink add protobuf serialization

### ISSUE THREAD

**Issue by zhangzaixuan** [StarRocks/starrocks#13943]
## Enhancement
stream-load  and flink-connector based on csv or json,add method of protobuf enhanced stream-load and memory pressure

**Comment by jaogoy** [comment]
We are designing loading protobuf data from Kafka.
And I want to ask you that why will you load protobuf data in stream-load, how do you manage the schema of your data, why don't you maintain the protobuf data in hive system?
