### ISSUE TITLE
[P1] LAST_VALUE() 窗口函数实际结果正确性和文档描述不一致

### ISSUE THREAD

**Issue by TTTTzz** [StarRocks/starrocks#13998]
![企业微信截图_16692594067772](https://user-images.githubusercontent.com/113418424/203685894-d4b70f86-d041-4d0b-b66d-d68c29a73fe1.png)

![企业微信截图_16692594512758](https://user-images.githubusercontent.com/113418424/203685912-85c29343-1b4a-4608-9043-efbddf6377c8.png)
greeting值应该是Guten tag Guten tag Hej Hej Hi Hi

**Comment by TTTTzz** [comment]
CREATE TABLE mail_merge
(
    name STRING ,
    country STRING,
    greeting STRING
)
AGGREGATE KEY(name, country, greeting)
DISTRIBUTED BY HASH(name) BUCKETS 10
PROPERTIES("replication_num" = "1");

insert into mail_merge values ("Pete","USA","Hello"),("John","USA","Hi"),("Boris","Germany","Guten tag"),("Michael","Germany","Guten morgen"),("Bjorn","Sweden","Hej"),("Mats","Sweden","Tja")

**Comment by TTTTzz** [comment]
select * from mail_merge;

select country, name,
    last_value(greeting)
        over (
            partition by country
            order by name, greeting
        ) as greeting
from mail_merge;

**Comment by TTTTzz** [comment]
目前所有版本结果都有问题

**Comment by liuyehcf** [comment]
the default window definition of `last_value/first_value` is `ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW`

So it is the right answer according to your cases.

If you want to get the result `Guten tag Guten tag Hej Hej Hi Hi`, you should specify the window to `ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING`
