### ISSUE TITLE
Delete date very slow

### ISSUE THREAD

**Issue by xltxb** [StarRocks/starrocks#14009]
### Steps to reproduce the behavior (Required)
**create table statement:**
```
CREATE TABLE `tbl_report_sub_member` (
  `report_time` largeint(40) NOT NULL COMMENT "统计日期",
  `report_type` int(11) NOT NULL,
  `id` varchar(65533) NOT NULL COMMENT "id",
  `uid` largeint(40) NOT NULL COMMENT "用户id",
  `created_at` int(11) NOT NULL COMMENT "注册时间",
  `username` varchar(65533) NOT NULL COMMENT "用户名称",
  `tester` varchar(65533) NOT NULL DEFAULT "1" COMMENT "1:正式0:测试",
  `prefix` varchar(65533) NOT NULL COMMENT "前缀"
) ENGINE=OLAP 
PRIMARY KEY(`report_time`, `report_type`, `id`)
COMMENT "会员子报表"
DISTRIBUTED BY HASH(`report_time`, `report_type`, `id`) BUCKETS 4 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);
```

**execute statement：**
`delete from  report.tbl_report_sub_member where id in('ace6688|ace6688|2022-11-19 00:00:00|5|jl8','ace6688|acedl01|2022-11-19 00:00:00|5|jl8','reilly2|reilly2|2022-11-19 00:00:00|5|jl8','reilly1|reilly2|2022-11-19 00:00:00|5|jl8','xiaocao01|xiaocao30|2022-11-19 00:00:00|5|jl8','xiaocao01|xiaocao01|2022-11-19 00:00:00|5|jl8','lws1001|lws1010|2022-11-19 00:00:00|5|jl8','lws1001|lws1001|2022-11-19 00:00:00|5|jl8','mango10270|mango10270|2022-11-19 00:00:00|5|jl8','mango10270|mango10272|2022-11-19 00:00:00|5|jl8','mango10270|mango10273|2022-11-19 00:00:00|5|jl8','wenda001|wenda001|2022-11-19 00:00:00|5|jl8','acedl01|acedl01|2022-11-19 00:00:00|5|jl8','lws1010|lws1010|2022-11-19 00:00:00|5|jl8','mango10272|mango10273|2022-11-19 00:00:00|5|jl8','mango10272|mango10272|2022-11-19 00:00:00|5|jl8','jy8vip|guoguo0|2022-11-19 00:00:00|5|jl8','jy8vip|wenda001|2022-11-19 00:00:00|5|jl8','mango10273|mango10273|2022-11-19 00:00:00|5|jl8','guoguo0|guoguo0|2022-11-19 00:00:00|5|jl8','xiaocao30|xiaocao30|2022-11-19 00:00:00|5|jl8')`

### Expected behavior (Required)
fastest to delete data  from table (primary key)

### Real behavior (Required)
`ResourceGroup=default_wg|Catalog=default_catalog|Db=jl8|State=OK|ErrorCode=|Time=2891|ScanBytes=0|ScanRows=0|ReturnRows=0|CpuCostNs=0|MemCostBytes=0|StmtId=22348146|QueryId=b625a115-6976-11ed-a650-005056b7a777|IsQuery=false|feIp=10.8.21.230|Stmt=delete from  report.tbl_report_sub_member where id in('ace6688|ace6688|2022-11-19 00:00:00|5|jl8','ace6688|acedl01|2022-11-19 00:00:00|5|jl8','reilly2|reilly2|2022-11-19 00:00:00|5|jl8','reilly1|reilly2|2022-11-19 00:00:00|5|jl8','xiaocao01|xiaocao30|2022-11-19 00:00:00|5|jl8','xiaocao01|xiaocao01|2022-11-19 00:00:00|5|jl8','lws1001|lws1010|2022-11-19 00:00:00|5|jl8','lws1001|lws1001|2022-11-19 00:00:00|5|jl8','mango10270|mango10270|2022-11-19 00:00:00|5|jl8','mango10270|mango10272|2022-11-19 00:00:00|5|jl8','mango10270|mango10273|2022-11-19 00:00:00|5|jl8','wenda001|wenda001|2022-11-19 00:00:00|5|jl8','acedl01|acedl01|2022-11-19 00:00:00|5|jl8','lws1010|lws1010|2022-11-19 00:00:00|5|jl8','mango10272|mango10273|2022-11-19 00:00:00|5|jl8','mango10272|mango10272|2022-11-19 00:00:00|5|jl8','jy8vip|guoguo0|2022-11-19 00:00:00|5|jl8','jy8vip|wenda001|2022-11-19 00:00:00|5|jl8','mango10273|mango10273|2022-11-19 00:00:00|5|jl8','guoguo0|guoguo0|2022-11-19 00:00:00|5|jl8','xiaocao30|xiaocao30|2022-11-19 00:00:00|5|jl8')|Digest=|PlanCpuCost=1675.6166613447785|PlanMemCost=0.0`
### StarRocks version (Required)
select current_version();
+-------------------+
| current_version() |
+-------------------+
| 2.4.0 c0fa2bb     |
+-------------------+

**Comment by decster** [comment]
could you execute 
```
select report_time, report_type, id from report.tbl_report_sub_member where id in('ace6688|ace6688|2022-11-19 00:00:00|5|jl8','ace6688|acedl01|2022-11-19 00:00:00|5|jl8','reilly2|reilly2|2022-11-19 00:00:00|5|jl8','reilly1|reilly2|2022-11-19 00:00:00|5|jl8','xiaocao01|xiaocao30|2022-11-19 00:00:00|5|jl8','xiaocao01|xiaocao01|2022-11-19 00:00:00|5|jl8','lws1001|lws1010|2022-11-19 00:00:00|5|jl8','lws1001|lws1001|2022-11-19 00:00:00|5|jl8','mango10270|mango10270|2022-11-19 00:00:00|5|jl8','mango10270|mango10272|2022-11-19 00:00:00|5|jl8','mango10270|mango10273|2022-11-19 00:00:00|5|jl8','wenda001|wenda001|2022-11-19 00:00:00|5|jl8','acedl01|acedl01|2022-11-19 00:00:00|5|jl8','lws1010|lws1010|2022-11-19 00:00:00|5|jl8','mango10272|mango10273|2022-11-19 00:00:00|5|jl8','mango10272|mango10272|2022-11-19 00:00:00|5|jl8','jy8vip|guoguo0|2022-11-19 00:00:00|5|jl8','jy8vip|wenda001|2022-11-19 00:00:00|5|jl8','mango10273|mango10273|2022-11-19 00:00:00|5|jl8','guoguo0|guoguo0|2022-11-19 00:00:00|5|jl8','xiaocao30|xiaocao30|2022-11-19 00:00:00|5|jl8')
```
see if it executes faster? also provide query profile for both queries

**Comment by decster** [comment]
```
mysql> CREATE TABLE `tbl_report_sub_member` (
    ->   `report_time` largeint(40) NOT NULL COMMENT "统计日期",
    ->   `report_type` int(11) NOT NULL,
    ->   `id` varchar(65533) NOT NULL COMMENT "id",
    ->   `uid` largeint(40) NOT NULL COMMENT "用户id",
    ->   `created_at` int(11) NOT NULL COMMENT "注册时间",
    ->   `username` varchar(65533) NOT NULL COMMENT "用户名称",
    ->   `tester` varchar(65533) NOT NULL DEFAULT "1" COMMENT "1:正式0:测试",
    ->   `prefix` varchar(65533) NOT NULL COMMENT "前缀"
    -> ) ENGINE=OLAP 
    -> PRIMARY KEY(`report_time`, `report_type`, `id`)
    -> COMMENT "会员子报表"
    -> DISTRIBUTED BY HASH(`report_time`, `report_type`, `id`) BUCKETS 4 
    -> PROPERTIES (
    -> "replication_num" = "1",
    -> "in_memory" = "false",
    -> "storage_format" = "DEFAULT",
    -> "enable_persistent_index" = "false"
    -> );
Query OK, 0 rows affected (0.05 sec)

mysql> delete from tbl_report_sub_member where id in('ace6688|ace6688|2022-11-19 00:00:00|5|jl8','ace6688|acedl01|2022-11-19 00:00:00|5|jl8','reilly2|reilly2|2022-11-19 00:00:00|5|jl8','reilly1|reilly2|2022-11-19 00:00:00|5|jl8','xiaocao01|xiaocao30|2022-11-19 00:00:00|5|jl8','xiaocao01|xiaocao01|2022-11-19 00:00:00|5|jl8','lws1001|lws1010|2022-11-19 00:00:00|5|jl8','lws1001|lws1001|2022-11-19 00:00:00|5|jl8','mango10270|mango10270|2022-11-19 00:00:00|5|jl8','mango10270|mango10272|2022-11-19 00:00:00|5|jl8','mango10270|mango10273|2022-11-19 00:00:00|5|jl8','wenda001|wenda001|2022-11-19 00:00:00|5|jl8','acedl01|acedl01|2022-11-19 00:00:00|5|jl8','lws1010|lws1010|2022-11-19 00:00:00|5|jl8','mango10272|mango10273|2022-11-19 00:00:00|5|jl8','mango10272|mango10272|2022-11-19 00:00:00|5|jl8','jy8vip|guoguo0|2022-11-19 00:00:00|5|jl8','jy8vip|wenda001|2022-11-19 00:00:00|5|jl8','mango10273|mango10273|2022-11-19 00:00:00|5|jl8','guoguo0|guoguo0|2022-11-19 00:00:00|5|jl8','xiaocao30|xiaocao30|2022-11-19 00:00:00|5|jl8')
    -> ;
Query OK, 0 rows affected (0.30 sec)
```

Cannot reproduce here, need more information

**Comment by xltxb** [comment]
> where
select report_time, report_type, id from report.tbl_report_sub_member where id in('ace6688|ace6688|2022-11-19 00:00:00|5|jl8','ace6688|acedl01|2022-11-19 00:00:00|5|jl8','reilly2|reilly2|2022-11-19 00:00:00|5|jl8','reilly1|reilly2|2022-11-19 00:00:00|5|jl8','xiaocao01|xiaocao30|2022-11-19 00:00:00|5|jl8','xiaocao01|xiaocao01|2022-11-19 00:00:00|5|jl8','lws1001|lws1010|2022-11-19 00:00:00|5|jl8','lws1001|lws1001|2022-11-19 00:00:00|5|jl8','mango10270|mango10270|2022-11-19 00:00:00|5|jl8','mango10270|mango10272|2022-11-19 00:00:00|5|jl8','mango10270|mango10273|2022-11-19 00:00:00|5|jl8','wenda001|wenda001|2022-11-19 00:00:00|5|jl8','acedl01|acedl01|2022-11-19 00:00:00|5|jl8','lws1010|lws1010|2022-11-19 00:00:00|5|jl8','mango10272|mango10273|2022-11-19 00:00:00|5|jl8','mango10272|mango10272|2022-11-19 00:00:00|5|jl8','jy8vip|guoguo0|2022-11-19 00:00:00|5|jl8','jy8vip|wenda001|2022-11-19 00:00:00|5|jl8','mango10273|mango10273|2022-11-19 00:00:00|5|jl8','guoguo0|guoguo0|2022-11-19 00:00:00|5|jl8','xiaocao30|xiaocao30|2022-11-19 00:00:00|5|jl8');

**Comment by xltxb** [comment]
> could you execute
> 
> ```
> select report_time, report_type, id from report.tbl_report_sub_member where id in('ace6688|ace6688|2022-11-19 00:00:00|5|jl8','ace6688|acedl01|2022-11-19 00:00:00|5|jl8','reilly2|reilly2|2022-11-19 00:00:00|5|jl8','reilly1|reilly2|2022-11-19 00:00:00|5|jl8','xiaocao01|xiaocao30|2022-11-19 00:00:00|5|jl8','xiaocao01|xiaocao01|2022-11-19 00:00:00|5|jl8','lws1001|lws1010|2022-11-19 00:00:00|5|jl8','lws1001|lws1001|2022-11-19 00:00:00|5|jl8','mango10270|mango10270|2022-11-19 00:00:00|5|jl8','mango10270|mango10272|2022-11-19 00:00:00|5|jl8','mango10270|mango10273|2022-11-19 00:00:00|5|jl8','wenda001|wenda001|2022-11-19 00:00:00|5|jl8','acedl01|acedl01|2022-11-19 00:00:00|5|jl8','lws1010|lws1010|2022-11-19 00:00:00|5|jl8','mango10272|mango10273|2022-11-19 00:00:00|5|jl8','mango10272|mango10272|2022-11-19 00:00:00|5|jl8','jy8vip|guoguo0|2022-11-19 00:00:00|5|jl8','jy8vip|wenda001|2022-11-19 00:00:00|5|jl8','mango10273|mango10273|2022-11-19 00:00:00|5|jl8','guoguo0|guoguo0|2022-11-19 00:00:00|5|jl8','xiaocao30|xiaocao30|2022-11-19 00:00:00|5|jl8')
> ```
> 
> see if it executes faster? also provide query profile for both queries



> could you execute
> 
> ```
> select report_time, report_type, id from report.tbl_report_sub_member where id in('ace6688|ace6688|2022-11-19 00:00:00|5|jl8','ace6688|acedl01|2022-11-19 00:00:00|5|jl8','reilly2|reilly2|2022-11-19 00:00:00|5|jl8','reilly1|reilly2|2022-11-19 00:00:00|5|jl8','xiaocao01|xiaocao30|2022-11-19 00:00:00|5|jl8','xiaocao01|xiaocao01|2022-11-19 00:00:00|5|jl8','lws1001|lws1010|2022-11-19 00:00:00|5|jl8','lws1001|lws1001|2022-11-19 00:00:00|5|jl8','mango10270|mango10270|2022-11-19 00:00:00|5|jl8','mango10270|mango10272|2022-11-19 00:00:00|5|jl8','mango10270|mango10273|2022-11-19 00:00:00|5|jl8','wenda001|wenda001|2022-11-19 00:00:00|5|jl8','acedl01|acedl01|2022-11-19 00:00:00|5|jl8','lws1010|lws1010|2022-11-19 00:00:00|5|jl8','mango10272|mango10273|2022-11-19 00:00:00|5|jl8','mango10272|mango10272|2022-11-19 00:00:00|5|jl8','jy8vip|guoguo0|2022-11-19 00:00:00|5|jl8','jy8vip|wenda001|2022-11-19 00:00:00|5|jl8','mango10273|mango10273|2022-11-19 00:00:00|5|jl8','guoguo0|guoguo0|2022-11-19 00:00:00|5|jl8','xiaocao30|xiaocao30|2022-11-19 00:00:00|5|jl8')
> ```
> 
> see if it executes faster? also provide query profile for both queries

select report_time, report_type, id from report.tbl_report_sub_member where id in('ace6688|ace6688|2022-11-19 00:00:00|5|jl8','ace6688|acedl01|2022-11-19 00:00:00|5|jl8','reilly2|reilly2|2022-11-19 00:00:00|5|jl8','reilly1|reilly2|2022-11-19 00:00:00|5|jl8','xiaocao01|xiaocao30|2022-11-19 00:00:00|5|jl8','xiaocao01|xiaocao01|2022-11-19 00:00:00|5|jl8','lws1001|lws1010|2022-11-19 00:00:00|5|jl8','lws1001|lws1001|2022-11-19 00:00:00|5|jl8','mango10270|mango10270|2022-11-19 00:00:00|5|jl8','mango10270|mango10272|2022-11-19 00:00:00|5|jl8','mango10270|mango10273|2022-11-19 00:00:00|5|jl8','wenda001|wenda001|2022-11-19 00:00:00|5|jl8','acedl01|acedl01|2022-11-19 00:00:00|5|jl8','lws1010|lws1010|2022-11-19 00:00:00|5|jl8','mango10272|mango10273|2022-11-19 00:00:00|5|jl8','mango10272|mango10272|2022-11-19 00:00:00|5|jl8','jy8vip|guoguo0|2022-11-19 00:00:00|5|jl8','jy8vip|wenda001|2022-11-19 00:00:00|5|jl8','mango10273|mango10273|2022-11-19 00:00:00|5|jl8','guoguo0|guoguo0|2022-11-19 00:00:00|5|jl8','xiaocao30|xiaocao30|2022-11-19 00:00:00|5|jl8');

**Comment by xltxb** [comment]
> could you execute
> 
> ```
> select report_time, report_type, id from report.tbl_report_sub_member where id in('ace6688|ace6688|2022-11-19 00:00:00|5|jl8','ace6688|acedl01|2022-11-19 00:00:00|5|jl8','reilly2|reilly2|2022-11-19 00:00:00|5|jl8','reilly1|reilly2|2022-11-19 00:00:00|5|jl8','xiaocao01|xiaocao30|2022-11-19 00:00:00|5|jl8','xiaocao01|xiaocao01|2022-11-19 00:00:00|5|jl8','lws1001|lws1010|2022-11-19 00:00:00|5|jl8','lws1001|lws1001|2022-11-19 00:00:00|5|jl8','mango10270|mango10270|2022-11-19 00:00:00|5|jl8','mango10270|mango10272|2022-11-19 00:00:00|5|jl8','mango10270|mango10273|2022-11-19 00:00:00|5|jl8','wenda001|wenda001|2022-11-19 00:00:00|5|jl8','acedl01|acedl01|2022-11-19 00:00:00|5|jl8','lws1010|lws1010|2022-11-19 00:00:00|5|jl8','mango10272|mango10273|2022-11-19 00:00:00|5|jl8','mango10272|mango10272|2022-11-19 00:00:00|5|jl8','jy8vip|guoguo0|2022-11-19 00:00:00|5|jl8','jy8vip|wenda001|2022-11-19 00:00:00|5|jl8','mango10273|mango10273|2022-11-19 00:00:00|5|jl8','guoguo0|guoguo0|2022-11-19 00:00:00|5|jl8','xiaocao30|xiaocao30|2022-11-19 00:00:00|5|jl8')
> ```
> 
> see if it executes faster? also provide query profile for both queries

<img width="1731" alt="image" src="https://user-images.githubusercontent.com/5130103/203897940-0aa479dc-e57a-4da4-9e99-17c6d6799e52.png">

**Comment by xltxb** [comment]
> 
Can u make same test data in that table ?
there is almost 40K data in the table.

<img width="711" alt="image" src="https://user-images.githubusercontent.com/5130103/203898051-33f0adaa-6c04-4f0d-864a-1a1c79496f5f.png">

**Comment by jaogoy** [comment]
@decster There is no index for `id` column, So, in a big table, Is it fast to find these string values without index? Is there any string dictionary to accelerate the search?

**Comment by decster** [comment]
```
mysql> select count(*) from tbl_report_sub_member;
+----------+
| count(*) |
+----------+
|  1048576 |
+----------+
1 row in set (0.01 sec)

mysql> delete from tbl_report_sub_member where id in('ace6688|ace6688|2022-11-19 00:00:00|5|jl8','ace6688|acedl01|2022-11-19 00:00:00|5|jl8','reilly2|reilly2|2022-11-19 00:00:00|5|jl8','reilly1|reilly2|2022-11-19 00:00:00|5|jl8','xiaocao01|xiaocao30|2022-11-19 00:00:00|5|jl8','xiaocao01|xiaocao01|2022-11-19 00:00:00|5|jl8','lws1001|lws1010|2022-11-19 00:00:00|5|jl8','lws1001|lws1001|2022-11-19 00:00:00|5|jl8','mango10270|mango10270|2022-11-19 00:00:00|5|jl8','mango10270|mango10272|2022-11-19 00:00:00|5|jl8','mango10270|mango10273|2022-11-19 00:00:00|5|jl8','wenda001|wenda001|2022-11-19 00:00:00|5|jl8','acedl01|acedl01|2022-11-19 00:00:00|5|jl8','lws1010|lws1010|2022-11-19 00:00:00|5|jl8','mango10272|mango10273|2022-11-19 00:00:00|5|jl8','mango10272|mango10272|2022-11-19 00:00:00|5|jl8','jy8vip|guoguo0|2022-11-19 00:00:00|5|jl8','jy8vip|wenda001|2022-11-19 00:00:00|5|jl8','mango10273|mango10273|2022-11-19 00:00:00|5|jl8','guoguo0|guoguo0|2022-11-19 00:00:00|5|jl8','xiaocao30|xiaocao30|2022-11-19 00:00:00|5|jl8');
Query OK, 0 rows affected (0.04 sec)


```

still OK

**Comment by decster** [comment]
> @decster There is no index for `id` column, So, in a big table, Is it fast to find these string values without index? Is there any string dictionary to accelerate the search?

select runs pretty normal, so it's probably not a query/read/index issue, maybe write issue in user's env
