### ISSUE TITLE
Unknown error cause all backends shut down in version 2.2.2

### ISSUE THREAD

**Issue by 5herhom** [StarRocks/starrocks#14091]
Unknown error made all 17 backends shut down in version 2.2.2. Log in be.out is below in time '**Nov 24 19:52:49 CST 2022**'

====================================be.out=========================================
start time: Wed Jul 6 10:10:39 CST 2022
tcmalloc: large alloc 1195728896 bytes == 0x1353a8000 @  0x548bc6f 0x571d4dc 0x1ecb118 0x566d755
start time: Fri Jul 22 15:19:24 CST 2022
tcmalloc: large alloc 1195728896 bytes == 0xa79810000 @  0x548bc6f 0x571d4dc 0x1ecb118 0x566d755
tcmalloc: large alloc 1677721600 bytes == 0x9e0cfc000 @  0x548bc6f 0x571d4dc 0x1ecb118 0x566d755 0x2a1f9d3 0x2a24c59 0x2a24e56 0x2943dec 0x26d94ae 0x26450ba 0x263779d 0x262d2a1 0x1f6cc39 0x1f687ea 0x7f1b3f137e65
tcmalloc: large alloc 1677721600 bytes == 0x9e0cfc000 @  0x548bc6f 0x571d4dc 0x1ecb118 0x566d755 0x2a1f9d3 0x2a24c59 0x2a24e56 0x2943dec 0x26d94ae 0x26450ba 0x263779d 0x262d2a1 0x1f6cc39 0x1f687ea 0x7f1b3f137e65
log4j:WARN No appenders could be found for logger (org.apache.hadoop.fs.FileSystem).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
tcmalloc: large alloc 2415927296 bytes == 0x103adcc000 @  0x548bc6f 0x571d4dc 0x1ecb118 0x566d755 0x1d65d03 0x2acb479 0x2ad351c 0x294acf3 0x26d95ed 0x264505a 0x263779d 0x262d2a1 0x1f6cc39 0x1f687ea 0x7f1b3f137e65
tcmalloc: large alloc 4831846400 bytes == 0x10cadd6000 @  0x548bc6f 0x571d4dc 0x1ecb118 0x566d755 0x1d65d03 0x2acb479 0x2ad351c 0x294acf3 0x26d95ed 0x264505a 0x263779d 0x262d2a1 0x1f6cc39 0x1f687ea 0x7f1b3f137e65
tcmalloc: large alloc 9663684608 bytes == 0x11eb5d8000 @  0x548bc6f 0x571d4dc 0x1ecb118 0x566d755 0x1d65d03 0x2acb479 0x2ad351c 0x294acf3 0x26d95ed 0x264505a 0x263779d 0x262d2a1 0x1f6cc39 0x1f687ea 0x7f1b3f137e65
tcmalloc: large alloc 2415927296 bytes == 0xc6d124000 @  0x548bc6f 0x571d4dc 0x1ecb118 0x566d755 0x1d65d03 0x2acdbac 0x28fbdee 0x26d941e 0x26450ba 0x263779d 0x262d2a1 0x1f6cc39 0x1f687ea 0x7f1b3f137e65
tcmalloc: large alloc 4831846400 bytes == 0x11eb5d8000 @  0x548bc6f 0x571d4dc 0x1ecb118 0x566d755 0x1d65d03 0x2acdbac 0x28fbdee 0x26d941e 0x26450ba 0x263779d 0x262d2a1 0x1f6cc39 0x1f687ea 0x7f1b3f137e65
tcmalloc: large alloc 9663684608 bytes == 0xf2506e000 @  0x548bc6f 0x571d4dc 0x1ecb118 0x566d755 0x1d65d03 0x2acdbac 0x28fbdee 0x26d941e 0x26450ba 0x263779d 0x262d2a1 0x1f6cc39 0x1f687ea 0x7f1b3f137e65
tcmalloc: large alloc 3784949760 bytes == 0x1e8adda000 @  0x548bc6f 0x571d4dc 0x1ecb118 0x566d755 0x29b166e 0x29de48b 0x236d35b 0x2659782 0x2636fba 0x262d2a1 0x1f6cc39 0x1f687ea 0x7f1b3f137e65
tcmalloc: large alloc 3784949760 bytes == 0x1e8adda000 @  0x548bc6f 0x571d4dc 0x1ecb118 0x566d755 0x29b166e 0x29de48b 0x236d35b 0x2659782 0x2636fba 0x262d2a1 0x1f6cc39 0x1f687ea 0x7f1b3f137e65
*** Aborted at 1669290762 (unix time) try "date -d @1669290762" if you are using GNU date ***
PC: @          0x310b9a1 _ZNSt17_Function_handlerIFN9starrocks6StatusEvEZNS0_10vectorized20JavaFunctionCallExpr4openEPNS0_12RuntimeStateEPNS0_11ExprContextEN13starrocks_udf15FunctionContext18FunctionStateScopeEEUlvE_E9_M_invokeERKSt9_Any_data
*** SIGSEGV (@0x0) received by PID 977797 (TID 0x7f1add33f700) from PID 0; stack trace: ***
    @          0x3caf752 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f1b3fc6fd62 os::Linux::chained_handler()
    @     0x7f1b3fc763f6 JVM_handle_linux_signal
    @     0x7f1b3fc6c9d3 signalHandler()
    @     0x7f1b3f13f5f0 (unknown)
    @          0x310b9a1 _ZNSt17_Function_handlerIFN9starrocks6StatusEvEZNS0_10vectorized20JavaFunctionCallExpr4openEPNS0_12RuntimeStateEPNS0_11ExprContextEN13starrocks_udf15FunctionContext18FunctionStateScopeEEUlvE_E9_M_invokeERKSt9_Any_data
    @          0x31c3dbe starrocks::call_function_in_pthread()
    @          0x310de51 starrocks::vectorized::JavaFunctionCallExpr::open()
    @          0x2b0cd5e starrocks::ExprContext::open()
    @          0x2b0df91 starrocks::Expr::open()
    @          0x25ccb7b starrocks::vectorized::ProjectNode::open()
    @          0x248115d starrocks::vectorized::HashJoinNode::open()
    @          0x25ccb4b starrocks::vectorized::ProjectNode::open()
    @          0x248115d starrocks::vectorized::HashJoinNode::open()
    @          0x25ccb4b starrocks::vectorized::ProjectNode::open()
    @          0x23e7e3a starrocks::vectorized::AggregateStreamingNode::open()
    @          0x1e915f4 starrocks::PlanFragmentExecutor::_open_internal_vectorized()
    @          0x1e922f7 starrocks::PlanFragmentExecutor::open()
    @          0x1e25f4b starrocks::FragmentExecState::execute()
    @          0x1e2a68c starrocks::FragmentMgr::exec_actual()
    @          0x1e2aef1 _ZNSt17_Function_handlerIFvvEZN9starrocks11FragmentMgr18exec_plan_fragmentERKNS1_23TExecPlanFragmentParamsERKSt8functionIFvPNS1_20PlanFragmentExecutorEEESC_EUlvE_E9_M_invokeERKSt9_Any_data
    @          0x1f6cc39 starrocks::ThreadPool::dispatch_thread()
    @          0x1f687ea starrocks::Thread::supervise_thread()
    @     0x7f1b3f137e65 start_thread
    @     0x7f1b3e75288d __clone
    @                0x0 (unknown)
start time: **Thu Nov 24 19:52:49 CST 2022**
log4j:WARN No appenders could be found for logger (org.apache.hadoop.fs.FileSystem).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by stdpain** [comment]
upgrade to latest 2.2.x and retry
