### ISSUE TITLE
hive外表（sqoop导入，snappy压缩）无法查询

### ISSUE THREAD

**Issue by Jarry520** [StarRocks/starrocks#14116]
### Steps to reproduce the behavior (Required)
创建了hive外部表或者hive catalog ，使用sr查询时报无法解析snappy压缩类型

### Expected behavior (Required)

query failed: Unknown compress type: 3:file = hdfs://nameservice1/user/hive/warehouse/ods.db/ods_biz_outline_urge_staff/dt=2022-10-27/part-m-00002.snappy
### Real behavior (Required)
<img width="994" alt="image" src="https://user-images.githubusercontent.com/108266979/203913337-3951ee5f-8530-46d6-97b2-2bdbdd070b8a.png">
![image](https://user-images.githubusercontent.com/108266979/203913360-7850792c-51bc-423f-9e57-3af519a684b6.png)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 -2.4.0 c0fa2bb

**Comment by jaogoy** [comment]
Does StarRocks support read hive data with snappy compression?
