### ISSUE TITLE
Can starrocks extend the function of an array?

### ISSUE THREAD

**Issue by screnwei** [StarRocks/starrocks#1420]
Can starrocks extend the function of an array? like array_contains_any(),  array_contains_all(), other functions. 

```
mysql> select array_contains_any(["apple","orange","pear"], ["orange","banana"]) as result;
+-----------------------------------------------------+
| result                                              |
+-----------------------------------------------------+
|  1                                                  |
+-----------------------------------------------------+
1 row in set (0.01 sec)
```

```
mysql> select array_contains_all(["apple","orange","pear"], ["orange","banana"]) as result;
+-----------------------------------------------------+
| result                                              |
+-----------------------------------------------------+
| 0                                                   |
+-----------------------------------------------------+
1 row in set (0.01 sec)
```

**Comment by imay** [comment]
@screnwei 
Of cause yes, what's the functions do you really want?

**Comment by screnwei** [comment]
@imay 
At present, the array type of starrocks only supports partial functions, like [array_contains](https://docs.starrocks.com/zh-cn/main/sql-reference/sql-functions/array-functions/array_contains). I need him to support more functions, like array_contains_any(), array_contains_all().

for example,  array_contains_all() returns **true** if this list contains **all** of the elements of the specified collection.
```
mysql> select array_contains_all(["apple","orange","pear"], ["orange","pear"]) as result;
+-----------------------------------------------------+
| result                                              |
+-----------------------------------------------------+
| 1                                                   |
+-----------------------------------------------------+
1 row in set (0.01 sec)
```

array_contains_any() returns true if this list contains **any of the elements** of the specified collection.
```
mysql> select array_contains_all(["apple","orange","pear"], ["orange","banana"]) as result;
+-----------------------------------------------------+
| result                                              |
+-----------------------------------------------------+
| 0                                                   |
+-----------------------------------------------------+
1 row in set (0.01 sec)

```

**Comment by imay** [comment]
@screnwei 
OK, I see. Thanks for your reply.
We will support it later.
And do you want to do it for StarRocks?

**Comment by screnwei** [comment]
@imay yes, I want. 
Unfortunately, I don't know source code of BE well.
I'm learning the source code of starrocks, now.  And I'll do it when I'm familiar with it.

**Comment by imay** [comment]
@screnwei 
Wonderful!
Please feel free to ask me. I'm very very happy to help you to do this job.

**Comment by cokolin** [comment]
借这个 issue 补充几个 array 相关的 函数：
- arrays_overlap，参考：https://spark.apache.org/docs/3.0.1/api/sql/index.html#arrays_overlap
- array_union，参考：https://spark.apache.org/docs/3.0.1/api/sql/index.html#array_union

**Comment by wangsimo0** [comment]
@screnwei Hi, we support array_contains now. Thanks for your suggestion😊 And we add several other array functions. Please check our documentation https://docs.starrocks.com/en-us/main/sql-reference/sql-functions/array-functions/array_contains
