### ISSUE TITLE
why I use JSON_OBJECT and use '3' at first, the value is null?

### ISSUE THREAD

**Issue by fjxmjmxcy** [StarRocks/starrocks#14297]
[Example]:

select 
	JSON_OBJECT(
		'big_label', '3A'
	) json_str
from dual

[Result]:
| json_str           |
-------------------+
{"big_label": null}|
{"big_label": null}|
{"big_label": null}|
{"big_label": null}|
{"big_label": null}|

**Comment by mofeiatwork** [comment]
JSON string needs to be quoted, like `select json_object('big_label', '"3A"')`

**Comment by huldarchen** [comment]
I think it's a bug.From the phenomenon point of view, type inference will be performed based on the first character. E.g
`select json_object('big_label', '3')` the result is expected `{"big_label": 3}` 
`select json_object('big_label', 'A')` the result is expected `{"big_label": 'A'}`
`select json_object('big_label', 'A3')`the result is expected `{"big_label": "A3"}`
but
`select json_object('big_label', '3A')` result is abnormal `{"big_label": null}`

**Comment by mofeiatwork** [comment]
I would fix this through https://github.com/StarRocks/starrocks/issues/14688
