### ISSUE TITLE
Memory exceed limit error while scanning hive external table with parquet format

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#1437]
### Steps to reproduce the behavior (Required)
1. create hive table，parquet format，and insert data：
create table hive_hdfs_parquet(
 col_tinyint tinyint comment "column tinyint"
,col_smallint smallint comment "column smallint"
,col_int int comment "column int"
,col_integer integer comment "column integer"
,col_bigint bigint comment "column bigint"
,col_float float comment "column float"
,col_double double comment "column double"
,col_double_precision double precision comment "column double precision"
,col_decimal decimal comment "column decimal"
,col_timestamp timestamp comment "column timestamp"
,col_date date comment "column date"
,col_string string comment "column string"
,col_varchar varchar(100) comment "column varchar"
,col_binary binary comment "column binary"
,col_char char(100) comment "column char"
,col_boolean boolean comment "column boolean"
,col_array array<int> comment "column array"
)
clustered by(col_int) sorted by(col_int) into 32 buckets
row format delimited fields terminated by ','
stored as parquet;

insert 200 rows；

2. create hive external table：
create external resource hive_resource_1637317432734 PROPERTIES("type" = "hive","hive.metastore.uris" = "thrift://***.***.***.***:9083");
create external table ex_hive_hdfs_parquet (         col_char char(100) comment "column char"         ,col_date date comment "column date"         ,col_tinyint tinyint comment "column tinyint"         ,col_string varchar(1000) comment "column string"         ,col_smallint smallint comment "column smallint"         ,col_int int comment "column int"         ,col_integer integer comment "column integer"         ,col_bigint bigint comment "column bigint"         ,col_float float comment "column float"         ,col_double double comment "column double"         ,col_double_precision double comment "column double precision"         ,col_decimal decimal comment "column decimal"         ,col_timestamp datetime comment "column timestamp"         ,col_varchar varchar(100) comment "column varchar"         ,col_binary varchar(1000) comment "column binary"         ,col_boolean boolean comment "column boolean")         ENGINE=hive         properties (             "resource" = "hive_resource_1637317432734",             "table" = "hive_hdfs_parquet",             "database" = "hive_extbl_test_1637317432735");

3. select hive external table：
mysql> select * from ex_hive_hdfs_parquet limit 1;
+----------+------------+-------------+-------------+--------------+---------+-------------+------------+-----------+------------+----------------------+-------------+---------------------+-------------+------------------------+-------------+
| col_char | col_date   | col_tinyint | col_string  | col_smallint | col_int | col_integer | col_bigint | col_float | col_double | col_double_precision | col_decimal | col_timestamp       | col_varchar | col_binary             | col_boolean |
+----------+------------+-------------+-------------+--------------+---------+-------------+------------+-----------+------------+----------------------+-------------+---------------------+-------------+------------------------+-------------+
| 8        | 2021-08-01 |           8 | hello world |            8 |       8 |           8 |          8 |     8.001 |       80.1 |                810.1 |        8110 | 2021-08-01 12:10:23 | hi          | 1110001010101011001001 |           1 |
+----------+------------+-------------+-------------+--------------+---------+-------------+------------+-----------+------------+----------------------+-------------+---------------------+-------------+------------------------+-------------+
1 row in set (0.04 sec)

mysql> select * from ex_hive_hdfs_parquet limit 1;
ERROR 1064 (HY000): Memory exceed limit. QUERY Backend: 172.26.92.151, fragment: dadc109c-4927-11ec-90f2-00163e10c9d8 Used: 2272090672, Limit: 2147483648. Mem usage has exceed the limit of single query, You can change the limit by set session variable exec_mem_limit.

### Expected behavior (Required)
returned the right result

### Real behavior (Required)
randomly error:
ERROR 1064 (HY000): Memory exceed limit. QUERY Backend: 172.26.92.151, fragment: dadc109c-4927-11ec-90f2-00163e10c9d8 Used: 2272090672, Limit: 2147483648. Mem usage has exceed the limit of single query, You can change the limit by set session variable exec_mem_limit.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN 411eb09   |
+-------------------+
1 row in set (0.00 sec)

**Comment by caneGuy** [comment]
if no one work on this, i would like to solve this problem

**Comment by stdpain** [comment]
@caneGuy 
I've located the problem, but it will take some time to test. https://github.com/StarRocks/starrocks/pull/1439

**Comment by caneGuy** [comment]
good job @caneGuy

**Comment by imay** [comment]
@stdpain I will assign this to you
