### ISSUE TITLE
Support multi-column IN subquery in SELECT and DELETE clauses

### ISSUE THREAD

**Issue by agubichev** [StarRocks/starrocks#14404]
## Feature request

**Is your feature request related to a problem? Please describe.**
An example of the query is:
`SELECT * FROM A WHERE (A.x,A.x) IN (SELECT B.x, B.y FROM B); `

Similarly:
` DELETE FROM MTL_SYSTEM_ITEMS_B
WHERE (INVENTORY_ITEM_ID, ORGANIZATION_ID, _CELONIS_CHANGE_DATE) in (
    SELECT INVENTORY_ITEM_ID, ORGANIZATION_ID, _CELONIS_CHANGE_DATE FROM _CEL_FSET_MOR_DELETE2
);`

**Describe the solution you'd like**
A simple case can be supported with an existing semi-join implementation. In general, IN subqueries that are part of complex predicates may require a Mark join (see https://15721.courses.cs.cmu.edu/spring2020/papers/20-optimizer2/hyperjoins-btw2017.pdf)
There are some corner cases that should be ruled out in the initial implementation (e.g., NULLs in the tuple in the left side etc)

**Describe alternatives you've considered**

**Additional context**
This seems to be a fairly common feature in other databases

**Comment by imay** [comment]
Because we have introduced Struct Type, maybe we can treat this feature as a struct type comparison?

**Comment by agubichev** [comment]
That works, the scope is overlapping (using a hash join over structs would require a struct type comparison).

**Comment by chaoyli** [comment]
We have a use case. I think the grammer is useful

**Comment by agubichev** [comment]
I agree about both points (MultiInPredicate and starting with WHERE clauses).
Your rewrite, however, is not identical to the original query. It matches a cross-product of input rows, whereas the multi-in predicate only looks for tuples

A:
x | y
0 | 10
1 | 10

B:
x | y
0 | 10
1 | 20


Here, `SELECT * FROM A WHERE (x, y) IN (SELECT x, y in B)` only returns the first tuple (0, 10).

The rewrite, however, returns the entire table A, because both x = 1 and x = 0 appear in B, and y = 10 appears in B (just not together with x = 1)
