### ISSUE TITLE
Materialized view query rewrite should support cross join

### ISSUE THREAD

**Issue by Dshadowzh** [StarRocks/starrocks#14451]
### Steps to reproduce the behavior (Required)
1. Using SSB benchmark data
2. create materialized view mv_1 distributed by hash(s_city) as  select s_city, s_nation , lo_orderpriority, sum(lo_revenue) as sum_1, sum(lo_revenue*lo_discount) as sum_2 from lineorder join supplier group by s_city, s_nation , lo_orderpriority;
3. refresh refresh materialized view mv_1; 
4. select s_city, s_nation , lo_orderpriority, sum(lo_revenue) as sum_1, sum(lo_revenue*lo_discount) as sum_2 from lineorder join supplier group by s_city, s_nation , lo_orderpriority; 

### Expected behavior (Required)
It should be hit the materialized view and query rewrite, but it not worked.
If I change the cross join to inner join, it works.

### Real behavior (Required)
Still query to base table and cost a lot of time.

### StarRocks version (Required)
 - branch-2.5- 35c84c8

**Comment by huangfeng1993** [comment]
Could I try it?  
I found two main problem is
1.  when table is nopartition,  don't compensate PartitionPredicate.
2. currently getMatchMode is only for equijoin.
