### ISSUE TITLE
Request for Data Encryption for enterprise level data security

### ISSUE THREAD

**Issue by jiabinxia-sanofi** [StarRocks/starrocks#14481]
## Feature request

We are using enterprise Starrocks and we are facing issues when we are trying to securely store our sensitive data at rest. SR now does not support automatic data encryption like HDFS. Data security is a crucial factor when we consider tech stack for enterprise level data warehouse or OLAP engine.

We would like to have a solution to securely store our data to ensure data security at rest.

Or we have to use UDF and application-level data encryption solution to encrypt and decrypt data which is more resource consuming and will impact overall performance. This will also impact our decision when we review our tech stack choice for OLAP engine or DW solution.

**Additional context**

**Comment by alberttwong** [comment]
Security features are only available in the enterprise/cloud version of StarRocks via CelerData and not in the community version.  Contact CelerData for more info.
