### ISSUE TITLE
The colocate groups info is not deleted when DB has been droped

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#1453]
### Steps to reproduce the behavior (Required)
1. CREATE DATABASE db1;
2. USE db1;
3. CREATE TABLE `t1` (
  `t1_c1` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `t1_c2` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `t1_c3` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `t1_c4` varchar(10) NOT NULL DEFAULT "" COMMENT "",
  `t1_c5` varchar(10) NOT NULL DEFAULT "" COMMENT "",
  `t1_c6` varchar(10) NOT NULL DEFAULT "" COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`t1_c1`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`t1_c1`) BUCKETS 10 
PROPERTIES (
"replication_num" = "1",
"colocate_with" = "group1",
"in_memory" = "false",
"storage_format" = "V2"
);
4.DROP DATABASE FORCE db1;
5.SHOW PROC '/colocation_group';
### Expected behavior (Required)
db1's group info has been deleted
### Real behavior (Required)
db1's group info still exists
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.0

**Comment by gengjun-git** [comment]
Can not reproduce
