### ISSUE TITLE
show create table  contains database 

### ISSUE THREAD

**Issue by yancheng44** [StarRocks/starrocks#1454]
show create table dw.dw_user_day command  shows 

create table dw_user_day
( user_id String,
xxx
)...

Can we add the database  ？

**Comment by Astralidea** [comment]
starrocks currently supports the mysql-compatible protocol.
If database is added, I worry that it will cause incompatibility with other BI products.

**Comment by jaogoy** [comment]
I wonder where to add database, can you give more detail info?
