### ISSUE TITLE
match_recognize feature support

### ISSUE THREAD

**Issue by vkingnew** [StarRocks/starrocks#14540]
https://trino.io/docs/current/sql/match-recognize.html
https://docs.snowflake.com/en/sql-reference/constructs/match_recognize.html
 **MATCH_RECOGNIZE**  features are support by many database ,for example oracle ,snowflake and so on.
And this feature in SQL:2016.

**Comment by zhaoyongjie** [comment]
The `MATCH_RECOGNIZE` should be an important feature and should be leveraged for many analytic use cases, such as user behavior analytics. Therefore, we should reopen this issue and continue working on it.
