### ISSUE TITLE
The Year-End Bug Hunting Party Is On！🥳

### ISSUE THREAD

**Issue by kateshaowanjou** [StarRocks/starrocks#14564]
Hi Community, 👋
It's the time of the year when we say goodbyes to things that don't work for us and get ready for better things ahead. That's why we plan this year-end Bug Hunting Party and would like you to join us! 
The bug hunt is on! 🔥 See how to participate below：

### How to participate
Register for this event by leaving a comment under this issue with a message like "I'd like to sign up for StarRocks Bug Hunt 2022." If someone invited you to join this bug hunt, please **also include the inviter's GitHub ID in your sign-up message** so they can get the extra points.

### Event Time
2022/12/5-2023/1/5
* Final results will be announced by 2023/1/11

### Event Rules
**Scope of the event**
⚠️ ****P0 level bugs** in StarRocks v2.2 and later (v2.5 RC included):**
- Storage and data bugs (bugs that cause data errors during data loading, compaction, or schema change)
- Query bugs (bugs that return incorrect or inconsistent results, or return errors)
- Bugs that cause service unavailability (including deadlocks, lock conflicts, or bugs in functions)
- Bugs that cause BE to crash or exit, or that affect the FE availability.
- Bugs that cause noticeable memory leaks, high memory usage, or OOM.

### 💬 Communication 
If you have any questions, you can open a new discussion [here](https://github.com/StarRocks/starrocks/discussions) including [Bug Hunt] in the title.

**Comment by kateshaowanjou** [comment]
I'd like to sign up for StarRocks Bug Hunt 2022 🙋‍♀️

**Comment by herocc19** [comment]
I'd like to sign up for StarRocks Bug Hunt 2022 🙋‍♀️

**Comment by haiboself** [comment]
I'd like to sign up for StarRocks Bug Hunt 2022.

**Comment by leoyy0316** [comment]
I'd like to sign up for StarRocks Bug Hunt 2022

**Comment by chen9t** [comment]
I'd like to sign up for StarRocks Bug Hunt 2022.

**Comment by Mile-Z** [comment]
I'd like to sign up for StarRocks Bug Hunt 2022. 🙋‍♀️

**Comment by jinshuangxian** [comment]
I'd like to sign up for StarRocks Bug Hunt 2022.

**Comment by lwlei** [comment]
I'd like to sign up for StarRocks Bug Hunt 2022

**Comment by syyfffy** [comment]
I'd like to sign up for StarRocks Bug Hunt 2022 🙋‍♀️

**Comment by winter-tang** [comment]
I'd like to sign up for StarRocks Bug Hunt 2022.

**Comment by liuzhimin1996** [comment]
I'd like to sign up for StarRocks Bug Hunt 2022.

**Comment by louishust** [comment]
I'd like to sign up for StarRocks Bug Hunt 2022.

**Comment by lixiaoer666** [comment]
I'd like to sign up for StarRocks Bug Hunt 2022 🙋‍♀️

**Comment by mchades** [comment]
I'd like to sign up for StarRocks Bug Hunt 2022 🙋‍♀️

**Comment by huangfeng1993** [comment]
I'd like to sign up for StarRocks Bug Hunt 2022 🙋‍♀️

**Comment by finddbbug** [comment]
I'd like to sign up for StarRocks Bug Hunt 2022.

**Comment by miomiocat** [comment]
I'd like to sign up for StarRocks Bug Hunt 2022.

**Comment by zyclove** [comment]
I'd like to sign up for StarRocks Bug Hunt 2022.

**Comment by anyepriest** [comment]
I'd like to sign up for StarRocks Bug Hunt 2022.

**Comment by kateshaowanjou** [comment]
Thanks for joining StarRock's bug hunt party. The event is closed so I'm closing this issue.

**Comment by kateshaowanjou** [comment]
> I'd like to sign up for StarRocks Bug Hunt 2022

@lwlei  Please add my wechat:wanjoushao for your reward. Thanks!

**Comment by kateshaowanjou** [comment]
> I'd like to sign up for StarRocks Bug Hunt 2022.

@winter-tang please add my wechat:wanjoushao  for a small thank-you gift!
