### ISSUE TITLE
starrocks_fe_tablet_max_compaction_score is not Precise

### ISSUE THREAD

**Issue by Wilson-BT** [StarRocks/starrocks#1462]
#### Problem： starrocks_fe_tablet_max_compaction_score is not Precise
When I use Prometheus to monitor starrocks and Import the latest template.The indicators of BE compaction Score is abnormal.
this is the BE compaction Score:
![8661637285592_ pic_hd](https://user-images.githubusercontent.com/40427110/142727013-398f6b4b-4173-4327-8921-2a54aa50d812.jpg)
but the log of be is very small :
![8721637286433_ pic_hd](https://user-images.githubusercontent.com/40427110/142727122-7eda1a88-7155-4f01-bab2-7e1a9734ca51.jpg)

**Comment by jaogoy** [comment]
You can only monitor the max_compaction_score, otherwise the monitor elements are too much.
