### ISSUE TITLE
FE node costs too much cpu

### ISSUE THREAD

**Issue by carr123** [StarRocks/starrocks#1465]
i deployed a 3-node cluster last week. each node has 8 cpu core, 16GB RAM.
i loaded about 400M records to one table 2 days ago.
recently i notice the FE processes on 2 of the 3 nodes cost too much CPU (36%~66%), while there are  no query no writes agaist the cluster. and the cpu usage seems never drop down.
BTW, the BE process stays slient on the background.

below is the screen capture:
%CPU %MEM     TIME+ COMMAND
43.3     12.4         1375:26 java

i wonder why the FE process is always busy.

**Comment by gengjun-git** [comment]
This is normal, the master node has some damon threads
