### ISSUE TITLE
[information_schema] when i run sql to select from information_schema use join, be exit

### ISSUE THREAD

**Issue by leoyy0316** [StarRocks/starrocks#14679]
### Steps to reproduce the behavior (Required)
1.run SHOW PROC '/backends'\G
be allive
2.run this sql
select * from information_schema.tables a left join information_schema.columns b on a.TABLE_NAME=b.TABLE_NAME;
3.run SHOW PROC '/backends'\G
be exit
### Expected behavior (Required)
return correct results
### Real behavior (Required)
![image](https://user-images.githubusercontent.com/105328124/205805326-7dd128b8-5671-4669-9f99-777a152787aa.png)

**be exit**
![image](https://user-images.githubusercontent.com/105328124/205806084-40236539-e41c-4b28-ba72-bd88feb11aa0.png)

### StarRocks version (Required)
**Compiled main code**
MySQL [(none)]> select current_version();
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN           |
+-------------------+

**Comment by kateshaowanjou** [comment]
@leoyy0316 Please include the StarRocks version you are using in the bug report, thanks!

**Comment by leoyy0316** [comment]
@kateshaowanjou tested main branch code

**Comment by Astralidea** [comment]
Can you still reproduce the problem now? I have not reproduced this problem locally? If you can reproduce it, can you provide the stack of be unstacked?

**Comment by leoyy0316** [comment]
> 

maybe some pr fix it, i can not reproduce it on now main branch, so i will close this issue, thanks

**Comment by Astralidea** [comment]
Okay, thanks, sorry we are a little late to see this question, if you have other questions later, welcome to raise issue again
