### ISSUE TITLE
支持带 cast 的 join 谓词等价传递

### ISSUE THREAD

**Issue by yancheng44** [StarRocks/starrocks#14673]
测试版本， 1.19.7， 2.2.9 。 
问题： 聚合的日志表join  Uniq模型的维表， 把逻辑封装成视图提供查询。  看profile 维表没有下推条件，这个要如何优化。 
    
TabA： 
 CREATE TABLE reddw.`dw_live_mertics_toufang_rt` (
  `advertiser_id` bigint(20) NULL COMMENT "",
  `unit_id` bigint(20) NULL COMMENT "",
  `ActionDate` datetime NULL COMMENT "",
  `campaign_id` bigint(20) NULL COMMENT "",
  `creative_id` bigint(20) NULL COMMENT "",
  `click_live_event_id` varchar(100) NULL COMMENT "",
  `pic_click_num` bigint(20) SUM NULL COMMENT "",
  `pic_click_fee` decimal64(12, 4) SUM NULL COMMENT "",
  `click_live_rgmv` decimal64(12, 4) SUM NULL COMMENT "",
  `click_valid_view_pv` bigint(20) SUM NULL COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`advertiser_id`, `unit_id`, `ActionDate`, `campaign_id`, `creative_id`, `click_live_event_id`)
COMMENT ""
PARTITION BY RANGE(`ActionDate`)
(
PARTITION p20221206 VALUES [('2022-12-06 00:00:00'), ('2022-12-07 00:00:00')),
PARTITION p20221207 VALUES [('2022-12-07 00:00:00'), ('2022-12-08 00:00:00')),
PARTITION p20221208 VALUES [('2022-12-08 00:00:00'), ('2022-12-09 00:00:00')),
PARTITION p20221209 VALUES [('2022-12-09 00:00:00'), ('2022-12-10 00:00:00')))
DISTRIBUTED BY HASH(`unit_id`) BUCKETS 2;

TabB :
CREATE TABLE mysql_sync.`t_ads_creativity` (
  `advertiser_id` int(11) NULL COMMENT "",
  `v_seller_id` varchar(24) NOT NULL DEFAULT "" COMMENT "",
  `id` bigint(20) NOT NULL COMMENT "",
    parent_id  bigint(20) NOT NULL COMMENT ""
) ENGINE=OLAP
UNIQUE KEY(`advertiser_id`, `v_seller_id`, `id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`advertiser_id`) BUCKETS 2

View:
CREATE VIEW `dw_live_mertics_toufang_rt_view` (
  ActionDate_h,
  advertiser_id,
  campaign_id,
  unit_id,
  creative_id,
  parent_creative_id,
  parent_unit_id,
  parent_campaign_id,
  click_num,
  fee,
  live_24h_click_rgmv,
  live_24h_click_effective_shutdown_num,
  live_24h_click_effective_shutdown_distinct_eventid_num
) COMMENT "VIEW" AS
SELECT
  `a`.`ActionDate_h` AS `ActionDate_h`,
  `a`.`advertiser_id` AS `advertiser_id`,
  `a`.`campaign_id` AS `campaign_id`,
  `a`.`unit_id` AS `unit_id`,
  `a`.`creative_id` AS `creative_id`,
  CASE
    WHEN ((coalesce(`b`.`parent_id`, 0)) > 0) THEN `b`.`parent_id`
    ELSE `a`.`creative_id`
  END AS `parent_creative_id`,
  `a`.`unit_id` AS `parent_unit_id`,
  `a`.`campaign_id` AS `parent_campaign_id`,
  `a`.`click_num` AS `click_num`,
  `a`.`fee` AS `fee`,
  `a`.`live_24h_click_rgmv` AS `live_24h_click_rgmv`,
  `a`.`live_24h_click_effective_shutdown_num` AS `live_24h_click_effective_shutdown_num`,
  `a`.`live_24h_click_effective_shutdown_distinct_eventid_num` AS `live_24h_click_effective_shutdown_distinct_eventid_num`
FROM
  (
    SELECT
      `reddw`.`dw_live_mertics_toufang_rt`.`ActionDate` AS `ActionDate_h`,
      `reddw`.`dw_live_mertics_toufang_rt`.`advertiser_id` AS `advertiser_id`,
      `reddw`.`dw_live_mertics_toufang_rt`.`campaign_id` AS `campaign_id`,
      `reddw`.`dw_live_mertics_toufang_rt`.`unit_id` AS `unit_id`,
      `reddw`.`dw_live_mertics_toufang_rt`.`creative_id` AS `creative_id`,
      sum(
        `reddw`.`dw_live_mertics_toufang_rt`.`pic_click_num`
      ) AS `click_num`,
      sum(
        `reddw`.`dw_live_mertics_toufang_rt`.`pic_click_fee`
      ) AS `fee`,
      sum(
        `reddw`.`dw_live_mertics_toufang_rt`.`click_live_rgmv`
      ) AS `live_24h_click_rgmv`,
      sum(
        `reddw`.`dw_live_mertics_toufang_rt`.`click_valid_view_pv`
      ) AS `live_24h_click_effective_shutdown_num`,
      count(
        DISTINCT `reddw`.`dw_live_mertics_toufang_rt`.`click_live_event_id`
      ) AS `live_24h_click_effective_shutdown_distinct_eventid_num`
    FROM
      `reddw`.`dw_live_mertics_toufang_rt`
    GROUP BY
      `reddw`.`dw_live_mertics_toufang_rt`.`ActionDate`,
      `reddw`.`dw_live_mertics_toufang_rt`.`advertiser_id`,
      `reddw`.`dw_live_mertics_toufang_rt`.`campaign_id`,
      `reddw`.`dw_live_mertics_toufang_rt`.`unit_id`,
      `reddw`.`dw_live_mertics_toufang_rt`.`creative_id`
  ) a
  LEFT OUTER JOIN `mysql_sync`.`t_ads_creativity` AS `b` ON (`a`.`advertiser_id` = `b`.`advertiser_id`)
  AND (`a`.`creative_id` = `b`.`id`);

验证SQL ：

set is_report_success=true;
select * 
from
    reddw.dw_live_mertics_toufang_rt_view
where
    ActionDate_h >= '2022-12-05 00:00:00'
    and ActionDate_h <= '2022-12-05 23:59:59'
    and advertiser_id = 88506 

PLAN:

PLAN FRAGMENT 0
OUTPUT EXPRS:3: ActionDate | 1: advertiser_id | 4: campaign_id | 2: unit_id | 5: creative_id | 79: case | 2: unit_id | 4: campaign_id | 11: sum | 12: sum | 13: sum | 14: sum | 15: count
PARTITION: UNPARTITIONED
RESULT SINK
9:EXCHANGE
PLAN FRAGMENT 1
OUTPUT EXPRS:
PARTITION: HASH_PARTITIONED: 80: cast, 18: id
STREAM DATA SINK
EXCHANGE ID: 09
UNPARTITIONED
8:Project
| <slot 1> : 1: advertiser_id
| <slot 2> : 2: unit_id
| <slot 3> : 3: ActionDate
| <slot 4> : 4: campaign_id
| <slot 5> : 5: creative_id
| <slot 11> : 11: sum
| <slot 12> : 12: sum
| <slot 13> : 13: sum
| <slot 14> : 14: sum
| <slot 15> : 15: count
| <slot 79> : if(coalesce(76: parent_id, 0) > 0, 76: parent_id, 5: creative_id)
|
7:HASH JOIN
| join op: RIGHT OUTER JOIN (PARTITIONED)
| hash predicates:
| colocate: false, reason:
| equal join conjunct: 80: cast = 1: advertiser_id
| equal join conjunct: 18: id = 5: creative_id
|
|----6:EXCHANGE
|
2:EXCHANGE
PLAN FRAGMENT 2
OUTPUT EXPRS:
PARTITION: RANDOM
STREAM DATA SINK
EXCHANGE ID: 06
HASH_PARTITIONED: 1: advertiser_id, 5: creative_id
5:AGGREGATE (update finalize)
| output: sum(11: sum), sum(12: sum), sum(13: sum), sum(14: sum), count(6: click_live_event_id)
| group by: 3: ActionDate, 1: advertiser_id, 4: campaign_id, 2: unit_id, 5: creative_id
|
4:AGGREGATE (update serialize)
| output: sum(7: pic_click_num), sum(8: pic_click_fee), sum(9: click_live_rgmv), sum(10: click_valid_view_pv)
| group by: 1: advertiser_id, 2: unit_id, 3: ActionDate, 4: campaign_id, 5: creative_id, 6: click_live_event_id
|
3:OlapScanNode
TABLE: dw_live_mertics_toufang_rt
PREAGGREGATION: ON
PREDICATES: 3: ActionDate <= '2022-12-05 23:59:59', 1: advertiser_id = 88506
partitions=1/33
rollup: dw_live_mertics_toufang_rt
tabletRatio=2/2
tabletList=50173,50177
cardinality=11
avgRowSize=44.0
numNodes=0
PLAN FRAGMENT 3
OUTPUT EXPRS:
PARTITION: RANDOM
STREAM DATA SINK
EXCHANGE ID: 02
HASH_PARTITIONED: 80: cast, 18: id
1:Project
| <slot 18> : 18: id
| <slot 76> : 76: parent_id
| <slot 80> : CAST(16: advertiser_id AS BIGINT)
|
0:OlapScanNode
TABLE: t_ads_creativity
PREAGGREGATION: OFF. Reason: None aggregate function
partitions=1/1
rollup: t_ads_creativity
tabletRatio=15/15
tabletList=52127,52131,52135,52139,52143,52147,52151,52155,52159,52163 ...
cardinality=7564378
avgRowSize=17.0
numNodes=0

**Comment by Astralidea** [comment]
The parent_id in your case seems to be wrong, can you modify the case to help me reproduce it locally?

**Comment by yancheng44** [comment]
> seems

fixed

**Comment by Astralidea** [comment]
The reason for this case is that | <slot 80> : CAST(16: advertiser_id AS BIGINT) is converted to bigint because of the different types of the left and right tables of advertiser_id, which affects the predicate transitivity optimization. You can consider unifying the types for optimization. Later You can see if this problem can be directly deduced by the optimizer.

**Comment by Astralidea** [comment]
The type may be between int bigint string, only need to support = for the time being
