### ISSUE TITLE
streamload 返回认证失败

### ISSUE THREAD

**Issue by carr123** [StarRocks/starrocks#1467]
starrocks 1.19.1
我在个循环里向某个FE节点发送http put 请求上传数据(写代码上传，不是调用curl命令)。它会307重定向，没问题。当我设置 http 头部 Connection:keep-alive 时， 第1，3，5，7... 次PUT 数据都成功， 但是第2，4，6，8 ...  次请求会返回http code 401,  Authentication Failed. <br/> Need auth information.
如果我设置http 头部 Connection:close 时， 每次PUT数据都能成功。

**Comment by stephen-shelby** [comment]
If it is convenient, you can provide some http parameter settings in your code.

**Comment by carr123** [comment]
我的代码是类似以下的golang http 客户端。希望对您有帮助。
---------------------------------------------------------------------------------------------------------------------------
package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"net/http"
	"time"
)

func main() {
	feAddr := "http://192.168.1.10:8030/api/example_db/table1/_stream_load"
	username := "test"
	passwd := "123456"
	label := fmt.Sprintf("label_%d", time.Now().UnixNano())
	loader := NewStreamLoader(feAddr, username, passwd)

	records := "1,1,jim,2\n2,1,grace,2"
	for {
		loader.Upload(label, records)
		time.Sleep(time.Second)
	}
}

type StreamLoader struct {
	hClient  *http.Client
	szURL    string
	username string
	passwd   string
}

func NewStreamLoader(szURL string, username string, passwd string) *StreamLoader {
	client := &http.Client{
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			req.SetBasicAuth(username, passwd)
			return nil
		},
	}

	return &StreamLoader{
		hClient:  client,
		szURL:    szURL,
		username: username,
		passwd:   passwd,
	}
}

func (t *StreamLoader) Upload(label string, records string) error {
	req, _ := http.NewRequest("PUT", t.szURL, bytes.NewBufferString(records))
	req.Header.Add("label", label)
	req.Header.Add("column_separator", ",")
	req.Header.Add("Content-Length", fmt.Sprintf("%d", len(records)))
	req.Header.Add("Content-Type", "text/html; charset=UTF-8")
	req.Header.Add("Expect", "100-continue")
	req.Header.Add("Accept", "*/*")
	//req.Header.Add("Connection", "close")
	req.Header.Add("Connection", "keep-alive")
	req.SetBasicAuth(t.username, t.passwd)

	resp, err := t.hClient.Do(req)
	if err != nil {
		return err
	}

	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return err
	}

	defer resp.Body.Close()

	fmt.Printf("resp code:%d,body:%s\n\n", resp.StatusCode, string(body))

	return nil
}

**Comment by stephen-shelby** [comment]
@carr123 
Thank you for the information.
 When I used golang to reproduce the problem, I found that the second time I sent the request threw a protocol exception.
I will continue to troubleshoot the problem. You could temporarily set 'Connection' to close.

**Comment by carr123** [comment]
@stephen-shelby  hi, did you fix this bug in the new release ?
