### ISSUE TITLE
Materialized views take up a lot of disk

### ISSUE THREAD

**Issue by Astralidea** [StarRocks/starrocks#14681]
### Real behavior (Required)
![img_v2_7d3c6135-2396-4c09-b346-fe5e4b0417eg](https://user-images.githubusercontent.com/4392280/205806364-b9367ff7-3d1c-4ea6-89f0-8b734fbf933b.jpg)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by Astralidea** [comment]
This can not reproduce so close it first.

**Comment by Astralidea** [comment]
![img_v2_8d1bb88b-032e-4e05-9c7a-ce84859f279g](https://user-images.githubusercontent.com/4392280/209917847-c99d34d5-da5f-491f-8b7e-77d42701f154.png)

**Comment by ABingHuang** [comment]
the reason is that dropped partitions of insert overwrite go into trash and not deleted directly. trash occupies too much disk space.
I will fix it by delete dropped partitions data directly
