### ISSUE TITLE
wrong sort limit result

### ISSUE THREAD

**Issue by yongkonglee** [StarRocks/starrocks#14740]
StarRocks 2.4.0 c0fa2bb，sort result is different by below two sql

## sort result is right，100 million data size is very slowly
SELECT *  FROM TAB ORDER BY UPDATED_AT DESC LIMIT 0, 100

## sort result is wrong
SELECT *  FROM (SELECT * FROM TAB ORDER BY UPDATED_AT DESC) T LIMIT 0, 100

**Comment by Seaven** [comment]
the result of subquery is a `set` in the SQL standard, so subquery will ignore `ORDER BY`(of course, it’s best to support `order by` on subquery, but subquery will also be very slow), so the result is different, and the performance of sort is being optimized and will relaesed in the future version

**Comment by Seaven** [comment]
the result of subquery is a `set` in the SQL standard, so subquery will ignore `ORDER BY`(of course, it’s best to support `order by` on subquery, but subquery will also be very slow), so the result is different, and the performance of sort is being optimized and will relaesed in the future version
