### ISSUE TITLE
[bug]Query a view containing subqueries to report an error: [42000][1064] Unknown table xxx.

### ISSUE THREAD

**Issue by ysyl23588** [StarRocks/starrocks#1479]
version:1.19.2

It can be created normally, but the query reports an error

1、create view dba_test.test_view16 (c_1) as with a as (select 1 c1 union all select 2 ), b as (select 1 c1 union all select 2 ) select from a union all select * from b;
2、select * from dba_test.test_view16;

**Comment by Dshadowzh** [comment]
Thanks @ysyl23588, could you provide error messages?

**Comment by ysyl23588** [comment]
> Thanks @ysyl23588, could you provide error messages?

**[42000][1064] Unknown table xxx**
This is the error message returned by the client, and the fe background log will be provided later
