### ISSUE TITLE
character num of hive external table name cant greater than 63

### ISSUE THREAD

**Issue by haiboself** [StarRocks/starrocks#14807]
### Steps to reproduce the behavior (Required)
Execute ddl
```
CREATE EXTERNAL TABLE tmp.`dwd_vehxcle_sgnfal_f_batty_sfoh_slow_chafrxging_xgb_re_pred_ict_di` (
  `v` varchar(65533) NULL COMMENT "",
  `t` bigint(20) NULL COMMENT "",
  `t` bigint(20) NULL COMMENT ""
) ENGINE = HIVE
PROPERTIES ("database"  =  "tmp",
"resource"  =  "hive_resource",
"table"  =  "dwd_vehxcle_sgnfal_f_batty_sfoh_slow_chafrxging_xgb_re_pred_ict_di");
```

Note: the external table name same as hive table name

### Expected behavior (Required)
Run ddl successfully or print real error msg；

Firstly, we hope starrocks external table name and hive table name are same. If so, user can use it like hive table and dont need to know starrocks table.
Secondly, error msg get now is confusing and I cant find root cause easily.

### Real behavior (Required)
ddl run failed and print msg 
```
[42000][1064] Incorrect table name 'dwd_vehxcle_sgnfal_f_batty_sfoh_slow_chafrxging_xgb_re_pred_ict_di'
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
+-------------------+
| current_version() |
+-------------------+
| 2.2.9 9e559c3     |
+-------------------+

**Comment by jaogoy** [comment]
Yes, that's right for all table names in StarRocks.
We will improve it.

**Comment by jaogoy** [comment]
@haiboself I wonder why you will use such long a table name.

**Comment by haiboself** [comment]
> @haiboself I wonder why you will use such long a table name.
We create hive external table by system, which has same name with hive table.  To do that, 
- user can use hive external table like hive table and dont need know about hive external table anything
- easy to switch sql engine(starrocks、impala、spark) to executed same sql

Unfortunetlly, some hive table name is too long.
