### ISSUE TITLE
Compatible with Trino syntax, type and functions

### ISSUE THREAD

**Issue by Youngwb** [StarRocks/starrocks#14825]
## Feature request
There are some syntax, types and functions in Trino that do not correspond to each other in Starrocks. In order to reduce the cost of user migration, we need to be as compatible as possible with Trino in syntax, types and functions

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DorianZheng** [comment]
Great work!
