### ISSUE TITLE
No error reported when set "colocate_with" = ""

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#1486]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE t_1 (
                            `id` int(18),
                            `value` varchar(20)
                        )
                        ENGINE=OLAP
                        DUPLICATE KEY(`id`)
                        COMMENT "OLAP"
                        DISTRIBUTED BY HASH(`id`) BUCKETS 3
                        PROPERTIES (
                            "replication_num" = "1",
                            "storage_format" = "v2",
                            "colocate_with" = ""
                        );
2.SHOW PROC '/colocation_group';

### Expected behavior (Required)
report error
### Real behavior (Required)
| GroupId              | GroupName| TableIds| BucketsNum | ReplicationNum | DistCols| IsStable |
| 193116.390730 | 193116_       | 390728 | 3                     | 1                          | int(11)   |true         |
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.0

**Comment by gengjun-git** [comment]
We should not report error, just ignore this property. Because the user can remove the table from the colocate group by setting this attribute to empty.

**Comment by imay** [comment]
@gengjun-git 
Please assign it to yourself, if you were going to handle this issue.

**Comment by gengjun-git** [comment]
> @gengjun-git Please assign it to yourself, if you were going to handle this issue.

OK
