### ISSUE TITLE
Official document<Apache Kafka import>SQL syntax error?

### ISSUE THREAD

**Issue by 2416210017** [StarRocks/starrocks#14909]
rul：https://docs.starrocks.io/zh-cn/2.3/loading/RoutineLoad

ENGINE should be written at the front！

![企业微信截图_16704896814006](https://user-images.githubusercontent.com/52597892/206421416-32228b94-1fcd-4722-a9f0-ff679b372c3c.png)

![企业微信截图_16704898517052](https://user-images.githubusercontent.com/52597892/206421967-b2a5d72f-b028-4b64-a5f1-a7521842b5f9.png)

```sql
-- Correct SQL syntax:
CREATE TABLE `example_tbl2` ( 
    `commodity_id` varchar(26) NULL COMMENT "品类ID", 
    `customer_name` varchar(26) NULL COMMENT "顾客姓名", 
    `country` varchar(26) NULL COMMENT "顾客国籍", 
    `pay_time` bigint(20) NULL COMMENT "支付时间", 
    `pay_dt` date NULL COMMENT "支付日期", 
    `price`double SUM NULL COMMENT "支付金额"
) ENGINE=OLAP
AGGREGATE KEY(`commodity_id`,`customer_name`,`country`,`pay_time`,`pay_dt`) 
DISTRIBUTED BY HASH(`commodity_id`) BUCKETS 5; ```

**Comment by chaoyli** [comment]
@2416210017  Could you help to change the doc from the website?
