### ISSUE TITLE
[HIVE-MAP] result error from hive map with compression

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#14911]
### Steps to reproduce the behavior (Required)
```
select count(a.col_map_bool_timestamp[cast(0 as boolean)]),count(b.col_map_string_date['+'])
                    from hdfs_orc_lz4_map_mix a full join hdfs_orc_lz4_map_mix b
                    on a.col_map_bool_timestamp[cast(0 as boolean)] > b.col_map_bool_timestamp[cast(0 as boolean)]
                    where a.col_map_bigint_string[88] is null;
```

```
mysql> select count(a.col_map_bool_timestamp[cast(0 as boolean)]),count(b.col_map_string_date['+'])
    ->                     from hdfs_orc_lz4_map_mix a full join hdfs_orc_lz4_map_mix b
    ->                     on a.col_map_bool_timestamp[cast(0 as boolean)] > b.col_map_bool_timestamp[cast(0 as boolean)]
    ->                     where a.col_map_bigint_string[88] is null;
+-----------------------------------------------------+-----------------------------------+
| count(a.col_map_bool_timestamp[CAST(0 AS BOOLEAN)]) | count(b.col_map_string_date['+']) |
+-----------------------------------------------------+-----------------------------------+
|                                                5904 |                              1517 |
+-----------------------------------------------------+-----------------------------------+
1 row in set (0.03 sec)

```

### Expected behavior (Required)
```
+-----------------------------------------------------+-----------------------------------+
| count(a.col_map_bool_timestamp[CAST(0 AS BOOLEAN)]) | count(b.col_map_string_date['+']) |
+-----------------------------------------------------+-----------------------------------+
|                                                5863 |                              1517 |
+-----------------------------------------------------+-----------------------------------+
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.5-RELEASE 04aff48 |
+----------------------------+
1 row in set (0.02 sec)
```

**Comment by zombee0** [comment]
`select a.c1 from test_join_int a left join test_join_int b on a.c1 > b.c1 where b.c1 is null;`
table test_join_int has only on column which is int, and the least value is 10 and has five 10,
when we execute this sql, we expect five 10, but we got 
<img width="109" alt="截屏2022-12-09 09 57 21" src="https://user-images.githubusercontent.com/28446271/206605923-e0fe767a-bb0b-43b3-8fdc-4ddc663a7216.png">

**Comment by tiannan-sr** [comment]
It seems to be a problem with the hive external table：
```
mysql> use hive_catalog.yunfei;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from test_join_int a left join test_join_int b on a.c1 > b.c1 where b.c1 is null;
+------+------+
| c1   | c1   |
+------+------+
|   10 | NULL |
|   51 | NULL |
|   26 | NULL |
|   85 | NULL |
|   97 | NULL |
+------+------+
5 rows in set (0.03 sec)

mysql> select * from default_catalog.tn_test.test_join a left join default_catalog.tn_test.test_join b
 on a.c_int > b.c_int where b.c_int is null;
+-------+-------+
| c_int | c_int |
+-------+-------+
|    10 |  NULL |
|    10 |  NULL |
|    10 |  NULL |
|    10 |  NULL |
|    10 |  NULL |
+-------+-------+
5 rows in set (0.01 sec)

mysql> select * from default_catalog.tn_test.test_join except select * from hive_catalog.yunfei.test_join_int;
Empty set (0.03 sec)

mysql>
```

**Comment by zombee0** [comment]
> It seems to be a problem with the hive external table：
> 
> ```
> mysql> use hive_catalog.yunfei;
> Reading table information for completion of table and column names
> You can turn off this feature to get a quicker startup with -A
> 
> Database changed
> mysql> select * from test_join_int a left join test_join_int b on a.c1 > b.c1 where b.c1 is null;
> +------+------+
> | c1   | c1   |
> +------+------+
> |   10 | NULL |
> |   51 | NULL |
> |   26 | NULL |
> |   85 | NULL |
> |   97 | NULL |
> +------+------+
> 5 rows in set (0.03 sec)
> 
> mysql> select * from default_catalog.tn_test.test_join a left join default_catalog.tn_test.test_join b
>  on a.c_int > b.c_int where b.c_int is null;
> +-------+-------+
> | c_int | c_int |
> +-------+-------+
> |    10 |  NULL |
> |    10 |  NULL |
> |    10 |  NULL |
> |    10 |  NULL |
> |    10 |  NULL |
> +-------+-------+
> 5 rows in set (0.01 sec)
> 
> mysql> select * from default_catalog.tn_test.test_join except select * from hive_catalog.yunfei.test_join_int;
> Empty set (0.03 sec)
> 
> mysql>
> ```

it is common case in both native table and external table. the reason why above doesn't reproduce the bug is the data is ordered by native table.

so let's represent the bug in native table:
`create table test_join2 (c_int int, c1 int) engine=olap duplicate key(c_int) distributed by hash (c_int) buckets 1 properties ("replication_num" = "1");`
`insert into test_join2 select 1, * from hive_test.yunfei.test_join_int;`
`select * from 
<img width="363" alt="截屏2022-12-13 10 09 32" src="https://user-images.githubusercontent.com/28446271/207208792-934ca34e-d8c8-4eb7-98c6-33d2d22b81d5.png">
test_join2 a left join test_join2 b on a.c1 > b.c1 where b.c1 is null;`

**Comment by tiannan-sr** [comment]
mysql> select count(a.col_map_bool_timestamp[cast(0 as boolean)]),count(b.col_map_string_date['+'])                     from hdfs_orc_lz4_map_mix a full join hdfs_orc_lz4_map_mix b
                    on a.col_map_bool_timestamp[cast(0 as boolean)] > b.col_map_bool_timestamp[cast(0 as boolean)]                     where a.col_map_bigint_string[88] is null;
+-----------------------------------------------------+-----------------------------------+
| count(a.col_map_bool_timestamp[CAST(0 AS BOOLEAN)]) | count(b.col_map_string_date['+']) |
+-----------------------------------------------------+-----------------------------------+
|                                                5863 |                              1517 |
+-----------------------------------------------------+-----------------------------------+
1 row in set (0.04 sec)
