### ISSUE TITLE
Wrong result from LAST_VALUE of Window functions

### ISSUE THREAD

**Issue by lwlei** [StarRocks/starrocks#14983]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE
```
CREATE TABLE `test` (
  `pt` date NOT NULL DEFAULT "1970-01-01" COMMENT "",
  `one_level_category_id` bigint(20) NOT NULL DEFAULT "0" COMMENT "",
  `sku_id` bigint(20) NOT NULL DEFAULT "0" COMMENT "",
  `inv_num` bigint(20) NOT NULL DEFAULT "0" COMMENT "",
  `statistics_date` varchar(128) NOT NULL DEFAULT "1970-01-01" COMMENT ""
) ENGINE=OLAP 
UNIQUE KEY(`pt`, `one_level_category_id`, `sku_id`)
COMMENT "OLAP"
PARTITION BY RANGE(`pt`)
(PARTITION p20221118 VALUES [('2022-11-18'), ('2022-11-19')),
PARTITION p20221119 VALUES [('2022-11-19'), ('2022-11-20')),
PARTITION p20221120 VALUES [('2022-11-20'), ('2022-11-21')),
PARTITION p20221121 VALUES [('2022-11-21'), ('2022-11-22')),
PARTITION p20221122 VALUES [('2022-11-22'), ('2022-11-23')),
PARTITION p20221123 VALUES [('2022-11-23'), ('2022-11-24')),
PARTITION p20221124 VALUES [('2022-11-24'), ('2022-11-25')),
PARTITION p20221125 VALUES [('2022-11-25'), ('2022-11-26')),
PARTITION p20221126 VALUES [('2022-11-26'), ('2022-11-27')))
DISTRIBUTED BY HASH(`sku_id`) BUCKETS 2 
PROPERTIES (
"replication_num" = "3",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-712",
"dynamic_partition.end" = "3",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "2",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
```
2. INSERT INTO
```
INSERT INTO `test` (`pt`,`one_level_category_id`,`sku_id`,`inv_num`) VALUES ('2022-11-24',0,123,122);
INSERT INTO `test` (`pt`,`one_level_category_id`,`sku_id`,`inv_num`) VALUES ('2022-11-22',1,123,111);
INSERT INTO `test` (`pt`,`one_level_category_id`,`sku_id`,`inv_num`) VALUES ('2022-11-25',0,123,125);
INSERT INTO `test` (`pt`,`one_level_category_id`,`sku_id`,`inv_num`) VALUES ('2022-11-26',0,123,126);
INSERT INTO `test` (`pt`,`one_level_category_id`,`sku_id`,`inv_num`) VALUES ('2022-11-23',0,123,111);
```
3. SELECT
```
select DATE_FORMAT(shssd.pt, '%Y%u') as week,
       pt,
       inv_num,
       ROW_NUMBER() OVER(PARTITION BY DATE_FORMAT(shssd.pt, '%Y%u') ORDER BY shssd.pt)  AS rn,
       LAST_VALUE(shssd.inv_num) over(PARTITION BY DATE_FORMAT(shssd.pt, '%Y%u') order by shssd.pt desc) AS last_inv
  from test shssd
 WHERE shssd.pt between '2022-11-18'
   and '2022-12-27'
```

### Expected behavior (Required)
The values of column "last_inv" are all 111. 

### Real behavior (Required)
```
MySQL [metabase_sr_test]> select DATE_FORMAT(shssd.pt, '%Y%u') as week,
    ->        pt,
    ->        inv_num,
    ->        ROW_NUMBER() OVER(PARTITION BY DATE_FORMAT(shssd.pt, '%Y%u') ORDER BY shssd.pt)  AS rn,
    ->        LAST_VALUE(shssd.inv_num) over(PARTITION BY DATE_FORMAT(shssd.pt, '%Y%u') order by shssd.pt desc) AS last_inv
    ->   from stock_health_sku_statistics_day shssd
    ->  WHERE shssd.pt between '2022-11-18'
    ->    and '2022-12-27';
+--------+------------+---------+------+----------+
| week   | pt         | inv_num | rn   | last_inv |
+--------+------------+---------+------+----------+
| 202247 | 2022-11-26 |     126 |    5 |      126 |
| 202247 | 2022-11-25 |     125 |    4 |      125 |
| 202247 | 2022-11-24 |     122 |    3 |      122 |
| 202247 | 2022-11-23 |     111 |    2 |      111 |
| 202247 | 2022-11-22 |     111 |    1 |      111 |
+--------+------------+---------+------+----------+
5 rows in set (0.01 sec)

MySQL [metabase_sr_test]> select DATE_FORMAT(shssd.pt, '%Y%u') as week,
    ->        pt,
    ->        inv_num,
    ->        ROW_NUMBER() OVER(PARTITION BY DATE_FORMAT(shssd.pt, '%Y%u') ORDER BY shssd.pt)  AS rn,
    ->        FIRST_VALUE(shssd.inv_num) over(PARTITION BY DATE_FORMAT(shssd.pt, '%Y%u') order by shssd.pt desc) AS first_inv
    ->   from stock_health_sku_statistics_day shssd
    ->  WHERE shssd.pt between '2022-11-18'
    ->    and '2022-12-27';
+--------+------------+---------+------+-----------+
| week   | pt         | inv_num | rn   | first_inv |
+--------+------------+---------+------+-----------+
| 202247 | 2022-11-26 |     126 |    5 |       126 |
| 202247 | 2022-11-25 |     125 |    4 |       126 |
| 202247 | 2022-11-24 |     122 |    3 |       126 |
| 202247 | 2022-11-23 |     111 |    2 |       126 |
| 202247 | 2022-11-22 |     111 |    1 |       126 |
+--------+------------+---------+------+-----------+
5 rows in set (0.01 sec)
```
![image](https://user-images.githubusercontent.com/49778699/206652070-370eba07-f16c-489f-95a6-7b800eda2d52.png)

### StarRocks version (Required)
```
MySQL [metabase_sr_test]> select current_version();
+-------------------+
| current_version() |
+-------------------+
| 2.2.10 b101696    |
+-------------------+
1 row in set (0.01 sec)
```

**Comment by lwlei** [comment]
2022-11-24 First issue.
![image](https://user-images.githubusercontent.com/49778699/206657839-3c7853dd-6d1f-413a-ae93-9abb87e16d65.png)

**Comment by liuyehcf** [comment]
It's the expected behavior.

the default window of `first_value` and `last_value` is `ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW`

* for the first line, window is `(126)`, so first value is `126` and last value is `126`
* for the second line, window is `(126, 125)`, so first value is `126` and last value is `125`
* for the third line, window is `(126, 125, 122)`, so first value is `126` and last value is `122`
* for the forth line, window is `(126, 125, 122, 111)`, so first value is `126` and last value is `111`
* for the fifth line, window is `(126, 125, 122, 111, 111)`, so first value is `126` and last value is `111`

so the first_value is `(126, 126, 126, 126, 126)` and last_value is `(126, 125, 122, 111, 111)`

You can specify the window to `ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING` so as to get your epxected output.

```
select DATE_FORMAT(shssd.pt, '%Y%u') as week,
       pt,
       inv_num,
       ROW_NUMBER() OVER(PARTITION BY DATE_FORMAT(shssd.pt, '%Y%u') ORDER BY shssd.pt)  AS rn,
       LAST_VALUE(shssd.inv_num) over(PARTITION BY DATE_FORMAT(shssd.pt, '%Y%u') order by shssd.pt desc ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS last_inv
  from test shssd
 WHERE shssd.pt between '2022-11-18'
   and '2022-12-27';

+--------+------------+---------+----+----------+
| week   | pt         | inv_num | rn | last_inv |
+--------+------------+---------+----+----------+
| 202247 | 2022-11-26 | 126     | 5  | 111      |
| 202247 | 2022-11-25 | 125     | 4  | 111      |
| 202247 | 2022-11-24 | 122     | 3  | 111      |
| 202247 | 2022-11-23 | 111     | 2  | 111      |
| 202247 | 2022-11-22 | 111     | 1  | 111      |
+--------+------------+---------+----+----------+
```

**Comment by lwlei** [comment]
https://docs.starrocks.io/zh-cn/latest/sql-reference/sql-functions/Window_function#%E4%BD%BF%E7%94%A8-last_value-%E7%AA%97%E5%8F%A3%E5%87%BD%E6%95%B0

**Comment by lwlei** [comment]
> It's the expected behavior.
> 
> the default window of `first_value` and `last_value` is `ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW`
> 
> * for the first line, window is `(126)`, so first value is `126` and last value is `126`
> * for the second line, window is `(126, 125)`, so first value is `126` and last value is `125`
> * for the third line, window is `(126, 125, 122)`, so first value is `126` and last value is `122`
> * for the forth line, window is `(126, 125, 122, 111)`, so first value is `126` and last value is `111`
> * for the fifth line, window is `(126, 125, 122, 111, 111)`, so first value is `126` and last value is `111`
> 
> so the first_value is `(126, 126, 126, 126, 126)` and last_value is `(126, 125, 122, 111, 111)`
> 
> You can specify the window to `ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING` so as to get your epxected output.
> 
> ```
> select DATE_FORMAT(shssd.pt, '%Y%u') as week,
>        pt,
>        inv_num,
>        ROW_NUMBER() OVER(PARTITION BY DATE_FORMAT(shssd.pt, '%Y%u') ORDER BY shssd.pt)  AS rn,
>        LAST_VALUE(shssd.inv_num) over(PARTITION BY DATE_FORMAT(shssd.pt, '%Y%u') order by shssd.pt desc ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS last_inv
>   from test shssd
>  WHERE shssd.pt between '2022-11-18'
>    and '2022-12-27';
> 
> +--------+------------+---------+----+----------+
> | week   | pt         | inv_num | rn | last_inv |
> +--------+------------+---------+----+----------+
> | 202247 | 2022-11-26 | 126     | 5  | 111      |
> | 202247 | 2022-11-25 | 125     | 4  | 111      |
> | 202247 | 2022-11-24 | 122     | 3  | 111      |
> | 202247 | 2022-11-23 | 111     | 2  | 111      |
> | 202247 | 2022-11-22 | 111     | 1  | 111      |
> +--------+------------+---------+----+----------+
> ```

https://docs.starrocks.io/zh-cn/latest/sql-reference/sql-functions/Window_function#%E4%BD%BF%E7%94%A8-last_value-%E7%AA%97%E5%8F%A3%E5%87%BD%E6%95%B0
