### ISSUE TITLE
routine load bug

### ISSUE THREAD

**Issue by gaigaikuaipao** [StarRocks/starrocks#1501]
### Steps to reproduce the behavior (Required)
When using routine load to synchronize Kafka data. Kafka downtime caused starrocks to fail to link normally. Need to restart before it can be normal

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by gengjun-git** [comment]
What do you mean "Kafka downtime caused starrocks to fail to link normally"? Are all services unavailable? Or is it just the routine load that doesn't work?

**Comment by gaigaikuaipao** [comment]
The link is not available through JDBC, but the viewing status and page are fine. The log always reports that the kafka link is abnormal



发自我的iPhone


------------------ Original ------------------
From: gengjun-git ***@***.***&gt;
Date: Tue,Nov 23,2021 7:30 PM
To: StarRocks/starrocks ***@***.***&gt;
Cc: gaigaikuaipao ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [StarRocks/starrocks] routine load bug (Issue #1501)





 
What do you mean "Kafka downtime caused starrocks to fail to link normally"? Are all services unavailable? Or is it just the routine load that doesn't work?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gengjun-git** [comment]
Thank you, we will try to reproduce the problem and fix it.
