### ISSUE TITLE
lpad/rpad function support default value

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#15021]
## Feature request
StarRocks already support the rpad function and lpad function. However, the third parameter is not optional.
For easy to use purpose, **it's better to make the third value optional with a default value ' ', a single blank.** 
That means:

1. For lpad: https://docs.starrocks.io/en-us/latest/sql-reference/sql-functions/string-functions/lpad
It will be like: 
```
VARCHAR lpad(VARCHAR str, INT len [, VARCHAR pad])
```

```
SELECT lpad("hi", 5);
```
will be equal to 
```
SELECT lpad("hi", 5, " ");
```
and returns 
```
+---------------------+
| lpad('hi', 5)       |
+---------------------+
|      hi             |
+---------------------+
```

2. For rpad :https://docs.starrocks.io/en-us/latest/sql-reference/sql-functions/string-functions/rpad
```
VARCHAR rpad(VARCHAR str, INT len [, VARCHAR pad])
```

```
SELECT rpad("hi", 5);
```
will be equal to 
```
SELECT rpad("hi", 5, " ");
```
and returns 
```
+---------------------+
| lpad('hi', 5) |
+---------------------+
| hi                    |
+---------------------+
```

**Comment by predator4ann** [comment]
@kateshaowanjou Sure, you can assign the issue to me. Let me know if you have any further questions or concerns.

**Comment by Moonm3n** [comment]
Hi @kateshaowanjou , I would like to try working on the rpad issue. Could you assign it to me? Thank you!
