### ISSUE TITLE
bitmap_to_array不支持unsigned bigint

### ISSUE THREAD

**Issue by rendason** [StarRocks/starrocks#1503]
### Steps to reproduce the behavior (Required)
-- BIGINT数据范围：[-9223372036854775808, 9223372036854775807]
-- SQL_1: 
select bitmap_to_array(to_bitmap(9223372036854775808));
--SQL_2:
select bitmap_to_string(to_bitmap(9223372036854775808));

### Expected behavior (Required)
SQL_1输出: [9223372036854775808]
SQL_2输出: 9223372036854775808

### Real behavior (Required)
SQL_1输出: [-9223372036854775808]
SQL_2输出: 9223372036854775808

### StarRocks version (Required)
1.19.1 65e87c3

**Comment by stdpain** [comment]
This is because starrocks does not support the uint64 data type at the moment, bigint is the int64 type
