### ISSUE TITLE
ALTER SYSTEM ADD FOLLOWER introduces duplicates.

### ISSUE THREAD

**Issue by didip** [StarRocks/starrocks#15042]
### Steps to reproduce the behavior (Required)
1. `ALTER SYSTEM ADD FOLLOWER 'my-fqdn-1:9010'`. `my-fqdn-1` IP is: 10.1.2.3.
2. Restart `my-fqdn-1`. It's IP is now 10.1.3.4.
3. Run `ALTER SYSTEM ADD FOLLOWER 'my-fqdn-1:9010'` again.

### Expected behavior (Required)
`my-fqdn-1` should not be added.

### Real behavior (Required)
`my-fqdn-1` is added. Now my system have two `my-fqdn-1`. The code should check uniqueness based on FQDN and port. If FQDN is not turned on, use IP and port.

### StarRocks version (Required)
Latest 2.5 branch.

**Comment by waittttting** [comment]
I followed the steps you said, but the problem you mentioned did not occur, do you have more information to provide?
