### ISSUE TITLE
support count_if

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#15063]
StarRocks already support count() and if().
However, this function is easier to implement count(if()). 
It is already supported in many database systems like clickhouse, snowflake, bigquery, databricks and so on.

## Description: 
```
COUNT_IF( <condition> )
```
The condition:
1. Can include multiple column, like column a>column b
2. Can use multiple conditions, and use 'and' to link
The count:
1. has the same behavior with the native count when dealing with null, that is, ignore

some examples:
```
MySQL [simo]> select * from table1;
+------+------+
| id   | id1  |
+------+------+
|    1 | NULL |
|    1 |    1 |
|    2 |    1 |
+------+------+
3 rows in set (0.01 sec)

MySQL [simo]> select countif(id>id1) from table1;
+------------+
| count(id1) |
+------------+
|          1 |
+------------+
1 row in set (0.02 sec)

MySQL [simo]> select countif(true) from table1;
+-------------+
| count(TRUE) |
+-------------+
|           3 |
+-------------+
1 row in set (0.02 sec)
```

**Comment by tomscut** [comment]
Hi @wangsimo0, please assign this to me. Thanks!

**Comment by ruyliu** [comment]
Hi @wangsimo0 , please assign this to me. Thanks!

**Comment by mlimwxxnn** [comment]
Hi @kateshaowanjou , Could you please assign `count_if` to me? thx!

**Comment by kateshaowanjou** [comment]
@mlimwxxnn Keep up the good work!!💪
