### ISSUE TITLE
support array_agg(distinct)

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#15064]
StarRocks already support `array_agg` and `array_distinct`. However, if user want to implement array agg with distinct value, they need to use `array_agg(array_distinct())`. 
So the better way is to support `DISTINCT` in  `array_agg`. Same problem happens in `group_concat`.

**Comment by tomscut** [comment]
Hi @wangsimo0, please assign this to me. Thanks!

**Comment by ruyliu** [comment]
@wangsimo0 , please assign this to me. Thanks!

**Comment by happut** [comment]
Hi @kateshaowanjou , Could you please assign this issue to me? Thank you!
