### ISSUE TITLE
after insert into, be is closed every time

### ISSUE THREAD

**Issue by skypan** [StarRocks/starrocks#1519]
### Steps to reproduce the behavior (Required)
1. create table tag_list(
    idcard varchar(50) not null
)
ENGINE = olap
PRIMARY KEY(idcard)
DISTRIBUTED BY HASH(idcard) BUCKETS 32
PROPERTIES (
    "replication_num" = "1"
);

// success
alter table tag_list ADD column tag1 varchar(200);
// success
alter table tag_list ADD column tag2 varchar(200);
// failed
alter table tag_list ADD column tag3 varchar(200);
the tip is "[42000][1064] tablet 4056758 has few replicas: 0", the tip show often

2. insert into tag_list(idcard, tag1) values ("001", "男性");
the tip is "[42000][1064] Execute timeout"，and after that be is closed

after i start the be, i run the sql "insert into tag_list(idcard, tag1) values ("001", "男性");", the same error occurs, and be closed

the be.info is below:

I1123 17:07:00.248281 29250 tablet_manager.cpp:739] Found the best tablet to compact. compaction_type=cumulative tablet_id=94722 highest_score=2
I1123 17:07:01.275981 29250 tablet_manager.cpp:739] Found the best tablet to compact. compaction_type=cumulative tablet_id=94720 highest_score=2
I1123 17:07:02.147642 29331 internal_service.cpp:242] exec plan fragment, fragment_instance_id=b8a8c6fc-4c3c-11ec-8238-0242661cf74d, coord=TNetworkAddress(hostname=172.17.0.1, port=9020), backend=0
I1123 17:07:02.147706 29331 plan_fragment_executor.cpp:67] Prepare(): query_id=b8a8c6fc-4c3c-11ec-8238-0242661cf74c fragment_instance_id=b8a8c6fc-4c3c-11ec-8238-0242661cf74d backend_num=0
I1123 17:07:02.148025 29331 plan_fragment_executor.cpp:126] Using query memory limit: 2.00 GB
I1123 17:07:02.148150 29331 exec_node.cpp:577] exec node: UNION_NODE, use vectorized:1
I1123 17:07:02.148363 29223 plan_fragment_executor.cpp:235] Open(): fragment_instance_id=b8a8c6fc-4c3c-11ec-8238-0242661cf74d
I1123 17:07:02.148948 29223 plan_fragment_executor.cpp:691] Fragment b8a8c6fc-4c3c-11ec-8238-0242661cf74d:(Active: 90.934us, non-child: 30.87%)
   - AverageThreadTokens: 0.00
   - MemoryLimit: 2.00 GB
   - PeakMemoryUsage: 32.00 KB
   - PeakReservation: 0
   - PeakUsedReservation: 0
   - RowsProduced: 1
  BlockMgr:
     - BlockWritesOutstanding: 0
     - BlocksCreated: 0
     - BlocksRecycled: 0
     - BufferedPins: 0
     - BytesWritten: 0
     - MaxBlockSize: 8.00 MB
     - TotalBufferWaitTime: 0.000ns
     - TotalReadBlockTime: 0.000ns
  DataBufferSender (dst_fragment_instance_id=b8a8c6fc-4c3c-11ec-8238-0242661cf74d):
     - AppendBatchTime: 13.710us
       - ResultRendTime: 1.497us
       - TupleConvertTime: 5.313us
     - NumSentRows: 1
  UNION_NODE (id=0):(Active: 62.866us, non-child: 69.13%)
     - PeakMemoryUsage: 0
     - RowsReturned: 1
     - RowsReturnedRate: 15.91 K/sec
I1123 17:07:02.200824 29331 internal_service.cpp:242] exec plan fragment, fragment_instance_id=b8b0b640-4c3c-11ec-8238-0242661cf74d, coord=TNetworkAddress(hostname=172.17.0.1, port=9020), backend=0
I1123 17:07:02.200858 29331 plan_fragment_executor.cpp:67] Prepare(): query_id=b8b0b640-4c3c-11ec-8238-0242661cf74c fragment_instance_id=b8b0b640-4c3c-11ec-8238-0242661cf74d backend_num=0
I1123 17:07:02.200909 29331 plan_fragment_executor.cpp:126] Using query memory limit: 2.00 GB
I1123 17:07:02.200953 29331 exec_node.cpp:577] exec node: UNION_NODE, use vectorized:1
I1123 17:07:02.201341 29223 plan_fragment_executor.cpp:235] Open(): fragment_instance_id=b8b0b640-4c3c-11ec-8238-0242661cf74d
I1123 17:07:02.202054 29328 tablets_channel.cpp:60] Opening tablets channel=(id=b8b0b6404c3c11ec-82380242661cf74c,index_id=4056757) tablets num=32 timeout=300 vectorized=1
I1123 17:07:02.202484 29408 tablet_sink.cpp:1485] Exiting consumer thread, no running channel
F1123 17:07:02.202828 29306 column_aggregate_func.cpp:599] Check failed: false bad agg method NONE for column: tag1
I1123 17:07:02.308646 29250 tablet_manager.cpp:739] Found the best tablet to compact. compaction_type=cumulative tablet_id=94716 highest_score=2

### StarRocks version (Required)
 1.18.5

**Comment by chaoyli** [comment]
Primary Key is a test feature in StarRocks-1.18.5.
The problem has already fixed in 1.19.x 
It's better to upgrade to 1.19.2 (https://github.com/StarRocks/starrocks/tree/1.19.2)
