### ISSUE TITLE
Hive catalog supports hudi/iceberg table?

### ISSUE THREAD

**Issue by melin** [StarRocks/starrocks#15198]
hudi/iceberg table 元数据注册到hive metastore，如果只注册 hive catalog，能够直接通过hive catalog 读取hudi/iceberg 表数据。
实际情况，hms 可能同时存储了parquet，huid，iceberg 等不同格式的表.

**Comment by leoyy0316** [comment]
if you want to select hudi/iceberg table，you can use hudi/iceberg catalog. doc: https://docs.starrocks.io/en-us/latest/data_source/catalog/catalog_overview

**Comment by melin** [comment]
> hms 可能同时存储了parquet，huid，iceberg 等不同格式的表.

hms 可能同时存储了parquet，huid，iceberg 等不同格式的表，创建多个不同表不是很友好使用方式。建议hive catalog 中根据表类型，自动加载hudi或者iceberg 表，理论上可以做到的。flink catalog 也存在这个问题，如果只有hudi和iceberg 一种类型表，注册catalog 名为spark_catalog，是可以屏蔽这个问题。
