### ISSUE TITLE
Support JDBC Catalog

### ISSUE THREAD

**Issue by melin** [StarRocks/starrocks#15200]
Support JDBC Catalog，类似hive catalog，方便访问mysql、oracle、pg、sqlserver 等数据库表

**Comment by imay** [comment]
it is already supported.

**Comment by melin** [comment]
文档中没有提到：
![image](https://user-images.githubusercontent.com/1145830/207747193-56441dc1-312e-40e5-830e-e982fffc0d75.png)

**Comment by melin** [comment]
是否支持插件方式自定义catalog？

**Comment by yangrong688** [comment]
> it is already supported.

Hi @imay, is there any document about jdbc external catalog?

jdbc external table has already been supported, but it's very time consuming for us to use it when we need to create many external tables.
