### ISSUE TITLE
pom.xml  dependencies are obsolete: sleepycat version 7.3.7 not found 

### ISSUE THREAD

**Issue by mklzl** [StarRocks/starrocks#153]
Can I use this version   ：com.sleepycat je-18.3.12 
maven repository not found sleepycat version 7.3.7

**Comment by gengjun-git** [comment]
You can download the jar from https://starrocks-public.oss-cn-beijing.aliyuncs.com/je-7.3.7.jar, and `mvn install` to your local repository

**Comment by mklzl** [comment]
ok,thank you



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 10, 2021 19:13 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [StarRocks/starrocks] pom.xml  dependencies are obsolete: sleepycat version 7.3.7 not found  (#153)




 
You can download the jar from https://starrocks-public.oss-cn-beijing.aliyuncs.com/je-7.3.7.jar, and mvn install to your local repository
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gengjun-git** [comment]
I have checked the compile, and it can be compiled successfully when I remove the local repository. Maybe it is a false report, can you redo problem @rickif

**Comment by rickif** [comment]
Maven >= 3.8.1 would block HTTP repository, which we use for the je-7.3.7. It would be fixed in #452 .
