### ISSUE TITLE
Query failed with error: ERROR 1064 (HY000): [E1003]Fail to compress request, compress_type=0 Does anyone have more insights?

### ISSUE THREAD

**Issue by fenganli** [StarRocks/starrocks#15316]
### Steps to reproduce the behavior (Required)
For query and be log, please see this gist:
https://gist.github.com/fenganli/e33125fdb081ca729d5472530011d33d

Also see the chat with Allen:
Allen Li:
It may be the packet to compress is larger than LZ4 upper limit
set  transmission_compression_type = NO_COMPRESSION
Have a try

Fengan Li:
The same error unfortunately: ERROR 1064 (HY000): [E1003]Fail to compress request, compress_type=0

Allen Li
I get the reason. The brpc do not support the 2G packet. It’s need to use this http interface to do it.

### Expected behavior (Required)
The query succeeded on a smaller scale of data.

### Real behavior (Required)
Query failed with error: ERROR 1064 (HY000): [E1003]Fail to compress request, compress_type=0 Does anyone have more insights?

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 2.5

**Comment by fzhedu** [comment]
pls set these and retry
```
set transmission_compression_type = zstd;
set transmission_encode_level = 0;
```

**Comment by fenganli** [comment]
The same error unfortunately: ERROR 1064 (HY000): [E1003]Fail to compress request, compress_type=0

**Comment by fzhedu** [comment]
@fenganli do you check the previous settings successful? the same result is unexpected.

**Comment by fzhedu** [comment]
if exceed 2GB when using iobuf, the message is printed:
```
W0313 17:06:43.236339 75043 sink_buffer.cpp:418] 2GB rpc size = 2147484748 p size 0
E0313 17:06:44.050314 77771 baidu_rpc_protocol.cpp:115] body_size=2147484897 from 172.26.92.195:51330 is too large
E0313 17:06:44.050360 77771 input_messenger.cpp:115] A message from 172.26.92.195:51330(protocol=baidu_std) is bigger than 2147483648 bytes, the connection will be closed. Set max_body_size to allow bigger messages
W0313 17:06:44.050383 77771 input_messenger.cpp:250] Close Socket{id=896 fd=288 addr=172.26.92.195:51330:8467} (0x63100012c800): too big data
W0313 17:06:44.050490 77686 socket.cpp:1615] Fail to keep-write into Socket{id=256 fd=287 addr=172.26.92.195:8467:51330} (0x631000104800): Connection reset by peer [104]
W0313 17:06:44.257230 77686 disposable_closure.h:50] brpc failed, error=Host is down, error_text=[E104]Fail to keep-write into Socket{id=256 fd=287 addr=172.26.92.195:8467:51330} (0x0x631000104800): Connection reset by peer [R1][E112]Not connected to 172.26.92.195:8467 yet, server_id=256 [R2][E112]Not connected to 172.26.92.195:8467 yet, server_id=256 [R3][E112]Not connected to 172.26.92.195:8467 yet, server_id=256
W0313 17:06:44.257328 77686 sink_buffer.cpp:340] transmit chunk rpc failed:5ee1f4dd-c17e-11ed-b042-0242ca170dfd
W0313 17:06:44.258803 74907 exec_state_reporter.cpp:142] Retrying ReportExecStatus: No more data to read.
```
