### ISSUE TITLE
Add new function support

### ISSUE THREAD

**Issue by chaoyli** [StarRocks/starrocks#15385]
## Enhancement
1. LAST_DAY
```
LAST_DAY in month, like LAST_DAY("2022-09-10") -> "2022-09-30"
LAST_DAY("2022-02-19") -> "2022-02-28"
LAST_DAY("2024-02-19") -> "2022-02-29"
```

2. CALENDAR_WEEK 

3.  PATINDEX

**Comment by rcauble** [comment]
Here's some more info on CALENDAR_WEEK -- the SQL function we need is the same as Vertica's `WEEK_ISO`. 

The following 2 examples shows the difference between `WEEK_ISO` and Starrock's current `WEEK` function. The left column consists of unix-timestamps corresponding to the date range from 1/1/2001 to 1/1/2002, incrementing by 1 day. Most datapoints are off by one, but roughly once a week it exactly matches, so it's not a consistent addition.

`WEEK_ISO`

```
"1000080000000","37"
"1000166400000","37"
"1000252800000","37"
"1000339200000","37"
"1000425600000","37"
"1000512000000","37"
"1000598400000","37"
"1000684800000","38"
"1000771200000","38"
"1000857600000","38"
"1000944000000","38"
"1001030400000","38"
"1001116800000","38"
"1001203200000","38"
"1001289600000","39"
"1001376000000","39"
"1001462400000","39"
"1001548800000","39"
"1001635200000","39"
"1001721600000","39"
"1001808000000","39"
"1001894400000","40"
"1001980800000","40"
"1002067200000","40"
"1002153600000","40"
"1002240000000","40"
"1002326400000","40"
"1002412800000","40"
"1002499200000","41"
"1002585600000","41"
"1002672000000","41"
"1002758400000","41"
"1002844800000","41"
"1002931200000","41"
"1003017600000","41"
"1003104000000","42"
"1003190400000","42"
"1003276800000","42"
"1003363200000","42"
"1003449600000","42"
"1003536000000","42"
"1003622400000","42"
"1003708800000","43"
"1003795200000","43"
"1003881600000","43"
"1003968000000","43"
"1004054400000","43"
"1004140800000","43"
"1004227200000","43"
"1004313600000","44"
"1004400000000","44"
"1004486400000","44"
"1004572800000","44"
"1004659200000","44"
"1004745600000","44"
"1004832000000","44"
"1004918400000","45"
"1005004800000","45"
"1005091200000","45"
"1005177600000","45"
"1005264000000","45"
"1005350400000","45"
"1005436800000","45"
"1005523200000","46"
"1005609600000","46"
"1005696000000","46"
"1005782400000","46"
"1005868800000","46"
"1005955200000","46"
"1006041600000","46"
"1006128000000","47"
"1006214400000","47"
"1006300800000","47"
"1006387200000","47"
"1006473600000","47"
"1006560000000","47"
"1006646400000","47"
"1006732800000","48"
"1006819200000","48"
"1006905600000","48"
"1006992000000","48"
"1007078400000","48"
"1007164800000","48"
"1007251200000","48"
"1007337600000","49"
"1007424000000","49"
"1007510400000","49"
"1007596800000","49"
"1007683200000","49"
"1007769600000","49"
"1007856000000","49"
"1007942400000","50"
"1008028800000","50"
"1008115200000","50"
"1008201600000","50"
"1008288000000","50"
"1008374400000","50"
"1008460800000","50"
"1008547200000","51"
"1008633600000","51"
"1008720000000","51"
"1008806400000","51"
"1008892800000","51"
"1008979200000","51"
"1009065600000","51"
"1009152000000","52"
"1009238400000","52"
"1009324800000","52"
"1009411200000","52"
"1009497600000","52"
"1009584000000","52"
"1009670400000","52"
"1009756800000","1"
"1009843200000","1"
"978307200000","1"
"978393600000","1"
"978480000000","1"
"978566400000","1"
"978652800000","1"
"978739200000","1"
"978825600000","1"
"978912000000","2"
"978998400000","2"
"979084800000","2"
"979171200000","2"
"979257600000","2"
"979344000000","2"
"979430400000","2"
"979516800000","3"
"979603200000","3"
"979689600000","3"
"979776000000","3"
"979862400000","3"
"979948800000","3"
"980035200000","3"
"980121600000","4"
"980208000000","4"
"980294400000","4"
"980380800000","4"
"980467200000","4"
"980553600000","4"
"980640000000","4"
"980726400000","5"
"980812800000","5"
"980899200000","5"
"980985600000","5"
"981072000000","5"
"981158400000","5"
"981244800000","5"
"981331200000","6"
"981417600000","6"
"981504000000","6"
"981590400000","6"
"981676800000","6"
"981763200000","6"
"981849600000","6"
"981936000000","7"
"982022400000","7"
"982108800000","7"
"982195200000","7"
"982281600000","7"
"982368000000","7"
"982454400000","7"
"982540800000","8"
"982627200000","8"
"982713600000","8"
"982800000000","8"
"982886400000","8"
"982972800000","8"
"983059200000","8"
"983145600000","9"
"983232000000","9"
"983318400000","9"
"983404800000","9"
"983491200000","9"
"983577600000","9"
"983664000000","9"
"983750400000","10"
"983836800000","10"
"983923200000","10"
"984009600000","10"
"984096000000","10"
"984182400000","10"
"984268800000","10"
"984355200000","11"
"984441600000","11"
"984528000000","11"
"984614400000","11"
"984700800000","11"
"984787200000","11"
"984873600000","11"
"984960000000","12"
"985046400000","12"
"985132800000","12"
"985219200000","12"
"985305600000","12"
"985392000000","12"
"985478400000","12"
"985564800000","13"
"985651200000","13"
"985737600000","13"
"985824000000","13"
"985910400000","13"
"985996800000","13"
"986083200000","13"
"986169600000","14"
"986256000000","14"
"986342400000","14"
"986428800000","14"
"986515200000","14"
"986601600000","14"
"986688000000","14"
"986774400000","15"
"986860800000","15"
"986947200000","15"
"987033600000","15"
"987120000000","15"
"987206400000","15"
"987292800000","15"
"987379200000","16"
"987465600000","16"
"987552000000","16"
"987638400000","16"
"987724800000","16"
"987811200000","16"
"987897600000","16"
"987984000000","17"
"988070400000","17"
"988156800000","17"
"988243200000","17"
"988329600000","17"
"988416000000","17"
"988502400000","17"
"988588800000","18"
"988675200000","18"
"988761600000","18"
"988848000000","18"
"988934400000","18"
"989020800000","18"
"989107200000","18"
"989193600000","19"
"989280000000","19"
"989366400000","19"
"989452800000","19"
"989539200000","19"
"989625600000","19"
"989712000000","19"
"989798400000","20"
"989884800000","20"
"989971200000","20"
"990057600000","20"
"990144000000","20"
"990230400000","20"
"990316800000","20"
"990403200000","21"
"990489600000","21"
"990576000000","21"
"990662400000","21"
"990748800000","21"
"990835200000","21"
"990921600000","21"
"991008000000","22"
"991094400000","22"
"991180800000","22"
"991267200000","22"
"991353600000","22"
"991440000000","22"
"991526400000","22"
"991612800000","23"
"991699200000","23"
"991785600000","23"
"991872000000","23"
"991958400000","23"
"992044800000","23"
"992131200000","23"
"992217600000","24"
"992304000000","24"
"992390400000","24"
"992476800000","24"
"992563200000","24"
"992649600000","24"
"992736000000","24"
"992822400000","25"
"992908800000","25"
"992995200000","25"
"993081600000","25"
"993168000000","25"
"993254400000","25"
"993340800000","25"
"993427200000","26"
"993513600000","26"
"993600000000","26"
"993686400000","26"
"993772800000","26"
"993859200000","26"
"993945600000","26"
"994032000000","27"
"994118400000","27"
"994204800000","27"
"994291200000","27"
"994377600000","27"
"994464000000","27"
"994550400000","27"
"994636800000","28"
"994723200000","28"
"994809600000","28"
"994896000000","28"
"994982400000","28"
"995068800000","28"
"995155200000","28"
"995241600000","29"
"995328000000","29"
"995414400000","29"
"995500800000","29"
"995587200000","29"
"995673600000","29"
"995760000000","29"
"995846400000","30"
"995932800000","30"
"996019200000","30"
"996105600000","30"
"996192000000","30"
"996278400000","30"
"996364800000","30"
"996451200000","31"
"996537600000","31"
"996624000000","31"
"996710400000","31"
"996796800000","31"
"996883200000","31"
"996969600000","31"
"997056000000","32"
"997142400000","32"
"997228800000","32"
"997315200000","32"
"997401600000","32"
"997488000000","32"
"997574400000","32"
"997660800000","33"
"997747200000","33"
"997833600000","33"
"997920000000","33"
"998006400000","33"
"998092800000","33"
"998179200000","33"
"998265600000","34"
"998352000000","34"
"998438400000","34"
"998524800000","34"
"998611200000","34"
"998697600000","34"
"998784000000","34"
"998870400000","35"
"998956800000","35"
"999043200000","35"
"999129600000","35"
"999216000000","35"
"999302400000","35"
"999388800000","35"
"999475200000","36"
"999561600000","36"
"999648000000","36"
"999734400000","36"
"999820800000","36"
"999907200000","36"
"999993600000","36"
```

`WEEK`
"1000080000000","36"
"1000166400000","36"
"1000252800000","36"
"1000339200000","36"
"1000425600000","36"
"1000512000000","36"
"1000598400000","37"
"1000684800000","37"
"1000771200000","37"
"1000857600000","37"
"1000944000000","37"
"1001030400000","37"
"1001116800000","37"
"1001203200000","38"
"1001289600000","38"
"1001376000000","38"
"1001462400000","38"
"1001548800000","38"
"1001635200000","38"
"1001721600000","38"
"1001808000000","39"
"1001894400000","39"
"1001980800000","39"
"1002067200000","39"
"1002153600000","39"
"1002240000000","39"
"1002326400000","39"
"1002412800000","40"
"1002499200000","40"
"1002585600000","40"
"1002672000000","40"
"1002758400000","40"
"1002844800000","40"
"1002931200000","40"
"1003017600000","41"
"1003104000000","41"
"1003190400000","41"
"1003276800000","41"
"1003363200000","41"
"1003449600000","41"
"1003536000000","41"
"1003622400000","42"
"1003708800000","42"
"1003795200000","42"
"1003881600000","42"
"1003968000000","42"
"1004054400000","42"
"1004140800000","42"
"1004227200000","43"
"1004313600000","43"
"1004400000000","43"
"1004486400000","43"
"1004572800000","43"
"1004659200000","43"
"1004745600000","43"
"1004832000000","44"
"1004918400000","44"
"1005004800000","44"
"1005091200000","44"
"1005177600000","44"
"1005264000000","44"
"1005350400000","44"
"1005436800000","45"
"1005523200000","45"
"1005609600000","45"
"1005696000000","45"
"1005782400000","45"
"1005868800000","45"
"1005955200000","45"
"1006041600000","46"
"1006128000000","46"
"1006214400000","46"
"1006300800000","46"
"1006387200000","46"
"1006473600000","46"
"1006560000000","46"
"1006646400000","47"
"1006732800000","47"
"1006819200000","47"
"1006905600000","47"
"1006992000000","47"
"1007078400000","47"
"1007164800000","47"
"1007251200000","48"
"1007337600000","48"
"1007424000000","48"
"1007510400000","48"
"1007596800000","48"
"1007683200000","48"
"1007769600000","48"
"1007856000000","49"
"1007942400000","49"
"1008028800000","49"
"1008115200000","49"
"1008201600000","49"
"1008288000000","49"
"1008374400000","49"
"1008460800000","50"
"1008547200000","50"
"1008633600000","50"
"1008720000000","50"
"1008806400000","50"
"1008892800000","50"
"1008979200000","50"
"1009065600000","51"
"1009152000000","51"
"1009238400000","51"
"1009324800000","51"
"1009411200000","51"
"1009497600000","51"
"1009584000000","51"
"1009670400000","52"
"1009756800000","52"
"1009843200000","0"
"978307200000","0"
"978393600000","0"
"978480000000","0"
"978566400000","0"
"978652800000","0"
"978739200000","0"
"978825600000","1"
"978912000000","1"
"978998400000","1"
"979084800000","1"
"979171200000","1"
"979257600000","1"
"979344000000","1"
"979430400000","2"
"979516800000","2"
"979603200000","2"
"979689600000","2"
"979776000000","2"
"979862400000","2"
"979948800000","2"
"980035200000","3"
"980121600000","3"
"980208000000","3"
"980294400000","3"
"980380800000","3"
"980467200000","3"
"980553600000","3"
"980640000000","4"
"980726400000","4"
"980812800000","4"
"980899200000","4"
"980985600000","4"
"981072000000","4"
"981158400000","4"
"981244800000","5"
"981331200000","5"
"981417600000","5"
"981504000000","5"
"981590400000","5"
"981676800000","5"
"981763200000","5"
"981849600000","6"
"981936000000","6"
"982022400000","6"
"982108800000","6"
"982195200000","6"
"982281600000","6"
"982368000000","6"
"982454400000","7"
"982540800000","7"
"982627200000","7"
"982713600000","7"
"982800000000","7"
"982886400000","7"
"982972800000","7"
"983059200000","8"
"983145600000","8"
"983232000000","8"
"983318400000","8"
"983404800000","8"
"983491200000","8"
"983577600000","8"
"983664000000","9"
"983750400000","9"
"983836800000","9"
"983923200000","9"
"984009600000","9"
"984096000000","9"
"984182400000","9"
"984268800000","10"
"984355200000","10"
"984441600000","10"
"984528000000","10"
"984614400000","10"
"984700800000","10"
"984787200000","10"
"984873600000","11"
"984960000000","11"
"985046400000","11"
"985132800000","11"
"985219200000","11"
"985305600000","11"
"985392000000","11"
"985478400000","12"
"985564800000","12"
"985651200000","12"
"985737600000","12"
"985824000000","12"
"985910400000","12"
"985996800000","12"
"986083200000","13"
"986169600000","13"
"986256000000","13"
"986342400000","13"
"986428800000","13"
"986515200000","13"
"986601600000","13"
"986688000000","14"
"986774400000","14"
"986860800000","14"
"986947200000","14"
"987033600000","14"
"987120000000","14"
"987206400000","14"
"987292800000","15"
"987379200000","15"
"987465600000","15"
"987552000000","15"
"987638400000","15"
"987724800000","15"
"987811200000","15"
"987897600000","16"
"987984000000","16"
"988070400000","16"
"988156800000","16"
"988243200000","16"
"988329600000","16"
"988416000000","16"
"988502400000","17"
"988588800000","17"
"988675200000","17"
"988761600000","17"
"988848000000","17"
"988934400000","17"
"989020800000","17"
"989107200000","18"
"989193600000","18"
"989280000000","18"
"989366400000","18"
"989452800000","18"
"989539200000","18"
"989625600000","18"
"989712000000","19"
"989798400000","19"
"989884800000","19"
"989971200000","19"
"990057600000","19"
"990144000000","19"
"990230400000","19"
"990316800000","20"
"990403200000","20"
"990489600000","20"
"990576000000","20"
"990662400000","20"
"990748800000","20"
"990835200000","20"
"990921600000","21"
"991008000000","21"
"991094400000","21"
"991180800000","21"
"991267200000","21"
"991353600000","21"
"991440000000","21"
"991526400000","22"
"991612800000","22"
"991699200000","22"
"991785600000","22"
"991872000000","22"
"991958400000","22"
"992044800000","22"
"992131200000","23"
"992217600000","23"
"992304000000","23"
"992390400000","23"
"992476800000","23"
"992563200000","23"
"992649600000","23"
"992736000000","24"
"992822400000","24"
"992908800000","24"
"992995200000","24"
"993081600000","24"
"993168000000","24"
"993254400000","24"
"993340800000","25"
"993427200000","25"
"993513600000","25"
"993600000000","25"
"993686400000","25"
"993772800000","25"
"993859200000","25"
"993945600000","26"
"994032000000","26"
"994118400000","26"
"994204800000","26"
"994291200000","26"
"994377600000","26"
"994464000000","26"
"994550400000","27"
"994636800000","27"
"994723200000","27"
"994809600000","27"
"994896000000","27"
"994982400000","27"
"995068800000","27"
"995155200000","28"
"995241600000","28"
"995328000000","28"
"995414400000","28"
"995500800000","28"
"995587200000","28"
"995673600000","28"
"995760000000","29"
"995846400000","29"
"995932800000","29"
"996019200000","29"
"996105600000","29"
"996192000000","29"
"996278400000","29"
"996364800000","30"
"996451200000","30"
"996537600000","30"
"996624000000","30"
"996710400000","30"
"996796800000","30"
"996883200000","30"
"996969600000","31"
"997056000000","31"
"997142400000","31"
"997228800000","31"
"997315200000","31"
"997401600000","31"
"997488000000","31"
"997574400000","32"
"997660800000","32"
"997747200000","32"
"997833600000","32"
"997920000000","32"
"998006400000","32"
"998092800000","32"
"998179200000","33"
"998265600000","33"
"998352000000","33"
"998438400000","33"
"998524800000","33"
"998611200000","33"
"998697600000","33"
"998784000000","34"
"998870400000","34"
"998956800000","34"
"999043200000","34"
"999129600000","34"
"999216000000","34"
"999302400000","34"
"999388800000","35"
"999475200000","35"
"999561600000","35"
"999648000000","35"
"999734400000","35"
"999820800000","35"
"999907200000","35"
"999993600000","36"
```

**Comment by rcauble** [comment]
I also tried `WEEK(TIMESTAMPADD(DAY,6,col))`. That gets closer but still see a number of diffs. For example:

`WEEK_ISO`

```
"1009324800000","52"
"1009411200000","52"
"1009497600000","52"
"1009584000000","52"
"1009670400000","52"
```

`WEEK(TIMESTAMPADD(DAY,6,col))`

```
"1009324800000","0"
"1009411200000","0"
"1009497600000","0"
"1009584000000","0"
"1009670400000","0"
```
