### ISSUE TITLE
[createTableWithLock]The param 'isReplay' is always false

### ISSUE THREAD

**Issue by zhangweiwhim** [StarRocks/starrocks#15393]
Version: 2.0.2~2.20 (we have used versions)

- src: src/main/java/com/starrocks/catalog/Catalog.java
- src: src/main/java/com/starrocks/catalog/Database.java

Question:
first of all [pic-1] & [pic-2]
```java
createTblSuccess = db.createTableWithLock(olapTable, false);
```
```java
// return false if table already exists
    public boolean createTableWithLock(Table table, boolean isReplay) {
```

the param [isReplay] is always false , When the createOlapTable task already sends to BE, the BE cluster has another question and has to restart.
1. Editlog can not Replay that Retry the createOlapTable task will write a new Editlog to BDBJE ?
2. If rename the table name and submit to BE, the old table data in BDBJE how to clean it?

Thx for all of SR 
[pic-1]
<img width="1439" alt="2" src="https://github.com/zhangweiwhim/readme_add_pic/blob/master/%E4%BC%81%E4%B8%9A%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_ed1fc8ca-d019-426d-9a4c-79061d663270.png?raw=true">

[pic-2]
<img width="1439" alt="1" src="https://github.com/zhangweiwhim/readme_add_pic/blob/master/%E4%BC%81%E4%B8%9A%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_111b2aec-8d1d-4586-98a5-69853a8f40ec.png?raw=true">

**Comment by gengjun-git** [comment]
Hello, @zhangweiwhim  the param [isReplay] is true when replaying the create tablet log
![image](https://user-images.githubusercontent.com/54172532/208571715-bbc863cb-9636-47c4-ab9e-bf75ef81e2ba.png)

Rename table just reset the table name and remain its data unchanged.

**Comment by zhangweiwhim** [comment]
@gengjun-git , Thx for your reply,

[Rename table just reset the table name and remain its data unchanged.]

as my questions [If rename the table name and submit to BE, the old table data in BDBJE how to clean it?]
describe more clearly that the cluster was restarted when creating table A( already submit to BE and written into BDBJE),
using another name  B to recreate the table, the A's data in BDBJE how to clean it?

**Comment by gengjun-git** [comment]
Write to bdb (wal) is the last step for creating table. If the cluster is restarted when creating table, there will be no data in BDBJE. And the dirty data on BE will be cleared when BE reports its tablet to FE leader node, because there is not related tablet meta record on FE leader node.

**Comment by zhangweiwhim** [comment]
@gengjun-git got it ，Thx bro

**Comment by zhangweiwhim** [comment]
close
