### ISSUE TITLE
Create a table after drop, the colocate group information is not deleted

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#1539]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE t_1 (
                                    `id` int(18),
                                    `value` varchar(20)
                                )
                                ENGINE=OLAP
                                DUPLICATE KEY(`id`)
                                COMMENT "OLAP"
                                DISTRIBUTED BY HASH(`id`) BUCKETS 3
                                PROPERTIES (
                                    "replication_num" = "1",
                                    "storage_format" = "v2",
                                    "colocate_with" = "group1"
                                );
2. DROP TABLE t_1;
3. CREATE TABLE t_1 (
                                    `id` int(18),
                                    `value` varchar(20)
                                )
                                ENGINE=OLAP
                                DUPLICATE KEY(`id`)
                                COMMENT "OLAP"
                                DISTRIBUTED BY HASH(`id`) BUCKETS 3
                                PROPERTIES (
                                    "replication_num" = "1",
                                    "storage_format" = "v2",
                                    "colocate_with" = "group1"
                                );
4. SHOW PROC '/colocation_group';

### Expected behavior (Required)
there is 1 tableID in group1
### Real behavior (Required)
there are 2 tableIDs in group1
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.0

**Comment by imay** [comment]
@gengjun-git Can you handle it?
