### ISSUE TITLE
Desc external catalog partition table,iceberg/hudi table no partition key for partition columns

### ISSUE THREAD

**Issue by leoyy0316** [StarRocks/starrocks#15394]
### Steps to reproduce the behavior (Required)
iceberg_catalog_01.test.test_iceberg_par
### Expected behavior (Required)
+-------+------------------+------+-------+---------+---------------+
| Field | Type             | Null | Key   | Default | Extra         |
+-------+------------------+------+-------+---------+---------------+
| id    | INT              | Yes  | false | NULL    |               |
| name  | VARCHAR(1048576) | Yes  | false | NULL    |               |
| dt    | VARCHAR(1048576) | Yes  | false | NULL    | partition key |
+-------+------------------+------+-------+---------+---------------+
### Real behavior (Required)
+-------+----------------+------+-------+---------+-------+
| Field | Type           | Null | Key   | Default | Extra |
+-------+----------------+------+-------+---------+-------+
| dt    | VARCHAR(65533) | Yes  | false | NULL    |       |
| name  | VARCHAR(65533) | Yes  | false | NULL    |       |
| id    | BIGINT         | Yes  | false | NULL    |       |
+-------+----------------+------+-------+---------+-------+
### StarRocks version (Required)

**main-branch code**

**Comment by leoyy0316** [comment]
@stephen-shelby pls assign to me

**Comment by wangyouzhuo** [comment]
display partition key in extra column is good for both iceberg/hudi
