### ISSUE TITLE
delete语句where条件中date类型字段不支持函数

### ISSUE THREAD

**Issue by ljkljkkjl** [StarRocks/starrocks#15407]
## Enhancement
建表语句如下：
```
CREATE TABLE `score_board` (
  `id` int(11) NOT NULL COMMENT "",
  `name` varchar(65533) NULL DEFAULT "" COMMENT "",
  `score` int(11) NOT NULL DEFAULT "0" COMMENT "",
 `s_date` DATE not null
)
 ENGINE=OLAP
 DUPLICATE KEY(id)
DISTRIBUTED BY HASH(`id`) BUCKETS 16
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);
```
准备数据:
```
insert into score_board VALUES
  (0, 'Jack', 21,'2022-12-10'),
  (1, 'Bob', 21,'2022-12-13'),
  (2, 'Stan', 21,'2022-12-11'),
  (3, 'Sam', 22,'2022-12-12');

```
删除数据sql以及执行情况:
+ delete from score_board where s_date = '2022-12-12' -- 可执行
+ delete from score_board where s_date = to_date("2022-12-12") -- 无法执行 1064 - Analyze DeleteStmt using old analyzer failed: Right expr of binary predicate should be value
+ delete from score_board where s_date >= DATE_ADD( CURDATE(), INTERVAL  -7 DAY ) --无法执行，错误同上

> 希望能够优化一下，date类型字段作为删除条件也支持函数

**Comment by Dshadowzh** [comment]
Primary key model could support this, you can try it.

**Comment by ljkljkkjl** [comment]
> 
我的业务决定了我只能用明细模型，做离线同步的时候，历史数据又可能会修改，因此无法使用主键模型
