### ISSUE TITLE
BE crash in ASAN build_type

### ISSUE THREAD

**Issue by wangruin** [StarRocks/starrocks#1549]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `primary_table` (
  `k1` datetime NOT NULL COMMENT "",
  `k2` varchar(65533) NOT NULL COMMENT "",
  `k3` varchar(65533) NOT NULL COMMENT "",
  `k4` boolean NOT NULL COMMENT "",
  `v1` tinyint(4) NOT NULL COMMENT "",
  `v2` smallint(6) NOT NULL COMMENT "",
  `v3` int(11) NOT NULL COMMENT "",
  `v4` double NOT NULL COMMENT "",
  `v5` decimal128(27, 9) NOT NULL COMMENT ""
) ENGINE=OLAP
PRIMARY KEY(`k1`, `k2`, `k3`, `k4`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`) BUCKETS 3
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
2. CREATE TABLE `test_cross_join_30` (
  `id_int` int(11) NOT NULL COMMENT "",
  `id_double` double NOT NULL COMMENT "",
  `id_varchar` varchar(100) NOT NULL COMMENT "",
  `id_datetime` datetime NOT NULL COMMENT "",
  `id_decimal` decimal128(20, 3) NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`id_int`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id_int`) BUCKETS 1
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
3. CREATE EXTERNAL TABLE `external_mysql_table_with_null` (
  `id_tinyint` tinyint(4) NULL COMMENT "",
  `id_smallint` smallint(6) NULL COMMENT "",
  `id_int` int(11) NULL COMMENT "",
  `id_float` float NULL COMMENT "",
  `id_double` double NULL COMMENT "",
  `id_decimal` decimal128(27, 9) NULL COMMENT "",
  `id_date` date NULL COMMENT "",
  `id_datetime` datetime NULL COMMENT "",
  `id_char` char(20) NULL COMMENT "",
  `id_varchar` varchar(20) NULL COMMENT ""
) ENGINE=MYSQL
COMMENT "MYSQL"
PROPERTIES (
"host" = "172.26.92.139",
"port" = "3306",
"user" = "root",
"password" = "",
"database" = "doris_external",
"table" = "mysql_external_null"
);
4. select     subq_0.c4 as c0 from    (select           10 as c0,          case when ref_1.v1 > ref_1.k4 then ref_0.v3 else ref_0.v3 end            as c1,          ref_3.id_tinyint as c2,          ref_0.k2 as c3,                     sum(             cast(ref_3.id_float as DOUBLE)) over (partition by ref_1.k4 order by ref_2.id_double,ref_2.id_double,ref_3.id_float,ref_2.id_double,ref_2.id_decimal) as c4,          ref_0.v5 as c5,          ref_3.id_decimal as c6,          pi() as c7,          ref_2.id_decimal as c8,
  ref_0.k1 as c9       from          sqlsmith.primary_table as ref_0               inner join sqlsmith.primary_table as ref_1               on (ref_0.k4 = ref_1.k4 )             inner join sqlsmith.test_cross_join_30 as ref_2             on (ref_0.k4 = ref_2.id_int )           left join sqlsmith.external_mysql_table_with_null as ref_3           on (ref_2.id_varchar = ref_3.id_char )       where (true)          or (ref_3.id_decimal >= rand())) as subq_0 where (subq_0.c2 is not NULL)    and (true) limit 110;

### Expected behavior (Required)
Query returns correctly

### Real behavior (Required)
BE crash

*** Aborted at 1637719590 (unix time) try "date -d @1637719590" if you are using GNU date ***
PC: @          0x5bc2ecf starrocks::vectorized::JoinBuildFunc<>::construct_hash_table()
*** SIGSEGV (@0xb6adace7) received by PID 29009 (TID 0x7f026447d700) from PID 18446744072479419623; stack trace: ***
    @          0x87ec702 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f02b502d5f0 (unknown)
    @          0x5bc2ecf starrocks::vectorized::JoinBuildFunc<>::construct_hash_table()
    @          0x5b8aea2 starrocks::vectorized::JoinHashMap<>::build()
    @          0x5b7cdfc starrocks::vectorized::JoinHashTable::build()
    @          0x5b66050 starrocks::vectorized::HashJoinNode::_build()
    @          0x5b61a22 starrocks::vectorized::HashJoinNode::open()
    @          0x6068433 starrocks::vectorized::ProjectNode::open()
    @          0x5b62437 starrocks::vectorized::HashJoinNode::open()
    @          0x6068433 starrocks::vectorized::ProjectNode::open()
    @          0x4b31f9f starrocks::PlanFragmentExecutor::_open_internal_vectorized()
    @          0x4b3168d starrocks::PlanFragmentExecutor::open()
    @          0x49bae82 starrocks::FragmentExecState::execute()
    @          0x49bfdcb starrocks::FragmentMgr::exec_actual()
    @          0x49c062f _ZZN9starrocks11FragmentMgr18exec_plan_fragmentERKNS_23TExecPlanFragmentParamsERKSt8functionIFvPNS_20PlanFragmentExecutorEEEENKUlvE_clEv
    @          0x49c91f2 _ZSt13__invoke_implIvRZN9starrocks11FragmentMgr18exec_plan_fragmentERKNS0_23TExecPlanFragmentParamsERKSt8functionIFvPNS0_20PlanFragmentExecutorEEEEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @          0x49c8eab _ZSt10__invoke_rIvRZN9starrocks11FragmentMgr18exec_plan_fragmentERKNS0_23TExecPlanFragmentParamsERKSt8functionIFvPNS0_20PlanFragmentExecutorEEEEUlvE_JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESF_E4typeEOSG_DpOSH_
    @          0x49c8802 _ZNSt17_Function_handlerIFvvEZN9starrocks11FragmentMgr18exec_plan_fragmentERKNS1_23TExecPlanFragmentParamsERKSt8functionIFvPNS1_20PlanFragmentExecutorEEEEUlvE_E9_M_invokeERKSt9_Any_data
    @          0x3ad58b2 std::function<>::operator()()
    @          0x4dd51e2 starrocks::FunctionRunnable::run()
    @          0x4dd1ae6 starrocks::ThreadPool::dispatch_thread()
    @          0x4def318 std::__invoke_impl<>()
    @          0x4deebfb std::__invoke<>()
    @          0x4dee012 _ZNSt5_BindIFMN9starrocks10ThreadPoolEFvvEPS1_EE6__callIvJEJLm0EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @          0x4decb70 std::_Bind<>::operator()<>()
    @          0x4de9a56 std::__invoke_impl<>()
    @          0x4de7a1e _ZSt10__invoke_rIvRSt5_BindIFMN9starrocks10ThreadPoolEFvvEPS2_EEJEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESA_E4typeEOSB_DpOSC_
    @          0x4de31b9 std::_Function_handler<>::_M_invoke()
    @          0x3ad58b2 std::function<>::operator()()
    @          0x4e03801 starrocks::Thread::supervise_thread()
    @     0x7f02b5025e65 start_thread
    @     0x7f02b442a88d __clone

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
branch-2.0 `13c78d7` ASAN

**Comment by wangruin** [comment]
fix in [https://github.com/StarRocks/starrocks/pull/1671](url)

**Comment by stdpain** [comment]
It was because a overflow.

calc_bucket_size will return zero if size greater than 2^31
```c++
#include <cstdint>
#include <iostream>

int LeadingZeros(uint64_t val) {
    if (val == 0) {
        return 64;
    }
    return __builtin_clzll(val);
}

inline size_t NormalizeCapacity(size_t n) {
    return n ? ~size_t{} >> LeadingZeros(n) : 1;
}

static uint32_t calc_bucket_size(uint32_t size) {
    size = size + (size - 1) / 7;
    return NormalizeCapacity(size) + 1;
}

int main() {
    uint32_t ans = 2147483648;
    std::cout << calc_bucket_size(ans + 1) << std::endl;
    return 0;
}
```
