### ISSUE TITLE
load index lazy to improve the first-time reading performance

### ISSUE THREAD

**Issue by DeepThinker666** [StarRocks/starrocks#1554]
## Enhancement
Now, when reading column data, all the indexes of column will be loaded, no matter whether they are used or not. But reading index will incur random io, which will hurt first-time reading performance.
So we can just load the necessary indexes to improve the first-time reading performance.

**Comment by sduzh** [comment]
Duplicated with https://github.com/StarRocks/starrocks/issues/199
