### ISSUE TITLE
中文文档性能测试部分部分描述不清楚有歧义

### ISSUE THREAD

**Issue by haiboself** [StarRocks/starrocks#15735]
### Steps to reproduce the behavior (Required)
1. SSB性能测试(https://docs.starrocks.io/zh-cn/2.5/benchmarking/SSB_Benchmarking) 和 TPC-H(https://docs.starrocks.io/zh-cn/2.5/benchmarking/TPC-H_Benchmark) 描述软件环境是 "部署 3BE 1FE", 但是没说明 1 台 FE 是单独部署还是和 BE 混部的
2. 在 SSB性能测试 文档中, 有2个描述问题
- （四）数据查询 SSB query 有2条命令，但是没解释这 2个的区别
![image](https://user-images.githubusercontent.com/22912087/209455552-c92ee968-6892-4096-9e72-0700c3d7c941.png)
- 三、测试数据与结果 描述 1. 单表测试 SQL 为 --Q1.1 -- Q2.2 等, 但是  `bin/benchmark.sh -p -d ssb` 命令输出的是 q1, q2, ...q12, 两者名字对不上, 容易产生误解

### Expected behavior (Required)
优化文档, 消除歧义以便于能根据文档步骤顺利操作
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.5-rc

**Comment by jaogoy** [comment]
1. 这里 FE 对性能没影响，所以混布/单独都无所谓。（可以补充下）
2. SSB-flat 是指块表。（这块也可以补充下）
3. 这个得修改统一下。
@evelynzhaojie

**Comment by evelynzhaojie** [comment]
issues 1 and 2 have been resolved and fixed in doc. issue 3 is in progress

**Comment by evelynzhaojie** [comment]
ssb single-table benchmarking 的测试脚本和文档已经重新修改 https://docs.starrocks.io/zh-cn/latest/benchmarking/SSB_Benchmarking
