### ISSUE TITLE
Create bloom index on on-key column for primary key table failed

### ISSUE THREAD

**Issue by decster** [StarRocks/starrocks#1577]
`create table t(id bigint not null, name string not null) primary key(id) distributed by hash(id) buckets  4 properties("bloom_filter_clumns":"name");
`
Failed:

`Bloom filter index only used in columns of DUP_KEYS table or key columns of UNIQUE_KEYS/AGG_KEYS table`

need to remove this check for primary key

**Comment by Linkerist** [comment]
```SQL
create table t(id bigint not null, name string not null) primary key(id) distributed by hash(id) buckets 4 properties("bloom_filter_columns"="name");
```
