### ISSUE TITLE
[delta lake] where statement query error

### ISSUE THREAD

**Issue by huoyue-git** [StarRocks/starrocks#15794]
### Steps to reproduce the behavior (Required)
1. hive
```
CREATE TABLE `delta_lake_data_type` ( 
col_tinyint           tinyint         ,
col_smallint          smallint        ,
col_int               integer         ,
col_long              long            ,
col_float             float           ,
col_double            double          ,
col_date              date            ,
col_timestamp         timestamp       ,
col_string            string          ,
col_decimal           decimal(10,2)   ,
col_boolean           boolean         ,
col_byte              byte            ,
col_array             array<int> )     
USING delta ;

insert into delta_lake_data_type
values
(null,10,10,10,10.002,100.2,'2022-12-10','2022-12-10 01:01:01','hello world', '1111.10',false,2,array(cast(10 as int), cast(11 as int))),
(11,null,null,null,null,null,null,null,null, null,null,null,array(cast(11 as int), cast(12 as int))),
(127,32767,2147483647,9223372036854775807,3.40E+38,1.79E+308,'9999-12-31','9999-12-31 23:59:59','hello world','9999.99',true, 0, null),
(-128,-32768,-2147483648,-9223372036854775808,-3.40E+38,-1.79E+308,'9999-12-31','9999-12-31 23:59:59','hello world','0.01',true, 0,array(null));
```
2. INSERT INTO '....'
```
CREATE EXTERNAL CATALOG "delta_catalog"  PROPERTIES ("type"="deltalake","hive.metastore.uris"="thrift://xxx.xx.xxx.xxx:xxxx");
use delta_catalog.delta_lake_db;
select * from delta_lake_data_type
```
3. SELECT  '....'
```
select * from delta_lake_data_type where col_tinyint > 1;
select * from delta_lake_data_type where col_float > 1;
select * from delta_lake_data_type where col_date > '2020-01-01';
select * from delta_lake_data_type where col_decimal > 10.2;
select * from delta_lake_data_type where col_byte > 1;
```

### Expected behavior (Required)
result as same as in hive query
### Real behavior (Required)
mysql> select * from delta_lake_data_type where col_tinyint > 1;
ERROR 1064 (HY000): BinaryOperator left and right DataTypes must be the same, found: byte > short
mysql> select * from delta_lake_data_type where col_float > 1;
ERROR 1064 (HY000): BinaryOperator left and right DataTypes must be the same, found: float > double
mysql> select * from delta_lake_data_type where col_date > '2020-01-01';
ERROR 1064 (HY000): java.util.Date cannot be cast to java.sql.Date
mysql> select * from delta_lake_data_type where col_decimal > 10.2;
ERROR 1064 (HY000): BinaryOperator left and right DataTypes must be the same, found: decimal > decimal
mysql> select * from delta_lake_data_type where col_byte > 1;
ERROR 1064 (HY000): BinaryOperator left and right DataTypes must be the same, found: byte > short
mysql>

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.5-RELEASE ab2f742 |
+----------------------------+
1 row in set (0.00 sec)

**Comment by leoyy0316** [comment]
@Youngwb @huoyue-git can you assign to me, want to have a try
