### ISSUE TITLE
Support JSON type for `max_by` function

### ISSUE THREAD

**Issue by syyfffy** [StarRocks/starrocks#15886]
### Steps to reproduce the behavior (Required)
```sql
select 
   `corpId` , `empId` ,  max_by(  table_data,effectDate_$date) table_data
from a
group by `corpId` , `empId` ;
```

### Expected behavior (Required)
`invalid agg function plan:max_by`

### Real behavior (Required)
i can get the result when i use max_by function 

### StarRocks version (2.5.1-rc1)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by syyfffy** [comment]
#这条语句是可以执行的，主要问题是max_by函数不识别table_data 是json数据类型

select 
   `corpId` , `empId` ,max_by(cast(table_data as string),effectDate_$date) table_data
from std_emp_history_info 
group by `corpId` , `empId` ;

**Comment by syyfffy** [comment]
std_emp_history_info 本身是一张物化视图表

**Comment by mofeiatwork** [comment]
JSON data type could not be applied to this function right now,I would convert this issue into a feature request, and support this functionality later.
