### ISSUE TITLE
drop mv throw Unexpected exception: null

### ISSUE THREAD

**Issue by Astralidea** [StarRocks/starrocks#15906]
### Real behavior (Required)
![image](https://user-images.githubusercontent.com/4392280/209774351-8fb091ac-0f4d-4481-a63f-9952bd082e5c.png)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
BRANCH-2.5-RELEASE ab2f742

**Comment by mchades** [comment]
@Astralidea I have met the same error at 2.3.7

**Comment by Astralidea** [comment]
I don't know how this problem arises, but I think some checks can be added to avoid this problem first.

**Comment by mchades** [comment]
@Astralidea I mean this pr should cherry pick to 2.3 branch? Or 2.3 branch should add the same check.

**Comment by Astralidea** [comment]
This can be cherry-picked to 2.3, but the code is not the same, so it cannot be simply merged. Do you have time to help me with a PR merge?
