### ISSUE TITLE
Query failed due to remove comment 

### ISSUE THREAD

**Issue by huangfeng1993** [StarRocks/starrocks#15967]
query

```
select 'a' in ('/products/men\'s-urina' , '/products/super--absorbency-short-trucks-washable-reusable' );
```
![image](https://user-images.githubusercontent.com/8199608/209910527-fba3e779-2f7e-46b2-a4a1-225904f19f47.png)

https://github.com/StarRocks/starrocks/commit/8c456a89a40a2d1aa3803597c1096876f275d9d4
this pr do remove comment , but don't consider apostrophe in string literal.  

### StarRocks version (Required)
2.3.4

**Comment by jaogoy** [comment]
I don't understand what it means.

**Comment by jaogoy** [comment]
I don't understand what it means.

**Comment by huangfeng1993** [comment]
For example,  select  'ab \'sdf' , 'bsdf --sdfssdfas'  is changed( com.starrocks.sql.parser.SqlParser#removeComment )  to  select  'ab \'sdf' , 'bsdf , send to sqlparser , and failed. root cause is that https://github.com/StarRocks/starrocks/commit/8c456a89a40a2d1aa3803597c1096876f275d9d4 don't consider nested apostrophe in string literal.

**Comment by huangfeng1993** [comment]
https://github.com/StarRocks/starrocks/pull/15561 solved
