### ISSUE TITLE
support connect differtent hive cluster by create different catalog

### ISSUE THREAD

**Issue by zhengtingxue** [StarRocks/starrocks#16015]
## Feature request

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

1. i have a cdh5.16 cluster with kerberos , and have another cdh6.3.2 cluster with no kerberos
2. then i want to create a hive catalog cdh5,then i can select table from cdh5 cluster,and create a hive catalog cdh6,then i can select table from cdh6 cluster.
3. but the cluster ha is opend.so i need put the hdfs-site.xml and core-site.xml under the fe and be conf path,so i need put two different cluster failes under the path,so there is a conflict,finally i just can only connect one cluster by create a catalog because the conf files is conflict.
4.  i think if we set the ha and kerberos properties when creating a catalog,we can fix it.just like 
create external catalog 'hive_cdh5' properties (
"type"="hive",
"hive.metastore.uris"="",
"ha.properties.*"="",
"kerberos.properties.**"=""
)

**Describe alternatives you've considered**

**Additional context**

**Comment by metalshanked** [comment]
> ## Feature request
> **Is your feature request related to a problem? Please describe.**
> 
> **Describe the solution you'd like**
> 
> 1. i have a cdh5.16 cluster with kerberos , and have another cdh6.3.2 cluster with no kerberos
> 2. then i want to create a hive catalog cdh5,then i can select table from cdh5 cluster,and create a hive catalog cdh6,then i can select table from cdh6 cluster.
> 3. but the cluster ha is opend.so i need put the hdfs-site.xml and core-site.xml under the fe and be conf path,so i need put two different cluster failes under the path,so there is a conflict,finally i just can only connect one cluster by create a catalog because the conf files is conflict.
> 4. i think if we set the ha and kerberos properties when creating a catalog,we can fix it.just like
>    create external catalog 'hive_cdh5' properties (
>    "type"="hive",
>    "hive.metastore.uris"="",
>    "ha.properties.*"="",
>    "kerberos.properties.**"=""
>    )
> 
> **Describe alternatives you've considered**
> 
> **Additional context**

Need this feature too. 
I have a kerberized Hive cluster and a NON kerberized hive cluster.
So if I add the hive-site.xml to the fe conf dir which is required for the Kerberized hive catalog,  the  non-kerberized hive catalog reads this too and fails.
