### ISSUE TITLE
sql correctness bug in cast datetime to date and in condition

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#1604]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE t1 (c_1_0 DATETIME NULL ,c_1_1 PERCENTILE PERCENTILE_UNION NULL ,c_1_2 DATETIME REPLACE_IF_NOT_NULL NULL ) AGGREGATE KEY (c_1_0) DISTRIBUTED BY HASH (c_1_0) properties("replication_num"="1") ;
2. INSERT INTO t1 VALUES ("1970-01-01 08:00:00", percentile_hash("-2118975606"), "1970-01-01 08:00:00"), ("1970-01-01 08:00:00", percentile_hash("1497210429"), "1970-01-01 08:00:00");
INSERT INTO t1 VALUES (NULL, percentile_hash("-1404529616"), "1970-01-01 08:00:00"), ("1970-01-01 08:00:00", percentile_hash("-1404529616"), "1970-01-01 08:00:00");
3. 
```
mysql> select * from t1;

+---------------------+-------+---------------------+
| c_1_0               | c_1_1 | c_1_2               |
+---------------------+-------+---------------------+
| NULL                | NULL  | 1970-01-01 08:00:00 |
| 1970-01-01 08:00:00 | NULL  | 1970-01-01 08:00:00 |
+---------------------+-------+---------------------+

mysql> select * from t1 where NOT  ((CAST(t1.c_1_0 AS DATETIME ) ) IN ("1970-01-01 07:59:59", "1970-01-02 20:31:46"));

+---------------------+-------+---------------------+
| c_1_0               | c_1_1 | c_1_2               |
+---------------------+-------+---------------------+
| 1970-01-01 08:00:00 | NULL  | 1970-01-01 08:00:00 |
+---------------------+-------+---------------------+

mysql> select * from t1 where NOT  (t1.c_1_0  IN ("1970-01-01 07:59:59", "1970-01-02 20:31:46"));
+---------------------+-------+---------------------+
| c_1_0               | c_1_1 | c_1_2               |
+---------------------+-------+---------------------+
| 1970-01-01 08:00:00 | NULL  | 1970-01-01 08:00:00 |
+---------------------+-------+---------------------+

mysql> select * from t1 where NOT  ((CAST(t1.c_1_0 AS DATE ) ) IN ("1970-01-01 07:59:59", "1970-01-02 20:31:46"));
Empty set (0.01 sec)
```

### Expected behavior (Required)
one line result

### Real behavior (Required)
Empty set
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - master release with 34e38da

**Comment by Seaven** [comment]
The SQL
```
mysql> select * from t1 where NOT  ((CAST(t1.c_1_0 AS DATE ) ) IN ("1970-01-01 07:59:59", "1970-01-02 20:31:46"));
Empty set (0.01 sec)
```

`("1970-01-01 07:59:59", "1970-01-02 20:31:46")` will cast to date: `("1970-01-01", "1970-01-02")`, so the result is right.
