### ISSUE TITLE
Query json type with between-and faild

### ISSUE THREAD

**Issue by mchades** [StarRocks/starrocks#16056]
### Steps to reproduce the behavior (Required)
1. SELECT  '....'
```
MySQL [dps_data_center_stream]> select parse_json('1') between 0.5 and 0.9;
ERROR 1064 (HY000): between predicate type json with type unknown type: INVALID_TYPE is invalid.
```

### Expected behavior (Required)
return 1
### Real behavior (Required)
report error
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main

**Comment by jaogoy** [comment]
cc @mofeiatwork
