### ISSUE TITLE
DROP INDEX failed

### ISSUE THREAD

**Issue by finddbbug** [StarRocks/starrocks#16162]
### Steps to reproduce the behavior (Required)
1.  CREATE TABLE `t1`(`x` INTEGER,`y` VARCHAR(8)) ENGINE=OLAP  DISTRIBUTED BY HASH(`x`) PROPERTIES ( "replication_num" = "1");
2. CREATE INDEX t1i1 ON t1(x);
3. DROP INDEX t1i1;

### Expected behavior (Required)
DROP INDEX success;

### Real behavior (Required)
mysql> DROP INDEX t1i1;
ERROR 1064 (HY000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '<EOF>' at line 1

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

2.5.0-RC01 cd45ba7

**Comment by alvin-coding** [comment]
Seems you need to execute `DROP INDEX t1i1 on t1`
Because the index belongs to some table, you should tell starrocks which table.

**Comment by finddbbug** [comment]
ok, close it
