### ISSUE TITLE
BE crash when using percentile_cont

### ISSUE THREAD

**Issue by goldenbean** [StarRocks/starrocks#16204]
BE crash when using percentile_cont

SR version: built from main branch on Nov 23, 2022

> W0103 18:14:07.122244 29597 mem_hook.cpp:254] large memory alloc: 17179869200 bytes, stack:
>     @          0x3ced0fb  malloc
>     @          0x6b11da5  operator new()
>     @          0x2205fd0  std::vector<>::_M_default_append()
>     @          0x228712f  starrocks::vectorized::BinaryColumnBase<>::append_selective()
>     @          0x42a2953  starrocks::vectorized::NullableColumn::append_selective()
>     @          0x42866fa  starrocks::vectorized::Chunk::append_selective()
>     @          0x4652f14  starrocks::pipeline::ExchangeSinkOperator::Channel::add_rows_selective()
>     @          0x46547b7  starrocks::pipeline::ExchangeSinkOperator::push_chunk()
>     @          0x229c69e  starrocks::pipeline::PipelineDriver::process()
>     @          0x435e3e5  starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
>     @          0x3dc4e65  starrocks::ThreadPool::dispatch_thread()
>     @          0x3dc027a  starrocks::Thread::supervise_thread()
>     @     0x7f3f4b756dc5  start_thread
>     @     0x7f3f4ad7773d  __clone
>     @              (nil)  (unknown)

BE.OUT

> 
> query_id:3c7b9b05-8b3e-11ed-ab96-a0369fc32e4c, fragment_instance:3c7b9b05-8b3e-11ed-ab96-a0369fc32e54
> *** Aborted at 1672733495 (unix time) try "date -d @1672733495" if you are using GNU date ***
> PC: @     0x7f2e85df0b2f __memcpy_ssse3_back
> *** SIGSEGV (@0x7f2a7fe00000) received by PID 46566 (TID 0x7f2d81afe700) from PID 2145386496; stack trace: ***
>     @          0x4ef7dc2 google::(anonymous namespace)::FailureSignalHandler()
>     @     0x7f2e872a4efb os::Linux::chained_handler()
>     @     0x7f2e872a9abd JVM_handle_linux_signal
>     @     0x7f2e8729c8b8 signalHandler()
>     @     0x7f2e86784370 (unknown)
>     @     0x7f2e85df0b2f __memcpy_ssse3_back
>     @          0x2286e62 starrocks::vectorized::BinaryColumnBase<>::append_selective()
>     @          0x42a2953 starrocks::vectorized::NullableColumn::append_selective()
>     @          0x42866fa starrocks::vectorized::Chunk::append_selective()
>     @          0x4652f14 starrocks::pipeline::ExchangeSinkOperator::Channel::add_rows_selective()
>     @          0x46547b7 starrocks::pipeline::ExchangeSinkOperator::push_chunk()
>     @          0x229c69e starrocks::pipeline::PipelineDriver::process()
>     @          0x435e3e5 starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
>     @          0x3dc4e65 starrocks::ThreadPool::dispatch_thread()
>     @          0x3dc027a starrocks::Thread::supervise_thread()
>     @     0x7f2e8677cdc5 start_thread
>     @     0x7f2e85d9d73d __clone
>     @                0x0 (unknown)
> start time: Tue Jan 3 16:25:22 CST 2023
> query_id:8b306e22-8b43-11ed-ab96-a0369fc32e4c, fragment_instance:8b306e22-8b43-11ed-ab96-a0369fc32e54
> *** Aborted at 1672735774 (unix time) try "date -d @1672735774" if you are using GNU date ***
> PC: @     0x7f0ab1b8dcd0 __memcpy_ssse3_back
> *** SIGSEGV (@0x7f093d5a2ff0) received by PID 13691 (TID 0x7f09bd9a6700) from PID 1029320688; stack trace: ***
>     @          0x4ef7dc2 google::(anonymous namespace)::FailureSignalHandler()
>     @     0x7f0ab2521370 (unknown)
>     @     0x7f0ab1b8dcd0 __memcpy_ssse3_back
>     @          0x2286e62 starrocks::vectorized::BinaryColumnBase<>::append_selective()
>     @          0x42a2953 starrocks::vectorized::NullableColumn::append_selective()
>     @          0x42866fa starrocks::vectorized::Chunk::append_selective()
>     @          0x4652f14 starrocks::pipeline::ExchangeSinkOperator::Channel::add_rows_selective()
>     @          0x46547b7 starrocks::pipeline::ExchangeSinkOperator::push_chunk()
>     @          0x229c69e starrocks::pipeline::PipelineDriver::process()
>     @          0x435e3e5 starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
>     @          0x3dc4e65 starrocks::ThreadPool::dispatch_thread()
>     @          0x3dc027a starrocks::Thread::supervise_thread()
>     @     0x7f0ab2519dc5 start_thread
>     @     0x7f0ab1b3a73d __clone
>     @                0x0 (unknown)
>  start time: Tue Jan 3 16:58:37 CST 2023
> start time: Tue Jan 3 17:01:59 CST 2023

**Comment by yulongfufu** [comment]
I encountered the same error, how to solve it？ @goldenbean

**Comment by goldenbean** [comment]
Since I deploy the latest stable version of SR 2.5, and it didn't happen again :)  @yulongfufu
