### ISSUE TITLE
Display ROLLUP and MATERIALIZED VIEW is incorrect

### ISSUE THREAD

**Issue by stephen-shelby** [StarRocks/starrocks#1620]
Show rollup information is inconsistent with schema.
### Steps to reproduce the behavior (Required)
show alter table rollup;
SHOW ALTER TABLE MATERIALIZED VIEW ;
### Expected behavior (Required)
Correct information
### Real behavior (Required)
![image](https://user-images.githubusercontent.com/91597003/143431698-944e48be-b4fd-46b2-b56b-529f75b9980b.png)

### StarRocks version (Required)
 main

**Comment by gengjun-git** [comment]
What is the problem?

**Comment by stephen-shelby** [comment]
> 

The display content is inconsistent with the schema. such as `TransactionId` on 'SHOW ALTER MATERIALIZED VIEW'
