### ISSUE TITLE
[Enhancement] SparseRange::intersection is O(n^2) complexity and should be optimized

### ISSUE THREAD

**Issue by decster** [StarRocks/starrocks#16254]
## Enhancement
SparseRange::intersection is used in  segment iterator init, and each filter apply will use intersec to reduce _scan_range, but some filters may produce a large number of ranges(like delvecter, bitmap, zone_map, bloom), and currently, intersection is O(n^2) complexity, so it may run very lowly.
If ranges are sorted, an efficient merge like algorithm is much better. Another option would be using roaringbitmap altogether(abandon SparseRange)
```
    RETURN_IF_ERROR(_get_row_ranges_by_keys());
    RETURN_IF_ERROR(_get_row_ranges_by_rowid_range());
    RETURN_IF_ERROR(_apply_del_vector());
    RETURN_IF_ERROR(_apply_bitmap_index());
    RETURN_IF_ERROR(_get_row_ranges_by_zone_map());
    RETURN_IF_ERROR(_get_row_ranges_by_bloom_filter());

inline SparseRange SparseRange::intersection(const SparseRange& rhs) const {
    SparseRange result;
    for (const auto& r1 : _ranges) {
        for (const auto& r2 : rhs._ranges) {
            if (r1.has_intersection(r2)) {
                result._add_uncheck(r1.intersection(r2));
            }
        }
    }
    return result;
}
```

**Comment by stdpain** [comment]
all of the sub range in SparseRange is ordered. We can reduce a certain number of comparisons based on this

**Comment by kangkaisen** [comment]
roaringbitmap intersection is very slow.
