### ISSUE TITLE
Rename data distribution type name

### ISSUE THREAD

**Issue by mofeiatwork** [StarRocks/starrocks#16268]
## Refactoring request

Current `DataPartition` name is chaos, not so straightforward: 
- `UNPARTITIONED` means broadcast
- `RANDOM`: means round robin
- `HASH_PARTITIONED` means partitioned by hash

**Comment by beanflower-bs** [comment]
Can you tell me which module the relevant code is in?

**Comment by mofeiatwork** [comment]
> Can you tell me which module the relevant code is in?

Almost cross all modules, include planner, executor, and thrift. You could search these names and look for the dependencies.
