### ISSUE TITLE
[Bug]: There is a problem viewing the materialized view structure with DESC

### ISSUE THREAD

**Issue by Shan-01** [StarRocks/starrocks#16276]
### Link to the Docs

https://docs.starrocks.io/zh-cn/latest/sql-reference/sql-statements/Utility/DESCRIBE

### Describe the Bug

There is a problem with the display of materialized view structure column names with DESC
`View table structure with DESC`
![image](https://user-images.githubusercontent.com/116535280/210711386-24638141-6e7c-4952-8fe3-06289ff95c8c.png)
`View Materialized View Structure with DESC`
![image](https://user-images.githubusercontent.com/116535280/210711512-0259037c-9b21-4380-aea5-1a83c504e518.png)

**Comment by EsoragotoSpirit** [comment]
![uVoWUhCWho](https://user-images.githubusercontent.com/104624482/210915724-2970d67c-cf2f-4ba4-a2d5-7c07d0358b75.jpg)
I have reproduced this bug on the main release. The example I used is from https://docs.starrocks.io/zh-cn/latest/using_starrocks/Materialized_view#%E4%BD%BF%E7%94%A8%E7%89%A9%E5%8C%96%E8%A7%86%E5%9B%BE%E5%8A%A0%E9%80%9F%E6%9F%A5%E8%AF%A2
