### ISSUE TITLE
High IO usage of materialized view

### ISSUE THREAD

**Issue by 12482** [StarRocks/starrocks#16309]
## 创建物化视图后导致IO飙升
- 测试环境如下:
  - 机器数量1台
  - cpu 4 core
  - 内存 30G
  - 磁盘 500G SSD
  - 操作系统 centos7

- base table1 帐号基础信息表:
```
CREATE TABLE IF NOT EXISTS account_info
(
    `account_id` VARCHAR(50) NOT NULL,
    `nick_name` VARCHAR(200),
    `description` VARCHAR(500) ,
    `register_address` VARCHAR(500) 
)PRIMARY KEY(`account_id`)
DISTRIBUTED BY HASH(`account_id`) BUCKETS 16
PROPERTIES (
"replication_num" = "1",
"enable_persistent_index" = "true"
);
```

- base table2 帐号关注信息表：
```
CREATE TABLE IF NOT EXISTS account_follow
(
    `account_id` VARCHAR(50) NOT NULL ,
    `follow_id` VARCHAR(50) NOT NULL  
)
PRIMARY KEY(`account_id`,`follow_id`)
COMMENT "account follow relation"
DISTRIBUTED BY HASH(`account_id`) BUCKETS 16
PROPERTIES (
"replication_num" = "1",
"enable_persistent_index" = "true"
);
```
我们需要统计某个帐号的关注的帐号的注册地信息，sql语句如下：

```
select
  ai.register_address as ra,
  count(ai.register_address) as cnt
from
  account_follow af
  inner join account_info ai on af.follow_id = ai.account_id
where
  af.account_id = "AC3344512"
  AND (ai.register_address like "%ai%")
group by
  ra
order by
  cnt desc
```
测试数据规模及测试结果如下
```
 account_info表，共有1.5亿条记录
 account_follow表，共有300万条记录
 帐号"AC3344512" 在account_follow表中有5000条记录（5000个粉丝）
 sql查询耗时： 27s
```
为了加速查询，避免查询的时候join，创建了一个物化视图，语句如下：
```
CREATE MATERIALIZED VIEW fans_info
DISTRIBUTED BY HASH(`account_id`) BUCKETS 48
REFRESH ASYNC
AS
select
  af.account_id as account_id,
  af.follow_id as follow_id,
  ai.nick_name as nick_name,
  ai.description as description,
  ai.register_address as register_address
from
  account_follow as af
  inner join account_info as ai on af.follow_id = ai.account_id;
```
然后使用sql查询物化视图，查询语句如下:

```
select register_address , count(register_address) as cnt
 from fans_info where account_id = 'AC3344512'
 and description like '%ai%'
group by register_address
order by cnt desc ;
```
查询结果非常快，只要800ms，更快的时候只要几十毫秒，但是，在测试服务器上看到磁盘IO非常高，一直在200MB/s～500MB/s,删掉物化视图后立马降下来了，是我物化视图使用场景不对吗

**Comment by Astralidea** [comment]
你好，请问你的base表也就是account_info或account_follow的导入频率是什么样的？使用的是2.4版本的物化视图是吗？
你这个大概率可能是由于使用的是REFRESH ASYNC导致，每次导入数据都会进行一次刷新导致的。假如是这个问题。可以使用周期性刷新来缓解这个问题，周期性刷新就写base表的导入频率无关了，相当于你自己设定频率。

**Comment by 12482** [comment]
> 你好，请问你的base表也就是account_info或account_follow的导入频率是什么样的？使用的是2.4版本的物化视图是吗？ 你这个大概率可能是由于使用的是REFRESH ASYNC导致，每次导入数据都会进行一次刷新导致的。假如是这个问题。可以使用周期性刷新来缓解这个问题，周期性刷新就写base表的导入频率无关了，相当于你自己设定频率。

是2.4版本的物化视图，base表的导入频率确实很高，基本每秒都有数据写入，如果周期性刷新，那随着数据量增大，刷新的时候耗时、io也会很高，也可能影响其他查询业务了，目前数据也没法用日期来分区每次只刷新指定分区，未来有没有可能根据join查询的条件base表有数据写入时计算写入数据相关的数据修改物化视图？

**Comment by Astralidea** [comment]
> > 你好，请问你的base表也就是account_info或account_follow的导入频率是什么样的？使用的是2.4版本的物化视图是吗？ 你这个大概率可能是由于使用的是REFRESH ASYNC导致，每次导入数据都会进行一次刷新导致的。假如是这个问题。可以使用周期性刷新来缓解这个问题，周期性刷新就写base表的导入频率无关了，相当于你自己设定频率。
> 
> 是2.4版本的物化视图，base表的导入频率确实很高，基本每秒都有数据写入，如果周期性刷新，那随着数据量增大，刷新的时候耗时、io也会很高，也可能影响其他查询业务了，目前数据也没法用日期来分区每次只刷新指定分区，未来有没有可能根据join查询的条件base表有数据写入时计算写入数据相关的数据修改物化视图？

会的。3.0的时候有会出增量更新的物化视图。有可能在你这个场景中刷新代价会较小。

**Comment by mofeiatwork** [comment]
It would be optimized in recent version
