### ISSUE TITLE
Support a PERCENTILE_DISC aggregation

### ISSUE THREAD

**Issue by rcauble** [StarRocks/starrocks#16332]
## Feature request

There's currently only a a PERCENTILE_CONT which interpolates values.

**Describe the solution you'd like**
A PERCENTILE_DISC with the same semantics as [Vertica's](https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/SQLReferenceManual/Functions/Analytic/PERCENTILE_DISCAnalytic.htm?tocpath=SQL%20Reference%20Manual%7CSQL%20Functions%7CAnalytic%20Functions%7C_____26)

Namely:
* Should not interpolate values
* Should support at least types bigint, double, and string (ideally all comparable types, but that is the minimum needed to match vertica)
* Return type should be the same as the input type.

**Describe alternatives you've considered**

**Additional context**

**Comment by before-Sunrise** [comment]
assign to me，please @kangkaisen
