### ISSUE TITLE
FE JVM memory increase abnormal and even crash when collecting statistics

### ISSUE THREAD

**Issue by lwlei** [StarRocks/starrocks#16331]
### Steps to reproduce the behavior (Required)
CREATE TABLE SQL is here --> [create_table.txt](https://github.com/StarRocks/starrocks/files/10361282/create_table.txt)

INSERT SQL is here -->  [sql2.txt](https://github.com/StarRocks/starrocks/files/10361199/sql2.txt)

Execute sql2.txt in "\_statistics\_" database:
```
MySQL [_statistics_]> source /root/sql2.txt
^@^@^@^@^@^@ERROR 1064 (HY000) at line 1 in file: '/root/sql2.txt': Java heap space
```

### Expected behavior (Required)
FE stat is normal and master JVM STAT is stable. 

### Real behavior (Required)
The JVM usage of FE master would increase to 100% and transfer master role every 4 hours. Just like this:
Grafana:
![image](https://user-images.githubusercontent.com/49778699/211044762-0863616e-8a5c-4b3e-be25-56c33ad9b2a9.png)
fe.log:
![image](https://user-images.githubusercontent.com/49778699/211045400-42da8dbf-e04d-4bc5-899a-5651aa6505e4.png)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.2.10 b101696

**Comment by lwlei** [comment]
jmap:
![image](https://user-images.githubusercontent.com/49778699/211047481-f5664a45-8331-46d1-80f2-36811c48af7c.png)
![image](https://user-images.githubusercontent.com/49778699/211047885-9190f307-73ca-455c-b442-5da95443f8c5.png)

**Comment by Seaven** [comment]
@lwlei I guess your table `wenjuan_answer_new1` has less than 20w rows?

**Comment by lwlei** [comment]
> @lwlei I guess your table `wenjuan_answer_new1` has less than 20w rows?

Yes, It just has 10 rows.
