### ISSUE TITLE
Support "IGNORE NULL" option for LEAD and LAG

### ISSUE THREAD

**Issue by rcauble** [StarRocks/starrocks#16350]
## Feature request

**Is your feature request related to a problem? Please describe.**
Currently LEAD and LAG take into account NULLs whereas the current semantic that we need to emulate for backwards compatibility is IGNORE NULL.

**Describe the solution you'd like**
Would like an IGNORE NULL option as described here:
https://docs.snowflake.com/en/sql-reference/functions/lag.html

**Describe alternatives you've considered**

**Additional context**

**Comment by before-Sunrise** [comment]
assgin to me，please @kangkaisen

**Comment by rcauble** [comment]
I gave it a run -- the behavior doesn't quite match the desired. See here with a repro:

https://github.com/StarRocks/starrocks/issues/18509
