### ISSUE TITLE
light schema change--add column

### ISSUE THREAD

**Issue by hello20230405** [StarRocks/starrocks#16352]
目前在表结构中添加列是异步实现，且在数据量较大时耗时较长，是否可以实现轻量级的添加列，这样的需求还是很强烈的。apche doris在1.2版本中已经相关实现，可参考

**Comment by tonyDong-code** [comment]
+1,有同样的诉求。使用2.0.9版本测试，添加1列和添加10列，100列的耗时都在1分钟左右。猜测添加列操作，会修改历史所有分区元数据信息。是否可以改成只修改未来分区的元数据。
