### ISSUE TITLE
StarRocks external table type is base table

### ISSUE THREAD

**Issue by blackstar-baba** [StarRocks/starrocks#16367]
## General Question

I am using  `select * from information_schema.tables ` to show all tables in databases, i see StarRocks external table type is `BASE TABLE`, why type is not `EXTERNAL TABLE` like mysql external table type?

**Comment by jaogoy** [comment]
Is this issue resolved? But, the corresponding PR is not merged, right?

**Comment by blackstar-baba** [comment]
> Is this issue resolved? But, the corresponding PR is not merged, right?

yes
