### ISSUE TITLE
The table structure is incorrect when using DESC to view the materialized view

### ISSUE THREAD

**Issue by Shan-01** [StarRocks/starrocks#16401]
1.创建表
`CREATE`` TABLE sales_records(
    record_id INT,
    seller_id INT,
    store_id INT,
    sale_date DATE,
    sale_amt BIGINT
) DISTRIBUTED BY `HASH(record_id);`

2.插入数据
`INSERT`` INTO sales_records
VALUES(001,01,1,"2022-03-13",8573),
(002,02,2,"2022-03-14",6948),
(003,01,1,"2022-03-14",4319),
(004,03,3,"2022-03-15",8734),
(005,03,3,"2022-03-16",4212),    
`(006,02,2,"2022-03-17",9515);`

3.创建物化视图
`CREATE` MATERIALIZED VIEW store_amt AS
SELECT store_id, SUM(sale_amt)
FROM sales_records
GROUP BY store_id;`

4.DESC查看表和物化视图，查看物化视图表结构显示有误
`DESC查看表`
![image](https://user-images.githubusercontent.com/116535280/211445691-300aca23-da4d-4bd6-82c8-e3c5efe4bbb3.png)
`DESC查看物化视图`
![image](https://user-images.githubusercontent.com/116535280/211445768-a9a0a777-a962-4cb8-adfd-73b8c0347fd7.png)

5.创建物化视图时，如果有类似sum的操作，数据类型不会顺延，例如基表中的列类型为int，sum之后的列类型还是int，容易数据溢出
![image](https://user-images.githubusercontent.com/116535280/211445818-48567321-d69b-4e06-9725-593a7ece6bb7.png)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
![image](https://user-images.githubusercontent.com/116535280/211445848-3f237257-3576-4770-8213-d2c5fe08808a.png)

**Comment by mofeiatwork** [comment]
it's already fixed in 3.0.
