### ISSUE TITLE
json field type  can add new element with functions

### ISSUE THREAD

**Issue by syyfffy** [StarRocks/starrocks#16461]
## Feature request
1. json_data {'a':'1','b':'1'}  element:{'c':3}
2. If i want to add new element to the json_data , I must cast the data as string ,then i use PARSE_JSON function like that
3. PARSE_JSON(concat(cast(json_data as string),element)) as json_data
4. If there is a json_add functhions to do like that ,it will be userful

**Comment by mofeiatwork** [comment]
Got it, this functionality can be classified as JSON update, updating an existing JSON document. This functionality is in our roadmap, but not so urgent. 

I want to know, what's your use case of this functionality? How would you use it?
