### ISSUE TITLE
hope to support the configuration of `maxAllowedPacket` in the JDBC URL.

### ISSUE THREAD

**Issue by AzonZhang** [StarRocks/starrocks#16518]
Because of the business scenario, we use the traditional JDBC writing method. Because of the reason suggested by StarRocks official website, we will splice an Insert SQL very large, so there is a problem of insufficient Packet size. We need to set the max_allowed_packet parameter, but we don't want to set this parameter as a global one, but for a single session, So I set this parameter in the link URL, but which doesn't seem to take effect. "& maxallowed packet = 65535"

**Comment by kateshaowanjou** [comment]
@AzonZhang Thanks for your feedback! It'd be better if you use English so people who can't read Chinese can also benefit from your input. ❤️

**Comment by AzonZhang** [comment]
Thank you for you suggestion to modify.

**Comment by insistcp** [comment]
所以，这个问题已经解决么？
