### ISSUE TITLE
JSON_OBJECT return wrong result 

### ISSUE THREAD

**Issue by anyepriest** [StarRocks/starrocks#16555]
### Steps to reproduce the behavior (Required)
**sql** :
select current_version(), JSON_OBJECT('aa','1x'),JSON_OBJECT('aa','1x'),JSON_OBJECT('aa','1x'),JSON_OBJECT('aa','1'),JSON_OBJECT('aa',1),JSON_OBJECT('aa','a1');

### Expected behavior (Required)

'2.4.2 3994421', '{"aa": "1x1"}', '{"aa": "111x"}', '{"aa": "1x"}', '{"aa": "1"}', '{"aa": 1}', '{"aa": "a1"}'

### Real behavior (Required)

'2.4.2 3994421', '{"aa": null}', '{"aa": null}', '{"aa": null}', '{"aa": "1"}', '{"aa": 1}', '{"aa": "a1"}'

### StarRocks version (Required)
 - 2.4.2 3994421

**Comment by mofeiatwork** [comment]
It has been fixed through https://github.com/StarRocks/starrocks/issues/14688
