### ISSUE TITLE
group by rollup 结果不对

### ISSUE THREAD

**Issue by cmdares** [StarRocks/starrocks#16577]
select 字段1,字段2,count(0) from 表1 group by rollup(字段1,字段2)，希望通过rollup获取小计，结果发下乱序。
着急，希望优先解决。感谢！

**Comment by LiShuMing** [comment]
Can you give more informations about this? 
- the SR's version 
- the minimal recurring set

Is the result is wrong or the result's order is not expected?

**Comment by cmdares** [comment]
对比Mysql，Oracle，Clickhouse等主流数据库
with t as (
select 'a1' g1,'b1' g2 union all
select 'a1' g1,'b2' g2 union all
select 'a1' g1,'b3' g2 union all
select 'a2' g1,'b1' g2 union all
select 'a2' g1,'b2' g2 union all
select 'a2' g1,'b3' g2 
)
select g1,g2,count(0) c from t group by g1,g2 with rollup   /**mysql,clickhouse 写法*/


with t as (
select 'a1' g1,'b1' g2 union all
select 'a1' g1,'b2' g2 union all
select 'a1' g1,'b3' g2 union all
select 'a2' g1,'b1' g2 union all
select 'a2' g1,'b2' g2 union all
select 'a2' g1,'b3' g2 
)
select g1,g2,count(0) c from t group by rollup(g1,g2) /***oracle,starrocks 写法**/

执行结果发下，mysql、oracle、clickhouse结果一致，先分组、在小计、最后一行合计。
而观测SR的结果统计数值对，但乱序的。
请官方核实一下，能够保证这些分析函数和主流数据库结果一致，便于后续无缝迁移，感谢。
-------------------------------------------------------------------------------------------
目前临时方式，通过修改程序增加order by g1 nulls last,g2 nulls last 暂时适配解决。
with t as (
select 'a1' g1,'b1' g2 union all
select 'a1' g1,'b2' g2 union all
select 'a1' g1,'b3' g2 union all
select 'a2' g1,'b1' g2 union all
select 'a2' g1,'b2' g2 union all
select 'a2' g1,'b3' g2 
)
select g1,g2,count(0) c from t group by rollup(g1,g2) order by g1 nulls last,g2 nulls last
