### ISSUE TITLE
Inconsistencies on be.conf

### ISSUE THREAD

**Issue by didip** [StarRocks/starrocks#16608]
### Steps to reproduce the behavior (Required)
be.conf understand basic variable assignments, for example:
```
DATA_DIR = ${STARROCKS_HOME}/ebs/data

storage_root_path = ${DATA_DIR}   # <-- storage_root_path gets the value of DATA_DIR
```

However, the same thing breaks on `block_cache_disk_path` and `block_cache_meta_path`

### Expected behavior (Required)

I should be able to do this:
```
CACHE_DIR = ${STARROCKS_HOME}/ebs/cache
CACHE_META_DIR = ${STARROCKS_HOME}/ebs/cache-meta

block_cache_disk_path = ${CACHE_DIR}
block_cache_meta_path = ${CACHE_META_DIR}
```

### Real behavior (Required)

but I can't. The config became invalid and I cannot starts the BE server.

### StarRocks version (Required)
 - The latest main branch.

**Comment by GavinMar** [comment]
Have you manually created the `ebs/cache` directory and the  `ebs/cache-meta` directory ?

**Comment by GavinMar** [comment]
Have you manually created the `ebs/cache` directory and the  `ebs/cache-meta` directory ?

**Comment by dirtysalt** [comment]
@didip 
Yes, I guess variable assignment mechanism works in all be.conf(no special treatment for block cache variables at all). 

Perhaps you can check if ebs/cache & ebs/cache-meta directory is created or not. (looks into be.out/be.INFO more details).

**Comment by didip** [comment]
ok I reran my tests again.

1. I made sure that the volume exists:
```
root@sr-be-0:~/starrocks/be/ebs# ll
total 20K
drwxr-xr-x 7 root root      83 Jan 16 04:53 .
drwxr-xr-x 1 root root      51 Jan 16 04:53 ..
drwxrwsr-x 2 root nogroup 4.0K Jan 16 04:52 block-cache
drwxrwsr-x 2 root nogroup 4.0K Jan 16 04:52 block-cache-meta
drwxrwsr-x 7 root nogroup 4.0K Jan 16 04:55 data
drwxrwsr-x 2 root nogroup 4.0K Dec 31 05:50 log
drwxrwsr-x 2 root nogroup 4.0K Dec 31 05:50 tmp
```
2. Made sure that `STARROCKS_HOME=/root/starrocks/be`

3. Then I added the config:
```
DATA_DIR = ${STARROCKS_HOME}/ebs/data
LOG_DIR = ${STARROCKS_HOME}/ebs/log
BLOCK_CACHE_DIR = ${STARROCKS_HOME}/ebs/block-cache
BLOCK_CACHE_META = ${STARROCKS_HOME}/ebs/block-cache-meta

# Caching

block_cache_enable = true
block_cache_disk_path = ${BLOCK_CACHE_DIR}
block_cache_meta_path = ${BLOCK_CACHE_META}

block_cache_block_size = 1048576
block_cache_mem_size = 2147483648
block_cache_disk_size = 21474836480
```

4. BE failed to start. The log says:
```
config field error: block_cache_disk_path
error read config file. 
```

**Comment by didip** [comment]
oh interesting.

This part is the one that doesn't work:
```
BLOCK_CACHE_DIR = ${STARROCKS_HOME}/ebs/block-cache
BLOCK_CACHE_META = ${STARROCKS_HOME}/ebs/block-cache-meta
```

When I explicitly defined BLOCK_CACHE_DIR and BLOCK_CACHE_META in environment variables, this substitution works
```
block_cache_disk_path = ${BLOCK_CACHE_DIR}
block_cache_meta_path = ${BLOCK_CACHE_META}
```

**Comment by didip** [comment]
ooo i see what's happening.
```
The uppercase properties are read and exported by bin/start_fe.sh
```
I wrote my own startup script that doesn't do this. OK, this makes sense.
