### ISSUE TITLE
sql result error

### ISSUE THREAD

**Issue by hiliuxg** [StarRocks/starrocks#16614]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE SQL

CREATE TABLE `flink_fx_user_in_room_heartbeat_part_i` (
  `dt` date NOT NULL COMMENT "dt",
  `system_default_id` varchar(60) NOT NULL  ,
  `server_time` varchar(65533) NULL ,
  `order` bigint(20) NULL ,
  `visibility` int(11) NULL ,
  `duration` bigint(20) NULL ,
  `stage` int(11) NULL ,
  `imei` varchar(65533) NULL ,
  `sid` varchar(65533) NULL ,
  `state` int(11) NULL 
) ENGINE=OLAP 
PRIMARY KEY(`dt`, `system_default_id`)
PARTITION BY RANGE(`dt`)
(PARTITION p20230108 VALUES [('2023-01-08'), ('2023-01-09')),
PARTITION p20230109 VALUES [('2023-01-09'), ('2023-01-10')),
PARTITION p20230110 VALUES [('2023-01-10'), ('2023-01-11')),
PARTITION p20230111 VALUES [('2023-01-11'), ('2023-01-12')),
PARTITION p20230112 VALUES [('2023-01-12'), ('2023-01-13')),
PARTITION p20230113 VALUES [('2023-01-13'), ('2023-01-14')),
PARTITION p20230114 VALUES [('2023-01-14'), ('2023-01-15')),
PARTITION p20230115 VALUES [('2023-01-15'), ('2023-01-16')),
PARTITION p20230116 VALUES [('2023-01-16'), ('2023-01-17')))
DISTRIBUTED BY HASH(`system_default_id`) BUCKETS 34 
PROPERTIES (
"replication_num" = "3",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-7",
"dynamic_partition.end" = "1",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "34",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"storage_medium" = "SSD"
);

2. SELECT  SQL
sql 1:
select sid,
             imei,
             state,
             cast(server_time as datetime) as server_time,
             date_trunc('minute', server_time) as __timestamp
      from fx_dcl.flink_fx_user_in_room_heartbeat_part_i
      where dt between '2023-01-15T13:45:57' and '2023-01-15T16:45:57'
limit 10

sql 2:
select sid,
        imei,
         state,
         cast(server_time as datetime) as server_time,
         date_trunc('minute', server_time) as __timestamp
      from fx_dcl.flink_fx_user_in_room_heartbeat_part_i
      where dt >= '2023-01-15T13:45:57' and  dt <= '2023-01-15T16:45:57'
limit 10

### Expected behavior (Required)
the sql 1 and sql 2 have the same result 

### Real behavior (Required)
sql 1return 10 records but sql 2 return null 

### StarRocks version (Required)
2.2.2 e27e2aa

**Comment by Seaven** [comment]
in 2.2.2
`date >= string` will cast to 'cast(date as datetime) >= cast(string as datetime)', 
but `date between string and string` will cast to `date >= cast(string as date) and date <= cast(string as date)`
so...the result is different

sr was fixed the question in later versions
