### ISSUE TITLE
flinksql  sink starrocks exactly once is not right, some data repeat

### ISSUE THREAD

**Issue by yaobukeji123** [StarRocks/starrocks#16640]
1、my flinksql job info 
-kafka in
![image](https://user-images.githubusercontent.com/35523218/212619749-1aca280e-53b3-425e-ad17-91a54027bc53.png)
-sr out (partial)
![image](https://user-images.githubusercontent.com/35523218/212619975-72ff7635-f27d-4e1a-9319-d3e64d768eaf.png)
--view to adjust field order and type (partial)
![image](https://user-images.githubusercontent.com/35523218/212620379-d613e253-c270-4fcd-8827-4d5c0253d252.png)
--etl 
![image](https://user-images.githubusercontent.com/35523218/212620416-5e990c5a-5570-4871-8b63-d2bc377a55dc.png)

### Expected behavior (Required)
data not repeat ,according to uuid to prove，kafka uuid is only once

### Real behavior (Required)
![image](https://user-images.githubusercontent.com/35523218/212621345-cd22e87c-4c9a-4fde-b29d-136ac8977c09.png)

some else
my sr cluster is not stable period,flink checkpoint fail period, may cause this result

### StarRocks version (Required)
  -2.3.2

**Comment by banmoy** [comment]
@yaobukeji123 What's the version of your Flink and starrocks connector? Do you set `sink.delivery-guarantee` to `exactly-once` for kafka connector?

**Comment by banmoy** [comment]
@yaobukeji123 If you want to use exactly-once, I suggest you first upgrade the starrocks to at least 2.4, and use the newest connector 1.2.6. We have improved the implementation of exactly-once greatly with the transaction stream load of starrocks which is supported since starrocks 2.4.
