### ISSUE TITLE
[fqdn] modify frontend host failed

### ISSUE THREAD

**Issue by huoyue-git** [StarRocks/starrocks#16714]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
![86495b12-81ca-45fe-a592-0f6a70d073f5](https://user-images.githubusercontent.com/91584973/212858315-b2f696d0-ce5c-48e4-b96a-6aeff8a88b27.jpeg)
![0e6d63f1-ab1c-4d6c-b86b-59bedd30e76d](https://user-images.githubusercontent.com/91584973/212858332-aed19229-281b-4087-aa7a-0ffda11e13f5.jpeg)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.5-RELEASE f2dc50b |
+----------------------------+
1 row in set (0.09 sec)

**Comment by gengjun-git** [comment]
fixed by https://github.com/StarRocks/starrocks/pull/14932
