### ISSUE TITLE
基于更新模型的数据追溯场景扩展建议

### ISSUE THREAD

**Issue by RunningXuan** [StarRocks/starrocks#16741]
更新模型并没有删除历史数据，能否增加个版本号的查询条件判断就可以让用户查询历史数据，这样就很方便的支撑了数据追溯场景，比如说追溯某个员工或者高管的职位、履历等变更记录，追溯数据的更变时间等等

**Comment by chaoyli** [comment]
@RunningXuan About the time-travel query, it is on the roadmap.

**Comment by RunningXuan** [comment]
roadmap 公开了吗？在哪里可以看到，想知道这个功能大概什么时间上线
