### ISSUE TITLE
[FR] Jupysql integration

### ISSUE THREAD

**Issue by idomic** [StarRocks/starrocks#16813]
## Description
It'd be great to see a tutorial or documentation of the 2 frameworks.
Probably a user working locally via a jupyter notebook and [jupysql](https://github.com/ploomber/jupysql) to query and perform EDA/modeling work.

## Motivation
Please provide the following for the desired feature or change:

A detailed explanation on querying via SQL.
Plotting via sql.
Using Jupyter notebooks to query.

Happy to work on the PR!

**Comment by imay** [comment]
That's a good idea to integrate these two frameworks.
Could you let me know if you have successfully integrated these two?

**Comment by idomic** [comment]
@imay I just did with the help I got from Alvin.
I was able to launch Starrocks on top of docker and query it via Jupysql.

I was thinking of adding a [guide here](https://github.com/StarRocks/starrocks/tree/a14ff60a2850c2a40d9ddcbf8cd6173d954baea3/docs/integrations) to allow users who want to connect from Jupyter notebooks.

Do you have an end-to-end sample you want to show? I saw the quickstart guide is just loading some dummy data.

**Comment by idomic** [comment]
@imay update on my end: I was able to run a sample with starrocks and it works great. Where's the documentation guide's repo? I can open a PR to add this section
