### ISSUE TITLE
Validate casting string to array 

### ISSUE THREAD

**Issue by mofeiatwork** [StarRocks/starrocks#16864]
### Steps to reproduce the behavior (Required)
```sql
select cast('1' as array<string>);
select cast('{}' as array<string>);
select cast('"a"' as array<string>)
```

### Expected behavior (Required)
All of these should fail since it's not a valid array syntax, which should be `["a", "b", "c"]` .

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by chenshaojin** [comment]
升级过程中，因为并没有信息提醒cast函数不再支持非'[]'类型转换成array，导致一直认为是升级版本之间不兼容导致。严谨一些是否将此函数一些转换失败的异常信息，而不是null呢？因为升级逐步升级worker，导致升级的这台worker上数据为null，而其他worker数据不为null，如果这个sql是一个实时报表表现形式就会造成结果值是跳动的，因为升级的worker处理的数据不是固定的。没有错误提醒将很难排查到cast函数逻辑发生了改变。或者说这本不是一个bug；eg：cast('a,b,c' as array<string>)

**Comment by chenshaojin** [comment]
@mofeiatwork
