### ISSUE TITLE
some advice about cross join.

### ISSUE THREAD

**Issue by yongbingwang** [StarRocks/starrocks#1693]
## Enhancement
![image](https://user-images.githubusercontent.com/86867342/143827626-c9eeb706-8fad-414e-8ef5-7657d0f45223.png)
query A:
```
SELECT count(*) from part a cross JOIN part b;
```
query B:
```
mysql> select count(*) from part;
+----------+
| count(*) |
+----------+
|  2000000 |
+----------+
1 row in set (0.03 sec)
```
The time cost of query A is 13 mins and query B is  0.03 s. i don't think it is reasonable. 
There is no join conditions in this query and the final result of the query is count of cross join rows.
It is better if the optimizer could do like this.
1. select count(*) from part; result = a
2. return a * a

**Comment by jaogoy** [comment]
I think it has little benifit to do such optimizaiton in this situation.

**Comment by Seaven** [comment]
That‘s so rare case
