### ISSUE TITLE
The first query result is not the same as the one after

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#1694]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS h85;
CREATE DATABASE h85;
USE h85;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 BOOLEAN NULL ,c_0_1 DATE NULL ,c_0_2 DECIMAL128(36, 16)  NOT NULL ,c_0_3 DOUBLE NOT NULL ,c_0_4 VARCHAR(1) NOT NULL ,c_0_5 LARGEINT NULL ,c_0_6 FLOAT NOT NULL ,c_0_7 FLOAT NOT NULL ,c_0_8 CHAR(1) NOT NULL ,c_0_9 BOOLEAN NOT NULL ,c_0_10 DECIMAL128(21, 11)  NOT NULL ,c_0_11 DECIMAL128(11, 3)  NULL ,c_0_12 LARGEINT NOT NULL ,c_0_13 DOUBLE NULL ,c_0_14 BIGINT NOT NULL ,c_0_15 INT NOT NULL ) DUPLICATE KEY (c_0_0,c_0_1) DISTRIBUTED BY HASH (c_0_1) properties("replication_num"="1") ;
CREATE TABLE t1 (c_1_0 DECIMAL128(2, 1)  NOT NULL ,c_1_1 DECIMAL128(8, 3)  NOT NULL ,c_1_2 DECIMAL128(11, 3)  NULL ,c_1_3 DATETIME NULL ,c_1_4 TINYINT NOT NULL ,c_1_5 VARCHAR(1) NOT NULL ,c_1_6 DOUBLE NOT NULL ,c_1_7 DECIMAL(4, 0)  NULL ,c_1_8 DECIMAL64(5, 5)  NULL ,c_1_9 FLOAT NOT NULL ,c_1_10 CHAR(21) NULL ,c_1_11 BOOLEAN NULL ,c_1_12 LARGEINT NULL ,c_1_13 DOUBLE NULL ,c_1_14 DATE NULL ,c_1_15 FLOAT NOT NULL ) DUPLICATE KEY (c_1_0,c_1_1,c_1_2,c_1_3) DISTRIBUTED BY HASH (c_1_2,c_1_0,c_1_3) properties("replication_num"="1") ;
CREATE TABLE t2 (c_2_0 DECIMAL(10, 9)  NULL ,c_2_1 SMALLINT NULL ,c_2_2 DATE MIN NULL ,c_2_3 DOUBLE SUM NULL ,c_2_4 BOOLEAN REPLACE NULL ,c_2_5 BOOLEAN REPLACE NOT NULL ,c_2_6 DECIMAL128(5, 0)  REPLACE NULL ,c_2_7 DECIMAL128(8, 4)  MIN NOT NULL ) AGGREGATE KEY (c_2_0,c_2_1) DISTRIBUTED BY HASH (c_2_0) properties("replication_num"="1") ;
CREATE TABLE IF NOT EXISTS t3 (c_3_0 DECIMAL(1, 0)  NULL ) DUPLICATE KEY (c_3_0) DISTRIBUTED BY HASH (c_3_0) properties("replication_num"="1") ;
INSERT INTO t3 VALUES (1);
INSERT INTO t1 VALUES (0.2, 0.024, 33219.157, "1970-01-01 08:00:00", 1, "", 0.5872441941371875, 1685, 0.00005, 1.997531379E9, "q", false, NULL, 6.54313714E8, "1970-01-01", 0.6226784860723025);
INSERT INTO t0 VALUES (false, "1970-01-01", 6258.1243091650823786, 0.3217100156596383, "", NULL, 0.8875369735479076, 0.12891409745609328, "", true, 0.05095073818, 76290.967, 0, 0.1330218350692972, 1199032, 13), (true, "1970-01-01", 4286.6532208049739231, 0.023224845094999003, "", 1142644499, 0.24435013230994884, 0.06685267503809522, "", false, 0.00391236167, 49506.176, -1646249553, 0.23393273840779505, 415906920, 20);
INSERT INTO t3 VALUES (5), (5), (8);
INSERT INTO t1 VALUES (0.3, 7.474, 93239.802, "1970-01-01 08:00:00", 7, "", 0.31785755871206756, 9748, 0.00001, 0.3643585915132076, "U", false, NULL, 1.915768952E9, "1970-01-01", -1.646249553E9), (0.3, 95.808, 63775.315, "1970-01-01 08:00:00", 2, "", 1.330846834E9, 9757, NULL, 7.05509884E8, "qi", false, 355843603, '+Inf', "1970-01-01", 0.402021809051882), (0.6, 61.883, 11322.513, "1970-01-01 08:00:00", 2, "", 0.6325968652510355, 7560, NULL, 0.5305793710796008, "5", false, -455726726, 0.33949649353470035, "1970-01-01", -1.601698821E9);
INSERT INTO t1 VALUES (0.3, 56.439, 2719.269, "1970-01-01 08:00:00", 2, "", 0.6990030639228475, 879, 0.00002, 0.21171321637531337, "FLtezT", true, -965250102, 0.27419447860774815, "1970-01-01", 0.17148924389572318);
INSERT INTO t2 VALUES (4E-9, 10, "1970-01-01", 0.9794520564929549, true, true, 76750, 0.6830), (1E-9, 7, "1970-01-01", NULL, NULL, true, 45389, 0.9145);
INSERT INTO t1 VALUES (0.1, 58.692, 25251.870, "1970-01-01 08:00:00", 2, "", 0.6608555648662383, 5949, 0.00000, 0.8273073997434381, "jdAjOnlX", NULL, -1777117792, 6.24961368E8, "1970-01-01", 0.45385361775933153), (0.4, 90.530, 50022.192, "1970-01-01 08:00:00", 4, "", 0.46534098101110866, 7284, 0.00001, 0.732541598994446, "", true, -1047643700, NULL, "1970-01-01", 0.457594459693493);
INSERT INTO t0 VALUES (NULL, "1970-01-01", 7106.5321719448409135, 0.20790224314311756, "", -731287722, -3.1018306E7, 0.4719166065039264, "", false, 0.07054194312, 90579.386, -813155498, 0.2250737671609998, 1208645751, 12), (false, "1970-01-01", 1489.6741164876921526, 0.13903920474989095, "", -1072754877, 0.9639872706966924, 0.9858333671123657, "", false, 0.02750273879, 55141.881, 822857676, -1.167728658E9, -620070481, 27);
DELETE FROM t1 WHERE c_1_1=77.320 AND c_1_3=NULL;
INSERT INTO t1 VALUES (0.2, 35.889, NULL, "1970-01-01 08:00:00", 2, "", 0.8003195047584896, 2260, 0.00002, 0.23374884261084417, "7", false, -1601698821, 0.0727817994758696, "1970-01-01", 0.501816930825343);
INSERT INTO t2 VALUES (5E-9, 9, "1970-01-01", 0.1185912144526754, true, true, 21145, 0.7031), (5E-9, 10, "1970-01-01", -5.35073199E8, false, true, 27186, 0.8631);

2. SELECT subt2.c_2_0 FROM  (SELECT t2.c_2_0, t2.c_2_1, t2.c_2_2, t2.c_2_3, t2.c_2_4, t2.c_2_5, t2.c_2_6, t2.c_2_7 FROM t2) subt2 RIGHT JOIN t3 ON subt2.c_2_4 = t3.c_3_0 AND subt2.c_2_4 = t3.c_3_0 WHERE true GROUP BY subt2.c_2_0;

### Real behavior (Required)
mysql> SELECT subt2.c_2_0 FROM  (SELECT t2.c_2_0, t2.c_2_1, t2.c_2_2, t2.c_2_3, t2.c_2_4, t2.c_2_5, t2.c_2_6, t2.c_2_7 FROM t2) subt2 RIGHT JOIN t3 ON subt2.c_2_4 = t3.c_3_0 AND subt2.c_2_4 = t3.c_3_0 WHERE true GROUP BY subt2.c_2_0;
+-------------+
| c_2_0       |
+-------------+
|        NULL |
| 0.000000004 |
+-------------+
2 rows in set (0.08 sec)

mysql> SELECT subt2.c_2_0 FROM  (SELECT t2.c_2_0, t2.c_2_1, t2.c_2_2, t2.c_2_3, t2.c_2_4, t2.c_2_5, t2.c_2_6, t2.c_2_7 FROM t2) subt2 RIGHT JOIN t3 ON subt2.c_2_4 = t3.c_3_0 AND
subt2.c_2_4 = t3.c_3_0 WHERE true GROUP BY subt2.c_2_0;
+-------------+
| c_2_0       |
+-------------+
| 0.000000004 |
| 0.000000005 |
|        NULL |
+-------------+

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.0 asan
 - mysql> select current_version();
+------------------------------+
| current_version()            |
+------------------------------+
| SQLANCER_BRANCH_ASAN 49b22bf |
+------------------------------+

**Comment by Seaven** [comment]
set variable:
```
set cbo_enable_replicated_join=false;
```

```
mysql> SELECT subt2.c_2_0 FROM t2 subt2 RIGHT JOIN t3 ON subt2.c_2_4 = t3.c_3_0  GROUP BY subt2.c_2_0;
+-------------+
| c_2_0       |
+-------------+
| 0.000000004 |
|        NULL |
+-------------+
2 rows in set (0.01 sec)
```

```
mysql> SELECT subt2.c_2_0 FROM t2 subt2 RIGHT JOIN t3 ON subt2.c_2_4 = t3.c_3_0 ;
+-------------+
| c_2_0       |
+-------------+
| 0.000000005 |
| 0.000000004 |
|        NULL |
|        NULL |
|        NULL |
+-------------+
5 rows in set (0.01 sec)
```

**Comment by Seaven** [comment]
+-------------------------------------------------------------------------------------------------+
| Explain String                                                                                  |
+-------------------------------------------------------------------------------------------------+
| PLAN FRAGMENT 0                                                                                 |
|  OUTPUT EXPRS:1: c_2_0                                                                          |
|   PARTITION: UNPARTITIONED                                                                      |
|                                                                                                 |
|   RESULT SINK                                                                                   |
|                                                                                                 |
|   11:EXCHANGE                                                                                   |
|      use vectorized: true                                                                       |
|                                                                                                 |
| PLAN FRAGMENT 1                                                                                 |
|  OUTPUT EXPRS:                                                                                  |
|   PARTITION: HASH_PARTITIONED: 1: c_2_0                                                         |
|                                                                                                 |
|   STREAM DATA SINK                                                                              |
|     EXCHANGE ID: 11                                                                             |
|     UNPARTITIONED                                                                               |
|                                                                                                 |
|   10:AGGREGATE (merge finalize)                                                                 |
|   |  group by: 1: c_2_0                                                                         |
|   |  use vectorized: true                                                                       |
|   |                                                                                             |
|   9:EXCHANGE                                                                                    |
|      use vectorized: true                                                                       |
|                                                                                                 |
| PLAN FRAGMENT 2                                                                                 |
|  OUTPUT EXPRS:                                                                                  |
|   PARTITION: HASH_PARTITIONED: 10: cast                                                         |
|                                                                                                 |
|   STREAM DATA SINK                                                                              |
|     EXCHANGE ID: 09                                                                             |
|     HASH_PARTITIONED: 1: c_2_0                                                                  |
|                                                                                                 |
|   8:AGGREGATE (update serialize)                                                                |
|   |  STREAMING                                                                                  |
|   |  group by: 1: c_2_0                                                                         |
|   |  use vectorized: true                                                                       |
|   |                                                                                             |
|   7:Project                                                                                     |
|   |  <slot 1> : 1: c_2_0                                                                        |
|   |  use vectorized: true                                                                       |
|   |                                                                                             |
|   6:HASH JOIN                                                                                   |
|   |  join op: RIGHT OUTER JOIN (PARTITIONED)                                                    |
|   |  hash predicates:                                                                           |
|   |  colocate: false, reason:                                                                   |
|   |  equal join conjunct: 10: cast = 11: cast                                                   |
|   |  use vectorized: true                                                                       |
|   |                                                                                             |
|   |----5:EXCHANGE                                                                               |
|   |       use vectorized: true                                                                  |
|   |                                                                                             |
|   2:EXCHANGE                                                                                    |
|      use vectorized: true                                                                       |
|                                                                                                 |
| PLAN FRAGMENT 3                                                                                 |
|  OUTPUT EXPRS:                                                                                  |
|   PARTITION: RANDOM                                                                             |
|                                                                                                 |
|   STREAM DATA SINK                                                                              |
|     EXCHANGE ID: 05                                                                             |
|     HASH_PARTITIONED: 11: cast                                                                  |
|                                                                                                 |
|   4:Project                                                                                     |
|   |  <slot 11> : CAST(9: c_3_0 AS DECIMAL32(1,0))                                               |
|   |  use vectorized: true                                                                       |
|   |                                                                                             |
|   3:OlapScanNode                                                                                |
|      TABLE: t3                                                                                  |
|      PREAGGREGATION: ON                                                                         |
|      partitions=1/1                                                                             |
|      rollup: t3                                                                                 |
|      tabletRatio=10/10                                                                          |
|      tabletList=3031478,3031480,3031482,3031484,3031486,3031488,3031490,3031492,3031494,3031496 |
|      cardinality=4                                                                              |
|      avgRowSize=2.0                                                                             |
|      numNodes=0                                                                                 |
|      use vectorized: true                                                                       |
|                                                                                                 |
| PLAN FRAGMENT 4                                                                                 |
|  OUTPUT EXPRS:                                                                                  |
|   PARTITION: RANDOM                                                                             |
|                                                                                                 |
|   STREAM DATA SINK                                                                              |
|     EXCHANGE ID: 02                                                                             |
|     HASH_PARTITIONED: 10: cast                                                                  |
|                                                                                                 |
|   1:Project                                                                                     |
|   |  <slot 1> : 1: c_2_0                                                                        |
|   |  <slot 10> : CAST(5: c_2_4 AS DECIMAL32(1,0))                                               |
|   |  use vectorized: true                                                                       |
|   |                                                                                             |
|   0:OlapScanNode                                                                                |
|      TABLE: t2                                                                                  |
|      PREAGGREGATION: ON                                                                         |
|      partitions=1/1                                                                             |
|      rollup: t2                                                                                 |
|      tabletRatio=10/10                                                                          |
|      tabletList=3031455,3031457,3031459,3031461,3031463,3031465,3031467,3031469,3031471,3031473 |
|      cardinality=4                                                                              |
|      avgRowSize=3.0                                                                             |
|      numNodes=0                                                                                 |
|      use vectorized: true                                                                       |
+-------------------------------------------------------------------------------------------------+

**Comment by kangkaisen** [comment]
https://github.com/StarRocks/starrocks/pull/1726 has fixed this issue.
