### ISSUE TITLE
Failed to modify colocate group status by api

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#1705]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE t_1 (
                            `id` int(18),
                            `value` varchar(20)
                        )
                        ENGINE=OLAP
                        DUPLICATE KEY(`id`)
                        COMMENT "OLAP"
                        DISTRIBUTED BY HASH(`id`) BUCKETS 3
                        PROPERTIES (
                            "replication_num" = "1",
                            "storage_format" = "v2",
                            "colocate_with" = "group1"
                        );
2. SHOW PROC '/colocation_group';
3. DELETE /api/colocate/group_stable?db_id=10005&group_id=10008
4. SHOW PROC '/colocation_group';

### Expected behavior (Required)
group status is unstable
### Real behavior (Required)
group status is stable
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by wyb** [comment]
This behavior is opposite to the documentation. 
https://docs.starrocks.com/zh-cn/main/using_starrocks/Colocation_join#http-restful-api

This interface uses post and delete to distinguish make unstable or stable, and is confusing.

I think it would be better to change to the following:
`POST /api/colocate/group_stable?db_id=10005&group_id=10008` make group stable
`POST /api/colocate/group_unstable?db_id=10005&group_id=10008` make group unstable
