### ISSUE TITLE
execute sql unknow error

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#1706]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS n2;
CREATE DATABASE n2;
USE n2;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DECIMAL64(4, 4)  NULL ,c_0_1 VARCHAR(11) NOT NULL ,c_0_2 BOOLEAN NULL ,c_0_3 TINYINT NULL ,c_0_4 DECIMAL32(8, 6)  NULL ,c_0_5 DECIMAL(11, 7)  NULL ,c_0_6 CHAR(1) NULL ,c_0_7 DECIMAL32(6, 6)  NOT NULL ,c_0_8 DECIMAL64(15, 12)  NOT NULL ,c_0_9 LARGEINT NULL ,c_0_10 DECIMAL(12, 4)  NOT NULL ,c_0_11 DATE NOT NULL ,c_0_12 DECIMAL32(7, 0)  NOT NULL ) DUPLICATE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5) DISTRIBUTED BY HASH (c_0_1,c_0_3,c_0_0,c_0_4,c_0_5) properties("replication_num"="1") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DECIMAL64(5, 2)  NULL ,c_1_1 DECIMAL128(9, 8)  NULL ,c_1_2 DECIMAL32(6, 0)  NOT NULL ,c_1_3 DATE NOT NULL ,c_1_4 BOOLEAN NULL ,c_1_5 DECIMAL(24, 2)  NULL ,c_1_6 BOOLEAN NOT NULL ,c_1_7 DECIMAL(26, 1)  NOT NULL ,c_1_8 PERCENTILE PERCENTILE_UNION NOT NULL ,c_1_9 BITMAP BITMAP_UNION NULL ) AGGREGATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6,c_1_7) DISTRIBUTED BY HASH (c_1_3,c_1_2,c_1_7,c_1_6,c_1_0,c_1_1,c_1_4,c_1_5) properties("replication_num"="1") ;
CREATE TABLE IF NOT EXISTS t2 (c_2_0 DATE NULL ,c_2_1 DECIMAL32(2, 2)  NULL ,c_2_2 DECIMAL(10, 2)  NOT NULL ,c_2_3 BOOLEAN NULL ,c_2_4 DATE NOT NULL ,c_2_5 DOUBLE NULL ,c_2_6 BOOLEAN NULL ,c_2_7 DECIMAL64(7, 1)  NOT NULL ,c_2_8 TINYINT NOT NULL ,c_2_9 BOOLEAN NOT NULL ,c_2_10 DOUBLE NULL ,c_2_11 FLOAT NOT NULL ,c_2_12 DECIMAL64(9, 9)  NOT NULL ,c_2_13 BOOLEAN NULL ,c_2_14 DECIMAL32(4, 1)  NOT NULL ,c_2_15 BIGINT NOT NULL ) DUPLICATE KEY (c_2_0,c_2_1,c_2_2,c_2_3) DISTRIBUTED BY HASH (c_2_0,c_2_1,c_2_3,c_2_2) properties("replication_num"="1") ;
INSERT INTO t2 VALUES ("1970-01-01", 0.04, 555995.57, true, "1970-01-01", 0.6295136534878222, NULL, 97030.6, 4, false, 0.20772079136100186, 0.27064523444088506, 6E-9, true, 62.1, 536674365), ("1970-01-01", 0.02, 51988.35, true, "1970-01-01", -1.84850493E9, false, 90781.4, 5, false, 4.05958948E8, 0.06775173867870277, 5E-9, false, 97.0, -99891779);
DELETE FROM t0 WHERE c_0_5=NULL AND c_0_2=NULL AND c_0_3=189558330 AND c_0_4=NULL AND c_0_1="c";
INSERT INTO t0 VALUES (0.0005, "y17M", false, 3, 0.000070, 0.0007716, "", 0.000002, 5.86E-10, 1278276947, 8196.2125, "1970-01-01", 7518091), (0.0000, "", true, 5, 0.000075, 0.0003532, "", 0.000000, 1.38E-10, 1331783632, 68.0594, "1970-01-01", 292423);
INSERT INTO t0 VALUES (0.0002, "bdf", NULL, 1, 0.000028, NULL, NULL, 0.000006, 8.74E-10, 2076812971, 8477.7120, "1970-01-01", 4586355);
INSERT INTO t2 VALUES ("1970-01-01", NULL, 723738.29, false, "1970-01-01", 0.672135962520473, false, 90585.4, 3, true, 0.18459425747808822, 0.2623960612721553, 8E-9, false, 71.7, -339560273);
INSERT INTO t0 VALUES (0.0004, "4khLe", true, 3, 0.000061, 0.0004387, "", 0.000003, 1.02E-10, -99891779, 6289.1450, "1970-01-01", 5593299), (0.0003, "N89Iw8P", false, 7, 0.000091, 0.0006959, "", 0.000006, 9.15E-10, -212817545, 5144.9287, "1970-01-01", 7486065);
INSERT INTO t1 VALUES (8.25, 5E-8, 823623, "1970-01-01", true, 96764238757310754225.36, true, 912641792881641045198737.5, percentile_hash("-1436052591"), bitmap_hash("FNd7cen"));
INSERT INTO t0 VALUES (0.0004, "", true, 5, 0.000006, NULL, NULL, 0.000006, 4.57E-10, 2100766036, 3747.7450, "1970-01-01", 9316401);
INSERT INTO t1 VALUES (7.09, 1E-8, 757986, "1970-01-01", true, 45982245332919556309.88, false, 621836109175050388842011.9, percentile_hash("53347973"), bitmap_hash(""));
INSERT INTO t2 VALUES ("1970-01-01", NULL, 500927.16, true, "1970-01-01", 0.15121912985701114, NULL, 63569.5, 6, true, 0.2615430350187816, 0.9856992279605874, 2E-9, false, 1.5, 1822965669), ("1970-01-01", 0.04, 946822.81, false, "1970-01-01", 0.6264688861495696, true, 75036.0, 7, true, 0.5828461188082539, 0.4258764811240511, 2E-9, true, 55.1, -669821205);

2. SELECT SUM(count) FROM (SELECT CAST((CAST(false AS BOOLEAN) = true) AND (CAST(false AS BOOLEAN) IS NOT NULL) AS INT) as count FROM t2,   t0 LEFT SEMI JOIN t1 ON t0.c_0_4 = t1.c_1_0 AND t0.c_0_4 >= t1.c_1_0 AND t0.c_0_10 > t1.c_1_4 AND t0.c_0_10 <= t1.c_1_4) t;

### Expected behavior (Required)
query correct
### Real behavior (Required)
Unknown error
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - main release
 - mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN 9c58955   |
+-------------------+

**Comment by Seaven** [comment]
@HangyuanLiu PTAL, the question like projection is empty
