### ISSUE TITLE
The status of tablet is inconsistent at different  FE.

### ISSUE THREAD

**Issue by yongbingwang** [StarRocks/starrocks#1708]
### Steps to reproduce the behavior (Required)
```
mysql> ADMIN SET REPLICA STATUS PROPERTIES("tablet_id" = "19291", "backend_id" = "10004", "status" = "bad");
Query OK, 0 rows affected (0.00 sec)
```
### Expected behavior (Required)
true,false,false
### Real behavior (Required)
one FE：
The status of tablet's isbad of 19291 is (**true**,false,false).
another FE：
The status of tablet's isbad of 19291 is (**false**,false,false).
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
-2.0

**Comment by gengjun-git** [comment]
The replica whose bad status is true will be fixed when processing tablet report. But the bad status will only be set to false in non-master fes. The reason is that we need to delete the broken replica by manually setting the status. This is a little tricky.
