### ISSUE TITLE
Permanently delete rows when rows are deleted in Duplicate key model by Starrocks UI

### ISSUE THREAD

**Issue by devendradora-ngram** [StarRocks/starrocks#17270]
## Feature request

**Is your feature request related to a problem? Please describe.**

There are many instances where we delete rows once in a while in duplicate key model , but the  select query performance is very slow on that particular table.

**Describe the solution you'd like**

We want some feature by which we can permanently delete deleted rows. According to one of the conversation with starrocks team , base compaction could remove deleted rows, but there’s no interface for it. Please can you provide interface for it

**Describe alternatives you've considered**

**Additional context**

**Comment by howrocks** [comment]
Good advice,  we will support an interface on FE to trigger table compaction, so all the deleted data will be merged.
