### ISSUE TITLE
After schema change&read&write for hours, meet alter error and already been compacted error

### ISSUE THREAD

**Issue by meegoo** [StarRocks/starrocks#17280]
### Steps to reproduce the behavior (Required)
1. alter tablet
2. write data to table

### Expected behavior (Required)
success

### Real behavior (Required)
ERROR: 2023-02-01 07:38:37,086 * [52664:7fa584ff9700] [test_duplicate.py:913] select_error:{'status': False, 'msg': (1064, 'version already been compacted. tablet_id: 12646993, version: 11712')}

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by huoarter** [comment]
https://forum.mirrorship.cn/t/topic/15591   
For a real-time write table, performing an ALTER TABLE operation may result in a "too many versions" error
