### ISSUE TITLE
Using the GROUP_CONCAT function, i want to concatenate a number of fields, the same deduplicated

### ISSUE THREAD

**Issue by lynnkechel** [StarRocks/starrocks#1733]
GROUP_CONCAT(DISTINCT column)，Is it not supported in this form or will it be supported in the future

**Comment by imay** [comment]
This feature is in our roadmap. And it will be supported in a future release.

**Comment by lynnkechel** [comment]
> This feature is in our roadmap. And it will be supported in a future release.

thanks so much
