### ISSUE TITLE
Connector: Metabase

### ISSUE THREAD

**Issue by dannyeuu** [StarRocks/starrocks#17363]
### Metabase connector request
Metabase is the BI tool with the friendly UX and integrated tooling to let your company explore data on their own

I created a feature request on Metabase repository too https://github.com/metabase/metabase/issues/28081

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by imay** [comment]
@dannyeuu Thank you for creating the request in the metabase repo. For now, you can connect starrocks and metabase with MySQL connector.

**Comment by alberttwong** [comment]
https://github.com/metabase/metabase/issues/35070
