### ISSUE TITLE
[Good First Issue] Substitute header guard to pragma once

### ISSUE THREAD

**Issue by imay** [StarRocks/starrocks#1741]
New header files uses `#pragma once` as header guard.
Some older files still use macro definitions as header guards.
We should substitute it with `#pragma once`.

This job does not require great familiarity with StarRocks. Perfect for people who are new to StarRocks.
Everyone is very welcome to contribute.

Please let me know if you want to handle it.

**Comment by tr29038** [comment]
Hey I would be happy to take this issue.

**Comment by imay** [comment]
@tr29038 
Thank you in advance. 
I suggest that you can modify one file in your first PR.
