### ISSUE TITLE
Backport PR #13707 to 2.5 ? 

### ISSUE THREAD

**Issue by fulghum** [StarRocks/starrocks#17467]
## General Question

Hello StarRocks friends 👋  I contributed a PR (https://github.com/StarRocks/starrocks/pull/13707) that was merged into `main` at the end of November 2022, but it doesn't seem to be included in the latest StarRocks release for 2.5.1. 

Is there another step I need to take to get that PR merged to the 2.5 release branch so that it gets included in the next release?

Thanks for any help you can provide!

**Comment by imay** [comment]
That is because when this PR is merged, branch-2.5 is cut. You can backport it to branch 2.5 if you want it in version 2.5.*. Otherwise, it will be released in the next major version, that would be in next month

**Comment by fulghum** [comment]
Thank you @imay! 🙏  That makes sense. I wasn't aware that release had been in planning since then. I think we can wait until the next major version release next month and use a dev build until then. I'll chat with our customer and may send over a backmerge PR for the 2.5.x line if they do need it. 

Thanks again for such a fast response!!
