### ISSUE TITLE
[Bugfix] query hive external text table , column case will  lead to reading failed

### ISSUE THREAD

**Issue by Jay-ju** [StarRocks/starrocks#17518]
### Steps to reproduce the behavior (Required)
**Step1:**     in hive
create table test(a int,  b string) stored as csv;
insert into test values(1, 'aa');

**Step2:**    query in sr
create external table test_sr (A int, B string) properties ()
select * from test_sr;

### Expected behavior (Required)

record can be found out.

### Real behavior (Required)
throw fail message "Can not get index of column name"

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by jaogoy** [comment]
So, is there any problem, that you closed this issue?
