### ISSUE TITLE
[Enhancement] Support jsonpath parsing for key in json containing .

### ISSUE THREAD

**Issue by itcats-cn** [StarRocks/starrocks#17545]
Our device logs contain 2 special fields, `"id.orig_h"`  and `"id.orig_p"`  key in the json contain .
For example:
```json
{
     "ts":1662565608.72016,
     "uid":"CKqtT7etgpCZDB5x9",
     "id.orig_h":"10.1.3.168",
     "id.orig_p": 49528
}
```
But currently Starrocks cannot parse the key-value pairs that contain `.` in the json key now
I tried the following jsonpath syntax, but it doesn't work
```bash
"jsonpaths" = "[\"$['ts']",\"$['uid']\",\"$['id.orig_h']\",\"$['id.orig_p']\"]"
"jsonpaths" = "[\"$.ts\",\"$.uid\",\"$.id\.orig_h\",\"$.id\.orig_p\"]"
```

it causes the values of two columns in the table to be captured as null

**Comment by mofeiatwork** [comment]
Good advice, it should be fixed later
