### ISSUE TITLE
OSS stuck in listPath after adding http:// to endpoint

### ISSUE THREAD

**Issue by xiaoyong-z** [StarRocks/starrocks#17726]
### Steps to reproduce the behavior (Required)

EXPORT TABLE duplicate_table_with_null TO "oss://xxx" 
PROPERTIES ("timeout" = "180") 
WITH BROKER hdfs_broker (
    'fs.oss.accessKeyId' = 'xxx',
    'fs.oss.accessKeySecret' = 'xxx',
    'fs.oss.endpoint' = 'http://oss-cn-zhangjiakou-internal.aliyuncs.com'
);
broker will stuck 
![image](https://user-images.githubusercontent.com/31178013/218396804-1f077c51-5385-41c6-a9f0-035793cb6915.png)

![image](https://user-images.githubusercontent.com/31178013/218396883-01b067fc-6c58-4237-8313-d7e4e4307b41.png)

### Expected behavior (Required)
success 
### Real behavior (Required)
broker stuck

### Other 
EXPORT TABLE duplicate_table_with_null TO "oss://xxx" 
PROPERTIES ("timeout" = "180") 
WITH BROKER hdfs_broker (
    'fs.oss.accessKeyId' = 'xxx',
    'fs.oss.accessKeySecret' = 'xxx',
    'fs.oss.endpoint' = 'oss-cn-zhangjiakou-internal.aliyuncs.com'
);

can success
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.5.0/main

**Comment by xiaoyong-z** [comment]
This problem is caused by jindo-4.6.2 sdk currently not supporting this

**Comment by miomiocat** [comment]
Prepfix `http://` is not valid OSS endpoint format

**Comment by xiaoyong-z** [comment]
If it is not valid,  i think it would be better to throw an exception, not stuck.
