### ISSUE TITLE
StarRocks支持jdbc连接吗

### ISSUE THREAD

**Issue by qy513449931** [StarRocks/starrocks#17761]
## General Question

大家好，我想通过API服务形式将StarRocks里的数据对外提供服务，以供业务同学使用，可是我不知道该怎样做，有没有相关的资料推荐

**Comment by imay** [comment]
Yes, you can use MySQL JDBC to connect to starrocks.
The following link is a demo of how to connect to StarRocks
https://github.com/StarRocks/demo/tree/master/MiscDemo/connect/java/client
