### ISSUE TITLE
[Bug] UDF is flaky on branch-2.5

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks#17823]
### Steps to reproduce the behavior (Required)
In this path, we have create a dummy udf and the test script to repro https://github.com/dengliu/starrocks/commit/48b8df43f3196e64ff4f1ae9340ee117f49b8e52#diff-78a6f1cd12f4dd1e03c3ae1c728b8defce8561d53f7087f2d622214d60197ee1

1) apply the above path to main HEAD or branch 2.5 HEAD
2) follow this [instruction](https://github.com/dengliu/starrocks/blob/48b8df43f3196e64ff4f1ae9340ee117f49b8e52/celonis/udfrepro/README.md) to build the allin1 image that packaged the dummy udf in the same container
3) run the [debug.sh](https://github.com/dengliu/starrocks/blob/48b8df43f3196e64ff4f1ae9340ee117f49b8e52/celonis/udfrepro/debug.sh#L10 ) 
it's about 25-30 errors in 100 loops for the image based on 2.5 branch `ghcr.io/dengliu/starrocks-allin1:udffailure-branch2.5-facfd5a0`

(Note: we have already build the images on upstream main and upstream branch2.5
and the images are available here. so you don't necessarily need to rebuild the images. We provide the above build steps just in case you want to use it to build images on other code base)
https://github.com/users/dengliu/packages/container/package/starrocks-allin1

### Expected behavior (Required)
Expect 100% suceess

### Real behavior (Required)
it's about 25-30 errors in 100 loops for the image based on 2.5 branch `ghcr.io/dengliu/starrocks-allin1:udffailure-branch2.5-facfd5a0`

### StarRocks version (Required)
`ghcr.io/dengliu/starrocks-allin1:udffailure-branch2.5-facfd5a0` : failed ~25% of the time
`ghcr.io/dengliu/starrocks-allin1:udffailure-main-76c7249b` : 100% success

**Comment by stdpain** [comment]
What is the specific error message?
