### ISSUE TITLE
[Feature] Inter-cluster low-level tablets replication

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks#17820]
## Feature request

**Is your feature request related to a problem? Please describe.**
We need a feature to implement a High-availability Starrocks cloud architecture.
There will be two starrocks clusters: Main & Standby. The Main cluster will be serving all the normal read/write/ingestion workload. The Standby cluster will have the same topology(i.e. same number of BE node) and receive the  tablets  updates that are caused by the Write/Ingestion happening on the Main cluster.  
As the sync of tablets are happening as low-level I/O operations, the actual computing resources on the Standby cluster should be very minimal.
In this way we could have Standby cluster mirroring the Main cluster in real-time with minimal computing resources. And in case of failure in Main cluster, we could seamless failover to the Standby cluster.

**Describe the solution you'd like**

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by imay** [comment]
I think you can consider our next-generation architecture, which will decouple the storage and computing. In this architecture, all data will be stored in S3. You even don't need a stand-by computing cluster at all.
When the Main cluster crash, you can create the stand-by cluster and start to serve.

**Comment by dengliu** [comment]
Will the performance, e.g. query latency be significant higher when storing data on S3 v.s. on a SRs managed EBS disk?

**Comment by imay** [comment]
When the data is stored in S3, it will be slower to read data from S3 than from EBS/local disk. But starrocks has local cache, if all the data is cached in local disk, the speed will be the same
