### ISSUE TITLE
MySql Client max_allowed_packet is ignored

### ISSUE THREAD

**Issue by grezap** [StarRocks/starrocks#17869]
After trying to batch insert I am getting the error "Packets larger than max_allowed_packet are not allowed.".
I used the following sql statement to change the variable value: 
SET GLOBAL max_allowed_packet = 1*1024*1024*1024;
After executing it the value has been changed successfully to 1073741824. 
When I try and execute again the insert statement , I get the same error as above again. 
So setting the max_allowed_packet does not have any effect.

Also I have got the same error result trying to get data using Power BI from Starrocks , using the official mysql driver. 
The error is again: 

DataSource.Error: MySQL: Packets larger than max_allowed_packet are not allowed.
Details:
    DataSourceKind=MySql
    DataSourcePath=dw-rocks1.hq.hellasdirect.gr:9030;dbtest
    Message=Packets larger than max_allowed_packet are not allowed.
    ErrorCode=-2147467259

**Comment by grezap** [comment]
any news on this ?

**Comment by Marlonc** [comment]
I get this error when I try to load large Starrocks tables from power bi.
The error does not appear for small tables

<img width="653" alt="image" src="https://github.com/StarRocks/starrocks/assets/7309224/a31c73c6-1782-4a2c-b56a-96e85b69303d">
