### ISSUE TITLE
support root password change on docker-compose bootstrap

### ISSUE THREAD

**Issue by geoHeil** [StarRocks/starrocks#17889]
## Enhancement

The docker-compose example of https://github.com/StarRocks/starrocks/tree/main/docker/docker-compose only allows to change the password from MySQL cli like:

```
set password = PASSWORD('') to change the password

```

https://starrocks.slack.com/archives/C02FACZSNJV/p1676487496413099?thread_ts=1676474544.408279&cid=C02FACZSNJV

It would be nice if the password could be specified from an environment variable during the bootstrap of the docker-compose  file

**Comment by alberttwong** [comment]
Most people use a k8s secrets.  Wouldn't that be better?
