### ISSUE TITLE
colocate info is lost after restore table

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#1794]
### Steps to reproduce the behavior (Required)
```
1. CREATE TABLE t_1 (
                            `id` int(18),
                            `value` varchar(20)
                        )
                        ENGINE=OLAP
                        DUPLICATE KEY(`id`)
                        COMMENT "OLAP"
                        DISTRIBUTED BY HASH(`id`) BUCKETS 3
                        PROPERTIES (
                            "replication_num" = "1",
                            "storage_format" = "v2",
                            "colocate_with" = "group1"
                        );
2.SHOW PROC '/colocation_group';
3. backup the table t_1
4. drop table t_1 force;
5. restore the table t_1
6. SHOW PROC '/colocation_group';
```
### Expected behavior (Required)
t_1 in group1
### Real behavior (Required)
t_1 is not in group1
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN ee338f4   |
+-------------------+
```

**Comment by gengjun-git** [comment]
After discuss with @chaoyli , our conclusions is that we do not need to backup/restore the colocate info, because the relation ship of tables may not work in another system, and not all tables in a group will be backed up. Backup/Restore only processes the basic data. What is your opinion? @jaogoy @Dshadowzh

**Comment by jaogoy** [comment]
I suggest storing those colocate info.
If some tables of a colocated group are not restored, what will the behavior be?  Maybe the system can ignore those non-existing tables of a colocated group.

**Comment by gengjun-git** [comment]
Features that are not urgent can be put on the latter versions, i think.
