### ISSUE TITLE
tablet writer add chunk failed, message=Update memory limit exceed

### ISSUE THREAD

**Issue by gentlescholar** [StarRocks/starrocks#1805]
### Steps to reproduce the behavior (Required)
flink-connector-starrocks，内部实现是通过缓存并批量由stream load导入

### Real behavior (Required)
W1202 18:46:39.626010 20377 internal_service.cpp:205] tablet writer add chunk failed, message=Update memory limit exceed tablet:1103977 16121088578 > 16111823093, id=3b4426ee-a47d-170e-247e-e15216dc7d88, index_id=1103976, sender_id=0
E1202 18:46:39.652133 20285 update_compaction_state.cpp:61]  memory limit exceeded when loading compaction state rssid tablet_id:1130998 rowset #rows:960715 size:18234785 seg:0 memory:3842860 stats:index:15.01 GB rowset:0 compaction:3.66 MB delvec:60.09 KB total:15.02 GB/15.01 GB
W1202 18:46:39.662302 20378 delta_writer.cpp:83] Update memory limit exceed tablet:1145650 16124931438 > 16111823093
W1202 18:46:39.662343 20378 internal_service.cpp:205] tablet writer add chunk failed, message=Update memory limit exceed tablet:1145650 16124931438 > 16111823093, id=de4c143c-966d-250e-b59d-ea2ca33827be, index_id=1145640, sender_id=0
W1202 18:46:39.663883 20379 delta_writer.cpp:83] Update memory limit exceed tablet:1137303 16124931438 > 16111823093
W1202 18:46:39.663920 20379 internal_service.cpp:205] tablet writer add chunk failed, message=Update memory limit exceed tablet:1137303 16124931438 > 16111823093, id=f6476f39-8793-da82-e549-6281908ddbbf, index_id=1137302, sender_id=0
W1202 18:46:39.663992 20357 tablet_sink.cpp:199] NodeChannel[1137302-10003] add batch req success but status isn't ok, load_id=f6476f39-8793-da82-e549-6281908ddbbf, txn_id=6038127, node=172.17.22.28:8060, errmsg=Update memory limit exceed tablet:1137303 16124931438 > 16111823093
E1202 18:46:39.690301 20285 update_compaction_state.cpp:112]  memory limit exceeded when loading compaction state pk tablet_id:1130998 rowset #rows:960715 size:18234785 seg:0 memory:24462940 stats:index:15.01 GB rowset:0 compaction:23.33 MB delvec:60.09 KB total:15.04 GB/15.01 GB
W1202 18:46:39.816627 20244 tablet_sink.cpp:991] close channel failed. channel_name=NodeChannel[1137302-10003], load_info=load_id=f6476f39-8793-da82-e549-6281908ddbbf, txn_id=6038127, errror_msg=already stopped, skip waiting for close. cancelled/!eos: : 1/0
W1202 18:46:39.817015 20244 plan_fragment_executor.cpp:228] fail to open fragment, instance_id=f6476f39-8793-da82-e549-6281908ddbc0, status=Internal error: close index channel failed, load_id=f6476f39-8793-da82-e549-6281908ddbbf
W1202 18:46:39.817085 20244 fragment_mgr.cpp:184] Fail to open fragment f6476f39-8793-da82-e549-6281908ddbc0: Internal error: close index channel failed, load_id=f6476f39-8793-da82-e549-6281908ddbbf
W1202 18:46:39.817278 20244 stream_load_executor.cpp:86] fragment execute failed, query_id=f6476f398793da82-e5496281908ddbbf, err_msg=close index channel failed, load_id=f6476f39-8793-da82-e549-6281908ddbbf, id=f6476f398793da82-e5496281908ddbbf, job_id=-1, txn_id=6038127, label=ef413019-802a-402b-b841-d6158a6c1579
W1202 18:46:39.817322 20429 stream_load.cpp:130] Fail to handle streaming load, id=f6476f398793da82-e5496281908ddbbf errmsg=close index channel failed, load_id=f6476f39-8793-da82-e549-6281908ddbbf

### StarRocks version (Required)
starrocks1.19.3

**Comment by decster** [comment]
What's your table schema and size? Primary key table is not suitable for scenarios with a very large quantity of active rows.
Please refer to doc: 
https://docs.starrocks.com/zh-cn/1.19/table_design/Data_model#%E9%80%82%E7%94%A8%E5%9C%BA%E6%99%AF

**Comment by gentlescholar** [comment]
请问一下，主键模型表未分区，upsert一条数据，会把这张表的所有索引都加载到内存吗？@decster

**Comment by gentlescholar** [comment]
> What's your table schema and size? Primary key table is not suitable for scenarios with a very large quantity of active rows. Please refer to doc: https://docs.starrocks.com/zh-cn/1.19/table_design/Data_model#%E9%80%82%E7%94%A8%E5%9C%BA%E6%99%AF

请问一下，主键模型表未分区，upsert一条数据，会把这张表的所有索引都加载到内存吗？@decster

**Comment by decster** [comment]
> 请问一下，主键模型表未分区，upsert一条数据，会把这张表的所有索引都加载到内存吗？@decster

会的

**Comment by gentlescholar** [comment]
> 好的，如果分区了，只会加载一个分区的索引到内存是吗？

**Comment by gentlescholar** [comment]
> 好的，如果分区了，只会加载一个分区的索引到内存是吗？

**Comment by gentlescholar** [comment]
> > 请问一下，主键模型表未分区，upsert一条数据，会把这张表的所有索引都加载到内存吗？@decster
> 
> 会的

好的，如果分区了，只会加载一个分区的索引到内存是吗？

**Comment by decster** [comment]
不再有导入的分区就不会加载索引
