### ISSUE TITLE
Test Starrocks release in the containerized environment.

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks#18072]
## Enhancement
 @imay @chaoyli @kevincai 
At present, the Starrocks team is running a regression test on a virtual machine. However, the runtime dependencies have been manually installed on the VM, which is a non-deterministic process. This approach can result in regressions not being detected during the regression test. For example (PR https://github.com/StarRocks/starrocks/pull/18070)  

It would be great to test it in a Docker environment, where the runtime libraries and dependencies are built from the Dockerfile, ensuring a deterministic environment for testing. Enjoy watching this video!" [In The Dark Days Before Docker](https://youtube.com/watch?v=dUEkUxgvwls&feature=shares)
 
cc @jiacheng-celonis @zuyu

**Comment by chaoyli** [comment]
It's a good suggestion.
