### ISSUE TITLE
column mask and row filter

### ISSUE THREAD

**Issue by yiluoya** [StarRocks/starrocks#1810]
## Feature request

column masking 
example：

customer table as follow ，the telephone num is sensitive ，don't want be select by user A。 but user B can view all data。
![image](https://user-images.githubusercontent.com/90463865/147716385-d90a14d4-7e93-4af0-be59-0856cb7d94dd.png)

solution ：
   add function at table customer column telephone  for user  A。
then user A  do ： select * from  customer  :
![image](https://user-images.githubusercontent.com/90463865/147716661-8b286524-608f-423c-8e51-d7d4564441ac.png)

at user B's view：   select * from  customer  :
![image](https://user-images.githubusercontent.com/90463865/147716824-37a703c9-078d-43c3-a6c2-596e76189580.png)

 
row filter 

example ：table order 
![image](https://user-images.githubusercontent.com/90463865/147716731-96c0926c-894e-4bfc-8579-ee8eaeede786.png)

hope user A only can view data ‘省份’ is ‘湖南’。 

solution ：  
   add express at table order  for user  A
then when user A  do ： select * from  order    
![image](https://user-images.githubusercontent.com/90463865/147717699-23708fd7-75e9-4058-a3f5-7fe8121fd3f8.png)

------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------

next is i implement example：

```
CREATE  database ods;
use ods;

CREATE TABLE test_chen
(
a varchar(10)
,b int 
)
ENGINE=olap
DISTRIBUTED BY HASH(a) BUCKETS 32
PROPERTIES(
"storage_type"="column",
"replication_num"="1"
);

insert into test_chen values("1",1);
insert into test_chen values("2",2);
insert into test_chen values("3",-1);`

row filter ：
`>> GRANT FILTER_POLICY ON  ods.test_chen TO 'root'  WITH a > 1;
>> SELECT * FROM ods.test_chen tc ;
```

![image](https://user-images.githubusercontent.com/90463865/147717819-199fc521-05a9-447c-8de5-2e11d6db5378.png)

column mask：
`GRANT MASK_POLICY ON  ods.test_chen TO 'root' COLUMN b  WITH abs(b);`

![image](https://user-images.githubusercontent.com/90463865/147717838-8766e728-6869-463d-966f-ee96f21a72a2.png)

show grants
`SHOW  GRANTS for 'root'`
![image](https://user-images.githubusercontent.com/90463865/147717847-3a71bb17-f78b-4a4a-a229-c003b7362500.png)

policy revoke

```
REVOKE FILTER_POLICY  ON  ods.test_chen FROM 'root'  
REVOKE MASK_POLICY ON  ods.test_chen FROM 'root' COLUMN b
```

![image](https://user-images.githubusercontent.com/90463865/147717903-6e4b5303-0056-4e87-b690-bd213e0dc061.png)

propose:
   **is it a good way use  mask_priv/filter_priv to grant ?**

for huawei gsDB
 >>  https://support.huaweicloud.com/devg2-dws/dws_0402_0042.html
        SELECT DBMS_REDACT.add_policy

for hive /presto user range 
![image](https://user-images.githubusercontent.com/90463865/147718769-b37edd76-92f3-4ece-93e5-d7f9095039d3.png)

**Comment by wuqiao** [comment]
> https://join.slack.com/t/starrocks/shared_invite/zt-z5zxqr0k-U5lrTVlgypRIV8RbnCIAzg

**Comment by wuqiao** [comment]
> ## Feature request
> 我们正打算使用starrocks，但是我们场景中会用到行过滤和字段加密， 自己也在研究这一块的东西。 如果完全自己做，可能不方便升级，所以希望社区能给个规范和接口，后面代码完成后想将代码提交给社区。
> 
> 主要涉及的点 1、语法和词法类cup， 基于grant 做 需要修改 定义规则， 另起一套也行， 也可以基于ranger。 2、分析器， 需要对 queryStmt 等 进行修改。
> 
> 希望社区开发，或者制定一个规则。
> 
> 谢谢

you can join StarRocks Community Slack Chanel ，Let's discuss it in detail：https://join.slack.com/t/starrocks/shared_invite/zt-z5zxqr0k-U5lrTVlgypRIV8RbnCIAzg

**Comment by yiluoya** [comment]
> > ## Feature request
> > 我们正打算使用starrocks，但是我们场景中会用到行过滤和字段加密， 自己也在研究这一块的东西。 如果完全自己做，可能不方便升级，所以希望社区能给个规范和接口，后面代码完成后想将代码提交给社区。
> > 主要涉及的点 1、语法和词法类cup， 基于grant 做 需要修改 定义规则， 另起一套也行， 也可以基于ranger。 2、分析器， 需要对 queryStmt 等 进行修改。
> > 希望社区开发，或者制定一个规则。
> > 谢谢
> 
> you can join StarRocks Community Slack Chanel ，Let's discuss it in detail：https://join.slack.com/t/starrocks/shared_invite/zt-z5zxqr0k-U5lrTVlgypRIV8RbnCIAzg

thank you

**Comment by yiluoya** [comment]
我已经基本完成了这个特性，问一下怎么发起一次讨论
