### ISSUE TITLE
Release plan 3.0

### ISSUE THREAD

**Issue by Dshadowzh** [StarRocks/starrocks#18125]
3.0.0 release plan 

### Architecture
* **Decouple storage and computing**. In this mode, data will be persisted to remote object storage/HDFS, and local disk will be used as cache, which can be more flexible for node addition and deletion, and support table-level cache life cycle management. The performance can be aligned with the shared-nothing architecture in case of local cache hits. 

### Storage engine and data ingestion
* Primary Key table fully supports `update` syntax, including the use of CTE and references to multiple tables. 
* The Primary key table supports `auto_increment` columns to provide globally unique IDs. 
* Dynamic on-demand partition creation is provided to improve the ease of use when importing historical data, as well as the ability to support the use of expressions to define partition columns.
* [Preview] Routine load supports importing data in Avro/Protobuf format. 

### Data Lake analytics
* Support Presto/Trino compatible dialect, can automatically rewrite Presto/Trino's SQL to StarRocks's SQL.
*  [Preview] Support for directly writing Parquet files into S3.
* Support Global UDF.

### Permissions and Security：
* Provides a new version of the full RBAC functionality, support for role inheritance and default roles.
* Provides more permission management objects and more fine-grained permissions.

### Query engine
* [Preview] Support operator **spilling** for large queries, which can use disk space to ensure stable execution of queries when there is insufficient memory.
* Support more `Query cache` scenarios, including bucket-shuffle/broadcast and other join scenarios.
* **Dynamic adaptive parallelism**, StarRocks can adjust the `pipeline_dop` according to the query concurrency adaptively.
* Array/Map/Struct supports Decimal V3.
* new functions: array_generate, map lambda function, array_agg support order by Function optimization

### Storage and import
* Provide richer CSV parameters in data ingestion, including SKIP_HEADER, TRIM_SPACE, ENCLOSE, ESCAPE. 
* Optimize the memory usage when importing Primary Key model tables. 

### Materialized View
* Optimize the rewriting capability of materialized views. including: view delta join, outer join, cross join and optimize the SQL rewrite of union with partition
* Improve the ability to materialize view construction: support CTE, select *, Union.
* Optimize the information of `show materialized view`.

### Query engine
* All operators support in pipeline engine. Non-pipeline code will be removed in the next several versions.
* Improve big query positioning, `show processing list` support to view cpu memory information, add big query log.
* Optimize outer join reorder 
* Optimize the error message of SQL parsing stage, make the error positioning of big query more clearly.

### Data Lake Analysis
* external table support `show create table`

### Other: 
* DateTime support to milliseconds.

**Comment by cmdares** [comment]
When is it expected to be released?

**Comment by Dshadowzh** [comment]
[Release notes ](https://github.com/StarRocks/starrocks/releases/tag/3.0.0-rc01)
