### ISSUE TITLE
JDBC Connector (Kyuubi Hive JDBC->Spark SQL) does not support time travel queries

### ISSUE THREAD

**Issue by chrisfw** [StarRocks/starrocks#18135]
**Using version 2.5.0**
I created a JDBC Resource that utilizes kyuubi's JDBC Hive Compatible driver using a Spark engine and Iceberg storage.  Running AS OF queries using DBeaver to retrieve data works fine, but the same query in Starrocks generates an error.  It would be great if setting a property, e.g. on the creation of the external resource and/or on the creation of the jdbc external table would push the entire query down to the driver.
```

create external resource kyuubijdbc
properties (
    "type"="jdbc",
    "jdbc_uri"="jdbc:kyuubi://10.18.102.29:10009",
    "driver_url"="https://repo1.maven.org/maven2/org/apache/kyuubi/kyuubi-hive-jdbc-shaded/1.6.1-incubating/kyuubi-hive-jdbc-shaded-1.6.1-incubating.jar",
    "driver_class"="org.apache.kyuubi.jdbc.KyuubiHiveDriver",
    "user"="scott",
    "password"="tiger"
);

show resources;
--drop resource kyuubijdbc;

create database sparkjdbc;
use sparkjdbc;

--drop table mysampleext;
create external table mysampleext (
    `id` bigint NULL, 
    `data` varchar (200) NULL 
) ENGINE=jdbc 
properties (
    "resource"="kyuubijdbc",
    "table"="my_catalog.iceberg.mysample"
);

select * from mysampleext;

SELECT * FROM mysampleext VERSION AS OF 1918948690536337515;

```

![dbeaver-kyuubi-spark](https://user-images.githubusercontent.com/6135741/220199432-552d167e-2ef3-4c80-bf0b-1d8da3b45d95.png)

**Comment by imay** [comment]
https://github.com/StarRocks/starrocks/pull/13707
As you can see, starrocks pass the temporal clause to MySQL external table in this PR. 
This is the only kind of table that starrocks will pass the temporal clause to.
If starrocks can pass the temporal clause to JDBC, does it work for you?

**Comment by chrisfw** [comment]
Hi @imay , 

Yes, that is exactly what I am looking for, thank you.  Is this something that can be implemented without too much difficulty?

Regards,
Chris
