### ISSUE TITLE
[StarOS] result mismatch from sqlancer querys

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#18187]
### Steps to reproduce the behavior (Required)
```
test_sr_9248_2_bug
test_sr_9505_bug
test_sr_10456_bug
test_sr_8248_bug
test_sr_9469_bug
test_sr_9472_bug
test_sr_7039_bug
test_sr_9257_3_bug
test_sr_8242_bug
test_sr_8243_bug
test_DSDB_1874_bug
test_sr_9256_bug
test_sr_9716_bug
test_DSDB_1950_bug
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
MySQL [tn_test]> select current_version();
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN 800b5477f |
+-------------------+
1 row in set (0.06 sec)
```

**Comment by TszKitLo40** [comment]
`enable_insert_strict` should be set with false. And in daily build, it is set in the Jenkins script.

**Comment by TszKitLo40** [comment]
After `enable_insert_strict` is set with false, some of the tests will also failed, because lake table does not support materialized view yet.
