### ISSUE TITLE
The sr load command without broker does not support adding hadoop related parameters.

### ISSUE THREAD

**Issue by ysyl23588** [StarRocks/starrocks#18188]
### Description
The load command **without broker** does not support adding **hadoop** **ha** related parameters.
But  the broker load command executes everything fine.

error msg: type:ETL_RUN_FAIL; msg:invalid load_properties, namenode HA should be set in hdfs/core-site.xmlfor load without broker. For broker load with broker, you can set namenode HA in the load_properties

After deleting the ha related parameters, the load command is executed successfully.

`LOAD LABEL ygf.ygf_bill_xxx_109815
(
	DATA INFILE("hdfs://xxx/xx/xx/ygf/xxx/pt={20190101,20190102,20190103,20190104,20190105}/*")
	INTO TABLE xxx 
	PARTITION (p20190105,p20190102,p20190101,p20190104,p20190103) 
	FORMAT AS "parquet"
	(discount_rate ...)
	COLUMNS FROM PATH AS (pt)
	SET(pt = STR_TO_DATE(pt, '%Y%m%d'))
)
WITH BROKER 
(
	"username"="hadoop",
	**"dfs.nameservices"="TestCluster01",
	"dfs.ha.namenodes.TestCluster01"="nn1,nn2",
	"dfs.namenode.rpc-address.TestCluster01.nn1"="xxx:8020",
	"dfs.namenode.rpc-address.TestCluster01.nn2"="xxx:8020",
	"dfs.client.failover.proxy.provider"="org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProx"**
)
PROPERTIES ("timeout" = "36000");`

### StarRocks version (Required)
StarRocks version  2.5.1 f1d669f

**Comment by jaogoy** [comment]
@ysyl23588 You're right, Broker Load without broker has some requirements.
check here for more info: [HDFS in HA configuration](https://docs.starrocks.io/en-us/latest/sql-reference/sql-statements/data-manipulation/BROKER%20LOAD#hdfs)
