### ISSUE TITLE
Getting Started directions don't work (Docker/Bare Ubuntu)

### ISSUE THREAD

**Issue by haydenflinner** [StarRocks/starrocks#18235]
### Steps to reproduce the behavior (Required)
Follow the instructions here on a clean/fresh Ubuntu 20 machine with Docker compose installed
https://docs.starrocks.io/en-us/latest/quick_start/deploy_in_docker

### Expected behavior (Required)
To have a working cluster

### Real behavior (Required)
BE fails to connect to FE to inform it off creation. If I manually add BE to FE through mysql client, always connection refused. I even tried adding port 9050 to the be section of the compose file and restarting from scratch, didn't help.

As a last resort I tried the base Linux install. With that, FE starts fine, but the BE just kind of hangs around without doing anything, never fully started. strace -f shows it is blocked on some futex, but it never logs to the .out file or creates a .log file, nor starts up enough to provide a port for FE to connect to or log any error to stderr.

### StarRocks version (Required)
StarRocks 2.5
Docker-compose 1.29.2

**Comment by imay** [comment]
If you are on the X86 chip, you can try this image https://github.com/StarRocks/starrocks/pkgs/container/starrocks%2Fallin1-ubuntu and refer to https://github.com/StarRocks/starrocks/tree/main/docker/starrocks-stack-compose 
We are working on the docker images now, so it will change a lot recently.

**Comment by alberttwong** [comment]
I tried it and it works for me.
