### ISSUE TITLE
starrocks not support stored procedures

### ISSUE THREAD

**Issue by Panzervid** [StarRocks/starrocks#18242]
需求：oracle迁移到starrocks  ，但oracle有很多存储过程，目前starrocks不能实现

**Comment by ltylty** [comment]
starrocks可以写udf

**Comment by Panzervid** [comment]
很多的存储过程是写入到一个另一个新表，跑批  。  udf目前不能支持这个需求

**Comment by maulanaady** [comment]
any update for this feature?
