### ISSUE TITLE
Support building azure dependency jar into the output of BE/FE build

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks#18341]
## Enhancement
it would be great to install these jars as part of  FE/BE build process, we we could easily package them into the runtime container image with the [dockerfiles](https://github.com/StarRocks/starrocks/tree/main/docker/dockerfiles)

Currently it requires manually Put JAR files under these dirs:
![image](https://user-images.githubusercontent.com/5108773/220783929-2c9898c9-fb09-4e84-b453-bf0cd0e41a93.png)

**Comment by dengliu** [comment]
cc @jiacheng-celonis @imay @chaoyli

**Comment by Smith-Cruise** [comment]
We already supporting azure in https://github.com/StarRocks/starrocks/pull/18981

**Comment by dengliu** [comment]
Hi @Smith-Cruise , great news.

is there an instruction of how to use broker load for Azure blobstorage?
Can you add that to the Starrocks Doc

https://docs.starrocks.io/en-us/3.0/sql-reference/sql-statements/data-manipulation/BROKER%20LOAD

https://docs.starrocks.io/zh-cn/3.0/sql-reference/sql-statements/data-manipulation/BROKER%20LOAD#with-broker
