### ISSUE TITLE
Support setting the azure ACCOUNT/KEY via broker load sql 

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks#18342]
## Enhancement
Prefer setting the azure ACCOUNT/KEY via broker load sql like the S3 broker load:

Load from S3 using aws access key/secret
```
WITH BROKER
(
   "aws.s3.access_key" = "AXXXXXXXXXXXXXXXK",
   "aws.s3.secret_key" = "KXXXXXXXXXXXXXXXXXXXXXXXU",
   "aws.s3.region"="us-west-1"
)
```
Load from minio using url
```
WITH BROKER
(
     "aws.s3.access_key" = "root",
     "aws.s3.secret_key" = "rootroot",
     "aws.s3.endpoint" = "http://minio.local.com:9000/",
     "aws.s3.enable_path_style_access" = "true"
)
```

Currently it requires putting the ACCOUNT/KEY in a core-site.xml file
![image](https://user-images.githubusercontent.com/5108773/220784364-06daea1e-9970-4670-95a8-d91b6fb2cd78.png)

**Comment by dengliu** [comment]
cc @jiacheng-celonis @chaoyli @imay

**Comment by DorianZheng** [comment]
@dengliu We have supported this in v3.0 https://github.com/StarRocks/starrocks/pull/18981. cc @Smith-Cruise

**Comment by dengliu** [comment]
@DorianZheng

**Comment by Smith-Cruise** [comment]
> 

I update some grammar in https://github.com/StarRocks/starrocks/pull/18981, you can take a look.

**Comment by dengliu** [comment]
Thanks. Is there a complete example of using Azure blobstore for broker load?

**Comment by Smith-Cruise** [comment]
> 

```sql
LOAD LABEL test.label3
(
    DATA INFILE("wasb[s]://brokerload@hello.dfs.core.windows.net/file_table.orc")
    INTO TABLE load_table
    FORMAT AS "orc"
    (player_id)
)
WITH BROKER
(
   "azure.blob.shared_key"="DrUWAStD6gbqA=="
)
PROPERTIES
(
    "timeout" = "600"
);
```
