### ISSUE TITLE
[StarOS] result error after broker load with op into primary table

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#18386]
### Steps to reproduce the behavior (Required)
````sql
CREATE TABLE primary_20cols_3rep
(k0 TINYINT NOT NULL, k1 DATE NOT NULL, k2 INT NOT NULL, k3 DATETIME NOT NULL, k4 BIGINT NOT NULL, v0 LARGEINT NULL,
v1 BOOLEAN NULL, v2 SMALLINT NULL, v3 VARCHAR(21) NULL, v4 STRING NULL, v5 DECIMAL(18,4) NULL,
v6 STRING NULL, v7 CHAR(126) NULL, v8 INT NULL, v9 DECIMAL(4,2) NULL, v10 DATETIME NULL, v11 DATETIME NULL, v12 STRING NULL,
v13 CHAR(40) NULL, v14 VARCHAR(165) NULL)
PRIMARY KEY(k0,k1,k2,k3,k4)
DISTRIBUTED BY HASH(k0,k1,k2,k3,k4) BUCKETS 5 PROPERTIES ("replication_num" = "3");

LOAD LABEL tn_test.broker_load_bb85c9ca_b355_11ed_8f95_00163e0e550b (DATA INFILE( "hdfs://172.26.194.238:9000/starrocks_test_data/system_data/hdfs_data/primary_test_parquet/primary_20cols_3rep_parquet_0/000000_0") INTO TABLE `primary_20cols_3rep` FORMAT AS "parquet" (k0,k1,k2,k3,k4,k5,k6,k7,k8,k9,v0,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10) SET (k0=k0,k1=k1,k2=k2,k3=k3,k4=k4,__op=v10) )  WITH BROKER hdfs_broker ("username"="sr","password"="sr@test") PROPERTIES("timeout"="259200");
select count(*) from primary_20cols_3rep;
select count(*) from primary_20cols_3rep where k0=-7 and k1='1999-07-14' and k2=1007088263 and k3='1975-11-25 08:23:14' and k4=6698990814679959142;

LOAD LABEL tn_test.broker_load_be831f92_b355_11ed_8f95_00163e0e550b (DATA INFILE( "hdfs://172.26.194.238:9000/starrocks_test_data/system_data/hdfs_data/primary_test_parquet/primary_20cols_3rep_parquet_0/000001_0") INTO TABLE `primary_20cols_3rep` FORMAT AS "parquet" (k0,k1,k2,k3,k4,k5,k6,k7,k8,k9,v0,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10) SET (k0=k0,k1=k1,k2=k2,k3=k3,k4=k4,__op=v10) )  WITH BROKER hdfs_broker ("username"="sr","password"="sr@test") PROPERTIES("timeout"="259200");

select count(*) from primary_20cols_3rep;
select count(*) from primary_20cols_3rep where k0=-7 and k1='1999-07-14' and k2=1007088263 and k3='1975-11-25 08:23:14' and k4=6698990814679959142;
````

### Expected behavior (Required)
olap table in main:
```
mysql> select count(*) from primary_20cols_3rep;
+----------+
| count(*) |
+----------+
|   345578 |
+----------+
1 row in set (0.03 sec)

mysql> select count(*) from primary_20cols_3rep where k0=-7 and k1='1999-07-14' and k2=1007088263 and k3='1975-11-25 08:23:14';
+----------+
| count(*) |
+----------+
|        1 |
+----------+
1 row in set (0.02 sec)
```

### Real behavior (Required)
lake table in StarOS:
```
mysql> select count(*) from primary_20cols_3rep;
+----------+
| count(*) |
+----------+
|   345578 |
+----------+
1 row in set (0.02 sec)

mysql> select count(*) from primary_20cols_3rep where k0=-7 and k1='1999-07-14' and k2=1007088263 and k3='1975-11-25 08:23:14' and k4=6698990814679959142;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.02 sec)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN 800b5477f |
+-------------------+
1 row in set (0.00 sec)
```

**Comment by tiannan-sr** [comment]
result from lake table with primary model mismatch with olap table after routine load:
````sql
        CREATE TABLE `primary_table_test` (
            `k0` date,
            `k1` date,
            `k2` datetime,
            `k3` string,
            `k4` string,
            `k5` boolean,
            `v1` tinyint NOT NULL,
            `v2` smallint NOT NULL,
            `v3` int NOT NULL,
            `v4` bigint NOT NULL,
            `v5` largeint NOT NULL,
            `v6` float NOT NULL,
            `v7` double NOT NULL,
            `v8` decimal(27,9) NOT NULL
        )
        PRIMARY KEY(`k0`)
        COMMENT "OLAP"
        DISTRIBUTED BY HASH(`k0`) BUCKETS 3
        ORDER BY(`k0`, `k1`)
        PROPERTIES (
            "replication_num" = "3",
            "storage_format" = "v2"
        );
CREATE ROUTINE LOAD primary_routine_load_8ce42cfa_b35b_11ed_8ddb_00163e0e550b on primary_table_test COLUMNS (k0,k1,k2,k3,k4,k5,v1,temp_gender,v2,v3,v4,v5,v6,v7,v8),COLUMNS TERMINATED BY '\t' PROPERTIES ("desired_concurrent_number"="1","max_error_number"="1000","max_batch_interval"="5","merge_condition"="v1") FROM KAFKA ("kafka_broker_list"="172.26.92.141:9092","kafka_partitions"="0,1,2,3,4","kafka_offsets"="OFFSET_BEGINNING,OFFSET_BEGINNING,OFFSET_BEGINNING,OFFSET_BEGINNING,OFFSET_BEGINNING","kafka_topic"="basic_types_data_2_more_columns");
````

result from lake table:
```
mysql> select * from primary_table_test where k0='2192-12-26';
+------------+------------+---------------------+-----------+--------+------+------+------+------------+----------------------+----------------------------------------+----------------+-------------------------+-----------------------+
| k0         | k1         | k2                  | k3        | k4     | k5   | v1   | v2   | v3         | v4                   | v5                                     | v6             | v7                      | v8                    |
+------------+------------+---------------------+-----------+--------+------+------+------+------------+----------------------+----------------------------------------+----------------+-------------------------+-----------------------+
| 2192-12-26 | 2323-11-21 | 2282-07-26 00:38:54 | char93058 | BRAZIL |    1 | -125 | 7734 | 2127609979 | -4299950399154092991 | 97435184000729906917358156909678681450 | -5.9099776e+08 | -1.2023037932662948e+18 | -1866686705.353901100 |
+------------+------------+---------------------+-----------+--------+------+------+------+------------+----------------------+----------------------------------------+----------------+-------------------------+-----------------------+
1 row in set (0.01 sec)

mysql> select count(*) from primary_table_test;
+----------+
| count(*) |
+----------+
|      998 |
+----------+
1 row in set (0.03 sec)
```

result from olap table:
```
mysql> select * from primary_table_test where k0='2192-12-26';
+------------+------------+---------------------+-----------+-----------+------+------+-------+-------------+----------------------+-----------------------------------------+----------+------------------------+----------------------+
| k0         | k1         | k2                  | k3        | k4        | k5   | v1   | v2    | v3          | v4                   | v5                                      | v6       | v7                     | v8                   |
+------------+------------+---------------------+-----------+-----------+------+------+-------+-------------+----------------------+-----------------------------------------+----------+------------------------+----------------------+
| 2192-12-26 | 2052-06-07 | 2325-03-19 22:11:01 | char99512 | INDONESIA |    1 |  122 | -1659 | -1753219176 | -4608653622063829751 | -11092550311707023354931075516338681041 | 57322290 | -3.185862961341659e+18 | -200801560.230624680 |
+------------+------------+---------------------+-----------+-----------+------+------+-------+-------------+----------------------+-----------------------------------------+----------+------------------------+----------------------+
1 row in set (0.00 sec)

mysql> select count(*) from primary_table_test;
+----------+
| count(*) |
+----------+
|      998 |
+----------+
1 row in set (0.03 sec)
```

**Comment by luohaha** [comment]
> result from lake table with primary model mismatch with olap table after routine load:
> 
> ```sql
>         CREATE TABLE `primary_table_test` (
>             `k0` date,
>             `k1` date,
>             `k2` datetime,
>             `k3` string,
>             `k4` string,
>             `k5` boolean,
>             `v1` tinyint NOT NULL,
>             `v2` smallint NOT NULL,
>             `v3` int NOT NULL,
>             `v4` bigint NOT NULL,
>             `v5` largeint NOT NULL,
>             `v6` float NOT NULL,
>             `v7` double NOT NULL,
>             `v8` decimal(27,9) NOT NULL
>         )
>         PRIMARY KEY(`k0`)
>         COMMENT "OLAP"
>         DISTRIBUTED BY HASH(`k0`) BUCKETS 3
>         ORDER BY(`k0`, `k1`)
>         PROPERTIES (
>             "replication_num" = "3",
>             "storage_format" = "v2"
>         );
> CREATE ROUTINE LOAD primary_routine_load_8ce42cfa_b35b_11ed_8ddb_00163e0e550b on primary_table_test COLUMNS (k0,k1,k2,k3,k4,k5,v1,temp_gender,v2,v3,v4,v5,v6,v7,v8),COLUMNS TERMINATED BY '\t' PROPERTIES ("desired_concurrent_number"="1","max_error_number"="1000","max_batch_interval"="5","merge_condition"="v1") FROM KAFKA ("kafka_broker_list"="172.26.92.141:9092","kafka_partitions"="0,1,2,3,4","kafka_offsets"="OFFSET_BEGINNING,OFFSET_BEGINNING,OFFSET_BEGINNING,OFFSET_BEGINNING,OFFSET_BEGINNING","kafka_topic"="basic_types_data_2_more_columns");
> ```
> 
> result from lake table:
> 
> ```
> mysql> select * from primary_table_test where k0='2192-12-26';
> +------------+------------+---------------------+-----------+--------+------+------+------+------------+----------------------+----------------------------------------+----------------+-------------------------+-----------------------+
> | k0         | k1         | k2                  | k3        | k4     | k5   | v1   | v2   | v3         | v4                   | v5                                     | v6             | v7                      | v8                    |
> +------------+------------+---------------------+-----------+--------+------+------+------+------------+----------------------+----------------------------------------+----------------+-------------------------+-----------------------+
> | 2192-12-26 | 2323-11-21 | 2282-07-26 00:38:54 | char93058 | BRAZIL |    1 | -125 | 7734 | 2127609979 | -4299950399154092991 | 97435184000729906917358156909678681450 | -5.9099776e+08 | -1.2023037932662948e+18 | -1866686705.353901100 |
> +------------+------------+---------------------+-----------+--------+------+------+------+------------+----------------------+----------------------------------------+----------------+-------------------------+-----------------------+
> 1 row in set (0.01 sec)
> 
> mysql> select count(*) from primary_table_test;
> +----------+
> | count(*) |
> +----------+
> |      998 |
> +----------+
> 1 row in set (0.03 sec)
> ```
> 
> result from olap table:
> 
> ```
> mysql> select * from primary_table_test where k0='2192-12-26';
> +------------+------------+---------------------+-----------+-----------+------+------+-------+-------------+----------------------+-----------------------------------------+----------+------------------------+----------------------+
> | k0         | k1         | k2                  | k3        | k4        | k5   | v1   | v2    | v3          | v4                   | v5                                      | v6       | v7                     | v8                   |
> +------------+------------+---------------------+-----------+-----------+------+------+-------+-------------+----------------------+-----------------------------------------+----------+------------------------+----------------------+
> | 2192-12-26 | 2052-06-07 | 2325-03-19 22:11:01 | char99512 | INDONESIA |    1 |  122 | -1659 | -1753219176 | -4608653622063829751 | -11092550311707023354931075516338681041 | 57322290 | -3.185862961341659e+18 | -200801560.230624680 |
> +------------+------------+---------------------+-----------+-----------+------+------+-------+-------------+----------------------+-----------------------------------------+----------+------------------------+----------------------+
> 1 row in set (0.00 sec)
> 
> mysql> select count(*) from primary_table_test;
> +----------+
> | count(*) |
> +----------+
> |      998 |
> +----------+
> 1 row in set (0.03 sec)
> ```

Different bug, open in https://github.com/StarRocks/starrocks/issues/18572
