### ISSUE TITLE
麻烦实现bitmap_subset_limit函数和min_by函数

### ISSUE THREAD

**Issue by ltylty** [StarRocks/starrocks#18448]
麻烦实现 min_by函数。 为什么实现了max_by不实现min_by？  
参考 https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-functions/aggregate-functions/min_by

麻烦实现bitmap_subset_limit函数。  为什么实现了sub_bitmap不实现bitmap_subset_limit？  
参考 https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-functions/bitmap-functions/bitmap_subset_limit

函数不够丰富，用起来太难受了。

**Comment by ltylty** [comment]
please implement min_by function such as https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-functions/aggregate-functions/min_by

please implement bitmap_subset_limit function such as https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-functions/bitmap-functions/bitmap_subset_limit

**Comment by ucasfl** [comment]
`min_by` has been implemented in https://github.com/StarRocks/starrocks/pull/18517, I will implement `bitmap_subset_limit` later.
