### ISSUE TITLE
Added the statistics function of hot and cold data

### ISSUE THREAD

**Issue by sqxinquan** [StarRocks/starrocks#18466]
During migration, hot and cold data tables cannot be found, so it is required to add a table which can be counted as frequently used tables and infrequently used tables. It is better to count the number of write and query times.

**Comment by imay** [comment]
The migration you mentioned is the work that moves some data from one table to another.

**Comment by sqxinquan** [comment]
> 

Migrating from one set of Starrocks to another set of Starrocks environments

**Comment by sqxinquan** [comment]
Migrating from one set of Starrocks to another set of Starrocks environments
