### ISSUE TITLE
Support hive , presto udf and sql syntax 

### ISSUE THREAD

**Issue by hiliuxg** [StarRocks/starrocks#1847]
## Enhancement
At present, many BI  tools datasource use HIVE and PRESTO and users are familiar with hive and presto syntax and udf.  If starrocks can support hive and presto udf  and there's syntax , it would be perfect. This not only allows the BI tools that use hive and presto to seamlessly switch to starrocks, but also allows users to switch to starrocks without feeling.

**Comment by jaogoy** [comment]
We are currently designing UDF framework.
You can also list some UDFs that you used most in hive, presto. It will be a big job to support all hive and presto UDFs.
