### ISSUE TITLE
LAG/LEAD IGNORE NULLS have incorrect behavior

### ISSUE THREAD

**Issue by rcauble** [StarRocks/starrocks#18509]
**UPDATE**: ignore this first example; there's a better example in my commentt below.

### Steps to reproduce the behavior (Required)
```
CREATE DATABASE TEST1;

CREATE TABLE `TEST1`.`A` (`a` BIGINT, `b` BIGINT, `val` BIGINT)  DISTRIBUTED BY HASH (`a`) PROPERTIES("replication_num" = "1");
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(1,1,1);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(2,2,1);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(2,3,1);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(2,4,1);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(3,5,2);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(3,6,2);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(4,7,2);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(4,8,2);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(5,9,3);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(6,10,3);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(200,11,3);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(201,12,3);
INSERT INTO `TEST1`.`A`(`a`,`b`) VALUES(13,4);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(6,14,4);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(201,16,4);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(6,17,5);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(201,19,5);
INSERT INTO `TEST1`.`A`(`a`,`b`) VALUES(20,5);
INSERT INTO `TEST1`.`A`(`a`,`b`) VALUES(21,6);
INSERT INTO `TEST1`.`A`(`a`,`b`) VALUES(22,6);
INSERT INTO `TEST1`.`A`(`a`,`b`) VALUES(23,6);
INSERT INTO `TEST1`.`A`(`a`,`b`) VALUES(24,6);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(10,25,7);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(20,26,7);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(30,27,7);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(40,28,7);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(10,29,8);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(20,30,8);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(30,31,8);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(40,32,8);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(50,33,8);


  SELECT
    `A`,
    `VAL`,
    LAG(`VAL` IGNORE NULLS, 2) over (
      order by
        `A` DESC
    ) AS `LAG`
  FROM
    `TEST1`.`A` ORDER BY A DESC;
```
### Expected behavior (Required)
```
"33","50","NULL"
"32","40","NULL"
"31","30","50"
"30","20","40"
"29","10","30"
"28","40","20"
"27","30","10"
"26","20","40"
"25","10","30"
"24","NULL","20"
"23","NULL","20"
"22","NULL","20"
"21","NULL","20"
"20","NULL","20"
"19","201","20"
"17","6","10"
"16","201","201"
"14","6","6"
"13","NULL","201"
"12","201","201"
"11","200","6"
"10","6","201"
"9","5","200"
"8","4","6"
"7","4","5"
"6","3","4"
"5","3","4"
"4","2","3"
"3","2","3"
"2","2","2"
"1","1","2"
```

### Real behavior (Required)
```
A	VAL	LAG
33	50	NULL
32	40	NULL
31	30	50
30	20	40
29	10	30
28	40	20
27	30	10
26	20	40
25	10	30
24	NULL	20
23	NULL	10
22	NULL	10
21	NULL	10
20	NULL	10
19	201	10
17	6	10
16	201	201
14	6	6
13	NULL	201
12	201	6
11	200	6
10	6	201
9	5	200
8	4	6
7	4	5
6	3	4
5	3	4
4	2	3
3	2	3
2	2	2
1	1	2
```

### StarRocks version (Required)
3.0

**Comment by rcauble** [comment]
I had to stare at this for a while but I think I finally have an explanation for the expected behavior. You basically need to remove the nulls from the stream entirely when calculating the window fn. Here's expected with NULLs removed from the VAL column:

```
"33","50","NULL"
"32","40","NULL"
"31","30","50"
"30","20","40"
"29","10","30"
"28","40","20"
"27","30","10"
"26","20","40"
"25","10","30"
"19","201","20"
"17","6","10"
"16","201","201"
"14","6","6"
"12","201","201"
"11","200","6"
"10","6","201"
"9","5","200"
"8","4","6"
"7","4","5"
"6","3","4"
"5","3","4"
"4","2","3"
"3","2","3"
"2","2","2"
"1","1","2"
```
In particular you can see line 19 and line 12 -- in the expected results they correctly reference the non-null value 2 elements beforehand (20 and 201 respectively) whereas in the actual results these return 10 and 6 respectively.

I'm going to create a simpler example because the example here is confusing.

**Comment by rcauble** [comment]
**HERE's a better example:**

### Steps to reproduce the behavior (Required)
```
CREATE DATABASE TEST1;

CREATE TABLE `TEST1`.`A` (`a` BIGINT, `b` BIGINT)  DISTRIBUTED BY HASH (`a`) PROPERTIES("replication_num" = "1");
INSERT INTO `TEST1`.`A`(`a`,`b`) VALUES(1,1);
INSERT INTO `TEST1`.`A`(`a`,`b`) VALUES(2,2);
INSERT INTO `TEST1`.`A`(`a`,`b`) VALUES(3,3);
INSERT INTO `TEST1`.`A`(`a`,`b`) VALUES(4,4);
INSERT INTO `TEST1`.`A`(`a`) VALUES(5);
INSERT INTO `TEST1`.`A`(`a`) VALUES(6);
INSERT INTO `TEST1`.`A`(`a`) VALUES(7);
INSERT INTO `TEST1`.`A`(`a`) VALUES(8);
INSERT INTO `TEST1`.`A`(`a`,`b`) VALUES(9,9);
INSERT INTO `TEST1`.`A`(`a`,`b`) VALUES(10,10);
INSERT INTO `TEST1`.`A`(`a`,`b`) VALUES(11,11);
INSERT INTO `TEST1`.`A`(`a`,`b`) VALUES(12,12);

  SELECT
    `A`,
    `B`,
    LAG(`B` IGNORE NULLS, 3) over (
      order by
        `A`
    ) AS `LAG`
  FROM
    `TEST1`.`A` ORDER BY A;
```
### Expected behavior (Required)
```
"1","1","NULL"
"2","2","NULL"
"3","3","NULL"
"4","4","1"
"5","NULL","2"
"6","NULL","2"
"7","NULL","2"
"8","NULL","2"
"9","9","2"
"10","10","3"
"11","11","4"
"12","12","9"
```

### Real behavior (Required)
```
A	B	LAG
1	1	NULL
2	2	NULL
3	3	NULL
4	4	1
5	NULL	2
6	NULL	3
7	NULL	4
8	NULL	4
9	9	4
10	10	4
11	11	4
12	12	9
```

### StarRocks version (Required)
3.0

**Comment by liuyehcf** [comment]
This is the expected behavior.

And here is how the current implementation goes:
LAG(`B` IGNORE NULLS, 3) means: For each row, looking at the value of index `i-3`, if the value is null, keep going until reaching a non-null value or all the rows are exhausted.

**Comment by rcauble** [comment]
Like I indicated in the chat, it's subtle behavior -- I think my 2nd and 3rd comment help to clarify it. The way IGNORE NULLS is intended to be interpreted is pretend as though there are no nulls in the stream. If you do that then on row 9 it should be looking at  2 since it's the -3rd non-null value. The real behavior outputs 4 which is the -1th non-null value.

**Comment by liuyehcf** [comment]
> Like I indicated in the chat, it's subtle behavior -- I think my 2nd and 3rd comment help to clarify it. The way IGNORE NULLS is intended to be interpreted is pretend as though there are no nulls in the stream. If you do that then on row 9 it should be looking at 2 since it's the -3rd non-null value. The real behavior outputs 4 which is the -1th non-null value.

where is the 2nd and 3rd comment?

**Comment by rcauble** [comment]
> > Like I indicated in the chat, it's subtle behavior -- I think my 2nd and 3rd comment help to clarify it. The way IGNORE NULLS is intended to be interpreted is pretend as though there are no nulls in the stream. If you do that then on row 9 it should be looking at 2 since it's the -3rd non-null value. The real behavior outputs 4 which is the -1th non-null value.
> 
> where is the 2nd and 3rd comment?

On this bug. I have my opening comment which had an initial example but then 2 follow on comments, one that starts with "I had to stare at this for a while but I think I finally have an explanation" and one that starts with "HERE's a better example:". Do you see those comments?

**Comment by liuyehcf** [comment]
> > > Like I indicated in the chat, it's subtle behavior -- I think my 2nd and 3rd comment help to clarify it. The way IGNORE NULLS is intended to be interpreted is pretend as though there are no nulls in the stream. If you do that then on row 9 it should be looking at 2 since it's the -3rd non-null value. The real behavior outputs 4 which is the -1th non-null value.
> > 
> > 
> > where is the 2nd and 3rd comment?
> 
> On this bug. I have my opening comment which had an initial example but then 2 follow on comments, one that starts with "I had to stare at this for a while but I think I finally have an explanation" and one that starts with "HERE's a better example:". Do you see those comments?

Sorry, I have mistook you as my colleague because you have the same icon, and of course I can see your comments.

And the fix pr has linked to this issue, you can check on it.
