### ISSUE TITLE
Support to read and write kudu external table

### ISSUE THREAD

**Issue by hiliuxg** [StarRocks/starrocks#1850]
## Enhancement
presto and impala support to read  and write kudu external table  .  many user use kudu as they upsert db and presto or impala as there olap tools . If they want to use starrocks , it would be perfect if starrocks  support read and write kudu external table .

**Comment by jaogoy** [comment]
It will be really useful for those Kudu users.
It may be listed on the roadmap.
We are also glad to see your contributions.
