### ISSUE TITLE
Broker load to primary key table, make backend crash

### ISSUE THREAD

**Issue by 5herhom** [StarRocks/starrocks#18531]
The situation happened everytime I execute the broker load. If i use udf to the pk in brokerload, the be will crash. And I remove the udf, it become normal.
#### Create the primary key  table：

CREATE TABLE fx_dcl.flink_fx_quality_kcd_deploy_frequency_part_i (
  `ymd` varchar(65533) COMMENT '年月日 例：2023-02-13',
  `system_default_id` varchar(65533) COMMENT ',
  `server_time` varchar(65533) COMMENT '',
  `count` int COMMENT '发',
  `t` int COMMENT '服务器时间 例：1676450290',
  `dt` varchar(65533) COMMENT ''
) ENGINE = OLAP PRIMARY KEY (`ymd`) COMMENT "业务发布数据统计" DISTRIBUTED BY HASH(`ymd`) BUCKETS 1 PROPERTIES (
  "replication_num" = "1",
  "storage_type" = "column",
  "storage_medium" = "SSD"
);

#### Broker load dfs to the table, and use 'ifnull' udf to the key：

LOAD LABEL fx_dcl.fx_dcl_flink_fx_quality_kcd_deploy_frequency_part_i_2023_02_15_20230224185658812 (
  DATA INFILE(
    "dfs_path"
  ) INTO TABLE flink_fx_quality_kcd_deploy_frequency_part_i FORMAT AS ORC (
    `system_default_id`,
    `server_time`,
    `count`,
    `ymd`,
    `t`
  ) COLUMNS
  FROM
    PATH AS (dt)
  SET
    (
      `ymd` = ifnull(`ymd`,' ')
      `system_default_id` = `system_default_id`,
      `server_time` = `server_time`,
      `count` = `count`,
      `t` = `t`,
      `dt` = `dt`
    )
) WITH BROKER 'srbroker' PROPERTIES ("strict_mode" = "true");

#### Then the be crashed. And print log:

W0224 18:05:35.665314  5711 stack_util.cpp:126] 2023-02-24 18:05:35.665289, query_id=6ca558de-5e50-43a5-b987-b6650392fea0, fragment_instance_id=6ca558de-5e50-43a5-b987-b6650392fea1 throws exception: std::length_error, trace:
     @          0x2a163a5  std::__throw_length_error()
    @          0x2c0c9c2  std::vector<>::_M_range_insert<>()
    @          0x2c0ff94  starrocks::vectorized::BinaryColumnBase<>::append()
    @          0x4c92a02  starrocks::vectorized::Chunk::append()
    @          0x3fde439  starrocks::ChunkPipelineAccumulator::push()
    @          0x2eeeb31  starrocks::pipeline::ConnectorChunkSource::_read_chunk()
    @          0x2ed888c  starrocks::pipeline::ChunkSource::buffer_next_batch_chunks_blocking()
    @          0x2c5bce4  _ZZN9starrocks8pipeline12ScanOperator18_trigger_next_scanEPNS_12RuntimeStateEiENKUlvE_clEv
    @          0x2c6cd1d  starrocks::workgroup::ScanExecutor::worker_thread()
    @          0x47a3a9d  starrocks::ThreadPool::dispatch_thread()
    @          0x479e82a  starrocks::Thread::supervise_thread()
    @     0x7f20b034ce65  start_thread
    @     0x7f20af96788d  __clone
    @              (nil)  (unknown)

### StarRocks version (Required)
version: 2.5.1

**Comment by meegoo** [comment]
@5herhom can you provider some data which can reproduce this case
