### ISSUE TITLE
Don't force to use alias  in some sql scenarios ?

### ISSUE THREAD

**Issue by hiliuxg** [StarRocks/starrocks#1855]
## Enhancement
the sql
`select
   count(distinct if(evid in ('fx_virtual_goods_Anchor_entrance_show'),kgid,null))                                                                                   as star_uv
 , count(distinct if(evid in ('fx_virtual_goods_Anchor_goodslist_show'),kgid,null))                                                                                  as expo_uv
 , count(distinct if(evid in ('fx_virtual_goods_User_entrance_show'),kgid,null))                                                                                     as list_expo_uv
 , count(distinct if(evid in ('fx_virtual_goods_User_goodslist_show'),kgid,null))                                                                                    as list_expo_uv
 , count(distinct if(evid in ('fx_virtual_goods_User_listbuy_click'),kgid,null))                                                                                     as buy_expo_uv
 , count(distinct if(evid in ('fx_virtual_goods_User_gooddetail_show'),kgid,null))                                                                                   as detil_expo_uv
 , count(distinct if(evid in ('fx_virtual_goods_User_Buydirectly_click'),kgid,null))                                                                                 as detil_buy_uv
 , count(distinct if(evid in ('fx_virtual_goods_User_goodsbuy_click','fx_virtual_goods_User_concernbuy_click','fx_virtual_goods_User_Buydirectly_click'),kgid,null)) as all_buy_uv
 , count(distinct if(evid in ('fx_virtual_goods_User_Confirmpay_click'),kgid,null))                                                                                  as sure_buy_uv
from
   (
      select
         dt
       , kgid
       , evid
      from
         fx_dcl.aaaaa
      where
         dt   >='2021-11-27'
         and dt<'2021-12-03'
         and evid     in ('fx_virtual_goods_User_goodsbuy_click' )
         and kgid not in ('739228844','99303996','1292668843')
      union all
      select
         dt
       , kugou_id  as kgid
       , action_id as evid
      from
         fx_ddl.bbbbb
      where
         dt   >='2021-11-27'
         and dt<'2021-12-03'
         and platform     in (1          , 2)
         and kugou_id not in ('739228844','99303996','1292668843')
         and action_id    in ('fx_virtual_goods_User_entrance_show')
   ) `
and
`select substr(dt,1,7) dtm
,intimacy
,avg(uv) uv
,avg(money) money
from (
    select a.dt
    ,case
    when intimacy < 10 and intimacy > 0 then '0.0-10'
    when intimacy < 100 then '1.10-100'
    when intimacy < 1000 then '2.100-1000'
    when intimacy < 5000 then '3.1000-5000'
    when intimacy >= 5000 then '4.5000-5000+'
    else '0.0-10' end intimacy
    ,count(a.kgid) uv
    ,sum(money) money
    from(
        select dt
        ,kgid
        ,count(1) pv
        ,count(if(is_follower = 1,1,null)) fans_pv
        from fx_ddl.dddddddddddd
        where dt >= '2021-11-01' and dt <= '2021-11-30'
        and plat_id in (5,6)
        and entry_id <> '5_1'
        and cast(kgid as bigint) > 0
        group by dt,kgid
    )a
    left join(
        select dt
        ,kgid
        ,sum(intimacy) intimacy
        from fx_ddl.fx_user_star_intimacy a
        left join(
            select kgid live_kgid
            from (
                select room_id
                from fx_dcl.cccccccccccc
                where dt = '2021-12-02'
            )a
            left join(
                select room_id,kgid
                from fx_ddl.bbbbbbbbbb
                where dt = '2021-12-02'
            )b on a.room_id = b.room_id
        )b on a.tkid = b.live_kgid
        where dt between '2021-11-01' and '2021-11-30'
        group by dt
        ,kgid
    )b on a.dt = b.dt and a.kgid = b.kgid
    left join(
        select dt
        ,kgid
        ,sum(consume_money_coin)/100.0 money
        from fx_ddl.aaaaaaa
        where dt between '2021-11-01' and '2021-11-30'
        --and plat_level2_code =9100
        group by dt
        ,kgid
    )c on a.dt = c.dt and a.kgid = c.kgid
    group by a.dt
    ,case
    when intimacy < 10 and intimacy > 0 then '0.0-10'
    when intimacy < 100 then '1.10-100'
    when intimacy < 1000 then '2.100-1000'
    when intimacy < 5000 then '3.1000-5000'
    when intimacy >= 5000 then '4.5000-5000+'
    else '0.0-10' end
)a
group by substr(dt,1,7)
,intimacy`
can use in presto but error in starrocks

**Comment by imay** [comment]
@HangyuanLiu PTAL
