### ISSUE TITLE
Support create table as 

### ISSUE THREAD

**Issue by hiliuxg** [StarRocks/starrocks#1856]
## Enhancement
support sql syntax create table as select ... 
`
CREATE TABLE IF NOT EXISTS orders_by_date AS
SELECT orderdate, sum(totalprice) AS price
FROM orders
GROUP BY orderdate
`

**Comment by Astralidea** [comment]
Hi @hiliuxg , this feature is under development, you can see it in #1392.

**Comment by Astralidea** [comment]
This feature is already release.
