### ISSUE TITLE
`SQL_SELECT_LIMIT` causes a valid query to external MySQL table to return a syntax error

### ISSUE THREAD

**Issue by fulghum** [StarRocks/starrocks#18596]
Hey StarRocks, we're working with a customer who is testing out the [new support for temporal/as-of queries with external MySQL databases](https://github.com/StarRocks/starrocks/pull/13707), but we ran into an issue where the queries fail with a syntax error when the `SQL_SELECT_LIMIT` system var is set, which happens automatically by SQL workbench tools like DBeaver and DataGrip. We were able to workaround this problem by disabling the option to send `SQL_SELECT_LIMIT` in DBeaver, but wanted to circle back and see if there is a change needed on StarRocks to smooth this out. 

When `SQL_SELECT_LIMIT` is NOT set, the query is dispatched to the external MySQL instance and the correct results are returned. When `SQL_SELECT_LIMIT` is set, the query seems to fail on the frontend node with a syntax error exception, starting at the "as of" clause in the query. 

I'm guessing that when `SQL_SELECT_LIMIT` is set, StarRocks tries to pass that limit on to other queries it's dispatching to be executed. I'm not sure why the parser is failing to parse the query in this case though. 

Thanks for any help you can provide! 

### Steps to reproduce the behavior (Required)
Launch an external MySQL-compatible server on localhost:
```sql
# install Dolt
sudo bash -c 'curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | bash'

# set up a Dolt database with some test data
mkdir doltdb
cd doltdb
dolt init
dolt sql -q "CREATE TABLE t (pk int NOT NULL, value varchar(100), PRIMARY KEY (pk));"
dolt commit -Am "Creating table t"
dolt sql -q "INSERT INTO t VALUES (1, 'one');"
dolt commit -Am "Inserting row 1"
dolt sql -q "INSERT INTO t VALUES (2, 'twooo');"
dolt commit -Am "Inserting row 2"
dolt sql -q "INSERT INTO t VALUES (100, 'one hundy!');"
dolt commit -Am "Inserting row 3"

# start the server process 
dolt sql-server -udolt --port 11223 
```

After starting an FE and BE node on localhost, connect to the FE SQL shell, configure the external MySQL table, and trigger the error: 
```sql
set enable_pipeline_engine=true;

-- Create a database to test with
create database db01;
use db01;

-- Declare the external MySQL table 
CREATE EXTERNAL TABLE mysql_external_table1
(
    pk INT,
    value VARCHAR(100)
)
ENGINE=mysql
PROPERTIES
(
    "host" = "127.0.0.1",
    "port" = "11223",
    "user" = "dolt",
    "password" = "",
    "database" = "dolt",
    "table" = "t"
);

-- Test out some queries
select * from mysql_external_table1;
select * from mysql_external_table1 as of ‘HEAD’;

-- This same query will fail with a syntax error after setting SQL_SELECT_LIMIT
SET SQL_SELECT_LIMIT=200;
select * from mysql_external_table1 as of ‘HEAD’;
```

### Expected behavior (Required)
I would expect the query above to return the same results (up to a maximum of `SQL_SELECT_LIMIT` rows) as it does when `SQL_SELECT_LIMIT` is not set. 

### Real behavior (Required)
StarRocks returns a syntax error about being unable to parse the statement when `SQL_SELECT_LIMIT` is set, but happily executes the query without any problems when `SQL_SELECT_LIMIT` is NOT set. 

### StarRocks version (Required)
2.5.2 c3772fb

**Comment by fulghum** [comment]
Hey @Astralidea, thank you for picking this one up! 🙏 Let me know if there's anything I can provide from my side, or anything I can run through the debugger to help provide more info or clues.

**Comment by Astralidea** [comment]
I'm a bit busy recently so I didn't come to look at this problem urgently. I will reproduce and try to solve this problem recently.

**Comment by Astralidea** [comment]
I'm sorry I didn't have time to read your question so late, you're amazing at playing this way.
However, I have already located the cause of your problem. In fact, it is caused by a mistake in spelling sql. The limit needs to be placed at the end. If it is placed in the middle through sr transparent transmission, there will be problems after passing.
<img width="436" alt="image" src="https://user-images.githubusercontent.com/4392280/224025498-845bef86-be1b-4cdf-921c-a22a78dba603.png">
At the same time, I also recommend typing out this sql. If there is a problem, it will be easier to locate the problem by turning on the verbose log.

**Comment by fulghum** [comment]
Amazing! Thank you @Astralidea! 😊 

Thanks for the help debugging and for pointing out the be query log. I'll be sure to dig deeper there for any future issues. 🙏  I really appreciate you opening the PR for this fix!! 🙏
