### ISSUE TITLE
Add array_remove function

### ISSUE THREAD

**Issue by luyou86** [StarRocks/starrocks#1869]
### 1. feature description
```
> SELECT array_remove(array(1, 2, 3, null, 3), 3);
 [1,2,null]
```
### 2. Additional context
- [spark sql array_remove](https://spark.apache.org/docs/latest/api/sql/index.html#array_remove)

**Comment by Dshadowzh** [comment]
Thanks for your reporting. We will improve array functions in the next few versions.
