### ISSUE TITLE
query result incorrect where value is null

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#1874]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS d8;
CREATE DATABASE d8;
USE d8;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 VARCHAR(21) NULL ,c_0_1 DATETIME NOT NULL ,c_0_2 DECIMAL32(2, 2)  NULL ) DUPLICATE KEY (c_0_0) DISTRIBUTED BY HASH (c_0_0) properties("replication_num"="1") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 TINYINT NOT NULL ,c_1_1 CHAR(31) NOT NULL ,c_1_2 DECIMAL64(15, 11)  NULL ,c_1_3 DECIMAL128(9, 8)  NULL ,c_1_4 DATE NULL ,c_1_5 DECIMAL32(2, 2)  MIN NOT NULL ,c_1_6 DECIMAL(17, 8)  MIN NULL ,c_1_7 VARCHAR(11) MIN NULL ,c_1_8 BOOLEAN REPLACE NOT NULL ,c_1_9 DECIMAL128(37, 7)  MIN NULL ,c_1_10 INT REPLACE NULL ,c_1_11 DATETIME MAX NULL ) AGGREGATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4) DISTRIBUTED BY HASH (c_1_0) properties("replication_num"="1") ;
CREATE TABLE t2 (c_2_0 DECIMAL(4, 1)  NULL ,c_2_1 DATE NULL ,c_2_2 DECIMAL128(25, 2)  NOT NULL ,c_2_3 DECIMAL32(7, 7)  NULL ,c_2_4 DECIMAL32(3, 3)  NULL ,c_2_5 DECIMAL(21, 4)  NULL ,c_2_6 DECIMAL(19, 2)  NULL ,c_2_7 DECIMAL(8, 5)  NOT NULL ,c_2_8 DECIMAL128(34, 29)  NOT NULL ,c_2_9 DECIMAL128(8, 6)  MAX NOT NULL ) AGGREGATE KEY (c_2_0,c_2_1,c_2_2,c_2_3,c_2_4,c_2_5,c_2_6,c_2_7,c_2_8) DISTRIBUTED BY HASH (c_2_8,c_2_7,c_2_0) properties("replication_num"="1") ;
INSERT INTO t0 VALUES ("w", "1970-01-01 08:00:00", 0.02);
TRUNCATE TABLE t2;
INSERT INTO t0 VALUES ("", "1970-01-01 08:00:00", 0.02);
INSERT INTO t0 VALUES ("ftTW", "1970-01-01 08:00:00", 0.08), ("", "1970-01-01 08:00:00", 0.00);
INSERT INTO t0 VALUES ("4", "1970-01-01 08:00:00", NULL), ("JN", "1970-01-01 08:00:00", 0.04);
INSERT INTO t1 VALUES (3, "aW9Npphm", 2.14E-9, 6E-8, "1970-01-01", 0.02, 7.68177861, "zmR5", false, 8144860864079470110030.5008623, NULL, "1970-01-01 08:00:00");
INSERT INTO t0 VALUES ("T4WUB2dX", "1970-01-01 08:00:00", 0.08), ("rI9KQw", "1970-01-01 08:00:00", 0.01);
INSERT INTO t0 VALUES ("Lg4", "1970-01-01 08:00:00", 0.05);
INSERT INTO t1 VALUES (2, "EyK23TP", 6.261E-8, 3E-8, "1970-01-01", 0.00, 5.41838174, NULL, false, 7142686605970773908359.5168239, 5, "1970-01-01 08:00:00");
INSERT INTO t1 VALUES (7, "sEWS7v", 8.30E-9, 3E-8, "1970-01-01", 0.05, 7.56676500, "", false, 65406066386600723457759.3099089, 19, "1970-01-01 08:00:00");
INSERT INTO t1 VALUES (0, "", 1.897E-8, 4E-8, "1970-01-01", 0.01, 7.93098545, "uj3v", false, 99540360687896774133053.2792431, 3, "1970-01-01 08:00:00"), (4, "bM", 2.786E-8, 3E-8, "1970-01-01", 0.08, 3.55557393, "fXHLAlg", true, 95549315308249794514279.4524286, 14, "1970-01-01 08:00:00");
INSERT INTO t2 VALUES (55.3, "1970-01-01", 650418576411155465540.32, 1E-7, 0.006, 8491252501254.0971, 56568581587046.93, 0.00865, 4.8337E-25, 0.000007), (31.7, "1970-01-01", 418566392871881091311.54, 4E-7, 0.006, NULL, 725772288497950.12, 0.00834, 9.559E-26, 0.000067), (65.4, "1970-01-01", 614571512707485112514.88, 2E-7, 0.006, 1310172067621.5048, 683723517185392.37, 0.00624, 8.2957E-25, 0.000021);
DELETE FROM t1 WHERE c_1_3=1E-8 AND c_1_4="1970-01-07" AND c_1_0=1070281118 AND c_1_1="11BuA" AND c_1_2=7.510E-8;
DELETE FROM t2 WHERE c_2_5=5020864403275.2163 AND c_2_8=NULL AND c_2_2=933029637008488096547.64 AND c_2_1="1970-01-10" AND c_2_3=5E-7 AND c_2_6=44239362242558.86;
INSERT INTO t1 VALUES (5, "YScB", 4.024E-8, 8E-8, "1970-01-01", 0.01, 2.31007880, "V", true, 29420125079293258845344.5941212, 30, "1970-01-01 08:00:00");
INSERT INTO t2 VALUES (44.9, "1970-01-01", 836411848337959992059.01, 5E-7, 0.004, NULL, 192137690981258.28, 0.00973, 4.6159E-25, 0.000065), (64.6, "1970-01-01", 765471679572456765039.21, 6E-7, 0.004, 7607080098834.4936, 883119778729438.51, 0.00359, 4.7845E-25, 0.000046);
INSERT INTO t1 VALUES (2, "k", 9.601E-8, 6E-8, "1970-01-01", 0.06, 1.35662433, "8", false, 42513177201504232449196.4631505, 14, "1970-01-01 08:00:00"), (2, "Fs", 7.344E-8, 2E-8, "1970-01-01", 0.07, 0.68028717, "", true, 25822078112515391283453.5585574, 23, "1970-01-01 08:00:00");
INSERT INTO t2 VALUES (85.8, "1970-01-01", 426658192833528474451.62, NULL, 0.006, 7891124457790.3103, 403893403152069.27, 0.00498, 2.8572E-25, 0.000031);
INSERT INTO t0 VALUES (NULL, "1970-01-01 08:00:00", NULL), (NULL, "1970-01-01 08:00:00", 0.02);
2. mysql> SELECT DISTINCT t0.c_0_0 FROM t0, t1;
+----------+
| c_0_0    |
+----------+
| rI9KQw   |
| T4WUB2dX |
| ftTW     |
| 4        |
| Lg4      |
| NULL     |
| JN       |
|          |
| w        |
+----------+
3. mysql> SELECT DISTINCT * FROM (SELECT DISTINCT t0.c_0_0 FROM t0, t1 WHERE ((t0.c_0_2) IS NULL) UNION ALL SELECT DISTINCT t0.c_0_0 FROM t0, t1 WHERE (NOT (((t0.c_0_2) IS NULL))) UNION ALL SELECT DISTINCT t0.c_0_0 FROM t0, t1 WHERE ((((t0.c_0_2) IS NULL)) IS NULL)) t;
+----------+
| c_0_0    |
+----------+
| w        |
| Lg4      |
| T4WUB2dX |
| ftTW     |
| JN       |
| rI9KQw   |
| 4        |
|          |
+----------+

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch release
 - mysql> select current_version();
+---------------------------------+
| current_version()               |
+---------------------------------+
| SQLANCER_BRANCH_RELEASE 44d6eed |
+---------------------------------+

**Comment by Seaven** [comment]
set cbo_enable_low_cardinality_optimize=false; result is right

**Comment by stdpain** [comment]
mini reproduce case:
```
 SELECT t0.c_0_0,t0.c_0_2 FROM t0, t1 WHERE (t0.c_0_2 IS NULL);
```
