### ISSUE TITLE
query return error: deserialize chunk data failed. len: 42, except: 45

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#1882]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS h30;
CREATE DATABASE h30;
USE h30;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DECIMAL64(16, 4)  NOT NULL ,c_0_1 DECIMAL64(6, 4)  NULL ,c_0_2 BOOLEAN NULL ,c_0_3 DECIMAL(1, 0)  NOT NULL ,c_0_4 DATETIME NOT NULL ,c_0_5 DECIMAL128(24, 16)  NULL ,c_0_6 DATETIME NULL ,c_0_7 DECIMAL32(4, 0)  NULL ,c_0_8 DECIMAL(25, 2)  NOT NULL ,c_0_9 BOOLEAN NOT NULL ,c_0_10 BIGINT NULL ,c_0_11 DOUBLE NULL ,c_0_12 DECIMAL64(11, 9)  NULL ,c_0_13 SMALLINT NOT NULL ,c_0_14 DOUBLE NULL ,c_0_15 DECIMAL32(4, 2)  NOT NULL ,c_0_16 DECIMAL32(7, 4)  NOT NULL ) DUPLICATE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5,c_0_6,c_0_7,c_0_8,c_0_9,c_0_10) DISTRIBUTED BY HASH (c_0_3,c_0_4,c_0_10) properties("replication_num"="1") ;
CREATE TABLE t1 (c_1_0 VARCHAR(11) NULL ,c_1_1 VARCHAR(41) NOT NULL ) DUPLICATE KEY (c_1_0) DISTRIBUTED BY HASH (c_1_0) properties("replication_num"="1") ;
CREATE TABLE t2 (c_2_0 DECIMAL(22, 5)  NULL ,c_2_1 DECIMAL(18, 6)  NOT NULL ,c_2_2 BOOLEAN NOT NULL ,c_2_3 CHAR(21) NOT NULL ,c_2_4 DATE NOT NULL ,c_2_5 DOUBLE NULL ,c_2_6 BIGINT NULL ) UNIQUE KEY (c_2_0,c_2_1,c_2_2,c_2_3,c_2_4) DISTRIBUTED BY HASH (c_2_1,c_2_2,c_2_4) properties("replication_num"="1") ;
INSERT INTO t1 VALUES ("2", ""), ("", ""), ("gGhP", "CDUIi");
INSERT INTO t1 VALUES ("k", ""), ("zlxXW", ""), ("", ""), ("z", "22BK");
INSERT INTO t1 VALUES ("i", ""), ("", ""), ("Wph", "");
INSERT INTO t1 VALUES ("g", ""), (NULL, "B6");
INSERT INTO t1 VALUES ("", "PDoK0O");
INSERT INTO t2 VALUES (881620845840.27549, 339618.280886, false, "", "1970-01-01", -5.87373764E8, 488623548), (177420267097.34784, 41850.302960, false, "qTt", "1970-01-01", 0.7897665892203528, 867990371);
INSERT INTO t0 VALUES (14357832.5271, NULL, true, 6, "1970-01-01 08:00:00", 1.3014878E-9, "1970-01-01 08:00:00", 3709, 195159381829384418040.43, false, 2131342246, NULL, NULL, 10, 0.3844218376524977, 0.88, 0.0922), (36127624.8323, 0.0003, false, 3, "1970-01-01 08:00:00", 4.8546334E-9, "1970-01-01 08:00:00", 5072, 818977147432448765144.32, false, 1909440985, NULL, 8.3E-8, 3, 0.8795587299286838, 0.62, 0.0854), (24784058.8388, 0.0010, false, 5, "1970-01-01 08:00:00", 1.8243137E-9, "1970-01-01 08:00:00", 6096, 278019194997043028335.07, false, -478518060, 0.21937273805620683, 1.3E-8, 4, 0.1462225494352255, 0.00, 0.0956);
INSERT INTO t0 VALUES (28160168.1691, 0.0088, false, 4, "1970-01-01 08:00:00", 8.0961113E-9, "1970-01-01 08:00:00", 7666, 418740144555059155086.83, true, -1916765676, 1.564722928E9, 9.2E-8, 8, 0.4011897957319308, 0.03, 0.0332);
INSERT INTO t1 VALUES ("lj", "kzW9hSN"), ("gP", "");
INSERT INTO t0 VALUES (71659134.2531, 0.0034, false, 1, "1970-01-01 08:00:00", 7.5136721E-9, "1970-01-01 08:00:00", 3077, 876303711454923473559.44, false, -1162087459, 0.9188744119897013, 2.0E-8, 3, 0.853332214562752, 0.62, 0.0598), (87588395.3718, 0.0044, false, 4, "1970-01-01 08:00:00", 4.4551795E-9, "1970-01-01 08:00:00", 8240, 440654948316037579728.93, false, 781482337, NULL, 4.9E-8, 4, 1.08856563E9, 0.71, 0.0611);
INSERT INTO t1 VALUES ("k8vcSIPe", "MeCKJvD"), ("", "Fd");
INSERT INTO t1 VALUES ("", "0"), ("MESUUg", "w");
INSERT INTO t0 VALUES (13760504.7880, 0.0025, true, 3, "1970-01-01 08:00:00", 7.7258938E-9, "1970-01-01 08:00:00", 6985, 350706149777792575153.27, true, -902727257, NULL, 8.8E-8, 6, -1.916765676E9, 0.33, 0.0979);
2. SELECT t1.c_1_0 FROM t1 WHERE (t1.c_1_0) IN ("PG", "")  GROUP BY t1.c_1_0, t1.c_1_0 HAVING false UNION ALL SELECT t1.c_1_0 FROM t1 WHERE (t1.c_1_0) IN ("PG", "")  GROUP BY t1.c_1_0, t1.c_1_0 HAVING (NOT (false)) UNION ALL SELECT t1.c_1_0 FROM t1 WHERE (t1.c_1_0) IN ("PG", "")  GROUP BY t1.c_1_0, t1.c_1_0 HAVING ((false) IS NULL);

### Expected behavior (Required)
execute correct
### Real behavior (Required)
mysql> SELECT t1.c_1_0 FROM t1 WHERE (t1.c_1_0) IN ("PG", "")  GROUP BY t1.c_1_0, t1.c_1_0 HAVING false UNION ALL SELECT t1.c_1_0 FROM t1 WHERE (t1.c_1_0) IN ("PG", "")  GROUP BY t1.c_1_0, t1.c_1_0 HAVING (NOT (false)) UNION ALL SELECT t1.c_1_0 FROM t1 WHERE (t1.c_1_0) IN ("PG", "")  GROUP BY t1.c_1_0, t1.c_1_0 HAVING ((false) IS NULL);
ERROR 1064 (HY000): deserialize chunk data failed. len: 42, except: 45

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.0 release
 - mysql> select current_version();
+---------------------------------+
| current_version()               |
+---------------------------------+
| SQLANCER_BRANCH_RELEASE 44d6eed |
+---------------------------------+

**Comment by Seaven** [comment]
`set cbo_enable_low_cardinality_optimize=false;` result is right
