### ISSUE TITLE
Add functions

### ISSUE THREAD

**Issue by hiliuxg** [StarRocks/starrocks#1886]
## Enhancement
Many of our users use the following udf a lot, hoping to support
```
json_extract
nvl
regexp_replace
regexp_extract
regexp_like
approx_percentile
```
link
https://trino.io/docs/current/functions/json.html?highlight=json_extract#json_extract
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF#LanguageManualUDF-Built-inFunctions
https://trino.io/docs/current/functions/regexp.html?highlight=regexp_replace#regexp_replace
https://trino.io/docs/current/functions/aggregate.html?highlight=approx_percentile#approx_percentile
https://trino.io/docs/current/functions/regexp.html?highlight=regexp_extract#regexp_extract
https://trino.io/docs/current/functions/regexp.html?highlight=regexp_like#regexp_like

**Comment by Dshadowzh** [comment]
regexp_replace approx_percentile  is supported.  
nvl is equal to approx_count_distinct in StarRocks.
You can search in docs.starrocks.com

**Comment by hiliuxg** [comment]
@Dshadowzh

**Comment by hiliuxg** [comment]
same sql when using regexp_replace but return different result . one execute in starrocks , one execute in presto .

![9da111d7e78663cc4ef1689c4628ead](https://user-images.githubusercontent.com/39675622/144805810-43372545-5733-4186-81be-d55effd5695b.png)

![7b7d551ff6273b8efcd04858c87024b](https://user-images.githubusercontent.com/39675622/144805826-61a12fed-5022-4045-9538-9b51d1a47c0d.png)

regexp_replace , we not only expect the same function conent , but also the same function name . because many of history 
jobs and users  are use approx_percentile  but not percentile_approx

nvl is different from  approx_count_distinct 
![image](https://user-images.githubusercontent.com/39675622/144806345-3ea82890-b692-4e92-81cc-ff652e928786.png)

In addition, I added two other regular udf 

@Dshadowzh

**Comment by Seaven** [comment]
@hiliuxg 
1. Starrocks was support `regrexp` stynax, you can use it such as: `select 'alike123' regexp '\\w+\\d+';`
2. For your `regexp_extract` case, you can try `(\\d+)([a-z]+)`, result different because '/' escape character is ignored
3. For `nvl`, it's not support now, and you can try `ifnull` function, the function support same work with `nvl`
