### ISSUE TITLE
query result error in: cast datetime as date in datetime

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#1887]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS w13;
CREATE DATABASE w13;
USE w13;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DECIMAL32(7, 2)  NOT NULL ) UNIQUE KEY (c_0_0) DISTRIBUTED BY HASH (c_0_0) properties("replication_num"="1") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 INT NULL ,c_1_1 DECIMAL(24, 5)  NOT NULL ,c_1_2 BIGINT MAX NULL ,c_1_3 HLL HLL_UNION NOT NULL ) AGGREGATE KEY (c_1_0,c_1_1) DISTRIBUTED BY HASH (c_1_0,c_1_1) properties("replication_num"="1") ;
CREATE TABLE t2 (c_2_0 DATETIME NULL ,c_2_1 DATETIME MAX NULL ) AGGREGATE KEY (c_2_0) DISTRIBUTED BY HASH (c_2_0) properties("replication_num"="1") ;
INSERT INTO t0 VALUES (790.08), (200.83);
INSERT INTO t2 VALUES ("1970-01-01 08:00:00", "1970-01-01 08:00:00"), ("1970-01-01 08:00:00", NULL);
INSERT INTO t1 VALUES (14, 10265098779416.29341, 170074617, hll_hash("HCs")), (23, 1833636651340.44094, -556772375, hll_hash(""));
INSERT INTO t0 VALUES (956.41), (362.06);
INSERT INTO t2 VALUES ("1970-01-01 08:00:00", "1970-01-01 08:00:00"), ("1970-01-01 08:00:00", "1970-01-01 08:00:00"), ("1970-01-01 08:00:00", "1970-01-01 08:00:00");
INSERT INTO t1 VALUES (14, 34860625445325.06960, 819008525, hll_hash("oWNH1zj"));
INSERT INTO t2 VALUES ("1970-01-01 08:00:00", NULL), ("1970-01-01 08:00:00", "1970-01-01 08:00:00");
INSERT INTO t1 VALUES (11, 45563253508603.76299, -1712528533, hll_hash("O")), (1, 96357644968044.30068, -433613249, hll_hash("SXynYP")), (9, 11536280268628.24826, -1775564803, hll_hash("HgqTauYhw"));
INSERT INTO t1 VALUES (7, 21538825906099.96380, 572231351, hll_hash("3"));
2. SELECT subt2.c_2_0 FROM t1,  (SELECT t0.c_0_0 FROM t0) subt0 RIGHT ANTI JOIN (SELECT t2.c_2_0, t2.c_2_1 FROM t2) subt2 ON subt0.c_0_0 = subt2.c_2_0 AND subt0.c_0_0 >= subt2.c_2_0;
3. SELECT subt2.c_2_0 FROM t1,  (SELECT t0.c_0_0 FROM t0) subt0 RIGHT ANTI JOIN (SELECT t2.c_2_0, t2.c_2_1 FROM t2) subt2 ON subt0.c_0_0 = subt2.c_2_0 AND subt0.c_0_0 >= subt2.c_2_0 WHERE (CAST(subt2.c_2_0 AS DATE ) ) IN ("1970-01-20 13:21:31", "1970-01-01 21:43:24") ;
4. SELECT subt2.c_2_0 FROM t1,  (SELECT t0.c_0_0 FROM t0) subt0 RIGHT ANTI JOIN (SELECT t2.c_2_0, t2.c_2_1 FROM t2) subt2 ON subt0.c_0_0 = subt2.c_2_0 AND subt0.c_0_0 >= subt2.c_2_0 WHERE (NOT ((CAST(subt2.c_2_0 AS DATE ) ) IN ("1970-01-20 13:21:31", "1970-01-01 21:43:24") ))
5. mysql> SELECT subt2.c_2_0 FROM t1,  (SELECT t0.c_0_0 FROM t0) subt0 RIGHT ANTI JOIN (SELECT t2.c_2_0, t2.c_2_1 FROM t2) subt2 ON subt0.c_0_0 = subt2.c_2_0 AND subt0.c_0_0 >= subt2.c_2_0;
+---------------------+
| c_2_0               |
+---------------------+
| 1970-01-01 08:00:00 |
+---------------------+
6. mysql> SELECT subt2.c_2_0 FROM t1,  (SELECT t0.c_0_0 FROM t0) subt0 RIGHT ANTI JOIN (SELECT t2.c_2_0, t2.c_2_1 FROM t2) subt2 ON subt0.c_0_0 = subt2.c_2_0 AND subt0.c_0_0 >= subt2.c_2_0 WHERE (CAST(subt2.c_2_0 AS DATE ) ) IN ("1970-01-20 13:21:31", "1970-01-01 21:43:24");
Empty set (0.01 sec)
7. mysql> SELECT subt2.c_2_0 FROM t1,  (SELECT t0.c_0_0 FROM t0) subt0 RIGHT ANTI JOIN (SELECT t2.c_2_0, t2.c_2_1 FROM t2) subt2 ON subt0.c_0_0 = subt2.c_2_0 AND subt0.c_0_0 >= subt2.c_2_0 WHERE (NOT ((CAST(subt2.c_2_0 AS DATE ) ) IN ("1970-01-20 13:21:31", "1970-01-01 21:43:24") ));
Empty set (0.02 sec)

### Expected behavior (Required)
cast datetime as date in datetime should in or not in, but it return all empty.
### Real behavior (Required)
Empty set
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.0 release
 - mysql> select current_version();
+---------------------------------+
| current_version()               |
+---------------------------------+
| SQLANCER_BRANCH_RELEASE 44d6eed |
+---------------------------------+

**Comment by Seaven** [comment]
Fixd before branch-2.0 0e6cd4dfd286

```
mysql> SELECT subt2.c_2_0 FROM t1, (SELECT t0.c_0_0 FROM t0) subt0 RIGHT ANTI JOIN (SELECT t2.c_2_0, t2.c_2_1 FROM t2) subt2 ON subt0.c_0_0 = subt2.c_2_0 AND subt0.c_0_0 >= subt2.c_2_0 WHERE (CAST(subt2.c_2_0 AS DATE ) ) IN ("1970-01-20 13:21:31", "1970-01-01 21:43:24") ;
+---------------------+
| c_2_0               |
+---------------------+
| 1970-01-01 08:00:00 |
+---------------------+
1 row in set (0.02 sec)

mysql> SELECT subt2.c_2_0 FROM t1, (SELECT t0.c_0_0 FROM t0) subt0 RIGHT ANTI JOIN (SELECT t2.c_2_0, t2.c_2_1 FROM t2) subt2 ON subt0.c_0_0 = subt2.c_2_0 AND subt0.c_0_0 >= subt2.c_2_0 WHERE (NOT ((CAST(subt2.c_2_0 AS DATE ) ) IN ("1970-01-20 13:21:31", "1970-01-01 21:43:24") ));
Empty set (0.02 sec)
```
