### ISSUE TITLE
When using exactly-once, must set version to V1 to write successfully

### ISSUE THREAD

**Issue by Shan-01** [StarRocks/starrocks#18918]
### Steps to reproduce the behavior (Required)
1. Version information
`本地复现版本
starrocks：2.5.2
flink版本：1.13.6
flink-connector-starrocks：1.2.4_flink-1.13_2.12`
`代码信息
public class Demo1 {
    public static void main(String[] args) throws Exception {
        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();

        DataStreamSource<String> dataStreamSource = env.fromElements(new String[]{
                        "{\"audit_time\":\"2022-10-25 12:55:29.0\",\"batch_id\":\"1675960151612\",\"bill_code\":\"\",\"bill_status\":\"\",\"biz_type\":\"TRANSPORT_PRICING\",\"clarify_detail_code\":\"QF-1675960151612\",\"contract_code\":\"\",\"contract_term_code\":\"2023-02-10\",\"cost_value\":100.0,\"cost_value_exclude\":91.74,\"create_time\":\"2023-02-10T00:29:11.724Z\",\"customer_code\":\"HZ1609738706282\",\"customer_name\":\"HZ1609738706282\",\"ext\":{\"taskId\":0,\"signTime\":1671281940000,\"auditTime\":1666673729072,\"orderTime\":1666668290000,\"projectId\":\"21472\",\"pickupTime\":1657430040000,\"taskStatus\":\"0\",\"projectName\":\"标准合同03\",\"customerCode\":\"HZ1609738706282\",\"customerName\":\"HZ1609738706282\",\"outCustomerName\":\"标准合同\",\"startStationCode\":\"ZD1624864500336\",\"lineIdentification\":\"默认标识\",\"receiptStationCode\":\"ZD1624418488813\"},\"group_cost_code\":\"配送费\",\"id\":4137595,\"load_sum\":11.0000,\"load_volume\":1.0000,\"load_weight\":111.0000,\"node_type\":\"AUDIT\",\"operationEnums\":0,\"order_time\":\"2022-10-25 12:29:46.0\",\"payee\":\"张维攀测试账号\",\"payee_info\":\"丰豪物流（北京）有限公司广州分公司\",\"payee_tenant_id\":\"T1020007011\",\"payer\":\"HZ1609738706282\",\"payer_info\":\"中弘广志建设发展（成都）有限公司\",\"payer_tenant_id\":\"T1020007009\",\"pickup_time\":\"2022-07-10 13:14:00\",\"plan_sum\":11.0000,\"plan_volume\":1.0000,\"plan_weight\":111.0000,\"pricing_source\":\"RULE_PRICING\",\"project_id\":\"21472\",\"project_name\":\"标准合同03\",\"receipt_address\":\"茶马北街1号院2号楼2层2区2-2-229\",\"receipt_city_code\":\"110100\",\"receipt_city_name\":\"北京市\",\"receipt_county_code\":\"110102\",\"receipt_county_name\":\"西城区\",\"receipt_province_code\":\"110000\",\"receipt_province_name\":\"北京市\",\"receipt_station_code\":\"ZD1624418488813\",\"receipt_station_name\":\"茶马北街1号院2号楼2层2区2-2-229\",\"ref_code\":\"D221025007011002305\",\"ref_create_time\":\"2022-10-25T12:55:28Z\",\"ref_type\":\"ORDER\",\"relevance_code\":\"Y221025007009002507\",\"sign_sum\":11.0000,\"sign_time\":\"2022-12-17 20:59:00\",\"sign_volume\":1.0000,\"sign_weight\":111.0000,\"start_address\":\"交子街道三色路与五冶路横向路口北侧(火炬·动力港-一期)\",\"start_city_code\":\"510100\",\"start_city_name\":\"成都市\",\"start_county_code\":\"510104\",\"start_county_name\":\"锦江区\",\"start_province_code\":\"510000\",\"start_province_name\":\"四川省\",\"start_station_code\":\"ZD1624864500336\",\"start_station_name\":\"川魂帽牌货冒菜\",\"status\":\"ENABLED\",\"tax_rate\":0.09,\"tenant_id\":\"T1020007011\",\"update_time\":\"2023-02-24T14:39:42.550Z\"}"
                        });

        dataStreamSource.addSink(
                StarRocksSink.sink(
                        StarRocksSinkOptions.builder()
                                .withProperty("jdbc-url", "jdbc:mysql://xxx.xxx.xxx.xxx:9030?characterEncoding=utf-8")
                                .withProperty("load-url", "xxx.xxx.xxx.xxx:8030")
                                .withProperty("username", "root")
                                .withProperty("password", "")
                                .withProperty("table-name", "b_bmsp_clarify_detail_record_details")
                                .withProperty("database-name", "test")
                                .withProperty("sink.buffer-flush.max-rows", "1000000")
                                .withProperty("sink.buffer-flush.max-bytes", "300000000")
                                .withProperty("sink.buffer-flush.interval-ms", "30000")
                                .withProperty("sink.properties.format", "json")
                                .withProperty("sink.properties.strip_outer_array", "true")
                                .withProperty("sink.semantic","exactly-once")
                                .withProperty("sink.version","V1")
                                // 设置并行度，多并行度情况下需要考虑如何保证数据有序性
                                .withProperty("sink.parallelism", "1")
                                .build()
                )
        );

        env.execute();
    }
}`
2. flink-connector-starrocks写入starrocks。json文件
   When sink. semantic is selected as exactly one, must change sink. version to V1 to write successfully

3.用户测试版本
`starrocks：2.4.1
flink版本：1.14
flink-connector-starrocks：1.2.5_flink-1.14_2.12`
日志显示写入成功
![2a59e2f0-8139-4fc3-a968-07056e8b2255](https://user-images.githubusercontent.com/116535280/222675757-b7efc5ef-219b-4a52-815e-94e18166a644.png)
查询没有
<img width="468" alt="6a5f3bf2-fd71-4b57-9e64-c5d6f9a39191" src="https://user-images.githubusercontent.com/116535280/222675790-4a2f6eeb-67b4-4eb4-8e9a-4ca5838a2927.png">
报错信息
<img width="1468" alt="b1d56623-2d0b-4ad3-a9ec-c991e252f54d" src="https://user-images.githubusercontent.com/116535280/222675930-ad985cc8-d487-4720-ac11-a14a3af0dc20.png">

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by banmoy** [comment]
@Shan-01 Could you send me the full taskmanager log?

**Comment by banmoy** [comment]
@Shan-01 There is an known problem for connector 1.2.4, and could you  upgrade the connector to the newest 1.2.6 to test your case?
