### ISSUE TITLE
Metadata issues in Trino and Metabase

### ISSUE THREAD

**Issue by leoChaoGlut** [StarRocks/starrocks#1896]
### Real behavior (Required)
- [Metabase ](https://www.metabase.com/)cannot reads the column metadata from StarRocks
![image](https://user-images.githubusercontent.com/13690212/144831071-1c1e5a7b-836d-4922-bd28-b3b3569a4286.png)
- [Trino](https://trino.io/) cannot reads the table metadata from StarRocks
![image](https://user-images.githubusercontent.com/13690212/144831288-6e12ee90-a657-49e9-996e-a26a8cb66547.png)
- No issues in mysql-cli
![image](https://user-images.githubusercontent.com/13690212/144831615-b97291fd-eee8-431d-be4f-08d46920e4d3.png)

### StarRocks version (Required)
 - 1.19.3

**Comment by imay** [comment]
@Astralidea PTAL

**Comment by hiliuxg** [comment]
you can fix it using follow command
`set global enable_groupby_use_output_alias=true;`

**Comment by leoChaoGlut** [comment]
> you can fix it using follow command `set global enable_groupby_use_output_alias=true;`

Thanks, it works for Trino, but Metabase still cannot fetch ColumnMetadata from StarRocks.

**Comment by Astralidea** [comment]
For Metabase, it was because he used some complicated SQL syntax to get metadata and needed to support it.
Like UNSIGNED, CONVERT, this need to write code to support that.
you could see this SQL in fe.audit.log.

**Comment by long2ice** [comment]
It's great if StarRocks  could support Metabase!

**Comment by Astralidea** [comment]
This issue has been resolved. Version 2.4 will support it.
https://github.com/StarRocks/starrocks/pull/11388
