### ISSUE TITLE
1次查询多表插入

### ISSUE THREAD

**Issue by radioliu92** [StarRocks/starrocks#18988]
背景:
在搭建数仓分层时, 我们会用 sql 从1张表中按照一定逻辑进行数据的分表处理, 譬如A逻辑入A表, B逻辑入B表 ....
现有的做法是: 处理每个逻辑都需要读取源表一次, 导致源表会被重复读取

希望:
有没有类似 Hive 那样:
from a
select * where ** insert b
select * where ** insert c
select * where ** insert d
....

**Comment by jaogoy** [comment]
You need a multi-table insert, like:
INSERT
    WHEN <condition1> THEN INTO b VALUES(c1, c2)
    WHEN <condition2> THEN INTO c VALUES(c2, c3)
    WHEN <condition3> THEN INTO d VALUES(c1, c2, c3)
SELECT c1, c2, c3 FROM a;

**Comment by radioliu92** [comment]
> You need a multi-table insert, like: INSERT WHEN THEN INTO b VALUES(c1, c2) WHEN THEN INTO c VALUES(c2, c3) WHEN THEN INTO d VALUES(c1, c2, c3) SELECT c1, c2, c3 FROM a;

是的
