### ISSUE TITLE
when execute the following  sql and be crash

### ISSUE THREAD

**Issue by goodqiang** [StarRocks/starrocks#19001]
### Steps to reproduce the behavior (Required)
1.建表语句
CREATE TABLE `example_table` (
  `k1` tinyint(4) NULL COMMENT "",
  `k2` ARRAY<varchar(255)> NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`k1`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`) BUCKETS 10 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);

 CREATE TABLE `example_table_1` (
  `k1` tinyint(4) NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`k1`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`) BUCKETS 10 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);

插入语句
insert into example_table_1 values(5);

执行：
insert into example_table select *,[] from example_table_1；

### Expected behavior (Required)
期望可以正常执行sql

### Real behavior (Required)
be crash
![image](https://user-images.githubusercontent.com/86873587/223049931-ae85b044-fa7e-48a9-9448-192f57c74331.png)

### StarRocks version (Required)
2.2.9

**Comment by wangruin** [comment]
@xiaoyong-z PTAL

**Comment by meegoo** [comment]
@goodqiang we have already fixed this bug, you can upgrade to version 2.3+
