### ISSUE TITLE
Can not use ROAPI/connector-X support to connect

### ISSUE THREAD

**Issue by ulnit** [StarRocks/starrocks#19055]
### Steps to reproduce the behavior (Required)
Use ROAPI to connect starrocks

### Real behavior (Required)
WARN connectorx::sources::mysql] mysql text prepared statement error: MySqlError { ERROR 1064 (HY000): Unsupported command(COM_STMT_PREPARE) }, switch to limit1 method
Error: Database error: MySqlError { ERROR 1064 (HY000): Unsupported command(COM_STMT_PREPARE) }

### StarRocks version (Required)
2.5.1

**Comment by ztsweet** [comment]
@ulnit  Has the problem been solved？
