### ISSUE TITLE
routine load --where_predicates

### ISSUE THREAD

**Issue by yuanzhangjun** [StarRocks/starrocks#1908]
### Steps to reproduce the behavior (Required)
使用routine load 接入kafka 过滤最近两天数据 
WHERE cdate >= DATE_ADD(CURDATE(),-2)
发现where 里面函数会提前转换为一个固定值，不会因为时间变化而变化，无法达到过滤最近两天的效果
### Expected behavior (Required)
![image](https://user-images.githubusercontent.com/55039122/144956879-b96febba-38a7-4600-9704-d92847da120e.png)

### Real behavior (Required)
where cdate>='2021-12-01',过滤时间不会因为时间变化而变化，无法达到过滤最近两天的效果
### StarRocks version (Required)
 1.19.1 和1.19.3 都试过有这个问题

**Comment by gengjun-git** [comment]
We will fix it in 2.1
