### ISSUE TITLE
starrocks operator error unmatched cluster id

### ISSUE THREAD

**Issue by jacopoberetta95** [StarRocks/starrocks#19152]
I deployed the starrocks operator and starrocks cluster on my k3s cluster.
After some restart i get this error and there is no way to recover the be. What should i do?

"W0303 11:31:23.762603  1705 heartbeat_server.cpp:74] Fail to handle heartbeat: Internal error: Unmatched cluster id cached master info: TMasterInfo(network_address=TNetworkAddress(hostname=, port=0), cluster_id=417525268, epoch=0, token=<null>, backend_ip=<null>, http_port=<null>, heartbeat_flags=<null>, backend_id=<null>) received master info: TMasterInfo(network_address=TNetworkAddress(hostname=starrockscluster-fe-0.fe-domain-search.starrocks.svc.cluster.local, port=9020), cluster_id=958778724, epoch=1, token=5371a2f9-b3e7-48ce-ba5c-f1b0e3e9b184, backend_ip=starrockscluster-be-2.be-domain-search.starrocks.svc.cluster.local, http_port=8030, heartbeat_flags=0, backend_id=10004)"

**Comment by cloverzyy** [comment]
Hi, have you ever solved this problem?

The be proc cannot add. Logs of be.INFO:
Fail to handle heartbeat: Internal error: Unmatched cluster id cached master info: TMasterInfo(network_address=TNetworkAddress(hostname=, port=0), cluster_id=1761943827, epoch=0, token=<null>, backend_ip=<null>, http_port=<null>, heartbeat_flags=<null>, backend_id=<null>, run_mode=<null>) received master info: TMasterInfo(network_address=TNetworkAddress(hostname=10.206.32.15, port=9020), cluster_id=1248103424, epoch=1, token=58f1e84f-180c-4b43-9d4e-c1bb22ba0f65, backend_ip=10.206.32.15, http_port=8030, heartbeat_flags=0, backend_id=10005, run_mode=SHARED_NOTHING)
<img width="921" alt="image" src="https://github.com/StarRocks/starrocks/assets/33452748/56a2f28e-1bf1-46fb-b7ed-44abd8e95606">
