### ISSUE TITLE
[GLIBC VERSION] /lib64/libc.so.6: version `GLIBC_2.14' not found in Pre-compiled binary

### ISSUE THREAD

**Issue by stdpain** [StarRocks/starrocks#192]
This is because the glibc version of your operating system is too old to start `starrocks`.

Starrocks relies on a minimum glibc version of GLIBC_2.17, if your system's glibc is lower than this version, then you need to follow the steps below.

How to check the default glibc version? Do the following:

```
[stdpain@main-machine lib]$ ll /lib64/libc.so.6
lrwxrwxrwx 1 root root 12 Aug 12 10:58 /lib64/libc.so.6 -> libc-2.17.so
```

## Solution 1 (recommend):

download glib-2.17

```
wget http://ftp.gnu.org/pub/gnu/glibc/glibc-2.17.tar.gz
```

> tips:  If you are in the CN region you can use the mirror address https://mirrors.tuna.tsinghua.edu.cn/gnu/glibc/glibc-2.17.tar.gz

```
tar -zxf glibc-2.17.tar.gz
```

```
cd glibc-2.17 && mkdir build && cd build && ../configure --prefix=$HOME/glibc-2.17
```

```
make -j 12 && make install
```

Then you can get the full glibc in your `$HOME/glibc-2.17` directory

Execute `patchelf --version` to check if the command patchelf exists

```
patchelf --set-interpreter $HOME/glibc-2.17/lib/ld-linux-x86-64.so.2 $STARROCKS/be/lib/starrocks_be
```

```
patchelf --set-rpath $HOME/glibc-2.17/lib/ $STARROCKS/be/lib/starrocks_be
```

Then you can deploy happily:

> Note: In a real production environment glibc should be placed under a fixed absolute path, e.g. /opt/, not under $HOME

## Solution 2 (not recommended due to risk):

Upgrade your glibc and install them under /lib64/

**Comment by stdpain** [comment]
这个是因为你的操作系统的glibc版本太老了导致无法启动 `starrocks`

Starrocks 依赖最低的glibc版本是GLIBC_2.17，如果你的系统的glibc低于这个版本，那么你需要按照后面的的步骤进行处理。

如何查看默认的glibc版本? 执行以下操作:

```
[stdpain@main-machine lib]$ ll /lib64/libc.so.6
lrwxrwxrwx 1 root root 12 Aug 12 10:58 /lib64/libc.so.6 -> libc-2.17.so
```

## 解决方案1 (推荐):

download glib-2.17

```
wget http://ftp.gnu.org/pub/gnu/glibc/glibc-2.17.tar.gz
```

> tips: 如果你是在 cn 地区可以使用镜像地址 https://mirrors.tuna.tsinghua.edu.cn/gnu/glibc/glibc-2.17.tar.gz

```
tar -zxf glibc-2.17.tar.gz
```

```
cd glibc-2.17 && mkdir build && ../configure --prefix=$HOME/glibc-2.17
```

```
make -j 12 && make install
```

然后你就可以在你的 `$HOME/glibc-2.17` 目录下得到完整的glibc了

执行 `patchelf --version` 确认patchelf 这个命令是否存在

```
patchelf --set-interpreter $HOME/glibc-2.17/lib/ld-linux-x86-64.so.2 $STARROCKS/be/lib/starrocks_be
```

```
patchelf --set-rpath $HOME/glibc-2.17/lib/ $STARROCKS/be/lib/starrocks_be
```



然后你就可以愉快的进行部署了:

> Note: 实际生产环境中 glibc 应该放在一个固定的绝对路径下，例如 /opt/，而不是 $HOME 下的绝对路径



## 解决方案2 (有风险不推荐):

升级你的glibc，把他们安装在 /lib64/ 下面

**Comment by dirtysalt** [comment]
Have not we linked the static library of glibc? I remember we link static version of glibc.

be/CMakeLists.txt
```
# Add all external dependencies. They should come after the starrocks libs.
# static link gcc's lib
set(STARROCKS_LINK_LIBS ${STARROCKS_LINK_LIBS}
    ${STARROCKS_DEPENDENCIES}
    -static-libstdc++
    -static-libgcc
)
```

**Comment by stdpain** [comment]
@dirtysalt 
static linking of glibc may have some license problems
