### ISSUE TITLE
"SHOW BACKUP FROM <db_name>" still returns entries of all dbs

### ISSUE THREAD

**Issue by fieldsfarmer** [StarRocks/starrocks#19256]
### Steps to reproduce the behavior (Required)
```
CREATE REPOSITORY f_repo
WITH BROKER
ON LOCATION "s3a://<location>"
PROPERTIES(
    "aws.s3.access_key" = "xxx",
    "aws.s3.secret_key" = "xxx",
    "aws.s3.endpoint" = "s3.<region>.amazonaws.com"
);

create database fieldsfarmer1;

CREATE TABLE `fieldsfarmer1`.`ACTIVITY` (`case` BIGINT) PRIMARY KEY(`case`) DISTRIBUTED BY HASH (`case`) PROPERTIES("replication_num" = "1");

create database fieldsfarmer2;

CREATE TABLE `fieldsfarmer2`.`ACTIVITY` (`case` BIGINT) PRIMARY KEY(`case`) DISTRIBUTED BY HASH (`case`) PROPERTIES("replication_num" = "1");

backup snapshot fieldsfarmer1.f1 to f_repo;

backup snapshot fieldsfarmer2.f2 to f_repo;

show backup;

show backup from fieldsfarmer1;
```
### Expected behavior (Required)
`show backup from fieldsfarmer1;` should only returns the backup info of `fieldsfarmer1`, but it still returns both backups (i.e. also the one of `fieldsfarmer2`).

### Real behavior (Required)
`show backup from fieldsfarmer1;` should only returns the backup info of `fieldsfarmer1`.

### StarRocks version (Required)
3.0

**Comment by srlch** [comment]
Could you please provide the commit id?

**Comment by srlch** [comment]
Could you please provide the commit id for FE? `SHOW FRONTENDS;`

**Comment by fieldsfarmer** [comment]
> Could you please provide the commit id for FE? `SHOW FRONTENDS;`

sr-0.sr.default.svc.cluster.local_9010_1670536426001,sr-0.sr.default.svc.cluster.local,9010,8030,9030,9020,LEADER,1167297684,true,true,2318108,2023-03-09 15:12:57,true,"",2023-03-03 17:01:29,PR137-3.0-EF51AE47-926d02f

**Comment by srlch** [comment]
This problem has been fixed in the lastest branch. PR: https://github.com/StarRocks/starrocks/pull/18096
