### ISSUE TITLE
BE build error ：starrocks/be/src/gutil/port.h:21:10: fatal error: butil/compiler_specific.h: No such file or directory

### ISSUE THREAD

**Issue by mklzl** [StarRocks/starrocks#193]
## operation：cd starrocks && sh build.sh 

> ++++ <STARROCKS_HOME> is set. formats/orc/apache-orc is compiled in StarRocks env ++++
-- Build type: RELEASE
-- compiler GNU version 8.3.1
-- SNAPPY_HOME: /usr/local/snappy
-- Found the Snappy header: /installed/snappy.h
-- Found the Snappy library: /usr/local/lib64/libsnappy.a
-- ZLIB_HOME: /installed
-- Found the ZLIB header: /installed/zlib.h
-- Found the ZLIB library: /usr/local/lib/libz.so
-- Found the ZLIB static library: /usr/local/lib/libz.a
-- ZSTD_HOME: /home/doris/starrocks/thirdparty/installed
-- Found the zstd header: /home/doris/starrocks/thirdparty/installed/include/zstd/zstd.h
-- Found the zstd library: /home/doris/starrocks/thirdparty/installed/lib
-- Found the zstd static library: /home/doris/starrocks/thirdparty/installed/lib64/libzstd.a
-- LZ4_HOME: /home/doris/starrocks/thirdparty/installed
-- Found the LZ4 header: /home/doris/starrocks/thirdparty/installed/include/lz4/lz4.h
-- Found the LZ4 library: /home/doris/starrocks/thirdparty/installed/lib
-- PROTOBUF_HOME: /home/doris/starrocks/thirdparty/installed
-- Found the Protobuf headers: /home/doris/starrocks/thirdparty/installed/include
-- Found the Protobuf library: /usr/local/lib/libprotobuf.so
-- Found the Protoc library: /usr/local/lib/libprotoc.so
-- Found the Protoc executable: /home/doris/starrocks/thirdparty/installed/bin/protoc
-- Found the Protobuf static library: /usr/local/lib/libprotobuf.a
-- Found the Protoc static library: /usr/local/lib/libprotoc.a
-- Configuring done
-- Generating done
-- Build files have been written to: /home/doris/starrocks/be
make: *** No targets specified and no makefile found.  Stop.

## and cd be && make

> -- Found the Protobuf headers: /home/doris/starrocks/thirdparty/installed/include
-- Found the Protobuf library: /usr/local/lib/libprotobuf.so
-- Found the Protoc library: /usr/local/lib/libprotoc.so
-- Found the Protoc executable: /home/doris/starrocks/thirdparty/installed/bin/protoc
-- Found the Protobuf static library: /usr/local/lib/libprotobuf.a
-- Found the Protoc static library: /usr/local/lib/libprotoc.a
-- Configuring done
-- Generating done
-- Build files have been written to: /home/doris/starrocks/be
[root@localhost be]# make
[  0%] Building CXX object src/agent/CMakeFiles/Agent.dir/agent_server.cpp.o
In file included from /home/doris/starrocks/be/src/gutil/macros.h:16,
                 from /home/doris/starrocks/be/src/gutil/basictypes.h:9,
                 from /home/doris/starrocks/be/src/gutil/integral_types.h:15,
                 from /home/doris/starrocks/be/src/gutil/int128.h:10,
                 from /home/doris/starrocks/be/src/gutil/strings/numbers.h:24,
                 from /home/doris/starrocks/be/src/runtime/decimal_value.h:35,
                 from /home/doris/starrocks/be/src/runtime/decimalv2_value.h:34,
                 from /home/doris/starrocks/be/src/column/datum.h:8,
                 from /home/doris/starrocks/be/src/column/column.h:9,
                 from /home/doris/starrocks/be/src/exprs/vectorized/runtime_filter_bank.h:7,
                 from /home/doris/starrocks/be/src/exec/exec_node.h:32,
                 from /home/doris/starrocks/be/src/exec/pipeline/fragment_context.h:7,
                 from /home/doris/starrocks/be/src/exec/pipeline/exec_state_reporter.h:7,
                 from /home/doris/starrocks/be/src/exec/pipeline/pipeline_driver_dispatcher.h:8,
                 from /home/doris/starrocks/be/src/runtime/exec_env.h:29,
                 from /home/doris/starrocks/be/src/agent/agent_server.h:30,
                 from /home/doris/starrocks/be/src/agent/agent_server.cpp:22:
/home/doris/starrocks/be/src/gutil/port.h:21:10: fatal error: butil/compiler_specific.h: No such file or directory
 #include "butil/compiler_specific.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/agent/CMakeFiles/Agent.dir/agent_server.cpp.o] Error 1
make[1]: *** [src/agent/CMakeFiles/Agent.dir/all] Error 2
make: *** [all] Error 2

**Comment by stdpain** [comment]
ls /home/doris/starrocks/thirdparty/installed/include/butil/compiler_specific.h confirm whether the file exists

**Comment by mklzl** [comment]
ok

**Comment by mklzl** [comment]
This file does not exist！
find / -name butil . This dir cannot be found
![image](https://user-images.githubusercontent.com/36362816/133034236-d0de75a6-62a6-45e0-ba04-7661a7c23308.png)

**Comment by stdpain** [comment]
It was because thirdparty Components brpc occur a compile error.

try to execute:
```
rm -rf /home/doris/starrocks/thirdparty/src/incubator-brpc-0.9.5
```

and modify your thirdparty/build-thirdparty.sh
move to the last page and only reserve build_brpc (we only need rebuild brpc)
```
 build_brpc

 echo "Finihsed to build all thirdparties"
```

execute :
```
bash thirdparty/build-thirdparty.sh 
```

then check butil/compiler_specific.h

Once the above steps are done, it's time to rebuild Starrocks

**Comment by mklzl** [comment]
rm -rf incubator-brpc-0.9.5 && vi build-thirdparty.sh and  execute : build-thirdparty.sh 
I met such mistakes：
![image](https://user-images.githubusercontent.com/36362816/133038833-6aa6f6da-a8fb-4831-8866-4f409efaba68.png)

**Comment by mklzl** [comment]
After following the above procedure, I encountered this error ：

> [ 93%] Linking CXX shared library ../output/lib/libbrpc.so
[ 93%] Built target brpc-shared
[ 94%] Linking CXX static library ../output/lib/libbrpc.a
[ 94%] Built target brpc-static
[ 94%] Linking CXX executable ../output/bin/protoc-gen-mcpack
../output/lib/libbrpc.so: undefined reference to `snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*)'
../output/lib/libbrpc.so: undefined reference to `snappy::MaxCompressedLength(unsigned long)'
../output/lib/libbrpc.so: undefined reference to `snappy::RawUncompress(char const*, unsigned long, char*)'
../output/lib/libbrpc.so: undefined reference to `snappy::RawCompress(char const*, unsigned long, char*, unsigned long*)'

I tried to fix the problem by removing snappy and recompiling snappy, but it didn't fix the problem

**Comment by stdpain** [comment]
Do not unpack the brpc manually, because we have some patches for the brpc.
please execute
```
rm -rf thirdparty/src/incubator-brpc-0.9.5
```
then execute 
```
bash thirdparty/build-thirdparty.sh 
```
