### ISSUE TITLE
Editable comment/description for a table or database

### ISSUE THREAD

**Issue by mofeiatwork** [StarRocks/starrocks#19323]
[Feature request] Editable comment/description for a table or database #19269

I found that we can set the comment for a table while creating it but we cannot update it anymore once it is created. (tried with ALTER TABLE command but it didn't work)

So, here are mainly 2 feature requests:
- Make the comment of a table editable
- Add the functionality to add a comment on a database too.

**Comment by ZhangChaoming** [comment]
I think this issue has been done in https://github.com/StarRocks/starrocks/pull/21035
