### ISSUE TITLE
Add a new `ANY_VALUE` function

### ISSUE THREAD

**Issue by Gabriel39** [StarRocks/starrocks#1938]
## Feature request

**Is your feature request related to a problem? Please describe.**
I want to implement `any_value` function for Starrocks. In mysql, this function is implemented after MySQL 5.7.5 and you can refer to [MySQL docs](https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html)  for more details. In a nutshell, `any_value` means you can select a unaggregated column in an aggregation statement and a random value in each group will be selected.

**Describe the solution you'd like**
Prototype for `any_value` function should be

`ANY_VALUE(expr: any_data_type)
RETURN value: any_data_type`

`any_value` should be implemented as a kind of aggregation function and should be nondeterministic. Besides, one additional option should be added to control this feature on or off. If turn this knob on, an aggregation statement with an unaggregated column in select list will execute and a random value will be chosen in each group for this unaggregated column while this statement will fail in analyze phase if you turn this knob off.

**Additional context**
Feel free to let me know for this new function about performance, compatibility or any thing you care about.

**Comment by imay** [comment]
@Gabriel39 Firstly, thanks for your contribution.
I think this function is a kind of uncertainty for the user, and thus can give a lot of freedom in the implementation.
So is it possible to return the first value inside the group directly and ignore later values to achieve a better performance?

**Comment by Gabriel39** [comment]
> @Gabriel39 Firstly, thanks for your contribution. I think this function is a kind of uncertainty for the user, and thus can give a lot of freedom in the implementation. So is it possible to return the first value inside the group directly and ignore later values to achieve a better performance?

Good point! Thanks for your suggestion 😄 @imay

**Comment by jaogoy** [comment]
> @Gabriel39 Firstly, thanks for your contribution. I think this function is a kind of uncertainty for the user, and thus can give a lot of freedom in the implementation. So is it possible to return the first value inside the group directly and ignore later values to achieve a better performance?

Which row will be the first row if we use combiner to aggregate rows before shuffle?
So `return the first row` is just for performance while it is not deterministic.

**Comment by imay** [comment]
> Which row will be the first row if we use combiner to aggregate rows before shuffle? So `return the first row` is just for performance while it is not deterministic.
@jaogoy 
Yes, I agree with you on that `the first row` is not deterministic.

@Gabriel39 
Now StarRocks' aggregate function has two stage, update and merge. And the intermediate results will be serialized and shuffled. So I suggest that it's better to keep only one value in intermediate result for better performance.
