### ISSUE TITLE
[Doc] What do you execute to get the query plan

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#19401]
File: [/docs/administration/Query_planning.md](https://docs.starrocks.io/en-us/latest/administration/Query_planning)

I see the results but not the command used to generate the query plan.

**Comment by leoyy0316** [comment]
https://docs.starrocks.io/en-us/latest/sql-reference/sql-statements/Administration/EXPLAIN,  use explain to get the query plain

**Comment by alberttwong** [comment]
https://github.com/StarRocks/starrocks/discussions/29735
