### ISSUE TITLE
Add a button in the query UI to send logs to support

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#19406]
## Enhancement

Add a button in the query UI (http://localhost:8030/query) to send logs to celerdata support

**Comment by Astralidea** [comment]
Hi, What does send logs to celerdata support mean?
Do you mean to add a button to this page, and then click this button to generate a file based on the current page, such as query.csv?

**Comment by alberttwong** [comment]
That could be it...   the idea is make it simple to have a customer send issues/errors for analysis to product support team.
