### ISSUE TITLE
trino connect starrocks success ，but get none table in my created schema

### ISSUE THREAD

**Issue by Linzol** [StarRocks/starrocks#195]
### Steps to reproduce the behavior (Required)
1. i try to connect starrocks use  trino-server-355
2. this is the file content i put into trino catalog directory ，file name is doris.properties 
      connector.name=mysql
      connection-url=jdbc:mysql://10.1.8.143:9030
      connection-user=root
      connection-password=
      case-insensitive-name-matching=true

3. i get this with command “show catalogs”  and  it show my starrocks's catalag “doris”
      trino:dw> show catalogs;
     Catalog   
      ------------
         clickhouse 
         doris      
         hive       
         hive1      
         iceberg    
         jmx        
         kudu       
         oracle     
         system     
        (9 rows)
     Query 20210913_063107_00042_yjd54, FINISHED, 3 nodes
     Splits: 53 total, 53 done (100.00%)
     0.23 [0 rows, 0B] [0 rows/s, 0B/s]

4.  then i get this result with command “show   shcemas from doris ;” 

     trino:dw> show schemas from doris;
       Schema       
       --------------------
        _statistics_       
        dw                 
        example_db         
        information_schema 
        tests              
       (5 rows)

     Query 20210913_063315_00043_yjd54, FINISHED, 4 nodes
     Splits: 53 total, 53 done (100.00%)
     0.25 [5 rows, 72B] [19 rows/s, 287B/s]

5.  when i want to see table ,i  exec this command "show tables from doris.dw" ,but it show nothing。

        trino:dw> show tables from doris.dw;
        Table 
       -------
       (0 rows)

       Query 20210913_063526_00045_yjd54, FINISHED, 4 nodes
       Splits: 53 total, 53 done (100.00%)
       0.26 [0 rows, 0B] [0 rows/s, 0B/s]

6. this is the table when i  use mysql client to exec  commend  “show tables from dw;”
      MySQL [(none)]> show tables from dw;
     +----------------------------------+
     | Tables_in_dw                     |
     +----------------------------------+
     | DICTIONARY_DORIS                 |
     | GLOG_DEPOSIT                     |
     | GLOG_LOGIN                       |
     | GLOG_LOGIN_BITMAP_MID            |
     | GLOG_LOGIN_RATIO                 |
     | GLOG_LOGOUT_AVGTIME              |
     | GLOG_LTV                         |
     | GLOG_M_LOGIN_RT                  |
     | GLOG_M_RETAIN_RT                 |
     | GLOG_NEWLOGIN                    |
     | GLOG_NEWLOGIN_RETAIN             |
     | GLOG_OLNUM                       |
     | ZZ_LOGIN                         |
     | ZZ_LOGIN_T                       |
     ......
    +----------------------------------+
     46 rows in set (0.01 sec)

### Real behavior (Required)
     i'm disturbed why trino can connect starrocks, but cant get  my tables in schema "dw" ,  also cant query table in starrocks.
     before this i update the version from 1.17 to 1.18.2  , detail step is ：
        1）replace  /fe/ bin，/fe/lib， /fe/spark-dpp  this three directory
        2）replace  /be/bin，/be/lib，/be/www  this three directory
### StarRocks version (Required)
  StarRocks-1.18.2

**Comment by imay** [comment]
@Linzol 
Firstly thanks for your issue.
We prefer English, better to create issue in English.

**Comment by Astralidea** [comment]
This because in current starrocks INFORMATION_SCHEMA.TABLES;
for column TABLE_TYPE is BASE TABLE, and trino only filtered TABLE_TYPE in (TABLE, VIEW)

**Comment by imay** [comment]
@Astralidea Could you fix it? If you can, better to assign this issue to yourself?

**Comment by Astralidea** [comment]
> @Astralidea Could you fix it? If you can, better to assign this issue to yourself?

Yes, I think it is not complicated to change. I will submit PR later.

**Comment by Astralidea** [comment]
Hi @Linzol 
you could run following command in starrocks to fix this problem.
```
set global enable_groupby_use_output_alias=true;
```
In order to compatible previous version this variable is false.
this set true to avoid select alias problem.

**Comment by Linzol** [comment]
> Hi @Linzol
> you could run following command in starrocks to fix this problem.
> 
> ```
> set global enable_groupby_use_output_alias=true;
> ```
> 
> In order to compatible previous version this variable is false.
> this set true to avoid select alias problem.

thanks，with the config updated，trino get all tables ！

**Comment by Linzol** [comment]
i have a new problem , with trino connect starrocks.  
trino client can show all tables , but when i try to exec any query like " select * from doris.dw.ff14_character limit 10;  "
i got exception with message 
"trino> select * from doris.dw.ff14_character limit 10;
Query 20210914_132553_00045_yjd54 failed: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: column size not present"

**Comment by Linzol** [comment]
Hi @Astralidea 
what should i do ，if  i want use the fixed code ?

**Comment by Astralidea** [comment]
> Hi @Astralidea
> what should i do ，if i want use the fixed code ?

you may better waiting for next release.
or you could compile master version after merge, but it is may not stable version and hard to compile.

**Comment by Linzol** [comment]
ok，i get，thanks
