### ISSUE TITLE
isnan need to be supported

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#19513]
## Feature request

for double data type, it will be better to have a function isnan. 

### description
Tests whether a value is equal to the special value "NaN", signifying "not a number".

### syntax
```
isnan(exp)
```
in which, exp represents an expression that evaluates to a numeric, and returns a boolean.

### examples
```
SELECT isnan(cast('NaN' as double)); 
true
SELECT isnan(10); 
false
```

**Comment by kateshaowanjou** [comment]
@Tianpingan Can you leave a comment here so I can assign this one to you? :)

**Comment by Tianpingan** [comment]
here

**Comment by Tianpingan** [comment]
> @Tianpingan Can you leave a comment here so I can assign this one to you? :)

here~
