### ISSUE TITLE
[function] last_day

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#19548]
## Feature request

as mentioned in #15385, last_day need to be supported. However last day can be used in month/quarter/year. So I think it's better to support this feature flexibly.

here is my proposal:

### description
Returns the last day of the specified date part for a date or datetime.

### syntax
```
LAST_DAY ( <date_or_datetime_expr> , [<date_part>])
```
in which, 
 `date_or_datetime_expr` is a date or datetime expression
`date_part` is an optional parameter. can be `month`, `quarter`,`year`, default to `month`. 
the return value is always a date.

**Comment by vendanner** [comment]
here
