### ISSUE TITLE
[function]next_day/previous_day need to be supported.

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#19553]
## Feature request

it is necessary for user to check next mon/tue/wed... day. here is my proposal:

### description

Returns the date of the first specified DOW (day of week) that occurs after the input date.

### syntax

```
NEXT_DAY( <date_or_datetime_expr> , <dow_string> )
```
in which, 
`date_or_datetime_expr` can be date or datetime type
`dow_string` specifies the day of week.
Validvalues include a number of abbreviations:
Sunday, Su, Sun
Monday, Mo, Mon
Tuesday, Tu, Tue
Wednesday, We, Wed
Thursday, Th, Thu
Friday,  Fr, Fri
Saturday,  Sa, Sat

and return a date.

**Comment by wangsimo0** [comment]
and the previous day is very similar to this, that returns the date of the first specified DOW (day of week) that occurs before the input date.

**Comment by mlimwxxnn** [comment]
Hi @wangsimo0 , Could you please assign next_day and previous_day  to me? thx!

**Comment by mlimwxxnn** [comment]
Hi @kateshaowanjou , Could you please assign `previous_day` to me? thx!

**Comment by kateshaowanjou** [comment]
@mlimwxxnn Wow you are good！👍🏻👍🏻
