### ISSUE TITLE
Add meta for partial rowset

### ISSUE THREAD

**Issue by decster** [StarRocks/starrocks#1956]

**Comment by jaogoy** [comment]
Suggest to add more description

**Comment by decster** [comment]
Add some txn semantic information bind to a written partial rowset, so when committing this txn, extra operations can be performed according to this semantic information,  i.e.

   1. partial update txn only provide and update a subset of columns,
      so it may add info about updated columns, whether to insert new
      rows if the old row doesn't exist, and default values, etc.
   2. conditional update txn may add some meta to describe the condition
   3. more general read-write txn may add complex expressions
