### ISSUE TITLE
[Docs] Deploy FE Cluster with High Availability.   What does a leader really do?

### ISSUE THREAD

**Issue by ghost** [StarRocks/starrocks#19589]
File: [/docs/administration/Deployment.md](https://docs.starrocks.io/en-us/latest/administration/Deployment)

Need docs to say why a FE leader is important.   This page doesn't list it.   Needs to be linked to https://docs.starrocks.io/en-us/latest/introduction/Architecture#fe-and-be

**Comment by EsoragotoSpirit** [comment]
fixed
