### ISSUE TITLE
[function]regexp_instr

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#19616]
## Feature request

as mentioned in #15385, we need a function to search for the pattern and return its index. However, the regexp expression is more flexible, so we better support this function: https://dev.mysql.com/doc/refman/8.0/en/regexp.html#function_regexp-instr

**Comment by wangsimo0** [comment]
Also, because `like` in sr is vectorized, is faster than `regex`, so it's better to support a `like_instr` as well so we can provide better performance in some cases.

**Comment by blanklin030** [comment]
@wangsimo0 could you please assign this issue to me? thank you!

**Comment by kateshaowanjou** [comment]
@blanklin030 sorry we missed your message, now it's assigned to you. Do you still want to work on it?🙏🏻

**Comment by blanklin030** [comment]
@kateshaowanjou yep, i want to work on it, please assign this issue to me, thank you!

**Comment by liuzhixing1006** [comment]
@wangsimo0 could you please assign this issue to me? I wanna try,  thank you!

**Comment by liuzhixing1006** [comment]
@kateshaowanjou Hi kate, could you please assign this issue to me?

**Comment by liuzhixing1006** [comment]
#36958
