### ISSUE TITLE
starrocks be metrics, resource_group memory inuse value is negative

### ISSUE THREAD

**Issue by mateng0915** [StarRocks/starrocks#19625]
### Steps to reproduce the behavior (Required)
![image](https://user-images.githubusercontent.com/26053753/225535009-62b50d78-6f9c-4c9e-b125-9371dd7149ce.png)

 Our grafana dashboard shows this metrics value is negative
this is for get the user resource group memory inuse

this is the  resource group create stmt

![image](https://user-images.githubusercontent.com/26053753/225535294-80dd77f1-6e02-4b52-bd44-5cc90725f399.png)

### StarRocks version (Required)
2.5.1

**Comment by mateng0915** [comment]
> How do you calculate the interval value of `resource_group_mem_inuse_bytes` in Grafana? delta, mean, or something else? @mateng0915

Here  is calculate method
![image](https://user-images.githubusercontent.com/26053753/225806359-db028d64-ae3f-47f3-a932-fa8c405dda2e.png)

**Comment by mateng0915** [comment]
> How do you calculate the interval value of `resource_group_mem_inuse_bytes` in Grafana? delta, mean, or something else? @mateng0915

Here is the detail about grafana setting
![image](https://user-images.githubusercontent.com/26053753/225806562-3604c6ff-113e-433d-b479-9b61e15e997c.png)

**Comment by ZiheLiu** [comment]
> > How do you calculate the interval value of `resource_group_mem_inuse_bytes` in Grafana? delta, mean, or something else? @mateng0915
> 
> Here is the detail about grafana setting ![image](https://user-images.githubusercontent.com/26053753/225806562-3604c6ff-113e-433d-b479-9b61e15e997c.png)

This grafana setting cannot indicates the calculation type of the interval values.

**Comment by ZiheLiu** [comment]
OK, We would troubleshoot this ASAP.

**Comment by mateng0915** [comment]
> OK, We would troubleshoot this ASAP.
Thx

**Comment by mateng0915** [comment]
@ZiheLiu 
![image](https://user-images.githubusercontent.com/26053753/227881395-861f88bc-dd39-4e4e-8075-f4914cb7dace.png)
We keep monitor this value, it turns out this negative value dost not related to Grafana , The metrics is negative itself

**Comment by mateng0915** [comment]
PIN
