### ISSUE TITLE
window function feature request

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#19632]
as mentioned in issue #13021 and #16340, we have several window functions that not supported yet. And this issue is to summarize all the related functions and to discuss about their design.

- [ ] STDDEV_SAMP
- [ ] VAR_SAMP
- [ ] CUME_DIST
- [ ] NTH_VALUE
- [ ] PERCENT_RANK
- [ ] MEDIAN

**Comment by wangsimo0** [comment]
# CUME_DIST

For CUME_DIST,  here is the standard definition
> If CUME_DIST is specified, then the relative rank of a row R is defined as NP/NR, where NP is defined to be the number of rows preceding or peer with R in the window ordering of the window partition of R and NR is defined to be the number of rows in the window partition of R. 

For CUME_DIST there is no other parameters needed. And also it is pretty clear in MySQL. https://dev.mysql.com/doc/refman/8.0/en/window-function-descriptions.html#function_cume-dist

```
mysql> SELECT
         val,
         ROW_NUMBER()   OVER w AS 'row_number',
         CUME_DIST()    OVER w AS 'cume_dist',
         PERCENT_RANK() OVER w AS 'percent_rank'
       FROM numbers
       WINDOW w AS (ORDER BY val);
+------+------------+--------------------+--------------+
| val  | row_number | cume_dist          | percent_rank |
+------+------------+--------------------+--------------+
|    1 |          1 | 0.2222222222222222 |            0 |
|    1 |          2 | 0.2222222222222222 |            0 |
|    2 |          3 | 0.3333333333333333 |         0.25 |
|    3 |          4 | 0.6666666666666666 |        0.375 |
|    3 |          5 | 0.6666666666666666 |        0.375 |
|    3 |          6 | 0.6666666666666666 |        0.375 |
|    4 |          7 | 0.8888888888888888 |         0.75 |
|    4 |          8 | 0.8888888888888888 |         0.75 |
|    5 |          9 |                  1 |            1 |
+------+------------+--------------------+--------------+
```

**Comment by wangsimo0** [comment]
# NTH_VALUE

For nth_value, here is the standard syntax
```
  NTH_VALUE ( <value expression>, <nth row>)
      [ FROM {FIRST | LAST} ] [{ IGNORE | RESPECT } NULLS ]
      OVER ([PARTITION BY] ORDER BY)
```

there are two necessary parameters. 

## 1. from first/last (optional)
this defines the direction is whether from the beginning or the ending of the ordered list. If this is not specified, the default is first.

for example: 

```
create table windowtest (col1 int, col2 int);
insert into windowtest values (1,11),(1,12),(1,13),(2,21),(2,22),(2,23);
```

```
 select * from windowtest;
+------+------+
| col1 | col2 |
+------+------+
|    1 |   11 |
|    1 |   12 |
|    1 |   13 |
|    2 |   21 |
|    2 |   22 |
|    2 |   23 |
+------+------+
```

```
SELECT
    col1,
    NTH_VALUE(col2, 1) OVER (PARTITION BY col1 ORDER BY col2) AS col2
FROM windowtest;

+------+------+
| col1 | col2 |
+------+------+
|    1 |   11 |
|    1 |   11 |
|    1 |   11 |
|    2 |   21 |
|    2 |   21 |
|    2 |   21 |
+------+------+

SELECT
    col1,
    NTH_VALUE(col2, 1) FROM LAST OVER (PARTITION BY col1 ORDER BY col2) AS col2
FROM windowtest;

+------+------+
| col1 | col2 |
+------+------+
|    1 |   13 |
|    1 |   13 |
|    1 |   13 |
|    2 |   23 |
|    2 |   23 |
|    2 |   23 |
+------+------+

```

## 2. ignore/respect nulls
this is a more common parameter. The default is respect nulls/

for example

```
+------+------+
| col1 | col2 |
+------+------+
|    1 |   11 |
|    1 |   12 |
|    1 |   null|
|    2 |   21 |
|    2 |   22 |
|    2 |   23 |
+------+------+

SELECT
    col1,
    NTH_VALUE(col2, 1) FROM LAST RESPECT NULLS OVER (PARTITION BY col1 ORDER BY col2) AS col2
FROM windowtest;

+------+------+
| col1 | col2 |
+------+------+
|    1 |   null |
|    1 |   null |
|    1 |   null |
|    2 |   23 |
|    2 |   23 |
|    2 |   23 |
+------+------+

SELECT
    col1,
    NTH_VALUE(col2, 1) FROM LAST IGNORE NULLS OVER (PARTITION BY col1 ORDER BY col2) AS col2
FROM windowtest;

+------+------+
| col1 | col2 |
+------+------+
|    1 |   12 |
|    1 |   12 |
|    1 |   12 |
|    2 |   23 |
|    2 |   23 |
|    2 |   23 |
+------+------+
```

## other notice

```
<nth value function> ::=
  NTH_VALUE ( <value expression>, <nth row>)
      [ FROM {FIRST | LAST} ] [{ IGNORE | RESPECT } NULLS ]
```

1. the `nth_row` must be positive integer.
2. if the `nth_row` is bigger than count(value), returns null. like in the example above

```
SELECT
    col2,
    NTH_VALUE(col2, 5) OVER (PARTITION BY col1 ORDER BY col2) AS col2
FROM windowtest;

+------+------+
| col1 | col2 |
+------+------+
|    1 |   null |
|    1 |   null |
|    1 |   null |
|    2 |   null |
|    2 |   null |
|    2 |   null |
+------+------+
```

3. partition by is optional. order by is compulsive.

**Comment by wangsimo0** [comment]
# median

Actually the agg function and window function are both needed.

```
MEDIAN( <expr> )
MEDIAN( <expr> ) OVER ( [ PARTITION BY <expr2> ] )
```

Although sr doesn't have median function ,but sr do have the `percentile_cont` function. `medium(exp)` is like `percentile_cont(exp, 0.5)`.

https://docs.starrocks.io/en-us/latest/sql-reference/sql-functions/aggregate-functions/percentile_cont

**Comment by wangsimo0** [comment]
# stddev_samp and var_samp

sr already has the agg function. 
https://docs.starrocks.io/en-us/latest/sql-reference/sql-functions/aggregate-functions/stddev_samp
https://docs.starrocks.io/en-us/latest/sql-reference/sql-functions/aggregate-functions/var_samp

**Comment by wangsimo0** [comment]
## COUNT(DISTINCT)

sr already has the count window function, still need a count(distinct)

**Comment by kateshaowanjou** [comment]
@ylcq Can you make a comment here？So I can assign median to you.

**Comment by ylcq** [comment]
Yes, I would take this

**Comment by byrantwithyou** [comment]
Hi, @kateshaowanjou I want to take the NTH_VALUE issue. Could you assign it to me?

**Comment by kateshaowanjou** [comment]
@ylcq Hi buddy, are you still working on this issue？ If you have any questions, feel free to join WeChat for discussion: https://ma3you.com/articles_qrcode_show/b12e90J.png?le_time=220907203008013206
