### ISSUE TITLE
Query hive external table: ERROR 1064 (HY000): com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: com/amazonaws/auth/AWSCredentialsProvider

### ISSUE THREAD

**Issue by Alxe1** [StarRocks/starrocks#19648]
### Steps to reproduce the behavior (Required)
1. 
```
CREATE EXTERNAL RESOURCE "hive_resource"
PROPERTIES (
  "type" = "hive",
  "hive.metastore.uris" = "thrift://ip:9083"
);


create external table hive_tbl (
eventid bigint(11),
eventname varchar(100),
eventtime bigint(20),
userid bigint(11),
custom string,
dt bigint(11)
)
engine = hive 
PROPERTIES (
	 "resource" = "hive_resource",
    "database" = "default",
    "table" = "json_copy",
    "hive.metastore.uris" = "thrift://ip:9083"
);
```

2.
```
select * from hive_tbl;
```
In this step, it raised an error: `ERROR 1064 (HY000): com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: com/amazonaws/auth/AWSCredentialsProvider`

My hive storage is in S3. and I also tested it using hdfs storage, the error still happend.
And I use Amazon ec2.

### Expected behavior (Required)
Can query data without error.

### StarRocks version (Required)
2.3.9 895425a

**Comment by imay** [comment]
@Alxe1 could you upgrade your cluster to version 2.5, then you can query Hive data by creating hive catalog

**Comment by Alxe1** [comment]
> @Alxe1 could you upgrade your cluster to version 2.5, then you can query Hive data by creating hive catalog

Yes, I can, but is there any solutions that can solve this problem using version 2.3?
