### ISSUE TITLE
Use group by to return multiple records

### ISSUE THREAD

**Issue by Shan-01** [StarRocks/starrocks#19640]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE 
`CREATE TABLE `testtable` (
  `history_type` tinyint(4) NOT NULL COMMENT "",
  `history_id` int(11) NOT NULL COMMENT "",
  `history_time` datetime NOT NULL COMMENT "",
  `history_category` varchar(120) NOT NULL COMMENT "",
  `created_by` varchar(10) NOT NULL COMMENT "",
  `created_time` datetime NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`history_type`, `history_id`, `history_time`, `history_category`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`history_type`) BUCKETS 10
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "true",
"compression" = "LZ4"
);`
2. INSERT INTO 
`INSERT INTO testtable (history_type, history_id, history_time, history_category, created_by, created_time) VALUES ('7', '162', '2018-12-31 00:00:00', 'aaaa','yliu68', '2023-02-07 18:44:14'),
('7', '162', '2019-12-31 00:00:00', 'bbbb', 'yliu68', '2023-02-07 18:44:14'),
('7', '162', '2020-12-31 00:00:00', 'cccc', 'yliu68', '2023-02-07 18:44:14'),
('7', '162', '2021-12-31 00:00:00', 'dddd', 'yliu68', '2023-02-07 18:44:14'),
('7', '162', '2022-12-31 00:00:00', 'eeee', 'yliu68', '2023-02-07 18:44:14'),
('7', '162', '2022-12-31 00:00:00', 'ffff', 'yliu68', '2023-02-23 15:29:47'),
('10', '162', '2023-12-31 00:00:00', 'gggg', 'hwu16', '2023-02-20 09:53:11'),
('10', '162', '2023-12-31 00:00:00', 'hhhh', 'hwan2', '2023-02-20 16:26:06'),
('10', '162', '2023-12-31 00:00:00', 'iiii', 'yma4', '2023-02-20 18:11:19'),
('10', '162', '2023-12-31 00:00:00', 'jjjj', 'yma4', '2023-02-20 18:16:31');`
3. SELECT  
starrocks version:2.5.2
![image](https://user-images.githubusercontent.com/116535280/225567245-542b3bbc-c992-49b5-af21-ed83d0b5be25.png)
`SELECT history_id AS supplier_id FROM (SELECT history_id,history_time,rank () over (PARTITION BY history_id,history_time ORDER BY created_time DESC) AS rk FROM testtable WHERE history_type = 7 AND history_id = 162) temp WHERE temp.rk = 1 GROUP BY history_id;`
![image](https://user-images.githubusercontent.com/116535280/225565386-93caf395-8a82-4d95-a13a-b0e58a535a10.png)
`SELECT history_id AS supplier_id FROM (SELECT history_id,history_time,rank () over (PARTITION BY history_id,history_time ORDER BY created_time DESC) AS rk FROM testtable WHERE history_type = 7 AND history_id = 162) temp GROUP BY history_id;`
![image](https://user-images.githubusercontent.com/116535280/225565490-8119b926-195b-451c-ae76-267928264449.png)

starrocks version:2.5.3
![image](https://user-images.githubusercontent.com/116535280/225566229-a2aa43b4-23a9-4bbe-a307-8d8bb4774f02.png)
`SELECT history_id AS supplier_id FROM (SELECT history_id,history_time,rank () over (PARTITION BY history_id,history_time ORDER BY created_time DESC) AS rk FROM testtable WHERE history_type = 7 AND history_id = 162) temp WHERE temp.rk = 1 GROUP BY history_id;`
![image](https://user-images.githubusercontent.com/116535280/225566647-d81259cd-5b33-48b7-9fc6-66d7a6d55c24.png)
`SELECT history_id AS supplier_id FROM (SELECT history_id,history_time,rank () over (PARTITION BY history_id,history_time ORDER BY created_time DESC) AS rk FROM testtable WHERE history_type = 7 AND history_id = 162) temp GROUP BY history_id;`
![image](https://user-images.githubusercontent.com/116535280/225567505-2abfae7b-fc61-49c1-90e0-9f4bc69097bb.png)

starrocks version:2.3.10
![image](https://user-images.githubusercontent.com/116535280/225567761-9f3c77fc-f9ef-4e3d-a1a4-d7cdbbb65973.png)
`SELECT history_id AS supplier_id FROM (SELECT history_id,history_time,rank () over (PARTITION BY history_id,history_time ORDER BY created_time DESC) AS rk FROM testtable WHERE history_type = 7 AND history_id = 162) temp WHERE temp.rk = 1 GROUP BY history_id;`
![image](https://user-images.githubusercontent.com/116535280/225567861-da97c1b6-b92b-4ae1-93f8-20a99b895521.png)
`SELECT history_id AS supplier_id FROM (SELECT history_id,history_time,rank () over (PARTITION BY history_id,history_time ORDER BY created_time DESC) AS rk FROM testtable WHERE history_type = 7 AND history_id = 162) temp GROUP BY history_id;`
![image](https://user-images.githubusercontent.com/116535280/225568052-1da2d926-6406-43de-8446-965239383d5c.png)

When WHERE temp.rk=1 is added, multiple results may be returned

**Comment by ZiheLiu** [comment]
Fixed by #19690.
