### ISSUE TITLE
[function] array_subscript

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#19660]
although starrocks already have the array_generate in the latest version, which generate an array using steps, it's better to have a function to simplify the process to generate an array's subscript. By using array_generate, you can achieve this by array_generate(1, array_length(arr),1)

## syntax

```
array_subscript(arr)
```

in which, 
the arr can be any type of array, including array<array<>>. The function will return the subscript of the array.

## examples

```
select array_subscript([2,5,3,7])
[1,2,3,4]

select array_subscript([[1,2],[0,3],[4,7]]);
[1,2,3]

```

**Comment by lqkkkkk** [comment]
Hi @kateshaowanjou , can you assign function-array_subscript  to me？ I will make it, Thank you.

**Comment by kateshaowanjou** [comment]
@lqkkkkk  no worries！
