### ISSUE TITLE
`auto_refresh_partitions_limit` not work when refresh mv first times

### ISSUE THREAD

**Issue by mchades** [StarRocks/starrocks#19759]
### Steps to reproduce the behavior (Required)

materialized view parititon is empty before the first refresh, so it will refresh all partitions of materialized view when the first refresh, it is not consistent with the meaning of  `auto_refresh_partitions_limit`  in doc.

### Expected behavior (Required)
Only refresh `auto_refresh_partitions_limit`  partitions in the first refresh too.
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.5.3

**Comment by Youngwb** [comment]
This has already fixed, refer to https://github.com/StarRocks/starrocks/pull/19494, and it will relase in 2.5.4
