### ISSUE TITLE
select from Hive external table ,be crash

### ISSUE THREAD

**Issue by dq1201** [StarRocks/starrocks#1984]
hive外表建完后，读取数据时，be直接挂掉，报错1064 `- fail to connect hdfs namenode, name=oss://ssports-bigdata-dw/, err=error=Error(255): Unknown error 255, root_cause=UnsupportedFileSystemException: No FileSystem for scheme "oss", Time: 6.286000s`
be.out.log内容如下
![image](https://user-images.githubusercontent.com/90668098/145327835-b8a44aea-f461-46a8-8a3b-59eda89928f7.png)

**Comment by miomiocat** [comment]
这个包是自己编译的么？

**Comment by dq1201** [comment]
不是自己编译的，直接下载的官方安装包

**Comment by miomiocat** [comment]
> 不是自己编译的，直接下载的官方安装包

@dq1201 下载的是哪个版本的呢？

**Comment by dq1201** [comment]
SE-1.18.2

**Comment by miomiocat** [comment]
可以先手动下载 https://repo1.maven.org/maven2/commons-lang/commons-lang/2.6/commons-lang-2.6.jar 放到 be/lib/hadoop/hdfs下，然后重启be解决。starrocks使用的oss sdk近期会修改一下。
