### ISSUE TITLE
Avoid loading unneeded column indexes

### ISSUE THREAD

**Issue by sduzh** [StarRocks/starrocks#199]
## Enhancement

In the current implementation of StarRocks,  all indexes of a column will be loaded from the disk into memory the first time you access it:
https://github.com/StarRocks/starrocks/blob/2f480565b456e71a32a5ec14df65a1c6ffba9cd1/be/src/storage/rowset/segment_v2/column_reader.cpp#L670

However, these indexes are usually only used when there are some pushdown predicates on the column, so many times these loads may not provide any benefit, but rather take up additional resources.

**Comment by GOGOYAO** [comment]
If possible, assign this issue to me.
