### ISSUE TITLE
[Docs] Materialized View section doesn't contain information on Intelligent materialized view

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#19943]
File: [/docs/using_starrocks/Materialized_view.md](https://docs.starrocks.io/en-us/latest/using_starrocks/Materialized_view)

Maybe a section to add and how it works and how to enable it?

**Comment by evelynzhaojie** [comment]
we are considering using another word to replace "intelligent" since this word may incur misunderstanding. i am talking to the product manager
