### ISSUE TITLE
[Docs] Export data section showing the wrong contents.  Showing load spark and flink content.

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#19942]
File: [/docs/unloading/Spark_connector.md](https://docs.starrocks.io/en-us/latest/unloading/Spark_connector)

![Screenshot 2023-03-21 at 10 19 54 AM](https://user-images.githubusercontent.com/749093/226690661-27fc410a-15c1-4d80-b29b-6c953610f557.png)

**Comment by amber-create** [comment]
@alberttwong Hi Albert~ Can I ask what do you mean by "Showing load spark and flink content."?  I can't find any thing about Flink in this article?
