### ISSUE TITLE
[Docs] Confusing statement.  A single-table Materialized Views in StarRocks is a special index for query acceleration. It cannot be queried directly.

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#19944]
File: [/docs/using_starrocks/Materialized_view-single_table.md](https://docs.starrocks.io/en-us/latest/using_starrocks/Materialized_view-single_table)

```
A single-table Materialized Views in StarRocks is a special index for query acceleration. It cannot be queried directly.
```

You say this in the beginning of the article but later on you query the single-table MV directly?   Are you trying to say something else?

**Comment by evelynzhaojie** [comment]
Hi Albert, I ran through this doc and find that all the SELECT...FROM statements are querying data from the base table. I didn't see an example like SELECT...FROM mv. Or I misunderstood you. Maybe we can talk more.

**Comment by EsoragotoSpirit** [comment]
Fixed
