### ISSUE TITLE
Enhance DBeaver mysql compatibility

### ISSUE THREAD

**Issue by Astralidea** [StarRocks/starrocks#19975]
## Enhancement
Materialized view supports show create view -> https://github.com/StarRocks/starrocks/pull/19999
support create database in DBeaver -> https://github.com/StarRocks/starrocks/pull/20101
Implement a fake mysql.user table -> https://github.com/StarRocks/starrocks/pull/22043
Support SHOW PRIVILEGES statement -> https://github.com/StarRocks/starrocks/pull/22083

**Comment by alberttwong** [comment]
I would add, create user too!

**Comment by Astralidea** [comment]
DBeaver has a lot of compatibility issues, here will list all the PRs that have been resolved, I already know the reason for your problem, I will solve it when I have time.
