### ISSUE TITLE
[Docs] support mean and variance functions in materialized views

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#20064]
File: [/docs/sql-reference/sql-statements/data-definition/CREATE MATERIALIZED VIEW.md](https://docs.starrocks.io/en-us/latest/sql-reference/sql-statements/data-definition/CREATE MATERIALIZED VIEW)

Documentation needs to be updated to say that we support mean and variance function in materialized views.

**Comment by alberttwong** [comment]
There may be more.   Need to talk to materialized view expert in engineering.

**Comment by hellolilyliuyi** [comment]
test
