### ISSUE TITLE
materialized_views rows statistical mistake

### ISSUE THREAD

**Issue by TTTTzz** [StarRocks/starrocks#20186]
2.5.2，2.5.0当物化视图的源表发生变更时，information_schema.materialized_views里面的物化视图的table_rows会变成0，show materialized view里面的rows也会变成0，过了2-3min才会更新，如果数据一直变更则统计一直为0

**Comment by ABingHuang** [comment]
这个不是一个bug。目前show materialized view展示的行数信息不是一个实时的数值，而是通过计算节点异步汇报上来的。所以每次物化视图有刷新的时候，这个数值就会发生变更。由于物化视图的刷新是采用insert ovewrite来实现，会先清空物化视图的数据，然后导入新的数据。所以在刚导入完成的时候，物化视图的rows会变为0。等过段时候之后，计算节点会汇报具体的行数，这个时候show materialized view会得到正确的行数。
information_schema.materialized_views看到的单个mv的信息跟show materialized views看到的是一样的，所以也会出现同样的问题。

**Comment by ABingHuang** [comment]
请问，你会基于这个table_rows信息做什么操作吗？

**Comment by mofeiatwork** [comment]
it's as expected according to current design and implementation.
