### ISSUE TITLE
After insert data, the query results are not same during multiple times

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#2023]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS h4;
CREATE DATABASE h4;
USE h4;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DECIMAL128(20, 9)  NULL ,c_0_1 DECIMAL32(7, 0)  NOT NULL ,c_0_2 DECIMAL64(17, 5)  NOT NULL ,c_0_3 DATETIME NULL ,c_0_4 CHAR(1) NULL ,c_0_5 CHAR(1) NOT NULL ,c_0_6 BOOLEAN NOT NULL ,c_0_7 VARCHAR(11) NOT NULL ,c_0_8 LARGEINT NOT NULL ,c_0_9 FLOAT NOT NULL ,c_0_10 DOUBLE NOT NULL ,c_0_11 DOUBLE NOT NULL ,c_0_12 DOUBLE NULL ) DUPLICATE KEY (c_0_0,c_0_1,c_0_2) DISTRIBUTED BY HASH (c_0_0,c_0_2,c_0_1) properties("replication_num"="1") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DECIMAL32(1, 1)  NOT NULL ) UNIQUE KEY (c_1_0) DISTRIBUTED BY HASH (c_1_0) properties("replication_num"="1") ;
INSERT INTO t1 VALUES (0.8), (0.2), (0.7);
INSERT INTO t1 VALUES (0.5);
INSERT INTO t0 VALUES (NULL, 4586379, 8244341.54382, NULL, "", "", true, "T3e", -1921581781, 0.01238120227987849, 0.35307249273774377, 0.7998286483911854, 0.20927796139091182), (10.461551972, 6984288, 3589701.08597, "1970-01-01 08:00:00", "", "", false, "e0", -380998818, 0.7741336262011999, 0.06013976448369551, 0.4557607751138173, 0.6614051281185037), (33.856236157, 2629370, 1512575.50952, "1970-01-01 08:00:00", "", "", true, "5j3ZEx", 1379261162, 0.18810762158523853, 1.986174152E9, 0.7463640902326995, 0.3310617814151906);
INSERT INTO t1 VALUES (0.7), (0.3);
DELETE FROM t0 WHERE c_0_2=9315145.22748 AND c_0_1=1514237 AND c_0_0=19.147741600;
INSERT INTO t0 VALUES (86.282073114, 7431852, 7096912.49690, "1970-01-01 08:00:00", "", "", false, "w", 635436709, 0.05033265125235664, 0.6477519834806055, 0.2477976279047811, 0.48069309207445765);
INSERT INTO t0 VALUES (57.080355761, 2037815, 1912662.46687, "1970-01-01 08:00:00", "", "", false, "89", -400198223, 0.8411662822969908, -1.726314151E9, 0.6724241929448578, NULL), (78.999320108, 641527, 5470247.89763, "1970-01-01 08:00:00", "", "", true, "obC", 1352837194, 0.25456502373376055, 0.32654675366989694, 0.06299241267102751, 0.42910379112482433);
INSERT INTO t1 VALUES (0.8);
INSERT INTO t1 VALUES (0.8);
INSERT INTO t1 VALUES (0.0);
INSERT INTO t0 VALUES (57.875696281, 1706667, 4724457.56030, "1970-01-01 08:00:00", "", "", false, "e5", 240551938, 0.004869162841907526, 1.752295973E9, -1.776175826E9, 0.9027363990187761), (77.419635081, 7787751, 7331098.21160, "1970-01-01 08:00:00", "", "", true, "Xiv", -918656624, 1.986174152E9, -1.291317029E9, 0.1266890904582063, 0.395013209989567), (NULL, 2130559, 5405415.59338, "1970-01-01 08:00:00", "", "", true, "HM", 717009794, 0.17124996171023332, 0.2359113229021561, 1.121839907E9, NULL);
INSERT INTO t0 VALUES (NULL, 5871810, 7473166.13285, "1970-01-01 08:00:00", "", "", false, "x", 393990083, 0.14182234616849965, 0.4934025670728097, 0.9121310889506321, 0.3164441052421969), (90.322589166, 82575, 6186925.12874, "1970-01-01 08:00:00", "", "", false, "", -1579175233, 0.5766664373640866, 3.41551283E8, 0.8219489991614343, 0.28548484794497764);
INSERT INTO t1 VALUES (0.1);
INSERT INTO t1 VALUES (0.3), (0.2), (0.1), (0.7);
INSERT INTO t0 VALUES (52.628736581, 602572, 5322403.54530, "1970-01-01 08:00:00", "", "", false, "r", -640217592, 0.6553398860752409, 0.44967706720097245, 0.7152638890867792, 0.7735463297274345);
INSERT INTO t0 VALUES (NULL, 272961, 2674453.32772, "1970-01-01 08:00:00", "", "", false, "o", -841862030, 0.5466016218055949, 0.47558889426009565, 5.18944103E8, 0.6087561971460421), (32.844301298, 8761939, 8098195.05841, "1970-01-01 08:00:00", "", "", false, "HUs67fL", 850069958, 0.8538656954562887, 0.5069154005211659, -4.62469104E8, 0.06108432522540452), (8.111546364, 9743887, 2091959.70710, "1970-01-01 08:00:00", "", "", false, "xL", 1524096420, 0.5051886775984274, 0.4628492350917571, 1.188380843E9, 0.6077516739377609);
INSERT INTO t0 VALUES (61.294432825, 5551259, 4556060.36807, "1970-01-01 08:00:00", "", "", true, "dJK", 721405329, 0.9064151898444809, 1.259162145E9, 0.8827239475520982, 0.09801905459560811), (37.070242719, 766006, 8285429.73775, "1970-01-01 08:00:00", "", "", false, "zb8U", 109274410, 0.80580623214422, 0.3603942943731313, 0.3073240971767768, 0.42006253542346916);
TRUNCATE TABLE t0;
2. SELECT t1.c_1_0 FROM t1 GROUP BY t1.c_1_0, CAST(CASE  WHEN (t1.c_1_0) IN (0.7, 0.4)  THEN 0.4  WHEN true THEN 0.1  WHEN (NOT (false)) THEN t1.c_1_0 ELSE t1.c_1_0 END AS STRING ) , CASE  WHEN false THEN t1.c_1_0  WHEN true THEN 0.1 ELSE t1.c_1_0 END;
3. the query result is:
mysql> SELECT t1.c_1_0 FROM t1 GROUP BY t1.c_1_0, CAST(CASE  WHEN (t1.c_1_0) IN (0.7, 0.4)  THEN 0.4  WHEN true THEN 0.1  WHEN (NOT (false)) THEN t1.c_1_0 ELSE t1.c_1_0 END AS STRING ) , CASE  WHEN false THEN t1.c_1_0  WHEN true THEN 0.1 ELSE t1.c_1_0 END;
+-------+
| c_1_0 |
+-------+
|   0.1 |
|   0.7 |
|   0.7 |
|   0.1 |
|   0.5 |
|     0 |
|   0.2 |
|   0.8 |
|   0.3 |
+-------+
9 rows in set (0.01 sec)
3.  query after sleep 3-5 mins
4. mysql> SELECT t1.c_1_0 FROM t1 GROUP BY t1.c_1_0, CAST(CASE  WHEN (t1.c_1_0) IN (0.7, 0.4)  THEN 0.4  WHEN true THEN 0.1  WHEN (NOT (false)) THEN t1.c_1_0 ELSE t1.c_1_0 END AS STRING ) , CASE  WHEN false THEN t1.c_1_0  WHEN true THEN 0.1 ELSE t1.c_1_0 END;
+-------+
| c_1_0 |
+-------+
|   0.1 |
|   0.7 |
|   0.5 |
|     0 |
|   0.2 |
|   0.8 |
|   0.3 |
+-------+
7 rows in set (0.02 sec)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.0 release
 - mysql> select current_version();
+---------------------------------+
| current_version()               |
+---------------------------------+
| SQLANCER_BRANCH_RELEASE a4059ab |
+---------------------------------+

**Comment by stdpain** [comment]
It was because a Error Plan
```
```

**Comment by stdpain** [comment]
it was caused by precision lose in case expr
