### ISSUE TITLE
page query return duplicate records

### ISSUE THREAD

**Issue by DeanWanghewei** [StarRocks/starrocks#20262]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE 
CREATE TABLE IF NOT EXISTS page_query_test_1
(
    gaia_cache_dt          DATE   COMMENT '',
    gaia_cache_id          String   COMMENT ',
    id                    bigInt   COMMENT '',
    create_time             DATETIME comment '',
    store_id String COMMENT '',
    pay_start_time     String COMMENT ''
)DUPLICATE KEY (
   gaia_cache_dt
  ,gaia_cache_id
  ,id
  ,create_time
  ,store_id
  ,pay_start_time
)
    COMMENT ""
    PARTITION BY RANGE(gaia_cache_dt)()
    DISTRIBUTED BY HASH(gaia_cache_id,id) BUCKETS 7
    PROPERTIES (
                   "dynamic_partition.enable" = "true",
                   "dynamic_partition.time_unit" = "DAY",
                   "dynamic_partition.start" = "-10",
                   "dynamic_partition.end" = "3",
                   "dynamic_partition.prefix" = "p",
                   "dynamic_partition.buckets" = "7"
               );

2. insert rows with different id 
4. select page data
select id,create_time,store_id,pay_start_time from xq_page_query_test_1 order by id asc limit 1000 offset 60000

### Expected behavior (Required)
 I should get the data that I didn't get, but the returned data has the data returned before。
### Real behavior (Required)
I get duplicate records

### StarRocks version (Required)
 - 2.3.2 dbc89ae

**Comment by jaogoy** [comment]
You are using `Duplicate Key` table table. So, all the rows you load wil be kept the same. If you load data more than one time, you'll get dup rows.
So, you can check it.
I'll be glad to hear your check and feedback.
