### ISSUE TITLE
PublishVersionDaemon.publishVersion got null exception at publishVersionTask.isFinished()

### ISSUE THREAD

**Issue by hoffermei** [StarRocks/starrocks#20277]
### Steps to reproduce the behavior (Required)
create routine load and run(occasionally)

### Expected behavior (Required)
finished transaction normally and recreate new consumer task

### Real behavior (Required)
1. PublishVersionDaemon throw null exception
2. routine load task stuck in committed state

### StarRocks version (Required)
 - 2.2/2.3/2.4/2.5

### Reason analysis
PublishVersionDaemon and DatabaseTransactionMgr run in parallel, both call TransactionState.addPublishVersionTask method.
It may present with a parallel problem:
1. DatabaseTransactionMgr mark TransactionState to be COMMITTED state
2. PublishVersionDaemon get TransactionState with COMMITTED state
3. PublishVersionDaemon call TransactionState.createPublishVersionTask
4. PublishVersionDaemon submit batchTask to be
5. DatabaseTransactionMgr call transactionState.addPublishVersionTask(backendId, `null`), this with update publishVersionTasks map with null value
6. PublishVersionDaemon call transactionState.getPublishVersionTasks and publishVersionTask.isFinished(), got null exception

### Fix method
1. TransactionState add a set/list field with name `totalInvolvedBackends`
2. DatabaseTransactionMgr add backendid to TransactionState.totalInvolvedBackends
3. TransactionState.createPublishVersionTask implement base on totalInvolvedBackends field

**Comment by decster** [comment]
Nice catch! @hoffermei would you like to submit a PR? or I will try to fix it

**Comment by hoffermei** [comment]
> I'll submit a PR this week

**Comment by decster** [comment]
what a coincidence, already did this earlier.

**Comment by decster** [comment]
@hoffermei  hi, do you have the NullPointerException stacktrace? we revised the code, and it seems the race logic you described is protected by `DatabaseTransactionMgr.transactionLock`, so looks like it won't happen?
```
        writeLock();
        try {
            unprotectedCommitTransaction(transactionState, stateListeners);
            txnOperated = true;
        } finally {
            writeUnlock();
            int numPartitions = 0;
            for (Map.Entry<Long, TableCommitInfo> entry : transactionState.getIdToTableCommitInfos().entrySet()) {
                numPartitions += entry.getValue().getIdToPartitionCommitInfo().size();
            }
            txnSpan.setAttribute("num_partition", numPartitions);
            unprotectedCommitSpan.end();
            // after state transform
            transactionState.afterStateTransform(TransactionStatus.COMMITTED, txnOperated, callback, null);
        }


    public List<TransactionState> getCommittedTxnList() {
        readLock();
        try {
            // only send task to committed transaction
            return idToRunningTransactionState.values().stream()
                    .filter(transactionState -> (transactionState.getTransactionStatus() ==
                            TransactionStatus.COMMITTED))
                    .sorted(Comparator.comparing(TransactionState::getCommitTime))
                    .collect(Collectors.toList());
        } finally {
            readUnlock();
        }
    }

```

**Comment by hoffermei** [comment]
> what a coincidence, already did this earlier.

i see, close my pr

**Comment by decster** [comment]
@hoffermei hi, do you have the NullPointerException stacktrace?
