### ISSUE TITLE
带kerberos认证的hive外部表

### ISSUE THREAD

**Issue by peterxiong13** [StarRocks/starrocks#2031]
按照官方文档在SR创建了hive外部表，使用keytab文件认证，能正常访问，有个问题，生产环境中都有权限控制问题，使用kinit -kt命令只能注册一个keytab文件和一个主体，那如何精准控制权限呢？
还有如果hive表是从两个或多个不同的kerberos认证的集群里来的，建立外部表的时候该如何操作？
谢谢！

**Comment by stephen-shelby** [comment]
Hey guys, It's a good question. IMO, most enterprises should have only one KDC. So I guess you are more like asking different users how to use their own principal and keytab for identity authentication. I suggest you could use our new feature which named [external catalog](https://docs.starrocks.com/zh-cn/main/using_starrocks/Manage_data). Our subsequent version will solve the authentication problem of multiple users based on catalog. For example, different users can specify different KeyTab information in the catalog properties. If you are interested in this feature, welcome to join our [slack channel #sig-dla](https://starrocks.slack.com/ssb/redirect) and discuss and implement this function together.
