### ISSUE TITLE
Equivalent sql query results are not the same

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#2033]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS w3;
CREATE DATABASE w3;
USE w3;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 BOOLEAN NOT NULL ,c_0_1 DATE NOT NULL ,c_0_2 CHAR(1) NOT NULL ,c_0_3 DATETIME NOT NULL ,c_0_4 TINYINT NULL ,c_0_5 VARCHAR(1) NOT NULL ,c_0_6 VARCHAR(1) NULL ,c_0_7 DECIMAL32(4, 1)  NULL ,c_0_8 TINYINT NOT NULL ,c_0_9 TINYINT NOT NULL ,c_0_10 LARGEINT NULL ,c_0_11 DECIMAL128(35, 3)  NOT NULL ,c_0_12 DECIMAL64(3, 3)  NULL ,c_0_13 DECIMAL(14, 6)  NOT NULL ,c_0_14 TINYINT NOT NULL ,c_0_15 BOOLEAN NULL ,c_0_16 DECIMAL(20, 6)  NULL ,c_0_17 FLOAT NOT NULL ,c_0_18 DECIMAL64(2, 1)  NOT NULL ) UNIQUE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5,c_0_6,c_0_7,c_0_8,c_0_9,c_0_10) DISTRIBUTED BY HASH (c_0_5,c_0_4) properties("replication_num"="1") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DATETIME NULL ) DUPLICATE KEY (c_1_0) DISTRIBUTED BY HASH (c_1_0) properties("replication_num"="1") ;
CREATE TABLE t2 (c_2_0 DECIMAL64(5, 5)  NOT NULL ,c_2_1 DATETIME NOT NULL ,c_2_2 DECIMAL64(5, 2)  NOT NULL ,c_2_3 DECIMAL32(8, 6)  NOT NULL ,c_2_4 VARCHAR(11) NULL ,c_2_5 DATE NULL ,c_2_6 DECIMAL128(26, 8)  NOT NULL ,c_2_7 SMALLINT NOT NULL ,c_2_8 DECIMAL128(36, 3)  NULL ,c_2_9 DECIMAL(16, 5)  NULL ,c_2_10 HLL HLL_UNION NULL ,c_2_11 FLOAT REPLACE_IF_NOT_NULL NULL ,c_2_12 DECIMAL64(6, 3)  MIN NULL ,c_2_13 DECIMAL(5, 2)  SUM NULL ) AGGREGATE KEY (c_2_0,c_2_1,c_2_2,c_2_3,c_2_4,c_2_5,c_2_6,c_2_7,c_2_8,c_2_9) DISTRIBUTED BY HASH (c_2_0,c_2_7) properties("replication_num"="1") ;
TRUNCATE TABLE t1;
INSERT INTO t0 VALUES (false, "1970-01-01", "", "1970-01-01 08:00:00", 4, "", "", 29.8, 5, 5, 926268140, 96069056005304407203198174713.953, 0.006, 73.175823, 3, true, 26721463.679323, 0.504174371705049, 0.0);
INSERT INTO t2 VALUES (0.00007, "1970-01-01 08:00:00", 6.51, 0.000051, NULL, "1970-01-01", 5006484789.18612951, 6, 939483235706575552988062772385.990, 31962.95538, hll_hash(""), 0.016143334797690034, 0.671, 7.92);
INSERT INTO t0 VALUES (true, "1970-01-01", "", "1970-01-01 08:00:00", 1, "", "", 23.9, 7, 7, 1841724443, 12524364400563064347211596927.245, 0.005, 7.026821, 6, NULL, 6831502.793928, 9.2626814E8, 0.0), (false, "1970-01-01", "", "1970-01-01 08:00:00", 6, "", "", 12.0, 7, 3, -887748510, 88218931551877135914462088162.046, 0.000, 7.845701, 7, false, 74956228.706610, 0.21095396214897222, 0.1);
INSERT INTO t0 VALUES (true, "1970-01-01", "", "1970-01-01 08:00:00", 2, "", "", 50.9, 0, 6, 648077397, 76102708117129183639420648632.700, 0.007, 90.504806, 0, false, 34917449.010398, 0.5393147844452684, 0.8), (true, "1970-01-01", "", "1970-01-01 08:00:00", 6, "", "", 15.1, 5, 5, -382759214, 38836889411322814638252454402.156, 0.006, 14.437155, 5, false, 23400886.308306, 0.2826719897871399, 0.4);
INSERT INTO t2 VALUES (0.00002, "1970-01-01 08:00:00", 0.71, 0.000085, "2U", "1970-01-01", 6565713523.06224420, 3, 988983546034492388322613820739.181, 111109.17033, hll_hash("ertSay41"), 0.0, 0.969, NULL);
INSERT INTO t1 VALUES (NULL);
INSERT INTO t0 VALUES (true, "1970-01-01", "", "1970-01-01 08:00:00", 6, "", "", 57.7, 3, 3, -983744095, 17437578761022951536976915272.170, 0.008, 37.184212, 2, true, 18059138.205537, 0.596084334953695, 0.6);
INSERT INTO t1 VALUES ("1970-01-01 08:00:00"), ("1970-01-01 08:00:00");
INSERT INTO t0 VALUES (true, "1970-01-01", "", "1970-01-01 08:00:00", NULL, "", "", 22.8, 5, 6, 156441121, 94865082693874179391473529077.138, 0.003, 70.286846, 3, true, 40338768.273963, 0.6818153856676621, 0.6), (true, "1970-01-01", "", "1970-01-01 08:00:00", 5, "", "", 91.8, 4, 0, -1189800773, 88785690232406565359762468658.821, 0.000, 19.003974, 1, false, 40613545.169801, 0.37341994988750404, 0.6), (false, "1970-01-01", "", "1970-01-01 08:00:00", 2, "", "", NULL, 0, 4, 648077397, 70656762062606989607797130914.512, NULL, 18.906657, 7, false, 12321750.376662, 0.6437097168013506, 0.0);
DELETE FROM t1 WHERE c_1_0="1969-12-23 06:01:46";
INSERT INTO t0 VALUES (false, "1970-01-01", "", "1970-01-01 08:00:00", 6, "", "", 94.2, 2, 7, 1574670368, 74008913501167596831366607630.364, 0.006, 74.423914, 7, false, NULL, 0.05299449484288621, 0.8);
INSERT INTO t1 VALUES ("1970-01-01 08:00:00"), ("1970-01-01 08:00:00"), ("1970-01-01 08:00:00");
INSERT INTO t2 VALUES (0.00005, "1970-01-01 08:00:00", 2.08, 0.000018, "s", "1970-01-01", 8338921534.76443642, 0, 489441325073130428824290406347.018, NULL, hll_hash("Ih0RSmNM"), NULL, 0.750, 0.21);
INSERT INTO t0 VALUES (true, "1970-01-01", "", "1970-01-01 08:00:00", NULL, "", "", 49.7, 0, 2, 648077397, 6806202395906732776628603942.548, 0.007, 84.951242, 3, true, 89661116.371968, 0.8254656144322028, 0.0), (false, "1970-01-01", "", "1970-01-01 08:00:00", 7, "", "", 21.6, 1, 6, 309441167, 2691849018743654870419565905.415, 0.002, 44.126663, 6, false, 98576154.175478, 0.62499048533053, 0.8), (true, "1970-01-01", "", "1970-01-01 08:00:00", 2, "", "", 63.4, 6, 1, 926268140, 66508422070264194827312226387.938, 0.000, 40.023480, 3, true, 78531212.582865, 0.9922198369311419, 0.6), (false, "1970-01-01", "", "1970-01-01 08:00:00", 2, "", "", NULL, 6, 6, 871311562, 66292679938487714036635938035.537, 0.007, 84.669794, 7, NULL, NULL, 0.0435756814884255, 0.0), (true, "1970-01-01", "", "1970-01-01 08:00:00", 5, "", "", 26.1, 0, 2, 1841724443, 24284849059851841833219104072.050, 0.007, 96.444500, 4, false, 57847223.538318, 1.574670368E9, 0.5);
INSERT INTO t2 VALUES (0.00007, "1970-01-01 08:00:00", 2.26, 0.000082, "c1", "1970-01-01", 2741224362.41796896, 5, 675101412809453904660127292945.613, 39926.56460, hll_hash("IrlUTKGBH"), 3.09441167E8, 0.098, 1.27), (0.00004, "1970-01-01 08:00:00", 0.96, 0.000026, "yl", "1970-01-01", 7460698510.43663587, 12, 313727299566467160595862247951.526, NULL, hll_hash("L"), 0.7015746230934191, 0.340, 3.94);
INSERT INTO t2 VALUES (0.00006, "1970-01-01 08:00:00", 7.14, 0.000084, "Q", "1970-01-01", 9940756431.80242855, 6, 161478084628511160396238826486.570, 661770.41385, hll_hash("1sv"), 0.30010913433605246, 0.186, 4.90);
INSERT INTO t0 VALUES (true, "1970-01-01", "", "1970-01-01 08:00:00", 4, "", "", NULL, 0, 1, 648077397, 29385236487729766178064804251.768, NULL, 76.042093, 2, false, 79910689.424771, 0.9775274234337885, 0.3), (true, "1970-01-01", "", "1970-01-01 08:00:00", 5, "", "", 6.9, 1, 4, 1841724443, 47594910417945847595110396288.653, 0.000, 44.876413, 1, true, 73687120.102122, 0.4035972148831023, 0.6);
2. SELECT t0.c_0_0 FROM t0, t2;
-- cardinality: 102
3. SELECT t0.c_0_0 FROM t0, t2 WHERE  ( ((CAST(t2.c_2_13 AS INT ) )/(((411537937)+(-1161626127)))) ) != ( t0.c_0_14 )  UNION ALL SELECT t0.c_0_0 FROM t0, t2 WHERE (NOT ( ( ((CAST(t2.c_2_13 AS INT ) )/(((411537937)+(-1161626127)))) ) != ( t0.c_0_14 ) )) UNION ALL SELECT t0.c_0_0 FROM t0, t2 WHERE (( ( ((CAST(t2.c_2_13 AS INT ) )/(((411537937)+(-1161626127)))) ) != ( t0.c_0_14 ) ) IS NULL);
-- cardinality: 101

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.0 release
 - mysql> select current_version();
+---------------------------------+
| current_version()               |
+---------------------------------+
| SQLANCER_BRANCH_RELEASE a4059ab |
+---------------------------------+

**Comment by Seaven** [comment]
The bug reason about the `-0` result

```
mysql> select t2.c_2_13, cast(t2.c_2_13 as int) / -1161626127  from t2;
+--------+------------------------------------------+
| c_2_13 | CAST(`t2`.`c_2_13` AS INT) / -1161626127 |
+--------+------------------------------------------+
|   4.90 |                   -3.443448719882314e-09 |
|   0.21 |                                       -0 |
|   1.27 |                   -8.608621799705785e-10 |
|   7.92 |                   -6.026035259794049e-09 |
|   NULL |                                     NULL |
|   3.94 |                  -2.5825865399117354e-09 |
+--------+------------------------------------------+
6 rows in set (0.01 sec)
```
