### ISSUE TITLE
tablet_max_pending_versions changed not effect

### ISSUE THREAD

**Issue by mofei920** [StarRocks/starrocks#20368]
Version: 2.5.3-46bf084
tablet_max_pending_versions set as 10000, I get the error as below after 1615 rows inserted continuously:
ERROR 1064 (HY000) at line 1: Too many versions. tablet_id: 221090, version_count: 1230, limit: 1000, replica_state: 0: be:mi

```sql
CREATE TABLE `insert_select_test` (
  `insert_time` datetime NOT NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(`insert_time`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`insert_time`) BUCKETS 10 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "true",
"compression" = "ZSTD"
);
```

**Comment by jaogoy** [comment]
Your loading is too frequent. Did you load data by `INSERT INTO xx values()`?
