### ISSUE TITLE
Broker Load maps JSON columns to different rows

### ISSUE THREAD

**Issue by gunjdesai** [StarRocks/starrocks#20443]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `events_spark` (
  `address` varchar(42) NOT NULL COMMENT "",
  `block_timestamp` datetime NOT NULL COMMENT "",
  `transaction_index` int(11) NOT NULL COMMENT "",
  `log_index` int(11) NOT NULL COMMENT "",
  `transaction_hash` varchar(66) NULL COMMENT "",
  `block_number` bigint(20) NULL COMMENT "",
  `block_hash` varchar(66) NULL COMMENT "",
  `raw_data` varchar(1048576) NULL COMMENT "",
  `topic0` varchar(66) NULL COMMENT "",
  `topic1` varchar(66) NULL COMMENT "",
  `topic2` varchar(66) NULL COMMENT "",
  `topic3` varchar(66) NULL COMMENT "",
  `event_name` varchar(127) NULL COMMENT "",
  `data` json NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(`address`, `block_timestamp`, `transaction_index`, `log_index`)
COMMENT "OLAP"
PARTITION BY RANGE(`block_timestamp`)
(PARTITION p201506 VALUES [("2015-06-01 00:00:00"), ("2015-07-01 00:00:00")),
PARTITION p201507 VALUES [("2015-07-01 00:00:00"), ("2015-08-01 00:00:00")),
PARTITION p201508 VALUES [("2015-08-01 00:00:00"), ("2015-09-01 00:00:00")),
PARTITION p201509 VALUES [("2015-09-01 00:00:00"), ("2015-10-01 00:00:00")),
PARTITION p201510 VALUES [("2015-10-01 00:00:00"), ("2015-11-01 00:00:00")),
PARTITION p201511 VALUES [("2015-11-01 00:00:00"), ("2015-12-01 00:00:00")),
PARTITION p201512 VALUES [("2015-12-01 00:00:00"), ("2016-01-01 00:00:00")),
PARTITION p201601 VALUES [("2016-01-01 00:00:00"), ("2016-02-01 00:00:00")),
PARTITION p201602 VALUES [("2016-02-01 00:00:00"), ("2016-03-01 00:00:00")),
PARTITION p201603 VALUES [("2016-03-01 00:00:00"), ("2016-04-01 00:00:00")),
PARTITION p201604 VALUES [("2016-04-01 00:00:00"), ("2016-05-01 00:00:00")),
PARTITION p201605 VALUES [("2016-05-01 00:00:00"), ("2016-06-01 00:00:00")),
PARTITION p201606 VALUES [("2016-06-01 00:00:00"), ("2016-07-01 00:00:00")),
PARTITION p201607 VALUES [("2016-07-01 00:00:00"), ("2016-08-01 00:00:00")),
PARTITION p201608 VALUES [("2016-08-01 00:00:00"), ("2016-09-01 00:00:00")),
PARTITION p201609 VALUES [("2016-09-01 00:00:00"), ("2016-10-01 00:00:00")),
PARTITION p201610 VALUES [("2016-10-01 00:00:00"), ("2016-11-01 00:00:00")),
PARTITION p201611 VALUES [("2016-11-01 00:00:00"), ("2016-12-01 00:00:00")),
PARTITION p201612 VALUES [("2016-12-01 00:00:00"), ("2017-01-01 00:00:00")),
PARTITION p201701 VALUES [("2017-01-01 00:00:00"), ("2017-02-01 00:00:00")),
PARTITION p201702 VALUES [("2017-02-01 00:00:00"), ("2017-03-01 00:00:00")),
PARTITION p201703 VALUES [("2017-03-01 00:00:00"), ("2017-04-01 00:00:00")),
PARTITION p201704 VALUES [("2017-04-01 00:00:00"), ("2017-05-01 00:00:00")),
PARTITION p201705 VALUES [("2017-05-01 00:00:00"), ("2017-06-01 00:00:00")),
PARTITION p201706 VALUES [("2017-06-01 00:00:00"), ("2017-07-01 00:00:00")),
PARTITION p201707 VALUES [("2017-07-01 00:00:00"), ("2017-08-01 00:00:00")),
PARTITION p201708 VALUES [("2017-08-01 00:00:00"), ("2017-09-01 00:00:00")),
PARTITION p201709 VALUES [("2017-09-01 00:00:00"), ("2017-10-01 00:00:00")),
PARTITION p201710 VALUES [("2017-10-01 00:00:00"), ("2017-11-01 00:00:00")),
PARTITION p201711 VALUES [("2017-11-01 00:00:00"), ("2017-12-01 00:00:00")),
PARTITION p201712 VALUES [("2017-12-01 00:00:00"), ("2018-01-01 00:00:00")),
PARTITION p201801 VALUES [("2018-01-01 00:00:00"), ("2018-02-01 00:00:00")),
PARTITION p201802 VALUES [("2018-02-01 00:00:00"), ("2018-03-01 00:00:00")),
PARTITION p201803 VALUES [("2018-03-01 00:00:00"), ("2018-04-01 00:00:00")),
PARTITION p201804 VALUES [("2018-04-01 00:00:00"), ("2018-05-01 00:00:00")),
PARTITION p201805 VALUES [("2018-05-01 00:00:00"), ("2018-06-01 00:00:00")),
PARTITION p201806 VALUES [("2018-06-01 00:00:00"), ("2018-07-01 00:00:00")),
PARTITION p201807 VALUES [("2018-07-01 00:00:00"), ("2018-08-01 00:00:00")),
PARTITION p201808 VALUES [("2018-08-01 00:00:00"), ("2018-09-01 00:00:00")),
PARTITION p201809 VALUES [("2018-09-01 00:00:00"), ("2018-10-01 00:00:00")),
PARTITION p201810 VALUES [("2018-10-01 00:00:00"), ("2018-11-01 00:00:00")),
PARTITION p201811 VALUES [("2018-11-01 00:00:00"), ("2018-12-01 00:00:00")),
PARTITION p201812 VALUES [("2018-12-01 00:00:00"), ("2019-01-01 00:00:00")),
PARTITION p201901 VALUES [("2019-01-01 00:00:00"), ("2019-02-01 00:00:00")),
PARTITION p201902 VALUES [("2019-02-01 00:00:00"), ("2019-03-01 00:00:00")),
PARTITION p201903 VALUES [("2019-03-01 00:00:00"), ("2019-04-01 00:00:00")),
PARTITION p201904 VALUES [("2019-04-01 00:00:00"), ("2019-05-01 00:00:00")),
PARTITION p201905 VALUES [("2019-05-01 00:00:00"), ("2019-06-01 00:00:00")),
PARTITION p201906 VALUES [("2019-06-01 00:00:00"), ("2019-07-01 00:00:00")),
PARTITION p201907 VALUES [("2019-07-01 00:00:00"), ("2019-08-01 00:00:00")),
PARTITION p201908 VALUES [("2019-08-01 00:00:00"), ("2019-09-01 00:00:00")),
PARTITION p201909 VALUES [("2019-09-01 00:00:00"), ("2019-10-01 00:00:00")),
PARTITION p201910 VALUES [("2019-10-01 00:00:00"), ("2019-11-01 00:00:00")),
PARTITION p201911 VALUES [("2019-11-01 00:00:00"), ("2019-12-01 00:00:00")),
PARTITION p201912 VALUES [("2019-12-01 00:00:00"), ("2020-01-01 00:00:00")),
PARTITION p202001 VALUES [("2020-01-01 00:00:00"), ("2020-02-01 00:00:00")),
PARTITION p202002 VALUES [("2020-02-01 00:00:00"), ("2020-03-01 00:00:00")),
PARTITION p202003 VALUES [("2020-03-01 00:00:00"), ("2020-04-01 00:00:00")),
PARTITION p202004 VALUES [("2020-04-01 00:00:00"), ("2020-05-01 00:00:00")),
PARTITION p202005 VALUES [("2020-05-01 00:00:00"), ("2020-06-01 00:00:00")),
PARTITION p202006 VALUES [("2020-06-01 00:00:00"), ("2020-07-01 00:00:00")),
PARTITION p202007 VALUES [("2020-07-01 00:00:00"), ("2020-08-01 00:00:00")),
PARTITION p202008 VALUES [("2020-08-01 00:00:00"), ("2020-09-01 00:00:00")),
PARTITION p202009 VALUES [("2020-09-01 00:00:00"), ("2020-10-01 00:00:00")),
PARTITION p202010 VALUES [("2020-10-01 00:00:00"), ("2020-11-01 00:00:00")),
PARTITION p202011 VALUES [("2020-11-01 00:00:00"), ("2020-12-01 00:00:00")),
PARTITION p202012 VALUES [("2020-12-01 00:00:00"), ("2021-01-01 00:00:00")),
PARTITION p202101 VALUES [("2021-01-01 00:00:00"), ("2021-02-01 00:00:00")),
PARTITION p202102 VALUES [("2021-02-01 00:00:00"), ("2021-03-01 00:00:00")),
PARTITION p202103 VALUES [("2021-03-01 00:00:00"), ("2021-04-01 00:00:00")),
PARTITION p202104 VALUES [("2021-04-01 00:00:00"), ("2021-05-01 00:00:00")),
PARTITION p202105 VALUES [("2021-05-01 00:00:00"), ("2021-06-01 00:00:00")),
PARTITION p202106 VALUES [("2021-06-01 00:00:00"), ("2021-07-01 00:00:00")),
PARTITION p202107 VALUES [("2021-07-01 00:00:00"), ("2021-08-01 00:00:00")),
PARTITION p202108 VALUES [("2021-08-01 00:00:00"), ("2021-09-01 00:00:00")),
PARTITION p202109 VALUES [("2021-09-01 00:00:00"), ("2021-10-01 00:00:00")),
PARTITION p202110 VALUES [("2021-10-01 00:00:00"), ("2021-11-01 00:00:00")),
PARTITION p202111 VALUES [("2021-11-01 00:00:00"), ("2021-12-01 00:00:00")),
PARTITION p202112 VALUES [("2021-12-01 00:00:00"), ("2022-01-01 00:00:00")),
PARTITION p202201 VALUES [("2022-01-01 00:00:00"), ("2022-02-01 00:00:00")),
PARTITION p202202 VALUES [("2022-02-01 00:00:00"), ("2022-03-01 00:00:00")),
PARTITION p202203 VALUES [("2022-03-01 00:00:00"), ("2022-04-01 00:00:00")),
PARTITION p202204 VALUES [("2022-04-01 00:00:00"), ("2022-05-01 00:00:00")),
PARTITION p202205 VALUES [("2022-05-01 00:00:00"), ("2022-06-01 00:00:00")),
PARTITION p202206 VALUES [("2022-06-01 00:00:00"), ("2022-07-01 00:00:00")),
PARTITION p202207 VALUES [("2022-07-01 00:00:00"), ("2022-08-01 00:00:00")),
PARTITION p202208 VALUES [("2022-08-01 00:00:00"), ("2022-09-01 00:00:00")),
PARTITION p202209 VALUES [("2022-09-01 00:00:00"), ("2022-10-01 00:00:00")),
PARTITION p202210 VALUES [("2022-10-01 00:00:00"), ("2022-11-01 00:00:00")),
PARTITION p202211 VALUES [("2022-11-01 00:00:00"), ("2022-12-01 00:00:00")),
PARTITION p202212 VALUES [("2022-12-01 00:00:00"), ("2023-01-01 00:00:00")),
PARTITION p202301 VALUES [("2023-01-01 00:00:00"), ("2023-02-01 00:00:00")),
PARTITION p202302 VALUES [("2023-02-01 00:00:00"), ("2023-03-01 00:00:00")),
PARTITION p202303 VALUES [("2023-03-01 00:00:00"), ("2023-04-01 00:00:00")),
PARTITION p202304 VALUES [("2023-04-01 00:00:00"), ("2023-05-01 00:00:00")),
PARTITION p202305 VALUES [("2023-05-01 00:00:00"), ("2023-06-01 00:00:00")),
PARTITION p202306 VALUES [("2023-06-01 00:00:00"), ("2023-07-01 00:00:00")))
DISTRIBUTED BY HASH(`transaction_index`) BUCKETS 10 
PROPERTIES (
"replication_num" = "2",
"bloom_filter_columns" = "topic0, transaction_hash",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "MONTH",
"dynamic_partition.time_zone" = "UTC",
"dynamic_partition.start" = "-2147483648",
"dynamic_partition.end" = "3",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "10",
"dynamic_partition.start_day_of_month" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"compression" = "LZ4"
); 
2. LOAD LABEL ethereum.events_gcs_spark_upload_7
(
DATA INFILE("s3a://__your_file_path__")
INTO TABLE events_spark
FORMAT AS "parquet"
(address, block_timestamp, transaction_index, log_index, transaction_hash, block_number, block_hash, raw_data, event_name, data, topic0, topic1, topic2, topic3)
)
WITH BROKER hdfs_broker
(
    "fs.s3a.access.key" = "__your_access_key__",
    "fs.s3a.secret.key" = "__your_secret_key__",
    "fs.s3a.endpoint" = "storage.googleapis.com"
)
PROPERTIES
(
    "timeout" = "20000",
    "timezone" = "UTC"
);

3. SELECT * FROM events_spark WHERE event_name = 'Transfer' ORDER BY block_timestamp DESC, log_index DESC

### Expected behavior (Required)
```
+------------------------------------------+-------------------+-----------------+---------+------------------------------------------------------------------+------------+------------------------------------------------------------------+------------------------------------------------------------------+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+------------------------------------------------------------------+------------------------------------------------------------------+------------------------------------------------------------------+
|address                                   |block_timestamp    |transaction_index|log_index|transaction_hash                                                  |block_number|block_hash                                                        |raw_data                                                          |event_name|data                                                                                                                                                                                                |topic0                                                            |topic1                                                            |topic2                                                            |topic3                                                            |
+------------------------------------------+-------------------+-----------------+---------+------------------------------------------------------------------+------------+------------------------------------------------------------------+------------------------------------------------------------------+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+------------------------------------------------------------------+------------------------------------------------------------------+------------------------------------------------------------------+
|0x03d1e72765545729a035e909edd9371a405f77fb|2022-01-26 23:56:15|16               |25       |0xa3ba3ee30cba70483f3f08f3bf6f21812f71c9490c35ee583a29fe29cc992cfb|14084319    |0xab28e95a7480da3f285c0b5c30327e570315d9ed4e6fabd0f45b6896284abdbb|0x00000000000000000000000000000000000000000034991ec28ced55a59f3541|Transfer  |{"from": "0xd3660ee5743108ddbbc6eb9dd07a0c325f6921fe", "to": "0xc707e0854da2d72c90a7453f8dc224dd937d7e82", "value": 63587232113002676293154113}                                                     |0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef|0x000000000000000000000000d3660ee5743108ddbbc6eb9dd07a0c325f6921fe|0x000000000000000000000000c707e0854da2d72c90a7453f8dc224dd937d7e82|null                                                              |
|0xf4d2888d29d722226fafa5d9b24f9164c092421e|2022-01-26 23:56:15|14               |20       |0x2fd1b7b18b38c395f1431bd0f4e7a76757f9edfe950a20e11d716b7be6f0a377|14084319    |0xab28e95a7480da3f285c0b5c30327e570315d9ed4e6fabd0f45b6896284abdbb|0x0000000000000000000000000000000000000000000006fc78ad77b7aa7dbcf6|Transfer  |{"from": "0xbcd7254a1d759efa08ec7c3291b2e85c5dcc12ce", "to": "0x465a790b428268196865a3ae2648481ad7e0d3b1", "value": 32991474141878923672822}                                                        |0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef|0x000000000000000000000000bcd7254a1d759efa08ec7c3291b2e85c5dcc12ce|0x000000000000000000000000465a790b428268196865a3ae2648481ad7e0d3b1|null                                                              |
|0xf4d2888d29d722226fafa5d9b24f9164c092421e|2022-01-26 23:56:15|14               |16       |0x2fd1b7b18b38c395f1431bd0f4e7a76757f9edfe950a20e11d716b7be6f0a377|14084319    |0xab28e95a7480da3f285c0b5c30327e570315d9ed4e6fabd0f45b6896284abdbb|0x0000000000000000000000000000000000000000000000211f540ec883ac0000|Transfer  |{"from": "0x0000000000000000000000000000000000000000", "to": "0xfec3069df398faaf689c559151e41fa8036c8203", "value": 611000000000000000000}                                                          |0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef|0x0000000000000000000000000000000000000000000000000000000000000000|0x000000000000000000000000fec3069df398faaf689c559151e41fa8036c8203|null                                                              |
|0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce|2022-01-26 23:52:27|163              |327      |0x07ab065cec018e7ea0355a2fdca1287313bb4fd9f535e2699e5809a8ee478525|14084300    |0x9c8bb4682a0dd9f6590c7c5740381eb47f8690395c921a04c5697c0a9e8048eb|0x0000000000000000000000000000000000000000000341baa7a61a375d658000|Transfer  |{"from": "0x0d7e144ce39f618321c8dc1cf084f739de892805", "to": "0x3d585f6ba5a63a48e62112507012221f5f143ebe", "value": 3937174455000000000000000}                                                      |0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef|0x0000000000000000000000000d7e144ce39f618321c8dc1cf084f739de892805|0x0000000000000000000000003d585f6ba5a63a48e62112507012221f5f143ebe|null                                                              |
|0x4a8b01e437c65fa8612e8b699266c0e0a98ff65c|2022-01-26 23:52:27|160              |291      |0x12676293fdf4af15605561fa7ad787254b1e6eedf0d7e36522ee71c9cd58f5e2|14084300    |0x9c8bb4682a0dd9f6590c7c5740381eb47f8690395c921a04c5697c0a9e8048eb|0x                                                                |Transfer  |{"from": "0xe2f517a291be8116178cd61ade66e3266641b4e9", "to": "0x9ca1971786778085be2fea12304ec48e18d558fb", "tokenId": 2112}                                                                         |0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef|0x000000000000000000000000e2f517a291be8116178cd61ade66e3266641b4e9|0x0000000000000000000000009ca1971786778085be2fea12304ec48e18d558fb|0x0000000000000000000000000000000000000000000000000000000000000840|
|0x4a8b01e437c65fa8612e8b699266c0e0a98ff65c|2022-01-26 23:52:27|160              |288      |0x12676293fdf4af15605561fa7ad787254b1e6eedf0d7e36522ee71c9cd58f5e2|14084300    |0x9c8bb4682a0dd9f6590c7c5740381eb47f8690395c921a04c5697c0a9e8048eb|0x                                                                |Transfer  |{"from": "0x13b17a75ee62170664b6febc18d269370978101d", "to": "0x9ca1971786778085be2fea12304ec48e18d558fb", "tokenId": 2099}                                                                         |0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef|0x00000000000000000000000013b17a75ee62170664b6febc18d269370978101d|0x0000000000000000000000009ca1971786778085be2fea12304ec48e18d558fb|0x0000000000000000000000000000000000000000000000000000000000000833|
|0x63fa29fec10c997851ccd2466dad20e51b17c8af|2022-01-26 23:52:27|154              |278      |0x1f848c88cbd614ab91f88ddc3b1a0b5f7cf19f3c89bf93e5814d29e8eb7bbaae|14084300    |0x9c8bb4682a0dd9f6590c7c5740381eb47f8690395c921a04c5697c0a9e8048eb|0x                                                                |Transfer  |{"from": "0x4cd521a32e083d15d74a0bc0522eb17b84a74fba", "to": "0x7badda0deedcecd5e27e0991824ea5961485f31d", "tokenId": 4048}                                                                         |0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef|0x0000000000000000000000004cd521a32e083d15d74a0bc0522eb17b84a74fba|0x0000000000000000000000007badda0deedcecd5e27e0991824ea5961485f31d|0x0000000000000000000000000000000000000000000000000000000000000fd0|
|0x63fa29fec10c997851ccd2466dad20e51b17c8af|2022-01-26 23:52:27|154              |274      |0x1f848c88cbd614ab91f88ddc3b1a0b5f7cf19f3c89bf93e5814d29e8eb7bbaae|14084300    |0x9c8bb4682a0dd9f6590c7c5740381eb47f8690395c921a04c5697c0a9e8048eb|0x                                                                |Transfer  |{"from": "0x4cd521a32e083d15d74a0bc0522eb17b84a74fba", "to": "0x7badda0deedcecd5e27e0991824ea5961485f31d", "tokenId": 4046}                                                                         |0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef|0x0000000000000000000000004cd521a32e083d15d74a0bc0522eb17b84a74fba|0x0000000000000000000000007badda0deedcecd5e27e0991824ea5961485f31d|0x0000000000000000000000000000000000000000000000000000000000000fce|
|0x7ea3cca10668b8346aec0bf1844a49e995527c8b|2022-01-26 23:52:27|152              |270      |0xba2a0d22a58d6d661db2356397a2a2b30e106d2700c8ff5b1c9497c90ba67d7c|14084300    |0x9c8bb4682a0dd9f6590c7c5740381eb47f8690395c921a04c5697c0a9e8048eb|0x                                                                |Transfer  |{"from": "0x4897d38b0974051d8fa34364e37a5993f4a966a5", "to": "0x8995add99d015ebea94daf9e98fc8c5deecbb67e", "tokenId": 9798}                                                                         |0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef|0x0000000000000000000000004897d38b0974051d8fa34364e37a5993f4a966a5|0x0000000000000000000000008995add99d015ebea94daf9e98fc8c5deecbb67e|0x0000000000000000000000000000000000000000000000000000000000002646|
|0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2|2022-01-26 23:52:27|151              |267      |0x01675a19b8493688f74ff9096fb39fa7d58bd0d703f511f4f0ad46cff79faf9d|14084300    |0x9c8bb4682a0dd9f6590c7c5740381eb47f8690395c921a04c5697c0a9e8048eb|0x00000000000000000000000000000000000000000000000009f42a818f2ff47e|Transfer  |{"from": "0xbcd7254a1d759efa08ec7c3291b2e85c5dcc12ce", "to": "0x873101ad72e69092c7fb9dd6c50378d0a00219d4", "value": 717244976600183934}                                                             |0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef|0x000000000000000000000000bcd7254a1d759efa08ec7c3291b2e85c5dcc12ce|0x000000000000000000000000873101ad72e69092c7fb9dd6c50378d0a00219d4|null                                                             |
```

### Real behavior (Required)

```
address|block_timestamp|transaction_index|log_index|transaction_hash|block_number|block_hash|raw_data|topic0|topic1|topic2|topic3|event_name|data
0x03d1e72765545729a035e909edd9371a405f77fb|2022-01-26 23:56:15|16|25|0xa3ba3ee30cba70483f3f08f3bf6f21812f71c9490c35ee583a29fe29cc992cfb|14084319|0xab28e95a7480da3f285c0b5c30327e570315d9ed4e6fabd0f45b6896284abdbb|0x00000000000000000000000000000000000000000034991ec28ced55a59f3541|0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef|0x000000000000000000000000d3660ee5743108ddbbc6eb9dd07a0c325f6921fe|0x000000000000000000000000c707e0854da2d72c90a7453f8dc224dd937d7e82||Transfer|"{""buyHash"": ""0x0000000000000000000000000000000000000000000000000000000000000000"", ""maker"": ""0x00b7e4266cde6cfa0ed1f966657a7af37a9218ed"", ""metadata"": ""0x0000000000000000000000000000000000000000000000000000000000000000"", ""price"": 350000000000000000, ""sellHash"": ""0x08dac0d4bab994effe09b490c639cb5bb4d1670d4836c8d6450af838522198cc"", ""taker"": ""0x88c15afd7fe91c8292c3543c02a40717222558ec""}"
0xf4d2888d29d722226fafa5d9b24f9164c092421e|2022-01-26 23:56:15|14|20|0x2fd1b7b18b38c395f1431bd0f4e7a76757f9edfe950a20e11d716b7be6f0a377|14084319|0xab28e95a7480da3f285c0b5c30327e570315d9ed4e6fabd0f45b6896284abdbb|0x0000000000000000000000000000000000000000000006fc78ad77b7aa7dbcf6|0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef|0x000000000000000000000000bcd7254a1d759efa08ec7c3291b2e85c5dcc12ce|0x000000000000000000000000465a790b428268196865a3ae2648481ad7e0d3b1||Transfer|"{""buyHash"": ""0x0000000000000000000000000000000000000000000000000000000000000000"", ""maker"": ""0xf1686055e50d269eb3a3809897c200092f7e13c2"", ""metadata"": ""0x0000000000000000000000000000000000000000000000000000000000000000"", ""price"": 249000000000000000, ""sellHash"": ""0xb406ca5c284cf4c5864fc25f37d29747f5683dd108fe58a5becb98c5e690373a"", ""taker"": ""0xd1a38b2c60c7b4f216811e632d770b26f45eb48f""}"
0xf4d2888d29d722226fafa5d9b24f9164c092421e|2022-01-26 23:56:15|14|16|0x2fd1b7b18b38c395f1431bd0f4e7a76757f9edfe950a20e11d716b7be6f0a377|14084319|0xab28e95a7480da3f285c0b5c30327e570315d9ed4e6fabd0f45b6896284abdbb|0x0000000000000000000000000000000000000000000000211f540ec883ac0000|0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef|0x0000000000000000000000000000000000000000000000000000000000000000|0x000000000000000000000000fec3069df398faaf689c559151e41fa8036c8203||Transfer|"{""from"": ""0x5bb2dc94246bb59574e5e8849116aa846bd67c46"", ""to"": ""0xecdb63c30d46e8c86bf1292fa7d4519535b161c3"", ""value"": 988000000}"
0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce|2022-01-26 23:52:27|163|327|0x07ab065cec018e7ea0355a2fdca1287313bb4fd9f535e2699e5809a8ee478525|14084300|0x9c8bb4682a0dd9f6590c7c5740381eb47f8690395c921a04c5697c0a9e8048eb|0x0000000000000000000000000000000000000000000341baa7a61a375d658000|0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef|0x0000000000000000000000000d7e144ce39f618321c8dc1cf084f739de892805|0x0000000000000000000000003d585f6ba5a63a48e62112507012221f5f143ebe||Transfer|"{""buyHash"": ""0x0000000000000000000000000000000000000000000000000000000000000000"", ""maker"": ""0xf8dee5549496b329041207913352b3e31dcc035b"", ""metadata"": ""0x0000000000000000000000000000000000000000000000000000000000000000"", ""price"": 30000000000000000, ""sellHash"": ""0x31c92cb9cb09547ed11e669cdb883d9d1125a495aa4f5c4cd577c99dd5f0a37a"", ""taker"": ""0xde2b48df58eed1be02b72da28d11b5964a51db5b""}"
0x4a8b01e437c65fa8612e8b699266c0e0a98ff65c|2022-01-26 23:52:27|160|291|0x12676293fdf4af15605561fa7ad787254b1e6eedf0d7e36522ee71c9cd58f5e2|14084300|0x9c8bb4682a0dd9f6590c7c5740381eb47f8690395c921a04c5697c0a9e8048eb|0x|0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef|0x000000000000000000000000e2f517a291be8116178cd61ade66e3266641b4e9|0x0000000000000000000000009ca1971786778085be2fea12304ec48e18d558fb|0x0000000000000000000000000000000000000000000000000000000000000840|Transfer|"{""amount0In"": 0, ""amount0Out"": 63310948165, ""amount1In"": 24514525532822260000, ""amount1Out"": 0, ""sender"": ""0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45"", ""to"": ""0xf9e38d9129f297f96af4acb1348f1fc121fe2cdb""}"
0x4a8b01e437c65fa8612e8b699266c0e0a98ff65c|2022-01-26 23:52:27|160|288|0x12676293fdf4af15605561fa7ad787254b1e6eedf0d7e36522ee71c9cd58f5e2|14084300|0x9c8bb4682a0dd9f6590c7c5740381eb47f8690395c921a04c5697c0a9e8048eb|0x|0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef|0x00000000000000000000000013b17a75ee62170664b6febc18d269370978101d|0x0000000000000000000000009ca1971786778085be2fea12304ec48e18d558fb|0x0000000000000000000000000000000000000000000000000000000000000833|Transfer|"{""provider"": ""0xa78ecfbdbe46b31d499a614ed5dfbbaf0b772782"", ""value"": 20000000000000000}"
0x63fa29fec10c997851ccd2466dad20e51b17c8af|2022-01-26 23:52:27|154|278|0x1f848c88cbd614ab91f88ddc3b1a0b5f7cf19f3c89bf93e5814d29e8eb7bbaae|14084300|0x9c8bb4682a0dd9f6590c7c5740381eb47f8690395c921a04c5697c0a9e8048eb|0x|0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef|0x0000000000000000000000004cd521a32e083d15d74a0bc0522eb17b84a74fba|0x0000000000000000000000007badda0deedcecd5e27e0991824ea5961485f31d|0x0000000000000000000000000000000000000000000000000000000000000fd0|Transfer|"{""from"": ""0x0c024705caaa48431e27d4e9d2246b6218e9248b"", ""to"": ""0xf1b243a4b7c1c4d6a2cd2effb8773a44197a7fa0"", ""value"": 1e+20}"
0x63fa29fec10c997851ccd2466dad20e51b17c8af|2022-01-26 23:52:27|154|274|0x1f848c88cbd614ab91f88ddc3b1a0b5f7cf19f3c89bf93e5814d29e8eb7bbaae|14084300|0x9c8bb4682a0dd9f6590c7c5740381eb47f8690395c921a04c5697c0a9e8048eb|0x|0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef|0x0000000000000000000000004cd521a32e083d15d74a0bc0522eb17b84a74fba|0x0000000000000000000000007badda0deedcecd5e27e0991824ea5961485f31d|0x0000000000000000000000000000000000000000000000000000000000000fce|Transfer|"{""from"": ""0x95a9bd206ae52c4ba8eecfc93d18eacdd41c88cc"", ""to"": ""0xfc429c2cdf98fd1ea97a0191b79ebcffcce027ef"", ""value"": 2.2841475470444699e+24}"
0x7ea3cca10668b8346aec0bf1844a49e995527c8b|2022-01-26 23:52:27|152|270|0xba2a0d22a58d6d661db2356397a2a2b30e106d2700c8ff5b1c9497c90ba67d7c|14084300|0x9c8bb4682a0dd9f6590c7c5740381eb47f8690395c921a04c5697c0a9e8048eb|0x|0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef|0x0000000000000000000000004897d38b0974051d8fa34364e37a5993f4a966a5|0x0000000000000000000000008995add99d015ebea94daf9e98fc8c5deecbb67e|0x0000000000000000000000000000000000000000000000000000000000002646|Transfer|"{""from"": ""0x6202ea561ce2c81e48eb54d5833011883ac5e3ec"", ""to"": ""0x84e0877366a4f566ba51bebd1467150294c52efe"", ""value"": 1075000000}"
0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2|2022-01-26 23:52:27|151|267|0x01675a19b8493688f74ff9096fb39fa7d58bd0d703f511f4f0ad46cff79faf9d|14084300|0x9c8bb4682a0dd9f6590c7c5740381eb47f8690395c921a04c5697c0a9e8048eb|0x00000000000000000000000000000000000000000000000009f42a818f2ff47e|0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef|0x000000000000000000000000bcd7254a1d759efa08ec7c3291b2e85c5dcc12ce|0x000000000000000000000000873101ad72e69092c7fb9dd6c50378d0a00219d4||Transfer|"{""from"": ""0x4d96369002fc5b9687ee924d458a7e5baa5df34e"", ""to"": ""0xd7c09e006a2891880331b0f6224071c1e890a98a"", ""value"": 960518305490989987}"
```

### StarRocks version (Required)
 - `2.5.0 6abafd3`
 - `2.5.3 46bf084`

### Description

When attempting to load data via broker load, the data column which is a json column, gets populated with random values, we are not sure but we believe the order of values is impacted, hence this affects the consistency of the data.
The rows in the expected behaviour section are exactly similar to the actual behaviour section in all areas except the data which is being populated in the data column is completely different

We tried this with parquet files and the output we get is same across the board.

Would really appreciate any help you'll can provide on this.

Thanks

**Comment by jaogoy** [comment]
@gunjdesai I haven't figured out what's the real problem. Can you point out the key problem part?

Broker Load will load data according to the column names from the column_list from Parquet.

**Comment by rickif** [comment]
@gunjdesai 
Do you mean that the value of column `data` is not correct?
Could you provide the parquet file to reproduce this problem?
