### ISSUE TITLE
compress and uncompress function

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#20507]
In some scenario, the data is too big to insert into StarRocks, so we need a function to compress the data during ingestion, and a function to uncompress the data during query.

so here is a proposal

### syntax
```
compress(input [,method])
```
in which, the input is a string value to be compressed, and the method is the compression method. By now, StarRocks support the following compress method:
- SNAPPY
- ZLIB
- ZSTD
- LZ4
the parameter should be case-insensitive. The default value of method is ZLIB.

### syntax
```
uncompress(input [,method])
```

also the method supports :
- SNAPPY
- ZLIB
- ZSTD
- LZ4
the parameter should be case-insensitive. The default value of method is ZLIB.

**Comment by Cai-Yao** [comment]
Can I have a try？

**Comment by kateshaowanjou** [comment]
@Cai-Yao I know compress and uncompress are sharing one issue number but they are actually two different issues so I'll assign compress to you first. Is it ok?

**Comment by Cai-Yao** [comment]
> @Cai-Yao I know compress and uncompress are sharing one issue number but they are actually two different issues so I'll assign compress to you first. Is it ok?

OK.

**Comment by kateshaowanjou** [comment]
@Cai-Yao Hi buddy, are you working on uncompress too?  If you have any questions, feel free to join WeChat for discussion: https://ma3you.com/articles_qrcode_show/b12e90J.png?le_time=220907203008013206

**Comment by Cai-Yao** [comment]
> We have marked this issue as stale because it has been inactive for 6 months. If this issue is still relevant, removing the stale label or adding a comment will keep it active. Otherwise, we'll close it in 10 days to keep the issue queue tidy. Thank you for your contribution to StarRocks!

In progress.
