### ISSUE TITLE
support array_agg(distinct)

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#20519]
sr already support array_agg(), array_agg(order by). Still, we need to support array_agg(distinct)

**Comment by chenshaojin** [comment]
goog luck

**Comment by wangxiaobaidu11** [comment]
Can you assign me?

**Comment by kateshaowanjou** [comment]
Hi @chenshaojin , are you still working on this issue？ If you have any questions, feel free to join WeChat for discussion:https://ma3you.com/articles_qrcode_show/b12e90J.png?le_time=220907203008013206💪
