### ISSUE TITLE
IFS to simplify CASE WHEN

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#20513]
In StarRocks, we can only use case when. However, ifs is a more simple way to express case when and widely used in excel, it's very easy to use.

so here is a proposal:

```
IFS(condition1, then [,condition2, then2, ....], else)
```

**Comment by srikker** [comment]
Hi @wangsimo0 , please assign this to me. Thanks!

**Comment by srikker** [comment]
This function just make a grammatical transformation or need reImplement? It looks exactly like the "case when" expression.

**Comment by LiShuMing** [comment]
Yep.  I think this can be covered by `CaseWhenExpr` totally. So just transform to `CaseExprr` in FE?

**Comment by srikker** [comment]
> Yep. I think this can be covered by `CaseWhenExpr` totally. So just transform to `CaseExprr` in FE?

ok
