### ISSUE TITLE
Optimize the StarRocksParser.g4 configuration

### ISSUE THREAD

**Issue by melin** [StarRocks/starrocks#20626]
https://github.com/StarRocks/starrocks/blob/01516cb33256332bd3dbafd349a82ed2d50e300b/fe/fe-core/src/main/java/com/starrocks/sql/parser/StarRocks.g4#L16

Optimize the StarRocksParser.g4 configuration:
```
parser grammar StarRocksParser;
options { tokenVocab = StarRocksLexer; }
```

参考spark antlr4 语法，doris 是在spark antlr4 语法文件上改的

@mofeiatwork

**Comment by mofeiatwork** [comment]
sorry, i don't understand that
