### ISSUE TITLE
Restore is super slow when  not using key to create a s3 repo

### ISSUE THREAD

**Issue by fieldsfarmer** [StarRocks/starrocks#20687]
### Steps to reproduce the behavior (Required)
We use two ways to create the aws repo
```	
first = `CREATE REPOSITORY %s
WITH BROKER
ON LOCATION "s3a://%s"
PROPERTIES(
    "aws.s3.use_aws_sdk_default_behavior" = "true",
    "aws.s3.region" = "%s"
);`

second = `CREATE REPOSITORY %s
WITH BROKER
ON LOCATION "s3a://%s"
PROPERTIES(
	"aws.s3.endpoint" = "s3.%s.amazonaws.com",
	"aws.s3.access_key" = "%s",
       "aws.s3.secret_key" = "%s"
);`
```

### Expected behavior (Required)
The restore job should finish in the same time

### Real behavior (Required)
The first one is much slower.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
3.0

**Comment by fieldsfarmer** [comment]
A db of 0 B and 1900 replicants, using the second way, it took around 30 seconds, using the first it took 3 hours.

**Comment by jaogoy** [comment]
@srlch can you have a look please.
