### ISSUE TITLE
Backend on k8s can't register self after change root password

### ISSUE THREAD

**Issue by Abel-Liu** [StarRocks/starrocks#20693]
### Steps to reproduce the behavior (Required)
1. Deploy on k8s(https://docs.starrocks.io/zh-cn/latest/administration/sr_operator)
2. SET PASSWORD for root = PASSWORD('xxxxxx');
3. BE pod restart

### Expected behavior (Required)
Pod start successfully.

### Real behavior (Required)
BE report error when start.
Failed to register self via executing sql to add backends. Permission Denied when connect using root without password.

### StarRocks version (Required)
 - 2.5.2 c3772fb2c
 - FE image: starrocks/fe-ubuntu:2.5.2
 - BE image: starrocks/be-ubuntu:2.5.2

**Comment by kevincai** [comment]
refer to this doc on how to handle the situation:

https://github.com/StarRocks/starrocks-kubernetes-operator/blob/main/doc/change_root_password_howto.md
