### ISSUE TITLE
Query return Invalid regex expression

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#2083]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS h11;
CREATE DATABASE h11;
USE h11;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DECIMAL64(9, 0)  NULL ,c_0_1 BOOLEAN NOT NULL ,c_0_2 DECIMAL32(7, 5)  NOT NULL ,c_0_3 DATETIME NOT NULL ,c_0_4 DECIMAL64(17, 5)  NOT NULL ,c_0_5 DATETIME NOT NULL ,c_0_6 DECIMAL(1, 0)  NULL ,c_0_7 SMALLINT NULL ,c_0_8 BOOLEAN NULL ,c_0_9 BOOLEAN NOT NULL ,c_0_10 DATE NOT NULL ,c_0_11 DECIMAL128(14, 13)  NULL ,c_0_12 BOOLEAN NULL ,c_0_13 CHAR(31) NULL ,c_0_14 BOOLEAN NULL ,c_0_15 FLOAT NULL ,c_0_16 VARCHAR(11) NOT NULL ) DUPLICATE KEY (c_0_0,c_0_1) DISTRIBUTED BY HASH (c_0_0) properties("replication_num"="1") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DECIMAL128(31, 2)  NULL ,c_1_1 DECIMAL128(19, 4)  NULL ,c_1_2 DECIMAL(12, 3)  NULL ,c_1_3 DECIMAL128(6, 6)  NOT NULL ,c_1_4 BOOLEAN NOT NULL ,c_1_5 DECIMAL(19, 6)  NULL ,c_1_6 PERCENTILE PERCENTILE_UNION NOT NULL ,c_1_7 DECIMAL(7, 1)  REPLACE NOT NULL ,c_1_8 DOUBLE SUM NULL ) AGGREGATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5) DISTRIBUTED BY HASH (c_1_5,c_1_4) properties("replication_num"="1") ;
INSERT INTO t0 VALUES (135198157, true, 0.00013, "1970-01-01 08:00:00", 2374921.27068, "1970-01-01 08:00:00", 5, 0, NULL, true, "1970-01-01", 6E-13, false, "iswGr", true, 0.7719798743587908, "");
INSERT INTO t0 VALUES (141278013, true, 0.00068, "1970-01-01 08:00:00", 3496973.28251, "1970-01-01 08:00:00", 5, 5, false, false, "1970-01-01", 5E-13, true, "bT7", true, 0.07962576812325772, ""), (782840150, false, 0.00003, "1970-01-01 08:00:00", 5876876.84070, "1970-01-01 08:00:00", 0, 10, true, true, "1970-01-01", 3E-13, false, "2Q", true, 0.23452199646852223, "Qrmo8");
INSERT INTO t1 VALUES (848797018242749533877722356.57, 11242235006.4305, 242422.343, 0.000006, true, NULL, percentile_hash("-1417723786"), 31583.1, 0.4871081043530118), (198764755056859516034739598.92, 48420939840.1484, 789643.723, 0.000008, false, 4215924.359410, percentile_hash("1571967904"), 48380.9, -2.048714805E9);
INSERT INTO t0 VALUES (543290042, true, 0.00039, "1970-01-01 08:00:00", 3346606.11109, "1970-01-01 08:00:00", 4, 1, false, false, "1970-01-01", 5E-13, false, "", true, -6.37071798E8, "d"), (247205420, false, 0.00024, "1970-01-01 08:00:00", 3588298.10842, "1970-01-01 08:00:00", 7, NULL, NULL, false, "1970-01-01", 1E-13, false, "N", false, 0.6379145913629616, "Z");
INSERT INTO t1 VALUES (128345375445030411075686416.21, 92319287585.4004, 714617.527, 0.000001, true, NULL, percentile_hash("-1425516317"), 54357.1, NULL), (207718743405925911909237768.78, 19797807690.8588, 675404.830, 0.000003, true, 4998111.187589, percentile_hash("553748121"), 44694.9, -1.780675027E9), (800412090760461688219828957.35, 79872745224.7736, 753868.286, 0.000002, true, 2296465.353181, percentile_hash("-1256404349"), 5169.5, 0.7165306649484809);
INSERT INTO t0 VALUES (746188538, false, 0.00031, "1970-01-01 08:00:00", 8767626.82507, "1970-01-01 08:00:00", NULL, 1, false, true, "1970-01-01", 4E-13, false, "wVG", false, 0.22253096818800977, "b"), (1560204, true, 0.00053, "1970-01-01 08:00:00", 3021360.97844, "1970-01-01 08:00:00", 8, 12, true, true, "1970-01-01", NULL, false, "z", true, NULL, "");
2. SELECT t1.c_1_0 FROM t1 WHERE false GROUP BY "", t1.c_1_3, NULL, t1.c_1_0, 566676.915 HAVING CAST(MAX(REGEXP_REPLACE("", ST_POINT(0.11544426985994183, 0.20763133900993713) , "X") )  AS BOOLEAN )  UNION ALL SELECT t1.c_1_0 FROM t1 WHERE false GROUP BY "", t1.c_1_3, NULL, t1.c_1_0, 566676.915 HAVING (NOT (CAST(MAX(REGEXP_REPLACE("", ST_POINT(0.11544426985994183, 0.20763133900993713) , "X") )  AS BOOLEAN ) )) UNION ALL SELECT t1.c_1_0 FROM t1 WHERE false GROUP BY "", t1.c_1_3, NULL, t1.c_1_0, 566676.915 HAVING ((CAST(MAX(REGEXP_REPLACE("", ST_POINT(0.11544426985994183, 0.20763133900993713) , "X") )  AS BOOLEAN ) ) IS NULL);

### Real behavior (Required)
mysql>  SELECT t1.c_1_0 FROM t1 WHERE false GROUP BY "", t1.c_1_3, NULL, t1.c_1_0, 566676.915 HAVING CAST(MAX(REGEXP_REPLACE("", ST_POINT(0.11544426985994183, 0.20763133900993713) , "X") )  AS BOOLEAN )  UNION ALL SELECT t1.c_1_0 FROM t1 WHERE false GROUP BY "", t1.c_1_3, NULL, t1.c_1_0, 566676.915 HAVING (NOT (CAST(MAX(REGEXP_REPLACE("", ST_POINT(0.11544426985994183, 0.20763133900993713) , "X") )  AS BOOLEAN ) )) UNION ALL SELECT t1.c_1_0 FROM t1 WHERE false GROUP BY "", t1.c_1_3, NULL, t1.c_1_0, 566676.915 HAVING ((CAST(MAX(REGEXP_REPLACE("", ST_POINT(0.11544426985994183, 0.20763133900993713) , "X") )  AS BOOLEAN ) ) IS NULL);
ERROR 1064 (HY000): Invalid regex expression: 

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.0 asan
 - mysql> select current_version();
+--------------------------+
| current_version()        |
+--------------------------+
| SQLANCER_01_ASAN f910af7 |
+--------------------------+

**Comment by kangkaisen** [comment]
`Invalid regex expression` this error message should be reasonable.
