### ISSUE TITLE
external_table implicit conversion bug

### ISSUE THREAD

**Issue by wang168003** [StarRocks/starrocks#20884]
I got a hudi table. And I found request it from starrocks using external_table. The column using varchar/string type compared to number cannot  get right answer. 
![image](https://user-images.githubusercontent.com/20813802/229492745-72324dbe-42b9-48a1-a732-242d4ed5b3a6.png)

**Comment by wang168003** [comment]
> sting >= int will implictly convert the string and int values into double values, then compare them. you can check it.
> 
> cc @yingtingdong

I think I am confident abount the result. And I can give another example more like in product environment.

The string value is '179.20', the int value is 20.  When query using external hudi table as data source gets wrong result, but simple query could get true result.
 
![image](https://github.com/StarRocks/starrocks/assets/20813802/fe0a6ab2-f390-473e-aa31-f2f471988ca5)
![image](https://github.com/StarRocks/starrocks/assets/20813802/e5458401-51ec-43b1-8f39-f109b9fa6c3d)
![image](https://github.com/StarRocks/starrocks/assets/20813802/3cac8ac7-7edd-4e5a-9495-4ca28f55bc02)

**Comment by wang168003** [comment]
May I ask for more fix information  or other whatever about this bug?

**Comment by packy92** [comment]
I am very sorry for not replying in time. This is a problem about principle of implicit conversion. For the operation of `col > constant`, we will first convert the constant to the type corresponding to col for performance. For the comparison between constants, we will choose a compatible type between them. Therefore, the above-mentioned inconsistency appears, and we are still thinking about how to unify this problem.

**Comment by wang168003** [comment]
Thank you for your reply. So I will have to try to cast the string field to number using sqlparser by myself.

**Comment by packy92** [comment]
BTW, If the varchar col only contains decimal value, maybe use decimal type is better?

**Comment by wang168003** [comment]
That's a good idea. Thanks.
