### ISSUE TITLE
[Doc] Can starrocks docs support catalog(right/left) folding?

### ISSUE THREAD

**Issue by shenhua19891109** [StarRocks/starrocks#20898]
![image](https://user-images.githubusercontent.com/14866179/229506248-af338260-1706-4d01-830a-9c05a4f40dbc.png)

it is very unfriendly for vertical screen.

**Comment by evelynzhaojie** [comment]
we supports left folding on new doc site https://docs.starrocks.io/docs/unloading/Flink_connector/
![image](https://github.com/StarRocks/starrocks/assets/98087056/ce8f7cb4-7b93-4b95-9859-042311d49f05)
