### ISSUE TITLE
[Docs] Download should point to the newest version of our product

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#20915]
File: [/docs/quick_start/Deploy.md](https://docs.starrocks.io/en-us/latest/quick_start/Deploy)

Why does it point to v2.4?  Shouldn't it point to a list of versions?

**Comment by alberttwong** [comment]
https://github.com/StarRocks/starrocks/releases

**Comment by EsoragotoSpirit** [comment]
fixed
