### ISSUE TITLE
[Docs] AWS broker load should use aws.s3.region parameter and not endpoint

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#21009]
File: [/docs/loading/BrokerLoad.md](https://docs.starrocks.io/en-us/latest/loading/BrokerLoad)

should use 
`aws.s3.region=us-west-2`

**Comment by amber-create** [comment]
For AWS, the doc now DOES use "aws.s3.region" instead of "aws.s3.endpoint", so this no longer seems an issue.
