### ISSUE TITLE
[Docs] Link to "cancel load" does not work

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#21007]
File: [/docs/loading/BrokerLoad.md](https://docs.starrocks.io/en-us/latest/loading/BrokerLoad)

Goes to https://docs.starrocks.io/en-us/latest/sql-reference/sql-statements/data-manipulation/CANCEL%20LOAD.  That is the wrong URL.  Should be https://docs.starrocks.io/en-us/latest/sql-reference/sql-statements/data-manipulation/CANCEL%20LOAD

**Comment by evelynzhaojie** [comment]
HI Albert, I tried the link in the Broker load doc, and it works for me, strange.
