### ISSUE TITLE
[Docs]  Routine Load using Kafka is missing parameters to connect to Confluent Kafka Cloud

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#21012]
File: [/docs/loading/RoutineLoad.md](https://docs.starrocks.io/en-us/latest/loading/RoutineLoad)

4 key lines need to be added. See
https://github.com/StarRocks/starrocks/issues/21011

**Comment by hellolilyliuyi** [comment]
This topic introduces how to use routine load to load data from self-managed kafka, not cloud managed kafka. For using routine load to load data from cloud managed kafka, see [Load data from Confluent Cloud](https://docs.celerdata.com/en-us/main/loading/loading_from_confluent) and [Load data from Amazon MSK
](https://docs.celerdata.com/en-us/main/loading/loading_from_msk).
