### ISSUE TITLE
[Docs] curl example should show auth commands

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#21026]
File: [/docs/loading/Stream_Load_transaction_interface.md](https://docs.starrocks.io/en-us/latest/loading/Stream_Load_transaction_interface)

currently
```
curl -H "label:<label_name>" -H "db:<database_name>" -H "table:<table_name>"
    -XPOST http://<fe_host>:<fe_http_port>/api/transaction/begin
```

should be
```
curl -H "label:<label_name>" -H "db:<database_name>" -H "table:<table_name>" -XPOST http://<fe_host>:<fe_http_port>/api/transaction/begin --user username:password
```

**Comment by amber-create** [comment]
This doc has been modified. See https://docs.starrocks.io/en-us/latest/loading/Stream_Load_transaction_interface.
