### ISSUE TITLE
Query stuck when run query03 of 100g tpcds using 1024 concurrent

### ISSUE THREAD

**Issue by wangruin** [StarRocks/starrocks#2105]
### Steps to reproduce the behavior (Required)
1. fragment_pool_thread_num_max uses the default 4096
2. The previous query reported an error
`ERROR : Put planfragment 05e532b8-5bf3-11ec-a0b2-00163e1f2b16 to thread pool failed. err = Thread pool is at capacity (4096/4096 tasks running, 2048/2048 tasks queued)`
3. mysqlslap -h172.26.34.182 -P9030 -uroot  --concurrency=1024                --create-schema=tpcds_100g --query=" select  dt.d_year ,item.i_brand_id brand_id ,item.i_brand brand ,sum(ss_ext_sales_price) sum_agg from  date_dim dt ,store_sales ,item where dt.d_date_sk = store_sales.ss_sold_date_sk and store_sales.ss_item_sk = item.i_item_sk and item.i_manufact_id = 128 and dt.d_moy=11 group by dt.d_year ,item.i_brand ,item.i_brand_id order by dt.d_year ,sum_agg desc ,brand_id limit 100;  " 
 This query returns 1 second normally, but now it is stuck and not return even after waiting longer than query_timeout
4. set  fragment_pool_thread_num_max=16384, fragment_pool_queue_size=65536, then query returns 1 second normally

### Expected behavior (Required)
Query should not get stuck when fragment_pool_thread_num_max = 4096

### Real behavior (Required)
Query stuck

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
branch-2.0 5ac54fc release

**Comment by kangkaisen** [comment]
This issue has been fixed by pipeline  query engine
