### ISSUE TITLE
[Bug] JSON_OBJECT parsed value to null when string contains "["

### ISSUE THREAD

**Issue by yangrong688** [StarRocks/starrocks#21257]
### Steps to reproduce the behavior (Required)
select JSON_OBJECT("key","[");

### Expected behavior (Required)
{"key": "["}
### Real behavior (Required)
{"key": null}
### StarRocks version (Required)
2.3 2.4 2.5 3.0

**Comment by yangrong688** [comment]
string contains "{" will be parsed to null also.
select JSON_OBJECT("key","{"); 
{"key": null}

**Comment by mofeiatwork** [comment]
you could quote the string with: `select json_object('k', '"["')`

**Comment by yangrong688** [comment]
it works with quote, thanks for your reply.
