### ISSUE TITLE
Querying view encounters error after rename database

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#2130]
### Steps to reproduce the behavior (Required)
```
create database db_test;
use db_test;
create table t(a int,b varchar) distributed by hash(a);
create view v_t as select * from t;
alter database db_test rename test_db;
use test_db;
mysql> select * from t;
Empty set (0.01 sec)

mysql> select * from v_t;
ERROR 1064 (HY000): Unknown database 'default_cluster:db_test'
```

### Expected behavior (Required)
Empty set

### Real behavior (Required)
ERROR 1064 (HY000): Unknown database 'default_cluster:db_test'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 ```
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN 4285c5f   |
+-------------------+
1 row in set (0.04 sec)
```

**Comment by Astralidea** [comment]
This is because the implementation of view record the database name information of this table
If change the database name, it need to change all the views. 
The cost of such a name change will be very large if there are many table in starrocks.

**Comment by jaogoy** [comment]
@Astralidea You can check the SQL standard to decide
