### ISSUE TITLE
support catalog dialect in starrocks ，like trino ptf

### ISSUE THREAD

**Issue by allendang001** [StarRocks/starrocks#21317]
## Feature request

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
there is the same solution in trino , link https://github.com/trinodb/trino/issues/1839

**Describe alternatives you've considered**

**Additional context**

**Comment by DorianZheng** [comment]
@allendang001 Could you provide us some of your typical usage as examples and why do you need this feature

**Comment by allendang001** [comment]
If I know the data distribution and index optimization of the data source, I can directly write more optimized SQL without starrocks to process or push down some operators, thereby improving the execution efficiency of tasks
