### ISSUE TITLE
Error reported when using broker load to import OCI storage files into Oracle Cloud.

### ISSUE THREAD

**Issue by zhazenmexie** [StarRocks/starrocks#21431]
## General Question

使用broker load导入oracle云的oci存储文件报错，我在社区群问了说2.5已经支持导入oracle云的oci文件，但是文档没有相关配置，我按照以下命令去执行的
`load label test1123456
( DATA INFILE('oci://xxxxxxxxxxx/test1/ds=2022-03-04/*.parquet') 
INTO TABLE test1 
FORMAT AS 'parquet' 
(      id, from_source_id) ) 
with BROKER broker_name 
( 'fs.oci.client.auth.tenantId' = 'oxxxxxxxxxxxxxxxxxefrqm42btvq', 
'fs.oci.client.auth.userId' = 'ocidxxxxxxxxxxxxxxxxxxxxxxxxxqhjkqgo36siba', 
'fs.oci.client.auth.fingerprint' = '69:2xxxxxxxxxxxxxxxxxxxxxxxxxa:a1:7c',
'fs.oci.client.auth.pemfilepath' = 'xxxxxxxxxxxy/oci_api_key.pem',
'fs.oci.client.regionCodeOrId' = 'me-jeddah-1');`
然后执行报错
`         JobId: 10232
         Label: test1123456
         State: CANCELLED
      Progress: ETL:N/A; LOAD:N/A
          Type: BROKER
      Priority: NORMAL
       EtlInfo: NULL
      TaskInfo: resource:N/A; timeout(s):14400; max_filter_ratio:0.0
      ErrorMsg: type:ETL_RUN_FAIL; msg:Broker list path failed. path=oci://xxxxxxx/test1/ds=2022-03-04/*.parquet,broker=TNetworkAddress(hostname:xxx.xx.xx.xx, port:8000),msg=org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "oci", cause by: No FileSystem for scheme "oci"
    CreateTime: 2023-04-12 08:41:37
  EtlStartTime: NULL
 EtlFinishTime: NULL
 LoadStartTime: NULL
LoadFinishTime: 2023-04-12 08:41:38
           URL: NULL
    JobDetails: {"All backends":{},"FileNumber":0,"FileSize":0,"InternalTableLoadBytes":0,"InternalTableLoadRows":0,"ScanBytes":0,"ScanRows":0,"TaskNumber":0,"Unfinished backends":{}}`
显示不支持oci 文件系统

**Comment by kateshaowanjou** [comment]
@zhazenmexie Thanks for your feedback but to ensure that everyone can understand and participate in the conversations, we kindly request everyone use English for communication. Your cooperation will be greatly appreciated! 🙏🏻
