### ISSUE TITLE
[Doc] Add official instruction and examples of brokerload from Azure blobstore to Starrocks doc

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks#21488]
## Enhancement
It seems that broker load from Azure blobstore is supported in 3.0?
Can we add the document for Azure blobstore as with other blobstores
https://docs.starrocks.io/en-us/3.0/sql-reference/sql-statements/data-manipulation/BROKER%20LOAD
![image](https://user-images.githubusercontent.com/5108773/231558303-5e4c7854-d523-42de-9675-4835920a1c75.png)

FYI, here is what I learned from @Smith-Cruise about this load sql 

https://github.com/StarRocks/starrocks/issues/18342#issuecomment-1496874460

cc @jiacheng-celonis @imay @chaoyli @rcauble

**Comment by Smith-Cruise** [comment]
I will push it

**Comment by amber-create** [comment]
This has been done long ago. See https://docs.starrocks.io/en-us/latest/sql-reference/sql-statements/data-manipulation/BROKER_LOAD#microsoft-azure-storage & https://docs.starrocks.io/en-us/latest/loading/cloud_storage_load#load-data-from-microsoft-azure-storage
