### ISSUE TITLE
File external table access failure

### ISSUE THREAD

**Issue by WholeWorld-Timothy** [StarRocks/starrocks#21521]
### Steps to reproduce the behavior (Required)
Create a file external table on version 2.5.4:
CREATE EXTERNAL TABLE EXT_FILE_TABLE (
OC varchar(65533) NOT NULL COMMENT “”,
PT varchar(65533) NOT NULL COMMENT “”,
P varchar(65533) NOT NULL COMMENT “”,
TI varchar(65533) NOT NULL COMMENT “”,
SI varchar(65533) NOT NULL COMMENT “”,
II varchar(65533) NOT NULL COMMENT “”,
IK varchar(65533) NOT NULL COMMENT “”,
IKN varchar(65533) NOT NULL COMMENT “”,
IV decimal64(18, 2) NULL COMMENT “”,
TS bigint(20) NOT NULL COMMENT “”
) ENGINE=FILE
COMMENT “FILE”
PROPERTIES (
“aws.s3.access_key” = “KEY”,
“path” = “s3a://tmp/TMPFILE.parquet”,
“aws.s3.secret_key” = “KEY”,
“aws.s3.enable_ssl” = “false”,
“aws.s3.endpoint” = “http://xx.xx.xxx.xxx:9900/”,
“format” = “parquet”,
“aws.s3.enable_path_style_access” = “true”
);
My cluster has 3 fe instances, and fe reported an error when creating a table：
2023-04-12 16:42:31,636 ERROR (audit loader thread|75) [AuditLoaderPlugin$LoadWorker.run():283] run audit logger error:
java.lang.NullPointerException: null

After creating the table, access FE separately, and the FE with the role of leader will report an error：
doesn’t get file with path: s3a://tmp/TMPFILE.parquet

detailed log：
[leader-fe.log](https://github.com/StarRocks/starrocks/files/11218616/leader-fe.log)

### Expected behavior (Required)

Ability to query data

### Real behavior (Required)

Unable to query data

### StarRocks version (Required)
2.5.4

**Comment by jaogoy** [comment]
@WholeWorld-Timothy is your path right?

**Comment by Smith-Cruise** [comment]
try with `s3://` protocol?
