### ISSUE TITLE
Query sql error: null in 

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#2154]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS g0;
CREATE DATABASE g0;
USE g0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 INT NOT NULL ,c_0_1 CHAR(1) NULL ) UNIQUE KEY (c_0_0) DISTRIBUTED BY HASH (c_0_0) properties("replication_num"="1") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 BOOLEAN NULL ,c_1_1 DECIMAL64(15, 4)  NULL ,c_1_2 DECIMAL(7, 3)  NOT NULL ,c_1_3 DECIMAL128(14, 0)  NULL ,c_1_4 CHAR(31) NOT NULL ,c_1_5 DECIMAL32(5, 2)  NULL ,c_1_6 DECIMAL32(6, 0)  NOT NULL ) DUPLICATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4) DISTRIBUTED BY HASH (c_1_1,c_1_2) properties("replication_num"="1") ;
CREATE TABLE IF NOT EXISTS t2 (c_2_0 VARCHAR(11) NULL ,c_2_1 DECIMAL64(13, 7)  NULL ,c_2_2 CHAR(21) REPLACE_IF_NOT_NULL NOT NULL ) AGGREGATE KEY (c_2_0,c_2_1) DISTRIBUTED BY HASH (c_2_1) properties("replication_num"="1") ;
INSERT INTO t1 VALUES (true, 7939556.3011, 0.000, 53540670925274, "F", 9.27, 435029);
INSERT INTO t0 VALUES (24, ""), (28, ""), (24, "");
INSERT INTO t2 VALUES ("TDCnP73nE", 0.0099742, "nLsA"), (NULL, 0.0923564, "hh");
INSERT INTO t2 VALUES ("Jir", 0.0728920, "");
INSERT INTO t2 VALUES ("E9", 0.0060752, "u7q"), ("", 0.0713655, NULL);
INSERT INTO t1 VALUES (NULL, 4948928.4200, 7.630, 7945217223820, "f1", 0.88, 458850);
INSERT INTO t1 VALUES (true, NULL, 5.475, 72575734979739, "J8", 6.05, 152722), (false, 7442737.0955, 5.093, 66552004989694, "G", 8.13, 241004);
INSERT INTO t1 VALUES (true, NULL, 9.548, 44403720377629, "", 1.85, 619814), (false, 2766961.1179, 7.723, 91004592732992, "8qEo9", NULL, 210260);
INSERT INTO t0 VALUES (2, "");
2. mysql> SELECT t0.c_0_1, t2.c_2_0, t2.c_2_2 FROM t1,  t2 LEFT OUTER JOIN t0 ON t2.c_2_0 = t0.c_0_1 AND t2.c_2_0 > "" GROUP BY t0.c_0_1, t2.c_2_0, t2.c_2_2;
+-------+-----------+-------+
| c_0_1 | c_2_0     | c_2_2 |
+-------+-----------+-------+
| NULL  | Jir       |       |
| NULL  | NULL      | hh    |
| NULL  | TDCnP73nE | nLsA  |
| NULL  | E9        | u7q   |
| NULL  |           | NULL  |
+-------+-----------+-------+

3. mysql> SELECT t0.c_0_1, t2.c_2_0, t2.c_2_2 FROM t1,  t2 LEFT JOIN t0 ON t2.c_2_0 = t0.c_0_1 AND t2.c_2_0 > "" WHERE (NOT ((t0.c_0_1) IN ("") )) GROUP BY t0.c_0_1, t2.c_2_0, t2.c_2_2 UNION SELECT t0.c_0_1, t2.c_2_0, t2.c_2_2 FROM t1,  t2 LEFT JOIN t0 ON t2.c_2_0 = t0.c_0_1 AND t2.c_2_0 > "" WHERE (NOT ((NOT ((t0.c_0_1) IN ("") )))) GROUP BY t0.c_0_1, t2.c_2_0, t2.c_2_2 UNION SELECT t0.c_0_1, t2.c_2_0, t2.c_2_2 FROM t1,  t2 LEFT JOIN t0 ON t2.c_2_0 = t0.c_0_1 AND t2.c_2_0 > "" WHERE (((NOT ((t0.c_0_1) IN ("") ))) IS NULL) GROUP BY t0.c_0_1, t2.c_2_0, t2.c_2_2;
+-------+-----------+-------+
| c_0_1 | c_2_0     | c_2_2 |
+-------+-----------+-------+
|       |           | NULL  |
| NULL  |           | NULL  |
| NULL  | Jir       |       |
| NULL  | NULL      | hh    |
| NULL  | TDCnP73nE | nLsA  |
| NULL  | E9        | u7q   |
+-------+-----------+-------+
4. mysql>  SELECT t0.c_0_1, t2.c_2_0, t2.c_2_2 FROM t1,  t2 LEFT JOIN t0 ON t2.c_2_0 = t0.c_0_1 AND t2.c_2_0 > "" WHERE (NOT ((NOT ((t0.c_0_1) IN ("") )))) GROUP BY t0.c_0_1, t2.c_2_0, t2.c_2_2;
+-------+-------+-------+
| c_0_1 | c_2_0 | c_2_2 |
+-------+-------+-------+
|       |       | NULL  |
+-------+-------+-------+

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.0 asan
 - mysql> select current_version();
+------------------------------+
| current_version()            |
+------------------------------+
| SQLANCER_MASTER_ASAN 6d468b7 |
+------------------------------+

**Comment by HangyuanLiu** [comment]
Query Plan is correct

**Comment by HangyuanLiu** [comment]
+--------------------------------------------------------------------------------------------+
| Explain String                                                                             |
+--------------------------------------------------------------------------------------------+
| PLAN FRAGMENT 0                                                                            |
|  OUTPUT EXPRS:12: c_0_1 | 8: c_2_0 | 10: c_2_2                                             |
|   PARTITION: UNPARTITIONED                                                                 |
|                                                                                            |
|   RESULT SINK                                                                              |
|                                                                                            |
|   10:EXCHANGE                                                                              |
|      use vectorized: true                                                                  |
|                                                                                            |
| PLAN FRAGMENT 1                                                                            |
|  OUTPUT EXPRS:                                                                             |
|   PARTITION: HASH_PARTITIONED: 12: c_0_1, 8: c_2_0, 10: c_2_2                              |
|                                                                                            |
|   STREAM DATA SINK                                                                         |
|     EXCHANGE ID: 10                                                                        |
|     UNPARTITIONED                                                                          |
|                                                                                            |
|   9:AGGREGATE (merge finalize)                                                             |
|   |  group by: 12: c_0_1, 8: c_2_0, 10: c_2_2                                              |
|   |  use vectorized: true                                                                  |
|   |                                                                                        |
|   8:EXCHANGE                                                                               |
|      use vectorized: true                                                                  |
|                                                                                            |
| PLAN FRAGMENT 2                                                                            |
|  OUTPUT EXPRS:                                                                             |
|   PARTITION: RANDOM                                                                        |
|                                                                                            |
|   STREAM DATA SINK                                                                         |
|     EXCHANGE ID: 08                                                                        |
|     HASH_PARTITIONED: 12: c_0_1, 8: c_2_0, 10: c_2_2                                       |
|                                                                                            |
|   7:AGGREGATE (update serialize)                                                           |
|   |  STREAMING                                                                             |
|   |  group by: 12: c_0_1, 8: c_2_0, 10: c_2_2                                              |
|   |  use vectorized: true                                                                  |
|   |                                                                                        |
|   6:HASH JOIN                                                                              |
|   |  join op: INNER JOIN (BROADCAST)                                                       |
|   |  hash predicates:                                                                      |
|   |  colocate: false, reason:                                                              |
|   |  equal join conjunct: 8: c_2_0 = 12: c_0_1                                             |
|   |  use vectorized: true                                                                  |
|   |                                                                                        |
|   |----5:EXCHANGE                                                                          |
|   |       use vectorized: true                                                             |
|   |                                                                                        |
|   3:Project                                                                                |
|   |  <slot 8> : 8: c_2_0                                                                   |
|   |  <slot 10> : 10: c_2_2                                                                 |
|   |  use vectorized: true                                                                  |
|   |                                                                                        |
|   2:CROSS JOIN                                                                             |
|   |  cross join:                                                                           |
|   |  predicates is NULL.                                                                   |
|   |  use vectorized: true                                                                  |
|   |                                                                                        |
|   |----1:OlapScanNode                                                                      |
|   |       TABLE: t2                                                                        |
|   |       PREAGGREGATION: OFF. Reason: Has can not pre-aggregation Join                    |
|   |       PREDICATES: 8: c_2_0 > '', 8: c_2_0 = ''                                         |
|   |       partitions=1/1                                                                   |
|   |       rollup: t2                                                                       |
|   |       tabletRatio=10/10                                                                |
|   |       tabletList=170524,170526,170528,170530,170532,170534,170536,170538,170540,170542 |
|   |       cardinality=3                                                                    |
|   |       avgRowSize=2.0                                                                   |
|   |       numNodes=0                                                                       |
|   |       use vectorized: true                                                             |
|   |                                                                                        |
|   0:OlapScanNode                                                                           |
|      TABLE: t1                                                                             |
|      PREAGGREGATION: ON                                                                    |
|      partitions=1/1                                                                        |
|      rollup: t1                                                                            |
|      tabletRatio=10/10                                                                     |
|      tabletList=170501,170503,170505,170507,170509,170511,170513,170515,170517,170519      |
|      cardinality=6                                                                         |
|      avgRowSize=1.0                                                                        |
|      numNodes=0                                                                            |
|      use vectorized: true                                                                  |
|                                                                                            |
| PLAN FRAGMENT 3                                                                            |
|  OUTPUT EXPRS:                                                                             |
|   PARTITION: RANDOM                                                                        |
|                                                                                            |
|   STREAM DATA SINK                                                                         |
|     EXCHANGE ID: 05                                                                        |
|     UNPARTITIONED                                                                          |
|                                                                                            |
|   4:OlapScanNode                                                                           |
|      TABLE: t0                                                                             |
|      PREAGGREGATION: OFF. Reason: Has can not pre-aggregation Join                         |
|      PREDICATES: 12: c_0_1 = '', 12: c_0_1 > ''                                            |
|      partitions=1/1                                                                        |
|      rollup: t0                                                                            |
|      tabletRatio=10/10                                                                     |
|      tabletList=170478,170480,170482,170484,170486,170488,170490,170492,170494,170496      |
|      cardinality=2                                                                         |
|      avgRowSize=1.0                                                                        |
|      numNodes=0                                                                            |
|      use vectorized: true                                                                  |
+--------------------------------------------------------------------------------------------+

**Comment by stdpain** [comment]
Fixed by #2187
