### ISSUE TITLE
about backup/restore

### ISSUE THREAD

**Issue by cliffzhan** [StarRocks/starrocks#2159]
## Enhancement
the backup for SR doesn't support the style like mysqldump, if we don't have a S3  or hdfs service ,we can't do backup/restore suitable,so i hope the SR can support it in the future.

**Comment by imay** [comment]
@cliffzhan 
In most cases, starrocks is a cluster of multiple machines. The size of the table has to exceed the capacity of a single machine. If you want to backup such a table, one node may not fit, do you have any suggestions?

**Comment by jaogoy** [comment]
Or, how is about the data size that you want to backup normally.
And, what's the backup style? A whole table, servel integral partitions of a table, or any complex query data?
