### ISSUE TITLE
很多时候在做多变等价关联时，需要多列先做处理后再关联起来，但是现在starrocks不支持

### ISSUE THREAD

**Issue by dq1201** [StarRocks/starrocks#2162]
eg: 
   关联条件： ON coalesce(B.id,C.id)= D.id AND coalesce(B.dt,C.dt)=D.dt
   报错：1064 - we do not support equal on predicate have multi columns in left or right

**Comment by Johnsonginati** [comment]
Could you translate the issue in English? Excuse.

**Comment by josonle** [comment]
> eg: 关联条件： ON coalesce(B.id,C.id)= D.id AND coalesce(B.dt,C.dt)=D.dt 报错：1064 - we do not support equal on predicate have multi columns in left or right

you can try `set enable_cbo=false`
