### ISSUE TITLE
Join using column selection error

### ISSUE THREAD

**Issue by HangyuanLiu** [StarRocks/starrocks#2164]
### Steps to reproduce the behavior (Required)
 CREATE TABLE `t0` (
  `v1` bigint DEFAULT NULL,
  `v2` bigint DEFAULT NULL,
  `v3` bigint DEFAULT NULL
)

- `select * from t0 x,t0 y inner join t0 z using(v1) `
### Expected behavior (Required)

Translate to `select * from (select * from t0 x,t0 y) t inner join t0 z on t.v1 = z.v1`
Analyze Error : Column 'v1' is ambiguous

### Real behavior (Required)

Translate to `select * from t0 x,t0 y inner join t0 z on y.v1 = z.v1`

### StarRocks version (Required)
Master

**Comment by yongbingwang** [comment]
Passed validation,close this issue.
```
mysql> select * from t0 x,t0 y inner join t0 z using(v1);
ERROR 1064 (HY000): Column 'v1' is ambiguous
```
