### ISSUE TITLE
cannot show create view

### ISSUE THREAD

**Issue by skyoct** [StarRocks/starrocks#21645]
### Steps to reproduce the behavior (Required)
When executing `show create table [view_name]` 

### Expected behavior (Required)
[42000][1064] Unknown table 'test_table_02'

### Real behavior (Required)

table info

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by imay** [comment]
Could you try `show create view [view_name]`

**Comment by skyoct** [comment]
@imay It's normal for me to try `show create view [view_name]`, But I can't use MySQL driver connection in superset. In MySQL, I can use `show create table to` view views,  Will this be compatible in the future?
