### ISSUE TITLE
Failed to build FE

### ISSUE THREAD

**Issue by leoluan2009** [StarRocks/starrocks#21662]
### Steps to reproduce the behavior (Required)
Failed to build the latest fe code in main branch following the doc https://docs.starrocks.io/en-us/main/developers/development-environment/IDEA
The error message is below:
```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/xxxx/github/starrocks/fe/fe-core/target/generated-sources/antlr4/com/starrocks/sql/parser/StarRocksParser.java:[13,8] duplicate class: com.starrocks.sql.parser.StarRocksParser
[ERROR] /Users/xxxx/github/starrocks/fe/fe-core/src/main/java/com/starrocks/sql/parser/gen/StarRocksLex.java:[387,117] cannot access StarRocksParser
  bad source file: /Users/xxxxx/github/starrocks/fe/fe-core/target/generated-sources/antlr4/com/starrocks/sql/parser/StarRocksParser.java
    file does not contain class StarRocksParser
    Please remove or make sure it appears in the correct subdirectory of the sourcepath.
[INFO] 2 errors
```

**Comment by leoluan2009** [comment]
@chaoyli   Can you help to look this issue? Thanks

**Comment by kevincai** [comment]
if you run into this on MAC system with IDEA, you have to do a clean up with the resource, e.g. `git clean -dfx -- fe/fe-core`

This error is because that IDEA helps generating the java code from the .g4 file but put into a different location than our `./build.sh` script.
