### ISSUE TITLE
Please provide external table support for Oracle's TIMESTAMP

### ISSUE THREAD

**Issue by niezl** [StarRocks/starrocks#21699]
## Feature request

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kateshaowanjou** [comment]
@niezl Thanks for your feedback but to ensure that everyone can understand and participate in the conversations, we kindly request everyone use English for communication. Your cooperation will be greatly appreciated! 🙏🏻

**Comment by stdpain** [comment]
dup with #21702
