### ISSUE TITLE
[Bug]The interval operation reported an error

### ISSUE THREAD

**Issue by Youngwb** [StarRocks/starrocks#21708]
### Steps to reproduce the behavior (Required)
```
mysql> select interval '1' year + interval '1' month + date '2022-01-01';
ERROR 1064 (HY000): Getting analyzing error. Detail message: Cannot cast 'interval '1'com.starrocks.sql.ast.UnitIdentifier@22cb72dd' from INVALID_TYPE to DATETIME.
mysql> select date '2022-01-01' + interval '1' year + interval '1' month;
+-------------------------------------------------------+
| '2022-01-01' + INTERVAL '1' YEAR + INTERVAL '1' MONTH |
+-------------------------------------------------------+
| 2023-02-01 00:00:00                                   |
+-------------------------------------------------------+
1 row in set (0.01 sec)
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by LiShuMing** [comment]
The kernel problem is we cannot support the `interval` type. Like this:
```
select interval '1' year + interval '1' month;

select interval '1' year;
```

If we want to support this clearly, we may introduce the `interval` type (I will try to study it later) in FE.  How about this?

Some docs:
- https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-INTERVAL-INPUT
- [select interval '1' year](https://docs.snowflake.com/en/sql-reference/data-types-datetime#interval-constants)
