### ISSUE TITLE
fe start with check meta directory error

### ISSUE THREAD

**Issue by 344970961** [StarRocks/starrocks#218]
### Steps to reproduce the behavior (Required)
1. according to install doc https://docs.dorisdb.com/zh-cn/main/quick_start/Deploy
2. mkdir -p starrocks-meta
3. bin/start_fe.sh --daemon and start failed with msg 'doris-meta does not exist, will exit'

### Expected behavior (Required)
fe start successfully
### Real behavior (Required)
fe start failed and with msg 'doris-meta does not exist, will exit'; metadata directory should be doris-meta
### StarRocks version (Required)
1.18.2 caa8b52
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by kangkaisen** [comment]
Thanks for your report, The doc issue  we  has fixed. Please refer  to https://github.com/StarRocks/docs/blob/main/quick_start/Deploy.md
