### ISSUE TITLE
Support async lookup for StarRocks connector

### ISSUE THREAD

**Issue by Bryce-Loski** [StarRocks/starrocks#21824]
## Feature request

**Is your feature request related to a problem? Please describe.**

Support async lookup for Support async lookup for HBase connector. 

**Describe the solution you'd like**

extends AsyncTableFunction  
**Describe alternatives you've considered**

**Additional context**

**Comment by jaogoy** [comment]
Currently, StarRocks doesn't support async query.
Can you give more information about your need that why you need a async lookup.

**Comment by Bryce-Loski** [comment]
I am using tables stored in StarRocks as dimension tables. If it doesn't support asynchronous queries, I'll have to synchronously query the database for each piece of data. This would slow down the execution of my program. Although increasing parallelism can alleviate this issue, it is not the most optimal solution.
