### ISSUE TITLE
主键表，使用auto_increase作为自增主键，insert时报错

### ISSUE THREAD

**Issue by huangzengzeng** [StarRocks/starrocks#21846]
### Steps to reproduce the behavior (Required)

0.ADMIN SET  FRONTEND CONFIG ("empty_load_as_error" = "false")
   SET  enable_insert_strict = false;

1. CREATE TABLE test_tbl
(
    id BIGINT AUTO_INCREMENT,
    name BIGINT ,
    job1 BIGINT ,
    job2 BIGINT 
) 
PRIMARY KEY (id)
DISTRIBUTED BY HASH(id)
2. insert into test_tbl (name,job1,job2) values (22,null,44)
3. select  * from test_tbl

### Expected behavior (Required)
insert时没有报错但是记录并没有写到表中,
使用发现当有一个字段值为NULL时，脚本可正常执行，但是记录不会入到表中
### StarRocks version (Required)
 3.0.0-RC02 84d70fd

**Comment by srlch** [comment]
Fix PR:
https://github.com/StarRocks/starrocks/pull/21877
