### ISSUE TITLE
Add a rule in optimizer to remove useless left join

### ISSUE THREAD

**Issue by mofeiatwork** [StarRocks/starrocks#21861]
## Enhancement

```sql
CTE X = (A LEFT JOIN B ON A.fk = B.pk)

X JOIN Y ON (A.col = Y.col1 AND B.col = Y.col2)
X JOIN Z ON (A.col = Z.col)
```

In this case: 
1. `X JOIN Z` could be changed to `A JOIN Z`, because the joins inside X doesn't add anything useful.
2. Generally, `A LEFT JOIN B` could be transformed to `A` if 
    a. The cardinality of `A` is equal to `A LEFT JOIN B ON A.fk = B.pk`, it could be guaranteed by foreign key constraints
    b. there's no output column from `B`
5. This case is only possible after inlining CTE, bc in normal left join the `JOIN ON` clause is required 

To optimize this case:
1. Implement unchecked foreign key constraints: it's already done
2. Based on the foreign key constraints, implement a rule to eliminate this useless left join

**Comment by rcauble** [comment]
If it'd help we can easily output the cardinality as a hint in the SQL. Something like  /*+ MANY_TO_ONE */ LEFT JOIN.

**Comment by mofeiatwork** [comment]
> 

The foreign key & unique key constraint should be like this: https://github.com/StarRocks/starrocks/issues/17930

**Comment by jiacheng-celonis** [comment]
Yes, we can annotate all the foreign key relationship in our schema. We know all of them.

**Comment by rcauble** [comment]
In case we also want this to apply to temp tables (not in our schema), the SQL-based hint might help. But yes the schema-basedd tables will be most common.

**Comment by mofeiatwork** [comment]
good point, the SQL-based hint will be helpful for debugging, performance tuning, generated sql

**Comment by Seaven** [comment]
refs: https://github.com/StarRocks/starrocks/pull/27006
