### ISSUE TITLE
insert overwrite partition not support variable

### ISSUE THREAD

**Issue by kele2013** [StarRocks/starrocks#21880]
## Feature request

**Is your feature request related to a problem? Please describe.**
when I  INSERT OVERWRITE  the month parition table, the partiton filed is change according to each month, so i use the statement
![549e2e8526f52421f969f303af00b2a](https://user-images.githubusercontent.com/4188183/232955731-4169354a-56ba-4b40-a59e-d9c2debf3b72.png)
but it not worked well

**Describe the solution you'd like**
I  expect the insert overwrite support the variable expression

**Describe alternatives you've considered**

**Additional context**

**Comment by jaogoy** [comment]
1. StarRocks doesn't support it yet, we can think about it and implement it.
    - If it's difficult to implement with function call in partition parameter, maybe we can use a SELECT column name created with a expression alias
2. What's the `${current_moth}`, it should be a column name if StarRocks had already supported it.
