### ISSUE TITLE
uninstall plugin error

### ISSUE THREAD

**Issue by wuhua08** [StarRocks/starrocks#2191]
### Steps to reproduce the behavior (Required)
1. INSTALL PLUGIN FROM "/fe/plugins/xxxx-xxx.zip";
2. UNINSTALL PLUGIN xxxx-xxx;

UNINSTALL PLUGIN xxxx-xxx
                            ^
Encountered: -
Expected

plugin name  contains char '-'  can`t uninstall, but it can be installed

### Expected behavior (Required)
uninstall  success
### Real behavior (Required)
uninstall  error
### StarRocks version (Required)
1.19.3 e65759c

**Comment by stdpain** [comment]
It seems to be a parsing problem, which can be temporarily circumvented with the following command.
```
UNINSTALL PLUGIN "xxxx-xxx";
```

**Comment by wuhua08** [comment]
> It seems to be a parsing problem, which can be temporarily circumvented with the following command.
> 
> ```
> UNINSTALL PLUGIN "xxxx-xxx";
> ```

OK, get it
