### ISSUE TITLE
#18597 这个Feature 在哪个版本发布？

### ISSUE THREAD

**Issue by arthurcommon** [StarRocks/starrocks#22018]
hi 开发者们
感谢你们帮我解决了我之前提的增加一个函数的需求
想进一步确认下 https://github.com/StarRocks/starrocks/pull/18597   这个Feature是不是加入到了 3.0 的版本。
因为 2.5.4 我已经更新，没有找到这个函数。
麻烦开发者们给确认下，是不是更新到了 3.0 这个版本。
再次感谢

**Comment by kangkaisen** [comment]
https://github.com/StarRocks/starrocks/pull/22175 we will support this function in 3.0 version.
