### ISSUE TITLE
Different schema information.

### ISSUE THREAD

**Issue by yongbingwang** [StarRocks/starrocks#2206]
different schema information between information_schema and BE thrift TScanOpenResult.
### Steps to reproduce the behavior (Required)
![middle_img_v2_a1454439-938e-4141-8ba2-6219c10f203g](https://user-images.githubusercontent.com/86867342/146343989-8487c9b9-c515-4d52-abd4-da3ff0155d20.png)
![middle_img_v2_ce80d8de-a67d-4704-9531-0f5536823a2g](https://user-images.githubusercontent.com/86867342/146344002-fb041427-44c5-4e30-9011-1b029f93fc73.png)
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - all

**Comment by Astralidea** [comment]
This because mysql does not have largeint type, so there is no standard to define what the result should be.
It should be modified for the impact of BI software.
