### ISSUE TITLE
Incremental refresh of Materialized View

### ISSUE THREAD

**Issue by dengjoy2000** [StarRocks/starrocks#22147]
**Describe the solution you'd like**
Now SR support MV of all data model，it's  great!  But it maybe slow and expensive when refresh a large MV. Can SR support MV incremental refresh like MVs refreshing in Oracle in future？

**Additional context**
In ORACLE，MV can be refreshed fully, and also can be refreshed incrementally, which can greatly save run time and computing resources. The incremental refresh in Oracle is based on MV log.

**Comment by imay** [comment]
This is in our roadmap now.
