### ISSUE TITLE
Routine Load Kafka Need Support More Message Type

### ISSUE THREAD

**Issue by HelloSrauker** [StarRocks/starrocks#2233]
## Enhancement
In official documents,I found Routine load Kafka only supports messages in CSV format.For a more general load method,Would you like to add a supported json and avro？

**Comment by HelloSrauker** [comment]
I later found that it supports JSON format import (In other page), which is enough for me. But can you change the document? At first, I only found that the document supports CSV format,

导入示例
环境要求
支持访问无认证或使用 SSL 方式认证的 Kafka 集群。
支持的消息格式为 CSV 文本格式，每一个 message 为一行，且行尾不包含换行符。
仅支持 Kafka 0.10.0.0(含) 以上版本。

**Comment by jaogoy** [comment]
All types of load support CSV and JSON.
If there is anything unclear in the document, point it out.
