### ISSUE TITLE
Aggregate model add key column why not need keyword 'key'?

### ISSUE THREAD

**Issue by srikker** [StarRocks/starrocks#22579]
## General Question

When adding a column to the aggregation model without aggregation type, the key column will be automatically generated.

Does it need to be consistent with other models?

**version**
Until version 3.0.0-rc02

**Comment by alberttwong** [comment]
I think it's only an aggregation thing.   I believe we support "replace", "sum", "min", "max"

**Comment by alberttwong** [comment]
https://github.com/StarRocks/starrocks/issues/22793
