### ISSUE TITLE
Integrate with Linkedin's Datahub project

### ISSUE THREAD

**Issue by anishone** [StarRocks/starrocks#22720]
## Enhancement
Datahub is widely used for Metadata management and data governance. It already supports MySQL and many other data warehouses. But Starrocks is prominently missing in it. Please add support so that we can manage our data warehouses effectively. 

https://github.com/datahub-project/datahub

**Comment by radioliu92** [comment]
+1 我们也需要, datahub在用mysql方式连接starrocks时发现 字段描述 拉取失败
