### ISSUE TITLE
使用Helm部署集群时，如果所有组件都宕机，集群不可恢复

### ISSUE THREAD

**Issue by artanis-zhou** [StarRocks/starrocks#22760]
当fe开启持久化时：
    如果所有fe节点宕机，则fe集群不可恢复
当be不开启持久化时：
    如果所有fe节点宕机，be集群过一段时间会显示正常，但是be集群可能会连不上，手动连接上后，alive为false，日志显示cluster_id不同。
    
当使用Helm uninstall集群时，只有operator组件会删除，be，fe没有响应。再次使用helm install，operator会被创建，但是be,fe会被删除。此时再次helm uninstall，集群才会被完整移除。

请问有什么办法能在所有组件都宕机后，能够恢复集群的办法，谢谢。

**Comment by kevincai** [comment]
能否完整描述一下重现步骤, 例如宕机前的配置, 如何模拟的宕机.

**Comment by artanis-zhou** [comment]
尝试过固定POD的IP，无效

**Comment by kevincai** [comment]
> fe开启持久化，副本数=3.手动删除2或者3个pod直到其pod自动重建后，发现三个pod全部不可用，可稳定复现。

非预期, 应该可用, 只要PVC挂载正确且数据有保存

> 单fe测试：fe开启持久化，副本数=1，手动删除pod，自动重建后，可恢复成功状态。

预期内, 单FE的数据由PVC保证, PVC数据丢失, 则FE的状态丢失

> 无持久化测试：fe关闭持久化，副本数=3。手动删除2或者3个pod直到自动重建，fe显示恢复正常，实际连接不上be。

无持久化时, FE在丢失双FOLLOWER或者单节点(LEADER或者FOLLOWER) 都可工作, 丢失双节点或三节点且包含LEADER节点, 则集群不可恢复, 即使重建成功, FE数据也全部丢失.

**Comment by kevincai** [comment]
> fe开启持久化，副本数=3.手动删除2或者3个pod直到其pod自动重建后，发现三个pod全部不可用，可稳定复现。

这个需要operator升级到1.6.1, 支持默认FE的所有POD同时重建, 并且fe版本使用2.5.5及以上, 或者3.0.0版本, 方可正常重启并恢复.

**Comment by artanis-zhou** [comment]
我部署是，helm版本为1.6.1，operator镜像用的是latest，应该是1.6.1. fe和be的版本为2.5.4.所以，我可以直接修改镜像版本从而解决这个问题吗。
helm下个版本什么时候发布呢，非常感谢

**Comment by kevincai** [comment]
先尝试修改一下fe/be的版本验证一下看看. helm下个版本时间需要看积攒的问题修复有多少, 以及问题严重程度.

**Comment by artanis-zhou** [comment]
好的，我去试试

**Comment by kevincai** [comment]
can close this issue for now.

**Comment by artanis-zhou** [comment]
ok
