### ISSUE TITLE
[function]oct and oct_length

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#22803]
oct related functions are very common to see in other database systems. However, StarRocks doesn't have any.

For example: 
MySQL
https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_oct
https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_octet-length

StarRocks has the conv function: https://docs.starrocks.io/en-us/latest/sql-reference/sql-functions/math-functions/conv
It's doable. But it is better to have oct and oct_length.

**Comment by kateshaowanjou** [comment]
@wuxiaobai24 Can you make a comment here so I can assign this issue to you?

**Comment by wuxiaobai24** [comment]
yap, I want to take this issue, please assign this issue to me. @kateshaowanjou

**Comment by kateshaowanjou** [comment]
@wuxiaobai24 Hi buddy, just checking in on you. Are you still working on this issue？If you have any questions, feel free to join WeChat for discussion: https://ma3you.com/articles_qrcode_show/b12e90J.png?le_time=220907203008013206
❤️

**Comment by wuxiaobai24** [comment]
@kateshaowanjou I'm still working on it. I'll do it as soon as possible. BTW, the URL is 404.

**Comment by kateshaowanjou** [comment]
@wuxiaobai24 Noted. Here's the updated link: https://853921.ma3you.cn/articles/b12e90J/
