### ISSUE TITLE
一个类似于ck中bitmapBuild 的函数，直接将整列转化成位图

### ISSUE THREAD

**Issue by 1342671130** [StarRocks/starrocks#22870]
## Feature request

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LiShuMing** [comment]
how about `to_bitmap`? https://docs.starrocks.io/en-us/2.5/sql-reference/sql-functions/bitmap-functions/to_bitmap

**Comment by ucasfl** [comment]
> how about `to_bitmap`? https://docs.starrocks.io/en-us/2.5/sql-reference/sql-functions/bitmap-functions/to_bitmap

Not same, the input of `bitmapBuild` in ClickHouse is an array: https://clickhouse.com/docs/en/sql-reference/functions/bitmap-functions#bitmapbuild

**Comment by LiShuMing** [comment]
like this? array_to_bitmap?

https://docs.starrocks.io/en-us/latest/sql-reference/sql-functions/array-functions/array_to_bitmap

**Comment by ucasfl** [comment]
> like this? array_to_bitmap?
> 
> https://docs.starrocks.io/en-us/latest/sql-reference/sql-functions/array-functions/array_to_bitmap

Yes.

**Comment by jaogoy** [comment]
@ucasfl @1342671130 So, if it's satisfied, you can close it.
