### ISSUE TITLE
异步物化视图 partition_refresh_number 参数导致非分区键表更新  物化视图不能全部更新

### ISSUE THREAD

**Issue by caohb1985** [StarRocks/starrocks#23043]
### Steps to reproduce the behavior (Required)
CREATE TABLE `dwd_oc_OcClassorder` (
  `orderId` varchar(108) NOT NULL COMMENT "订单标识",
  `coCreateddatesss` datetime NOT NULL COMMENT "创建时间",
  `descClass` varchar(65533) NULL COMMENT "异常信息(建议用json格式存储各个异常字段及原值)"
) ENGINE=OLAP
PRIMARY KEY(`orderId`, `coCreateddatesss`)
COMMENT "班级订单表"
PARTITION BY RANGE(`coCreateddatesss`)
(PARTITION p202301 VALUES [("2023-01-01 00:00:00"), ("2023-02-01 00:00:00")),
PARTITION p202302 VALUES [("2023-02-01 00:00:00"), ("2023-03-01 00:00:00")),
PARTITION p202303 VALUES [("2023-03-01 00:00:00"), ("2023-04-01 00:00:00")),
PARTITION p202304 VALUES [("2023-04-01 00:00:00"), ("2023-05-01 00:00:00")),
PARTITION p202305 VALUES [("2023-05-01 00:00:00"), ("2023-06-01 00:00:00")),
PARTITION p202306 VALUES [("2023-06-01 00:00:00"), ("2023-07-01 00:00:00")),
PARTITION p202307 VALUES [("2023-07-01 00:00:00"), ("2023-08-01 00:00:00")),
PARTITION p202308 VALUES [("2023-08-01 00:00:00"), ("2023-09-01 00:00:00")),
PARTITION p202309 VALUES [("2023-09-01 00:00:00"), ("2023-10-01 00:00:00")),
PARTITION p202310 VALUES [("2023-10-01 00:00:00"), ("2023-11-01 00:00:00")),
PARTITION p202311 VALUES [("2023-11-01 00:00:00"), ("2023-12-01 00:00:00")),
PARTITION p202312 VALUES [("2023-12-01 00:00:00"), ("2024-01-01 00:00:00")))
DISTRIBUTED BY HASH(`orderId`) BUCKETS 6
PROPERTIES (
"replication_num" = "1",
"colocate_with" = "orderIdGroup",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "true",
"compression" = "LZ4"
);

CREATE TABLE `dwd_oc_OcClassorder` (
  `orderId` varchar(108) NOT NULL COMMENT "订单标识",
  `coCreateddatesss` datetime NOT NULL COMMENT "创建时间",
  `descClass` varchar(65533) NULL COMMENT "异常信息(建议用json格式存储各个异常字段及原值)"
) ENGINE=OLAP
PRIMARY KEY(`orderId`, `coCreateddatesss`)
COMMENT "班级订单表"
PARTITION BY RANGE(`coCreateddatesss`)
(PARTITION p202301 VALUES [("2023-01-01 00:00:00"), ("2023-02-01 00:00:00")),
PARTITION p202302 VALUES [("2023-02-01 00:00:00"), ("2023-03-01 00:00:00")),
PARTITION p202303 VALUES [("2023-03-01 00:00:00"), ("2023-04-01 00:00:00")),
PARTITION p202304 VALUES [("2023-04-01 00:00:00"), ("2023-05-01 00:00:00")),
PARTITION p202305 VALUES [("2023-05-01 00:00:00"), ("2023-06-01 00:00:00")),
PARTITION p202306 VALUES [("2023-06-01 00:00:00"), ("2023-07-01 00:00:00")),
PARTITION p202307 VALUES [("2023-07-01 00:00:00"), ("2023-08-01 00:00:00")),
PARTITION p202308 VALUES [("2023-08-01 00:00:00"), ("2023-09-01 00:00:00")),
PARTITION p202309 VALUES [("2023-09-01 00:00:00"), ("2023-10-01 00:00:00")),
PARTITION p202310 VALUES [("2023-10-01 00:00:00"), ("2023-11-01 00:00:00")),
PARTITION p202311 VALUES [("2023-11-01 00:00:00"), ("2023-12-01 00:00:00")),
PARTITION p202312 VALUES [("2023-12-01 00:00:00"), ("2024-01-01 00:00:00")))
DISTRIBUTED BY HASH(`orderId`) BUCKETS 6
PROPERTIES (
"replication_num" = "1",
"colocate_with" = "orderIdGroup",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "true",
"compression" = "LZ4"
);

CREATE MATERIALIZED VIEW `dwd_oc_OcOrder_extend`
COMMENT "MATERIALIZED_VIEW"
PARTITION BY (date_trunc('month', `orderCreateddate`))
DISTRIBUTED BY HASH(`orderId`) BUCKETS 20
REFRESH ASYNC
PROPERTIES (
"replication_num" = "1",
"auto_refresh_partitions_limit" = "12",
"partition_refresh_number" = "1"
)
AS SELECT `a`.`orderId`, `a`.`orderCreateddate`, `a`.`descOrder`, `b`.`descClass`, `b`.`coCreateddatesss`
FROM `dwd_flink_test`.`dwd_oc_OcOrder` AS `a` LEFT OUTER JOIN `dwd_flink_test`.`dwd_oc_OcClassorder` AS `b` ON `a`.`orderId` = `b`.`orderId`;

### Expected behavior (Required)
dwd_oc_OcClassorder表更新  dwd_oc_OcOrder_extend 物化视图更新
### Real behavior (Required)
dwd_oc_OcClassorder表更新  dwd_oc_OcOrder_extend 物化视图只更新了第一个分区
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.5.5 24c1eca

代码跟踪发现的问题
public Set<String> getUpdatedPartitionNamesOfOlapTable(OlapTable baseTable) 

basePartition.getVisibleVersion() > basePartitionInfo.getVersion()  为 false

**Comment by Astralidea** [comment]
This already fix by https://github.com/StarRocks/starrocks/pull/21619 but forgot to merge. I will merge it and fix it in next version.

**Comment by caohb1985** [comment]
PartitionBasedMaterializedViewRefreshProcessor   

public void processTaskRun(TaskRunContext context) throws Exception {
 // execute the ExecPlan of insert outside lock
        refreshMaterializedView(mvContext, execPlan, insertStmt);

        // insert execute successfully, update the meta of materialized view according to ExecPlan

        if (mvContext.hasNextBatchPartition()) {
            generateNextTaskRun();
            return;
        }

        updateMeta(execPlan);
    }
先执行generateNextTaskRun()   而后updateMeta
本地修改测试可行

**Comment by caohb1985** [comment]
https://github.com/StarRocks/starrocks/pull/21619  这个问题跟我遇到的问题还不太一样

**Comment by caohb1985** [comment]
同时给个建议  可否跟主表一样，只更新对应分区

**Comment by Astralidea** [comment]
> #21619 这个问题跟我遇到的问题还不太一样

我想复现你的问题，你可以提供 dwd_oc_OcOrder 这个表吗？我看你给的两个表都是dwd_oc_OcClassorder
如果可以给一些简单的测试数据就更好了。

**Comment by caohb1985** [comment]
select * FROM dwd_oc_OcOrder dooo 

update dwd_oc_OcOrder set descOrder = 'asdsssasddsdfsfd' WHERE  orderId = '1111';

select * FROM dwd_oc_OcClassorder dooc ;

UPDATE dwd_flink_test.dwd_oc_OcClassorder
SET descClass='gssssdsdsdsdsddjjkjkjll'
WHERE orderId='1111';


SELECT * FROM dwd_oc_OcOrder_extend;


每张表只有三个字段  全是假数据

**Comment by caohb1985** [comment]
我想表达的是可否在子表更新的时候    找到对应关系的主表分区，更新对应分区，     这样可以减少更新的范围

**Comment by caohb1985** [comment]
我想表达的是可否在子表更新的时候 找到对应关系的主表分区，更新对应分区， 这样可以减少更新的范围









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "StarRocks/starrocks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月9日(星期二) 下午5:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [StarRocks/starrocks] 异步物化视图 partition_refresh_number 参数导致非分区键表更新  物化视图不能全部更新 (Issue #23043)





  
同时给个建议 可否跟主表一样，只更新对应分区
  
你说的是忽略另一个表的更新，只是主表更新的时候更新对应分区吗？可以考虑使用excluded_trigger_tables忽略非主表的触发刷新。

**Comment by Astralidea** [comment]
方便的话给我一下dwd_oc_OcOrder的表结构，或者你告诉我这个表的分区是跟dwd_oc_OcClassorder是一样的？

**Comment by caohb1985** [comment]
CREATE TABLE dwd_oc_OcClassorder (
orderId varchar(108) NOT NULL COMMENT "订单标识",
coCreateddatesss datetime NOT NULL COMMENT "创建时间",
descClass varchar(65533) NULL COMMENT "异常信息(建议用json格式存储各个异常字段及原值)"
) ENGINE=OLAP
PRIMARY KEY(orderId, coCreateddatesss)
COMMENT "班级订单表"
PARTITION BY RANGE(coCreateddatesss)
(PARTITION p202301 VALUES [("2023-01-01 00:00:00"), ("2023-02-01 00:00:00")),
PARTITION p202302 VALUES [("2023-02-01 00:00:00"), ("2023-03-01 00:00:00")),
PARTITION p202303 VALUES [("2023-03-01 00:00:00"), ("2023-04-01 00:00:00")),
PARTITION p202304 VALUES [("2023-04-01 00:00:00"), ("2023-05-01 00:00:00")),
PARTITION p202305 VALUES [("2023-05-01 00:00:00"), ("2023-06-01 00:00:00")),
PARTITION p202306 VALUES [("2023-06-01 00:00:00"), ("2023-07-01 00:00:00")),
PARTITION p202307 VALUES [("2023-07-01 00:00:00"), ("2023-08-01 00:00:00")),
PARTITION p202308 VALUES [("2023-08-01 00:00:00"), ("2023-09-01 00:00:00")),
PARTITION p202309 VALUES [("2023-09-01 00:00:00"), ("2023-10-01 00:00:00")),
PARTITION p202310 VALUES [("2023-10-01 00:00:00"), ("2023-11-01 00:00:00")),
PARTITION p202311 VALUES [("2023-11-01 00:00:00"), ("2023-12-01 00:00:00")),
PARTITION p202312 VALUES [("2023-12-01 00:00:00"), ("2024-01-01 00:00:00")))
DISTRIBUTED BY HASH(orderId) BUCKETS 6
PROPERTIES (
"replication_num" = "1",
"colocate_with" = "orderIdGroup",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "true",
"compression" = "LZ4"
);

CREATE TABLE dwd_oc_OcClassorder (
orderId varchar(108) NOT NULL COMMENT "订单标识",
coCreateddatesss datetime NOT NULL COMMENT "创建时间",
descClass varchar(65533) NULL COMMENT "异常信息(建议用json格式存储各个异常字段及原值)"
) ENGINE=OLAP
PRIMARY KEY(orderId, coCreateddatesss)
COMMENT "班级订单表"
PARTITION BY RANGE(coCreateddatesss)
(PARTITION p202301 VALUES [("2023-01-01 00:00:00"), ("2023-02-01 00:00:00")),
PARTITION p202302 VALUES [("2023-02-01 00:00:00"), ("2023-03-01 00:00:00")),
PARTITION p202303 VALUES [("2023-03-01 00:00:00"), ("2023-04-01 00:00:00")),
PARTITION p202304 VALUES [("2023-04-01 00:00:00"), ("2023-05-01 00:00:00")),
PARTITION p202305 VALUES [("2023-05-01 00:00:00"), ("2023-06-01 00:00:00")),
PARTITION p202306 VALUES [("2023-06-01 00:00:00"), ("2023-07-01 00:00:00")),
PARTITION p202307 VALUES [("2023-07-01 00:00:00"), ("2023-08-01 00:00:00")),
PARTITION p202308 VALUES [("2023-08-01 00:00:00"), ("2023-09-01 00:00:00")),
PARTITION p202309 VALUES [("2023-09-01 00:00:00"), ("2023-10-01 00:00:00")),
PARTITION p202310 VALUES [("2023-10-01 00:00:00"), ("2023-11-01 00:00:00")),
PARTITION p202311 VALUES [("2023-11-01 00:00:00"), ("2023-12-01 00:00:00")),
PARTITION p202312 VALUES [("2023-12-01 00:00:00"), ("2024-01-01 00:00:00")))
DISTRIBUTED BY HASH(orderId) BUCKETS 6
PROPERTIES (
"replication_num" = "1",
"colocate_with" = "orderIdGroup",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "true",
"compression" = "LZ4"
);

CREATE MATERIALIZED VIEW dwd_oc_OcOrder_extend
COMMENT "MATERIALIZED_VIEW"
PARTITION BY (date_trunc('month', orderCreateddate))
DISTRIBUTED BY HASH(orderId) BUCKETS 20
REFRESH ASYNC
PROPERTIES (
"replication_num" = "1",
"auto_refresh_partitions_limit" = "12",
"partition_refresh_number" = "1"
)
AS SELECT a.orderId, a.orderCreateddate, a.descOrder, b.descClass, b.coCreateddatesss
FROM dwd_flink_test.dwd_oc_OcOrder AS a LEFT OUTER JOIN dwd_flink_test.dwd_oc_OcClassorder AS b ON a.orderId = b.orderId;

**Comment by caohb1985** [comment]
dwd_oc_OcClassorder   这张表建不建分区都是一样的

**Comment by caohb1985** [comment]
CREATE TABLE `dwd_oc_OcOrder` (
  `orderId` varchar(108) NOT NULL COMMENT "订单表主键",
  `orderCreateddate` datetime NOT NULL COMMENT "创建时间",
  `descOrder` varchar(108) NOT NULL COMMENT "描述"
) ENGINE=OLAP 
PRIMARY KEY(`orderId`, `orderCreateddate`)
COMMENT "订单表"
PARTITION BY RANGE(`orderCreateddate`)
(PARTITION p202301 VALUES [("2023-01-01 00:00:00"), ("2023-02-01 00:00:00")),
PARTITION p202302 VALUES [("2023-02-01 00:00:00"), ("2023-03-01 00:00:00")),
PARTITION p202303 VALUES [("2023-03-01 00:00:00"), ("2023-04-01 00:00:00")),
PARTITION p202304 VALUES [("2023-04-01 00:00:00"), ("2023-05-01 00:00:00")),
PARTITION p202305 VALUES [("2023-05-01 00:00:00"), ("2023-06-01 00:00:00")),
PARTITION p202306 VALUES [("2023-06-01 00:00:00"), ("2023-07-01 00:00:00")),
PARTITION p202307 VALUES [("2023-07-01 00:00:00"), ("2023-08-01 00:00:00")),
PARTITION p202308 VALUES [("2023-08-01 00:00:00"), ("2023-09-01 00:00:00")),
PARTITION p202309 VALUES [("2023-09-01 00:00:00"), ("2023-10-01 00:00:00")),
PARTITION p202310 VALUES [("2023-10-01 00:00:00"), ("2023-11-01 00:00:00")),
PARTITION p202311 VALUES [("2023-11-01 00:00:00"), ("2023-12-01 00:00:00")),
PARTITION p202312 VALUES [("2023-12-01 00:00:00"), ("2024-01-01 00:00:00")))
DISTRIBUTED BY HASH(`orderId`) BUCKETS 6 
PROPERTIES (
"replication_num" = "1",
"colocate_with" = "orderIdGroup",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"compression" = "LZ4"
);

**Comment by caohb1985** [comment]
只是为了测试建的临时表

**Comment by Astralidea** [comment]
感谢你提供的信息，这个问题我已经在2.5.5复现。并且我在branch-2.5的最新分支验证了下已经得到解决。但是我不太确定是哪个PR解决的。可能我得翻一下。
因此这个问题将在2.5.6版本中解决。我的复现步骤如下：

```
CREATE TABLE dwd_oc_OcClassorder (
orderId varchar(108) NOT NULL COMMENT "订单标识",
coCreateddatesss datetime NOT NULL COMMENT "创建时间",
descClass varchar(65533) NULL COMMENT "异常信息(建议用json格式存储各个异常字段及原值)"
) ENGINE=OLAP
PRIMARY KEY(orderId, coCreateddatesss)
COMMENT "班级订单表"
PARTITION BY RANGE(coCreateddatesss)
(PARTITION p202301 VALUES [("2023-01-01 00:00:00"), ("2023-02-01 00:00:00")),
PARTITION p202302 VALUES [("2023-02-01 00:00:00"), ("2023-03-01 00:00:00")),
PARTITION p202303 VALUES [("2023-03-01 00:00:00"), ("2023-04-01 00:00:00")),
PARTITION p202304 VALUES [("2023-04-01 00:00:00"), ("2023-05-01 00:00:00")),
PARTITION p202305 VALUES [("2023-05-01 00:00:00"), ("2023-06-01 00:00:00")),
PARTITION p202306 VALUES [("2023-06-01 00:00:00"), ("2023-07-01 00:00:00")),
PARTITION p202307 VALUES [("2023-07-01 00:00:00"), ("2023-08-01 00:00:00")),
PARTITION p202308 VALUES [("2023-08-01 00:00:00"), ("2023-09-01 00:00:00")),
PARTITION p202309 VALUES [("2023-09-01 00:00:00"), ("2023-10-01 00:00:00")),
PARTITION p202310 VALUES [("2023-10-01 00:00:00"), ("2023-11-01 00:00:00")),
PARTITION p202311 VALUES [("2023-11-01 00:00:00"), ("2023-12-01 00:00:00")),
PARTITION p202312 VALUES [("2023-12-01 00:00:00"), ("2024-01-01 00:00:00")))
DISTRIBUTED BY HASH(orderId) BUCKETS 6
PROPERTIES (
"replication_num" = "1",
"colocate_with" = "orderIdGroup",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "true",
"compression" = "LZ4"
);

CREATE TABLE dwd_oc_OcOrder (
orderId varchar(108) NOT NULL COMMENT "订单表主键",
orderCreateddate datetime NOT NULL COMMENT "创建时间",
descOrder varchar(108) NOT NULL COMMENT "描述"
) ENGINE=OLAP
PRIMARY KEY(orderId, orderCreateddate)
COMMENT "订单表"
PARTITION BY RANGE(orderCreateddate)
(PARTITION p202301 VALUES [("2023-01-01 00:00:00"), ("2023-02-01 00:00:00")),
PARTITION p202302 VALUES [("2023-02-01 00:00:00"), ("2023-03-01 00:00:00")),
PARTITION p202303 VALUES [("2023-03-01 00:00:00"), ("2023-04-01 00:00:00")),
PARTITION p202304 VALUES [("2023-04-01 00:00:00"), ("2023-05-01 00:00:00")),
PARTITION p202305 VALUES [("2023-05-01 00:00:00"), ("2023-06-01 00:00:00")),
PARTITION p202306 VALUES [("2023-06-01 00:00:00"), ("2023-07-01 00:00:00")),
PARTITION p202307 VALUES [("2023-07-01 00:00:00"), ("2023-08-01 00:00:00")),
PARTITION p202308 VALUES [("2023-08-01 00:00:00"), ("2023-09-01 00:00:00")),
PARTITION p202309 VALUES [("2023-09-01 00:00:00"), ("2023-10-01 00:00:00")),
PARTITION p202310 VALUES [("2023-10-01 00:00:00"), ("2023-11-01 00:00:00")),
PARTITION p202311 VALUES [("2023-11-01 00:00:00"), ("2023-12-01 00:00:00")),
PARTITION p202312 VALUES [("2023-12-01 00:00:00"), ("2024-01-01 00:00:00")))
DISTRIBUTED BY HASH(orderId) BUCKETS 6
PROPERTIES (
"replication_num" = "1",
"colocate_with" = "orderIdGroup",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"compression" = "LZ4"
);


INSERT INTO dwd_oc_OcClassorder (orderId, coCreateddatesss, descClass) 
VALUES 
('order_1', '2023-01-15 00:00:00', '{"error":"error_detail_1"}'),
('order_2', '2023-02-15 00:00:00', '{"error":"error_detail_2"}'),
('order_3', '2023-03-15 00:00:00', '{"error":"error_detail_3"}'),
('order_4', '2023-04-15 00:00:00', '{"error":"error_detail_4"}'),
('order_5', '2023-05-15 00:00:00', '{"error":"error_detail_5"}'),
('order_6', '2023-06-15 00:00:00', '{"error":"error_detail_6"}'),
('order_7', '2023-07-15 00:00:00', '{"error":"error_detail_7"}'),
('order_8', '2023-08-15 00:00:00', '{"error":"error_detail_8"}'),
('order_9', '2023-09-15 00:00:00', '{"error":"error_detail_9"}'),
('order_10', '2023-10-15 00:00:00', '{"error":"error_detail_10"}'),
('order_11', '2023-11-15 00:00:00', '{"error":"error_detail_11"}'),
('order_12', '2023-12-15 00:00:00', '{"error":"error_detail_12"}');

INSERT INTO dwd_oc_OcOrder (orderId, orderCreateddate, descOrder) 
VALUES 
('order_1', '2023-01-15 00:00:00', '{"error":"error_detail_1"}'),
('order_2', '2023-02-15 00:00:00', '{"error":"error_detail_2"}'),
('order_3', '2023-03-15 00:00:00', '{"error":"error_detail_3"}'),
('order_4', '2023-04-15 00:00:00', '{"error":"error_detail_4"}'),
('order_5', '2023-05-15 00:00:00', '{"error":"error_detail_5"}'),
('order_6', '2023-06-15 00:00:00', '{"error":"error_detail_6"}'),
('order_7', '2023-07-15 00:00:00', '{"error":"error_detail_7"}'),
('order_8', '2023-08-15 00:00:00', '{"error":"error_detail_8"}'),
('order_9', '2023-09-15 00:00:00', '{"error":"error_detail_9"}'),
('order_10', '2023-10-15 00:00:00', '{"error":"error_detail_10"}'),
('order_11', '2023-11-15 00:00:00', '{"error":"error_detail_11"}'),
('order_12', '2023-12-15 00:00:00', '{"error":"error_detail_12"}');

CREATE MATERIALIZED VIEW dwd_oc_OcOrder_extend
COMMENT "MATERIALIZED_VIEW"
PARTITION BY (date_trunc('month', orderCreateddate))
DISTRIBUTED BY HASH(orderId) BUCKETS 20
REFRESH ASYNC
PROPERTIES (
"replication_num" = "1",
"auto_refresh_partitions_limit" = "12",
"partition_refresh_number" = "1"
)
AS SELECT a.orderId, a.orderCreateddate, a.descOrder, b.descClass, b.coCreateddatesss
FROM dwd_oc_OcOrder AS a LEFT OUTER JOIN dwd_oc_OcClassorder AS b ON a.orderId = b.orderId;

select * from information_schema.task_runs;

INSERT INTO dwd_oc_OcClassorder (orderId, coCreateddatesss, descClass) 
VALUES 
('order_1', '2023-01-15 00:00:00', '{"error":"after_udpate_1"}'),
('order_2', '2023-02-15 00:00:00', '{"error":"after_udpate_2"}'),
('order_3', '2023-03-15 00:00:00', '{"error":"after_udpate_3"}'),
('order_4', '2023-04-15 00:00:00', '{"error":"after_udpate_4"}'),
('order_5', '2023-05-15 00:00:00', '{"error":"after_udpate_5"}'),
('order_6', '2023-06-15 00:00:00', '{"error":"after_udpate_6"}'),
('order_7', '2023-07-15 00:00:00', '{"error":"after_udpate_7"}'),
('order_8', '2023-08-15 00:00:00', '{"error":"after_udpate_8"}'),
('order_9', '2023-09-15 00:00:00', '{"error":"after_udpate_9"}'),
('order_10', '2023-10-15 00:00:00', '{"error":"after_udpate_10"}'),
('order_11', '2023-11-15 00:00:00', '{"error":"after_udpate_11"}'),
('order_12', '2023-12-15 00:00:00', '{"error":"after_udpate_12"}');

in branch-2.5 [5c9cb2a](https://github.com/StarRocks/starrocks/commit/5c9cb2ad3c76c8e2a7363f775c20a7e6416b22b8)
mysql> SELECT * FROM dwd_oc_OcOrder_extend;
+----------+---------------------+-----------------------------+-----------------------------+---------------------+
| orderId  | orderCreateddate    | descOrder                   | descClass                   | coCreateddatesss    |
+----------+---------------------+-----------------------------+-----------------------------+---------------------+
| order_4  | 2023-04-15 00:00:00 | {"error":"error_detail_4"}  | {"error":"after_udpate_4"}  | 2023-04-15 00:00:00 |
| order_2  | 2023-02-15 00:00:00 | {"error":"error_detail_2"}  | {"error":"after_udpate_2"}  | 2023-02-15 00:00:00 |
| order_9  | 2023-09-15 00:00:00 | {"error":"error_detail_9"}  | {"error":"after_udpate_9"}  | 2023-09-15 00:00:00 |
| order_8  | 2023-08-15 00:00:00 | {"error":"error_detail_8"}  | {"error":"after_udpate_8"}  | 2023-08-15 00:00:00 |
| order_12 | 2023-12-15 00:00:00 | {"error":"error_detail_12"} | {"error":"after_udpate_12"} | 2023-12-15 00:00:00 |
| order_6  | 2023-06-15 00:00:00 | {"error":"error_detail_6"}  | {"error":"after_udpate_6"}  | 2023-06-15 00:00:00 |
| order_1  | 2023-01-15 00:00:00 | {"error":"error_detail_1"}  | {"error":"after_udpate_1"}  | 2023-01-15 00:00:00 |
| order_3  | 2023-03-15 00:00:00 | {"error":"error_detail_3"}  | {"error":"after_udpate_3"}  | 2023-03-15 00:00:00 |
| order_5  | 2023-05-15 00:00:00 | {"error":"error_detail_5"}  | {"error":"after_udpate_5"}  | 2023-05-15 00:00:00 |
| order_7  | 2023-07-15 00:00:00 | {"error":"error_detail_7"}  | {"error":"after_udpate_7"}  | 2023-07-15 00:00:00 |
| order_10 | 2023-10-15 00:00:00 | {"error":"error_detail_10"} | {"error":"after_udpate_10"} | 2023-10-15 00:00:00 |
| order_11 | 2023-11-15 00:00:00 | {"error":"error_detail_11"} | {"error":"after_udpate_11"} | 2023-11-15 00:00:00 |
+----------+---------------------+-----------------------------+-----------------------------+---------------------+

in 2.5.5
mysql> SELECT * FROM dwd_oc_OcOrder_extend;
+----------+---------------------+-----------------------------+-----------------------------+---------------------+
| orderId  | orderCreateddate    | descOrder                   | descClass                   | coCreateddatesss    |
+----------+---------------------+-----------------------------+-----------------------------+---------------------+
| order_2  | 2023-02-15 00:00:00 | {"error":"error_detail_2"}  | {"error":"error_detail_2"}  | 2023-02-15 00:00:00 |
| order_5  | 2023-05-15 00:00:00 | {"error":"error_detail_5"}  | {"error":"error_detail_5"}  | 2023-05-15 00:00:00 |
| order_1  | 2023-01-15 00:00:00 | {"error":"error_detail_1"}  | {"error":"after_udpate_1"}  | 2023-01-15 00:00:00 |
| order_6  | 2023-06-15 00:00:00 | {"error":"error_detail_6"}  | {"error":"error_detail_6"}  | 2023-06-15 00:00:00 |
| order_10 | 2023-10-15 00:00:00 | {"error":"error_detail_10"} | {"error":"error_detail_10"} | 2023-10-15 00:00:00 |
| order_3  | 2023-03-15 00:00:00 | {"error":"error_detail_3"}  | {"error":"error_detail_3"}  | 2023-03-15 00:00:00 |
| order_12 | 2023-12-15 00:00:00 | {"error":"error_detail_12"} | {"error":"error_detail_12"} | 2023-12-15 00:00:00 |
| order_9  | 2023-09-15 00:00:00 | {"error":"error_detail_9"}  | {"error":"error_detail_9"}  | 2023-09-15 00:00:00 |
| order_7  | 2023-07-15 00:00:00 | {"error":"error_detail_7"}  | {"error":"error_detail_7"}  | 2023-07-15 00:00:00 |
| order_8  | 2023-08-15 00:00:00 | {"error":"error_detail_8"}  | {"error":"error_detail_8"}  | 2023-08-15 00:00:00 |
| order_4  | 2023-04-15 00:00:00 | {"error":"error_detail_4"}  | {"error":"error_detail_4"}  | 2023-04-15 00:00:00 |
| order_11 | 2023-11-15 00:00:00 | {"error":"error_detail_11"} | {"error":"error_detail_11"} | 2023-11-15 00:00:00 |
+----------+---------------------+-----------------------------+-----------------------------+---------------------+
```

**Comment by Astralidea** [comment]
我又验证一下，就是我发的那个PR修复的。我把https://github.com/StarRocks/starrocks/pull/23047 给revert了以后，问题复现。

**Comment by caohb1985** [comment]
咱们的2.5.6什么时候发版？
