### ISSUE TITLE
Have StarRocks OLAP database as an option in Superset 

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#23089]
https://github.com/apache/superset/discussions/23996

**Comment by alberttwong** [comment]
https://github.com/miomiocat did a PR https://github.com/apache/superset/pull/18613

**Comment by rusackas** [comment]
There's this older one too:
https://github.com/apache/superset/pull/18613

**Comment by alberttwong** [comment]
https://preset.ideas.aha.io/ideas/PROD-I-3538

**Comment by alberttwong** [comment]
@rusackas so I'm looking at https://github.com/apache/superset/pull/23209/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 and it should have updated https://superset.apache.org/docs/databases/installing-database-drivers/ but I don't see the entry for StarRocks.

**Comment by alberttwong** [comment]
https://github.com/apache/superset/issues/24015
