### ISSUE TITLE
Use the iceberg catalog to query the iceberg table, and the partition field value is null

### ISSUE THREAD

**Issue by winfys** [StarRocks/starrocks#23163]
### Steps to reproduce the behavior (Required)
1.create iceberg table 
`CREATE TABLE `bdc_dwd`.`dwd_dflog_event_iceberg_inc_realtime_1d`(
  `menu_code` string, 
  `uid` string, 
  `query_start_time` bigint, 
  `query_end_time` bigint, 
  `query_consume_time` bigint, 
  `query_prams` string, 
  `form_code` string, 
  `traceid` string, 
  `code` string, 
  `message` string, 
  `system_env` string, 
  `pro_code` string, 
  `business_time` string, 
  `logtime` bigint, 
  `user_id` string, 
  `user_name` string, 
  `template_code` string, 
  `menu_id` string, 
  `menu_name` string, 
  `model_type` string, 
  `game_key` string, 
  `sql` string, 
  `appkey` string, 
  `calculate_start_time` bigint, 
  `calculate_end_time` bigint, 
  `calculate_consume_time` bigint, 
  `sql_format_consume_time` bigint, 
  `sql_format_start_time` bigint, 
  `sql_format_end_time` bigint, 
  `sql_start_time` bigint, 
  `sql_consume_time` bigint, 
  `sql_end_time` bigint, 
  `sql_result` string, 
  `sql_result_msg` string, 
  `source_type` string, 
  `sql_thread_id` string, 
  `cuid` string, 
  `data_source` string, 
  `source_id` string, 
  `currency_consume_time` bigint, 
  `currency_end_time` bigint, 
  `currency_start_time` bigint, 
  `trans_consume_time` bigint, 
  `trans_end_time` bigint, 
  `trans_start_time` bigint, 
  `exception_type` string, 
  `detail` string, 
  `result` string,
  `dt` string,
  `event_code` string
  )
  USING parquet 
PARTITIONED BY ( 
  `dt`, 
  `event_code`)
LOCATION
  'oss://xxxx';
`
2. query partition column in Spark SQL
![image](https://github.com/StarRocks/starrocks/assets/13195083/2edb1cc6-286b-4851-9c2f-a8662c22db57)
3.Query iceberg in StarRocks3.0
![image](https://github.com/StarRocks/starrocks/assets/13195083/07428911-eb02-4c31-ae31-648abd7f62ff)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
![image](https://github.com/StarRocks/starrocks/assets/13195083/888136ce-5aea-4aee-aa58-5c4e094342e5)

**Comment by Smith-Cruise** [comment]
Are you have done iceberg schema evolution?

**Comment by Smith-Cruise** [comment]
And also can you provide your parquet file schema?

**Comment by winfys** [comment]
> Are you have done iceberg schema evolution?

The iceberg table is migrated through the hive parquet table, without schema evolution

**Comment by winfys** [comment]
> And also can you provide your parquet file schema?
`File path:  oss://xxxx/dwd_dflog_event_delta_inc_realtime_test2/dt=2023-05-03/event_code=30007/part-00009-27547fc7-772b-41e9-9103-70abf3c2347c.c000.snappy.parquet
Created by: parquet-mr version 1.12.2 (build 77e30c8093386ec52c3cfa6c34b7ef3321322c94)
Properties:
                  org.apache.spark.timeZone: Asia/Shanghai
                   org.apache.spark.version: 3.3.1
  org.apache.spark.sql.parquet.row.metadata: {"type":"struct","fields":[{"name":"menu_code","type":"string","nullable":true,"metadata":{}},{"name":"uid","type":"string","nullable":true,"metadata":{}},{"name":"query_start_time","type":"long","nullable":true,"metadata":{}},{"name":"query_end_time","type":"long","nullable":true,"metadata":{}},{"name":"query_consume_time","type":"long","nullable":true,"metadata":{}},{"name":"query_prams","type":"string","nullable":true,"metadata":{}},{"name":"form_code","type":"string","nullable":true,"metadata":{}},{"name":"traceid","type":"string","nullable":true,"metadata":{}},{"name":"code","type":"string","nullable":true,"metadata":{}},{"name":"message","type":"string","nullable":true,"metadata":{}},{"name":"system_env","type":"string","nullable":true,"metadata":{}},{"name":"pro_code","type":"string","nullable":true,"metadata":{}},{"name":"business_time","type":"string","nullable":true,"metadata":{}},{"name":"logtime","type":"long","nullable":true,"metadata":{}},{"name":"user_id","type":"string","nullable":true,"metadata":{}},{"name":"user_name","type":"string","nullable":true,"metadata":{}},{"name":"template_code","type":"string","nullable":true,"metadata":{}},{"name":"menu_id","type":"string","nullable":true,"metadata":{}},{"name":"menu_name","type":"string","nullable":true,"metadata":{}},{"name":"model_type","type":"string","nullable":true,"metadata":{}},{"name":"game_key","type":"string","nullable":true,"metadata":{}},{"name":"sql","type":"string","nullable":true,"metadata":{}},{"name":"appkey","type":"string","nullable":true,"metadata":{}},{"name":"calculate_start_time","type":"long","nullable":true,"metadata":{}},{"name":"calculate_end_time","type":"long","nullable":true,"metadata":{}},{"name":"calculate_consume_time","type":"long","nullable":true,"metadata":{}},{"name":"sql_format_consume_time","type":"long","nullable":true,"metadata":{}},{"name":"sql_format_start_time","type":"long","nullable":true,"metadata":{}},{"name":"sql_format_end_time","type":"long","nullable":true,"metadata":{}},{"name":"sql_start_time","type":"long","nullable":true,"metadata":{}},{"name":"sql_consume_time","type":"long","nullable":true,"metadata":{}},{"name":"sql_end_time","type":"long","nullable":true,"metadata":{}},{"name":"sql_result","type":"string","nullable":true,"metadata":{}},{"name":"sql_result_msg","type":"string","nullable":true,"metadata":{}},{"name":"source_type","type":"string","nullable":true,"metadata":{}},{"name":"sql_thread_id","type":"string","nullable":true,"metadata":{}},{"name":"cuid","type":"string","nullable":true,"metadata":{}},{"name":"data_source","type":"string","nullable":true,"metadata":{}},{"name":"source_id","type":"string","nullable":true,"metadata":{}},{"name":"currency_consume_time","type":"long","nullable":true,"metadata":{}},{"name":"currency_end_time","type":"long","nullable":true,"metadata":{}},{"name":"currency_start_time","type":"long","nullable":true,"metadata":{}},{"name":"trans_consume_time","type":"long","nullable":true,"metadata":{}},{"name":"trans_end_time","type":"long","nullable":true,"metadata":{}},{"name":"trans_start_time","type":"long","nullable":true,"metadata":{}},{"name":"exception_type","type":"string","nullable":true,"metadata":{}},{"name":"detail","type":"string","nullable":true,"metadata":{}},{"name":"result","type":"string","nullable":true,"metadata":{}}]}
            org.apache.spark.legacyDateTime: 
Schema:
message spark_schema {
  optional binary menu_code (STRING);
  optional binary uid (STRING);
  optional int64 query_start_time;
  optional int64 query_end_time;
  optional int64 query_consume_time;
  optional binary query_prams (STRING);
  optional binary form_code (STRING);
  optional binary traceid (STRING);
  optional binary code (STRING);
  optional binary message (STRING);
  optional binary system_env (STRING);
  optional binary pro_code (STRING);
  optional binary business_time (STRING);
  optional int64 logtime;
  optional binary user_id (STRING);
  optional binary user_name (STRING);
  optional binary template_code (STRING);
  optional binary menu_id (STRING);
  optional binary menu_name (STRING);
  optional binary model_type (STRING);
  optional binary game_key (STRING);
  optional binary sql (STRING);
  optional binary appkey (STRING);
  optional int64 calculate_start_time;
  optional int64 calculate_end_time;
  optional int64 calculate_consume_time;
  optional int64 sql_format_consume_time;
  optional int64 sql_format_start_time;
  optional int64 sql_format_end_time;
  optional int64 sql_start_time;
  optional int64 sql_consume_time;
  optional int64 sql_end_time;
  optional binary sql_result (STRING);
  optional binary sql_result_msg (STRING);
  optional binary source_type (STRING);
  optional binary sql_thread_id (STRING);
  optional binary cuid (STRING);
  optional binary data_source (STRING);
  optional binary source_id (STRING);
  optional int64 currency_consume_time;
  optional int64 currency_end_time;
  optional int64 currency_start_time;
  optional int64 trans_consume_time;
  optional int64 trans_end_time;
  optional int64 trans_start_time;
  optional binary exception_type (STRING);
  optional binary detail (STRING);
  optional binary result (STRING);
}


Row group 0:  count: 27037  45.66 B records  start: 4  total: 1.177 MB
--------------------------------------------------------------------------------
                         type      encodings count     avg size   nulls   min / max
menu_code                BINARY    S   _     27037     0.00 B     27037   
uid                      BINARY    S   _     27037     0.00 B     27037   
query_start_time         INT64     S   _     27037     0.00 B     27037   
query_end_time           INT64     S   _     27037     0.00 B     27037   
query_consume_time       INT64     S   _     27037     0.00 B     27037   
query_prams              BINARY    S   _     27037     0.00 B     27037   
form_code                BINARY    S   _     27037     0.00 B     27037   
traceid                  BINARY    S   _     27037     0.00 B     27037   
code                     BINARY    S   _     27037     32.53 B    0       "00009ee79f334d668bf6465c4..." / "ffff2950eefd4a2f8ffdd2ec5..."
message                  BINARY    S   _     27037     0.00 B     27037   
system_env               BINARY    S _ R     27037     0.00 B     0       "dev" / "hero"
pro_code                 BINARY    S _ R     27037     0.00 B     0       "1008" / "1008"
business_time            BINARY    S _ R     27037     3.45 B     0       "2023-05-03 00:00:00" / "2023-05-03 23:59:02"
logtime                  INT64     S   _     27037     4.95 B     0       "1683043200148" / "1683129542285"
user_id                  BINARY    S   _     27037     0.00 B     27037   
user_name                BINARY    S   _     27037     0.00 B     27037   
template_code            BINARY    S   _     27037     0.00 B     27037   
menu_id                  BINARY    S   _     27037     0.00 B     27037   
menu_name                BINARY    S   _     27037     0.00 B     27037   
model_type               BINARY    S   _     27037     0.00 B     27037   
game_key                 BINARY    S   _     27037     0.00 B     27037   
sql                      BINARY    S   _     27037     0.00 B     27037   
appkey                   BINARY    S   _     27037     0.00 B     27037   
calculate_start_time     INT64     S   _     27037     0.00 B     27037   
calculate_end_time       INT64     S   _     27037     0.00 B     27037   
calculate_consume_time   INT64     S   _     27037     0.00 B     27037   
sql_format_consume_time  INT64     S   _     27037     0.00 B     27037   
sql_format_start_time    INT64     S   _     27037     0.00 B     27037   
sql_format_end_time      INT64     S   _     27037     0.00 B     27037   
sql_start_time           INT64     S   _     27037     0.00 B     27037   
sql_consume_time         INT64     S   _     27037     0.00 B     27037   
sql_end_time             INT64     S   _     27037     0.00 B     27037   
sql_result               BINARY    S   _     27037     0.00 B     27037   
sql_result_msg           BINARY    S   _     27037     0.00 B     27037   
source_type              BINARY    S _ R     27037     0.01 B     0       "doris" / "mysql"
sql_thread_id            BINARY    S   _     27037     4.62 B     0       "0579312b-9a64-4711-9fa5-1..." / "f4bc8d66-c264-4bee-ae71-0..."
cuid                     BINARY    S   _     27037     0.00 B     27037   
data_source              BINARY    S   _     27037     0.00 B     27037   
source_id                BINARY    S   _     27037     0.00 B     27037   
currency_consume_time    INT64     S   _     27037     0.00 B     27037   
currency_end_time        INT64     S   _     27037     0.00 B     27037   
currency_start_time      INT64     S   _     27037     0.00 B     27037   
trans_consume_time       INT64     S   _     27037     0.00 B     27037   
trans_end_time           INT64     S   _     27037     0.00 B     27037   
trans_start_time         INT64     S   _     27037     0.00 B     27037   
exception_type           BINARY    S   _     27037     0.00 B     27037   
detail                   BINARY    S   _     27037     0.00 B     27037   
result                   BINARY    S   _     27037     0.00 B     27037   
`

**Comment by winfys** [comment]
This is the directory structure. Some partitioned directories have no files
![image](https://github.com/StarRocks/starrocks/assets/13195083/d3b3ce2b-4d9d-4620-9d84-491b44ed68b2)
![image](https://github.com/StarRocks/starrocks/assets/13195083/4dfa0a8b-b61e-4f62-a98c-d8b59e339784)

**Comment by Smith-Cruise** [comment]
So only the partition keys are not existed?

**Comment by stephen-shelby** [comment]
the parquet file of hive table doesn't contain partition columns values.  but the iceberg partition columns values need to be materialized in the parquet file.

**Comment by winfys** [comment]
> the parquet file of hive table doesn't contain partition columns values. but the iceberg partition columns values need to be materialized in the parquet file.

Can you support this case？

**Comment by stephen-shelby** [comment]
> > the parquet file of hive table doesn't contain partition columns values. but the iceberg partition columns values need to be materialized in the parquet file.
> 
> Can you support this case？

we will support it later. I want to know which procedure do you use for migration

**Comment by winfys** [comment]
> > > hive 表的 parquet 文件不包含分区列值。但 iceberg 分区列值需要在 parquet 文件中具体化。
> > 
> > 
> > 你能支持这个案例吗？
> 
> 我们稍后会支持它。我想知道您使用哪个程序进行迁移

spark sql:   Call migrate

**Comment by lipenglin** [comment]
Someone is solving this issue?

**Comment by Smith-Cruise** [comment]
> Someone is solving this issue?

Nobody

**Comment by lipenglin** [comment]
> > Someone is solving this issue?
> 
> No one for now

Okey, we have the same issue and plan to fix it in a few days. If someone has already solved it, we can help test.
