### ISSUE TITLE
The sequenceMatch function similar to click house, when can StarRocks support it

### ISSUE THREAD

**Issue by syb853553110** [StarRocks/starrocks#2320]
## Feature request
The sequenceMatch function similar to click house, when can StarRocks support it

**Describe the solution you'd like**
The sequenceMatch function similar to click house, when can StarRocks support it

**Describe alternatives you've considered**
The sequenceMatch function similar to click house, when can StarRocks support it

**Additional context**
The sequenceMatch function similar to click house, when can StarRocks support it

**Comment by jaogoy** [comment]
It seems like a window funnel function, we will do some investigation on it.
