### ISSUE TITLE
[Analyze External Table] Support analyze external table to collect statistics

### ISSUE THREAD

**Issue by zombee0** [StarRocks/starrocks#23327]
## Feature request

we are working on support analyze external table, iceberg first.
there are several step to do.
- [x] refactor native analyze. https://github.com/StarRocks/starrocks/pull/23326
- [x] collect external table statistics of table level. https://github.com/StarRocks/starrocks/pull/23493
- [x] query external table statistics of table level. https://github.com/StarRocks/starrocks/pull/23881
- [x] cache of iceberg.
- [x] collect external table statistics of partition level

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kShines** [comment]
Don't external tables support column statistics, such as ndv?

**Comment by Youngwb** [comment]
> Can the exterior also support the hll algorithm, for example hive should not support hll, how to calculate ndv in this case

Yes, SR could compute external table's ndv by hll algorithm, and store these statistics as SR native table
