### ISSUE TITLE
[function] date_diff

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#23420]
starrocks already have the function days_diff, but it only calculates the difference of days. 
we need more accurate calculations when it comes to hour/minute/second/millisecond, and also it will be wired to name this function days_dff. It is more like a date_diff. 

so here is a proposal:

## date_diff

```
date_diff(<datetime or date 1>,<datetime or date 2 >[, <unit>])
```

in which
1. <datetime or date1> and <datetime or date 2> are date or datetime expression
2. <unit> can be day, hour, second, millisecond, it is an optional parameter. default to day.

Notes:
1. when both <datetime or date 1> and <datetime or date 2 > are date. the unit can only be day. 

Examples:

```
SELECT date_diff( '2020-03-01 00:00:00', '2020-03-02 00:00:00', 'second',);
-- 86400

SELECT date_diff('2020-03-01 00:00:00','2020-03-02 00:00:05',hour');
-- 24

SELECT date_diff(, '2020-03-01', '2020-03-02','day');
-- 1

SELECT date_diff( '2020-06-01 12:30:45.000000',  '2020-06-01 12:30:45.123798','millisecond');
-- 123

```

after this function is developed, we will not recommend users to use days_diff.

**Comment by xuzifu666** [comment]
@wangsimo0  assgine to me please~
