### ISSUE TITLE
support Apache Paimon 

### ISSUE THREAD

**Issue by AnemoneIndicum** [StarRocks/starrocks#23481]
Apache Paimon(incubating) is a streaming data lake platform as Hudi、Iceberg well. It can be written to the 'hdfs filesystem' that uses the hive catalog. Nowadays, the company of using it will keep growing. 

In the past several days， I have tested using the hive catalog('starrocks') to read the table metadata created by Paimon, it's OK， but can not read table data.

**Comment by miomiocat** [comment]
Thanks for your attention.

We are working on this and expect an initial version at the end of the month.

The current overall plan is as follows:
- support paimon metastore catalog
- support reading paimon table without filter pushdown and data types excluding complex types (map, array, struct)
- support paimon warehouse catalog
- support complex type reading (map, array, struct)
- support filter pushdown

Welcome to discuss and contribute this work.
