### ISSUE TITLE
Accessing a parquet file stored in MINIO S3 with the Engine=file does not work

### ISSUE THREAD

**Issue by chrisfw** [StarRocks/starrocks#23605]
### Steps to reproduce the behavior (Required)
1. Set up MINIO, create a bucket and upload a test parquet file
2. Create external table with Engine=file and the properties matching the MINIO deployment
3. Attempt to query data with SQL

### Expected behavior (Required)
Data is returned
### Real behavior (Required)
Error is generated:  SQL Error [1064] [42000]: code=-1(SdkErrorType:99), message=curlCode: 6, Couldn't resolve 
### StarRocks version (Required)
 3.0.0 48f4d81 

My configuration:
```
CREATE EXTERNAL TABLE cistestext
(
    cis_number bigint, 
    cis_alpha_sort string
) 
ENGINE=file
PROPERTIES 
(
    "path" = "s3://parquet-test/test2.parquet", 
    "format" = "parquet",
	"enable_recursive_listing" = "false",
        "aws.s3.enable_ssl" = "false",
	"aws.s3.enable_path_style_access" = "false",
	"aws.s3.endpoint" = "http://10.18.102.29:9000",
	"aws.s3.access_key" = "redacted",
	"aws.s3.secret_key" = "redacted"
);
```

![minio](https://github.com/StarRocks/starrocks/assets/6135741/39c98794-fe6b-4ed9-9e0c-69bae529edba)

Note: The external table was created in the externalfile database:
```
create database externalfile;
```
![starrockserror](https://github.com/StarRocks/starrocks/assets/6135741/a3d18bdd-95f1-4e97-bdbc-8b13de3f7427)

**Comment by alberttwong** [comment]
This is another way through another tutorial.  https://github.com/StarRocks/starrocks/discussions/22777

**Comment by chrisfw** [comment]
@alberttwong , thank you for the links.  I revisited my setup based upon https://github.com/StarRocks/starrocks/discussions/22723 and it appears that setting the aws.s3.enable_path_style_access property to true fixed my issue.  I appreciate your assistance.
Regards,
Chris
