### ISSUE TITLE
Segmentation fault of perf report

### ISSUE THREAD

**Issue by mellonyou** [StarRocks/starrocks#23695]
After fe&be is running, do "sudo perf record" and get perf.data file, then do "sudo perf report" to analyze the perf.data file, it will cause Segmentation fault. I have try to build from main source code, and also try the binary release version of 3.0.0, this issue exist in all cases.
But on binary release version of StarRocks-2.5.1, this issue does not exist.

**Comment by mellonyou** [comment]
No one encounter this issue, or did not pay attention?

**Comment by zenoyang** [comment]
> No one encounter this issue, or did not pay attention?

I also encountered the same problem, is there a solution? @mellonyou
