### ISSUE TITLE
Unrecognized VM option 'CMSClassUnloadingEnabled'

### ISSUE THREAD

**Issue by jots** [StarRocks/starrocks#23959]
going through the steps to deploy (on ubuntu 22.04)
https://docs.starrocks.io/en-us/2.5/deployment/deploy_manually

when running
 ```
 ./fe/bin/start_fe.sh --daemon
these errors would occur 
Unrecognized VM option 'CMSClassUnloadingEnabled'
Unrecognized VM option 'CMSInitiatingOccupancyFraction=80'
Unrecognized VM option 'CMSParallelRemarkEnabled'
```
I removed those options from JAVA_OPTS=  and  JAVA_OPTS_FOR_JDK_9= in `fe/conf/fe.conf`
and then the the fe would start.

Do I need to be worried about removing  those options?
Using this java version (installed by `apt install openjdk-18-jdk`:
```
java --version
openjdk 18.0.2-ea 2022-07-19
OpenJDK Runtime Environment (build 18.0.2-ea+9-Ubuntu-222.04)
OpenJDK 64-Bit Server VM (build 18.0.2-ea+9-Ubuntu-222.04, mixed mode, sharing)
```

**Comment by nshangyiming** [comment]
hi @jots , we haven't supported jdk18 yet, jdk 8 is recommended.
