### ISSUE TITLE
Varchar length not compatible with MySQL external table 

### ISSUE THREAD

**Issue by murphyatwork** [StarRocks/starrocks#23980]
### Steps to reproduce the behavior (Required)
```sql
CREATE EXTERNAL TABLE `wwwww` (
    `v1` varchar(30) NULL COMMENT \ "",
    `v2` varchar(81) NULL COMMENT "",
) ENGINE JDBC COMMENT "JDBC" PROPERTIES (
    "resource" = "jdbc_wwwwww",
    "table" = "wwwwww"
);
```

User will copy the MySQL schema into SR to create an external table, so the schema of SR should be compatible with MySQL. But actually:
1. `varchar(30)` in MySQL means maximum characters is 30
2. `varchar(30)` in SR means maximum bytes is 30

So this behavior should be fixed.

### StarRocks version (Required)
- 2.2, 2.3, 2.4, 2.5, 3.0

**Comment by jhcnet2** [comment]
I got this error. when I submitted a select query to mysql.

**Comment by alberttwong** [comment]
we should change the varchar default to varchar(80).  https://github.com/StarRocks/starrocks/issues/33089

**Comment by alberttwong** [comment]
https://github.com/StarRocks/starrocks/issues/33089
