### ISSUE TITLE
一个报错信息好像是说内存泄漏还是网络通信导致的。可以帮我分析一下吗

### ISSUE THREAD

**Issue by yangzehan** [StarRocks/starrocks#24018]
query_id:fc23b5b5-f94d-11ed-9c80-fa163e30870d, fragment_instance:fc23b5b5-f94d-11ed-9c80-fa163e30870e
*** Aborted at 1684834885 (unix time) try "date -d @1684834885" if you are using GNU date ***
PC: @          0x4ccb226 starrocks::vectorized::Chunk::clone_empty_with_slot()
*** SIGSEGV (@0x0) received by PID 20221 (TID 0x7fcea0748700) from PID 0; stack trace: ***
    @          0x5722822 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fcf2fa6a7bb os::Linux::chained_handler()
    @     0x7fcf2fa6f29c JVM_handle_linux_signal
    @     0x7fcf2fa62158 signalHandler()
    @     0x7fcf2ef40630 (unknown)
    @          0x4ccb226 starrocks::vectorized::Chunk::clone_empty_with_slot()
    @          0x4ccb953 starrocks::vectorized::Chunk::clone_empty_with_slot()
    @          0x30ec210 starrocks::pipeline::LocalExchangeSourceOperator::_pull_shuffle_chunk()
    @          0x30ecd67 starrocks::pipeline::LocalExchangeSourceOperator::pull_chunk()
    @          0x2c3fbe3 starrocks::pipeline::PipelineDriver::process()
    @          0x4dc1bd7 starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x47d2acd starrocks::ThreadPool::dispatch_thread()
    @          0x47cd85a starrocks::Thread::supervise_thread()
    @     0x7fcf2ef38ea5 start_thread
    @     0x7fcf2e553b0d __clone
    @                0x0 (unknown)

**Comment by trueeyu** [comment]
already fixed

**Comment by trueeyu** [comment]
https://github.com/StarRocks/starrocks/pull/23027
https://github.com/StarRocks/starrocks/pull/18055
