### ISSUE TITLE
Add dbid and tableid to information_schema.tables_config

### ISSUE THREAD

**Issue by decster** [StarRocks/starrocks#24014]

**Comment by leoyy0316** [comment]
@decster want to have a try, can you assign this to me if this feature is not urgent?

**Comment by decster** [comment]
oh.. already done this

**Comment by leoyy0316** [comment]
> oh.. already done this

@decster  oh,  no chance to do this. if have other features about information_schema, pls  assign it to me. thanks

**Comment by decster** [comment]
> > oh.. already done this
> 
> @decster oh, no chance to do this. if have other features about information_schema, pls assign it to me. thanks

sure, thanks
