### ISSUE TITLE
Why am I routine load kafka so slowly

### ISSUE THREAD

**Issue by HelloSrauker** [StarRocks/starrocks#2403]
## General Question

**environment :**  3fe & 3be in 3 Physical machine
**starrocks Version :** 1.19.1
**Custom ：**  I recompiled librdKafka of be, now it can support kerberos, its works fine.

**question:**    Why am I routine load kafka so slowly ,  I calculated it only 1700+ loadRows/s

this is my JobProperties

`"desireTaskConcurrentNum":"10","maxErrorNum":"2000","strip_outer_array":"false","currentTaskConcurrentNum":"3","maxBatchRows":"200000"`

I set desireTaskConcurrentNum is 10 ,but currentTaskConcurrentNum just 3 ,I look at the source code because it selects the number of be number。
`currentTaskConcurrentNum = Math.min(Math.min(partitionNum, Math.min(desireTaskConcurrentNum, aliveBeNum)),
                Config.max_routine_load_task_concurrent_num);`

but why？

this is my be Memory Usage Detail,You can see that performance is wasted

`<html>
<body>

level | Label | Parent | Limit | Current Consumption | Peak Consumption
-- | -- | -- | -- | -- | --
1 | process |   | 301G | 1370M | 1479M
2 | query_pool | process | 270G | 7M | 83M
2 | load | process | 90G | 290K | 12M

</body>
</html>`

Can you provide some performance adjustments to me?thanks so much

**Comment by chaoyli** [comment]
@HelloSrauker I think the speed is not normal. What about the partition number in Kafka?

**Comment by HelloSrauker** [comment]
@chaoyli This is the result of my running all night

this is DataSourceProperties :
`{"topic":"xxxx","currentKafkaPartitions":"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21","brokerList":"xxxx"}`
22 number in kafka

this is Progress:
`{"0":"83219384","1":"83329422","2":"83079975","3":"83154186","4":"85066522","5":"85533146","6":"85396286","7":"85427015","8":"85341258","9":"83440630","10":"83455448","11":"83449086","12":"83432992","13":"84750894","14":"84218989","15":"84268018","16":"84383882","17":"84096630","18":"82906739","19":"82921590","20":"82851818","21":"82970053"}


this is Statistic:
`{"receivedBytes":91900268361,"errorRows":14,"committedTaskNum":5516,"loadedRows":86693971,"loadRowsRate":1000,"abortedTaskNum":4066,"totalRows":86693985,"unselectedRows":0,"receivedBytesRate":1653000,"taskExecuteTimeMs":55592291}`
`

**Comment by gengjun-git** [comment]
@HelloSrauker  Is there a lot of data accumulation in kafka?

**Comment by HelloSrauker** [comment]
@gengjun-git  yes .kafka have a lot of data accumulation

about 1700+ loadRows/s

I use select count(*) from table  every 10 minutes
i find avg 1 million load row in 10 minutes  ,so i simply calculate the import rate.

**Comment by HelloSrauker** [comment]
now i change some conf:
be.conf:
`push_write_mbytes_per_sec = 30
routine_load_thread_pool_size = 30
push_worker_count_normal_priority = 8
push_worker_count_high_priority = 8`

fe.conf:
`routine_load_task_consume_second = 12
routine_load_task_timeout_second = 30
max_routine_load_task_concurrent_num = 20
max_routine_load_task_num_per_be = 20`

It looks a lot faster
And I find some be's log ,Can you help me check whether this is normal


I1224 10:37:35.519393 385694 data_consumer.cpp:149] consumer: 6e42521fa4097dee-a7561bed22d2698e, grp: 2946533b1a198e51-e7957012a392b6a6 assign topic partitions: topic_v10, [1: 83417007] [10: 83565457] [19: 83015622]
I1224 10:37:35.519524 385694 data_consumer.cpp:149] consumer: 9d4c265a76709fba-96f8594f1f7a948a, grp: 2946533b1a198e51-e7957012a392b6a6 assign topic partitions: topic_v10, [4: 85217414] [13: 84890299]
I1224 10:37:35.519631 385694 data_consumer.cpp:149] consumer: 5b41d25db58d5d51-89d527df7e94a0ab, grp: 2946533b1a198e51-e7957012a392b6a6 assign topic partitions: topic_v10, [7: 85588790] [16: 84510844]
I1224 10:37:35.519776 385694 stream_load_executor.cpp:54] begin to execute job. label=topic_load_04-56331-0d207b5a-fecb-44ec-99c9-21c64622b254-67045, txn_id=67045, query_id=0d207b5a-fecb-44ec-99c9-21c64622b254
I1224 10:37:35.519829 385694 plan_fragment_executor.cpp:67] Prepare(): query_id=0d207b5a-fecb-44ec-99c9-21c64622b254 fragment_instance_id=0d207b5a-fecb-44ec-99c9-21c64622b255 backend_num=0
I1224 10:37:35.520126 385694 plan_fragment_executor.cpp:123] Using query memory limit: 2.00 GB
I1224 10:37:35.525395 385678 plan_fragment_executor.cpp:223] Open(): fragment_instance_id=0d207b5a-fecb-44ec-99c9-21c64622b255
I1224 10:37:35.525440 385694 data_consumer_group.cpp:101] start consumer group: 2946533b1a198e51-e7957012a392b6a6. max time(ms): 12000, batch size: 524288000. id=0d207b5afecb44ec-99c921c64622b254, job_id=56331, txn_id=67045, label=topic_v10_load_04-56331-0d207b5a-fecb-44ec-99c9-21c64622b254-67045
I1224 10:37:35.525449 389306 data_consumer.cpp:172] start kafka consumer: 9d4c265a76709fba-96f8594f1f7a948a, grp: 2946533b1a198e51-e7957012a392b6a6, max running time(ms): 12000
I1224 10:37:35.525444 389305 data_consumer.cpp:172] start kafka consumer: 6e42521fa4097dee-a7561bed22d2698e, grp: 2946533b1a198e51-e7957012a392b6a6, max running time(ms): 12000
I1224 10:37:35.525473 389307 data_consumer.cpp:172] start kafka consumer: 5b41d25db58d5d51-89d527df7e94a0ab, grp: 2946533b1a198e51-e7957012a392b6a6, max running time(ms): 12000

ellipsis..........

I1224 10:37:47.525768 385694 data_consumer.cpp:331] kafka consumer cancelled. 6e42521fa4097dee-a7561bed22d2698e
I1224 10:37:47.525779 385694 data_consumer.cpp:331] kafka consumer cancelled. 9d4c265a76709fba-96f8594f1f7a948a
I1224 10:37:47.525785 385694 data_consumer.cpp:331] kafka consumer cancelled. 5b41d25db58d5d51-89d527df7e94a0ab
I1224 10:37:47.525820 389307 data_consumer.cpp:234] kafka consume done: 5b41d25db58d5d51-89d527df7e94a0ab, grp: 2946533b1a198e51-e7957012a392b6a6. cancelled: 1, left time(ms): 0, total cost(ms): 12000, consume cost(ms): 76, received rows: 11072, put rows: 11071
I1224 10:37:47.525820 389306 data_consumer.cpp:234] kafka consume done: 9d4c265a76709fba-96f8594f1f7a948a, grp: 2946533b1a198e51-e7957012a392b6a6. cancelled: 1, left time(ms): 0, total cost(ms): 12000, consume cost(ms): 71, received rows: 11755, put rows: 11754
I1224 10:37:47.525822 389305 data_consumer.cpp:234] kafka consume done: 6e42521fa4097dee-a7561bed22d2698e, grp: 2946533b1a198e51-e7957012a392b6a6. cancelled: 1, left time(ms): 0, total cost(ms): 12000, consume cost(ms): 73, received rows: 11938, put rows: 11937
I1224 10:37:47.525897 389305 data_consumer_group.cpp:81] all consumers are finished. shutdown queue. group id: 2946533b1a198e51-e7957012a392b6a6

**Comment by gengjun-git** [comment]
This is a normal log

**Comment by HelloSrauker** [comment]
What affects the  received rows and put rows?

I find that sometimes these two values are very small
(i add consumer number to 7)

I1224 14:58:42.103646 18647 data_consumer.cpp:331] kafka consumer cancelled. f84068a3210215fc-e14da9aec899c286
I1224 14:58:42.103662 18647 data_consumer.cpp:331] kafka consumer cancelled. 044d24e232aa1882-c783d0fba3d82bbf
I1224 14:58:42.103674 18647 data_consumer.cpp:331] kafka consumer cancelled. f94d5b9d8f15a01d-5246ac89773b7cb7
I1224 14:58:42.103682 18647 data_consumer.cpp:331] kafka consumer cancelled. 4340eae3c4be0357-ae25e82edccbdc98
I1224 14:58:42.103662 28851 data_consumer.cpp:234] kafka consume done: 314bb491d623049a-5eca4f123e2a19bc, grp: 014d104d1d25e64e-416a7e4e24e3fe81. cancelled: 1, left time(ms): 0, total cost(ms): 3000, consume cost(ms): 1094, received rows: 401, put rows: 400
I1224 14:58:42.103688 18647 data_consumer.cpp:331] kafka consumer cancelled. 314bb491d623049a-5eca4f123e2a19bc
I1224 14:58:42.103684 28849 data_consumer.cpp:234] kafka consume done: f94d5b9d8f15a01d-5246ac89773b7cb7, grp: 014d104d1d25e64e-416a7e4e24e3fe81. cancelled: 1, left time(ms): 0, total cost(ms): 3000, consume cost(ms): 1052, received rows: 389, put rows: 388
I1224 14:58:42.103727 18647 data_consumer.cpp:331] kafka consumer cancelled. f14b30f6231526ea-666ded45a99381b7
I1224 14:58:42.103731 28850 data_consumer.cpp:234] kafka consume done: 4340eae3c4be0357-ae25e82edccbdc98, grp: 014d104d1d25e64e-416a7e4e24e3fe81. cancelled: 1, left time(ms): 0, total cost(ms): 3001, consume cost(ms): 110, received rows: 959, put rows: 958
I1224 14:58:42.103765 18647 data_consumer.cpp:331] kafka consumer cancelled. c84ded3c0ad286ed-ec7f0aa0f52b1fa3
I1224 14:58:42.103716 28853 data_consumer.cpp:234] kafka consume done: c84ded3c0ad286ed-ec7f0aa0f52b1fa3, grp: 014d104d1d25e64e-416a7e4e24e3fe81. cancelled: 0, left time(ms): 0, total cost(ms): 3000, consume cost(ms): 1062, received rows: 403, put rows: 402
I1224 14:58:42.103749 28848 data_consumer.cpp:234] kafka consume done: 044d24e232aa1882-c783d0fba3d82bbf, grp: 014d104d1d25e64e-416a7e4e24e3fe81. cancelled: 1, left time(ms): -1, total cost(ms): 3001, consume cost(ms): 1059, received rows: 391, put rows: 390
I1224 14:58:42.103732 28847 data_consumer.cpp:234] kafka consume done: f84068a3210215fc-e14da9aec899c286, grp: 014d104d1d25e64e-416a7e4e24e3fe81. cancelled: 1, left time(ms): 0, total cost(ms): 3000, consume cost(ms): 1071, received rows: 410, put rows: 409
I1224 14:58:42.103766 28852 data_consumer.cpp:234] kafka consume done: f14b30f6231526ea-666ded45a99381b7, grp: 014d104d1d25e64e-416a7e4e24e3fe81. cancelled: 1, left time(ms): 0, total cost(ms): 3001, consume cost(ms): 121, received rows: 1333, put rows: 1332
I1224 14:58:42.103813 28852 data_consumer_group.cpp:81] all consumers are finished. shutdown queue. group id: 014d104d1d25e64e-416a7e4e24e3fe81

**Comment by HelloSrauker** [comment]
@chaoyli Can you  tell me generally speaking, what is the efficiency of importing a be through Kafka by default?thanks

**Comment by chaoyli** [comment]
@HelloSrauker one core, 10MB/s

**Comment by HelloSrauker** [comment]
@chaoyli Hi, I found that the pipe was blocked most of the time. What does this have to do with?

`consumer group done: 854d8195b8c22a2c-b149aaa577ba36aa. consume time(ms)=20000, received rows=59809, received bytes=62086353, eos: 0, left_time: 0, left_bytes: 462201647, blocking get time(us): 1049097, blocking put time(us): 56307988
`

**Comment by gengjun-git** [comment]
write will block if the queue is full, read will block it the queue is empty

**Comment by HelloSrauker** [comment]
@gengjun-git 谢谢，再求教大佬一下，我阅读了源代码并且加了一些日志后发现 kafka消息管道阻塞的原因应该主要是在
src/exec.vectorized/json_scanner.cpp中的_read_and_parse_json方法。好像是因为这块儿消费 KafkaConsumerPipe 慢了，导致 blocking put time 很大，管道一直都是满的。

这是be执行fe传来的任务的其中一个结果:
一个ROUTINE LOAD 的时间我设置成20秒了
`   - AverageThreadTokens: 1.00 
   - MemoryLimit: 2.00 GB
   - PeakMemoryUsage: 13.31 MB
   - PeakReservation: 0
   - PeakUsedReservation: 0
   - RowsProduced: 61.83K
  BlockMgr:
     - BlockWritesOutstanding: 0
     - BlocksCreated: 0
     - BlocksRecycled: 0
     - BufferedPins: 0
     - BytesWritten: 0
     - MaxBlockSize: 8.00 MB
     - TotalBufferWaitTime: 0.000ns
     - TotalReadBlockTime: 0.000ns
  OlapTableSink:(Active: 7s391ms, non-child: 28.17%)
     - CloseWaitTime: 4s437ms
     - ConvertBatchTime: 193.092us
     - NonBlockingSendTime: 21s824ms
     - OpenTime: 4.830ms
     - RowsFiltered: 0
     - RowsRead: 61.83K
     - RowsReturned: 61.83K
     - SendDataTime: 2s947ms
     - SerializeBatchTime: 96.795ms
     - ValidateDataTime: 50.333ms
  FILE_SCAN_NODE (id=0):(Active: 18s189ms, non-child: 69.32%)
     - BytesRead: 0
     - NumDiskAccess: 0
     - PeakMemoryUsage: 4.27 MB
     - PerReadThreadRawHdfsThroughput: 0.00 /sec
     - RowsRead: 0
     - RowsReturned: 61.83K
     - RowsReturnedRate: 3.40 K/sec
     - ScannerThreadsInvoluntaryContextSwitches: 0
     - ScannerThreadsTotalWallClockTime: 0.000ns
       - MaterializeTupleTime(*): 0.000ns
       - ScannerThreadsSysTime: 0.000ns
       - ScannerThreadsUserTime: 0.000ns
     - ScannerThreadsVoluntaryContextSwitches: 0
     - **ScannerTotalTimer: 20s296ms**
     - TotalRawReadTime(*): 0.000ns
     - TotalReadThroughput: 0.00 /sec
     - **WaitScannerTime: 18s188ms**
    FileScanner:
       - CastChunkTimer: 130.935ms
       - CreateChunkTimer: 4.872ms
       - FillTimer: 0.000ns
       - MaterializeTimer: 25.987ms
       - ReadTimer: 0.000ns
      FilePRead:
         - FileReadTimer: 0.000ns
`

我看了下好像瓶颈确实是在scanner这块儿，首先我想确认下这个速度正常么？如果正常是因为json解析外加转换比较消耗性能吗？如果过低请问一般是什么原因呢，我机器的cpu,内存,io都还有挺大的空余。请问有什么优化方式，谢谢。不胜感激

**Comment by chaoyli** [comment]
@HelloSrauker You can add me wechat(chaoy-li) to talk about it.

**Comment by chaoyli** [comment]
@HelloSrauker We have optimized the routine load in 2.2.1

**Comment by HelloSrauker** [comment]
@[chaoyli](https://github.com/chaoyli) thanks, i try try
