### ISSUE TITLE
datax 导入主键模型，reader 部分_op 字段要怎么添加

### ISSUE THREAD

**Issue by zhangb0120** [StarRocks/starrocks#24182]
主键模型已支持通过 DataX 更新数据。您需要在 JSON 配置文件的 reader 部分添加 _op 字段配置该功能。
官网只有简单的一句话，能不能提供一个简单的示例

**Comment by chaoyli** [comment]
https://docs.starrocks.io/zh-cn/latest/loading/Load_to_Primary_Key_tables @zhangb0120
