### ISSUE TITLE
Index files for primary model table is too large, almost the same size as data files

### ISSUE THREAD

**Issue by leozhangsr** [StarRocks/starrocks#24221]
I am using starrocks with most of my tables are primary module table.80% of these tables have a composite primary key, which with three fields, one field is date type for date partition, the others are varchar type with the length of 128 or 32. Now I have 395G data in a be, but the total storage size it used it up to 848GB. I tried to analyse the data storage(the size of storage/data), and found that total size of index.l0 is up to 53.54 GB, total size of index.l1 is up to 329.34 GB, when the total size of data files is 411.1 GB. Relative ratio is:  Size(dat):Size(index.l0):Size(index.l1) = 1:0.13:0.8, which means when I have 1GB data, I need to pay another 0.93GB space for index file, and I think that is unacceptable, can we make some effort to reduce the cost?

------------- info from show backends -----------------
TabletNum: 137556
DataUsedCapacity: 395.029 GB
AvailCapacity: 159.755 GB
TotalCapacity: 1007.804 GB
--------------statistic info from disk --------------------
dat files size: 411.1 GB
index.l0 : 53.54 GB
index.l1 : 329.34 GB
---------------------------------------------------------

### Steps to reproduce the behavior (Required)
1. CREATE TABLE `my_table` (
  `key1` varchar(128) NOT NULL COMMENT "",
  `date` date NOT NULL COMMENT "",
  `key2` varchar(32) NOT NULL COMMENT "",
  `i1` int(11) NULL COMMENT "",
  `i2` int(11) NULL COMMENT "",
  `s1` varchar(128) NULL COMMENT "",
  `s2` varchar(128) NULL COMMENT "",
  `s3` varchar(128) NULL COMMENT "",
  `s4` varchar(128) NULL COMMENT "",
  `s5` varchar(128) NULL COMMENT "",
  `s6` varchar(128) NULL COMMENT "",
  `bi1` bigint(20) NULL COMMENT "",
  `bi2` bigint(20) NULL COMMENT "",
  `bi3` bigint(20) NULL COMMENT "",
  `d1` decimal128(20, 8) NULL COMMENT "",
  `d2` decimal128(20, 8) NULL COMMENT "",
  `d3` decimal128(20, 8) NULL COMMENT "",
  `d4` decimal128(20, 8) NULL COMMENT "",
  `dt1` datetime NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(`key1`, `date`, `key2`)
COMMENT "OLAP"
PARTITION BY RANGE(date)
(
    START ("2023-01-01") END ("2023-12-31") EVERY (INTERVAL 1 DAY)
)
DISTRIBUTED BY HASH(`key2`, `date`) BUCKETS 12 
PROPERTIES (
"replication_num" = "2",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-100",
"dynamic_partition.end" = "3",
"dynamic_partition.prefix" = "p",
"dynamic_partition.history_partition_num" = "0",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "true",
"compression" = "LZ4"
);
2. Fill data into the table, and check the storage usage. 

### Expected behavior (Required)
Total size of the index files is less than 20% of the data files.The less is better.
### Real behavior (Required)
Total size of the index files is up to  93% of the data files

### StarRocks version (Required)
2.5.5 24c1eca

**Comment by sevev** [comment]
@leozhangsr How many rows are in this table and what is the average length of key columns？

**Comment by leozhangsr** [comment]
> 



> @leozhangsr How many rows are in this table and what is the average length of key columns？

3009267479 rows, 74 partitions, average 40665776 per partition. 
Average length of key1 is 16, and key2 is a md5 text, which is fixed to 32.

**Comment by sevev** [comment]
> >
> ------------- info from show backends -----------------
TabletNum: 137556
DataUsedCapacity: 395.029 GB
AvailCapacity: 159.755 GB
TotalCapacity: 1007.804 GB
--------------statistic info from disk --------------------
dat files size: 411.1 GB
index.l0 : 53.54 GB
index.l1 : 329.34 GB

Another question, how many BE in you cluster and how many tables enable persistent index in your cluster? Is the index file size above the sum of the index file sizes on all BEs? Or is it just one of the BE's? @leozhangsr

**Comment by leozhangsr** [comment]
> > > 
> > 
> > 
> > ------------- info from show backends -----------------
> > TabletNum: 137556
> > DataUsedCapacity: 395.029 GB
> > AvailCapacity: 159.755 GB
> > TotalCapacity: 1007.804 GB
> > --------------statistic info from disk --------------------
> > dat files size: 411.1 GB
> > index.l0 : 53.54 GB
> > index.l1 : 329.34 GB
> 
> Another question, how many BE in you cluster and how many tables enable persistent index in your cluster? Is the index file size above the sum of the index file sizes on all BEs? Or is it just one of the BE's? @leozhangsr
I have 4 be in my cluster.All the primary tables have enabled persistent index.
The index file above is just one for the be's. Since the data is  distributed by HASH(key2, date), and the key2 is a md5 text, all the data is distributed evenly.You can time 4 to get the total size over the cluster.

**Comment by sevev** [comment]
> > > > 
> > > 
> > > 
> > > ------------- info from show backends -----------------
> > > TabletNum: 137556
> > > DataUsedCapacity: 395.029 GB
> > > AvailCapacity: 159.755 GB
> > > TotalCapacity: 1007.804 GB
> > > --------------statistic info from disk --------------------
> > > dat files size: 411.1 GB
> > > index.l0 : 53.54 GB
> > > index.l1 : 329.34 GB
> > 
> > 
> > Another question, how many BE in you cluster and how many tables enable persistent index in your cluster? Is the index file size above the sum of the index file sizes on all BEs? Or is it just one of the BE's? @leozhangsr
> 
> I have 4 be in my cluster.All the primary tables have enabled persistent index. The index file above is just one for the be's. Since the data is distributed by HASH(key2, date), and the key2 is a md5 text, all the data is distributed evenly.You can time 4 to get the total size over the cluster.

Can you provide the total number of rows and the average length of the primary key columns for all primary key tables？

**Comment by leozhangsr** [comment]
> > > > > 
> > > > 
> > > > 
> > > > ------------- info from show backends -----------------
> > > > TabletNum: 137556
> > > > DataUsedCapacity: 395.029 GB
> > > > AvailCapacity: 159.755 GB
> > > > TotalCapacity: 1007.804 GB
> > > > --------------statistic info from disk --------------------
> > > > dat files size: 411.1 GB
> > > > index.l0 : 53.54 GB
> > > > index.l1 : 329.34 GB
> > > 
> > > 
> > > Another question, how many BE in you cluster and how many tables enable persistent index in your cluster? Is the index file size above the sum of the index file sizes on all BEs? Or is it just one of the BE's? @leozhangsr
> > 
> > 
> > I have 4 be in my cluster.All the primary tables have enabled persistent index. The index file above is just one for the be's. Since the data is distributed by HASH(key2, date), and the key2 is a md5 text, all the data is distributed evenly.You can time 4 to get the total size over the cluster.
> 
> Can you provide the total number of rows and the average length of the primary key columns for all primary key tables？

check if this data can meet your need
[starrocks_index_issue_stat.xlsx](https://github.com/StarRocks/starrocks/files/11573754/starrocks_index_issue_stat.xlsx)

**Comment by sevev** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > ------------- info from show backends -----------------
> > > > > TabletNum: 137556
> > > > > DataUsedCapacity: 395.029 GB
> > > > > AvailCapacity: 159.755 GB
> > > > > TotalCapacity: 1007.804 GB
> > > > > --------------statistic info from disk --------------------
> > > > > dat files size: 411.1 GB
> > > > > index.l0 : 53.54 GB
> > > > > index.l1 : 329.34 GB
> > > > 
> > > > 
> > > > Another question, how many BE in you cluster and how many tables enable persistent index in your cluster? Is the index file size above the sum of the index file sizes on all BEs? Or is it just one of the BE's? @leozhangsr
> > > 
> > > 
> > > I have 4 be in my cluster.All the primary tables have enabled persistent index. The index file above is just one for the be's. Since the data is distributed by HASH(key2, date), and the key2 is a md5 text, all the data is distributed evenly.You can time 4 to get the total size over the cluster.
> > 
> > 
> > Can you provide the total number of rows and the average length of the primary key columns for all primary key tables？
> 
> check if this data can meet your need [starrocks_index_issue_stat.xlsx](https://github.com/StarRocks/starrocks/files/11573754/starrocks_index_issue_stat.xlsx)

Sorry, I may not have expressed myself clearly. What I was trying to say is that you have multiple primary key tables enable persistent index in your cluster. I want to know the total number of rows and the average length of the key columns for each of these tables, just like :

**Comment by leozhangsr** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > ------------- info from show backends -----------------
> > > > > > TabletNum: 137556
> > > > > > DataUsedCapacity: 395.029 GB
> > > > > > AvailCapacity: 159.755 GB
> > > > > > TotalCapacity: 1007.804 GB
> > > > > > --------------statistic info from disk --------------------
> > > > > > dat files size: 411.1 GB
> > > > > > index.l0 : 53.54 GB
> > > > > > index.l1 : 329.34 GB
> > > > > 
> > > > > 
> > > > > Another question, how many BE in you cluster and how many tables enable persistent index in your cluster? Is the index file size above the sum of the index file sizes on all BEs? Or is it just one of the BE's? @leozhangsr
> > > > 
> > > > 
> > > > I have 4 be in my cluster.All the primary tables have enabled persistent index. The index file above is just one for the be's. Since the data is distributed by HASH(key2, date), and the key2 is a md5 text, all the data is distributed evenly.You can time 4 to get the total size over the cluster.
> > > 
> > > 
> > > Can you provide the total number of rows and the average length of the primary key columns for all primary key tables？
> > 
> > 
> > check if this data can meet your need [starrocks_index_issue_stat.xlsx](https://github.com/StarRocks/starrocks/files/11573754/starrocks_index_issue_stat.xlsx)
> 
> Sorry, I may not have expressed myself clearly. What I was trying to say is that you have multiple primary key tables enable persistent index in your cluster. I want to know the total number of rows and the average length of the key columns for each of these tables, just like :
> 
> > table1: 100 Million rows, average length of key columns: 48 bytes
> > table2: 1 Billion rows, average length of key columns: 64 bytes
> > ...
the excel I provided previously had all the raw data you want, I have rearranged the data into the format you want as below. 
[primary_table_stat.xlsx](https://github.com/StarRocks/starrocks/files/11587719/primary_table_stat.xlsx)

**Comment by leozhangsr** [comment]
close
