### ISSUE TITLE
StarRocks Stream Load 数据提示不当

### ISSUE THREAD

**Issue by wwx441476** [StarRocks/starrocks#24316]
1. StarRocks建表语句 版本2.4.1 cc3c302

`create table JW_JCDM_JXLDMB(
XMLBDM    VARCHAR(255)     comment '  项目类别代码 ' ,
XMDM    VARCHAR(255)     comment '  项目代码 ' ,
XMMC    VARCHAR(255)     comment '  项目类别名称 ' ,
XMYWMC    VARCHAR(255)     comment '  项目英文名称 ' ,
XMSYZT    CHAR     comment '  项目使用状态(1启用,0停用) ' ,
XMLBBZ    VARCHAR(255)     comment '  项目类别备注 ' ,
XMYXJ    VARCHAR(255)     comment '  项目优先级 ' 
 )
ENGINE=OLAP
DUPLICATE KEY(XMLBDM)
DISTRIBUTED BY HASH(XMLBDM) BUCKETS 5
PROPERTIES(
    "storage_type" = "column",
    "replication_num" = "2"
)  ;`

2. java代码
`HttpClientBuilder httpClientBuilder = HttpClients
                .custom()
                .setRedirectStrategy(new DefaultRedirectStrategy() {
                    @Override
                    protected boolean isRedirectable(String method) {
                        return true;
                    }
                });
        String connection = "*.*.*.*";
        String streamLoadPort = "8031";
        String schemaName = "dmp_ana";
        String tableName = "JW_JCDM_JXLDMB";
        String username = "";
        String password = "";
        String url = String.format("http://%s:%s/api/%s/%s/_stream_load",
                connection,
                streamLoadPort,
                schemaName,
                tableName);
        CloseableHttpClient httpClient = httpClientBuilder.build();
        HttpPut httpPut = new HttpPut(url);
        httpPut.setHeader(HttpHeaders.EXPECT, "100-continue");
        httpPut.setHeader(HttpHeaders.AUTHORIZATION, "*");
//        httpPut.setHeader(HttpHeaders.ACCEPT, "application/json;charset=UTF-8");
//        httpPut.setHeader(HttpHeaders.CONTENT_TYPE, "application/x-www-form-urlencoded;charset=UTF-8");
        httpPut.setHeader("strip_outer_array", "true");
        httpPut.setHeader("format", "json");
        httpPut.setHeader("strict_mode", "true");
//        httpPut.setHeader("merge_type", "MERGE");
//        httpPut.setHeader("delete", "canal_type=\"DELETE\"");
        httpPut.setHeader("column_separator", ",");
        httpPut.setHeader("columns", "JXLDM,JXLMC,XQH_ID,PKYXJ,PKSYXJ,SFQY,JXLYWMC,SFCDZYPT");
//        httpPut.setHeader("columns", "XMLBDM,JXLMC,XQH_ID,PKYXJ,PKSYXJ,SFQY,JXLYWMC,SFCDZYPT");
        String cnt = "[{\"XMMC1\":\"1\",\"XMDM1\":\"图书馆\",\"XMYWMC1\":\"null\",\"XMLBBZ1\":\"1\",\"XMYXJ1\":\"null\",\"XMSYZT1\":\"null\",\"XMLBDM1\":\"20\"}]";
        JSONArray objects = JSONArray.parseArray(cnt);
        httpPut.setEntity(new StringEntity(objects.toJSONString(), "UTF-8"));
        httpPut.setConfig(RequestConfig.custom()
                .setSocketTimeout(600000)
                .setConnectTimeout(600000)
                .setConnectionRequestTimeout(600000)
                .build());
        try (CloseableHttpResponse response = httpClient.execute(httpPut)){
            String loadResult = "";
            if (response.getEntity() != null) {
                loadResult = EntityUtils.toString(response.getEntity());
            }
            final int statusCode = response.getStatusLine().getStatusCode();
            // statusCode 200 just indicates that starrocks be service is ok, not stream load
            // you should see the output content to find whether stream load is success
            if (!(statusCode == 200 && JSONObject.parseObject(loadResult).getString("Status").equalsIgnoreCase("Success"))) {
                throw new IOException(
                        String.format("Stream load failed, statusCode=%s load result=%s", statusCode, loadResult));
            }
        } catch (IOException e) {
            e.printStackTrace();
        }`
3. 响应提示 all partitions have no load data
`{
    "TxnId": 3623340,
    "Label": "6500260a-c4a1-405b-b659-e472076740e8",
    "Status": "Fail",
    "Message": "all partitions have no load data",
    "NumberTotalRows": 0,
    "NumberLoadedRows": 0,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 114,
    "LoadTimeMs": 12,
    "BeginTxnTimeMs": 0,
    "StreamLoadPlanTimeMs": 1,
    "ReadDataTimeMs": 0,
    "WriteDataTimeMs": 9,
    "CommitAndPublishTimeMs": 0
}`

**Comment by jaogoy** [comment]
建议修改下格式吧，否则真的没法看
