### ISSUE TITLE
Function: window_ Funnel model: 4, same event type, calculation error

### ISSUE THREAD

**Issue by zmns** [StarRocks/starrocks#24348]
data set

<img width="729" alt="image" src="https://github.com/StarRocks/starrocks/assets/34592135/6f0f971c-9938-427b-8e85-10b20671fc3c">

Query statement

> SELECT uid,
		 window_funnel(1800,
		 event_time,
		 4,
		 [event_type='点击', event_type='点击', event_type='点击']) as LEVEL
FROM 
    action_test t
  GROUP BY  uid;

result
<img width="542" alt="image" src="https://github.com/StarRocks/starrocks/assets/34592135/bea6ab85-7890-4caf-844d-3dd09b1a0d1f">

The event type is the same, but the time is different. Model: 4 statistics error
I think the level should be 3. Is this a bug?

Create Table Statement
> CREATE TABLE `action_test` (
  `event_time` datetime NOT NULL COMMENT "datetime of event",
  `event_type` varchar(65533) NOT NULL COMMENT "type of event",
  `uid` int(11) NULL COMMENT "id of user"
) ENGINE=OLAP 
DUPLICATE KEY(`event_time`, `event_type`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`uid`) BUCKETS 8 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"compression" = "LZ4"
);

Data insertion statement

> insert into action_test (event_time,event_type,uid) values(STR_TO_DATE('2020-01-02 11:40:00', '%Y-%m-%d %H:%i:%s'),'点击',4);
insert into action_test (event_time,event_type,uid) values(STR_TO_DATE('2020-01-02 11:50:00', '%Y-%m-%d %H:%i:%s'),'点击',4);
insert into action_test (event_time,event_type,uid) values(STR_TO_DATE('2020-01-02 12:00:00', '%Y-%m-%d %H:%i:%s'),'点击',4);

**Comment by LiShuMing** [comment]
version : 2.5.3

**Comment by LiShuMing** [comment]
![image](https://github.com/StarRocks/starrocks/assets/5104975/c74c73fa-98ce-4829-9125-c4740dc8df26)

You choose the mode 4 which means "the filtered events must have strictly increasing timestamps. Duplicate timestamp disrupts the event chain. ".

If you no need the strictly increasing  for the filtered events, you can try other modes:

![image](https://github.com/StarRocks/starrocks/assets/5104975/77aa76e2-dd96-41e3-990b-50a32594e92c)
