### ISSUE TITLE
Support Light Schema Change of adding and dropping columns

### ISSUE THREAD

**Issue by dujijun007** [StarRocks/starrocks#24341]
## Background
I found that simply adding a few value columns takes a long time, even though StarRocks supports hard link schema changes. As the number of partitions, buckets, and replicas increases, the duration growth of schema changes becomes more noticeable.

## Solution
The light schema change request will not be sent to the BE, but rather will be completed directly on the FE side. The schema consistency will be delegated to the BE side for resolution:
- For queries, the FE will sent the latest schema with all BE sides each time, utilizing the most recent schema when reading columns.
- For writing/deleting, the FE side will sent the latest schema to the BE side, and the most recently written rowset will carry the updated schema.
- For compaction, the schema with the newest version of rowset will be selected as the merged data schema.
- For every column in the new version, the unique id will be generated by FE, and send to BE.
- For adding/dropping a value column, apply light schema change. For the key column, fallback to the old way.
- For the tables created in old version, the schema change should always act as the old way.

**Overall**
![image](https://github.com/StarRocks/starrocks/assets/28496936/7cf18cb4-63ed-44f9-a3d0-003364b38207)

**Schema Change**
![image](https://github.com/StarRocks/starrocks/assets/28496936/f953acd0-05fc-44e8-9e57-76e96f32c03c)

**Write**
![image](https://github.com/StarRocks/starrocks/assets/28496936/e0d35e77-de4c-4dc7-aa04-87062db1299c)

**Query**
![image](https://github.com/StarRocks/starrocks/assets/28496936/70337faa-bd9f-49cb-8f74-32c511c2c826)

**Compaction**
<img width="684" alt="image" src="https://github.com/StarRocks/starrocks/assets/28496936/4e1f9e48-ef09-4e3d-8037-92a5374f7d17">

**Delete**
<img width="748" alt="image" src="https://github.com/StarRocks/starrocks/assets/28496936/dfb5bd11-6f41-4fd8-9258-815c9870b34a">

## Other Tasks
**Global Schema Cache**
Since the metadata of Rowset is always stored in memory, if each RowsetMeta stores a Schema, it will put a lot of pressure on the memory. In order to solve this problem, a global Schema Cache is implemented to manage the same Schema, so that even if there are thousands of Rowsets, as long as the Schemas are the same, only one Schema will exist in memory.

**Support materialized view and Rollup**
Light Schema Change also implements support for materialized views. After modifying the read and write process, the materialized view can also be read and written normally. At the same time, if the column to be deleted is a value column in the materialized view, Light Schema Change will be triggered with the base table; if the value column in the base table is the key column in the materialized view, an asynchronous task needs to be initiated to perform Sort/Direct Schema Change.

**Support rename value column**
Renaming is equivalent to dropping a column and add a new one, thanks to the unique column id generated by FE side, it will not conflict with the historical schema.

**Comment by sevev** [comment]
Starrocks already has schema cache in BE and all tablets belong one table will use a tablet schema. All schemas will has a unique schema_id which will be reallocated,

**Comment by sevev** [comment]
Greate Job! Thank you for your contribution.

I have some questions:

1. How to turn on light schema change in new created table? Can this feature be turned off? If once turn off, can it be turn on again?
2. Can we support it for the tables created in old version?
3. Can Schema Change tasks be submitted concurrently?

A small advice:

Starrocks already has schema cache in BE and all tablets belong one table will use a tablet schema. All schemas will has a unique schema_id which will be reallocated, maybe you can use it to realize the Global Schema Cache.

**Comment by dujijun007** [comment]
> Greate Job! Thank you for your contribution.
> 
> I have some questions:
> 
> 1. How to turn on light schema change in new created table? Can this feature be turned off? If once turn off, can it be turn on again?
> 2. Can we support it for the tables created in old version?
> 3. Can Schema Change tasks be submitted concurrently?
> 
> A small advice:
> 
> Starrocks already has schema cache in BE and all tablets belong one table will use a tablet schema. All schemas has a unique schema_id which generate in FE, maybe you can use it to realize the Global Schema Cache.

Thank you for your advice! 
1. We will allow users set a `enable_light_schema_change=true` in table properties to open this feature, and allow them to change it via `alter_table_properties_clause`. After this feature becomes stable, we will set it by default.
2. it's a little risky, we want to modify `OlapTable` to add unique column id and upgrade version number, it would affect  serialization/deserialization of metadata. 
3. we design it to lock on table rather than database, so submit tasks concurrently would not trigger thread unsafe issues, and meanwhile schema change within different tables could run concurrently.

**Comment by zhangruchubaba** [comment]
I think this idea is great, currently adding columns takes a long time and is also our pain point
