### ISSUE TITLE
Is support for the Iceberg REST Catalog going to be introduced in StarRocks external catalog functionality in an upcoming 3.x release build? 

### ISSUE THREAD

**Issue by chrisfw** [StarRocks/starrocks#24428]
Hi,

I noticed in the roadmap for 2023 enhanced support for Iceberg is planned.  I found a reference in the latest StarRocks code to the Iceberg REST catalog type and was wondering when that catalog type will be available for use in an upcoming release build?

Regards,
Chris Whelan

```
package com.starrocks.connector.iceberg;

public enum IcebergCatalogType {
    HIVE_CATALOG,
    CUSTOM_CATALOG,
    GLUE_CATALOG,
    REST_CATALOG,
    UNKNOWN;
    // TODO: add more iceberg catalog type

    public static IcebergCatalogType fromString(String catalogType) {
        for (IcebergCatalogType type : IcebergCatalogType.values()) {
            if (type.name().equalsIgnoreCase(String.format("%s_CATALOG", catalogType))) {
                return type;
            }
        }
        return UNKNOWN;
    }
}
```

**Comment by alberttwong** [comment]
it's already in main branch.   What we don't support is Apache Iceberg S3 signing.

**Comment by chrisfw** [comment]
@alberttwong , thank you for your quick reply.  That is great to hear.  Is there any documentation you can point me to with instructions on how to create an external iceberg catalog specifically of type REST?  I am following the 3.0 docs, but they don't have an Iceberg example for the REST catalog type.  I tried a variety of different property names and can create the external catalog reference successfully in StarRocks, but I keep getting the error `SQL Error [1064] [42000]: Invalid uri for http client: null` when I execute `show databases from icebergcat;`  

```
CREATE EXTERNAL CATALOG icebergcat
PROPERTIES ("type"="iceberg", 
"iceberg.catalog.type"="REST",
"iceberg.catalog.restcatalog.uri."="http://10.18.102.29:8181",
"iceberg.catalog.restcatalog"="org.apache.iceberg.spark.SparkCatalog",
"iceberg.catalog.restcatalog.warehouse"="s3a://warehouse",
"iceberg.catalog.restcatalog.io-impl"="org.apache.iceberg.aws.s3.S3FileIO",
"iceberg.catalog.restcatalog.s3.endpoint"="http://10.18.102.29:9000",
"iceberg.catalog.my_catalog.token"="redacted"
```

**Comment by chrisfw** [comment]
Hi again @alberttwong ,

I was able to get further utilizing the Iceberg rest catalog in StarRocks 3.0.0 through experimentation, but I am unable to retrieve data from an iceberg table hosted in MINIO.  I added AWS region and secrets in the fe.conf JAVA properties, but perhaps I am unable to get the correct combination of the remaining property names or StarRocks is attempting to query information schema tables that are not available.  

Any assistance you can provide would be greatly appreciated.  All of the statements below work until I try to execute `select * from restsample;`

```
CREATE EXTERNAL CATALOG icebergcat
PROPERTIES ("type"="iceberg", 
"iceberg.catalog.type"="REST",
"uri"="http://10.18.102.29:8181",
"token"="redacted",
"catalog.warehouse"="s3://warehouse",
"s3.endpoint"="http://10.18.102.29:9000"
);
show catalogs;

show databases from icebergcat;

use icebergcat.resticeberg;

show tables;

select * from restsample;
```

The error that is returned from StarRocks is:  
```
2023-05-31 21:14:25,166 INFO (starrocks-mysql-nio-pool-18|353) [MetadataMgr$QueryMetadatas.getConnectorMetadata():244] Succeed to register query level connector metadata [catalog:icebergcat, queryId: 1ec67c39-fff8-11ed-83c3-020017137546]
2023-05-31 21:14:25,203 ERROR (starrocks-mysql-nio-pool-18|353) [MetadataMgr.getRemoteFileInfos():185] Failed to list remote file's metadata on catalog [icebergcat], table [Table [id=100000246, name=restsample, type=ICEBERG]]
software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 400, Request ID: 176456DC6941DD60, Extended Request ID: e3b0c44298fc1c149afbf4c8996fb924
```
And the rest server has a corresponding error:
```
2023-05-31 21:13:37,702 ERROR [qtp2108044736-78] org.apache.iceberg.rest.RESTCatalogServlet: Error processing REST request
org.apache.iceberg.exceptions.RESTException: Unhandled error: ErrorResponse(code=404, type=NoSuchNamespaceException, message=Namespace does not exist: information_schema)
org.apache.iceberg.exceptions.NoSuchNamespaceException: Namespace does not exist: information_schema
        at org.apache.iceberg.jdbc.JdbcCatalog.loadNamespaceMetadata(JdbcCatalog.java:387)
        at org.apache.iceberg.rest.CatalogHandlers.loadNamespace(CatalogHandlers.java:118)
        at org.apache.iceberg.rest.RESTCatalogAdapter.handleRequest(RESTCatalogAdapter.java:281)
 
```

**Comment by alberttwong** [comment]
Are you on starrocks slack?

**Comment by alberttwong** [comment]
Did you also look at our tutorials?  https://github.com/StarRocks/starrocks/discussions/23616

**Comment by alberttwong** [comment]
Here is also another one that uses the apache iceberg quickstart as a base.  https://github.com/StarRocks/starrocks/discussions/23427

**Comment by chrisfw** [comment]
@alberttwong , thanks a lot for the tutorial links.  They are very helpful.  I will try to adapt the information to my MINIO storage config.
