### ISSUE TITLE
Support MILLISECOND unit for TIMESTAMPADD and TIMESTAMPDIFF

### ISSUE THREAD

**Issue by rcauble** [StarRocks/starrocks#24481]
## Feature request

**Is your feature request related to a problem? Please describe.**
We often need to deal with milliseconds precision as it is necessary to disambiguate events that occur at nearly the same time. 

**Describe the solution you'd like**
Would like a MILLISECOND unit for TIMESTAMPADD and TIMESTAMPDIFF like in Vertica:

https://www.vertica.com/docs/9.3.x/HTML/Content/Authoring/SQLReferenceManual/Functions/Date-Time/TIMESTAMPADD.htm

**Describe alternatives you've considered**
If we had a function to convert from a DATETIME to milliseconds since unix epoch, we could do the math ourselves, but it seems that that function doesn't exist either.

**Additional context**

**Comment by wangsimo0** [comment]
actually, starrocks support microsecond. so it is better to support millisecond and microsecond.

**Comment by wg1026688210** [comment]
Assign to me plz, I will start the thread at this weekend
