### ISSUE TITLE
Poor query performance cause by too high schedule time when deployed with k8s

### ISSUE THREAD

**Issue by dujijun007** [StarRocks/starrocks#24534]
#### sql
TPCH 1000G

Q2
select count(*) from (
select  s_acctbal, s_name,  n_name,  p_partkey,  p_mfgr,  s_address,  s_phone,  s_comment
from  part,  partsupp,  supplier,  nation,  region
where
  p_partkey = ps_partkey
  and s_suppkey = ps_suppkey
  and p_size = 15
  and p_type like '%BRASS'
  and s_nationkey = n_nationkey
  and n_regionkey = r_regionkey
  and r_name = 'EUROPE'
  and ps_supplycost = (
    select  min(ps_supplycost)
    from  partsupp,  supplier,  nation,  region
    where
      p_partkey = ps_partkey
      and s_suppkey = ps_suppkey
      and s_nationkey = n_nationkey
      and n_regionkey = r_regionkey
      and r_name = 'EUROPE'
  )
order by  s_acctbal desc, n_name,  s_name,  p_partkey
) as t1;

#### Test enviroment
3 fe and 3 be, 84 core 350g, Linux version 5.4.119, gcc version 8.5.0 20210514 (Red Hat 8.5.0-10)
Both k8s deployment and physical cluster deployment have the same physical hardware resources.

#### Query performance
k8s deployment with best-effort
![image](https://github.com/StarRocks/starrocks/assets/28496936/8f6b236b-496d-4805-936b-e6fc427f9e7a)

Physical cluster deployment
![image](https://github.com/StarRocks/starrocks/assets/28496936/c7ad82cb-39d1-47f0-9d8b-f4d7b561f645)

#### Profile
[profile-k8s.txt](https://github.com/StarRocks/starrocks/files/11621958/profile-k8s.txt)
[profile-physical-cluster.txt](https://github.com/StarRocks/starrocks/files/11621963/profile-physical-cluster.txt)

k8s deployment with best-effort
![image](https://github.com/StarRocks/starrocks/assets/28496936/0e40a54c-e720-4be8-9e64-88c48ea249f3)

Physical cluster deployment
![image](https://github.com/StarRocks/starrocks/assets/28496936/548a1e16-abbd-48e2-a14f-a6f12a0a3a05)

#### Flame Graph
k8s deployment with best-effort
![image](https://github.com/StarRocks/starrocks/assets/28496936/aff4d85b-77b2-421f-84d2-bd0dd13f0958)

Physical cluster deployment
![image](https://github.com/StarRocks/starrocks/assets/28496936/9f7cff21-0feb-4fa9-8c31-685211ec382f)

found that 22% cpu overhead show at poll thread to schedule pipeline_driver when deployed with k8s whereas physical cluster deployment show 1%~ cpu overhead.

### StarRocks version (Required)
2.5.4-TQ-0.6 dbc1950

Can someone offer some clues or provide any better way to analyze this problem?

**Comment by liuyehcf** [comment]
Can you add some pod information which be belongs to?

**Comment by dujijun007** [comment]
> Can you add some pod information which be belongs to?
> 
> 1. `kubectl get pod -n <namespace> <pod-name> -o yaml`
> 2. `kubectl describe pod -n <namespace> <pod-name>`

apiVersion: v1
kind: Pod
metadata:
  annotations:
    apps.kruise.io/runtime-containers-meta: '{"containers":[]}'
    lifecycle.apps.kruise.io/timestamp: "2023-05-29T02:54:32Z"
    prometheus.io/path: /metrics
    prometheus.io/port: "8040"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  creationTimestamp: "2023-05-29T02:54:32Z"
  generateName: xxx
  labels:
    app.kubernetes.io/component: be
    app.starrocks.ownerreference/name: xxx
    controller-revision-hash: xxx-be-68bf545df9
    lifecycle.apps.kruise.io/state: Normal
    statefulset.kubernetes.io/pod-name: xxx
  name: xxx
  namespace: starrocks
  ownerReferences:
  - apiVersion: apps.kruise.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: xxx
    uid: 8cd14137-34ce-4a13-b71e-3ab6de2ae834
  resourceVersion: "1257272330"
  selfLink: /api/v1/namespaces/starrocks/pods/xxx
  uid: 03a001ca-91b4-4202-8e8a-337ebb444672
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node.info.kubernetes.io/instance-type
            operator: In
            values:
            - IT5.21XLARGE320
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/component
            operator: In
            values:
            - fe
        topologyKey: kubernetes.io/hostname
  containers:
  - args:
    - $(FE_SERVICE_NAME)
    command:
    - /opt/starrocks/be_entrypoint.sh
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: COMPONENT_NAME
      value: cn
    - name: FE_SERVICE_NAME
      value: xxx-service
    - name: FE_SERVICE_CLB_IP
      value: 30.169.206.238
    - name: FE_QUERY_PORT
      value: "9030"
    - name: HOST_TYPE
      value: FQDN
    - name: USER
      value: root
    - name: SUB_DOMAIN
      value: xxx
    - name: CONFIGMAP_MOUNT_PATH
      value: /opt/starrocks/be/conf
    image: xxx
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /opt/starrocks/be_prestop.sh
    livenessProbe:
      failureThreshold: 3
      periodSeconds: 5
      successThreshold: 1
      tcpSocket:
        port: 9050
      timeoutSeconds: 1
    name: be
    ports:
    - containerPort: 9060
      hostPort: 9060
      name: be-port
      protocol: TCP
    - containerPort: 8040
      hostPort: 8040
      name: webserver-port
      protocol: TCP
    - containerPort: 9050
      hostPort: 9050
      name: heartbeat-port
      protocol: TCP
    - containerPort: 8060
      hostPort: 8060
      name: brpc-port
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      periodSeconds: 5
      successThreshold: 1
      tcpSocket:
        port: 9060
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "84"
        memory: 350Gi
      requests:
        cpu: "84"
        memory: 350Gi
    startupProbe:
      failureThreshold: 60
      periodSeconds: 5
      successThreshold: 1
      tcpSocket:
        port: 8060
      timeoutSeconds: 1
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/starrocks/be/log
      name: be-log
    - mountPath: /opt/starrocks/be/storage
      name: be-storage
    - mountPath: /opt/starrocks/be/conf/be.conf
      name: be-config
      subPath: be.conf
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: xxx
      readOnly: true
  dnsPolicy: ClusterFirstWithHostNet
  enableServiceLinks: true
  hostNetwork: true
  hostname: xxx
  nodeName: xxx
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  readinessGates:
  - conditionType: InPlaceUpdateReady
  - conditionType: KruisePodReady
  restartPolicy: Always
  schedulerName: batch-scheduler
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  serviceAccount: default
  serviceAccountName: default
  subdomain: xxx
  terminationGracePeriodSeconds: 120
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /data13/xxx/sr/be-log
      type: DirectoryOrCreate
    name: be-log
  - hostPath:
      path: /data13/xxx/sr/be-storage
      type: DirectoryOrCreate
    name: be-storage
  - configMap:
      defaultMode: 420
      name: be-config
    name: be-config
  - name: xxx
    secret:
      defaultMode: 420
      secretName: xxx
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-05-29T02:54:32Z"
    status: "True"
    type: KruisePodReady
  - lastProbeTime: null
    lastTransitionTime: "2023-05-29T02:54:32Z"
    status: "True"
    type: InPlaceUpdateReady
  - lastProbeTime: null
    lastTransitionTime: "2023-05-29T02:54:32Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-05-29T02:54:44Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-05-29T02:54:44Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-05-29T02:54:32Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: xxx
    image: xxx
    imageID: xxx
    lastState: {}
    name: be
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-05-29T02:54:33Z"
  hostIP: 30.174.255.85
  phase: Running
  podIP: 30.174.255.85
  podIPs:
  - ip: 30.174.255.85
  qosClass: Guaranteed
  startTime: "2023-05-29T02:54:32Z"

**Comment by dujijun007** [comment]
> Please provide the svg file of the above two flame graphs

svg file upload here is auto-transformed to a static image, please modify suffix to svg
[perf_physical_cluster.txt](https://github.com/StarRocks/starrocks/files/11622943/perf_physical_cluster.txt)
[perf_k8s.txt](https://github.com/StarRocks/starrocks/files/11622941/perf_k8s.txt)

**Comment by liuyehcf** [comment]
Thanks for your update. And here's another question, how many nodes(physical machines) are there in your k8s cluster? does each backend be deployed to different nodes?

**Comment by liuyehcf** [comment]
Thanks for update. I'll setup a similar environment to see if I can reproduce this problem and to figure out the reason.

**Comment by dujijun007** [comment]
> Thanks for update. I'll setup a similar environment to see if I can reproduce this problem and to figure out the reason.

thank you for your time~

**Comment by guangxuCheng** [comment]
> Thanks for update. I'll setup a similar environment to see if I can reproduce this problem and to figure out the reason.

any update？

**Comment by liuyehcf** [comment]
I have conduct a experiment at my local environment

starrocks-version: 2.5.4
k8s-version: v1.25.0
tpch_100g

| Query | starrocks-in-host-machine | starrocks-in-k8s | diff(k8s - host) |
|:--|:--|:--|:--|
| Q1 |  |  |  |
| Q1 |  |  |  |
| Q1 |  |  |  |
| Q1 |  |  |  |
| Q1 |  |  |  |
| Q1 |  |  |  |
| Q1 |  |  |  |
| Q1 |  |  |  |
| Q1 |  |  |  |
| Q1 |  |  |  |
| Q1 |  |  |  |
