### ISSUE TITLE
[Optimization]Convert case-when without case-clause to its counterpart with case-clause to leverage SimplifiedCaseWhenRule

### ISSUE THREAD

**Issue by satanson** [StarRocks/starrocks#24571]
## Enhancement

```sql
case when col = 'a' then 1 when col = 'b' then 2 else 3 end 

--- equivalent to 

case col when 'a' then 1 when 'b' then 2 else 3 end
```
SimplifiedCaseWhenRule optimized case-when with case-clause better than case-when without case-clause, so if the latter's when clause contains Eq binary predicates all of that  use the some column, we can convert it.

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it.
