### ISSUE TITLE
[Optimization] Reduce duplication factor to speed up count-distinct query 

### ISSUE THREAD

**Issue by satanson** [StarRocks/starrocks#24596]
## Enhancement

```sql
-- Q0: original sql
select count(distinct b) from t inner join s on t.a = s.a

-- Q1: equivalent optimized sql
select count(distinct b) from
(select distinct a, b from t ) t0 left semi join s on t0.a = s.a

-- Q2: equivalent optimized sql
select count(distinct b) from
(select a, b from t ) t0 left semi join s on t0.a = s.a
```

We find that Q0 can be speeded up for 10X~100X times after rewriting it into Q1 or Q2 in some typical scenarios.  Count-distinct aggregation has nothing to do with duplication factor in subplan below it. so we can reduce the duplication factors:
1. for join operators, we can use semi join instead inner join to output matched rows only once.
2. for other operators, we can put a DistinctAggregateOperator on it to deduplicate the rows.

It works fine when the duplication factors are quite high,  that is to say, join equal conjunctions' columns  and  DistinctAggregateOperator's output columns are low-cardinality.  it must be badcases if these columns are high-cardinality. so
row count and distinct values estimation in cost model can be employed to dictate whether to rewrite or not.

We can add a optimization rule to rewrite such queries, this rule take effect when:
1. cost model shows that involved columns are low cardinality.
2. add a bracket hint(e.g. [deduplicate]) to force the optimizer to rewrite the queries.

Introducing DistinctAggregateOperators can incurr spurious high cost of the plan, so cost model may be adjusted to recognize good plans and deny bad plans, this way may lead some abstract leak in the Cascades optimizer, so we implement the hint [deduplicate] at first.

**Comment by XinzhuangL** [comment]
Hi @satanson  Could you assign this task to me?  I'd like to try it.
