### ISSUE TITLE
希望update语法更新支持多表关联更新

### ISSUE THREAD

**Issue by arthurcommon** [StarRocks/starrocks#24607]
对于 update 语句，希望研发者们能够支持：用表B的某个字段去更新表A的某个字段

类似的表达如下：
update 表A
     set  表A.col=表B.col
   from 表A， 表B
 where 表A.id=表B.id
; 同时支持with 结构作为表B。

谢谢研发者们！

**Comment by decster** [comment]
already supported

**Comment by jaogoy** [comment]
@arthurcommon in V3.0
