### ISSUE TITLE
Cannot do a backup and recovery

### ISSUE THREAD

**Issue by success-m** [StarRocks/starrocks#24717]
### Steps to reproduce the behavior (Required)
```CREATE REPOSITORY hive_warehouse_repo
WITH BROKER
ON LOCATION "s3a://hive-warehouse/backup"
PROPERTIES(
    "aws.s3.access_key" = "key",
    "aws.s3.secret_key" = "secret",
    "aws.s3.endpoint" = "minio:9000"
);
```

### Expected behavior (Required)
Repository is created

### Real behavior (Required)
Runs for a long time and gives an error connecting to minio.

### StarRocks version (Required)
 - 2.5.1

**Comment by wasser-winfried** [comment]
similar problem with oracle object-store @ starrocks 3.1.3

`create repository s3_backup
with broker
on location "s3a://data-starrocks/backup"
PROPERTIES(
  "aws.s3.access_key" = "...",
  "aws.s3.secret_key" = "...",
  "aws.s3.endpoint" = "https://<tenant>.compat.objectstorage.eu-frankfurt-1.oraclecloud.com"
);
`

We only see the following errors
On Client:
`ERROR 1064 (HY000): Unexpected exception: Failed to create repository: failed to list remote path: s3a://data-starrocks/backup/__starrocks_repository_s3_backup/__repo_info. msg: listPath failed`

On Fe:
`2023-10-23 11:25:59,485 ERROR (starrocks-mysql-nio-pool-390|91083) [HdfsFsManager.listPath():1226] errors while get file status	at com.starrocks.fs.hdfs.HdfsFsManager.listPath(HdfsFsManager.java:1191) ~[starrocks-fe.jar:?]	at com.starrocks.fs.hdfs.HdfsService.listPath(HdfsService.java:59) ~[starrocks-fe.jar:?]com.starrocks.common.DdlException: Failed to create repository: failed to list remote path: s3a://data-starrocks/backup/__starrocks_repository_s3_backup/__repo_info. msg: listPath failed`

**Comment by wasser-winfried** [comment]
adding "aws.s3.enable_path_style_access" = "true" solves the problem - currently only documented at [https://docs.starrocks.io/en-us/latest/data_source/file_external_table](https://docs.starrocks.io/en-us/latest/data_source/file_external_table)
