### ISSUE TITLE
[drop task] task did not canceled after drop task

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#24740]
### Steps to reproduce the behavior (Required)
SUBMIT TASK test_kill AS CREATE TABLE TEST PROPERTIES ( "replication_num" = "1" ) AS SELECT sleep(1000);
select sleep(2);
drop task test_kill;
select TASK_NAME, STATE, ERROR_MESSAGE from information_schema.task_runs where `DATABASE`='yn_db';

### Expected behavior (Required)
```
+-----------+---------+---------------+
| TASK_NAME | STATE   | ERROR_MESSAGE |
+-----------+---------+---------------+
| test_kill | FAILED | CANCELLED          |
+-----------+---------+---------------+
```
### Real behavior (Required)
```
+-----------+---------+---------------+
| TASK_NAME | STATE   | ERROR_MESSAGE |
+-----------+---------+---------------+
| test_kill | RUNNING | NULL          |
+-----------+---------+---------------+
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`BRANCH-2.5-a865dd5`

**Comment by Astralidea** [comment]
This cannot be reproduced at present, so it is temporarily closed.
