### ISSUE TITLE
[drop task] drop task failed

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#24741]
### Steps to reproduce the behavior (Required)
```
submit task as insert overwrite t1 select * from t1;
drop task insert-ca1cdcca-0439-11ee-990f-00163e0e2cf9;
```
### Expected behavior (Required)
`drop ok`
### Real behavior (Required)
`ERROR 1064 (HY000): Getting syntax error at line 1, column 10. Detail message: Input 'insert' is not valid at this position.
`### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main-Release-e688b48

**Comment by Astralidea** [comment]
This should use the drop task `insert-ca1cdcca-0439-11ee-990f-00163e0e2cf9`;
But dropping a non-existent task will cause NPE and need to be dealt with.
