### ISSUE TITLE
Support returning arrays from "CASE WHEN" 

### ISSUE THREAD

**Issue by rcauble** [StarRocks/starrocks#24767]
## Feature request

**Is your feature request related to a problem? Please describe.**
CASE WHEN is a critical piece of our solution for calculating deltas and needs to be able to return arrays.

**Describe the solution you'd like**
Would like for "CASE WHEN" to support array types.

**Describe alternatives you've considered**
Unaware of any alternatives

**Additional context**

**Comment by fzhedu** [comment]
@rcauble  what's you SR version? this feature alread supported on the main branch in the last week.

**Comment by rcauble** [comment]
We're on 3.0-branch

**Comment by Seaven** [comment]
https://github.com/StarRocks/starrocks/pull/23786
