### ISSUE TITLE
[Bug] query exceed memory limit crashes the entire backend

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks#24788]
### Steps to reproduce the behavior (Required)
we have observed that the BE crashed when a query consume too much memory.

> [Driver] Process error, query_id=2a15d7bb-0485-11ee-a565-0a580a82d007, instance_id=2a15d7bb-0485-11ee-a565-0a580a82d00c, status=Memory limit exceeded: Memory of process exceed limit. Pipeline Backend: celostar-be-9.celostar-be-search.celostar.svc.cluster.local, fragment: 2a15d7bb-0485-11ee-a565-0a580a82d00c Used: 95803120968, Limit: 95789142835. Mem usage has exceed the limit of BE

### Expected behavior (Required)
I think the right behavior should be killing the query instead of killing the BE.

### Real behavior (Required)
Full log 
[extract-2023-06-06T20_07_21.982Z.log](https://github.com/StarRocks/starrocks/files/11672276/extract-2023-06-06T20_07_21.982Z.log)

### StarRocks version (Required)
 - 3.0

**Comment by stdpain** [comment]
in fact it was cased by 
```
"2023-06-06T16:24:45.119Z","/opt/starrocks/be/bin/start_be.sh: line 24: 31 Segmentation fault (core dumped) bash ${STARROCKS_HOME}/bin/start_backend.sh --be $@"
"2023-06-06T16:14:40.762Z","'@ 0x0 (unknown)"
"2023-06-06T16:14:40.762Z","'@ 0x7f4557546bb4 clone"
"2023-06-06T16:14:40.762Z","'@ 0x7f45574b5b43 (unknown)"
"2023-06-06T16:14:40.762Z","'@ 0x5e311ca starrocks::Thread::supervise_thread()"
"2023-06-06T16:14:40.762Z","'@ 0x5e36f0b starrocks::ThreadPool::dispatch_thread()"
"2023-06-06T16:14:40.762Z","'@ 0x5aeb866 starrocks::pipeline::GlobalDriverExecutor::_worker_thread()"
"2023-06-06T16:14:40.762Z","'@ 0x383cb49 starrocks::pipeline::PipelineDriver::finalize()"
"2023-06-06T16:14:40.762Z","'@ 0x383c513 starrocks::pipeline::PipelineDriver::_mark_operator_closed()"
"2023-06-06T16:14:40.762Z","'@ 0x3afd690 starrocks::pipeline::AggregateBlockingSinkOperator::close()"
"2023-06-06T16:14:40.762Z","'@ 0x38c7c45 starrocks::Aggregator::close()"
"2023-06-06T16:14:40.762Z","'@ 0x38a25f6 (unknown)"
"2023-06-06T16:14:40.762Z","'@ 0x79b8747 je_arena_dalloc_promoted"
"2023-06-06T16:14:40.762Z","'@ 0x7f4557463520 (unknown)"
"2023-06-06T16:14:40.762Z","'@ 0x6e63e0a google::(anonymous namespace)::FailureSignalHandler()"
```

**Comment by stdpain** [comment]
https://github.com/StarRocks/starrocks/pull/19633 will resolve this problem
https://github.com/StarRocks/starrocks/pull/21569
