### ISSUE TITLE
[BugFix] AUTO_INCREMENT column can be inserted by null using SELECT

### ISSUE THREAD

**Issue by srlch** [StarRocks/starrocks#24795]
Problem:
AUTO_INCREMENT column can not be specified by NULL through simple INSERT stmt. But It can be inserted by INSERT INTO t SELECT 1, NULL or INSERT INTO a t1 SELECT b from t2, where a is AUTO_INCREMENT column and b may contain NULL value.

Solution:
Check data in OlapTableSink::send_chunk, if AUTO_INCREMENT is specified in INSERT INTO SELECT stmt, the value can not be NULL.

**Comment by kevinbds** [comment]
I still have this issue when the select is performed on a VIEW
