### ISSUE TITLE
Broker load shall fail immediately with error message on wrong PROPERTIES setting

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks#24794]
## Enhancement
When there is misconfig in the broker load PROPERTIES(e.g. wrong AWS AK/SK or endpoint), broker load job state becomes `QEUEUEING`  with out and error message to help debug.

Suggest fixing this issue by setting the state to `CANCELLED` or `FAILED` and have details in ErrorMsg fields.
This is essential for the upstream service to check the status and take appropriate measure for failure resilience. 

![image](https://github.com/StarRocks/starrocks/assets/5108773/2c3a5f29-6b32-4db3-a6d9-57ad82492ce3)

cc @chaoyli

**Comment by rickif** [comment]
Thanks for reporting this issue. It's highly OK to add a check whether the ak/sk is set.
I'll resolve it.

**Comment by rickif** [comment]
![image](https://github.com/StarRocks/starrocks/assets/16649269/573efa98-3cd4-43c0-a108-bd1893f553da)
I've checked the latest version of branch-2.5/branch-3.0 and found that the result has been shown like this. It seems to be what you want.

**Comment by dengliu** [comment]
It is PENDING state in a built from branch-3.0 commit hash https://github.com/StarRocks/starrocks/commits/a5dd8c36
on 5/23/2023

In this test, I issued the load sql with a wrong secret key in the properties.

> LOAD LABEL abb_10m.KNA1_4
> (
>     DATA INFILE("s3a://celostar/test_data/abb_10m/fd1c713c-d76f-4113-99d2-a22c38afc7a6/*.parquet")
>     INTO TABLE KNA1
>     FORMAT AS "parquet"
>     ******
> WITH BROKER
> (
>   "aws.s3.access_key" = "xxx",
>   "aws.s3.secret_key" = "WRONG SECRET", <===================
>   "aws.s3.region"="us-west-1"
> )
> PROPERTIES
> (
>     "timeout" = "36000", --  the timeout time in seconds for the import operation. e.g 3600 means 1 hr time out. Jobs not completed in timeout window will be CANCELLED state.
>     "max_filter_ratio" = "0.2", -- Data ratio of maximum tolerance filterable (data irregularity, etc.).
>     "timezone" = "America/Los_Angeles"
> );

 
![image](https://github.com/StarRocks/starrocks/assets/5108773/d4624fc6-b6a0-4fa6-8a6f-ef841bdb3005)

**Comment by rickif** [comment]
This is enhanced in https://github.com/StarRocks/starrocks/pull/21982.
Could you check it with a newer version again?
