### ISSUE TITLE
Unable to query external MySQL catalog's table with `longtext` column type

### ISSUE THREAD

**Issue by Ashish-Bansal** [StarRocks/starrocks#24813]
### Description

I'm unable to select from an external MySQL table which contains `longtext` column type. 

### Steps to reproduce the behavior (Required)

1. Create a table in MySQL with column type = longtext. 
2. Add this table as external catalog in starrocks. 
3. Query table from this catalog

```
mysql> select * from external_catalog.db.table;
ERROR 1064 (HY000): Datatype of external table column [description, extra_info] is not supported!
```

### StarRocks version (Required)

```
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| 2.5.4 1021a9299   |
+-------------------+
1 row in set (0.02 sec)
```

**Comment by zombee0** [comment]
2.5.4 doesn't support JDBC catalog, and longtext is support by https://github.com/StarRocks/starrocks/pull/22732, also you can use it as external resource table and specify the column type as varchar

**Comment by Ashish-Bansal** [comment]
I just upgraded to `3.0.1` and it works fine. Thanks!

**Comment by Ashish-Bansal** [comment]
> tinyint(1)

@zombee0 It seems like this isn't supported right now, right?

**Comment by zombee0** [comment]
@Ashish-Bansal tinting(1) is stored as bit in mysql, supported by https://github.com/StarRocks/starrocks/pull/26324/files

**Comment by Ashish-Bansal** [comment]
Oh, I see, you added it in https://github.com/StarRocks/starrocks/commit/932bc50d37327695d4a7b008691039d144ff62f3

Upgrading to 3.1 worked, thanks!
