### ISSUE TITLE
Can materialized view data be retained when deleting base table data?

### ISSUE THREAD

**Issue by jinshuangxian** [StarRocks/starrocks#24898]
## Feature request

**Is your feature request related to a problem? Please describe.**
Yes, the problem is that in StarRocks 3.0 version, when data is deleted from the base table, the corresponding data in the materialized view is also deleted. In the production environment, the base table contains detailed data that needs to be periodically cleaned up, but we want to retain the data in the materialized view.

**Describe the solution you'd like**
I would like to propose adding a configuration option that allows preserving (not deleting) the data in the materialized view, even when data is deleted from the base table.

**Describe alternatives you've considered**
no

**Additional context**
In our production environment, the base table contains large amounts of detailed data, and periodic cleanup is necessary to manage the data size. However, it is important to retain the data in the materialized view for reporting and analysis purposes. Therefore, having a configuration option to preserve the data in the materialized view would greatly benefit our workflow.

**Comment by LiShuMing** [comment]
Good Question.

Can I ask you the materialized view is `Synchronous materialized view` or `ASynchronous materialized view`?

https://docs.starrocks.io/en-us/latest/sql-reference/sql-statements/data-definition/CREATE%20MATERIALIZED%20VIEW

**Comment by LiShuMing** [comment]
If you mean `Synchronous materialized view`, now `Synchronous materialized view` behaviors like a `index`.  You need take care when you decouple the relation between `Synchronous materialized view` and the base table.

However We have some other solution to support this in our later version:
1. Support associated tables, you can use an existed table as the sync materialized view;
2. Use binlog to decouple `Synchronous materialized view` and the base table if you no need to acheive the strong consitency.

**Comment by jinshuangxian** [comment]
Thank you for your answer .
I am using Aynchronous materialized view.

**Comment by LiShuMing** [comment]
`Aynchronous materialized view.` will not drop the mv if you drop the base table?

can you give me some SQLs about this?

![image](https://github.com/StarRocks/starrocks/assets/5104975/f6edbb2d-2a25-439a-b469-09ecd50a0b4e)

**Comment by jinshuangxian** [comment]
It's not drop the base table, but delete the data in the base table.

![image](https://github.com/StarRocks/starrocks/assets/9390698/c829cadf-767f-4d06-9393-c5d81be08bf0)

![image](https://github.com/StarRocks/starrocks/assets/9390698/b9fbf200-655a-4bba-9fef-71b76d8ee014)

**Comment by mofeiatwork** [comment]
MV has several refresh mechanisms:
1. `MANUAL`:  MV would not be refreshed automatically, user needs to refresh it manually
2. `ASYNC`: The refreshing is triggered by updating of base table
3. `SCHEDULED`: specify the `INTERVAL` and `START` of refresh timing

IMO the `MANUAL` refresh is what you need ?
