### ISSUE TITLE
Can the materialized view have flexible partitioning fields

### ISSUE THREAD

**Issue by jinshuangxian** [StarRocks/starrocks#24907]
## Is your feature request related to a problem? Please describe.

Yes, the problem is that when creating a materialized view based on the "orders" table and using the `date_trunc('month', dt)` function to aggregate the data by month, an error occurs '`Materialized view partition function date_trunc must related with column`'.

Using the following SQL：

```sql
create table orders ( 
    day datetime NOT NULL, 
    order_id bigint NOT NULL, 
    user_id int NOT NULL, 
    merchant_id int NOT NULL, 
    good_id int NOT NULL, 
    good_name string NOT NULL, 
    price int NOT NULL, 
    cnt int NOT NULL, 
    revenue int NOT NULL, 
    state tinyint NOT NULL 
) 
PRIMARY KEY (day, order_id) 
PARTITION BY RANGE(`day`) 
( PARTITION p20210820 VALUES [('2023-06-01'), ('2023-07-01')), 
PARTITION p20210821 VALUES [('2023-07-01'), ('2023-08-01')) ) 
DISTRIBUTED BY HASH(order_id) BUCKETS 1
PROPERTIES (
    "replication_num" = "3", 
    "enable_persistent_index" = "true"
);

CREATE MATERIALIZED VIEW order_month_mv1
PARTITION BY date_trunc('month', month)
DISTRIBUTED BY HASH(`user_id`) BUCKETS 1 
REFRESH ASYNC START('2023-06-01 10:00:00') EVERY (interval 1 day)
AS
select
    date_trunc('month', `dt`) as month,
    user_id,
    sum(cnt) as total_cnt,
    sum(revenue) as total_revenue,
    count(state) as state_count
from orders
group by month, user_id;
```

Describe the solution you'd like
I would like to propose the ability to aggregate data using the date_trunc('month', dt) function and partition the materialized view based on the month.

Describe alternatives you've considered
no

Additional context
no

**Comment by carlosescura** [comment]
> There're some easy workarounds like referencing the column directly, so we don't plan to do it for this feature request right now.

Can you please elaborate more on this? What do you mean by referencing the column? I'm in the same situation and I would like to generate a MV that aggregates records by "less granular partition" based on "more granular partition" base table.
