### ISSUE TITLE
[Bug] SR query pg external table return no records because of different behavior of escape character from pg

### ISSUE THREAD

**Issue by yangrong688** [StarRocks/starrocks#24985]
### Steps to reproduce the behavior (Required)
pg side:

CREATE TABLE test_escape_table (
	id int8 NOT NULL,
	value varchar(100) null,
	CONSTRAINT test_escape_table_pkey PRIMARY KEY (id)
);

insert into test_escape_table values(1,'test\test');

select * from test_escape_table t where t.value='test\test';

1	test\test

sr side:

create external resource test_postgres_jdbc
properties (
    "type"="jdbc",
    "user"="root",
    "password"="$password",
    "jdbc_uri"="jdbc:postgresql://$ip:5432/$database?currentSchema=test_schema",
    "driver_url"="https://repo1.maven.org/maven2/org/postgresql/postgresql/42.3.3/postgresql-42.3.3.jar",
    "driver_class"="org.postgresql.Driver"
);

use db_test;

create external table test_escape_table (
    id bigint NULL,
	value varchar(100) NULL
) ENGINE=jdbc 
properties (
    "resource"="test_postgres_jdbc",
    "table"="test_escape_table"
);

select * from test_escape_table t where t.value='test\test';

### Expected behavior (Required)
query return records:
1	test\test

### Real behavior (Required)
return no records

explain select * from test_escape_table t where t.value='test\test';
```
PLAN FRAGMENT 0
 OUTPUT EXPRS:id | value
  PARTITION: UNPARTITIONED

  RESULT SINK

  0:SCAN JDBC
     TABLE: `test_escape_table`
"     QUERY: SELECT id, value FROM `test_escape_table` WHERE (value = 'test	est')"
     limit: 200
``` 

### StarRocks version (Required)
 2.5.6

**Comment by jaogoy** [comment]
What's the behavior supposed in PG?

**Comment by yangrong688** [comment]
> What's the behavior supposed in PG?

pg can normally query the record normally.

pg query:
select * from test_escape_table t where t.value='test\test';
1 test\test
