### ISSUE TITLE
Can starrocks be implemented? Store cold data in OSS or HDFS and provide the ability to query cold data

### ISSUE THREAD

**Issue by awk333** [StarRocks/starrocks#24982]
## Feature request

**Is your feature request related to a problem? Please describe.**

Starrocks storage of full data results in high costs. If cold data can be stored in OSS or HDFS and can provide the ability to query cold data, the cost will be much lower after cooling down.

**Describe the solution you'd like**

I am still looking forward to Starrocks providing cooling capacity. If Starrocks has plans to implement it, please let me know the specific implementation version and date.

**Describe alternatives you've considered**

At present, we are also considering how to cool the data. We want to use Data lake and other products, but this will introduce more components.

**Additional context**

Starrocks storage of full data results in high costs. If cold data can be stored in OSS or HDFS and can provide the ability to query cold data, the cost will be much lower after cooling down. At present, we are also considering how to cool the data. We want to use Data lake and other products, but this will introduce more components. I am still looking forward to Starrocks providing cooling capacity. If Starrocks has plans to implement it, please let me know the specific implementation version and date. thanks

**Comment by imay** [comment]
You can try with starrocks shared-data mode, which store all data in remote storage. And recently used data will be cached in the local disk cache.

**Comment by imay** [comment]
you can refer to this document to get more information about it.
https://docs.starrocks.io/en-us/latest/deployment/deploy_shared_data#load-data-into-a-shared-data-starrocks-cluster
