### ISSUE TITLE
对中文首字母排序的支持？？

### ISSUE THREAD

**Issue by lianglujiang** [StarRocks/starrocks#25067]
## General Question

对中文首字母排序的支持？？

**Comment by lianglujiang** [comment]
![image](https://github.com/StarRocks/starrocks/assets/17944316/52d6c5f9-0de8-4112-8f19-165807b95921)

**Comment by SYaoJun** [comment]
> ![image](https://user-images.githubusercontent.com/17944316/245085119-52d6c5f9-0de8-4112-8f19-165807b95921.png) 排序结果不符合预期（大“D”开头的没有排在再“Z”前面）
你可以考虑换成这个试试，COLLATE "zh_CN"

**Comment by lianglujiang** [comment]
> > ![image](https://user-images.githubusercontent.com/17944316/245085119-52d6c5f9-0de8-4112-8f19-165807b95921.png) 排序结果不符合预期（大“D”开头的没有排在再“Z”前面）
> 
> 你可以考虑换成这个试试，COLLATE "zh_CN"

这个字符集也试过了，和上面效果一样，看到官方文档说不支持GB,不知道什么时候出才能支持
