### ISSUE TITLE
[generate column] stream load failed when table with generate column

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#25208]
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `t1` (
    `k1` date,
    `k2` datetime,
    `k3` char(20),
    `k4` varchar(20),
    `k5` boolean,
    `k6` tinyint,
    `k7` smallint,
    `k8` int,
    `k9` bigint,
    `k10` largeint,
    `k11` float,
    `k12` double,
    `k13` decimal(27,9),
    `col_char` char as char(77)
    )
    DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
    COMMENT "OLAP"
    PARTITION BY RANGE(`k1`)
    (
    PARTITION `p202006` VALUES LESS THAN ("2020-07-01"),
    PARTITION `p202007` VALUES LESS THAN ("2020-08-01"),
    PARTITION `p202008` VALUES LESS THAN ("2020-09-01")
    )
    DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3
    PROPERTIES (
    "replication_num" = "3",
    "storage_format" = "v2"
    );
```
stream load:
`curl --location-trusted -u root: -T common/data/basic_types_data -XPUT  http://xxx.xxx.xxx.xxx:xxxx/api/test_db/t1/_stream_load`
### Expected behavior (Required)
`load success`
### Real behavior (Required)
`Error: Value count does not match column count. Expect 14, but got 13`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`main-ccaa9d5`

**Comment by srlch** [comment]
https://github.com/StarRocks/starrocks/pull/25236
