### ISSUE TITLE
Broker Load support speed limit

### ISSUE THREAD

**Issue by imgaoyue** [StarRocks/starrocks#25242]
V2.5.6
When performing the synchronization of Broker Load data, it currently consumes a large amount of disk and network IO resources, which may affect query performance. It is necessary to configure resource limits for it.

**Comment by jaogoy** [comment]
@imgaoyue What resource limit do you want? Parallel thread? data throughput? IOPS ?
Parallel thread I think is supported now only.

**Comment by imgaoyue** [comment]
Yes, I would like to reduce the impact on queries when synchronizing data, so I need to limit things such as memory or IOPS.

2023年6月19日 20:47，Li Jiao ***@***.***> 写道：



@imgaoyue<https://github.com/imgaoyue> What resource limit do you want? Parallel thread? data throughput? IOPS ?
Parallel thread I think is supported now only.
