### ISSUE TITLE
Wrong result return while date type of column is `datetime`.

### ISSUE THREAD

**Issue by yongbingwang** [StarRocks/starrocks#2527]
insert and delete error.
1. Precision problem of `datetime` when insert into table values.
2. Delete error('ERROR 1064 (HY000): Invalid column value[null] for column k2')
### Steps to reproduce the behavior (Required)
```
mysql> CREATE TABLE test_string2 (`k1` string not null,k2 datetime) ENGINE=OLAP duplicate key(k1) DISTRIBUTED BY HASH(`k1`) BUCKETS 3 PROPERTIES ("replication_num" = "1");
Query OK, 0 rows affected (0.01 sec)

mysql> insert into test_string2 values('2021-12-29 16:58:56.032000','2021-12-29 16:58:56.032000');
Query OK, 1 row affected (0.03 sec)
{'label':'insert_5e9563d2-689f-11ec-8fab-00163e10c9d6', 'status':'VISIBLE', 'txnId':'33055'}

mysql> select * from test_string2;
+----------------------------+----------------------------+
| k1                         | k2                         |
+----------------------------+----------------------------+
| 2021-12-29 16:58:56.032000 | 2021-12-29 16:58:56.032000 |
+----------------------------+----------------------------+
1 row in set (0.01 sec)

mysql> delete from test_string2 where k2='2021-12-29 16:58:56.032000';
ERROR 1064 (HY000): Invalid column value[null] for column k2
mysql> delete from test_string2 where k1='2021-12-29 16:58:56.032000';
Query OK, 0 rows affected (0.02 sec)
{'label':'delete_a088fb14-0748-44ce-b354-18e3b66fc20d', 'status':'VISIBLE', 'txnId':'33056'}

mysql> select * from test_string2;
Empty set (0.00 sec)
```

-mysql
```
mysql>  CREATE TABLE test_string2 (`k1` datetime not null,k2 datetime);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into test_string2 values('2021-12-29 16:58:56.032000','2021-12-29 16:58:56.032000');
Query OK, 1 row affected (0.00 sec)

mysql> select * from test_string2;
+---------------------+---------------------+
| k1                  | k2                  |
+---------------------+---------------------+
| 2021-12-29 16:58:56 | 2021-12-29 16:58:56 |
+---------------------+---------------------+
1 row in set (0.00 sec)
```

### Expected behavior (Required)
```
mysql> select * from test_string2;
+---------------------+---------------------+
| k1                  | k2                  |
+---------------------+---------------------+
| 2021-12-29 16:58:56 | 2021-12-29 16:58:56 |
+---------------------+---------------------+
1 row in set (0.00 sec)
```
### Real behavior (Required)
```
mysql> select * from test_string2;
+----------------------------+----------------------------+
| k1                         | k2                         |
+----------------------------+----------------------------+
| 2021-12-29 16:58:56.032000 | 2021-12-29 16:58:56.032000 |
+----------------------------+----------------------------+
1 row in set (0.01 sec)
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 2.1

**Comment by Seaven** [comment]
Starrocks wasn't support millisecond now

**Comment by Seaven** [comment]
Starrocks wasn't support millisecond now

**Comment by kangkaisen** [comment]
> Starrocks wasn't support millisecond now

if we don't support millisecond, the output should be 2021-12-29 16:58:56, not 2021-12-29 16:58:56.032000

**Comment by yongbingwang** [comment]
delete failed.
```
mysql> CREATE TABLE test_string2 (`k1` string not null,k2 datetime) ENGINE=OLAP duplicate key(k1) DISTRIBUTED BY HASH(`k1`) BUCKETS 3 PROPERTIES ("replication_num" = "1");
Query OK, 0 rows affected (0.02 sec)

mysql> insert into test_string2 values('2021-12-29 16:58:56.032000','2021-12-29 16:58:56.032000');
Query OK, 1 row affected (0.07 sec)
{'label':'insert_d92d1efb-ee5f-11ed-835d-00163e0e2cf9', 'status':'VISIBLE', 'txnId':'2121444'}

mysql> Query OK, 1 row affected (0.03 sec)^C
mysql> select * from test_string2;
+----------------------------+---------------------+
| k1                         | k2                  |
+----------------------------+---------------------+
| 2021-12-29 16:58:56.032000 | 2021-12-29 16:58:56 |
+----------------------------+---------------------+
1 row in set (0.00 sec)

mysql> delete from test_string2 where k2='2021-12-29 16:58:56.032000';
ERROR 1064 (HY000): failed to execute delete. transaction id 2121446, timeout(ms) 30000, unfinished replicas: 10004=22030992, 10075=22030990, 10076=22030994
```

**Comment by sevev** [comment]
> delete failed.
> 
> ```
> mysql> CREATE TABLE test_string2 (`k1` string not null,k2 datetime) ENGINE=OLAP duplicate key(k1) DISTRIBUTED BY HASH(`k1`) BUCKETS 3 PROPERTIES ("replication_num" = "1");
> Query OK, 0 rows affected (0.02 sec)
> 
> mysql> insert into test_string2 values('2021-12-29 16:58:56.032000','2021-12-29 16:58:56.032000');
> Query OK, 1 row affected (0.07 sec)
> {'label':'insert_d92d1efb-ee5f-11ed-835d-00163e0e2cf9', 'status':'VISIBLE', 'txnId':'2121444'}
> 
> mysql> Query OK, 1 row affected (0.03 sec)^C
> mysql> select * from test_string2;
> +----------------------------+---------------------+
> | k1                         | k2                  |
> +----------------------------+---------------------+
> | 2021-12-29 16:58:56.032000 | 2021-12-29 16:58:56 |
> +----------------------------+---------------------+
> 1 row in set (0.00 sec)
> 
> mysql> delete from test_string2 where k2='2021-12-29 16:58:56.032000';
> ERROR 1064 (HY000): failed to execute delete. transaction id 2121446, timeout(ms) 30000, unfinished replicas: 10004=22030992, 10075=22030990, 10076=22030994
> ```
> 
> ```
> mysql> select current_version();
> +----------------------+
> | current_version()    |
> +----------------------+
> | MAIN-RELEASE 68e0d56 |
> +----------------------+
> 1 row in set (0.00 sec)
> ```

The root cause is sr don't support millisecond and the task failed in BE. And FE will retry the task every 10 seconds and the timeout for deleted tasks is 30 seconds. So the tasks failed in 30 seconds.
