### ISSUE TITLE
wrong result of the UNIX_TIMESTAMP function

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#2530]
### Steps to reproduce the behavior (Required)
select UNIX_TIMESTAMP("2015-07-28 19:41:12", "22");

### Expected behavior (Required)
error reported
### Real behavior (Required)
A random number
`mysql> select UNIX_TIMESTAMP("2015-07-28 19:41:12", "22");
+---------------------------------------------+
| unix_timestamp('2015-07-28 19:41:12', '22') |
+---------------------------------------------+
|                                  -350326512 |
+---------------------------------------------+
1 row in set (0.00 sec)

mysql> select UNIX_TIMESTAMP("2015-07-28 19:41:12", "22");
+---------------------------------------------+
| unix_timestamp('2015-07-28 19:41:12', '22') |
+---------------------------------------------+
|                                  1014299288 |
+---------------------------------------------+`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
25f568d

**Comment by Seaven** [comment]
@stdpain PTAL

**Comment by stdpain** [comment]
a wrong plan
unix_timestamp should return null but plan has a no-null column
