### ISSUE TITLE
不能对分区表, 配置冷热数据的存储类型 SSD / HDD

### ISSUE THREAD

**Issue by imgaoyue** [StarRocks/starrocks#2535]
目前表只能配置SSD HDD单一属性. 不能针对一个表的冷热分区 或 最近分区分别配置SSD or HDD存储
 "storage_cooldown_time" = "2015-06-04 00:00:00"
这个配置只能配置具体的时间   不能动态的获取最近的分区数
比如我有一张 20210101 - 20211231 的分区表   20211201之前的分区希望存储到HDD  最近一个月或几天的分区数据放到SDD 按照目前的功能看似乎是不允许的  希望增加针对自建分区的存储类型配置

**Comment by Johnsonginati** [comment]
Could you describe it in English? Excuse
