### ISSUE TITLE
 When a column appears in the DISTRIBUTED BY HASH clause in SQL, if both count(distinct col) and count(col) are used in the query, the data is incorrect.

### ISSUE THREAD

**Issue by jameswangchen** [StarRocks/starrocks#25380]
### Steps to reproduce the behavior (Required)
use research;
drop table test_count_distinct2 force;
CREATE TABLE test_count_distinct2 (
`dt`      date ,
`a`       VARCHAR(256), 
`mid`     VARCHAR(256),
`user_id` VARCHAR(256), 
`b`       int, 
`c`       int,
`d`       int
) ENGINE=OLAP
DUPLICATE KEY(dt,a,mid,user_id)
COMMENT "OLAP"
PARTITION BY RANGE(dt)
()
DISTRIBUTED BY HASH(mid) BUCKETS 3
PROPERTIES (
"replication_num" = "2",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-30",
"dynamic_partition.end" = "1",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);

use research;
INSERT INTO test_count_distinct2 VALUES('2023-06-15','aaa','xxa', 'uua', 1, 1, 1);
INSERT INTO test_count_distinct2 VALUES('2023-06-15','aab','xxb', 'uub', 1, 1, 1);
INSERT INTO test_count_distinct2 VALUES('2023-06-15','aac','xxc', 'uuc', 1, 1, 1);
INSERT INTO test_count_distinct2 VALUES('2023-06-15','aad','xxd', 'uud', 1, 1, 1);
INSERT INTO test_count_distinct2 VALUES('2023-06-15','aae','xxe', 'uue', 1, 1, 1);
INSERT INTO test_count_distinct2 VALUES('2023-06-15','aaf','xxf', 'uuf', 1, 1, 1);
INSERT INTO test_count_distinct2 VALUES('2023-06-15','aag','xxa', 'uua', 1, 1, 1);
INSERT INTO test_count_distinct2 VALUES('2023-06-15','aah','xxb', 'uub', 1, 1, 1);
INSERT INTO test_count_distinct2 VALUES('2023-06-15','aai','xxc', 'uuc', 1, 1, 1);
INSERT INTO test_count_distinct2 VALUES('2023-06-15','aag','xxd', 'uud', 1, 1, 1);
INSERT INTO test_count_distinct2 VALUES('2023-06-15','aak','xxe', 'uue', 1, 1, 1);
INSERT INTO test_count_distinct2 VALUES('2023-06-15','aaa','xxf', 'uuf', 1, 1, 1);
INSERT INTO test_count_distinct2 VALUES('2023-06-15','aab','xxa', 'uua', 1, 1, 1);
INSERT INTO test_count_distinct2 VALUES('2023-06-15','aac','xxb', 'uub', 1, 1, 1);
INSERT INTO test_count_distinct2 VALUES('2023-06-15','aad','xxc', 'uuc', 1, 1, 1);
INSERT INTO test_count_distinct2 VALUES('2023-06-15','aae','xxd', 'uud', 1, 1, 1);
INSERT INTO test_count_distinct2 VALUES('2023-06-15','aaf','xxe', 'uue', 1, 1, 1);
INSERT INTO test_count_distinct2 VALUES('2023-06-15','aag','xxf', 'uuf', 1, 1, 1);
INSERT INTO test_count_distinct2 VALUES('2023-06-15','aaa','xxa', 'uua', 1, 1, 1);

example 1：
select count(mid) from  test_count_distinct2 group by dt;
select count(distinct mid) from  test_count_distinct2 group by dt;
select dt, count(distinct mid), count(mid) from test_count_distinct2 group by dt;
![image](https://github.com/StarRocks/starrocks/assets/21259595/f82208f6-4bd2-4e87-9161-de90ae40739f)

example 2：
select dt, count(distinct mid), count(user_id) from test_count_distinct2 group by dt;
select dt, count(distinct mid) from test_count_distinct2 group by dt;
select dt, count(user_id) from test_count_distinct2 group by dt;
![image](https://github.com/StarRocks/starrocks/assets/21259595/dffef5cb-b0fd-4682-b4b7-126dad42c4c7)

### Expected behavior (Required)
The data in Example 1 and Example 2 is the same.

### Real behavior (Required)
The data in Example 1 and Example 2 is not the same.

### StarRocks version (Required)
2.5.6

**Comment by packy92** [comment]
https://github.com/StarRocks/starrocks/pull/24222 this pr had fixed.

**Comment by jameswangchen** [comment]
Thank you @packy92

**Comment by jameswangchen** [comment]
Thank you @packy92
