### ISSUE TITLE
stream load array type, result is null

### ISSUE THREAD

**Issue by huoyue-git** [StarRocks/starrocks#25562]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
CREATE TABLE `duplicate_table_200_abnormal_test` (
  `k1` date NULL COMMENT "",
  `k2` datetime NULL COMMENT "",
  `k3` char(20) NULL COMMENT "",
  `k4` varchar(20) NULL COMMENT "",
  `k5` boolean NULL COMMENT "",
  `v1` tinyint(4) NULL COMMENT "",
  `v2` smallint(6) NULL COMMENT "",
  `v3` int(11) NULL COMMENT "",
  `v4` bigint(20) NULL COMMENT "",
  `v5` largeint(40) NULL COMMENT "",
  `v6` float NULL COMMENT "",
  `v7` double NULL COMMENT "",
  `v8` char(20) NULL COMMENT "",
  `v9` decimal64(10, 5) NULL COMMENT "",
  `v10` array<varchar(200)> NULL COMMENT "",
  `v11` array<int> NULL COMMENT "",
  `v12` array<string> NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`, `k2`, `k3`)
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
);

curl --location-trusted -u root: -T /home/disk4/huoyue/abnormal_200_complex_column_10_temp -XPUT -H "label:stream_load_1687143610712"  http://xxx.xx.xx.xxx:xxxx/api/test_hy/duplicate_table_200_abnormal_test/_stream_load
```
data
1985-10-17	1983-09-04 18:59:08	GB50OVYN79862340562	9510947053	0	83	-4483	534314220	2829377979345344422	94859552725664939189733244611501852375	9817.34906	76568097.6	Discover partner fo	-201.470	['project']	[1,2]	['aaa']
2007-03-02	2011-05-26 08:44:08	GB71RESV04787319030	672.703.5194	0	112	-17774	1306055240	-6607337543924666978	155734659646771713948093023332130290857	8384.66	1063594.1	Project camera gun -55775.31499	['detail', 'least', 'today']	[1,2]	['bbb']

### Expected behavior (Required)
v10 and v12 result is correct
### Real behavior (Required)
v10 and v12 result is null
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+--------------------+
| current_version()  |
+--------------------+
| branch-3.1-9547469 |
+--------------------+
1 row in set (0.00 sec)

**Comment by zaorangyang** [comment]
You should wrap the string field in double quotation marks
