### ISSUE TITLE
 time used with time_slice can't before 0001-01-01 00:00:00

### ISSUE THREAD

**Issue by mch312** [StarRocks/starrocks#25573]
mysql> INSERT INTO antai_data(tagindex, timestamp, ms, quality, value)  VALUES (1429992, '2021-02-15 00:00:00', 354, 0, 1.0);
ERROR 1064 (HY000): time used with time_slice can't before 0001-01-01 00:00:00
mysql> INSERT INTO antai_data(tagindex, timestamp, ms, quality, value)  VALUES (1429992, '2021-02-15 00:00:00', 354, 0, 1.0);
ERROR 1064 (HY000): time used with time_slice can't before 0001-01-01 00:00:00
mysql> INSERT INTO antai_data(tagindex, timestamp, ms, quality, value)  VALUES (1429992, '2021-02-15 00:00:00', 354, 0, 1.0);
Query OK, 1 row affected (0.05 sec)
{'label':'insert_16d6c596-0e84-11ee-b250-4efc62accf1b', 'status':'VISIBLE', 'txnId':'1194071'}

mysql> INSERT INTO antai_data(tagindex, timestamp, ms, quality, value)  VALUES (1429992, '2021-02-15 00:00:00', 354, 0, 1.0);
ERROR 1064 (HY000): time used with time_slice can't before 0001-01-01 00:00:00
mysql> INSERT INTO antai_data(tagindex, timestamp, ms, quality, value)  VALUES (1429992, '2021-02-15 00:00:00', 354, 0, 1.0);
ERROR 1064 (HY000): time used with time_slice can't before 0001-01-01 00:00:00
mysql> INSERT INTO antai_data(tagindex, timestamp, ms, quality, value)  VALUES (1429992, '2021-02-15 00:00:00', 354, 0, 1.0);
Query OK, 1 row affected (0.05 sec)
{'label':'insert_9ac1699f-0e85-11ee-b250-4efc62accf1b', 'status':'VISIBLE', 'txnId':'1194074'}
插入相同的数据，2次失败，之后1次成功，如此循环。
发生在重启fe和be之后。
出现异常时，be.WARNING中有类似如下告警：
230893:W0619 17:21:52.333676 20512 tablet_sink.cpp:1632] close channel failed. channel_name=NodeChannel[16008], load_info=load_id=b9f0fdf7-0e82-11ee-b250-4efc62accf1b, txn_id: 1194061, parallel=1, compress_type=2, error_msg=Cancelled by pipeline engine
231151:W0619 17:21:52.338704 20510 tablet_sink.cpp:1632] close channel failed. channel_name=NodeChannel[16008], load_info=load_id=b9f0fdf7-0e82-11ee-b250-4efc62accf1b, txn_id: 1194061, parallel=1, compress_type=2, error_msg=Cancelled by pipeline engine
231152:W0619 17:21:52.343788 20510 tablet_sink.cpp:1795] close channel failed. channel_name=NodeChannel[16008], load_info=load_id=b9f0fdf7-0e82-11ee-b250-4efc62accf1b, txn_id: 1194061, parallel=1, compress_type=2, error_msg=Cancelled by pipeline engine
请问是什么原因，如何解决？

**Comment by mch312** [comment]
CREATE TABLE `antai_data` (
  `tagindex` int(11) NOT NULL COMMENT "",
  `timestamp` datetime NOT NULL COMMENT "",
  `ms` smallint(6) NOT NULL COMMENT "",
  `quality` smallint(6) NOT NULL COMMENT "",
  `value` double NOT NULL COMMENT ""
) ENGINE=OLAP
PRIMARY KEY(`tagindex`, `timestamp`, `ms`)
COMMENT "OLAP"
PARTITION BY time_slice(timestamp, 10, 'day', 'floor')
DISTRIBUTED BY HASH(`tagindex`) BUCKETS 4
ORDER BY(`tagindex`, `timestamp`, `ms`)
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);

**Comment by Astralidea** [comment]
你是哪个版本？

**Comment by Astralidea** [comment]
https://github.com/StarRocks/starrocks/pull/25177
你好，这个PR修复了这个问题，目前3.0.3没有发布。
所以你可以选择基于3.0.0版本合入这个代码编译出来一个版本来解决这个问题。
当然另一个办法就是你把分区列设置成第一列，来暂时规避这个问题。
然后等待3.0.3版本发布再升级也可以。
