### ISSUE TITLE
In the case of large data, the performance of distinct operator is very low, can it be optimized?

### ISSUE THREAD

**Issue by jameswangchen** [StarRocks/starrocks#25641]
## Enhancement
In the default configuration, when new_planner_agg_stage = 0, queries fail due to timeout
![image](https://github.com/StarRocks/starrocks/assets/21259595/9d6f6c46-798b-4846-ae0f-cbbc559fe4f9)

explain:
+------------------------------------------------------------------------------------------------------------------------------------------------+
| Explain String                                                                                                                                 |
+------------------------------------------------------------------------------------------------------------------------------------------------+
| PLAN FRAGMENT 0(F02)                                                                                                                           |
|   Output Exprs:1: dt | 69: count                                                                                                               |
|   Input Partition: UNPARTITIONED                                                                                                               |
|   RESULT SINK                                                                                                                                  |
|                                                                                                                                                |
|   4:EXCHANGE                                                                                                                                   |
|      cardinality: 1                                                                                                                            |
|                                                                                                                                                |
| PLAN FRAGMENT 1(F01)                                                                                                                           |
|                                                                                                                                                |
|   Input Partition: HASH_PARTITIONED: 1: dt                                                                                                     |
|   OutPut Partition: UNPARTITIONED                                                                                                              |
|   OutPut Exchange Id: 04                                                                                                                       |
|                                                                                                                                                |
|   3:AGGREGATE (merge finalize)                                                                                                                 |
|   |  aggregate: multi_distinct_count[([69: count, VARBINARY, false]); args: CHAR; result: BIGINT; args nullable: true; result nullable: false] |
|   |  group by: [1: dt, DATE, true]                                                                                                             |
|   |  cardinality: 1                                                                                                                            |
|   |  column statistics:                                                                                                                        |
|   |  * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                                                   |
|   |  * count-->[0.0, 8.085873079E9, 0.0, 8.0, 1.0] ESTIMATE                                                                                    |
|   |                                                                                                                                            |
|   2:EXCHANGE                                                                                                                                   |
|      distribution type: SHUFFLE                                                                                                                |
|      partition exprs: [1: dt, DATE, true]                                                                                                      |
|      cardinality: 1                                                                                                                            |
|                                                                                                                                                |
| PLAN FRAGMENT 2(F00)                                                                                                                           |
|                                                                                                                                                |
|   Input Partition: RANDOM                                                                                                                      |
|   OutPut Partition: HASH_PARTITIONED: 1: dt                                                                                                    |
|   OutPut Exchange Id: 02                                                                                                                       |
|                                                                                                                                                |
|   1:AGGREGATE (update serialize)                                                                                                               |
|   |  STREAMING                                                                                                                                 |
|   |  aggregate: multi_distinct_count[([4: i, VARCHAR, true]); args: CHAR; result: VARBINARY; args nullable: true; result nullable: false]      |
|   |  group by: [1: dt, DATE, true]                                                                                                             |
|   |  cardinality: 1                                                                                                                            |
|   |  column statistics:                                                                                                                        |
|   |  * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                                                   |
|   |  * count-->[0.0, 5647.0, 0.0, 0.27444, 1.0] ESTIMATE                                                                                       |
|   |                                                                                                                                            |
|   0:OlapScanNode                                                                                                                               |
|      table: test01, rollup: test01                                                                                                             |
|      preAggregation: on                                                                                                                        |
|      partitionsRatio=5/8, tabletsRatio=5120/5120                                                                                               |
|      tabletList=1024918,1024921,1024924,1024927,1024930,1024933,1024936,1024939,1024942,1024945 ...                                            |
|      actualRows=8085873079, avgRowSize=4.27444                                                                                                 |
|      cardinality: 8085873079                                                                                                                   |
|      column statistics:                                                                                                                        |
|      * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                                                   |
|      * i-->[-Infinity, Infinity, 0.0, 0.27444, 5647.0] ESTIMATE                                                                                |

When executing 'set new_planner_agg_stage = 4;', the query can run successfully, but the performance is still slow.
![image](https://github.com/StarRocks/starrocks/assets/21259595/1c519108-cf6e-428c-8acb-93ab01fcd22e)

explain:
+----------------------------------------------------------------------------------------------------------------------------+
| Explain String                                                                                                             |
+----------------------------------------------------------------------------------------------------------------------------+
| PLAN FRAGMENT 0(F02)                                                                                                       |
|   Output Exprs:1: dt | 69: count                                                                                           |
|   Input Partition: UNPARTITIONED                                                                                           |
|   RESULT SINK                                                                                                              |
|                                                                                                                            |
|   5:EXCHANGE                                                                                                               |
|      cardinality: 1                                                                                                        |
|                                                                                                                            |
| PLAN FRAGMENT 1(F01)                                                                                                       |
|                                                                                                                            |
|   Input Partition: HASH_PARTITIONED: 1: dt                                                                                 |
|   OutPut Partition: UNPARTITIONED                                                                                          |
|   OutPut Exchange Id: 05                                                                                                   |
|                                                                                                                            |
|   4:AGGREGATE (update finalize)                                                                                            |
|   |  aggregate: count[([4: i, VARCHAR, true]); args: VARCHAR; result: BIGINT; args nullable: true; result nullable: false] |
|   |  group by: [1: dt, DATE, true]                                                                                         |
|   |  cardinality: 1                                                                                                        |
|   |  column statistics:                                                                                                    |
|   |  * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                               |
|   |  * count-->[0.0, 8.085873079E9, 0.0, 8.0, 1.0] ESTIMATE                                                                |
|   |                                                                                                                        |
|   3:AGGREGATE (merge serialize)                                                                                            |
|   |  group by: [1: dt, DATE, true], [4: i, VARCHAR, true]                                                                  |
|   |  cardinality: 3176                                                                                                     |
|   |  column statistics:                                                                                                    |
|   |  * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                               |
|   |  * i-->[-Infinity, Infinity, 0.0, 0.27444, 5647.0] ESTIMATE                                                            |
|   |                                                                                                                        |
|   2:EXCHANGE                                                                                                               |
|      distribution type: SHUFFLE                                                                                            |
|      partition exprs: [1: dt, DATE, true]                                                                                  |
|      cardinality: 3176                                                                                                     |
|                                                                                                                            |
| PLAN FRAGMENT 2(F00)                                                                                                       |
|                                                                                                                            |
|   Input Partition: RANDOM                                                                                                  |
|   OutPut Partition: HASH_PARTITIONED: 1: dt                                                                                |
|   OutPut Exchange Id: 02                                                                                                   |
|                                                                                                                            |
|   1:AGGREGATE (update serialize)                                                                                           |
|   |  STREAMING                                                                                                             |
|   |  group by: [1: dt, DATE, true], [4: i, VARCHAR, true]                                                                  |
|   |  cardinality: 3176                                                                                                     |
|   |  column statistics:                                                                                                    |
|   |  * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                               |
|   |  * i-->[-Infinity, Infinity, 0.0, 0.27444, 5647.0] ESTIMATE                                                            |
|   |                                                                                                                        |
|   0:OlapScanNode                                                                                                           |
|      table: test01, rollup: test01                                                                                         |
|      preAggregation: on                                                                                                    |
|      partitionsRatio=5/8, tabletsRatio=5120/5120                                                                           |
|      tabletList=1024918,1024921,1024924,1024927,1024930,1024933,1024936,1024939,1024942,1024945 ...                        |
|      actualRows=8085873079, avgRowSize=4.27444                                                                             |
|      cardinality: 8085873079                                                                                               |
|      column statistics:                                                                                                    |
|      * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                               |
|      * i-->[-Infinity, Infinity, 0.0, 0.27444, 5647.0] ESTIMATE                                                            |

After rewriting the DISTINCT, the performance has improved. Here is the code:
![image](https://github.com/StarRocks/starrocks/assets/21259595/115ff5a5-eeed-42ff-b9d4-e2f25318e65b)

explain:
+--------------------------------------------------------------------------------------------------------------------------+
| Explain String                                                                                                           |
+--------------------------------------------------------------------------------------------------------------------------+
| PLAN FRAGMENT 0(F03)                                                                                                     |
|   Output Exprs:1: dt | 69: count                                                                                         |
|   Input Partition: UNPARTITIONED                                                                                         |
|   RESULT SINK                                                                                                            |
|                                                                                                                          |
|   8:EXCHANGE                                                                                                             |
|      cardinality: 1                                                                                                      |
|                                                                                                                          |
| PLAN FRAGMENT 1(F02)                                                                                                     |
|                                                                                                                          |
|   Input Partition: HASH_PARTITIONED: 1: dt                                                                               |
|   OutPut Partition: UNPARTITIONED                                                                                        |
|   OutPut Exchange Id: 08                                                                                                 |
|                                                                                                                          |
|   7:AGGREGATE (merge finalize)                                                                                           |
|   |  aggregate: count[([69: count, BIGINT, false]); args: ; result: BIGINT; args nullable: true; result nullable: false] |
|   |  group by: [1: dt, DATE, true]                                                                                       |
|   |  cardinality: 1                                                                                                      |
|   |  column statistics:                                                                                                  |
|   |  * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                             |
|   |  * count-->[0.0, 3176.4375, 0.0, 8.0, 1.0] ESTIMATE                                                                  |
|   |                                                                                                                      |
|   6:EXCHANGE                                                                                                             |
|      distribution type: SHUFFLE                                                                                          |
|      partition exprs: [1: dt, DATE, true]                                                                                |
|      cardinality: 1                                                                                                      |
|                                                                                                                          |
| PLAN FRAGMENT 2(F01)                                                                                                     |
|                                                                                                                          |
|   Input Partition: HASH_PARTITIONED: 1: dt, 4: i                                                                         |
|   OutPut Partition: HASH_PARTITIONED: 1: dt                                                                              |
|   OutPut Exchange Id: 06                                                                                                 |
|                                                                                                                          |
|   5:AGGREGATE (update serialize)                                                                                         |
|   |  STREAMING                                                                                                           |
|   |  aggregate: count[(*); args: ; result: BIGINT; args nullable: false; result nullable: false]                         |
|   |  group by: [1: dt, DATE, true]                                                                                       |
|   |  cardinality: 1                                                                                                      |
|   |  column statistics:                                                                                                  |
|   |  * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                             |
|   |  * count-->[0.0, 3176.4375, 0.0, 8.0, 1.0] ESTIMATE                                                                  |
|   |                                                                                                                      |
|   4:Project                                                                                                              |
|   |  output columns:                                                                                                     |
|   |  1 <-> [1: dt, DATE, true]                                                                                           |
|   |  cardinality: 3176                                                                                                   |
|   |  column statistics:                                                                                                  |
|   |  * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                             |
|   |                                                                                                                      |
|   3:AGGREGATE (merge finalize)                                                                                           |
|   |  group by: [1: dt, DATE, true], [4: i, VARCHAR, true]                                                                |
|   |  cardinality: 3176                                                                                                   |
|   |  column statistics:                                                                                                  |
|   |  * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                             |
|   |  * i-->[-Infinity, Infinity, 0.0, 0.27444, 5647.0] ESTIMATE                                                          |
|   |                                                                                                                      |
|   2:EXCHANGE                                                                                                             |
|      distribution type: SHUFFLE                                                                                          |
|      partition exprs: [1: dt, DATE, true], [4: i, VARCHAR, true]                                                         |
|      cardinality: 3176                                                                                                   |
|                                                                                                                          |
| PLAN FRAGMENT 3(F00)                                                                                                     |
|                                                                                                                          |
|   Input Partition: RANDOM                                                                                                |
|   OutPut Partition: HASH_PARTITIONED: 1: dt, 4: i                                                                        |
|   OutPut Exchange Id: 02                                                                                                 |
|                                                                                                                          |
|   1:AGGREGATE (update serialize)                                                                                         |
|   |  STREAMING                                                                                                           |
|   |  group by: [1: dt, DATE, true], [4: i, VARCHAR, true]                                                                |
|   |  cardinality: 3176                                                                                                   |
|   |  column statistics:                                                                                                  |
|   |  * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                             |
|   |  * i-->[-Infinity, Infinity, 0.0, 0.27444, 5647.0] ESTIMATE                                                          |
|   |                                                                                                                      |
|   0:OlapScanNode                                                                                                         |
|      table: test01, rollup: test01                                                                                       |
|      preAggregation: on                                                                                                  |
|      partitionsRatio=5/8, tabletsRatio=5120/5120                                                                         |
|      tabletList=1024918,1024921,1024924,1024927,1024930,1024933,1024936,1024939,1024942,1024945 ...                      |
|      actualRows=8085873079, avgRowSize=4.27444                                                                           |
|      cardinality: 8085873079                                                                                             |
|      column statistics:                                                                                                  |
|      * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                             |
|      * i-->[-Infinity, Infinity, 0.0, 0.27444, 5647.0] ESTIMATE

**Comment by packy92** [comment]
can you provide your create table clause? I want to check the distribution key info.

**Comment by jameswangchen** [comment]
CREATE TABLE `test01` (
`dt`    date                       ,
`a`     varchar(1048575)            ,
`mid`   varchar(1048575)          ,
`i`     varchar(1048575)            ,
`b0`    varchar(1048575)            ,
`b1`    varchar(1048575)          ,
`b2`    varchar(1048575)           ,
`b3`    varchar(1048575)          ,
`b4`    varchar(1048575)            ,
`b5`    varchar(1048575)            ,
`b6`    varchar(1048575)            ,
`b7`    varchar(1048575)           ,
`b8`    varchar(1048575)           ,
`b9`    varchar(1048575)           ,
`c1`    varchar(1048575)           ,
`c2`    varchar(1048575)           ,
`c3`    varchar(1048575)          ,
`c4`    varchar(1048575)           ,
`c5`    varchar(1048575)           ,
`c6`    varchar(1048575)           ,
`c7`    varchar(1048575)            ,
`c8`    varchar(65533)       ,
`c9`    varchar(65533)           ,
`i7`    varchar(1048575)        ,
`i6`    varchar(1048575)        ,
`i9`    varchar(1048575)        ,
`i8`    varchar(1048575)        ,
`i10`   varchar(1048575)       ,
`i11`   varchar(1048575)       ,
`i12`   varchar(1048575)       ,
`i1`    varchar(1048575)        ,
`i3`    varchar(1048575)        ,
`i2`    varchar(1048575)        ,
`i5`    varchar(1048575)        ,
`i4`    varchar(1048575)        ,
`s1`    varchar(1048575)        ,
`s2`    varchar(1048575)        ,
`s3`    varchar(1048575)          ,
`s4`    varchar(1048575)           ,
`s5`    varchar(1048575)          ,
`s6`    varchar(1048575)          ,
`s7`    varchar(1048575)           ,
`s8`    varchar(1048575)          ,
`s9`    varchar(1048575)          ,
`r1`    varchar(1048575)        ,
`r2`    varchar(1048575)        ,
`r3`    varchar(1048575)        ,
`r4`    varchar(1048575)        ,
`r5`    varchar(1048575)          ,
`r6`    varchar(1048575)          ,
`r7`    varchar(1048575)          ,
`r8`    varchar(1048575)   ,
`r9`    varchar(1048575)       ,
`uuid`  varchar(1048575)         ,
`q1`    varchar(1048575) ,
`q2`    varchar(1048575)        ,
`q3`    varchar(1048575)       ,
`q4`    tinyint(4)       ,
`q5`    varchar(1048575)  ,
`q6`    tinyint(4)           ,
`q7`    varchar(1048575)     ,
`q8`    varchar(1048575)    ,
`q9`    varchar(1048575)      ,
`q10`   varchar(1048575)          ,
`q11`   varchar(1048575)       ,
`q12`   varchar(1048575)     ,
`q13`   varchar(1048575)  ,
`q14`   varchar(1048575)
) ENGINE=OLAP                     
DUPLICATE KEY(`dt`, `a`, `mid`, `i`)
COMMENT "OLAP"
PARTITION BY RANGE(`dt`)
(PARTITION p20230614 VALUES [("2023-06-14"), ("2023-06-15")),
PARTITION p20230615 VALUES [("2023-06-15"), ("2023-06-16")),
PARTITION p20230617 VALUES [("2023-06-17"), ("2023-06-18")),
PARTITION p20230618 VALUES [("2023-06-18"), ("2023-06-19")),
PARTITION p20230619 VALUES [("2023-06-19"), ("2023-06-20")),
PARTITION p20230620 VALUES [("2023-06-20"), ("2023-06-21")))
DISTRIBUTED BY HASH(`mid`) BUCKETS 1024
PROPERTIES (
"replication_num" = "2",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-30",
"dynamic_partition.end" = "1",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "1024",
"dynamic_partition.history_partition_num" = "0",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "false",
"compression" = "LZ4"
);
