### ISSUE TITLE
希望update语法更新支持多表关联更新(之前已提过一次，估计被研发同学们误解，现举例重提）

### ISSUE THREAD

**Issue by arthurcommon** [StarRocks/starrocks#25668]
这是之前的issue的地址：https://github.com/StarRocks/starrocks/issues/24607

本次需求同前，已在3.0做了测试，测试如附件图示，如果没有语法错误的话，应该是不支持我的需求。请研发同学们再次查看一下。
![693af1e232a0e9214bf28b3a2f768a6](https://github.com/StarRocks/starrocks/assets/115995632/b0c68489-3b3e-4f4b-afcd-6eb420aee772)

**Comment by imay** [comment]
please try 
```
update test_a set v1 = test_b.v1 from test_b where test_a.k1 = test_b.k1;
```

**Comment by arthurcommon** [comment]
It works. 
Thanks a lot!
