### ISSUE TITLE
[function]approx_top_k

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#25684]
during the compatibility work of trino's grammar, there is a function that starrocks doesn't have.

https://trino.io/docs/current/functions/aggregate.html?highlight=approx_most_frequent
https://docs.snowflake.com/en/sql-reference/functions/approx_top_k
https://docs.databricks.com/sql/language-manual/functions/approx_top_k.html

this is a common function that widely used in dbms.  so here is a proposal:

### description

Uses Space-Saving to return an approximation of the most frequent values in the input, along with their approximate frequencies.

The function uses the stream summary data structure proposed in the paper [Efficient Computation of Frequent and Top-k Elements in Data Streams](https://www.cse.ust.hk/~raywong/comp5331/References/EfficientComputationOfFrequentAndTop-kElementsInDataStreams.pdf) by A. Metwalley, D. Agrawl and A. Abbadi.

### syntax

```
APPROX_TOP_K( <expr> [ , <k> [ , <counters> ] ] )
```

### arguments
- expr: a countable column. it can be numeric, string or date/datetime 
- k: The number of values whose counts you want approximated. For example, if you want to see the top 10 most common values, then set k to 10. If k is omitted, the default is 1. The maximum value is 100000 (100,000), and is automatically reduced if items cannot fit in the output.
- counters: This is the maximum number of distinct values that can be tracked at a time during the estimation process. The maximum number of counters is 100,000, and default to 10,000.

### output
map<[same as value], bigint>
I consider to use map because:
1. we can use lambda functions and other map functions to do some further calculation
2. compare to nested array, it is more easy to use map_keys and map_values to extract values.

### example

```
SELECT approx_top_k(expr, 2) FROM VALUES ('a'), ('b'), ('c'), ('c'), ('c'), ('c'), ('d'), ('d') AS tab(expr);

 {c=4,d=2}

```

**Comment by liuyehcf** [comment]
begin working on this.
