### ISSUE TITLE
Support to create new tables from parquet files 

### ISSUE THREAD

**Issue by powerLambda** [StarRocks/starrocks#25720]
## Feature request

**Is your feature request related to a problem? Please describe.**

Parquet is a portable file format for heterogeneous data warehouse migration, which has table metadata embedded, is self-described, and high data compression ratio.  
SparkSQL and ClickHouse are already convenient for creating new tables from parquet files. 
For example in SparkSQL : 
```
    CREATE TABLE  table_identifier 
    [ ( col_name1 col_type1 [ COMMENT col_comment1 ], ... ) ]
    USING parquet LOCATION path 
```
https://spark.apache.org/docs/latest/sql-ref-syntax-ddl-create-table-datasource.html
in ClickHouse: 
```
CREATE TABLE imported_from_parquet
ENGINE = MergeTree
ORDER BY tuple() AS
SELECT *
FROM file('data.parquet', Parquet)
```
https://clickhouse.com/docs/en/integrations/data-formats/parquet#creating-new-tables-from-parquet-files

SparkRocks is expected to support this feature.

**Comment by imay** [comment]
https://docs.starrocks.io/en-us/latest/data_source/file_external_table
Can this feature meet your requirement?

Also, starrocks will release a table function feature in version 3.1

**Comment by powerLambda** [comment]
> https://docs.starrocks.io/en-us/latest/data_source/file_external_table Can this feature meet your requirement?
> 
> Also, starrocks will release a table function feature in version 3.1

Hi, I Read the docs above,  below SQL statement requires specifying the column name and column type, but in spark SQL and clickhouse, those are not required. Both column name and column type information are loaded from self-described parquet files, which are much more convenient. 
```
CREATE EXTERNAL TABLE <table_name>
(
    <col_name> <col_type> [NULL | NOT NULL] [COMMENT "<comment>"]
) 
ENGINE=file
COMMENT ["comment"]
PROPERTIES
(
    FileLayoutParams,
    StorageCredentialParams
)

```

**Comment by alberttwong** [comment]
I think you're looking for this. https://docs.starrocks.io/docs/3.2/sql-reference/sql-functions/table-functions/files/
