### ISSUE TITLE
Prepared Statement errors when using https://diesel.rs/

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#25798]
https://diesel.rs/ is a rust library to help you with SQL

**Comment by Jungle666** [comment]
does the problem solved? I'm working with rust,is there a rust starrocks client ?

I got error message when use sea-orm

{ code: Some("HY000"), number: 1064, message: "Set statement only support constant expr." }

**Comment by alberttwong** [comment]
Have you tried any mysql libraries that work with rust?    ORMs may or maybe not work.  Better if it's just straight SQL.

**Comment by Jungle666** [comment]
The [mysql_async](https://docs.rs/mysql_async/latest/mysql_async/) a rust libraries got the same error。

**Comment by Jungle666** [comment]
I tried aother [mysql](https://docs.rs/mysql/latest/mysql/) libraries ,that solve my prolems, thanks a lot.

**Comment by zhangruchubaba** [comment]
@Jungle666  Hi bro, which libraries did you use, i got the same error

**Comment by zhangruchubaba** [comment]
> > @Jungle666 Hi bro, which libraries did you use, i got the same error
> 
> do not use sync mysql libraries

Do you have any recommendations?

**Comment by Jungle666** [comment]
> > > @Jungle666 Hi bro, which libraries did you use, i got the same error
> > 
> > 
> > do not use sync mysql libraries
> 
> Do you have any recommendations?

https://docs.rs/mysql/latest/mysql/

mysql = "*"

**Comment by zhangruchubaba** [comment]
OK! Thank you , i`ll have a try
