### ISSUE TITLE
mac m2芯片安装了一整天都失败了

### ISSUE THREAD

**Issue by yangyongyongyong** [StarRocks/starrocks#25799]
无论使用物理机还是容器. 可以适配下mac arm芯片么. 学个东西心态炸了

**Comment by kevincai** [comment]
please describe your problem in details.

**Comment by kevincai** [comment]
build project: https://docs.starrocks.io/zh-cn/main/developers/build-starrocks/Build_in_docker
deploy in docker: https://docs.starrocks.io/zh-cn/latest/quick_start/deploy_with_docker
