### ISSUE TITLE
Two equivalent SQL results are not the same

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#2581]
### Steps to reproduce the behavior (Required)
1. `DROP DATABASE IF EXISTS w0;
CREATE DATABASE w0;
USE w0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 BOOLEAN NULL ,c_0_1 DECIMAL128(28, 4)  NOT NULL ,c_0_2 DECIMAL32(5, 5)  NULL ,c_0_3 VARCHAR(11) NOT NULL ,c_0_4 DECIMAL32(6, 0)  NOT NULL ) DUPLICATE KEY (c_0_0,c_0_1,c_0_2,c_0_3) DISTRIBUTED BY HASH (c_0_2,c_0_0,c_0_3,c_0_1) properties("replication_num"="1") ;
CREATE TABLE t1 (c_1_0 DECIMAL32(2, 0)  NOT NULL ,c_1_1 BOOLEAN NULL ,c_1_2 BOOLEAN NOT NULL ,c_1_3 DECIMAL64(10, 7)  NULL ,c_1_4 DATE NULL ,c_1_5 DECIMAL(13, 9)  NOT NULL ,c_1_6 DECIMAL128(17, 16)  NOT NULL ,c_1_7 DECIMAL128(27, 25)  NULL ,c_1_8 CHAR(11) NOT NULL ,c_1_9 DATE NOT NULL ,c_1_10 VARCHAR(1) NOT NULL ,c_1_11 BOOLEAN NOT NULL ,c_1_12 DATE NOT NULL ,c_1_13 DECIMAL64(13, 9)  NOT NULL ,c_1_14 DECIMAL128(20, 11)  NOT NULL ,c_1_15 TINYINT NULL ,c_1_16 VARCHAR(1) NULL ) UNIQUE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6,c_1_7,c_1_8,c_1_9,c_1_10,c_1_11,c_1_12,c_1_13) DISTRIBUTED BY HASH (c_1_7,c_1_13,c_1_12,c_1_9) properties("replication_num"="1") ;
CREATE TABLE IF NOT EXISTS t2 (c_2_0 DATE NOT NULL ) UNIQUE KEY (c_2_0) DISTRIBUTED BY HASH (c_2_0) properties("replication_num"="1") ;
INSERT INTO t1 VALUES (81, false, true, 0.0000178, "1970-01-01", 0.000002645, 0E-16, 9.3E-24, "s", "1970-01-01", "", true, "1970-01-01", 0.000006862, 0.00472826613, NULL, ""), (87, true, true, NULL, "1970-01-01", 0.000006542, 1E-16, 7.3E-24, "Z5", "1970-01-01", "", false, "1970-01-01", 0.000007716, 0.00668808012, 7, ""), (43, false, false, 0.0000766, "1970-01-01", 0.000004828, 1E-16, 7.4E-24, "", "1970-01-01", "", false, "1970-01-01", 0.000008989, 0.00462716305, 2, NULL), (51, true, false, 0.0000686, "1970-01-01", 0.000007828, 0E-16, 5.6E-24, "D", "1970-01-01", "", false, "1970-01-01", 0.000001249, 0.00804696294, 7, "");
INSERT INTO t0 VALUES (true, 11956602944523453405.2932, 0.00006, "", 778591), (false, 84392008270214446960.6214, NULL, "O8PZP", 385306);
INSERT INTO t2 VALUES ("1970-01-01"), ("1970-01-01");
INSERT INTO t0 VALUES (true, 72011997853163123296.1276, 0.00008, "", 350510), (false, 81969968960921946186.9073, 0.00003, "", 11844), (NULL, 46401959046257658769.7185, 0.00001, "2", 604860);
INSERT INTO t0 VALUES (false, 48922474018119643802.2116, 0.00003, "J", 969356);
INSERT INTO t0 VALUES (true, 72093838498642881527.3242, 0.00003, "", 982195), (false, 93230379588802847480.1356, 0.00007, "ke1dllLr", 347025);
INSERT INTO t0 VALUES (true, 61660335258878617999.1564, 0.00008, "dC", 389499), (false, 80080702524625380078.7599, 0.00002, "C", 652143), (true, 99298391558294341055.5435, NULL, "", 700644), (false, 42312535761799452416.3227, 0.00008, "DAE9kHhEh", 843751);
INSERT INTO t0 VALUES (true, 59625670519337248270.3758, 0.00005, "QhLhh", 546017), (false, 36586666287032088009.0141, 0.00006, "Z81", 865642), (true, 65039094552237841640.4557, 0.00003, "", 669324);
INSERT INTO t1 VALUES (71, true, true, 0.0000132, "1970-01-01", 0.000003230, 8E-16, 1.7E-24, "A", "1970-01-01", "", true, "1970-01-01", 0.000004923, 0.00705839065, 0, ""), (73, true, false, NULL, "1970-01-01", 0.000004794, 6E-16, 4.3E-24, "Zh", "1970-01-01", "", true, "1970-01-01", 0.000006298, 0.00300458179, 6, "");
INSERT INTO t0 VALUES (false, 41379862260668787148.0851, 0.00000, "Nv", 407394), (true, 44288933618282655402.4961, 0.00008, "", 41577);
INSERT INTO t0 VALUES (true, 11933849047168010315.6179, 0.00008, "swT2", 247567), (false, 33221408015223019560.8379, 0.00001, "h24Hw", 804955);
INSERT INTO t1 VALUES (21, true, false, 0.0000501, "1970-01-01", 0.000007599, 2E-16, 8.5E-24, "", "1970-01-01", "", true, "1970-01-01", 0.000001267, 0.00171303866, 4, NULL);
INSERT INTO t2 VALUES ("1970-01-01"), ("1970-01-01"), ("1970-01-01");
INSERT INTO t2 VALUES ("1970-01-01");
INSERT INTO t0 VALUES (true, 19414272664256415623.6406, NULL, "zFM", 37203);
INSERT INTO t0 VALUES (false, 98625564019898703812.0802, 0.00001, "G5", 135927), (true, 90561182029601283721.7485, 0.00008, "mQ9", 344168);
TRUNCATE TABLE t2;
INSERT INTO t0 VALUES (NULL, 5476607497795882296.2695, NULL, "b", 997454);`
2. 
SELECT  ( subt2.c_2_0 ) < ( subt2.c_2_0 )  FROM t1,  t0 FULL JOIN (SELECT t2.c_2_0 FROM t2 WHERE true) subt2 ON t0.c_0_1 = subt2.c_2_0 AND t0.c_0_1 <= subt2.c_2_0 AND t0.c_0_4 >= subt2.c_2_0 AND t0.c_0_4 >= subt2.c_2_0;
---- cardinality: 161
SELECT  ( subt2.c_2_0 ) < ( subt2.c_2_0 )  FROM t1,  t0 FULL JOIN (SELECT t2.c_2_0 FROM t2 WHERE true) subt2 ON t0.c_0_1 = subt2.c_2_0 AND t0.c_0_1 <= subt2.c_2_0 AND t0.c_0_4 >= subt2.c_2_0 AND t0.c_0_4 >= subt2.c_2_0 WHERE  ( t0.c_0_4 ) < ( t0.c_0_4 )  UNION ALL SELECT  ( subt2.c_2_0 ) < ( subt2.c_2_0 )  FROM t1,  t0 FULL JOIN (SELECT t2.c_2_0 FROM t2 WHERE true) subt2 ON t0.c_0_1 = subt2.c_2_0 AND t0.c_0_1 <= subt2.c_2_0 AND t0.c_0_4 >= subt2.c_2_0 AND t0.c_0_4 >= subt2.c_2_0 WHERE (NOT ( ( t0.c_0_4 ) < ( t0.c_0_4 ) )) UNION ALL SELECT  ( subt2.c_2_0 ) < ( subt2.c_2_0 )  FROM t1,  t0 FULL JOIN (SELECT t2.c_2_0 FROM t2 WHERE true) subt2 ON t0.c_0_1 = subt2.c_2_0 AND t0.c_0_1 <= subt2.c_2_0 AND t0.c_0_4 >= subt2.c_2_0 AND t0.c_0_4 >= subt2.c_2_0 WHERE (( ( t0.c_0_4 ) < ( t0.c_0_4 ) ) IS NULL);
---- cardinality: 147

### Expected behavior (Required)
same results
### Real behavior (Required)
results are not same
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
+---------------------------------------+
| current_version()                     |
+---------------------------------------+
| PIPELINE_SQLANCER_MASTER_ASAN bb2d138 |
+---------------------------------------+

**Comment by Seaven** [comment]
Unable to reproduce the problem
