### ISSUE TITLE
use Buffer<T> instead of std::vector<T> 

### ISSUE THREAD

**Issue by stdpain** [StarRocks/starrocks#2594]
## use Buffer<T> instead of std::vector<T> in column container

We may change the Buffer implementation in the future. but some function break this rules. we need fix it
eg:
```
raw::make_room(std::vector<T>* v, size_t n) -> raw::make_room(Buffer<T>* v, size_t n)
```

**Comment by karan-kap00r** [comment]
hey..... if this issue is still open then i would like to contribute in it!!

**Comment by johndinh391** [comment]
May I contribute to this issue? If the person above me hasn't taken it, of course.

**Comment by stdpain** [comment]
@johndinh391 I have assigned to you
