### ISSUE TITLE
Binary Data Type

### ISSUE THREAD

**Issue by smithaps89** [StarRocks/starrocks#26016]
## Enhancement
Is there not a binary data type? UUID usage is very high in our processing and we have found with mysql we can save a massive amount of space by storing them as binary data types not strings. It appears StarRocks doesn't have that data type available. Is there a reason? Also it would be great if it would get added.

**Comment by imay** [comment]
https://docs.starrocks.io/en-us/latest/sql-reference/sql-statements/data-types/BINARY#query-and-process-binary-data

In version 3.0, binary type is supported.
