### ISSUE TITLE
3.0.1版本 创建表时报错ERROR 1064 (HY000): Unexpected exception: fail to create tablet: 10012: [create tablet failed]

### ISSUE THREAD

**Issue by smallcattle** [StarRocks/starrocks#26027]
环境:分离计算模式
环境:3.0.1

### Steps to reproduce the behavior (Required)
CREATE TABLE `goods1` (
  `item_id1` int(11) NULL COMMENT "",
  `item_name` varchar(65533) NULL COMMENT "",
  `price` float NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`item_id1`, `item_name`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`item_id1`) BUCKETS 6 
PROPERTIES (
"replication_num" = "1",
"enable_storage_cache" = "true",
"storage_cache_ttl" = "2592000",
"enable_async_write_back" = "false",
"compression" = "LZ4"
); 

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by tracymacding** [comment]
Could you please give us more infomation, be.INFO for example
