### ISSUE TITLE
TRUNCATE() result error

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#2605]
### Steps to reproduce the behavior (Required)
`SELECT TRUNCATE(0.0, 1326124691);`

### Expected behavior (Required)
0.000000000000000000000000000000
### Real behavior (Required)
```
+-------------------------+
| truncate(0, 1326124691) |
+-------------------------+
|                     nan |
+-------------------------+
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
select current_version();
+------------------------------------------+
| current_version()                        |
+------------------------------------------+
| PIPELINE_SQLANCER_MASTER_RELEASE 635482f |
+------------------------------------------+
```

**Comment by liuyehcf** [comment]
Currently, function `truncate` only support type `double`, so it's the loss of accuracy is inevitable. And we can solve this problem by supporting type `decimal`
