### ISSUE TITLE
use std::variant instead of boost::variant

### ISSUE THREAD

**Issue by stdpain** [StarRocks/starrocks#2619]
StarRocks is compiled using c++17, so instead of relying on boost::variant, we can use std::variant.

This is a very simple issue, you can try this modification

**Comment by OrionSkywalker** [comment]
Is this what needs to be changed? 
be/src/exec/olap_common.h

**Comment by karan-kap00r** [comment]
hey ....if this issue is open then i would like to work with this!!

**Comment by stdpain** [comment]
@karan-kap00r I have assigned to you

**Comment by karan-kap00r** [comment]
yeah.... i have made some changes 
pls check them out  like did i do it in right way??
