### ISSUE TITLE
Whether Starrocks external tables can support RESTAPI interfaces

### ISSUE THREAD

**Issue by 0xqq** [StarRocks/starrocks#26190]
## Feature request
Whether Starrocks external tables can support RESTAPI interfaces。

**Comment by before-Sunrise** [comment]
do you mean external tables support quering using restapi interface?

**Comment by alanpaulkwan** [comment]
would be cool if you could do something liek

http://starrocks.node:9030/crsp/dsf (crps.dsf table)

aws_key = root
aws_secrey = password
