### ISSUE TITLE
BE crashed when running a long term sql

### ISSUE THREAD

**Issue by winbillatgithub** [StarRocks/starrocks#263]
### Steps to reproduce the behavior (Required)
OS: centos7.4
MEM: 32G
CPU: 16C
set global parallel_fragment_exec_instance_num = 4;
set global exec_mem_limit = 4294967296;
Running SQL:
select   
     i_item_id
    ,i_item_desc
    ,s_store_id
    ,s_store_name
    ,stddev_samp(ss_quantity)        as store_sales_quantity
    ,stddev_samp(sr_return_quantity) as store_returns_quantity
    ,stddev_samp(cs_quantity)        as catalog_sales_quantity
 from
    store_sales
   ,store_returns
   ,catalog_sales
   ,date_dim             d1
   ,date_dim             d2
   ,date_dim             d3
   ,store
   ,item
 where
     d1.d_moy               = 4 
 and d1.d_year              = 1998
 and d1.d_date_sk           = ss_sold_date_sk
 and i_item_sk              = ss_item_sk
 and s_store_sk             = ss_store_sk
 and ss_customer_sk         = sr_customer_sk
 and ss_item_sk             = sr_item_sk
 and ss_ticket_number       = sr_ticket_number
 and sr_returned_date_sk    = d2.d_date_sk
 and d2.d_moy               between 4 and  4 + 3 
 and d2.d_year              = 1998
 and sr_customer_sk         = cs_bill_customer_sk
 and sr_item_sk             = cs_item_sk
 and cs_sold_date_sk        = d3.d_date_sk     
 and d3.d_year              in (1998,1998+1,1998+2)
 group by
    i_item_id
   ,i_item_desc
   ,s_store_id
   ,s_store_name
 order by
    i_item_id 
   ,i_item_desc
   ,s_store_id
   ,s_store_name
 limit 100;

### Expected behavior (Required)
Timeout or normally end

### Real behavior (Required)
BE Crashed, 

### StarRocks version (Required)
Version: 1.18.2

### be.out
start time: Thu Sep 16 10:39:14 CST 2021
I0100 00:00:00.000000 13257 vlog_is_on.cc:192] RAW: Set VLOG level for "*" to 10
terminate called recursively
terminate called recursively
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
*** Aborted at 1631762146 (unix time) try "date -d @1631762146" if you are using GNU date ***
PC: @     0x7f95efdba387 __GI_raise
*** SIGABRT (@0x33c9) received by PID 13257 (TID 0x7f95b3f8a700) from PID 13257; stack trace: ***
    @          0x3093812 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f95f1b2f630 (unknown)
    @     0x7f95efdba387 __GI_raise
    @     0x7f95efdbba78 __GI_abort
    @          0x13ca533 _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold
    @          0x3c29f36 __cxxabiv1::__terminate()
    @          0x3c29fa1 std::terminate()
    @          0x3c2a0f5 __cxa_throw
    @          0x13c9412 _ZN12_GLOBAL__N_110handle_oomEPFPvS0_ES0_bb.cold
    @          0x3cdaa7e tcmalloc::allocate_full_cpp_throw_oom()
    @          0x14ff02b doris::vectorized::FixedLengthColumnBase<>::append()
    @          0x1519476 doris::vectorized::NullableColumn::append()
    @          0x25fb6d2 doris::vectorized::CrossJoinNode::_build()
    @          0x25fdc64 doris::vectorized::CrossJoinNode::open()
    @          0x2509335 doris::vectorized::HashJoinNode::open()
    @          0x2509335 doris::vectorized::HashJoinNode::open()
    @          0x2509335 doris::vectorized::HashJoinNode::open()
    @          0x2509335 doris::vectorized::HashJoinNode::open()
    @          0x2509335 doris::vectorized::HashJoinNode::open()
    @          0x2509335 doris::vectorized::HashJoinNode::open()
    @          0x24c434d doris::vectorized::AggregateStreamingNode::open()
    @          0x1f3f0e8 doris::PlanFragmentExecutor::_open_internal_vectorized()
    @          0x1f40751 doris::PlanFragmentExecutor::open()
    @          0x1edb5af doris::FragmentExecState::execute()
    @          0x1edcba0 doris::FragmentMgr::exec_actual()
    @          0x1ee293b std::_Function_handler<>::_M_invoke()
    @          0x2026389 doris::ThreadPool::dispatch_thread()
    @          0x2034a05 doris::Thread::supervise_thread()
    @     0x7f95f1b27ea5 start_thread
    @     0x7f95efe829fd __clone

**Comment by imay** [comment]
It is OOM.
You can set `echo 1 > /proc/sys/vm/overcommit_memory` to allow overcommit.

**Comment by trueeyu** [comment]
We plan to use ‘try catch’ to prevent this std::vector rash from being unable to apply for virtual memory.
Current can echo 1 > /proc/sys/vm/overcommit_memory to allow overcommit virtual memory

**Comment by winbillatgithub** [comment]
Yes, I have reduce the parameter of exec_mem_limit to avoid OOM.
