### ISSUE TITLE
[Docs] confusion with local caching mecanisms

### ISSUE THREAD

**Issue by parisni** [StarRocks/starrocks#26359]
File: [/docs/using_starrocks/query_cache.md](https://docs.starrocks.io/en-us/latest/using_starrocks/query_cache)

- storage cache
- block cache
- query cache

The documentation uses` local cache` in place of the 3 above and this leads to confusion

Eg:
- https://docs.starrocks.io/en-us/3.0/deployment/deploy_shared_data
- https://github.com/StarRocks/starrocks/releases/tag/3.0.0

Would help to make clear distinction

**Comment by EsoragotoSpirit** [comment]
fixed in 
https://docs.starrocks.io/en-us/3.0/deployment/deploy_shared_data
https://github.com/StarRocks/starrocks/releases/tag/3.0.0
