### ISSUE TITLE
mysql外表连接异常导致be shutdown

### ISSUE THREAD

**Issue by GitHub-19** [StarRocks/starrocks#26438]
### Steps to reproduce the behavior (Required)
![image](https://github.com/StarRocks/starrocks/assets/55374958/71a23454-a300-480a-99e4-5a7951449b10)

### StarRocks version (Required)
 - 2.4.0 c0fa2bb

**Comment by mofeiatwork** [comment]
The error message indicates that there're `too many connections` on the mysql side.

You could decrease the value of `jdbc_connection_pool_size` in `be.conf`.
