### ISSUE TITLE
Support openEuler 22.03 OS

### ISSUE THREAD

**Issue by zhengxingmao** [StarRocks/starrocks#26487]
## Feature request
Support openEuler 22.03 os

**Comment by mofeiatwork** [comment]
why ?

**Comment by zhengxingmao** [comment]
国产操作系统，信创要求下，后续都会使用国产系统。

**Comment by kevincai** [comment]
any known issues with current arm build for centos7 running on openEuler 22.03?

**Comment by zhengxingmao** [comment]
openEuler 22.03 是基于Centos 8 构建的，与Centos 7差太多了 主要是GCC版本。

**Comment by kevincai** [comment]
starrocks be binary静态链接, 生成的binary对GCC没有依赖. 可以先尝试跑一跑看.

我们很多x86_64环境也是centos7的binary在centos8的OS上运行, 目前来看没有遇到什么问题.

**Comment by zhengxingmao** [comment]
> starrocks be binary静态链接, 生成的binary对GCC没有依赖. 可以先尝试跑一跑看.
> 
> 我们很多x86_64环境也是centos7的binary在centos8的OS上运行, 目前来看没有遇到什么问题.

Centos 8上编译支持吗？

**Comment by kevincai** [comment]
想要自己宿主机直接编译的话, 可能得花点时间. 用docker环境编译的话, 应该没什么问题.

**Comment by zhengxingmao** [comment]
> 想要自己宿主机直接编译的话, 可能得花点时间. 用docker环境编译的话, 应该没什么问题.

准备裸部署的，不使用容器

**Comment by kevincai** [comment]
可以编译完成后, 生成的产物复制出来, 裸部署

**Comment by zhengxingmao** [comment]
对稳定性有没有影响呢，比如brpc，还有第三方依赖库

**Comment by kevincai** [comment]
目前没有已知的问题, 如果遇到, 请反馈给我们.
