### ISSUE TITLE
CANCELLED msg:[Set cancelled by MemoryScratchSinkOperator]

### ISSUE THREAD

**Issue by Harries** [StarRocks/starrocks#26560]
### Steps to reproduce the behavior (Required)
CREATE TABLE `ods_core_lcprem` (
  `polno` varchar(20) NOT NULL COMMENT "",
  `dutycode` varchar(10) NOT NULL COMMENT "",
  `payplancode` varchar(8) NOT NULL COMMENT "",
  `grpcontno` varchar(20) NOT NULL COMMENT "",
  `contno` varchar(20) NOT NULL COMMENT "",
  `payplantype` varchar(6) NULL COMMENT "",
  `appnttype` char(1) NULL COMMENT "",
  `appntno` varchar(24) NULL COMMENT "",
  `urgepayflag` char(1) NULL COMMENT "",
  `needacc` char(1) NULL COMMENT "",
  `paytimes` decimal128(27, 0) NULL COMMENT "",
  `rate` decimal128(10, 4) NULL COMMENT "",
  `paystartdate` datetime NULL COMMENT "",
  `payenddate` datetime NULL COMMENT "",
  `paytodate` datetime NULL COMMENT "",
  `payintv` decimal128(27, 0) NULL COMMENT "",
  `standprem` decimal128(12, 2) NULL COMMENT "",
  `prem` decimal128(12, 2) NULL COMMENT "",
  `sumprem` decimal128(12, 2) NULL COMMENT "",
  `suppriskscore` decimal128(12, 2) NULL COMMENT "",
  `freeflag` char(1) NULL COMMENT "",
  `freerate` decimal128(11, 4) NULL COMMENT "",
  `freestartdate` datetime NULL COMMENT "",
  `freeenddate` datetime NULL COMMENT "",
  `state` varchar(10) NULL COMMENT "",
  `managecom` varchar(10) NULL COMMENT "",
  `operator` varchar(10) NOT NULL COMMENT "",
  `makedate` datetime NOT NULL COMMENT "",
  `maketime` char(8) NOT NULL COMMENT "",
  `modifydate` datetime NOT NULL COMMENT "",
  `modifytime` char(8) NOT NULL COMMENT "",
  `addfeedirect` varchar(2) NULL COMMENT "",
  `secinsuaddpoint` decimal128(12, 2) NULL COMMENT "",
  `addform` varchar(2) NULL COMMENT "",
  `currency` varchar(3) NULL COMMENT "",
  `addresult` varchar(1) NULL COMMENT "",
  `addremark` varchar(500) NULL COMMENT "",
  `prtseq` varchar(20) NULL COMMENT "",
  `needprint` char(1) NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(`polno`, `dutycode`, `payplancode`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`polno`, `dutycode`, `payplancode`) BUCKETS 16 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
);
2. INSERT INTO  ods_core_lcprem (  faker data about 13357436  rows)
3. [select ](http://XXXX/api/{database}/{table}/_query_plan)
4. use thrift to connect to be node  for get tablets datas.

### Expected behavior (Required)
get all data for this table
### Real behavior (Required)
java.lang.RuntimeException: Failed to get next from be -> ip:[kube-starrocks-be-1.kube-starrocks-be-search.int.svc.cluster.local] CANCELLED msg:[Set cancelled by MemoryScratchSinkOperator]

### StarRocks version (Required)
3.0
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by Harries** [comment]
3.0.0 48f4d81d7b

**Comment by trueeyu** [comment]
Fixed by: 

  - https://github.com/StarRocks/starrocks/pull/30702
  - https://github.com/StarRocks/starrocks/pull/30751
