### ISSUE TITLE
dbt use incremental and engine=primary appear compile error

### ISSUE THREAD

**Issue by lllong33** [StarRocks/starrocks#26608]
## General Question
@motto1314 @chaoyli please help me!

![image](https://github.com/StarRocks/starrocks/assets/29864358/043716a5-bb84-46e4-a04f-9b72c0505c0e)

**Comment by chaoyli** [comment]
What's the meaning of `materialized` here?

**Comment by lllong33** [comment]
The creation of the table is initialized only once, followed by insert into select *

**Comment by chaoyli** [comment]
What's the `create table` SQL?

**Comment by lllong33** [comment]
![image](https://github.com/StarRocks/starrocks/assets/29864358/ffdfa005-4161-4982-a5e8-6f4ca026f218)

**Comment by lllong33** [comment]
Is there any good debug method, other than intrusive breakpoint()

**Comment by chaoyli** [comment]
@lllong33 are you in china, could you can add my wechat(chaoy-li)?

**Comment by Astralidea** [comment]
Now the engine only supports olap, maybe you want to set table_type: 'PRIMARY'?

**Comment by lllong33** [comment]
Find a partition increment mode, as shown in the following figure, because the local SR version =2.3, the primary function cannot be verified for the time being.
![a1ef1b11afc477cb394eb327df6b9b4](https://github.com/StarRocks/starrocks/assets/29864358/21760c3a-7eb8-4782-9517-f3d1899b9014)
