### ISSUE TITLE
support  json、array、bitmap  Datatype of external table column for postgresql JDBC catalog 

### ISSUE THREAD

**Issue by ZeyiY** [StarRocks/starrocks#26701]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Real behavior (Required)
![image](https://github.com/StarRocks/starrocks/assets/11460868/7883d425-0c62-4d69-8831-f2c939a7fcb8)
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 3.0.3 fe5e3a1

**Comment by mofeiatwork** [comment]
it should be a feature request, but not a bug.
