### ISSUE TITLE
flink StarRocks Connector has no data type mapping table

### ISSUE THREAD

**Issue by walkhan** [StarRocks/starrocks#2671]
## Enhancement
website link：https://docs.starrocks.com/zh-cn/main/loading/Flink-connector-starrocks
add: Flink and StarRocks data type mapping table
Reference:https://doris.apache.org/master/zh-CN/extending-doris/flink-doris-connector.html#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

**Comment by hffariel** [comment]
Thanks for the feedback, we'll add the type mapping table ASAP. 
BTW, you could try out the [smt](https://starrocks-public.oss-cn-zhangjiakou.aliyuncs.com/flink/smt.tar.gz) which will help you to convert the table structure automatically, both for the `flink` and `StarRocks`.
