### ISSUE TITLE
[Feature] filter cluase or filter syntax support

### ISSUE THREAD

**Issue by vkingnew** [StarRocks/starrocks#26730]
SQL:2003 introduced the filter clause as part of the optional feature “Advanced OLAP operations” (T612). pg had impelements.

refer to:
https://modern-sql.com/feature/filter
refer postgresql:
https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-AGGREGATES

refer trino:
https://trino.io/docs/current/functions/aggregate.html#

Use case
simple the SQL statement

**Comment by mofeiatwork** [comment]
it could be simulated with a `case-when` expression, because aggregation function will ignore null values.

**Comment by LiShuMing** [comment]
But if we can support `filter` aggregate, this may make it easier for users?

**Comment by vkingnew** [comment]
> But if we can support `filter` aggregate, this may make it easier for users?

it useful for aggredate .clickhouse had support it 
refer to:
https://clickhouse.com/docs/knowledgebase/filtered-aggregates
