### ISSUE TITLE
[materialized view optimization] inactive_reason is not empty when mv is active

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#27038]
### Steps to reproduce the behavior (Required)
![image](https://github.com/StarRocks/starrocks/assets/35227922/783d4566-873d-48c6-8e57-1c15d08e28e4)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`branch-3.1-dca7ca2`

**Comment by mofeiatwork** [comment]
fixed by https://github.com/StarRocks/starrocks/pull/27053
