### ISSUE TITLE
[materialized view optimization] create mv failed

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#27080]
### Steps to reproduce the behavior (Required)
```
CREATE TABLE t1 (
    k1 int,
    k2 int
)
DUPLICATE KEY(k1)
distributed by hash(k1)
properties ("colocate_with" = "group11");
CREATE MATERIALIZED VIEW mv4 distributed by hash(k1) REFRESH MANUAL properties ("colocate_with" = "group11") AS SELECT k1,sum(k2) FROM t1 group by k1;
```

### Expected behavior (Required)
`Query OK, 0 rows affected (0.02 sec)`
### Real behavior (Required)
`ERROR 1064 (HY000): Unexpected exception: Colocate tables must have same bucket num: 0, with group 14188.14198`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`branch-3.1-dca7ca2`

**Comment by chaoyli** [comment]
https://github.com/StarRocks/starrocks/pull/27086 This pull request will address this problem.
