### ISSUE TITLE
Load memory limited exceeded causing tablet set to error state

### ISSUE THREAD

**Issue by decster** [StarRocks/starrocks#2714]
`
E0108 15:23:14.099944 80768 tablet_updates.cpp:713] _apply_rowset_commit error: load rowset update state failed: Memory limit exceeded: Memory exceed limit. read and decompress page Used: 65702297112, Limit: 65701739630. Mem usage has exceed the limit of load tablet:17295515 #version:516 [3596 4100@514 4101] pending: rowsets:35
E0108 15:23:14.102236 80767 tablet_updates.cpp:713] _apply_rowset_commit error: load rowset update state failed: Memory limit exceeded: Memory exceed limit. read and decompress page Used: 65985572488, Limit: 65701739630. Mem usage has exceed the limit of load tablet:17295535 #version:3448 [27530 30965@3446 30966] pending: rowsets:9
E0108 15:45:29.738562 89835 tablet_updates.cpp:713] _apply_rowset_commit error: load rowset update state failed: Memory limit exceeded: Memory exceed limit. read and decompress page Used: 65765473072, Limit: 65701739630. Mem usage has exceed the limit of load tablet:17295535 #version:3483 [27530 30999@3481 31000] pending: rowsets:37
E0108 15:45:29.738725 89836 tablet_updates.cpp:713] _apply_rowset_commit error: load rowset update state failed: Memory limit exceeded: Memory exceed limit. read and decompress page Used: 65765461632, Limit: 65701739630. Mem usage has exceed the limit of load tablet:17295519 #version:13 [4123 4133@11 4134] pending: rowsets:12
E0108 15:45:29.738812 89837 tablet_updates.cpp:713] _apply_rowset_commit error: load rowset update state failed: Memory limit exceeded: Memory exceed limit. read and decompress page Used: 65765450144, Limit: 65701739630. Mem usage has exceed the limit of load tablet:17295503 #version:11 [190 196.1@9 197] pending: rowsets:2
E0108 15:45:29.739686 89837 tablet_updates.cpp:713] _apply_rowset_commit error: load rowset update state failed: Memory limit exceeded: Memory exceed limit. read and decompress page Used: 65769587864, Limit: 65701739630. Mem usage has exceed the limit of load tablet:17295495 #version:16 [51 62@14 63] pending: rowsets:3
E0108 15:45:31.848917 89843 tablet_updates.cpp:713] _apply_rowset_commit error: load rowset update state failed: Memory limit exceeded: Memory exceed limit. read and decompress page Used: 65765473072, Limit: 65701739630. Mem usage has exceed the limit of load tablet:17295535 #version:3484 [27530 30999@3481 31000.1] pending: rowsets:2
`

`
W0108 15:32:59.195078 132154 tablet_scanner.cpp:56] [10.200.0.35] fail to prepare tablet reader 17295515.1502340074.934035bbd02ee30e-bc2b1ada568993bf: Internal error: tablet updates in error state, cannot get_applied_rowsets failed, tablet in error state, tablet:17295515
E0108 15:32:59.195099 132154 olap_scan_node.cpp:89] Failed to start scan node: Internal error: [10.200.0.35] fail to prepare tablet reader 17295515.1502340074.934035bbd02ee30e-bc2b1ada568993bf: Internal error: tablet updates in error state, cannot get_applied_rowsets failed, tablet in error state, tablet:17295515
`

**Comment by trueeyu** [comment]
https://github.com/StarRocks/starrocks/pull/2794/files  https://github.com/StarRocks/starrocks/pull/2744/files may fix this
