### ISSUE TITLE
Not able to select struct fields within Iceberg table in case field name has non-lowercase letters

### ISSUE THREAD

**Issue by mcgray** [StarRocks/starrocks#27173]
Version 3.0

When adding external Glue catalogue with Iceberg tables I can see that for a struct:
`STRUCT<enriched_ts varchar(1048576), enriched_ts_long bigint(20), create_ts bigint(20), message_ts bigint(20), sessionId varchar(1048576), version varchar(1048576), originRQ varchar(1048576), originRC varchar(1048576), st varchar(1048576), tm varchar(1048576), og varchar(1048576), bs varchar(1048576), bsr varchar(1048576), sprtnr varchar(1048576)>`
All fields are accessible except those having uppercase letters. E.g. : sessionId.
`select enriched_attrs.sessionId from some_db.some_table limit 10;`
Produces:
`SQL Error [1064] [42000]: Struct subfield name: sessionid not found!`

**Comment by zombee0** [comment]
use #27313
