### ISSUE TITLE
docker run starRocks error!!!

### ISSUE THREAD

**Issue by chengpeng2015** [StarRocks/starrocks#27177]
### Steps to reproduce the behavior (Required)
1. pull imags `docker pull starrocks/allin1-ubuntu:2.5-latest`
2. run starRocks container `docker run -p 9030:9030 -p 8030:8030 -p 8040:8040     -itd starrocks/allin1-ubuntu-2.5`
3. start error!

error detail:
![image](https://github.com/StarRocks/starrocks/assets/13881307/26bd4b70-5c84-44ae-83bc-d40d0c566e7e)

env:
![image](https://github.com/StarRocks/starrocks/assets/13881307/39a1571c-ff84-45cc-81bf-3d516fb0e068)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by kevincai** [comment]
can you mount a directory into container at `/data/deploy/starrocks/fe/log`, when the docker container exits, check the logs named `fe.out`, `fe.info` see if any findings.

**Comment by alberttwong** [comment]
why is the docker version so old? 

```
atwong@Alberts-MBP-3 ~ % docker version
Client:
 Cloud integration: v1.0.35
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:51:16 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.21.1 (114176)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:50:59 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
