### ISSUE TITLE
Help. How can you change the password in the k8s operator

### ISSUE THREAD

**Issue by rpkrfy** [StarRocks/starrocks#27245]
## General Question
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
[Fri Jul 14 07:34:36 UTC 2023] Add myself (starrockscluster-sample-be-0.starrockscluster-sample-be-search.starrocks.svc.cluster.local:9050) into FE ...
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
[Fri Jul 14 07:34:38 UTC 2023] Add myself (starrockscluster-sample-be-0.starrockscluster-sample-be-search.starrocks.svc.cluster.local:9050) into FE ...
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
[Fri Jul 14 07:34:40 UTC 2023] Add myself (starrockscluster-sample-be-0.starrockscluster-sample-be-search.starrocks.svc.cluster.local:9050) into FE ...
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
[Fri Jul 14 07:34:42 UTC 2023] Add myself (starrockscluster-sample-be-0.starrockscluster-sample-be-search.starrocks.svc.cluster.local:9050) into FE ...
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
[Fri Jul 14 07:34:44 UTC 2023] Add myself (starrockscluster-sample-be-0.starrockscluster-sample-be-search.starrocks.svc.cluster.local:9050) into FE ...
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
[Fri Jul 14 07:34:44 UTC 2023] Time out, abort!

**Comment by kevincai** [comment]
please refer to this doc if you need change the root password: https://github.com/StarRocks/starrocks-kubernetes-operator/blob/main/doc/change_root_password_howto.md
