### ISSUE TITLE
Delete handle error 

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#2724]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS w0;
CREATE DATABASE w0;
USE w0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 VARCHAR(21) NULL ,c_0_1 DATETIME NULL ,c_0_2 DECIMAL64(4, 3)  NULL ,c_0_3 BOOLEAN NULL ) DUPLICATE KEY (c_0_0,c_0_1) DISTRIBUTED BY HASH (c_0_1,c_0_0) properties("replication_num"="1") ;
CREATE TABLE t1 (c_1_0 BIGINT NOT NULL ,c_1_1 SMALLINT NOT NULL ,c_1_2 BOOLEAN NOT NULL ,c_1_3 DATE NOT NULL ,c_1_4 VARCHAR(1) NOT NULL ,c_1_5 DECIMAL32(6, 4)  NULL ,c_1_6 DATETIME NULL ,c_1_7 FLOAT NOT NULL ,c_1_8 DECIMAL64(13, 4)  NOT NULL ,c_1_9 DECIMAL64(3, 1)  NULL ,c_1_10 BOOLEAN NOT NULL ,c_1_11 DECIMAL64(1, 0)  NOT NULL ,c_1_12 DECIMAL32(2, 1)  NOT NULL ,c_1_13 FLOAT NOT NULL ,c_1_14 DECIMAL(1, 0)  NOT NULL ,c_1_15 DECIMAL32(2, 1)  NOT NULL ) DUPLICATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6) DISTRIBUTED BY HASH (c_1_5,c_1_1,c_1_2,c_1_6,c_1_0) properties("replication_num"="1") ;
CREATE TABLE t2 (c_2_0 CHAR(1) NOT NULL ,c_2_1 DATETIME MIN NULL ,c_2_2 DECIMAL(3, 2)  MIN NULL ,c_2_3 BITMAP BITMAP_UNION NOT NULL ,c_2_4 VARCHAR(21) MIN NOT NULL ,c_2_5 PERCENTILE PERCENTILE_UNION NULL ,c_2_6 CHAR(1) MAX NOT NULL ) AGGREGATE KEY (c_2_0) DISTRIBUTED BY HASH (c_2_0) properties("replication_num"="1") ;
CREATE TABLE t3 (c_3_0 LARGEINT NULL ,c_3_1 DECIMAL128(20, 10)  NULL ,c_3_2 DATE NULL ,c_3_3 VARCHAR(1) NULL ,c_3_4 DECIMAL64(11, 5)  NOT NULL ,c_3_5 HLL HLL_UNION NOT NULL ,c_3_6 FLOAT MAX NOT NULL ) AGGREGATE KEY (c_3_0,c_3_1,c_3_2,c_3_3,c_3_4) DISTRIBUTED BY HASH (c_3_0,c_3_1,c_3_4,c_3_3) properties("replication_num"="1") ;
INSERT INTO t1 VALUES (-735417873, 14, true, "1970-01-01", "", 0.0066, "1970-01-01 08:00:00", 0.05675517356692883, 33064.9080, 5.6, false, 3, 0.1, 0.46958567314993893, 0, 0.5), (779416366, 14, true, "1970-01-01", "", NULL, NULL, 2.55431187E8, 11853.3288, 2.3, true, 0, 0.6, 0.7020445228190976, 1, 0.5);
TRUNCATE TABLE t0;
INSERT INTO t2 VALUES ("", "1970-01-01 08:00:00", 0.01, bitmap_hash("EBZbwNEX5"), "p", percentile_hash("1321826953"), ""), ("", "1970-01-01 08:00:00", 0.04, bitmap_hash("R977"), "J", percentile_hash("-2135471277"), ""), ("", "1970-01-01 08:00:00", 0.01, bitmap_hash("m"), "", percentile_hash("878343143"), "");
INSERT INTO t2 VALUES ("", NULL, 0.01, bitmap_hash("Go"), "QthXw6G", percentile_hash("-1262563540"), ""), ("", "1970-01-01 08:00:00", 0.06, bitmap_hash("T6"), "E2Y", percentile_hash("-1962124352"), "");
INSERT INTO t2 VALUES ("", "1970-01-01 08:00:00", 0.08, bitmap_hash("mLt"), "cx", percentile_hash("-1903372921"), ""), ("", NULL, 0.01, bitmap_hash("DM"), "5A", percentile_hash("-304290156"), "");
INSERT INTO t0 VALUES ("l", "1970-01-01 08:00:00", 0.007, true);
INSERT INTO t0 VALUES (NULL, "1970-01-01 08:00:00", 0.008, true), ("", "1970-01-01 08:00:00", NULL, false);
INSERT INTO t2 VALUES ("", "1970-01-01 08:00:00", 0.06, bitmap_hash("rtZ5"), "", percentile_hash("508218485"), ""), ("", "1970-01-01 08:00:00", 0.06, bitmap_hash("nP4"), "", percentile_hash("-1836516471"), "");
DELETE FROM t2 WHERE c_2_0="";
2. SELECT t2.c_2_0 FROM t2;
-- cardinality: 0
-- SELECT t2.c_2_0 FROM t2 WHERE ((((("")||("")))||(ST_LINEFROMTEXT("") )))  BETWEEN (t2.c_2_0) AND (SPACE(407245419) )  UNION ALL SELECT t2.c_2_0 FROM t2 WHERE (NOT (((((("")||("")))||(ST_LINEFROMTEXT("") )))  BETWEEN (t2.c_2_0) AND (SPACE(407245419) ) )) UNION ALL SELECT t2.c_2_0 FROM t2 WHERE ((((((("")||("")))||(ST_LINEFROMTEXT("") )))  BETWEEN (t2.c_2_0) AND (SPACE(407245419) ) ) IS NULL);
-- cardinality: 1

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - main Release
 - mysql> select current_version();
+---------------------------------+
| current_version()               |
+---------------------------------+
| SQLANCER_MASTER_RELEASE f24400d |
+---------------------------------+

**Comment by laotan332** [comment]
fix by #2755
