### ISSUE TITLE
properties info disappeared in table

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#27357]
### Steps to reproduce the behavior (Required)
```
CREATE TABLE t2 (
    k1 INT,
    k2 varchar(20))
DUPLICATE KEY(k1)
DISTRIBUTED BY HASH(k1)
properties (
"replication_num" = "3",
"replicated_storage" = "false",
"storage_medium" = "SSD",
"colocate_with" = "groupmnbvc",
"storage_cooldown_time" = "2050-01-01 00:00:01"
);
show create table t2;
```

### Expected behavior (Required)
CREATE TABLE `t2` (
  `k1` int(11) NULL COMMENT "",
  `k2` varchar(20) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`k1`)
DISTRIBUTED BY HASH(`k1`) BUCKETS 6
PROPERTIES (
"replication_num" = "3",
"colocate_with" = "groupmnbvc",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "false",
"storage_medium" = "SSD",
"compression" = "LZ4",
"storage_cooldown_time" = "2050-01-01 00:00:01"
);
### Real behavior (Required)
```
CREATE TABLE `t2` (
  `k1` int(11) NULL COMMENT "",
  `k2` varchar(20) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`k1`)
DISTRIBUTED BY HASH(`k1`) BUCKETS 6
PROPERTIES (
"replication_num" = "3",
"colocate_with" = "groupmnbvc",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "false",
"storage_medium" = "SSD",
"compression" = "LZ4"
);
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`branch-3.1-0f690e6`

**Comment by Astralidea** [comment]
This parameter should be a consumed parameter during design, and it is normal that it does not exist after create table.
