### ISSUE TITLE
[materialized view optimization] properties info error in mv

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#27356]
### Steps to reproduce the behavior (Required)
```
CREATE TABLE t1 (
    k1 INT,
    k2 varchar(20))
DUPLICATE KEY(k1);
CREATE MATERIALIZED VIEW mv1 distributed by hash(k1) REFRESH MANUAL
properties (
    "replication_num" = "3",
    "replicated_storage" = "false",
    "storage_medium" = "SSD",
    "colocate_with" = "groupmnbvc",
    "storage_cooldown_time" = "2050-01-01 00:00:01"
    ) AS SELECT k1,sum(k2) FROM t1 group by k1;
show create table mv1;
```

### Expected behavior (Required)
`"replicated_storage" = "false"`
### Real behavior (Required)
`"replicated_storage" = "true"`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`branch-3.1-0f690e6`

**Comment by Astralidea** [comment]
Fixed in https://github.com/StarRocks/starrocks/pull/27309
