### ISSUE TITLE
Column matching problem of hive external table with csv format

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#2738]
### Steps to reproduce the behavior (Required)
For hive external table with CSV format, the column content display is based on the column order in the text file, not the corresponding content based on the field name of the hive table

### Expected behavior (Required)
The content of the hive external table with CSV format field is the content of the field in the corresponding hive table.

### Real behavior (Required)
For hive external table with CSV format, the column content display is based on the column order in the text file.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN e8f11970  |
+-------------------+
1 row in set (0.01 sec)
```

**Comment by caneGuy** [comment]
user may need to give <column name , column id number> when create external table for this 
@imay @DorianZheng
Do you have any idea?
