### ISSUE TITLE
how to use Destination Starrocks - Airbyte Connector

### ISSUE THREAD

**Issue by imiskolee** [StarRocks/starrocks#27459]
did anyone tried the airbyte starrocks connector, I tried https://github.com/StarRocks/starrocks/tree/main/contrib/destination-starrocks on master airbyte repo, but said Cannot locate tasks that match ':airbyte-integrations:connectors:destination-starrocks:airbyteDocker' as project 'destination-starrocks' not found in project ':airbyte-integrations:connectors'.

**Comment by alberttwong** [comment]
You want to follow this.  https://github.com/StarRocks/starrocks/discussions/23713.   I wouldn't compile the container and just use the one that StarRock's docker hub account gives you.
