### ISSUE TITLE
[Doc]:  使用 Operator 部署 的 StarRocks 集群  如何修改持久化存储为nfs

### ISSUE THREAD

**Issue by An1990** [StarRocks/starrocks#27465]
### Ask the Question

 使用 Operator 部署 的 StarRocks 集群  如何修改持久化存储为nfs

**Comment by yandongxiao** [comment]
Operator 后端是使用 Statefulset，NFS 服务需要支持通过 PVC 动态供应PV。

如果你使用的是HELM Chart部署，请参看 https://github.com/StarRocks/starrocks-kubernetes-operator/blob/main/helm-charts/charts/kube-starrocks/values.yaml 中的 storageSpec 字段。
如果你直接使用 StarRocksCluster CRD 来部署，请参看 https://github.com/StarRocks/starrocks-kubernetes-operator/blob/main/doc/api.md 的 storageVolumes 字段。
