### ISSUE TITLE
Add `toStartOfFiveMinute` or similar functions in StarRocks

### ISSUE THREAD

**Issue by SaintBacchus** [StarRocks/starrocks#2747]
Clickhouse function `toStartOfFiveMinute` and `toStartOfTenMinutes`  are offen been used by BI user, but StarRocks only support the `toStartOfMinute` by using `date_trunc('minute', datetime_field)`.

Is there any plan to imlp these function?  If not, can I add some new format such as `5min` or `10min` in function `date_trunc`

**Comment by imay** [comment]
Thanks for your suggestion.
@Dshadowzh PTAL.

**Comment by Dshadowzh** [comment]
Thanks, will consider it in next few versions.
