### ISSUE TITLE
[Enhancement] Early materialization for non-collerated semi join

### ISSUE THREAD

**Issue by Leon-WTF** [StarRocks/starrocks#27558]
## Enhancement
For query like "select * from t1 where a = (select max(a) from t2)", normally it is done by a join. 
If the subquery "select max(a) from t2" can be materialized firstly, then the outer query become "select * from t1 where a = 'xx'", the predicate can by pushed down to storage to reduce data scanned greatly, and avoid the join overhead.

**Comment by imay** [comment]
I think this query can leverage starrocks' runtime filter which can also let the intermediate result be pushed down to the probe side.
Have you tested the different ways to run this query? Could you share the performances and the profiles?

**Comment by Leon-WTF** [comment]
> I think this query can leverage starrocks' runtime filter which can also let the intermediate result be pushed down to the probe side. Have you tested the different ways to run this query? Could you share the performances and the profiles?

@imay yes, maybe we can extend runtime filter to in/=/>/< and we can also bypass the join operation for semi join, right?
