### ISSUE TITLE
when there is no constant function,the predicate push down failed

### ISSUE THREAD

**Issue by bigdata-kuxingseng** [StarRocks/starrocks#2759]
when there is no constant function,such as the timestamp,str_to_date(date_format(`t0`.`__fcol_13`, '%Y-%m-%d'), '%Y-%m-%d'),date,the predicate push down failed,the starrocks scan all data

**Comment by Dshadowzh** [comment]
Yeah, There is some constant expressions (especially datetime functions) that are not yet implemented in FE. Would you like to implement them？

**Comment by bigdata-kuxingseng** [comment]
> Yeah, There is some constant expressions (especially datetime functions) that are not yet implemented in FE. Would you like to implement them？

yes,with pleasure.Would you pls give me a thinking ,my wechat is tengluo0904,pls contact me
