### ISSUE TITLE
Column nullable info is wrong

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#2761]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS d4;
CREATE DATABASE d4;
USE d4;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DATE NULL ,c_0_1 DECIMAL32(3, 2)  NULL ,c_0_2 CHAR(11) NOT NULL ,c_0_3 DECIMAL64(9, 3)  NULL ,c_0_4 DATE NOT NULL ,c_0_5 DECIMAL64(13, 4)  NULL ,c_0_6 DECIMAL(17, 7)  NULL ,c_0_7 LARGEINT NULL ,c_0_8 DATETIME NULL ,c_0_9 DECIMAL128(23, 2)  NOT NULL ,c_0_10 DATETIME NOT NULL ,c_0_11 BOOLEAN NULL ,c_0_12 DECIMAL128(30, 9)  NOT NULL ,c_0_13 DOUBLE NOT NULL ,c_0_14 DECIMAL(20, 6)  NULL ,c_0_15 DECIMAL64(11, 1)  NULL ,c_0_16 DECIMAL32(5, 3)  NULL ) DUPLICATE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5,c_0_6,c_0_7,c_0_8,c_0_9,c_0_10) DISTRIBUTED BY HASH (c_0_3,c_0_6,c_0_10,c_0_9,c_0_2,c_0_8,c_0_4,c_0_0,c_0_7,c_0_5,c_0_1) properties("replication_num"="1") ;
CREATE TABLE t1 (c_1_0 DECIMAL(18, 8)  NULL ,c_1_1 DECIMAL128(11, 2)  NOT NULL ,c_1_2 DECIMAL64(6, 5)  NOT NULL ,c_1_3 DECIMAL(12, 7)  NOT NULL ,c_1_4 DECIMAL(7, 1)  NULL ,c_1_5 DECIMAL(11, 7)  NULL ,c_1_6 DECIMAL64(2, 2)  MIN NULL ,c_1_7 CHAR(11) MIN NULL ,c_1_8 DECIMAL32(3, 3)  MIN NOT NULL ,c_1_9 BOOLEAN REPLACE NULL ,c_1_10 FLOAT REPLACE NULL ,c_1_11 DECIMAL32(8, 4)  REPLACE NULL ) AGGREGATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5) DISTRIBUTED BY HASH (c_1_3,c_1_0) properties("replication_num"="1") ;
CREATE TABLE IF NOT EXISTS t2 (c_2_0 DECIMAL128(13, 10)  NULL ,c_2_1 BOOLEAN NULL ,c_2_2 BOOLEAN NOT NULL ,c_2_3 DOUBLE NULL ,c_2_4 INT NOT NULL ,c_2_5 VARCHAR(1) NULL ,c_2_6 DATE NULL ) UNIQUE KEY (c_2_0) DISTRIBUTED BY HASH (c_2_0) properties("replication_num"="1") ;
CREATE TABLE IF NOT EXISTS t3 (c_3_0 BIGINT NULL ,c_3_1 FLOAT MAX NULL ) AGGREGATE KEY (c_3_0) DISTRIBUTED BY HASH (c_3_0) properties("replication_num"="1") ;
INSERT INTO t1 VALUES (19.81997123, 2136874.21, 0.00007, 0.0084281, 95237.3, 0.0007339, 0.08, "", 0.001, false, 0.9107814538323017, 0.8445);
INSERT INTO t0 VALUES ("1970-01-01", 0.04, "", NULL, "1970-01-01", 33951.9965, 395.6458098, -165208317, "1970-01-01 08:00:00", 2632890166924921217.68, "1970-01-01 08:00:00", false, 485180362950.708907924, 5.83512768E8, 79540186.864131, 427261493.1, 0.065), ("1970-01-01", 0.06, "2x", 472.001, "1970-01-01", 77798.2753, 203.3031726, -951303276, "1970-01-01 08:00:00", 4271521841091293677.39, "1970-01-01 08:00:00", false, 486815688242.700824605, -0.0, 66494515.787469, 277998772.6, 0.024), ("1970-01-01", NULL, "1N", 485.319, "1970-01-01", 47011.5600, 495.7961641, -252349457, "1970-01-01 08:00:00", 3401368723906133009.54, "1970-01-01 08:00:00", true, 587811317143.127464799, 0.09765618552770317, 81580109.534696, 759219309.4, 0.056);
INSERT INTO t0 VALUES ("1970-01-01", 0.00, "", 888.310, "1970-01-01", NULL, NULL, -1881161675, "1970-01-01 08:00:00", 1577748855948582598.68, "1970-01-01 08:00:00", true, 688832430763.630151990, 0.2232839047662768, 48074381.179268, 600319386.6, 0.056);
INSERT INTO t0 VALUES ("1970-01-01", NULL, "", 440.895, "1970-01-01", 87363.1302, 356.9958507, -654358448, "1970-01-01 08:00:00", 9202699853776513134.01, "1970-01-01 08:00:00", false, 205729012021.019088631, 0.404423187607022, 73941596.399865, 294846149.2, 0.014), ("1970-01-01", 0.08, "", 417.040, "1970-01-01", 98689.5170, 605.1609781, 102135764, "1970-01-01 08:00:00", 1486305453120623879.06, "1970-01-01 08:00:00", true, 210568113603.363607923, -9.65702411E8, 57682548.299920, 111046709.1, NULL);
INSERT INTO t2 VALUES (3.25E-8, true, true, NULL, 30, "", "1970-01-01");
INSERT INTO t3 VALUES (-625501169, 0.7255277599763855);
INSERT INTO t2 VALUES (4.31E-8, true, true, 0.36076480661643406, 1, "", "1970-01-01"), (5.34E-8, false, false, 0.2562690449783457, 13, "", "1970-01-01"), (NULL, true, true, NULL, 29, "", "1970-01-01");
INSERT INTO t0 VALUES ("1970-01-01", 0.00, "dKFvZdL", NULL, "1970-01-01", 66260.7287, NULL, -1550424519, "1970-01-01 08:00:00", 1015771030987047284.71, "1970-01-01 08:00:00", false, 572644646771.870150712, 0.8342678736900822, 64620992.193810, 43320234.1, 0.003), ("1970-01-01", NULL, "", 777.850, "1970-01-01", 46122.2626, 857.8501699, -1730039404, "1970-01-01 08:00:00", 4393200386682590085.63, "1970-01-01 08:00:00", true, 343520854281.388301798, 0.055826380703112743, 84157262.577948, 773419774.1, 0.093);
INSERT INTO t0 VALUES (NULL, 0.01, "vJ", 291.756, "1970-01-01", 83463.8396, 25.9164413, 1124418430, "1970-01-01 08:00:00", 2046457030418075485.84, "1970-01-01 08:00:00", true, 994621778232.420721383, 0.7915375544930072, 19800128.348516, 140029410.6, 0.012), ("1970-01-01", 0.04, "F", 181.262, "1970-01-01", 30416.6165, 508.9052462, 1720762366, "1970-01-01 08:00:00", 8705050071319748658.40, "1970-01-01 08:00:00", true, 47899752454.313687333, 0.13915468216067262, 64134281.209974, 632664940.8, 0.009);
INSERT INTO t2 VALUES (5.52E-8, true, false, 0.4534181604923957, 4, "", "1970-01-01"), (6.22E-8, true, false, 0.4377990212439278, 20, "", "1970-01-01");
INSERT INTO t3 VALUES (1671224719, 0.6811176964435338), (-423858841, 0.7093945686051187);
INSERT INTO t3 VALUES (636545648, 0.518865770662371);
DELETE FROM t1 WHERE c_1_2=0.00008 AND c_1_5=0.0003448 AND c_1_1=5555080.12 AND c_1_4=23696.7 AND c_1_0=85.76412084;
INSERT INTO t2 VALUES (6.81E-8, true, false, 0.1935732519934964, 3, "", "1970-01-01");
INSERT INTO t0 VALUES ("1970-01-01", 0.02, "iq8", 928.828, "1970-01-01", 39926.2448, 436.6794256, 1491910726, "1970-01-01 08:00:00", 8739056363461714920.22, "1970-01-01 08:00:00", true, 763861894318.919904888, 0.35476096851075933, 81652290.767247, NULL, 0.032), ("1970-01-01", 0.08, "1qXwyKD2", 117.914, "1970-01-01", 81239.5217, 425.8972593, -846308968, "1970-01-01 08:00:00", 6603439133053550701.09, "1970-01-01 08:00:00", false, 263156930297.413361137, 0.09788617464241456, 49512484.731148, 707372665.3, 0.088), ("1970-01-01", 0.06, "xx", 202.265, "1970-01-01", 18101.2800, 404.9365772, 892663233, "1970-01-01 08:00:00", 449705863546581817.62, "1970-01-01 08:00:00", true, 390230997235.761134991, 0.30019090916505153, 2414662.842009, 768438165.8, 0.063);
TRUNCATE TABLE t1;
INSERT INTO t1 VALUES (0.20739520, 7951896.77, 0.00001, 0.0095874, 63359.0, 0.0007322, 0.02, "Y9", 0.003, false, 0.8776853098354057, 0.4811);
INSERT INTO t3 VALUES (-1361058133, 0.43149025103017025);
INSERT INTO t1 VALUES (67.31778219, 7039064.31, 0.00002, 0.0037009, 15003.2, NULL, 0.04, "", 0.003, false, 0.3242578965934375, 0.0196);
2. SELECT DISTINCT * FROM (SELECT DISTINCT DAY("292269055-12-03 00:47:04")  FROM  t1 RIGHT ANTI JOIN (SELECT t3.c_3_0, t3.c_3_1 FROM t3 WHERE true) subt3 ON t1.c_1_2 = subt3.c_3_1 AND t1.c_1_2 >= subt3.c_3_1 AND t1.c_1_4 > subt3.c_3_0 AND 46518.0 = subt3.c_3_0 WHERE true UNION ALL SELECT DISTINCT DAY("292269055-12-03 00:47:04")  FROM  t1 RIGHT ANTI JOIN (SELECT t3.c_3_0, t3.c_3_1 FROM t3 WHERE true) subt3 ON t1.c_1_2 = subt3.c_3_1 AND t1.c_1_2 >= subt3.c_3_1 AND t1.c_1_4 > subt3.c_3_0 AND 46518.0 = subt3.c_3_0 WHERE (NOT (true)) UNION ALL SELECT DISTINCT DAY("292269055-12-03 00:47:04")  FROM  t1 RIGHT ANTI JOIN (SELECT t3.c_3_0, t3.c_3_1 FROM t3 WHERE true) subt3 ON t1.c_1_2 = subt3.c_3_1 AND t1.c_1_2 >= subt3.c_3_1 AND t1.c_1_4 > subt3.c_3_0 AND 46518.0 = subt3.c_3_0 WHERE ((true) IS NULL)) t;

crash.log:
tcmalloc: large alloc 1073741824 bytes == 0xb70f8000 @  0x4d16659 0x4e9405c 0x4e943be 0x1cc2c99 0x1ca907d 0x1c54fd3 0x1c18967 0x20f6d38 0x2183038 0x21b9f2c 0x1c81bda 0x1c83575 0x1c84147 0x1c206d2 0x1c24b7c 0x1d49bb9 0x1d45778 0x7f8c89527e65
*** Aborted at 1641818427 (unix time) try "date -d @1641818427" if you are using GNU date ***
PC: @          0x21c8eb2 starrocks::vectorized::AggHashSetOfOneNumberKey<>::build_set()
*** SIGSEGV (@0x222cb8000) received by PID 32313 (TID 0x7f8c3f56f700) from PID 583761920; stack trace: ***
    @          0x342f6c2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f8c8952f5f0 (unknown)
    @          0x21c8eb2 starrocks::vectorized::AggHashSetOfOneNumberKey<>::build_set()
    @          0x21b8f2a starrocks::vectorized::DistinctStreamingNode::get_next()
    @          0x1c81bda starrocks::PlanFragmentExecutor::_get_next_internal_vectorized()
    @          0x1c83575 starrocks::PlanFragmentExecutor::_open_internal_vectorized()
    @          0x1c84147 starrocks::PlanFragmentExecutor::open()
    @          0x1c206d2 starrocks::FragmentExecState::execute()
    @          0x1c24b7c starrocks::FragmentMgr::exec_actual()
    @          0x1d49bb9 starrocks::ThreadPool::dispatch_thread()
    @          0x1d45778 starrocks::Thread::supervise_thread()
    @     0x7f8c89527e65 start_thread
    @     0x7f8c8892c88d __clone
    @                0x0 (unknown)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - main Release
 - mysql> select current_version();
+---------------------------------+
| current_version()               |
+---------------------------------+
| SQLANCER_BRANCH_RELEASE d92cde3 |
+---------------------------------+

**Comment by stdpain** [comment]
```
| PLAN FRAGMENT 2(F00)                                                                                                                                                                                                                  |
|                                                                                                                                                                                                                                       |
|   Input Partition: RANDOM                                                                                                                                                                                                             |
|   OutPut Partition: HASH_PARTITIONED: 46: day                                                                                                                                                                                         |
|   OutPut Exchange Id: 18                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                       |
|   17:AGGREGATE (update serialize)                                                                                                                                                                                                     |
|   |  STREAMING                                                                                                                                                                                                                        |
|   |  group by: [46: day, TINYINT, false]                                                                                                                                                                                              |
|   |  cardinality: 0                                                                                                                                                                                                                   |
|   |  column statistics:                                                                                                                                                                                                               |
|   |  * day-->[-Infinity, Infinity, 0.0, 1.0, 1.0] UNKNOWN                                                                                                                                                                             |
|   |                                                                                                                                                                                                                                   |
|   0:UNION                                                                                                                                                                                                                             |
|   |  child exprs:                                                                                                                                                                                                                     |
|   |      [15, TINYINT, true]                                                                                                                                                                                                          |
|   |      [30, TINYINT, false]                                                                                                                                                                                                         |
|   |      [45, TINYINT, false]                                                                                                                                                                                                         |
|   |  pass-through-operands: all                                                                                                                                                                                                       |
|   |  cardinality: 0                                                                                                                                                                                                                   |
|   |  column statistics:                                                                                                                                                                                                               |
|   |  * day-->[-Infinity, Infinity, 0.0, 1.0, 1.0] UNKNOWN                                                                                                                                                                             |
|   |                                                                                                                                                                                                                                   |
|   |----13:EXCHANGE                                                                                                                                                                                                                    |
|   |       cardinality: 0                                                                                                                                                                                                              |
|   |                                                                                                                                                                                                                                   |
|   |----16:EXCHANGE                                                                                                                                                                                                                    |
|   |       cardinality: 0                                                                                                                                                                                                              |
|   |                                                                                                                                                                                                                                   |
|   10:EXCHANGE                                                                                                                                                                                                                         |
|      cardinality: 0
```

exec_node 17 was no-nullable
but child 15 was nullable
