### ISSUE TITLE
jdk11 causes fe  unable to write to the fe.log log file

### ISSUE THREAD

**Issue by gdbcode** [StarRocks/starrocks#27650]
### Steps to reproduce the behavior (Required)
1. docker pull starrocks/fe-ubuntu:2.5.9
2. docker run -it starrocks/fe-ubuntu:2.5.9 bash
3. export STARROCKS_HOME=/opt/starrocks/fe
4. cd /opt/starrocks/fe
5. bin/start_fe.sh --daemon
6. cat log/fe.log

### Expected behavior (Required)
![image](https://github.com/StarRocks/starrocks/assets/27483527/c6acc42e-a7eb-4695-91cf-37b1ecc8f000)
lots of lines

### Real behavior (Required)
![image](https://github.com/StarRocks/starrocks/assets/27483527/bf73dcc5-9a6a-452e-ac65-fa36a4f7c7ed)
only two lines

### StarRocks version (Required)
 -  2.5.9

**Comment by kevincai** [comment]
possibly something to do with slf42j version upgrade.

**Comment by kevincai** [comment]
suspicious commit: [dfb89fada40a8d5eeadfc5c20c6899289705acf8](https://github.com/StarRocks/starrocks/commit/dfb89fada40a8d5eeadfc5c20c6899289705acf8)

**Comment by gengjun-git** [comment]
I have found the reason, PR is on the way.

**Comment by gdbcode** [comment]
![image](https://github.com/StarRocks/starrocks/assets/27483527/93f79e68-63e8-491f-93be-51201c1cac8f)

**Comment by gdbcode** [comment]
i had patched https://github.com/StarRocks/starrocks/pull/27671 to tag2.5.9，still have some issues

**Comment by gdbcode** [comment]
> i had patched #27671 to tag2.5.9，still have some issues ![image](https://user-images.githubusercontent.com/27483527/255063591-87941f11-85e5-4927-963a-a44820fd4862.png)

using LogManager replace LoggerFactory in PluginInfo.java file，still has  some issues in jdk11 env
  
![image](https://github.com/StarRocks/starrocks/assets/27483527/f55d7761-d4a9-47b1-91dd-237d0b852fea)

**Comment by gengjun-git** [comment]
https://github.com/StarRocks/starrocks/pull/27852 把这个加上试试呢

**Comment by gdbcode** [comment]
> #27852 把这个加上试试呢

![image](https://github.com/StarRocks/starrocks/assets/27483527/358971a7-4834-4379-96b3-bec951cc31e4)
