### ISSUE TITLE
 1.2.6_flink和 1.2.7_flink就一致报错  1.2.5_flink就可以正常写入

### ISSUE THREAD

**Issue by Leexinmao** [StarRocks/starrocks#27686]
flink写sr的依赖中， 1.2.6_flink和 1.2.7_flink就一致报错  1.2.5_flink就可以正常写入，报错原因：
"status": "TXN NOT_EXISTS"
"Message": "transaction with label xxxxxxxxxxxxxxxxxx not exists"

**Comment by banmoy** [comment]
@Leexinmao Could you post the configuration of connector? Or if you are convenient, we can chat offline via wechat or other tools so that I can get more details

**Comment by Leexinmao** [comment]
SinkFunction<String> sink = StarRocksSink.sink(
                StarRocksSinkOptions.builder()
                        .withProperty("jdbc-url", jdbcUrl)
                        .withProperty("load-url", loadUrl)
                        .withProperty("username", userName)
                        .withProperty("password", password)
                        // sink_sr_table_name
                        //sink_sr_database
                        .withProperty("database-name", database)
                        .withProperty("table-name", tableName) 
                        .withProperty("sink.properties.format", "json")
                        .withProperty("sink.properties.strip_outer_array", "true")
                        .withProperty("sink.properties.max_filter_ratio", "0.1") 
                        .withProperty("sink.buffer-flush.max-bytes", "67108864")
                        .withProperty("sink.buffer-flush.interval-ms", "5000")
                        .withProperty("sink.buffer-flush.max-rows", "64000")
                        .withProperty("sink.properties.column_separator", "\\x01")
                        .withProperty("sink.properties.row_delimiter", "\\x02")
                        .build()
        );

**Comment by banmoy** [comment]
Could you search the label in both flink taskmanager log and StarRocks FE leader log, and send me the result?
