### ISSUE TITLE
Support reading external hudi table

### ISSUE THREAD

**Issue by miomiocat** [StarRocks/starrocks#2772]
Hudi is a rich platform to build streaming data lakes with incremental data pipelines on a self-managing database layer, while being optimized for lake engines and regular batch processing. 
We should give more abilities to Starrocks in data lake analytics scenario. 

Here is a parent issue for work plan about reading hudi data as a external table like hive.
- [x] read copy on write table
- [x] read merge on read table
- [x] get table statistics for CBO
- [ ] incremental query
- [ ] history version query
- [ ] get table meta from file system
- [ ] support metadata table
- [ ] decouple from hive metastore

@imay @dirtysalt @DorianZheng @caneGuy @Ielihs

**Comment by DorianZheng** [comment]
@miomiocat This is an exciting feature. Do you have some project milestone?

**Comment by miomiocat** [comment]
> @miomiocat This is an exciting feature. Do you have any project milestone or roadmap?

Full feature support will be divided into 3 milestones and implemented in the following order:
1.  support copy on write table
2.  support copy on write table
3.  support hadoop catalog

**Comment by caneGuy** [comment]
> > @miomiocat This is an exciting feature. Do you have any project milestone or roadmap?
> 
> Full feature support will be divided into 3 milestones and implemented in the following order:
> 
> 1. support copy on write table
> 2. support copy on write table
> 3. support hadoop catalog

1 and 2 is the same? may be you mean '2. support mor table'? right?  @miomiocat

**Comment by miomiocat** [comment]
> > > @miomiocat This is an exciting feature. Do you have any project milestone or roadmap?
> > 
> > 
> > Full feature support will be divided into 3 milestones and implemented in the following order:
> > 
> > 1. support copy on write table
> > 2. support copy on write table
> > 3. support hadoop catalog
> 
> 1 and 2 is the same? may be you mean '2. support mor table'? right? @miomiocat

yes, sorry for typo

**Comment by dujl** [comment]
what's the feature support hadoop catalog? Does it mean support hudi table that meta is stored in hadoop?

**Comment by miomiocat** [comment]
> what's the feature support hadoop catalog? Does it mean support hudi table that meta is stored in hadoop?
Thank you for your attention.

Currently, Starrocks obtains all of table/partition statistics from hive metastore to do CBO tasks for Hive/Hudi external table and there are no APIs to extract related statistics in hudi like iceberg.

The term of `hadoop catalog` is more like iceberg's, We hope starrocks can read external table efficiently without external meta system like hive metastore to make the whole data lake framework more general.

Welcome to participate in community building of Starrocks and we can discuss more about this topic.
