### ISSUE TITLE
[CLOUD_NATIVE] Cache data not deleted when execute `drop table force` stmt

### ISSUE THREAD

**Issue by wxl24life** [StarRocks/starrocks#27736]
### Steps to reproduce the behavior (Required)

Create some cloud_native table with default cache settings, load data into the table, then execute `drop table xx force`

### Expected behavior (Required)

1. remote object storage table path deleted
2. local disk cache deleted

### Real behavior (Required)

1. [done] remote object storage table path deleted
2. local disk cache not fully deleted, only a small fraction of disk space released.

Before drop the table...
![image](https://github.com/StarRocks/starrocks/assets/3615043/37936438-abf0-4a8f-9832-6a4b4714f2b0)

After drop the table...
![image](https://github.com/StarRocks/starrocks/assets/3615043/e4d063f0-6843-4752-b6ef-1ad2fcefd659)

ON be node, I can find data directory remains there on storage/starlet_cache path..

### StarRocks version (Required)

Latest version build from main branch on 07-20.

**Comment by wxl24life** [comment]
@sduzh please take your time to review this issue, thanks

**Comment by sduzh** [comment]
Yes, you're right, with the current implementation, dropping a table does not guarantee that all cache files on the local disk will be deleted. This is because, with the current cache implementation, there is no straightforward way to determine which table a cache file on disk belongs to.

**Comment by wxl24life** [comment]
> Yes, you're right, with the current implementation, dropping a table does not guarantee that all cache files on the local disk will be deleted. This is because, with the current cache implementation, there is no straightforward way to determine which table a cache file on disk belongs to.

Thanks for your explanation:-)  

Two more questions:
1) Did you have any plan to solve this problem?  Since it would introduce unnecessary local disk cost. 
2) For current implementation, will the cache files of dropped tables be deleted when cache TTL time reached?

**Comment by sduzh** [comment]
> 

We do have plans to work on this optimization, but to be honest it is not high on our priority list right now. So we don't have a specific timeline for it at the moment. Also, there is no longer a TTL in place, so deletion based on TTL will not happen.

**Comment by sduzh** [comment]
> > Yes, you're right, with the current implementation, dropping a table does not guarantee that all cache files on the local disk will be deleted. This is because, with the current cache implementation, there is no straightforward way to determine which table a cache file on disk belongs to.
> 
> Thanks for your explanation:-)
> 
> Did you have any plan to solve this problem? Since it would introduce unnecessary local disk cost. For current implementation, will the cache files of dropped tables be deleted when cache TTL time reached?

We do have plans to work on this optimization, but to be honest it is not high on our priority list right now. So we don't have a specific timeline for it at the moment. Also, there is no longer a TTL in place, so deletion based on TTL will not happen.
