### ISSUE TITLE
Remove class PackedInt128

### ISSUE THREAD

**Issue by stdpain** [StarRocks/starrocks#2774]
PackedInt128 is used to avoid the segment fault caused by using the aligned SSE instruction load16byte memory, and we can replace this class with unaligned_load entirely.

unaligned_access file path: be/src/util/unaligned_access.h
packed int128 file path: be/src/util/types.h

use unaligned_load<int128_t> instead of reinterpret_cast<const PackedInt128*>(value) 
eg:
```c++
int128_t tmp = unaligned_load<int128_t>(src);
unaligned_store<int128_t>(dst, tmp);
// instead of
*reinterpret_cast<PackedInt128*>(dst) = *reinterpret_cast<const PackedInt128*>(value);
```

**Comment by manahshetty** [comment]
I'm new to contributing to Open Source but I would like to try and solve this issue.

**Comment by stdpain** [comment]
@manahshetty Thank you, I'll assign to you
