### ISSUE TITLE
Using 3.1 rc01, aws s3 sdk ssl will failed

### ISSUE THREAD

**Issue by Smith-Cruise** [StarRocks/starrocks#27766]
It will report the below error in BE
```sql
ERROR 1064 (HY000): code=-1(SdkErrorType:99), message=curlCode: 77, Problem with the SSL CA cert (path? access rights?): file = s3://xxxx/44c2e57b-d1ed-4a44-af62-9169c7e59e77/89bf7394-a607-4321-bc20-cfbd35315c7c/data/2664b7de-084e-11ee-a3d8-024220ff6397_0_1.parquet
```

The reason like this https://github.com/aws/aws-sdk-cpp/issues/1491

If I compile SR in Ubuntu 22, it works.

### StarRocks version (Required)
3.1 rc01

**Comment by kevincai** [comment]
this is not the aws sdk issue, it is the curl/openssl compiled with different default CA location on different linux distro that causes the issue. Currently there is no good way to solve this problem but use the binary that built from the specific platform. That is, our CentOS binary only works on RH related distribution and for Ubuntu/debian series, the binary needs a rebuilt.

**Comment by kevincai** [comment]
or we have to patch curl library ourselves.

**Comment by kevincai** [comment]
#23506

**Comment by Smith-Cruise** [comment]
Do we have a plan to publish different sr binary for different Linux distro?

**Comment by kevincai** [comment]
> Do we have a plan to publish different sr binary for different Linux distro?

we have provided different binaries for different distro in docker image, but not in the official download link.
