### ISSUE TITLE
Fail to "select * from events;" 

### ISSUE THREAD

**Issue by imay** [StarRocks/starrocks#278]
### Steps to reproduce the behavior (Required)

1. `use information_schema;`

2. `select * from events;`

### Expected behavior (Required)

return content from events.

### Real behavior (Required)

```
mysql>  select * from events;
ERROR 1064 (HY000): no match column for this column.
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

current master 04acb23

**Comment by starrocks-xueli** [comment]
this can be closed.
