### ISSUE TITLE
Materialized view partitions are refreshed repeatedly

### ISSUE THREAD

**Issue by gdbcode** [StarRocks/starrocks#27914]
### Steps to reproduce the behavior (Required)
1. CREATE MATERIALIZED VIEW `xxxxx`
COMMENT "MATERIALIZED_VIEW"
PARTITION BY (`dt`)
DISTRIBUTED BY HASH(`id`) BUCKETS 3
REFRESH ASYNC START("2023-07-24 19:19:00") EVERY(INTERVAL 10 MINUTE)
PROPERTIES (
"replication_num" = "3",
"storage_medium" = "HDD",
"auto_refresh_partitions_limit" = "5",
"partition_refresh_number" = "1",
"excluded_trigger_tables" = ""
)
AS SELECT '......'

### Expected behavior (Required)
The history partition is only refreshed once
### Real behavior (Required)
![image](https://github.com/StarRocks/starrocks/assets/27483527/8b4904a7-1109-44d3-b95f-9aa9b0441cb7)
![image](https://github.com/StarRocks/starrocks/assets/27483527/c09b4f88-20a5-4c57-92b5-9f10c236e879)

History partition refreshed multiple times，lots of pending tasks

### StarRocks version (Required)
 - 2.5.6

**Comment by jaogoy** [comment]
@gdbcode Is it not a problem?
