### ISSUE TITLE
Query fails with No matching function with signature: array_map(function, array<datetime>, array<boolean>)

### ISSUE THREAD

**Issue by rcauble** [StarRocks/starrocks#27936]
[bug-repro.zip](https://github.com/StarRocks/starrocks/files/12166209/bug-repro.zip)

### Steps to reproduce the behavior (Required)
1. Download the attachment and name as bug-repro.zip
2. unzip bug-repro.zip 
3. cd bug-repro
4. ./bug.sh

### Expected behavior (Required)
Should run without error.

### Real behavior (Required)
You'll get an error message No matching function with signature: array_map(function, array<datetime>, array<boolean>). But if you look at the SQL we never actually invoke a function with that signature.

### StarRocks version (Required)
starrocks/allin1-ubuntu:3.1.0-rc01

**Comment by fzhedu** [comment]
as array_filter is based on `array_map`, and related code was changed, so this error came. simpley reproduce
```
select array_map((x,y)->((x is null) and (y is null)), [true], [[1]]);
```
will fixed by https://github.com/StarRocks/starrocks/pull/27963
