### ISSUE TITLE
When displaying the specific information of resource and catalog, the sensitive password information is not hidden

### ISSUE THREAD

**Issue by 0xqq** [StarRocks/starrocks#27976]
### Steps to reproduce the behavior (Required)
SHOW CREATE CATALOG  
SHOW RESOURCES

### Expected behavior (Required)
When displaying the specific information of resource and catalog, the sensitive password information is not hidden
### Real behavior (Required)
the sensitive password information is  hidden
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
SR3.X

**Comment by letian-jiang** [comment]
AK/SK is currently masked in 3.X versions.

Could you please provide more details? A snapshot with password masked would be best.

**Comment by 0xqq** [comment]
SHOW CREATE CATALOG catalog_pg 

CREATE EXTERNAL CATALOG `catalog_pg`
PROPERTIES ("password"  =  "postgres",
"driver_class"  =  "org.postgresql.Driver",
"checksum"  =  "c422ffa6eb00ea92d11cbff4a7ce27b2",
"driver_url"  =  "file:///bdp/jdbc/postgresql-42.4.0.jar",
"type"  =  "jdbc",
"user"  =  "postgres",
"jdbc_uri"  =  "jdbc:postgresql://XXXX:15432/postgres"
)
