### ISSUE TITLE
1064 - mysql query failed. Err: FUNCTION t6.get_json_string does not exist, Time: 0.208000s

### ISSUE THREAD

**Issue by Ink00Bamboo** [StarRocks/starrocks#2811]
**DESC**:  
    I create mysql outside table data_analysis.ods_mysql_vms_metadata_content  ;the table in mysql is in t6 database.
    run the sql `SELECT  id
          FROM  data_analysis.ods_mysql_vms_metadata_content
          WHERE get_json_string(content, '$.content_column_3') IS NOT NULL`   then get the error msg like title；
  but if i change the sql like this `        SELECT  id
          FROM  data_analysis.ods_mysql_vms_metadata_content
          WHERE get_json_string(content, '$.content_column_3') != NULL`   is run success.

**analyze**：
    the first sql by optimized and `WHERE get_json_string(content, '$.content_column_3') IS NOT NULL` predicate push down in mysql running to return smaller data to starRocks, but mysql not have get_json_string function so it`s running error。however  use 
`WHERE get_json_string(content, '$.content_column_3') != NULL` it`s running in starRocks so it`s surccess.

**result**
    some mysql don`t have function not should predicate push down to mysql。

thanks，my first issue.

**Comment by kangkaisen** [comment]
We will fix this issue.
