### ISSUE TITLE
flink-starrocks-connector 有计划支持 catalog么

### ISSUE THREAD

**Issue by zouchangzhen** [StarRocks/starrocks#28180]

**Comment by Dshadowzh** [comment]
Yes. we have a pr https://github.com/StarRocks/starrocks-connector-for-apache-flink/pull/175, still working on to merge this.

**Comment by zouchangzhen** [comment]
> Yes. we have a pr [StarRocks/starrocks-connector-for-apache-flink#175](https://github.com/StarRocks/starrocks-connector-for-apache-flink/pull/175), still working on to merge this.

这样创建catalog语句么？
CREATE CATALOG doris_catalog WITH(
      'type' = 'starrocks-catalog',
      'jdbc-url' = 'jdbc:mysql://*:9030,*:9030,*:9030',
      'default-database' = '@',
      'database-name' = '@',
      'username' = '@',
       'table-name' = '@',
      'password' = '@'
);
为什么还要table-name呢

**Comment by zouchangzhen** [comment]
catalog 好像不支持主键模型？
 insert into sink_sr.sdp_test.sink_test_zj/*+ OPTIONS( 'sink.parallelism' = '3','sink.properties.partial_update' = 'true','sink.properties.columns' = 'f_sequence,f_random,f_random_str,__op') */(f_sequence,f_random,f_random_str,ts) select f_sequence,f_random,concat('testcatalog20230808sdp',f_random_str),ts from source_kafka <<< java.lang.IllegalArgumentException: Primary keys not defined in the sink `TableSchema`. at com.starrocks.connector.flink.manager.StarRocksSinkTable.validateTableStructure(StarRocksSinkTable.java:83) at com.starrocks.connector.flink.table.sink.StarRocksDynamicSinkFunctionV2.<init>(StarRocksDynamicSinkFunctionV2.java:70) at com.starrocks.connector.flink.table.sink.SinkFunctionFactory.createSinkFunction(SinkFunctionFactory.java:156) at com.starrocks.connector.flink.table.sink.StarRocksDynamicTableSink.getSinkRuntimeProvider(StarRocksDynamicTableSink.java:44) at org.apache.flink.table.planner.plan.nodes.exec.common.CommonExecSink.createSinkTransformation(CommonExecSink.java:149) at org.apache.flink.table.planner.plan.nodes.exec.stream.StreamExecSink.translateToPlanInternal(StreamExecSink.java:176) at org.apache.flink.table.planner.plan.nodes.exec.ExecNodeBase.translateToPlan(ExecNodeBase.java:158) at
