### ISSUE TITLE
Not showing password on show resouces

### ISSUE THREAD

**Issue by 0xqq** [StarRocks/starrocks#28230]
### Steps to reproduce the behavior (Required)
show resources
### Expected behavior (Required)
password not mask
![image](https://github.com/StarRocks/starrocks/assets/16940356/ca04cd05-1563-4944-abbd-e10ac3eb7cb5)

### Real behavior (Required)
 not show password
### StarRocks version (Required)
SR3.X

**Comment by Dshadowzh** [comment]
Yes, it should be masked. 
But JDBC external table is to be deprecated, JDBC catalog is recommended.

**Comment by 0xqq** [comment]
Currently, the jdbc catalog only supports mysql pg, others JDBC external table。

**Comment by letian-jiang** [comment]
Please use JDBC catalog :) 

You may open another issue if it doesn't fit your need.

**Comment by kevincai** [comment]
@letian-jiang
