### ISSUE TITLE
[cleanup] Some unused files can be deleted

### ISSUE THREAD

**Issue by stdpain** [StarRocks/starrocks#2825]
* be/test/runtime/string_buffer_test.cpp
* be/src/runtime/string_buffer.hpp
* be/src/util/types.h

**Comment by Ccuurryy** [comment]
ok，here

**Comment by Ccuurryy** [comment]
Already push branch

**Comment by imay** [comment]
@Ccuurryy Thanks for your contribution. I will assign this issue for you.
