### ISSUE TITLE
hive catalog CSV

### ISSUE THREAD

**Issue by YannngHQ** [StarRocks/starrocks#28275]
table format:
CREATE EXTERNAL TABLE db.name(
  `a` string COMMENT 'from deserializer', 
  `b` string COMMENT 'from deserializer', 
  `c` string COMMENT 'from deserializer')
PARTITIONED BY ( 
  `dt` string)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
WITH SERDEPROPERTIES ( 
  'escapeChar'='\\', 
  'quoteChar'='"', 
  'separatorChar'=',', 
  'serialization.encoding'='GBK') 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
 'xxx'

If the create table statement is specified like this, the specifications of separatorChar and quoteChar do not take effect. Version: 3.1.

**Comment by jaogoy** [comment]
@YannngHQ you create external in Hive or StarRocks?
