### ISSUE TITLE
Query sql crash in ASAN mode

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#2828]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS d2;
CREATE DATABASE d2;
USE d2;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DECIMAL128(3, 1)  NULL ,c_0_1 DECIMAL32(3, 2)  NOT NULL ) UNIQUE KEY (c_0_0) DISTRIBUTED BY HASH (c_0_0) properties("replication_num"="1") ;
CREATE TABLE t1 (c_1_0 DATE NOT NULL ,c_1_1 DATETIME NULL ,c_1_2 DECIMAL64(6, 0)  NULL ,c_1_3 DECIMAL(1, 0)  NOT NULL ,c_1_4 DECIMAL128(29, 5)  NOT NULL ,c_1_5 DECIMAL64(13, 9)  NULL ,c_1_6 DECIMAL(2, 0)  NOT NULL ,c_1_7 DECIMAL64(8, 8)  NOT NULL ,c_1_8 DOUBLE NULL ,c_1_9 FLOAT NULL ,c_1_10 DECIMAL64(6, 4)  NULL ,c_1_11 FLOAT NULL ) DUPLICATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4) DISTRIBUTED BY HASH (c_1_2) properties("replication_num"="1") ;
CREATE TABLE IF NOT EXISTS t2 (c_2_0 DECIMAL(19, 7)  NOT NULL ,c_2_1 BOOLEAN NOT NULL ,c_2_2 BIGINT NOT NULL ,c_2_3 LARGEINT NOT NULL ,c_2_4 DATE NOT NULL ,c_2_5 BOOLEAN NOT NULL ,c_2_6 DECIMAL64(6, 2)  NULL ,c_2_7 SMALLINT NULL ,c_2_8 DECIMAL128(30, 4)  NOT NULL ,c_2_9 FLOAT NOT NULL ,c_2_10 DOUBLE NOT NULL ,c_2_11 DECIMAL64(14, 4)  NOT NULL ,c_2_12 FLOAT NULL ,c_2_13 VARCHAR(11) NULL ,c_2_14 DECIMAL32(6, 4)  NULL ,c_2_15 DECIMAL64(12, 7)  NULL ) UNIQUE KEY (c_2_0,c_2_1,c_2_2,c_2_3,c_2_4) DISTRIBUTED BY HASH (c_2_2,c_2_0,c_2_3) properties("replication_num"="1") ;
CREATE TABLE t3 (c_3_0 DECIMAL128(28, 9)  NULL ,c_3_1 CHAR(1) NOT NULL ,c_3_2 CHAR(21) NOT NULL ,c_3_3 DECIMAL128(22, 10)  NULL ,c_3_4 DECIMAL(3, 0)  NULL ,c_3_5 CHAR(21) NOT NULL ,c_3_6 DECIMAL(18, 4)  NOT NULL ) DUPLICATE KEY (c_3_0,c_3_1,c_3_2,c_3_3,c_3_4) DISTRIBUTED BY HASH (c_3_2) properties("replication_num"="1") ;
INSERT INTO t3 VALUES (9223785158.771303155, "", "jE", 32.2902913133, 429, "", 3472092368.8597), (8496200003.043317501, "", "F2", NULL, 286, "MQY", 4342800411.2927), (1480603055.516799883, "", "t", 31.2896217541, 457, "31Lp", 7812885330.1899);
INSERT INTO t2 VALUES (39916.1958179, false, -334098922, 323866762, "1970-01-01", false, NULL, 11, 1714382003675869459158.3212, 3.23866762E8, 0.7432024664598944, 400310.9895, 0.7432024664598944, "o8kLsWA", 0.0014, 0.0070835);
INSERT INTO t2 VALUES (11458.2407204, false, 323866762, -334098922, "1970-01-01", false, 54.04, NULL, 6853198609400810159542.0621, -3.34098922E8, 0.7975282382227781, 516194.4459, 0.7386134785618869, "", 0.0081, NULL), (69732.3224605, false, 1077975482, 2037548206, "1970-01-01", true, NULL, NULL, 8853658313184343153778.8546, 0.3763691161210567, 0.08490738538555498, 414799.0118, 0.40152325710820014, "s", 0.0011, 0.0089848);
INSERT INTO t3 VALUES (9101678747.697600972, "", "", 54.6384726974, 741, "G", 2938931453.4822);
INSERT INTO t0 VALUES (6.3, 0.00), (2.5, 0.02);
TRUNCATE TABLE t3;
INSERT INTO t0 VALUES (8.2, 0.01);
INSERT INTO t3 VALUES (6853865770.768970259, "", "Xve", 24.4087794988, 947, "", 4390087546.2055), (8785901189.105276348, "", "", 15.0020045197, NULL, "", 5053859104.9858), (NULL, "", "pqTo1", 84.2673318149, 58, "4t", 7617476147.3744);
INSERT INTO t0 VALUES (2.9, 0.04);
INSERT INTO t2 VALUES (84355.6448564, false, 365379798, 1749928692, "1970-01-01", true, NULL, 15, 8178322711071197570475.9884, 0.563707577296722, 0.2311984751021786, 387423.5114, NULL, "", 0.0088, 0.0083228), (90368.5229107, false, 879736935, -774669080, "1970-01-01", true, 50.69, 2, 6207888493479407632236.1895, -7.7466908E8, 3.65379798E8, 692518.8434, NULL, NULL, 0.0038, 0.0040327);
DELETE FROM t0 WHERE c_0_0=9.8;
2.  SELECT DISTINCT * FROM (SELECT DISTINCT CASE  WHEN false THEN subt3.c_3_0  WHEN false THEN subt3.c_3_0 END FROM  (SELECT t1.c_1_0, t1.c_1_1, t1.c_1_2, t1.c_1_3, t1.c_1_4, t1.c_1_5, t1.c_1_6, t1.c_1_7, t1.c_1_8, t1.c_1_9, t1.c_1_10, t1.c_1_11 FROM t1) subt1 RIGHT ANTI JOIN (SELECT t3.c_3_0, t3.c_3_1, t3.c_3_2, t3.c_3_3, t3.c_3_4, t3.c_3_5, t3.c_3_6 FROM t3) subt3 ON subt1.c_1_10 = subt3.c_3_6 AND subt1.c_1_10 >= subt3.c_3_6 AND subt1.c_1_4 != subt3.c_3_6 AND subt1.c_1_4 <= subt3.c_3_6 WHERE false UNION ALL SELECT DISTINCT CASE  WHEN false THEN subt3.c_3_0  WHEN false THEN subt3.c_3_0 END FROM  (SELECT t1.c_1_0, t1.c_1_1, t1.c_1_2, t1.c_1_3, t1.c_1_4, t1.c_1_5, t1.c_1_6, t1.c_1_7, t1.c_1_8, t1.c_1_9, t1.c_1_10, t1.c_1_11 FROM t1) subt1 RIGHT ANTI JOIN (SELECT t3.c_3_0, t3.c_3_1, t3.c_3_2, t3.c_3_3, t3.c_3_4, t3.c_3_5, t3.c_3_6 FROM t3) subt3 ON subt1.c_1_10 = subt3.c_3_6 AND subt1.c_1_10 >= subt3.c_3_6 AND subt1.c_1_4 != subt3.c_3_6 AND subt1.c_1_4 <= subt3.c_3_6 WHERE (NOT (false)) UNION ALL SELECT DISTINCT CASE  WHEN false THEN subt3.c_3_0  WHEN false THEN subt3.c_3_0 END FROM  (SELECT t1.c_1_0, t1.c_1_1, t1.c_1_2, t1.c_1_3, t1.c_1_4, t1.c_1_5, t1.c_1_6, t1.c_1_7, t1.c_1_8, t1.c_1_9, t1.c_1_10, t1.c_1_11 FROM t1) subt1 RIGHT ANTI JOIN (SELECT t3.c_3_0, t3.c_3_1, t3.c_3_2, t3.c_3_3, t3.c_3_4, t3.c_3_5, t3.c_3_6 FROM t3) subt3 ON subt1.c_1_10 = subt3.c_3_6 AND subt1.c_1_10 >= subt3.c_3_6 AND subt1.c_1_4 != subt3.c_3_6 AND subt1.c_1_4 <= subt3.c_3_6 WHERE ((false) IS NULL)) t;

```
crash.log:
*** Check failure stack trace: ***
    @          0x8dacf1d  google::LogMessage::Fail()
    @          0x8daf1f9  google::LogMessage::SendToLog()
    @          0x8daca99  google::LogMessage::Flush()
    @          0x8daf7f9  google::LogMessageFatal::~LogMessageFatal()
    @          0x5e490bf  starrocks::vectorized::AggHashSetOfOneNumberKey<>::build_set()
    @          0x5e142aa  starrocks::Aggregator::build_hash_set<>()
    @          0x5decb8b  starrocks::vectorized::DistinctBlockingNode::open()
    @          0x4ffa74b  starrocks::PlanFragmentExecutor::_open_internal_vectorized()
    @          0x4ff9e39  starrocks::PlanFragmentExecutor::open()
    @          0x4e78e62  starrocks::FragmentExecState::execute()
    @          0x4e7df2b  starrocks::FragmentMgr::exec_actual()
    @          0x4e7e947  _ZZN9starrocks11FragmentMgr18exec_plan_fragmentERKNS_23TExecPlanFragmentParamsERKSt8functionIFvPNS_20PlanFragmentExecutorEEESA_ENKUlvE_clEv
    @          0x4e87972  _ZSt13__invoke_implIvRZN9starrocks11FragmentMgr18exec_plan_fragmentERKNS0_23TExecPlanFragmentParamsERKSt8functionIFvPNS0_20PlanFragmentExecutorEEESB_EUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @          0x4e87563  _ZSt10__invoke_rIvRZN9starrocks11FragmentMgr18exec_plan_fragmentERKNS0_23TExecPlanFragmentParamsERKSt8functionIFvPNS0_20PlanFragmentExecutorEEESB_EUlvE_JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESF_E4typeEOSG_DpOSH_
    @          0x4e86d14  _ZNSt17_Function_handlerIFvvEZN9starrocks11FragmentMgr18exec_plan_fragmentERKNS1_23TExecPlanFragmentParamsERKSt8functionIFvPNS1_20PlanFragmentExecutorEEESC_EUlvE_E9_M_invokeERKSt9_Any_data
    @          0x3dc8a64  std::function<>::operator()()
    @          0x526c618  starrocks::FunctionRunnable::run()
    @          0x52690f6  starrocks::ThreadPool::dispatch_thread()
    @          0x5286740  std::__invoke_impl<>()
    @          0x5286023  std::__invoke<>()
    @          0x528543a  _ZNSt5_BindIFMN9starrocks10ThreadPoolEFvvEPS1_EE6__callIvJEJLm0EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @          0x5283fa6  std::_Bind<>::operator()<>()
    @          0x5280e8c  std::__invoke_impl<>()
    @          0x527ee54  _ZSt10__invoke_rIvRSt5_BindIFMN9starrocks10ThreadPoolEFvvEPS2_EEJEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESA_E4typeEOSB_DpOSC_
    @          0x527a5ef  std::_Function_handler<>::_M_invoke()
    @          0x3dc8a64  std::function<>::operator()()
    @          0x52537f5  starrocks::Thread::supervise_thread()
    @     0x7f3f458f9e65  start_thread
    @     0x7f3f44cfe88d  __clone
    @              (nil)  (unknown)

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - main ASAN
 - mysql> select current_version();
+------------------------------+
| current_version()            |
+------------------------------+
| SQLANCER_MASTER_ASAN 328c8c4 |
+------------------------------+

**Comment by stdpain** [comment]
mini reproduce case:
```
select count(*) from (select 1 as c1 union all select null as c1) t group by t.c1;
```

**Comment by stdpain** [comment]
```
|                                                                                       |
|   5:Project                                                                           |
|   |  <slot 7> : 6: c_0_0 + 2                                                          |
|   |                                                                                   |
|   0:UNION                                                                             |
|   |                                                                                   |
|   |----4:EXCHANGE                                                                     |
|   |                                                                                   |
|   2:EXCHANGE
```

dst_type for NULL was TYPE_BOOLEAN, Union node will return a Nullable(UInt8Column), which will cause a wrong cast
