### ISSUE TITLE
Add try catch exception at the  entrance of the executor thread

### ISSUE THREAD

**Issue by trueeyu** [StarRocks/starrocks#283]
## Enhancement

std::vector emplace_back may throw bad_alloc exception. If the exception is not thrown frequently, in fact, catch exception has no effect on performance. Actually tested it, and it really has no effect on performance. We can consider adding try catch exception at the entrance of the executor.

https://dev.to/visheshpatel/the-real-cost-of-exception-handling-in-c-with-benchmark-kd
https://pspdfkit.com/blog/2020/performance-overhead-of-exceptions-in-cpp/

**Comment by sduzh** [comment]
In addition to performance considerations, [exception safety](https://en.wikipedia.org/wiki/Exception_safety) must also be considered when handling exceptions. I don't think our code is exception-safe, or at least not strictly verified

**Comment by xuzifu666** [comment]
this issue resovled?

**Comment by trueeyu** [comment]
> this issue resovled?

Not resolved yet

**Comment by trueeyu** [comment]
> In addition to performance considerations, [exception safety](https://en.wikipedia.org/wiki/Exception_safety) must also be considered when handling exceptions. I don't think our code is exception-safe, or at least not been strictly verified

This should be considered
