### ISSUE TITLE
When there is only 1 BE, create table should automatically add "replication_num" = "1",

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#28330]
It's hard for people to remember how many BEs they have.   Why not make it easier that if the user has only 1 BE, don't give the error message and just create a table with 

```
"replication_num" = "1",
```

**Comment by imay** [comment]
A good suggestion, if there is only one backend we can downgrade to create a table with one replica.

**Comment by alberttwong** [comment]
ADMIN SET FRONTEND CONFIG ('default_replication_num' ="1");
