### ISSUE TITLE
Telnet 9030 returns banner: mysql/5.1.0, can the banner information of mysql be blocked through the configuration information?

### ISSUE THREAD

**Issue by ghost** [StarRocks/starrocks#28371]

**Comment by kevincai** [comment]
what type of information are you referring?

when a TCP connection is setup to FE TCP/9030, FE will respond with information negotiating the connection setup, this is part of the mysql protocol.

what the purpose of probing tcp/9030 with telnet? if for liveness check, suggest turn to `http://<FE_IP>:8030/api/health`

**Comment by autoing** [comment]
The scanner of the security company obtains the banner information of port 9030, gets the banner information mysql/5.1.0, and then gives the vulnerability information of mysql, I want to set or cancel the banner information of mysql/5.1.0 to achieve the purpose of avoiding the vulnerability

**Comment by kevincai** [comment]
I see, probably needs to enable ssl encryption to mysql query port, to enforce the security policy.
