### ISSUE TITLE
date_format 函数问题

### ISSUE THREAD

**Issue by yqzdy1207** [StarRocks/starrocks#28484]
SR version : 3.0.2
select date_format(date_sub(current_date(),1),'yyyy-MM');

只是返回了 yyyy-MM、不是期望数据值

**Comment by yqzdy1207** [comment]
select last_day(current_date()); 直接报错了

**Comment by jackqh** [comment]
日期格式必须带%，示例：select date_format(date_sub(current_date(),1),'%Y-%m');

**Comment by jaogoy** [comment]
> select last_day(current_date()); 直接报错了

Give more information please. It's correct for me.

And, so it's not a problem for the issue?
