### ISSUE TITLE
multi-segment only supported by pure upsert/delete, so pure upsert after another operation is illegal

### ISSUE THREAD

**Issue by zouchangzhen** [StarRocks/starrocks#28487]
{
	"Status": "Fail",
	"BeginTxnTimeMs": 0,
	"Message": "multi-segment only supported by pure upsert/delete, so pure upsert after another operation is illegal",
	"NumberUnselectedRows": 0,
	"CommitAndPublishTimeMs": 0,
	"Label": "c9815b6c-ac5a-4807-bfa1-c0ddbf06d1eb",
	"LoadBytes": 67155382,
	"StreamLoadPutTimeMs": 1,
	"NumberTotalRows": 0,
	"WriteDataTimeMs": 537,
	"TxnId": 24056712,
	"LoadTimeMs": 540,
	"ReadDataTimeMs": 84,
	"NumberLoadedRows": 0,
	"NumberFilteredRows": 0
}
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by jaogoy** [comment]
The message isn't friendly enough to let us know the real reason.
