### ISSUE TITLE
startrock in aarch64(arm64)  build fail

### ISSUE THREAD

**Issue by blank-1** [StarRocks/starrocks#2860]
cd starrocks
sh build.sh --help
```
configure: error: in `/root/starrocks/thirdparty/src/protobuf-3.14.0':
configure: error: --with-zlib was given, but no working zlib library was found
See `config.log' for more details
```
### StarRocks version (Required)
- 2.0

**Comment by imay** [comment]
@rickif PTAL

**Comment by rickif** [comment]
It seems that there's something wrong with the zlib building. Could u provide more detail about the failure? The complete log file is better.

**Comment by blank-1** [comment]
[root@dev-vm5 thirdparty]# ls -l /usr/include/ | grep zlib
-rw-r--r--   1 root root  96239  3月 16  2020 zlib.h

**Comment by rickif** [comment]
https://github.com/StarRocks/starrocks/blob/be8455358caaba5e8f9576c41cc126d89bce374b/thirdparty/build-thirdparty.sh#L738
The zlib that the protobuf depends is in the thirdparty of starrocks, not the one installed in the system.
