### ISSUE TITLE
[Doc] need an overview page for data types

### ISSUE THREAD

**Issue by DanRoscigno** [StarRocks/starrocks#28614]
Currently, we point to the bigint datatype page from the loading overview, we should be pointing to an overview page about
supported data types in general.

It would be a better user experience if clicking on a folder in the nav opened an overview page for the topic.  In this example, clicking on `Data Types` should bring up a page containing the content in the `Data type list` page, and the `Data type list` page could be removed from the nav:

<img width="224" alt="image" src="https://github.com/StarRocks/starrocks/assets/25182304/553aef3c-2770-48d3-9595-e1448b6362a7">

@RowenWoo is this something that we can change in the nav please?  I would rather that the readers click on a topic folder and see the folder expand and the page update (right now only the folder expands, the page displayed stays on the previous page viewed)

**Comment by evelynzhaojie** [comment]
we have this overview page https://docs.starrocks.io/en-us/latest/sql-reference/sql-statements/data-types/data-type-list

**Comment by evelynzhaojie** [comment]
yes, maybe one year ago, we thought about adding the overview .md doc to the folder, but our parser does not support this. this may cause an HTML error. i will try this again

**Comment by DanRoscigno** [comment]
I just tried it, it did not work.  I will ask RD.

**Comment by DanRoscigno** [comment]
unstale
