### ISSUE TITLE
routine load 不提交offset

### ISSUE THREAD

**Issue by yuanzhangjun** [StarRocks/starrocks#2862]
发现在某种情况下routine load 不提交offset
问题复现
### Steps to reproduce the behavior (Required)
建表
1. CREATE TABLE `routine_test2` (
`cdate` date NOT NULL COMMENT '分区日期',
`id` varchar(32) NOT NULL,
`create_time` varchar(32) NOT NULL
) ENGINE=OLAP 
PRIMARY KEY(`cdate`,`id`) COMMENT "routine测试表" 
PARTITION BY RANGE (`cdate`) (
    START ("2022-01-10") END ("2022-01-18") EVERY (INTERVAL 1 day)
)
DISTRIBUTED BY HASH(`id`) 
BUCKETS 1
PROPERTIES ( 
    "replication_num" = "1", 
    "in_memory" = "false",
    "dynamic_partition.enable" = "true",
    "dynamic_partition.time_unit" = "DAY",
    "dynamic_partition.start" = "-3",
    "dynamic_partition.end" = "3",
    "dynamic_partition.prefix" = "p",
    "dynamic_partition.buckets" = "1",
    "storage_format" = "DEFAULT"
);
建routine load
2. create routine load routine_routine_test_c2 on routine_test2
columns (id,create_time,cdate=date(create_time)),
WHERE cdate >= date_add(curdate(),-2)
PROPERTIES ( 
    "format"="json", 
    "desired_concurrent_number" = "1", 
    "strip_outer_array" ="true",  
    "json_root"="$.data", 
    "max_batch_interval" = "5", 
    "max_error_number"="1000" 
) 
FROM KAFKA (     
    "kafka_broker_list"= "xxx:9092",     
    "kafka_topic" = "routine_test2",
    "property.group.id" = "starrocks_routine_test_c2",
    "property.kafka_default_offsets" = "OFFSET_BEGINNING"
);

### Expected behavior (Required)
3.kafka 写入数据
"{\"data\":[{\"id\":\"2\",\"create_time\": \"2022-01-14 00:00:00\"}]}"
routine load Progress offset 更新offset ，且kafka consumer offset 也更新 ，并和Progress保持一致
当写入"{\"data\":[{\"id\":\"2\",\"create_time\": \"2022-01-11 00:00:00\"}]}"
数据这where中过滤掉了时
routine load Progress offset 更新offset ，但kafka consumer offset 不会更新 ，和Progress中offset不一致

4.得出结论：routine load where 条件过滤数据时，不会提交offset到kafka

### StarRocks version (Required)
 - 1.19.5 ,1.19.3

**Comment by gengjun-git** [comment]
Thank you, we will fix it in the later version.

**Comment by rickif** [comment]
@gengjun-git please assign this to me.
