### ISSUE TITLE
Deploy and use shared-data StarRocks: Unknown properties

### ISSUE THREAD

**Issue by RYiHui** [StarRocks/starrocks#28660]
### Steps to reproduce the behavior (Required)
fe.conf:

run_model = shared_data
cloud_native_meta_port = 6090
cloud_native_storage_type = HDFS
cloud_native_hdfs_url = hdfs://10.122.33.***:8020/user/sr

be.conf:

starlet_port = 9070
storage_root_path = /data3,medium:ssd

SQL:

CREATE DATABASE cloud_db;
USE cloud_db;
CREATE TABLE IF NOT EXISTS detail_demo (
    recruit_date  DATE           NOT NULL COMMENT "YYYY-MM-DD",
    region_num    TINYINT        COMMENT "range [-128, 127]",
    num_plate     SMALLINT       COMMENT "range [-32768, 32767] ",
    tel           INT            COMMENT "range [-2147483648, 2147483647]",
    id            BIGINT         COMMENT "range [-2^63 + 1 ~ 2^63 - 1]",
    password      LARGEINT       COMMENT "range [-2^127 + 1 ~ 2^127 - 1]",
    name          CHAR(20)       NOT NULL COMMENT "range char(m),m in (1-255) ",
    profile       VARCHAR(500)   NOT NULL COMMENT "upper limit value 65533 bytes",
    ispass        BOOLEAN        COMMENT "true/false"
)
DUPLICATE KEY(recruit_date, region_num)
DISTRIBUTED BY HASH(recruit_date, region_num)
PROPERTIES (
    "enable_storage_cache" = "true",
    "storage_cache_ttl" = "2592000",
    "enable_async_write_back" = "false"
);

### Real behavior (Required)

ERROR 1064 (HY000): Unexpected exception: Unknown properties: {enable_storage_cache=true, storage_cache_ttl=2592000, enable_async_write_back=false}

fe.warn.log:

PROPERTIES (
    "enable_storage_cache" = "true",
    "storage_cache_ttl" = "2592000",
    "enable_async_write_back" = "false"
)) process failed.
com.starrocks.common.DdlException: Unknown properties: {enable_storage_cache=true, storage_cache_ttl=2592000, enable_async_write_back=false}
        at com.starrocks.server.LocalMetastore.createOlapOrLakeTable(LocalMetastore.java:2455) ~[starrocks-fe.jar:?]
        at com.starrocks.server.LocalMetastore.createTable(LocalMetastore.java:814) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.createTable(GlobalStateMgr.java:2275) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.lambda$visitCreateTableStatement$4(DDLStmtExecutor.java:235) ~[starrocks-fe.jar:?]
        at com.starrocks.common.ErrorReport.wrapWithRuntimeException(ErrorReport.java:108) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.visitCreateTableStatement(DDLStmtExecutor.java:234) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.visitCreateTableStatement(DDLStmtExecutor.java:147) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.CreateTableStmt.accept(CreateTableStmt.java:272) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.DDLStmtExecutor.execute(DDLStmtExecutor.java:133) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:1250) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:556) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:349) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:463) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:729) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_131]

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
version：3.0.3

**Comment by RYiHui** [comment]
![image](https://github.com/StarRocks/starrocks/assets/90946052/0335ed3c-0811-4c0e-8084-286f684c7f67)

**Comment by RYiHui** [comment]
![image](https://github.com/StarRocks/starrocks/assets/90946052/505d597c-1e5b-44ed-98bc-cad314b760f4)

**Comment by sduzh** [comment]
Hi @RYiHui , could you please execute "show frontends" and check the "version" column in the result?

The "enable_storage_cache" property was renamed to "datacache.enable" in version 3.1, and the "storage_cache_ttl" attribute was removed since version 3.1.

Therefore, in version 3.1 you can write:
```
properties("datacache.enable"="true")
```

To enable the data cache.

**Comment by RYiHui** [comment]
> Hi @RYiHui , could you please execute "show frontends" and check the "version" column in the result?
> 
> The "enable_storage_cache" property was renamed to "datacache.enable" in version 3.1, and the "storage_cache_ttl" attribute was removed since version 3.1.
> 
> Therefore, in version 3.1 you can write:
> 
> ```
> properties("datacache.enable"="true")
> ```
> 
> To enable the data cache.

hi, @sduzh ,thanks for your reply,but my starrocks version is 3.0.3 , when i try to use "datacache.enable"="true" in create table SQL,   report Unknown properties ，The results are as follows:
![image](https://github.com/StarRocks/starrocks/assets/90946052/89d6421b-8fa9-4ca5-8030-0a55944bbcb8)

![image](https://github.com/StarRocks/starrocks/assets/90946052/76d1cd5f-cd50-4935-b4a9-521d9220f801)

**Comment by sduzh** [comment]
> ### Steps to reproduce the behavior (Required)
> fe.conf:
> 
> run_model = shared_data cloud_native_meta_port = 6090 cloud_native_storage_type = HDFS cloud_native_hdfs_url = hdfs://10.122.33.***:8020/user/sr
> 

Should be `run_mode` not `run_model`

**Comment by RYiHui** [comment]
thanks !!!,Why can't  start the service  after I modify it?

**Comment by RYiHui** [comment]
> > ### Steps to reproduce the behavior (Required)
> > fe.conf:
> > run_model = shared_data cloud_native_meta_port = 6090 cloud_native_storage_type = HDFS cloud_native_hdfs_url = hdfs://10.122.33.***:8020/user/sr
> 
> Should be `run_mode` not `run_model`

thanks !!!,Why can't start the service after I modify it?

**Comment by RYiHui** [comment]
> > ### Steps to reproduce the behavior (Required)
> > fe.conf:
> > run_model = shared_data cloud_native_meta_port = 6090 cloud_native_storage_type = HDFS cloud_native_hdfs_url = hdfs://10.122.33.***:8020/user/sr
> 
> Should be `run_mode` not `run_model`


![image](https://github.com/StarRocks/starrocks/assets/90946052/24e15ce1-1c5f-4043-8872-de26fef33bf5)
when i kill -9 this process, StarRocksFE Still can't start.

**Comment by RYiHui** [comment]
> > ### Steps to reproduce the behavior (Required)
> > fe.conf:
> > run_model = shared_data cloud_native_meta_port = 6090 cloud_native_storage_type = HDFS cloud_native_hdfs_url = hdfs://10.122.33.***:8020/user/sr
> 
> Should be `run_mode` not `run_model`

![image](https://github.com/StarRocks/starrocks/assets/90946052/d222bf94-6906-4b54-a074-52bd0ff0679a)
Should I uninstall starrocks and then reinstall the deployment?

**Comment by sduzh** [comment]
> > > ### Steps to reproduce the behavior (Required)
> > > fe.conf:
> > > run_model = shared_data cloud_native_meta_port = 6090 cloud_native_storage_type = HDFS cloud_native_hdfs_url = hdfs://10.122.33.***:8020/user/sr
> > 
> > 
> > Should be `run_mode` not `run_model`
> 
> ![image](https://user-images.githubusercontent.com/90946052/258694923-d222bf94-6906-4b54-a074-52bd0ff0679a.png) Should I uninstall starrocks and then reinstall the deployment?

Yes

**Comment by sduzh** [comment]
@RYiHui, I wanted to check if the problems raised in this issue have been resolved on your end. If so, I plan to close this issue for now. Please feel free to reopen it anytime if you still have outstanding questions or issues.

**Comment by RYiHui** [comment]
I have resolved this problem,thanks for your help.

**Comment by techkuz** [comment]
hey @sduzh . do i really need a cn for shared data mode? or can i stick with be + fe?

**Comment by sduzh** [comment]
> hey @sduzh . do i really need a cn for shared data mode? or can i stick with be + fe?

You can still use BE.
