### ISSUE TITLE
the starrocks cluster  made of fe,be,cn on k8s didn't work well when set a password to the user 'root' and enabled auth check

### ISSUE THREAD

**Issue by GoodJeek** [StarRocks/starrocks#28692]
### **problem description**

‘tI deployed the cluster on k8s with a elastic scaling CN cluster. When I didn’t enable the  auth check and have no password for the user ‘root’, the cluster run normally; In order to make the cluster work securely，I set a passwod to the user root and started the auth check parameter-'enable_auth_check=true' in the fe.conf, then restarted the fe-pods.  As  a result, the be-pods restarted failed and the cn-pods restarted failed as well, but the fe-pods worked normally.

### **error log as below**
_cn-pods log:_

"ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
[Sat Aug  5 13:03:51 UTC 2023] Add myself (strccn-cn-1.strccn-cn-search.starrocks.svc.cluster.local:9050) into FE ...
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
[Sat Aug  5 13:03:54 UTC 2023] Add myself (strccn-cn-1.strccn-cn-search.starrocks.svc.cluster.local:9050) into FE ...
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
[Sat Aug  5 13:03:56 UTC 2023] Add myself (strccn-cn-1.strccn-cn-search.starrocks.svc.cluster.local:9050) into FE ...
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)"

_be-pods log:_

"ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
[Sat Aug  5 13:21:22 UTC 2023] Add myself (strccn-be-2.strccn-be-search.starrocks.svc.cluster.local:9050) into FE ...
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
[Sat Aug  5 13:21:24 UTC 2023] Add myself (strccn-be-2.strccn-be-search.starrocks.svc.cluster.local:9050) into FE ...
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
[Sat Aug  5 13:21:26 UTC 2023] Add myself (strccn-be-2.strccn-be-search.starrocks.svc.cluster.local:9050) into FE ...
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
[Sat Aug  5 13:21:28 UTC 2023] Add myself (strccn-be-2.strccn-be-search.starro
"

**I tried to add the user 'root' and its password to the be.conf and cn.conf ,but it didn't work well.  I also tried to deploy a cluster without cn cluster on k8s and enabled the auth check , set the root user with password, the cluster worked well. I don‘t  know if it's bug or else in the Cn （compute node）cluster.**
How to solve this problem ? Can you give some advice to this ?

thanks  in advance!!!

**Comment by kevincai** [comment]
https://github.com/StarRocks/starrocks-kubernetes-operator/blob/main/doc/change_root_password_howto.md

check thw doc if you need to change root password.

**Comment by GoodJeek** [comment]
Thanks a lot;
 I have  experimented following the instruction,but the problem repeated as before;
 I have a doubt that the secret rootcredential yaml config  should be added to the starrocks.com_starrocksclusters.yaml  or satrrocks-be-fe-and-cn-with-autoscaler.yaml? The  secret rootcredential  config cant't be added to   starrocks.com_starrocksclusters.yaml for some errros（
_error: error validating "management-state/tmp/yaml-467204180": error validating data: [ValidationError(CustomResourceDefinition.spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.starRocksCnSpec.properties.cnEnvVars): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps: got "array", expected "map" 。。。 ）, 
so I added the  secret rootcredential  config to the deployment yaml of be,fe,cn---satrrocks-be-fe-and-cn-with-autoscaler.yaml; This didn‘t solve the access denied problem.
Why？

**Comment by deschman** [comment]
I am currently experiencing the same problem signing into mysql with the root user upon deployment to kubernetes. Changing the root password did not resolve the problem.

**Comment by kevincai** [comment]
> 

did you follow the instruction to add the env var into starrocks cluster ? or you can share your cr, we can take a look.

**Comment by deschman** [comment]
yes, I did add the env var into the starrocks cluster
