### ISSUE TITLE
不同集群读写分离集群共用一套存储，集群间的元数据共享

### ISSUE THREAD

**Issue by chengqiancheng** [StarRocks/starrocks#28709]
## Enhancement
不同集群读写分离集群共用一套存储，集群间的元数据共享，这样能保证不同集群的计算资源互不影响，只需要元数据同步即可访问其他集群的数据，减少不同集群间同步数据的资源消耗，据了解apache doris的商业运作公司SELECTDB实现了该功能，希望StarRocks也可以实现此应用场景

**Comment by imay** [comment]
Even without metadata sync, you can use different compute resources to handle workloads.

**Comment by chengqiancheng** [comment]
使用jdbc catalog查询其他starRocks集群的性能和我描述场景的查询性能是一致的吗?
