### ISSUE TITLE
[paimon catalog]The grant table permission is given to the user, but the user cannot view the table

### ISSUE THREAD

**Issue by huoyue-git** [StarRocks/starrocks#28727]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
create database test_create_user_6f38eb1a_34ec_11ee_ba53_00163e0e550b;
use test_create_user_6f38eb1a_34ec_11ee_ba53_00163e0e550b
CREATE EXTERNAL CATALOG catalog_6f399498_34ec_11ee_ba53_00163e0e550b properties ("type" = "paimon","paimon.catalog.type"="hive", "paimon.catalog.warehouse" = "hdfs://xxx.xx.xxx.xx:xxxx/user/hive/warehouse", "hive.metastore.uris"="thrift://xxx.xx.xxx.xx:xxxx");
create user user_6f39fb4a_34ec_11ee_ba53_00163e0e550b identified by '123456';
use catalog_6f399498_34ec_11ee_ba53_00163e0e550b.paimon_db;

GRANT all ON table paimon_hdfs_orc_lz4 TO user user_6f39fb4a_34ec_11ee_ba53_00163e0e550b;
select * from default_catalog.sys.grants_to_users;

connect SR use new user

set catalog catalog_6f399498_34ec_11ee_ba53_00163e0e550b  ;
 show catalogs  ;
 show databases ;
use paimon_db;
 show tables ;
 select count(1) from catalog_6f399498_34ec_11ee_ba53_00163e0e550b.paimon_db.paimon_hdfs_orc_lz4;

```

![image](https://github.com/StarRocks/starrocks/assets/91584973/515a3bbd-3bb0-472e-ab8d-e7932d5b33f6)
![image](https://github.com/StarRocks/starrocks/assets/91584973/c05213d8-54aa-4622-a552-6e2a960f1704)

### Expected behavior (Required)
When the user has any permissions on the table, show tables can see the results. When the user has the select or all permission of the table, the query table can be successful

mysql> show tables ;
+---------------------+
| Tables_in_paimon_db |
+---------------------+
| paimon_hdfs_orc_lz4            |
+---------------------+
1 row in set (0.00 sec)

mysql> select count(1) from catalog_6f399498_34ec_11ee_ba53_00163e0e550b.paimon_db.paimon_hdfs_orc_lz4;
+----------+
| count(1) |
+----------+
|       13 |
+----------+
1 row in set (5.43 sec)

### Real behavior (Required)
When the user has any permissions on the table, show tables can not see the results. When the user has the select or all permission of the table, the query table can not be successful

mysql> show tables ;
Empty set (0.44 sec)

mysql> select count(1) from catalog_6f399498_34ec_11ee_ba53_00163e0e550b.paimon_db.paimon_hdfs_orc_lz4;
ERROR 1064 (HY000): Getting analyzing error. Detail message: SELECT command denied to user 'user_6f39fb4a_34ec_11ee_ba53_00163e0e550b'@'xxx.xx.xx.xxx' for table 'catalog_6f399498_34ec_11ee_ba53_00163e0e550b.paimon_db.paimon_hdfs_orc_lz4'.
mysql>
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
+--------------------+
| current_version()  |
+--------------------+
| branch-3.1-1778465 |
+--------------------+
1 row in set (0.01 sec)

**Comment by miomiocat** [comment]
This problem cannot be reproduced using the latest main branch
