### ISSUE TITLE
Could you introduce more about  streaming load ?

### ISSUE THREAD

**Issue by xiaoshao** [StarRocks/starrocks#28756]
## General Question

I read the document about import data and I am interesting in the streaming load logic. 

I read the code about it. 

I found that FE receive the streaming load request and the redirect to a BE node. The BE accpet the streaming load request convert the data to chunk(as my data is csv format), and then send it to other be nodes. But I want to know more about how the be nodes work when it receive the rpc request? Could you introduce it ?

**Comment by alberttwong** [comment]
see the latest docs
