### ISSUE TITLE
Stats collection on first load is  very slow

### ISSUE THREAD

**Issue by hagonzal** [StarRocks/starrocks#28782]
### Steps to reproduce the behavior (Required)
Create a table with 20 array columns and 50 primitive columns.
Each array column contains on average 5 entries.
The table should have 100 million rows.

10 be pods, each be pod with 10 million rows.
An insert statement that updates all rows finishes in 5 minutes, but collect statistics times out after 1 hour.

when we set the following, the query finishes in 5 minutes.
admin set frontend config("enable_statistic_collect_on_first_load"="false");

### Expected behavior (Required)

Statistics collection should take less than 1 minute.

### Real behavior (Required)

Statistics collection has a timeout after 1 hour and the query fails.

### StarRocks version (Required)
3.1

**Comment by liuyehcf** [comment]
Maybe something wong about the communication between the be and fe was happened. And if so, this can be solved by this pr https://github.com/StarRocks/starrocks/pull/28030

**Comment by liuyehcf** [comment]
Is there any important information that I missed? Please let me know if it has.

**Comment by hagonzal** [comment]
In our setup we run a query of the form:

set enable_sort_aggregate = true;
set enable_tablet_internal_parallel = false;
insert into dim_table

with input as (
select FK,
select array_agg(col1 order by eventtime) as c1,
select array_agg(col2 order by eventtime) as  c2,
...
select array_agg(col20 order by eventtime) as c3
from fact_table 
group by FK)
select *
from  dim_table left join input on (input.FK = dim_table.PK)

After the insert the size of the dim_table size (as shown by show data) is 1.47 TB
and the number of rows is 1.3 billion.

This insert completes, and then it waits for 1 hour to collect stats and fails.

**Comment by liuyehcf** [comment]
> In our setup we run a query of the form:
> 
> set enable_sort_aggregate = true; set enable_tablet_internal_parallel = false; insert into dim_table
> 
> with input as ( select FK, select array_agg(col1 order by eventtime) as c1, select array_agg(col2 order by eventtime) as c2, ... select array_agg(col20 order by eventtime) as c3 from fact_table group by FK) select * from dim_table left join input on (input.FK = dim_table.PK)
> 
> After the insert the size of the dim_table size (as shown by show data) is 1.47 TB and the number of rows is 1.3 billion.
> 
> This insert completes, and then it waits for 1 hour to collect stats and fails.

Is this issue consistently reproducible?

**Comment by liuyehcf** [comment]
And could offer the full stack of the fe when the situation happens?

**Comment by liuyehcf** [comment]
Cannot recreate it, close for now.
