### ISSUE TITLE
Optimize broker load startup parameters

### ISSUE THREAD

**Issue by taoshengyijiua** [StarRocks/starrocks#28797]
## Enhancement
We hope to optimize the jvm parameters without changing the script, but JAVA_OPTS is set to a fixed value in the current script, so we can optimize the existing jvm parameters by adding the JAVA_OPTS variable to the value.

**Comment by tclxlijifang** [comment]
@taoshengyijiua 大佬，我是您同程旅行的同事方李骥，请您在企业微信上告诉我您是谁，账号关联不上人

**Comment by tclxlijifang** [comment]
@taoshengyijiua 有点急，辛苦看到了，及时联系我
