### ISSUE TITLE
The official documentation provides inconsistent descriptions of supported shared storage types (such as: HDFS).

### ISSUE THREAD

**Issue by caoyj1024** [StarRocks/starrocks#28912]
- Read the documentation:
  - [StarRocks Doc](https://docs.starrocks.io/en-us/latest/deployment/deploy_shared_data)
  - [StarRocks Doc](https://docs.starrocks.io/zh-cn/latest/deployment/deploy_shared_data)

**Comment by kevincai** [comment]
![image](https://github.com/StarRocks/starrocks/assets/771299/c8da2052-ef16-4dd2-b1a5-2cf618e4d39e)
![image](https://github.com/StarRocks/starrocks/assets/771299/79b81c27-10cd-4264-9300-efcf100f347f)

**Comment by EsoragotoSpirit** [comment]
Hi @caoyj1024 , the difference in the doc you have noticed is because we believe that very few StarRocks' overseas users work with an HDFS environment, thus we removed this part from the EN doc.
