### ISSUE TITLE
query ok when alter table and change nothing

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#2893]
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `t3` (
  `k1` int(11) NULL COMMENT "",
  `k2` int(11) NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`k1`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`) BUCKETS 3 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "V2"
);
alter table t3 modify column k2 int(11);
```

### Expected behavior (Required)
`Nothing is changed. please check your alter stmt.`
### Real behavior (Required)
`Query OK, 0 rows affected (0.00 sec)`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`6d8e035`

**Comment by chaoyli** [comment]
This bug has already been fixed.
