### ISSUE TITLE
Why std(stddev, variance) windows function doesn't support order by?

### ISSUE THREAD

**Issue by BDon-Tan** [StarRocks/starrocks#29087]
## Enhancement
I think var windows functions are useful. Starrocks supports partition by but doesn't work with order by.
Why? And how could I solve some problems like  "select order_id, datetime, std(price) over (partition by order_id order by datetime rows between 5preceding and current row) from table"?

**Comment by before-Sunrise** [comment]
fixed by https://github.com/StarRocks/starrocks/pull/30786
