### ISSUE TITLE
Non-root user cannot stream load 

### ISSUE THREAD

**Issue by mcgray** [StarRocks/starrocks#29086]
Using SR 3.0 and Stream Load (Scala application). While testing and piloting with root user had no issues. When separate user created for load - seeing errors accessing SR. 

### Steps to reproduce the behavior (Required)
Create DB/Table.
Create user with Insert/Select permissions to that table
Try to stream load into table with user

### Expected behavior (Required)
Stream load successful. 

### Real behavior (Required)
Seeing errors:
```
20:55:13.828 ERROR blaze - Supervisor RestartSupervisor saw failure: Stream load failed, statusCode=401 load result={"status":"FAILED","msg":"Access denied for blaze-gom@<removed_infosec>"}
java.lang.RuntimeException: Stream load failed, statusCode=401 load result={"status":"FAILED","msg":"Access denied for blaze-gom@<removed_infosec>"}
```

### StarRocks version (Required)
3.0

**Comment by jaogoy** [comment]
401 means no authentication.

Would you mind to migive more information? 
Does that you mean you submit a curl requrest  to SR with a non-root user, then SR gives you a failed message?

**Comment by mcgray** [comment]
Correct. For non-root user we are having auth issue BUT for root users - everything works fine.
