### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by skypan** [StarRocks/starrocks#2908]
### Steps to reproduce the behavior (Required)
 may be select, 
may be insert into select
then I query again, it remind that there is no scanNode backend
 
### Expected behavior (Required)
run successful
### Real behavior (Required)
be is down, and i found the reason is oom：
![image](https://user-images.githubusercontent.com/11325807/149888404-8b4d7215-2c55-437c-95ee-8daab2cad754.png)

Pleaes Can you resolve it，it happends often
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
starrocks-2.0

**Comment by yiluoya** [comment]
我们在测试的时候也遇到内存问题，所以目前不打算升级到2.0版本   TPC-DS  测试，  Q25

**Comment by Dshadowzh** [comment]
@trueeyu PTAL

**Comment by Dshadowzh** [comment]
@skypan  Would you please add more information, just like SQL and scenario.

**Comment by skypan** [comment]
@Dshadowzh One Scenario is below：
The  statistical of Every day/Every Hour/Every Minute ，the Sql is Below：

select a.num, case when a.lastnum <> 0 then concat(round((a.num - a.lastnum)/a.lastnum * 100, 2), '%') else '0%' end hb, a.sjwd, 'day' sjwdlx, '全部' znbm, a.cjbh xzcj, a.flmc ywfl from (
select a.*, LAG (a.num, 1, 0) OVER (partition by a.flmc, a.cjbh ORDER BY a.sjwd) lastnum from (
select sum(case when (starts_with(a.sjfsdxzqhbh, b.cjbh) > 0 or b.cjbh='全区') and (a.sqlxbm = c.flmc or c.flmc='全部') then a.num else 0 end) num, a.sjwd, b.cjbh, c.flmc from (select sum(case when (DATE_FORMAT(a.gddjsj,'%Y-%m-%d') = b.sjwd or (str_to_date(b.sjwd, '%Y-%m-%d') > a.gddjsj and (a.bjsj is null or date_add(str_to_date(b.sjwd, '%Y-%m-%d'), interval 1 day) <= a.bjsj))) then 1 else 0 end) num, b.sjwd, a.sjfsdxzqhbh, a.sqlxbm from M_MYSB_HZ_SJGDXX a, M_MYSB_WD_SJWDXX_DAY b 
group by b.sjwd, a.sjfsdxzqhbh, a.sqlxbm) a, (select * from M_MYSB_WD_XZCJXX where length(cjbh) <= 12) b, M_MYSB_WD_YWFLXX c group by a.sjwd, b.cjbh, c.flmc) a) a

The Sql Contains The Cross Join

**Comment by skypan** [comment]
Other Scenario is that

the page query, for Example：

select * from audit_project order by createtime desc limint 10 offset 20

It runs slow than mysql，I do not know why ？

**Comment by skypan** [comment]
> Other Scenario is that
> 
> the page query, for Example：
> 
> select * from audit_project order by createtime desc limint 10 offset 20
> 
> It runs slow than mysql，I do not know why ？

the machine's memory is 64G

**Comment by trueeyu** [comment]
Configure the mem_limit of BE = the actual memory that can be used by BE. 

For example, if the machine memory is 40G and FE uses 10G, then add mem_limit=30G in be.conf

**Comment by trueeyu** [comment]
Look at the log of be.out

**Comment by trueeyu** [comment]
Only 56G of memory is used, and it is OOM, indicating that other processes also use a lot of memory, which may be mixed deployment, and the available memory of BE needs to be configured.

**Comment by trueeyu** [comment]
the bin dir of be should be replaced by bin of 2.0, Otherwise, there will be the risk of OOM
