### ISSUE TITLE
StarRocks can support ETL in big data warehouse and replace spark?

### ISSUE THREAD

**Issue by zhaojintaozhao** [StarRocks/starrocks#29089]
## Feature request
Now StarRocks support hive&iceberg query, we can use doris query orc file directly. StarRocks is much faster than spark during TPCDS test.

Will StarRocks support ETL in big data warehouse and replace spark?

**Describe the solution you'd like**
StarRocks should support these features then can replace spark.
StarRocks should support ETL in big data warehouse and replace spark.
StarRocks should support multi-stage execution and ETL capabilities at the execution layer, support batch processing and exchange shufle, support complex SQL statements for querying large tables in the data warehouse.
StarRocks should support support write to ORC files.

**Comment by mofeiatwork** [comment]
we have realized this potential, but it looks like moonshot, we need to consider the resource and path.

**Comment by zhaojintaozhao** [comment]
Hi @mofeiatwork @kangkaisen 
Than's for your message.

In the big data warehouse ETL computing scenario, what's features need to be added to Starrock to replace Spark?
It is impossible to replace Spark limited by architecture?
Or it takes a lot of work and develop may features to replace Spark then can support ETL.

**Comment by alberttwong** [comment]
Why can't you use Airbyte or something similar?
