### ISSUE TITLE
[Bug] values of disk device metrics is always zero when device name ends with number 

### ISSUE THREAD

**Issue by haiboself** [StarRocks/starrocks#29093]
### Steps to reproduce the behavior (Required)
1. Using disk device which name ends with number, like
nvme0n1p1
2. Get be metrics from be:8040/metrics, we can find
- value of disk device metrics is always 0
- device name, which is deleted the rightest number from origin name
starrocks_be_disk_io_time_ms{device="nvme0n1p"}

### Expected behavior (Required)
 value of disk device metrics is real value

### Real behavior (Required)
value of disk device metrics is always 0

### StarRocks version (Required)
2.3.11
2.5.4
2.5.8

**Comment by haiboself** [comment]
The root cause is when update disk device metrics, it does not delete the largest number of device name from '/proc/diskstats' file, so the `device` not in `_disk_metrics`  
![image](https://github.com/StarRocks/starrocks/assets/22912087/4bd0c267-c518-444a-9b52-ad85b2d2cfaf)

**Comment by phenix-gao** [comment]
遇到同样的问题，请问如何解决？
