### ISSUE TITLE
Does starrocks support "replace into" ? 

### ISSUE THREAD

**Issue by laichong** [StarRocks/starrocks#291]
Does starrocks support "replace into" now? 

If not, When can we support it?

**Comment by imay** [comment]
@laichong Welcome. Could you explain more about this feature and what do you want to suport?

**Comment by laichong** [comment]
upsert into  or  replace into, like mysql

If there is no primary key, insert it
If there is this primary key, it will be updated

**Comment by laichong** [comment]
@imay

**Comment by sduzh** [comment]
> upsert into or replace into, like mysql
> 
> If there is no primary key, insert it If there is this primary key, it will be updated

@laichong sorry for the late reply, it seems like this is exactly what the `unique key` does. Please take  https://docs.starrocks.com/en-us/main/table_design/Data_model as a reference.
On the other hand, our upcoming primary key model also supports the needs you described.
