### ISSUE TITLE
flink connector

### ISSUE THREAD

**Issue by ghost** [StarRocks/starrocks#2914]
## Enhancement
现象：
目前flink connector中对于label命名，我看是固定前缀 insert_ ，然后取的uuid，排查错误时，没有什么具体的业务含义。

改进：
flink connector 可以提供对label指定前缀的功。

- 对于 flink streaming ，增加一个新的入口，增加指定 label 前缀的参数，可以让开发人员自己选择，以便后续错误排查使用。
- 对于flink sql，增加一个可配置 with 属性，功能和 flink streaming 一致。

**Comment by Wilson-BT** [comment]
1、不管是流式还是sql，都是使用的streamload，走的统一函数，增加前缀没必要吧，任务报错，自然会去查找相应label。
2、flink sql支持with 属性，不明白你指的with属性是啥。

**Comment by Dshadowzh** [comment]
Flink-connector has an individual repo. You can open issue in https://github.com/StarRocks/flink-connector-starrocks/issues.

**Comment by wzq2468101** [comment]
@Wilson-BT 
1. 我想自己手动指定任务名作为label前缀，指定之后，通过show label，或者是通过日志查看的时候，能知道每个label是哪个任务的，这样的话，看了label名字，就知道这个Label是哪个任务的。

2. with里面有个新的属性来指定这个label前缀。
