### ISSUE TITLE
Batch import into Iceberg runs out of memory

### ISSUE THREAD

**Issue by alanpaulkwan** [StarRocks/starrocks#29193]
Reading a large set of Parquet files, I find that 100gb is not enough memory (the uncompressed table size is probably less than 100 gb, but I guess close). This is true despite the fact that 

1. I have over 384GB of memory on this machine, though I think WSL allocates half by default, and I gave StarRocks 128GB limit and I am guessing the REST / tabular.io instance being used also consume memory. Either way should be a lot.
2. I'm using actually 20ish Parquet files, and hence each piece should just be a few GB

This is true both using the S3( )and newer FILES() functions. The error messages look quite different, but I think are talking roughly about the same thing.

The way I coded around it was simply to use the FILES function to read file by file, so I assume its really just StarRocks' current batch import is unintelligent. Nevertheless, even if the file were 500GB I would imagine StarRocks could just iterate across row blocks, instead of doing something so memory-intensive and inefficient.

Note: I don't know if problem generalizes to writing a native table, I don't recall in the past importing via the S3 function, but I haven't tested in 3.1

**Comment by alberttwong** [comment]
I also have a need for my demos :-D

**Comment by alberttwong** [comment]
The new PIPE command in 3.2 will fix this.
