### ISSUE TITLE
Iceberg catalog needs to automatically self-register all tables

### ISSUE THREAD

**Issue by alanpaulkwan** [StarRocks/starrocks#29304]
## Enhancement

Based on 3.1, I noticed the following problem:

1. Suppose I start a new StarRocks instance.
2. I register an Iceberg rest catalog, with an s3 bucket that has a path called s3://warehouse/db/table1 (inside are written data/metadata folders written by SR)
3. **None** of the tables show up. 

In fact, when you apply a valid schema for an existing table e.g. 

```sql
 CREATE TABLE iceberg.crsp.`dsenames` (
 ... schema details
)PROPERTIES ("location" = "s3://warehouse/crsp/dsenames"); 
```

what happens is **instead of finding the latest metadata and recognizing the data in the path** StarRocks writes a new metadata file ignoring the existing data.

I would assume the fix is to just read the latest metadata file in each folder and register the table into the catalog.

Something like below: for each database, for each table, find the latest .json and register the table accordingly. This is the equivalent Spark Procedure but I couldn't get it working. https://iceberg.apache.org/docs/latest/spark-procedures/#register_table

**Comment by letian-jiang** [comment]
- If you want to reuse an existing storage table, you must register it first in your metadata service.
- Creating table will create a fresh table, not reuse existing data even if you provide the location.

If you cannot get it work, you may file an issue at spark.

**Comment by alanpaulkwan** [comment]
Thanks. Do you have an example?

**Comment by Smith-Cruise** [comment]
If you already create `s3://warehouse/crsp/dsenames` by sr, why there is no table's metadata record in your rest catalog?

**Comment by alanpaulkwan** [comment]
@Smith-Cruise Because I had to recreate the REST catalog. This is because I either moved the data to a new machine or just wiped it.

**Comment by Smith-Cruise** [comment]
Sorry, the current mechanism of Starrocks is to obtain the latest metadata file path from hms, which does not support obtaining it from iceberg folders.

We did not support that function yet, so the only way you need to register iceberg table by Spark.

**Comment by alanpaulkwan** [comment]
Ideally it would be something like ..
```sql
CREATE TABLE iceberg.crsp.dsenames 
USING metadata('s3://warehouse/crsp/dsenames/metadata/latestmetadata.json')
```

I understand that's not of interest to you guys for now, so I'll try to figure out Spark or just revert back to native SR. thanks!
