### ISSUE TITLE
insert large varchar failed

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#2944]
### Steps to reproduce the behavior (Required)
```
1.CREATE TABLE `t1` (
                  `k1` varchar(1048576) not null,
                  `k2` int
                ) ENGINE=OLAP
                PRIMARY KEY(`k1`)
                COMMENT "OLAP"
                DISTRIBUTED BY HASH(`k1`) BUCKETS 3
                PROPERTIES (
                "replication_num" = "1",
                "storage_format" = "V2"
                );

2. insert large varchar into k1 column
```
### Expected behavior (Required)
`query ok`
### Real behavior (Required)
`close index channel failed
`### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`6d8e035`

**Comment by Astralidea** [comment]
This is due to the length limit of the primary key of the primary key.
There is a problem with the error report, it should not report close index channel failed, but should report the real error.
For other type of the table it will be ok.

**Comment by colorfulu** [comment]
Could directly report an error when creating a primary table with such a large varchar primary key.

**Comment by Astralidea** [comment]
> 

You are right

**Comment by Linkerist** [comment]
It's OK for now, you can have a check and close this issue.
