### ISSUE TITLE
从2.3.4升级到2.3.14之后，进行明文模糊查询和密文模糊测试发现BE集群异常挂掉

### ISSUE THREAD

**Issue by zhouhaolong** [StarRocks/starrocks#29458]
# 背景
之前使用2.3.4发现有BUG，集群需要升级到2.3.14，升级之后又发现集群挂掉。

## 之前Bug信息：
这个是BE 启动加载 Tablet 反复 Crash，需要开启Syslog找到对应的TabletId，使用meta_tool 删除这个Tablet，然后升级到2.3最新小版本，高版本有做过修复
https://forum.mirrorship.cn/t/topic/3928/90 

# 表现
目前Be集群能正常运行，但be.out日志里面显示之前有不断挂掉，需要排查定位问题。
如下是升级后的be日志
`      
start time: Sat Aug 12 22:12:54 CST 2023
tcmalloc: large alloc 3472334919084163072 bytes == (nil) @  0x59c939f 0x5c5aa1c 0x217fa18 0x5baae95 0x1aeee3e 0x26fa7b1 0x2a0e4a3 0x29e0633 0x29d6cde 0x2236199 0x2231d4a 0x7f6eb42bcea5
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
query_id:c5229c54-3cde-11ee-98cf-00e0ed4962c6, fragment_instance:c5229c54-3cde-11ee-98cf-00e0ed4962c8
*** Aborted at 1692263798 (unix time) try "date -d @1692263798" if you are using GNU date ***
PC: @     0x7f6eb380f387 __GI_raise
*** SIGABRT (@0x217c4) received by PID 137156 (TID 0x7f6e244a4700) from PID 137156; stack trace: ***
    @          0x3f91c22 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f6eb42c4630 (unknown)
    @     0x7f6eb380f387 __GI_raise
    @     0x7f6eb3810a78 __GI_abort
    @          0x1967d63 _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold
    @          0x5baa946 __cxxabiv1::__terminate()
    @          0x5baa9b1 std::terminate()
    @          0x5baab04 __cxa_throw
    @          0x1967c6a _Znwm.cold
    @          0x1aebbce std::vector<>::_M_range_insert<>()
    @          0x1aeee3e starrocks::vectorized::BinaryColumnBase<>::append_strings()
    @          0x26fa7b1 starrocks::Aggregator::convert_hash_set_to_chunk<>()
    @          0x2a0e4a3 starrocks::pipeline::AggregateDistinctBlockingSourceOperator::pull_chunk()
    @          0x29e0633 starrocks::pipeline::PipelineDriver::process()
    @          0x29d6cde starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x2236199 starrocks::ThreadPool::dispatch_thread()
    @          0x2231d4a starrocks::Thread::supervise_thread()
    @     0x7f6eb42bcea5 start_thread
    @     0x7f6eb38d7b0d __clone
    @                0x0 (unknown)
start time: Thu Aug 17 17:17:02 CST 2023
tcmalloc: large alloc 21754009362432 bytes == (nil) @  0x59c939f 0x5c5aa1c 0x217fa18 0x5baae95 0x1aeee3e 0x26fa7b1 0x2a0e4a3 0x29e0633 0x29d6cde 0x2236199 0x2231d4a 0x7f819c6c5ea5
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
query_id:deed8c4c-3cde-11ee-aef9-00e0ed48580a, fragment_instance:deed8c4c-3cde-11ee-aef9-00e0ed48580d
*** Aborted at 1692263841 (unix time) try "date -d @1692263841" if you are using GNU date ***
PC: @     0x7f819bc18387 __GI_raise
*** SIGABRT (@0x28406) received by PID 164870 (TID 0x7f80fa889700) from PID 164870; stack trace: ***
    @          0x3f91c22 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f819c6cd630 (unknown)
    @     0x7f819bc18387 __GI_raise
    @     0x7f819bc19a78 __GI_abort
    @          0x1967d63 _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold
    @          0x5baa946 __cxxabiv1::__terminate()
    @          0x5baa9b1 std::terminate()
    @          0x5baab04 __cxa_throw
    @          0x1967c6a _Znwm.cold
    @          0x1aebbce std::vector<>::_M_range_insert<>()
    @          0x1aeee3e starrocks::vectorized::BinaryColumnBase<>::append_strings()
    @          0x26fa7b1 starrocks::Aggregator::convert_hash_set_to_chunk<>()
    @          0x2a0e4a3 starrocks::pipeline::AggregateDistinctBlockingSourceOperator::pull_chunk()
    @          0x29e0633 starrocks::pipeline::PipelineDriver::process()
    @          0x29d6cde starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x2236199 starrocks::ThreadPool::dispatch_thread()
    @          0x2231d4a starrocks::Thread::supervise_thread()
    @     0x7f819c6c5ea5 start_thread
    @     0x7f819bce0b0d __clone
    @                0x0 (unknown)
start time: Thu Aug 17 17:18:02 CST 2023
query_id:056bac28-3cdf-11ee-a305-00e0ed4962dc, fragment_instance:056bac28-3cdf-11ee-a305-00e0ed4962dd
*** Aborted at 1692263906 (unix time) try "date -d @1692263906" if you are using GNU date ***
PC: @          0x59dc3ab tcmalloc::ThreadCache::ReleaseToCentralCache()
*** SIGSEGV (@0x0) received by PID 167408 (TID 0x7fa02abcf700) from PID 0; stack trace: ***
    @          0x3f91c22 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fa0b99ed630 (unknown)
    @          0x59dc3ab tcmalloc::ThreadCache::ReleaseToCentralCache()
    @          0x59dca05 tcmalloc::ThreadCache::ListTooLong()
    @          0x25e492a starrocks::vectorized::Chunk::clone_empty_with_slot()
    @          0x36713ff starrocks::pipeline::ExchangeSinkOperator::Channel::add_rows_selective()
    @          0x3672a4d starrocks::pipeline::ExchangeSinkOperator::push_chunk()
    @          0x29e0e14 starrocks::pipeline::PipelineDriver::process()
    @          0x29d6cde starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x2236199 starrocks::ThreadPool::dispatch_thread()
    @          0x2231d4a starrocks::Thread::supervise_thread()
    @     0x7fa0b99e5ea5 start_thread
    @     0x7fa0b9000b0d __clone
    @                0x0 (unknown)
start time: Thu Aug 17 17:19:02 CST 2023
query_id:256bf643-3cdf-11ee-98cf-00e0ed4962c6, fragment_instance:256bf643-3cdf-11ee-98cf-00e0ed4962c7
*** Aborted at 1692263959 (unix time) try "date -d @1692263959" if you are using GNU date ***
PC: @          0x59dc3ab tcmalloc::ThreadCache::ReleaseToCentralCache()
*** SIGSEGV (@0x0) received by PID 169958 (TID 0x7f84178a0700) from PID 0; stack trace: ***
    @          0x3f91c22 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f84b7ee1630 (unknown)
    @          0x59dc3ab tcmalloc::ThreadCache::ReleaseToCentralCache()
    @          0x59dca05 tcmalloc::ThreadCache::ListTooLong()
    @          0x25e54fa starrocks::vectorized::Chunk::clone_empty_with_tuple()
    @          0x25e572e starrocks::vectorized::Chunk::clone_unique()
    @          0x217a9bc starrocks::PassThroughContext::append_chunk()
    @          0x3670bd5 starrocks::pipeline::ExchangeSinkOperator::Channel::send_one_chunk()
    @          0x3671762 starrocks::pipeline::ExchangeSinkOperator::Channel::_close_internal()
    @          0x3671866 starrocks::pipeline::ExchangeSinkOperator::Channel::close()
    @          0x3671bbf starrocks::pipeline::ExchangeSinkOperator::set_finishing()
    @          0x29df7d7 starrocks::pipeline::PipelineDriver::_mark_operator_finishing()
    @          0x29e07ab starrocks::pipeline::PipelineDriver::process()
    @          0x29d6cde starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x2236199 starrocks::ThreadPool::dispatch_thread()
    @          0x2231d4a starrocks::Thread::supervise_thread()
    @     0x7f84b7ed9ea5 start_thread
    @     0x7f84b74f4b0d __clone
    @                0x0 (unknown)
start time: Thu Aug 17 17:20:02 CST 2023
tcmalloc: large alloc 1387671635505324032 bytes == (nil) @  0x59c939f 0x5c5aa1c 0x217fa18 0x5baae95 0x1aeee3e 0x26fa7b1 0x2a0e4a3 0x29e0633 0x29d6cde 0x2236199 0x2231d4a 0x7f36d7100ea5
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
query_id:7eb18292-3cdf-11ee-98cf-00e0ed4962c6, fragment_instance:7eb18292-3cdf-11ee-98cf-00e0ed4962ca
*** Aborted at 1692264109 (unix time) try "date -d @1692264109" if you are using GNU date ***
PC: @     0x7f36d6653387 __GI_raise
*** SIGABRT (@0x2a1f9) received by PID 172537 (TID 0x7f363e2d6700) from PID 172537; stack trace: ***
    @          0x3f91c22 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f36d7108630 (unknown)
    @     0x7f36d6653387 __GI_raise
    @     0x7f36d6654a78 __GI_abort
    @          0x1967d63 _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold
    @          0x5baa946 __cxxabiv1::__terminate()
    @          0x5baa9b1 std::terminate()
    @          0x5baab04 __cxa_throw
    @          0x1967c6a _Znwm.cold
    @          0x1aebbce std::vector<>::_M_range_insert<>()
    @          0x1aeee3e starrocks::vectorized::BinaryColumnBase<>::append_strings()
    @          0x26fa7b1 starrocks::Aggregator::convert_hash_set_to_chunk<>()
    @          0x2a0e4a3 starrocks::pipeline::AggregateDistinctBlockingSourceOperator::pull_chunk()
    @          0x29e0633 starrocks::pipeline::PipelineDriver::process()
    @          0x29d6cde starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x2236199 starrocks::ThreadPool::dispatch_thread()
    @          0x2231d4a starrocks::Thread::supervise_thread()
    @     0x7f36d7100ea5 start_thread
    @     0x7f36d671bb0d __clone
    @                0x0 (unknown)
start time: Thu Aug 17 17:22:02 CST 2023
tcmalloc: large alloc 2391991947964194816 bytes == (nil) @  0x59c939f 0x5c5aa1c 0x217fa18 0x5baae95 0x1aeee3e 0x26fa7b1 0x2a0e4a3 0x29e0633 0x29d6cde 0x2236199 0x2231d4a 0x7fbd9534aea5
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
query_id:57b081a6-3ce0-11ee-aef9-00e0ed48580a, fragment_instance:57b081a6-3ce0-11ee-aef9-00e0ed48580f
*** Aborted at 1692264474 (unix time) try "date -d @1692264474" if you are using GNU date ***
PC: @     0x7fbd9489d387 __GI_raise
*** SIGABRT (@0x2ac5c) received by PID 175196 (TID 0x7fbd00d29700) from PID 175196; stack trace: ***
    @          0x3f91c22 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fbd95352630 (unknown)
    @     0x7fbd9489d387 __GI_raise
    @     0x7fbd9489ea78 __GI_abort
    @          0x1967d63 _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold
    @          0x5baa946 __cxxabiv1::__terminate()
    @          0x5baa9b1 std::terminate()
    @          0x5baab04 __cxa_throw
    @          0x1967c6a _Znwm.cold
    @          0x1aebbce std::vector<>::_M_range_insert<>()
    @          0x1aeee3e starrocks::vectorized::BinaryColumnBase<>::append_strings()
    @          0x26fa7b1 starrocks::Aggregator::convert_hash_set_to_chunk<>()
    @          0x2a0e4a3 starrocks::pipeline::AggregateDistinctBlockingSourceOperator::pull_chunk()
    @          0x29e0633 starrocks::pipeline::PipelineDriver::process()
    @          0x29d6cde starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x2236199 starrocks::ThreadPool::dispatch_thread()
    @          0x2231d4a starrocks::Thread::supervise_thread()
    @     0x7fbd9534aea5 start_thread
    @     0x7fbd94965b0d __clone
    @                0x0 (unknown)
start time: Thu Aug 17 17:28:02 CST 2023
query_id:00000000-0000-0000-0000-000000000000, fragment_instance:00000000-0000-0000-0000-000000000000
*** Aborted at 1692264508 (unix time) try "date -d @1692264508" if you are using GNU date ***
PC: @          0x59dc3ab tcmalloc::ThreadCache::ReleaseToCentralCache()
*** SIGSEGV (@0x0) received by PID 178455 (TID 0x7fbc5d3ff700) from PID 0; stack trace: ***
    @          0x3f91c22 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fbdb5bb0630 (unknown)
    @          0x59dc3ab tcmalloc::ThreadCache::ReleaseToCentralCache()
    @          0x59dc97f tcmalloc::ThreadCache::Scavenge()
    @          0x40b0b5c butil::IOBuf::clear()
    @          0x41049ff brpc::Controller::ResetNonPods()
    @          0x4104d10 brpc::Controller::~Controller()
    @          0x3680e29 starrocks::DisposableClosure<>::Run()
    @          0x4102bdb brpc::Controller::EndRPC()
    @          0x4129f8e brpc::policy::ProcessRpcResponse()
    @          0x4122b77 brpc::ProcessInputMessage()
    @          0x4123a23 brpc::InputMessenger::OnNewMessages()
    @          0x41ca6ee brpc::Socket::ProcessEvent()
    @          0x40d867f bthread::TaskGroup::task_runner()
    @          0x4260e61 bthread_make_fcontext
start time: Thu Aug 17 17:29:02 CST 2023
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_range_insert
query_id:3cdc42e4-3ce1-11ee-98cf-00e0ed4962c6, fragment_instance:3cdc42e4-3ce1-11ee-98cf-00e0ed4962cc
*** Aborted at 1692264858 (unix time) try "date -d @1692264858" if you are using GNU date ***
PC: @     0x7fa3a491e387 __GI_raise
*** SIGABRT (@0x2c2ff) received by PID 180991 (TID 0x7fa305d94700) from PID 180991; stack trace: ***
    @          0x3f91c22 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fa3a53d3630 (unknown)
    @     0x7fa3a491e387 __GI_raise
    @     0x7fa3a491fa78 __GI_abort
    @          0x1967d63 _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold
    @          0x5baa946 __cxxabiv1::__terminate()
    @          0x5baa9b1 std::terminate()
    @          0x5baab04 __cxa_throw
    @          0x1969947 std::__throw_length_error()
    @          0x1aebd42 std::vector<>::_M_range_insert<>()
    @          0x1aeee3e starrocks::vectorized::BinaryColumnBase<>::append_strings()
    @          0x26fa7b1 starrocks::Aggregator::convert_hash_set_to_chunk<>()
    @          0x2a0e4a3 starrocks::pipeline::AggregateDistinctBlockingSourceOperator::pull_chunk()
    @          0x29e0633 starrocks::pipeline::PipelineDriver::process()
    @          0x29d6cde starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x2236199 starrocks::ThreadPool::dispatch_thread()
    @          0x2231d4a starrocks::Thread::supervise_thread()
    @     0x7fa3a53cbea5 start_thread
    @     0x7fa3a49e6b0d __clone
    @                0x0 (unknown)
start time: Thu Aug 17 17:35:02 CST 2023
tcmalloc: large alloc 4984921838704992256 bytes == (nil) @  0x59c939f 0x5c5aa1c 0x217fa18 0x5baae95 0x1aeee3e 0x26fa7b1 0x2a0e4a3 0x29e0633 0x29d6cde 0x2236199 0x2231d4a 0x7fb70fc27ea5
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
query_id:5fd3d462-3ce1-11ee-98cf-00e0ed4962c6, fragment_instance:5fd3d462-3ce1-11ee-98cf-00e0ed4962c9
*** Aborted at 1692264916 (unix time) try "date -d @1692264916" if you are using GNU date ***
PC: @     0x7fb70f17a387 __GI_raise
*** SIGABRT (@0x2cf6e) received by PID 184174 (TID 0x7fb681e13700) from PID 184174; stack trace: ***
    @          0x3f91c22 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fb70fc2f630 (unknown)
    @     0x7fb70f17a387 __GI_raise
    @     0x7fb70f17ba78 __GI_abort
    @          0x1967d63 _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold
    @          0x5baa946 __cxxabiv1::__terminate()
    @          0x5baa9b1 std::terminate()
    @          0x5baab04 __cxa_throw
    @          0x1967c6a _Znwm.cold
    @          0x1aebbce std::vector<>::_M_range_insert<>()
    @          0x1aeee3e starrocks::vectorized::BinaryColumnBase<>::append_strings()
    @          0x26fa7b1 starrocks::Aggregator::convert_hash_set_to_chunk<>()
    @          0x2a0e4a3 starrocks::pipeline::AggregateDistinctBlockingSourceOperator::pull_chunk()
    @          0x29e0633 starrocks::pipeline::PipelineDriver::process()
    @          0x29d6cde starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x2236199 starrocks::ThreadPool::dispatch_thread()
    @          0x2231d4a starrocks::Thread::supervise_thread()
    @     0x7fb70fc27ea5 start_thread
    @     0x7fb70f242b0d __clone
    @                0x0 (unknown)
start time: Thu Aug 17 17:36:02 CST 2023
query_id:5c055e19-8fcd-41dc-a59d-daff5cadc7cc, fragment_instance:5c055e19-8fcd-41dc-a59d-daff5cadc7cf
*** Aborted at 1692264982 (unix time) try "date -d @1692264982" if you are using GNU date ***
PC: @          0x26fa6cf starrocks::Aggregator::convert_hash_set_to_chunk<>()
*** SIGSEGV (@0x1) received by PID 186698 (TID 0x7fedd060c700) from PID 1; stack trace: ***
    @          0x3f91c22 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fee68c3d630 (unknown)
    @          0x26fa6cf starrocks::Aggregator::convert_hash_set_to_chunk<>()
    @          0x2a0e4a3 starrocks::pipeline::AggregateDistinctBlockingSourceOperator::pull_chunk()
    @          0x29e0633 starrocks::pipeline::PipelineDriver::process()
    @          0x29d6cde starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x2236199 starrocks::ThreadPool::dispatch_thread()
    @          0x2231d4a starrocks::Thread::supervise_thread()
    @     0x7fee68c35ea5 start_thread
    @     0x7fee68250b0d __clone
    @                0x0 (unknown)
start time: Thu Aug 17 17:37:02 CST 2023
query_id:add0bbc2-3ce1-11ee-aef9-00e0ed48580a, fragment_instance:add0bbc2-3ce1-11ee-aef9-00e0ed48580b
*** Aborted at 1692265047 (unix time) try "date -d @1692265047" if you are using GNU date ***
PC: @          0x59dc3ab tcmalloc::ThreadCache::ReleaseToCentralCache()
*** SIGSEGV (@0x0) received by PID 189231 (TID 0x7f01fd2c4700) from PID 0; stack trace: ***
    @          0x3f91c22 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f02908eb630 (unknown)
    @          0x59dc3ab tcmalloc::ThreadCache::ReleaseToCentralCache()
    @          0x59dc97f tcmalloc::ThreadCache::Scavenge()
    @          0x1a9b1e3 std::vector<>::_M_default_append()
    @          0x1af9a3f starrocks::vectorized::BinaryColumnBase<>::append_selective()
    @          0x25f56e3 starrocks::vectorized::NullableColumn::append_selective()
    @          0x25e27da starrocks::vectorized::Chunk::append_selective()
    @          0x3671394 starrocks::pipeline::ExchangeSinkOperator::Channel::add_rows_selective()
    @          0x3672a4d starrocks::pipeline::ExchangeSinkOperator::push_chunk()
    @          0x29e0e14 starrocks::pipeline::PipelineDriver::process()
    @          0x29d6cde starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x2236199 starrocks::ThreadPool::dispatch_thread()
    @          0x2231d4a starrocks::Thread::supervise_thread()
    @     0x7f02908e3ea5 start_thread
    @     0x7f028fefeb0d __clone
    @                0x0 (unknown)
start time: Thu Aug 17 17:38:02 CST 2023
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_range_insert
query_id:ca6a5ba6-3ce1-11ee-a305-00e0ed4962dc, fragment_instance:ca6a5ba6-3ce1-11ee-a305-00e0ed4962e1
*** Aborted at 1692265095 (unix time) try "date -d @1692265095" if you are using GNU date ***
PC: @     0x7fb53e9c5387 __GI_raise
*** SIGABRT (@0x2ed0f) received by PID 191759 (TID 0x7fb4ade57700) from PID 191759; stack trace: ***
    @          0x3f91c22 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fb53f47a630 (unknown)
    @     0x7fb53e9c5387 __GI_raise
    @     0x7fb53e9c6a78 __GI_abort
    @          0x1967d63 _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold
    @          0x5baa946 __cxxabiv1::__terminate()
    @          0x5baa9b1 std::terminate()
    @          0x5baab04 __cxa_throw
    @          0x1969947 std::__throw_length_error()
    @          0x1aebd42 std::vector<>::_M_range_insert<>()
    @          0x1aeee3e starrocks::vectorized::BinaryColumnBase<>::append_strings()
    @          0x26fa7b1 starrocks::Aggregator::convert_hash_set_to_chunk<>()
    @          0x2a0e4a3 starrocks::pipeline::AggregateDistinctBlockingSourceOperator::pull_chunk()
    @          0x29e0633 starrocks::pipeline::PipelineDriver::process()
    @          0x29d6cde starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x2236199 starrocks::ThreadPool::dispatch_thread()
    @          0x2231d4a starrocks::Thread::supervise_thread()
    @     0x7fb53f472ea5 start_thread
    @     0x7fb53ea8db0d __clone
    @                0x0 (unknown)
start time: Thu Aug 17 17:39:02 CST 2023
query_id:20e751be-3ce2-11ee-aef9-00e0ed48580a, fragment_instance:20e751be-3ce2-11ee-aef9-00e0ed48580d
*** Aborted at 1692265240 (unix time) try "date -d @1692265240" if you are using GNU date ***
PC: @         0xfede32d0 (unknown)
*** SIGSEGV (@0xfede32d0) received by PID 194289 (TID 0x7f84d9897700) from PID 18446744073690559184; stack trace: ***
    @          0x3f91c22 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f85796d7630 (unknown)
    @         0xfede32d0 (unknown)
start time: Thu Aug 17 17:41:02 CST 2023

    `

# 使用分析
08-12日从2.3.4升级到2.3.14后，运行都正常，08-17下午进行明文模糊查询和密文模糊对比测试，测试过程中出现集群异常，怀疑是高并发测试导致BE节点挂掉，需要官方详细排查下。

## 测试说明
表是非分区表，表的数据量是220w。
使用jmeter5.5工具测试，所有测试统一持续查询10s，每次返回200条数据，结果单位为毫秒。
查询场景1 - 明文查询 ： select * from db_name.tablename_encrypt where sku_name like '%哈哈%' limit 200;
查询场景1 - 密文查询 ： select * from db_name.tablename_encrypt where aes_decrypt(from_base64(sku_name_encrypt), 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx') like '%哈哈%' limit 200;

查询场景2 - 明文查询 ： select distinct user_id from db_name.tablename_encrypt where order_type='嘎嘎' and sku_name like '%哈哈%' limit 200;
查询场景2 - 密文查询 ： select distinct user_id from db_name.tablename_encrypt where order_type='嘎嘎' and aes_decrypt(from_base64(sku_name_encrypt),'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx') like '%哈哈%' limit 200;

## 测试结果
![c1a6f256e6af9d8b1756878ef083a75](https://github.com/StarRocks/starrocks/assets/14014006/20ce7d8e-66cb-475e-967b-7886a3483e86)

**Comment by stdpain** [comment]
fixed in https://github.com/StarRocks/starrocks/pull/26042. 2.3.15+
