### ISSUE TITLE
[core](be) StarRocks be core when query send data chunk on be

### ISSUE THREAD

**Issue by caiconghui** [StarRocks/starrocks#29580]
### Steps to reproduce the behavior (Required)
query make be core when send data chunk 
no idea how it happend, because query is normal, try query, not happen again, so just record this core first

PC: @          0x3fbffa2 starrocks::pipeline::SinkBuffer::_try_to_send_rpc()
*** SIGSEGV (@0x0) received by PID 769 (TID 0x7f489efff700) from PID 0; stack trace: ***
    @          0x487c722 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f49c5619630 (unknown)
    @          0x3fbffa2 starrocks::pipeline::SinkBuffer::_try_to_send_rpc()
    @          0x3fc0742 starrocks::pipeline::SinkBuffer::add_request()
    @          0x3fb4357 starrocks::pipeline::ExchangeSinkOperator::Channel::send_one_chunk()
    @          0x3fb4cb4 starrocks::pipeline::ExchangeSinkOperator::Channel::_close_internal()
    @          0x3fb4d46 starrocks::pipeline::ExchangeSinkOperator::Channel::close()
    @          0x3fb5137 starrocks::pipeline::ExchangeSinkOperator::set_finishing()
    @          0x1e5c1a7 starrocks::pipeline::PipelineDriver::_mark_operator_finishing()
    @          0x1e5cdc5 starrocks::pipeline::PipelineDriver::process()
    @          0x3ce8805 starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x37adbf5 starrocks::ThreadPool::dispatch_thread()
    @          0x37a8a9a starrocks::Thread::supervise_thread()
    @     0x7f49c5611ea5 start_thread
    @     0x7f49c4c2cb0d __clone
    @                0x0 (unknown)

### Expected behavior (Required)
no core 
### StarRocks version (Required)
 - 2.4.2

**Comment by jaogoy** [comment]
@kangkaisen PTAL
