### ISSUE TITLE
Load support skip_header params.

### ISSUE THREAD

**Issue by Astralidea** [StarRocks/starrocks#296]
## Background
Typically, users will export DSV(Delimiter-separated values) from a system and then import it using steam load.
but for general DSV files, it only defines the record delimiter and row delimiter.
there is no standard definition of the separator between header and data.

snowflake use CLRF for separator between header and data.
redshift we can't tell from the document which rule he used.
mysql is according to LINES TERMINATED BY to IGNORE 1 LINES。
there more system will be further investigation...

## Enhancement
Starrocks currently has five Load modes.
For stream load & broker load . we could support skip_header which represent number of lines at the start of the file to skip.
skip_header does not use the column_sepeartor or row_seperator values to determine what a header line is; rather, it simply skips the specified number of \n lines in the file. 
spark load may also need support.
insert into and routine load may not need support.

## Usage
```
curl --location-trusted -u root: -T test.data -XPUT -H "column_separator:," -H "skip_header:1" http://localhost:8030/api/test/test/_stream_load/
```
if remove  -H "skip_header:1" the default will be skip_header:0 is the same as previous syntax.
if skip_header set to 10 it will skip 10 line of the file use \n and load.

# Reference
https://en.wikipedia.org/wiki/Delimiter-separated_values
https://docs.snowflake.com/en/sql-reference/sql/copy-into-table.html
https://docs.aws.amazon.com/redshift/latest/dg/copy-parameters-data-conversion.html#copy-ignoreheader

**Comment by imay** [comment]
Could you please explain more about this feature's backgroud?

> it simply skips the specified number of \n lines in the file.

Why don't consider the column_sepeartor or row_seperator? Is this way a common case?

And what's more, you should describe the syntax after supporting this feature, add some example to show how to use it.

**Comment by jaogoy** [comment]
We
