### ISSUE TITLE
FE FOLLOWER SHOW PROC '/backends' 显示错误问题

### ISSUE THREAD

**Issue by phenix-gao** [StarRocks/starrocks#29638]
FE FOLLOWER SHOW PROC '/backends' 显示信息如下：
![image](https://github.com/StarRocks/starrocks/assets/10410904/0d70f659-8c45-4353-bb63-0ddad92ed109)

FE LEADER SHOW PROC '/backends' 显示信息如下：
![image](https://github.com/StarRocks/starrocks/assets/10410904/a07819d3-32ee-4512-adbc-3432ead2faac)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 3.0.5
 - 2.5.10

**Comment by kevincai** [comment]
this is working as design. backends info in follower is only updated when necessary. the `LastHeartbeat` `DataUsedCapacity`, `AvailCapacity` fields does't affect the FOLLOWER to perform readonly operations.
