### ISSUE TITLE
S3 object store StarRocks tables

### ISSUE THREAD

**Issue by alanpaulkwan** [StarRocks/starrocks#29637]
Given that SR supports self-describing Parquet tables, would it make sense for SR to support self-describing file-based external StarRocks table? Part of the shared-nothing philosophy, but rather than forcing one to set up a shared-nothing version of SR, this flexibly allows one to define it on an object basis. Useful for backups as well.

**Comment by alberttwong** [comment]
Yes... the new quickstart in 3.2 shows how to do this with MinIO
