### ISSUE TITLE
启动脚本报错问题

### ISSUE THREAD

**Issue by phenix-gao** [StarRocks/starrocks#29644]
操作系统版本：CentOS Linux release 7.4.1708 (Core)
启动be报错如下：
![image](https://github.com/StarRocks/starrocks/assets/10410904/b6a977c9-5e94-484a-9e87-50f28545f5d9)

建议将common.sh的95行修改如下
![image](https://github.com/StarRocks/starrocks/assets/10410904/50929631-173c-4995-8cc7-b175b946272a)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 3.0.5
 - 2.5.10

**Comment by kevincai** [comment]
the mem_limit is removed in branch-3.1.

Maybe we can remove it in branch-2.5 and branch-3.0 as well. @trueeyu
