### ISSUE TITLE
Power BI MySQL ODBC compatibility matrix

### ISSUE THREAD

**Issue by jiabinxia-sanofi** [StarRocks/starrocks#29670]
Dear Team,

We are using SR 2.5.5 and we are using PowerBI to directly connect to SR. We use the official mez connector.
We find that only MySQL ODBC driver 8.0.23 works but not later versions of the ODBC driver. Please provide compatibility matrix for PowerBI direct query compatibility. Thank you.

**Comment by alberttwong** [comment]
PowerBI connector is only available in the enterprise/cloud version of StarRocks.
