### ISSUE TITLE
同样的SQL，未建立物化视图能正确执行；建立物化视图后，执行异常：ERROR 1064 (HY000): Unknown error

### ISSUE THREAD

**Issue by Smartbicaopan** [StarRocks/starrocks#2975]
版本：StarRocks2.0.0-GA

CREATE TABLE fact (
  dim1 varchar(8), 
  dim2 varchar(8),
  m1 int
) 
DUPLICATE KEY(dim1, dim2)
DISTRIBUTED BY HASH(dim2) BUCKETS 4
PROPERTIES ("replication_num" = "1");

insert into fact values('a1', 'b1', 1);
insert into fact values('a1', 'b2', 2);
insert into fact values('a2', 'b1', 3);

该语句能正确执行：
select * from (select *,'v1' as vid from fact) T where vid = 'v1'

建立物化视图：
create materialized view MV_1 as select dim1,sum(m1) from fact group by dim1;

物化视图建立完成后，执行如下语句会报错（ERROR 1064 (HY000): Unknown error）：
select * from (select *,'v1' as vid from fact) T where vid = 'v1'
select * from (select *,'v1' as vid from fact) T where vid in ('v1')

物化视图建立完成后，执行如下语句正确：
select * from (select *,'v1' as vid from fact) T where vid like ('v1')

删除物化视图后，以上语句均能正确执行

**Comment by stdpain** [comment]
please provide fe.warn.log

**Comment by Seaven** [comment]
#3063 Fixed
