### ISSUE TITLE
[storage_cooldown_ttl] show create

### ISSUE THREAD

**Issue by huoyue-git** [StarRocks/starrocks#29805]
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `cooldown_ttl_month3_table_with_null`
            (  `k1`  date, `k2`  datetime,`k3`  string, `k4`  varchar(20), `k5`  boolean)
            unique KEY(`k1`, `k2`)
            PARTITION BY range(k2)
            (
                PARTITION p1 VALUES LESS THAN ("2021-01-02 11:30:35")
            ) DISTRIBUTED BY HASH(`k1`)
            PROPERTIES ("storage_medium" = "SSD", "storage_cooldown_ttl" = "2 month");
show create table cooldown_ttl_month3_table_with_null;
alter table cooldown_ttl_month3_table_with_null set ("storage_cooldown_ttl" = "2 month");
show create table cooldown_ttl_month3_table_with_null;
```
![image](https://github.com/StarRocks/starrocks/assets/91584973/a9510dc9-7d7d-4d41-b9b4-eb7f82014ea1)

![image](https://github.com/StarRocks/starrocks/assets/91584973/9c46464f-a480-4164-8c5b-dd5febf888f8)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+--------------------+
| current_version()  |
+--------------------+
| branch-3.1-88c9416 |
+--------------------+
1 row in set (0.00 sec)

**Comment by Astralidea** [comment]
This is not a big problem and does not need to be solved for the time being.
