### ISSUE TITLE
在高并发测试时，be出现_rq is full报错

### ISSUE THREAD

**Issue by yaystrong** [StarRocks/starrocks#2998]
hi~ 我使用2.0.0-GA版本进行并发测试，
我的测试表为明细表，按天分区，每天的原始数据大小是22G，每个partition创建10个分桶，查询90天数据，在300并发下执行测试sql：
SELECT name,class,address,grade,sum(cnt_1),sum(cnt_2),sum(cnt_3),sum(cnt_4),sum(cnt_5),sum(cnt_6),sum(cnt_7),sum(cnt_8) from test where start_time>=day1 and start_time<=day90 group by name,class,address,gradename,class,address,grade;
每次在测试时，会有1到两次的报错

be.WARNING报错如下：
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/98150091/150492032-edf0e14d-4976-497b-bc70-892920d914be.png">

fe.warn.log报错如下
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/98150091/150491434-dad1bd2c-d6d9-4c43-a16e-1a8651dba50b.png">
我先后调整了参数：
fe:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/98150091/150490398-47f89cdc-bfa1-49a4-88ca-c7ba15d0df0c.png">
be:
<img width="427" alt="image" src="https://user-images.githubusercontent.com/98150091/150490450-cd4f454a-5c80-48d9-a444-9ae3c4ca3d43.png">
以及parallel_fragment_exec_instance_num=32

请问应当如何优化和解决？谢谢

**Comment by stdpain** [comment]
Please provide pstack logs.

**Comment by yaystrong** [comment]
附件为pstack log，请查看
[be1_pstack.log](https://github.com/StarRocks/starrocks/files/7923772/be1_pstack.log)
[be2_pstack.log](https://github.com/StarRocks/starrocks/files/7923773/be2_pstack.log)
[be3_pstack.log](https://github.com/StarRocks/starrocks/files/7923774/be3_pstack.log)
[be4_pstack.log](https://github.com/StarRocks/starrocks/files/7923776/be4_pstack.log)
[fe_pstack.log](https://github.com/StarRocks/starrocks/files/7923777/fe_pstack.log)

**Comment by stdpain** [comment]
No useful information from the logs, it looks like the brpc was backed up with too many tasks in the queue at one point. you could reduce config `brpc_number_of_concurrent_requests_processed`

**Comment by yaystrong** [comment]
I reduced brpc_number_of_concurrent_requests_processed to 512, 1024, 2048 respectively, this error situation did not improve. And when the configuration is 512, when BE executes to 50 concurrency (previously it was 300 concurrency), the earlier prompt "_rq is full"

**Comment by stdpain** [comment]
pipeline engine will solve this problem
