### ISSUE TITLE
Created user cannot connect with Database in the connection.

### ISSUE THREAD

**Issue by smithaps89** [StarRocks/starrocks#29985]
### Steps to reproduce the behavior (Required)
1. CREATE DATABASE test;
2. CREATE TABLE test.`test` (`created_at` datetime NOT NULL, `id` varchar(36) NOT NULL );
3. CREATE USER 'foo'@'%' identified by 'foo_pass';
4. GRANT SELECT ON test.test TO 'foo'@'%';
5. Try and connect to database with the foo user
  - mysql -h <IP_ADDRESS> -P 9030 -u foo -p'foo_pass' test -e 'select * from test.test;'
  - ERROR 1064 (HY000): Access denied; you need (at least one of) the ANY privilege(s) on DATABASE test for this operation
6. It does work if you connect without the database
  - mysql -h <IP_ADDRESS> -P 9030 -u foo -p'foo_pass' -e 'select * from test.test;'

### Expected behavior (Required)
User should be able to connect to database to execute select statements.

### Real behavior (Required)
User cannot connect to database and must leave it off of the connection string.

### StarRocks version (Required)
 - 3.1.1-e0229632f9

**Comment by smithaps89** [comment]
Appears to be related to https://github.com/StarRocks/starrocks/issues/29851 as well

**Comment by jaogoy** [comment]
Is it normal to deny the connection without the privilege on the database test?

**Comment by HangyuanLiu** [comment]
https://github.com/StarRocks/starrocks/pull/29767 has resolved

**Comment by smithaps89** [comment]
By granting `SELECT ON test.test TO 'foo'@'%';` to the foo user it gets rights to connect to the database. An example showing this with mysql

Start up mysql server
```
docker run -e MYSQL_ALLOW_EMPTY_PASSWORD=true -p 3306:3306 mysql:5.7
```

Then run table creates and commands from this issue.
```
mysql -h 127.0.0.1 -u root

CREATE DATABASE test;
CREATE TABLE test.test (created_at datetime NOT NULL, id varchar(36) NOT NULL );
CREATE USER 'foo'@'%' identified by 'foo_pass';
GRANT SELECT ON test.test TO 'foo'@'%';
```

Now trying to connect as this foo user works fine.
```
$  mysql -h 127.0.0.1 -u foo -p'foo_pass' test -e 'select count(*) from test.test;'
mysql: [Warning] Using a password on the command line interface can be insecure.
+----------+
| count(*) |
+----------+
|        0 |
+----------+
```

**Comment by smithaps89** [comment]
FYI I just tested this on v3.1.2 and it appears its fixed 💯 

```
$  mysql -h 127.0.0.1 -P 9030 -u foo -p'foo_pass' test -e 'select count(*) from test.test;'
mysql: [Warning] Using a password on the command line interface can be insecure.
+----------+
| count(*) |
+----------+
|        0 |
+----------+

$  mysql -h 127.0.0.1 -P 9030 -u foo -p'foo_pass' test -e 'show variables like "%version%";'
mysql: [Warning] Using a password on the command line interface can be insecure.
+-----------------+------------------+
| Variable_name   | Value            |
+-----------------+------------------+
| version         | 5.1.0            |
| version_comment | 3.1.2-4f3a2ee91b |
+-----------------+------------------+
```
