### ISSUE TITLE
Starrocks external catalog schema metadata in Metabase UI

### ISSUE THREAD

**Issue by williamho123** [StarRocks/starrocks#29989]
Hello! I have deployed a shared-data Starrocks cluster, created an external Hive catalog (AWS Glue), and am linking it with Metabase (BI tool). My understanding is that I can use the MySQL connection to link Metabase with Starrocks. When I setup the connection, I setup the database to be like `<catalog_name>.<db_name>`. With this, I can run queries perfectly in a raw Metabase SQL editor.

However, I would like Metabase to be able to display the tables in the database using the visual editor — currently, it shows a blank page like this:

![Screenshot 2023-08-25 at 3 04 09 PM](https://github.com/StarRocks/starrocks/assets/23107175/8c156d04-0329-4546-be73-2bf5a3a67190)

- I’m not sure if there’s something I am missing for this to happen? 
- Does it have to do with where the schema metadata is stored by Starrocks and where MySQL clients try to retrieve that information? 
 
My guess is BI tools like Metabase query the `information_schema` database to get the metadata about db's and tables, and external catalog metadata is not stored there currently.

**Comment by imay** [comment]
https://github.com/StarRocks/starrocks/pull/27359
This has been fixed in the main branch, and will be released in version 3.2
