### ISSUE TITLE
docker run starRocks，FE service query port is NOT alive yet

### ISSUE THREAD

**Issue by yusiwen123** [StarRocks/starrocks#29990]
### Steps
1. pull imags ```docker pull starrocks/allin1-ubuntu:latest```
2. run container ```docker run -p 19030:9030 -p 18030:8030 -p 18040:8040 -itd --name starrocks docker.io/starrocks/allin1-ubuntu:latest```
3. connect failed ```mysql -P19030 -h127.0.0.1 -uroot --prompt="StarRocks > "```

got docker container  log:

![image](https://github.com/StarRocks/starrocks/assets/26161327/80d3faac-278e-4a96-b0e3-0df1d031b563)

Entered the Docker image and checked the fe.out log and Java commands,  reporting insufficient memory for any operation.The following is the hs_err_pid.log file.

![image](https://github.com/StarRocks/starrocks/assets/26161327/dcd08960-d11b-4f7c-af2b-2e2a66961308)
![image](https://github.com/StarRocks/starrocks/assets/26161327/ba780aea-5a2b-4868-ad9f-6750d61f66ae)

But the server's memory is sufficient.

![image](https://github.com/StarRocks/starrocks/assets/26161327/6b70b86c-7da9-4794-8adc-fcf29e7c23c4)
![image](https://github.com/StarRocks/starrocks/assets/26161327/265f5204-85c0-4b63-be9b-e7f174fa9844)

### Question
How should I continue to troubleshoot this issue?

**Comment by kevincai** [comment]
interesting, not only the FE component was not started, but also the broker and BE service.

Can you pull the broker log at `/data/deploy/starrocks/apache_hdfs_broker/log` and be log at `/data/deploy/starrocks/be/log`, check if there is more information about the crash.

**Comment by yusiwen123** [comment]
> interesting, not only the FE component was not started, but also the broker and BE service.
> 
> Can you pull the broker log at `/data/deploy/starrocks/apache_hdfs_broker/log` and be log at `/data/deploy/starrocks/be/log`, check if there is more information about the crash.

 `/data/deploy/starrocks/apache_hdfs_broker/log` 
just like the FE component, it's the same JVM error.

![image](https://github.com/StarRocks/starrocks/assets/26161327/e6cd0916-0ecf-4177-804d-4030291d886f)

`/data/deploy/starrocks/be/log`

![image](https://github.com/StarRocks/starrocks/assets/26161327/3bd112e3-5946-4001-8431-70715fd9a2e3)

**Comment by kevincai** [comment]
did you inject a different JAVA_HOME env?

**Comment by yusiwen123** [comment]
> did you inject a different JAVA_HOME env?

This is the official docker image. I didn't do any changes。

**Comment by kevincai** [comment]
can you get the starrocks/allin1-ubuntu:latest image digest (the sha256), I need to confirm the exact version of the image?

![image](https://github.com/StarRocks/starrocks/assets/771299/19f062cc-b1b5-4e07-8ae5-c1d9ec9327fe)

Also this log is suspecious, if with the default JAVA_HOME=/lib/jvm/default-java, the libjvm.so can be found at `/lib/jvm/default-java/lib/server/libjvm.so`, shouldn't report the file not found.

**Comment by yusiwen123** [comment]
> can you get the starrocks/allin1-ubuntu:latest image digest (the sha256), I need to confirm the exact version of the image?
> 
> ![image](https://user-images.githubusercontent.com/771299/263597136-19f062cc-b1b5-4e07-8ae5-c1d9ec9327fe.png)
> 
> Also this log is suspecious, if with the default JAVA_HOME=/lib/jvm/default-java, the libjvm.so can be found at `/lib/jvm/default-java/lib/server/libjvm.so`, shouldn't report the file not found.

Of course, i got the sha256 from docker: 
```sha256:88b810a4000b56dc0e112f8f7736696cea45ec06afe30eac3f2cbaf530919164```

In additiion, the ```/lib/jvm/default-java/lib/server/libjvm.so``` can be found.

![image](https://github.com/StarRocks/starrocks/assets/26161327/ac3f33fa-72f0-4447-90e4-5921ab93fa1d)

**Comment by kevincai** [comment]
can you login to the container and collect following information

1. uname -a
2. ulimit -a
3. env (necessary filtering or masking if there is any sensitive information)

**Comment by yusiwen123** [comment]
> can you login to the container and collect following information
> 
> 1. uname -a
> 2. ulimit -a
> 3. env (necessary filtering or masking if there is any sensitive information)

1. uname -a
```
Linux fd4029f4feec 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
2. ulimit -a
```
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) unlimited
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 256282
max locked memory           (kbytes, -l) 64
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1048576
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) unlimited
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```
3. env
```
HOSTNAME=fd4029f4feec
JAVA_HOME=/lib/jvm/default-java
PWD=/data/deploy
HOME=/root
SR_HOME=/data/deploy/starrocks
TERM=xterm
SHLVL=1
PATH=/usr/lib/linux-tools/5.15.0-60-generic:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
```

**Comment by kevincai** [comment]
Interesting, is it proper to get in touch in person and have a live meeting for this?

**Comment by yusiwen123** [comment]
> Interesting, is it proper to get in touch in person and have a live meeting for this?

sure

**Comment by yusiwen123** [comment]
> Interesting, is it proper to get in touch in person and have a live meeting for this?

Sure, could you mind sending your WeChat or another personal contact information to my email? email: 18702515518@163.com

**Comment by yusiwen123** [comment]
Thanks, I can now use it normally.

**Comment by LinMingQiang** [comment]
```docker run -p 9030:9030 -p 8030:8030 -p 8040:8040 --security-opt seccomp=unconfined -itd --name quickstart starrocks/allin1-ubuntu```
is  still meet this err

**Comment by kevincai** [comment]
@LinMingQiang please open a new issue and paste the logs/error messages.

**Comment by qianyiwen2019** [comment]
I met this error too. with --security-opt seccomp=unconfined
