### ISSUE TITLE
JDBC Catalogs for ORacle

### ISSUE THREAD

**Issue by jacopoberetta95** [StarRocks/starrocks#30061]
Good morning, 

i would like to configure External JDBC catalog for oracle.
In StarRocks v.3.1.1 documentation i see that "JDBC catalogs currently support MySQL and PostgreSQL"

Is possible to provide support even for oracle?

**Comment by c-thiel** [comment]
+1 for Oracle and SQL-Server.
Are there already plans to extend the JDBC Catalog to other Databases?
