### ISSUE TITLE
异步物化视图能够控制先后顺序

### ISSUE THREAD

**Issue by happyi** [StarRocks/starrocks#30114]
## Feature request

**Is your feature request related to a problem? Please describe.**
使用异步物化视图做数仓分成的时候，期望下层跑完再去跑上层。

**Describe the solution you'd like**
异步物化视图能够控制先后顺序

**Comment by mofeiatwork** [comment]
- You could create the MV with `MANUAL` refresh, and schedule it with a outside scheduler like Airflow
- Builtin scheduling is not supported, but on the roadmap
