### ISSUE TITLE
版本升级到3.1.1后报错

### ISSUE THREAD

**Issue by hophiya** [StarRocks/starrocks#30118]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Expected behavior (Required)
the database upgrade from 3.0.2 to 3.1.1
all most everything runs OK,but a ccount cannot connect

### Real behavior (Required)
after upgrade,the user cannot connect StarRocks database:
Access denied; you need (at least one of) the ANY privilege(s) on DATABASE tmp for this operation

error message:
![image](https://github.com/StarRocks/starrocks/assets/120696271/1fc5e6a2-842a-46d0-9110-9933e580f970)
create test user as follow:
CREATE USER 'test_user'@'%' IDENTIFIED BY '123456';
grant all privileges on all MATERIALIZED VIEWS in database tmp to 'test_user'@'%';
grant all privileges on all VIEWS in database tmp to 'test_user'@'%';
grant all privileges on all tables in database tmp to 'test_user'@'%';

check the user privileges:
MySQL [(none)]> show grants for test_user;
+-----------------+-----------------+-----------------------------------------------------------------------------------------------------------------+
| UserIdentity    | Catalog         | Grants                                                            |
+-----------------+-----------------+-----------------------------------------------------------------------------------------------------------------+
| 'test_user'@'%' | default_catalog | GRANT DELETE, DROP, INSERT, SELECT, ALTER, EXPORT, UPDATE ON ALL TABLES IN DATABASE tmp TO USER 'test_user'@'%' |
| 'test_user'@'%' | default_catalog | GRANT SELECT, ALTER, DROP ON ALL VIEWS IN DATABASE tmp TO USER 'test_user'@'%'                                  |
| 'test_user'@'%' | default_catalog | GRANT ALTER, REFRESH, DROP, SELECT ON ALL MATERIALIZED VIEWS IN DATABASE tmp TO USER 'test_user'@'%'            |

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
3.1.1-e0229632f9

**Comment by happyi** [comment]
要加一个表操作权限

**Comment by hophiya** [comment]
> 要加一个表操作权限

这里具体是加什么权限呢，上面有授权语句：
grant all privileges on all tables in database tmp to 'test_user'@'%';

而且查看权限也是有表操作权限的：
| 'test_user'@'%' | default_catalog | GRANT DELETE, DROP, INSERT, SELECT, ALTER, EXPORT, UPDATE ON ALL TABLES IN DATABASE tmp TO USER 'test_user'@'%' |

**Comment by happyi** [comment]
加一个 这个 权限  GRANT CREATE VIEW, CREATE FUNCTION, CREATE MATERIALIZED VIEW ON ALL DATABASES TO USER 'xxx'@'%'

**Comment by Oloong** [comment]
有这么严重的问题，就要在官方上建议不要升级此版本！！！

**Comment by hophiya** [comment]
经确认在3.1.2版本已解决此问题，
当前版本规避方案确如上所说，通过授权 CREATE FUNCTION on database后解决（有一定权限扩大风险，但可控）
