### ISSUE TITLE
when  I update the version from 2.4 to 3.0.5: Column 'URL' not found.

### ISSUE THREAD

**Issue by laglangyue** [StarRocks/starrocks#30123]
### Steps to reproduce the behavior (Required)

when  I update the version from 2.4 to 3.0.5,use broker load to import data，and execute query sql

    val sql =
      s"""
         |SHOW LOAD
         |FROM $database
         |WHERE LABEL = "$label"
         |ORDER BY CREATETIME DESC LIMIT 1
         |""".stripMargin

### Expected behavior (Required)

Unregistering ApplicationMaster with FAILED (diag message: User class threw exception: java.sql.SQLException: Column 'URL' not found.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by jaogoy** [comment]
@laglangyue Can you give more info? Maybe, it's about the case-sensitive? I guess

**Comment by laglangyue** [comment]
> @laglangyue Can you give more info? Maybe, it's about the case-sensitive? I guess

I asked a Starrock DBA and he said that the new version does not support this parameter, but the document has not been updated
