### ISSUE TITLE
how  to run an unit test on time_function_test.cpp

### ISSUE THREAD

**Issue by superdiaodiao** [StarRocks/starrocks#30186]
When I want to test the time_function_test.cpp file, it cannot pass. 
Then I followed the error info and  looked into this file(path: starrocks/be/src/runtime/runtime_state.h) in VScode, it shows that it include these three files
(FrontendService.h, InternalService_types.h, Types_types.h) , but actually I can't find any of them or install the package by VCPKG.

If I can't get this over, I can't run a unit test either, so it means a lot.
Thanks~

![image.png](https://github.com/StarRocks/starrocks/assets/42577861/3c0ef635-1db0-4cf8-811e-9c5ea5cfe9d4)

![image-1.png](https://github.com/StarRocks/starrocks/assets/42577861/70d156a2-fbe0-4895-aa09-0d0ac8797aac)

**Comment by kevincai** [comment]
these are auto generated files from thrift, if you run build.sh or run-be-ut.sh, it will do the necessary make and generating.

**Comment by superdiaodiao** [comment]
> these are auto generated files from thrift, if you run build.sh or run-be-ut.sh, it will do the necessary make and generating.

Do you mean that I have to compile the whole project to generate these files before I run a unit test?

If so, which path will these file exist?

**Comment by kevincai** [comment]
under `./gensrc/build/gen_cpp/` from the root of the source code repo

**Comment by superdiaodiao** [comment]
> under `./gensrc/build/gen_cpp/` from the root of the source code repo

ok, I will ckeck it, thx
