### ISSUE TITLE
JDBC CATALOG 不支持bigint unsigned类型

### ISSUE THREAD

**Issue by Oloong** [StarRocks/starrocks#30249]
### Steps to reproduce the behavior (Required)
1. CREATE EXTERNAL CATALOG mysql07
PROPERTIES
(
    "type"="jdbc",
    "user"="bg",
    "password"="XXXXXXXX",
    "jdbc_uri"="jdbc:mysql://*.*.*.*:3306",
    "driver_url"= "file:///data/starrocks/deploy/be/lib/jdbc_drivers/mysql-connector-java-5.1.49.jar",
    "driver_class"="com.mysql.jdbc.Driver"
);
use mysql07.mydb;
找个id为 bigint unsigned 表 tb
select * from tb a limit 1000
查询报错
### Expected behavior (Required)
不报错，正常查询
### Real behavior (Required)
1064 - Type is not supported on column[id], JDBC result type is [java.math.BigInteger]
不支持 bigint unsigned
### StarRocks version (Required)
StarRocks V3.1.2
mysql 5.7.39

**Comment by jaogoy** [comment]
SR doesn't support unsighed bigint, but I think SR can use LargeInt instead.

**Comment by Hoxxx** [comment]
> SR doesn't support unsighed bigint, but I think SR can use LargeInt instead.

后续有计划支持吗？
