### ISSUE TITLE
增强sql审计功能

### ISSUE THREAD

**Issue by Qu-zhiqiang** [StarRocks/starrocks#30262]
## Enhancement
目前非查询sql，在审计日志中并没有cpu，内存，扫描行等等详细信息，都是0，希望可以增强这一块功能，完善一下, 不然不方便进行资源占用的量化。
![e94b4dce0c4a15c278353893a0583eb](https://github.com/StarRocks/starrocks/assets/125423890/792a7156-84e9-4444-8b41-2941b9d44336)

**Comment by ZiheLiu** [comment]
Fixed by #29901 and #30663, which are cherry-pick to branch-2.5~branch-3.2. Could try use it.
