### ISSUE TITLE
日志格式无法更改

### ISSUE THREAD

**Issue by Alexios-cd** [StarRocks/starrocks#30283]
### Steps to reproduce the behavior (Required)
1. 默认的日志存储在 be.INFO.log.2023xxx-xxx，打印内容为：I0901 11:27:08.965626 23134 daemon.cpp:188] Current memory statistics:……
2. 可以看出默认的日志里面是没有 年月日的，
3. 修改 be/conf/log4j.properties 中的 log4j.appender.stdout.layout.ConversionPattern=%5p [%t] (%F:%L) - %m%n 修改为 ：log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %5p [%t] (%F:%L) - %m%n
4. 在be/log/be.INFO.log.2023xxx-xxx 文件中日志格式依然没有变化，还是原来的格式 I0901 11:27:08.965626 23134 daemon.cpp:188] Current memory statistics:……

### Expected behavior (Required)
在官方的文档中也没有找到可以更改日志格式的位置，其实就是想在每一条日志内容前面加上年月日，方便排查问题。
### Real behavior (Required)
希望官方可以提供更改日志日式的方法，包含fe和be
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.5.11 b75b46d

**Comment by kevincai** [comment]
be.INFO, `I0901` 表示`月日`信息.

**Comment by Alexios-cd** [comment]
> be.INFO, `I0901` , `I`表示loglevel为INFO, `0901`表示`9月1日`

日志格式有方法自定义吗？

**Comment by kevincai** [comment]
not for now, you can submit a PR to support customized log format if needed.

**Comment by Alexios-cd** [comment]
> not for now, you can submit a PR to support customized log format if needed.

Thank you very much for your patient guidance.
