### ISSUE TITLE
The BE image is too large because starrocks_be.debuginfo file have been added

### ISSUE THREAD

**Issue by Jin-H** [StarRocks/starrocks#30291]
### Steps to reproduce the behavior (Required)
1.  docker pull starrocks/be-ubuntu:3.1.2
2. using  dive tool analyze  starrocks/be-ubuntu:3.1.2 images with command `dive starrocks/be-ubuntu:3.1.2`
3. find large file starrocks_be.debuginfo 
![6e14e0775b6b09440a7f112930f1cdb](https://github.com/StarRocks/starrocks/assets/16933180/d05de7db-6b03-40cc-92f8-48fe514ab035)
4. Compile the image with the following Dockerfile, starrocks can start and query table info.
```Dockerfile
FROM starrocks/be-ubuntu:3.1.2 AS builder

RUN rm -rf /opt/starrocks/be/lib/starrocks_be.debuginfo

FROM eclipse-temurin:11-jdk-jammy

COPY --from=builder /opt/starrocks/ /opt/starrocks/


ARG STARROCKS_ROOT=/opt/starrocks


RUN apt-get update -y && apt-get install -y --no-install-recommends binutils-dev python2 mysql-client curl vim tree net-tools less tzdata linux-tools-common linux-tools-generic && ln -fs /usr/share/zoneinfo/UTC /etc/localtime && dpkg-reconfigure -f noninteractive tzdata && rm -rf /var/lib/apt/lists/*

RUN touch /.dockerenv

WORKDIR $STARROCKS_ROOT



ARG USER=starrocks
ARG GROUP=starrocks
RUN groupadd --gid 1000 $GROUP && useradd --no-create-home --uid 1000 --gid 1000 \
             --shell /usr/sbin/nologin $USER  && \
                 chown -R $USER:$GROUP $STARROCKS_ROOT

USER $USER

COPY --chown=starrocks:starrocks *.sh $STARROCKS_ROOT/

# Create directory for BE storage, create cn symbolic link to be
RUN mkdir -p $STARROCKS_ROOT/be/storage && ln -sfT be $STARROCKS_ROOT/cn && chmod 777 $STARROCKS_ROOT/*.sh


USER root
```

### Expected behavior (Required)
I think release image should not contains starrocks_be.debuginfo.
This file is not included in StarRocks 3.0.x versions

### Real behavior (Required)
starrocks_be.debuginfo was add in /opt/starrocks/be/lib directory

### StarRocks version (Required)
 - 3.1.2、3.1.1、3.1.0

**Comment by Jin-H** [comment]
I found the debuginfo file is added in this pr https://github.com/StarRocks/starrocks/pull/24442

**Comment by kevincai** [comment]
it is not the debuginfo not exist in 3.0.x release, it is just not separated. in 3.1.x the debuginfo is separated from the starrocks_be file, and can be deleted safely.

You can check the previous image, the `starrocks_be` binary is pretty large in comparison to current 200+ MB with debuginfo splitted.

**Comment by Jin-H** [comment]
I'm sorry, I'm not very good at c++, I checked the information, and it is indeed like what you described, the debug information is separated, but I have a question, why should the debug information be kept in the release version? In my usage scenario, the image cannot exceed 5G, so can the official launch an image that does not contain debuginfo?

**Comment by kevincai** [comment]
your dockerfile looks good. we are thinking about removing the debuginfo from the final image as well.

the debuginfo is pretty useful for us to analysis whenever there is a crash.

**Comment by Jin-H** [comment]
I tested it with the dockerfile posted above, and the functions is OK.

thanks for reply.

**Comment by kevincai** [comment]
try to remove the debuginfo in #30335
