### ISSUE TITLE
starrocks/thirdparty/build-thirdparty.sh : build brpc; cmake -v; Unknown argument -v

### ISSUE THREAD

**Issue by mklzl** [StarRocks/starrocks#303]
Compile environment

    cmake version : 3.21.2
    linux : centos 7.6
****
This error occurs when I use the build.sh
    
    CMake Error: Unknown argument -v

I didn't find this parameter  '-v' in the official documentation for cmake

And I removed this parameter from build-thirdparty.sh and successfully compiled BRPC

    $CMAKE_CMD  -DBUILD_SHARED_LIBS=0 -DCMAKE_INSTALL_PREFIX=$TP_INSTALL_DIR \
    -DBRPC_WITH_GLOG=ON -DWITH_GLOG=ON -DCMAKE_INCLUDE_PATH="$TP_INSTALL_DIR/include" \
    -DCMAKE_LIBRARY_PATH="$TP_INSTALL_DIR/lib;$TP_INSTALL_DIR/lib64" \
    -DProtobuf_PROTOC_EXECUTABLE=$TP_INSTALL_DIR/bin/protoc ..

Am I using it incorrectly?

**Comment by imay** [comment]
@mklzl I think you're right, can you create an pull request to fix it?

**Comment by mklzl** [comment]
ok.



---Original---
From: "Zhao ***@***.***&gt;
Date: Sat, Sep 18, 2021 09:22 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [StarRocks/starrocks] starrocks/thirdparty/build-thirdparty.sh : build brpc; cmake -v; Unknown argument -v (#303)




 
@mklzl I think you're right, can you create an pull request to fix it?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mklzl** [comment]
fix it on #305
