### ISSUE TITLE
Materialized view supports kafka？

### ISSUE THREAD

**Issue by melin** [StarRocks/starrocks#30340]
Materialized view supports kafka? Similar to redshift materialized view feature：
https://aws.amazon.com/cn/blogs/china/new-for-amazon-redshift-general-availability-of-streaming-ingestion-for-kinesis-data-streams-and-managed-streaming-for-apache-kafka/

**Comment by mofeiatwork** [comment]
it's not supported, since you cannot perform a `select` on top the kafka source.
