### ISSUE TITLE
V2.1 Release plan 

### ISSUE THREAD

**Issue by Dshadowzh** [StarRocks/starrocks#3035]
### New Features
- 【Preview】Iceberg external table is supported. (#1030)
- 【Preview】Pipeline engine released, a new execution engine designed for multicore scheduling. Adaptive parallelism mechanism, no need to set parallel_fragment_exec_instance_num manually, also improve performance in high concurrency scenario.(sig/pipeline)
- CTAS(Create Table As Select) is supported, making ETL and table creation easier.(#1125 )
- SQL fingerprint is supported, generate fingerprint in audit.log when slowquery.

### Improvement
- Optimize compaction, flat-table is up to 10000 columns.
- Optimize first-time scan(for cold query) and pagecahce(for warm query). Reduce random I/O in scanning, especially in SATA disk. Support bitshuffle in pagecache to avoid unnecessary decompress.
- Schema change in the primary key model is supported. You can add bitmap index or change column type by `alter table`.
- 【Preview】String size is up to 1MB.
- Optimize JSON load performance. You can load more than 100MB at a time.
- Optimize scan performance and support csv format for hive external table.
- Multi delimiter when csv loading is supported.

### Behavior Changes
- API for disabling colocated join: change DELETE /api/colocate/group_stable to POST /api/colocate/group_unstable.

**Comment by caneGuy** [comment]
may be this feature? https://github.com/StarRocks/starrocks/issues/1873 @Dshadowzh

**Comment by Dshadowzh** [comment]
Released

**Comment by Dshadowzh** [comment]
Final release notes: https://github.com/StarRocks/starrocks/releases/tag/2.1.0
