### ISSUE TITLE
Streamload can not delete records in a primary key model table by PK

### ISSUE THREAD

**Issue by arthurcommon** [StarRocks/starrocks#30360]
hi developers,
We found that streamload can not delete records in a primary key  model table by PK. 

for example:
my_test ( id int pk, name varchar(10), addr varchar(100)) (primary key model)

if i want to delete  id=1, i must supply the whole record values , such as (1,'testA','test addr').

Why i can't delete id=1 by only supply id values to streamload ?

**Comment by jaogoy** [comment]
Have you set the parameter `partial_update:true` in the Stream Load?

**Comment by arthurcommon** [comment]
> Have you set the parameter `partial_update:true` in the Stream Load?

Yes. I do have set this parameter. So I want developers to fix this bug. Or to add a new feature that is streamload can delete record in a PK model table by PKs. Thanks a lot
