### ISSUE TITLE
starrocks create catalog hive error

### ISSUE THREAD

**Issue by smallcattle** [StarRocks/starrocks#30426]
ERROR 1064 (HY000): Unexpected exception: Failed to fetch current notification event id, msg: Unable to instantiate com.starrocks.connector.hive.HiveMetaStoreThriftClient

### Steps to reproduce the behavior (Required)
 CREATE EXTERNAL CATALOG hive_catalog
PROPERTIES ("type"  =  "hive",
"hive.metastore.uris"  =  "thrift://bigdata1.com:9083");

hive:2.1.1
hadoop：Hadoop 3.0.0-cdh6.3.2
starrocks:3.0.1 a1f411b
kerberos:hive enabled ,hadoop
### Expected behavior (Required)
create external catalog hive:it can visits hive metastore data

### Real behavior (Required)
ERROR 1064 (HY000): Unexpected exception: Failed to fetch current notification event id, msg: Unable to instantiate com.starrocks.connector.hive.HiveMetaStoreThriftClient
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
3.0.1 a1f411b

**Comment by stephen-shelby** [comment]
Do you use the hive event listener to sync metadata?  maybe you could disable the event sync by  setting "enable_hms_events_incremental_sync" = "false" to the $FE_HOME/conf/fe.conf.  https://docs.starrocks.io/en-us/latest/data_source/catalog/hive_catalog#step-2-enable-automatic-incremental-update-on-starrocks

**Comment by alberttwong** [comment]
Also we need FE and BE logs.
