### ISSUE TITLE
When i  use shared-data StarRocks, and my data be stored in HDFS,I found many small files on HDFS，Can it be merged automatically?

### ISSUE THREAD

**Issue by tuoluzhe8521** [StarRocks/starrocks#30465]
i load data from kafka to starrocks and my table is a a large width table。
### Steps to reproduce the behavior (Required)

CREATE ROUTINE LOAD tableName ON table
PROPERTIES
(
    "desired_concurrent_number" = "3",
    "format" = "json",
   "strict_mode" = "false"
 )
FROM KAFKA
(
"kafka_broker_list" = "xxxxx:9092",
"kafka_topic" = "xxxx",
"kafka_partitions" = "0,1,2"
);
### Expected behavior (Required)
When load data into hdfs, small files can be merged automatically on a scheduled basis
### Real behavior (Required)
I am using a large wide table with over 900 columns 
I found that over 10000 small files were generated within two days, which will affect HDFS performance in the future
### StarRocks version (Required)
 - starrocks-3.0.4

**Comment by kevincai** [comment]
yes, the files will be compacted into large ones. the final number of files depends on the bucket number for the table and number of partitions, linear to total number of tablets.
