### ISSUE TITLE
Enhancement: Avoid creating thread when concurrently creating partitions.

### ISSUE THREAD

**Issue by sduzh** [StarRocks/starrocks#30475]
## Refactoring request

In the current implementation, a new thread is created when concurrently creating partitions to simplify timeout handling logic.
https://github.com/StarRocks/starrocks/blob/0ae18c0de0b575560f98288f0ee582d6887d3d32/fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java#L1888

If there are many table creation tasks in the system, this can lead to resource overuse. It should be avoided as much as possible.

**Comment by sduzh** [comment]
> Hi, I'm new here. I'd like to do this task

Hi @XinzhuangL, no problem, I would be glad to assign this issue to you! Please go ahead and and let me know if you have any other questions. Looking forward to your solution, thanks!

**Comment by XinzhuangL** [comment]
Simply, I created a thread pool  to avoid resource overuse.  Temporarily set 8 sizes, I don't have any experience on how to set the size. And I'm not sure if I fully understand what you mean ?  could you give me some advice.
