### ISSUE TITLE
Code and docs for Promethus and Grafana out of date

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#30507]
Hey Colleagues! I am comparing metrics described  - https://docs.starrocks.io/en-us/latest/administration/Monitor_and_Alert and what my cluster nodes are really producing and pushing to Prometeus/Grafana and it is a slightly different list. Some are missing in the doc, some are prefixed starrocks_ in Grafana but not in the doc, some are missing in Grafana. Is this an issue or outdated documentation? Cluster is on 3.1, Checking docs for 3.1. Thanks!

**Comment by mcgray** [comment]
As I was the one who posted that in Slack adding some details. Metrics produced by FE and BE /metrics endpoints are not reflected in documentation and I would work on pull request to change that. Along with StarRocks metrics for BE we see also `fslib` and other third party metrics. I am mostly interested in how can we use those.
