### ISSUE TITLE
Stream Load produces inconsistent responses

### ISSUE THREAD

**Issue by mcgray** [StarRocks/starrocks#30602]
### Steps to reproduce the behavior (Required)

When working with Stream Load the responses could look like:

```
{
    "TxnId": 1935,
    "Label": "1d4e0784-50c1-4e21-a9f4-3fc0134aab7a",
    "Status": "Success",
    "Message": "OK",
    "NumberTotalRows": 3233,
    "NumberLoadedRows": 3233,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 9999699,
    "LoadTimeMs": 5397,
    "BeginTxnTimeMs": 1,
    "StreamLoadPlanTimeMs": 2,
    "ReadDataTimeMs": 18,
    "WriteDataTimeMs": 5369,
    "CommitAndPublishTimeMs": 24
}
```
OR in some cases 

` {"status":"FAILED","msg":"There is no 100-continue header"}`

I presume this is happening that responses above from BE and FE nodes and the codebase there is different. 

### Expected behavior (Required)
Same fields user for status and message. 

### Real behavior (Required)
See above. 

### StarRocks version (Required)
3.1

**Comment by alberttwong** [comment]
What is the commands you executed to generate those responses.

**Comment by mcgray** [comment]
This is a generic case of Stream Load. Nothing special, everything based on https://docs.starrocks.io/en-us/latest/sql-reference/sql-statements/data-manipulation/STREAM%20LOAD. The error is due to network infra changes that caused HTTP headers to be dropped. It is just causing our response parser to crash on top of having an error.

**Comment by jaogoy** [comment]
@mcgray Maybe, it worthes to have a look.

**Comment by mcgray** [comment]
@jaogoy I am sorry, would you like me to take a look at something?
