### ISSUE TITLE
动态分区无法自动创建

### ISSUE THREAD

**Issue by amarantine-yu** [StarRocks/starrocks#3067]
### Steps to reproduce the behavior (Required)
1. 创建动态分区
DROP TABLE REALS.RT_PROD_INST_ORD_INFO_Z;
CREATE TABLE REALS.RT_PROD_INST_ORD_INFO_Z (
ETL_DT DATETIME
,PROD_ORDER_ITEM_ID BIGINT
,CUST_ORDER_ID BIGINT

)
UNIQUE KEY(ETL_DT,PROD_ORDER_ITEM_ID)
PARTITION BY RANGE(ETL_DT)(
PARTITION p20220121 VALUES LESS THAN ("2022-01-22"),
PARTITION p20220122 VALUES LESS THAN ("2022-01-23"),
PARTITION p20220123 VALUES LESS THAN ("2022-01-24"),
PARTITION p20220124 VALUES LESS THAN ("2022-01-25")
)
DISTRIBUTED BY HASH(ETL_DT,PROD_ORDER_ITEM_ID) BUCKETS 32
PROPERTIES(
    "dynamic_partition.enable" = "true",
    "dynamic_partition.time_unit" = "DAY",
    "dynamic_partition.start" = "-30",
    "dynamic_partition.end" = "30",
    "dynamic_partition.prefix" = "p",
    "dynamic_partition.buckets" = "32"
);
2. 查看分区信息
SHOW PARTITIONS FROM REALS.RT_PROD_INST_ORD_INFO_Z;

35245310	p20220121	1	2022-01-25 09:38:00	0	NORMAL	ETL_DT	[types: [DATETIME]; keys: [0000-01-01 00:00:00]; ..types: [DATETIME]; keys: [2022-01-22 00:00:00]; )	ETL_DT, PROD_ORDER_ITEM_ID	32	3	HDD	9999-12-31 23:59:59	(null)
35245311	p20220122	1	2022-01-25 09:38:00	0	NORMAL	ETL_DT	[types: [DATETIME]; keys: [2022-01-22 00:00:00]; ..types: [DATETIME]; keys: [2022-01-23 00:00:00]; )	ETL_DT, PROD_ORDER_ITEM_ID	32	3	HDD	9999-12-31 23:59:59	(null)
35245312	p20220123	1	2022-01-25 09:38:00	0	NORMAL	ETL_DT	[types: [DATETIME]; keys: [2022-01-23 00:00:00]; ..types: [DATETIME]; keys: [2022-01-24 00:00:00]; )	ETL_DT, PROD_ORDER_ITEM_ID	32	3	HDD	9999-12-31 23:59:59	(null)
35245313	p20220124	1	2022-01-25 09:38:00	0	NORMAL	ETL_DT	[types: [DATETIME]; keys: [2022-01-24 00:00:00]; ..types: [DATETIME]; keys: [2022-01-25 00:00:00]; )	ETL_DT, PROD_ORDER_ITEM_ID	32	3	HDD	9999-12-31 23:59:59	(null)

### Expected behavior (Required)
按照解释是会自动创建未来30天的分区

### Real behavior (Required)
实际只创建了初始指定的几个分区

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 2.0.0-GA 2ffdf30

**Comment by Dshadowzh** [comment]
Dynamic_partition table will create the partition day by day, not create future partitions in advance. If you want to build future partitions, you can add historical partitions by `START ("2021-01-01") END ("2021-01-15") EVERY (INTERVAL 1 day)`.

**Comment by jaogoy** [comment]
your understanding sounds more reasonable.
We will discuss the dynamic partition's semantics.
