### ISSUE TITLE
_statistics_.column_statistics getting created with "replication_num" = "1"

### ISSUE THREAD

**Issue by shristi10** [StarRocks/starrocks#31013]
Steps to reproduce the behavior -

    Bring up 6 instances - 3 backend, 3 frontend(where one has envoy proxy set up).
    Connect to any of the frontend nodes and add the remaining 2 observers and 3 backends using below respective commands -
    ALTER SYSTEM ADD FOLLOWER "<fe_host>:<edit_log_port>";
    ALTER SYSTEM ADD BACKEND "<be_host>:<heartbeat_service_port>";

First all the observer nodes were added and then the backend nodes.

The frontend and backend nodes starts showing 3 instance each upon show frontends and show backends

Expected behaviour -
As the frontend and backend nodes are 3 each now, the _statistics_.column_statistics table should have 3 replicas by default, but that is not happening.

Real behaviour -
-- statistics`.column_statistics definition

CREATE TABLE column_statistics (
table_id bigint(20) NOT NULL COMMENT "",
partition_id bigint(20) NOT NULL COMMENT "",
column_name varchar(65530) NOT NULL COMMENT "",
....
) ENGINE=OLAP
PRIMARY KEY(table_id, partition_id, column_name)
DISTRIBUTED BY HASH(table_id, partition_id, column_name) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
);`

Not just column_statistics, but all the tables under statistics db show the same behaviour.

The possible issue that we can have is when the backend node contaning this data goes down, causing this table to become corrupt.

StarRocks version - 3.1.0

**Comment by mcgray** [comment]
Same issue. Stays 1 whatever we do.
