### ISSUE TITLE
After the version was upgraded from 2.5 to 3.0, the account that could be queried in hive catalog before was prompted to have no permissions. Even after following the official documentation, it still could not be solved.

### ISSUE THREAD

**Issue by leiyang0324** [StarRocks/starrocks#31037]
### Steps to reproduce the behavior (Required)

create  role test;
GRANT SELECT ON catalog hive TO ROLE test;
GRANT hive_reader TO USER doris_query@'%'; //doris_query is an existing user who can query hive catalog before

===============================================================================================

CREATE USER jack@'172.10.1.10' IDENTIFIED BY '12345' DEFAULT ROLE 'test';
Only after this is created can hive be queried, which means that the authorization of the old account according to the operation document is invalid.

### Real behavior (Required)
<img width="808" alt="image" src="https://github.com/StarRocks/starrocks/assets/43801168/109c619b-65cf-4e5d-bbf4-cca34e7b6bb2">

### StarRocks version (Required) 2.5.10 -》 3.0.0
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by jaogoy** [comment]
Isn't is a problem?
