### ISSUE TITLE
Create Delta Tables in Metastore

### ISSUE THREAD

**Issue by andreyolv** [StarRocks/starrocks#31130]
## Feature request

**Is your feature request related to a problem? Please describe.**
I have tables in delta format in the azure data lake gen2, but I don't use metastore. And it is not possible to create a delta table in the metastore using StarRocks, only read existing ones.

**Describe the solution you'd like**
Create tables by StarRocks in the metastore pointing to an azure data lake gen2 path where the format is in delta.

**Describe alternatives you've considered**
Use [trino](https://trino.io/docs/current/connector/delta-lake.html#register-table) because it allows this feature.

**Additional context**
I believe it is an important feature for those who want to query in delta but there is no metastore.

**Comment by alberttwong** [comment]
I would suggest that you only use StarRocks as a query (read) engine and let another application/library write the data.
