### ISSUE TITLE
 3.0.6 AuditLoader import failed

### ISSUE THREAD

**Issue by leiyang0324** [StarRocks/starrocks#31232]
### Steps to reproduce the behavior (Required)
java.lang.Exception: status is not TEMPORARY_REDIRECT 307, status: 401, response: {“status”:“FAILED”,“msg”:“Access denied for root@10.xx.xx.xx”}, request is: curl -v -X PUT
-H “Authorization”:“Basic cm9vdDo3YjU4YmRmMWE3YWU0YjI1YWU2MTRiMWE0Zjg5YTlmOCA=”
-H “Expect”:“100-continue”
-H “Content-Type”:“text/plain; charset=UTF-8”
-H “max_filter_ratio”:“1.0”
-H “columns”:“queryId, timestamp, clientIp, user, authorizedUser, resourceGroup, catalog, db, state, errorCode,queryTime, scanBytes, scanRows, returnRows, cpuCostNs, memCostBytes, stmtId, isQuery, feIp, stmt, digest, planCpuCosts, planMemCosts”
"[http://10.201.48.33:8030/api/starrocks_audit_db__/starrocks_audit_tbl__/_stream_load?"](http://10.201.48.33:8030/api/starrocks_audit_db__/starrocks_audit_tbl__/_stream_load?%22)
at com.starrocks.plugin.audit.StarrocksStreamLoader.loadBatch(StarrocksStreamLoader.java:127) ~[?:?]
at com.starrocks.plugin.audit.AuditLoaderPlugin.loadIfNecessary(AuditLoaderPlugin.java:199) ~[?:?]
at com.starrocks.plugin.audit.AuditLoaderPlugin.access$300(AuditLoaderPlugin.java:47) ~[?:?]
at com.starrocks.plugin.audit.AuditLoaderPlugin$LoadWorker.run(AuditLoaderPlugin.java:278) ~[?:?]
at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_321]

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by mofeiatwork** [comment]
Please use the latest table schema for audit:

```sql

CREATE TABLE starrocks_audit_db__.starrocks_audit_tbl__ (
  `queryId` VARCHAR(48) COMMENT "查询的唯一ID",
  `timestamp` DATETIME NOT NULL COMMENT "查询开始时间",
  `queryType` VARCHAR(12) COMMENT "查询类型（query, slow_query）",
  `clientIp` VARCHAR(32) COMMENT "客户端IP",
  `user` VARCHAR(64) COMMENT "查询用户名",
  `authorizedUser` VARCHAR(64) COMMENT "用户唯一标识，既user_identity",
  `resourceGroup` VARCHAR(64) COMMENT "资源组名",
  `catalog` VARCHAR(32) COMMENT "数据目录名",
  `db` VARCHAR(96) COMMENT "查询所在数据库",
  `state` VARCHAR(8) COMMENT "查询状态（EOF，ERR，OK）",
  `errorCode` VARCHAR(96) COMMENT "错误码",
  `queryTime` BIGINT COMMENT "查询执行时间（毫秒）",
  `scanBytes` BIGINT COMMENT "查询扫描的字节数",
  `scanRows` BIGINT COMMENT "查询扫描的记录行数",
  `returnRows` BIGINT COMMENT "查询返回的结果行数",
  `cpuCostNs` BIGINT COMMENT "查询CPU耗时（纳秒）",
  `memCostBytes` BIGINT COMMENT "查询消耗内存（字节）",
  `stmtId` INT COMMENT "SQL语句增量ID",
  `isQuery` TINYINT COMMENT "SQL是否为查询（1或0）",
  `feIp` VARCHAR(32) COMMENT "执行该语句的FE IP",
  `stmt` STRING COMMENT "SQL原始语句",
  `digest` VARCHAR(32) COMMENT "慢SQL指纹",
  `planCpuCosts` DOUBLE COMMENT "查询规划阶段CPU占用（纳秒）",
  `planMemCosts` DOUBLE COMMENT "查询规划阶段内存占用（字节）"
) ENGINE = OLAP
DUPLICATE KEY (`queryId`, `timestamp`, `queryType`)
COMMENT "审计日志表"
PARTITION BY RANGE (`timestamp`) ()
DISTRIBUTED BY HASH (`queryId`) BUCKETS 3 
PROPERTIES (
  "dynamic_partition.time_unit" = "DAY",
  "dynamic_partition.start" = "-30",
  "dynamic_partition.end" = "3",
  "dynamic_partition.prefix" = "p",
  "dynamic_partition.buckets" = "3",
  "dynamic_partition.enable" = "true",
  "replication_num" = "3"
);
```
