### ISSUE TITLE
How to use indicator columns to quickly find dimensions

### ISSUE THREAD

**Issue by johncai0** [StarRocks/starrocks#31295]
My requirement is to select groups of people based on real-time changing indicators for precision marketing.
Because starrocks does not support indexing on indicator columns, searching based on indicator columns is very slow.

I have two needs
1. The indicator column needs to be updated
2. Quick search based on indicator columns

"Unique key table" and "primary key table" are suitable for my update needs, but they cannot meet the needs of fast retrieval of indicator columns.
"Duplicate key table" is suitable for fast retrieval needs, but it cannot meet the needs of indicator column updates.
Based on starrocks, is there any other feasible method for this requirement?

**Comment by imay** [comment]
Did you try the primary key table with an indicator column as a sorted key?
I think it may make your case better

**Comment by johncai0** [comment]
> Did you try the primary key table with an indicator column as a sorted key? I think it may make your case better

Yes, adding the indicator column to the sorting column in the "duplicate key table" can meet the needs of fast retrieval, but it cannot meet the needs of updating the indicator column.
