### ISSUE TITLE
query fail  Memory exceed limit

### ISSUE THREAD

**Issue by chenglong-bigdata** [StarRocks/starrocks#3146]
![1643274032(1)](https://user-images.githubusercontent.com/50446282/151326047-16068848-eb69-4c22-bc11-c2d6ff1e36fd.jpg)

the table have 900+ columns

**Comment by trueeyu** [comment]
the version is 2.0GA?

**Comment by trueeyu** [comment]
the bug has been fixed in 2.0.1
