### ISSUE TITLE
Unable to select from View when underlying table contains generated columns - Column cannot be resolved.

### ISSUE THREAD

**Issue by gerritvanzyl** [StarRocks/starrocks#31514]
### Steps to reproduce the behavior (Required)

DDL for Client Table:

CREATE TABLE `client` (
  `_airbyte_ab_id` varchar(40) NULL COMMENT "",
  `_airbyte_emitted_at` bigint(20) NULL COMMENT "",
  `_airbyte_data` varchar(65533) NULL COMMENT "",
  `client_id` int(11) NULL AS get_json_int(_airbyte_data, '$.id') COMMENT "",
  `id` int(11) NULL AS get_json_int(_airbyte_data, '$.id') COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`_airbyte_ab_id`, `_airbyte_emitted_at`)
DISTRIBUTED BY HASH(`_airbyte_ab_id`) BUCKETS 16 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
);

----Create view on the client table

create view fact as 
select id from client;

----Select from view

select * from fact;

### Expected behavior (Required)

Expected to return id column

### Real behavior (Required)

SQL Error [1064] [42000]: Getting analyzing error. Detail message: Column '`test`.`client`.`id`' cannot be resolved.

### StarRocks version (Required)

 - Version 3.1.3

**Comment by srlch** [comment]
https://github.com/StarRocks/starrocks/pull/31727 FIX PR
