### ISSUE TITLE
distinct * with order by will return error

### ISSUE THREAD

**Issue by even986025158** [StarRocks/starrocks#31579]
### Steps to reproduce the behavior (Required)
1. Create Table: 
CREATE TABLE `olap_01` (
  `event` varchar(65533) NULL COMMENT "",
  `vopenid` varchar(65533) NULL COMMENT "",
  `dteventtime` datetime NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`event`, `vopenid`, `dteventtime`)
COMMENT "OLAP"
PARTITION BY RANGE(`dteventtime`)
(PARTITION p20220418 VALUES [("2022-04-18 00:00:00"), ("2022-04-19 00:00:00")),
PARTITION p20220419 VALUES [("2022-04-19 00:00:00"), ("2022-04-20 00:00:00")),
PARTITION p20220420 VALUES [("2022-04-20 00:00:00"), ("2022-04-21 00:00:00")),
PARTITION p20220421 VALUES [("2022-04-21 00:00:00"), ("2022-04-22 00:00:00")))
DISTRIBUTED BY HASH(`vopenid`) BUCKETS 4 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"compression" = "LZ4"
);

2.  
SELECT
  DISTINCT *
FROM
  olap_01
ORDER BY
  event

### Expected behavior (Required)
return Empty
### Real behavior (Required)
ERROR 1064 (HY000): '`test`.`olap_01`.`event`' must be an aggregate expression or appear in GROUP BY clause

### StarRocks version (Required)
 - 2.5.7

**Comment by jaogoy** [comment]
Isn't it right? there must be a GROUP BY clause to use DISTINCT

**Comment by even986025158** [comment]
> Isn't it right? there must be a GROUP BY clause to use DISTINCT

but when I distinct Specific fields instead of * ,the result is right,and there is no group by clause. I think it not need to a GROUP BY clause to use DISTINCT

**Comment by even986025158** [comment]
> Isn't it right? there must be a GROUP BY clause to use DISTINCT
