### ISSUE TITLE
Unable to load data from Kafka topic to Starrocks table using routine load job.

### ISSUE THREAD

**Issue by satyam679** [StarRocks/starrocks#31599]
## Issue Description
we are encountering an issue when trying to load data from a Kafka topic into a Starrocks table using the HTTP source connector. The problem is that I am receiving all null values in the Starrocks table.

### Steps to reproduce 
1. Created a table alertData
2. Use the HTTP source connector to load data from source to  Kafka topic.
3. Utilize a routine load process to load data from the  Kafka topic into the  StarRocks table.

### Expected behavior 
I expect the data from the Kafka topic to be loaded into the  Starrocks table successfully with the correct values.

### Real behavior 
I am receiving all null values in the "alertData" Starrocks table,
### Environment
- Starrocks version: 3.1.0
- Kafka version: 2.13-3.5.1
- kafka connector : Kafka-http-connector

#### StarRocks Table DDL
 ```sql

 CREATE TABLE IF NOT EXISTS alertData (
    alertId VARCHAR(50),
    eventId VARCHAR(50),
    region VARCHAR(70),
    substation VARCHAR(50),
    transformer VARCHAR(50),
    transformerId VARCHAR(50),
    alertType VARCHAR(50),
    alertGroup VARCHAR(30),
    severity VARCHAR(50),
    value VARCHAR(50),
    notice VARCHAR(50),
    comment VARCHAR(60),
    attribute VARCHAR(50),
    date VARCHAR(50),
    id VARCHAR(40)
)
DISTRIBUTED BY HASH(eventId) BUCKETS 10
PROPERTIES (
"replication_num" = "1"
);


####Routine load job

example:
CREATE ROUTINE LOAD StarRocks.alertData1 ON alertData
PROPERTIES
(
      "format" ="json",
      "jsonpaths" ="[\"$.alertId\",\"$.eventId\",\"$.region\",\"$.substation\",\"$.transformer\",\"$.transformerId\",\"$.alertType\",\"$.alertGroup\",\"$.severity\",\"$.value\",\"$.notice\",\"$.comment\",\"$.attribute\",\"$.date\",\"$.id\"]",
      "json_root" = "$.payload"
 )
FROM KAFKA
(
    "kafka_broker_list" ="192.168.XX.XX:9092",
    "kafka_topic" = "http_topic",
    "property.kafka_default_offsets" = "OFFSET_BEGINNING"
);

#### DATA in the kafka topic 
file Attached 
[TOPIC_DATA.txt](https://github.com/StarRocks/starrocks/files/12685376/TOPIC_DATA.txt)

#### After loading data  StarRocks table 
Receiving all null values in the "alertData" Starrocks table,

<img width="588" alt="image" src="https://github.com/StarRocks/starrocks/assets/109329078/148dfce9-c949-4634-90c6-e784d647ea72">

## Additional Information

starrocks table after data loading :

<img width="588" alt="Starocks_table" src="https://github.com/StarRocks/starrocks/assets/109329078/07372e24-5cdf-47bd-873d-52b449b4e1d1">

topic data :

<img width="764" alt="topic_data" src="https://github.com/StarRocks/starrocks/assets/109329078/26f79ade-fae0-4199-ae72-8ef27ec2a36c">

**Comment by jaogoy** [comment]
@satyam679 What's "HTTP source connector"?

**Comment by satyam679** [comment]
Kafka connector that enables [Change Data Capture](https://github.com/castorm/kafka-connect-http/blob/master/docs/Change_Data_Capture.md) from JSON/HTTP APIs into Kafka.

**Comment by jaogoy** [comment]
The value of field `value` in `payload` is a string, not a JSON. So, you can’t use `jsonpaths` to extract the values from a STRING type field.

You can extract value from `data` (value of the `value` field) for every field:
```
COLUMNS (data, alertId=get_json_string(data, "$.alertId"), eventId=get_json_string(data, "$.eventId"), ...)
PROPERTIES
(
      "format" ="json",
      "jsonpaths" = "[\"$.value\"]",
      "json_root" = "$.payload"
)
```

And, currently, It’s not so convenient now to use `js=PARSE_JSON(value)` as a temp field.
