### ISSUE TITLE
[Feature] shared-data mode support JuiceFS

### ISSUE THREAD

**Issue by vkingnew** [StarRocks/starrocks#31617]
IN the shared-data mode whether support distribution file system JuiceFS. If no,do you have a plan to support it?
https://github.com/juicedata/juicefs

**Comment by kevincai** [comment]
can use juicefs s3 gateway as backend storage.

will support the hadoop compatible filesystem soon.

**Comment by tcodehuber** [comment]
> can use juicefs s3 gateway as backend storage.
> 
> will support the hadoop compatible filesystem soon.

Does starrocks 3.x support the hadoop compatible filesystem, such as juicefs, cubefs?

**Comment by kevincai** [comment]
yes. hadoop compatible fs is supported since 3.2 release.

**Comment by kevincai** [comment]
take a look at this doc: https://docs.starrocks.io/zh/docs/sql-reference/sql-statements/Administration/CREATE_STORAGE_VOLUME/
