### ISSUE TITLE
[move] sysinfo-test.cc needs to be moved to the correct location

### ISSUE THREAD

**Issue by stdpain** [StarRocks/starrocks#3162]
we should move sysinfo-test.cc to correct location
be/src/gutil/sysinfo-test.cc -> be/test/gutil/sysinfo-test.cc

add add it to be/test/CMakeLists.txt
```patch
         ./util/bit_packing_test.cpp
         ./util/gc_helper_test.cpp
+        ./gutil/sysinfo-test.cc
         )
```

Welcome newcomers to solve this issue

**Comment by stdpain** [comment]
@RishiKumarRay  Sure, I will assign to you

**Comment by RishiKumarRay** [comment]
@stdpain Please review PR #3164
