### ISSUE TITLE
Why only support AES_128_ECB?

### ISSUE THREAD

**Issue by BushJack** [StarRocks/starrocks#31679]
File: [/docs/sql-reference/sql-functions/crytographic-functions/aes_encrypt.md](https://docs.starrocks.io/en-us/3.0/sql-reference/sql-functions/crytographic-functions/aes_encrypt)
Why only support AES_128_ECB?

**Comment by kangkaisen** [comment]
@BushJack Hi, do you have any other crytographic functions requirement?
