### ISSUE TITLE
[help] how can i update mysql sql to starRocks

### ISSUE THREAD

**Issue by elemyin** [StarRocks/starrocks#31764]
I have an sql that can be run in msyql as follows: 

`select
t1.code
from (
(
	SELECT
	t.id AS id,
	t.parent_id AS parent_id,
	t.CODE,
	IF( find_in_set( t.parent_id, @pids ) > 0, @pids := concat( @pids, ',', t.id ), 0 ) AS childList 
	FROM
		sys_industry_chain t 
	ORDER BY
		t.parent_id,
		t.CODE
) t1,
( 
	SELECT @pids := ( SELECT id FROM sys_industry_chain WHERE `code` = 'I' ) 
) t2
)
where t1.childList != 0`

i want use Iterate to get the code for the tree structure, But it is not available. How can I modify this sql without modifying it from the business layer, the table structure is as follows：
![image](https://github.com/StarRocks/starrocks/assets/37828742/93c985d8-0864-46c4-b0e1-9d33eb5a2f7c)

**Comment by alberttwong** [comment]
Unfortunately SQL help is out of scope for this.
