### ISSUE TITLE
Docker compose image version setting error

### ISSUE THREAD

**Issue by xxhZs** [StarRocks/starrocks#31775]
In` docker/docker-compose.yml `and `docker-compose-3BE.yml`. `fe-ubuntu be-ubuntu `image's version is `main`. But i can't find it in https://hub.docker.com/r/starrocks/be-ubuntu/tags. So maybe it is `latest`
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by kevincai** [comment]
thanks, would you mind submit a PR to fix it?
