### ISSUE TITLE
Provide bitmap_max/bitmap_min functions to starrocks.

### ISSUE THREAD

**Issue by stdpain** [StarRocks/starrocks#3180]
bitmap_max: input: Bitmap output: Bigint
return the max value of bitmap, if input was null return null

1. We need to implement the max/min functions in the class BitmapValue in be/src/util/bitmap_value.h
2. define bitmap_max and bitmap_min in be/src/exprs/vectorized/bitmap_functions.h
3. implement bitmap_min and bitmap_max in bitmap_function.cpp, you can refer to bitmap_count for the implementation of the function
4. Register bitmap_max or bitmap_min in gensrc/script/vectorized/vectorized_functions.py, you can refer to the bitmap_count function

optional:
Add UT to be/test/exprs/vectorized/bitmap_functions_test.cpp
Submit the function documentation in https://github.com/StarRocks/docs

Welcome newcomers to solve this issue
If you have any difficulties you can contact me (stdpain) in slack (https://app.slack.com/client/T02EUPUD8FP/C02FAD0JSSD)

**Comment by blackstar-baba** [comment]
LGTM
