### ISSUE TITLE
Starrocks spark connector reading a table with JSON type will cause an exception

### ISSUE THREAD

**Issue by LinYuHeng-Con** [StarRocks/starrocks#31802]
error position:
![image](https://github.com/StarRocks/starrocks/assets/48077349/40f09094-63e7-496d-a39e-ae694c51a0c8)

![image](https://github.com/StarRocks/starrocks/assets/48077349/320efc38-445d-4b22-a60e-063bf07c4de7)

Exception：
![image](https://github.com/StarRocks/starrocks/assets/48077349/b19ed9eb-f9c0-46de-916f-133f79c1ff11)

BackendClient: The status of open scanner result from StarRocks BE{host='xxxxx', port=xxxx} is 'INVALID_ARGUMENT', error message is: [Unknown primitive type(27)].

**Comment by chaoyli** [comment]
I think the spark connector doesn't support the JSON type.
