### ISSUE TITLE
some delete operation do not support on DUPLICATE KEY

### ISSUE THREAD

**Issue by Q-maple** [StarRocks/starrocks#31804]
starrocks version : 2.5.6

column type: play_time datetime 

delete from play_log where play_time >= '2023-09-25' and play_time < '2023-09-26'
SQL 错误 [1064] [42000]: date literal [2023-09-25] is invalid

delete from play_log where play_time >= '2023-09-25' and play_time < date_add('2023-09-25',1)
SQL 错误 [1064] [42000]: Analyze DeleteStmt using old analyzer failed: Right expr of binary predicate should be value

**Comment by alberttwong** [comment]
MySQL retrieves and displays DATETIME values in ' YYYY-MM-DD hh:mm:ss ' format.
