### ISSUE TITLE
provide math function SQUARE in StarRocks

### ISSUE THREAD

**Issue by stdpain** [StarRocks/starrocks#3181]
`SQUARE` Definition: https://docs.microsoft.com/en-us/sql/t-sql/functions/square-transact-sql?view=sql-server-ver15

We can refer to the log2 implementation

1. declare function `square` in be/src/exprs/vectorized/math_functions.h
2. implentment function `square` in be/src/exprs/vectorized/math_functions.cpp
3. Register function `square` in gensrc/script/vectorized/vectorized_functions.py

Welcome newcomers to solve this issue
If you have any difficulties you can contact me (stdpain) in slack (https://app.slack.com/client/T02EUPUD8FP/C02FAD0JSSD)

**Comment by blackstar-baba** [comment]
LGTM

**Comment by stdpain** [comment]
@blackstar-baba 
Thank you, I'll assign to you
