### ISSUE TITLE
Display the last modified time in the output of the show data command

### ISSUE THREAD

**Issue by sduzh** [StarRocks/starrocks#31903]
Add a column in the output of `show data` to display the last modified time of the data. The results of `show data` are collected asynchronously in the background. This asynchronous collection may lead to some discrepancy between the data size in show data and the actual size. Displaying the last modified time in `show data` can help better understand how old the statistics are.

**Comment by lingtaolf** [comment]
Colud you let me try this ?

**Comment by sduzh** [comment]
Hi @lingtaolf, I wanted to check in and see how the work is going on this issue. Don't hesitate to reach out if you need any assistance or have any questions. But no pressure - please take your time. Just keep us posted so we can support you.

**Comment by Jin-H** [comment]
@lingtaolf Are you still willing to change this issue? If you don't plan to modify it in the near future, I would like to give it a try

**Comment by sduzh** [comment]
> @lingtaolf Are you still willing to change this issue? If you don't plan to modify it in the near future, I would like to give it a try



> @lingtaolf Are you still willing to change this issue? If you don't plan to modify it in the near future, I would like to give it a try

No pressure, please take your time

**Comment by lingtaolf** [comment]
> future

@Jin-H I'm a little busy recently, and I still work on this.  I will finish it in next week.
