### ISSUE TITLE
[Enhancement] We may need to introduce a new container type, like PODArray or uvector？

### ISSUE THREAD

**Issue by yulongfufu** [StarRocks/starrocks#31938]
### Background
Recently, we've identified some long-tail scenarios in various business clusters. These are primarily due to numerous long strings (binary columns) as revealed through profiling. Upon investigation, I substituted the **offsets** and **bytes** buffer in the binary column with podarray. We constructed a micro test set by exporting 1000 rows using the 'order by length(large field)' method. Upon testing with this set, we observed a time reduction ranging from **9.8%** to **52.3%** after the replacement. Additionally, there was an improvement of approximately **5%** in the 100G SSB (external parquet table) test. Given these results, I'm considering submitting my changes to the community. Alternatively, should we collaborate on designing a new container type?

**Motivation:**
After introduction of podarray, the process of rebasing community's latest code became quite challenging and required modifications. Consequently, I am opening this issue.

**SQL demo:**
```plaintext
select baselistenid,
    max(listenidtype_) listenidtype_,
    approx_count_distinct(uin_) uv,
    count(1) as vv,
    sum(playdurationoflistenid_)*1.00000/1000.0/60.0 sum_play_minute,
    sum(playdurationoflistenid_)*1.00000/1000.0/60.0/count(distinct uin_) avg_play_minute,
    min(sdt) min_sdt,
    max(sdt) max_sdt,
    max(title) title,
    max(author) author,
    max(musicdataurl) musicdataurl,
    max(albumname) albumname
from tt
group by baselistenid
limit 100
```

### Test Result
The `musicdataurl` is the long string field I mentioned earlier.
**Before replacement:**
Remove max(musicdataurl) 100 rows in set (**0.51** sec) 
Add max(musicdataurl) 100 rows in set (**3.42** sec) 

**After replacement:**
Remove max(musicdataurl) 100 rows in set (**0.46** sec) 
Add max(musicdataurl) 100 rows in set (**1.63** sec)

Promote **9.8%** ~ **52.3%**

**Comment by imay** [comment]
The result is really exciting.
Could you elaborate on this change?
Is this a change that just changes the internal structure?

**Comment by yulongfufu** [comment]
> Is this a change that just changes the internal structure?

Yes, the modification primarily involves three key aspects:

- The introduction of podarray and a new allocator (the inclusion of this new allocator is mainly for quick replacement, although it might not be necessary)
- After replacing with podarray, some interface compatibility adjustments are required. (this is due to the fact that a few interfaces between podarray and vector aren't fully compatible, even though most of them are)
- The replacement of raw::make_room. After the switch to podarray, raw::make_room is no longer needed, as podarray itself doesn't use value initialization when resize.

While my changes were somewhat rudimentary, they proved to be problem-free when implemented in an online cluster. For the open-source community, more refinements may be required. May I submit my modifications? I would greatly appreciate it if you could review these changes and provide feedback on areas that need improvement. Thank you! @imay

**Comment by stdpain** [comment]
What are the resources brought about by the savings from replacing it with a POD array. Is it mainly the overhead from saving memset to zero.

**Comment by yulongfufu** [comment]
> Is it mainly the overhead from saving memset to zero.

Yes, avoiding the overhead of memset to zero is indeed one of the optimizations that PodArray offers.

> What are the resources brought about by the savings from replacing it with a POD array.

Some common optimizations: align padding / Use default constructs instead of value initialization when resize, But I see that all these optimizations are in Starrocks. 

In addition to the above, there are two main points to note:

- Memory Management: PodArray's memory management strategy is more scenario-specific than that of vector. It pre-allocates a large chunk of memory and then expands it as needed. This strategy can reduce the number of memory allocations and releases, thereby improving performance.

- Flexible Memory Allocator: PodArray's memory allocator can accept a variety of parameters. These parameters will be passed to the corresponding methods of the allocator. This provides greater flexibility, allowing for the customization of the memory allocation strategy as needed.

At present, according to my judgment, the feeling is that the performance is too poor on the assembly and copy of large string columns
