### ISSUE TITLE
Ubuntu docker deployment has Vulnerabilities

### ISSUE THREAD

**Issue by talknopf** [StarRocks/starrocks#32004]
### Steps to reproduce the behavior (Required)
1. docker pull starrocks/artifacts-ubuntu:3.1.1
3. docker scout quickview

### Expected behavior (Required)
No critical issues
As little as possible High issues

### Real behavior (Required)
Please see attached screen capture
![Screenshot 2023-10-01 at 15 58 26](https://github.com/StarRocks/starrocks/assets/11613935/3555114e-96c9-4800-8948-f66698d786ee)
![Screenshot 2023-10-01 at 15 44 31](https://github.com/StarRocks/starrocks/assets/11613935/ec4398b1-b1bd-441a-9714-3fbd2b3bf66b)

### StarRocks version (Required)
 - 3.1.3

**Comment by Astralidea** [comment]
Thank you for your feedback. We are gradually fixing the security issue recently. When we fix it, we will try to check again according to your method to see how to fix it.
