### ISSUE TITLE
Add table related statistic to metrics 

### ISSUE THREAD

**Issue by mcgray** [StarRocks/starrocks#32000]
##Add table related statistic to metrics.

There is no way to see  data from for instance `SHOW PROC '/statistic'` or data from `8030/system?path=//statistic` in a same/similar way as` /metrics`.

I think it might be a good addition to exposed metrics especially data like unhealthy tablets or replication.

**Comment by nshangyiming** [comment]
@mcgray Thanks for reporting the issue, i think it's a quite reasonable requirement, we will arrange our engineers to work on it. Let me know if you have any other questions.
