### ISSUE TITLE
Manual block cache data warm up

### ISSUE THREAD

**Issue by williamho123** [StarRocks/starrocks#32014]
## Feature request

**Note**: I am aware from the Starrocks community that a native way to warm up the block cache is being worked on. Prior to that being released, I am following suggestions to manually warm up the cache as described below.

I would like to be able to warm up data in the block cache manually by running `select * from catalog.db.table` on a schedule. From my testing, I am able to populate the cache, but this operation takes longer than it needs to as Starrocks attempts to deliver hundreds of millions of rows back to my SQL client (from the query profile). 

Is there a way to perform the operation so that the query is executed but data is not returned to the client (since the data is not needed)?

**Is your feature request related to a problem? Please describe.**

Yes, populating the block cache for faster future queries.

**Describe the solution you'd like**

Being able to execute the query but not have data returned to the client.

**Describe alternatives you've considered**

N/A

**Additional context**

I am using `PyMySQL` client to query. 

```
connection = pymysql.connect(
    host=os.getenv("MYSQL_HOST"),
    port=int(os.getenv("MYSQL_PORT")),
    user=os.getenv("MYSQL_USER"),
    password=os.getenv("MYSQL_PWD"),
    init_command="SET enable_scan_block_cache = true;",
    cursorclass=pymysql.cursors.SSCursor
  )

with connection.cursor() as cursor:
    sql = 'SELECT * FROM catalog.db.table;'
    cursor.execute(sql)
```

I have tried playing around with fetching one record, fetching all records, etc. but that hasn’t helped.

Alternatively, I have also tried using a CTE like
```
WITH warmed_table AS (
  SELECT * FROM catalog.db.table
)
SELECT * FROM warmed_table WHERE 1 = 0;
```
but this returns immediately, I guess since the Starrocks optimizer sees the bogus where condition.

Maybe there’s a way to disable a system variable for the optimization? I have tried to set `enable_global_runtime_filter` to false, but that also didn’t work.

**Comment by imay** [comment]
Yes, starrocks will optimize `where 1 = 0` to an empty operator node, and you can see it via `explain`.
Another way to do the warmup manually is to execute `select count(column1), count(column2)... from table1`

**Comment by williamho123** [comment]
Thank you for the suggestion! That worked
