### ISSUE TITLE
官方文档-FE配置项错误

### ISSUE THREAD

**Issue by even986025158** [StarRocks/starrocks#3206]
官方文档-FE配置项错误
priority_networks 应该为指定FE IP地址;文档中为指定BE IP地址；
[https://docs.starrocks.com/zh-cn/main/administration/Configuration#fe%E9%85%8D%E7%BD%AE%E9%A1%B9](url)
<img width="864" alt="截屏2022-01-31 下午1 26 39" src="https://user-images.githubusercontent.com/39552698/151743269-3cc8e618-0953-400c-8c81-41dc5b1bbfa8.png">

**Comment by jaogoy** [comment]
Could you submit a Pull-Request for the Documentation.

**Comment by chaoyli** [comment]
@even986025158 Could you trouble you to change

**Comment by EsoragotoSpirit** [comment]
Fixed and good to be closed
