### ISSUE TITLE
Error when trying to get SQL dump backup

### ISSUE THREAD

**Issue by ashish-learnyst** [StarRocks/starrocks#32076]
### Steps to reproduce the behavior (Required)
mysqldump -h127.0.0.1 -P9030 -uUser -pPassword dbname > filepath

### Real behavior 
Couldn't execute '/*!40100 SET @@SQL_MODE='' */': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '<EOF>' at line 1 (1064)

### StarRocks version 
3.0.0-RC01 a99fb85

**Comment by imay** [comment]
@ashish-learnyst 
mysqldump is not supported now.

**Comment by ashish-learnyst** [comment]
Can you tell me how you get an SQL dump then?

**Comment by alberttwong** [comment]
Just curious why can't you use https://docs.starrocks.io/docs/sql-reference/sql-statements/data-definition/BACKUP/
