### ISSUE TITLE
Implement Pulsar exactly-once consume

### ISSUE THREAD

**Issue by hoffermei** [StarRocks/starrocks#32086]
## Background
As [#7893](https://github.com/StarRocks/starrocks/issues/7893) Pulsar Routine Load currently don't support exactly-once consume, it may cause data loss when fe transaction commit failed(ex: commit timeout).

## Design target
Implement exactly-once consume for Pulsar Routine Load Job by record Pulsar MessageId to fe when transaction committed.

## User interface
Create a new Pulsar Routine Load Job support specify start consume position(MessageId) for corresponding pulsar partition like Kafka Routine Load Job, the MessageId can be any valid value then only support POSITION_EARLIEST and POSITION_LATEST.

```sql
CREATE ROUTINE LOAD rl_pulsar_01 on olap_tbl_01
COLUMNS TERMINATED BY "|",
COLUMNS (key_1,key_2,key_3)
PROPERTIES
(
    "desired_concurrent_number"="1",
    "timezone" = "Asia/Shanghai"
)
FROM PULSAR
(
    "pulsar_service_url" = "pulsar://127.0.0.1:6650",
    "pulsar_topic" = "persistent://pulsar/sr/pulsar_topic_01",
    "pulsar_subscription" = "k_sr_01",
    "pulsar_partitions" = "persistent://pulsar/sr/pulsar_topic_01-partition-0,persistent://pulsar/sr/pulsar_topic_01-partition-1",
    "pulsar_positions" = "(186404,29894,0,0),(186393,24148,1,0)",
    "property.pulsar_default_position" = "POSITION_EARLIEST",
    "property.auth.token" = "xxxxxxxx"
);
```
Then new routine load job rl_pulsar_01 will start consume data at MessageId `(186404,29894,0,0)` for partition `persistent://pulsar/sr/pulsar_topic_01-partition-0`, start at MessageId `(186393,24148,1,0)` for partition `persistent://pulsar/sr/pulsar_topic_01-partition-1`. Just like we can specify an individual offset for every partition when creating Kafka Routine Job.

For better use experience, POSITION_EARLIEST and POSITION_LATEST can also be used in pulsar_partitions property.

When execute `show routine load for rl_pulsar_01` command, we can get result like:

```sql
show routine load for rl_pulsar_01 \G
*************************** 1. row ***************************
                  Id: 12192859
                Name: rl_pulsar_01
          CreateTime: 2023-09-28 18:11:30
           PauseTime: NULL
             EndTime: NULL
              DbName: foo
           TableName: olap_tbl_01
               State: RUNNING
      DataSourceType: PULSAR
      CurrentTaskNum: 8
       JobProperties: {"partitions":"*","rowDelimiter":"\t","partial_update":"false","columnToColumnExpr":"key_1,key_2,key_3","maxBatchIntervalS":"15","whereExpr":"*","timezone":"Asia/Shanghai","format":"csv","columnSeparator":"'|'","json_root":"","maxFilterRatio":"1.0","prefer_compute_node":"false","strict_mode":"false","jsonpaths":"","desireTaskConcurrentNum":"8","maxErrorNum":"1000","strip_outer_array":"false","currentTaskConcurrentNum":"8","maxBatchRows":"30000000"}
DataSourceProperties: {"serviceUrl":"pulsar://127.0.0.1:6650","currentPulsarPartitions":"persistent://pulsar/sr/pulsar_topic_01-partition-0,persistent://pulsar/sr/pulsar_topic_01-partition-1","topic":"persistent://pulsar/sr/pulsar_topic_01","subscription":"k_sr_01"}
    CustomProperties: {"auth.token":"xxxxxxxx","pulsar_default_position":"POSITION_EARLIEST"}
           Statistic: {"receivedBytes":426898,"errorRows":0,"committedTaskNum":5,"loadedRows":6105,"loadRowsRate":1000,"abortedTaskNum":0,"totalRows":6105,"unselectedRows":0,"receivedBytesRate":22350,"currentErrorRows":0,"taskExecuteTimeMs":1909}
            Progress: {"persistent://pulsar/sr/pulsar_topic_01-partition-0":"(186404,29894,0,22)","persistent://pulsar/sr/pulsar_topic_01-partition-1":"(186393,24148,1,2)"}
ReasonOfStateChanged: 
        ErrorLogUrls: 
            OtherMsg: 
1 row in set (0.00 sec)
```

We use four element tuple represent MessageId with format: `(ledgerId,entryID,partition-index,batch-index)`, it equal to offset in kafka.

## Inner Implement
1. record [MessageId](https://pulsar.apache.org/docs/3.1.x/concepts-messaging/#messages) to fe when pulsar routine load task committed, just like offset in kafka case.
2. in new loop, start to consume at position specified by MessageId last record by fe, implement by [Pulsar Reader](https://pulsar.apache.org/docs/3.1.x/client-libraries-readers/#receive-and-read-messages), which can specify startMessageId when a new reader created.

## Design Detail

1. parse MessageId tuple from job property pulsar_partitions, if specified(FE)
2. add begin_positions to TPulsarLoadInfo, so that we can specify start position when submit routine load task to be(FE)

```thrift
struct TPulsarLoadInfo {
    1: required string service_url;
    2: required string topic;
    3: required string subscription;
    4: required list<string> partitions;
    5: optional map<string, i64> initial_positions;
    6: optional map<string, string> properties;
    7: optional map<string, InternalService.TPulsarMessageId> begin_positions;
}
```

3. create a pulsar reader in PulsarDataConsumer::assign_partition, with partition and begin_positions parameter(BE)
4. use reader.receive to consume data in PulsarDataConsumer::group_consume(BE)
5. save last message id PulsarDataConsumerGroup::start_all finished(BE)
6. fill TPulsarRLTaskProgress with last message id in StreamLoadExecutor::collect_load_stat(BE)
7. do updateProgress in RoutineLoadJob.executeTaskOnTxnStatusChanged(FE), what actually do is update partition to messageId map info.

## Batch message exactly-once consume mechanism
1. Starrocks record last message's id which has been successed commit to transaction. ex: record a messageId: `(100, 234, -1, 12)`, the last number in tuple 12 means the message's index in batch message(start from 0).
2. In next consume loop, starrocks create a pulsar reader and specify start message id with `(100, 234, -1, 12)`, the start message id will be send to pulsar broker service. Detail can be see in [pulsar newSubscribe Command](https://github.com/apache/pulsar/blob/branch-2.10/pulsar-client-cpp/lib/Commands.cc#L294).
3. When pulsar broker service receive the subscription request, it will create a cursor start from `(100, 234-1, -1, 0)`, as pulsar broker not sure whether client has receive the whole batch, it rollback to entryId-1 postition, and begin to resend whole batch to consumer. Detail can be see in [pulsar getNonDurableSubscription](https://github.com/apache/pulsar/blob/branch-2.10/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L942)
4. Pulsar client receive the batch message and decode it to multiple single messages, then compare each single message id with the start message id `(100, 234, -1, 12)`, ignore single message if it's message id smaller or equal to start message id, finally return remaining messages which id bigger then start message id. Detail can be see in [ConsumerImpl::receiveIndividualMessagesFromBatch](https://github.com/apache/pulsar/blob/branch-2.10/pulsar-client-cpp/lib/ConsumerImpl.cc#L550)
5. starrocks receive first message is just next to start message id in 2. To here exactly-once consume for batch message on pulsar part finished.

**Comment by chaoyli** [comment]
It's better to unify the nonu with Kafka.
```
pulsar_default_position="POSITION_BEGINNING/POSITION_END"
```

**Comment by chaoyli** [comment]
```
7: optional map<string, InternalService.TPulsarMessageId> begin_positions;
```
Every partition needs a different begin_position? May be `partition_begin_partitions` is a better name?

**Comment by rickif** [comment]
Hi, thanks for contributing. I have several questions.
* How to know the start position of pulsar message in every batch? What we record is the last message id of the last batch.
* Is consumer group necessary for pulsar?
