### ISSUE TITLE
make compression scheme configurable

### ISSUE THREAD

**Issue by DeepThinker666** [StarRocks/starrocks#321]
## Enhancement
now, the default compression scheme is hard code.
making this configurable is useful to do some tests.

**Comment by imay** [comment]
@DeepThinker666 
I think a better solution would be to specify the encoding type and compression type for each field when building the table.

**Comment by DeepThinker666** [comment]
@imay I agree. It could be an intermediate state. I think a better solution is storage engine can automatically decide the best encoding and compression scheme.

**Comment by imay** [comment]
> @imay I agree. It could be an intermediate state. I think a better solution is storage engine can automatically decide the best encoding and compression scheme.

The storage engine can select automatically when not specified by the user. However, different users will have different preferences and StarRocks needs to provide this option to the user. For example, some users may want to save space and choose a compression algorithm with a higher compression ratio.

**Comment by DeepThinker666** [comment]
ok, I will do it.

**Comment by DeepThinker666** [comment]
I propose a design here.
now starrocks create table is as following:

> CREATE [EXTERNAL] TABLE [IF NOT EXISTS] [database.]table_name
>     (column_definition1[, column_definition2, ...]
>     [, index_definition1[, ndex_definition12,]])
>     [ENGINE = [olap|mysql|broker|hive]]
>     [key_desc]
>     [COMMENT "table comment"];
>     [partition_desc]
>     [distribution_desc]
>     [rollup_index]
>     [PROPERTIES ("key"="value", ...)]
>     [BROKER PROPERTIES ("key"="value", ...)]
> 
> column_definition:
> col_name col_type [agg_type] [NULL | NOT NULL] [DEFAULT "default_value"]

I want to add encoding and compression property in column_definition for users to specify the encoding or compression for specific column. just like following:

> column_definition:
> col_name col_type [agg_type] [NULL | NOT NULL] [DEFAULT "default_value"] [ ENCODING "PLAIN"] [COMPRESSION "LZ4F"]

And I think one could change the default compression scheme for entire table by specifying "compression" inPROPERTIES , not just for specific column, like following:

> PROPERTIES (
>     "compression" = "zstd"
> )

Is this feasible?
Here I need to ask for your opinions!
