### ISSUE TITLE
Support materialized view on DeltaLake catalog tables

### ISSUE THREAD

**Issue by neokjchen** [StarRocks/starrocks#32121]
## Feature request
Creating  materialized view on top of DELTALAKE table will failed, leaving error message: 
`Create/Rebuild materialized view do not support the table type: DELTALAKE`   
Other lake format (Iceberg, Hudi) is OK.
Hope to support materialized view on DELTALAKE catalog tables.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mofeiatwork** [comment]
What's the use case for it?
