### ISSUE TITLE
how to export table structure

### ISSUE THREAD

**Issue by dufeng1010** [StarRocks/starrocks#3219]
i see docs in starrocks，it says use doris tools can export table structure(https://docs.starrocks.com/zh-cn/main/faq/loading/Flink_connector_faq), but i search docs in apache doris，it says it use mysqldump command, i use this command. but not work.

**Comment by Dshadowzh** [comment]
You can check this [tool](https://github.com/Astralidea/olapdb-tool).

**Comment by dufeng1010** [comment]
> You can check this [tool](https://github.com/Astralidea/olapdb-tool).

thanks, i will try it.
