### ISSUE TITLE
Paging query returns inconsistent data

### ISSUE THREAD

**Issue by LittleBeeBee** [StarRocks/starrocks#3221]
### Steps to reproduce the behavior (Required)
1. create table:
```SQL
CREATE TABLE audit_project (
RowGuid varchar(65533) NOT NULL COMMENT "",
APPLYDATE datetime NULL COMMENT "",
AREACODE varchar(65533) NULL COMMENT ""
) ENGINE=OLAP
PRIMARY KEY(RowGuid)
COMMENT "OLAP"
DISTRIBUTED BY HASH(RowGuid) BUCKETS 32
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
```
2. insert data:
```SQL
insert into audit_project VALUES 
('qweer','2022-01-01','210101'),
('qwe7r','2022-01-02','210101'),
('qwe6r','2022-01-03','210101'),
('qwe5r','2022-01-04','210101'),
('qwe4r','2022-01-05','210101'),
('qwe1r','2022-01-06','210101'),
('qwe2r','2022-01-07','210101'),
('qwe3r','2022-01-08','210101'),
('qw43r','2022-01-09','210101'),
('qw23r','2022-01-10','210101'),
('qwwer','2022-01-11','210102'),
('qdafr','2022-01-12','210103'),
('qgfdr','2022-01-13','210104'),
('qdfar','2022-01-16','210102'),
('qgrtr','2022-01-19','210101'),
('qfdtr','2022-01-20','210101');
```

3. query:
```SQL
select * from audit_project
where rowguid in (
    select rowguid from audit_project
    where 1=1 and areacode='210101'
    order by applydate desc
    limit 10)
order by applydate desc;
```

### Expected behavior (Required)
The data returned should be sorted by APPLYDATE in descending order.
![image](https://user-images.githubusercontent.com/18304062/152783485-f272d355-3264-41cb-86b6-bb7637488c4c.png)

### Real behavior (Required)
The data returned is random.
![image](https://user-images.githubusercontent.com/18304062/152783593-04f294f8-fd5c-4dba-ab9f-d5467cf4440f.png)
![image](https://user-images.githubusercontent.com/18304062/152783715-d0a090de-f22e-4648-b3be-8c0a6ae36495.png)

### StarRocks version (Required)
 2.0.1

**Comment by kangkaisen** [comment]
@HangyuanLiu This bug seems has been fixed，please check  it

**Comment by HangyuanLiu** [comment]
This has been fixed in https://github.com/StarRocks/starrocks/pull/2512 and merged into the 2.1 branch

**Comment by kangkaisen** [comment]
please cherry-pick https://github.com/StarRocks/starrocks/pull/2512 to branch 2.0

**Comment by HangyuanLiu** [comment]
> please cherry-pick #2512 to branch 2.0

done
