### ISSUE TITLE
Regularly pre aggregate multi table data to new table

### ISSUE THREAD

**Issue by zddr** [StarRocks/starrocks#3232]
## Feature request

**Is your feature request related to a problem? Please describe.**

If there are many associated tables, the query will still be slow

**Describe the solution you'd like**

I want to add some syntax for adding, deleting and modifying query pre aggregation, which can support custom aggregation interval and custom SQL statements, such as insert into XX select * from XX join XX on where create_ time=now() and ...

**Describe alternatives you've considered**

I want to create a new folder in Fe like ’statistic‘ and put most of the implementation logic in it

**Additional context**

I am not sure whether this function conflicts with the planned multi table materialized view. If there is no conflict, I am willing to implement this function.

**Comment by jaogoy** [comment]
So, what's the difference between multi-table MV and your multi-table pre-aggregate?
And what is your main purpose? Improve the performance when many joined tables, or just want to improve the performance of table join by pre-aggregate?

**Comment by zddr** [comment]
Now that I know the general function of materialized view in the future, my idea should only be a part of materialized view function。
