### ISSUE TITLE
StarRocks Integration Issue with Cloudera-flavored Hive

### ISSUE THREAD

**Issue by joice1910** [StarRocks/starrocks#32323]
I am reaching out to the community to seek assistance with an integration issue I've encountered while trying to use Hive on a CDP distribution with StarRocks 3.1.
Here are the details of my setup:
StarRocks Version: 3.1
Hive Version:  3.1.3000.7.1.7.0-551
Cluster Security: Kerberized

I have successfully created a Hive catalog in StarRocks and have been able to set up the integration between Hive and StarRocks. However, when I attempt to query a Hive table using StarRocks, I encounter the following error:

`ERROR 1064 (HY000): Type mismatch: orc BIGINT to native VARCHAR(50). file = hdfs://instance-3:8020/warehouse/tablespace/managed/hive/baby/data_id=200401/delta_0000003_0000003_0000/bucket_00000_0: file = hdfs://instance-3:8020/warehouse/tablespace/managed/hive/baby/data_id=200401/delta_0000003_0000003_0000/bucket_00000_0`

Hive Catalog Creation Statement:
```
CREATE EXTERNAL CATALOG hive
PROPERTIES
(
    "type" = "hive",
    "hive.metastore.type" = "hive",
    "hive.metastore.uris" = "thrift://10.128.0.4:9083"
);

```

Hive table Creation Statement:

`CREATE  TABLE  BABY(
id int,
FNAME VARCHAR(50),
GENDER VARCHAR(2),
TOTCOUNT INT
)
PARTITIONED BY(DATA_ID INT)
TBLPROPERTIES (
   'orc.compress'='snappy');
`

`show create table baby;
+----------------------------------------------------+
|                   createtab_stmt                   |
+----------------------------------------------------+
| CREATE TABLE `baby`(                               |
|   `id` int,                                        |
|   `fname` varchar(50),                             |
|   `gender` varchar(2),                             |
|   `totcount` int)                                  |
| PARTITIONED BY (                                   |
|   `data_id` int)                                   |
| ROW FORMAT SERDE                                   |
|   '[org.apache.hadoop.hive.ql.io](http://org.apache.hadoop.hive.ql.io/).orc.OrcSerde'      |
| STORED AS INPUTFORMAT                              |
|   '[org.apache.hadoop.hive.ql.io](http://org.apache.hadoop.hive.ql.io/).orc.OrcInputFormat'  |
| OUTPUTFORMAT                                       |
|   '[org.apache.hadoop.hive.ql.io](http://org.apache.hadoop.hive.ql.io/).orc.OrcOutputFormat' |
| LOCATION                                           |
|   'hdfs://instance-3:8020/warehouse/tablespace/managed/hive/baby' |
| TBLPROPERTIES (                                    |
|   'bucketing_version'='2',                         |
|   'orc.compress'='snappy',                         |
|   'transactional'='true',                          |
|   'transactional_properties'='default',            |
|   'transient_lastDdlTime'='1696408694')            |
+----------------------------------------------------+`

ORC schema:

`hive --orcfiledump /warehouse/tablespace/managed/hive/baby/data_id=200401/delta_0000003_0000003_0000/bucket_00000_0
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-7.1.7-1.cdh7.1.7.p0.15945976/jars/log4j-slf4j-impl-2.13.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-7.1.7-1.cdh7.1.7.p0.15945976/jars/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
WARNING: Use "yarn jar" to launch YARN applications.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-7.1.7-1.cdh7.1.7.p0.15945976/jars/log4j-slf4j-impl-2.13.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-7.1.7-1.cdh7.1.7.p0.15945976/jars/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Processing data file /warehouse/tablespace/managed/hive/baby/data_id=200401/delta_0000003_0000003_0000/bucket_00000_0 [length: 1045]
Structure for /warehouse/tablespace/managed/hive/baby/data_id=200401/delta_0000003_0000003_0000/bucket_00000_0
File Version: 0.12 with ORC_135
Rows: 1
Compression: SNAPPY
Compression size: 32768
Calendar: Julian/Gregorian
Type: struct<operation:int,originalTransaction:bigint,bucket:int,rowId:bigint,currentTransaction:bigint,row:struct<id:int,fname:varchar(50),gender:varchar(2),totcount:int>>
Stripe Statistics:
  Stripe 1:
    Column 0: count: 1 hasNull: false
    Column 1: count: 1 hasNull: false bytesOnDisk: 6 min: 0 max: 0 sum: 0
    Column 2: count: 1 hasNull: false bytesOnDisk: 6 min: 3 max: 3 sum: 3
    Column 3: count: 1 hasNull: false bytesOnDisk: 9 min: 536870912 max: 536870912 sum: 536870912
    Column 4: count: 1 hasNull: false bytesOnDisk: 6 min: 0 max: 0 sum: 0
    Column 5: count: 1 hasNull: false bytesOnDisk: 6 min: 3 max: 3 sum: 3
    Column 6: count: 1 hasNull: false
    Column 7: count: 1 hasNull: false bytesOnDisk: 6 min: 4 max: 4 sum: 4
    Column 8: count: 1 hasNull: false bytesOnDisk: 15 min: Ashley max: Ashley sum: 6
    Column 9: count: 1 hasNull: false bytesOnDisk: 10 min: F max: F sum: 1
    Column 10: count: 1 hasNull: false bytesOnDisk: 7 min: 17997 max: 17997 sum: 17997
File Statistics:
  Column 0: count: 1 hasNull: false
  Column 1: count: 1 hasNull: false bytesOnDisk: 6 min: 0 max: 0 sum: 0
  Column 2: count: 1 hasNull: false bytesOnDisk: 6 min: 3 max: 3 sum: 3
  Column 3: count: 1 hasNull: false bytesOnDisk: 9 min: 536870912 max: 536870912 sum: 536870912
  Column 4: count: 1 hasNull: false bytesOnDisk: 6 min: 0 max: 0 sum: 0
  Column 5: count: 1 hasNull: false bytesOnDisk: 6 min: 3 max: 3 sum: 3
  Column 6: count: 1 hasNull: false
  Column 7: count: 1 hasNull: false bytesOnDisk: 6 min: 4 max: 4 sum: 4
  Column 8: count: 1 hasNull: false bytesOnDisk: 15 min: Ashley max: Ashley sum: 6
  Column 9: count: 1 hasNull: false bytesOnDisk: 10 min: F max: F sum: 1
  Column 10: count: 1 hasNull: false bytesOnDisk: 7 min: 17997 max: 17997 sum: 17997
Stripes:
  Stripe: offset: 3 data: 71 rows: 1 tail: 136 index: 274
    Stream: column 0 section ROW_INDEX start: 3 length 11
    Stream: column 1 section ROW_INDEX start: 14 length 24
    Stream: column 2 section ROW_INDEX start: 38 length 24
    Stream: column 3 section ROW_INDEX start: 62 length 36
    Stream: column 4 section ROW_INDEX start: 98 length 24
    Stream: column 5 section ROW_INDEX start: 122 length 24
    Stream: column 6 section ROW_INDEX start: 146 length 11
    Stream: column 7 section ROW_INDEX start: 157 length 24
    Stream: column 8 section ROW_INDEX start: 181 length 38
    Stream: column 9 section ROW_INDEX start: 219 length 28
    Stream: column 10 section ROW_INDEX start: 247 length 30
    Stream: column 1 section DATA start: 277 length 6
    Stream: column 2 section DATA start: 283 length 6
    Stream: column 3 section DATA start: 289 length 9
    Stream: column 4 section DATA start: 298 length 6
    Stream: column 5 section DATA start: 304 length 6
    Stream: column 7 section DATA start: 310 length 6
    Stream: column 8 section DATA start: 316 length 9
    Stream: column 8 section LENGTH start: 325 length 6
    Stream: column 9 section DATA start: 331 length 4
    Stream: column 9 section LENGTH start: 335 length 6
    Stream: column 10 section DATA start: 341 length 7
    Encoding column 0: DIRECT
    Encoding column 1: DIRECT_V2
    Encoding column 2: DIRECT_V2
    Encoding column 3: DIRECT_V2
    Encoding column 4: DIRECT_V2
    Encoding column 5: DIRECT_V2
    Encoding column 6: DIRECT
    Encoding column 7: DIRECT_V2
    Encoding column 8: DIRECT_V2
    Encoding column 9: DIRECT_V2
    Encoding column 10: DIRECT_V2
File length: 1045 bytes
Padding length: 0 bytes
Padding ratio: 0%
User Metadata:
  hive.acid.key.index=3,536870912,0;
  hive.acid.stats=1,0,0
  hive.acid.version=2
________________________________________________________________________________________________________________________`

I would greatly appreciate any insights, guidance, or solutions that the StarRocks community can offer to help me resolve this issue. 

![image](https://github.com/StarRocks/starrocks/assets/143017182/948c977b-e8d8-48fa-abd8-01d3f5baac60)

**Comment by juliethjaramillo96** [comment]
This issue seems to be due to ORC Format. Documentation says StarRocks does support HIve Tables using ORC. Has this worked on previous version and the issue is on the latest 3.1 version?

**Comment by juliethjaramillo96** [comment]
I recreated some of the ORC tables into Parquet tables and then the issue was magically fixed. I am now able to query all orc hive tables through StarRocks. Any idea on why?

**Comment by alberttwong** [comment]
I'm glad that its working now.  However, we couldn't help before because we didn't have FE or BE logs.    That would tell us why it wouldn't have worked.
