### ISSUE TITLE
Support various kinds of MySQL partitioned table in Materialized View

### ISSUE THREAD

**Issue by murphyatwork** [StarRocks/starrocks#32347]
## Feature request

**Is your feature request related to a problem? Please describe.**

Since materialized view has supported basic functionality of JDBC partition table, it could be improved to support various kinds of partition table.

Support all kinds of MySQL partition table:
- [ ] RANGE MySQL Partitions
- [ ] HASH MySQL Partitions
- [ ] KEY MySQL Partitions
- [ ] LIST MySQL Partitions
- [x] Column MySQL Partitions

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alyokaz** [comment]
Can I get assigned to this?

**Comment by mofeiatwork** [comment]
> Can I get assigned to this?

Sure. Thanks for contributing. 

You can get started from the "report a clear error message for unsupported partition types", then you can enhance it to support more partition types.
