### ISSUE TITLE
Broken SUM aggregation over DOUBLE type column

### ISSUE THREAD

**Issue by MariuszJurowicz** [StarRocks/starrocks#32415]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE sum_agg_test(id INT NOT NULL, val DOUBLE NULL);
2. INSERT INTO sum_agg_test VALUES (1, 0.0159), (2, 0.0119), (3, 0.0272);
3. SELECT SUM(val) from sum_agg_test;

### Expected behavior (Required)
Returns 0.055

### Real behavior (Required)
Once per couple of requests the result is 0.05499999999999999

### StarRocks version (Required)
 - 3.1.3-384ba23554

**Comment by decster** [comment]
double is known to have precision issues, it's expected, if you want precision add/minus, should use decimal.

```
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 0.0159 + 0.0119 + 0.0272
0.055
>>> 0.0119 + 0.0272 + 0.0159
0.05499999999999999

```
