### ISSUE TITLE
Support reading external kudu table

### ISSUE THREAD

**Issue by GSHF** [StarRocks/starrocks#3242]
- [x] https://github.com/StarRocks/starrocks/pull/45533
- [x] https://github.com/StarRocks/starrocks/pull/41090
## Enhancement
什么时候能支持kudu外表呀？

**Comment by Dshadowzh** [comment]
The community is focusing on Hive/Iceberg/Hudi external table. Kudu is still in discussion, If you want to contribute,  you can enter slack channel sig/dla to join us.  https://starrocks.slack.com/archives/C02SKR5SK3J

**Comment by DorianZheng** [comment]
duplicate issue #1850
