### ISSUE TITLE
StarRocks v3.0.4 information_schema.columns bug

### ISSUE THREAD

**Issue by Jerrylovescoding** [StarRocks/starrocks#32492]
### Bug:
The DATA_TYPE and COLUMN_TYPE in the "information_schema.columns" table actually show "unknown" when I use binary or varbinary type field.
![image](https://github.com/StarRocks/starrocks/assets/25549512/cec5425f-6b20-4a14-a3a2-5034122806c7)
![image](https://github.com/StarRocks/starrocks/assets/25549512/6e1cdf9b-3ed0-47eb-a75f-5af16ba46786)

### StarRocks Version:
v3.0.4

**Comment by Jerrylovescoding** [comment]
邮件已收到，谢谢！

**Comment by Amourzxq** [comment]
same as array type
