### ISSUE TITLE
join sql crash

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#3250]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS n0;
CREATE DATABASE n0;
USE n0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 VARCHAR(11) NULL ,c_0_1 SMALLINT NULL ,c_0_2 TINYINT NOT NULL ,c_0_3 DECIMAL(9, 7)  NULL ,c_0_4 DATETIME NULL ,c_0_5 SMALLINT NOT NULL ,c_0_6 LARGEINT NULL ,c_0_7 DATE NULL ,c_0_8 BOOLEAN NULL ,c_0_9 DECIMAL(30, 20)  NULL ,c_0_10 DECIMAL(23, 6)  NULL ,c_0_11 INT NOT NULL ,c_0_12 DATE NULL ,c_0_13 VARCHAR(11) NOT NULL ,c_0_14 BOOLEAN NOT NULL ,c_0_15 DOUBLE NOT NULL ,c_0_16 DOUBLE NULL ,c_0_17 INT NOT NULL ) UNIQUE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5,c_0_6,c_0_7,c_0_8,c_0_9,c_0_10,c_0_11) DISTRIBUTED BY HASH (c_0_3,c_0_9,c_0_5,c_0_0,c_0_1,c_0_6,c_0_2,c_0_4,c_0_10,c_0_11) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DECIMAL(5, 4)  NOT NULL ,c_1_1 BITMAP BITMAP_UNION NULL ,c_1_2 VARCHAR(1) REPLACE NOT NULL ) AGGREGATE KEY (c_1_0) DISTRIBUTED BY HASH (c_1_0) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t2 (c_2_0 DECIMAL(8, 4)  NOT NULL ,c_2_1 BOOLEAN NOT NULL ,c_2_2 DATETIME NULL ,c_2_3 DATE NULL ,c_2_4 BOOLEAN NULL ,c_2_5 DATETIME NULL ,c_2_6 VARCHAR(1) NULL ,c_2_7 DECIMAL(1, 0)  NOT NULL ,c_2_8 DECIMAL(24, 7)  NOT NULL ,c_2_9 DECIMAL(37, 6)  NOT NULL ,c_2_10 FLOAT NOT NULL ) UNIQUE KEY (c_2_0,c_2_1,c_2_2,c_2_3,c_2_4,c_2_5) DISTRIBUTED BY HASH (c_2_3) properties("replication_num"="3") ;
INSERT INTO t2 VALUES (0.0091, false, "1970-01-01 08:00:00", "1970-01-01", false, "1970-01-01 08:00:00", "", 1, 1787648508.0526779, 5421043499443048479588962.029751, 0.9009569860790836);
INSERT INTO t0 VALUES ("W", 3, 5, 0.0000013, "1970-01-01 08:00:00", 13, 225384511, NULL, false, NULL, 15765710331.329484, 24, "1970-01-01", "", false, -4.36946159E8, 0.0011603442785503848, 24), ("W", 7, 3, 0.0000074, "1970-01-01 08:00:00", 11, 1621101573, "1970-01-01", false, 6.005517877E-11, 5206598242.379508, 30, "1970-01-01", "j4BScYKj", true, 0.49945701274601606, 1.578510391E9, 16), ("X", 5, 0, 0.0000061, "1970-01-01 08:00:00", 8, -808488585, "1970-01-01", true, 1.645122198E-11, 79113013891.771596, 8, NULL, "U", true, 0.9537009193335366, 0.4675241201673769, 3);
TRUNCATE TABLE t2;
INSERT INTO t1 VALUES (0.0002, bitmap_hash(""), ""), (0.0002, bitmap_hash("HkXfkdU"), "");
INSERT INTO t1 VALUES (0.0000, bitmap_hash("LO8"), ""), (0.0000, bitmap_hash("z"), "");
INSERT INTO t2 VALUES (0.5723, false, "1970-01-01 08:00:00", "1970-01-01", false, "1970-01-01 08:00:00", "", 8, 9020098602.3038387, 7480918011477974309915298.656292, 0.9197559458685889);
INSERT INTO t2 VALUES (0.1673, true, "1970-01-01 08:00:00", "1970-01-01", false, NULL, NULL, 2, 9775465994.6106903, 3103404665394112618585342.966426, 0.06263421150013926), (0.0080, true, "1970-01-01 08:00:00", "1970-01-01", true, "1970-01-01 08:00:00", "", 8, 8371696747.0562950, 4132201480681964315687284.026168, 0.47504253885594183), (0.9014, true, "1970-01-01 08:00:00", "1970-01-01", true, "1970-01-01 08:00:00", "", 5, 2905252590.9858943, 2241058914233122748560217.418756, 0.6288328807451069);
INSERT INTO t1 VALUES (0.0004, bitmap_hash(""), ""), (0.0000, bitmap_hash("tPA"), "");
DELETE FROM t1 WHERE c_1_0=0.0005;
INSERT INTO t2 VALUES (0.3130, true, "1970-01-01 08:00:00", "1970-01-01", true, NULL, "", 1, 3951266448.0504172, 4885879915585872337425029.643398, 0.5970170971536328);
INSERT INTO t2 VALUES (0.2478, false, "1970-01-01 08:00:00", "1970-01-01", true, "1970-01-01 08:00:00", "", 4, 739419570.1591012, 8316710056226649981040720.982505, 0.7157230456303098);
INSERT INTO t1 VALUES (0.0003, bitmap_hash(""), ""), (0.0007, bitmap_hash("6"), ""), (0.0001, bitmap_hash(""), ""), (0.0005, bitmap_hash("X"), "");
INSERT INTO t0 VALUES ("q", 9, 3, 0.0000098, "1970-01-01 08:00:00", 2, 427756184, "1970-01-01", true, 7.64562736E-12, 46198135975.544041, 19, "1970-01-01", "u", false, 0.5648453310737522, 0.2001616072123199, 29);
INSERT INTO t1 VALUES (0.0004, bitmap_hash("Emt5JH1YW"), ""), (0.0008, bitmap_hash("d"), ""), (0.0007, bitmap_hash(""), "");
INSERT INTO t0 VALUES ("AG", 2, 5, 0.0000098, "1970-01-01 08:00:00", 3, -723524474, "1970-01-01", false, 5.163840044E-11, 20285702546.596651, 21, "1970-01-01", "5", true, 0.7289497181621729, 0.6813454213619267, 31), ("phQLZCN", 2, 6, 0.0000016, "1970-01-01 08:00:00", 8, 2141362445, "1970-01-01", true, 7.061483767E-11, 41258140644.732515, 29, "1970-01-01", "", true, 0.352533918912585, 0.28071307151631364, 22);
INSERT INTO t1 VALUES (0.0001, bitmap_hash(""), ""), (0.0005, bitmap_hash("m"), "");
INSERT INTO t1 VALUES (0.0002, bitmap_hash("rB"), ""), (0.0003, bitmap_hash(""), "");
SELECT COUNT(*) FROM  t0 RIGHT OUTER JOIN (SELECT t1.c_1_0, t1.c_1_2 FROM t1 WHERE (t1.c_1_2) IN ("") ) subt1 ON t0.c_0_3 = subt1.c_1_0 AND t0.c_0_3 > subt1.c_1_0 AND t0.c_0_0 = subt1.c_1_0 AND t0.c_0_0 < subt1.c_1_0 AND t0.c_0_8 > subt1.c_1_0 AND CASE  WHEN false THEN t0.c_0_8 ELSE t0.c_0_8 END = CAST(subt1.c_1_0 AS DECIMAL(7, 4) )  WHERE true;

```
crash.log:
*** Aborted at 1644377522 (unix time) try "date -d @1644377522" if you are using GNU date ***
PC: @     0x7fc16a04c476 __memcpy_ssse3_back
*** SIGSEGV (@0x10d92b190) received by PID 454 (TID 0x7fc115759700) from PID 227717520; stack trace: ***
    @          0x3479002 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fc16abf7630 (unknown)
    @     0x7fc16a04c476 __memcpy_ssse3_back
    @          0x172c039 starrocks::vectorized::BinaryColumn::serialize()
    @          0x2249bf8 starrocks::vectorized::SerializedJoinProbeFunc::_probe_column()
    @          0x224b8dc starrocks::vectorized::SerializedJoinProbeFunc::lookup_init()
    @          0x229da6a starrocks::vectorized::JoinHashMap<>::_search_ht()
    @          0x22cb94b starrocks::vectorized::JoinHashMap<>::probe()
    @          0x224eedf starrocks::vectorized::JoinHashTable::probe()
    @          0x2240827 starrocks::vectorized::HashJoinNode::_probe()
    @          0x2241591 starrocks::vectorized::HashJoinNode::get_next()
    @          0x2380a71 starrocks::vectorized::ProjectNode::get_next()
    @          0x20fe9cd starrocks::vectorized::AggregateBlockingNode::open()
    @          0x1c8f72b starrocks::PlanFragmentExecutor::_open_internal_vectorized()
    @          0x1c90417 starrocks::PlanFragmentExecutor::open()
    @          0x1c2ce12 starrocks::FragmentExecState::execute()
    @          0x1c312bc starrocks::FragmentMgr::exec_actual()
    @          0x1d564b9 starrocks::ThreadPool::dispatch_thread()
    @          0x1d52078 starrocks::Thread::supervise_thread()
    @     0x7fc16abefea5 start_thread
    @     0x7fc169ff48dd __clone
    @                0x0 (unknown)

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.1 Release
 - mysql> select current_version();
+---------------------------------+
| current_version()               |
+---------------------------------+
| SQLANCER_01_RELEASE cee9fdd |
+---------------------------------+

**Comment by trueeyu** [comment]
Simplified SQL:

SELECT COUNT(*) FROM t0 INNER JOIN t1 subt1 ON t0.c_0_8 > subt1.c_1_0 AND  t0.c_0_8 = CAST(subt1.c_1_0 AS DECIMAL(7, 4));
