### ISSUE TITLE
Column permission

### ISSUE THREAD

**Issue by LaoRay-Hub** [StarRocks/starrocks#32624]
A table where different users are only allowed to query specific fields, I need to set the user's column permissions. Although I know that views can work, too many field combinations can result in too many views.

**Comment by ChengJie1053** [comment]
Hello, does the community currently have plans to complete the column permissions feature

**Comment by HangyuanLiu** [comment]
The current open source version does not have the feature of internally maintaining row and column permissions, but it currently supports row and column permissions in Apache Ranger in the Main branch.

**Comment by ChengJie1053** [comment]
> The current open source version does not have the feature of internally maintaining row and column permissions, but it currently supports row and column permissions in Apache Ranger in the Main branch.

Ok, thank you

**Comment by LaoRay-Hub** [comment]
> The current open source version does not have the feature of internally maintaining row and column permissions, but it currently supports row and column permissions in Apache Ranger in the Main branch.

![image](https://github.com/StarRocks/starrocks/assets/65069002/c6a9f2ff-2a7b-47f8-8c5d-f81f3476f6ae)
![image](https://github.com/StarRocks/starrocks/assets/65069002/c1d1f6b7-a08e-4df3-aad3-d2ead648da9a)
I'm trying to use ranger，Where is the plugin jar and where should it go

**Comment by LaoRay-Hub** [comment]
> > The current open source version does not have the feature of internally maintaining row and column permissions, but it currently supports row and column permissions in Apache Ranger in the Main branch.
> 
> ![image](https://user-images.githubusercontent.com/65069002/275767542-c6a9f2ff-2a7b-47f8-8c5d-f81f3476f6ae.png) ![image](https://user-images.githubusercontent.com/65069002/275767932-c1d1f6b7-a08e-4df3-aad3-d2ead648da9a.png) I'm trying to use ranger，Where is the plugin jar and where should it go

<img width="614" alt="image" src="https://github.com/StarRocks/starrocks/assets/65069002/bf4930a2-d8f3-4778-83e5-237a3030089e">
work out

**Comment by LaoRay-Hub** [comment]
![image](https://github.com/StarRocks/starrocks/assets/65069002/57851eb2-3296-48f2-9f24-3289effb7f3d)

finally it It didn't work out, help plz~~~
1.What to fill in   Policy Conditions ？
2.Do I need to change any configuration in starrocks?

**Comment by jinmu0410** [comment]
I have the same problem, Are there any instructions for use? @HangyuanLiu

**Comment by piekill** [comment]
same here.
I get the following error with a column policy:
`mysql> select k from tmp.ranger_test;
ERROR 1253 (42000): Access denied; you need (at least one of) the SELECT privilege(s) on TABLE ranger_test for this operation.`
![image](https://github.com/StarRocks/starrocks/assets/1186842/1f0ffb20-ebfd-4400-8db5-1d129ab4629e)
I can select with a table policy (none for column), but then I can select all columns even if the column policy also exists.
