### ISSUE TITLE
Clear text password displayed during 'SHOW ALL Authorization'

### ISSUE THREAD

**Issue by dm520** [StarRocks/starrocks#32684]
UserIdentity     |Password|AuthPlugin                |UserForAuthPlugin|
-----------------|--------|--------------------------|-----------------|
'user002'@'%'    |Yes     |MYSQL_NATIVE_PASSWORD     |123456       |
'user001'@'%'    |Yes     |MYSQL_NATIVE_PASSWORD     |123456        |
'root'@'%'       |Yes     |MYSQL_NATIVE_PASSWORD     |                 |

starrocks version is V3.1.1

**Comment by HangyuanLiu** [comment]
Starrocks does not display the clear text of the password. How can I reproduce your scenario? Please fill in a Sql sequence, such as how to use SQL to create a user

**Comment by dm520** [comment]
> Starrocks does not display the clear text of the password. How can I reproduce your scenario? Please fill in a Sql sequence, such as how to use SQL to create a user

CREATE USER user001 IDENTIFIED WITH mysql_native_password BY '123456';
