### ISSUE TITLE
StarRocks support RoaringBitmap write to bitmap table

### ISSUE THREAD

**Issue by xuzifu666** [StarRocks/starrocks#3279]
currently, we cannot write bitmap parquet files into sr tables, so we need to support. 

for example:
table uid_uv (id, bitmap_uid) 
if we want to get bitmap about uid, we need to write all parquet files into the table to get bitmap result, but support write bitmap to Starrocks table, we just need to write a parquet file with bitmap column into table directly.

**Comment by chaoyli** [comment]
If you want to load bitmap binary from a parquet file, there are two places to modify.
First, modify the plan generated for load bitmap in load/Load.java
Second, take the bitmap binary size into consideration, we should change the packet sent between nodes. The default packet is about 4096 lines. If every bitmap is 10MB, the packet will be at 40GB. This will be rejected by the RPC framework.
The code paths are in runtime/data_stream_sender.cpp
