### ISSUE TITLE
[catalog] hive_2_sr 在dolphinscheduler 中、执行insert into starrocks select * from hive_table.

### ISSUE THREAD

**Issue by yqzdy1207** [StarRocks/starrocks#32796]
在 [catalog] hive_2_sr 在dolphinscheduler 中、执行insert into starrocks select * from hive_table.；
1. 7-8个任务会连接超时错误
2. 任务执行完成后，海豚不返回完成，一直在执行

**Comment by dengyunsheng250** [comment]
死锁？
