### ISSUE TITLE
Doc Error for to cancel process MATERIALIZED.

### ISSUE THREAD

**Issue by ggKe** [StarRocks/starrocks#328]
[ about MATERIALIZED page
](https://docs.starrocks.com/zh-cn/main/table_design/Materialized_view#%E6%9F%A5%E7%9C%8B%E7%89%A9%E5%8C%96%E8%A7%86%E5%9B%BE%EF%BC%9A)
In accordance  with the doc command “CANCEL ALTER MATERIALIZED VIEW FROM db_name.table_name” to cancel MATERIALIZED process.

### Expected behavior (Required)
The MATERIALIZED process is canceled;

### Real behavior (Required)
Screen will output info "Error 1064 (HY000):Table[table_name] is not under MATERIALIZED VIEW,Use 'DROP MATERIALIZED VIEW' if you want to."

The command "CANCEL ALTER MATERIALIZED VIEW FROM db_name.view_name" can to cancel process for MATERIALIZED.

**Comment by imay** [comment]
Are you sure that the task of creating the materialized view was not completed when the cancel command was executed?
It seems that the task has finished.

**Comment by ggKe** [comment]
> Are you sure that the task of creating the materialized view was not completed when the cancel command was executed?
> It seems that the task has finished.
I‘m sure the materialized process task state is running.
Because at that time the materialized  build have a bit slow,i went to change the materialized’s group column;
