### ISSUE TITLE
k8s-3.1.3 sr query_timeout is invalid when set greater than  300s

### ISSUE THREAD

**Issue by yaobukeji123** [StarRocks/starrocks#32831]
### Steps to reproduce the behavior (Required)
set query_timeout=3000;
insert into k8s_shared_data _sr
select * from mysql_catalog.old_sr_db.tablename where partition=partition_name

### Expected behavior (Required)
the sql can run 3000s when it is still processing

### Real behavior (Required)
the sql  only can run 300s but it is not processd  over.
![image](https://github.com/StarRocks/starrocks/assets/35523218/3532f8bb-e1ac-46bf-99a5-d43e3a493f7b)

### StarRocks version (Required)
 -  3.1.3-384ba23554

but when the value less then 300s，it is work

**Comment by kangkaisen** [comment]
@yaobukeji123 Hi, could you set global query_timeout=259200;  and try again?

**Comment by yaobukeji123** [comment]
it is not work for 259200，it is still 300s

**Comment by yaobukeji123** [comment]
![image](https://github.com/StarRocks/starrocks/assets/35523218/b2441dab-5d0d-4ee0-9cea-f467806440b9)
![image](https://github.com/StarRocks/starrocks/assets/35523218/05d7faf1-4252-4c18-959c-e7052dad8ddc)

**Comment by yaobukeji123** [comment]
![image](https://github.com/StarRocks/starrocks/assets/35523218/a1a19d67-5cf9-4b2d-bb19-6a2a4aedd1f6)

**Comment by liuyehcf** [comment]
try to set globally?

```
set global query_timeout = 259200;
```

**Comment by stdpain** [comment]
It seems that the error is caused by the external table timeout.

**Comment by yaobukeji123** [comment]
> It seems that the error is caused by the external table timeout.
yes. you are right! thanks
