### ISSUE TITLE
Is there a function like argMax() argMin() in Clickhouse or min_by() max_by() in presto？

### ISSUE THREAD

**Issue by ScyBernate** [StarRocks/starrocks#3288]
比如在分组统计中，我要获取时间戳最近的一条数据，或者获取时间戳最早的一条数据 ，ck中可以使用argMax(xx,timestamp),argMin(xx,timestamp)来解决
presto中的max_by()，min_by()也可以解决，不知是否有相关类似函数？或者有计划在哪个版本提供类似函数支持？

**Comment by imay** [comment]
Good suggestion! we will support these functions in next versions. You are appreciated if you could do this for StarRocks.

**Comment by harryhan1989** [comment]
这个功能特别需要，例如合并股票的bar数据时就特别有用，另外还有几个有用的需求：
1、Primary Key模式下支持物化视图
2、物化视图支持基于同一个字段的多次聚合，看官方文档“select sum(a), min(a) from table”这个描述的支持，同样是合成bar的时候需要对单个price字段进行min(price),max(price), argMin(value, timestamp),argMax(value, timestamp)

**Comment by xlwh** [comment]
Can you assing me？thanks

**Comment by wangsimo0** [comment]
@xlwh Hi hongbin,
Thanks for your interest in contributing!
I have done some functional design, could you please take a look to see if this is reasonable? 
Looking forward to discussing this with you.


### max_by(x,y,[n])

#### Description

Returns `n` value of `x` associated with the maximum value of `y`. If there are more than `n` different values of `x` for minimum values of `y`, returns the first `n` of these values encountered.

#### Syntax

```SQL
max_by(x,y,[n BIGINT])
```

#### Parameters

`x`: An expression of any type.

`y`: An expression of a type that can be ordered.

`n`: An expression of a positive BIGINT. This is optional. Default to be 1.

#### Return Value

If n=1 (by default), returns the values of `x` that corresponds to maximum of all input values of `y`;

If n>=1, returns an array of `n` values of `x` that corresponds to maximum of all input values of `y` in descending order of `y`.

#### Usage notes

If you use a unsortable type of `y`, such as `bitmap` or `hll`, it will cause an error.

#### Example

Input table:

```YAML
┌─subject──┬─exam_result─┐

│ math     │          95 │

│ english  │          70 │

│ physics  │          87 │

└──────────┴─────────────┘
```

##### Example1

Query:

```SQL
SELECT max_by(subject, exam_result) FROM exam;
```

Result:

```SQL
math
```

##### Example2

Query:

```SQL
SELECT max_by(subject, exam_result,2) FROM exam;
```

Result:

```SQL
[math, physics]
```

#### Cautions

1. Error message related to `n`: Invalid Argument: The third argument of max_by/min_by must be a positive integer.
2. Error message related to `y`: Invalid Argument: The second argument of max_by/min_by must be a sortable type.
3. If `n`>rows can be returned, then return as much as it can.
4. If there are more than `n` values of  `x` has the same value of `y`, returns the first n values of these `x` values encountered.





### min_by(x,y)

#### Description

Returns `n` value of `x` associated with the minimum value of `y`. If there are more than `n` different values of `x` for minimum values of `y`, returns the first `n` of these values encountered.

#### Syntax

```SQL
min_by(x,y,[n BIGINT]))
```

#### Parameters

`x`: An expression of any type.

`y`: An expression of a type that can be ordered.

`n`: An expression of a positive integer. This is optional.  Default to be 1.

#### Return Value

If n=1 (by default), returns the values of `x` that corresponds to maximum of all input values of `y`;

If n>=1, returns an array of `n` values of `x` that corresponds to maximum of all input values of `y` in ascending order of `y`.

#### Usage notes

If you use a unsortable type of `y`, such as `bitmap` or `hll`, it will cause an error.

#### Example

Input table:

```YAML
┌─subject──┬─exam_result─┐

│ math     │          95 │

│ english  │          70 │

│ physics  │          87 │

└──────────┴─────────────┘
```

##### Example1

Query:

```SQL
SELECT min_by(subject, exam_result) FROM exam;
```

Result:

```SQL
english
```

##### Example2

Query:

```SQL
SELECT max_by(subject, exam_result,2) FROM exam;
```

Result:

```SQL
[english, physics]
```

#### Cautions

1. Error message related to `n`: Invalid Argument: The third argument of max_by/min_by must be a positive integer.
2. Error message related to `y`: Invalid Argument: The second argument of max_by/min_by must be a sortable type.
3. If `n`>rows can be returned, then return as much as it can.
4. If there are more than `n` values of  `x` has the same value of `y`, returns the first n values of these `x` values encountered.

**Comment by xlwh** [comment]
@wangsimo0  Thank you very much, I'll take a look.

**Comment by wangsimo0** [comment]
> @wangsimo0 Thank you very much, I'll take a look.

Hi xlwh, 

Hope you are doing well :)
How is everything going? Do you need any help?

**Comment by wangsimo0** [comment]
@hzh0425 hi could you please reply to this issue so I can assign it to you?
