### ISSUE TITLE
Dremio starrocks connector

### ISSUE THREAD

**Issue by colagy** [StarRocks/starrocks#32963]
## Feature request

**Is your feature request related to a problem? Please describe.**

![image](https://github.com/StarRocks/starrocks/assets/37213080/19e951d5-c846-40cf-a631-2543ad3b30af)
I am using the dremio lakehouse engine to query the data from starrocks, when I use "select * from starrocks.tpch.nation" it already work. But when I use "select * from table(external_query('select * from nation'))" that means directly query from starrocks, it did not work.

**Describe the solution you'd like**

Dremio connect mysql-like database by using mariaDB Driver, Starrocks can provider a connector that uses mysql Driver.
It can also natively support the PreicatePushdown

**Describe alternatives you've considered**

**Additional context**

**Comment by imay** [comment]
Did you compare two engines when both served as lakehouse query engines?

**Comment by colagy** [comment]
> Did you compare two engines when both served as lakehouse query engines?

They can be used in different departments. some data is stored in the internal table of starRocks, while others are stored in the iceberg that managed by dremio. We didn't have metastore service, so we store the metadata in s3 as iceberg's metadata file format. dremio can optimize and vacuum the iceberg just like merge small files, but starRocks can't support it. neither of them can replace each other.

**Comment by imay** [comment]
Thank you for explaining to me. @colagy 
COM_PREPARE is supported in new versions of starrocks. I think with this feature supported you can query starrocks via Dremio.
Could you change the JDBC or ODBC version or adjudge some configure to make dremio access SR via another way other than COM_PREPARE?

**Comment by colagy** [comment]
> Thank you for explaining to me. @colagy COM_PREPARE is supported in new versions of starrocks. I think with this feature supported you can query starrocks via Dremio. Could you change the JDBC or ODBC version or adjudge some configure to make dremio access SR via another way other than COM_PREPARE?

What is the version of Starrocks?
Change the JDBC driver is difficult from Dremio.
