### ISSUE TITLE
add new compaction task framework

### ISSUE THREAD

**Issue by DeepThinker666** [StarRocks/starrocks#3301]
## Enhancement
add new compaction execution framework.

the design is as following:
![image](https://user-images.githubusercontent.com/89860388/153864469-8b7c7a4d-6f24-4376-a498-819e2a8cf797.png)

1. pick the compaction candidate tablet by triggering instead of polling to solve the CPU cost problem of compaction. The candidate tablets will be a subset of total tablets, which will save a lot of scheduler computation in situations with large tablets num. The tablet will be judged whether to be compacted when there are rowsets modification, including new rowset loaded, schema change finished, compaction task finished, clone finished.
2. add CompactionPolicy to decide which tablet should be compacted and which rowsets in a tablet should be compacted. Now LevelCompactionPolicy is created based on CompactionContext to decide whether the tablet should be compacted, which level should be compacted, and how many rowsets in that level should be compacted. And LevelCompactionPolicy use the same strategy as before. The details are as follows: when the compaction score is above threshold, it is considered to be compaction candidate. It use the same strategy to pick rowsets from level. But the difference is there is no cumulative compaction or base compaction. Now it is replaced by level compaction. And there are only three levels and also two types of compaction(level-0 and level-1 compaction) to keep compatible. Level-0 compaction is equivalent to cumulative compaction as before; Level-1 compaction is equivalent to base compaction. Maybe it can be extended to more levels in the future.
3. add CompactionScheduler to pick the candidate tablet by compaction score descendingly to run compaction task and control the concurrency of compaction tasks.
4. add CompactionTask to abstract the basic compaction task logic, and realize the functions including stop compaction task, get task progress, and so on. Now there is two types of compaction task, VerticalCompactionTask, and HorizontalCompactionTask. Realize CompactionTaskFactory to create compaction task according to the context
5. add CompactionManager to manage the candidate tablets which are stored as set ordered by compaction score descendingly, and compaction tasks. the HTTP APIs to get candidates' info, compaction tasks info, and the detail of a compaction task will be developed later accordingly.
6. CompactionContext contains infos about the detail rowsets in different level, ordered by version. 
![image](https://user-images.githubusercontent.com/89860388/153864943-046dd2c0-6755-486b-9873-d6180ee5d9f1.png)
7. the compaction score is calculated as follows:
![image](https://user-images.githubusercontent.com/89860388/153865048-d97a5b3d-d2a8-4448-9bee-fe006552a4f4.png)
MinRowsetNumber is config::min_cumulative_compaction_num_singleton_deltas for level-0, and is config::base_compaction_num_cumulative_deltas for level-1

**Comment by chaoyli** [comment]
Under the current circumstance, the cumulative compaction cost too much CPU when there are a large number of tablets and many storage paths.
![image](https://user-images.githubusercontent.com/89860388/145987909-fb4e2942-e4bd-482a-9bb9-973dff479934.png)
