### ISSUE TITLE
Third-party package can not be downloaded

### ISSUE THREAD

**Issue by HackToday** [StarRocks/starrocks#33058]
### Steps to reproduce the behavior (Required)
bash build-thirdparty.sh

### Expected behavior (Required)

package can be download successfully 

### Real behavior (Required)

 curl  -v https://cdn-thirdparty.starrocks.com/jindosdk-4.6.8-linux.tar.gz  got 503 error. the link is not accessable

### StarRocks version (Required)

master branch

**Comment by chaoyli** [comment]
![image](https://github.com/StarRocks/starrocks/assets/44767902/97233be3-b508-454e-ab1e-32add3f03d72)
It works now @HackToday

**Comment by HackToday** [comment]
@chaoyli  seems this cdn link has some issue, some machine can access, while some other machine can not access.
I am thinking if this cdn link configuration issue or something else.

**Comment by alberttwong** [comment]
I can also confirm that this works.
