### ISSUE TITLE
Timestamp data type support

### ISSUE THREAD

**Issue by svdimchenko** [StarRocks/starrocks#33088]
## Feature request

I already have timestamp fields in my aws glue catalog (iceberg tables) and I want to use starrocks as serving layer for my reporting system and other consuming apps. And I want to have possibilities:
- to filter required timestamp intervals
- to calculate timestamp diff between events

Iceberg has 6 digit precision for timestamp and it would be nice to keep this precision when I move my data marts to starrocks.

**Describe the solution you'd like**
- Timestamp data type is implemented with precision 3 (millis), 6 (micros) or 9 (nanos) digits
- Major timestamp functions are supported. Let's take some the most frequently used from trino, returned precision may be generalized if it's possible https://trino.io/docs/current/functions/datetime.html#date-and-time-functions
-- date_add(unit, value, timestamp) → [same as input][#](https://trino.io/docs/current/functions/datetime.html#date_add)
-- date_diff(unit, timestamp1, timestamp2) → bigint[#](https://trino.io/docs/current/functions/datetime.html#date_diff)
-- from_iso8601_timestamp(string) → timestamp(3) with timezone[#](https://trino.io/docs/current/functions/datetime.html#from_iso8601_timestamp)
-- from_iso8601_timestamp_nanos(string) → timestamp(9) with time zone[#](https://trino.io/docs/current/functions/datetime.html#from_iso8601_timestamp_nanos)
from_unixtime(unixtime) → timestamp(3) with time zone[#](https://trino.io/docs/current/functions/datetime.html#from_unixtime)-- from_unixtime_nanos(unixtime) → timestamp(9) with time zone[#](https://trino.io/docs/current/functions/datetime.html#from_unixtime_nanos)
-- to_unixtime(timestamp) → double[#](https://trino.io/docs/current/functions/datetime.html#to_unixtime)

**Describe alternatives you've considered**
There is the only option to have 2 fields:
- datetime - truncated field to use for partitioning and filtering
- long - to use for more precise calculations
and it seems to be not so optimal as in iceberg now I can use only 1 field with timestamp(6) type which cover all my needs.

**Additional context**
This feature is especially crucial for users behaviour analysis, when you want to track web site events sequence or if you need to analyze high load system with many events and sequence is important (for instance, telco industry).

**Comment by imay** [comment]
You can use DateTime type in starrocks as timestamp type in Iceberg.
Have you tried your case in StarRocks?

**Comment by svdimchenko** [comment]
@imay yeah, I can query timestamp fields from iceberg, but it returns data truncated to seconds (as datetime data type), which is not precise enough, I need to have at least millis precision or even better micros.

**Comment by imay** [comment]
Got it.
So, the requirement is to read the timestamp type in Iceberg and reserve the millisecond. The above functions you mentioned are the functions that you will use in your case, is that right?

**Comment by svdimchenko** [comment]
Yes for mentioned above.
However I will use timestamp data type and corresponding functions for native starrocks tables as well, not only to read data from external tables.
Expression partitioning (`date_trunc(<date part>, <column name>)`) by timestamp fields is also required as now only date and datetime types are supported.

**Comment by wrb2** [comment]
> **Additional context**
> This feature is especially crucial for users behaviour analysis, when you want to track web site events sequence or if you need to analyze high load system with many events and sequence is important (for instance, telco industry).

I want to add that this data type is also important in manufacturing domain - the precision is required both for practical, and often for regulatory reasons. In all other was (speed, streaming processing, materialized views, ...) StarRocks is a really good fit for that use.

**Comment by Smith-Cruise** [comment]
What version of starrocks are you using? Is it too old? We support timestamp accuracy to microseconds.

**Comment by svdimchenko** [comment]
> What version of starrocks are you using? Is it too old? We support timestamp accuracy to microseconds.

Hi @Smith-Cruise ! Thanks for your reply. Could you add references to your documentation regarding timestamp support? I don't see timestamp data type here https://docs.starrocks.io/docs/sql-reference/sql-statements/data-types/data-type-list/

**Comment by Smith-Cruise** [comment]
> > What version of starrocks are you using? Is it too old? We support timestamp accuracy to microseconds.
> 
> Hi @Smith-Cruise ! Thanks for your reply. Could you add references to your documentation regarding timestamp support? I don't see timestamp data type here https://docs.starrocks.io/docs/sql-reference/sql-statements/data-types/data-type-list/

Sorry, looks like that document is not correct. You can try with StarRocks 3.1.5 or 3.2 rc1, it works now.

**Comment by Smith-Cruise** [comment]
I know why the document does not contain timestamp type, because SR didn't support timestamp, but it will mapping iceberg's timestamp type to datetime type. And sr's datetime type's is accurate to microseconds.

**Comment by Smith-Cruise** [comment]
You can just have a try, I think it will work easily.

**Comment by wrb2** [comment]
I can confirm this works to microsecond precision.

One part that might be confusing is that while MySQL client does render the microseconds by default, DBeaver shows truncated form unless you explicitly ask it to format it a certain way, probably because the data type doesn't register as microsecond precise? Maybe having that data type report itself as TIMESTAMP would fix that.

<img width="498" alt="Screenshot 2023-12-08 at 10 16 14" src="https://github.com/StarRocks/starrocks/assets/25055982/6027d103-593e-4dd3-b0cd-eae678cd44f0">

<img width="521" alt="Screenshot 2023-12-08 at 10 15 24" src="https://github.com/StarRocks/starrocks/assets/25055982/cbb02d29-73ac-4ec8-af7f-6e4b5dd3224d">
