### ISSUE TITLE
JDBCUtil class is not real JDBCUtil

### ISSUE THREAD

**Issue by git-aking** [StarRocks/starrocks#33098]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Expected behavior (Required)
com.starrocks.jdbcbridge.JDBCUtil is a DateUtil，is not real JDBCUtil，please exchange class name 
### Real behavior (Required)
com.starrocks.jdbcbridge.JDBCUtil
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by imay** [comment]
@git-aking thanks for pointing it out. Could you submit a PR to fix it?

**Comment by Jin-H** [comment]
If no one wants to modify it, I can contribute it.

**Comment by git-aking** [comment]
i will commit this branch，you can review code and logic 
  
 
  
 
 -- 
 
 
  
  发自新浪邮箱客户端 
  
  
   
   在 今天 19:40，redscarf ***@***.***> 写道：  
    
   If no one wants to modify it, I can contribute it.

**Comment by Jin-H** [comment]
ok
