### ISSUE TITLE
threadpool.cpp:78 CHECK_GT(max_threads, 0); Check failed: max_threads > 0 (0 vs. 0) 

### ISSUE THREAD

**Issue by matrix-static** [StarRocks/starrocks#33169]
### Steps to reproduce the behavior (Required)
1. os kvm rockylinux9.2 
2. run
     ./be/bin/start_cn.sh --daemon
3. get error in cn.WARNING

ps: do this in os kvm centos7.9-2009, i got nothing.

### Expected behavior (Required)
cn node started

### Real behavior (Required)
starrocks/log/cn.WARNING
W1019 17:40:58.295658  2014 timezone_utils.cpp:93] not found timezone:Africa/Casablanca
W1019 17:40:58.296542  2014 timezone_utils.cpp:93] not found timezone:Africa/El_Aaiun
F1019 17:40:58.383560  2014 threadpool.cpp:78] Check failed: max_threads > 0 (0 vs. 0) 

starrocks/log/cn.INFO
I1019 17:40:58.206768  2014 daemon.cpp:305]  version 3.1.3-384ba23
BuildType: RELEASE
Built on 2023-09-22 10:13:59 by StarRocks@localhost
I1019 17:40:58.208716  2014 mem_info.cpp:104] Physical Memory: 15.34 GB
I1019 17:40:58.208729  2014 daemon.cpp:311] Cpu Info:
  Model: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
  Cores: 16
  Max Possible Cores: 16
  L1 Cache: 32.00 KB (Line: 64.00 B)
  L2 Cache: 2.00 MB (Line: 64.00 B)
  L3 Cache: 16.00 MB (Line: 64.00 B)
  Hardware Supports:
    ssse3
    sse4_1
    sse4_2
    popcnt
    avx
    avx2
  Numa Nodes: 1
  Numa Nodes of Cores: 0->0 | 1->0 | 2->0 | 3->0 | 4->0 | 5->0 | 6->0 | 7->0 | 8->0 | 9->0 | 10->0 | 11->0 | 12->0 | 13->0 | 14->0 | 15->0 |
I1019 17:40:58.208748  2014 daemon.cpp:312] Disk Info: 
  Num disks 1: vda
I1019 17:40:58.208755  2014 daemon.cpp:313] Mem Info: 15.34 GB
I1019 17:40:58.208758  2014 daemon.cpp:314] CPU Info:
  Type: 0
  Family: 6
  Model: 79
  Stepping: 1
  ExtendModel: 4
  ExtendFamily: 0
  RunningInVM: 1
  Vendor: GenuineIntel
  Brand: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
  HardwareSupport: mmx sse sse2 sse3 ssse3 sse41 sse42 avx avx2 popcnt
W1019 17:40:58.295658  2014 timezone_utils.cpp:93] not found timezone:Africa/Casablanca
W1019 17:40:58.296542  2014 timezone_utils.cpp:93] not found timezone:Africa/El_Aaiun
I1019 17:40:58.381911  2014 daemon.cpp:288] Minidump is disabled
I1019 17:40:58.381974  2014 backend_options.cpp:100] priority cidrs in conf: 10.0.10.0/24
I1019 17:40:58.382084  2014 backend_options.cpp:77] localhost 10.0.10.61
I1019 17:40:58.382480  2014 exec_env.cpp:479] Set storage page cache size 2667918311
I1019 17:40:58.382812  2028 daemon.cpp:211] Current memory statistics: process(0), query_pool(0), load(0), metadata(0), compaction(0), schema_change(0), column_pool(0), page_cache(0), update(0), chunk_allocator(0), clone(0), consistency(0)
F1019 17:40:58.383560  2014 threadpool.cpp:78] Check failed: max_threads > 0 (0 vs. 0) 

source:
\starrocks\3.1.3\be\src\util\threadpool.cpp
line: 78
ThreadPoolBuilder& ThreadPoolBuilder::set_max_threads(int max_threads) {
    CHECK_GT(max_threads, 0);
    _max_threads = max_threads;
    return *this;
}

### StarRocks version (Required)
 - 3.1.3

**Comment by kevincai** [comment]
to be clear, it was ok on.centos7.9 but failed on rockylinux9.2, correct?

**Comment by matrix-static** [comment]
I am sorry to tell you it was not worked in contos7.9. when i run compute node command ‘./be/bin/start_cn.sh’, I got nothing, no output, no log.

**Comment by matrix-static** [comment]
now, i changed to version starrock3.0.7 + ceph S3, fe and cn node is running , but i got a new error:
2023-10-20 19:24:44,754 WARN (Routine load task scheduler|38) [RoutineLoadTaskScheduler.process():117] no available be slot to scheduler tasks, wait for 10 seconds to scheduler again, you can set max_routine_load_task_num_per_be bigger in fe.conf, current value is 10
2023-10-20 19:24:44,832 WARN (statistics meta manager|23) [StatisticsMetaManager.createSampleStatisticsTable():155] Failed to create sample statisticsCluster has no available capacity
2023-10-20 19:24:44,832 WARN (statistics meta manager|23) [StatisticsMetaManager.refreshStatisticsTable():298] create statistics table table_statistic_v1 failed

PS: thanks for you replay.

**Comment by matrix-static** [comment]
when i run create table in fe mysql command, i got error : 
ERROR 1064 (HY000): Unexpected exception: Cluster has no available capacity

**Comment by kevincai** [comment]
are you testing `shared_data` mode or `shared_nothing` mode?

**Comment by matrix-static** [comment]
#####################################################################
## The uppercase properties are read and exported by bin/start_fe.sh.
## To see all Frontend configurations,
## see fe/src/com/starrocks/common/Config.java

run_mode = shared_data
cloud_native_meta_port = 6090
enable_load_volume_from_conf = true
cloud_native_storage_type = S3
# aws_s3_path = starrocks
aws_s3_path = kvm
# aws_s3_region = starrocks
# aws_s3_endpoint = http://10.0.10.32:8080
aws_s3_endpoint = http://10.0.10.31:7480
# aws_s3_use_aws_sdk_default_behavior = false
# aws_s3_use_instance_profile = false
# aws_s3_access_key = xxx
# aws_s3_secret_key = yyy
aws_s3_access_key = UF7S1EGYRSUZOQF4M8MB
aws_s3_secret_key = V3zlQDBCJ1CTqCpxmCenJhDBEitre3gzC4d2EkEc
# aws_s3_iam_role_arn = 
# aws_s3_external_id = 

# the output dir of stderr/stdout/gc
# LOG_DIR = ${STARROCKS_HOME}/log
LOG_DIR = /data_disk_01/starrocks/log

DATE = "$(date +%Y%m%d-%H%M%S)"
JAVA_OPTS="-Dlog4j2.formatMsgNoLookups=true -Xmx8192m -XX:+UseMembar -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=80 -XX:SoftRefLRUPolicyMSPerMB=0 -Xloggc:${LOG_DIR}/fe.gc.log.$DATE -XX:+PrintConcurrentLocks"

# JAVA_HOME = /usr/lib/jvm/java-17-openjdk-17.0.8.0.7-2.el9.x86_64
JAVA_HOME = /usr/lib/jvm/java-11-openjdk-11.0.20.0.8-3.el9.x86_64

# For jdk 9+, this JAVA_OPTS will be used as default JVM options
JAVA_OPTS_FOR_JDK_9="-Dlog4j2.formatMsgNoLookups=true -Xmx8192m -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=80 -XX:SoftRefLRUPolicyMSPerMB=0 -Xlog:gc*:${LOG_DIR}/fe.gc.log.$DATE:time"

**Comment by matrix-static** [comment]
I am run in shared_data mode.

fe.conf
run_mode = shared_data
cloud_native_meta_port = 6090
enable_load_volume_from_conf = true
cloud_native_storage_type = S3
aws_s3_path = kvm
aws_s3_endpoint = http://10.0.10.31:7480
aws_s3_access_key = xxx
aws_s3_secret_key = yyy

**Comment by matrix-static** [comment]
fe.log 
2023-10-20 19:23:22,100 INFO (main|1) [StarRocksFE.start():124] StarRocks FE starting, version: 3.0.7-208c9db
2023-10-20 19:23:22,108 INFO (main|1) [FrontendOptions.analyzePriorityCidrs():299] configured prior_cidrs value: 10.0.10.0/24
2023-10-20 19:23:22,112 INFO (main|1) [FrontendOptions.initAddrUseIp():249] Use IP init local addr, IP: /10.0.10.51
2023-10-20 19:23:22,393 INFO (main|1) [Auth.grantRoleInternal():835] grant operator to 'root'@'%', isReplay = true
2023-10-20 19:23:22,423 INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():277] create built-in role root[-1]
2023-10-20 19:23:22,428 INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():277] create built-in role db_admin[-2]
2023-10-20 19:23:22,429 INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():277] create built-in role cluster_admin[-3]
2023-10-20 19:23:22,429 INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():277] create built-in role user_admin[-4]
2023-10-20 19:23:22,429 INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():277] create built-in role public[-5]
2023-10-20 19:23:22,430 INFO (main|1) [GlobalStateMgr.initAuth():1055] using new privilege framework..
2023-10-20 19:23:22,639 INFO (main|1) [NodeMgr.getHelperNodes():656] get helper nodes: [10.0.10.51:9010]
2023-10-20 19:23:22,655 INFO (main|1) [NodeMgr.getClusterIdAndRoleOnStartup():449] Current run_mode is shared_data
2023-10-20 19:23:22,655 INFO (main|1) [NodeMgr.getClusterIdAndRoleOnStartup():456] Got cluster id: 943872521, role: FOLLOWER, node name: 10.0.10.51_9010_1697780347622 and run_mode: shared_data
2023-10-20 19:23:22,657 INFO (main|1) [BDBEnvironment.ensureHelperInLocal():340] skip check local environment because helper node and local node are identical.
2023-10-20 19:23:22,689 INFO (main|1) [BDBEnvironment.setupEnvironment():269] start to setup bdb environment for 1 times
2023-10-20 19:23:23,355 WARN (UNKNOWN 10.0.10.51_9010_1697780347622(-1)|1) [StateChangeExecutor.notifyNewFETypeTransfer():62] notify new FE type transfer: UNKNOWN
2023-10-20 19:23:23,374 INFO (UNKNOWN 10.0.10.51_9010_1697780347622(-1)|1) [BDBEnvironment.setupEnvironment():280] replicated environment is all set, wait for state change...
2023-10-20 19:23:23,374 WARN (RepNode 10.0.10.51_9010_1697780347622(-1)|56) [StateChangeExecutor.notifyNewFETypeTransfer():62] notify new FE type transfer: LEADER
2023-10-20 19:23:23,375 INFO (UNKNOWN 10.0.10.51_9010_1697780347622(-1)|1) [BDBEnvironment.setupEnvironment():288] state change done, current role LEADER

**Comment by kevincai** [comment]
please use 'be' for shared data mode if using 3.0.x version, 'cn' is not supported in shared-data mode in the release.

you can either use 3.1.x version with a better 'cn' support in shared data mode, or switch to 'be' for the computing engine.

**Comment by matrix-static** [comment]
I miss understand about 3.1.3, when i got this cn node error, may be i missed something?
error: F1019 17:40:58.383560 2014 threadpool.cpp:78] Check failed: max_threads > 0 (0 vs. 0)

**Comment by kevincai** [comment]
I see, can you switch to be for the test? I will check the cn max_threads issue.

**Comment by kevincai** [comment]
be/cn has nothing to do with shared-data or shared nothing, `be` can be used in `shared-data` mode as well.

**Comment by kevincai** [comment]
`F1019 17:40:58.383560 2014 threadpool.cpp:78] Check failed: max_threads > 0 (0 vs. 0)`

for this error, do you still have the `cn.out` content? can you paste it here?

**Comment by matrix-static** [comment]
wait , i just install a new instance, then sent to you.

**Comment by matrix-static** [comment]
could you check your email in gmail? and call to me?

**Comment by matrix-static** [comment]
cn.INFO
I1020 20:39:50.869894  3835 daemon.cpp:305]  version 3.1.3-384ba23
BuildType: RELEASE
Built on 2023-09-22 10:13:59 by StarRocks@localhost
I1020 20:39:50.871398  3835 mem_info.cpp:104] Physical Memory: 15.34 GB
I1020 20:39:50.871414  3835 daemon.cpp:311] Cpu Info:
  Model: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
  Cores: 16
  Max Possible Cores: 16
  L1 Cache: 32.00 KB (Line: 64.00 B)
  L2 Cache: 2.00 MB (Line: 64.00 B)
  L3 Cache: 16.00 MB (Line: 64.00 B)
  Hardware Supports:
    ssse3
    sse4_1
    sse4_2
    popcnt
    avx
    avx2
  Numa Nodes: 1
  Numa Nodes of Cores: 0->0 | 1->0 | 2->0 | 3->0 | 4->0 | 5->0 | 6->0 | 7->0 | 8->0 | 9->0 | 10->0 | 11->0 | 12->0 | 13->0 | 14->0 | 15->0 |
I1020 20:39:50.871433  3835 daemon.cpp:312] Disk Info: 
  Num disks 1: vda
I1020 20:39:50.871438  3835 daemon.cpp:313] Mem Info: 15.34 GB
I1020 20:39:50.871443  3835 daemon.cpp:314] CPU Info:
  Type: 0
  Family: 6
  Model: 79
  Stepping: 1
  ExtendModel: 4
  ExtendFamily: 0
  RunningInVM: 1
  Vendor: GenuineIntel
  Brand: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
  HardwareSupport: mmx sse sse2 sse3 ssse3 sse41 sse42 avx avx2 popcnt
W1020 20:39:50.939824  3835 timezone_utils.cpp:93] not found timezone:Africa/Casablanca
W1020 20:39:50.940464  3835 timezone_utils.cpp:93] not found timezone:Africa/El_Aaiun
I1020 20:39:51.016359  3835 daemon.cpp:288] Minidump is disabled
I1020 20:39:51.016469  3835 backend_options.cpp:100] priority cidrs in conf: 10.0.10.0/24
I1020 20:39:51.016575  3835 backend_options.cpp:77] localhost 10.0.10.61
I1020 20:39:51.016894  3835 exec_env.cpp:479] Set storage page cache size 2667918311
I1020 20:39:51.018465  3849 daemon.cpp:211] Current memory statistics: process(0), query_pool(0), load(0), metadata(0), compaction(0), schema_change(0), column_pool(0), page_cache(0), update(0), chunk_allocator(0), clone(0), consistency(0)
F1020 20:39:51.019168  3835 threadpool.cpp:78] Check failed: max_threads > 0 (0 vs. 0) 


cn.WARNNING
W1020 20:39:50.939824  3835 timezone_utils.cpp:93] not found timezone:Africa/Casablanca
W1020 20:39:50.940464  3835 timezone_utils.cpp:93] not found timezone:Africa/El_Aaiun
F1020 20:39:51.019168  3835 threadpool.cpp:78] Check failed: max_threads > 0 (0 vs. 0) 

there are four file in starrocks/log folder:
cn.INFO
cn.INFO.log.20231020-203950
cn.WARNING
cn.WARNING.log.20231020-203950

I am sorry to tell you no cn.out file in log folder.

**Comment by kevincai** [comment]
caused by incorrect configuration of `storage_root_path`, causes CN start crashing, related to code change in #30089

**Comment by kevincai** [comment]
should be already fixed.
