### ISSUE TITLE
Configurable replica placement policy

### ISSUE THREAD

**Issue by littleeleventhwolf** [StarRocks/starrocks#3317]
## Feature request

If we can config the replica placement, for example, second replica on the same rack with first replica, and third replica off the rack. It will provide better robustness.

**Describe the solution you'd like**
Let user config the different racks information, and SR place replicas in different racks according to configuration file.

**Comment by jaogoy** [comment]
Can you describe more info about racks, like, what's the feature of racks, IP prefix, or host name prefix, or other infos?

**Comment by littleeleventhwolf** [comment]
What I can see is,  the machines have name start with location name and end with serial number, e.g.  oklahoma-data-doris-be01.
