### ISSUE TITLE
Terraform provider resources management

### ISSUE THREAD

**Issue by svdimchenko** [StarRocks/starrocks#33184]
## Feature request

It would be nice to add following resources managemnt to terraform provider https://registry.terraform.io/providers/CelerData/celerdatabyoc/latest/docs:

- catalogs
- databases
- roles
- users
- groups
- grants

Terraform provider must support open source starrocks as well.

**Describe the solution you'd like**
Terraform provider supports mentioned resources.

**Describe alternatives you've considered**
If it's not implemented, seems some extra automation tool must be created from scratch.

**Additional context**
See an implementation example for [redshift](https://github.com/brainly/terraform-provider-redshift/tree/master)

**Comment by creativedutchmen** [comment]
This is a killer feature, and one that would greatly improve the ease of managing StarRocks / Celerdata clusters. Closing this seems like a mistake.
