### ISSUE TITLE
The size queried by show data is not  correctly

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#3345]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE t1
2. load data
3. show data from t1

### Expected behavior (Required)
exact size
### Real behavior (Required)
wrong size
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+------------------------------------------+
| current_version()                        |
+------------------------------------------+
| PIPELINE_SQLANCER_MASTER_RELEASE a87e76c |
+------------------------------------------+
```

**Comment by Astralidea** [comment]
This may not a problem.It may be that your data is particularly easy to compress.
You can use some of the following commands to help you identify the problem.
```
show partitions from $table
show tablet from $table
```
