### ISSUE TITLE
Question: Can StarRocks Read hudi data If data stored in local disk not hdfs Directory

### ISSUE THREAD

**Issue by littleDrew** [StarRocks/starrocks#33461]
Here I have question as for features that starRocks support read hudi data, more in detail is:
* If data stored in local disk(like given path ls `/home/xyz/hudi-data/table1`), whether starRocks can read it?
* And more, here i see currently read hudi data mainly call API in `hudi-hadoop-mr ` jar, whether it is possible to support read local disk data with using this jar?

Backgroud of this question: here spark and flink can read data whether data in hdfs directory or local disk directory, but whether starRocks can support both or only hdfs directory?

**Comment by littleDrew** [comment]
@miomiocat hello, do you have answer for my question~

**Comment by alberttwong** [comment]
You can also put it in S3. See https://github.com/StarRocks/starrocks/discussions/22947

**Comment by miomiocat** [comment]
> @miomiocat hello, do you have answer for my question~

Generally yes but we did not test this scenario.

All data is stored on local disk In your environment, so spark or flink is deployed with local mode?
