### ISSUE TITLE
BE slot leak in routine load

### ISSUE THREAD

**Issue by chen9t** [StarRocks/starrocks#33549]
### Steps to reproduce the behavior (Required)
1. Assume RoutineLoadJob create 2 sub tasks, and added into needScheduleTasksQueue;
2. The first task was submitted to execute, and job comes to PAUSE state because of "Kafka offset out of range" issue;
3. Meanwhile, the second task comes before [allocateTaskToBe()](https://github.com/StarRocks/starrocks/blob/main/fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadTaskScheduler.java#L211), and BE has not been allocated;
5. For the PAUSE procedure, ClearTask() will clear these 2 tasks from routineLoadTaskInfoList. BE of 1st task was released;
6. Then BE was allocated to task2, and submitted to execute. Finally aborted for same reason("Kafka offset out of range");
7. In [AfterAborted()](https://github.com/StarRocks/starrocks/blob/main/fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java#L1073), routineLoadTaskInfoOptional is not present, and BE will not be released. Which result in BE slot leak.

### Expected behavior (Required)
Not BE slot leak.

### Real behavior (Required)
BE slot was leaked.

### StarRocks version (Required)
latest version

**Comment by rickif** [comment]
Nice catch! I'll check the PR later.
