### ISSUE TITLE
Files() Supports sftp/ftp, and csv format

### ISSUE THREAD

**Issue by melin** [StarRocks/starrocks#33710]
## Feature request

files() Supports sftp/ftp, and csv format

**Comment by jaogoy** [comment]
@melin CSV format is in our plan, it will be released in V3.3 if possible.

About sftp/ftp, I want to know something more. Would you mind to share with me?
* How about the data size? Can you use Stream Load to ingest the data?
* What's the frequency to load the data? one-time for all data or daily loading?
* How about the performance to get data from the ftp server?
