### ISSUE TITLE
StarRocks 2.5.9 版本 基于 Hive catalog table 的 异步物化视图创建/刷新 抛出 hive 表不存在问题

### ISSUE THREAD

**Issue by mateng0915** [StarRocks/starrocks#33814]
### Steps to reproduce the behavior (Required)
1. 基于 Hive 表hive_test 创建了一张 异步物化视图 test_mv (设置为手动刷新)
2. 确认 test_mv 可以查询，可以刷新
3. 删除 hive_test, 再次创建同名 hive 表 hive_test
4. 刷新 异步物化视图 test_mv， 抛出异常 hive_test 不存在
5. 直接通过 starrocks hive catalog 查询 hive_test, 查询正常
6. 删除 test_mv, 重新创建 test_mv, 抛出异常 hive_test 不存在
7. 再次删除 test_mv, 重新创建 test_mv, 正常

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by Youngwb** [comment]
You could upgrafe the version of starrocks, this issue has been fix at latest version of brnach-3.1
