### ISSUE TITLE
when set  "partial_update" = "true"，The table column configuration " DEFAULT CURRENT_TIMESTAMP " is invalid

### ISSUE THREAD

**Issue by 15388915362** [StarRocks/starrocks#33872]
### Steps to reproduce the behavior (Required)
1、create Primary Key table ,two column are set to “AUTO_INCREMENT”  and "DEFAULT current_timestamp"。
![f81a6773d4df85c3bd2ef75d04390cc](https://github.com/StarRocks/starrocks/assets/45592110/0badbb77-3910-4a4a-a4c7-6e367566fd0c)

2、When load data(broker load or flinksql)，set  "partial_update" = "false", the column of "DEFAULT current_timestamp" is correct，but the column of "AUTO_INCREMENT"  will update every time when the same key value is written
3、when set  "partial_update" = "true"，The table column configuration " DEFAULT CURRENT_TIMESTAMP " is invalid.the column of    "AUTO_INCREMENT"  is correct
![6bd57bdfe4503eded220ddff7f45aaa](https://github.com/StarRocks/starrocks/assets/45592110/e3932366-fed7-4f07-b764-e070443ef6d5)

### StarRocks version (Required)
 3.1.0 and 3.1.2

**Comment by chaoyli** [comment]
@15388915362 Thank you, we will test it and fix it.

**Comment by 15388915362** [comment]
请问，DEFAULT CURRENT_TIMESTAMP  不生效的问题，会在近期版本修复吗
