### ISSUE TITLE
[function] convert_interval

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#33893]
there is a function request of to_milliseconds in trino.
link: https://trino.io/docs/current/functions/datetime.html#to_milliseconds

this function is a unique function of trino.  it is not found in other dbms like snowflake, databricks, bigquery, clickhouse.
it's functionality is to return a millisecond value from an interval. 
For example: 

```
select to_milliseconds(interval '1' second);

 _col0 
-------
  1000 

```

In StarRocks, we don't have a similar function that returns an int value from an interval input. For trino's compatibility, we need to support it natively.  And also, for more scenarios, this function could be more flexible. So here is a proposal:

### description

Returns the day-to-second interval as given unit.

### syntax

convert_interval(interval N type, to_type)

### parameters

- INTERVAL N type: the time granularity, for example, interval 5 second.
  - N is the length of time interval. It must be an INT value.
  - type is the unit, which can be DAY, HOUR, MINUTE, SECOND,  MILLISECOND, MICROSECOND. 

- to_type: unit that user want to convert to, which can be  DAY, HOUR, MINUTE, SECOND, MILLISECOND, MICROSECOND.

### output

bigint

### notice

- if the to_type is bigger than the interval type. For example, convert_interval( interval 1 second, day);, then it returns 0.

### examples

```
select convert_interval(interval 10 day, millisecond);

returns:
864000000 
```

```
select convert_interval(interval 10 day, day);

returns:
10
```

**Comment by wangsimo0** [comment]
@XinzhuangL Hi can you reply here so I can assign this issue to you

**Comment by XinzhuangL** [comment]
Hi @wangsimo0

**Comment by XinzhuangL** [comment]
Hi @wangsimo0  I have implemented the basic functionality, but I now have a few questions:

1. The conversion process may result in a value exceeding the maximum value of LONG, Now  I'm going to set it to a maximum of xxx, like TimeUnit.
2. I added MICROSECOND and MILLISECOND to *.g4,  if there are any unexpected effects?
3. Do I need to add a unit test?

**Comment by XinzhuangL** [comment]
#35420

**Comment by XinzhuangL** [comment]
1
