### ISSUE TITLE
Add rack concept like Hadoop

### ISSUE THREAD

**Issue by FrommyMind** [StarRocks/starrocks#34008]
## Feature request

**Is your feature request related to a problem? Please describe.**

No
**Describe the solution you'd like**

Each Fe and BE has it's own rack properties.

**Describe alternatives you've considered**

As we all know, distribution system, like hadoop, has a rack concept. Replicas of one data will spill into different server in different rack to prevent data lose when one entire rack lose from cluster.
**Additional context**

**Comment by milletnis** [comment]
We agree with this. For high availability reasons, "Rack Awareness" or "Location Awareness" is actually critical for high availability.

Example: We operate a containerized Starrocks cluster in which the BEs are divided into different fault domains and availability domains (= data centers). We guarantee that BEs are evenly distributed across the zones, but if replicas of tablets are located in the same server, rack, room, floor or building, the replica concept is not sufficient for high availability in the event of a large-scale failure (e.g. network).

It should be possible to place replicas based on rules similar to affinity or anti-affinity rules in Kubernetes.

Example of a well-implemented RACK AWARENESS
https://kudu.apache.org/2019/04/30/location-awareness.html

Are there any plans to implement this?
