### ISSUE TITLE
ADMIN SHOW REPLICA STATUS FROM db.table WHERE STATUS != "OK"  can't filter by STATUS

### ISSUE THREAD

**Issue by Haox-liu** [StarRocks/starrocks#34122]
### Steps to reproduce the behavior (Required)
ADMIN SHOW REPLICA STATUS FROM db.table WHERE STATUS != "OK";

### Expected behavior (Required)
expect results  doesn't contain replicas with status is "OK".

### Real behavior (Required)
real results is all replicas and contain replicas with status is "OK".
![image](https://github.com/StarRocks/starrocks/assets/16420851/0cb88ccf-6cbf-49e2-a467-e03d5e70acac)

### StarRocks version (Required)
 3.1.2

**Comment by imay** [comment]
This is duplicated with #32015
