### ISSUE TITLE
Query sql error:  Cancelled BufferControlBlock::cancel

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#3412]
This problem may not be stable reappear, please run the sql for several times.

### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS w3;
CREATE DATABASE w3;
USE w3;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 VARCHAR(1) NOT NULL ) UNIQUE KEY (c_0_0) DISTRIBUTED BY HASH (c_0_0) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 INT NULL ,c_1_1 VARCHAR(21) NOT NULL ,c_1_2 TINYINT NOT NULL ,c_1_3 SMALLINT NULL ,c_1_4 BOOLEAN NOT NULL ,c_1_5 CHAR(1) NULL ,c_1_6 DECIMAL(22, 11)  NOT NULL ,c_1_7 LARGEINT NULL ,c_1_8 VARCHAR(11) NULL ,c_1_9 DATETIME NULL ,c_1_10 BOOLEAN REPLACE NULL ,c_1_11 CHAR(21) MAX NULL ,c_1_12 PERCENTILE PERCENTILE_UNION NULL ,c_1_13 DATE REPLACE_IF_NOT_NULL NULL ) AGGREGATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6,c_1_7,c_1_8,c_1_9) DISTRIBUTED BY HASH (c_1_0,c_1_3,c_1_5,c_1_9,c_1_6,c_1_8,c_1_4) properties("replication_num"="3") ;
INSERT INTO t1 VALUES (1, "1G", 2, 15, true, "", 0.32238399747, 251837969, "H", "1970-01-01 08:00:00", false, NULL, percentile_hash("-1825261417"), "1970-01-01"), (27, "uFx", 1, 15, true, "", 0.98666314854, 1515239949, "b", NULL, false, "s", percentile_hash("-910821167"), "1970-01-01"), (6, "ktWh", 7, 3, true, "", 0.80151348397, NULL, "Jr", "1970-01-01 08:00:00", NULL, "rr", percentile_hash("-1826697334"), "1970-01-01");
TRUNCATE TABLE t1;
DELETE FROM t1 WHERE c_1_9="1969-12-09 16:02:27" AND c_1_3=1544741200 AND c_1_2=2120815199 AND c_1_1="" AND c_1_7=-2027666357 AND c_1_0=-618338605;
DELETE FROM t1 WHERE c_1_4=false AND c_1_7=-1187192786 AND c_1_8="0zg" AND c_1_3=1306164014 AND c_1_0=NULL AND c_1_1="" AND c_1_6=0.57285997209 AND c_1_2=-422367574 AND c_1_9="1970-01-19 04:26:52";
2. mysql>  SELECT t0.c_0_0 FROM  t0 LEFT SEMI JOIN (SELECT t1.c_1_0, t1.c_1_1, t1.c_1_2, t1.c_1_3, t1.c_1_4, t1.c_1_5, t1.c_1_6, t1.c_1_7, t1.c_1_8, t1.c_1_9, t1.c_1_10, t1.c_1_11,
t1.c_1_13 FROM t1 WHERE  ( "1969-12-13" ) > ( DATE_TRUNC("", "1970-01-08 23:55:12")  ) ) subt1 ON t0.c_0_0 = subt1.c_1_0 AND CAST(42 AS STRING )  != ((1983286810)-(1646376959)) AND t0.c_0_0 != subt1.c_1_11 AND t0.c_0_0 != subt1.c_1_11 AND t0.c_0_0 <= subt1.c_1_0 AND t0.c_0_0 <= subt1.c_1_0;
ERROR 1064 (HY000): Cancelled BufferControlBlock::cancel

```
fe.log:
2022-02-16 14:31:06,829 INFO (starrocks-mysql-nio-pool-45|2059) [QeProcessorImpl.registerQuery():69] register query id = 0591224c-8ef2-11ec-aa8f-00163e137b38, job: -1
2022-02-16 14:31:19,573 WARN (starrocks-mysql-nio-pool-45|2059) [Coordinator.getNext():731] get next fail, need cancel. status errorCode CANCELLED Cancelled BufferControlBlock::cancel, query id: 0591224c-8ef2-11ec-aa8f-00163e137b38
2022-02-16 14:31:19,573 WARN (starrocks-mysql-nio-pool-45|2059) [Coordinator.updateStatus():712] one instance report fail throw updateStatus(), need cancel. job id: -1, query id: 0591224c-8ef2-11ec-aa8f-00163e137b38, instance id: NaN
2022-02-16 14:31:19,573 INFO (starrocks-mysql-nio-pool-45|2059) [QeProcessorImpl.unregisterQuery():79] deregister query id 0591224c-8ef2-11ec-aa8f-00163e137b38

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.1 ASAN
 - mysql> select current_version();
+------------------------------+
| current_version() |
+------------------------------+
| SQLANCER_01_ASAN 317a367|
+------------------------------+

**Comment by kangkaisen** [comment]
Couldn't reproduce.
