### ISSUE TITLE
Add Ability to Reset Properties to Default Values in ALTER TABLE and ROUTINE LOAD Statements

### ISSUE THREAD

**Issue by ChenlingXie** [StarRocks/starrocks#34174]
### Summary:
I would like to request a feature enhancement for StarRocks. Specifically, I propose the addition of a capability in the ALTER TABLE and ROUTINE LOAD statements that would allow users to reset specific properties to their default values. This feature would be similar to Flink SQL's "ALTER RESET" syntax.

### Motivation:
There are situations where users may want to reset specific properties to their default values in their StarRocks tables or routines. Currently, there is no built-in mechanism to achieve this, and users must manually specify the default values. The proposed enhancement would provide a convenient and consistent way to reset properties.

### Use Case:
Consider a scenario where a user has customized several properties in a StarRocks table or routine, and they want to revert some of these properties to their default settings. With the proposed feature, they could use an "ALTER RESET" syntax in the ALTER TABLE or ROUTINE LOAD statements to achieve this.

### Syntax Example:
For example, the proposed syntax could look like this:
```sql
-- reset 'rows-per-second' to the default value
ALTER TABLE DataGenSource RESET ('rows-per-second');
```

```sql
ALTER ROUTINE LOAD FOR db1.label1
RESET PROPERTIES
(
    "desired_concurrent_number"
)
```

**Comment by ChenlingXie** [comment]
need this  issue

**Comment by jaogoy** [comment]
You can directly set the value to the default value instead. And if the default value for a property is not listed in the docs, we should add/optimize it.
