### ISSUE TITLE
Start of FE is time consuming

### ISSUE THREAD

**Issue by chaoyli** [StarRocks/starrocks#3420]
After thousands of tables and databases have been created and dropped. The meta will have much information.
Upon restart, the CatalogRecycleBin mush replays the journal. The start will last five minutes and more.
![image](https://user-images.githubusercontent.com/44767902/154225979-f4f2c8a7-ae20-4129-b2f7-4d35257917b7.png)

**Comment by Astralidea** [comment]
This already resloved
