### ISSUE TITLE
Ordering of JSON keys could not be kept 

### ISSUE THREAD

**Issue by yaoyu73100** [StarRocks/starrocks#34217]
**Is your feature request related to a problem? Please describe.**
写入sr时，json类型字段默认按照key的顺序排序，无法保持写入前的json数据顺序
而且key冒号后多了空格

**Describe the solution you'd like**
sr的json字段中key的顺序应该保持写入前的顺序，json的key后不需要加入空格

**Describe alternatives you've considered**

**Additional context**
CREATE TABLE `test_json_table` (
  `id` bigint(20) NOT NULL COMMENT "id",
  `reason_detail` json NULL COMMENT "停机原因详情"
) ENGINE=OLAP 
PRIMARY KEY(`id`)
COMMENT ""
DISTRIBUTED BY HASH(`id`) BUCKETS 12 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "true",
"compression" = "LZ4"
);

INSERT INTO `test_json_table` VALUES 
(1, '{\"hkey\": [\"9960148\", \"9960153\", \"9960156\", \"9960150\"], \"dkey\": [\"9970098\", \"9970042\", \"9970042\", \"9970042\"], \"skey\": \"test content\", \"akey\": \"9960148\", \"vkey\": \"9970098\", \"ikey\": \"test content\", \"wkey\": \"9960042\"}');

select reason_detail from test_json_table where id=1;

{"akey": "9960148", "dkey": ["9970098", "9970042", "9970042", "9970042"], "hkey": ["9960148", "9960153", "9960156", "9960150"], "ikey": "test content", "skey": "test content", "vkey": "9970098", "wkey": "9960042"}

**Comment by mofeiatwork** [comment]
As JSON spec, there's no requirement for the ordering of json keys. 

If you need to keep the order, you should put them into kinda arrays.
