### ISSUE TITLE
read jdbc (sr) catalog tablename   error

### ISSUE THREAD

**Issue by yaobukeji123** [StarRocks/starrocks#34320]
### Steps to reproduce the behavior (Required)
![image](https://github.com/StarRocks/starrocks/assets/35523218/c62082a6-6f6c-4def-970f-24d881357c95)

### Expected behavior (Required)
work normal as 3.1.3 
we can list tables in sr_old according to jdbc catalog 
### Real behavior (Required)
![image](https://github.com/StarRocks/starrocks/assets/35523218/b714ed86-9bae-45fa-ac6a-c51f1bb6ee39)
![image](https://github.com/StarRocks/starrocks/assets/35523218/8df28fb7-7aa5-44ac-ba65-cdd6c3e2e351)

### StarRocks version (Required)
 - 3.1.4 on k8s shared data

**Comment by zombee0** [comment]
could you check is there a table named partitions in information_schema in your mysql server?

**Comment by yaobukeji123** [comment]
my  new sr is 3.1.4 version. it is meta information_schema has the table
but my catalog jdbc old sr is 2.5.13, it not has the table in information_schema 
so select from old_sr it not work

**Comment by WholeWorld-Timothy** [comment]
Can error messages be pasted with text?
