### ISSUE TITLE
Support MariaDB PowerBI connector for Direct Query

### ISSUE THREAD

**Issue by snippins** [StarRocks/starrocks#34343]
## Feature request

**Is your feature request related to a problem? Please describe.**
I'm investigating using Starrocks as the backend database for visualizing with PowerBI. I was able to use import mode in with the MySQL Connector in PowerBI, however, this seems to defeat the purpose as I could not use the query power of StarRocks itself.

Furthermore, I notice that MariaDB support Direct Query mode for their connector, and I was able to use it with an actual Mysql database, however when I'm trying to use the connector with Starrocks, I was not able to see the list of databases. Trying to enter the database name resulted in the error "The key didn't match any rows in the table".

**Describe the solution you'd like**
Either:
- Make some changes to Starrocks so that we can use the Mariadb connector.
- Create an PowerBI connector for Starrocks that allows Direct Query.

I don't know which way is easier. For me, however, I would love to try making the second option happen myself, but I'm quite lost at how to check for the difference between Starrocks vs Mysql/Mariadb. All I know now is that the above error suggests the connector is querying some table for the database name, but is not able to find it.

**Comment by alberttwong** [comment]
A PowerBi connector is available in the cloud/enterprise version of StarRocks by CelerData.

**Comment by snippins** [comment]
@alberttwong We've been using starrocks for a while with other BI tools, however the need for PowerBI connector recently comes up again. We could not use CelerData BYOC on AWS or Azure, but would willing to pay for the connector, is this possible @alberttwong
