### ISSUE TITLE
Table INFORMATION_SCHEMA.SCHEMATA is not correctly populated and is different from mysql-server

### ISSUE THREAD

**Issue by snippins** [StarRocks/starrocks#34355]
I found this bug while investigating solutions for this feature request https://github.com/StarRocks/starrocks/issues/34343:

MariaDB odbc driver use information_schema.SCHEMATA to list the databases, and there seems to be mismatched between Starrocks and an actual Mysql Server, this leads to the ODBC driver unable to list databases. Consequentially, this makes the MariaDB PowerBI connector (which use the ODBC driver) unable to list and use Starrocks databases.

### Steps to reproduce the behavior (Required)
Run this command 2 times on connecting to starrocks and mysql server

`select * from information_schema.SCHEMATA`

### Expected behavior (Required)
The CATALOG_NAME column's values should not be null.

### Real behavior (Required)
The CATALOG_NAME column's values are all nulls.

- starrocks
![image](https://github.com/StarRocks/starrocks/assets/6032077/1db71d69-7503-4541-baf4-eb1a4bfc4f89)

- mysql server
![image](https://github.com/StarRocks/starrocks/assets/6032077/825ad6a5-e315-430a-89c1-6529a492d06f)

### StarRocks version (Required)
3.1.4-0c4b2a3

**Comment by imay** [comment]
@snippins thanks for pointing it out. Do you want to create a pull request to fix it?

**Comment by snippins** [comment]
@imay Sorry, I don't know how to fix it. I would have already made a PR if I did. :)

**Comment by imay** [comment]
No worries, my teams will fix it.
