### ISSUE TITLE
/api/show_data automatically aggregates results by db or table

### ISSUE THREAD

**Issue by sduzh** [StarRocks/starrocks#34477]
## Feature request
Provides an option to count the data size of all databases or tables via the RESTful API `/api/show_data`.

**Comment by Jin-H** [comment]
I want try this task, can you assign it to me?

**Comment by sduzh** [comment]
> I want try this task, can you assign it to me?

Of course! If you have any questions, please feel free to discuss with me at any time.

**Comment by Jin-H** [comment]
> ## Feature request
> Provides an option to count the data size of all databases or tables via the RESTful API `/api/show_data`.

I have a question about this requirement. Should I provide a table parameter to indicate that I want to count the current table size? 

In `show data` statement we can calculate each table size in table format 

```shell
StarRocks > show data;
+--------------------------+----------------+---------------------+
| TableName                | Size           | ReplicaCount        |
+--------------------------+----------------+---------------------+
| table_1                       | 587.555 KB     | 36                  |
| table_2                      | 88.386 KB       | 36                  |
| table_3                      | 433.913 KB     | 36                  |
| table_4                      | 0.000 B           | 36                  |
| table_5                      | 71.426 KB       | 36                  |
| table_6                      | 166.251 KB     | 36                  |
| table_7                      | 49.008 KB      | 36                  |
| table_8                      | 6.404 MB       | 36                  |
| table_9                      | 5.617 MB        | 36                  |
| table_10                    | 433.913 KB     | 36                  |
| Total                          | 13.809 MB      | 360                 |
| Quota                        | 8388608.000 TB | 9223372036854775807 |
| Left                            | 8388608.000 TB | 9223372036854775447 |
+--------------------------+----------------+---------------------+
```

Do we want to remain unified?

**Comment by sduzh** [comment]
> > ## Feature request
> > Provides an option to count the data size of all databases or tables via the RESTful API `/api/show_data`.
> 
> I have a question about this requirement. Should I provide a table parameter to indicate that I want to count the current table size?
> 
> In `show data` statement we can calculate each table size in table format
> 
> ```shell
> StarRocks > show data;
> +--------------------------+----------------+---------------------+
> | TableName                | Size           | ReplicaCount        |
> +--------------------------+----------------+---------------------+
> | table_1                       | 587.555 KB     | 36                  |
> | table_2                      | 88.386 KB       | 36                  |
> | table_3                      | 433.913 KB     | 36                  |
> | table_4                      | 0.000 B           | 36                  |
> | table_5                      | 71.426 KB       | 36                  |
> | table_6                      | 166.251 KB     | 36                  |
> | table_7                      | 49.008 KB      | 36                  |
> | table_8                      | 6.404 MB       | 36                  |
> | table_9                      | 5.617 MB        | 36                  |
> | table_10                    | 433.913 KB     | 36                  |
> | Total                          | 13.809 MB      | 360                 |
> | Quota                        | 8388608.000 TB | 9223372036854775807 |
> | Left                            | 8388608.000 TB | 9223372036854775447 |
> +--------------------------+----------------+---------------------+
> ```
> 
> Do we want to remain unified?

I think it's ok.

**Comment by kevincai** [comment]
@Jin-H are you still working on this issue?
