### ISSUE TITLE
Query fails to hit asynchronous materialised views

### ISSUE THREAD

**Issue by moody1117** [StarRocks/starrocks#34485]
### Steps to reproduce the behavior (Required)
CREATE TABLE realtime.`dwd_bolean_sa_flow_standard_detail_ri_30` (
  `flow_ts` DATETIME  NOT NULL COMMENT "流量发生时间",
  `id` BIGINT NOT NULL COMMENT "雪花id",
  `region` STRING NULL COMMENT "区域",
  `src_id` STRING NULL COMMENT "来源设备编号",
  `src_type` STRING NULL COMMENT "来源设备类型",
  `src_name` STRING NULL COMMENT "来源设备资产名称",
  `src_group` STRING NULL COMMENT "来源设备资产组",
  `src_ip` STRING NULL COMMENT "来源IP",
  `dst_ip` STRING NULL COMMENT "目的IP",
  `src_mac` STRING NULL COMMENT "来源MAC",
  `dst_mac` STRING NULL COMMENT "目的MAC",
  `src_port` INT NULL COMMENT "来源端口",
  `dst_port` INT NULL COMMENT "目的端口",
  `l4_pact` STRING NULL COMMENT "传输层协议",
  `l7_pact` STRING NULL COMMENT "应用层协议",
  `func_code` STRING NULL COMMENT "功能码json",
  `byte_size` INT NULL COMMENT "字节数",
  `flow_ts_raw` BIGINT NOT NULL COMMENT "13位时间戳",
  `flow_content` STRING NULL COMMENT "流量内容",
  `dst_asset_group` STRING NULL COMMENT "目的IP资产组",
  `dst_asset_group_id` BIGINT NULL COMMENT "目的IP资产组编号",
  `asset_id` BIGINT NULL COMMENT "目的IP资产编号",
  `asset_name` STRING NULL COMMENT "目的IP资产名称"
) ENGINE=OLAP 
DUPLICATE KEY(`flow_ts`,`id`)
COMMENT "OLAP"
PARTITION BY RANGE(`flow_ts`)
(START ("2023-10-20") END ("2023-10-31") EVERY (INTERVAL 1 day))
DISTRIBUTED BY HASH(`flow_ts`) BUCKETS 48
PROPERTIES (
"replication_num" = "1",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-30",
"dynamic_partition.end" = "30",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "48",
"in_memory" = "false",
"compression" = "LZ4",
"storage_format" = "DEFAULT");

-- 异步物化视图
-- drop MATERIALIZED VIEW dst_ip_mv;
CREATE MATERIALIZED VIEW dst_ip_mv
DISTRIBUTED BY HASH(`dst_ip`) 
REFRESH ASYNC EVERY (interval 20 SECOND) 
AS
select dst_ip,count(dst_ip) as cnt 
from dwd_bolean_sa_flow_standard_detail_ri_30
group by dst_ip;

-- 查看执行计划是否命中物化视图 
EXPLAIN LOGICAL select dst_ip,count(dst_ip) as cnt 
from dwd_bolean_sa_flow_standard_detail_ri_30
group by dst_ip;

### Expected behavior (Required)
- SCAN [dst_ip_mv] => [9:dst_ip]

### Real behavior (Required)
![image](https://github.com/StarRocks/starrocks/assets/50506546/eaf7e6cc-a2cf-4bd4-8266-98277a421ee2)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
sr version: 3.1.4-opt (unofficial)
![image](https://github.com/StarRocks/starrocks/assets/50506546/9dac881f-4c6a-4161-a71b-c3aa56a7ae28)

**Comment by ABingHuang** [comment]
hi, how frequent do you update your base table dwd_bolean_sa_flow_standard_detail_ri_30?

**Comment by moody1117** [comment]
Because it is a test environment, the base table is not currently updated。

---- Replied Message ----
| From | ***@***.***> |
| Date | 11/07/2023 14:49 |
| To | StarRocks/starrocks ***@***.***> |
| Cc | Moody ***@***.***>,
Author ***@***.***> |
| Subject | Re: [StarRocks/starrocks] Query fails to hit asynchronous materialised views (Issue #34485) |

hi, how frequent do you update your base table dwd_bolean_sa_flow_standard_detail_ri_30?

**Comment by ABingHuang** [comment]
try to refresh the mv by
refresh materialized view dst_ip_mv;
and then query again.
I guess the mv is not refreshed.

**Comment by moody1117** [comment]
> try to refresh the mv by refresh materialized view dst_ip_mv; and then query again. I guess the mv is not refreshed.
I turned on the flink task to write to this base table in real time and manually refreshed the materialised view, and found through the execution plan that it didn't hit the materialised view. I don't know if it's a problem with the version I'm using, it's not the official 3.1.4 version!

![image](https://github.com/StarRocks/starrocks/assets/50506546/cce5daa1-a52a-43b7-8688-f935c0613109)
![image](https://github.com/StarRocks/starrocks/assets/50506546/3f0fd96d-cf8c-4560-9b75-3f52c7820d7d)
![image](https://github.com/StarRocks/starrocks/assets/50506546/8af481f5-e0b6-4687-87e5-dd77d15f6e2c)

**Comment by ABingHuang** [comment]
there is a consistence check during mv rewrite. When base table updated, mv is outdated, mv will not be used to rewrite.
use the following sql to get some logs:
trace rewrite select dst_ip,count(dst_ip) as cnt
from dwd_bolean_sa_flow_standard_detail_ri_30
group by dst_ip;

**Comment by moody1117** [comment]
> there is a consistence check during mv rewrite. When base table updated, mv is outdated, mv will not be used to rewrite. use the following sql to get some logs: trace rewrite select dst_ip,count(dst_ip) as cnt from dwd_bolean_sa_flow_standard_detail_ri_30 group by dst_ip;

![image](https://github.com/StarRocks/starrocks/assets/50506546/351cf635-b816-4081-a702-abdcfa0a9abb)
![image](https://github.com/StarRocks/starrocks/assets/50506546/27b1c0f7-2050-41db-9de6-379189ca123a)

**Comment by ABingHuang** [comment]
now mv is not recommended in realtime streaming situation, if you want to use mv, you can reference this doc:
https://docs.starrocks.io/zh-cn/latest/using_starrocks/troubleshooting_asynchronous_materialized_views#%E7%89%A9%E5%8C%96%E8%A7%86%E5%9B%BE%E6%97%A0%E6%B3%95%E6%94%B9%E5%86%99%E6%9F%A5%E8%AF%A2
consider these two properties:
![image](https://github.com/StarRocks/starrocks/assets/101158374/fa1988aa-45c9-4a6e-baa2-d77c34d158de)

**Comment by moody1117** [comment]
> now mv is not recommended in realtime streaming situation, if you want to use mv, you can reference this doc: https://docs.starrocks.io/zh-cn/latest/using_starrocks/troubleshooting_asynchronous_materialized_views#%E7%89%A9%E5%8C%96%E8%A7%86%E5%9B%BE%E6%97%A0%E6%B3%95%E6%94%B9%E5%86%99%E6%9F%A5%E8%AF%A2 consider these two properties: ![image](https://user-images.githubusercontent.com/101158374/281248958-fa1988aa-45c9-4a6e-baa2-d77c34d158de.png)

Ok, I'll try that, will the subsequent materialised views provide better support for streaming scenarios

**Comment by moody1117** [comment]
> now mv is not recommended in realtime streaming situation, if you want to use mv, you can reference this doc: https://docs.starrocks.io/zh-cn/latest/using_starrocks/troubleshooting_asynchronous_materialized_views#%E7%89%A9%E5%8C%96%E8%A7%86%E5%9B%BE%E6%97%A0%E6%B3%95%E6%94%B9%E5%86%99%E6%9F%A5%E8%AF%A2 consider these two properties: ![image](https://user-images.githubusercontent.com/101158374/281248958-fa1988aa-45c9-4a6e-baa2-d77c34d158de.png)

![image](https://github.com/StarRocks/starrocks/assets/50506546/df244d98-dd4b-4991-9c02-810b9d03af88)

**Comment by ABingHuang** [comment]
Streaming Materialized View is for streaming situation. It is on our roadmap, but we currently do not have a specific timeline.

**Comment by moody1117** [comment]
> now mv is not recommended in realtime streaming situation, if you want to use mv, you can reference this doc: https://docs.starrocks.io/zh-cn/latest/using_starrocks/troubleshooting_asynchronous_materialized_views#%E7%89%A9%E5%8C%96%E8%A7%86%E5%9B%BE%E6%97%A0%E6%B3%95%E6%94%B9%E5%86%99%E6%9F%A5%E8%AF%A2 consider these two properties: ![image](https://user-images.githubusercontent.com/101158374/281248958-fa1988aa-45c9-4a6e-baa2-d77c34d158de.png)

Can I avoid the problem of long response to querying the base table by querying the materialised view directly

**Comment by ABingHuang** [comment]
> directly

yes, mv can be read directly.

**Comment by moody1117** [comment]
> > directly
> 
> yes, mv can be read directly.The current business goal is to ensure that the response time and resource consumption for querying large data volume tables can tolerate a certain delay in results

**Comment by ABingHuang** [comment]
> * 3.1.4

which version do you use?  3.1.4?

**Comment by ABingHuang** [comment]
> > > directly
> > 
> > 
> > yes, mv can be read directly.The current business goal is to ensure that the response time and resource consumption for querying large data volume tables can tolerate a certain delay in results

then mv_rewrite_staleness_second may be useful.

**Comment by moody1117** [comment]
> > * 3.1.4
> 
> which version do you use? 3.1.4?

It's an unofficial version , should be 3.1.4-opt

**Comment by ABingHuang** [comment]
it is bit weird. I will check it.

**Comment by moody1117** [comment]
> it is bit weird. I will check it.
I tried upgrading to version 3.1.4 on the website to test it.
