### ISSUE TITLE
The query result for the synchronized materialized view was incorrect 

### ISSUE THREAD

**Issue by Shan-01** [StarRocks/starrocks#34567]
### Steps to reproduce the behavior (Required)
```
CREATE TABLE sales_records(
record_id INT,
seller_id INT,
store_id INT,
sale_date DATE,
sale_amt BIGINT
) DISTRIBUTED BY HASH(record_id);
```

```
INSERT INTO sales_records
VALUES
(001,01,1,"2022-03-13",8573),
(002,02,2,"2022-03-14",6948),
(003,01,1,"2022-03-14",4319),
(004,03,3,"2022-03-15",8734),
(005,03,3,"2022-03-16",4212),
(006,02,2,"2022-03-17",9515);
```

```
CREATE MATERIALIZED VIEW store_amt AS
SELECT store_id, SUM(sale_amt)
FROM sales_records
GROUP BY store_id;
```

```
SELECT store_id, SUM(sale_amt)
FROM sales_records
GROUP BY store_id;
```
![image](https://github.com/StarRocks/starrocks/assets/116535280/0a0b5145-076b-4804-94d6-db93f6513883)

SELECT * FROM store_amt [SYNC_MV];
![image](https://github.com/StarRocks/starrocks/assets/116535280/59c1d969-4dc3-47b7-b1ea-2030f554420a)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
![image](https://github.com/StarRocks/starrocks/assets/116535280/7af283a6-294f-4e6b-871a-f6600f863966)

**Comment by ysq5202121** [comment]
可能与分桶键有一定的关系，如果不在同一个桶中无法合并数据
DISTRIBUTED BY HASH(store_id); 
上面这样设置是可以实现合并数据的
具体是否这个原因也不清楚
