### ISSUE TITLE
在starrocks中进行表或库授权，当表/库不存在时，应该给出报错信息。

### ISSUE THREAD

**Issue by dengjoy2000** [StarRocks/starrocks#34589]
版本：2.5.5
现有版本在授权时，即使库/表不存在，也能授权GRANT成功。然后再show grants 里会显示这个实际上是错误的授权造成困扰。

希望的增强：
在starrocks中进行表/库授权，当表/库不存在时，应该给出报错信息，给用户明确的信息。

**Comment by HangyuanLiu** [comment]
新版本的rbac已经支持，可以使用最新版本
