### ISSUE TITLE
[Feature] With recursive syntax support

### ISSUE THREAD

**Issue by vkingnew** [StarRocks/starrocks#34616]
With recursive syntax support please. With recursive syntax had as SQL standard, and it's wide used by oracle,db2,mysql,postgresql and so on.

 refer to MySQL:
https://dev.mysql.com/doc/refman/8.0/en/with.html#common-table-expressions-recursive

refer to Postgresql:
https://www.postgresql.org/docs/current/queries-with.html#QUERIES-WITH-RECURSIVE

**Comment by abfisher0417** [comment]
It would be amazing if this could be re-considered. I added a comment on #16213.

**Comment by SebastianHindhedeAdvisoa** [comment]
+1 will be useful for gapfilling timeseries data

**Comment by Peschido** [comment]
+1
