### ISSUE TITLE
Query sql result error

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#3478]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE IF NOT EXISTS t0 (c_0_0 BOOLEAN NULL ,c_0_1 BOOLEAN NULL ,c_0_2 VARCHAR(41) NULL ,c_0_3 DECIMAL(2, 1)  NOT NULL ) UNIQUE KEY (c_0_0) DISTRIBUTED BY HASH (c_0_0) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 LARGEINT NOT NULL ,c_1_1 VARCHAR(1) NULL ,c_1_2 LARGEINT NOT NULL ,c_1_3 SMALLINT NOT NULL ,c_1_4 VARCHAR(11) NOT NULL ,c_1_5 SMALLINT NULL ,c_1_6 DECIMAL(10, 2)  NOT NULL ,c_1_7 CHAR(11) NOT NULL ) DUPLICATE KEY (c_1_0,c_1_1) DISTRIBUTED BY HASH (c_1_1) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t2 (c_2_0 TINYINT NOT NULL ,c_2_1 DECIMAL(15, 7)  NOT NULL ,c_2_2 BOOLEAN NULL ,c_2_3 BOOLEAN NULL ,c_2_4 DATETIME NOT NULL ,c_2_5 CHAR(1) NULL ,c_2_6 LARGEINT NULL ,c_2_7 DATE NOT NULL ,c_2_8 DECIMAL(34, 19)  NOT NULL ,c_2_9 LARGEINT NULL ) UNIQUE KEY (c_2_0,c_2_1,c_2_2,c_2_3,c_2_4,c_2_5,c_2_6,c_2_7) DISTRIBUTED BY HASH (c_2_6,c_2_4,c_2_2,c_2_1,c_2_0,c_2_5,c_2_3,c_2_7) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t3 (c_3_0 LARGEINT NOT NULL ,c_3_1 TINYINT NOT NULL ,c_3_2 DECIMAL(16, 11)  NULL ,c_3_3 TINYINT NULL ,c_3_4 DECIMAL(1, 0)  NOT NULL ,c_3_5 DECIMAL(16, 7)  NULL ,c_3_6 DECIMAL(8, 1)  NOT NULL ,c_3_7 BOOLEAN NULL ,c_3_8 DECIMAL(1, 0)  NOT NULL ,c_3_9 LARGEINT NULL ,c_3_10 LARGEINT NOT NULL ,c_3_11 BOOLEAN NULL ,c_3_12 SMALLINT NULL ,c_3_13 VARCHAR(1) NOT NULL ,c_3_14 DECIMAL(18, 6)  MIN NULL ) AGGREGATE KEY (c_3_0,c_3_1,c_3_2,c_3_3,c_3_4,c_3_5,c_3_6,c_3_7,c_3_8,c_3_9,c_3_10,c_3_11,c_3_12,c_3_13) DISTRIBUTED BY HASH (c_3_0,c_3_1,c_3_13,c_3_3,c_3_8,c_3_9,c_3_4,c_3_7,c_3_12,c_3_11,c_3_6) properties("replication_num"="3") ;
INSERT INTO t1 VALUES (-1078398059, "", -726010725, 0, "qQ", 10, 116652.55, ""), (1665734916, "", 163588185, 10, "", 10, 92906.45, ""), (573269337, "", 747144672, 4, "", 11, 208107.91, "YDqc8c");
INSERT INTO t1 VALUES (-180575223, NULL, 653434271, 13, "gJJqPd9Q", 5, 900708.96, "aw44vp"), (-2054657788, NULL, 142341515, 7, "5", NULL, 37737.35, "7k");
INSERT INTO t2 VALUES (6, 1.0855670, true, true, "1970-01-01 08:00:00", "", -1054432730, "1970-01-01", 0.0000071999790618874, NULL), (6, 9.6530824, true, false, "1970-01-01 08:00:00", "", 535014978, "1970-01-01", 0.0000936882718876624, -1973201942), (7, 5.3288339, false, false, "1970-01-01 08:00:00", "", -1417992336, "1970-01-01", 0.0000499056247127803, 1951704594);
INSERT INTO t2 VALUES (5, 7.0905772, true, true, "1970-01-01 08:00:00", "", 312418344, "1970-01-01", 0.0000417653404340336, 561116665), (5, 6.7749228, false, true, "1970-01-01 08:00:00", "", 2103602302, "1970-01-01", 0.0000164429482714252, -126130197);
INSERT INTO t0 VALUES (true, true, "", 0.1);
INSERT INTO t2 VALUES (4, 2.0645766, false, false, "1970-01-01 08:00:00", "", NULL, "1970-01-01", 0.0000726701252394884, -92105439);
INSERT INTO t3 VALUES (355150057, 3, 1.8405E-7, 2, 0, 51.8218973, 502812.0, true, 1, -1318073265, -1927066323, false, 9, "", 514986.335606), (-419229502, 3, 9.507E-8, 4, 3, NULL, 598390.4, true, 8, 470212480, 1577021534, false, 7, "", 99766.340571);
TRUNCATE TABLE t3;
INSERT INTO t1 VALUES (-171611304, "", -352711266, 7, "", 3, 481106.62, ""), (597654578, NULL, -832509534, 9, "", 9, 395661.31, ""), (1398606362, NULL, -1718155025, 2, "e", 7, 879488.79, "ymL");
INSERT INTO t1 VALUES (1596716644, NULL, -693581438, 13, "UO3DP", 10, 138282.63, "SvsM");
INSERT INTO t0 VALUES (true, true, "K", 0.2), (false, false, "S", 0.1);
INSERT INTO t3 VALUES (540816070, 3, 1.1603E-7, 3, 0, 94.2680214, 238174.5, true, 0, 491043858, 659422157, false, 10, "", NULL);
DELETE FROM t1 WHERE c_1_1="";
INSERT INTO t3 VALUES (1456925303, 2, 6.4378E-7, 7, 2, NULL, 243764.6, true, 0, -1512429819, -725419465, true, 15, "", 974026.709159), (-1278563631, 1, 9.7028E-7, 1, 1, 57.1484629, 939888.0, false, 1, -1439558413, 1203940715, true, 5, "", 503167.680772);
INSERT INTO t2 VALUES (2, 7.5584223, false, false, "1970-01-01 08:00:00", "", -75286599, "1970-01-01", 0.0000979631542599670, -1525374663), (1, 0.9940500, false, NULL, "1970-01-01 08:00:00", "", 1070272600, "1970-01-01", 0.0000096899302615447, -2002440769), (7, 4.4015452, true, NULL, "1970-01-01 08:00:00", "", 991171515, "1970-01-01", 0.0000031506337324072, 1504178559);
INSERT INTO t3 VALUES (-514618523, 0, 4.633E-8, 1, 7, 64.7514240, 554902.0, true, 5, 1412144810, -335587616, true, 4, "", 260964.582421), (1552932460, 7, 8.4958E-7, 5, 6, 56.5776355, 253445.8, NULL, 4, 1495715487, 478234153, true, 4, "", 584174.602644), (321599669, 7, NULL, 0, 7, 18.6814080, 340544.1, false, 0, -555038844, 595458307, true, 1, "", 321655.121539);
-- SELECT t1.c_1_0 FROM t1, t0, t3;
-- cardinality: 60
-- SELECT t1.c_1_0 FROM t1, t0, t3 WHERE CAST(t1.c_1_6 AS BOOLEAN )  ORDER BY t1.c_1_1, t1.c_1_3;SELECT t1.c_1_0 FROM t1, t0, t3 WHERE (NOT (CAST(t1.c_1_6 AS BOOLEAN ) )) ORDER BY t1.c_1_1, t1.c_1_3;SELECT t1.c_1_0 FROM t1, t0, t3 WHERE ((CAST(t1.c_1_6 AS BOOLEAN ) ) IS NULL) ORDER BY t1.c_1_1, t1.c_1_3;
-- cardinality: 108

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.1 ASAN
 - mysql> select current_version();
+------------------------------+
| current_version()            |
+------------------------------+
| SQLANCER_01_ASAN 728e940 |
+------------------------------+

**Comment by Youngwb** [comment]
can not reproduction
