### ISSUE TITLE
Query sql result in norec mode

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#3480]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE t0 (c_0_0 DECIMAL(8, 6)  NOT NULL ,c_0_1 FLOAT REPLACE NULL ) AGGREGATE KEY (c_0_0) DISTRIBUTED BY HASH (c_0_0) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DATE NOT NULL ,c_1_1 DECIMAL(31, 11)  NOT NULL ,c_1_2 LARGEINT NULL ,c_1_3 HLL HLL_UNION NOT NULL ,c_1_4 HLL HLL_UNION NULL ,c_1_5 DATE MAX NOT NULL ,c_1_6 BIGINT REPLACE_IF_NOT_NULL NOT NULL ,c_1_7 PERCENTILE PERCENTILE_UNION NOT NULL ,c_1_8 DOUBLE MIN NOT NULL ,c_1_9 VARCHAR(1) MIN NULL ,c_1_10 CHAR(11) REPLACE NULL ,c_1_11 DECIMAL(29, 10)  MAX NOT NULL ,c_1_12 PERCENTILE PERCENTILE_UNION NOT NULL ,c_1_13 DATETIME MAX NULL ,c_1_14 PERCENTILE PERCENTILE_UNION NULL ,c_1_15 DOUBLE SUM NOT NULL ) AGGREGATE KEY (c_1_0,c_1_1,c_1_2) DISTRIBUTED BY HASH (c_1_2,c_1_0) properties("replication_num"="3") ;
CREATE TABLE t2 (c_2_0 DATE NOT NULL ,c_2_1 CHAR(21) NOT NULL ,c_2_2 BOOLEAN NOT NULL ,c_2_3 DATETIME NULL ,c_2_4 DECIMAL(4, 1)  NULL ,c_2_5 BOOLEAN NOT NULL ,c_2_6 CHAR(11) NULL ,c_2_7 DATE NOT NULL ,c_2_8 DOUBLE NOT NULL ) DUPLICATE KEY (c_2_0,c_2_1,c_2_2) DISTRIBUTED BY HASH (c_2_0) properties("replication_num"="3") ;
INSERT INTO t0 VALUES (0.000068, 0.07178466449598508);
DELETE FROM t2 WHERE c_2_0="1969-12-15" AND c_2_2=false AND c_2_1="OWVObWPR";
INSERT INTO t2 VALUES ("1970-01-01", "", false, "1970-01-01 08:00:00", 79.2, false, "UV", "1970-01-01", 0.6278334178606755);
INSERT INTO t1 VALUES ("1970-01-01", 676685732.72728941296, -691177954, hll_hash("lYTfy"), hll_hash("zu94w6pJ"), "1970-01-01", NULL, percentile_hash("-620729970"), 0.867632715053438, "", "RP", 440509150.9499759423, percentile_hash("564352953"), "1970-01-01 08:00:00", percentile_hash("-680945693"), 0.43654711064393836), ("1970-01-01", 494782378.73798649345, 61508606, hll_hash("2"), hll_hash("x"), "1970-01-01", -1973598243, percentile_hash("-307321783"), 0.3569878952736363, NULL, "", 719645062.3374887065, percentile_hash("-1781663991"), "1970-01-01 08:00:00", percentile_hash("1766942123"), 0.4120977374652026);
INSERT INTO t2 VALUES ("1970-01-01", "", true, NULL, 18.3, false, NULL, "1970-01-01", 0.9906628149151309), ("1970-01-01", "", true, "1970-01-01 08:00:00", 47.8, false, "Aq", "1970-01-01", 0.7185212972445313);
INSERT INTO t0 VALUES (0.000027, -1.821270293E9);
INSERT INTO t0 VALUES (0.000005, 0.556139389725361);
INSERT INTO t1 VALUES ("1970-01-01", 614886728.62040617706, 112452042, hll_hash("gKv"), hll_hash(""), "1970-01-01", 1657677615, percentile_hash("-1518758870"), 0.7924095375631915, NULL, "", 242744934.0161926698, percentile_hash("497222208"), NULL, percentile_hash("725152415"), 0.19804390626131207), ("1970-01-01", 107267789.13510835844, 331288100, hll_hash("CtHFTvo"), hll_hash("8Yuk"), "1970-01-01", -996861475, percentile_hash("92147827"), 0.42588821415352573, "", "z", 833837903.7541472867, percentile_hash("1766102489"), "1970-01-01 08:00:00", percentile_hash("-263692018"), 0.09516567233394035);
INSERT INTO t2 VALUES ("1970-01-01", "z68", false, "1970-01-01 08:00:00", 29.0, false, "I", "1970-01-01", 0.9805593914106053), ("1970-01-01", "jdo", false, "1970-01-01 08:00:00", 63.9, false, "fjyv", "1970-01-01", 1.08070389E9);
INSERT INTO t1 VALUES ("1970-01-01", 80201997.65763706670, -1163296542, hll_hash("iY"), hll_hash(""), "1970-01-01", 1044105313, percentile_hash("-416459316"), 0.6816444255651524, "", "f", 840528529.6427888231, percentile_hash("1743941104"), NULL, percentile_hash("-1884990210"), 0.03267267172661059);
INSERT INTO t0 VALUES (0.000009, 0.4776282564619798);
2. mysql> SELECT COUNT(\*) FROM t2, t1, t0 WHERE (NOT ( ( 507977186.73526878660 ) = ( CAST(CASE  WHEN false THEN CASE  WHEN false THEN t1.c_1_2  WHEN true THEN t1.c_1_2 ELSE 1743941104 END  WHEN  ( t0.c_0_0 ) > ( t0.c_0_0 )  THEN ((1334723343)/(1330779537))  WHEN  ( "" ) < ( "A" )  THEN ((677207149)%(-1243365361)) END AS DECIMAL(7, 4) )  ) ));
+----------+
| count(*) |
+----------+
|        0 |
+----------+
3. mysql> SELECT SUM(count) FROM (SELECT CAST((CAST((NOT ( ( 507977186.73526878660 ) = ( CAST(CASE  WHEN false THEN CASE  WHEN false THEN t1.c_1_2  WHEN true THEN t1.c_1_2 ELSE 1743941104 END  WHEN  ( t0.c_0_0 ) > ( t0.c_0_0 )  THEN ((1334723343)/(1330779537))  WHEN  ( "" ) < ( "A" )  THEN ((677207149)%(-1243365361)) END AS DECIMAL(7, 4) )  ) )) AS BOOLEAN) = true) AND (CAST((NOT ( ( 507977186.73526878660 ) = ( CAST(CASE  WHEN false THEN CASE  WHEN false THEN t1.c_1_2  WHEN true THEN t1.c_1_2 ELSE 1743941104 END  WHEN  ( t0.c_0_0 ) > ( t0.c_0_0 )  THEN ((1334723343)/(1330779537))  WHEN  ( "" ) < ( "A" )  THEN ((677207149)%(-1243365361)) END AS DECIMAL(7, 4) )  ) )) AS BOOLEAN) IS NOT NULL) AS INT) as count FROM t2, t1, t0 ) t;
+--------------+
| sum(`count`) |
+--------------+
|          100 |
+--------------+

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.1 ASAN
 - mysql> select current_version();
+------------------------------+
| current_version()            |
+------------------------------+
| SQLANCER_02_ASAN 728e940 |
+------------------------------+

**Comment by satanson** [comment]
explain verbose select cast(((677207149)%(-1243365361)) as decimal(7,4));
```
+----------------------------------+
| Explain String                   |
+----------------------------------+
| PLAN FRAGMENT 0(F00)             |
|   Output Exprs:1: cast           |
|   Input Partition: UNPARTITIONED |
|   RESULT SINK                    |
|                                  |
|   0:UNION                        |
|      constant exprs:             |
|          NULL                    |
|      cardinality: 1              |
+----------------------------------+
9 rows in set (0.00 sec)
```

```
mysql> select ((677207149)%(-1243365361));
+-------------------------------+
| ((677207149) % (-1243365361)) |
+-------------------------------+
|                     677207149 |
+-------------------------------+
```

677207149 exceeds the range (-999.9999, +999.9999), but it can be held in int64.
