### ISSUE TITLE
date_format

### ISSUE THREAD

**Issue by yaoyu73100** [StarRocks/starrocks#34839]
### Steps to reproduce the behavior (Required)
select date_format('2023-10-11 00:00:01.030', '%Y-%m-%d %H:%i:%s.%f');

### Expected behavior (Required)
2023-10-11 00:00:01.030000

### Real behavior (Required)
2023-10-11 00:00:01.000030

### StarRocks version (Required)
2.5.10

**Comment by yaoyu73100** [comment]
CREATE TABLE IF NOT EXISTS `test_order` (
  `id` varchar(150) NOT NULL COMMENT '主键id',
  `reset_period_data` varchar(32) NULL COMMENT "上次重置的日期",
) ENGINE=olap  PRIMARY KEY (`id`) COMMENT '' DISTRIBUTED BY HASH(id) BUCKETS 1 PROPERTIES("enable_persistent_index" = "true");

insert into test_order values('1','2023-10-11 00:00:01.030');
select DATE_FORMAT(reset_period_data, '%Y-%m-%d %H:%i:%s.%f') from test_data_format where id='1';

2023-10-11 00:00:01.030000

**Comment by silly-carbon** [comment]
It seems that this is fixed in the latest version.
