### ISSUE TITLE
Why Starocks colocate join must dependence on colocate group?

### ISSUE THREAD

**Issue by colagy** [StarRocks/starrocks#34830]
## Enhancement
![image](https://github.com/StarRocks/starrocks/assets/37213080/053224c5-382d-452f-8053-b2b451c224b7)
If two tables have the same bucket nums/ bucket keys and same type, they are not the same distribution?
If they have the same distribution, they can join locally.
Why do you necessarily need colocate group?
The query optimizer can do this.

**Comment by kevincai** [comment]
The two tables can have the same buckets and bucket keys and the same type, but they not necessarily having the same distribution.

There are variant cases. Here are a few examples. Let's say tableA and tableB have 3 buckets defined with the same distribution key, there are 3 BE nodes.
* TableA's tablets: A-1, A-2, A-3
* TableB's tablets: B-1, B-2, B-3
* BE nodes: be-1, be-2, be-3

table A's distribution can be: [A-1 -> be-1,  A-2 -> be-2, A-3 -> be-3]
table B's distribution can be: [B-1 -> be-2, B-2 -> be-1, B-3 -> be-3]

not all the combination distribution of tableA and tableB can be called colocation.

**Comment by colagy** [comment]
> The two tables can have the same buckets and bucket keys and the same type, but they not necessarily having the same distribution.
> 
> There are variant cases. Here are a few examples. Let's say tableA and tableB have 3 buckets defined with the same distribution key, there are 3 BE nodes.
> 
> * TableA's tablets: A-1, A-2, A-3
> * TableB's tablets: B-1, B-2, B-3
> * BE nodes: be-1, be-2, be-3
> 
> table A's distribution can be: [A-1 -> be-1, A-2 -> be-2, A-3 -> be-3] table B's distribution can be: [B-1 -> be-2, B-2 -> be-1, B-3 -> be-3]
> 
> not all the combination distribution of tableA and tableB can be called colocation.

Why do the same bucket keys not have the same distribution?  is random?
