### ISSUE TITLE
字符串最大长度太短了：Value length is beyond the capacity.

### ISSUE THREAD

**Issue by mtzbs** [StarRocks/starrocks#34840]
## Enhancement
从mysql导出数据到starrocks，报字段太长；mysql中为longtext类型，既然starrocks宣称可以做数仓，那至少要能涵盖住mysql中的所有数据类型吧，否则就妄称数据仓库了

**Comment by haoranchuixue** [comment]
我们也遇见这个问题了，字符串长度不够用呀。数据进不去都被截断了。
