### ISSUE TITLE
Add log Reminders : PriorityCidrs is not empty and does not contain all hosts

### ISSUE THREAD

**Issue by mklzl** [StarRocks/starrocks#349]
### The source code：

     for (InetAddress addr : hosts) {
            LOG.debug("check ip address: {}", addr);
            if (addr instanceof Inet4Address) {
                if (addr.isLoopbackAddress()) {
                    loopBack = addr;
                } else if (!priorityCidrs.isEmpty()) {
                    if (isInPriorNetwork(addr.getHostAddress())) {
                        localAddr = addr;
                        break;
                    }
                    //We should print some logs to remind users to properly configure Priority_networks
                } else {
                    localAddr = addr;
                    break;
                }
            }
        }

#### But when the user configures priorityCidrs incorrectly, priorityCidrs is not empty and does not contain all hosts. This code will only start FE with the loopback address, and there is no prompt message, thus bringing network communication problems for users to build clusters.I think we should alert the user when priorityCidrs is not empty and does not contain all hosts to reduce the user's subsequent problems.

**Comment by imay** [comment]
I agree with you. Could you please submit a pull request to fix it? @mklzl

**Comment by mklzl** [comment]
ok.



---Original---
From: "Zhao ***@***.***&gt;
Date: Thu, Sep 23, 2021 13:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [StarRocks/starrocks] Add log Reminders : PriorityCidrs is not empty and does not contain all hosts (#349)




 
I agree with you. Could you please submit a pull request to fix it? @mklzl
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
