### ISSUE TITLE
[Feature Request] Parallel Execution for RewriteTreeTask in Optimizer

### ISSUE THREAD

**Issue by dingxin-tech** [StarRocks/starrocks#34910]
## Feature request

**Is your feature request related to a problem? Please describe.**
Yes, the current sequential execution of the RewriteTreeTask in the optimizer impacts the performance of certain external catalog split operations. These split operations take a considerable amount of time to complete, which affects the overall query planning and optimization process.

优化器中RewriteTreeTask的当前顺序执行方式影响了某些外部目录分割操作的性能。这些分割操作需要较长的时间来完成，从而影响整个查询规划和优化过程。

**Describe the solution you'd like**
I would like to propose introducing parallel execution for the RewriteTreeTask in the optimizer. By allowing the rewrite logic to be executed concurrently, we can significantly reduce the execution time for external catalog split operations.

我想提议在优化器中为RewriteTreeTask引入并行执行的功能。通过允许并行执行重写逻辑，我们可以显著减少外部目录分割操作的执行时间。

**Describe alternatives you've considered**
One alternative solution is to perform parallel operations only on the leaf nodes. Since scan operators are typically leaf nodes, performing parallel operations on the leaf nodes can improve query speed without being limited by the sequential execution of the entire query tree.

也可以考虑仅对叶子结点进行并行操作。由于扫描算子通常作为叶子结点，对叶子结点进行并行操作可以提高查询速度，而不会受到整个查询树的顺序执行方式的限制。

**Comment by mofeiatwork** [comment]
In some research projects it's promising to parallelize the optimizer tasks, but in industrial project it's not common.

First, the parallelization would make the optimizer more complicated, and hard to debug.

Second, the bottleneck of accessing the external catalog could be optimized through caching mechanism, it not only reduce the latency but also reduce the cost.
