### ISSUE TITLE
query result inconsistent for execute many times

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#3493]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS n1;
CREATE DATABASE n1;
USE n1;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DECIMAL(12, 6)  NOT NULL ,c_0_1 BOOLEAN NULL ,c_0_2 BOOLEAN NOT NULL ,c_0_3 FLOAT NULL ,c_0_4 DATE NOT NULL ,c_0_5 DECIMAL(35, 2)  NOT NULL ,c_0_6 DATETIME NULL ,c_0_7 BIGINT NULL ,c_0_8 CHAR(11) NOT NULL ,c_0_9 CHAR(1) NOT NULL ,c_0_10 BIGINT NULL ) UNIQUE KEY (c_0_0,c_0_1,c_0_2) DISTRIBUTED BY HASH (c_0_2,c_0_1) properties("replication_num"="3") ;
CREATE TABLE t1 (c_1_0 DECIMAL(30, 20)  NULL ,c_1_1 DATETIME NULL ,c_1_2 VARCHAR(11) NULL ,c_1_3 DECIMAL(7, 2)  NULL ,c_1_4 LARGEINT NULL ,c_1_5 INT NULL ,c_1_6 INT NULL ,c_1_7 VARCHAR(21) NULL ,c_1_8 INT NOT NULL ,c_1_9 BOOLEAN NOT NULL ,c_1_10 LARGEINT NULL ,c_1_11 INT NULL ,c_1_12 BOOLEAN NOT NULL ,c_1_13 FLOAT NOT NULL ,c_1_14 BOOLEAN NULL ,c_1_15 VARCHAR(11) NULL ,c_1_16 FLOAT NOT NULL ) DUPLICATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6,c_1_7,c_1_8) DISTRIBUTED BY HASH (c_1_7) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t2 (c_2_0 DATE NOT NULL ) DUPLICATE KEY (c_2_0) DISTRIBUTED BY HASH (c_2_0) properties("replication_num"="3") ;
INSERT INTO t0 VALUES (0.803809, false, false, 0.27417689955473157, "1970-01-01", 8009616649943253311850730768672.86, "1970-01-01 08:00:00", -750099595, "Vnwt", "", NULL), (0.670284, false, false, NULL, "1970-01-01", 7206940412289025449034334503628.50, "1970-01-01 08:00:00", -1830797122, "WxJGRNz9H", "", 1899867603);
INSERT INTO t1 VALUES (7.964034059E-11, "1970-01-01 08:00:00", "", NULL, 1032918830, NULL, 11, "d9fBqI", 21, false, -299857473, 30, false, 0.8678131612179864, false, "", 0.8881471129271626), (2.380037522E-11, "1970-01-01 08:00:00", "gLnfJ", 192.69, -2025084516, 20, 0, "o0", 22, false, 1959914500, 20, false, 0.3180144579779043, true, "o", 2.92610378E8);
INSERT INTO t1 VALUES (7.318986091E-11, "1970-01-01 08:00:00", "D", 790.57, -101516247, 31, 1, "ODWjaAe", 17, false, 434964342, 0, true, 0.7390258411910271, false, "2YL", 0.9336156424842879), (NULL, "1970-01-01 08:00:00", "", 138.68, -2110655096, 2, 25, "KD", 29, true, NULL, 15, false, 0.14888373636890817, false, "c", 0.4876902178929736), (4.040724176E-11, "1970-01-01 08:00:00", "vE", 696.81, 1872472535, 18, 3, NULL, 24, true, 1743461028, NULL, true, 0.9742096331486547, true, "", 2.019759016E9);
INSERT INTO t2 VALUES ("1970-01-01"), ("1970-01-01");
INSERT INTO t1 VALUES (5.745380262E-11, "1970-01-01 08:00:00", "K", NULL, -496414745, 28, 7, "Z8S", 16, true, NULL, 18, false, 0.5043961020203955, false, "MdC", 0.20749390697974368), (6.48113305E-12, "1970-01-01 08:00:00", "LW", 871.75, 2024847513, 20, 26, "8m", 5, true, -1405730615, 20, false, 0.565695483376128, NULL, "Logol", -6.04870899E8), (6.500346440E-11, "1970-01-01 08:00:00", "3Q", NULL, NULL, NULL, 25, "u", 31, true, -262393707, 31, false, 0.5959079173711046, false, "ya", 0.6394095013686204);
DELETE FROM t1 WHERE c_1_6=-1320422083 AND c_1_2=NULL AND c_1_5=-1646547655 AND c_1_0=7.389719789E-11;
TRUNCATE TABLE t0;
INSERT INTO t0 VALUES (0.192800, false, true, 0.6217272743897296, "1970-01-01", 7162430881290515276253592878208.38, "1970-01-01 08:00:00", 189598080, "Xr", "", -536945625);
INSERT INTO t2 VALUES ("1970-01-01"), ("1970-01-01");
INSERT INTO t2 VALUES ("1970-01-01"), ("1970-01-01");
INSERT INTO t1 VALUES (NULL, "1970-01-01 08:00:00", "RmJYmy9nL", 91.42, 1492631502, NULL, 23, "iE", 3, false, -1933790374, 11, false, 0.7028182814848521, false, "jiv", 0.44201972658482613), (4.047842957E-11, "1970-01-01 08:00:00", "", 576.50, -804269779, 14, 30, NULL, 24, false, 983210669, 13, false, 0.03875178366366605, false, "sj3", -8.20608471E8);
INSERT INTO t1 VALUES (3.805953455E-11, "1970-01-01 08:00:00", "", 441.24, 1092225992, 0, 8, "l", 7, false, -1907095151, 11, true, 0.5944533570808495, NULL, "mT", 0.1637738198846379);
2. mysql> SELECT SUM(count) FROM (SELECT CAST((CAST(((((((("")||("")))||("")))||("i")))  BETWEEN ((("")||(""))) AND (AES_ENCRYPT((((("k")||("")))||((("")||("")))), CAST(t1.c_1_0 AS STRING ) ) )  AS BOOLEAN) = true) AND (CAST(((((((("")||("")))||("")))||("i")))  BETWEEN ((("")||(""))) AND (AES_ENCRYPT((((("k")||("")))||((("")||("")))), CAST(t1.c_1_0 AS STRING ) ) )  AS BOOLEAN) IS NOT NULL) AS INT) as count FROM t1, t2, t0 ) t;
+--------------+
| sum(`count`) |
+--------------+
|           48 |
+--------------+
1 row in set (0.03 sec)

mysql> SELECT SUM(count) FROM (SELECT CAST((CAST(((((((("")||("")))||("")))||("i")))  BETWEEN ((("")||(""))) AND (AES_ENCRYPT((((("k")||("")))||((("")||("")))), CAST(t1.c_1_0 AS
STRING ) ) )  AS BOOLEAN) = true) AND (CAST(((((((("")||("")))||("")))||("i")))  BETWEEN ((("")||(""))) AND (AES_ENCRYPT((((("k")||("")))||((("")||("")))), CAST(t1.c_1_0 AS STRING ) ) )  AS BOOLEAN) IS NOT NULL) AS INT) as count FROM t1, t2, t0 ) t;
+--------------+
| sum(`count`) |
+--------------+
|           54 |
+--------------+

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.1 Release
 - mysql> select current_version();
+---------------------------------+
| current_version()               |
+---------------------------------+
| SQLANCER_01_RELEASE 24e26f4 |
+---------------------------------+

**Comment by Youngwb** [comment]
![image](https://user-images.githubusercontent.com/9495145/155091315-2b7ee45d-3452-4f8d-bc7a-e59a7d9e07eb.png)
sql :
```
SELECT 
      CAST(
        CAST(
          "i" <= (
            AES_ENCRYPT(
              "k", 
              CAST(t1.c_1_0 AS STRING)
            )
          ) AS BOOLEAN
        ) = true 
        AS INT
      ) as count, t1.c_1_0 
    FROM 
      t1
    order by t1.c_1_0
```

**Comment by satanson** [comment]
```
SELECT Aes_encrypt("k", Cast(t1.c_1_0 AS STRING)) AS count1,
       Cast(t1.c_1_0 AS STRING)                   AS count2,
       Cast(Cast("i" <= ( Aes_encrypt("k", Cast(t1.c_1_0 AS STRING)) ) AS
                 BOOLEAN) =
            true AS
            INT)                                  AS count,
       t1.c_1_0
FROM   t1
ORDER  BY t1.c_1_0;
```
output

```
+------------------+------------------------+-------+------------------------+
| count1           | count2                 | count | c_1_0                  |
+------------------+------------------------+-------+------------------------+
| x���]_�ƅ�3�        | NULL                   |     0 |                   NULL |
| �y��Ў6�~�KHo�        | NULL                   |     1 |                   NULL |
| t����_�/����u�           | 0.00000000000648113305 |     1 | 0.00000000000648113305 |
| �Üe-���S
�e�         | 0.00000000002380037522 |     1 | 0.00000000002380037522 |
| �[0�;� ���Wٗ�           | 0.00000000003805953455 |     1 | 0.00000000003805953455 |
| `Ф	��&�S���5
                 �         | 0.00000000004040724176 |     0 | 0.00000000004040724176 |
Nƫ�        | 0.00000000004047842957 |     1 | 0.00000000004047842957 |
| �Iɯ^v�6��3�Ӟ	�         | 0.00000000005745380262 |     1 | 0.00000000005745380262 |
| �����|�bM�9N_1         | 0.00000000006500346440 |     1 | 0.00000000006500346440 |
| b
   ���Z)�OO��"l�7        | 0.00000000007318986091 |     0 | 0.00000000007318986091 |
| ��r��(�P��{�&K�          | 0.00000000007964034059 |     1 | 0.00000000007964034059 |
+------------------+------------------------+-------+------------------------+
```
Conclusion: 
Aes_encrypt apply NULL elements of NullableColumn generates a NOT NULL result

**Comment by satanson** [comment]
```
CREATE TABLE IF NOT EXISTS t3 (c_0_0 INT NULL ,c_0_1 VARCHAR(255)) UNIQUE KEY (c_0_0) DISTRIBUTED BY HASH (c_0_0) properties("replication_num"="1") ;

insert into t3 values (1, NULL),(2, "abc"), (3, NULL);

select AES_ENCRYPT('k', c_0_1), c_0_1 from t3;

+---------------------------+-------+
| aes_encrypt('k', `c_0_1`) | c_0_1 |
+---------------------------+-------+
| X����<���:�����                     | abc   |
| x���]_�ƅ�3�                 | NULL  |
| x���]_�ƅ�3�                 | NULL  |
+---------------------------+-------+
```
