### ISSUE TITLE
Support cache statistics for iceberg table

### ISSUE THREAD

**Issue by caneGuy** [StarRocks/starrocks#3497]
## Enhancement
related with  #1030 
since we get statistics for iceberg by metafiles on dfs each time. i think we should cache statistics in memory for performance consideration

**Comment by caneGuy** [comment]
cc @DorianZheng @dirtysalt

**Comment by DorianZheng** [comment]
I remember some system use BE to load and parse manifest concurrently

**Comment by caneGuy** [comment]
you mean dremio? @DorianZheng i will submit a documentation for this later and let's discuss about this together
