### ISSUE TITLE
When importing Flink SQL into Starlocks, if the data format is JSON, the default value cannot be triggered, while if the data format is CSV, the default value can be triggered

### ISSUE THREAD

**Issue by YangQian-99** [StarRocks/starrocks#34983]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `send_coupon_info` (
  `dt` date NOT NULL COMMENT "分区时间，取自drawTime字段",
  `primary_id` varchar(50) NOT NULL COMMENT "主键id,上游表名和主键id拼接而成",
  `insert_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "插入数据库时间"
) ENGINE=OLAP 
PRIMARY KEY(`dt`, `primary_id`)
COMMENT "领券记录表"
PARTITION BY RANGE(`dt`)
(
PARTITION p20231112 VALUES [("2023-11-12"), ("2023-11-13")),
PARTITION p20231113 VALUES [("2023-11-13"), ("2023-11-14")),
PARTITION p20231114 VALUES [("2023-11-14"), ("2023-11-15")),
PARTITION p20231115 VALUES [("2023-11-15"), ("2023-11-16")),
PARTITION p20231116 VALUES [("2023-11-16"), ("2023-11-17")))
DISTRIBUTED BY HASH(`primary_id`) BUCKETS 1 
PROPERTIES (
"replication_num" = "3",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-1",
"dynamic_partition.end" = "2",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "1",
"dynamic_partition.history_partition_num" = "0",
"dynamic_partition.replication_num" = "3",
"in_memory" = "false",
"storage_format" = "V2",
"enable_persistent_index" = "true",
"compression" = "LZ4"
);
2. Flink SQL DDL and insert statements:
CREATE TABLE send_coupon_info (
dt              date,
primary_id      STRING,
     PRIMARY KEY(dt,primary_id) NOT ENFORCED
     ) WITH (
    'connector' = 'starrocks',
    'jdbc-url' = 'jdbc:mysql://',
    'load-url' = '',
    'database-name' = 'ods',
    'table-name' = 'send_coupon_info',
    'username' = 'root',
    'password' = '',
    'sink.semantic'='at-least-once',
    'sink.label-prefix'='send_coupon_info',
    'sink.properties.format'='json'
    );
insert into send_coupon_info
 	select 
TO_DATE(DATE_FORMAT(create_time,'yyyy-MM-dd'),'yyyy-MM-dd'),
CONCAT(table_name,'_',cast(id  as string)),        
 	 from send_coupon_info_source ;
3. select current_version()
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| 2.5.13 a3b58a0    |
+-------------------+
1 row in set (0.01 sec)
4. View insert_ All values in the time column are null, and it was found that the default current was not triggered_ TIMESTAMP value
5. Modify the DDL 'sink. properties. format'='json 'in Flink SQL to' sink. properties. format '='CSV', which triggers the default current_ TIMESTAMP value, which can obtain the normal storage time
![image](https://github.com/StarRocks/starrocks/assets/80536089/80db39d4-ba6c-4c44-9fdc-30c82aec9c49)

**Comment by jlj-incom** [comment]
I experience the same thing.
