### ISSUE TITLE
sql result error bug

### ISSUE THREAD

**Issue by Seaven** [StarRocks/starrocks#3499]
2.DROP DATABASE IF EXISTS w0;
CREATE DATABASE w0;
USE w0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 VARCHAR(21) NOT NULL ,c_0_1 DOUBLE NULL ,c_0_2 BOOLEAN NOT NULL ,c_0_3 DECIMAL(32, 9) NOT NULL ,c_0_4 DECIMAL(12, 8) NULL ,c_0_5 DATETIME NULL ,c_0_6 FLOAT NOT NULL ,c_0_7 DOUBLE NOT NULL ,c_0_8 BOOLEAN NULL ) UNIQUE KEY (c_0_0) DISTRIBUTED BY HASH (c_0_0) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 TINYINT NOT NULL ,c_1_1 VARCHAR(1) NULL ,c_1_2 INT NOT NULL ,c_1_3 DOUBLE NOT NULL ,c_1_4 FLOAT NOT NULL ,c_1_5 LARGEINT NOT NULL ) UNIQUE KEY (c_1_0,c_1_1) DISTRIBUTED BY HASH (c_1_0) properties("replication_num"="3") ;
CREATE TABLE t2 (c_2_0 BOOLEAN NOT NULL ,c_2_1 DATETIME NOT NULL ,c_2_2 CHAR(1) NOT NULL ,c_2_3 BOOLEAN NOT NULL ,c_2_4 CHAR(11) NOT NULL ,c_2_5 TINYINT NULL ,c_2_6 BOOLEAN NULL ,c_2_7 BOOLEAN NOT NULL ,c_2_8 LARGEINT NULL ,c_2_9 TINYINT NOT NULL ,c_2_10 DECIMAL(15, 5) NULL ,c_2_11 SMALLINT NOT NULL ,c_2_12 BOOLEAN NOT NULL ,c_2_13 DECIMAL(25, 4) NULL ) UNIQUE KEY (c_2_0,c_2_1,c_2_2,c_2_3,c_2_4,c_2_5,c_2_6,c_2_7,c_2_8,c_2_9,c_2_10) DISTRIBUTED BY HASH (c_2_6,c_2_10,c_2_3,c_2_2,c_2_7) properties("replication_num"="3") ;
CREATE TABLE t3 (c_3_0 SMALLINT NOT NULL ,c_3_1 VARCHAR(1) NULL ,c_3_2 BOOLEAN NULL ,c_3_3 DECIMAL(32, 18) NULL ,c_3_4 DECIMAL(12, 5) NULL ,c_3_5 TINYINT NULL ,c_3_6 BOOLEAN NOT NULL ,c_3_7 TINYINT NOT NULL ,c_3_8 BOOLEAN NOT NULL ,c_3_9 DOUBLE NULL ,c_3_10 VARCHAR(1) NULL ,c_3_11 BOOLEAN NULL ,c_3_12 DECIMAL(16, 8) NOT NULL ,c_3_13 BOOLEAN NULL ) DUPLICATE KEY (c_3_0,c_3_1,c_3_2,c_3_3) DISTRIBUTED BY HASH (c_3_0) properties("replication_num"="3") ;
INSERT INTO t3 VALUES (4, "", false, 0.000023061416080895, 28.72426, 5, false, 4, false, NULL, "", true, 0.73961274, false);
INSERT INTO t2 VALUES (false, "1970-01-01 08:00:00", "", true, "", 1, true, true, 1753969698, 0, 45836.29443, 14, true, 50167529558314351.1295), (false, "1970-01-01 08:00:00", "", true, "", 1, true, true, 199714952, 3, 9246.62293, 1, false, 96809467892242621.5775), (true, "1970-01-01 08:00:00", "", false, "", 2, true, false, -338349533, 7, 64765.33221, 7, false, 19132730821758004.0435);
INSERT INTO t2 VALUES (true, "1970-01-01 08:00:00", "", true, "tO9", 1, false, true, -714611643, 7, 80904.63697, 12, false, 54355680806858785.8991), (true, "1970-01-01 08:00:00", "", true, "rp2dy4", NULL, true, true, -848772858, 0, 54015.43008, 13, true, 3894628410175284.0399);
INSERT INTO t1 VALUES (7, NULL, 24, 0.8191708955464794, 0.8989978650413526, 562189773), (0, NULL, 20, 0.9727841641087446, 0.12761559957813595, -1573610742);
DELETE FROM t2 WHERE c_2_1="1970-01-15 23:27:30" AND c_2_4="mX" AND c_2_5=-1232348819 AND c_2_7=true;
DELETE FROM t1 WHERE c_1_0=466312696;
INSERT INTO t3 VALUES (7, "", true, NULL, 72.19389, 4, true, 0, false, 0.8272769092604589, "", true, 0.29136084, false), (11, "", true, 0.000052912987397476, 53.71636, 1, true, 7, true, 0.6868180367507648, "", NULL, 0.35844747, true), (12, "", false, 0.000097320137212866, 54.45029, 1, false, 1, false, 0.5507183647934979, "", NULL, 0.88593358, true);
INSERT INTO t3 VALUES (14, "", false, 0.000030782769653024, 37.95748, 1, true, 7, true, 0.9867374826700028, "", true, 0.01755017, false), (0, "", true, 0.000079301984179047, 67.74437, 2, false, 1, true, 0.1544376910493338, "", true, 0.73550185, true);
INSERT INTO t3 VALUES (11, "", true, NULL, 65.54660, 5, false, 2, true, 0.9047564052301408, "", false, 0.41619710, true), (9, "", true, 0.000055558023489245, 7.62866, 4, true, 1, true, 0.13796432061325925, "", true, 0.24058014, false);
INSERT INTO t0 VALUES ("", 0.3358036990018052, true, 39192217429474.858775641, 0.00007465, "1970-01-01 08:00:00", 0.6690806834033431, 1.07535674E8, false);
-- SELECT ((1893798492)%(1021349691)) FROM t1 LEFT ANTI JOIN t2 ON t1.c_1_0 = t2.c_2_13 AND t1.c_1_0 < t2.c_2_13;
-- cardinality: 2
-- SELECT ((1893798492)%(1021349691)) FROM t1 LEFT ANTI JOIN t2 ON t1.c_1_0 = t2.c_2_13 AND t1.c_1_0 < t2.c_2_13 WHERE ( t1.c_1_4 ) >= ( TRUNCATE(TRUNCATE(0.2970198812468864, -1113965038) , 1146662479) ) UNION ALL SELECT ((1893798492)%(1021349691)) FROM t1 LEFT ANTI JOIN t2 ON t1.c_1_0 = t2.c_2_13 AND t1.c_1_0 < t2.c_2_13 WHERE (NOT ( ( t1.c_1_4 ) >= ( TRUNCATE(TRUNCATE(0.2970198812468864, -1113965038) , 1146662479) ) )) UNION ALL SELECT ((1893798492)%(1021349691)) FROM t1 LEFT ANTI JOIN t2 ON t1.c_1_0 = t2.c_2_13 AND t1.c_1_0 < t2.c_2_13 WHERE (( ( t1.c_1_4 ) >= ( TRUNCATE(TRUNCATE(0.2970198812468864, -1113965038) , 1146662479) ) ) IS NULL);
-- cardinality: 0

**Comment by Seaven** [comment]
the reason:
```
mysql> select TRUNCATE(0, 1146662479) ;
+-------------------------+
| truncate(0, 1146662479) |
+-------------------------+
|                     nan |
+-------------------------+
1 row in set (0.01 sec)
```

**Comment by Pslydhh** [comment]
This is fixed by https://github.com/StarRocks/starrocks/pull/3498
