### ISSUE TITLE
Changing fe.conf and be.conf should trigger pod restart when using the Kubernetes Operator

### ISSUE THREAD

**Issue by didip** [StarRocks/starrocks#35014]
## Feature request

**Is your feature request related to a problem? Please describe.**

Currently, the fe.conf and be.conf is located inside 2 ConfigMap.

When we changed the values, pods are not being restarted gracefully. We had to manually perform rolling restart to pick up the changes.

It would be amazing if the operator performs restart correctly when config file is changed.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kevincai** [comment]
@yandongxiao 

@didip I suppose you are using operator to deploy the cluster using CR instead of helm chart, in helm chart, the fe.conf/be.conf configmaps are managed by the chart and will change the annotation whenever the content is changed, and hence triggers the rolling restart.
