### ISSUE TITLE
Kubernetes Operator should have a convenient shell script hook

### ISSUE THREAD

**Issue by didip** [StarRocks/starrocks#35013]
## Feature request

**Is your feature request related to a problem? Please describe.**

After a cluster is setup using the operator, I want to setup a number of GLOBAL variables.

If there is a convenient shell script hook to do that, that would be great.

This hook can be used for many other things, for example: configuring LDAP.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kevincai** [comment]
@yandongxiao
