### ISSUE TITLE
Hope to support cloumn comment in materialized views

### ISSUE THREAD

**Issue by wc99** [StarRocks/starrocks#35051]
## Feature request

We use materialized views in OLAP scenarios, there are no support column comment that affect users' ability to view table data. Hope to support column comment in materialized view

**Comment by mofeiatwork** [comment]
Actually you could write the column comment in this syntax:
```sql
CREATE MATERIALIZED VIEW `mv1` 
  (`c_region` COMMENT "a", 
   `s1` COMMENT "b", 
   `s2`)
DISTRIBUTED BY RANDOM
....
```

**Comment by wc99** [comment]
think u ，the method is effective and can be use
