### ISSUE TITLE
BE crash in ColumnDecoder

### ISSUE THREAD

**Issue by TheheiWorld** [StarRocks/starrocks#3510]
I0218 19:10:47.043725 26715 column_decoder.cpp:60] Internal error: not found slice: in global dict will force the use of the global dictionary encoding

**Comment by stdpain** [comment]
starrocks version ? 
2.0.0-GA ?

**Comment by stdpain** [comment]
you could set cbo_enable_low_cardinality_optimize=false to avoid crash.
this is a known issue https://github.com/StarRocks/starrocks/issues/3082
Fixed By https://github.com/StarRocks/starrocks/pull/3083

**Comment by jaogoy** [comment]
This week, we will publish version 2.0.2 . 
You can reopen this issue if you still meet this problem after you upgrade to 2.0.2.
