### ISSUE TITLE
murmur_hash3_64

### ISSUE THREAD

**Issue by Rucling** [StarRocks/starrocks#35198]
## Enhancement
建议在3.2版本新增murmur_hash3_64方法，因为在使用时发现murmur_hash3_32方法把两个不同的字符串加密成同一个密文

**Comment by imay** [comment]
you can try [xx_hash3_64](https://docs.starrocks.io/docs/3.2/sql-reference/sql-functions/hash-functions/xx_hash3_64/) in version 3.2
