### ISSUE TITLE
compiled results does not contain broker 

### ISSUE THREAD

**Issue by cloverzyy** [StarRocks/starrocks#35284]
Hi, there are two questions hoping to get help.

Q1: After compiling with the command "cd /root/starrocks && ./build.sh", the output does not contain the package: apache_hdfs_broker. Should I compile it manually?

Q2: I ran the  command in branch-3.2 with starrocks/dev-env-centos7:3.2-latest: "sh fs_brokers/apache_hdfs_broker/build.sh"
An error message is displayed:
[ERROR] Failed to execute goal on project starrocks-apache-hdfs-broker: Could not resolve dependencies for project com:starrocks-apache-hdfs-broker:jar:3.4.0: Could not transfer artifact log4j:log4j:jar:1.2.17-cloudera6 from/to cloudera (https://repository.cloudera.com/artifactory/cloudera-repos/): Transfer failed for https://repository.cloudera.com/artifactory/cloudera-repos/log4j/log4j/1.2.17-cloudera6/log4j-1.2.17-cloudera6.jar: Unsupported or unrecognized SSL message -> [Help 1]

**Comment by kevincai** [comment]
A1. the `build.sh` script doesn't contain the build of `apache_hdfs_broker`. You have to `cd fs_brokers/apache_hdfs_broker/  && ./build.sh`, check https://github.com/StarRocks/starrocks/blob/main/docker/dockerfiles/artifacts/artifact.Dockerfile for how we produce the artifacts docker image.
