### ISSUE TITLE
Support unnamed struct

### ISSUE THREAD

**Issue by colagy** [StarRocks/starrocks#35328]
## Enhancement
![image](https://github.com/StarRocks/starrocks/assets/37213080/60387c07-d1f3-4d9c-8c59-e9651761827f)

It is already supported in dremio, the struct is convert from json string without named.
![image](https://github.com/StarRocks/starrocks/assets/37213080/1c627fae-028e-4c1b-8ec4-37b9f3d44a3c)

**Comment by LiShuMing** [comment]
Good Idea. can you use [`json_parse`](https://docs.starrocks.io/docs/sql-reference/sql-functions/json-functions/json-constructor-functions/parse_json/) to bypass?

**Comment by colagy** [comment]
There are something difference between json and struct.
1. ItemOperator , json_field ->'$.a.b.c'  to  struct_field.a.b.c 
2. encoding, json without encoding
3. We use struct type in dremio , so we can not use json type in starrocks sometimes.

**Comment by jaogoy** [comment]
What you need is `SELECT cast(parse_json('{"a":123}') as Struct<a int>) as c2;`.
And SR doesn't support a function converting from a json to a struct.
