### ISSUE TITLE
Support unnest json array directly

### ISSUE THREAD

**Issue by colagy** [StarRocks/starrocks#35378]
## Enhancement
![image](https://github.com/StarRocks/starrocks/assets/37213080/860ee361-4f58-4784-ac54-43d26126c968)

**Comment by LiShuMing** [comment]
Do other database systems support this syntax, can you give an example?

**Comment by colagy** [comment]
Such like jsonb_array_elements in postgreSQL can unnest jsonArray as jsonb type directly.
```sql
select 
    ...
    from t1,
    jsonb_array_elements(c1) 
```

**Comment by atifiu** [comment]
Is there any workaround available, I want to unnest json data and lateral join it.
