### ISSUE TITLE
BE crashes frequently

### ISSUE THREAD

**Issue by sridhard** [StarRocks/starrocks#35823]
### Steps to reproduce the behavior (Required)
BE crashes randomly every 3-4 days once. We are using shared data mode:
Below is the crash:

*** Aborted at 1700834160 (unix time) try "date -d @1700834160" if you are using GNU date ***
PC: @          0x6187e3a bthread_mutex_unlock
*** SIGSEGV (@0x6) received by PID 1413095 (TID 0x7f6598fee640) from PID 6; stack trace: ***
    @          0x6033302 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f668cdf69f6 PosixSignals::chained_handler()
    @     0x7f668cdf745e JVM_handle_linux_signal
    @     0x7f668bc42520 (unknown)
    @          0x6187e3a bthread_mutex_unlock
    @          0x4b6336b _ZNSt17_Function_handlerIFvvEZN9starrocks15LakeServiceImpl16get_tablet_statsEPN6google8protobuf13RpcControllerEPKNS1_4lake17TabletStatRequestEPNS7_18TabletStatResponseEPNS4_7ClosureEEUlvE_E9_M_invokeERKSt9_Any_data
    @          0x4c4df02 starrocks::ThreadPool::dispatch_thread()
    @          0x4c489fa starrocks::Thread::supervise_thread()
    @     0x7f668bc94ac3 (unknown)
    @     0x7f668bd26a40 (unknown)
    @                0x0 (unknown)

### Expected behavior (Required)
BE should be stable and should not crash

### Real behavior (Required)
BE is very unstable. crashing frequently

### StarRocks version (Required)
3.1 (Latest)

**Comment by kevincai** [comment]
this crash is fixed, please upgrade to at least 3.1.4
