### ISSUE TITLE
Doc Enhancement for Vector search feature.

### ISSUE THREAD

**Issue by mozhou-tech** [StarRocks/starrocks#35844]
Missing vector search related documents, hoping to provide relevant usage instructions, technical specifications, such as compatibility with storage and computation separation, performance testing, and supported approximate algorithms.

I found some usage in following URL:
https://python.langchain.com/docs/integrations/vectorstores/starrocks

**Comment by imay** [comment]
https://docs.starrocks.io/docs/sql-reference/sql-functions/math-functions/cos_similarity/
you can use this function
