### ISSUE TITLE
[enhancement] datetime related function that need to support micro and milli seconds.

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#35859]
## Enhancement
In SR, we support years_diff, months_diff, weeks_diff, hours_diff, seconds_diff function. and also we support micro and millisecond. however those functions do not support micro and millisecond input that cause wrong result. so it's better to fix this. 

- [ ]  years_diff
- [ ] months_diff
- [ ] weeks_diff
- [ ] hours_diff
- [ ] seconds_diff

**Comment by xuzifu666** [comment]
cc ~@wangsimo0
