### ISSUE TITLE
unknown error when group by has couldn't push down predicate 

### ISSUE THREAD

**Issue by stdpain** [StarRocks/starrocks#3597]
### Steps to reproduce the behavior (Required)
Table supplier was SSB DataSet
```
select sum(S_NATIONKEY) a, sum(S_ACCTBAL) as b, S_ADDRESS as c from supplier group by S_ADDRESS 
having a < b*1.2 or c not like '%open%'"
```

### Expected behavior (Required)
success

### Real behavior (Required)
unknown error

### StarRocks version (Required)
 - 2.0.0-GA 2.0.1

**Comment by jaogoy** [comment]
Reopen it for other test only.
