### ISSUE TITLE
编译的时候在hub.docker.io能看到dev-env-centos7，但是无法拉取编译环境，报找不到呢

### ISSUE THREAD

**Issue by samfeng2003** [StarRocks/starrocks#36034]
why pull fail? 为什么会拉取失败呢？报找不到。
[root@99 ~]# docker pull starrocks/dev-env-centos7:latest
Trying to pull repository docker.io/starrocks/dev-env-centos7 ...
latest: Pulling from docker.io/starrocks/dev-env-centos7
manifest for docker.io/starrocks/dev-env-centos7:latest not found

please help.

**Comment by kevincai** [comment]
run `docker system info`, check if there is any mirror image configured. most of the mirror images are not working or out of sync with hub.docker.io.
