### ISSUE TITLE
Duplicate Audit Logs

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks#36112]
### Steps to reproduce the behavior (Required)
for the same query ID we always have three logs in the fe audit log.
The the first log , it contains bigQueryLog* attributes.
the 2nd and 3rd are identical
[extract-2024-01-22T16_55_17.106Z.csv](https://github.com/StarRocks/starrocks/files/14013143/extract-2024-01-22T16_55_17.106Z.csv)

### Expected behavior (Required)
One one log for a query

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by liuyehcf** [comment]
I don't see the problem, can you provide the audit log?

**Comment by dengliu** [comment]
[extract-2024-01-22T16_55_17.106Z.csv](https://github.com/StarRocks/starrocks/files/14013147/extract-2024-01-22T16_55_17.106Z.csv)
Here are the audit logs.
