### ISSUE TITLE
Some aggregation functions do not support named struct type parameters

### ISSUE THREAD

**Issue by NJCrazyRen** [StarRocks/starrocks#36141]
### Steps to reproduce the behavior (Required)
select
	max_by(tt.ns,tt.age)
from (
	select
		t.age,
		named_struct('id', t.id, 'name', t.name) ns
	from (
		select 1 as id, '张三' as name, 20 as age	
		union
		select 2 as id, '李四' as name, 18 as age
	) t
) tt

### Expected behavior (Required)
return the result: {'id': 1, 'name':'张三'}

### Real behavior (Required)
SQL 错误 [1064] [42000]: Getting analyzing error from line 2, column 1 to line 2, column 20. Detail message: No matching function with signature: max_by(struct<id tinyint(4), name varchar>, tinyint(4)).

### StarRocks version (Required)
3.1.0

### additional
Other aggregate functions (eg min_by, first_value) do not support named struct type parameters, too

**Comment by LiShuMing** [comment]
@Seaven

**Comment by yue6121** [comment]
Has this issue been resolved?

**Comment by Seaven** [comment]
most aggregate function doesn't support struct type now
