### ISSUE TITLE
mode function result is wrong

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#3616]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS n0;
CREATE DATABASE n0;
USE n0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 CHAR(11) NULL ,c_0_1 VARCHAR(21) NOT NULL ,c_0_2 FLOAT NOT NULL ,c_0_3 VARCHAR(21) NOT NULL ,c_0_4 BOOLEAN NULL ,c_0_5 BOOLEAN NULL ,c_0_6 BOOLEAN NULL ,c_0_7 CHAR(41) NOT NULL ,c_0_8 DATETIME NOT NULL ,c_0_9 DOUBLE NULL ,c_0_10 SMALLINT NOT NULL ,c_0_11 BOOLEAN NOT NULL ,c_0_12 DATE NOT NULL ,c_0_13 DATETIME NULL ,c_0_14 FLOAT NOT NULL ,c_0_15 BOOLEAN NOT NULL ,c_0_16 BIGINT NOT NULL ,c_0_17 DECIMAL(16, 15)  NULL ,c_0_18 DECIMAL(29, 0)  NOT NULL ) UNIQUE KEY (c_0_0) DISTRIBUTED BY HASH (c_0_0) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DECIMAL(8, 7)  NULL ,c_1_1 BIGINT NOT NULL ,c_1_2 LARGEINT NULL ,c_1_3 DATE NULL ,c_1_4 DATETIME NULL ,c_1_5 TINYINT NOT NULL ,c_1_6 DOUBLE NOT NULL ) UNIQUE KEY (c_1_0) DISTRIBUTED BY HASH (c_1_0) properties("replication_num"="3") ;
CREATE TABLE t2 (c_2_0 DATE NOT NULL ,c_2_1 FLOAT REPLACE NULL ) AGGREGATE KEY (c_2_0) DISTRIBUTED BY HASH (c_2_0) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t3 (c_3_0 DECIMAL(27, 3)  NOT NULL ,c_3_1 BOOLEAN NOT NULL ,c_3_2 BOOLEAN NULL ,c_3_3 INT NULL ,c_3_4 DATE NOT NULL ,c_3_5 BOOLEAN NULL ,c_3_6 BOOLEAN NULL ,c_3_7 BITMAP BITMAP_UNION NULL ,c_3_8 DOUBLE MAX NOT NULL ,c_3_9 FLOAT MAX NULL ,c_3_10 DECIMAL(20, 6)  MAX NULL ,c_3_11 PERCENTILE PERCENTILE_UNION NOT NULL ,c_3_12 HLL HLL_UNION NULL ,c_3_13 HLL HLL_UNION NULL ,c_3_14 DECIMAL(20, 14)  MAX NULL ,c_3_15 DOUBLE REPLACE NULL ) AGGREGATE KEY (c_3_0,c_3_1,c_3_2,c_3_3,c_3_4,c_3_5,c_3_6) DISTRIBUTED BY HASH (c_3_0,c_3_6,c_3_4) properties("replication_num"="3") ;
CREATE TABLE t4 (c_4_0 VARCHAR(11) NULL ,c_4_1 DECIMAL(8, 2)  NOT NULL ,c_4_2 DATE NULL ,c_4_3 BOOLEAN NOT NULL ,c_4_4 INT NOT NULL ,c_4_5 BOOLEAN NOT NULL ,c_4_6 SMALLINT NOT NULL ,c_4_7 VARCHAR(21) NOT NULL ,c_4_8 BOOLEAN NOT NULL ,c_4_9 DATETIME NOT NULL ,c_4_10 FLOAT NOT NULL ,c_4_11 DECIMAL(32, 0)  NOT NULL ,c_4_12 DOUBLE NOT NULL ,c_4_13 BOOLEAN NULL ) DUPLICATE KEY (c_4_0,c_4_1,c_4_2,c_4_3) DISTRIBUTED BY HASH (c_4_2,c_4_0,c_4_3) properties("replication_num"="3") ;
INSERT INTO t2 VALUES ("1970-01-01", NULL), ("1970-01-01", 0.43996468357147855);
INSERT INTO t0 VALUES (NULL, "DX", 0.25279759434326077, "3j", false, true, false, "wT", "1970-01-01 08:00:00", 0.25279759434326077, 2, true, "1970-01-01", "1970-01-01 08:00:00", 0.25279759434326077, true, -1739287123, 1E-15, 98269013878974578890361790683), ("", "V42Yo", -1.739287123E9, "nO", true, true, true, "", "1970-01-01 08:00:00", 0.3295698231283156, 4, true, "1970-01-01", "1970-01-01 08:00:00", 0.17915554825842595, false, 404504292, 3E-15, 16787585571795228611358119508);
DELETE FROM t1 WHERE c_1_0=8E-7;
INSERT INTO t2 VALUES ("1970-01-01", 0.3806009571174438), ("1970-01-01", 0.059649261106069607), ("1970-01-01", 0.26809908052941034);
INSERT INTO t4 VALUES ("", 7900.49, "1970-01-01", false, 28, true, 1, "Pm", false, "1970-01-01 08:00:00", 0.25279759434326077, 89298997656591722024321404860280, 0.12391582911651922, true);
INSERT INTO t4 VALUES ("hN", 5237.17, "1970-01-01", false, 8, true, 4, "", false, "1970-01-01 08:00:00", -1.739287123E9, 25467150356329958390199455275926, 0.5407765797188717, true);
INSERT INTO t4 VALUES (NULL, 1712.20, "1970-01-01", false, 30, true, 3, "", false, "1970-01-01 08:00:00", 0.773159899888732, 10682171513326478365607761172562, 0.3679519811781712, false), ("ROs5h", 4533.00, "1970-01-01", false, 0, true, 6, "tc", true, "1970-01-01 08:00:00", 0.5407765797188717, 67503389786226884295713932426785, 0.152903747825339, false), (NULL, 8485.31, "1970-01-01", true, 13, false, 8, "", true, "1970-01-01 08:00:00", 0.8092700491486843, 4633155721263235004670840910812, 0.44604466440988666, true), ("", 4072.18, "1970-01-01", false, 27, true, 5, "xoZJntI", true, "1970-01-01 08:00:00", 0.19204846266754583, 77323937346481975478984506655599, 0.3806009571174438, NULL);
INSERT INTO t0 VALUES ("IiPNMd1", "", 0.3806009571174438, "", false, false, false, "qD", "1970-01-01 08:00:00", 0.6318159643372342, 11, true, "1970-01-01", "1970-01-01 08:00:00", 0.773159899888732, true, -1739287123, 6E-15, 48991939401924841918314790234), ("", "t", 0.26809908052941034, "", false, false, false, "", "1970-01-01 08:00:00", 0.003299087504698539, 15, false, "1970-01-01", "1970-01-01 08:00:00", 0.23401592518845626, false, -1739287123, 2E-15, 16187820987847305774386619248), (NULL, "xL", 0.5142731169903662, "3", false, false, false, "RqzDAxMP", "1970-01-01 08:00:00", 0.6318159643372342, 5, true, "1970-01-01", "1970-01-01 08:00:00", 0.7253422784119049, true, 404504292, 5E-15, 12700673591681682311871348645);
INSERT INTO t0 VALUES ("7", "Th", 0.16639196734601958, "", false, true, false, "eDaQDc", "1970-01-01 08:00:00", 0.15066205074987027, 11, true, "1970-01-01", "1970-01-01 08:00:00", -1.739287123E9, true, 1063061500, 5E-15, 5010109355181842299820083042), ("ua4", "D78iD", 0.1607463355960439, "", false, true, false, "bFidmCMrB", "1970-01-01 08:00:00", 0.1902024117476433, 6, true, "1970-01-01", "1970-01-01 08:00:00", 0.1607463355960439, true, -1739287123, 3E-15, 25982843037270304741785942326);
INSERT INTO t3 VALUES (656619243096866256393.336, false, true, 1, "1970-01-01", NULL, true, bitmap_hash("es"), 0.8537913575685493, 0.284496089770389, 25327036.434491, percentile_hash("-1208607752"), hll_hash("t"), hll_hash(""), 9.09344E-9, 0.38831466211997434), (755288780403931895079.949, true, true, 25, "1970-01-01", true, NULL, bitmap_hash(""), 0.4055529856020538, 0.01188970872310624, NULL, percentile_hash("-1208607752"), hll_hash("7"), hll_hash("wI"), 1.75877E-9, 0.8752796128159727), (851721778657708483707.298, true, false, 16, "1970-01-01", true, false, bitmap_hash(""), 0.515524912839354, 0.06545378724510331, 75310205.411249, percentile_hash("1710444268"), hll_hash("1j"), hll_hash(""), 7.69134E-9, 0.904437056560162);
INSERT INTO t1 VALUES (7E-7, -1208607752, 404504292, "1970-01-01", "1970-01-01 08:00:00", 1, -0.0);
INSERT INTO t2 VALUES ("1970-01-01", 0.9211231167222723);
INSERT INTO t2 VALUES ("1970-01-01", 0.2903801369783091);
INSERT INTO t2 VALUES ("1970-01-01", 0.5005975461231202), ("1970-01-01", 0.9950584050707447);
INSERT INTO t0 VALUES ("Y", "", 0.2147121673662009, "", false, true, true, "", "1970-01-01 08:00:00", 0.981860481270191, 5, true, "1970-01-01", "1970-01-01 08:00:00", -1.739287123E9, true, 326844482, 1E-15, 65639506260568014078926601939);
INSERT INTO t0 VALUES ("", "f", 0.24922495241086517, "CdIHSTi0", false, false, false, "H4tFySL", "1970-01-01 08:00:00", 0.2132528355148241, 13, false, "1970-01-01", "1970-01-01 08:00:00", 0.15066205074987027, false, 1047976795, 1E-15, 6950479552679390161329386899), ("", "p", 0.4055529856020538, "I", true, NULL, true, "HS", "1970-01-01 08:00:00", 0.0431272916332891, 9, true, "1970-01-01", "1970-01-01 08:00:00", 3.26844482E8, false, 1975379914, 7E-15, 41796648295210019182488458966), ("Dy", "5T", 3.26844482E8, "P", false, true, false, "Uf", "1970-01-01 08:00:00", 0.41277735193030374, 15, true, "1970-01-01", "1970-01-01 08:00:00", 0.44604466440988666, false, -689462136, 1E-15, 82733621636023904160281894348);
INSERT INTO t1 VALUES (2E-7, 508603959, -689462136, "1970-01-01", "1970-01-01 08:00:00", 7, 0.8596802591986158);
INSERT INTO t3 VALUES (479416499050540068086.695, false, true, NULL, "1970-01-01", true, false, bitmap_hash("fj"), 4.04504292E8, 1.047976795E9, 88154928.577110, percentile_hash("-1820474098"), hll_hash("GW"), hll_hash("96"), 3.86997E-9, 0.14902202406992426), (353175571637766694300.677, false, false, NULL, "1970-01-01", false, true, bitmap_hash(""), 0.009121337554633624, 0.043960850622130954, 96169834.697297, percentile_hash("2069486448"), hll_hash(""), hll_hash("T"), 7.35191E-9, 0.46962832719397773);
INSERT INTO t0 VALUES ("", "", 0.9211231167222723, "c", false, false, true, "", "1970-01-01 08:00:00", -1.739287123E9, 4, false, "1970-01-01", "1970-01-01 08:00:00", 1.710444268E9, true, -570814994, 8E-15, 12746325080417202182636593477), ("p", "we", -1.820474098E9, "", false, false, false, "gPz", "1970-01-01 08:00:00", 0.5717215994541579, 10, false, "1970-01-01", NULL, 0.17915554825842595, false, -1776422868, NULL, 23019309163560687190528817325);
INSERT INTO t0 VALUES ("E", "NS", 0.9386463488728595, "K", true, true, NULL, "b", "1970-01-01 08:00:00", 0.3567489872466655, 7, true, "1970-01-01", "1970-01-01 08:00:00", -5.70814994E8, false, 1047976795, 5E-15, 87832428148701154212248276564);
```
mysql> SELECT COUNT(*) FROM t0 WHERE (t0.c_0_16)  BETWEEN (t0.c_0_16) AND (CASE  WHEN true THEN ((CASE  WHEN (t0.c_0_12)  BETWEEN (t0.c_0_12) AND (t0.c_0_12)  THEN -9223372036854775808 END)%(1347393872)) ELSE t0.c_0_16 END) ;
+----------+
| count(*) |
+----------+
|        7 |
+----------+
1 row in set (0.03 sec)

mysql> SELECT SUM(count) FROM (SELECT CAST((CAST((t0.c_0_16)  BETWEEN (t0.c_0_16) AND (CASE  WHEN true THEN ((CASE  WHEN (t0.c_0_12)  BETWEEN (t0.c_0_12) AND (t0.c_0_12)  THEN -9223372036854775808 END)%(1347393872)) ELSE t0.c_0_16 END)  AS BOOLEAN) = true) AND (CAST((t0.c_0_16)  BETWEEN (t0.c_0_16) AND (CASE  WHEN true THEN ((CASE  WHEN (t0.c_0_12)  BETWEEN (t0.c_0_12) AND (t0.c_0_12)  THEN -9223372036854775808 END)%(1347393872)) ELSE t0.c_0_16 END)  AS BOOLEAN) IS NOT NULL) AS INT) as count FROM t0 ) t;
+--------------+
| sum(`count`) |
+--------------+
|            5 |
+--------------+

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.1 ASAN
 - mysql> select current_version();
+------------------------------+
| current_version()            |
+------------------------------+
| SQLANCER_BRANCH_ASAN 7ea2d38 |
+------------------------------+

**Comment by Seaven** [comment]
```
mysql> SELECT (CASE WHEN (t0.c_0_12)  BETWEEN (t0.c_0_12) AND (t0.c_0_12)  THEN -9223372036854775808 END)% (1347393872)
    -> from t0;
+------------------------------------------------------------------------------------------------------------+
| CASE WHEN `t0`.`c_0_12` BETWEEN `t0`.`c_0_12` AND `t0`.`c_0_12` THEN -9223372036854775808 END % 1347393872 |
+------------------------------------------------------------------------------------------------------------+
| -496742320                                                                                                 |
| -496742320                                                                                                 |
| -496742320                                                                                                 |
| -496742320                                                                                                 |
| -496742320                                                                                                 |
| -496742320                                                                                                 |
| -496742320                                                                                                 |
| -496742320                                                                                                 |
| -496742320                                                                                                 |
+------------------------------------------------------------------------------------------------------------+
9 rows in set (0.02 sec)

mysql> select -9223372036854775808 % 1347393872
    -> from t0;
+-----------------------------------+
| -9223372036854775808 % 1347393872 |
+-----------------------------------+
| 850651552                         |
| 850651552                         |
| 850651552                         |
| 850651552                         |
| 850651552                         |
| 850651552                         |
| 850651552                         |
| 850651552                         |
| 850651552                         |
+-----------------------------------+
9 rows in set (0.01 sec)
```

**Comment by Seaven** [comment]
```
mysql> select (-9223372036854775808) % 1347393872  from t0;
+-------------------------------------+
| (-9223372036854775808) % 1347393872 |
+-------------------------------------+
| -496742320                          |
| -496742320                          |
| -496742320                          |
| -496742320                          |
+-------------------------------------+
4 rows in set (0.01 sec)

mysql> select (-9223372036854775808) % 1347393872;
+-------------------------------------+
| (-9223372036854775808) % 1347393872 |
+-------------------------------------+
| -496742320                          |
+-------------------------------------+
1 row in set (0.00 sec)
```
