### ISSUE TITLE
Add minio into the sharded nothing allin1 container

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#36203]
so that we can support the the quickstart files() tutorial.

**Comment by kevincai** [comment]
I am hesitated to add more and more components into allin1 docker image. Think about the boundary of the allin1 docker image, what should be included, what should not.

Right now I have a simple criteria:
* all the SR components can be packed into the allin1 docker images
* none-SR components will not be included by default.

As for this minio requirement, I think `docker-compose` solution is preferred which is available at https://github.com/StarRocks/demo/tree/master/deploy/docker-compose
