### ISSUE TITLE
[function] typeof

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#36245]
sometimes we don't know the exact type of an output, in starrocks there is not a good way to confirm that. so we need this function.

## typeof

Returns the name of the type of the provided expression

## syntax

```
TYPEOF( <expr> )
```

## input
any expr, it can be a funtion's result or an expression of column..

## output
the name of the type of the provided expression, like int(11),varchar(65533) or datetime.

reference 
https://trino.io/docs/current/functions/conversion.html?highlight=typeof#typeof
https://docs.snowflake.com/en/sql-reference/functions/typeof

**Comment by NeelakshSharma** [comment]
Hi @wangsimo0 , i would like to work on this issue. Can we please connect on how to get started?

**Comment by xuzifu666** [comment]
> Hi @wangsimo0 , i would like to work on this issue. Can we please connect on how to get started?

i would do the issue recently  @NeelakshSharma

**Comment by NeelakshSharma** [comment]
Oh okay, can you please attach the PR for my reference? I would like to see the implementation.

**Comment by MicePilot** [comment]
@xuzifu666 May I ask how the current progress is? We need this function.

**Comment by MicePilot** [comment]
@xuzifu666 Hi，I have implemented the typeof function, can I submit a PR for this issue?

**Comment by xuzifu666** [comment]
> @xuzifu666 Hi，I have implemented the typeof function, can I submit a PR for this issue?

OK，you can submit it，Thanks @MicePilot
