### ISSUE TITLE
sql analysis bug

### ISSUE THREAD

**Issue by bigdata-kuxingseng** [StarRocks/starrocks#3639]
where outside select contains inner computed expression,the can not be explained

**Comment by bigdata-kuxingseng** [comment]
SELECT
	`T_AABC60`.`acc_id` AS `__fcol_0`,
	`T_AABC60`.`(``violation_ad_spend_amt_28d_agent`` - ``violation_ad_spend_amt_28d_acc``) / (``spend_amt_28d_agent`` - ``spend_amt_28d_acc``)` AS `__fcol_5` 
FROM
	(
	SELECT
		acc_id,
		( violation_ad_spend_amt_28d_agent - violation_ad_spend_amt_28d_acc ) / ( spend_amt_28d_agent - spend_amt_28d_acc ) 
	FROM
		test.testabc 
	WHERE
		acc_agent != '' 
		AND acc_agent != 'avc' 
		AND dt = date_sub( CURRENT_DATE ( ), 1 ) 
	) AS `T_AABC60` 
	LIMIT 5000;

**Comment by kangkaisen** [comment]
@bigdata-kuxingseng what your mean is this sql could execute，but couldn't explain？

**Comment by kangkaisen** [comment]
@bigdata-kuxingseng please describe your create table sql. thank you.
