### ISSUE TITLE
Support retrieving Kafka message key when using a routine load job

### ISSUE THREAD

**Issue by Fanvadar** [StarRocks/starrocks#36511]
## Feature request

**Is your feature request related to a problem? Please describe.**
When using a routine load job to consume a kafka topic, it doesn't seem possible to access the key of the messages. 

**Describe the solution you'd like**
Clickhouse handles this with virtual columns, which could be a viable solution: 
https://clickhouse.com/docs/en/engines/table-engines/integrations/kafka#virtual-columns

**Describe alternatives you've considered**
You could just put that data in the kafka message value as well, but this isn't always possible.

**Comment by ahemon** [comment]
Any update on this feature ?
