### ISSUE TITLE
Unable to create Materialized view on Iceberg format V2 table with PARTITION BY clause

### ISSUE THREAD

**Issue by atifiu** [StarRocks/starrocks#36532]
I am trying to create MV on Iceberg catalog partitioned table( format version V2) and although I am able to create MV without partition by clause but if I include partition by clause in the MV create statement it throws error  which says:

`Detail message: Materialized view partition column in partition exp must be base table partition column`

### Steps to reproduce the error:

**Successful i.e. without partition by clause**

```
CREATE MATERIALIZED VIEW sr_db1.view_ice_mv
DISTRIBUTED BY HASH(num_ID)
REFRESH ASYNC EVERY(INTERVAL 1 DAY) 
AS 
SELECT date_trunc('day',page_view_dtm) as page_view_dt,
COALESCE (site, 'abc') as site1,
case when country_nm = 'a1' then 1 else 0 END as a1_only,
case when device_type_nm = 'mp' then 0 else 1 END as device_type,
site,
       list_nm,
  COUNT( distinct ID) as num_ID,
  COUNT( distinct (concat(cast(ID as varchar), cast(ARR_NUM as varchar)))) as num_ARR,
       COUNT(1) as num_PV
FROM iceberg_dev.db1.table1_iceberg
WHERE page_view_dtm  between '2023-08-01 00:00:00' and '2023-08-31 23:59:59'
  AND CD = 0
  AND site = 'cR'
GROUP BY 1, 2, 3, 4, 5, 6
ORDER BY num_PV DESC;
```

**Unsuccessful i.e. with partition by clause**

```
CREATE MATERIALIZED VIEW sr_db1.view_ice_mv1
DISTRIBUTED BY HASH(num_ID)
PARTITION BY site_nm
REFRESH ASYNC EVERY(INTERVAL 1 DAY) 
AS 
SELECT date_trunc('day',page_view_dtm) as page_view_dt,
COALESCE (site, 'abc') as site1,
case when country_nm = 'a1' then 1 else 0 END as a1_only,
case when device_type_nm = 'mp' then 0 else 1 END as device_type,
site,
       list_nm,
  COUNT( distinct ID) as num_ID,
  COUNT( distinct (concat(cast(ID as varchar), cast(ARR_NUM as varchar)))) as num_ARR,
       COUNT(1) as num_PV
FROM iceberg_dev.db1.table1_iceberg
WHERE page_view_dtm  between '2023-08-01 00:00:00' and '2023-08-31 23:59:59'
  AND CD = 0
  AND site = 'cR'
GROUP BY 1, 2, 3, 4, 5, 6
ORDER BY num_PV DESC;
```

### StarRocks version (Required)
 - 3.1.2-4f3a2ee

**Comment by Youngwb** [comment]
The 'site_nm' column should be 'table1_iceberg' partition column, and it also need to be the output column of the select clause

**Comment by atifiu** [comment]
@Youngwb Iceberg table is partitioned using `day(page_view_dtm )` and even if I use this column with or without transformation it throws me same error. Please suggest.

**Comment by Youngwb** [comment]
SR do not support create Iceberg MV when the icebegr table partition column has transformation for now, we will support it later

**Comment by atifiu** [comment]
@Youngwb @DorianZheng Thanks your response. We wont be able to change out iceberg table partitioning as we have recently moved away from Hive integer based date partitioning to more flexible timestamp based partitioning.

**Comment by DorianZheng** [comment]
@atifiu We have supported create MV for iceberg table with transformation partition. https://github.com/StarRocks/starrocks/pull/38196

**Comment by mofeiatwork** [comment]
> @atifiu We have supported create MV for iceberg table with transformation partition. #38196

awesome
