### ISSUE TITLE
goland gorm use ? Placeholder query for starrocks-3.2 data gives error

### ISSUE THREAD

**Issue by moody1117** [StarRocks/starrocks#36586]
Does sr3.2-rc01 support this feature now?
Related Discussions：
https://forum.mirrorship.cn/t/topic/2725/3
<img width="946" alt="image" src="https://github.com/StarRocks/starrocks/assets/50506546/9b9ab6e7-dec1-4299-9c99-466a5a8c1160">

### Steps to reproduce the behavior (Required)
CREATE TABLE `food` (
 `id` int(10),
   `name` varchar(30),
  `price` decimal(10,2),
  `type_id` int(10),
  `createtime` int(10)
) ENGINE=OLAP 
DUPLICATE KEY(`id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id`) BUCKETS 32 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
);
insert into food values(1,'bbb',112,222,1701867720);
select * from food;
![image](https://github.com/StarRocks/starrocks/assets/50506546/4e32a138-f9d1-4668-b1f0-fe1c2c7339af)

### Expected behavior (Required)
<img width="744" alt="image" src="https://github.com/StarRocks/starrocks/assets/50506546/345fb07e-6d1e-424c-98c1-9cfd12fb6ae4">

### Real behavior (Required)
<img width="903" alt="image" src="https://github.com/StarRocks/starrocks/assets/50506546/20376cf3-891c-4ef2-9f27-dfc668946a14">

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 
![image](https://github.com/StarRocks/starrocks/assets/50506546/2245e4f3-6ac0-48b6-8673-4e847eec2680)

### code
```goland
package main

import (
	"encoding/json"
	"fmt"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
)

type Food struct {
	Id     int    
	Name   string 
	Price  float64 
	TypeId int     
	CreateTime int64 `gorm:"column:createtime"` //表字段名为：createtime
}

func (v Food) TableName() string {
	return "food"
}

func sr() []Food {
	dsn := "root:xxxx@tcp(xxxxxxx:9030)/realtime?charset=utf8mb4"
	db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})
	if err != nil {
		panic("failed to connect database")
	}
	fmt.Print("连接SR成功")
	var food []Food
	db.Debug().Where("id = ?", 1).First(&food)

	jsonVal, err := json.Marshal(food)
	if err == nil {
		fmt.Println("SR数据:", string(jsonVal))
	} else {
		panic(err)
	}
	return food
}

func main() {
	dsn := "root:xxxxxx@tcp(127.0.0.1:3306)/sa_cloud?charset=utf8mb4"
	db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})
	if err != nil {
		panic("failed to connect database")
	}
	fmt.Print("连接Mysql成功")
	var food []Food
	db.Debug().Where("id = ?", 1).First(&food)

	jsonVal, err := json.Marshal(food)
	if err == nil {
		fmt.Println("Mysql数据:", string(jsonVal))
	} else {
		panic(err)
	}
	fmt.Println("\n==============================")
	sr()
}
```

**Comment by Evilran** [comment]
interpolateParams=true

**Comment by moody1117** [comment]
> interpolateParams=true

thanks
