### ISSUE TITLE
Push down limit into TabletReader upon SegmentIterator

### ISSUE THREAD

**Issue by satanson** [StarRocks/starrocks#36595]
## Feature request
If a query that accesses duplicate tables carries with quite a small limit and predicates that can be pushed down to storage layer, Limit may be pushed down into TabletReader upon SegmentIterator to save IO cost in advance. The query like this:
```
select * from t where t.name like "%A%" limit 10;
```
Assuming ChunkSource would deliver the same rows to ScanOperator before the numbe of rows reaches limit,  
when predicate t.name like "%A%" is pushed down to storage layer, the storage layer would read more rows than the counterpart in that case the predicate is not pushed down. The reason is that SegmentIterators would read superfluous rows, if we place a LimitIterator on the SegmentIterators and choose a moderate chunk size as a unit to fetch data from segment files, the unnecessary IO would be eliminated. 

**Describe the solution you'd like**

1. It seems that only a small limit could benefit from this optimization.
2. duplicate/primary key tables can adopts this optimization, while aggregate/unique key not. 
3. Push down the limit into TabletReader and place a LimitIterator onto SegmentIterator.
4. Use a moderate chunk size instead of default chunk_size as fetch unit.
 
**Describe alternatives you've considered**
Please refer to these the code as follows:
1. ChunkSource uses limit to save IO cost.
```cpp
Status OlapChunkSource::_read_chunk_from_storage(RuntimeState* state, Chunk* chunk) {
...
    // Improve for select * from table limit x, x is small
    if (_limit != -1 && _num_rows_read >= _limit) {
        return Status::EndOfFile("limit reach");
    }
    return Status::OK();
}
```

2. To see Status TabletReader::init_collector(const TabletReaderParams& params) and found out how to decorate SegmentIterators and build other complex iterators from SegmentIterators.
3. The LimitIerator should extend from ChunkIterator, please reference to TimedChunkIterator.
4. Please add some profile counter to check if the LimitIterator works.
5. Conduct some tests on this feature.

**Additional context**

**Comment by before-Sunrise** [comment]
can u assigin this issue to me?
