### ISSUE TITLE
Support Object Storage to store FE metadata

### ISSUE THREAD

**Issue by kant777** [StarRocks/starrocks#36705]
While support for storage and compute separation is great the FE metadata is still on local disk today which means there is additional operational overhead etc so storing FE metadata in an object will make star rocks more cloud native.

**Comment by inviscid** [comment]
This would be a very welcome feature so the persistent storage layer for StarRocks instance could exist completely in cloud storage.

The FE data must be backed up and recovered separately from the table data adds complexity and potential mismatches between structure and data if the backups can't maintain consistency between FE and cloud storage table data.
