### ISSUE TITLE
Make SHOW ALTER TABLE more queriable

### ISSUE THREAD

**Issue by AsaiWiz** [StarRocks/starrocks#36741]
## Enhancement
SHOW ALTER TABLE COLUMN WHERE 
(state = "RUNNING" or state = "PENDING" or state = "WAITING_TXN") and
TableName = "sat_order_pocdata" ;

gives 

QL Error [1064] [42000]: Getting analyzing error. Detail message: Only allow compound predicate with operator AND.

If I want to know if I want to execute the next ALTER TABLE ADD COLUMN programmatically, this limitation blocks. 

I favor a metadata table that can be queried with Select for this. Please consider.

**Comment by imay** [comment]
Yeah, we can move all this information into a system view in information_schema
