### ISSUE TITLE
How to implement such a requirement with Flinks-Starrock-sink,

### ISSUE THREAD

**Issue by qq1196064062** [StarRocks/starrocks#36745]
How to implement such a requirement with Flinks-Starrock-sink,
If it exists, update accumulates, if it does not exist, insert,
If I use mysql, I know how to do it, but now with starrock, I have looked up a lot of information, there is no relevant information,
My Flink collects data every five minutes, and I need to sum these data and update the statistics to startRocks because our requirements are daily statistics.
To give you an example,
A has recharged $10 in five minutes and recharged for the first time today.
So I need to insert,
In the second count, A recharges $20 within five minutes, at this time, the record needs to be updated to 30.

**Comment by LoseYSelf** [comment]
Aggregate table can help you
