### ISSUE TITLE
[trino's compatibility issue] date related calculation

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#36773]
## Enhancement

there are some difference between trino and starrocks when dealing with date calculation. here are two examples that need to be fixed.

1.  select date_add('day', -1, date(concat(substr('2023-12-10', 1, 7), '-01'))); 
in StarRocks, when set SQL dialect to trino, the SQL returns: 2023-11-30 00:00:00
in trino, the SQL returns 2023-11-30

2. select date('2023-12-10')-interval '1' day;
in StarRocks, when set SQL dialect to trino, the SQL returns: 2023-12-09 00:00:00
in trino, the SQL returns 2023-12-09

a simple solution is to use date_trunc or cast as date. the first one can be fixed by adding transform in Trino2SRFunctionCallTransformer and the second one need to be fixed in AstBuilder

**Comment by silly-carbon** [comment]
I could help finish this, please assign it to me if OK
