### ISSUE TITLE
Starrocks crashes every 4-5 days once

### ISSUE THREAD

**Issue by sridhard** [StarRocks/starrocks#36789]
### Steps to reproduce the behavior (Required)
random crash

### Expected behavior (Required)
there should not be any crash

### Real behavior (Required)
crashes every 3-4 days

### StarRocks version (Required)
3.1.2
[](url)

We are using starrocks in shared data mode. I have attached the crash logs file
[be.out.txt](https://github.com/StarRocks/starrocks/files/13633217/be.out.txt)

**Comment by sduzh** [comment]
@sridhard Please upgrade to 3.1.5 to fix this problem.

**Comment by sduzh** [comment]
Looks like the same problem as https://github.com/StarRocks/starrocks/issues/29929
