### ISSUE TITLE
optimize materialized view

### ISSUE THREAD

**Issue by DeepThinker666** [StarRocks/starrocks#3680]
## Enhancement
Materialized view can be used in data warehouse for two general purpose: 1. modeling, just like a view; 2. query performance optimization.
Starrocks support materialized view now. It acts as a rollup and it has some limitations:
1. can not query materialized view directly
2. materialized view can not support multi tables
3. the partition and distribution must be the same as the base table, which will hurt performance in some situations, like tables with too many partitions
4. can not support complex computation on columns
5. do not support predicates in materialized view
6. do not support external tables

Now I want to enhance the materialized view and make it to be more general. The purpose is as followings:
1. to support querying materiazlied view directly and try best to keep the result consistent with querying base tables
2. to support creating mvs on multi tables
3. partition and distribution desc can be specified for each mv independently.
4. to support complex computation on columns
5. to support adding predicate in sql for mvs
6. to support making mvs on external tables

This issue will be used to track all detail works which will be added later.

**Comment by blackstar-baba** [comment]
Create mv grammar:
```
createMaterializedViewStatement
    : CREATE MATERIALIZED VIEW (IF NOT EXISTS)? mvName=qualifiedName
    comment?
    (PARTITION BY primaryExpression)?
    distributionDesc?
    refreshSchemeDesc?
    properties?
    AS queryStatement
    ;
```

**Comment by hackeryang** [comment]
Supplement: This issue is where the distinction between synchronous and asynchronous materialized views begins: https://docs.starrocks.io/docs/using_starrocks/Materialized_view-single_table/
