### ISSUE TITLE
Hive external : RC_FILE should be supported

### ISSUE THREAD

**Issue by mklzl** [StarRocks/starrocks#369]
## Enhancement

    Some users use RC_FILE for their Hive tables，but they cannot use external tables for starrocks.
    Can this defect be modified to support RC_FILE formatted Hive external tables for starrocks ?

**Comment by imay** [comment]
Starrocks will support RC_FILE. Do you want to handle it?

**Comment by dirtysalt** [comment]
For performance consideration, we are accessing hdfs file using C++ APIs. Is there available C++ lib to access RC File? Btw the way, are RCFile and ORCFile compatible? Right now we support to access ORCFile on hdfs.
