### ISSUE TITLE
[BUG] Starrocks can't synchronize iceberg schema changes 

### ISSUE THREAD

**Issue by Zhangg7723** [StarRocks/starrocks#36938]
### Steps to reproduce the behavior (Required)
1. create iceberg table in starrocks
```
    CREATE TABLE iceberg_db.ice_table01 (
  `id` bigint(20) DEFAULT NULL COMMENT "unique id",
  `data` varchar(1048576) DEFAULT NULL
)
PROPERTIES (
"file_format"="parquet"
)
```

2. alter table in spark
`    alter table ice_table01 add column col2 bigint;`

### Expected behavior (Required)
show create table in starrocks and find new column in table schema.
### Real behavior (Required)
show create table in starrocks and the schema is not changed.
starrocks can't load the latest schema.
### StarRocks version (Required)
 - 3.1.5

**Comment by alberttwong** [comment]
Did you try creating the table in spark-sql and connecting via apache iceberg external catalog?

**Comment by Zhangg7723** [comment]
> Did you try creating the table in spark-sql and connecting via apache iceberg external catalog?

No，but I think there is no difference, maybe iceberg metadata is cached in fe memory I guess. table schema is always the latest in spark.
