### ISSUE TITLE
Not hit datacache while reading the Paimon table

### ISSUE THREAD

**Issue by taoshengyijiua** [StarRocks/starrocks#36943]
## Enhancement
![1702449611096_329B4303-E688-42c6-B1A6-C839A098E81A](https://github.com/StarRocks/starrocks/assets/45588521/37ca5397-889f-44cc-9339-a6c9c1b21a2c)
When reading the Paimon external table  through StarRocks, enabling datacache is invalid. It is recommended to add this feature to improve the efficiency of reading the Paimon external table

**Comment by miomiocat** [comment]
Thank you for the feedback.   
Data cache does not yet support Paimon, but we will evaluate the addition of this feature as soon as possible.

**Comment by lmagic233** [comment]
@miomiocat  I've tested reading Paimon tables on S3 just before, with identical aggregation queries, and both `enable_scan_datacache` and `enable_populate_datacache` parameters are set to true. The query profile shows that data cache is effective. Is this a false indicator or it's truely available? Thanks.
<img width="2209" alt="image" src="https://github.com/StarRocks/starrocks/assets/26239106/6a635008-f866-4a26-9ae3-da7c05ae8318">

**Comment by Pandas886** [comment]
Does piamon now support data cache?

**Comment by miomiocat** [comment]
> @miomiocat I've tested reading Paimon tables on S3 just before, with identical aggregation queries, and both `enable_scan_datacache` and `enable_populate_datacache` parameters are set to true. The query profile shows that data cache is effective. Is this a false indicator or it's truely available? Thanks. <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/26239106/313057805-6a635008-f866-4a26-9ae3-da7c05ae8318.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzY4NjksIm5iZiI6MTcxMzg3NjU2OSwicGF0aCI6Ii8yNjIzOTEwNi8zMTMwNTc4MDUtNmE2MzUwMDgtZjg2Ni00YTI2LTlhZTMtZGE3YzA1YWU4MzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDEyNDkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMDkyZWY1MDI0NmZjNDhlNGNiNGRkNjBlNDdmZWI4OWUwYjE3ZThkNzQ3ZWI2MzU1NjViNTRjYTQ1YTIxNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2jC962uDdqktjn-lnEFdA2M2FgmooaY4ZV31yamOg_s">

paimon datacache available from 3.2.3 version

**Comment by miomiocat** [comment]
> Does piamon now support data cache?

yes. available from 3.2.3 version
