### ISSUE TITLE
Multiple MAX/AVG window functions are mixed in one SQL, and the MAX result is incorrect.

### ISSUE THREAD

**Issue by dream1cast** [StarRocks/starrocks#36966]
### Steps to reproduce the behavior (Required)
1. CREATE duplicated key table with columns time_id, uuid and some metrics, like `tbl_data_res_2080_15_starrocks`
```sql
create table tbl_data_res_2080_15_starrocks (
    time_id datetime,res_ins_id bigint,r2080_i10005 double,r2080_i10006 double,r2080_i10007 double,r2080_i10008 double
)
DUPLICATE KEY(time_id, res_ins_id)
PARTITION BY RANGE(time_id) (
    START ("20231205") END ("20231207") EVERY (INTERVAL 1 HOUR)
)
DISTRIBUTED BY HASH(res_ins_id)
PROPERTIES(
    "dynamic_partition.enable" = "true",
    "dynamic_partition.time_unit" = "HOUR",
    "dynamic_partition.start" = "-168",
    "dynamic_partition.end" = "12",
    "dynamic_partition.prefix" = "p",
    "dynamic_partition.history_partition_num" = "0"
);
```
2. INSERT INTO table with some metrics with time_id and uuid
![image](https://github.com/StarRocks/starrocks/assets/41135592/0febf561-5098-4ee2-89ce-0af9038439f8)
[row_data.csv](https://github.com/StarRocks/starrocks/files/13658827/row_data.csv)

3. 
```sql
select time_id, res_ins_id as longID,
        r2080_i10005,MAX(r2080_i10005) OVER (partition by res_ins_id order by time_id rows between 3 PRECEDING and current row) as OutboundPeakTrafficUtilization,
        r2080_i10006,AVG(r2080_i10006) OVER (partition by res_ins_id order by time_id rows between 3 PRECEDING and current row) as OutboundBandwidthUtilization,
        r2080_i10007,MAX(r2080_i10007) OVER (partition by res_ins_id order by time_id rows between 3 PRECEDING and current row) as InboundPeakTrafficUtilization,
        r2080_i10008,AVG(r2080_i10008) OVER (partition by res_ins_id order by time_id rows between 3 PRECEDING and current row) as InboundBandwidthUtilization
from tbl_data_res_2080_15_starrocks
where from_unixtime(time_id/1000) > '2023-12-13 12:00:00' and res_ins_id = '50086357'
order by res_ins_id,time_id;
```

### Expected behavior (Required)
get the correct window aggregation result for each metrics over past 4 time_id

### Real behavior (Required)
only the AVG aggregation result is correct, the MAX aggregation result is incorrect, which is only the first value.
like "OutboundPeakTrafficUtilization" is always 41.84,  and "InboundPeakTrafficUtilization"  is always 73.49

+---------------------+----------+--------------+--------------------------------+--------------+------------------------------+--------------+-------------------------------+--------------+-----------------------------+
| time_id             | longID   | r2080_i10005 | OutboundPeakTrafficUtilization | r2080_i10006 | OutboundBandwidthUtilization | r2080_i10007 | InboundPeakTrafficUtilization | r2080_i10008 | InboundBandwidthUtilization |
+---------------------+----------+--------------+--------------------------------+--------------+------------------------------+--------------+-------------------------------+--------------+-----------------------------+
| 2023-12-06 17:00:00 | 50086357 |        41.84 |                          41.84 |        33.62 |                        33.62 |        73.49 |                         73.49 |        40.76 |                       40.76 |
| 2023-12-06 17:15:00 | 50086357 |        28.33 |                          41.84 |        71.49 |            52.55499999999999 |        80.47 |                         73.49 |        88.71 |                      64.735 |
| 2023-12-06 17:30:00 | 50086357 |         24.6 |                          41.84 |        48.39 |           51.166666666666664 |        23.89 |                         73.49 |         3.62 |           44.36333333333334 |
| 2023-12-06 17:45:00 | 50086357 |        37.71 |                          41.84 |        91.71 |           61.302499999999995 |        58.25 |                         73.49 |        39.67 |                       43.19 |
| 2023-12-06 18:00:00 | 50086357 |        94.94 |                          41.84 |        73.91 |                       71.375 |        43.18 |                         73.49 |         0.07 |                     33.0175 |
| 2023-12-06 18:15:00 | 50086357 |        43.31 |                          41.84 |        19.22 |                      58.3075 |          3.1 |                         73.49 |        71.51 |                     28.7175 |
| 2023-12-06 18:30:00 | 50086357 |        89.48 |                          41.84 |        32.29 |            54.28249999999999 |        37.73 |                         73.49 |        53.39 |                       41.16 |
| 2023-12-06 18:45:00 | 50086357 |         6.29 |                          41.84 |        40.76 |           41.544999999999995 |        23.53 |                         73.49 |        81.96 |          51.732499999999995 |
| 2023-12-06 19:00:00 | 50086357 |        43.18 |                          41.84 |        32.03 |           31.074999999999996 |        30.48 |                         73.49 |        22.34 |                        57.3 |
| 2023-12-06 19:15:00 | 50086357 |        34.09 |                          41.84 |        78.35 |           45.857499999999995 |         6.39 |                         73.49 |        53.19 |                       52.72 |
| 2023-12-06 19:30:00 | 50086357 |        67.57 |                          41.84 |        88.36 |                       59.875 |        87.76 |                         73.49 |        76.93 |          58.605000000000004 |
| 2023-12-06 19:45:00 | 50086357 |        68.73 |                          41.84 |        31.49 |           57.557500000000005 |         3.75 |                         73.49 |        96.81 |           62.31750000000001 |
| 2023-12-06 20:00:00 | 50086357 |        20.35 |                          41.84 |        22.53 |           55.182500000000005 |        28.32 |                         73.49 |           51 |           69.48250000000002 |
| 2023-12-06 20:15:00 | 50086357 |        29.51 |                          41.84 |           14 |           39.095000000000006 |        56.85 |                         73.49 |         8.43 |           58.29250000000002 |
| 2023-12-06 20:30:00 | 50086357 |        13.99 |                          41.84 |        30.55 |           24.642500000000005 |         9.65 |                         73.49 |        31.98 |          47.055000000000014 |
| 2023-12-06 20:45:00 | 50086357 |        77.88 |                          41.84 |        46.34 |           28.355000000000008 |         2.65 |                         73.49 |        96.62 |          47.007500000000014 |
| 2023-12-06 21:00:00 | 50086357 |        70.09 |                          41.84 |        51.64 |            35.63250000000001 |        86.52 |                         73.49 |        92.36 |           57.34750000000001 |
| 2023-12-06 21:15:00 | 50086357 |        47.68 |                          41.84 |        83.87 |            53.10000000000001 |         96.1 |                         73.49 |        54.39 |                     68.8375 |
| 2023-12-06 21:30:00 | 50086357 |         97.3 |                          41.84 |         46.7 |                      57.1375 |         6.29 |                         73.49 |        35.54 |                     69.7275 |
| 2023-12-06 21:45:00 | 50086357 |         27.4 |                          41.84 |        35.07 |                        54.32 |        56.51 |                         73.49 |           32 |          53.572500000000005 |
| 2023-12-06 22:00:00 | 50086357 |        11.29 |                          41.84 |         46.7 |           53.084999999999994 |        30.84 |                         73.49 |        94.79 |           54.18000000000001 |
| 2023-12-06 22:15:00 | 50086357 |        95.17 |                          41.84 |        30.92 |                      39.8475 |         3.65 |                         73.49 |         41.7 |           51.00750000000001 |
| 2023-12-06 22:30:00 | 50086357 |        16.15 |                          41.84 |        83.15 |           48.959999999999994 |        36.99 |                         73.49 |        37.67 |          51.540000000000006 |
| 2023-12-06 22:45:00 | 50086357 |        52.84 |                          41.84 |        99.61 |                       65.095 |        94.55 |                         73.49 |         8.88 |          45.760000000000005 |
| 2023-12-06 23:00:00 | 50086357 |         8.09 |                          41.84 |        54.55 |                      67.0575 |        96.25 |                         73.49 |        86.43 |                       43.67 |
| 2023-12-06 23:15:00 | 50086357 |        67.59 |                          41.84 |        28.97 |                        66.57 |        43.19 |                         73.49 |        35.93 |          42.227500000000006 |
| 2023-12-06 23:30:00 | 50086357 |        60.79 |                          41.84 |        68.72 |            62.96249999999999 |        64.92 |                         73.49 |        77.72 |                       52.24 |
| 2023-12-06 23:45:00 | 50086357 |        69.72 |                          41.84 |        51.83 |           51.017499999999984 |        20.15 |                         73.49 |         88.2 |           72.07000000000001 |
+---------------------+----------+--------------+--------------------------------+--------------+------------------------------+--------------+-------------------------------+--------------+-----------------------------+

### StarRocks version (Required)
 - 3.1.2-4f3a2ee

**Comment by liuyehcf** [comment]
This problem has been solved by https://github.com/StarRocks/starrocks/pull/34312
Fixed version: >=3.1.5
