### ISSUE TITLE
Unsupported iceberg file content

### ISSUE THREAD

**Issue by yuanzhangjun** [StarRocks/starrocks#37122]
### Steps to reproduce the behavior (Required)
CREATE TABLE iceberg_db.iceberg_xxl_job_log (
  `id` STRING,
  `job_group` STRING COMMENT '',
  `job_id` STRING COMMENT '',
  `executor_address` STRING COMMENT '',
  `executor_handler` STRING COMMENT '',
  `executor_param` STRING COMMENT '',
  `executor_sharding_param` STRING COMMENT '',
  `executor_fail_retry_count` STRING COMMENT '',
  `trigger_time` STRING COMMENT '',
  `trigger_code` STRING COMMENT '',
  `trigger_msg` STRING COMMENT '',
  `handle_time` STRING COMMENT '',
  `handle_code` STRING COMMENT '',
  `handle_msg` STRING COMMENT '',
  `alarm_status` STRING COMMENT '',
  `execute_date` STRING COMMENT '',
  `handle_type` STRING COMMENT '',
  `call_back_msg` STRING COMMENT '',
  `wait_time` STRING COMMENT '',
  `wait_status` STRING COMMENT '',
  `release_code` STRING COMMENT '',
  `time_zone` STRING COMMENT '')
USING iceberg
PARTITIONED BY (truncate(trigger_time, 10))
LOCATION ''
TBLPROPERTIES(
  'current-snapshot-id' = '7573267705329840892',
  'format' = 'iceberg/parquet',
  'write.format.default' = 'parquet',
  'write.metadata.delete-after-commit.enabled' = 'true',
  'write.metadata.previous-versions-max' = '1',
  'write.parquet.compression-codec' = 'zstd',
  'format-version'='2')

### Expected behavior (Required)
return result

### Real behavior (Required)
ERROR 1064 (HY000): Unsupported iceberg file content: 2

### StarRocks version (Required)
 -3.1.4

be.warn.log
W1214 07:19:19.821959 3144 iceberg_delete_builder.h:91] Unsupported iceberg file content: 2
W1214 07:19:19.822075 3144 iceberg_delete_builder.h:91] Unsupported iceberg file content: 2
W1214 07:19:19.822147 3144 iceberg_delete_builder.h:91] Unsupported iceberg file content: 2
W1214 07:19:19.822222 3132 pipeline_driver.cpp:308] pull_chunk returns not ok status Internal error: Unsupported iceberg file content: 2
/build/starrocks/be/src/exec/hdfs_scanner_parquet.cpp:33 iceberg_delete_builder->build_parquet(runtime_state->timezone(), *tdelete_file)
/build/starrocks/be/src/connector/hive_connector.cpp:653 scanner->init(state, scanner_params)
/build/starrocks/be/src/connector/hive_connector.cpp:110 _init_scanner(state)
/build/starrocks/be/src/exec/pipeline/scan/connector_scan_operator.cpp:504 _data_source->open(state)
/build/starrocks/be/src/exec/pipeline/scan/connector_scan_operator.cpp:533 _open_data_source(state)
/build/starrocks/be/src/exec/pipeline/scan/scan_operator.cpp:227 _get_scan_status()
W1214 07:19:19.822255 3144 iceberg_delete_builder.h:91] Unsupported iceberg file content: 2
W1214 07:19:19.822384 3144 iceberg_delete_builder.h:91] Unsupported iceberg file content: 2
W1214 07:19:19.822541 3144 iceberg_delete_builder.h:91] Unsupported iceberg file content: 2
W1214 07:19:19.822258 3132 pipeline_driver_executor.cpp:161] [Driver] Process error, query_id=18c3882c-9a51-11ee-898d-021f8add70b0, instance_id=18c3882c-9a51-11ee-898d-021f8add70b2, status=Internal error: Unsupported iceberg file content: 2
/build/starrocks/be/src/exec/hdfs_scanner_parquet.cpp:33 iceberg_delete_builder->build_parquet(runtime_state->timezone(), *tdelete_file)
/build/starrocks/be/src/connector/hive_connector.cpp:653 scanner->init(state, scanner_params)
/build/starrocks/be/src/connector/hive_connector.cpp:110 _init_scanner(state)
/build/starrocks/be/src/exec/pipeline/scan/connector_scan_operator.cpp:504 _data_source->open(state)
/build/starrocks/be/src/exec/pipeline/scan/connector_scan_operator.cpp:533 _open_data_source(state)
/build/starrocks/be/src/exec/pipeline/scan/scan_operator.cpp:227 _get_scan_status()

**Comment by yuanzhangjun** [comment]
麻烦老师解决一下这个问题
对应论坛文档：https://forum.mirrorship.cn/t/topic/10263

**Comment by chrisfw** [comment]
Hi, I just ran into this same issue in version 3.2.
