### ISSUE TITLE
how to convert varchar to  array

### ISSUE THREAD

**Issue by dufeng1010** [StarRocks/starrocks#3717]
## General Question

I use group_concat function, this method return varchar data type, but i want convert return type to array。but i don't know how to implement it.

**Comment by imay** [comment]
@trueeyu PTAL

**Comment by trueeyu** [comment]
[main has ar](https://github.com/StarRocks/docs.zh-cn/pull/253)

**Comment by trueeyu** [comment]
https://github.com/StarRocks/docs.zh-cn/pull/282/files

**Comment by dufeng1010** [comment]
ok, thanks
