### ISSUE TITLE
bitmap_agg（largeint）结果变成负数

### ISSUE THREAD

**Issue by newrain-zh** [StarRocks/starrocks#37184]
#bitmap_agg函数
##描述
1. bitmap_agg函数使用时 如果列值为largeint时，有时会变成负数，但是所在的列并没有超过largeint超过该数字范围，示例如下
2.版本 2.5

## example

select bitmap_to_string(bitmap_agg(dwd_dim_one_id.hash_code)) from dwd_dim_one_id where hash_code in (9223524362489283035,9223524362489283034); 
得到的结果值如下
[-9223219711220268582,-9223219711220268581]

**Comment by trueeyu** [comment]
I will fix it

**Comment by trueeyu** [comment]
This is one bug of bitmap_to_string.
