### ISSUE TITLE
[BUG] dbv cannot use mysql driver 8

### ISSUE THREAD

**Issue by nmgliangwei** [StarRocks/starrocks#37206]
### Steps to reproduce the behavior (Required)
1. dbv version:10.0.27  use mysql jdbc dirver version: 8.0.33 8.0.11 8.0.22 8.0.19 
2. SELECT  xxx from xxx

### Expected behavior (Required)

Normal return results

### Real behavior (Required)
<img width="440" alt="image" src="https://github.com/StarRocks/starrocks/assets/7336263/b19b2edf-bfa6-42d9-8d82-8e2f12ef9e12">

### StarRocks version (Required)
 3.2-rc1

**Comment by Astralidea** [comment]
I simply tested it, and it seems that it is due to a long period of non-connection or fe restart and the connection failed. As long as the user clicks reconnect again, it can be used normally.
Are you still unable to connect after clicking reconnect?

**Comment by nmgliangwei** [comment]
@Astralidea Yes, I still can’t connect after clicking Reconnect.

**Comment by nmgliangwei** [comment]
Execute sql once and a reconnection window pops up.

**Comment by Astralidea** [comment]
Is it convenient to add WeChat to view remotely?

**Comment by nmgliangwei** [comment]
WeChat ID has been sent to your email（163）。

**Comment by Astralidea** [comment]
hi，@nmgliangwei I used a new driver to reproduce your problem. It was because I used the default driver version 5 that it did not reproduce. Let me see the reason first.

**Comment by nmgliangwei** [comment]
@Astralidea  Okay, 5.1.x In some environments, it may be impossible to return for a long time. Manually adding limit can return normally.   if necessary, we can reproduce remotely via weichat.

**Comment by Astralidea** [comment]
We have found out the reason for this problem, which is caused by the substandard support of COM_STMT_PREPARE. We will submit a PR later to fix this problem.
