### ISSUE TITLE
`show resource groups all` need display `default_wg` and `default_mv_wg`

### ISSUE THREAD

**Issue by Jin-H** [StarRocks/starrocks#37297]
## Feature request

**Is your feature request related to a problem? Please describe.**

Now, StarRocks have two default resource groups, but we can not find any information when execute statement `show resource groups all`.

```log
StarRocks > show resource groups all;
Empty set (13.53 sec)

StarRocks > 
```

**Describe the solution you'd like**

I think we can view the default resource group, but deletion is not allowed. We can also use the alter statement to modify the materialized view default resource group.

**Describe alternatives you've considered**

* `show resource groups all` display default_wg and default_mv_wg
* `show resource group default_wg` show resource group info
* `drop resource group default_wg` throws ddl exception as we can not drop default mv
* `alter resource group default_wg` throws ddl exception as we can not modify default mv
* `alter resource group default_mv_wg` can be success.

**Additional context**

**Comment by Jin-H** [comment]
@QingdongZeng3 Do you think this is reasonable? Do you have any ideas?

**Comment by mofeiatwork** [comment]
it's a good idea, we should support it
