### ISSUE TITLE
In the bitmap_from_string function of StarRocks, the documentation description and code implementation are inconsistent

### ISSUE THREAD

**Issue by MrLevo520** [StarRocks/starrocks#37306]
The documentation requires uint32 type numbers, but from the core code and practical tests, it seems that numbers can exceed the uint32 type.

![企业微信截图_7e95ce92-f387-4ba2-b65e-50ed9cbaff79](https://github.com/StarRocks/starrocks/assets/20299815/06035930-8277-4648-bf64-7716bb42718a)

![企业微信截图_67e493ec-67cd-4da3-aac1-eb16214d386a](https://github.com/StarRocks/starrocks/assets/20299815/df1dd506-d76d-461d-a263-f224b68a177b)

**Comment by imay** [comment]
@MrLevo520 could you submit a PR to fix the document?

**Comment by MrLevo520** [comment]
> @MrLevo520 could you submit a PR to fix the document?
It would be my pleasure. If you could also help me check whether issue #37311 has the same problem, I would be very grateful. I will submit a PR later to fix both issues at the same time.
