### ISSUE TITLE
docker build no version

### ISSUE THREAD

**Issue by clcc2019** [StarRocks/starrocks#3737]
<img width="566" alt="image" src="https://user-images.githubusercontent.com/46099295/156084172-c6702402-b02e-4036-8423-964639bb7231.png">

use source v2.1.0  build in docker

**Comment by wangruin** [comment]
Thanks for your feedback, the version needs to be set when you compile, like this `STARROCKS_VERSION="branch-2.1" ./build.sh --fe --be`

**Comment by clcc2019** [comment]
> Thanks for your feedback, the version needs to be set when you compile, like this `STARROCKS_VERSION="2.1.0" ./build.sh --fe --be`

Use the command:
```shell
STARROCKS_VERSION="2.1.1";
./build.sh --fe --be
```
built starrocks, but no version number
Version: UNKNOWN-
