### ISSUE TITLE
starrocks用户交流群

### ISSUE THREAD

**Issue by Gensiss** [StarRocks/starrocks#3743]
starrocks使用中碰到很多问题，方便大家互惠互通，不知道官方让不让搞

starrocks用户交流群
wx：damaiplus
备注：starrocks用户

**Comment by Johnsonginati** [comment]
Hi Gensiss, there are many ways to get in touch with others to solve the problem when using StarRocks, such as slack, WeChat, and forum.
If you want to join, I can show you the way.
