### ISSUE TITLE
LakeTablet cannot be cast to LocalTablet

### ISSUE THREAD

**Issue by sergeyshaykhullin** [StarRocks/starrocks#37462]
### Steps to reproduce the behavior (Required)

1.
```sql
CREATE TABLE `table` (
  `c1` date NOT NULL COMMENT "",
  `c2` varchar(2048) NOT NULL COMMENT "",
  `c3` int(11) NULL COMMENT "",
  `c4` int(11) NULL COMMENT "",
  `c5` int(11) NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`c1`, `c2`)
COMMENT "OLAP"
PARTITION BY date_trunc('day', c1)
DISTRIBUTED BY HASH(`c2`)
PROPERTIES (
"replication_num" = "1",
"datacache.enable" = "true",
"storage_volume" = "builtin_storage_volume",
"enable_async_write_back" = "false",
"enable_persistent_index" = "false",
"compression" = "LZ4"
);
```

2. Insert some data

3.
```sql
ALTER TABLE table COMPACT;
```

### Expected behavior (Required)
Perform compaction

### Real behavior (Required)

`
SQL Error [1064] [42000]: Unexpected exception: class com.starrocks.lake.LakeTablet cannot be cast to class com.starrocks.catalog.LocalTablet (com.starrocks.lake.LakeTablet and com.starrocks.catalog.LocalTablet are in unnamed module of loader 'app')
`

### StarRocks version (Required)
3.1.6-fcc0c6b

**Comment by abc982627271** [comment]
already fixed, pr : https://github.com/StarRocks/starrocks/pull/36979

**Comment by abc982627271** [comment]
https://github.com/StarRocks/starrocks/pull/36979
