### ISSUE TITLE
Enhancement: Support Catalog Classloader Isolation in FE

### ISSUE THREAD

**Issue by JackWangCS** [StarRocks/starrocks#37510]
## Enhancement
FE should support Classloader isolation for catalogs.
* StarRocks now supports many catalogs, but does not isolate these classes from different catalogs.
* For each catalog, It's a common requirement to support different versions of external systems. For example, different JDBC Catalogs use different versions of mysql Drivers.  

If Catalogs are not isolated, it will result some unexpected exceptions in some cases.

**Comment by imay** [comment]
Would you like to contribute to improve it?

**Comment by JackWangCS** [comment]
> Would you like to contribute to improve it?

Yeah, I'd like to. I thinks this is a big enhancement for SR, I would like to hear more from community and work together on it.
