### ISSUE TITLE
unable to load file from s3 with path containing equals sign

### ISSUE THREAD

**Issue by ftong2020** [StarRocks/starrocks#37681]
### Steps to reproduce the behavior (Required)
create some primary key table.

create a load job.

> LOAD LABEL some_db.some_primary_key_table_load (
>     DATA INFILE("s3://data_bucket/some/data/path/date=2023-12-23/*")
>     INTO TABLE some_primary_key_table 
>     FORMAT AS "parquet"
>  )
>  WITH BROKER
>  (
>     "aws.s3.enable_ssl" = "true",
>     "aws.s3.enable_path_style_access" = "true",
>     "aws.s3.use_instance_profile" = "false",
>     "aws.s3.region" = "your_region",
>     "aws.s3.endpoint" = "https://your.s3.provider",
>     "aws.s3.access_key" = "aaaaa",
>     "aws.s3.secret_key" = "bbbbbb"
>  )
> PROPERTIES ( "timeout" = "7200");

### Expected behavior (Required)
Loading job should succeed.

### Real behavior (Required)
Loading job seems to be able to list file, but unable to get them. Http Code 403 is returned by object store provider.

Run `show load` command, and the job complains that "type:LOAD_RUN_FAIL; msg:IOError: BE access S3 file failed, SdkResponseCode=403, SdkErrorType=15, SdkErrorMessage=No response body."

This only happens when s3 file path contains equals sign(=). If files are loaded from paths with out equals sign, it will proceed as expected.

The job actually correctly count files of the job. In job details, it shows "{"All backends":{"xxxxxxxxxxxxxxxx":[606072,637531,637533,637532,637534]},"FileNumber":5,"FileSize":2192348303,"InternalTableLoadBytes":0,"InternalTableLoadRows":0,"ScanBytes":0,"ScanRows":0,"TaskNumber":1,"Unfinished backends":{"xxxxxxxxxxxxxxxx":[]}}"

This behavior seems to be related to "insert into files()" feature, too. When partition feature is enabled during insert, CN will complain  that s3 signature is invalid during file upload(put).

### StarRocks version (Required)
3.2.1, running in shared-data mode.

**Comment by rvk16** [comment]
Hi do we have any resolution on it ?
