### ISSUE TITLE
backup 空表时会一直SNAPSHOTING

### ISSUE THREAD

**Issue by liangkiller** [StarRocks/starrocks#3771]
备份到阿里云的oss库，如果表里有空表，会一直在SHAPSHOTING状态
### Steps to reproduce the behavior (Required)
1. CREATE TABLE IF NOT EXISTS `lineorder_flat` (
  `LO_ORDERKEY` int(11) NOT NULL COMMENT "",
  `LO_ORDERDATE` date NOT NULL COMMENT "",
  `LO_LINENUMBER` tinyint(4) NOT NULL COMMENT "",
  `LO_CUSTKEY` int(11) NOT NULL COMMENT "",
  `LO_PARTKEY` int(11) NOT NULL COMMENT "",
  `LO_SUPPKEY` int(11) NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`LO_ORDERKEY`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`LO_ORDERKEY`) BUCKETS 192
PROPERTIES (
"replication_num" = "1",
"colocate_with" = "groupxx1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
 ### Expected behavior (Required)
BACKUP SNAPSHOT  test.lineorder_flat TO test_repo ON (lineorder_flat);

### Real behavior (Required)
show backup;

State: SNAPSHOT

### StarRocks version (Required)
版本 2.0

**Comment by DeepThinker666** [comment]
hi, thank you for your issue.
I use starrocks 2.0-GA to reproduce the process. I can get a success in backup the empty table.

![image](https://user-images.githubusercontent.com/89860388/156556901-c3659e82-9c49-45c7-bc6e-61915b743771.png)

**Comment by DeepThinker666** [comment]
I think you can take a look at the fe.log to check whether there is any warning or error logs.
Maybe there is something wrong with your broker?
