### ISSUE TITLE
DISTINCT does not work on the final select of scalar values

### ISSUE THREAD

**Issue by AsaiWiz** [StarRocks/starrocks#37878]
In a CTE query like
with cte1 as ( select scalar_col_1, scalar_col2, json_col_1 from tables)
, cte2 as (select scalar_col_1, extract_scalar_from_json_col_1 as scalar_col_11 from cte1)
select distinct  scalar_col_1,scalar_col_11 from cte2
gives error: DISTINCT can only be applied to comparable types : JSON.
at the time I apply distinct there is no json.

**Comment by kangkaisen** [comment]
OK， we will check and fix this issue

**Comment by AsaiWiz** [comment]
👎
