### ISSUE TITLE
Routine Load + kafka ，使用java和python发送topic消息中日期字符串格式问题

### ISSUE THREAD

**Issue by wcp1230** [StarRocks/starrocks#3788]
场景一：
 使用java开发发送topic消息时，消息内容如下：
'2018-01-01 23:00:00',201,1210814
表字段：
dt DATETIME NOT NULL comment  '时间',
表类型：
DUPLICATE KEY(dt）

场景二：
使用python 3.9.5 发送消息时，消息内容如下：
'2018-01-01 23:00:00',201,1210814
表字段：
dt DATETIME NOT NULL comment  '时间',
表类型：
UNIQUE KEY(dt)

日期字符串对应SR中日期（DATETIME）字段；

问题：
在python 中使用场景二方式发送消息，SR的Routine Load任务中，报如下错误：
   Reason: null value for not null column, column=dt. src line: []; 

解决方式：
   把场景二中日期字符串两边的单引号去掉后，就能正常导入

请问为什么在两种开发语言中存在差异？

### StarRocks version (Required)
 SR版本：2.0.1，kafka 2.13-3.1.0

**Comment by imay** [comment]
seems it is not the StarRocks reason. No matter which language you use, you should make sure data send to StarRocks should be the format without `'`. 
You can print and check the content python send. I suppose that there will be an enclosed `'`.
