### ISSUE TITLE
Asynchronous materialized view refresh failure caused by rebuilding the iceberg table

### ISSUE THREAD

**Issue by chengyi3192** [StarRocks/starrocks#37885]
### Steps to reproduce the behavior (Required)
Firstly, I created two tables with associated relationships on Iceberg.

Subsequently, asynchronous materialized views were successfully created through starrocks.

But when the iceberg table is deleted and the same table is immediately recreated, the asynchronous materialized view will prompt that the table in the iceberg does not exist when it is refreshed asynchronously.

create mv sql 
```sql
CREATE MATERIALIZED VIEW `audit_project_width3` (`rowguid`, `operatedate`, `taskid`, `areacode`, `ouname`, `operateusername`, `taskname`, `cr_date`)
DISTRIBUTED BY RANDOM
REFRESH ASYNC EVERY(INTERVAL 1 HOUR)
PROPERTIES (
"replicated_storage" = "true",
"replication_num" = "1",
"storage_medium" = "HDD"
)
AS SELECT `audit_task_1`.`rowguid`, `audit_task_1`.`operatedate`, `audit_project_1`.`taskid`, `audit_project_1`.`areacode`, `audit_project_1`.`ouname`, `audit_project_1`.`operateusername`, `audit_task_1`.`taskname`, current_date() AS `cr_date`
FROM `iceberg_catalog_122`.`iceberg`.`audit_project` AS `audit_project_1` LEFT OUTER JOIN `iceberg_catalog_122`.`iceberg`.`audit_task` AS `audit_task_1` ON `audit_project_1`.`taskguid` = `audit_task_1`.`rowguid`;
```

![image](https://github.com/StarRocks/starrocks/assets/52986451/74ea6ba4-5623-4000-91e8-79aa3e83b930)

### Expected behavior (Required)
Successfully created materialized view

### Real behavior (Required)
Prompt that the iceberg table does not exist

### StarRocks version (Required)
3.1.4-0c4b2a3

**Comment by mofeiatwork** [comment]
as a workaround, you could inactive and active the MV:
1. `alter materialized view xxx inactive`
2. `alter materialized view xxx active`
