### ISSUE TITLE
Materialized View on CTE queries

### ISSUE THREAD

**Issue by AsaiWiz** [StarRocks/starrocks#37881]
## Enhancement
CTE queries are a very common method of extracting data from tables and it is used extensively. 
The results of such queries being set up as materialized view is extremely valuable.
Currently a statemnet like 
create materialized view text_met_vw as (with cte1 as ( select scalar_col_1, scalar_col2, json_col_1 from tables)
, cte2 as (select scalar_col_1, extract_scalar_from_json_col_1 as scalar_col_11 from cte1)
select distinct  scalar_col_1,scalar_col_11 from cte2 )

gives 
SQL Error [1064] [42000]: Getting analyzing error. Detail message: Materialized view query statement only support select.

an enhancement to support CTE queries in materialized view is inevitable need for data analytics.

**Comment by mofeiatwork** [comment]
implemented by #36142
