### ISSUE TITLE
FE is not able to start on linux after system reboot (manual installation)

### ISSUE THREAD

**Issue by stalek71** [StarRocks/starrocks#37930]
I performed the installation on Linux Ubuntu according to the documentation describing manual deployment. 
The files `be.conf` and `fe.conf` contain information that enables the launch of the respective services, and when I start and stop the services from the command line through direct use of `start/stop_x.sh` scripts or through `sudo systemctl start starrocks.fe/be`, everything works as expected. 
The problem starts when I manually stop the services (so to be sure I do it safe manner) and then do a system reboot.
After that, the FE service is unable to start properly and continuously displays the message below:

`2023-12-27 13:54:19,380 INFO (UNKNOWN 192.168.1.16_9010_1703247090563(-1)|1) [GlobalStateMgr.waitForReady():1206] wait globalStateMgr to be ready. FE type: INIT. is ready: false`

Below is the file with the definition of the fe service (I also tested a version with the --daemon parameter and stop commands for the forking type):
```
[Unit]
Description=StarRocks DB Frontend Service
After=starrocks.be.service

[Service]
Environment="JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"
ExecStart=/opt/starrocks/current/fe_artifacts/fe/bin/start_fe.sh
Type=simple
User=starrocks

[Install]
WantedBy=multi-user.target
```

Sometimes I also get the message below:

`2023-12-27 14:13:52,334 WARN (heartbeat mgr|14) [HeartbeatMgr.runAfterCatalogReady():164] get bad heartbeat response: type: BACKEND, status: BAD, msg: FE saved address not match backend address`

After stopping BE and restarting it, BE works properly.

The only solution is to use `metadata_failure_recovery=true` after every restart, but that's not something you can expect from a reliable service...

### StarRocks version (Required)
`3.2.1-79ee91d`

**Comment by kevincai** [comment]
please check  if your host has multiple network interfaces, and if the FE can detect the right ip address to use. If so, please use `priority_networks` for both fe.conf and be.conf. check https://docs.starrocks.io/docs/administration/Deployment/#deploy-a-fe-ha-cluster for some explanations on `priority_networks` configuration item.

**Comment by stalek71** [comment]
It has loopback and ether interfaces only. Both priority networks have the same definition:
`priority_networks = 192.168.1.0/24;127.0.0.1/32`
The host has `192.168.1.16/24` ip addr

**Comment by stalek71** [comment]
Maybe the issue is it should be dependent on some other specific services yet?
When I start it manually (using starrocks user account as well) it's able to start without any problems.
The only difference is the host started all the services already...

**Comment by stalek71** [comment]
Strange it's doesn't start stable/predictable way when I enable services for them and reboot the host.
I added 127.0.0.1 only for the test case when FE was complaining that `localhost` is not a registered ip FE expects.
It means BE **_somehow_** is able to start on loopback instead on ether (0.0.0.0) interface...

**Comment by stalek71** [comment]
When I stop BE and start it again it starts on 0.0.0.0 as expected (so with 192.168.0.16 ip addr)

**Comment by stalek71** [comment]
It looks the missing dependency is like below:

```
Wants=network-online.target
After=network-online.target
```

**Comment by stalek71** [comment]
It works now so the issue can be closed.
