### ISSUE TITLE
max() function is not supported self define start row in window funcition

### ISSUE THREAD

**Issue by gholay** [StarRocks/starrocks#3796]
## Enhancement
![image](https://user-images.githubusercontent.com/4527271/156490689-261dc4a3-c687-42fc-a63a-96061efeb4ce.png)

**Comment by trueeyu** [comment]
currently not supported, we will support it right away

**Comment by gholay** [comment]
> currently not supported, we will support it right away

Thanks for supporting max function . and could you support min function with specific start row as well ?

**Comment by gholay** [comment]
thanks
