### ISSUE TITLE
Whether to support continuous asynchronous loading using Pipe from Apache Paimon‘s table on s3?

### ISSUE THREAD

**Issue by yfcck** [StarRocks/starrocks#38247]
Only supports a single parquet file？

```
CREATE PIPE user_behavior_replica
PROPERTIES
(
    "AUTO_INGEST" = "TRUE"
)
AS
INSERT INTO user_behavior_replica
SELECT * FROM FILES
(
    "path" = "s3://starrocks-datasets/user_behavior_ten_million_rows.parquet",   //  if it is partitioned and bucketed table?
    "format" = "parquet",
    "aws.s3.region" = "us-east-1",
    "aws.s3.access_key" = "AAAAAAAAAAAAAAAAAAAA",
    "aws.s3.secret_key" = "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
); 
```

**Comment by mofeiatwork** [comment]
PIPE is not aware of any table format, it only list file in the directory and load the changed file into table.

But the extensible point is how to list file:
- currently it's based on the `S3 list objects`, which work for common case, but not efficient enough for Paimon/Iceberg like table format
- it could be extended to file manifest, which could be more efficient

It's on the roadmap but not urgent until we see some promising use cases.

**Comment by mofeiatwork** [comment]
BTW, if you want to incremental load data from Lake into SR, you could consider the MaterializedView.

**Comment by wnnlyf** [comment]
> BTW, if you want to incremental load data from Lake into SR, you could consider the MaterializedView.

ths!
