### ISSUE TITLE
Support Iceberg custom catalog

### ISSUE THREAD

**Issue by DorianZheng** [StarRocks/starrocks#3826]
## Feature request
Support Iceberg custom catalog so that users can build their own catalog to store metadata of Iceberg
related with https://github.com/StarRocks/starrocks/issues/1030

**Comment by caneGuy** [comment]
please assign this to me thanks

**Comment by mxdzs0612** [comment]
I'll take it, pls assign to me.

**Comment by caneGuy** [comment]
thanks @mxdzs0612
