### ISSUE TITLE
command 'SHOW RUNNING QUERIES' return more information

### ISSUE THREAD

**Issue by MatthewH00** [StarRocks/starrocks#38468]
## Enhancement
v3.1.4+，command 'SHOW RUNNING QUERIES'，base current return result，hope  reutrn more information，as follow:
1.querysql
2.ResourceGroupName
3.task submit user
4.client ip
5.database
6.ScanBytes
7.ScanRows
8.MemoryUsage
9.DiskSpillSize
10.CPUTime
11.ExecTime
12.Query progress%
and more information related to query task，it will easy to monitor query task. 
It is better to offer a http api.

**Comment by MatthewW00** [comment]
11.client ip
