### ISSUE TITLE
 The broker load import data contains an IF statement, but IF does not take effect

### ISSUE THREAD

**Issue by goodqiang** [StarRocks/starrocks#38500]
### Steps to reproduce the behavior (Required)
建表语句
 CREATE TABLE `province_test` (
  `province_id` int(11) NULL COMMENT "省ID",
  `province_name` varchar(64) NULL COMMENT "省Name",
  `city_id` int(11) NULL COMMENT "市ID",
  `city_name` varchar(64) NULL COMMENT "市Name"
) ENGINE=OLAP 
AGGREGATE KEY(`province_id`, `province_name`, `city_id`, `city_name`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`province_id`, `city_id`) BUCKETS 10 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"compression" = "LZ4"
); 

导入数据：test
14      福建省  139     莆田市
12      浙江省  112     宁波市
18      湖北省  197     潜江市
13      安徽省  125     淮北市
11      江苏省  102     南通市
23      四川省  248     成都市
29      宁夏    315     银川市
2       上海市  0       全部
1       北京市  0       全部
3       天津市  0       全部

导入命令
LOAD LABEL test.province_test2225
(
  DATA INFILE ("hdfs://xxxxx:9000/xxxx/test")
  INTO TABLE province_test 
  COLUMNS TERMINATED BY "\t" (
    province_id,
    province_name,
    city_id,
    city_name
    )
  SET
  ( province_id=province_id,
    province_name=province_name,
    city_id=city_id,
    city_name=IF ((province_id>=1 AND province_id<=3) OR province_id=13, province_name, city_id)
    )
    )WITH BROKER broker_hdfs
(
  "username"="",
  "password"=""
)
PROPERTIES
(
  "load_mem_limit"="2147483648",
  "strict_mode"="false",
  "max_filter_ratio"="0",
  "timeout"="14400"
);

### Expected behavior (Required)
![image](https://github.com/StarRocks/starrocks/assets/86873587/fbad71ca-1aa8-49d2-8f2c-fc2ecf17073e)
select province_id,province_name,city_id,city_name from province_test;
+-------------+---------------+---------+-----------+
| province_id | province_name | city_id | city_name |
+-------------+---------------+---------+-----------+
|          18 | 湖北省        |     197 | 湖北省    |
|           2 | 上海市        |       0 | 上海市    |
|          29 | 宁夏          |     315 | 315       |
|          14 | 福建省        |     139 | 福建省    |
|          23 | 四川省        |     248 | 248       |
|          11 | 江苏省        |     102 | 江苏省    |
|          12 | 浙江省        |     112 | 浙江省    |
|           1 | 北京市        |       0 | 北京市    |
|          13 | 安徽省        |     125 | 安徽省    |
+-------------+---------------+---------+-----------+

### Real behavior (Required)
select province_id,province_name,city_id,city_name from province_test;
+-------------+---------------+---------+-----------+
| province_id | province_name | city_id | city_name |
+-------------+---------------+---------+-----------+
|          18 | 湖北省        |     197 | 197    |
|           2 | 上海市        |       0 | 上海市    |
|          29 | 宁夏          |     315 | 315       |
|          14 | 福建省        |     139 | 139|
|          23 | 四川省        |     248 | 248       |
|          11 | 江苏省        |     102 | 102   |
|          12 | 浙江省        |     112 | 112    |
|           1 | 北京市        |       0 | 北京市    |
|          13 | 安徽省        |     125 | 安徽省    |
+-------------+---------------+---------+-----------+
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
+-------------------+
| current_version() |
+-------------------+
| 2.5.16 82f76a9    |
+-------------------+
1 row in set (0.00 sec)

**Comment by rickif** [comment]
I'll troubleshoot the problem.
