### ISSUE TITLE
Unable to create materialized views for tables with string partitions in the hive external catalog

### ISSUE THREAD

**Issue by qian0817** [StarRocks/starrocks#38541]
### Steps to reproduce the behavior (Required)
```sql
CREATE TABLE t1(col1 int) PARTITIONED BY(pt_d string); --in hive
CREATE MATERIALIZED VIEW default_catalog.hiveviewtestdb.test_mv_1
PARTITION BY (pt_d) 
DISTRIBUTED BY HASH(pt_d) 
REFRESH ASYNC START ('2024-01-05 11:20:00') every (interval 10 minute) 
AS SELECT * FROM t1;
```
### Expected behavior (Required)
can create Materialized view.

### Real behavior (Required)
ERROR 1064 (HY000): Unexpected exception: List partition columns must not be nullable in Materialized view for now.
can not create Materialized view.

### StarRocks version (Required)
 - StarRocks version: 3.2.2
 - Hive version: 2.3.8

**Comment by LiShuMing** [comment]
List partitions for MV is not supported yet. but if the string partition value can be converted to date, you can try `str2date` like example4:
https://docs.starrocks.io/docs/sql-reference/sql-statements/data-definition/CREATE_MATERIALIZED_VIEW/#examples-of-asynchronous-materialized-views
