### ISSUE TITLE
be启动coredump

### ISSUE THREAD

**Issue by icedrugs89** [StarRocks/starrocks#3860]
centos系统安装的StarRocks-2.1.1版本，fe程序启动没问题，be程序启动报错
使用gdb调试生成的coredump文件，命令如下：
gdb ../lib/starrocks_be   core.10674结果如下：
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/100941547/156763949-c6ef19d0-10e8-43c7-8b72-cd6d719a7f6a.png">
能不能帮忙看下是什么原因呢，调试信息也不够清楚

### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by stdpain** [comment]
It seems your machine not support AVX2 instruction
please run `cat /proc/cpuinfo |grep avx2` and see output

**Comment by icedrugs89** [comment]
1、不支持AVX2的cpu，需要使用docker容器去掉AVX2 版本编译源码验证可以启动
2、使用支持AVX2的cpu，直接使用官方提供的编译好的版本
