### ISSUE TITLE
AMV is failing to refresh after one of the source tables re-created

### ISSUE THREAD

**Issue by mcgray** [StarRocks/starrocks#38764]
When creating AMV on top of tables/views that are by some business reasons being re-created (with the same name) AMV is failing during refresh. 

### Steps to reproduce the behavior (Required)
1. Create AMV on top of an arbitrary table
2. Fill in some data into source table
3. Re-create source table, fill in some more data

### Expected behavior (Required)
AMV is successfully updated

### Real behavior (Required)
AMV update is failing with an error similar to:
`com.starrocks.sql.common.DmlException: Materialized view base table: 64327.10764074 not exist.`

### StarRocks version (Required)
3.1

**Comment by mofeiatwork** [comment]
https://github.com/StarRocks/starrocks/pull/38008
