### ISSUE TITLE
Failed to build starrocks with --use-staros on physical machine

### ISSUE THREAD

**Issue by 1153710405** [StarRocks/starrocks#38805]
I tried to build starrocks on an ARM physical machine and encountered the following problem. It seems that the thirdparty starlet is missed. From thirdparty/build-thirdparty.sh and thirdparty/vars.sh, starlet is not included in both the build list and the download list. So there is no way that starlet can be automatically downloaded and installed.

### Steps to reproduce the behavior (Required)
./build.sh --be --use-staros
### Expected behavior (Required)
Success
### Real behavior (Required)

CMake Error at CMakeLists.txt:436 (message):
     Starlet thirdparty directory
     /home/starrocks-3.1.4/thirdparty/installed/starlet not exist!

### StarRocks version (Required)
3.1.4

**Comment by kevincai** [comment]
part of shared data related code is delivered as thirdparty in dev-env docker image, if you want to rebuild from scratch on physical machine, please find the correct dev-env docker image and copy `/var/local/thirdparty/installed/starlet/` into your physical machine under `starrocks/thirdparty/installed/starlet/`

**Comment by kevincai** [comment]
solved. Related to BE/CN JAVA_HOME setting.

close it.
