### ISSUE TITLE
Starrocks Can I use catalog to query ClickHouse? If so, what should I do?

### ISSUE THREAD

**Issue by szy833** [StarRocks/starrocks#38890]
## Feature request

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alberttwong** [comment]
Currently no.   I would export the data and then import into StarRocks.  Another option is to use Apache Flink 3.0 CDC to move the data from Clickhouse to StarRocks.

**Comment by Dshadowzh** [comment]
The feature is supported. You can find more details at https://github.com/StarRocks/starrocks/pull/42930.
