### ISSUE TITLE
parser sql error

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#3895]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS w99;
CREATE DATABASE w99;
USE w99;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 BOOLEAN NOT NULL ,c_0_1 DATE NOT NULL ,c_0_2 PERCENTILE PERCENTILE_UNION NULL ,c_0_3 FLOAT REPLACE_IF_NOT_NULL NOT NULL ,c_0_4 DECIMAL(32, 8)  SUM NOT NULL ,c_0_5 BOOLEAN REPLACE NOT NULL ,c_0_6 FLOAT REPLACE_IF_NOT_NULL NULL ,c_0_7 BOOLEAN REPLACE NOT NULL ,c_0_8 DOUBLE SUM NOT NULL ) AGGREGATE KEY (c_0_0,c_0_1) DISTRIBUTED BY HASH (c_0_0,c_0_1) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 VARCHAR(21) NOT NULL ,c_1_1 BOOLEAN NOT NULL ,c_1_2 DECIMAL(32, 12)  NULL ,c_1_3 DECIMAL(5, 0)  NOT NULL ,c_1_4 DATE NOT NULL ,c_1_5 DECIMAL(15, 0)  NOT NULL ,c_1_6 DECIMAL(19, 17)  NULL ,c_1_7 DATETIME REPLACE NOT NULL ,c_1_8 DOUBLE MAX NULL ,c_1_9 DATE MIN NOT NULL ,c_1_10 DATE REPLACE_IF_NOT_NULL NULL ,c_1_11 CHAR(21) REPLACE_IF_NOT_NULL NULL ,c_1_12 HLL HLL_UNION NOT NULL ,c_1_13 DATE REPLACE NULL ,c_1_14 FLOAT MIN NOT NULL ,c_1_15 HLL HLL_UNION NOT NULL ,c_1_16 DECIMAL(2, 0)  REPLACE NOT NULL ,c_1_17 PERCENTILE PERCENTILE_UNION NOT NULL ,c_1_18 DECIMAL(16, 7)  REPLACE NOT NULL ) AGGREGATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6) DISTRIBUTED BY HASH (c_1_6,c_1_0,c_1_4,c_1_2,c_1_5) properties("replication_num"="3") ;
INSERT INTO t0 VALUES (false, "1970-01-01", percentile_hash("472141185"), 0.36106049664367557, 3903270608517921.40290313, true, 0.9618571213741992, true, 0.12342305392330222), (true, "1970-01-01", percentile_hash("-9223372036854775808"), 0.9618571213741992, 3814234804573892.74598814, true, 0.7272386506868256, false, 0.46861330975562876), (true, "1970-01-01", percentile_hash("-328716925"), 0.961138705924982, 9179101139518728.30291566, true, 0.19945052899036697, true, 4.72141185E8);
INSERT INTO t0 VALUES (false, "1970-01-01", percentile_hash("-328716925"), 0.15352895677920997, 1675115330950269.76603131, false, NULL, false, 0.9768078911990955), (false, "1970-01-01", percentile_hash("1156955738"), 0.3996836802190237, 8389233193587877.22422789, true, 0.42591247349828776, false, 0.6292705471062816);
INSERT INTO t1 VALUES ("", true, 26171490.446741486952, 1000, "1970-01-01", 852586175145842, 2.8E-16, "1970-01-01 08:00:00", 0.12342305392330222, "1970-01-01", "1970-01-01", "PgdmMTR", hll_hash("JP"), "1970-01-01", 0.744497605527635, hll_hash("1gR"), 68, percentile_hash("1742900779"), 83.5838804);
INSERT INTO t0 VALUES (true, "1970-01-01", percentile_hash("306902014"), 0.5509352839268539, 4099411995933444.07504975, true, 0.6612988156490568, true, 0.3312404022124861);
INSERT INTO t0 VALUES (false, "1970-01-01", percentile_hash("1354385711"), 0.6943707882950748, 6767111031912911.30117944, false, 0.5410471506358701, false, 0.39879668115327827), (true, "1970-01-01", percentile_hash("543727663"), 0.32424389950491883, 5874583176281795.71603617, false, 0.1596211886909431, true, -1.7976931348623157E308), (false, "1970-01-01", percentile_hash("1742900779"), 0.09027908994554068, 9555167131928321.56733505, false, 0.7199420057077359, false, 0.821002298156296);
INSERT INTO t1 VALUES ("ntH", true, 2709033.269837325076, 94307, "1970-01-01", 153819426358611, 6.0E-16, "1970-01-01 08:00:00", 0.71930781208834, "1970-01-01", "1970-01-01", NULL, hll_hash(""), "1970-01-01", 0.018711926632661302, hll_hash("9s"), 40, percentile_hash("-269709655"), 61.3423420), ("Q", false, 40973511.157340746380, 96564, "1970-01-01", 966748136722831, 3.5E-16, "1970-01-01 08:00:00", -3.28716925E8, "1970-01-01", "1970-01-01", "3", hll_hash("XPh"), "1970-01-01", 0.8769183621077501, hll_hash("9Er0j"), 44, percentile_hash("406449981"), 1.1203490);
INSERT INTO t1 VALUES ("vTz", true, 8117935.179817246568, 48649, "1970-01-01", 592761397239881, 9.0E-16, "1970-01-01 08:00:00", 0.006564307819933224, "1970-01-01", "1970-01-01", "h9J", hll_hash(""), "1970-01-01", -2.69709655E8, hll_hash("LTCCWO8"), 1, percentile_hash("1354385711"), 37.3002977), ("", true, 60802905.537056428359, 95673, "1970-01-01", 765260906823616, 5.4E-16, "1970-01-01 08:00:00", 0.6844851197968739, "1970-01-01", "1970-01-01", "", hll_hash("hqmRK"), "1970-01-01", 0.39262273558251815, hll_hash("1M"), 35, percentile_hash("2130152047"), 85.1586594), ("", true, 38109187.016171091179, 42149, "1970-01-01", 608118398500006, 6E-17, "1970-01-01 08:00:00", NULL, "1970-01-01", "1970-01-01", "o", hll_hash(""), NULL, 0.15753318869753086, hll_hash(""), 19, percentile_hash("1180489039"), 8.5482729);
INSERT INTO t0 VALUES (true, "1970-01-01", percentile_hash("-1641380624"), 0.5217943792016095, 7693353284110493.46194990, false, NULL, false, 0.9229004721653943), (false, "1970-01-01", percentile_hash("-1692012212"), 1.180489039E9, 4494366376979748.16777937, false, NULL, true, 1.742900779E9);
INSERT INTO t1 VALUES ("s53M", false, 23455244.390183770661, 76281, "1970-01-01", 173094431348748, 5.6E-16, "1970-01-01 08:00:00", 0.39262273558251815, "1970-01-01", "1970-01-01", NULL, hll_hash("9"), "1970-01-01", 0.07736054869093079, hll_hash("h7X"), 70, percentile_hash("-1440948676"), 18.4658814), ("f", true, 14638357.391779092868, 87533, "1970-01-01", 87718745303051, 1E-17, "1970-01-01 08:00:00", 0.9718126397264383, "1970-01-01", "1970-01-01", NULL, hll_hash(""), "1970-01-01", 0.8823880899413168, hll_hash("1hJ"), 42, percentile_hash("1354385711"), 73.6305133);
DELETE FROM t1 WHERE c_1_2=27383797.504711324889 AND c_1_4="1970-01-18" AND c_1_0="j3uC5" AND c_1_6=1.1E-16 AND c_1_5=220265728942782 AND c_1_3=NULL AND c_1_1=false;
2. mysql> SELECT t0.c_0_0, RANK(t0.c_0_2) OVER ( PARTITION BY t0.c_0_8, t0.c_0_1, t0.c_0_7, t0.c_0_3, t0.c_0_5, t0.c_0_4, t0.c_0_0, t0.c_0_2, t0.c_0_6 ORDER BY t0.c_0_8)  FROM t0;
ERROR 1064 (HY000): mismatched input 't0' expecting ')'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - main ASAN
 - mysql> select current_version();
+------------------------------+
| current_version()            |
+------------------------------+
| SQLANCER_BRANCH_ASAN 3679598 |
+------------------------------+

**Comment by HangyuanLiu** [comment]
The rank function cannot have parameters, and there is no problem with parsing

**Comment by wanpengfei-git** [comment]
> The rank function cannot have parameters, and there is no problem with parsing

ok, the report error result is not same with branch-2.1, i will add this filter.
