### ISSUE TITLE
[schema auto-detection merge] when query file table function the data file has different semi struct type of parquet format, error

### ISSUE THREAD

**Issue by huoyue-git** [StarRocks/starrocks#38970]
### Steps to reproduce the behavior (Required)
```
select * from files("path" = "hdfs://xxx:xxx/xxx/nose-ut-data/table_function/parquet/schema_auto_merge/semi_struct_type/all/*",
                         "format" = "parquet",
                         "auto_detect_sample_files" = "1"
                          ) order by 1;
ERROR 1064 (HY000): Apache Arrow type (nested) map does not match the type ARRAY in StarRocks
```

### Expected behavior (Required)
query successfully
### Real behavior (Required)
query failed 
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+--------------------+
| current_version()  |
+--------------------+
| branch-3.2-689ebb4 |
+--------------------+
1 row in set (0.01 sec)

**Comment by rickif** [comment]
I think this is by design. When the inferred schema is different from the file schema and it cannot be converted implicitly, we should set `auto_detect_sample_files` larger to sample more files.
