### ISSUE TITLE
Failed to compile starrocks-3.1.4 with --use-staros on X86 platform

### ISSUE THREAD

**Issue by 1153710405** [StarRocks/starrocks#39055]
I tried to compile starrocks-3.1.4 with --use-staros on X86 platform. I downloaded the centos branch-3.1 docker image and cp /var/local/thirdparty/installed/starlet/ to /home/starrocks-3.1.4/thirdparty/installed/. However, there seems somethings wrong with starlet and the build failed as showed below.

### Steps to reproduce the behavior (Required)
./build.sh --be --use-staros

### Expected behavior (Required)
Compile success

### Real behavior (Required)
/home/starrocks-3.1.4/be/src/service/staros_worker.cpp: In static member function ‘static absl::lts_20220623::StatusOr<std::unordered_map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > > starrocks::StarOSWorker::build_conf_from_shard_info(const ShardInfo&)’:
/home/starrocks-3.1.4/be/src/service/staros_worker.cpp:337:86: error: ‘google::protobuf::int64 staros::FileCacheInfo::ttl_seconds() const’ is deprecated [-Werror=deprecated-declarations]
  337 |         conf[fslib::kCacheFsTtlSecs] = absl::StrFormat("%ld", cache_info.ttl_seconds());
      |                                                                                      ^
In file included from /home/starrocks-3.1.4/thirdparty/installed/starlet/starlet_install/include/starlet.pb.h:38,
                 from /home/starrocks-3.1.4/thirdparty/installed/starlet/starlet_install/include/starlet.grpc.pb.h:22,
                 from /home/starrocks-3.1.4/thirdparty/installed/starlet/starlet_install/include/service.h:20,
                 from /home/starrocks-3.1.4/thirdparty/installed/starlet/starlet_install/include/starlet.h:24,
                 from /home/starrocks-3.1.4/be/src/service/staros_worker.h:19,
                 from /home/starrocks-3.1.4/be/src/service/staros_worker.cpp:16:
/home/starrocks-3.1.4/thirdparty/installed/starlet/starlet_install/include/file_store.pb.h:6840:39: note: declared here
 6840 | inline ::PROTOBUF_NAMESPACE_ID::int64 FileCacheInfo::ttl_seconds() const {
      |                                       ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [src/service/CMakeFiles/Service.dir/build.make:118: src/service/CMakeFiles/Service.dir/staros_worker.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1181: src/service/CMakeFiles/Service.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/starrocks-3.1.4/be/src/fs/fs_starlet.cpp: In member function ‘virtual starrocks::Status starrocks::StarletFileSystem::delete_files(const std::vector<std::__cxx11::basic_string<char> >&)’:
/home/starrocks-3.1.4/be/src/fs/fs_starlet.cpp:540:43: error: cannot convert ‘std::vector<std::basic_string_view<char> >’ to ‘absl::lts_20220623::Span<const std::__cxx11::basic_string<char> >’
  540 |         return to_status(fs->delete_files(parsed_path_views));
      |                                           ^~~~~~~~~~~~~~~~~
      |                                           |
      |                                           std::vector<std::basic_string_view<char> >
In file included from /home/starrocks-3.1.4/be/src/fs/fs_starlet.cpp:26:
/home/starrocks-3.1.4/thirdparty/installed/starlet/starlet_install/include/fslib/file_system.h:128:69: note:   initializing argument 1 of ‘virtual absl::lts_20220623::Status staros::starlet::fslib::FileSystem::delete_files(absl::lts_20220623::Span<const std::__cxx11::basic_string<char> >)’
  128 |     virtual absl::Status delete_files(absl::Span<const std::string> paths) = 0;
      |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
make[2]: *** [src/fs/CMakeFiles/FileSystem.dir/build.make:202: src/fs/CMakeFiles/FileSystem.dir/fs_starlet.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:815: src/fs/CMakeFiles/FileSystem.dir/all] Error 2

### StarRocks version (Required)
3.1.4

**Comment by kevincai** [comment]
use starrocks/dev-env-centos7:3.1.4 for 3.1.4 release codebase build.
