### ISSUE TITLE
Reserved Keywords within struct field names parsed with backticks.

### ISSUE THREAD

**Issue by DeadMeme5441** [StarRocks/starrocks#39237]
The outputs and inputs row of the table are nested structs within an array, containing the field "index". This is a reserved keyword, and hence I escaped it with backticks. The problem is - when reading from the parquet file, the column name is being read as "`index`" including the backticks and not without them. This is causing the engine to only read null values as the column "`index`" with backticks does not exist in the parquet file. 

### Steps to reproduce the behavior (Required)
CREATE DATABASE bitcoin;

USE bitcoin;

CREATE EXTERNAL TABLE `s3_transactions` (
  `date` varchar(1048576) NULL COMMENT "",
  `hash` varchar(1048576) NULL COMMENT "",
  `size` bigint(20) NULL COMMENT "",
  `virtual_size` bigint(20) NULL COMMENT "",
  `version` bigint(20) NULL COMMENT "",
  `lock_time` bigint(20) NULL COMMENT "",
  `block_hash` varchar(1048576) NULL COMMENT "",
  `block_number` bigint(20) NULL COMMENT "",
  `block_timestamp` datetime NULL COMMENT "",
  `index` bigint(20) NULL COMMENT "",
  `input_count` bigint(20) NULL COMMENT "",
  `output_count` bigint(20) NULL COMMENT "",
  `input_value` double NULL COMMENT "",
  `output_value` double NULL COMMENT "",
  `is_coinbase` boolean NULL COMMENT "",
  `fee` double NULL COMMENT "",
  `inputs` array<struct<`index` bigint(20), spent_transaction_hash varchar(1048576), spent_output_index bigint(20), script_asm varchar(1048576), script_hex varchar(1048576), sequence bigint(20), required_signatures bigint(20), type varchar(1048576), address varchar(1048576), value double>> NULL COMMENT "",
  `outputs` array<struct<`index` bigint(20), script_asm varchar(1048576), script_hex varchar(1048576), required_signatures bigint(20), type varchar(1048576), address varchar(1048576), value double>> NULL COMMENT ""
) ENGINE=FILE
PROPERTIES (
"aws.s3.access_key"  =  "AK******X7",
"path"  =  "s3://aws-public-blockchain/v1.0/btc/transactions/date=2009-01-03/",
"aws.s3.secret_key"  =  "FI******OY",
"format"  =  "parquet",
"aws.s3.region"  =  "us-east-2",
"enable_recursive_listing"  =  "true"
);

SELECT outputs from s3_transactions;

### Expected behavior (Required)
['{"index": 0, "required_signatures": 1, "script_asm": "04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f OP_CHECKSIG", "script_hex": "4104678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5fac", "type": "pubkey", "value": 50}']

### Real behavior (Required)
[{"`index`":null,"script_asm":"04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f OP_CHECKSIG","script_hex":"4104678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5fac","required_signatures":1,"type":"pubkey","address":null,"value":50}] 

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

+-------------------+
| current_version() |
+-------------------+
| 3.2.2-269e832     |
+-------------------+

**Comment by DeadMeme5441** [comment]
Hi @packy92 , any updates on the commit? Our deployment is a little blocked because of this issue - could I help in any way? Would love to contribute if necessary.

**Comment by packy92** [comment]
> Hi @packy92 , any updates on the commit? Our deployment is a little blocked because of this issue - could I help in any way? Would love to contribute if necessary.

Sorry, I am working on it.

**Comment by DeadMeme5441** [comment]
The issue persists with broker load - if I use broker load to load data from s3 files, the internal fields in the s3 file column struct still errors because it's not escaped correctly. 

## Steps to reproduce the behavior (Required)

1. Create table
CREATE TABLE `transactions` (
  `date` varchar(1048576) NULL COMMENT "",
  `hash` varchar(1048576) NULL COMMENT "",
  `size` bigint(20) NULL COMMENT "",
  `virtual_size` bigint(20) NULL COMMENT "",
  `version` bigint(20) NULL COMMENT "",
  `lock_time` bigint(20) NULL COMMENT "",
  `block_hash` varchar(1048576) NULL COMMENT "",
  `block_number` bigint(20) NULL COMMENT "",
  `block_timestamp` datetime NULL COMMENT "",
  `index` bigint(20) NULL COMMENT "",
  `input_count` bigint(20) NULL COMMENT "",
  `output_count` bigint(20) NULL COMMENT "",
  `input_value` double NULL COMMENT "",
  `output_value` double NULL COMMENT "",
  `is_coinbase` boolean NULL COMMENT "",
  `fee` double NULL COMMENT "",
  `inputs` array<struct<`index` bigint(20), spent_transaction_hash varchar(1048576), spent_output_index bigint(20), script_asm varchar(1048576), script_hex varchar(1048576), sequence bigint(20), required_signatures bigint(20), type varchar(1048576), address varchar(1048576), value double>> NULL COMMENT "",
  `outputs` array<struct<`index` bigint(20), script_asm varchar(1048576), script_hex varchar(1048576), required_signatures bigint(20), type varchar(1048576), address varchar(1048576), value double>> NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`date`, `hash`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`hash`)

2. Load with broker load from s3 infile - parquet

load label bitcoin.tx_load( data infile("s3://aws-public-blockchain/v1.0/btc/transactions/date=2024-01-01/*.snappy.parquet") into table transactions format as "parquet" (date, hash, size, virtual_size, version, lock_time, block_hash, block_number, block_timestamp, `index`, input_count, output_count, input_value, output_value, is_coinbase, fee, inputs, outputs)) with broker ("aws.s3.use_instance_profile" = "false", "aws.s3.region" = "us-east-2", "aws.s3.access_key" = "*************************", "aws.s3.secret_key" = "****************************") properties ( "timeout" = "259200");

## Expected Behavior

Broker load loads the files.

## Actual Behaviour

Error - type:LOAD_RUN_FAIL; msg:Invalid Column Name:index

The error is with the nested index field within outputs and intputs.

**Comment by packy92** [comment]
Let me check it.
