### ISSUE TITLE
support modifying external resources through sql syntax

### ISSUE THREAD

**Issue by hiliuxg** [StarRocks/starrocks#3928]
## Background
When using hive external tables, sometimes the uri of the metastore is changed. The existing method can only recreate the hive external resources, and rebuild all the downstream tables.

## Target 
Ability to modify external resources through SQL syntax, and downstream dependent tables do not need to be rebuilt

## How
Define a syntax to support this feature, maybe  like this 
```sql

ALTER RESOURCE 'hive0' SET PROPERTIES ("hive.metastore.uris" = "thrift://10.10.44.97:9083")

```
1. It can update the origin property
2. It can add a new property
3. It can not delete the property 

any other have suggestions  ?

**Comment by imay** [comment]
@hiliuxg Thanks for your idea and contribution. 
I have some questions about this interface.
Because a resource may have many properties, what will the `SET PROPERTIES` command do?
Will it just override the `hive.metastore.uris` property or replace all properties with only the new properties?

As a user, what's the command he/she can use to update/add a property. You should make them clear

**Comment by hiliuxg** [comment]
@imay 
1. the set properties command will only override the properties that the user set , not replace all the properties . for this example , it will only override the `hive.metastore.uris`  property , not replace all properties . 
2. if the property that the user set dose not exists  , it will throw a exception that says ' the property dose not support yet .'

**Comment by DorianZheng** [comment]
I think `set` is much better too. refer to: https://gpdb.docs.pivotal.io/6-9/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html

**Comment by imay** [comment]
> I think `set` is much better too. refer to: https://gpdb.docs.pivotal.io/6-9/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html

I see. It is OK for me to use `set property`
