### ISSUE TITLE
使用docker编译starrocks报错

### ISSUE THREAD

**Issue by icedrugs89** [StarRocks/starrocks#3931]
1、按照git的安装步骤执行如下：
docker run -it \
-v /{local-path}/.m2:/root/.m2 \
-v /{local-path}/starrocks:/root/starrocks \
--name {container-name} \
-d starrocks/dev-env:{version}

docker exec -it {container-name} /bin/bash
cd /root/starrocks
sh build.sh
2、docker中编译出现的错误，环境是mac
<img width="491" alt="image" src="https://user-images.githubusercontent.com/100941547/157167009-9ad054fb-cf54-4303-baac-3150ed21f31d.png">

<img width="575" alt="image" src="https://user-images.githubusercontent.com/100941547/157166864-0db02540-aab7-411b-8480-a70ee41f410e.png">

**Comment by imay** [comment]
Because your mac is M1, we only support compiling on intel chip

**Comment by decster** [comment]
From the screenshot, the build process(specifically g++) was killed somehow, probably because of OOM(you can check by show dmesg).
And whether M1 can build StarRocks or not is another issue.

**Comment by stdpain** [comment]
https://github.com/StarRocks/docs/blob/main/administration/Build_in_docker.md#faq
