### ISSUE TITLE
Query Hive  External Table Error:ERROR 1064 (HY000): open file failed

### ISSUE THREAD

**Issue by moranrr** [StarRocks/starrocks#395]
I create a hive external table like this:
`create EXTERNAL TABLE `dw_part_info`( 
code     	string,
name           	string
  ) ENGINE=HIVE
PROPERTIES (
  "resource" = "hive0",
  "database" = "dim",
  "table" = "dw_part_info"
);`

When I query this table：

`select count(1) from dw_part_info`

client error:

ERROR 1064 (HY000): open file failed, file=hdfs://XX/part-00003-0cce13e9-99f3-4c65-b795-79554df45957-c000.snappy.parquet

The query in hive is correct。

BE Log:
`
I0924 14:21:00.071480 22221 plan_fragment_executor.cpp:67] Prepare(): query_id=96028bd8-1cff-11ec-b545-b4055d5a0fba fragment_instance_id=96028bd8-1cff-11ec-b545-b4055d5a0fc0 backend_num=0
I0924 14:21:00.071557 22221 plan_fragment_executor.cpp:126] Using query memory limit: 2.00 GB
I0924 14:21:00.071601 22221 exec_node.cpp:577] exec node: AGGREGATION_NODE, use vectorized:1
I0924 14:21:00.071611 22221 exec_node.cpp:577] exec node: EXCHANGE_NODE, use vectorized:1
I0924 14:21:00.071772 21998 plan_fragment_executor.cpp:235] Open(): fragment_instance_id=96028bd8-1cff-11ec-b545-b4055d5a0fc0
I0924 14:21:00.074401 22190 internal_service.cpp:242] exec plan fragment, fragment_instance_id=96028bd8-1cff-11ec-b545-b4055d5a0fbd, coord=TNetworkAddress(hostname=10.186.66.54, port=9020), backend=3
I0924 14:21:00.074414 22190 plan_fragment_executor.cpp:67] Prepare(): query_id=96028bd8-1cff-11ec-b545-b4055d5a0fba fragment_instance_id=96028bd8-1cff-11ec-b545-b4055d5a0fbd backend_num=3
I0924 14:21:00.074435 22190 plan_fragment_executor.cpp:126] Using query memory limit: 2.00 GB
I0924 14:21:00.074462 22190 exec_node.cpp:577] exec node: AGGREGATION_NODE, use vectorized:1
I0924 14:21:00.074470 22190 exec_node.cpp:577] exec node: HDFS_SCAN_NODE, use vectorized:1
I0924 14:21:00.074674 21997 plan_fragment_executor.cpp:235] Open(): fragment_instance_id=96028bd8-1cff-11ec-b545-b4055d5a0fbd
W0924 14:21:00.079509 21997 plan_fragment_executor.cpp:260] fail to open fragment, instance_id=96028bd8-1cff-11ec-b545-b4055d5a0fbd, status=Internal error: open file failed, file=hdfs://XX/part-00003-0cce13e9-99f3-4c65-b795-79554df45957-c000.snappy.parquet
I0924 14:21:00.083300 22209 internal_service.cpp:260] cancel framgent, fragment_instance_id=96028bd8-1cff-11ec-b545-b4055d5a0fc0, reason: 3
I0924 14:21:00.083308 22209 plan_fragment_executor.cpp:621] cancel(): fragment_instance_id=96028bd8-1cff-11ec-b545-b4055d5a0fc0
I0924 14:21:00.083561 22198 internal_service.cpp:260] cancel framgent, fragment_instance_id=96028bd8-1cff-11ec-b545-b4055d5a0fbd, reason: 3
W0924 14:21:00.086483 21997 fragment_mgr.cpp:183] Fail to open fragment 96028bd8-1cff-11ec-b545-b4055d5a0fbd: Internal error: open file failed, file=hdfs://XX/part-00003-0cce13e9-99f3-4c65-b795-79554df45957-c000.snappy.parquet
I0924 14:21:00.086956 21997 plan_fragment_executor.cpp:691] Fragment 96028bd8-1cff-11ec-b545-b4055d5a0fbd:(Active: 4.749ms, non-child: 0.00%)
   - AverageThreadTokens: 0.00 
   - MemoryLimit: 2.00 GB
   - PeakMemoryUsage: 52.00 KB
   - PeakReservation: 0
   - PeakUsedReservation: 0
   - RowsProduced: 0
  BlockMgr:
     - BlockWritesOutstanding: 0
     - BlocksCreated: 0
     - BlocksRecycled: 0
     - BufferedPins: 0
     - BytesWritten: 0
     - MaxBlockSize: 8.00 MB
     - TotalBufferWaitTime: 0.000ns
     - TotalReadBlockTime: 0.000ns
  DataStreamSender (dst_id=2, dst_fragments=[96028bd81cff11ec-b545b4055d5a0fc0]):(Active: 269.582us, non-child: 5.68%)
     - PartType: UNPARTITIONED
     - BytesSent: 0
     - CompressTime: 0.000ns
     - IgnoreRows: 0
     - OverallThroughput: 0.00 /sec
     - PeakMemoryUsage: 16.00 KB
     - SendRequestTime: 123.039us
     - SerializeBatchTime: 0.000ns
     - ShuffleDispatchTime: 0.000ns
     - ShuffleHashTime: 0.000ns
     - UncompressedBytes: 0
     - WaitResponseTime: 95.914us
  AGGREGATION_NODE (id=1):(Active: 4.770ms, non-child: 0.74%)
     - AggregateFunctions: count(1)
     - AggComputeTime: 0.000ns
     - ExprComputeTime: 0.000ns
     - ExprReleaseTime: 0.000ns
     - GetResultsTime: 0.000ns
     - HashTableSize: 0
     - InputRowCount: 0
     - PassThroughRowCount: 0
     - PeakMemoryUsage: 4.00 KB
     - ResultAggAppendTime: 0.000ns
     - ResultGroupByAppendTime: 0.000ns
     - ResultIteratorTime: 0.000ns
     - RowsReturned: 0
     - RowsReturnedRate: 0
     - StreamingTime: 0.000ns
    HDFS_SCAN_NODE (id=0):(Active: 4.735ms, non-child: 99.72%)
       - BytesRead: 0
       - BytesReadDataNodeCache: 0
       - BytesReadFromDisk: 0
       - BytesReadLocal: 0
       - BytesReadRemote: 0
       - BytesReadShortCircuit: 0
       - BytesTotalRead: 0
       - ColumnConvertTime: 0.000ns
       - ColumnReadTime: 0.000ns
       - ExprFilterTime: 0.000ns
       - GroupChunkRead: 0.000ns
       - GroupDictDecode: 0.000ns
       - GroupDictFilter: 0.000ns
       - IoCounter: 0
       - IoTime: 0.000ns
       - LevelDecodeTime: 0.000ns
       - NumDiskAccess: 0
       - OpenFile: 4.731ms
       - PageReadTime: 0.000ns
       - PeakMemoryUsage: 0
       - PerReadThreadRawHdfsThroughput: 0.00 /sec
       - RawRowsRead: 0
       - ReaderInit: 0.000ns
       - ReaderInitColumnReaderInit: 0.000ns
       - ReaderInitFooterRead: 0.000ns
       - RowsRead: 0
       - RowsReturned: 0
       - RowsReturnedRate: 0
       - ScanTime: 0.000ns
       - ScannerThreadsInvoluntaryContextSwitches: 0
       - ScannerThreadsTotalWallClockTime: 0.000ns
         - MaterializeTupleTime(*): 0.000ns
         - ScannerThreadsSysTime: 0.000ns
         - ScannerThreadsUserTime: 0.000ns
       - ScannerThreadsVoluntaryContextSwitches: 0
       - TotalRawReadTime(*): 0.000ns
       - TotalReadThroughput: 0.00 /sec
       - ValueDecodeTime: 0.000ns
`

**Comment by imay** [comment]
@moranrr 
You can try `refresh` to get the new meta information from Hive.

**Comment by moranrr** [comment]
@imay 
how to refresh？ I did not find this command in documentation.

**Comment by moranrr** [comment]
This file exists in the table path, and the data in this table has not been updated for two years.

**Comment by mklzl** [comment]
Try refreshing Hive table
