### ISSUE TITLE
[Bug] Drop Table(iceberg) Force won't completely remove all files on S3

### ISSUE THREAD

**Issue by xiaobingxia-at** [StarRocks/starrocks#39709]
Create one iceberg table, and ingest 11B rows of data.
Do "Drop Table <table> Force", 

### Expected behavior (Required)
After the drop operation is complete, the whole s3 folder is removed.

### Real behavior (Required)
After the drop operation is complete, check the s3 folder, there are still several data files and metadata files left.

### StarRocks version (Required)
3.2.2

**Comment by letian-jiang** [comment]
Hi @xiaobingxia-at, in my testing, `drop table force` will delete all data files and metadata files, with only directories left.

**Comment by stephen-shelby** [comment]
This behavior is consistent with Spark and is relatively conservative. Do you have a need to delete the directory?
