### ISSUE TITLE
Support user-defined variables through set_var_stmt

### ISSUE THREAD

**Issue by rcauble** [StarRocks/starrocks#39819]
## Feature request

**Is your feature request related to a problem? Please describe.**
For the some of the same rationale described here we would like for user-defined variables to also be defined at the query rather than session level: https://github.com/StarRocks/starrocks/issues/32024

One additional reason is that we're planning to use user-defined variables to manage large strings. While the client can release memory by setting the VAR to null at the end of the query, this has a downside which is that the client needs to manage this before returning to the pool; it's easy to forget to do this since standard connection pool practice is to just add the connection back to the pool.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jaogoy** [comment]
Use `set_user_variable` as described in #40746
