### ISSUE TITLE
Support native iceberg metadata, REST and STORAGE

### ISSUE THREAD

**Issue by colagy** [StarRocks/starrocks#39844]
## Enhancement
STORAGE means the metadata storaged in remote storage, such as s3 or hdfs
https://iceberg.apache.org/catalog/
![image](https://github.com/StarRocks/starrocks/assets/37213080/1c5cfe6a-6b51-4c3a-aca5-9b4dc85fa336)

**Comment by tcodehuber** [comment]
@colagy  Does starrocks now support creating iceberg catalog whose backend is rest catalog impl? 
Now only hms/aws glue/tabular are mentioned in the official docs.
