### ISSUE TITLE
[JDBC CATALOG] Unable to view table.

### ISSUE THREAD

**Issue by xiaoyongheng** [StarRocks/starrocks#39860]
### Steps to reproduce the behavior (Required)
```sql
1.Create catalog
CREATE EXTERNAL CATALOG mysql_catalog
PROPERTIES
(
    "type"="jdbc",
    "user"="root",
    "password"="MYSQL_PASSWORD",
    "jdbc_uri"="jdbc:mysql://MYSQL_IP:3306",
    "driver_url"="file:///mysql-connector/mysql-connector-java-5.1.49.jar",
    "driver_class"="com.mysql.jdbc.Driver"
);

2.View all tables in the catalog database
show tables from mysql_catalog.db;
ERROR 1064 (HY000): DECIMAL's precision should range from 1 to 38
```

### Expected behavior (Required)

Show all tables

```sql
table1
table2
table3
table4
...
```

### Real behavior (Required)

```shell
ERROR 1064 (HY000): DECIMAL's precision should range from 1 to 38
```

### StarRocks version (Required)

```sql
mysql> select current_version();

+-------------------+

| current_version() |

+-------------------+

| 3.2.1-79ee91d   |

+-------------------+

1 row in set (0.01 sec)
```

**Comment by xiaoyongheng** [comment]
show tables from mysql_catalog.db(db_name)

**Comment by ChewJ404** [comment]
![9ea8d452bb4715c66d91190ec2ca5d23](https://github.com/StarRocks/starrocks/assets/10162958/cb933217-7f19-45eb-96ef-07f248340825)
![image](https://github.com/StarRocks/starrocks/assets/10162958/729fa780-0d82-4534-8f31-a97013032272)

mysql decimal(50,2)  ,  JDBC CATALOG    DECIMAL's precision should range from 1 to 38    How to solve
