### ISSUE TITLE
FILES() doesn't ignore empty/underscore files

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#39916]
In Kubernetes and a Shared Data Cluster, when restarting a single CN I noticed this kind of log in pretty much all other CNs: W0123 08:39:37.188024   455 socket.cpp:1227] Fail to wait EPOLLOUT of fd=1431: Connection timed out [110]
FILES() doesn't ignore empty/underscore files, which are commonly used for big data Batch frameworks to mark a "folder" as processed. E.g. _SUCCESS

@nferrario

**Comment by nferrario** [comment]
I forgot to mention that this applies to Parquet, since INSERT FILES will try to infer the schema and of course it fails . That's why it would be nice to have the option to ignore such files which are very common.

**Comment by jaogoy** [comment]
@nferrario I'm not clear about your problem.
If you are loading parquet files, can you specify the files in `path` by using giving the parquet extention, like `s3://path/to/dir/*.parquet`?
And, a valid parquet file shoule be only zero byte.

**Comment by nferrario** [comment]
Hi @jaogoy, we can close this issue, I forgot it was still open.

**Comment by jaogoy** [comment]
OK, if there are still some problems, we can reopen it.
