### ISSUE TITLE
Routine Load. confluent_schema_registry_url.  infinite retry loop on shared data

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#39915]
After restarting all FEs, two Routine Loads that were working fine started to show a 'confluent_schema_registry_url' not set error in "OtherMsgs". The main problem is that these loads never failed. There would be an infinite retry loop, where the BE would throw that error and the FE would reschedule, but there's no "progression" metric that I'm aware of.

@nferrario

**Comment by allencelerdata** [comment]
The issue is that I create a valid routine load, then I restart all FEs, and the routine enters this endless loop where it's stuck in RUNNING but the logs in CNs say 'confluent_schema_registry_url' not set.
StarRocks' self-start on recovery of already created routines is what fails

**Comment by nferrario** [comment]
I've migrated my ROUTINE LOADS to the Flink Connector, which does work perfectly. I think we need to get the StarRocks docs updated to let users know about ROUTINE LOAD limitations.

**Comment by alberttwong** [comment]
@DanRoscigno fyi

**Comment by wyb** [comment]
`confluent_schema_registry_url` is not persisted.
this bug has been fixed last month.

https://github.com/StarRocks/starrocks/pull/32302
https://github.com/StarRocks/starrocks/pull/41171
