### ISSUE TITLE
AWS S3 "Slow Down" errors don't appear to be retried

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#39917]
AWS S3 "Slow Down" errors don't appear to be retried. I had to wait for the cluster load to decrease to re-run my large INSERT statement, otherwise it'd simply fail.

@nferrario

**Comment by kevincai** [comment]
what's the scenario of this `slow down` error occur?

**Comment by nferrario** [comment]
@kevincai AWS S3 has a limit for IOPS, and returns an HTTP 503 code when it's been reached.

https://repost.aws/knowledge-center/http-5xx-errors-s3
https://repost.aws/questions/QU_F-UC6-fSdOYzp-gZSDTvQ/receiving-s3-503-slow-down-responses

**Comment by kevincai** [comment]
we know the limitation of iops of aws s3 service. And the sdk DO has retry, the default retry backoff is not aggressive, by default the backoff interval is 0,50ms,100ms,200ms,400ms, so it will be fairly short running out of the 5 attempts.

B.T.W. which version are you on? And I suppose you are running starrocks in shared-data mode, right?

**Comment by nferrario** [comment]
Interesting. Is there any config that can be changed to perhaps extend the backoff interval?

Yes, Shared Data on 3.2.2. Deployed on K8s

**Comment by kevincai** [comment]
yes, we have adjusted the default retry backoff policy for PUT request. it will be available in next release. The parameters are not exposed yet, will be exposed soon.

**Comment by nferrario** [comment]
Great! So it sounds like we can close this ticket

**Comment by kevincai** [comment]
close this ticket for now.
