### ISSUE TITLE
StarRocks 3.2.1 couldn't obtain the latest data from hive catalog occasionally

### ISSUE THREAD

**Issue by VisionaryAries** [StarRocks/starrocks#39921]
StarRocks version: 3.1.2
We encounter an issue that StarRocks 3.2.1 couldn't obtain the latest data from hive catalog occasionally after refreshing hive table data, but StarRocks could obtain the latest data after waiting for a while.
For troubleshooting the issue, we have disabled HMS cache, but the  data cache is still enabled. While the issue still exist.

**Comment by 839224346** [comment]
try adding these settings when create hive catalog.
` "enable_cache_list_names" = "false",
"enable_metastore_cache" = "false",
"enable_remote_file_cache" = "false"`

**Comment by VisionaryAries** [comment]
@839224346 Thanks a lot, I'll try it and feedback the result after a while.
