### ISSUE TITLE
pipeline engine query result error

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#3994]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS g3;
CREATE DATABASE g3;
USE g3;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 BOOLEAN NULL ,c_0_1 DATE NULL ,c_0_2 DECIMAL(36, 0)  NOT NULL ,c_0_3 BIGINT NOT NULL ,c_0_4 DATE NULL ,c_0_5 VARCHAR(1) NULL ,c_0_6 BOOLEAN NOT NULL ,c_0_7 BOOLEAN NULL ,c_0_8 DOUBLE NOT NULL ,c_0_9 CHAR(11) NOT NULL ,c_0_10 BIGINT NOT NULL ,c_0_11 DECIMAL(5, 3)  NOT NULL ,c_0_12 BOOLEAN NOT NULL ,c_0_13 VARCHAR(21) NULL ,c_0_14 FLOAT NOT NULL ,c_0_15 LARGEINT NOT NULL ,c_0_16 INT NULL ,c_0_17 DATETIME NULL ) DUPLICATE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4) DISTRIBUTED BY HASH (c_0_1,c_0_3,c_0_4) properties("replication_num"="3") ;
CREATE TABLE t1 (c_1_0 BOOLEAN NOT NULL ,c_1_1 DATETIME NULL ,c_1_2 DOUBLE NOT NULL ,c_1_3 DATETIME NULL ) UNIQUE KEY (c_1_0) DISTRIBUTED BY HASH (c_1_0) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t2 (c_2_0 BIGINT NOT NULL ,c_2_1 DATETIME NOT NULL ,c_2_2 INT NOT NULL ,c_2_3 VARCHAR(1) NULL ,c_2_4 DECIMAL(13, 2)  NOT NULL ,c_2_5 DECIMAL(28, 18)  NULL ,c_2_6 VARCHAR(1) NOT NULL ,c_2_7 DATE NOT NULL ,c_2_8 BOOLEAN NOT NULL ,c_2_9 SMALLINT NULL ,c_2_10 CHAR(21) NOT NULL ,c_2_11 DECIMAL(30, 9)  NULL ,c_2_12 BOOLEAN NOT NULL ,c_2_13 PERCENTILE PERCENTILE_UNION NOT NULL ,c_2_14 VARCHAR(31) MAX NULL ,c_2_15 DECIMAL(25, 6)  SUM NOT NULL ) AGGREGATE KEY (c_2_0,c_2_1,c_2_2,c_2_3,c_2_4,c_2_5,c_2_6,c_2_7,c_2_8,c_2_9,c_2_10,c_2_11,c_2_12) DISTRIBUTED BY HASH (c_2_9,c_2_12,c_2_0) properties("replication_num"="3") ;
DELETE FROM t1 WHERE c_1_0=false;
INSERT INTO t2 VALUES (1280923558, "1970-01-01 08:00:00", 3, "", 534091256.21, 6.605528719E-9, "", "1970-01-01", false, 11, "x", NULL, false, percentile_hash("-1540841253"), "R0", 8852497190670.035495);
INSERT INTO t0 VALUES (true, NULL, 200144811111385934138880480490454594, -1794301102, "1970-01-01", "", false, true, 0.21617318713825995, "b", 2080071413, 0.098, true, "FU9s2", 0.618969039161291, 2080071413, 16, "1970-01-01 08:00:00"), (false, "1970-01-01", 927076761974603869025730317838519793, 1159460159, "1970-01-01", "", true, true, 0.18538473819231005, "Xc", 1275111475, 0.092, false, "Ic", 0.5649390929280488, 1159460159, 14, "1970-01-01 08:00:00"), (false, NULL, 222515630666748620601767968719122470, -1540841253, "1970-01-01", "", false, true, 0.03786547365536963, "V1Pk6Y5gy", 1019971365, 0.006, false, "", 0.735723962413321, 123103572, 3, "1970-01-01 08:00:00"), (true, NULL, 22215751712792553016813090673005997, 1382402926, "1970-01-01", "", false, true, 0.13306707899603087, "X", -1157814204, 0.028, false, "hDcEo", 0.162108947069604, -2145671046, 22, "1970-01-01 08:00:00");
INSERT INTO t0 VALUES (true, "1970-01-01", 832594460734981112221146222224179200, -712848329, "1970-01-01", "", false, true, 2.080071413E9, "", -798645607, 0.056, false, "c", 0.7649039687108197, -1272403455, 29, "1970-01-01 08:00:00");
TRUNCATE TABLE t2;
INSERT INTO t1 VALUES (false, "1970-01-01 08:00:00", 0.618969039161291, NULL), (false, "1970-01-01 08:00:00", 0.7468033836004077, "1970-01-01 08:00:00");
INSERT INTO t2 VALUES (-1412343908, "1970-01-01 08:00:00", 17, "", 583669061.21, 7.996292385E-9, "", "1970-01-01", true, 0, "iw", 859921780681.399293582, true, percentile_hash("-2145671046"), "", 4777045872950.704838);
INSERT INTO t0 VALUES (true, "1970-01-01", 741134105206583626568318276570043609, 576227012, "1970-01-01", "", true, false, 0.03786547365536963, "hs", 123103572, 0.036, false, "jd", 0.7909906348221928, 576227012, 20, "1970-01-01 08:00:00"), (NULL, "1970-01-01", 807097245196928270161974374210343910, -798645607, "1970-01-01", "", false, false, 0.22086699594538584, "AtY", -1309680894, 0.055, true, "", -7.98645607E8, 978146798, 22, "1970-01-01 08:00:00"), (false, "1970-01-01", 359325378885841928427457591121540010, -2138555341, "1970-01-01", "", true, true, -1.412343908E9, "E", -2120591435, 0.096, false, "", 0.618969039161291, -1794301102, 9, "1970-01-01 08:00:00");
INSERT INTO t2 VALUES (-1675969968, "1970-01-01 08:00:00", 30, "", 504697045.54, 8.610664634E-9, "", "1970-01-01", false, NULL, "16", 902994005285.965956559, true, percentile_hash("2136868340"), "E7W", 5679165895513.655481), (-2039924262, "1970-01-01 08:00:00", 15, "", 426765979.84, 5.434978510E-9, "", "1970-01-01", true, 2, "p", 545395624331.191583816, false, percentile_hash("-1675969968"), "", 4532413644494.903452), (1763622844, "1970-01-01 08:00:00", 9, "", 417745209.45, 5.346409371E-9, "", "1970-01-01", true, 8, "aYO", 385421352268.850189156, false, percentile_hash("2024752319"), "oU", 8490339924093.738090);
-- SELECT t1.c_1_1, t0.c_0_13, t2.c_2_8, t2.c_2_5, t2.c_2_1, t1.c_1_2, t2.c_2_4, t0.c_0_3, t0.c_0_15, t2.c_2_10 FROM t0, t1, t2 GROUP BY t1.c_1_1, t0.c_0_13, t2.c_2_8, t2.c_2_5, t2.c_2_1, t1.c_1_2, t2.c_2_4, t0.c_0_3, t0.c_0_15, t2.c_2_10;
-- cardinality: 32
-- SELECT t1.c_1_1, t0.c_0_13, t2.c_2_8, t2.c_2_5, t2.c_2_1, t1.c_1_2, t2.c_2_4, t0.c_0_3, t0.c_0_15, t2.c_2_10 FROM t0, t1, t2 WHERE false GROUP BY t1.c_1_1, t0.c_0_13, t2.c_2_8, t2.c_2_5, t2.c_2_1, t1.c_1_2, t2.c_2_4, t0.c_0_3, t0.c_0_15, t2.c_2_10 UNION SELECT t1.c_1_1, t0.c_0_13, t2.c_2_8, t2.c_2_5, t2.c_2_1, t1.c_1_2, t2.c_2_4, t0.c_0_3, t0.c_0_15, t2.c_2_10 FROM t0, t1, t2 WHERE (NOT (false)) GROUP BY t1.c_1_1, t0.c_0_13, t2.c_2_8, t2.c_2_5, t2.c_2_1, t1.c_1_2, t2.c_2_4, t0.c_0_3, t0.c_0_15, t2.c_2_10 UNION SELECT t1.c_1_1, t0.c_0_13, t2.c_2_8, t2.c_2_5, t2.c_2_1, t1.c_1_2, t2.c_2_4, t0.c_0_3, t0.c_0_15, t2.c_2_10 FROM t0, t1, t2 WHERE ((false) IS NULL) GROUP BY t1.c_1_1, t0.c_0_13, t2.c_2_8, t2.c_2_5, t2.c_2_1, t1.c_1_2, t2.c_2_4, t0.c_0_3, t0.c_0_15, t2.c_2_10;
-- cardinality: 26

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - main asan
 - mysql> select current_version();
+------------------------------+
| current_version()            |
+------------------------------+
| SQLANCER_01_ASAN 1782c4c |
+------------------------------+

**Comment by wanpengfei-git** [comment]
the query result error when turn pipeline on.

**Comment by mofeiatwork** [comment]
I could not reproduce this issue, both `1782c4` and `9e1f77f` return correct result.
