### ISSUE TITLE
The JSON import is not as expected.

### ISSUE THREAD

**Issue by yongbingwang** [StarRocks/starrocks#3998]
### Steps to reproduce the behavior (Required)
1. create table.
```SQL
CREATE TABLE `primary_table_without_null` (
    `k1` date NOT NULL, `k2` datetime NOT NULL, `k3` string NOT NULL, `k4` string NOT NULL, `k5` boolean NOT NULL, 
    `v1` tinyint NOT NULL, `v2` smallint NOT NULL, `v3` int NOT NULL, `v4` bigint NOT NULL, `v5` largeint NOT NULL, `v6` float NOT NULL, `v7` double NOT NULL, `v8` decimal(27,9) NOT NULL 
) ENGINE=OLAP 
PRIMARY KEY(`k1`, `k2`, `k3`, `k4`, `k5`) 
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) 
BUCKETS 3 PROPERTIES ( "replication_num" = "1", "storage_format" = "v2" );
```
2. stream load.
curl --location-trusted -u root:
    -T /basic_types_data.json -XPUT -H label:stream_load_1646904047656 -H format:json
    -H columns:k1, k2, k3, k4, k5, v1, v2, v3, v4, v5, v6, v7, v8
    -H jsonpaths:["$.k1", "$.k2", "$.k3", "$.k4", "$.k5", "$.k6", "$.k7", "$.k8", "$.k9", "$.k10", "$.k11", "$.k12", "$.k13", "$.k13"]
    http://x.x.x.x:8234/api/stream_load_test_db_1646904047518/primary_table_without_null/_stream_load

data file:
```
{
    "k1": "2020-06-23",
    "k2": "2020-06-23 00:00:09",
    "k3": "beijing",
    "k4": "haidian",
    "k5": 0,
    "k6": -119,
    "k7": -32759,
    "k8": -2147483639,
    "k9": -9223372036854775799,
    "k10": "-18446744073709551607",
    "k11": -2.2,
    "k12": -3.05,
    "k13": -3.132
}
```
### Expected behavior (Required)
import ok.
### Real behavior (Required)
```AssertionError: too many filtered rows```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 2.0 2.1

**Comment by rickif** [comment]
ErrorURL:
```
Reason: column(__op)) value is null while columns is not nullable. src line: [['2020-06-23', '2020-06-23 00:00:09', 'beijing', 'haidian', '0', '-119', '-32759', '-2147483639', '-9223372036854775799', '-18446744073709551607', '-2.2', '-3.05', '-3.132', '-3.132']];
```

**Comment by decster** [comment]
I tested it using current number of json paths, and it succeeded, the reason of the error is the 13 columns are specified, but 14 json paths are specified, there is one more json path

```
decster@decster-MS-7C94:~/projects/starrocks/localrun$ curl --location-trusted -u root: -T basic_types_data.json -XPUT -H label:stream_load_1646904047656 -H format:json -H columns:'k1, k2, k3, k4, k5, v1, v2, v3, v4, v5, v6, v7, v8' -H jsonpaths:'["$.k1", "$.k2", "$.k3", "$.k4", "$.k5", "$.k6", "$.k7", "$.k8", "$.k9", "$.k10", "$.k11", "$.k12", "$.k13"]' http://localhost:8030/api/test/primary_table_without_null/_stream_load
{
    "TxnId": 3,
    "Label": "stream_load_1646904047656",
    "Status": "Success",
    "Message": "OK",
    "NumberTotalRows": 1,
    "NumberLoadedRows": 1,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 294,
    "LoadTimeMs": 54,
    "BeginTxnTimeMs": 0,
    "StreamLoadPutTimeMs": 2,
    "ReadDataTimeMs": 0,
    "WriteDataTimeMs": 10,
    "CommitAndPublishTimeMs": 40
```

**Comment by jaogoy** [comment]
@yongbingwang  @rickif  So, is this still a bug or not.

**Comment by yongbingwang** [comment]
> 

I think it's bug. 
At the same cluster, if the table type is `duplicate`, the data can be imported normally.
![rBsjlANVOa](https://user-images.githubusercontent.com/86867342/157793410-a5e2776e-d5aa-42d9-b83a-5c728ea393b0.png)
