### ISSUE TITLE
Load json file to Starrocks got an error：The surrogate pair in string is invalid.. src line: [null];

### ISSUE THREAD

**Issue by jxzdoing** [StarRocks/starrocks#400]
i need to load json data to starrocks[actually in my cluster called dorisdb] table,i execute the command beyond in my cluster,but it's failed!
`curl -v --location-trusted -u user:password -H "format:json" -H "strip_outer_array:true" -T my_json_file  http://fe:8030/api/database/table/_stream_load`
![image](https://user-images.githubusercontent.com/16585537/134656619-e09d5f61-58bb-414d-9dec-3282645a23aa.png)
according to the errorURL, i download the file and found some tips in it,that's:
`Reason: Failed to parse string to json. code=9, error=The surrogate pair in string is invalid.. src line: [null];`
my json file content example:
[{},{},{}]
first of all,i doubt it's my json file it's wrong? so i check my file by this way:
1.copy the json string to website and validate.
2.cat json_file|python -m json.tool
all above shows there is no problem about the json file，finally i found the single error json string, it contains content like \ud804\udxxxx，this are unicode for emotion,but some can recognize,some can't。
is a bug for starrcoks?
my version is 1.18.1

**Comment by mklzl** [comment]
You may have non-UTF-8 encoded values in your JSON characters. I have encountered similar problems because my JSON contains expressions, which are not utF-8 encoded

**Comment by jxzdoing** [comment]
> You may have non-UTF-8 encoded values in your JSON characters. I have encountered similar problems because my JSON contains expressions, which are not utF-8 encoded

i run my program on linux centos system[default encoder utf-8] ,it should not have other encoder。
