### ISSUE TITLE
flink cdc iceberg,starrocks query is errors that is Unsupported iceberg file content:2

### ISSUE THREAD

**Issue by 13453547819** [StarRocks/starrocks#40043]
【Details】flink cdc collect mysql data to iceberg and starrocks query iceberg catalog，but mysql row data be update, starrocks query is errors that is Unsupported iceberg file content:2。
【StarRocks version]】3.1.3
【Flink version】1.15.2
【lceberg version】1.4.2
1. create table IF NOT EXISTS test(
  dt INT NOT NULL
  name varchar.
  PRIMARY KEY (dt) NOT ENFORCED
  )with ('format-version' = '2',
  'write.upsert.enabled' = 'true',
  'engine.hive.enabled' = 'true'
);
2. Flink cdc iceberg
3. starrocks query:
select * from iceberg catalog.db.test;
## Expected behavior (Required)
![image](https://github.com/StarRocks/starrocks/assets/119465257/9359bd39-44a4-4b18-8505-839593f3fb67)

## Real behavior (Required)
![image](https://github.com/StarRocks/starrocks/assets/119465257/aa73bb7f-43cc-47d9-ae23-e738cf09ab8d)
## StarRocks version (Required)
![image](https://github.com/StarRocks/starrocks/assets/119465257/9d937c7e-9d52-402b-9660-8989c4d6d2c9)

**Comment by dirtysalt** [comment]
it means we don't support equality delete feature. And it's been recently supported in this PR: https://github.com/StarRocks/starrocks/pull/38529, and released in 3.1.7

**Comment by 13453547819** [comment]
> it means we don't support equality delete feature. And it's been recently supported in this PR: #38529, and released in 3.1.7
![image](https://github.com/StarRocks/starrocks/assets/119465257/3f132fa8-b41d-4840-9770-1f82ca94beed)

![image](https://github.com/StarRocks/starrocks/assets/119465257/4648b533-f766-411d-9eba-5a781121dbaf)

**Comment by chrisfw** [comment]
FYI, I just encountered the same issue in 3.2 today.

**Comment by chengyi3192** [comment]
> FYI, I just encountered the same issue in 3.2 today.

@chrisfw The problem will be solved in sections 3.1.8 and 3.2.3, But limited to ORC format only
If it is in parquet format, Official response in format needs to wait for version 3.3 of parquet format

**Comment by chrisfw** [comment]
Thank you for the update @chengyi3192.  I appreciate your assistance.

Regards,
Chris
