### ISSUE TITLE
StarRocks Geek Camp 2022

### ISSUE THREAD

**Issue by wuqiao** [StarRocks/starrocks#4008]
# Welcome to StarRocks Geek Camp 2022!

> Geek Camp is a collaborative development event launched and organized by the StarRocks community. Developers interested in database technologies are welcome to sign up for this 3-week event to complete community development tasks of varied difficulties. The StarRocks community panel will review the code quality and award the most outstanding participants "StarRocks Geek 2022".

Better Together! Be the most hard-core Geek in the StarRocks community! We prepared 34 tasks in 8 categories: **Execution Engine, Storage Engine, Data Lake Analytics, Ecosystem, Loading, Observability, Planner, and Usability**, assigned different difficulties, including Challenging, Moderate, and Easy. You can pick the one that interests and fits you the most.

## Registration procedure

- **Step1.**  Pick an issue you are interested in, click the issue link to go to the issue details page, and leave a comment under the issue as required to sign up.
- **Step2**. On your WeChat, add the StarRocks community assistant "**_StarRocks-1_**" as a WeChat friend and leave your GitHub ID. The assistant will invite you to a WeChat group based on the issue you pick.
- **Step3**.The mentor will communicate with all the participants who picked this issue and assign the task to the best match through communication and test. Other participants who chose this issue but are not selected as the best match, choose another one or enter the procedure： “Independent development channel”.

## Let's pick! 
**Independent development channel**
- If all the tasks below do not include the task you are interested in, please add the  StarRocks community assistant WeChat ”**_StarRocks-1_**“to communicate and then submit an issue stating the task you would like to do. The community will evaluate and confirm if the task will be added to the campaign.

**Points to note**

- 1 person can choose multiple issues，1 issue will only be developed by 1 person
- Technology stacks that will be involved in all tasks: Java, C++, Python

### **1. Execution Engine**
- [ ]  #4010
- [ ]  #4013
- [ ]  #4015
- [x]  #4016
- [ ]  #4020
- [ ]  #4022
- [ ]  #4023
- [x]  #4028
- [x]  #4036
- [ ]  #4037

### 2. Storage Engine

- [x] #4029
- [x] #4032
- [x] #4033
- [x] #4449 
- [x] #4669

### 3. Ecosystem

- [ ]  #4027
- [x] #4788
### 4. Data Lake Analysis

- [x]  #4030
- [ ]  #4039

### 5. Planner
- [x]  #4024
- [ ]  #4025
- [x] #4038
- [x] #4040
- [x] #4041
- [x] #4042
- [x] #4043
- [x] #4044
- [x] #4045
- [x] #4046
- [x] #4047
- [x] #4048
- [x] #4049

### 6. Observability
- [x]  #4009
- [ ]  #4847

### 7、Loading

- [x] #4026  
- [x]  #4031

### 8、Usability

- [x] #4034
- [x] #4035

### 9、Others（Independent development）
- [x] #4730

# Before you start
1. Read the StarRocks [GitHub workflow](https://github.com/StarRocks/community/blob/main/Contributors/guide/workflow.md) carefully, which provides the configurations of BE and FE and describes how to submit a pull request.
2. To learn more about StarRocks, read [StarRocks documentation](https://github.com/StarRocks/docs/blob/main/TOC.md).

# Pull request requirements

1. After you complete code development, upload the code to the StarRocks code repo as a pull request (PR).

  - PR title format: **[SR GeekCamp] + PR title**
  - Labels ：[Geek Camp 2022/feature]

2. After you submit your PR, comment on the status of your PR submission as requested under this page.

  - Comment format: **"I have finished Issue #" + PR link id**

**Comment by yangrong688** [comment]
Hi @wuqiao, I want to pick #4020 .

**Comment by wuqiao** [comment]
> Hi @wuqiao, I want to pick #4020 .

 Hi，@yangrong688 The geek camp has not yet been officially released. The process is being optimized, but you can click on it to go to the issue details page, and leave a comment under the issue as required to sign up.We give you the record in advance. Thanks a lot!

**Comment by luo981695830** [comment]
I want to pick #4029

**Comment by mklzl** [comment]
I want to pick # #4034

**Comment by mchades** [comment]
I have finished #4691
