### ISSUE TITLE
start fe should be supported hostname

### ISSUE THREAD

**Issue by mklzl** [StarRocks/starrocks#401]
## Enhancement
I have modified the local code to support the configuration of frontend_address as IP address or hostname when starting FE. I think it makes cluster building easier.

    
![image](https://user-images.githubusercontent.com/36362816/134657540-642d66bc-1a34-4585-b9ac-69122a2d8d87.png)

or

![image](https://user-images.githubusercontent.com/36362816/134657678-c2f6b947-4a50-403a-904d-8752ecdac960.png)
Of course, you can still start FE using Priority_Networks
Do you think this change is worth it?

**Comment by sduzh** [comment]
@imay @gengjun-git PTAL

**Comment by gengjun-git** [comment]
@mklzl Can you make a pr to our repository?

**Comment by imay** [comment]
@mklzl 
In my opinion, a valid ip should be accept by `priority_networks`. If it doesn't work now, it is a bug. This should be fixed.
