### ISSUE TITLE
Support function array_to_bitmap in StarRocks 【Easy】

### ISSUE THREAD

**Issue by wuqiao** [StarRocks/starrocks#4010]
#  Requirement Description
input: ARRAY_INT ARRAY_SMALLINT ARRAY_TINYINT
output:TYPE_BITMAP
construct a bitmap from array,if input was NULL  then output was null. empty bitmap will be return if array is empty
eg:
array_to_bitmap([1,2,3]) -> bitmap(1,2,3)
array_to_bitmap(NULL) -> NULL
array_to_bitmap([]) -> bitmap()

# Mentor
@stdpain 

# Registration procedure

**Step 1.** Add a comment when you sign up. The comment can be a brief self-introduction and reason for signing up, including what you do, what you're good at, what you're interested in and your technology stack, and how familiar you are with StarRocks. Example:

> I pick! My name is Johnny. I am from StarRocks, and I have been working on database kernel development for one year. I am interested in OLAP, good at C++ programming, and have been using StarRocks for six months. I chose to solve this issue because I am familiar with the execution engine.

**Step 2.** On your WeChat, add the StarRocks community assistant "**_StarRocks-1_**" as a WeChat friend and leave your GitHub ID. The assistant will invite you to a WeChat group based on your picked issue.

**Step 3.** The mentor will communicate with all the participants who picked this issue and assign the task to the best match. 

# Before you start
1. Read the StarRocks [GitHub workflow](https://github.com/StarRocks/community/blob/main/Contributors/guide/workflow.md) carefully, which provides the configurations of BE and FE and describes how to submit a pull request.
2. To learn more about StarRocks, read [StarRocks documentation](https://github.com/StarRocks/docs/blob/main/TOC.md).

# Pull request requirements

1. After you complete code development, upload the code to the StarRocks code repo as a pull request (PR).

  - PR title format: **[SR GeekCamp] + PR title**
  - Labels ：[Geek Camp 2022/feature]
2. After you submit your PR, comment on the status of your PR submission as requested under the Pinned Issue [[StarRocks geek Camp 2022] ](https://github.com/StarRocks/starrocks/issues/4008)page.

  - Comment format: **"I have finished Issue #" + PR link id**

**Comment by MonsterChenzhuo** [comment]
@wuqiao Hello, I would like to complete this current pr

**Comment by MonsterChenzhuo** [comment]
I pick! My name is Monster. I'm from ziroom, and I've been working as a data developer for a year now. I am interested in OLAP, good at Java programming and have not used StarRocks. I chose to solve this problem because I am familiar with bitmap as well as RBM.

**Comment by Im-Manshushu** [comment]
My name is WangMan. I'd like to pick this issue. I started using it very early StarRocks. From version 1.14 to 2.1.  I chose to solve this problem because I am familiar with using starrocks and  I am big data development engineer from beijing  and good at Java programming and and a little knowledge of C + + programming.I hope I can contribute a little to the community. Complete the task

**Comment by johnnyflute** [comment]
My name is xu cheng，I am instrested in olap
