### ISSUE TITLE
[Feature] [jdbc catalog] Support all jdbc protocol queries, not just postgres and mysql

### ISSUE THREAD

**Issue by guestli** [StarRocks/starrocks#40125]
## Feature request

**Is your feature request related to a problem? Please describe.**
I would like starrocks to support more jdbc data sources, such as oracle and sqlserver.

**Describe the solution you'd like**
When I register the "jdbc catalog" with starrocks, it downloads the driver from the driver download address in my configuration. Obtain metadata from the downloaded driver and query data. We can provide default field type handling, retaining the ability to extend custom type handling.

**Describe alternatives you've considered**

**Additional context**

If you have any ideas, please leave a comment. If we can agree, I'm willing to contribute code to this feature.

**Comment by zombee0** [comment]
Hi, are you still working on this, let's move it to merge
