### ISSUE TITLE
query result error in norec mode (pipeline off)

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#4014]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS n2;
CREATE DATABASE n2;
USE n2;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DATE NOT NULL ,c_0_1 BITMAP BITMAP_UNION NULL ) AGGREGATE KEY (c_0_0) DISTRIBUTED BY HASH (c_0_0) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DECIMAL(35, 17)  NOT NULL ,c_1_1 LARGEINT NOT NULL ,c_1_2 DATETIME REPLACE_IF_NOT_NULL NOT NULL ) AGGREGATE KEY (c_1_0,c_1_1) DISTRIBUTED BY HASH (c_1_1) properties("replication_num"="3") ;
CREATE TABLE t2 (c_2_0 DATE NULL ,c_2_1 DECIMAL(13, 6)  NOT NULL ,c_2_2 LARGEINT NULL ,c_2_3 BIGINT NULL ,c_2_4 TINYINT NOT NULL ,c_2_5 SMALLINT NULL ,c_2_6 DECIMAL(21, 8)  NULL ,c_2_7 BOOLEAN NULL ,c_2_8 DATE NULL ,c_2_9 BOOLEAN NULL ,c_2_10 DATETIME NOT NULL ,c_2_11 DATETIME NOT NULL ,c_2_12 SMALLINT NULL ,c_2_13 BOOLEAN NOT NULL ,c_2_14 BOOLEAN NOT NULL ,c_2_15 FLOAT NOT NULL ) UNIQUE KEY (c_2_0,c_2_1,c_2_2,c_2_3,c_2_4,c_2_5,c_2_6,c_2_7,c_2_8,c_2_9,c_2_10,c_2_11,c_2_12,c_2_13,c_2_14) DISTRIBUTED BY HASH (c_2_14,c_2_11,c_2_1,c_2_6) properties("replication_num"="3") ;
INSERT INTO t2 VALUES ("1970-01-01", 5.870616, -1469816515, 702067435, 1, 6, NULL, false, "1970-01-01", true, "1970-01-01 08:00:00", "1970-01-01 08:00:00", 11, true, true, -1.362021329E9);
TRUNCATE TABLE t1;
INSERT INTO t0 VALUES ("1970-01-01", bitmap_hash("sZ5AIAwa0"));
INSERT INTO t1 VALUES (1.77717487840032906, 482445010, "1970-01-01 08:00:00"), (9.76437393409399911, 1345663061, "1970-01-01 08:00:00");
DELETE FROM t1 WHERE c_1_1=-700910363 AND c_1_0=7.69649397083192454;
INSERT INTO t2 VALUES ("1970-01-01", 5.303083, 551622975, 1197533121, 0, 7, 99696.76384157, true, "1970-01-01", false, "1970-01-01 08:00:00", "1970-01-01 08:00:00", 9, false, true, 0.7552708837260608);

```
2. mysql> SELECT COUNT(*) FROM t0, t2, t1 WHERE CAST(CASE  WHEN ((((("")||("")))||(NULL)))  BETWEEN (CAST(((-1782983271)+(-1089441619)) AS STRING ) ) AND ("")  THEN t2.c_2_10  WHEN  ( t2.c_2_15 ) > ( t2.c_2_15 )  THEN "1969-12-28 19:46:52"  WHEN true THEN t2.c_2_10  WHEN true THEN t2.c_2_10 ELSE t2.c_2_10 END AS BOOLEAN ) ;
```
+----------+
| count(*) |
+----------+
|        4 |
+----------+
1 row in set (0.04 sec)

```
mysql> SELECT SUM(count) FROM (SELECT CAST((CAST(CAST(CASE  WHEN ((((("")||("")))||(NULL)))  BETWEEN (CAST(((-1782983271)+(-1089441619)) AS STRING ) ) AND ("")  THEN t2.c_2_10  WHEN  ( t2.c_2_15 ) > ( t2.c_2_15 )  THEN "1969-12-28 19:46:52"  WHEN true THEN t2.c_2_10  WHEN true THEN t2.c_2_10 ELSE t2.c_2_10 END AS BOOLEAN )  AS BOOLEAN) = true) AND (CAST(CAST(CASE  WHEN ((((("")||("")))||(NULL)))  BETWEEN (CAST(((-1782983271)+(-1089441619)) AS STRING ) ) AND ("")  THEN t2.c_2_10  WHEN  ( t2.c_2_15 ) > ( t2.c_2_15 )  THEN "1969-12-28 19:46:52"  WHEN true THEN t2.c_2_10  WHEN true THEN t2.c_2_10 ELSE t2.c_2_10 END AS BOOLEAN )  AS BOOLEAN) IS NOT NULL) AS INT) as count FROM t0, t2, t1 ) t;
```
+------------+
| sum(count) |
+------------+
|          0 |
+------------+

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - main Release
 - mysql> select current_version();
+---------------------------------+
| current_version()               |
+---------------------------------+
| SQLANCER_02_RELEASE 3ff7605 |
+---------------------------------+

**Comment by Seaven** [comment]
Fixed
