### ISSUE TITLE
The JAVA_OPTS conf does not seem to be taking effect in the CN nodes

### ISSUE THREAD

**Issue by metalshanked** [StarRocks/starrocks#40151]
The JAVA_OPTS conf does not seem to be taking effect in the CN nodes
It works fine in the FE nodes

Running in shared data mode with only FE and CN Nodes
below is the `cn.conf`
```
JAVA_OPTS_FOR_JDK_9_AND_LATER="-Djava.security.krb5.conf=/etc/krb5.conf"
JAVA_OPTS_FOR_JDK_9="-Djava.security.krb5.conf=/etc/krb5.conf"
JAVA_OPTS_FOR_JDK_11="-Djava.security.krb5.conf=/etc/krb5.conf"
JAVA_OPTS="-Djava.security.krb5.conf=/etc/krb5.conf"
sys_log_level = DEBUG
# ports for admin, web, heartbeat service
thrift_port = 9060
webserver_port = 8040
heartbeat_service_port = 9050
brpc_port = 8060
starlet_port = 9070
storage_root_path = ${STARROCKS_HOME}/storage
```
Running `jps -lvm` on CN Pods do not show above OPTS
FE picks it up fine with same command to check

### StarRocks version (Required)
 - 3.2.2 on K8s Operator

**Comment by kevincai** [comment]
there is no java process running on be/cn node, BE/CN will launch JVM via jni. I guess that might be the reason `jps` doesn't show anything.

**Comment by kevincai** [comment]
can you enter the cn pod and take a look at `/proc/<cn_pid>/environ`, check the environment variables such as `JAVA_*` and `LIBHDFS_*`.

**Comment by metalshanked** [comment]
> can you enter the cn pod and take a look at `/proc/<cn_pid>/environ`, check the environment variables such as `JAVA_*` and `LIBHDFS_*`.

Thanks for the info. I found that JAVA options espcially for kerberos are not required for CN nodes.
But still here is what i did to add it to CN
Used a `_JAVA_OPTIONS` env variable in the CN Pods and it gets picked up.  No other variable works.
My ubuntu pod has JDK11
