### ISSUE TITLE
query result error in norec mode(pipeline off)

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#4017]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS n0;
CREATE DATABASE n0;
USE n0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DECIMAL(20, 11)  NULL ,c_0_1 CHAR(1) NULL ,c_0_2 DATE NULL ,c_0_3 BOOLEAN NOT NULL ,c_0_4 BIGINT NULL ,c_0_5 DATE NOT NULL ,c_0_6 INT NULL ,c_0_7 BIGINT NOT NULL ,c_0_8 BOOLEAN NULL ,c_0_9 DECIMAL(13, 1)  NULL ,c_0_10 LARGEINT NOT NULL ,c_0_11 DATE NULL ,c_0_12 DOUBLE NULL ,c_0_13 CHAR(1) NULL ,c_0_14 BOOLEAN NULL ,c_0_15 DOUBLE NULL ) UNIQUE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5,c_0_6,c_0_7,c_0_8,c_0_9) DISTRIBUTED BY HASH (c_0_6) properties("replication_num"="3") ;
CREATE TABLE t1 (c_1_0 DECIMAL(16, 2)  NOT NULL ,c_1_1 CHAR(21) NOT NULL ,c_1_2 BOOLEAN REPLACE NOT NULL ,c_1_3 DATE REPLACE NULL ,c_1_4 FLOAT MAX NOT NULL ,c_1_5 DATE MIN NULL ,c_1_6 DATE MIN NULL ,c_1_7 CHAR(41) REPLACE_IF_NOT_NULL NOT NULL ,c_1_8 BITMAP BITMAP_UNION NOT NULL ,c_1_9 BOOLEAN REPLACE NULL ,c_1_10 DATE REPLACE NOT NULL ,c_1_11 DOUBLE REPLACE_IF_NOT_NULL NOT NULL ,c_1_12 HLL HLL_UNION NOT NULL ,c_1_13 BITMAP BITMAP_UNION NULL ) AGGREGATE KEY (c_1_0,c_1_1) DISTRIBUTED BY HASH (c_1_0) properties("replication_num"="3") ;
INSERT INTO t0 VALUES (0.00414971815, "", "1970-01-01", true, -1202698265, "1970-01-01", 17, -626280778, true, 96592323390.5, -1880077726, "1970-01-01", NULL, "", NULL, -6.26280778E8), (0.00403150927, "", "1970-01-01", false, -393428342, "1970-01-01", 21, -393428342, true, 49489048723.8, -626280778, "1970-01-01", 0.4088173323442733, "", false, 0.4088173323442733), (0.00198217958, "", "1970-01-01", true, -1880077726, "1970-01-01", 31, -151952445, false, 59403233277.0, 375328224, "1970-01-01", -1.880077726E9, "", false, NULL), (0.00098772201, "", "1970-01-01", false, -151952445, "1970-01-01", 12, 206718732, NULL, NULL, -834645119, "1970-01-01", 0.23246975853945862, "", true, -1.880077726E9);
INSERT INTO t1 VALUES (144164626268.99, "w", true, "1970-01-01", 0.6068429090031373, "1970-01-01", "1970-01-01", "", bitmap_hash(""), false, "1970-01-01", 0.855085549352562, hll_hash(""), bitmap_hash("wwD"));
INSERT INTO t1 VALUES (340553199079.07, "l", false, "1970-01-01", 0.7820025184677747, "1970-01-01", "1970-01-01", "6N", bitmap_hash("e"), false, "1970-01-01", 0.1999436722302229, hll_hash("Uyv"), bitmap_hash("b0G7Bh")), (727554271400.32, "n3jKqrl1", true, "1970-01-01", 0.10682929807376551, "1970-01-01", "1970-01-01", "Q91", bitmap_hash("VSw"), true, "1970-01-01", 0.7880423474440651, hll_hash("I"), bitmap_hash("2lTfhiL"));
INSERT INTO t1 VALUES (519682536180.40, "hZ", true, NULL, 0.35268028499816695, "1970-01-01", "1970-01-01", "xD9", bitmap_hash("wxw8"), false, "1970-01-01", 0.894935021544012, hll_hash("HU"), bitmap_hash(""));
INSERT INTO t0 VALUES (0.00214511219, "", NULL, false, 2056281553, "1970-01-01", 29, -626280778, NULL, 94384251366.9, 492032219, "1970-01-01", NULL, "", false, 0.27743044020048224);
INSERT INTO t0 VALUES (0.00299882881, NULL, "1970-01-01", true, 492032219, "1970-01-01", 13, 375328224, true, 39658637619.9, 1686834298, NULL, 0.645015404844541, "", true, 0.3699205055375684), (0.00645089381, NULL, "1970-01-01", true, -2057652610, "1970-01-01", 0, -534889101, NULL, 71459813851.9, 953916158, "1970-01-01", -8.34645119E8, "", true, 3.75328224E8);
INSERT INTO t0 VALUES (0.00335860772, "", "1970-01-01", false, -678385343, "1970-01-01", 0, 148822831, false, 34317565472.7, 1686834298, "1970-01-01", -1.880077726E9, "", true, 0.28988320840941395), (0.00403540929, "", "1970-01-01", true, -2035159022, "1970-01-01", 15, 1059677360, true, 74217647549.2, -393428342, "1970-01-01", 0.36181733387218007, "", true, 4.92032219E8), (0.00753403557, "", "1970-01-01", true, -534889101, "1970-01-01", 21, 492032219, NULL, 37957638375.4, 1495349208, "1970-01-01", 2.06718732E8, "", false, 0.10682929807376551);
INSERT INTO t1 VALUES (644405933656.22, "ysOs", true, "1970-01-01", 0.36181733387218007, "1970-01-01", "1970-01-01", "", bitmap_hash("6DTF0e3Tc"), true, "1970-01-01", 0.6219280111029066, hll_hash("Y"), bitmap_hash("QQ")), (503440575250.14, "", false, "1970-01-01", 0.24595414296464435, "1970-01-01", "1970-01-01", "", bitmap_hash(""), true, "1970-01-01", NULL, hll_hash("QNEBCvjyd"), bitmap_hash("j7Jo"));
INSERT INTO t1 VALUES (473651944815.06, "K", false, "1970-01-01", 0.10682929807376551, "1970-01-01", "1970-01-01", "", bitmap_hash("t"), NULL, "1970-01-01", 0.02739030990513569, hll_hash("G"), bitmap_hash("W1jSPB"));
INSERT INTO t1 VALUES (432222989749.44, "AD", false, "1970-01-01", -5.34889101E8, "1970-01-01", "1970-01-01", "IB", bitmap_hash("C5"), false, "1970-01-01", NULL, hll_hash("w"), bitmap_hash("k")), (463278801437.38, "", true, "1970-01-01", 0.7634918420474657, "1970-01-01", "1970-01-01", "w7y", bitmap_hash(""), false, "1970-01-01", 0.1960382443350519, hll_hash("Za3ddp"), bitmap_hash(""));
INSERT INTO t0 VALUES (0.00182320180, NULL, "1970-01-01", true, -2089142483, "1970-01-01", 11, 1445220912, true, 11387114313.6, 721241933, "1970-01-01", 1.48822831E8, "", false, 0.37709984372865046), (0.00741513335, "", "1970-01-01", false, 1446106578, "1970-01-01", 5, 1097718787, false, 70471191450.1, 1662829264, "1970-01-01", 0.7735941439265194, "", true, 0.44580177869508486), (0.00919646377, "", "1970-01-01", false, 1059677360, "1970-01-01", NULL, -1072032615, true, 10536638350.1, 566888785, "1970-01-01", NULL, "", true, 0.4922242315208375);
INSERT INTO t0 VALUES (0.00933416618, "", "1970-01-01", true, NULL, "1970-01-01", 13, -944106886, NULL, 8799020380.2, -1425527842, "1970-01-01", 0.28988320840941395, NULL, true, NULL);
INSERT INTO t0 VALUES (0.00037115574, "", "1970-01-01", true, NULL, "1970-01-01", 4, -40121114, NULL, 73703224717.9, 1446106578, "1970-01-01", 1.446106578E9, "", true, -2.05765261E9), (NULL, "", "1970-01-01", false, 1473335222, "1970-01-01", 2, -102132847, true, 21118511350.9, -40121114, "1970-01-01", 0.4355015040001543, "", true, 0.8827962742040042);
INSERT INTO t1 VALUES (496930373014.29, "xJ9poh", false, "1970-01-01", 0.014170412033948532, "1970-01-01", "1970-01-01", "nF", bitmap_hash("XRrcNm1we"), false, "1970-01-01", 0.7419683098764112, hll_hash("73LiC"), bitmap_hash("p")), (102101999717.43, "", false, NULL, 0.3699205055375684, "1970-01-01", "1970-01-01", "r2", bitmap_hash(""), true, "1970-01-01", 0.05729421408928581, hll_hash("En1s"), bitmap_hash("Z")), (189110180688.76, "", false, "1970-01-01", 1.7976931348623157E308, "1970-01-01", NULL, "", bitmap_hash("DFWwQ"), true, "1970-01-01", 4.92032219E8, hll_hash("s"), bitmap_hash("5"));
INSERT INTO t1 VALUES (733790083289.91, "oWuV", true, "1970-01-01", 0.2113474918162921, "1970-01-01", "1970-01-01", "6x", bitmap_hash("n93j1y5"), true, "1970-01-01", 0.7735941439265194, hll_hash(""), bitmap_hash("")), (525772524208.20, "lxw", true, "1970-01-01", 0.32107831793427877, "1970-01-01", "1970-01-01", NULL, bitmap_hash("LgtLW"), true, "1970-01-01", 4.92032219E8, hll_hash("kDB"), bitmap_hash(""));
INSERT INTO t1 VALUES (157175983638.20, "3", false, "1970-01-01", 0.830867628431417, "1970-01-01", "1970-01-01", "amZ57Q", bitmap_hash("gO"), true, "1970-01-01", 5.66888785E8, hll_hash("m"), bitmap_hash("l"));
INSERT INTO t0 VALUES (0.00825085267, "", "1970-01-01", true, -543884901, "1970-01-01", 7, 2110663888, true, 21877281463.6, -1659010482, "1970-01-01", 0.43809670507223364, "", true, 0.43809670507223364), (0.00855384772, "", "1970-01-01", false, -841147320, "1970-01-01", 17, -1375880641, true, 74627234230.5, -1657458593, "1970-01-01", NULL, NULL, NULL, 0.02739030990513569);

```
2. mysql> SELECT COUNT(*) FROM t1, t0 WHERE CAST(CASE  WHEN (NOT (NULL)) THEN "1970-01-21"  WHEN (t1.c_1_10)  BETWEEN (t1.c_1_10) AND (t1.c_1_10)  THEN t1.c_1_6 ELSE "1970-01-10" END AS BOOLEAN ) ;
+----------+
| count(*) |
+----------+
|      252 |
+----------+
1 row in set (0.01 sec)
```
```
mysql> SELECT SUM(count) FROM (SELECT CAST((CAST(CAST(CASE  WHEN (NOT (NULL)) THEN "1970-01-21"  WHEN (t1.c_1_10)  BETWEEN (t1.c_1_10) AND (t1.c_1_10)  THEN t1.c_1_6 ELSE "1970-01-10" END AS BOOLEAN )  AS BOOLEAN) = true) AND (CAST(CAST(CASE  WHEN (NOT (NULL)) THEN "1970-01-21"  WHEN (t1.c_1_10)  BETWEEN (t1.c_1_10) AND (t1.c_1_10)  THEN t1.c_1_6 ELSE "1970-01-10" END AS BOOLEAN )  AS BOOLEAN) IS NOT NULL) AS INT) as count FROM t1, t0 ) t;
+------------+
| sum(count) |
+------------+
|          0 |
+------------+
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - main Release
 - mysql> select current_version();
+---------------------------------+
| current_version()               |
+---------------------------------+
| SQLANCER_01_RELEASE 3ff7605 |
+---------------------------------+

**Comment by Seaven** [comment]
Fixed
