### ISSUE TITLE
Reorder predicates based on selectivity【Challenging】

### ISSUE THREAD

**Issue by wuqiao** [StarRocks/starrocks#4024]
# Requirement Description
Reorder predicate execution order based on selectivity.
1. Estimate the selectivity of each predicate
2. Reorder predicates by selectivity, predicates with higher selectivity should be executed first.

# Mentor
@Seaven 

# Registration procedure

**Step 1.** Add a comment when you sign up. The comment can be a brief self-introduction and reason for signing up, including what you do, what you're good at, what you're interested in and your technology stack, and how familiar you are with StarRocks. Example:

> I pick! My name is Johnny. I am from StarRocks and I have been working on database kernel development for 1 year. I am interested in OLAP, good at C++ programming, and have been using StarRocks for 6 months. I chose to solve this issue because I am familiar with execution engine.

**Step 2.** On your WeChat, add the StarRocks community assistant "**_StarRocks-1_**" as a WeChat friend and leave your GitHub ID. The assistant will invite you to a WeChat group based on the issue you picked.

**Step 3.** The mentor will communicate with all the participants who picked this issue and assign the task to the best match. 

# Before you start
1. Read the StarRocks [GitHub workflow](https://github.com/StarRocks/community/blob/main/Contributors/guide/workflow.md) carefully, which provides the configurations of BE and FE and describes how to submit a pull request.
2. To learn more about StarRocks, read [StarRocks documentation](https://github.com/StarRocks/docs/blob/main/TOC.md).

# Pull request requirements

1. After you complete code development, upload the code to the StarRocks code repo as a pull request (PR).

  - PR title format: **[SR GeekCamp] + PR title**
  - Labels ：[Geek Camp 2022/feature]
2. After you submit your PR, comment on the status of your PR submission as requested under the Pinned Issue [[StarRocks geek Camp 2022] ](https://github.com/StarRocks/starrocks/issues/4008)page.

  - Comment format: **"I have finished Issue #" + PR link id**

**Comment by blackstar-baba** [comment]
LGTM ! My name is blackstar-baba. I am from Peixi-IOT and I have been working on database kernel development for 1 year. I am interested in OLAP, good at Java programming, and have some experience in simple C++ programming, and have been using StarRocks for 4 months. I also solved https://github.com/StarRocks/starrocks/issues/3180 & https://github.com/StarRocks/starrocks/issues/3181 issues. I chose to solve this issue because I am familiar with Planner.

**Comment by blackstar-baba** [comment]
Hello,@Seaven. Is there anything I can prepare for?

**Comment by ikaruga4600** [comment]
I pick! My name is Zhongjian Sun. I am from Beike and I have been working on olap devops for 1 year. I am interested in OLAP, good at JAVA programming,  have a little experience in C++, and have been using StarRocks for more than 1 years. I chose to solve this issue because I am familiar with CBO planner.

**Comment by Seaven** [comment]
> Hello,@Seaven. Is there anything I can prepare for?

1. Learn the code of the optimizer/statistic, where need the feature?
2. Learn the code of the predicate/funciton, to get the execution logic of each predicate 
3. Find some ways to evaluate selectivity, maybe from peper, or other system.

**Comment by blackstar-baba** [comment]
Do you have any recommended papers ? @Seaven

**Comment by blackstar-baba** [comment]
I know StarRocks some optimizations base on CBO which statistic table informations in background ,  so this issue use CBO to evaluate selectivity?

**Comment by Seaven** [comment]
Like:
https://courses.cs.washington.edu/courses/cse544/11wi/papers/markl-vldb-2005.pdf
http://www.vldb.org/pvldb/vol12/p1044-dutt.pdf
http://www.cs.columbia.edu/~gravano/Papers/2004/icde04.pdf

Selectivity estimate is a hard question, you can refer to these papers, but I think it may be difficult to implement them directly, and starrocks doesn't support many complex statistics. So we want to use the current statistics to support some common predicate selectivity derivation

**Comment by Seaven** [comment]
Prepare
1. Learn the code of the optimizer/statistic, where need the feature?
2. Learn the code of the predicate/funciton, to get the execution logic of each predicate

Develop
1. Support detailed design documents
2. Support a predicates reorder framework on optimizer
3. Support some simple function or predicate reorder

Challenge(optional, not required):
1. To research or develop selectivity estimate method.
2. Implement the selectivity estimation of most functions or predicates

**Comment by blackstar-baba** [comment]
My idea:
1. After physicalRuleRewrite, add logic to rewrite predicate in function optimize which in class Optimize
2. The logic like this: Iteratively filter PhysicalOlapScanOperator in optExpression, filter CompoundPredicateOperator which in PhysicalOlapScanOperator predicate property and get children in CompoundPredicateOperator,  if children size equals 2, compare and swap it conditional, if children has childen, iterative it.


Some codes like this:
1. edit method `optimize` 
```
.......
.......
.......
result = physicalRuleRewrite(rootTaskContext, result); //改写物理计划
//rewrite predicate
result = predicateRewrite(result);

return result;
```
2. add method `predicateRewrite`
```
private OptExpression predicateRewrite(OptExpression optExpression) {
    // process PhysicalOlapScanOperator, iterator
    if(optExpression.getOp() instanceof PhysicalOlapScanOperator) {
        PhysicalOlapScanOperator op = (PhysicalOlapScanOperator) optExpression.getOp();
        ScalarOperator predicate = op.getPredicate();
        //check predicate type
        if(predicate == null || !(predicate instanceof CompoundPredicateOperator)) {
            return optExpression;
        }
        CompoundPredicateOperator compoundPredicateOperator = (CompoundPredicateOperator) predicate;
        //reorder predicate
        predicateRewrite(compoundPredicateOperator.getChildren(), optExpression.getStatistics());
    } else {
        List<OptExpression> inputs = optExpression.getInputs();
        for (int i = 0; i < inputs.size(); i++) {
            predicateRewrite(inputs.get(i));
        }
    }
    return optExpression;
}
```
4. add method `predicateRewrite`
```
private void predicateRewrite(List<ScalarOperator> children, Statistics statistics) {
    if(children == null || children.size() == 0 ) {
        return;
    }
    if(children.size() == 2){
        ColumnStatistic leftColumnStatistics = ExpressionStatisticCalculator.calculate(children.get(0), statistics);
        ColumnStatistic rightColumnStatistics = ExpressionStatisticCalculator.calculate(children.get(1), statistics);
        predicateRewrite(children.get(0).getChildren(), statistics);
        predicateRewrite(children.get(1).getChildren(), statistics);
        //todo compare left and right, if left selectivity > right selectivity, swap it
        // only use averageRowSize now
        if(leftColumnStatistics.getAverageRowSize() > rightColumnStatistics.getAverageRowSize()) {
            ScalarOperator tempScalarOperator = children.get(0);
            children.set(0,children.get(1));
            children.set(1,tempScalarOperator);
        }
    } else if(children.size() == 1){
        predicateRewrite(children.get(0).getChildren(), statistics);
    } else {
        // must not here
    }
}
```

**Comment by blackstar-baba** [comment]
@Seaven  Code link: https://github.com/StarRocks/starrocks/compare/main...blackstar-baba:issue-4024

**Comment by Seaven** [comment]
I've review your idea, it's cool, and I have some comment about your code:
1. Every node need order predicate, not only scan node
2. Refactor your code like PhysicalRule plz

**Comment by blackstar-baba** [comment]
@Seaven I write a design document in Feishu,please take a look.
Docs Link:https://qp40s7cffx.feishu.cn/docs/doccnkgEJTc8hoI2u0Cg6ZMhncc 
Password: 8U3v

**Comment by blackstar-baba** [comment]
#### Table data
```
mysql> select * from test.table1;
+--------+----------+----------+------+
| siteid | citycode | username | pv   |
+--------+----------+----------+------+
|      3 |        3 | my       |    3 |
|      1 |        1 | my       |    1 |
|      2 |        2 | my       |    2 |
+--------+----------+----------+------+
3 rows in set (0.05 sec)
```
#### Table statistics
```
mysql> select * from _statistics_.table_statistic_v1;
+----------+-------------+-------+-------------+----------------------+-----------+-----------+----------------+------------+------+------+---------------------+
| table_id | column_name | db_id | table_name  | db_name              | row_count | data_size | distinct_count | null_count | max  | min  | update_time         |
+----------+-------------+-------+-------------+----------------------+-----------+-----------+----------------+------------+------+------+---------------------+
|    10005 | siteid      | 10003 | test.table1 | default_cluster:test |         3 |        12 |              3 |          0 | 3    | 1    | 2022-04-15 14:27:52 |
|    10005 | username    | 10003 | test.table1 | default_cluster:test |         3 |         6 |              1 |          0 | my   | my   | 2022-04-15 14:27:52 |
|    10005 | citycode    | 10003 | test.table1 | default_cluster:test |         3 |         6 |              3 |          0 | 3    | 1    | 2022-04-15 14:27:52 |
+----------+-------------+-------+-------------+----------------------+-----------+-----------+----------------+------------+------+------+---------------------+
3 rows in set (0.05 sec)
```
### Table  query explain
```
mysql> explain select * from test.table1 where citycode < 2 and siteid > 3;
+-----------------------------------------------------------------------------+
| Explain String                                                              |
+-----------------------------------------------------------------------------+
| PLAN FRAGMENT 0                                                             |
|  OUTPUT EXPRS:1: siteid | 2: citycode | 3: username | 4: pv                 |
|   PARTITION: UNPARTITIONED                                                  |
|                                                                             |
|   RESULT SINK                                                               |
|                                                                             |
|   1:EXCHANGE                                                                |
|                                                                             |
| PLAN FRAGMENT 1                                                             |
|  OUTPUT EXPRS:                                                              |
|   PARTITION: RANDOM                                                         |
|                                                                             |
|   STREAM DATA SINK                                                          |
|     EXCHANGE ID: 01                                                         |
|     UNPARTITIONED                                                           |
|                                                                             |
|   0:OlapScanNode                                                            |
|      TABLE: table1                                                          |
|      PREAGGREGATION: OFF. Reason: None aggregate function                   |
|      PREDICATES: 1: siteid > 3, 2: citycode < 2                             |
|      partitions=1/1                                                         |
|      rollup: table1                                                         |
|      tabletRatio=10/10                                                      |
|      tabletList=10007,10009,10011,10013,10015,10017,10019,10021,10023,10025 |
|      cardinality=1                                                          |
|      avgRowSize=4.0                                                         |
|      numNodes=0                                                             |
+-----------------------------------------------------------------------------+
27 rows in set (0.03 sec)
```
expression `citycode < 2` after expression `siteid > 3` now!
