### ISSUE TITLE
Distributed execution of count distinct for multiple columns 【Moderate】

### ISSUE THREAD

**Issue by wuqiao** [StarRocks/starrocks#4025]
# Requirement Description
Starrocks support mutli_count_distinct function to reslove multi-column count distinct, like SQL
`SELECT v1, count(distinct v2), count(distinct v3) from t1 group by v1`.

But for SQL: `SELECT count(distinct v2), count(distinct v3) from t1`, which one without `group by`, the second phase of mutli_count_distinct must be gather to one instance, it's poor performance.

the process of the function: 
1. recorde values to a set
2. gather to one instance and merge the set
3. output the cardinality of this set

In addition, we can support some other solution:
* rewrite SQL with Grouping set if the aggregate without `group by`

e.g. `SELECT count(distinct v2), count(distinct v3) from t1`
after rewrite: `select count(v2), count(v3) from (select v2, v3 from t1 group by grouping sets ((v2), (v3))) as xx`

This takes advantage of distributed execution.
And rewrite by Grouping set also work on aggregate with `group by`, but this isn't a big advantage over the original, so we only support the optimizition when the aggregate without `group by`.

# Mentor
@Seaven 

# Registration procedure

**Step 1.** Add a comment when you sign up. The comment can be a brief self-introduction and reason for signing up, including what you do, what you're good at, what you're interested in and your technology stack, and how familiar you are with StarRocks. Example:

> I pick! My name is Johnny. I am from StarRocks and I have been working on database kernel development for 1 year. I am interested in OLAP, good at C++ programming, and have been using StarRocks for 6 months. I chose to solve this issue because I am familiar with execution engine.

**Step 2.** On your WeChat, add the StarRocks community assistant "**_StarRocks-1_**" as a WeChat friend and leave your GitHub ID. The assistant will invite you to a WeChat group based on the issue you picked.

**Step 3.** The mentor will communicate with all the participants who picked this issue and assign the task to the best match. 

# Before you start
1. Read the StarRocks [GitHub workflow](https://github.com/StarRocks/community/blob/main/Contributors/guide/workflow.md) carefully, which provides the configurations of BE and FE and describes how to submit a pull request.
2. To learn more about StarRocks, read [StarRocks documentation](https://github.com/StarRocks/docs/blob/main/TOC.md).

# Pull request requirements

1. After you complete code development, upload the code to the StarRocks code repo as a pull request (PR).

  - PR title format: **[SR GeekCamp] + PR title**
  - Labels ：[Geek Camp 2022/feature]
2. After you submit your PR, comment on the status of your PR submission as requested under the Pinned Issue [[StarRocks geek Camp 2022] ](https://github.com/StarRocks/starrocks/issues/4008)page.

  - Comment format: **"I have finished Issue #" + PR link id**

**Comment by ylcq** [comment]
My name is YangLian, I have been working on machine learning algorithms development for 3 years using C++ programming; working on data development for 2.5 years using Java programming. I have been using StarRocks for 4 months. I am interested in OLAP and StarRocks and our company has been introduced StarRocks, so I chose to solve this issue to contribute to the community.

**Comment by wangxiaobaidu11** [comment]
my name is wangxiao, beke olap team. I want to pick it

**Comment by beyond-up** [comment]
I pick! My name is WuChang. I have been working on olap team for 1 year. I am interested in OLAP, good at Java programming, and have been using StarRocks for 6 months. I chose to solve this issue because I am familiar with execution engine.

**Comment by Seaven** [comment]
Prepare
1. Learn optimizer of StarRocks, get how to add a rule
2. Learn the plan of count distinct for multiple columns

Develop
1. Support distributed execution of count distinct for multiple columns
2. Catch a performance about the optimization

Challenge(optional, not required):
1. To find or research other optimization ways, can refer to papers or other systems

**Comment by xiang2102** [comment]
I pick! My name is ShanXiang. I'm from Qunar. I am interested in OLAP and StarRocks, good at Java programming and have not used StarRocks.I chose to solve this issue to contribute to the community.
