### ISSUE TITLE
Support AWS Glue with Starrocks  Running Locally 

### ISSUE THREAD

**Issue by soumilshah1995** [StarRocks/starrocks#40290]
Step 1: 
```
wget https://raw.githubusercontent.com/starrocks/demo/master/deploy/docker-compose/docker-compose.yml

```

step 2 
```
docker-compose up --build -d
```

# Step 3 ;

Exec into container 
```
mysql -P9030 -h127.0.0.1 -uroot --prompt="StarRocks > "

```

```
CREATE EXTERNAL CATALOG hudi_catalog_glue
PROPERTIES
(
    "type" = "hive",
    "hive.metastore.type" = "glue",
    "aws.glue.use_instance_profile" = "true",
     "aws.glue.region" = "us-east-1",
    "hive.metastore.uris" = "thrift://localhost:9083",
    "aws.s3.use_instance_profile" = "true",
    "aws.glue.access_key" = "XX",
    "aws.glue.secret_key" = "XX",
    "aws.s3.secret_key" = "XX",
    "aws.s3.secret_key" = "XX"
);


```

Error 
StarRocks > show databases;
ERROR 1064 (HY000): Failed to getAllDatabases, msg: Unable to instantiate com.starrocks.connector.hive.glue.AWSCatalogMetastoreClient
StarRocks >

**Comment by alberttwong** [comment]
I don't think glue will work because they don't publish instructions on how to get HMS with thrift running locally.

**Comment by soumilshah1995** [comment]
Agree with you

Thanking You,
Soumil Nitin Shah

B.E in Electronic
MS Electrical Engineering
MS  Computer Engineering
+1-646 204 5957
