### ISSUE TITLE
Hive external tables support schema change【Easy】

### ISSUE THREAD

**Issue by wuqiao** [StarRocks/starrocks#4030]
# Requirement Description

Currently StarRocks supports querying hive external table. The table/partition and other information in hive external table are obtained from the hive metastore and cached in the StarRocks FE. Hive partitions and cached statistics such as row count and file location can be refreshed and synchronized by manually executing the refresh table syntax or enabling the StarRocks automatic incremental synchronization option.

The schema of hive table in FE cannot be changed after external table is created. Therefore, if the user's original hive table is schema changed (such as add/drop column, etc.) , the user needs to recreate the hive external table to obtain the correct result.

We need to support schema changes so that users can get correct query results without having to recreate the external table.We may support schema changes in the following two aspects:

- refresh external table
- Background automatic incremental synchronization hive metastore cache

# Mentor
@stephen-shelby 

# Registration procedure

**Step 1.** Add a comment when you sign up. The comment can be a brief self-introduction and reason for signing up, including what you do, what you're good at, what you're interested in and your technology stack, and how familiar you are with StarRocks. Example:

> I pick! My name is Johnny. I am from StarRocks and I have been working on database kernel development for 1 year. I am interested in OLAP, good at C++ programming, and have been using StarRocks for 6 months. I chose to solve this issue because I am familiar with execution engine.

**Step 2.** On your WeChat, add the StarRocks community assistant "**_StarRocks-1_**" as a WeChat friend and leave your GitHub ID. The assistant will invite you to a WeChat group based on the issue you picked.

**Step 3.** The mentor will communicate with all the participants who picked this issue and assign the task to the best match. 

# Before you start
1. Read the StarRocks [GitHub workflow](https://github.com/StarRocks/community/blob/main/Contributors/guide/workflow.md) carefully, which provides the configurations of BE and FE and describes how to submit a pull request.
2. To learn more about StarRocks, read [StarRocks documentation](https://github.com/StarRocks/docs/blob/main/TOC.md).

# Pull request requirements

1. After you complete code development, upload the code to the StarRocks code repo as a pull request (PR).

  - PR title format: **[SR GeekCamp] + PR title**
  - Labels ：[Geek Camp 2022/feature]
2. After you submit your PR, comment on the status of your PR submission as requested under the Pinned Issue [[StarRocks geek Camp 2022] ](https://github.com/StarRocks/starrocks/issues/4008)page.

  - Comment format: **"I have finished Issue #" + PR link id**

**Comment by Im-Manshushu** [comment]
My name is WangMan. I'd like to pick this issue. I started using it very early StarRocks. From version 1.14 to 2.1.  I chose to solve this problem because I am familiar with using starrocks and  I am big data development engineer from beijing  and good at Java programming and and a little knowledge of C + + programming.I hope I can contribute a little to the community. Complete the task

**Comment by hiliuxg** [comment]
I pick! My name is hiliuxg. I am from Kugou Music and I have worked in big data development for 5 years . I am interested in OLAP, good at JAVA programming, and have been using StarRocks for 1 year.  I like starrocks community and hope to contribute.

**Comment by Zhangruichao** [comment]
I pick!! My name is ZhangRuichao. As a StarRocks deep user, I want to do my best to make the StarRocks great. so here i am.

**Comment by wangxiaobaidu11** [comment]
I pick! beike olap team

**Comment by ericdoug-qi** [comment]
I pick! My name is eric, I have been learning on database kernel development for 1 year. I am interested in OLAP, good at C++ programming. I think it is a good chance to join the StarRocks community and read the code.

**Comment by xdlequ** [comment]
I pick! My name is LeQu. I have worked in big data area for 2 years . I am interested in OLAP, good at Java programming, and have been using StarRocks for 1 year. I chose to solve this issue because I am interested in Data Lake warehouse .I think it is a good chance to join the StarRocks community and read the code. I like StarRocks and hope that StarRocks will become better and better.
