### ISSUE TITLE
Support GBK character set【Moderate】

### ISSUE THREAD

**Issue by wuqiao** [StarRocks/starrocks#4033]
# Requirement Description
1.Support GBK character set defination when create table e.g.
create table test
(
c1 varchar(10) charset utf8 collate utf8_romanian_ci not null
)DEFAULT CHARSET=gbk;

2.Consider metadata when designing.
e.g. status or show collation command, session variables.

3.In the storage layer, it needs to be stored in the form of GBK

# Mentor
@Astralidea 

# Registration procedure

**Step 1.** Add a comment when you sign up. The comment can be a brief self-introduction and reason for signing up, including what you do, what you're good at, what you're interested in and your technology stack, and how familiar you are with StarRocks. Example:

> I pick! My name is Johnny. I am from StarRocks and I have been working on database kernel development for 1 year. I am interested in OLAP, good at C++ programming, and have been using StarRocks for 6 months. I chose to solve this issue because I am familiar with execution engine.

**Step 2.** On your WeChat, add the StarRocks community assistant "**_StarRocks-1_**" as a WeChat friend and leave your GitHub ID. The assistant will invite you to a WeChat group based on the issue you picked.

**Step 3.** The mentor will communicate with all the participants who picked this issue and assign the task to the best match. 

# Before you start
1. Read the StarRocks [GitHub workflow](https://github.com/StarRocks/community/blob/main/Contributors/guide/workflow.md) carefully, which provides the configurations of BE and FE and describes how to submit a pull request.
2. To learn more about StarRocks, read [StarRocks documentation](https://github.com/StarRocks/docs/blob/main/TOC.md).

# Pull request requirements

1. After you complete code development, upload the code to the StarRocks code repo as a pull request (PR).

  - PR title format: **[SR GeekCamp] + PR title**
  - Labels ：[Geek Camp 2022/feature]
2. After you submit your PR, comment on the status of your PR submission as requested under the Pinned Issue [[StarRocks geek Camp 2022] ](https://github.com/StarRocks/starrocks/issues/4008)page.

  - Comment format: **"I have finished Issue #" + PR link id**

**Comment by complone** [comment]
@wuqiao Hello, my name is Cheng Xingyuan. I have been working in big data for two years and back-end development for one year. My blog is https://juejin.cn/user/2875978147955741 . I want to choose this issue because I want to contribute to starrocks

**Comment by zdsg1024** [comment]
My name is Xuhao Zhao, graduated for two years, has been focusing on the field of big data, has done digital warehouse development, big data development, and is now a database delivery engineer in Beijing, good at Java language, C++ language is only slightly understood in school; mainly read Sang Boss's book, so I am very interested in this challenge item;
