### ISSUE TITLE
Develop a tool for managing multiple StarRocks clusters【Easy】

### ISSUE THREAD

**Issue by wuqiao** [StarRocks/starrocks#4034]
# Requirement Description
1.Support to install StarRocks clusters
2.Support to scale in and scale out  StarRocks clusters
3.Support to upgrade and downgrade  StarRocks clusters

# Mentor
@LittleBeeBee

# Registration procedure

**Step 1.** Add a comment when you sign up. The comment can be a brief self-introduction and reason for signing up, including what you do, what you're good at, what you're interested in and your technology stack, and how familiar you are with StarRocks. Example:

> I pick! My name is Johnny. I am from StarRocks and I have been working on database kernel development for 1 year. I am interested in OLAP, good at C++ programming, and have been using StarRocks for 6 months. I chose to solve this issue because I am familiar with execution engine.

**Step 2.** On your WeChat, add the StarRocks community assistant "**_StarRocks-1_**" as a WeChat friend and leave your GitHub ID. The assistant will invite you to a WeChat group based on the issue you picked.

**Step 3.** The mentor will communicate with all the participants who picked this issue and assign the task to the best match. 

# Before you start
1. Read the StarRocks [GitHub workflow](https://github.com/StarRocks/community/blob/main/Contributors/guide/workflow.md) carefully, which provides the configurations of BE and FE and describes how to submit a pull request.
2. To learn more about StarRocks, read [StarRocks documentation](https://github.com/StarRocks/docs/blob/main/TOC.md).

# Pull request requirements

1. After you complete code development, upload the code to the StarRocks code repo as a pull request (PR).

  - PR title format: **[SR GeekCamp] + PR title**
  - Labels ：[Geek Camp 2022/feature]
2. After you submit your PR, comment on the status of your PR submission as requested under the Pinned Issue [[StarRocks geek Camp 2022] ](https://github.com/StarRocks/starrocks/issues/4008)page.

  - Comment format: **"I have finished Issue #" + PR link id**

**Comment by mincwang** [comment]
I pick! My name is mincho. I am from lingxing and I have been working on big-data platform development for 1.5 year. I am interested in OLAP, good at java programming, and have been using StarRocks for 4 months. I chose to solve this issue because we are need managing multiple StarRocks clusters.

**Comment by zhuxt2015** [comment]
I pick! My name is zhuxuetong. I am from Yili Group and I have been working on big data development for 5 year. I am interested in OLAP, good at Java programming  and Shell programming, and have been using StarRocks for 1 months. I chose to solve this issue because I want to learn more about StarRocks and challenge myself.

**Comment by elkan1788** [comment]
I pick! My name is elkan.Lee. I am from TY tech and I have been working on big-data development for 2 years. I'm interested in (M)OLAP, good at Java & python programming & letter about html skill. I was used StarRocks for 2 months. I chose to solve this issue because I want to make  install & maintance StarRocks cluster in a easy way & make use way friendly.

**Comment by elkan1788** [comment]
I pick! My name is elkan.Lee. I am from TY tech and I have been working on big-data development for 2 years. I'm interested in (M)OLAP, good at Java & python programming & letter about html skill. I was used StarRocks for 2 months. I chose to solve this issue because I want to make install & maintance StarRocks cluster in a easy way & make use way friendly.

**Comment by wuqiao** [comment]
> I pick! My name is mincho. I am from lingxing and I have been working on big-data platform development for 1.5 year. I am interested in OLAP, good at java programming, and have been using StarRocks for 4 months. I chose to solve this issue because we are need managing multiple StarRocks clusters.

@minchowang @lisenhui  hi guys,after leave the comments,please add the Community assistant's wechat "StarRocks-1".

**Comment by minchowang** [comment]
>  ok

**Comment by minchowang** [comment]
> > I pick! My name is mincho. I am from lingxing and I have been working on big-data platform development for 1.5 year. I am interested in OLAP, good at java programming, and have been using StarRocks for 4 months. I chose to solve this issue because we are need managing multiple StarRocks clusters.
> 
> @minchowang @lisenhui hi guys,after leave the comments,please add the Community assistant's wechat "StarRocks-1".

@wuqiao ok

**Comment by lisenhui** [comment]
> > I pick! My name is mincho. I am from lingxing and I have been working on big-data platform development for 1.5 year. I am interested in OLAP, good at java programming, and have been using StarRocks for 4 months. I chose to solve this issue because we are need managing multiple StarRocks clusters.
> 
> @minchowang @lisenhui hi guys,after leave the comments,please add the Community assistant's wechat "StarRocks-1".

@wuqiao  Got it. Completed connected with community assistant and wait for assign  task.

**Comment by zhuxt2015** [comment]
> I pick! My name is zhuxuetong. I am from Yili Group and I have been working on big data development for 5 year. I am interested in OLAP, good at Java programming and Shell programming, and have been using StarRocks for 1 months. I chose to solve this issue because I want to learn more about StarRocks and challenge myself.

We have Lots of scenes that use SR,  in especial we will install multiple SR clusters,  we plan to use ansible install SR cluster, hope to have the opportunity to join this team.

**Comment by lisenhui** [comment]
> > I pick! My name is zhuxuetong. I am from Yili Group and I have been working on big data development for 5 year. I am interested in OLAP, good at Java programming and Shell programming, and have been using StarRocks for 1 months. I chose to solve this issue because I want to learn more about StarRocks and challenge myself.
> 
> We have Lots of scenes that use SR, in especial we will install multiple SR clusters, we plan to use ansible install SR cluster, hope to have the opportunity to join this team.

Ansible scripts is good for software deploy and automation and wich kind like Travis CI tool.

**Comment by wangtianyi2004** [comment]
I pick! My name is Morgan. In my points of views, Ansible is a good deployment tool but it depends on python and it's need to install Ansible before build a starrocks env. Do you think to build a ansible env is easy than build a starrocks env? Maybe :) To develop a tool which don't depends on other component is a good way for building starrocks env. And I think golang is a good language for building a platform. 
What a coincidence, I build a tool to install MySQL, PostgreSQL and StarRocks before. I think it's a good way to have a secondary development on this tool.

**Comment by zhbdesign** [comment]
What's the current progress? Doris is already developing it，[https://github.com/apache/incubator-doris-manager](url)

**Comment by mklzl** [comment]
I finished it ! https://github.com/mklzl/starrocks_ansible

**Comment by wangtianyi2004** [comment]
https://github.com/wangtianyi2004/starrocks-controller

**Comment by wangtianyi2004** [comment]
I build a binary to setup StarRocks.
Here is the link https://github.com/wangtianyi2004/starrocks-controller

**Comment by Johnsonginati** [comment]
Nice work @wangtianyi2004

**Comment by LittleBeeBee** [comment]
Greate job @wangtianyi2004
