### ISSUE TITLE
Support list partition【Moderate】

### ISSUE THREAD

**Issue by wuqiao** [StarRocks/starrocks#4035]
# Requirement Description
1. List partition design.
2. List partition implementation, including table creation, loading and query.

```
CREATE TABLE h2 (
  c1 INT,
  c2 INT
)
PARTITION BY LIST(c1) (
  PARTITION p0 VALUES IN (1, 4, 7),
  PARTITION p1 VALUES IN (2, 5, 8)
)
DISTRIBUTED BY HASH(c2) BUCKETS 3;
```

# Mentor
@wyb 

# Registration procedure

**Step 1.** Add a comment when you sign up. The comment can be a brief self-introduction and reason for signing up, including what you do, what you're good at, what you're interested in and your technology stack, and how familiar you are with StarRocks. Example:

> I pick! My name is Johnny. I am from StarRocks and I have been working on database kernel development for 1 year. I am interested in OLAP, good at C++ programming, and have been using StarRocks for 6 months. I chose to solve this issue because I am familiar with execution engine.

**Step 2.** On your WeChat, add the StarRocks community assistant "**_StarRocks-1_**" as a WeChat friend and leave your GitHub ID. The assistant will invite you to a WeChat group based on the issue you picked.

**Step 3.** The mentor will communicate with all the participants who picked this issue and assign the task to the best match. 

# Before you start
1. Read the StarRocks [GitHub workflow](https://github.com/StarRocks/community/blob/main/Contributors/guide/workflow.md) carefully, which provides the configurations of BE and FE and describes how to submit a pull request.
2. To learn more about StarRocks, read [StarRocks documentation](https://github.com/StarRocks/docs/blob/main/TOC.md).

# Pull request requirements

1. After you complete code development, upload the code to the StarRocks code repo as a pull request (PR).

  - PR title format: **[SR GeekCamp] + PR title**
  - Labels ：[Geek Camp 2022/feature]
2. After you submit your PR, comment on the status of your PR submission as requested under the Pinned Issue [[StarRocks geek Camp 2022] ](https://github.com/StarRocks/starrocks/issues/4008)page.

  - Comment format: **"I have finished Issue #" + PR link id**

**Comment by hiliuxg** [comment]
I pick! My name is hiliuxg. I have worked in big data development for 5 years . I am interested in OLAP, good at JAVA programming, and have been using StarRocks for 1 year. I like StarRocks community and hope to contribute.

**Comment by wsjz** [comment]
I pick! My name is JInzhe.I have been working on big data development for 3 year. I am interested in OLAP, good at JAVA programming. I will try to solve this issue because I am familiar with Presto. I wanna contribute to StarRocks with my experience.

**Comment by wsjz** [comment]
这是来自QQ邮箱的假期自动回复邮件。
好，我最近正在休假中

 
您，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hiliuxg** [comment]
The main changes comes here .

### Grammar File
sql_parser.cup to add related grammar

### Create table
Grammar  analyze changes in  CreateTableStmt#analyze
1.  PartitionType.java  add LIST('LIST')  enum  type 
2.  TPartitionType.java  add LIST('LIST')  enum type 
3.  Make a subclass implement of PartitionDesc to analyze grammar

Meta data changes in catalog#createOlapTable
1.  Create a listPartitionInfo implement of PartitionInfo 
2.  Take listPartitionInfo to memory and persis to log 

### Alter table add/drop partition
Grammar  analyze changes in AlterTableStmt#analyze
1. AddPartitionClause.java 
2. DropPartitionClause.java

Meta data changes in Catalog#alterTable

### Truncate partition 
Grammar  analyze changes in TruncateTableStmt#analyze
Meta data changes in Catalog#truncateTable

### Show partition
No changes 

### Load data
1.  OlapTableSink#createPartition 
2.  shuffe change by list partition rule in tablet_sink  on BE side 

### query data
1. OlapScanNode#computePartitionInfo
2. Make ListPartitionPruner implement of PartitionPruner
