### ISSUE TITLE
Optimizer supports Merge Join【Challenging】

### ISSUE THREAD

**Issue by wuqiao** [StarRocks/starrocks#4036]
# Requirement Description
In some specific scenarios, such as all tables are naturally ordered, non-equivalent Join, or other possible scenarios, MergeJoin is better than HashJoin in performance and memory usage. It is necessary to explore possible scenarios and modify the optimizer, Properly plan MergeJoin based on statistics or metadata information.

# Mentor
@trueeyu 

# Registration procedure

**Step 1.** Add a comment when you sign up. The comment can be a brief self-introduction and reason for signing up, including what you do, what you're good at, what you're interested in and your technology stack, and how familiar you are with StarRocks. Example:

> I pick! My name is Johnny. I am from StarRocks and I have been working on database kernel development for 1 year. I am interested in OLAP, good at C++ programming, and have been using StarRocks for 6 months. I chose to solve this issue because I am familiar with execution engine.

**Step 2.** On your WeChat, add the StarRocks community assistant "**_StarRocks-1_**" as a WeChat friend and leave your GitHub ID. The assistant will invite you to a WeChat group based on the issue you picked.

**Step 3.** The mentor will communicate with all the participants who picked this issue and assign the task to the best match. 

# Before you start
1. Read the StarRocks [GitHub workflow](https://github.com/StarRocks/community/blob/main/Contributors/guide/workflow.md) carefully, which provides the configurations of BE and FE and describes how to submit a pull request.
2. To learn more about StarRocks, read [StarRocks documentation](https://github.com/StarRocks/docs/blob/main/TOC.md).

# Pull request requirements

1. After you complete code development, upload the code to the StarRocks code repo as a pull request (PR).

  - PR title format: **[SR GeekCamp] + PR title**
  - Labels ：[Geek Camp 2022/feature]
2. After you submit your PR, comment on the status of your PR submission as requested under the Pinned Issue [[StarRocks geek Camp 2022] ](https://github.com/StarRocks/starrocks/issues/4008)page.

  - Comment format: **"I have finished Issue #" + PR link id**

**Comment by zddr** [comment]
I pick! My name is zhang dong,I have been working on database kernel development for 1 year. I am interested in OLAP, I am good at Java programming, and I have been using StarRocks for 4 months.I chose to solve this issue because I'm interested in query optimization。

**Comment by wuqiao** [comment]
> add the StarRocks community assistant "**_StarRocks-1_**"

hi，@zddr  Please add the StarRocks community assistant "StarRocks-1"

**Comment by zddr** [comment]
@wuqiao ok

**Comment by trueeyu** [comment]
one interesting article about sort merge join: https://15721.courses.cs.cmu.edu/spring2018/papers/20-sortmergejoins/kim-vldb2009.pdf

**Comment by zddr** [comment]
3q,I read it right now.

**Comment by trueeyu** [comment]
We can first look at the current query optimization implementation for HashJoin. It may be help to implement the SortMergeJoin

**Comment by trueeyu** [comment]
Need to think about what scenarios are suitable for SortMergeJoin, and also need to investigate the implementation of other databases

**Comment by zddr** [comment]
OK, I'll study it, and then I'll say what I think.
