### ISSUE TITLE
Executor supports Merge Join【Challenging】

### ISSUE THREAD

**Issue by wuqiao** [StarRocks/starrocks#4037]
# Requirement Description
Implement MergeJoin operator and optimize MergeJoin performance.Sort-merge join is highly dependent on a good sort implementation, we should looking for a faster sorting algorithm

# Mentor
@trueeyu 

# Registration procedure

**Step 1.** Add a comment when you sign up. The comment can be a brief self-introduction and reason for signing up, including what you do, what you're good at, what you're interested in and your technology stack, and how familiar you are with StarRocks. Example:

> I pick! My name is Johnny. I am from StarRocks and I have been working on database kernel development for 1 year. I am interested in OLAP, good at C++ programming, and have been using StarRocks for 6 months. I chose to solve this issue because I am familiar with execution engine.

**Step 2.** On your WeChat, add the StarRocks community assistant "**_StarRocks-1_**" as a WeChat friend and leave your GitHub ID. The assistant will invite you to a WeChat group based on the issue you picked.

**Step 3.** The mentor will communicate with all the participants who picked this issue and assign the task to the best match. 

# Before you start
1. Read the StarRocks [GitHub workflow](https://github.com/StarRocks/community/blob/main/Contributors/guide/workflow.md) carefully, which provides the configurations of BE and FE and describes how to submit a pull request.
2. To learn more about StarRocks, read [StarRocks documentation](https://github.com/StarRocks/docs/blob/main/TOC.md).

# Pull request requirements

1. After you complete code development, upload the code to the StarRocks code repo as a pull request (PR).

  - PR title format: **[SR GeekCamp] + PR title**
  - Labels ：[Geek Camp 2022/feature]
2. After you submit your PR, comment on the status of your PR submission as requested under the Pinned Issue [[StarRocks geek Camp 2022] ](https://github.com/StarRocks/starrocks/issues/4008)page.

  - Comment format: **"I have finished Issue #" + PR link id**

**Comment by chinawch007** [comment]
I pick! My name is Wang Chong. I'm now working in Vmware GreenPlum database team. I have used C++ for many years. I have a good knowledge base of database([my blog](https://www.zhihu.com/column/c_1449351860348362752)) and I can learn knowledge about merge join quickly. I'm now studying the source code of the execution of join of StarRocks and I plan to study the implementation of merge join of other database such as ClickHouse, Postgres. Because I am working in foreign company, I have much free time to implement this feature. I think I am a suitable candidate, please consider me.

**Comment by trueeyu** [comment]
one interesting article about sort merge join: https://15721.courses.cs.cmu.edu/spring2018/papers/20-sortmergejoins/kim-vldb2009.pdf

**Comment by chinawch007** [comment]
> one interesting article about sort merge join: https://15721.courses.cs.cmu.edu/spring2018/papers/20-sortmergejoins/kim-vldb2009.pdf

Thank you for presenting me this paper. I read it right now.

**Comment by chinawch007** [comment]
A demo that execute merge sort with SIMD as the paper illustrates.
https://github.com/chinawch007/SIMD

**Comment by trueeyu** [comment]
Also need to investigate the implementation of other olap databases.

There are also research cases where sort merge join is suitable for use, such as natural ordering of data

**Comment by trueeyu** [comment]
I will also write a research document recently, we can discuss it together
