### ISSUE TITLE
Incorrect 'quantile' Label Value in Prometheus Metrics

### ISSUE THREAD

**Issue by cdgh2021** [StarRocks/starrocks#40611]
### Steps to reproduce the behavior (Required)
When attempting to pull metrics using the /metrics endpoint on the BE nodes, we encountered the following error:

"expected float as value for 'quantile' label, got 'avg'"

Upon further investigation, it appears that the 'quantile' label in the summary metrics generated by the BE nodes is being set to "avg." This seems to be inconsistent with the expected behavior of the 'quantile' label in Prometheus, which should contain a floating-point value representing the percentile.

```
# HELP rpc_server_8060_doris_pbackend_service_exec_batch_plan_fragments
# TYPE rpc_server_8060_doris_pbackend_service_exec_batch_plan_fragments summary
rpc_server_8060_doris_pbackend_service_exec_batch_plan_fragments{quantile="0.8"} 3592
rpc_server_8060_doris_pbackend_service_exec_batch_plan_fragments{quantile="0.9"} 6330
rpc_server_8060_doris_pbackend_service_exec_batch_plan_fragments{quantile="0.99"} 6899
rpc_server_8060_doris_pbackend_service_exec_batch_plan_fragments{quantile="0.999"} 6899
rpc_server_8060_doris_pbackend_service_exec_batch_plan_fragments{quantile="0.9999"} 6899
rpc_server_8060_doris_pbackend_service_exec_batch_plan_fragments{quantile="1"} 6899
rpc_server_8060_doris_pbackend_service_exec_batch_plan_fragments{quantile="avg"} 2412
rpc_server_8060_doris_pbackend_service_exec_batch_plan_fragments_sum 56355805944
rpc_server_8060_doris_pbackend_service_exec_batch_plan_fragments_count 23364762
````

### Expected behavior (Required)

all quantile label values are float numbers

### Real behavior (Required)

all summary type metrics in be contains {quantile="avg"}

### StarRocks version (Required)

3.0.5

**Comment by kevincai** [comment]
`quantile="avg"` is not necessary, as long as `*_sum` and `*_count` is provided, the average metric can be calculated from `*_sum / *_count` by prometheus expr.
