### ISSUE TITLE
ADLS Gen2 Share Key endpoint hardcode cause connection failure.

### ISSUE THREAD

**Issue by dacoolbaby** [StarRocks/starrocks#40669]
I have check the source code on :
https://github.com/StarRocks/starrocks/blob/cc4aae6a62f0480576260a98a0049c6c4b894ecf/fe/fe-core/src/main/java/com/starrocks/credential/azure/AzureStorageCloudCredential.java 

When using adls2, the endpoint of the Azure Blob has been hard code to **blob.core.windows.net** which not apply to china endpoint: **core.chinacloudapi.cn**

I would consider it is a bug. 
With Azure ADLS gen2 abfss protocol, we would have better performance on using directories.

### Steps to reproduce the behavior (Required)
**This code cant verify to Azure Blob** 
CREATE EXTERNAL CATALOG test_catalog
PROPERTIES
(
    "type" = "deltalake",
    "hive.metastore.type" = "hive",
    "hive.metastore.uris" = "thrift://hmstest.com:9083", 
    "azure.adls2.storage_account" = "$account_name",
    "azure.adls2.endpoint" = "$account_name.dfs.core.chinacloudapi.cn",
    "azure.adls2.shared_key"="****88****"
);

**This can work fine.**
CREATE EXTERNAL CATALOG test_catalog
PROPERTIES
(
    "type" = "deltalake",
    "hive.metastore.type" = "hive",
    "hive.metastore.uris" = "thrift://hmstest.com:9083", 
    "azure.blob.storage_account" = "$account_name",
    "azure.blob.endpoint" = "$account_name.dfs.core.chinacloudapi.cn",
    "azure.blob.shared_key"="****88****"
);

### Expected behavior (Required)
show tables;
clickdata

### Real behavior (Required)
 show tables;
Empty set (0.28 sec)

2024-02-04 03:19:24,576 WARN (starrocks-mysql-nio-pool-18|708) [DeltaLakeMetadata.getTable():74] Failure to initialize configuration for $account_name.dfs.core.chinacloudapi.cn key ="null": Invalid confi
guration value detected for fs.azure.account.key

### StarRocks version (Required)
3.2.2-269e832

**Comment by Smith-Cruise** [comment]
Yes, It's a problem.
Can you take a pr to support it.
You can refer to: https://github.com/StarRocks/starrocks/pull/25655
