### ISSUE TITLE
Schema change job is always in state FINISHED_REWRITING, cannot finished and cannot cancel

### ISSUE THREAD

**Issue by medivh666** [StarRocks/starrocks#40750]
### Steps to reproduce the behavior (Required)

1, alter table  game_order add column `sr_update_time`    DATETIME       DEFAULT CURRENT_TIMESTAMP;

a day later,it is the same sate

2, show alter table column \G;
     JobId: 49180794
    TableName: game_order
   CreateTime: 2024-02-03 18:13:54
   FinishTime: 2024-02-03 18:14:47
    IndexName: game_order
      IndexId: 49180795
OriginIndexId: 48659865
SchemaVersion: 0:0
TransactionId: 27387620
        State: FINISHED_REWRITING
          Msg: 
     Progress: NULL
      Timeout: 86400
1 row in set (0.203 sec)

3. cancel alter table column from game_order\G;
ERROR 1064 (HY000): Unexpected exception: Job can not be cancelled. State: FINISHED_REWRITING
ERROR: No query specified

### StarRocks version (Required)
 - 3.2.2-269e832  
 - shared_data

**Comment by dorsegal** [comment]
@medivh666 Did you manage to solve this?
