### ISSUE TITLE
In trino's sql_dialect mode, date_add returns different precision as trino.

### ISSUE THREAD

**Issue by renzhimin7** [StarRocks/starrocks#40814]
### Steps to reproduce the behavior (Required)
In SR
1、set sql_dialect = 'trino';
2、select date_add('day', -1, current_date);   -- return '2024-02-04 00:00:00'
In Trino
1、select date_add('day', -1, current_date);   -- return '2024-02-04'
### StarRocks version (Required)
3.1.3-384ba23

**Comment by renzhimin7** [comment]
1、set sql_dialect = 'trino';

**Comment by metalshanked** [comment]
facing the same issue thx

**Comment by wangsimo0** [comment]
I'm just curious, in what scenarios would this precision issue lead to actual calculation problems? As there don't seem to be any correctness issues with the data.

**Comment by renzhimin7** [comment]
在类似于这样的写法 dt = cast(date_add('day', -1, current_date), as varchar)，trino和SR执行会有不同的结果。在迁移trino到SR时，对于原来的SQL不能无缝迁移。
