### ISSUE TITLE
Issue with Python Django Support

### ISSUE THREAD

**Issue by metalshanked** [StarRocks/starrocks#40846]
Running Django versions from 3.2.x to 5.x (Same issue)

### Steps to reproduce the behavior (Required)
Below is an example config that I tried
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django',
        'PASSWORD':'',
        'HOST':'127.0.0.1',
        'PORT':'3306',
        'USER':'',
        'OPTIONS': {
            "init_command": "SET storage_engine=olap",
             #"init_command": "SET @default_storage_engine=olap",
        },
    }
}
```

### Expected behavior (Required)
Should Connect without errors
### Real behavior (Required)
```
(1064, "Getting analyzing error. Detail message: Unknown system variable 'default_storage_engine', the most similar variables are {'default_rowset_type', 'default_table_compression', 'enable_sort_aggregate'}.")
```
### StarRocks version (Required)
3.2.2

Seems like there is no system variable in Starrocks for `default_storage_engine` which is needed by the mssqlclient for Django

Note:
default_storage_engine was introduced in MySQL 5.5.3.
storage_engine was removed in MySQL 5.7.5.

Starrocks seem to be show up as `5.1.0`
```
MySQL 8.0.11 or later is required (found 5.1.0)
```

Please advise.

Thanks!

**Comment by chaoyli** [comment]
You can change the `mysql_server_version` in the fe.conf. The default is 5.1.0

**Comment by metalshanked** [comment]
Thanks @chaoyli. Will update it
How about the 1st part of the problem...i.e. Django is hardcoded to look for system variable `default_storage_engine`

`default_storage_engine` was introduced in MySQL 5.5.3 and above and `storage_engine` variable used in starrocks is deprecated
so applications like Django are hardcoded to look for default_storage_engine  variable and cannot connect to starrocks

**Comment by metalshanked** [comment]
@chaoyli  if we change `mysql_server_version` to any 8.x.x version then DDL statements like create throw error like below

setting mysql_server_version as `8.0.0`
```
SQL Error [1064] [42000]: Getting analyzing error. Detail message: Unknown system variable 'tx_read_only', the most similar variables are {'innodb_read_only', 'trace_log_mode', 'default_rowset_type'}.
```

setting mysql_server_version > `8.0.0`
```
SQL Error [1064] [42000]: Getting analyzing error. Detail message: Unknown system variable 'transaction_read_only', the most similar variables are {'innodb_read_only', 'trace_log_mode', 'default_rowset_type'}.
```
