### ISSUE TITLE
[function]cardinality(HLL)

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#40879]
StarRocks support hll_cardinality
https://docs.starrocks.io/docs/sql-reference/sql-functions/scalar-functions/hll_cardinality/
however, in trino's compatibility, trino support hll type's cardinality in function cardinality().

if starrocks support hll input in cardinality(), it will make starrocks be more compatible with trino in trino's sql_dialect

**Comment by mychaow** [comment]
Hi, I'd like to try it, thanks!

**Comment by mychaow** [comment]
Sorry, I've been a bit busy lately. I'll unassign this task for now. Sorry for the inconvenience.

**Comment by wangsimo0** [comment]
> Sorry, I've been a bit busy lately. I'll unassign this task for now. Sorry for the inconvenience.

that's ok~~:)

**Comment by mychaow** [comment]
Hi, I've tried it. Please help me review it. Thanks!
