### ISSUE TITLE
Error when execute update sql on primary key table

### ISSUE THREAD

**Issue by qian0817** [StarRocks/starrocks#40871]
### Steps to reproduce the behavior (Required)
```sql
CREATE TABLE `t1` (
    `a` int NOT NULL,
    `b` int NULL,
    `c` bigint NULL
) ENGINE=OLAP
  PRIMARY KEY(`a`)
  DISTRIBUTED BY HASH(`a`);
UPDATE t1 SET b=1, c=1 WHERE a=1;
```

### Expected behavior (Required)
The update sql can be executed correctly.

### Real behavior (Required)
ERROR 1064 (HY000): type of exprs is not match slot's, expr_type=7, slot_type=5, slot_name=b backend [id=11003] [host=xxx]
### StarRocks version (Required)
3.2.2-269e832

**Comment by yusufozturk** [comment]
Any update on this issue? We are waiting for this PR.

**Comment by luohaha** [comment]
@yusufozturk https://github.com/StarRocks/starrocks/pull/41969 should fix this.
