### ISSUE TITLE
Link error with LLVM when building on arm

### ISSUE THREAD

**Issue by 1153710405** [StarRocks/starrocks#40906]
Failed to build starrocks-main on arm. Encounter the same link error when built on physical machine and in docker (starrocks/dev-env-centos7:latest).

### Steps to reproduce the behavior (Required)
sh build.sh

### Real behavior (Required)
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64CodeGen.a(AArch64ISelDAGToDAG.cpp.o): In function `(anonymous namespace)::AArch64DAGToDAGISel::tryWriteRegister(llvm::SDNode*)':
AArch64ISelDAGToDAG.cpp:(.text._ZN12_GLOBAL__N_119AArch64DAGToDAGISel16tryWriteRegisterEPN4llvm6SDNodeE+0x78): undefined reference to `llvm::AArch64PState::lookupPStateImm0_15ByName(llvm::StringRef)'
AArch64ISelDAGToDAG.cpp:(.text._ZN12_GLOBAL__N_119AArch64DAGToDAGISel16tryWriteRegisterEPN4llvm6SDNodeE+0x168): undefined reference to `llvm::AArch64PState::lookupPStateImm0_1ByName(llvm::StringRef)'
AArch64ISelDAGToDAG.cpp:(.text._ZN12_GLOBAL__N_119AArch64DAGToDAGISel16tryWriteRegisterEPN4llvm6SDNodeE+0x3d8): undefined reference to `llvm::AArch64SysReg::lookupSysRegByName(llvm::StringRef)'
AArch64ISelDAGToDAG.cpp:(.text._ZN12_GLOBAL__N_119AArch64DAGToDAGISel16tryWriteRegisterEPN4llvm6SDNodeE+0x3f0): undefined reference to `llvm::AArch64SysReg::parseGenericRegister(llvm::StringRef)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64CodeGen.a(AArch64ISelDAGToDAG.cpp.o): In function `(anonymous namespace)::AArch64DAGToDAGISel::tryReadRegister(llvm::SDNode*)':
AArch64ISelDAGToDAG.cpp:(.text._ZN12_GLOBAL__N_119AArch64DAGToDAGISel15tryReadRegisterEPN4llvm6SDNodeE+0x14c): undefined reference to `llvm::AArch64SysReg::lookupSysRegByName(llvm::StringRef)'
AArch64ISelDAGToDAG.cpp:(.text._ZN12_GLOBAL__N_119AArch64DAGToDAGISel15tryReadRegisterEPN4llvm6SDNodeE+0x164): undefined reference to `llvm::AArch64SysReg::parseGenericRegister(llvm::StringRef)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64CodeGen.a(AArch64ISelDAGToDAG.cpp.o): In function `(anonymous namespace)::AArch64DAGToDAGISel::CheckNodePredicate(llvm::SDNode*, unsigned int) const':
AArch64ISelDAGToDAG.cpp:(.text._ZNK12_GLOBAL__N_119AArch64DAGToDAGISel18CheckNodePredicateEPN4llvm6SDNodeEj+0x133c): undefined reference to `llvm::AArch64SVCR::lookupSVCRByEncoding(unsigned char)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64CodeGen.a(AArch64ISelLowering.cpp.o): In function `llvm::AArch64TargetLowering::fallBackToDAGISel(llvm::Instruction const&) const':
AArch64ISelLowering.cpp:(.text._ZNK4llvm21AArch64TargetLowering17fallBackToDAGISelERKNS_11InstructionE+0x12c): undefined reference to `llvm::SMEAttrs::SMEAttrs(llvm::AttributeList const&)'
AArch64ISelLowering.cpp:(.text._ZNK4llvm21AArch64TargetLowering17fallBackToDAGISelERKNS_11InstructionE+0x138): undefined reference to `llvm::SMEAttrs::SMEAttrs(llvm::CallBase const&)'
AArch64ISelLowering.cpp:(.text._ZNK4llvm21AArch64TargetLowering17fallBackToDAGISelERKNS_11InstructionE+0x148): undefined reference to `llvm::SMEAttrs::requiresSMChange(llvm::SMEAttrs const&, bool) const'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64CodeGen.a(AArch64ISelLowering.cpp.o): In function `llvm::AArch64TargetLowering::LowerFormalArguments(llvm::SDValue, unsigned int, bool, llvm::SmallVectorImpl<llvm::ISD::InputArg> const&, llvm::SDLoc const&, llvm::SelectionDAG&, llvm::SmallVectorImpl<llvm::SDValue>&) const':
AArch64ISelLowering.cpp:(.text._ZNK4llvm21AArch64TargetLowering20LowerFormalArgumentsENS_7SDValueEjbRKNS_15SmallVectorImplINS_3ISD8InputArgEEERKNS_5SDLocERNS_12SelectionDAGERNS2_IS1_EE+0x2f4): undefined reference to `llvm::SMEAttrs::SMEAttrs(llvm::AttributeList const&)'
AArch64ISelLowering.cpp:(.text._ZNK4llvm21AArch64TargetLowering20LowerFormalArgumentsENS_7SDValueEjbRKNS_15SmallVectorImplINS_3ISD8InputArgEEERKNS_5SDLocERNS_12SelectionDAGERNS2_IS1_EE+0xf70): undefined reference to `llvm::SMEAttrs::SMEAttrs(llvm::AttributeList const&)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64CodeGen.a(AArch64ISelLowering.cpp.o): In function `llvm::AArch64TargetLowering::LowerReturn(llvm::SDValue, unsigned int, bool, llvm::SmallVectorImpl<llvm::ISD::OutputArg> const&, llvm::SmallVectorImpl<llvm::SDValue> const&, llvm::SDLoc const&, llvm::SelectionDAG&) const':
AArch64ISelLowering.cpp:(.text._ZNK4llvm21AArch64TargetLowering11LowerReturnENS_7SDValueEjbRKNS_15SmallVectorImplINS_3ISD9OutputArgEEERKNS2_IS1_EERKNS_5SDLocERNS_12SelectionDAGE+0x334): undefined reference to `llvm::SMEAttrs::SMEAttrs(llvm::AttributeList const&)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64CodeGen.a(AArch64ISelLowering.cpp.o): In function `llvm::AArch64TargetLowering::isEligibleForTailCallOptimization(llvm::TargetLowering::CallLoweringInfo const&) const':
AArch64ISelLowering.cpp:(.text._ZNK4llvm21AArch64TargetLowering33isEligibleForTailCallOptimizationERKNS_14TargetLowering16CallLoweringInfoE+0xbc): undefined reference to `llvm::SMEAttrs::SMEAttrs(llvm::AttributeList const&)'
AArch64ISelLowering.cpp:(.text._ZNK4llvm21AArch64TargetLowering33isEligibleForTailCallOptimizationERKNS_14TargetLowering16CallLoweringInfoE+0xcc): undefined reference to `llvm::SMEAttrs::SMEAttrs(llvm::CallBase const&)'
AArch64ISelLowering.cpp:(.text._ZNK4llvm21AArch64TargetLowering33isEligibleForTailCallOptimizationERKNS_14TargetLowering16CallLoweringInfoE+0xdc): undefined reference to `llvm::SMEAttrs::requiresSMChange(llvm::SMEAttrs const&, bool) const'
AArch64ISelLowering.cpp:(.text._ZNK4llvm21AArch64TargetLowering33isEligibleForTailCallOptimizationERKNS_14TargetLowering16CallLoweringInfoE+0x238): undefined reference to `llvm::SMEAttrs::set(unsigned int, bool)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64CodeGen.a(AArch64ISelLowering.cpp.o): In function `llvm::AArch64TargetLowering::LowerCall(llvm::TargetLowering::CallLoweringInfo&, llvm::SmallVectorImpl<llvm::SDValue>&) const':
AArch64ISelLowering.cpp:(.text._ZNK4llvm21AArch64TargetLowering9LowerCallERNS_14TargetLowering16CallLoweringInfoERNS_15SmallVectorImplINS_7SDValueEEE+0x288): undefined reference to `llvm::SMEAttrs::set(unsigned int, bool)'
AArch64ISelLowering.cpp:(.text._ZNK4llvm21AArch64TargetLowering9LowerCallERNS_14TargetLowering16CallLoweringInfoERNS_15SmallVectorImplINS_7SDValueEEE+0x2a8): undefined reference to `llvm::SMEAttrs::SMEAttrs(llvm::AttributeList const&)'
AArch64ISelLowering.cpp:(.text._ZNK4llvm21AArch64TargetLowering9LowerCallERNS_14TargetLowering16CallLoweringInfoERNS_15SmallVectorImplINS_7SDValueEEE+0x2bc): undefined reference to `llvm::SMEAttrs::SMEAttrs(llvm::CallBase const&)'
AArch64ISelLowering.cpp:(.text._ZNK4llvm21AArch64TargetLowering9LowerCallERNS_14TargetLowering16CallLoweringInfoERNS_15SmallVectorImplINS_7SDValueEEE+0x568): undefined reference to `llvm::SMEAttrs::requiresSMChange(llvm::SMEAttrs const&, bool) const'
AArch64ISelLowering.cpp:(.text._ZNK4llvm21AArch64TargetLowering9LowerCallERNS_14TargetLowering16CallLoweringInfoERNS_15SmallVectorImplINS_7SDValueEEE+0x3a50): undefined reference to `llvm::SMEAttrs::set(unsigned int, bool)'
AArch64ISelLowering.cpp:(.text._ZNK4llvm21AArch64TargetLowering9LowerCallERNS_14TargetLowering16CallLoweringInfoERNS_15SmallVectorImplINS_7SDValueEEE+0x3c9c): undefined reference to `llvm::SMEAttrs::set(unsigned int, bool)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64CodeGen.a(AArch64CallLowering.cpp.o): In function `llvm::AArch64CallLowering::fallBackToDAGISel(llvm::MachineFunction const&) const':
AArch64CallLowering.cpp:(.text._ZNK4llvm19AArch64CallLowering17fallBackToDAGISelERKNS_15MachineFunctionE+0x158): undefined reference to `llvm::SMEAttrs::SMEAttrs(llvm::AttributeList const&)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64CodeGen.a(AArch64TargetTransformInfo.cpp.o): In function `llvm::AArch64TTIImpl::areInlineCompatible(llvm::Function const*, llvm::Function const*) const':
AArch64TargetTransformInfo.cpp:(.text._ZNK4llvm14AArch64TTIImpl19areInlineCompatibleEPKNS_8FunctionES3_+0x38): undefined reference to `llvm::SMEAttrs::SMEAttrs(llvm::AttributeList const&)'
AArch64TargetTransformInfo.cpp:(.text._ZNK4llvm14AArch64TTIImpl19areInlineCompatibleEPKNS_8FunctionES3_+0x50): undefined reference to `llvm::SMEAttrs::SMEAttrs(llvm::AttributeList const&)'
AArch64TargetTransformInfo.cpp:(.text._ZNK4llvm14AArch64TTIImpl19areInlineCompatibleEPKNS_8FunctionES3_+0x60): undefined reference to `llvm::SMEAttrs::requiresSMChange(llvm::SMEAttrs const&, bool) const'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64CodeGen.a(AArch64InstrInfo.cpp.o): In function `llvm::AArch64InstrInfo::expandPostRAPseudo(llvm::MachineInstr&) const':
AArch64InstrInfo.cpp:(.text._ZNK4llvm16AArch64InstrInfo18expandPostRAPseudoERNS_12MachineInstrE+0x640): undefined reference to `llvm::AArch64SysReg::lookupSysRegByName(llvm::StringRef)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64CodeGen.a(AArch64InstructionSelector.cpp.o): In function `(anonymous namespace)::AArch64InstructionSelector::testImmPredicate_I64(unsigned int, long) const':
AArch64InstructionSelector.cpp:(.text._ZNK12_GLOBAL__N_126AArch64InstructionSelector20testImmPredicate_I64Ejl+0x2f4): undefined reference to `llvm::AArch64SVCR::lookupSVCRByEncoding(unsigned char)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64CodeGen.a(SMEABIPass.cpp.o): In function `(anonymous namespace)::SMEABI::runOnFunction(llvm::Function&)':
SMEABIPass.cpp:(.text._ZN12_GLOBAL__N_16SMEABI13runOnFunctionERN4llvm8FunctionE+0x124): undefined reference to `llvm::SMEAttrs::SMEAttrs(llvm::AttributeList const&)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64CodeGen.a(AArch64FastISel.cpp.o): In function `llvm::AArch64::createFastISel(llvm::FunctionLoweringInfo&, llvm::TargetLibraryInfo const*)':
AArch64FastISel.cpp:(.text._ZN4llvm7AArch6414createFastISelERNS_20FunctionLoweringInfoEPKNS_17TargetLibraryInfoE+0x28): undefined reference to `llvm::SMEAttrs::SMEAttrs(llvm::AttributeList const&)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `lookupSysReg(unsigned int, bool, llvm::MCSubtargetInfo const&)':
AArch64InstPrinter.cpp:(.text._ZL12lookupSysRegjbRKN4llvm15MCSubtargetInfoE+0x14): undefined reference to `llvm::AArch64SysReg::lookupSysRegByEncoding(unsigned short)'
AArch64InstPrinter.cpp:(.text._ZL12lookupSysRegjbRKN4llvm15MCSubtargetInfoE+0x8c): undefined reference to `llvm::AArch64SysReg::lookupSysRegByName(llvm::StringRef)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `llvm::AArch64InstPrinter::printSVEVecLenSpecifier(llvm::MCInst const*, unsigned int, llvm::MCSubtargetInfo const&, llvm::raw_ostream&) [clone .constprop.0]':
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter23printSVEVecLenSpecifierEPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE.constprop.0+0x24): undefined reference to `llvm::AArch64SVEVecLenSpecifier::lookupSVEVECLENSPECIFIERByEncoding(unsigned char)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `AArch64InstPrinterValidateMCOperand(llvm::MCOperand const&, llvm::MCSubtargetInfo const&, unsigned int)':
AArch64InstPrinter.cpp:(.text._ZL35AArch64InstPrinterValidateMCOperandRKN4llvm9MCOperandERKNS_15MCSubtargetInfoEj+0x424): undefined reference to `llvm::AArch64BTIHint::lookupBTIByEncoding(unsigned char)'
AArch64InstPrinter.cpp:(.text._ZL35AArch64InstPrinterValidateMCOperandRKN4llvm9MCOperandERKNS_15MCSubtargetInfoEj+0x438): undefined reference to `llvm::AArch64PSBHint::lookupPSBByEncoding(unsigned char)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `llvm::AArch64InstPrinter::printSVCROp(llvm::MCInst const*, unsigned int, llvm::MCSubtargetInfo const&, llvm::raw_ostream&)':
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter11printSVCROpEPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE+0x24): undefined reference to `llvm::AArch64SVCR::lookupSVCRByEncoding(unsigned char)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `llvm::AArch64InstPrinter::printRangePrefetchAlias(llvm::MCInst const*, llvm::MCSubtargetInfo const&, llvm::raw_ostream&, llvm::StringRef)':
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter23printRangePrefetchAliasEPKNS_6MCInstERKNS_15MCSubtargetInfoERNS_11raw_ostreamENS_9StringRefE+0xdc): undefined reference to `llvm::AArch64RPRFM::lookupRPRFMByEncoding(unsigned char)'
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter23printRangePrefetchAliasEPKNS_6MCInstERKNS_15MCSubtargetInfoERNS_11raw_ostreamENS_9StringRefE+0x25c): undefined reference to `llvm::AArch64RPRFM::lookupRPRFMByEncoding(unsigned char)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `llvm::AArch64InstPrinter::printRPRFMOperand(llvm::MCInst const*, unsigned int, llvm::MCSubtargetInfo const&, llvm::raw_ostream&)':
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter17printRPRFMOperandEPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE+0x2c): undefined reference to `llvm::AArch64RPRFM::lookupRPRFMByEncoding(unsigned char)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `llvm::AArch64InstPrinter::printPSBHintOp(llvm::MCInst const*, unsigned int, llvm::MCSubtargetInfo const&, llvm::raw_ostream&)':
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter14printPSBHintOpEPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE+0x2c): undefined reference to `llvm::AArch64PSBHint::lookupPSBByEncoding(unsigned char)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `llvm::AArch64InstPrinter::printBTIHintOp(llvm::MCInst const*, unsigned int, llvm::MCSubtargetInfo const&, llvm::raw_ostream&)':
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter14printBTIHintOpEPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE+0x30): undefined reference to `llvm::AArch64BTIHint::lookupBTIByEncoding(unsigned char)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `llvm::AArch64InstPrinter::printBarrierOption(llvm::MCInst const*, unsigned int, llvm::MCSubtargetInfo const&, llvm::raw_ostream&)':
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter18printBarrierOptionEPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE+0x48): undefined reference to `llvm::AArch64DB::lookupDBByEncoding(unsigned char)'
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter18printBarrierOptionEPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE+0xa4): undefined reference to `llvm::AArch64TSB::lookupTSBByEncoding(unsigned char)'
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter18printBarrierOptionEPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE+0x168): undefined reference to `llvm::AArch64ISB::lookupISBByEncoding(unsigned char)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `llvm::AArch64InstPrinter::printBarriernXSOption(llvm::MCInst const*, unsigned int, llvm::MCSubtargetInfo const&, llvm::raw_ostream&)':
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter21printBarriernXSOptionEPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE+0x2c): undefined reference to `llvm::AArch64DBnXS::lookupDBnXSByEncoding(unsigned char)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `llvm::AArch64InstPrinter::printMRSSystemRegister(llvm::MCInst const*, unsigned int, llvm::MCSubtargetInfo const&, llvm::raw_ostream&)':
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter22printMRSSystemRegisterEPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE+0xb8): undefined reference to `llvm::AArch64SysReg::genericRegisterString[abi:cxx11](unsigned int)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `llvm::AArch64InstPrinter::printMSRSystemRegister(llvm::MCInst const*, unsigned int, llvm::MCSubtargetInfo const&, llvm::raw_ostream&)':
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter22printMSRSystemRegisterEPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE+0xb8): undefined reference to `llvm::AArch64SysReg::genericRegisterString[abi:cxx11](unsigned int)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `llvm::AArch64InstPrinter::printSystemPStateField(llvm::MCInst const*, unsigned int, llvm::MCSubtargetInfo const&, llvm::raw_ostream&)':
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter22printSystemPStateFieldEPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE+0x34): undefined reference to `llvm::AArch64PState::lookupPStateImm0_15ByEncoding(unsigned char)'
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter22printSystemPStateFieldEPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE+0x40): undefined reference to `llvm::AArch64PState::lookupPStateImm0_1ByEncoding(unsigned short)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `llvm::AArch64InstPrinter::printSVEPattern(llvm::MCInst const*, unsigned int, llvm::MCSubtargetInfo const&, llvm::raw_ostream&)':
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter15printSVEPatternEPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE+0x2c): undefined reference to `llvm::AArch64SVEPredPattern::lookupSVEPREDPATByEncoding(unsigned char)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `llvm::AArch64InstPrinter::printSVEVecLenSpecifier(llvm::MCInst const*, unsigned int, llvm::MCSubtargetInfo const&, llvm::raw_ostream&)':
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter23printSVEVecLenSpecifierEPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE+0x24): undefined reference to `llvm::AArch64SVEVecLenSpecifier::lookupSVEVECLENSPECIFIERByEncoding(unsigned char)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `void llvm::AArch64InstPrinter::printPrefetchOp<true>(llvm::MCInst const*, unsigned int, llvm::MCSubtargetInfo const&, llvm::raw_ostream&)':
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter15printPrefetchOpILb1EEEvPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE[_ZN4llvm18AArch64InstPrinter15printPrefetchOpILb1EEEvPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE]+0x2c): undefined reference to `llvm::AArch64SVEPRFM::lookupSVEPRFMByEncoding(unsigned char)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `void llvm::AArch64InstPrinter::printPrefetchOp<false>(llvm::MCInst const*, unsigned int, llvm::MCSubtargetInfo const&, llvm::raw_ostream&)':
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter15printPrefetchOpILb0EEEvPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE[_ZN4llvm18AArch64InstPrinter15printPrefetchOpILb0EEEvPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE]+0x38): undefined reference to `llvm::AArch64PRFM::lookupPRFMByEncoding(unsigned char)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `void llvm::AArch64InstPrinter::printExactFPImm<1u, 2u>(llvm::MCInst const*, unsigned int, llvm::MCSubtargetInfo const&, llvm::raw_ostream&)':
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter15printExactFPImmILj1ELj2EEEvPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE[_ZN4llvm18AArch64InstPrinter15printExactFPImmILj1ELj2EEEvPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE]+0x28): undefined reference to `llvm::AArch64ExactFPImm::lookupExactFPImmByEnum(unsigned char)'
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter15printExactFPImmILj1ELj2EEEvPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE[_ZN4llvm18AArch64InstPrinter15printExactFPImmILj1ELj2EEEvPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE]+0x34): undefined reference to `llvm::AArch64ExactFPImm::lookupExactFPImmByEnum(unsigned char)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `void llvm::AArch64InstPrinter::printExactFPImm<0u, 2u>(llvm::MCInst const*, unsigned int, llvm::MCSubtargetInfo const&, llvm::raw_ostream&)':
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter15printExactFPImmILj0ELj2EEEvPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE[_ZN4llvm18AArch64InstPrinter15printExactFPImmILj0ELj2EEEvPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE]+0x28): undefined reference to `llvm::AArch64ExactFPImm::lookupExactFPImmByEnum(unsigned char)'
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter15printExactFPImmILj0ELj2EEEvPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE[_ZN4llvm18AArch64InstPrinter15printExactFPImmILj0ELj2EEEvPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE]+0x34): undefined reference to `llvm::AArch64ExactFPImm::lookupExactFPImmByEnum(unsigned char)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `void llvm::AArch64InstPrinter::printExactFPImm<1u, 3u>(llvm::MCInst const*, unsigned int, llvm::MCSubtargetInfo const&, llvm::raw_ostream&)':
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter15printExactFPImmILj1ELj3EEEvPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE[_ZN4llvm18AArch64InstPrinter15printExactFPImmILj1ELj3EEEvPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE]+0x28): undefined reference to `llvm::AArch64ExactFPImm::lookupExactFPImmByEnum(unsigned char)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o):AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter15printExactFPImmILj1ELj3EEEvPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE[_ZN4llvm18AArch64InstPrinter15printExactFPImmILj1ELj3EEEvPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE]+0x34): more undefined references to `llvm::AArch64ExactFPImm::lookupExactFPImmByEnum(unsigned char)' follow
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `llvm::AArch64InstPrinter::printSysAlias(llvm::MCInst const*, llvm::MCSubtargetInfo const&, llvm::raw_ostream&)':
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter13printSysAliasEPKNS_6MCInstERKNS_15MCSubtargetInfoERNS_11raw_ostreamE+0xa8): undefined reference to `llvm::AArch64TLBI::lookupTLBIByEncoding(unsigned short)'
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter13printSysAliasEPKNS_6MCInstERKNS_15MCSubtargetInfoERNS_11raw_ostreamE+0x190): undefined reference to `llvm::AArch64AT::lookupATByEncoding(unsigned short)'
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter13printSysAliasEPKNS_6MCInstERKNS_15MCSubtargetInfoERNS_11raw_ostreamE+0x37c): undefined reference to `llvm::AArch64DC::lookupDCByEncoding(unsigned short)'
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter13printSysAliasEPKNS_6MCInstERKNS_15MCSubtargetInfoERNS_11raw_ostreamE+0x4d4): undefined reference to `llvm::AArch64IC::lookupICByEncoding(unsigned short)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `llvm::AArch64InstPrinter::printSyspAlias(llvm::MCInst const*, llvm::MCSubtargetInfo const&, llvm::raw_ostream&)':
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter14printSyspAliasEPKNS_6MCInstERKNS_15MCSubtargetInfoERNS_11raw_ostreamE+0x94): undefined reference to `llvm::AArch64TLBI::lookupTLBIByEncoding(unsigned short)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `llvm::AArch64InstPrinter::printInstruction(llvm::MCInst const*, unsigned long, llvm::MCSubtargetInfo const&, llvm::raw_ostream&)':
AArch64InstPrinter.cpp:(.text._ZN4llvm18AArch64InstPrinter16printInstructionEPKNS_6MCInstEmRKNS_15MCSubtargetInfoERNS_11raw_ostreamE+0x3e4): undefined reference to `llvm::AArch64SVCR::lookupSVCRByEncoding(unsigned char)'
/var/local/thirdparty/installed//llvm/lib/libLLVMAArch64Desc.a(AArch64InstPrinter.cpp.o): In function `llvm::AArch64AppleInstPrinter::printInstruction(llvm::MCInst const*, unsigned long, llvm::MCSubtargetInfo const&, llvm::raw_ostream&)':
AArch64InstPrinter.cpp:(.text._ZN4llvm23AArch64AppleInstPrinter16printInstructionEPKNS_6MCInstEmRKNS_15MCSubtargetInfoERNS_11raw_ostreamE+0x13b4): undefined reference to `llvm::AArch64SVCR::lookupSVCRByEncoding(unsigned char)'
collect2: error: ld returned 1 exit status
### StarRocks version (Required)
main branch

**Comment by kevincai** [comment]
can you provide the exact git commit id and the dev-env-centos7 docker image id?

**Comment by 1153710405** [comment]
> can you provide the exact git commit id and the dev-env-centos7 docker image id?

commit id: b01ed409a193606199095693253de5e0758c1a48
docker image id: bdaa879393c3

**Comment by kevincai** [comment]
let me check the compiling based on your PR.

**Comment by kevincai** [comment]
@1153710405 it is a fairly easy fix. please check #40967 , make that one line change in your local code, and continue your arm64 build testing.
