### ISSUE TITLE
V2.2 Release plan

### ISSUE THREAD

**Issue by Dshadowzh** [StarRocks/starrocks#4095]
### New feature
- Support **resource group**. Use Resource groups to reasonably control CPU and memory resources to achieve multi-tenant resource isolation, while also making the best use of resources, allowing different loads to work on the same cluster.
- Support **UDF**. You can write JAVA user-defined functions to implement custom requirements.
- **Primary key model supports partial update**. You can use stream load / broker load / routine load to update some of the columns. For example, use partial update instead of multi-stream join.
- Support **Hudi external table**. 
- Support **JSON** type. Make it easy to access semi-structured data efficiently.
- Support more functions
  -  Bitmap_max, Bitmap_min
  - [array_agg](https://github.com/StarRocks/docs.zh-cn/pull/253)[ ](https://github.com/StarRocks/docs.zh-cn/pull/269)   [array_sort](https://github.com/StarRocks/docs.zh-cn/pull/271) [array_distinct](https://github.com/StarRocks/docs.zh-cn/pull/266) [array_join](https://github.com/StarRocks/docs.zh-cn/pull/282)  array_slice array_concat array_difference array_overlap array_intersect
  - [reverse](https://github.com/StarRocks/docs.zh-cn/pull/272) 
  - [retention](https://github.com/StarRocks/docs.zh-cn/pull/269) 
- Pipeline engine release. 
  
### Improvement
- TPC-DS benchmark performance improvement, including CTE reuse.
- Compaction strategy improvement 
- Improve performance of Hive external table on S3
- Incremental synchronization of Hive metadata.
- Support Decimal and Array in Hive external table

**Comment by cj1201** [comment]
2.2什么预计什么时候发布？

**Comment by Dshadowzh** [comment]
2.0.0-rc will publish in this week.

**Comment by mklzl** [comment]
> 2.0.0-rc will publish in this week.

2.2.0？ or 2.0.0?

**Comment by Dshadowzh** [comment]
Sorry, It's 2.2.0-rc. You can download here, https://www.starrocks.com/en-us/download/community

**Comment by cj1201** [comment]
请问2.2什么时候发布正式版呀？

**Comment by Dshadowzh** [comment]
At the end of this month.

**Comment by tangjunj1994** [comment]
请问2.2.0有正式的release时间表吗，已经到5月份了。
