### ISSUE TITLE
Configuring StarRock Connection to Hive Catalog with Kerberos Authentication Issue

### ISSUE THREAD

**Issue by CherryYummy** [StarRocks/starrocks#41005]
[](https://docs.starrocks.io/docs/data_source/catalog/hive_catalog/ )The documentation lacks specific details on setting up the connection to a Hive catalog with Kerberos. It does not provide guidance on which files need configuration, such as jaas.conf and hive-site.xml. Despite following the outlined steps, errors persist, and there is insufficient information for troubleshooting. I've documented the steps I've taken below. If you can identify any mistakes or provide additional insights, your assistance would be greatly appreciated.

 I try to setup starrock on BM (CENTOS) connect to Hive catalog with kerberos.
i took step as below. but I got the error as in the thread . Does Anyone know how to solve it?
tep
Add JAAS config jaas.conf in /opt/starrock/
jaas.conf
`HiveMetastoreJaas {
com.sun.security.auth.module.Krb5LoginModule required
useKeyTab=true
useTicketCache=true
storeKey=false
renewTicket=true
debug=true;
};`
2. Add /etc/krb5.conf to all FE and CN in fe.conf and cn.conf by adding  JAVA_OPTS="-Djava.security.krb5.conf=/etc/krb5.conf -Djava.security.auth.login.config=/opt/starrock/jaas.conf" and JAVA_OPTS_JDK_11 ="-Djava.security.krb5.conf=/etc/krb5.conf -Djava.security.auth.login.config=/opt/starrock/jaas.conf"
3. paste starrock.keytab in /etc/security/keytabs and test kinit -kt /etc/security/keytabs/starrock.keytab starrock
4. Add hive-site.xml to the fe/conf dir
`<configuration>
    <property>
        <name>hive.metastore.kerberos.principal</name>
        <value>hive/metastore.hkp.hd.ag.local@DOMAIN.DOM</value>
    </property>
    <property>
        <name>hive.metastore.sasl.enabled</name>
        <value>true</value>
    </property>
</configuration>`
5. Restart all FE and CN
6.create catalog
`CREATE EXTERNAL CATALOG hive_hk
PROPERTIES
(
"type" = "hive",
"hive.metastore.type" = "hive",
"hive.metastore.uris" = "thrift://metastore.hkp.hd.ag.local:9083")`

**Comment by CherryYummy** [comment]
https://starrocks.slack.com/archives/C02FACZSNJV/p1707219380741559

**Comment by alberttwong** [comment]
Pretty much Security is out of scope for the community version.  You're welcome to work on it and then donating it to the community project.   If you really want this to work, I would contact CelerData.
