### ISSUE TITLE
unlimited: integer expression expected

### ISSUE THREAD

**Issue by geoHeil** [StarRocks/starrocks#41026]
### Steps to reproduce the behavior (Required)

a docker compose file with

https://github.com/StarRocks/demo/blob/master/deploy/docker-compose/docker-compose.yml 3.3.2 version of starrocks

### Expected behavior (Required)

no error

### Real behavior (Required)

```
unlimited: integer expression expected
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by kevincai** [comment]
fixed in https://github.com/StarRocks/starrocks/pull/39967 but not included in v3.2.3, please wait for next minor release to include this fix.
