### ISSUE TITLE
Provides locale / en_us.UTF-8 in docker images

### ISSUE THREAD

**Issue by teddy-hackle** [StarRocks/starrocks#41035]
## Feature request
Default docker image does not have locale packages.
Locale is not set in Ubuntu.

**Is your feature request related to a problem? Please describe.**

We are serving in Korea, and we need to log using auditLoader.
If there is korean in the query, It is recorded as `???` in the log.

**Describe the solution you'd like**

```dockerfile
RUN apt-get update -y && \
    apt-get -y install --no-install-recommends locales && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US.UTF-8
```

**Describe alternatives you've considered**

**Additional context**

**Comment by kevincai** [comment]
fixed in #41039

**Comment by teddy-hackle** [comment]
@kevincai We use audit loader. I think it should work for frontend too.

**Comment by kevincai** [comment]
I see, this locale is needed for FE docker image as well.
