### ISSUE TITLE
Support timezone sync in container images

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#41047]
https://www.howtogeek.com/devops/how-to-handle-timezones-in-docker-containers/

**Comment by kevincai** [comment]
`TZ` env works for all our docker image. Is it good enough?

**Comment by alberttwong** [comment]
It shows UTC TZ.   I was expecting that if I query the TZ in the container, it should show PST.

**Comment by kevincai** [comment]
the docker image is just a static image of the filesystem and a bunch of scripts, it is hard to detect the host TZ and sync it to the container.

Usually it will be up to the user who starts the container from the image to set correct `TZ` env to reflect the correct location.
