### ISSUE TITLE
show resources cmd blocked

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#4111]
### Steps to reproduce the behavior (Required)
```
mysql> create database show_resource_db_test;
Query OK, 0 rows affected (0.00 sec)

mysql> use show_resource_db_test;
Database changed
mysql> show resources;

```
### Expected behavior (Required)
return resources info
### Real behavior (Required)
cmd execute blocked

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - main Release && ASAN

**Comment by hiliuxg** [comment]
can this assign to me  ?

**Comment by imay** [comment]
> can this assign to me ?

Thanks, I will assign it to you.
