### ISSUE TITLE
[enhancement] Reduce duplicate data in execPlanFragmentAsync during RPC transmission.

### ISSUE THREAD

**Issue by liming30** [StarRocks/starrocks#41277]
## Enhancement
Currently, when `FE` deploys `PlanFragment` to `BE`, both `data` and `attachment` in `RpcDataPackage` contain the serialization result of plan fragment, causing the rpc message body size to double. This leaves brpc with only half the bandwidth available.

1. `data` added to `RpcDataPackage`: https://github.com/baidu/Jprotobuf-rpc-socket/blob/master/jprotobuf-rpc-core/src/main/java/com/baidu/jprotobuf/pbrpc/data/RpcDataPackage.java#L762
2. `attachment` added to `RpcDataPackage`: https://github.com/StarRocks/starrocks/blob/main/fe/fe-core/src/main/java/com/starrocks/rpc/ThriftClientAttachmentHandler.java#L24

## Solution
There are two ways to reduce redundant data:
1. remove the `attachment` in `FE` and modify the code on the `BE` side to use the `data`. This may cause different versions of `FE` and `BE` to be incompatible.
2. currently, `BE` only uses `attachment`, so the `codec` can be rewritten in `FE` without serializing the plan fragment into rpc. The advantage is that different versions are compatible.

**Comment by liming30** [comment]
@kangkaisen Thanks for your reply. Which solution do you think is more reasonable?

**Comment by kangkaisen** [comment]
> @kangkaisen Thanks for your reply. Which solution do you think is more reasonable?

@liming30 Sorry for delay. I prefer to solution 2. we should use the compatible solution as much as possible.

**Comment by liming30** [comment]
@kangkaisen Can you help assign this issue to me? I should be able to fix it.
