### ISSUE TITLE
Problem in UI of starrocks homepage

### ISSUE THREAD

**Issue by ajayanuragi** [StarRocks/starrocks#41352]
## Enhancement

When we scroll to the bottom in homepage, download now button should be in a line, 

Currently download and now are in different line.

Attaching screenshot of the problem 
![Screenshot_2024-02-21-17-36-42-614_com.brave.browser.jpg](https://github.com/StarRocks/starrocks/assets/92710715/a22ad354-1a3f-48bb-8710-f6eacdb05061)

**Comment by hffariel** [comment]
Sorry for the bad experience, and it's been fixed.
