### ISSUE TITLE
Vector memory usage problem

### ISSUE THREAD

**Issue by zhangzf875** [StarRocks/starrocks#41414]
I have 40 collections on qdrant installed with version 1.7.2, and the memory of the server is 5G. I will optimize the collection through the official document and update the configuration information of these 40 collections:
PATCH /collections/collection_name
{
"optimizers_config": {
"memmap_threshold": 20000
}
}
After the update, it is found that the memory occupied by the server is still unchanged, what is the reason for this, and how to optimize the collection memory usage

**Comment by mofeiatwork** [comment]
I think you should put the issue qdrant repo instead of StarRocks ?
