### ISSUE TITLE
Isolate udf objects in shared udf mode

### ISSUE THREAD

**Issue by MicePilot** [StarRocks/starrocks#41567]
## Feature request

**Is your feature request related to a problem? Please describe.**

https://github.com/StarRocks/starrocks/pull/34812 makes it easy to use static variables to share and cache some data in udf, but in this implementation, it seems that the entire JavaUDFContext object is shared, and the udf_handle in this object stores an object of the udf class, which means that in In shared mode, each java udf expr using the same name udf will use the same udf_handle, so that the member variables of each java udf expr are also shared, which will be very inconvenient in some scenarios.

**Describe the solution you'd like**

I want to be able to share static variables, but isolate member variables, so, could you please isolate the udf_handle in shared udf mode，or add a new mode to isolate udf_handle?

**Describe alternatives you've considered**

**Additional context**

For example：
```java
public class TestFunc {
    private int num = 0;
    public final String evaluate(String type, String value) {
        num++;
        return type + value + num;
    }
}
```
Suppose I register the above udf. In shared mode, when two different SQLs use this udf, the variable num will affect each other because they use the same object.

**Comment by MicePilot** [comment]
@stdpain Hello，do you have any plans for this issue？

**Comment by kangkaisen** [comment]
@MicePilot Hi，could you let me know why do you want to use member variables in the UDF?

**Comment by MicePilot** [comment]
> @MicePilot Hi，could you let me know why do you want to use member variables in the UDF?

Of course, in our udf, assuming its name is testFunc, testFunc will load another jar package to do some intermediate result calculations. For the same expr, it only needs to be initialized and loaded once, so I will store this result in member variables, avoid repeated loading during each data calculation.
