### ISSUE TITLE
maven error during building in docker

### ISSUE THREAD

**Issue by chinawch007** [StarRocks/starrocks#4157]
I follow this.

    docker run -it --name sr -d starrocks/dev-env:main
    docker exec -it sr /bin/bash
    git clone https://github.com/StarRocks/starrocks.git
    cd starrocks
    sh build.sh

And I meet this error:

    Build Frontend Modules: fe-common,spark-dpp,fe-core
    [INFO] Scanning for projects...
    [WARNING]
    [WARNING] Some problems were encountered while building the effective model for com.starrocks:spark-dpp:jar:1.0.0
    [WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
    [WARNING]
    [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
    [WARNING]
    [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
    [WARNING]
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Build Order:
    [INFO]
    [INFO] fe-common [jar]
    [INFO] spark-dpp [jar]
    [INFO] fe-core [jar]
    [INFO]
    [INFO] ----------------------< com.starrocks:fe-common >-----------------------
    [INFO] Building fe-common 1.0.0 [1/3]
    [INFO] --------------------------------[ jar ]---------------------------------
    Downloading from spring-plugins: https://repo.spring.io/plugins-release/org/apache/maven/plugins/maven-checkstyle-plugin/3.1.1/maven-checkstyle-plugin-3.1.1.pom
    Downloading from cloudera-public: https://repository.cloudera.com/artifactory/public/org/apache/maven/plugins/maven-checkstyle-plugin/3.1.1/maven-checkstyle-plugin-3.1.1.pom
    Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-checkstyle-plugin/3.1.1/maven-checkstyle-plugin-3.1.1.pom
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Summary:
    [INFO]
    [INFO] fe-common 1.0.0 .................................... FAILURE [ 6.457 s]
    [INFO] spark-dpp 1.0.0 .................................... SKIPPED
    [INFO] fe-core 3.4.0 ...................................... SKIPPED
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 6.564 s
    [INFO] Finished at: 2022-03-16T02:39:36Z
    [INFO] ------------------------------------------------------------------------
    [ERROR] Plugin org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-checkstyle-plugin:jar:3.1.1: Could not transfer artifact org.apache.maven.plugins:maven-checkstyle-plugin:pom:3.1.1 from/to spring-plugins (https://repo.spring.io/plugins-release/): Transfer failed for https://repo.spring.io/plugins-release/org/apache/maven/plugins/maven-checkstyle-plugin/3.1.1/maven-checkstyle-plugin-3.1.1.pom: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty -> [Help 1]
    [ERROR]
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR]
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

What should I do? Please help me.

**Comment by stdpain** [comment]
> [ERROR] Plugin org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-checkstyle-plugin:jar:3.1.1: Could not transfer artifact org.apache.maven.plugins:maven-checkstyle-plugin:pom:3.1.1 from/to spring-plugins (https://repo.spring.io/plugins-release/): Transfer failed for https://repo.spring.io/plugins-release/org/apache/maven/plugins/maven-checkstyle-plugin/3.1.1/maven-checkstyle-plugin-3.1.1.pom: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty -> [Help 1]
[ERROR]

please check your network

**Comment by chinawch007** [comment]
> 

ok, I try.

**Comment by stdpain** [comment]
you could add a mirror in `~/.m2/settings.xml `
```
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <localRepository/>
  <interactiveMode/>
  <usePluginRegistry/>
  <offline/>
  <pluginGroups/>
  <servers/>
  <mirrors>
    <mirror>
     <id>aliyunmaven</id>
     <mirrorOf>central</mirrorOf>
     <name>阿里云公共仓库</name>
     <url>https://maven.aliyun.com/repository/central</url>
    </mirror>
    <mirror>
      <id>repo1</id>
      <mirrorOf>central</mirrorOf>
      <name>central repo</name>
      <url>http://repo1.maven.org/maven2/</url>
    </mirror>
    <mirror>
     <id>aliyunmaven</id>
     <mirrorOf>apache snapshots</mirrorOf>
     <name>阿里云阿帕奇仓库</name>
     <url>https://maven.aliyun.com/repository/apache-snapshots</url>
    </mirror>
  </mirrors>
  <proxies/>
  <activeProfiles/>
  <profiles>
    <profile>  
        <repositories>
           <repository>
                <id>aliyunmaven</id>
                <name>aliyunmaven</name>
                <url>https://maven.aliyun.com/repository/public</url>
                <layout>default</layout>
                <releases>
                        <enabled>true</enabled>
                </releases>
                <snapshots>
                        <enabled>true</enabled>
                </snapshots>
            </repository>
            <repository>
                <id>MavenCentral</id>
                <url>http://repo1.maven.org/maven2/</url>
            </repository>
            <repository>
                <id>aliyunmavenApache</id>
                <url>https://maven.aliyun.com/repository/apache-snapshots</url>
            </repository>
            <repository>
                <id>spring</id>
                <url>https://maven.aliyun.com/repository/spring</url>
                <releases>
                <enabled>true</enabled>
                </releases>
                <snapshots>
                    <enabled>true</enabled>
                </snapshots>
            </repository>
        </repositories>             
     </profile>
  </profiles>
</settings>
```

**Comment by chinawch007** [comment]
How do I make this xml work, just write these contents into ~/.m2/settings.xml ?
I had writen this xml and tried building in aliyun HongKong emc and aliyun ShangHai emc, but still met this errors...

**Comment by stdpain** [comment]
you could run `curl https://repo.spring.io/plugins-release/` and see output.

**Comment by chinawch007** [comment]
I got this.
![image](https://user-images.githubusercontent.com/13758273/158587597-a98d6d0b-1010-4b66-949a-fb0597a88a11.png)

**Comment by stdpain** [comment]
could you retry it with a oracle JDK?
https://stackoverflow.com/questions/21579247/plugin-org-apache-maven-pluginsmaven-compiler-plugin-or-one-of-its-dependencies

**Comment by chinawch007** [comment]
ok, I try.

**Comment by stdpain** [comment]
@waittttting We need to consider putting ~/.m2 into the docker image.
