### ISSUE TITLE
Support open source data visualization tool Redash

### ISSUE THREAD

**Issue by realzyy** [StarRocks/starrocks#41592]
## Feature request

**Is your feature request related to a problem? Please describe.**
I am using Redash to manage all kinds of database services including MySQL, MongoDB, TiDB, and ClickHouse.
However, I cannot find StarRocks on the list. Where can I find an open-source query editor and dashboard for StarRocks?

**Describe the solution you'd like**
It should be easy to add StarRocks to the list since StarRocks is MySQL-compatible.
https://github.com/getredash/redash

**Describe alternatives you've considered**
Maybe Bytebase since it's open source

**Additional context**

**Comment by kangkaisen** [comment]
Hi，Can you describe the specific issue? Thanks.
If there are not many problems, we can fix them as soon as possible
