### ISSUE TITLE
support file() function for version 2.5

### ISSUE THREAD

**Issue by MicePilot** [StarRocks/starrocks#41635]
## Feature request

**Is your feature request related to a problem? Please describe.**

We are using version 2.5 of SR and need to use the files() function to read CSV files. This feature has already been implemented in https://github.com/StarRocks/starrocks/pull/37875 submission. Do you have any plans to check pick it in version 2.5?

**Describe the solution you'd like**

Cherry pick related submissions to version 2.5 and release in the next version

**Describe alternatives you've considered**

**Additional context**

**Comment by imay** [comment]
Sorry for that, new features are not planned to back-port to released version. If you want to use this feature, you need to upgrade to the new versions.

**Comment by MicePilot** [comment]
Got it, thanks
