### ISSUE TITLE
Registering a BE or CN with the FEs uses IP address instead of hostname

### ISSUE THREAD

**Issue by DanRoscigno** [StarRocks/starrocks#41681]
## Enhancement

When using stream load I specify the hostname and port of an FE and the stream load job gets assigned to a BE or a CN. This makes sense to me.

But

The FE assigns it to the IP address of the BE or CN instead of the hostname of the BE or CN, and that IP may be local to the internal network of the StarRocks cluster. The use of an internal network is likely true in the case where StarRocks is running in a Docker environment. My local machine may not know the IP address, but if a hostname was used I could expose the port 8040 and assign the hostname to 127.0.0.1. 

Would it be possible to use the hostname that the BE or CN registers as instead of the internal IP address when forwarding the curl connection to the BE or CN?

Here is how I am registering:
```
mysql --connect-timeout 2 -h starrocks-fe -P9030 -uroot -e \
"ALTER SYSTEM ADD COMPUTE NODE \"starrocks-cn:9050\";"
```

**Comment by kevincai** [comment]
@DanRoscigno are you talking about our fqdn mode, or enhance our allin1 image with fqdn name registering?

**Comment by DanRoscigno** [comment]
This is not for allin1, it is for standard docker containers. I did not know about FQDN mode, but it sounds like what I need.  Thanks for telling me about it. I will give it a try!

**Comment by rkinwork** [comment]
@DanRoscigno Do you have updated version of the docker-compose file with FQDN mode?

**Comment by DanRoscigno** [comment]
> @DanRoscigno Do you have updated version of the docker-compose file with FQDN mode?

Hi Roman. No, I will give it a go now. This has been on my list for a while.

**Comment by DanRoscigno** [comment]
@rkinwork here it is: https://raw.githubusercontent.com/StarRocks/demo/a5ed13f9c0e9f11fa99debd784294342bcb5c6a4/documentation-samples/quickstart/docker-compose.yml

I have not merged this yet, I need to update the docs and possibly add a delay to the minio_mc job that sets up the access key, as it failed one time in testing today. If you have the same issue then just run this after the minio service shows healthy:

```
docker compose run minio_mc
```

You also need starrocks_cn in /etc/hosts:

```
127.0.0.1 starrocks-cn
```

**Comment by rkinwork** [comment]
> You also need starrocks_cn in /etc/hosts:

Thank you, Dan. This eventually helped me set up my local dev environment properly
