### ISSUE TITLE
A simple query takes a lot of time in the primary key model table, and the field has been added with `bitmap index`

### ISSUE THREAD

**Issue by sanikoyes** [StarRocks/starrocks#41680]
### Steps to reproduce the behavior (Required)

query is:

```bash

StarRocks > select count(*) from ta_user_119;
+----------+
| count(*) |
+----------+
| 41631084 |
+----------+
1 row in set (22.41 sec)

StarRocks > SELECT `user_id`, `distinct_id`, `distinct_list` FROM `ta_user_119` WHERE `account_id` = 91271240;
+---------------------+--------------------------+----------------------------------------------------------+
| user_id             | distinct_id              | distinct_list                                            |
+---------------------+--------------------------+----------------------------------------------------------+
| 1156955274418860033 | 8241407947-1689326386000 | ["8241407947-1689326386000"]                             |
| 1171345915089268736 | 6313635658-1699312227285 | ["8241407947-1689326386000", "6313635658-1699312227285"] |
+---------------------+--------------------------+----------------------------------------------------------+
2 rows in set (7.33 sec)

```

create table sql is:
```sql
CREATE TABLE `ta_user_119` (
  `user_id` bigint(20) NOT NULL COMMENT "#user_id",
  `account_id` varchar(128) NULL COMMENT "#account_id",
  `distinct_id` varchar(128) NULL COMMENT "#distinct_id",
  `active_time` datetime NULL COMMENT "#active_time",

  //
  // ...
  //

  INDEX index_account_id (`account_id`) USING BITMAP,
  INDEX index_distinct_id (`distinct_id`) USING BITMAP
) ENGINE=OLAP 
PRIMARY KEY(`user_id`)
DISTRIBUTED BY HASH(`user_id`)
ORDER BY(`active_time`)
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
);
```

### Expected behavior (Required)

How to optimize this table to quickly query the required data through the account_id field?

### Real behavior (Required)

too slow, in 7.33 sec

### StarRocks version (Required)

3.1.5-5d8438a

**Comment by kangkaisen** [comment]
@sanikoyes Hi，could you send us the query profile? https://docs.starrocks.io/docs/administration/query_profile_overview/

**Comment by sanikoyes** [comment]
> @sanikoyes Hi，could you send us the query profile? https://docs.starrocks.io/docs/administration/query_profile_overview/

background:
1. When data that does not exist in redis, query it from starrocks and store it in redis
2. After starting the server at the first time, a large number of query requests came to the starrocks server.

When performance issues occurred, I checked the status of the server:
1. There are about 120 sql queries executing, all with the same statement.
2. Each query takes 5-10 seconds to execute.
3. The CPU usage of all be (3 nodes, each node is configured with 8 cores and 16g ram) has reached 100%
4. After stopping the server and pending query finished, the execution time of this query down to about 0.1 seconds.

My questions:
1. Is starrocks not suitable for this kind of concurrent query business scenario?
2. If it can be used in this way, how should I optimize the table?

I am considering switching to mysql for data storage + query, and synchronizing it to starrocks in real time. . .
