### ISSUE TITLE
Catalog 查询 不支持 表和列的 comment

### ISSUE THREAD

**Issue by PalaceK999** [StarRocks/starrocks#41903]
sr的版本：3.1.2
创建的catalog是 hive的catalog（同理 mysql的catalog也无法获取）
无法获取表和列的comment
![image](https://github.com/StarRocks/starrocks/assets/55040421/3ae6c9ae-f4f7-4ed8-88f8-0208bb04f3b9)

**Comment by 839224346** [comment]
https://github.com/StarRocks/starrocks/pull/37712
