### ISSUE TITLE
[BUG] Hive partition pruning failed for a date-type partition that has a value with an invalid date format

### ISSUE THREAD

**Issue by haiboself** [StarRocks/starrocks#42033]
### Steps to reproduce the behavior (Required)
1. CREATE HIVE TABLE & Add a invalid date format partition
```
create table test_partition_prune(a int) partitioned by (dt string comment 'yyyy-mm-dd');
 alter table test_partition_prune add partition(dt='xxxxx');
```
2. Query this table by starrocks using hive catalog

```
mysql> explain select * from hive_catalog.tmp.test_partition_prune where dt = to_date(days_add(now(),-1));
ERROR 1064 (HY000): can not cast literal value xxxxx to target type datetime
```
### Expected behavior (Required)
execute success

### Real behavior (Required)
execute failed

### StarRocks version (Required)
- 3.1.8
- 3.2.3

**Comment by letian-jiang** [comment]
Why not just delete the invalid partition? Is it useful?

**Comment by wangsimo0** [comment]
I've tested trino, it will also report a cast fail.

**Comment by haiboself** [comment]
> I've tested trino, it will report a cast fail at first because dt is a string col and the data type in where condition is date. and I add a cast to dt, also report a cast fail because there is a xxxxx.

The 'yyyy-mm' format value also triggers this error. Does it also fail in Trino? reproduce steps:
```
alter table test_partition_prune add partition(dt='2024-01');
mysql> explain select * from hive_catalog.tmp.test_partition_prune where dt = to_date(days_add(now(),-1));
ERROR 1064 (HY000): can not cast literal value 2024-01 to target type datetime
```

**Comment by haiboself** [comment]
> Why not just delete the invalid partition? Is it useful?

Because starrocks 2.5 can execute successfully while move to higher version execute failed that let user feel confused.

**Comment by letian-jiang** [comment]
The fact is that SR2.5 does not make use of the predicate, therefore the SQL is executed successfully.

**Comment by letian-jiang** [comment]
In 3.1+, the predicate is used to prune partitions. However, you have a partition of type string `xxxx` that is unable to cast to type date. Hence, the SQL fails.

**Comment by wangsimo0** [comment]
> > I've tested trino, it will report a cast fail at first because dt is a string col and the data type in where condition is date. and I add a cast to dt, also report a cast fail because there is a xxxxx.
> 
> The 'yyyy-mm' format value also triggers this error. Does it also fail in Trino? reproduce steps:
> 
> ```
> alter table test_partition_prune add partition(dt='2024-01');
> mysql> explain select * from hive_catalog.tmp.test_partition_prune where dt = to_date(days_add(now(),-1));
> ERROR 1064 (HY000): can not cast literal value 2024-01 to target type datetime
> ```

yyyy-mm is not a valid date format either, can not be cast to date directly.
