### ISSUE TITLE
[Bug] Querying the Hive table failed because it didn't skip the “_temporary” directory

### ISSUE THREAD

**Issue by haiboself** [StarRocks/starrocks#42060]
I find StarRocks 2.5.x will skip _tempory dir created by spark（In Spark, a workspace directory named _temporary/ is created under the directory where the table is located to store the intermediate work, and all apps share this workspace） while StarRocks 3.x dont when query hive table

### Steps to reproduce the behavior (Required)
1. Create a temporary directory in specific in a hive table  named tmp.test
```
hdfs://data/tmp/vom/test/dt=2023-10-11/_temporary/0/_temporary/...files
```
2. Refresh external partition
```
refresh external table hive_catalog.tmp.test partition("dt=2023-10-11");
```
3. watch Fe behavior using arthas
```
watch com.starrocks.connector.CachingRemoteFileIO  loadRemoteFiles "{returnObj}" -s -x 2 
``` 
4. query hive table failed
```
select * from hive_catalog.tmp.test where dt = '2023-10-11'  failed , error msg:
ERROR 1064 (HY000): Parquet file size is 4 bytes, smaller than the minimum parquet file footer (8 bytes)
```

### Expected behavior (Required)
skip _temporary and query success
### Real behavior (Required)
dont skip  files from _temporary dir & query failed
```
[arthas@530181]$ watch com.starrocks.connector.CachingRemoteFileIO  loadRemoteFiles "{returnObj}" -s -x 2 "params[0].path.contains('test')"
Press Q or Ctrl+C to abort.
Affect(class count: 1 , method count: 1) cost in 160 ms, listenerId: 12
method=com.starrocks.connector.CachingRemoteFileIO.loadRemoteFiles location=AtExit
ts=2024-03-04 15:54:55; [cost=11.725592ms] result=@ArrayList[
    @ArrayList[
        @RemoteFileDesc[RemoteFileDesc{fileName='_temporary/0/_temporary/attempt_20240123104122_0008_m_000000_1470/part-00000-79dfc67c-c157-4f3e-bc3e-c410b6d167d9-c000.snappy.parquet', compression='', length=4, modificationTime=1705977697753, blockDescs=[RemoteFileBlockDesc{offset=0, length=4, replicaHostIds=[140], 133], 443], diskIds=[-1], remoteFileIO=com.starrocks.connector.hive.HiveRemoteFileIO@9b4f9a0}], splittable=false, textFileFormatDesc=null, hudiDeltaLogs=[], icebergScanTasks=[], paimonSplitsInfo=null}],
        @RemoteFileDesc[RemoteFileDesc{fileName='_temporary/0/_temporary/attempt_20240123104122_0008_m_000003_1473/part-00003-79dfc67c-c157-4f3e-bc3e-c410b6d167d9-c000.snappy.parquet', compression='', length=2193, modificationTime=1705977697748, blockDescs=[RemoteFileBlockDesc{offset=0, length=2193, replicaHostIds=[709], 339], 226], diskIds=[-1], remoteFileIO=com.starrocks.connector.hive.HiveRemoteFileIO@9b4f9a0}], splittable=false, textFileFormatDesc=null, hudiDeltaLogs=[], icebergScanTasks=[], paimonSplitsInfo=null}],
    ],
]
```

### StarRocks version (Required)
- 3.1.8
- 3.2.3

**Comment by haiboself** [comment]
Is config “enable_recursive_listing” can solve this probolem?

**Comment by letian-jiang** [comment]
> Is config item “enable_recursive_listing” can solve the probolem? refrence: https://docs.starrocks.io/zh/docs/data_source/catalog/hive_catalog/#generalparams

Probably not. You may try it.

**Comment by letian-jiang** [comment]
<img width="813" alt="image" src="https://github.com/StarRocks/starrocks/assets/16740944/45a90c2b-c1aa-4b61-bf8e-12657602dec5">
The implementation should skip the file with a leading `_`.

**Comment by haiboself** [comment]
> > Is config item “enable_recursive_listing” can solve the probolem? refrence: https://docs.starrocks.io/zh/docs/data_source/catalog/hive_catalog/#generalparams
> 
> Probably not. You may try it.

I fount set "enable_recursive_listing = false" can solve the problem。 

Config item "enable_recursive_listing" 's default value is true in code in 3.1.8/main branch
![image](https://github.com/StarRocks/starrocks/assets/22912087/1f455f95-57d8-407c-95f3-d2820503e835)

So will call method listFilesRecursive and then calll method isValidDataFile, that cant skip the file with a leading `_`.
![image](https://github.com/StarRocks/starrocks/assets/22912087/2183da04-7198-444f-9a95-6cf95001a7f5)

**Comment by haiboself** [comment]
The 'arthas stack' command can prove it.  "isValidDirectory" methos called when running 'refresh external table' command with enable_recursive_listing's default value:
```
[arthas@530181]$ stack com.starrocks.connector.hive.HiveRemoteFileIO isValidDirectory  "params[0].path.toString().contains('test')"
Press Q or Ctrl+C to abort.
Affect(class count: 1 , method count: 1) cost in 195 ms, listenerId: 39
ts=2024-03-06 14:40:36;thread_name=pull-hive-remote-files-23;id=164;is_daemon=false;priority=5;TCCL=sun.misc.Launcher$AppClassLoader@78308db1
    @com.starrocks.connector.hive.HiveRemoteFileIO.isValidDirectory()
        at com.starrocks.connector.hive.HiveRemoteFileIO.access$000(HiveRemoteFileIO.java:48)
        at com.starrocks.connector.hive.HiveRemoteFileIO$1.handleFileStat(HiveRemoteFileIO.java:138)
        at com.starrocks.connector.hive.HiveRemoteFileIO$1.hasNext(HiveRemoteFileIO.java:122)
        at com.starrocks.connector.hive.HiveRemoteFileIO.getRemoteFiles(HiveRemoteFileIO.java:86)
        at com.starrocks.connector.CachingRemoteFileIO.loadRemoteFiles(CachingRemoteFileIO.java:87)
        at com.starrocks.connector.CachingRemoteFileIO.updateRemoteFiles(CachingRemoteFileIO.java:105)
        at com.starrocks.connector.hive.CacheUpdateProcessor.lambda$null$13(CacheUpdateProcessor.java:284)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by letian-jiang** [comment]
@haiboself Awesome! Could you open an PR to fix `isValidDirectory` function?

**Comment by haiboself** [comment]
> @haiboself Awesome! Could you open an PR to fix `isValidDirectory` function?
Yes, I will
