### ISSUE TITLE
Implicit cast of string to boolean is broken

### ISSUE THREAD

**Issue by mcgray** [StarRocks/starrocks#42234]
We noticed that in case we are using string field in WHERE clause without expression it is always mistakenly cast to FALSE

### Steps to reproduce the behavior (Required)
Use String value without expression (going to be used as cast(table.field as boolean)) . 

### Expected behavior (Required)
Non-empty non-null String cast to TRUE and SQL has results.

### Real behavior (Required)
SQL has no results. String cast to false.

### StarRocks version (Required)
3.2.1

**Comment by mofeiatwork** [comment]
```sql
MySQL> select cast('123123' as boolean)
1

MySQL> select cast('100018588397' as boolean)
<null>
```
