### ISSUE TITLE
SMT  tool unsupport  mysql column's type is point

### ISSUE THREAD

**Issue by zyfbbd** [StarRocks/starrocks#42246]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by alberttwong** [comment]
I believe we deprecated SMT for Flink 3.0.  another option is to use Sling Data.
