### ISSUE TITLE
How to storage a large field exceed 64 KB in storage page 

### ISSUE THREAD

**Issue by easymanlo** [StarRocks/starrocks#423]
segment默认是256M，page页面默认是64kb，如果某个超出64kb，某个字段值超过64kb、甚至超过256M以上这个字段如何存储，例如一个超级大的bitmap位图字段

**Comment by sduzh** [comment]
Sorry for the late reply,  defining columns longer than 64KB is not supported in StarRocks now.

**Comment by easymanlo** [comment]
> Sorry for the late reply, defining columns longer than 64KB is not supported in StarRocks now.

What I mean is a critical value. For example, when many rows are stored in the page, they will not be exactly equal to 64kb. I think the code first judges is_full_page, and then writes data. Whether there is a judgment page is not full, and then writes to the page. More than 64KB.

**Comment by sduzh** [comment]
> > Sorry for the late reply, defining columns longer than 64KB is not supported in StarRocks now.
> 
> What I mean is a critical value. For example, when many rows are stored in the page, they will not be exactly equal to 64kb. I think the code first judges is_full_page, and then writes data. Whether there is a judgment page is not full, and then writes to the page. More than 64KB.

It's possible that an uncompressed data page is larger than 64KB, according to the following code:
https://github.com/StarRocks/starrocks/blob/d70078a484d11f68ede965812531f05905ac78fa/be/src/storage/rowset/segment_v2/binary_plain_page.h#L83

Notice that the data to be written does not participate in the calculation of whether the page is full or not。

**Comment by easymanlo** [comment]
> > > Sorry for the late reply, defining columns longer than 64KB is not supported in StarRocks now.
> > 
> > 
> > What I mean is a critical value. For example, when many rows are stored in the page, they will not be exactly equal to 64kb. I think the code first judges is_full_page, and then writes data. Whether there is a judgment page is not full, and then writes to the page. More than 64KB.
> 
> It's possible that an uncompressed data page is larger than 64KB, according to the following code:
> 
> https://github.com/StarRocks/starrocks/blob/d70078a484d11f68ede965812531f05905ac78fa/be/src/storage/rowset/segment_v2/binary_plain_page.h#L83
> 
> Notice that the data to be written does not participate in the calculation of whether the page is full or not。

I don't quite understand. Isn't the datapage supposed to store data? Whether a datapage is full or not is not judged by the uppercase of the written data. I look at the is_page_full() method and compare it with a 1M or 64KB threshold.
https://github.com/StarRocks/starrocks/blob/d70078a484d11f68ede965812531f05905ac78fa/be/src/storage/rowset/segment_v2/binary_plain_page.h#L67
