### ISSUE TITLE
starlet has security hole

### ISSUE THREAD

**Issue by motto1314** [StarRocks/starrocks#42327]
### Steps to reproduce the behavior (Required)
starlet has security hole:
libxml2-2.10.3(Fixed in 2.11.7)      https://gitlab.gnome.org/GNOME/libxml2/-/issues/604
c-ares-1.6.0(Fixed in 1.19.1)    https://github.com/c-ares/c-ares/security/advisories/GHSA-9g78-jv2r-p7vc

### Expected behavior (Required)
detect

### Real behavior (Required)
detect

### StarRocks version (Required)
 - 3.1.8

**Comment by kevincai** [comment]
fixed. will be upgraded along with next staros release.

**Comment by kevincai** [comment]
main branch fix: https://github.com/StarRocks/starrocks/pull/43180

branch-3.2 fix: https://github.com/StarRocks/starrocks/pull/43188

**Comment by kevincai** [comment]
branch-3.1 fix: https://github.com/StarRocks/starrocks/pull/43267

**Comment by kevincai** [comment]
done
