### ISSUE TITLE
Refactor Env for better readability

### ISSUE THREAD

**Issue by sduzh** [StarRocks/starrocks#4240]
Change method signatures:

Env:
| Before | After |
|------- |  ------|
| Status is_directory(const std::string&, bool*) | StatusOr\<bool\> is_directory(const std::string&) |
| Status get_file_size(const std::string&, uint64_t*)  | StatusOr\<int64_t\> get_file_size(const std::string&) |
| Status get_file_modified_time(const std::string&, uint64_t*) | StatusOr\<uint64_t\> get_file_modified_time(const std::string&) |
| Status path_exists(const std::string&) | StatusOr<bool>  path_exists(const std::string&) |

RandomAccessFile:
| Before | After |
|--------|------|
| Status size(uint64_t*) const | StatusOr\<int64_t\> get_size() |

RandomRWFile:
| Before | After |
|--------|------|
| Status size(uint64_t*) const | StatusOr\<int64_t\> get_size() |

**Comment by xlwh** [comment]
Let me have a try, thanks!
