### ISSUE TITLE
hive查询分区数据过滤失败，已经稳定复现

### ISSUE THREAD

**Issue by zck573693104** [StarRocks/starrocks#42425]
SR:3.2.3 ,部署3节点1fe3cn(其中一台fe cn混合部署 jdk-17)
hive:华为MRS-3.1.0 
数据存储在OBS上
执行sql如下:
`SELECT
  vin,
  dt AS date_id,
  COUNT(groupid) AS air_condition_activate_cnt,
  ROUND(MIN(contin_minutes) / 60, 4) AS min_contin_hours,
  ROUND(MAX(contin_minutes) / 60, 4) AS max_contin_hours,
  ROUND(AVG(contin_minutes) / 60, 2) AS avg_contin_hours,
  ROUND(SUM(contin_minutes) / 60, 4) AS daily_sum_contin_hours,
  ROUND(MIN(min_HVAC_RefrigerantPr), 2) AS daily_min_HVAC_RefrigerantPr,
  ROUND(MAX(max_HVAC_RefrigerantPr), 2) AS daily_max_HVAC_RefrigerantPr,
  ROUND(AVG(avg_HVAC_RefrigerantPr), 2) AS daily_avg_HVAC_RefrigerantPr,
  ROUND((
    SUM(low_condition_temp_contin_minutes) / SUM(contin_minutes)
  ), 4) AS low_temp_rate,
  ROUND((
    SUM(high_wind_speed_contin_minutes) / SUM(contin_minutes)
  ), 4) AS high_wind_speed_rate,
  ROUND((
    SUM(outside_circulation_contin_munutes) / SUM(contin_minutes)
  ), 4) AS outside_circulation_rate,
  ROUND(AVG(avg_exter_temp), 2) AS avg_exter_temps,
  ROUND(MAX(max_exter_temp), 2) AS max_exter_temps
FROM (
  SELECT
    vin,
    dt,
    groupid,
    MIN(message_time) AS start_time,
    MAX(message_time) AS end_time,
    COUNT(message_time) AS contin_minutes,
    ROUND(MIN(HVAC_RefrigerantPr), 2) AS min_HVAC_RefrigerantPr,
    ROUND(MAX(HVAC_RefrigerantPr), 2) AS max_HVAC_RefrigerantPr,
    ROUND(AVG(HVAC_RefrigerantPr), 2) AS avg_HVAC_RefrigerantPr,
    ROUND(SUM(high_wind_label), 2) AS high_wind_speed_contin_minutes,
    ROUND(SUM(low_condition_temp), 2) AS low_condition_temp_contin_minutes,
    ROUND(SUM(whether_outside_circulation), 2) AS outside_circulation_contin_munutes,
    ROUND(AVG(exter_temp), 2) AS avg_exter_temp,
    MAX(exter_temp) AS max_exter_temp
  FROM (
    SELECT
      vin,
      dt,
      message_time,
      HVAC_RefrigerantPr,
      low_condition_temp,
      high_wind_label,
      whether_outside_circulation,
      exter_temp,
      SUM(dlt_flag) OVER (PARTITION BY vin ORDER BY message_time rows BETWEEN UNBOUNDED preceding AND CURRENT ROW) AS groupid
    FROM (
      SELECT
        vin,
        dt,
        message_time,
        CAST(HVAC_RefrigerantPr AS DOUBLE) AS HVAC_RefrigerantPr,
        CASE WHEN CAST(HVAC_DriverTempSelect AS DOUBLE) < 20 THEN 1 ELSE 0 END AS low_condition_temp,
        CASE WHEN CAST(HVAC_WindExitSpd AS INT) > 4 THEN 1 ELSE 0 END AS high_wind_label,
        CASE WHEN CAST(HVAC_AirCirculationSt AS INT) = 2 THEN 1 ELSE 0 END AS whether_outside_circulation,
        CASE
          WHEN CAST(VCU_aiTAmbBD AS DOUBLE) = -50
          THEN NULL
          WHEN CAST(VCU_aiTAmbBD AS DOUBLE) = 20
          THEN NULL
          WHEN CAST(VCU_aiTAmbBD AS DOUBLE) = 85
          THEN NULL
          ELSE CAST(VCU_aiTAmbBD AS DOUBLE)
        END AS exter_temp,
        CASE
          WHEN (
            UNIX_TIMESTAMP(message_time) - UNIX_TIMESTAMP(
              LAG(message_time, 1, current_timestamp) OVER (PARTITION BY vin ORDER BY message_time)
            )
          ) <= 121
          THEN 0
          ELSE 1
        END AS dlt_flag
      FROM hive.ods_enterprise.g05_new_enterprise_tel_ul_tx AS g05_new_enterprise_tel_ul_tx
      WHERE
        CAST(dt AS DATE) >= DATE_ADD(CAST('20230-05-01' AS DATE), INTERVAL -2 DAY)
        AND CAST(dt AS DATE) <= DATE_ADD(CAST('20230-05-01' AS DATE), INTERVAL -1 DAY)
        AND vin = '1'
        AND CAST(BCM_KeySt AS INT) = 2
        AND CAST(VCU_BMS_BatModeReq AS INT) = 2
        AND CAST(VCU_stSupBD AS INT) IN (89, 90)
        AND CAST(BMS_HVBattSt AS INT) = 4
        AND CAST(HVAC_ACSt AS INT) = 1
        AND CAST(HVAC_AirCompressorReq AS INT) = 1
    ) AS t1
  ) AS t2
  GROUP BY
    vin,
    dt,
    groupid
  HAVING
    COUNT(1) >= 5
    AND MAX(CAST(dt AS DATE)) = DATE_ADD(CAST('20230-05-01' AS DATE), INTERVAL -1 DAY)
    AND MAX(message_time) < DATE_ADD(CAST(DATE_ADD(CAST('20230-05-01' AS DATE), INTERVAL 0 DAY) AS DATETIME), INTERVAL -61 SECOND)
) AS t3
GROUP BY
  vin,
  dt
ORDER BY
  date_id;`

其中fe,cn通过进程ID得知依然存活.
explain 结果如下:此分区数据在hive实际不存在的
![7fe902a191b71d042c5fb98087017bb](https://github.com/StarRocks/starrocks/assets/17779352/ab6790f2-2336-4318-9237-e8b9823a6b0f)
正常存在于hive分区的explain图
![bb9be78f1f529fd2549caf64f31d18d](https://github.com/StarRocks/starrocks/assets/17779352/9ff4f2d0-209e-4304-b38c-8065a2073e97)

**Comment by stephen-shelby** [comment]
20300 is an invalid date format.
