### ISSUE TITLE
Be warning log is being flashed by error: illegal state: another compaction is running

### ISSUE THREAD

**Issue by gujincheng** [StarRocks/starrocks#42667]
### Steps to reproduce the behavior (Required)
After upgrading Starrocks from 3.2.2 to 3.2.4, the logs were flushed with error: illegal state: another compaction is running。

There are 19 primary key tables in the current cluster, of which 9 tables are streamed once every 1 second. The other 10 tables run every minute, and the disk IO in version 3.2.2 is relatively high. After upgrading to 3.2.4, there is no significant decrease in disk IO, but there are a large number of error logs in be

### Expected behavior (Required)
Be has no error logs, disk IO can be reduced
### Real behavior (Required)
Be warning log is being flashed by error: illegal state: another compaction is running
![image](https://github.com/StarRocks/starrocks/assets/26380832/cde03f93-378e-48f1-876b-a310d9dbf66d)

### StarRocks version (Required)
3.2.4-613f0b5

**Comment by luohaha** [comment]
> the disk IO in version 3.2.2 is relatively high

Could you use `iotop` to find out which thread cost more of IO resource?
