### ISSUE TITLE
Support IF EXISTS in the FUNCTION statement

### ISSUE THREAD

**Issue by hanyunYep** [StarRocks/starrocks#42675]
## Feature request

need support EXISTS in the statement:

- CREATE FUNCTION IF NOT EXISTS
- DROP FUNCTION IF EXISTS

**Comment by danielhumanmod** [comment]
Hi @hanyunYep , I am new to StarRocks community, can I take a look and start contribute from this issue?

**Comment by hanyunYep** [comment]
> Hi @hanyunYep , I am new to StarRocks community, can I take a look and start contribute from this issue?

Thanks and Looking forward to seeing the feature launched soon

**Comment by danielhumanmod** [comment]
Hi @hanyunYep , I've reviewed the code and have an initial idea. But before diving into the implementation, I wanted to sync up with you to ensure I’m on the right track:

Take CREATE FUNCTION IF NOT EXISTS as example:

1. SQL Parser Modification:
Modify the ANTLR grammar in StarRocksParser.g4 to include IF EXISTS for CREATE FUNCTION. This will involve updating the createFunctionStatement rule to optionally accept IF NOT EXISTS option.
2. AST Builder Updates:
In AstBuilder.java, I’ll extend the `visitCreateFunctionStatement` method to handle the new IF NOT EXISTS logic and add corresponding params in `CreateFunctionStmt`
3. Query Executor Adjustments:
In DDLStmtExecutor.java, add the conditional creation logic in 'visitCreateFunctionStatement'. This ensures the func will only be crated if not exists.
4. Testing:
Add Unit Test to verify the SQL query work as expected

Looking forward to your feedback to ensure this approach aligns with the project’s goals and style.
