### ISSUE TITLE
Wrong cast from double to decimal when using "create table as select" statement to create hive table

### ISSUE THREAD

**Issue by mxdzs0612** [StarRocks/starrocks#42671]
### Steps to reproduce the behavior (Required)
```sql
create table xx as select * from yy
```
yy is a external catalog table, such as hive table。

When there is a column with type double/float, it will be cast to decimal automatically, which is not as expected.

### Expected behavior (Required)
![image](https://github.com/StarRocks/starrocks/assets/35512473/5019f5e7-8fc5-448a-b0a8-6ec2539bd71c)

![image](https://github.com/StarRocks/starrocks/assets/35512473/b86e38b2-a935-40fb-9238-68e641b58822)

### Real behavior (Required)
![image](https://github.com/StarRocks/starrocks/assets/35512473/17e0ca3b-fe8e-4320-85de-800f73d7bddc)

### StarRocks version (Required)
main branch

**Comment by mxdzs0612** [comment]
A brief fix in #42350, only affects external tables, though the default action itself is kindly weird.

**Comment by letian-jiang** [comment]
> A brief fix in #42350, only affects external tables, though the default action itself is kindly weird.

+1
