### ISSUE TITLE
What is the main operation of the pip_wg_scan_io thread, with occasional CPU spikes

### ISSUE THREAD

**Issue by LinYuHeng-Con** [StarRocks/starrocks#42706]
## Enhancement
![image](https://github.com/StarRocks/starrocks/assets/48077349/98933885-5ecf-4272-aa82-48b7bb9acbf4)
![image](https://github.com/StarRocks/starrocks/assets/48077349/191399f0-6fd3-47a9-937b-1607ed9aabd1)

**Comment by zhangheihei** [comment]
https://github.com/StarRocks/starrocks/pull/45569
resolve the problem
