### ISSUE TITLE
starrocks-be doesn't start

### ISSUE THREAD

**Issue by robson-koji** [StarRocks/starrocks#42704]
I would like to use this architecture in my company to the data pipeline, and everything goes smoothly up to some point. 

StarRocks > CREATE EXTERNAL CATALOG hudi_catalog_hms
    -> PROPERTIES
    -> (
    ->     "type" = "hudi",
    ->     "hive.metastore.type" = "hive",
    ->     "hive.metastore.uris" = "thrift://hive-metastore:9083",
    ->     "aws.s3.use_instance_profile" = "false",
    ->     "aws.s3.access_key" = "admin",
    ->     "aws.s3.secret_key" = "password",
    ->     "aws.s3.enable_ssl" = "false",
    ->     "aws.s3.enable_path_style_access" = "true",
    ->     "aws.s3.endpoint" = "http://minio:9000"
    -> );
Query OK, 0 rows affected (0.58 sec)

StarRocks > SET CATALOG hudi_catalog_hms;
Query OK, 0 rows affected (0.00 sec)

StarRocks > 
StarRocks > SHOW DATABASES;
+--------------------+
| Database           |
+--------------------+
| default            |
| hudi_sample        |
| information_schema |
+--------------------+
3 rows in set (0.29 sec)

StarRocks > 
StarRocks > USE hudi_catalog_hms.hudi_sample;
No connection. Trying to reconnect...
Connection id:    55
Current database: *** NONE ***

Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
StarRocks > SHOW tables;
+-----------------------+
| Tables_in_hudi_sample |
+-----------------------+
| hudi_coders_hive      |
+-----------------------+
1 row in set (0.00 sec)

StarRocks > 
StarRocks > show columns from hudi_sample.hudi_coders_hive;
+------------------------+------------------+------+------+---------+-------+
| Field                  | Type             | Null | Key  | Default | Extra |
+------------------------+------------------+------+------+---------+-------+
| _hoodie_commit_time    | varchar(1048576) | YES  | NO   | NULL    |       |
| _hoodie_commit_seqno   | varchar(1048576) | YES  | NO   | NULL    |       |
| _hoodie_record_key     | varchar(1048576) | YES  | NO   | NULL    |       |
| _hoodie_partition_path | varchar(1048576) | YES  | NO   | NULL    |       |
| _hoodie_file_name      | varchar(1048576) | YES  | NO   | NULL    |       |
| language               | varchar(1048576) | YES  | NO   | NULL    |       |
| users                  | varchar(1048576) | YES  | NO   | NULL    |       |
| id                     | varchar(1048576) | YES  | NO   | NULL    |       |
+------------------------+------------------+------+------+---------+-------+
8 rows in set (0.01 sec)

StarRocks >
StarRocks > select * from hudi_coders_hive;
ERROR 1064 (HY000): Failed to find backend to execute

/**************
THIS IS THE POINT 
***************/

starrocks-be doesn't start on docker-compose up. I don't now the reason and throws the ERROR above.

If I try to start starrocks-be:
hudi-starrocks-be-1 | ERROR 1064 (HY000) at line 1: Unexpected exception: Backend already exists with same host 172.19.0.8 and port 9050

StarRocks > SHOW BACKENDS;
+-------------------+------------+------------+
| BackendId | IP         | HeartbeatPort | BePort | HttpPort | BrpcPort | LastStartTime | LastHeartbeat | Alive | SystemDecommissioned | ClusterDecommissioned | TabletNum | DataUsedCapacity | AvailCapacity | TotalCapacity | UsedPct | MaxDiskUsedPct | ErrMsg                                                               | Version | Status                                 | DataTotalCapacity | DataUsedPct | CpuCores | NumRunningQueries | MemUsedPct | CpuUsedPct |
+-------------------+------------+------------+
| 10004     | 172.20.0.6 | 9050          | -1     | -1       | -1       | NULL          | NULL          | false | false                | false                 | 0         | 0.000 B          | 1.000 B       | 0.000 B       | 0.00 %  | 0.00 %         | java.net.ConnectException: Connection refused (Connection refused)   |         | {"lastSuccessReportTabletsTime":"N/A"} | 0.000 B           | 0.00 %      | 0        | 0                 | 0.00 %     | 0.0 %      |
| 10099     | 172.20.0.8 | 9050          | -1     | -1       | -1       | NULL          | NULL          | false | false                | false                 | 0         | 0.000 B          | 1.000 B       | 0.000 B       | 0.00 %  | 0.00 %         | java.net.NoRouteToHostException: No route to host (Host unreachable) |         | {"lastSuccessReportTabletsTime":"N/A"} | 0.000 B           | 0.00 %      | 0        | 0                 | 0.00 %     | 0.0 %      |
+-------------------+------------+------------+
2 rows in set (0.00 sec)

I am stuck here. How to boot starrocks-be? If you need more information, please just let me know.

**Comment by imay** [comment]
Can you see the log/be.out file? It may be because the machine doesn't support the necessary instructions

**Comment by robson-koji** [comment]
This is the content of /opt/starrocks/be/log/be.out

docker cp 3a66408d8710:/opt/starrocks/be/log/be.out /tmp

start time: Sat Mar 16 05:01:09 UTC 2024
start time: Sat Mar 16 05:06:55 UTC 2024
start time: Sat Mar 16 05:07:32 UTC 2024
/tmp/be.out (END)

What do you think?

**Comment by robson-koji** [comment]
CPU should suport **avx2**. 
Check /dev/cpuinfo

**avx** doesn't work. must be **avx2**.

Thanks to Alvin at StarRocks Slack channel.

**Comment by snakevictor** [comment]
Check /**proc**/cpuinfo
