### ISSUE TITLE
Rowset id cache will leak In some scenarios

### ISSUE THREAD

**Issue by trueeyu** [StarRocks/starrocks#4277]
### Steps to reproduce the behavior (Required)

Rowset id cache will leak In some scenarios

* alloc rowset id success, but create file failed
* other scenariose
* ....

There should be a way to solve this problem completely.

Can rowset id be removed from cache, when rowset meta destruct?

### Real behavior (Required)

![image](https://user-images.githubusercontent.com/11428742/159195939-f3db7e33-f443-4ca7-a07a-309b28fd243a.png)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

2.1.x

**Comment by sevev** [comment]
There are a lot of `rollback` log in be.INFO
![image](https://user-images.githubusercontent.com/19386148/159396519-b9420e1d-d471-48eb-9af7-0777c6eef70d.png)
