### ISSUE TITLE
CSV Load, Allow jagged rows

### ISSUE THREAD

**Issue by eugen-korentsov** [StarRocks/starrocks#42810]
Hi,
currently, if you try to import CSV with empty values in some columns, you will get an error about a wrong number of columns.

In BigQuery it is solved by enabling option --allow_jagged_rows, in this case missing values are treated as nulls.

Is it possible to add such a feature to StarRocks CSV data load?

**Comment by alberttwong** [comment]
How did you load the data? One of the load tools?  Did you also try Sling Data?

**Comment by eugen-korentsov** [comment]
Tried with https://docs.starrocks.io/docs/loading/gcs/
```
LOAD label ...
(
    DATA INFILE("gs://test-bucket/test.*.csv")
    INTO TABLE test
    COLUMNS TERMINATED BY ","
    FORMAT AS "CSV"
    (
       enclose = "\""
       escape = "\\"
    )
    (rows list here)
)
```

yes, I've tried also  sling-cli, but it is much slower than load above, like 200-250 rows per second max.

**Comment by alberttwong** [comment]
Did you post the a sling github issue on the performance?

**Comment by alberttwong** [comment]
Generally speaking, you're welcome to submit a PR to create this feature.   If you don't have the ability to create this feature, the development of features is prioritized by paid CelerData enterprise/cloud customers.

**Comment by kangkaisen** [comment]
@eugen-korentsov  

```
For CSV data, take note of the following points:

Null values are denoted by using \N. For example, a data file consists of three columns, and a record from that data file holds data in the first and third columns but no data in the second column. In this situation, you need to use \N in the second column to denote a null value. This means the record must be compiled as a,\N,b instead of a,,b. a,,b denotes that the second column of the record holds an empty string.
```

https://docs.starrocks.io/docs/loading/StreamLoad/
