### ISSUE TITLE
[Docker] properly handle /root/.m2 build cache

### ISSUE THREAD

**Issue by kevincai** [StarRocks/starrocks#42829]
`/root/.m2` maven artifacts can be cached in dev-env image, and overwrite by `RUN --mount=type=cache,target=/root/.m2/` which invalidates the cache by dev-env.

Need fix this.

**Comment by dengliu** [comment]
@kevincai 
It seems that it is not fixed yet
https://github.com/StarRocks/starrocks/blame/main/docker/dockerfiles/artifacts/artifact.Dockerfile#L24

**Comment by kevincai** [comment]
it was fixed in dev env image, is that not working for you ?
