### ISSUE TITLE
query sql error: DECIMAL's precision should range from 1 to 38

### ISSUE THREAD

**Issue by wanpengfei-git** [StarRocks/starrocks#4284]
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS h8;
CREATE DATABASE h8;
USE h8;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 BOOLEAN NOT NULL ,c_0_1 DATETIME NOT NULL ,c_0_2 DOUBLE NULL ,c_0_3 VARCHAR(1) NULL ,c_0_4 BOOLEAN NOT NULL ,c_0_5 BOOLEAN NULL ,c_0_6 DECIMAL(4, 0)  NOT NULL ) UNIQUE KEY (c_0_0,c_0_1) DISTRIBUTED BY HASH (c_0_0) properties("replication_num"="3") ;
CREATE TABLE t1 (c_1_0 VARCHAR(11) NOT NULL ,c_1_1 BOOLEAN NULL ,c_1_2 BOOLEAN NOT NULL ,c_1_3 VARCHAR(11) NULL ,c_1_4 DECIMAL(14, 1)  NULL ,c_1_5 VARCHAR(11) NULL ,c_1_6 CHAR(1) NULL ,c_1_7 LARGEINT NOT NULL ,c_1_8 DECIMAL(28, 3)  NULL ,c_1_9 DECIMAL(14, 11)  NULL ,c_1_10 DOUBLE NOT NULL ,c_1_11 INT NOT NULL ,c_1_12 BOOLEAN NOT NULL ) UNIQUE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6) DISTRIBUTED BY HASH (c_1_0,c_1_1,c_1_2,c_1_3,c_1_6,c_1_4,c_1_5) properties("replication_num"="3") ;
DELETE FROM t0 WHERE c_0_0=true AND c_0_1="1969-12-17 23:26:48";
TRUNCATE TABLE t1;
 SELECT t1.c_1_0 FROM t1 WHERE true GROUP BY t1.c_1_8,  ( ROUND(-0.0)  ) >= ( SECOND("1970-01-06")  ) , t1.c_1_4 ORDER BY t1.c_1_6 DESC;

### Real behavior (Required)
ERROR 1064 (HY000): DECIMAL's precision should range from 1 to 38
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.2 ASAN
 - mysql> select current_version();
+------------------------------+
| current_version()            |
+------------------------------+
| SQLANCER_01_ASAN b61b70b |
+------------------------------+

**Comment by liuyehcf** [comment]
Solved by #4370
