### ISSUE TITLE
ERROR when using long jdbc_uri in JDBC Catalogue config

### ISSUE THREAD

**Issue by MariuszJurowicz** [StarRocks/starrocks#42857]
### Steps to reproduce the behavior (Required)
1. Create the external JDBC catalog with jdbc_uri longer than 136 characters:
```
CREATE EXTERNAL CATALOG ext
PROPERTIES (
    "type"="jdbc",
    "user"="user",
    "password"="pass",
    "jdbc_uri"="jdbc:mysql://(host=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.com,zeroDateTimeBehavior=ROUND)",
    "driver_url"="https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.30/mysql-connector-java-8.0.30.jar",
    "driver_class"="com.mysql.cj.jdbc.Driver"
);
```
2. `SELECT * from ext.db.table;`

### Expected behavior (Required)
Query executed and result returned.

### Real behavior (Required)
Query 1 ERROR at Line 647: : fail to open tmp file when downloading file from https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.30/mysql-connector-java-8.0.30.jar

### StarRocks version (Required)
3.2.4

### Additional info
It looks like the driver jar file link is created in BE node that has the name longer that allowed:
`'jdbc_mysql_(host=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.com,zeroDateTimeBehavior=ROUND)_95cde01c78e7b04e13305338d60e056a_1710923312296.jar'`

**Comment by jhcnet2** [comment]
I got a same error after i upgraded 3.2.4 starrocks
when I submit a select query, i got same error messages;

```
CREATE EXTERNAL CATALOG dbsss
PROPERTIES ("driver_class"  =  "com.mysql.cj.jdbc.Driver",
"driver_url"  =  "file:///opt/driver/mysql-connector-java-8.0.29.jar",
"type"  =  "jdbc",
"user"  =  "cc",
"password" = "cc",
"jdbc_uri"  =  "jdbc:mysql://(host=my.db.com,port=3307,useUnicode=true,characterEncoding=utf8,useCursorFetch=true,defaultFetchSize=5000)"
);
```

**Comment by dirtysalt** [comment]
@MariuszJurowicz yes, you are correct, it's because temporary file length is too long.

**Comment by dirtysalt** [comment]
When I use follwoing command

> 
drop catalog jdbc_hive2;
CREATE EXTERNAL CATALOG jdbc_hive2
COMMENT "jdbc to hive mysql (from maven repo)"
PROPERTIES
(
    "type"="jdbc",
    "user"="root",
    "password"="EMRroot1234",
    "jdbc_uri" = "jdbc:mysql://(host=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.com,port=3306,useUnicode=true,characterEncoding=utf8,useCursorFetch=true,defaultFetchSize=5000)",
    "driver_url"="http://127.0.0.1:41006/data/mysql-connector-java-8.0.28.jar",
    "driver_class"="com.mysql.cj.jdbc.Driver"
);


The temp file is like.. too long

>  /home/disk4/zhangyan/StarRocks/output/be/lib/jdbc_drivers/jdbc_mysql_(host=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.com,port=3306,useUnicode=true,characterEncoding=utf8,useCursorFetch=true,defaultFetchSize=5000)_95cde01c78e7b04e13305338d60e056a_1711561489397.jar_95cde01c78e7b04e13305338d60e056a_c5567a4b-9507-466f-aa47-c86ad038368a

**Comment by dirtysalt** [comment]
expected check sum `95cde01c78e7b04e13305338d60e056a` takes 32 bytes (used 2 times).
timestamp takes `1711561489397` takes 13 bytes
last uuid takes `c5567a4b-9507-466f-aa47-c86ad038368a` 36 bytes


That's to say, set aside the jdbc uri part, the extra part alredy takes

> 32 + 32 + 13 + 36 = 113 bytes

And linux max size of file name is 255,  so only have 142 byets to specify jdbc uri.
