### ISSUE TITLE
com.starrocks.common.UserException: Internal error: vector::_M_range_insert

### ISSUE THREAD

**Issue by YanivKaplan** [StarRocks/starrocks#42873]
### Steps to reproduce the behavior (Required)
1. 
```
CREATE MATERIALIZED VIEW `account_balance_user_categories_mv_1` (`chain_id`, `cat_uuid`, `account`, `account_last_activity`, `account_total_amount_usd`, `account_type`, `block_timestamp`, `ts_day`)
DISTRIBUTED BY HASH(`account`) BUCKETS 8 
REFRESH MANUAL
PROPERTIES (
"replicated_storage" = "true",
"replication_num" = "1",
"session.query_timeout" = "3600",
"storage_medium" = "HDD"
)
AS SELECT `b`.`chain_id`, `a`.`cat_uuid`, `a`.`account`, any_value(`b`.`account_last_activity`) AS `any_value(b.account_last_activity)`, any_value(`b`.`account_total_amount_usd`) AS `any_value(b.account_total_amount_usd)`, any_value(`b`.`account_type`) AS `any_value(b.account_type)`, any_value(`b`.`block_timestamp`) AS `any_value(b.block_timestamp)`, any_value(`b`.`ts_day`) AS `any_value(b.ts_day)`
FROM `prod`.`account_categories_with_type_mv` AS `a` INNER JOIN `prod`.`account_balance_no_chain_par_acc` AS `b` ON (`a`.`account` = `b`.`account`) AND (`a`.`type` = 'user')
GROUP BY `b`.`chain_id`, `a`.`cat_uuid`, `a`.`account`;
```
2. `ALTER MATERIALIZED VIEW account_balance_user_categories_mv_1 INACTIVE;`
3. `ALTER MATERIALIZED VIEW account_balance_user_categories_mv_1 ACTIVE;`

### Expected behavior (Required)
The command joins a ~3 Billion record table (account_balance_no_chain_par_acc) to a ~85 Million one (account_categories_with_type_mv). the result table result with a table the has ~273 Million records.
The cluster has 5 BE nodes with 64GB RAM, 8 CPU in each node.
The run, when succeeds, should have a SUCCESS status after a few minutes.

### Real behavior (Required)
When checking for the status of the run after a while:
```
SELECT is_active, last_refresh_state, last_refresh_start_time, last_refresh_finished_time, last_refresh_error_message
                                 FROM information_schema.materialized_views
                                 WHERE table_name = 'account_balance_user_categories_mv_1'
```
The run fails and the `last_refresh_error_message` column shows the following error, with no other apparent explanation in the logs:
`com.starrocks.common.UserException: Internal error: vector::_M_range_insert
`

### StarRocks version (Required)
3.1.3

**Comment by mofeiatwork** [comment]
`Internal error: vector::_M_range_insert` is thrown from the backend. please attach the exception log in `be.out` or `be.INFO` to help diagnose this issue.

**Comment by YanivKaplan** [comment]
`W0312 15:46:39.009855 53036 pipeline_driver_executor.cpp:161] [Driver] Process error, query_id=87ecbe1b-e087-11ee-890f-0242ae8db6c2, instance_id=87ecbe1b-e087-11ee-890f-0242ae8db6c6, status=Internal error: Internal error: vector::_M_range_insert
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69b96  std::vector<>::_M_range_insert<>()
W0312 15:47:59.450398 53038 pipeline_driver_executor.cpp:161] [Driver] Process error, query_id=8f4b2fce-e087-11ee-890f-0242ae8db6c2, instance_id=8f4b2fce-e087-11ee-890f-0242ae8db6c6, status=Internal error: Internal error: vector::_M_range_insert
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69a58  std::vector<>::_M_range_insert<>()
    @          0x3a69b96  std::vector<>::_M_range_insert<>()
W0318 12:59:00.081459 53034 pipeline_driver_executor.cpp:161] [Driver] Process error, query_id=1bb4736a-e527-11ee-890f-0242ae8db6c2, instance_id=1bb4736a-e527-11ee-890f-0242ae8db6c6, status=Internal error: Internal error: vector::_M_range_insert`


Nothing helpful there either

**Comment by miguelgilmartinez** [comment]
In my case it happens like that:
```
INSERT INTO target (SELECT column1, column2   FROM  tbl1
  LEFT JOIN   tbl2  ON tbl1.id = tbl2.id  AND tbl1.id2 = tbl2.id2);
```

column1 is an ARRAY<varchar(256)>.


> W0430 19:05:05.136888 321892 mem_hook.cpp:249] large memory alloc, query_id:68222561-0724-11ef-9f7b-1addc8db8679 instance: 68222561-0724-11ef-9f7b-1addc8db867a acquire:16897667472 bytes, stack:
>     @          0x6881122  malloc
>     @          0xa38a40c  operator new()
>     @          0x3d3c156  std::vector<>::_M_range_insert<>()
>     @          0x3d3f736  starrocks::BinaryColumnBase<>::append()
>     @          0x630da36  starrocks::JoinHashTable::append_chunk()
>     @          0x63038c1  starrocks::HashJoinBuilder::append_chunk()
>     @          0x62fc224  starrocks::HashJoiner::append_chunk_to_ht()
>     @          0x64145ac  starrocks::pipeline::HashJoinBuildOperator::push_chunk()
>     @          0x6419b48  starrocks::pipeline::SpillableHashJoinBuildOperator::push_chunk()
>     @          0x5dc92df  starrocks::pipeline::PipelineDriver::process()
>     @          0x668278e  starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
>     @          0x69fafcb  starrocks::ThreadPool::dispatch_thread()
>     @          0x69f530a  starrocks::Thread::supervise_thread()
>     @     0x7fca7820cac3  (unknown)
>     @     0x7fca7829e850  (unknown)
>     @              (nil)  (unknown)
> W0430 19:05:15.892854 321885 stack_util.cpp:350] 2024-04-30 19:05:15.892570, query_id=68222561-0724-11ef-9f7b-1addc8db8679, fragment_instance_id=68222561-0724-11ef-9f7b-1addc8db867a throws exception: std::length_error, trace:
>      @          0xa3eed11  std::__throw_length_error()
>     @          0x3d3c296  std::vector<>::_M_range_insert<>()
>     @          0x3d3f736  starrocks::BinaryColumnBase<>::append()
>     @          0x3ecfd86  starrocks::NullableColumn::append()
>     @          0x3f9ecca  starrocks::Chunk::append()
>     @          0x3ec9994  starrocks::ChunkSliceTemplate<>::cutoff()
>     @          0x641ab09  _ZNSt17_Function_handlerIFN9starrocks8StatusOrISt10shared_ptrINS0_5ChunkEEEEvEZNS0_8pipeline30SpillableHashJoinBuildOperator26_convert_hash_map_to_chunkEvEUlvE_E9_M_invokeERKSt9_Any_data
>     @          0x62a4d13  starrocks::pipeline::SpillProcessOperator::pull_chunk()
>     @          0x5dc89d5  starrocks::pipeline::PipelineDriver::process()
>     @          0x668278e  starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
>     @          0x69fafcb  starrocks::ThreadPool::dispatch_thread()
>     @          0x69f530a  starrocks::Thread::supervise_thread()
>     @     0x7fca7820cac3  (unknown)
>     @     0x7fca7829e850  (unknown)
>     @              (nil)  (unknown)
>  
> W0430 19:05:15.893952 321885 pipeline_driver_executor.cpp:169] [Driver] Process error, query_id=68222561-0724-11ef-9f7b-1addc8db8679, instance_id=68222561-0724-11ef-9f7b-1addc8db867a, status=Internal error: Internal error: vector::_M_range_insert
> W0430 19:05:15.894948 321871 tablet_sink_sender.cpp:245] close channel failed. channel_name=NodeChannel[10005], load_info=load_id=68222561-0724-11ef-9f7b-1addc8db8679, txn_id: 5025, parallel=1, compress_type=2, error_msg=Cancelled by pipeline engine
> W0430 19:05:15.895422 321871 tablet_sink_sender.cpp:245] close channel failed. channel_name=NodeChannel[10005], load_info=load_id=68222561-0724-11ef-9f7b-1addc8db8679, txn_id: 5025, parallel=1, compress_type=2, error_msg=Cancelled by pipeline engine

**Comment by aleixtusetbadia** [comment]
Facing same error

**Comment by stdpain** [comment]
@miguelgilmartinez https://github.com/StarRocks/starrocks/pull/32754

**Comment by miguelgilmartinez** [comment]
> @miguelgilmartinez https://github.com/StarRocks/starrocks/pull/32754

None of our columns is so big.

**Comment by stdpain** [comment]
> > @miguelgilmartinez #32754
> 
> None of our columns is so big.

hash join will splice a binary column into a large binary column. if the input rows are large and the individual elements are large it may be more than 4G.
