### ISSUE TITLE
be node crash after execute a sql 

### ISSUE THREAD

**Issue by nough1** [StarRocks/starrocks#42884]
### Steps to reproduce the behavior (Required)
1. execute the sql 
SELECT
base_query.*
FROM
(
SELECT
count(
distinct xxx621_column_8cRm0F7LlVYKmR0BOw7E
) as i_v_xxx621_column_8cRm0F7LlVYKmR0BOw7E_1705645931677,
IF(
count(
distinct xxx621_column_8cRm0F7LlVYKmR0BOw7E
) > 400,
count(
distinct xxx621_column_8cRm0F7LlVYKmR0BOw7E
) -400,
0
) as i_v_column88975_1705646119869,
sum (
case
when xxx621_column_m3IUm0DqsDvPW3CvBZWb = 3 then 1
else 0
end
) as i_v_column88975_1705647714467,
IF(
sum (
case
when xxx621_column_m3IUm0DqsDvPW3CvBZWb = 3 then 1
else 0
end
) < 40,
40 - sum (
case
when xxx621_column_m3IUm0DqsDvPW3CvBZWb = 3 then 1
else 0
end
),
0
) as i_v_column88975_1705653314373,
sum (
case
when xxx621_column_m3IUm0DqsDvPW3CvBZWb = 2 then 1
else 0
end
) as i_v_column88975_1705647914706,
sum (
case
when xxx621_column_m3IUm0DqsDvPW3CvBZWb = 1 then 1
else 0
end
) as i_v_column88975_1705647925854,
sum (
case
when xxx621_column_m3IUm0DqsDvPW3CvBZWb = 4 then 1
else 0
end
) as i_v_column88975_1705651769346,
xxx62789_e7345f93cd4081345351b83af60344e1.xxx621_column_9yuJpqD4RY71YXztBUCC as xxx621_column_9yuJpqD4RY71YXztBUCC,
grouping(xxx621_column_9yuJpqD4RY71YXztBUCC) as xxx621_column_9yuJpqD4RY71YXztBUCC_total_flag
from
xxx62789_e7345f93cd4081345351b83af60344e1
group by
grouping sets (
(),
(xxx621_column_9yuJpqD4RY71YXztBUCC)
)
) AS base_query
order by
xxx621_column_9yuJpqD4RY71YXztBUCC_total_flag desc,
base_query.xxx621_column_9yuJpqD4RY71YXztBUCC asc
LIMIT
6000 OFFSET 0

xxx62789_e7345f93cd4081345351b83af60344e1  this is a cte ( with multi table join ) 

### Expected behavior (Required)

normal return 

### Real behavior (Required)

be node down 

be.out trace 

*** Aborted at 1705967445 (unix time) try "date -d @1705967445" if you are using GNU date ***
PC: @          0x2d57320 starrocks::vectorized::FixedLengthColumnBase<>::append_selective()
*** SIGSEGV (@0x1000) received by PID 14905 (TID 0x7ffb0cafb700) from PID 4096; stack trace: ***
    @          0x5b97b22 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7ffbd8c54630 (unknown)
    @          0x2d57320 starrocks::vectorized::FixedLengthColumnBase<>::append_selective()
    @          0x50cb458 starrocks::vectorized::NullableColumn::append_selective()
    @          0x50ae6ca starrocks::vectorized::Chunk::append_selective()
    @          0x324dfbe starrocks::pipeline::LocalExchangeSourceOperator::_pull_shuffle_chunk()
    @          0x324e897 starrocks::pipeline::LocalExchangeSourceOperator::pull_chunk()
    @          0x2d906c0 starrocks::pipeline::PipelineDriver::process()
    @          0x51add6a starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x4b968f2 starrocks::ThreadPool::dispatch_thread()
    @          0x4b9138a starrocks::Thread::supervise_thread()
    @     0x7ffbd8c4cea5 start_thread
    @     0x7ffbd8267b0d __clone
    @                0x0 (unknown)

### StarRocks version (Required)

2.5.10 9feb716

**Comment by nough1** [comment]
cpu utilze and memory usage merics is normal

**Comment by alberttwong** [comment]
have you tried this in 3.2?

**Comment by nough1** [comment]
no , in the company , the sre has no upgrade plan ...

**Comment by nough1** [comment]
> have you tried this in 3.2?
no , in the company , the sre has no upgrade plan ... , it seems the cause it's the io util 100%
