### ISSUE TITLE
Support rebuild materialized view

### ISSUE THREAD

**Issue by murphyatwork** [StarRocks/starrocks#42882]
## Feature Request

**Is your feature request related to a problem? Please describe.**

The MV activate mechanism can only support some simple schema change operations, like re-create the table, rename table, but not the data-type change, column name change, etc.

Since the schema change in the source of MaterializedView is pretty common, it's necessary to support such kind of changes.

E.g.

```sql
CREATE TABLE t1 (c1 int, c2 int);
CREATE MATERIALIZED VIEW mv
REFRESH MANUAL 
AS 
select c1, c2 from t1;

ALTER TABLE t1 MODIFY COLUMN c2 bigint;

```

**Describe the solution you'd like**

Two solutions:
- Simple schema change: handle the data-type change case, when data type of column in the base table changes, change the corresponding MV column as well.
- Rebuild the MV: when inactivate MV, rebuild the MV if necessary

**Describe alternatives you've considered**

**Additional context**

**Comment by stalary** [comment]
The first solution seems not difficult, it can implement only in fe？I'm not familiar with be.

**Comment by Stereo1989** [comment]
Hello, can I try to solve this problem?
