### ISSUE TITLE
be node crash

### ISSUE THREAD

**Issue by nough1** [StarRocks/starrocks#42885]
### Steps to reproduce the behavior (Required)

1. online environment and execute some sql 

### Expected behavior (Required)

not crash

### Real behavior (Required)

be crash

be.out crash trace :

*** Aborted at 1710922285 (unix time) try "date -d @1710922285" if you are using GNU date ***
PC: @          0x400541e starrocks::vectorized::VectorizedInConstPredicate<>::eval_on_chunk<>()
*** SIGSEGV (@0x7f1ff34770c4) received by PID 31689 (TID 0x7f2314655700) from PID 18446744073496129732; stack trace: ***
    @          0x5aed0a2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f2643255630 (unknown)
    @          0x400541e starrocks::vectorized::VectorizedInConstPredicate<>::eval_on_chunk<>()
    @          0x40351d9 starrocks::vectorized::VectorizedInConstPredicate<>::evaluate_with_filter()
    @          0x4035705 starrocks::vectorized::VectorizedInConstPredicate<>::evaluate_checked()
    @          0x38ea553 starrocks::ExprContext::evaluate()
    @          0x38ea89f starrocks::ExprContext::evaluate()
    @          0x488acb9 starrocks::vectorized::ColumnExprPredicate::evaluate()
    @          0x42c5b7a starrocks::vectorized::SegmentIterator::_filter_by_expr_predicates()
    @          0x42c7460 starrocks::vectorized::SegmentIterator::_do_get_next()
    @          0x42ca900 starrocks::vectorized::SegmentIterator::do_get_next()
    @          0x434edf2 starrocks::vectorized::ProjectionIterator::do_get_next()
    @          0x48f66e5 starrocks::SegmentIteratorWrapper::do_get_next()
    @          0x4725b23 starrocks::vectorized::TimedChunkIterator::do_get_next()
    @          0x4380226 starrocks::vectorized::TabletReader::do_get_next()
    @          0x30235eb starrocks::pipeline::OlapChunkSource::_read_chunk_from_storage()
    @          0x3023ccb starrocks::pipeline::OlapChunkSource::_read_chunk()
    @          0x301353f starrocks::pipeline::ChunkSource::buffer_next_batch_chunks_blocking()

### StarRocks version (Required)

2.5.10

**Comment by nough1** [comment]
cpu utilze and memory usage merics is normal

**Comment by alberttwong** [comment]
have you tried this in 3.2?
