### ISSUE TITLE
split function : unexpected exception in starrocks 1.18.2

### ISSUE THREAD

**Issue by mklzl** [StarRocks/starrocks#430]
### Steps to reproduce the behavior (Required)

    select split("a,b,c",",");
### Expected behavior (Required)

    +---------------------+
    | split('a,b,c', ',') |
    +---------------------+
    | ["a","b","c"]       |
    +---------------------+

### Real behavior (Required)

    ERROR 1064 (HY000): Unexpected exception: org.apache.doris.catalog.ArrayType cannot be cast to org.apache.doris.catalog.ScalarType

### StarRocks version (Required)
A version that works properly

    1.18.2 caa8b52 
    +---------------------+
    | split('a,b,c', ',') |
    +---------------------+
    | ["a","b","c"]       |
    +---------------------+
A version that does not work properly ， download from : https://www.dorisdb.com/zh-CN/download/community

    1.18.2 7b65727  is Unexpected exception
    ERROR 1064 (HY000): Unexpected exception: org.apache.doris.catalog.ArrayType cannot be cast to org.apache.doris.catalog.ScalarType
please check  and repair it

**Comment by HangyuanLiu** [comment]
The current Master branch code cannot reproduce the error you submitted. Can you reproduce the error on the Master branch?

**Comment by mklzl** [comment]
I did not have this problem when debugging the code from the master branch fork, but using the official website installation package, this problem can occur. link : https://www.dorisdb.com/zh-CN/download/community  md5 : 468b4f1cf725e02fb23ba0393c9f2f81

**Comment by HangyuanLiu** [comment]
split should open new planner. set enable_cbo=true

**Comment by mklzl** [comment]
ok , open set enable_CBO =true and the operation succeeds . tks

**Comment by mklzl** [comment]
But I don't think the proper use of this query should be determined by whether CBO is enabled or not

**Comment by HangyuanLiu** [comment]
Yes, what you said is correct. However, the old version of the optimizer will be gradually removed, and the old version will not be used by default in 1.19. So the old version is no longer maintained.

**Comment by mklzl** [comment]
Ok, I see
