### ISSUE TITLE
Support expanding array with json root

### ISSUE THREAD

**Issue by rickif** [StarRocks/starrocks#4307]
## Enhancement
Now, the SR >= version 2.1 cannot support expanding json sub-array with json root.
```
{
	"data": [{
		"key": 1
	}, {
		"key": 2
	}]
}
```
We cannot get `key: 1`, `key: 2` by setting json root `$.data` and `strip_outer_array`.
The reason is that the order of the json parsing process is:
1. expanding the array
1. extract json with json root
1. scan json

To parse the json above with json root, we could change the order of process as:
1. extract json with json root
1. expanding the array
1. scan json

**Comment by mofeiatwork** [comment]
Why does user store json in this layout? It's not intuitive.
