### ISSUE TITLE
insert into table_name values  不支持 ？ 进行占位，报错  prepare statement only support QueryStatement

### ISSUE THREAD

**Issue by gospider007** [StarRocks/starrocks#43096]
导入的时候用？ 进行占位报错， 第一次尝试starrocks ，用代码批量插入数据 希望可以进行占位，很多库都支持和鼓励用占位符，这样可以防止sql 注入。  starrocks 的insert into  的sql 占位符是什么呢

**Comment by mofeiatwork** [comment]
It's not supported right now.

For batch data loading, the recommended way is to use files-function/stream-load/broker-load/routine-load.
