### ISSUE TITLE
[Doc] stream load 没有提示用户使用时需要打通网络的端口有哪些，有一些客户因为不了解这点不能准时上线

### ISSUE THREAD

**Issue by dq1201** [StarRocks/starrocks#43107]
## Enhancement
flink connector 和 stream load 的文档中应该提示客户使用过程中除了打通客户端和sr集群的fe_http_port 端口网络，还需要打通和每个be的be_http_port
![image](https://github.com/StarRocks/starrocks/assets/90668098/455d7ebc-543b-4afe-afd5-e8f1edbc5893)

**Comment by jaogoy** [comment]
All kind of loading methods using Stream Load need BE ports, including flink/spark sink connector. And,flink/spark source connector (read data from SR) also needs BE ports.
@evelynzhaojie Could you optimize the docs.
@banmoy You can correct me if there is some misunderstanding, or add something if there are more scenarios need BE ports.
