### ISSUE TITLE
Querying the iceberg table may cause fe oom

### ISSUE THREAD

**Issue by MicePilot** [StarRocks/starrocks#43205]
## Enhancement

When I have a very huge iceberg table, even if I only query a small part of its partitions, it may still cause fe oom. There are two ways to reproduce it. The first is to kill all be nodes during the query process, and the second is use explain verbose to view the plan of this query. The root cause of fe oom caused by these two recurrence methods is that all partitions are obtained by using listPartitionNames in IcebergScanNode.getNodeExplainString. Is there any plan to optimize it?

**Comment by alberttwong** [comment]
Can you post the "analyze" of the plan.   Also post the FE and BE.   Also what version are you using?
