### ISSUE TITLE
stream load error： Error: Value count does not match column count.

### ISSUE THREAD

**Issue by moranrr** [StarRocks/starrocks#4337]
**1. create table** 
```
create table test.page_view(
uid varchar(64),
visit_date date, 
url varchar(64),
duration int
)DUPLICATE KEY(uid)  DISTRIBUTED BY HASH(uid) BUCKETS 4;
```
**2. The test data has 5 columns, but the table has only 4 columns；as described in the documentation for cloumns：**
例2：表中有3列"c1, c2, c3" ，源文件中前3列一一对应，但是还有多余1列；那么需要指定-H "columns: c1, c2, c3, temp"，最后1列随意指定名称用于占位即可。

`a,2022-02-12,1,2,3`

**3. load**
`curl --location-trusted -u root: -T /opt/test_data.log -H "label:a123b"  -H "column_separator:,"   -H "cloumns:uid,visit_date,url,duration,tmp"   http://ip:8030/api/test/page_view/_stream_load`

**Starrocks  2.1.3 ERROR：**
`Error: Value count does not match column count. Expect 5, but got 4. Row: a,2022-02-12,1,2,3`

**Starrocks1.9.7 ERROR：**

`Reason: column count mismatch, expect=4 real=5. src line: [a,2022-02-12,1,2,3];`

**Comment by yongbingwang** [comment]
@moranrr  Load sql is incorrect, `columns` not `cloumns`.

**Comment by jaogoy** [comment]
@moranrr Please modify the load configuration and try again.
If there are no error again, that's the reason.
And we will improve the printed log for easy-to-read.
