### ISSUE TITLE
[Feature] CUSTOM authentication support

### ISSUE THREAD

**Issue by lianneli** [StarRocks/starrocks#43540]
## Feature request

**Is your feature request related to a problem? Please describe.**

in company, we have an unify ID and password within any platforms. To use StarRocks better, we hope to use the same authentication method without extra management.

**Describe the solution you'd like**

An interface which can pass username and password to our authentication server.

**Describe alternatives you've considered**

I considered to add an SQL Gateway before StarRocks to check user. However, it's more complex for the whole structure. 
﻿
**Additional context**

**Comment by Stereo1989** [comment]
Hi, What can I try to resolve this issue?

**Comment by Dshadowzh** [comment]
Could you provide more details about CUSTOMIZED authentication? The term is quite broad. StarRocks supports LDAP and Kerberos protocols for authentication. We are also considering supporting SAML2.0 in the future. Could you specify which protocol you use in-house?
