### ISSUE TITLE
percentile_approx: support values and weights

### ISSUE THREAD

**Issue by nagarajatantry** [StarRocks/starrocks#43615]
## Feature request

**Is your feature request related to a problem? Please describe.**
I have a map of values and weights. I want to use them to calculate the percentile.  Something similar to what is supported in Athena/[PrestoDB](https://prestodb.io/docs/current/functions/aggregate.html#approx_percentile)
```
approx_percentile(x, w, percentage) → [same as x][#](https://prestodb.io/docs/current/functions/aggregate.html#id10)
Returns the approximate weighed percentile for all input values of x using the per-item weight w at the percentage p. The weight must be an integer value of at least one. It is effectively a replication count for the value x in the percentile set. The value of p must be between zero and one and must be constant for all input rows.
```

**Comment by kangkaisen** [comment]
We will support it later

**Comment by zhanglistar** [comment]
Great! Clickhouse and gluten already have it.

**Comment by SaiSharathReddy** [comment]
this is very important feature accessing rollup data from data lake systems, is there any ETA on this feature request ?
