### ISSUE TITLE
be crash after a select operation 

### ISSUE THREAD

**Issue by priterzhang** [StarRocks/starrocks#43651]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `event_13` (
  `$part_event` varchar(64) NULL COMMENT "",
  `$part_date` date NULL COMMENT "",
  `#user_id` bigint(20) NULL COMMENT "",
  `#account_id` varchar(128) NULL COMMENT "",
  `#distinct_id` varchar(128) NULL COMMENT "",
  `#event_time` datetime NULL COMMENT "",
  `#server_time` datetime NULL COMMENT "",
  `#lib` varchar(512) NULL COMMENT "",
  `#lib_version` varchar(512) NULL COMMENT "",
  `DeviceSystem` varchar(512) NULL COMMENT "",
  `DeviceModel` varchar(512) NULL COMMENT "",
  `logMsg` varchar(512) NULL COMMENT "",
  `openid` varchar(512) NULL COMMENT "",
  `DeviceWxVersion` varchar(512) NULL COMMENT "",
  `OS` varchar(512) NULL COMMENT "",
  `DeviceName` varchar(512) NULL COMMENT "",
  `GameName` varchar(512) NULL COMMENT "",
  `RegionName` varchar(512) NULL COMMENT "",
  `app_envVer` varchar(512) NULL COMMENT "",
  `stack` array<varchar(1024)> NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`$part_event`, `$part_date`)
PARTITION BY date_trunc('day', $part_date)
DISTRIBUTED BY HASH(`$part_event`, `#user_id`)
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"fast_schema_evolution" = "true",
"compression" = "LZ4"
);
2. write a batch of data(the attach file event_76_other_40000.log) into the kafka and load to db through routine load job , the data has no special  properties.
3. SELECT * from event_13 
[event_76_other_40000.log](https://github.com/StarRocks/starrocks/files/14896199/event_76_other_40000.log)

### Expected behavior (Required)
show the right data

### Real behavior (Required)
the be crash  at 
![image](https://github.com/StarRocks/starrocks/assets/2581640/0e4f7b38-8523-4863-9240-a1fc0d82f406)
and at the frame 8, the size is too big （18446744073709551612）

### StarRocks version (Required)
 - 3.2.2

###some other information
if i sep this file into two file(event_76_other_20000.log and event_76_other_20000-40000.log) and insert the data individual, the  be will not crash.

**Comment by priterzhang** [comment]
and if i drop the `stack` column ,the BE will not crash at all. but there is no `stack` column data in the  data files.

**Comment by kangkaisen** [comment]
@priterzhang Hi, could you send us the log in the be.out file? thanks.

**Comment by priterzhang** [comment]
> @priterzhang Hi, could you send us the log in the be.out file? thanks.

![image](https://github.com/StarRocks/starrocks/assets/2581640/378acb74-4692-4916-bfb5-c76e8c2bdf0e)
may i add your slack or wechat to describe this issue, the situation is a little complex and i have the core file with more information

**Comment by stdpain** [comment]
@priterzhang  Is it really 3.2.2?

**Comment by stdpain** [comment]
```
commit e4596bf4e5b2d40744b203f238d5bcaf9cfd2bb1
Author: Seaven <seaven_7@qq.com>
Date:   Wed Jan 31 16:48:03 2024 +0800

    [BugFix] Fix array<string> use local dict optimization (#40369)
    
    Signed-off-by: Seaven <seaven_7@qq.com>

diff --git a/be/src/storage/rowset/array_column_iterator.cpp b/be/src/storage/rowset/array_column_iterator.cpp
index a933c1f744..cb122544d4 100644
--- a/be/src/storage/rowset/array_column_iterator.cpp
+++ b/be/src/storage/rowset/array_column_iterator.cpp
@@ -353,7 +353,7 @@ Status ArrayColumnIterator::fetch_dict_codes_by_rowid(const rowid_t* rowids, siz
 }
 
 Status ArrayColumnIterator::decode_dict_codes(const int32_t* codes, size_t size, Column* words) {
-    return _element_iterator->decode_dict_codes(codes, size, words);
+    return Status::NotSupported("ArrayColumn don't support local low-cardinality dict optimization");
 }
 
 } // namespace starrocks
```

**Comment by stdpain** [comment]
you can change it to a release version

**Comment by priterzhang** [comment]
> @priterzhang Is it really 3.2.2?


> you can change it to a release version

thank you, i will try it. i fork this version from the main branch after the 3.2.2 release.
