### ISSUE TITLE
Suggestion regarding the introduction of the bucketing concept.

### ISSUE THREAD

**Issue by zxf216** [StarRocks/starrocks#43684]
## Enhancement

It is suggested that in the official documentation, the concept of "bucketing" should no longer be emphasized (with a default to random bucketing), and only "partitioning" should be mentioned. This would align with the concept of table creation in Hive. Bucketing can be introduced as an effective method for query performance optimization, which I believe would be more user-friendly for beginners learning StarRocks.

**Comment by jaogoy** [comment]
It's a good idea. I'll think about it.
