### ISSUE TITLE
Possible Memory Leak Found

### ISSUE THREAD

**Issue by DataScientistSamChan** [StarRocks/starrocks#43729]
### Steps to reproduce the behavior (Required)
Currently it's very likely that the memory leak problem occurs because of AWS sdk. So the revelant steps to reproduce the behavior is to bring up a cluster and start streaming data into the cluster through the`Stream Load` http interface.  Depending on the size of your data, the memory leak will become apparent as soon as 1 hour or possibly longer. The memory leak could be identified by accessing the http `mem_tracker`  api, where memory consumption of the sub modules doesn't add up to the total(You could see in the snapshot below that the consumption of the sub modules doesn't add up to 56G, leaving a gap of over 36G).

<img width="1726" alt="image" src="https://github.com/StarRocks/starrocks/assets/18599494/1323be3e-19ed-48fc-b9e0-d14a136be35b">

### Expected behavior (Required)
Memory leak should not happen. Memory consumption of the sub modules should add up to the total.

### Real behavior (Required)
Memory leak will render the whole cluster unavailable from time to time.

### StarRocks version (Required)
 3.1.9-e1c6e4e

**Comment by tracymacding** [comment]
Memory profile like this:

![graphviz](https://github.com/StarRocks/starrocks/assets/4231537/ec9271d0-d253-4733-982f-e84f9ba4b68b)

**Comment by tracymacding** [comment]
The aws sdk version StarRocks cloud native is 1.10.36, and the s2n version sdk used is v1.3.27:
```
S2N_URI=${CRT_URI_PREFIX}/s2n/zip/15d534e8a9ca1eda6bacee514e37d08b4f38a526
```
![img_v3_029o_154d59c1-df2f-440f-9f74-493558be0b5g](https://github.com/StarRocks/starrocks/assets/4231537/c1c9b44c-2ac4-4a58-9677-2b4660b0b655)

**Comment by tracymacding** [comment]
The memory allocated here, but seems never freed:
```
int s2n_drbg_instantiate(struct s2n_drbg *drbg, struct s2n_blob *personalization_string, const s2n_drbg_mode mode)
{   
    POSIX_ENSURE_REF(drbg);
    
    drbg->ctx = EVP_CIPHER_CTX_new();
    S2N_ERROR_IF(!drbg->ctx, S2N_ERR_DRBG);

    s2n_evp_ctx_init(drbg->ctx);
}
```
it should be freed here:
```
int s2n_drbg_wipe(struct s2n_drbg *drbg)
{   
    POSIX_ENSURE_REF(drbg);
    if (drbg->ctx) {
        POSIX_GUARD_OSSL(EVP_CIPHER_CTX_cleanup(drbg->ctx), S2N_ERR_DRBG);
            
        EVP_CIPHER_CTX_free(drbg->ctx);
        drbg->ctx = NULL;
    }       
            
    *drbg = (struct s2n_drbg) {0};
    return 0;
}
```
But no one calls `s2n_drbg_wipe`:

```
dingkai@DingKaideMacBook-Pro-2 crypto % grep s2n_drbg_wipe *
s2n_drbg.c:int s2n_drbg_wipe(struct s2n_drbg *drbg)
s2n_drbg.h:extern int s2n_drbg_wipe(struct s2n_drbg *drbg);
```

**Comment by kevincai** [comment]
A few aws sdk s2n fixes that may be related to this leak:

https://github.com/aws/s2n-tls/pull/3771
https://github.com/aws/s2n-tls/pull/3966
https://github.com/aws/s2n-tls/pull/4037

**Comment by kevincai** [comment]
https://github.com/aws/aws-sdk-cpp/pull/2373

**Comment by kevincai** [comment]
I am opt to give a go to backport the aws sdk version upgrade to v3.2

**Comment by kevincai** [comment]
https://github.com/StarRocks/starrocks/pull/43887 the aws sdk version upgraded to 1.11.267 and is released in 3.3.0-rc01

**Comment by kevincai** [comment]
https://github.com/StarRocks/starrocks/pull/45543 for release 3.2.x

**Comment by DataScientistSamChan** [comment]
We upgraded to 3.3-rc01 and have been closely monitoring this issue and not observed the memory leak again.
