### ISSUE TITLE
SQL Error [1064] [42000]: Vectorized engine does not support the operator, cast from VARBINARY to ARRAY failed, maybe use switch function backend

### ISSUE THREAD

**Issue by miguelgilmartinez** [StarRocks/starrocks#43751]
### Steps to reproduce the behavior (Required)
1. Create a parquet file with a column like this (SUPER varchar column exported from Redshift, in my case)
physical_type: BYTE_ARRAY
logical_type: JSON
converted_type (legacy): JSON
2. INSERT INTO tablename SELECT colum1, column2.... from that parquet file. Using AWS S3 storage for incoming parquet file.

### Expected behavior (Required)
Data is imported. array<varchar> data type.

### Real behavior (Required)
SQL Error [1064] [42000]: Vectorized engine does not support the operator, cast from VARBINARY to ARRAY failed, maybe use switch function backend [id=10005] [host=10.0.139.180]

### StarRocks version (Required)
3.2.1 Ubuntu shared-nothing it works.
3.2.3 and 3.2.4 it fails.

**Comment by miguelgilmartinez** [comment]
> @miguelgilmartinez It's wired that JSON logical type of Parquet files is not supposed to be implemented, we will check it.

It worked in 3.2.1 version. It fails moving to 3.2.4

**Comment by nodecharts** [comment]
Same issue in 3.2.6
{"errorMessage":"execution failed: Not support cast VARBINARY(-1) to ARRAY<VARCHAR(256)>. backend [id=10005]  ....}

**Comment by wyb** [comment]
@miguelgilmartinez @nodecharts can you provide a parquet file with some test data?

**Comment by wyb** [comment]
@miguelgilmartinez @nodecharts what is the type of the column in the target table corresponding to the json column in parquet file?

**Comment by wyb** [comment]
@miguelgilmartinez fixed, this will be released in 3.2.10
