### ISSUE TITLE
Commond 'Drop table force' is not effective to clean data file forcely in 1.19.1

### ISSUE THREAD

**Issue by 5herhom** [StarRocks/starrocks#4376]
*  Create a table and insert data. One id of tablet with data is 158888
![Tablet of data](https://user-images.githubusercontent.com/35916131/159688557-185ebc86-ee95-48c7-a433-32b18e81725e.png)

* Drop table force xxxx, we can see the data file disappeared after few seconds.
![file after drop force](https://user-images.githubusercontent.com/35916131/159688899-14d4ed6e-5e1e-4e93-b90c-16a527d2c319.png)

* But the file can be still found in trash ! Even after half hour.
![Data in trash](https://user-images.githubusercontent.com/35916131/159689118-894beda3-aa0f-4ba5-bd1b-4b76eded1145.png)

**Comment by chaoyli** [comment]
After 2.0, the sql `drop table xxx force` will be the statement.
