### ISSUE TITLE
[Enhancement] support percentage number for cpu_limit when creating a resource-group

### ISSUE THREAD

**Issue by mingmxu** [StarRocks/starrocks#43807]
## context

Currently, when creating a resource_group, it only supports `cpu_core_limit` which is the number of CPU cores. It's not straightforward to know the allocation, also needs to be adjusted when total resource in a SR cluster is changed.

## Enhancement

Adding support for percentage values similar as `mem_limit`, to calculate based on cluster resources.

**Comment by ZiheLiu** [comment]
Good suggestions, we will consider to support it later.

**Comment by mingmxu** [comment]
can we re-open this task and prioritize it? We definitely need the feature to simplify resource allocation, especially when a cluster is scaled vertically, using larger/smaller nodes during different periods.
cc @ZiheLiu @chaoyli
