### ISSUE TITLE
Contribute paimon reader to add caching function

### ISSUE THREAD

**Issue by FanHui0225** [StarRocks/starrocks#43899]
## Enhancement
Hi,  I want to contribute the implementation code of paimon reader caching function, how can I do it?

**Comment by miomiocat** [comment]
@Larix1989 Thank you, all contributions are welcome. Please contact me via email (284487410@qq.com). I will provide you with some necessary information and the current R&D progress of Paimon.

**Comment by Larix1989** [comment]
ok! @miomiocat

**Comment by Pandas886** [comment]
Is there any progress?

**Comment by miomiocat** [comment]
> Is there any progress?

Since version 3.2.3, data cache with the native reader has been supported. The topic of discussion in this issue is about supporting data cache with the JNI reader.
