### ISSUE TITLE
[BUG] Paimon catalog scan phase always assigin 3 backends

### ISSUE THREAD

**Issue by yohengyang** [StarRocks/starrocks#44098]
https://forum.mirrorship.cn/t/topic/12192/5
## 问题描述
查询一个paimon 大表非常慢，表总数据行数大约22 亿，集群 100 个 backends节点，查看 profile发现数据 scan只有 3 实例运行
![image](https://github.com/StarRocks/starrocks/assets/39874737/cc3a7b7f-fe69-4396-bfaa-5e6363d6a235)
Starrocks版本：社区3.2.4
paimon 表 有200 bucket
查询语句：select count(1) from paimon.xxx.xxxx;

## 定位到问题原因
com.starrocks.qe.HDFSBackendSelector.HdfsScanRangeHasher#acceptScanRangeLocations没有考虑到paimon

下面是一个 paimon的THdfsScanRange具体信息
![image](https://github.com/StarRocks/starrocks/assets/39874737/41dee9e3-955b-44c5-bc8d-3b0f3a1683c8)

没有一个条件命中com.starrocks.qe.HDFSBackendSelector.HdfsScanRangeHasher#acceptScanRangeLocations中的primitiveSink，所以最终所有 paimon THdfsScanRange计算的 hash 值都是 0
https://github.com/StarRocks/starrocks/blob/613f0b5c107dafec0116fe5c3551ad3d88a2372b/fe/fe-core/src/main/java/com/starrocks/qe/HDFSBackendSelector.java#L127-L145

因为 hash值都是 0， 所以 com.starrocks.qe.HDFSBackendSelector#computeScanRangeAssignment中hashring 返回的始终是同一组 backend
https://github.com/StarRocks/starrocks/blob/613f0b5c107dafec0116fe5c3551ad3d88a2372b/fe/fe-core/src/main/java/com/starrocks/qe/HDFSBackendSelector.java#L278-L279

一个修复思路是在PaimonScanNode中把 split bucket 信息放入THdfsScanRange，HDFSBackendSelector根据 bucket 信息做 hash
https://github.com/StarRocks/starrocks/blob/613f0b5c107dafec0116fe5c3551ad3d88a2372b/fe/fe-core/src/main/java/com/starrocks/planner/PaimonScanNode.java#L208-L226

**Comment by miomiocat** [comment]
@yohengyang 感谢反馈，请问下，你们的这个case里，具体有多少个`remoteScanRangeLocations`(PaimonScanNode::getScanRangeLocations()的返回值)？
