### ISSUE TITLE
HDFS is not recognized in StarRocks K8s deployment mode.

### ISSUE THREAD

**Issue by hwangjeongwook** [StarRocks/starrocks#44298]
### Steps to reproduce the behavior (Required)

I create a hive external table, and I store the data in the Hadoop.
I looked at the starrocks manual and set it up.

* ./fe/conf 
   ><img width="567" alt="스크린샷 2024-04-18 오전 12 08 20" src="https://github.com/StarRocks/starrocks/assets/15261936/411b65e2-9dc0-4fcc-b83b-a3762e36525a">
* krb5.conf (kerberos) 
   ><img width="614" alt="스크린샷 2024-04-18 오전 12 45 56" src="https://github.com/StarRocks/starrocks/assets/15261936/444dc20c-05a3-4c61-8d28-43b0004f71b2">
* hive catalog
   >CREATE EXTERNAL CATALOG `hive` PROPERTIES (
"hive.metastore.type"  =  "hive",
"hadoop.security.authentication"  =  "kerberos",
"hive.metastore.sasl.enabled"  =  "true",
"hadoop.kerberos.keytab"  =  "/home1/irteam/keytab",
"hadoop.kerberos.principal"  =  "......",
"hive.metastore.uris"  =  "...",
"type"  =  "hive",
"hive.metastore.kerberos.principal"  =  "..."
)

At first, it was installed and set up on a general equipment server, and it was confirmed that the query of hive external table was working well.

So, I installed and set it in k8s with the same setting.
It works well up to the hive table lookup (show tables).
However, if I do query, I get a Hadoop error.

* hadoop error  (UnknownHostException)
   ><img width="698" alt="스크린샷 2024-04-18 오전 1 02 18" src="https://github.com/StarRocks/starrocks/assets/15261936/ca7247a4-b9ca-421e-aad5-d5e858ad9f8f">

I have dfs.nameservices set in hdfs-core.xml, but hdfs was not recognized.

So, I made a hive external table by putting the name node address of the haoop.
However, an authentication error occurred this time.

*  an authentication error
   ><img width="700" alt="스크린샷 2024-04-18 오전 1 10 51" src="https://github.com/StarRocks/starrocks/assets/15261936/4129262b-8406-4e7d-91bf-78247b819160">

So, after various tests, it seems that hdfs is not recognized in k8s.

I found an article about an error similar to my symptoms, and it seems that there is an error in fe script.
  >https://forum.mirrorship.cn/t/topic/7465

So this is a real bug so it doesn't recognize hdfs?
Also, how should I set up?
Help me

### Expected behavior (Required)

Expect HDFS to be recognized in StarRocks K8s deployment mode.

### Real behavior (Required)

HDFS is not recognized in StarRocks K8s deployment mode.

### StarRocks version (Required)
3.2

**Comment by kevincai** [comment]
1. unknown host `pg08`, this is the hostname, not a domain name, so in k8s env, it can't be resolved to an IP address. putting the full fqdn name should fix the issue, just like what you did to set it as `pg08-nn1.xx....`
2. authentication error. I saw the configuration `"hadoop.kerberos.keytab" = "/home1/irteam/keytab",`, is this file available for every pod in k8s env?
