### ISSUE TITLE
[inverted index] standard tokenization is not expected

### ISSUE THREAD

**Issue by chengqianli-git** [StarRocks/starrocks#44317]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'4. 

![img_v3_02a2_fa31e981-fa97-4001-afaa-973ff8bcbfag](https://github.com/StarRocks/starrocks/assets/113428458/d58571aa-b0c2-4dac-9aab-c1bbe3bac272)

### Real behavior (Required)

standard 模式下，
50kg, not match
180cm, not match
2024年4月13日, not match
502f3c04-8f5c-11ee-a41f-b22a2c00f66b, not match，502f3c04, not match too.
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main-f493d17

**Comment by srlch** [comment]
no blocking issue
