### ISSUE TITLE
[inverted index]add gin index fail,/xxx/xxx.ivt: No such file or directory

### ISSUE THREAD

**Issue by chengqianli-git** [StarRocks/starrocks#44457]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Real behavior (Required)

```
W0419 16:10:27.095881 15013 schema_change.cpp:273] [Alter Job:13721, tablet:13574]: fail to convert rowset., new_tablet=13727.137595008.3c4bfa526d8f04f0-3c90d1d840862f97, base_tablet=13574.1898834901.22485fdd0a9ea3c9-ef77792d4425e0ac, version=[3-3]
W0419 16:10:27.095899 15013 schema_change.cpp:1056] [Alter Job:13721, tablet:13574]: failed to process the schema change. from tablet 13574.1898834901.22485fdd0a9ea3c9-ef77792d4425e0ac to tablet 13727.137595008.3c4bfa526d8f04f0-3c90d1d840862f97 version=0-4 error Not found: /home/disk1/sr/be/storage/data/800/13574/1898834901/02000000000006f2a940d3df9179541e20af8d24467976ae_0_1.ivt: No such file or directory
/root/starrocks/be/src/fs/fs_util.cpp:30 fs->iterate_dir(path, [&](std::string_view name) { auto full_path = fmt::format("{}/{}", path, name); auto is_dir = fs->is_directory(full_path); if (!is_dir.ok()) { st = is_dir.status(); return false; } if (*is_dir && dirs != nullptr) { dirs->emplace(name); } else if (!*is_dir && files != nullptr) { files->emplace(name); } return true; })
/root/starrocks/be/src/storage/rowset/rowset.cpp:409 fs::list_dirs_files(src_inverted_file_path, nullptr, &files)
/root/starrocks/be/src/storage/rowset/rowset_writer.cpp:624 rowset->link_files_to(tablet == nullptr ? nullptr : tablet->data_dir()->get_meta(), _context.rowset_path_prefix, _context.rowset_id)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main-f493d17

**Comment by srlch** [comment]
https://github.com/StarRocks/starrocks/issues/44523 same problem

**Comment by srlch** [comment]
https://github.com/StarRocks/starrocks/pull/44547

**Comment by srlch** [comment]
repeated:
`CREATE TABLE `t` (
  `k` BIGINT NOT NULL COMMENT "",
  `v1` string COMMENT "",
  `v2` string COMMENT "",
  INDEX idx1 (v2) USING BITMAP,
  INDEX idx2 (v1) USING GIN ('parser' = 'english')
) ENGINE=OLAP 
DUPLICATE KEY(`k`, v1)
DISTRIBUTED BY HASH(`k`,`v1`) BUCKETS 1
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "false",
"compression" = "LZ4"
);

insert into t values (1,"a","b");

create materialized view mv1 as select k, v1 from t;`
