### ISSUE TITLE
StreamLoad 部分更新，希望 create_time 这种字段的默认值能够生效。目前并不支持，详见截图和 pdf

### ISSUE THREAD

**Issue by plough** [StarRocks/starrocks#44464]
## Feature request

**Is your feature request related to a problem? Please describe.**
我通过 StreamLoad api 导入数据，开启了部分更新特性。有一个字段是 create_time，已设置默认值为当前时间戳。实际进行导入时，默认值不生效。

这种场景应该挺常见的，希望能提供一个解决方案。

![截屏2024-04-19 16 24 04](https://github.com/StarRocks/starrocks/assets/7723382/f93688a9-e9d5-45b1-95f7-d9d7b1c981e8)

**Describe the solution you'd like**
我希望能 StreamLoad 能支持默认值，就像执行 insert 语句那样。

**Describe alternatives you've considered**
暂时还没有想到替代方案。

**Additional context**
完整复现步骤，见附件 pdf
[StarRocks StreamLoad 默认值失效 7c1923f25a3e443a89069c437eb690d5.pdf](https://github.com/StarRocks/starrocks/files/15038537/StarRocks.StreamLoad.7c1923f25a3e443a89069c437eb690d5.pdf)

**Comment by jaogoy** [comment]
It's probably the default function such as  current_timestamp is not supported in partial update, const value, such as "2024-01-01", is supported, I'll check it.
