### ISSUE TITLE
Support bitmap as a primitive type【Easy】

### ISSUE THREAD

**Issue by aaawuanjun** [StarRocks/starrocks#4449]
### BackGround
In our situations, we have 2 tables：the detail label table、the aggregate label table.
The detail label table data can store outside of StarRocks, generate final data, and store the datas in StarRocks.

The detail lable table:
<html  xmlns:o="urn:schemas-microsoft-com:office:office"  xmlns:x="urn:schemas-microsoft-com:office:excel"  xmlns="http://www.w3.org/TR/REC-html40">
<head>
</head>
<body>

tagname | tagvalue | userid
-- | -- | --
持有产品 | 保险 | 2
持有产品 | 保险 | 3
持有产品 | 保险 | 5
持有产品 | 保险 | 7
持有产品 | 保险 | 8
持有产品 | 保险 | 11
持有产品 | 保险 | 12
持有产品 | 保险 | 13
持有产品 | 保险 | 15
持有产品 | 男 | 0
持有产品 | 男 | 1
持有产品 | 男 | 2
持有产品 | 贵金属 | 0
持有产品 | 贵金属 | 1
持有产品 | 贵金属 | 4
持有产品 | 贵金属 | 5
持有产品 | 贵金属 | 6
持有产品 | 贵金属 | 7
持有产品 | 贵金属 | 9
持有产品 | 贵金属 | 10
持有产品 | 贵金属 | 13
持有产品 | 贵金属 | 14

</body>
</html>

The aggregate label table:
<html  xmlns:o="urn:schemas-microsoft-com:office:office"  xmlns:x="urn:schemas-microsoft-com:office:excel"  xmlns="http://www.w3.org/TR/REC-html40">
<head>
</head>

<body>

tagname | tagvalue | userids
-- | -- | --
持有产品 | 保险 | [2,3,5,7,8,11,12,13,15]
持有产品 | 男 | [0,1,2]
持有产品 | 贵金属 | [0,1,4,5,6,7,9,10,13,14]

</body>
</html>

### what we want?
1、bitmap as a primitive type, we can use in all modules: Duplicate Key、aggregate key、primary key、Unique Key
2、This  aggregate label table can insert/update/delete bitmap data,  it is best if bit update is supported.

### Example:
for example in primary key module:
In StarRocks, only one table as below:
> CREATE TABLE tbl_tag_bitmap (
  tagname string NOT NULL COMMENT '标签名称',
  tagvalue string NOT NULL COMMENT '标签值',
  userid bitmap NOT NULL COMMENT '访问用户id' 
) ENGINE=OLAP
PRIMARY KEY(tagname, tagvalue) DISTRIBUTED BY HASH(tagname) BUCKETS 1
PROPERTIES (   
  "replication_num" = "1",   
  "storage_format" = "DEFAULT" 
);

outside of starrocks, we calculate the results and store those in starrocks, we can use insert query、 broker loader or stream loader etc. to input data
> -- eg: use insert query
> insert into tbl_tag_bitmap values('持有产品','金属',[0000000011]);
> insert into tbl_tag_bitmap values('持有产品','男',[1010111110]);
> 
> -- use select query with "and" operation on bitmap
> WITH bitmap1 AS (
> 		SELECT userid AS userid1
> 		FROM tbl_tag_bitmap
> 		WHERE tagname = '持有产品'
> 			AND tagvalue = '贵金属'
> 	), 
> 	bitmap2 AS (
> 		SELECT userid AS userid2
> 		FROM tbl_tag_bitmap
> 		WHERE tagname = '持有产品'
> 			AND tagvalue = '男'
> 	)
> SELECT bitmap_to_string(bitmap_and(userid1, userid2))
> FROM bitmap1, bitmap2;

### any ideas or key points of develop this feature?

# Mentor
@decster 

# Before you start
1. Read the StarRocks [GitHub workflow](https://github.com/StarRocks/community/blob/main/Contributors/guide/workflow.md) carefully, which provides the configurations of BE and FE and describes how to submit a pull request.
2. To learn more about StarRocks, read [StarRocks documentation](https://github.com/StarRocks/docs/blob/main/TOC.md).

# Pull request requirements

1. After you complete code development, upload the code to the StarRocks code repo as a pull request (PR).

  - PR title format: **[SR GeekCamp] + PR title**
  - Labels ：[Geek Camp 2022/feature]
2. After you submit your PR, comment on the status of your PR submission as requested under the Pinned Issue [[StarRocks geek Camp 2022] ](https://github.com/StarRocks/starrocks/issues/4008)page.

  - Comment format: **"I have finished Issue #" + PR link id**

**Comment by aaawuanjun** [comment]
The Develop Process:
1、create table process
2、store data into table process (insert  or stream/broker load)
3、query process

any other key point?

**Comment by taizilongxu** [comment]
We need bitmap as a primitive type too, it will useful for us to compute the common focus of friends rather than use the agg table which cannnot delete the bitmap field
