### ISSUE TITLE
[BUG] Dont's show load when i run show compute node

### ISSUE THREAD

**Issue by richzhu369** [StarRocks/starrocks#44563]
### Steps to reproduce the behavior (Required)
SHOW PROC '/compute_nodes'\G

### Expected behavior (Required)
it will should show cpu and memory load
![image](https://github.com/StarRocks/starrocks/assets/152697677/830f2838-9094-4380-87ee-f2cc07996d2e)

### Real behavior (Required)
i just restart FE and put qe_max_connection = 10000 to cn.conf, but they don't show the load right now ,always show 0%

### StarRocks version (Required)
3.2.4-613f0b5

**Comment by kevincai** [comment]
work as design. `show proc '/compute_nodes'` will be a local view of the compute nodes on the fe, in case the fe instance is a follower/observer, some of the information is not synced with leader which is intended.

use `show compute nodes` if willing to get the info from the leader's view.
