### ISSUE TITLE
缩容出现UnhealthyTabletNum无法正常剔除BE机器

### ISSUE THREAD

**Issue by icedrugs89** [StarRocks/starrocks#4463]
请问下，我们现在在线上做一些扩容缩容的测试，目前是2台FE，4台BE，之前测试的人建的表语句副本选择了3份，由于做缩容需要下线3台，只保留一台BE，我对之前的表做了类似这样的修改ALTER TABLE `test_one_1` SET("replication_num"="1");
然后开始了下述的缩容操作，通过下述的方式下缩容，10.161.124.44可以完成，
alter system decommission backend "10.161.124.44:19050"; 下线完成
alter system decommission backend "10.161.124.26:19050";执行后过了1天多TabletNum为89062一直降不下去，如下图
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/100941547/160225402-de8f9ded-a981-4a0f-95c2-270899dfb0de.png">
show proc '/statistic/';如下图：
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/100941547/160225459-c6973cf9-2e65-421c-be3d-3ad9bb69e032.png">
因为192319、10535的UnhealthyTabletNum输出太多，使用10302查看
show proc '/statistic/10302';
<img width="569" alt="image" src="https://user-images.githubusercontent.com/100941547/160225517-6f3ea7a9-ce2f-4ff7-a003-c1a4a03a65b7.png">
show tablet 10491;
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/100941547/160225512-79db12fb-53b4-4c5c-a45f-473821f35f03.png">
 SHOW PROC '/dbs/10302/10463/partitions/10461/10464/10491';
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/100941547/160225531-570bf0d2-20b3-49bb-b364-7732fc80df5d.png">
请问下这种情况要怎么处理

**Comment by gengjun-git** [comment]
ALTER TABLE test_one_1 SET("replication_num"="1"); 这个语句只能对表做修改，新增的分区会集成该属性。
使用 ALTER TABLE test_one_1 MODIFY PARTITION (*) SET("replication_num"="1");对现有的分区作修改。

**Comment by icedrugs89** [comment]
那是用ALTER TABLE test_one_1 MODIFY PARTITION (*) SET("replication_num"="1");重新修改一次后，在进行缩容吗

**Comment by gengjun-git** [comment]
Yes

**Comment by icedrugs89** [comment]
![image](https://user-images.githubusercontent.com/100941547/160317704-382bba52-1590-41d7-9fae-d6e717c5ca11.png)
![image](https://user-images.githubusercontent.com/100941547/160317715-06ae462c-06e8-4c9b-b917-5f5f465d25f5.png)
![image](https://user-images.githubusercontent.com/100941547/160317737-651358a5-efb8-45fd-b0cc-4db5429d0ad8.png)
这个表已经是1个副本了修改后，按照ALTER TABLE a_mysql_all_types_notime_1 MODIFY PARTITION (*) SET("replication_num"="1");执行的，还是有不健康的tablet，接下来还有什么办法修复吗

**Comment by gengjun-git** [comment]
show proc '/dbs/190839/301140/partitions/301351/301141/301380';看一下。单副本有问题的话，可能就不能自动修复了。

**Comment by icedrugs89** [comment]
现在有问题的，我截图你看看这个
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/100941547/160527355-4feeb466-25ae-42ea-a78d-e189e7c7cd1e.png">

**Comment by icedrugs89** [comment]
现在卡住的剩下2个tabletNum
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/100941547/160541452-8d1fc0fb-35fe-43ab-a040-4b87674357ba.png">

**Comment by icedrugs89** [comment]
这个是对应10003 backendId的日志
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/100941547/160546009-2dae2b61-6b6d-458d-ba9e-956638ee7df1.png">

**Comment by gengjun-git** [comment]
1.18版本对primary key支持的还不好，把表删了升级到2.0吧。

**Comment by icedrugs89** [comment]
我们这个线上的数据。。还有其他方式来处理吗？或者删除表的话数据要怎么迁移到2.0的表
