### ISSUE TITLE
 v3.0 不知道现在版本还有没有。 数字类型字段col3用 insert into test(col3) values('1,2') 会有报错提示，但是 insert into test(col3) select '1,2' 就没有提示插进去是空置，我觉的这个地方应该报错提示才对

### ISSUE THREAD

**Issue by javak8** [StarRocks/starrocks#44641]
v3.0 版本发现，不知道现在版本还有没有。
 数字类型字段col3用 insert into test(col3) values('1,2') 会有报错提示，
但是 insert into test(col3) select '1,2' 就没有提示插进去是空置，我觉的这个地方应该报错提示才对，
否则数据同步时这里会造成一些数据问题

**Comment by Andy-xu-007** [comment]
Same problem are not encountered in versrion 3.2.6
![1714036013347](https://github.com/StarRocks/starrocks/assets/32799875/9fbe2e62-0e28-4096-831e-6f995e258ed3)

**Comment by Seaven** [comment]
try to `set sql_mode='ALLOW_THROW_EXCEPTION'`
