### ISSUE TITLE
[BUG] 负载不平均 - FE load balance not fair

### ISSUE THREAD

**Issue by richzhu369** [StarRocks/starrocks#44700]
### Steps to reproduce the behavior (Required)
SHOW PROC '/compute_nodes'\G

### Expected behavior (Required)
我的集群是存算分离，由FE+CN组成， 
集群规模是：6个FE，2个OB，17个CN， 一开始集群只有5个CN 3个FE，慢慢扩容到当前的规模

目前发现 FE发送到后端的CN，任务数量不平均
我发现每个CN的 load不同，前5个节点的load几乎都是满满的，CPU占用也非常高，后几个CN尤其是 15，16，17 倒数这三个CN，非常清闲， load不高，cpu占用也不高，当我执行 SHOW PROC '/compute_nodes'\G，  之后 发现每个CN的 NumRunningQueries 数量也不同，有些已经 30多个了， 有些CN上的NumRunningQueries: 值 只有1个

### Real behavior (Required)
麻烦让负载均衡，更平均一些

### StarRocks version (Required)
3.2.4-613f0b5

服务器配置：
FE/OB:
16c/32G/500G

CN:
16C/64G/2T

aws linux

**Comment by richzhu369** [comment]
服务器配置：
FE/OB:
16c/32G/500G

CN:
16C/64G/2T

aws linux

**Comment by kevincai** [comment]
can you run `show compute nodes`? check the tabletnum of each compute node.

Also what's the bucket number for your tables?

**Comment by richzhu369** [comment]
is CN , not BE, don't have TabletNum:

as flow:
*************************** 1. row ***************************
        ComputeNodeId: 829111
                   IP: 172.31.0.174
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2024-04-20 08:51:27
        LastHeartbeat: 2024-04-25 03:00:22
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
               ErrMsg: 
              Version: 3.2.4-613f0b5
             CpuCores: 16
    NumRunningQueries: 259
           MemUsedPct: 46.06 %
           CpuUsedPct: 93.7 %
       HasStoragePath: true
          StarletPort: 9070
             WorkerId: 1114
*************************** 2. row ***************************
        ComputeNodeId: 2164817
                   IP: 172.31.1.43
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2024-04-20 08:51:27
        LastHeartbeat: 2024-04-25 03:00:22
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
               ErrMsg: 
              Version: 3.2.4-613f0b5
             CpuCores: 16
    NumRunningQueries: 237
           MemUsedPct: 45.94 %
           CpuUsedPct: 67.9 %
       HasStoragePath: true
          StarletPort: 9070
             WorkerId: 1827
*************************** 3. row ***************************
        ComputeNodeId: 2164819
                   IP: 172.31.11.179
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2024-04-20 08:51:27
        LastHeartbeat: 2024-04-25 03:00:22
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
               ErrMsg: 
              Version: 3.2.4-613f0b5
             CpuCores: 16
    NumRunningQueries: 220
           MemUsedPct: 46.97 %
           CpuUsedPct: 71.3 %
       HasStoragePath: true
          StarletPort: 9070
             WorkerId: 1828
*************************** 4. row ***************************
        ComputeNodeId: 829110
                   IP: 172.31.14.214
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2024-04-20 08:51:27
        LastHeartbeat: 2024-04-25 03:00:22
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
               ErrMsg: 
              Version: 3.2.4-613f0b5
             CpuCores: 16
    NumRunningQueries: 292
           MemUsedPct: 46.23 %
           CpuUsedPct: 94.3 %
       HasStoragePath: true
          StarletPort: 9070
             WorkerId: 1113
*************************** 5. row ***************************
        ComputeNodeId: 12195343
                   IP: 172.31.20.12
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2024-04-22 02:05:52
        LastHeartbeat: 2024-04-25 03:00:22
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
               ErrMsg: 
              Version: 3.2.4-613f0b5
             CpuCores: 16
    NumRunningQueries: 181
           MemUsedPct: 41.77 %
           CpuUsedPct: 46.0 %
       HasStoragePath: true
          StarletPort: 9070
             WorkerId: 3983
*************************** 6. row ***************************
        ComputeNodeId: 12195339
                   IP: 172.31.24.122
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2024-04-22 02:05:52
        LastHeartbeat: 2024-04-25 03:00:22
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
               ErrMsg: 
              Version: 3.2.4-613f0b5
             CpuCores: 16
    NumRunningQueries: 188
           MemUsedPct: 42.95 %
           CpuUsedPct: 42.8 %
       HasStoragePath: true
          StarletPort: 9070
             WorkerId: 3981
*************************** 7. row ***************************
        ComputeNodeId: 12195341
                   IP: 172.31.25.253
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2024-04-22 02:05:52
        LastHeartbeat: 2024-04-25 03:00:22
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
               ErrMsg: 
              Version: 3.2.4-613f0b5
             CpuCores: 16
    NumRunningQueries: 169
           MemUsedPct: 41.75 %
           CpuUsedPct: 57.6 %
       HasStoragePath: true
          StarletPort: 9070
             WorkerId: 3984
*************************** 8. row ***************************
        ComputeNodeId: 12195342
                   IP: 172.31.28.179
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2024-04-22 02:05:52
        LastHeartbeat: 2024-04-25 03:00:22
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
               ErrMsg: 
              Version: 3.2.4-613f0b5
             CpuCores: 16
    NumRunningQueries: 193
           MemUsedPct: 43.34 %
           CpuUsedPct: 65.4 %
       HasStoragePath: true
          StarletPort: 9070
             WorkerId: 3982
*************************** 9. row ***************************
        ComputeNodeId: 6645757
                   IP: 172.31.3.158
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2024-04-22 12:11:23
        LastHeartbeat: 2024-04-25 03:00:22
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
               ErrMsg: 
              Version: 3.2.4-613f0b5
             CpuCores: 16
    NumRunningQueries: 103
           MemUsedPct: 36.48 %
           CpuUsedPct: 26.2 %
       HasStoragePath: true
          StarletPort: 9070
             WorkerId: 2953
*************************** 10. row ***************************
        ComputeNodeId: 829109
                   IP: 172.31.3.211
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2024-04-20 08:51:27
        LastHeartbeat: 2024-04-25 03:00:22
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
               ErrMsg: 
              Version: 3.2.4-613f0b5
             CpuCores: 16
    NumRunningQueries: 254
           MemUsedPct: 45.39 %
           CpuUsedPct: 86.4 %
       HasStoragePath: true
          StarletPort: 9070
             WorkerId: 1112
*************************** 11. row ***************************
        ComputeNodeId: 6645755
                   IP: 172.31.3.36
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2024-04-22 12:08:33
        LastHeartbeat: 2024-04-25 03:00:22
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
               ErrMsg: 
              Version: 3.2.4-613f0b5
             CpuCores: 16
    NumRunningQueries: 173
           MemUsedPct: 42.90 %
           CpuUsedPct: 39.9 %
       HasStoragePath: true
          StarletPort: 9070
             WorkerId: 2954
*************************** 12. row ***************************
        ComputeNodeId: 12866
                   IP: 172.31.32.95
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2024-04-20 08:51:27
        LastHeartbeat: 2024-04-25 03:00:22
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
               ErrMsg: 
              Version: 3.2.4-613f0b5
             CpuCores: 16
    NumRunningQueries: 397
           MemUsedPct: 48.42 %
           CpuUsedPct: 95.9 %
       HasStoragePath: true
          StarletPort: 9070
             WorkerId: 9
*************************** 13. row ***************************
        ComputeNodeId: 12802
                   IP: 172.31.37.115
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2024-04-20 08:51:27
        LastHeartbeat: 2024-04-25 03:00:22
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
               ErrMsg: 
              Version: 3.2.4-613f0b5
             CpuCores: 16
    NumRunningQueries: 311
           MemUsedPct: 45.63 %
           CpuUsedPct: 96.0 %
       HasStoragePath: true
          StarletPort: 9070
             WorkerId: 3
*************************** 14. row ***************************
        ComputeNodeId: 12801
                   IP: 172.31.40.5
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2024-04-20 08:51:27
        LastHeartbeat: 2024-04-25 03:00:22
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
               ErrMsg: 
              Version: 3.2.4-613f0b5
             CpuCores: 16
    NumRunningQueries: 261
           MemUsedPct: 45.38 %
           CpuUsedPct: 89.4 %
       HasStoragePath: true
          StarletPort: 9070
             WorkerId: 2
*************************** 15. row ***************************
        ComputeNodeId: 12800
                   IP: 172.31.42.239
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2024-04-20 08:51:27
        LastHeartbeat: 2024-04-25 03:00:22
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
               ErrMsg: 
              Version: 3.2.4-613f0b5
             CpuCores: 16
    NumRunningQueries: 243
           MemUsedPct: 46.12 %
           CpuUsedPct: 93.5 %
       HasStoragePath: true
          StarletPort: 9070
             WorkerId: 1
*************************** 16. row ***************************
        ComputeNodeId: 2164818
                   IP: 172.31.7.28
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2024-04-20 08:51:27
        LastHeartbeat: 2024-04-25 03:00:22
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
               ErrMsg: 
              Version: 3.2.4-613f0b5
             CpuCores: 16
    NumRunningQueries: 206
           MemUsedPct: 44.59 %
           CpuUsedPct: 58.9 %
       HasStoragePath: true
          StarletPort: 9070
             WorkerId: 1829
*************************** 17. row ***************************
        ComputeNodeId: 2164820
                   IP: 172.31.7.36
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2024-04-22 12:03:53
        LastHeartbeat: 2024-04-25 03:00:22
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
               ErrMsg: 
              Version: 3.2.4-613f0b5
             CpuCores: 16
    NumRunningQueries: 175
           MemUsedPct: 41.32 %
           CpuUsedPct: 45.7 %
       HasStoragePath: true
          StarletPort: 9070
             WorkerId: 1830
17 rows in set (0.01 sec)

**Comment by kevincai** [comment]
ok.

**Comment by kevincai** [comment]
how many buckets specified for the tables in the system?

**Comment by richzhu369** [comment]
> how many buckets specified for the tables in the system?

hmm , can you please tell me how to check buckets

**Comment by kevincai** [comment]
`show create table xxx`. what's the `BUCKETS` number for the table.

**Comment by richzhu369** [comment]
> `show create table xxx`. what's the `BUCKETS` number for the table.

hello ,thank you , i had check it , some tables have 6 buckets, and some tables have 4 buckets

**Comment by richzhu369** [comment]
> `show create table xxx`. what's the `BUCKETS` number for the table.

can you tell me how to optimizer buckets numbers
