### ISSUE TITLE
[Enhancement] Support to batch drop partitions

### ISSUE THREAD

**Issue by jaogoy** [StarRocks/starrocks#44744]
## Enhancement
Supports batch deletion of partitions in som ways:
[ ] using names:  #43539 
[ ] using START/END:  #43539
[ ] using equal conditions:
[ ] using rich expression conditions:
```SQL
DROP PARTITION(S) p0, p1, ...;

DROP PARTITION(S) [date_col] [FROM] START(v1) [TO] END(v2) EVERY ( interval );

DROP PARTITION(S) (v11, v12), (v21, v22);
DROP PARTITION(S) (c1=v11, c2=v12), (c1=v21, c2=v22);
DROP PARTITION(S) (c1, c2) { VALUES | IN } ((v11, v12), (v21, v22) ,...);

DROP PARTITION(S) (c1 >= v11 and c1 <= v12, c2 >= v21);
```
The later two methods need more discussion.

**Comment by leiyang0324** [comment]
1.目前支持了这两种模式，一种是Range分区，一种是list模式，参考如下：
alter table %s.%s DROP PARTITIONS IF EXISTS START(\"2021-02-01\") END(\"2021-02-03\") EVERY (INTERVAL 1 DAY);
alter table %s.%s DROP PARTITIONS IF EXISTS (p20210201,p20210202) ;
2.没有支持多列
