### ISSUE TITLE
got exception when replay star mgr journal

### ISSUE THREAD

**Issue by yandongxiao** [StarRocks/starrocks#44832]
### Steps to reproduce the behavior (Required)

1. Use the main branch to build FE
2. start to run SR In shared-data mode
3. do some SQL operation
4. restart FE and check the fe.warn.log.

### Expected behavior (Required)

there is no logs in fe.warn.log

### Real behavior (Required)

```
2024-04-26 00:17:21.299+08:00 ERROR (star mgr LeaderCheckpointer|112) [Checkpoint.replayAndGenerateStarMgrImage():236] Exception when generate new star mgr image file, null.
```

### StarRocks version (Required)
 - main
 - branch-3.3

**Comment by kevincai** [comment]
done
