### ISSUE TITLE
Support COM_STMT_PREPARE and related commands in MySQL Protocol implementation

### ISSUE THREAD

**Issue by benkimpel** [StarRocks/starrocks#45055]
## Feature request

Prepared statement support in the MySQL Protocol implementation would help us increase adoption of StarRocks within our organization.

**Comment by imay** [comment]
This has been supported in the new version already.

**Comment by benkimpel** [comment]
> This has been supported in the new version already.

Oh, I'm sorry. Which version? I was asked to create an issue here from discussion on slack.

https://starrocks.slack.com/archives/C02FACZSNJV/p1714421427693439

I'm glad it's supported

**Comment by benkimpel** [comment]
@imay I'm currently on `3.2.4-613f0b5` and I get malformed packet when using prepared statements over the mysql protocol. Is this supported in `3.2.6`? I didn't see any mention of it in the release notes.

**Comment by imay** [comment]
https://docs.starrocks.io/docs/sql-reference/sql-statements/prepared_statement/
As you can see from this document, prepare statement has been supported since v3.2
Maybe your issue is a bug, could you please paste the step to reproduce it and we can see if it has been fixed or not.

**Comment by benkimpel** [comment]
Thanks. I'll investigate further and open an issue as a bug if needed.

**Comment by benkimpel** [comment]
@imay Opened issue #45072
