### ISSUE TITLE
Malformed packet or encoding issue with date over binary protocol

### ISSUE THREAD

**Issue by benkimpel** [StarRocks/starrocks#45072]
It seems like the official MySQL Python Connector (and at least one other driver) is having trouble parsing dates sent from StarRocks over binary protocol. 

### Steps to reproduce the behavior (Required)

```sql
CREATE DATABASE example_db;
USE example_db;

CREATE TABLE date_example (dt DATE);

INSERT INTO date_example
VALUES ('2024-01-01'),
       ('2024-01-02'),
       ('2024-01-03')
       ('2024-01-04');
```

**BAD (`prepared=True`)**

```python
import mysql.connector

db = mysql.connector(
  host="...", 
  user="root", 
  password="...", 
  port=9030, 
  database="example_db"
)

sql = "SELECT dt FROM example"

cursor = db.cursor(prepared=True)
cursor.execute(sql, [])

result = cursor.fetchall()
print(result)

# => [(None,), (None,), (None,), (None,)]
```

**GOOD (`prepared=False`)**

```python
import mysql.connector

db = mysql.connector(
  host="...", 
  user="root", 
  password="...", 
  port=9030, 
  database="example_db"
)

sql = "SELECT dt FROM example"

cursor = db.cursor(prepared=False)
cursor.execute(sql, [])

result = cursor.fetchall()

print(result)

# => [(datetime.date(2024, 4, 1),), (datetime.date(2024, 4, 2),), (datetime.date(2024, 4, 3),), (datetime.date(2024, 4, 4),)]
```

Here is a screenshot of Wireshark packet capture where StarRocks is responding to request execute statement.

<img width="1540" alt="Screenshot 2024-05-04 at 1 45 09 PM" src="https://github.com/StarRocks/starrocks/assets/3131496/54135499-4b18-4dcd-bfc7-5dd6f81c4553">

I don't think this is a Python/Python library issue, because I can replicate the issue in at least one other language/library.

### Expected behavior (Required)

Dates are encoded properly in binary protocol.

### Real behavior (Required)

Packets with dates in binary protocol are incorrectly encoded or the packet itself is malformed.

### StarRocks version (Required)

`3.2.4-613f0b5`

**Comment by packy92** [comment]
Yes, we had noticed this bug. We will fix it ASAP.

**Comment by benkimpel** [comment]
Thanks. I appreciate it.

**Comment by danilagamma** [comment]
I believe this is still an issue for 3.3.0 when multiple null values are present in the response
