### ISSUE TITLE
使用视图关联其他表join查询时BE挂掉

### ISSUE THREAD

**Issue by Lunmer** [StarRocks/starrocks#4515]
2.1.1版本be.out堆栈信息：
start time: Mon Mar 28 17:15:44 CST 2022
tcmalloc: large alloc 111518825848832 bytes == (nil) @  0x4e93709 0x50113dc 0x1ce55e8 0x4f61c75 0x2daccd2 0x2daddf5 0x2d4ef66 0x28dab02 0x2860f20 0x2d4ec95 0x296669c 0x2d1574b 0x2860fb4 0x239bf10 0x21c5883 0x1ca9eba 0x1cab7f5 0x1cac3c7 0x1c47452 0x1c4bcec 0x1c4c511 0x1d741b9 0x1d6fd78 0x7fe3168ece25
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
*** Aborted at 1648459141 (unix time) try "date -d @1648459141" if you are using GNU date ***
PC: @     0x7fe315c2a277 __GI_raise
*** SIGABRT (@0x42b32) received by PID 273202 (TID 0x7fe2a371d700) from PID 273202; stack trace: ***
    @          0x34fe482 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fe3168f46d0 (unknown)
    @     0x7fe315c2a277 __GI_raise
    @     0x7fe315c2b968 __GI_abort
    @          0x15dc529 _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold
    @          0x4f61726 __cxxabiv1::__terminate()
    @          0x4f61791 std::terminate()
    @          0x4f618e4 __cxa_throw
    @          0x15dc430 _Znwm.cold
    @          0x2daa37e std::__cxx11::basic_string<>::_M_construct<>()
    @          0x2daccd2 starrocks::vectorized::JsonFunctions::_iterate_rows<>()
    @          0x2daddf5 starrocks::vectorized::JsonFunctions::get_json_string()
    @          0x2d4ef66 starrocks::vectorized::VectorizedFunctionCallExpr::evaluate()
    @          0x28dab02 starrocks::vectorized::ArrayExpr::evaluate()
    @          0x2860f20 starrocks::ExprContext::evaluate()
    @          0x2d4ec95 starrocks::vectorized::VectorizedFunctionCallExpr::evaluate()
    @          0x296669c starrocks::vectorized::VectorizedBinaryPredicate<>::evaluate()
    @          0x2d1574b starrocks::vectorized::VectorizedIfExpr<>::evaluate()
    @          0x2860fb4 starrocks::ExprContext::evaluate()
    @          0x239bf10 starrocks::vectorized::ProjectNode::get_next()
    @          0x21c5883 starrocks::vectorized::AggregateStreamingNode::get_next()
    @          0x1ca9eba starrocks::PlanFragmentExecutor::_get_next_internal_vectorized()
    @          0x1cab7f5 starrocks::PlanFragmentExecutor::_open_internal_vectorized()
    @          0x1cac3c7 starrocks::PlanFragmentExecutor::open()
    @          0x1c47452 starrocks::FragmentExecState::execute()
    @          0x1c4bcec starrocks::FragmentMgr::exec_actual()
    @          0x1c4c511 _ZNSt17_Function_handlerIFvvEZN9starrocks11FragmentMgr18exec_plan_fragmentERKNS1_23TExecPlanFragmentParamsERKSt8functionIFvPNS1_20PlanFragmentExecutorEEESC_EUlvE_E9_M_invokeERKSt9_Any_data
    @          0x1d741b9 starrocks::ThreadPool::dispatch_thread()
    @          0x1d6fd78 starrocks::Thread::supervise_thread()
    @     0x7fe3168ece25 start_thread
    @     0x7fe315cf2bad __clone
    @                0x0 (unknown)
start time: Mon Mar 28 17:19:17 CST 2022
*** Aborted at 1648459726 (unix time) try "date -d @1648459726" if you are using GNU date ***
PC: @          0x2dacca5 starrocks::vectorized::JsonFunctions::_iterate_rows<>()
*** SIGSEGV (@0x17) received by PID 500214 (TID 0x7fe149f40700) from PID 23; stack trace: ***
    @          0x34fe482 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fe1ab8856d0 (unknown)
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
    @          0x2dacca5 starrocks::vectorized::JsonFunctions::_iterate_rows<>()
    @          0x2daddf5 starrocks::vectorized::JsonFunctions::get_json_string()
    @          0x2d4ef66 starrocks::vectorized::VectorizedFunctionCallExpr::evaluate()
terminate called recursively
terminate called recursively
    @          0x28dab02 starrocks::vectorized::ArrayExpr::evaluate()
    @          0x2860f20 starrocks::ExprContext::evaluate()
    @          0x2d4ec95 starrocks::vectorized::VectorizedFunctionCallExpr::evaluate()
    @          0x296669c starrocks::vectorized::VectorizedBinaryPredicate<>::evaluate()
    @          0x2d1574b starrocks::vectorized::VectorizedIfExpr<>::evaluate()
    @          0x2860fb4 starrocks::ExprContext::evaluate()
    @          0x239bf10 starrocks::vectorized::ProjectNode::get_next()
    @          0x21c5883 starrocks::vectorized::AggregateStreamingNode::get_next()
    @          0x1ca9eba starrocks::PlanFragmentExecutor::_get_next_internal_vectorized()
    @          0x1cab7f5 starrocks::PlanFragmentExecutor::_open_internal_vectorized()
    @          0x1cac3c7 starrocks::PlanFragmentExecutor::open()
    @          0x1c47452 starrocks::FragmentExecState::execute()
    @          0x1c4bcec starrocks::FragmentMgr::exec_actual()
    @          0x1c4c511 _ZNSt17_Function_handlerIFvvEZN9starrocks11FragmentMgr18exec_plan_fragmentERKNS1_23TExecPlanFragmentParamsERKSt8functionIFvPNS1_20PlanFragmentExecutorEEESC_EUlvE_E9_M_invokeERKSt9_Any_data
    @          0x1d741b9 starrocks::ThreadPool::dispatch_thread()
    @          0x1d6fd78 starrocks::Thread::supervise_thread()
    @     0x7fe1ab87de25 start_thread
    @     0x7fe1aac83bad __clone
    @                0x0 (unknown)
start time: Mon Mar 28 17:29:01 CST 2022
*** Aborted at 1648459796 (unix time) try "date -d @1648459796" if you are using GNU date ***
PC: @          0x2dacca5 starrocks::vectorized::JsonFunctions::_iterate_rows<>()
*** SIGSEGV (@0x8) received by PID 306454 (TID 0x7f53bc31d700) from PID 8; stack trace: ***
    @          0x34fe482 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f542f4ee6d0 (unknown)
terminate called after throwing an instance of 'std::length_error'
  what():  vector::reserve
    @          0x2dacca5 starrocks::vectorized::JsonFunctions::_iterate_rows<>()
terminate called recursively
src/tcmalloc.cc:342] Attempt to get the size of an invalid pointer 0x5014b58 
    @          0x2daddf5 starrocks::vectorized::JsonFunctions::get_json_string()
    @          0x2d4ef66 starrocks::vectorized::VectorizedFunctionCallExpr::evaluate()
    @          0x28dab02 starrocks::vectorized::ArrayExpr::evaluate()
    @          0x2860f20 starrocks::ExprContext::evaluate()
    @          0x2d4ec95 starrocks::vectorized::VectorizedFunctionCallExpr::evaluate()
    @          0x296669c starrocks::vectorized::VectorizedBinaryPredicate<>::evaluate()
    @          0x2d1574b starrocks::vectorized::VectorizedIfExpr<>::evaluate()
    @          0x2860fb4 starrocks::ExprContext::evaluate()
    @          0x239bf10 starrocks::vectorized::ProjectNode::get_next()
    @          0x21c5883 starrocks::vectorized::AggregateStreamingNode::get_next()
    @          0x1ca9eba starrocks::PlanFragmentExecutor::_get_next_internal_vectorized()
    @          0x1cab7f5 starrocks::PlanFragmentExecutor::_open_internal_vectorized()
    @          0x1cac3c7 starrocks::PlanFragmentExecutor::open()
    @          0x1c47452 starrocks::FragmentExecState::execute()
    @          0x1c4bcec starrocks::FragmentMgr::exec_actual()
    @          0x1c4c511 _ZNSt17_Function_handlerIFvvEZN9starrocks11FragmentMgr18exec_plan_fragmentERKNS1_23TExecPlanFragmentParamsERKSt8functionIFvPNS1_20PlanFragmentExecutorEEESC_EUlvE_E9_M_invokeERKSt9_Any_data
    @          0x1d741b9 starrocks::ThreadPool::dispatch_thread()
    @          0x1d6fd78 starrocks::Thread::supervise_thread()
    @     0x7f542f4e6e25 start_thread
    @     0x7f542e8ecbad __clone
    @                0x0 (unknown)
start time: Mon Mar 28 17:30:00 CST 2022

**Comment by mofeiatwork** [comment]
Looks like it's caused by the BinaryColumn overflow issue, and the `get_json_string` function receives a broken BinaryColumn.

**Comment by mofeiatwork** [comment]
Related SQL:


```sql
CREATE VIEW `v_rm_log_freq` AS SELECT `a`.`st` AS `st`, `a`.`rmid` AS `rmid`, `a`.`pure_date` AS `pure_date`, `a`.`hour` AS `hour`, `a`.`advertiser_id` AS `advertiser_id`, `a`.`campaign_group_id` AS `campaign_group_id`, `a`.`campaign_id` AS `campaign_id`, `a`.`order_id` AS `order_id`, `a`.`cid` AS `cid`, `a`.`publisher_id` AS `publisher_id`, `a`.`region_id` AS `region_id`, `a`.`position_id` AS `position_id`, `a`.`channel_id` AS `channel_id`, `a`.`Buy_in_Model` AS `Buy_in_Model`, `a`.`app_name` AS `app_name`, `a`.`meid` AS `meid`, `a`.`mtype` AS `mtype`, `a`.`dmp_tag` AS `dmp_tag`, `a`.`dmp_ident` AS `dmp_ident`, `a`.`so` AS `so`, `a`.`ta` AS `ta`, `a`.`cms_ta` AS `cms_ta`, `a`.`afidip` AS `afidip`, `a`.`rtbscore` AS `rtbscore`, `a`.`tyscore` AS `tyscore`, `a`.`newrmid` AS `newrmid`, `a`.`r2m` AS `r2m`, `a`.`push` AS `push`, `a`.`sel` AS `sel`, `a`.`imp` AS `imp`, `a`.`imp_s` AS `imp_s`, `a`.`imp_m` AS `imp_m`, `a`.`imp_e` AS `imp_e`, `a`.`imp_v` AS `imp_v`, `a`.`click` AS `click`, `a`.`platform_id` AS `platform_id`, `a`.`dmp_id` AS `dmp_id`, `a`.`type` AS `type`, `a`.`fq` AS `fq`, `a`.`ip_info` AS `ip_info`, `a`.`err` AS `err`, split_part(`a`.`ip_info`, ',', 1) AS `country`, split_part(`a`.`ip_info`, ',', 2) AS `province`, split_part(`a`.`ip_info`, ',', 3) AS `city`, split_part(`a`.`ip_info`, ',', 4) AS `District`, get_json_string(`a`.`dmp_tag`, '$.d_m') AS `d_m`, get_json_string(`a`.`dmp_tag`, '$.d_a') AS `d_a`, get_json_string(`a`.`dmp_tag`, '$.d_t') AS `d_t`, get_json_string(`a`.`dmp_tag`, '$.d_b') AS `d_b`, get_json_string(`a`.`dmp_tag`, '$.d_td') AS `d_td`, get_json_string(`a`.`dmp_tag`, '$.d_gt') AS `d_gt`, get_json_string(`a`.`dmp_tag`, '$.d_gp') AS `d_gp`, get_json_string(`a`.`dmp_tag`, '$.d_i') AS `d_i`, get_json_string(`a`.`dmp_tag`, '$.d_yk') AS `d_yk`, get_json_string(`a`.`dmp_tag`, '$.d_rt') AS `d_rt`, get_json_string(`a`.`dmp_tag`, '$.d_pg') AS `d_pg`, get_json_string(`a`.`dmp_tag`, '$.d_rti') AS `d_rti`, get_json_string(`a`.`dmp_tag`, '$.d_rtc') AS `d_rtc`, get_json_string(`a`.`dmp_tag`, '$.d_mzup'



select a.campaign_id,campaign_name,e.name,b.product_name,case  when  1=1  then '全部人群'   end  as ta_filter,
case when array_contains([d_gz],'50102')=true then '8.4-美白精华-All Female'  end as dmp_tag,
case when array_contains([d_gz],'50102')=true then '50102'  end as tag_id,pure_date,sum(push) as pushPV,
124935 as parent_task_id,2022031707 as task_id  from v_rm_log_freq a 
join rmos_order b on a.campaign_id=b.campaign_id and a.order_id =b.order_id 
join rm_publisher e on a.publisher_id =e.publisher_id 
where a.campaign_id in (228763,228766,228769,228775,228778,228781,228840,228843,228846,228859,228862,228865,
228868,228872) and  pure_date >= (20220316) and  pure_date <= (20220316) and ( err is null or err =0 ) 
group by 1,2,3,4,5,6,7,8 ;

```

**Comment by mofeiatwork** [comment]
The direct cause is, the first parameter of `get_json_string` function should be `varchar`, but actually it's a `Int64Column`, so crashed.

![image](https://user-images.githubusercontent.com/96611012/161002631-73dcd44f-c683-4c52-b22d-5ee6944feaae.png)

**Comment by stdpain** [comment]
It seems a plan problems.
