### ISSUE TITLE
Support DROP USER [IF EXISTS]

### ISSUE THREAD

**Issue by zingdle** [StarRocks/starrocks#4524]
## Enhancement

Currently StarRocks [doesn't support](https://docs.starrocks.com/en-us/main/sql-reference/sql-statements/account-management/DROP%20USER) `IF EXISTS` option in `DROP USER` statement [like MySQL](https://dev.mysql.com/doc/refman/5.7/en/drop-user.html). It would be great to have this feature.

Silimar statements: `CREATE USER`, `CREATE ROLE`, `DROP ROLE`, etc.

**Comment by imay** [comment]
@zingdle Would you like to create a PR to finish this feature for StarRocks?

**Comment by zingdle** [comment]
@imay Yes I'd love to. I'm a little busy these days but I can work on this feature once I'm free.

**Comment by zingdle** [comment]
@imay I've submitted a PR and PTAL at your convenience :)
