### ISSUE TITLE
Support case-insensitive when select where

### ISSUE THREAD

**Issue by mzgs9988** [StarRocks/starrocks#45264]
## Enhancement
I'm using Realtime synchronization from MySQL，when i query with sql: select * from xxx where name like '%a%' on mysql，the result returned name with 'aAa',  case-insensitive，but when i query in starrocks，the result is empty, case-sensitive，how can i resolve this problem？Thank you !
starrocks version: 3.0

**Comment by xyan3880** [comment]
mysql uses collation/charset of the value/column for case sensitivity .

Unfortunately I don't think starrocks supports it now,  so you can try "ilike()" function, which is undocumented so far.

**Comment by durlabhjain** [comment]
Will this be handled or is it an official recommendation to use LOWER comparison? If yes, what's the performance impact of it? Any optimizations/ recommendations?

**Comment by tshiyuoo** [comment]
Also encountered the same issue. Will there be an implementation of an ILIKE-like operator in the future?
