### ISSUE TITLE
import json data with routine load can't success if json data contains unescaped character

### ISSUE THREAD

**Issue by kaijianding** [StarRocks/starrocks#45273]
### Steps to reproduce the behavior (Required)
1. CREATE routine load to ingest json data
2. unescaped character in json
![img_v3_02am_88bbf69b-9bcb-4347-8c0a-f0c9044049fg](https://github.com/StarRocks/starrocks/assets/8663725/78a20cd9-2315-4009-998e-3d606d5e0a68)

### Expected behavior (Required)
1. task success with this row skipped
2. `errorRows` increases

### Real behavior (Required)
routine load tasks failed repeatly:

`2024-05-08 09:24:04,644 WARN (thrift-server-pool-667203|857580) [RoutineLoadJob.executeTaskOnTxnStatusChanged():1048] routine load task [job name xxxx, task id 36869260-d0ce-4ebd-bec8-423d6d78e08f] aborted because of Failed to iterate document stream as object. error: Within strings, some characters must be escaped, we found unescaped characters, remove old task and generate new one`

### StarRocks version (Required)
 - 2.5.20

**Comment by rickif** [comment]
Thanks. I'll look into this issue.

**Comment by jaogoy** [comment]
We need to support auto escape in JSON string.
