### ISSUE TITLE
 when using "Cross-cluster Data Migration Tool" , not disable compaction may cause be crash

### ISSUE THREAD

**Issue by Jay-ju** [StarRocks/starrocks#45276]
### Steps to reproduce the behavior (Required)
if not set ADMIN SET FRONTEND CONFIG("lake_compaction_max_tasks"="0");  will cause be crash

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by xiangguangyxg** [comment]
It‘s required to disable compaction when migrating to a shared-data cluster now. We're also working on not having to disable    compaction in the future.
