### ISSUE TITLE
[Bug] Backup Restore failed to work on compute node only cluster

### ISSUE THREAD

**Issue by wxl24life** [StarRocks/starrocks#45323]
### Real behavior (Required)
[COMMON_ERROR, msg: failed to find 1 different hosts to create table: xxx]

### StarRocks version (Required)
 - 3.2.4、3.2.6

**Comment by ItielOlenick** [comment]
Ran into this just now. Shared data cluster, 3 CNs 3 FEs.
How did you solve the issue @wxl24life ?

**Comment by imbue11235** [comment]
I got the same error, because I did not specify `replication_num` property, when performing the `RESTORE`. It obviously has to match the amount of replicas you are working with, in my case `2`. The default is `3`.
