### ISSUE TITLE
SELECT split("1m_2d", '_')[0];Starrocks supports executing this sql, why not give an error instead of an error result??

### ISSUE THREAD

**Issue by luckylhb90** [StarRocks/starrocks#45433]
### Steps to reproduce the behavior (Required)
1. SELECT split("1m_2d", '_')[0];

### Expected behavior (Required)
I want to get an error or return a correct result like the other engines.

### Real behavior (Required)
return null....
<img width="349" alt="image" src="https://github.com/StarRocks/starrocks/assets/6822397/435d5419-2978-431d-acc6-b1ab4dfaf3e7">

### StarRocks version (Required)
 - 2.5.20 74821e9

**Comment by kangkaisen** [comment]
We will check and fix it, Thanks

**Comment by before-Sunrise** [comment]
you can check https://docs.starrocks.io/docs/sql-reference/data-types/semi_structured/Array/#query-array-data, our array index begin from 1 instead of 0, and return NULL if index is invalid @luckylhb90

**Comment by luckylhb90** [comment]
> you can check https://docs.starrocks.io/docs/sql-reference/data-types/semi_structured/Array/#query-array-data, our array index begin from 1 instead of 0, and return NULL if index is invalid @luckylhb90

Why did you design it that way? Other engine indexes start at 0, so why do you have to do something special here?
If the index is invalid, should you give an error?
