### ISSUE TITLE
The http api for query tablet metadata is wrong

### ISSUE THREAD

**Issue by liuqian1990** [StarRocks/starrocks#455]
### Steps to reproduce the behavior (Required)
1. 通过api 接口 查询 /api/meta/header/182500/172828978，得到shard_id 757

{
    "table_id": 179362,
    "partition_id": 179330,
    "tablet_id": 182500,
    "schema_hash": 1728289786,
    "shard_id": 757,
    "creation_time": 1631699334,
    "cumulative_layer_point": -1,

2. The normal path pattern is like "/data/{shard_id}/{tablet_id}/{schema_hash}/xxx.data".
正常目录应该是tablet_id是 /data1/StarRocks-1.18.2/be/storage/data/757/182500/1728289786
可实际目录为 /data1/StarRocks-1.18.2/be/storage/data/999/182500/1728289786

**Comment by imay** [comment]
Could you fix it for StarRocks?
