### ISSUE TITLE
Hive external table queries the type of array < date > and the result is incorrect

### ISSUE THREAD

**Issue by huoyue-git** [StarRocks/starrocks#4557]
### Steps to reproduce the behavior (Required)
1. In hive environment
 create table hive_hdfs_array_orc1(
    col_int int comment "column int"
,col_array_date array<date> comment "column array<date>"
)
    clustered by(col_int) sorted by(col_int) into 32 buckets
    row format delimited fields terminated by ","
    stored as orc
    tblproperties("orc.compress"="none");
insert into hive_hdfs_array_orc1 select 1 ,array(cast('9999-12-31' as date), cast('0000-01-01' as date), null);
 create table hive_hdfs_array_orc2(
    col_int int comment "column int"
,col_array_datetime array<timestamp> comment "column array<timestamp>"
)
    clustered by(col_int) sorted by(col_int) into 32 buckets
    row format delimited fields terminated by ","
    stored as orc
    tblproperties("orc.compress"="none");

insert into hive_hdfs_array_orc2 select 1 ,array(cast('9999-12-31 23:59:59' as timestamp), cast('0000-01-01 00:00:00' as timestamp), null);
2.In Starrocks environment
create external resource hive_resource_hy PROPERTIES ("type" = "hive", "hive.metastore.uris" = "thrift://172.26.92.141:9083");
create external table ex_hive_tbl_array_orc1 (
    col_int int comment "column int"
    ,col_array_date array<date> comment "column array<date>"
        )
                ENGINE=hive
                properties (
                    "resource" = "hive_resource_hy",
                    "table" = "hive_hdfs_array_orc1",
                    "database" = "hive_test_hy") ;
create external table ex_hive_tbl_array_orc2 (
    col_int int comment "column int"
    ,col_array_datetime array<datetime> comment "column array<datetime>"
        )
                ENGINE=hive
                properties (
                    "resource" = "hive_resource_hy",
                    "table" = "hive_hdfs_array_orc2",
                    "database" = "hive_test_hy") ;

3. 
select * from ex_hive_tbl_array_orc1;
select * from ex_hive_tbl_array_orc2;

### Expected behavior (Required)
mysql> select * from ex_hive_tbl_array_orc1;
+---------+----------------------------------+
| col_int | col_array_date                   |
+---------+----------------------------------+
|       1 | ["9999-12-31","0001-01-01",null]  |
+---------+----------------------------------+
1 row in set (2.78 sec)

mysql> select * from ex_hive_tbl_array_orc2;
+---------+----------------------------------------------------+
| col_int | col_array_datetime                                 |
+---------+----------------------------------------------------+
|       1 | ["9999-12-31 23:59:59","0001-01-01 00:00:00",null]  |
+---------+----------------------------------------------------+
### Real behavior (Required)
mysql> select * from ex_hive_tbl_array_orc1;
+---------+----------------------------------+
| col_int | col_array_date                   |
+---------+----------------------------------+
|       1 | ["9999-12-31","00�5-12-30",null]  |
+---------+----------------------------------+
1 row in set (2.78 sec)

mysql> select * from ex_hive_tbl_array_orc2;
+---------+----------------------------------------------------+
| col_int | col_array_datetime                                 |
+---------+----------------------------------------------------+
|       1 | ["9999-12-31 23:59:59","00�5-12-30 00:05:43",null]  |
+---------+----------------------------------------------------+
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+------------------------+
| current_version()      |
+------------------------+
| QA_TEST_MASTER f6f6228 |
+------------------------+
1 row in set (0.01 sec)

**Comment by DorianZheng** [comment]
only oss + orc/csv will cause problem

**Comment by dirtysalt** [comment]
It's because we are using a simple and straight way to convert days(since unix epoch time) -> date. This way is very efficient to handle wide range of date, but except for dates are quite old enough.

```
// orc date value is days since unix epoch time.
// so conversion will be very simple.
static inline void orc_date_to_native_date(DateValue* dv, int64_t value) {
    dv->_julian = value + date::UNIX_EPOCH_JULIAN;
}
static inline void orc_date_to_native_date(JulianDate* jd, int64_t value) {
    *jd = value + date::UNIX_EPOCH_JULIAN;
}
static inline int64_t native_date_to_orc_date(const DateValue& dv) {
    return dv._julian - date::UNIX_EPOCH_JULIAN;
}
static inline int64_t native_date_to_orc_date(const JulianDate& jd) {
    return jd - date::UNIX_EPOCH_JULIAN;
}
```

I've tested that current way is correct enough to handle back to `0300-01-01`. I think it's okay to have this tradeoff.
