### ISSUE TITLE
support order by clause in show data statement.

### ISSUE THREAD

**Issue by immutablecodes** [StarRocks/starrocks#45676]
## Feature request

**Is your feature request related to a problem? Please describe.**

I ususally have to find the biggest disk usage table in my work, this information usually can be found in show data statement, but the data type of 'size' field in the esult schema is formatted to human readable string, make it difficult to sort.

**Describe the solution you'd like**

1. change the data type of 'size' field in the esult schema from string to bigint.
2. support order by clause in show data statement. 

**Describe alternatives you've considered**

**Additional context**

**Comment by wangsimo0** [comment]
good catch. for your scenario, maybe information_schema.tables will be easier to use.

**Comment by immutablecodes** [comment]
> good catch. for your scenario, maybe information_schema.tables will be easier to use.

good point, but I can't found full information, can you show me how to construct the corresponding SQL? including with and without table to the show data statement.
