### ISSUE TITLE
[Feature Request] Increase scan size limit for large queries

### ISSUE THREAD

**Issue by yuanzhangjun** [StarRocks/starrocks#45729]
## Feature request
At present, there are three major query limitations for SR, but none of them fully meet our limitation requirements. We hope to limit them based on the size of the scan volume (scanbytes), which is more effective than scanning the number of rows.

##at present
big_query_cpu_second_limit
big_query_scan_rows_limit
big_query_mem_limit

##Describe the solution you'd like
add big_query_scan_bytes_limit ?

**Comment by Dshadowzh** [comment]
Thx for you advice. Both big_query_scan_rows_limit and big_query_scan_bytes_limit are an estimation for big query, Can you tell how do you choose big_query_scan_bytes_limit rather than big_query_scan_rows_limit?

**Comment by yuanzhangjun** [comment]
> Thx for you advice. Both big_query_scan_rows_limit and big_query_scan_bytes_limit are an estimation for big query, Can you tell how do you choose big_query_scan_bytes_limit rather than big_query_scan_rows_limit?

For column storage, when I scan a large number of rows with few fields, the required resources are not significant, for example: select count (1) from t. If it is big_query_scan_rows_limit, then this SQL will be restricted. Therefore, I hope to adjust large queries based on scan size.
