### ISSUE TITLE
Load to olap external table causes be crash.

### ISSUE THREAD

**Issue by gengjun-git** [StarRocks/starrocks#4573]
### Steps to reproduce the behavior (Required)
1. CREATE EXTERNAL OLAP Table and the host is non-master fe' host.
2. load to the external table.

### Expected behavior (Required)
load successfully.

### Real behavior (Required)
be crashed with FATAL log:
F0328 10:26:50.170414  8962 txn_manager.cpp:158] invalid commit req  partition_id=991573 transaction_id=0 tablet_id=992498

### StarRocks version (Required)
 - 2.0.3

**Comment by gengjun-git** [comment]
The reason is : calling the non-master fe's beginRemoteTxn rpc will fail, but the caller ignored the error and returns the txn id of 0.

**Comment by jaogoy** [comment]
Does the FE crash or the BE crash?
From the comment, I think it's the non-master FE who crashes.

**Comment by gengjun-git** [comment]
BE crash
