### ISSUE TITLE
BE crash when load data with stream load  in shared data

### ISSUE THREAD

**Issue by smartlxh** [StarRocks/starrocks#45879]
![image](https://github.com/StarRocks/starrocks/assets/13373748/1f3ea010-c6a9-44b0-9bb4-23ec5b1dff1d)

be crash
![image](https://github.com/StarRocks/starrocks/assets/13373748/5ae5eacc-ca50-49d0-8927-37c65e84bf39)

### Steps to reproduce the behavior (Required)
1. generate data 1T with tpcds
2. bin/stream_load.sh 
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by mlbzssk** [comment]
the crash node is be or cn？
