### ISSUE TITLE
query error when create external table like

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#4602]
### Steps to reproduce the behavior (Required)
create hudi external table like hudi external table error:
```
mysql> create external table hudi_crt_like_1 like ex_hudi_tbl8;
ERROR 1064 (HY000): Failed to execute CREATE TABLE LIKE ex_hudi_tbl8. Reason: Please set properties of hudi table.
```

### Expected behavior (Required)
create external table like execute successfully

### Real behavior (Required)
error
iceberg external table also has the problem

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+------------------------+
| current_version()      |
+------------------------+
| QA_TEST_MASTER f6f6228 |
+------------------------+
1 row in set (0.01 sec)
```

**Comment by miomiocat** [comment]
i will fix it
