### ISSUE TITLE
SQL指纹功能，嵌套语句的参数无法过滤，归类为相同语句

### ISSUE THREAD

**Issue by linjiuqiu** [StarRocks/starrocks#4606]
### 嵌套测试语句如下,修改了嵌套语句的时间参数:
1.`SELECT MAX(RN) AS RES   FROM (     SELECT COLUMN47,COLUMN19,COLUMN181,COLUMN252,COLUMN649,COLUMN599,COLUMN602, ROW_NUMBER() OVER(PARTITION BY COLUMN649,COLUMN47,COLUMN751 ORDER BY COLUMN602                 DESC NULLS LAST,COLUMN599 DESC NULLS LAST, COLUMN252 ASC) RN           FROM TABLE33           WHERE COLUMN751 BETWEEN DATE'2020-01-01' AND DATE'2020-12-31') Z；`

2.`SELECT MAX(RN) AS RES   FROM (     SELECT COLUMN47,COLUMN19,COLUMN181,COLUMN252,COLUMN649,COLUMN599,COLUMN602, ROW_NUMBER() OVER(PARTITION BY COLUMN649,COLUMN47,COLUMN751 ORDER BY COLUMN602                 DESC NULLS LAST,COLUMN599 DESC NULLS LAST, COLUMN252 ASC) RN           FROM TABLE33           WHERE COLUMN751 BETWEEN DATE'2020-10-01' AND DATE'2020-12-31') Z`
![4f100a5f6707f93b3045687fc7648b3](https://user-images.githubusercontent.com/67308950/160791938-3643acde-9c7d-439c-85c9-2d2958dd3e80.png)
识别出的指纹为两个

### 简单的测试语句如下:
1.`select * from  StaticData where  siteid = 2`
2.`select * from  StaticData where  siteid = 1006`
![image](https://user-images.githubusercontent.com/67308950/160793008-c7280719-8ee5-4e7c-af15-90ea35231f9e.png)
是可以识别为相同指纹

### StarRocks version (Required)
 - 版本为 2.1.2

**Comment by Dshadowzh** [comment]
@kangkaisen  PTAL

**Comment by kangkaisen** [comment]
```
WHERE CN DATE'2020-01-01' AND DATE'2020-12-31') Z

WHERE COLUATE'2020-10-01' AND DATE'2020-12-31')
```

CN isn’t same with COLUATE

**Comment by linjiuqiu** [comment]
> ```
> WHERE CN DATE'2020-01-01' AND DATE'2020-12-31') Z
> 
> WHERE COLUATE'2020-10-01' AND DATE'2020-12-31')
> ```
> 
> CN isn’t same with COLUATE

sorry，there is some misstake, I fixed it
![image](https://user-images.githubusercontent.com/67308950/160965289-8bae0582-4fe4-4bad-8978-0f486089df02.png)
they are same in the logs

![image](https://user-images.githubusercontent.com/67308950/160964794-40f0bd25-2b89-4568-93ab-e991265d6f11.png)

**Comment by kangkaisen** [comment]
OK，we will fix it
