### ISSUE TITLE
内存溢出，无法恢复

### ISSUE THREAD

**Issue by isMrH** [StarRocks/starrocks#46066]
### 过程
1.  创建主键表
 ``` 
CREATE TABLE ods_pd_eps.`chtrade_hs2017_data2_20240521` (
  `indicator_code` varchar(20) NOT NULL COMMENT "",
  `commodity_code` varchar(20) NOT NULL COMMENT "",
  `region_code` varchar(20) NOT NULL COMMENT "",
  `country_code` varchar(20) NOT NULL COMMENT "",
  `tradeway_code` varchar(20) NOT NULL COMMENT "",
  `classify_code` varchar(20) NOT NULL COMMENT "",
  `time_code` varchar(20) NOT NULL COMMENT "",
  `val` decimal128(38, 5) NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY  KEY(`indicator_code`, `commodity_code`, `region_code`, `country_code`, `tradeway_code`, `classify_code`, `time_code`)
COMMENT ""
DISTRIBUTED BY HASH(`indicator_code`, `time_code`)
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
);
```
2. load 数据 
```
LOAD LABEL CHTRADE_HS2017_DATA2
(
    DATA INFILE("s3a://starrocks/CHTRADE_HS2017_DATA2_2023.TXT")
    INTO TABLE chtrade_hs2017_data2
    COLUMNS TERMINATED BY ","    
    FORMAT AS "csv"
    (
        skip_header = 0
        trim_space = TRUE
        enclose = "\""
        escape = "\\"
    )(indicator_code,commodity_code,region_code,country_code,tradeway_code,classify_code,time_code,val)
)
WITH BROKER
(
    "aws.s3.access_key" = "***",
    "aws.s3.secret_key" = "***",
    "aws.s3.endpoint" = "http://192***"
);
```
3. 数据量大约三四十亿，load过程中OOM，后续be重新启动后，不做任何操作，内存持续增长，直到OOM。
4. 调整BE内存 mem_limit配置，无效。
![image-20240522092930164](https://github.com/StarRocks/starrocks/assets/37281700/d5f79daa-182e-4167-bc36-f451a2dcf535)

![image-20240522144907449](https://github.com/StarRocks/starrocks/assets/37281700/30438c47-3071-447b-9d18-19eb2b3ce473)
![a6aff671527a2649741eddf69cbc6d4](https://github.com/StarRocks/starrocks/assets/37281700/69c1f8db-6b98-4f3b-a3e4-ff628c1bbdd4)
![ad8baaa07431bfd959f2460fc4f5dd0](https://github.com/StarRocks/starrocks/assets/37281700/dced71b3-acc9-4585-a865-17f80eb3eafc)
![08c8fd15d9c1db15ea337b1d1b44c54](https://github.com/StarRocks/starrocks/assets/37281700/3abb970a-fecf-4acc-a6be-3674edcbab67)

### StarRocks version (Required)
 - 3.2.6

**Comment by isMrH** [comment]
[fe.log.txt](https://github.com/StarRocks/starrocks/files/15410736/fe.log.txt)
[be.INFO.txt](https://github.com/StarRocks/starrocks/files/15410737/be.INFO.txt)

**Comment by luohaha** [comment]
@isMrH Hi, 这可能是一个已知问题，你们可以升级最新的3.2.7版本，然后在be.conf里加上
```
enable_light_pk_compaction_publish = true
```
来解决这个问题。需要重新建表导入数据。

**Comment by luohaha** [comment]
@isMrH `enable_persistent_index` 需要设置为true，启用持久化索引。
