### ISSUE TITLE
[BE][BUILD]Failed at compiling formats/orc/apache-orc

### ISSUE THREAD

**Issue by 1153710405** [StarRocks/starrocks#46070]
Failed at compiling formats/orc/apache-orc at my arm64 build testing. The error message seems to be not related to my patch.

### Steps to reproduce the behavior (Required)
OS: openeuler 20.03LTS-SP3
gcc:10.3.0
cmake:3.20.1
python 3.7.9
./build.sh

### Expected behavior 
Build success
### Real behavior (Required)
++++ <STARROCKS_HOME> is set. formats/orc/apache-orc is compiled in StarRocks env ++++
-- Build type: RELEASE
-- compiler GNU version 10.3.0
-- SNAPPY_HOME: /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed
-- Found the Snappy header: /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/include/snappy.h
-- Found the Snappy library: /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/lib64/libsnappy.a
-- ZLIB_HOME: /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed
-- Found the ZLIB header: /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/include/zlib.h
-- Found the ZLIB library: /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/lib/libz.a
-- Found the ZLIB static library: /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/lib/libz.a
-- ZSTD_HOME: /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed
-- Found the zstd header: /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/include/zstd/zstd.h
-- Found the zstd library: /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/lib
-- Found the zstd static library: /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/lib64/libzstd.a
-- LZ4_HOME: /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed
-- Found the LZ4 header: /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/include/lz4/lz4.h
-- Found the LZ4 library: /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/lib
-- PROTOBUF_HOME: /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed
-- Found the Protobuf headers: /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/include
-- Found the Protobuf library: /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/lib/libprotobuf.a
-- Found the Protoc library: /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/lib/libprotoc.a
-- Found the Protoc executable: /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/bin/protoc
-- Found the Protobuf static library: /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/lib/libprotobuf.a
-- Found the Protoc static library: /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/lib/libprotoc.a
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hqs/starrocks-arm_neon-adaptation-patch/be/build_Release
[2/1110] Building CXX object src/formats/orc/apache-orc/c++/src/CMakeFiles/orc.dir/Adaptor.cc.o
FAILED: src/formats/orc/apache-orc/c++/src/CMakeFiles/orc.dir/Adaptor.cc.o 
/usr/local/gcc/bin/../bin/g++ -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -DUSE_AVX2KI -Isrc/formats/orc/apache-orc/c++/src -I../src/formats/orc/apache-orc/c++/src -I../src/formats/orc/apache-orc/c++/include -Isrc/formats/orc/apache-orc/c++/include -I../src -I../test -I../../gensrc/build -I/home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/open_jdk/include -I/home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/open_jdk/include/linux -I/home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed -I/home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/include/zstd -I/home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/include/lz4 -isystem /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/include -isystem /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/starcache/include -isystem /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/gperftools/include -isystem /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/jemalloc/include -isystem /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/include/thrift -isystem /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/include/event -isystem /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed/llvm/include -Wall -Wno-sign-compare -Wno-unknown-pragmas -pthread -Wno-register -Wno-strict-aliasing -fno-omit-frame-pointer -std=gnu++20 -D__STDC_FORMAT_MACROS -Wno-deprecated -Wno-vla -Wno-comment -fno-sized-deallocation -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX -Werror=return-type -Werror=switch -DWITH_STARCACHE -march=armv8-a+crc -I /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed//ksl/include -L /home/hqs/starrocks-arm_neon-adaptation-patch/thirdparty/installed//ksl/lib -lavx2ki  -Wno-attributes -DS2_USE_GFLAGS -DS2_USE_GLOG -faligned-new  -Werror -fcoroutines -g -Wno-unused-local-typedefs -O3 -gdwarf-4 -DNDEBUG  -Wall -Wno-unknown-pragmas -Wno-conversion -Werror  -Wall -Wno-unknown-pragmas -Wno-conversion -Werror -O3 -DNDEBUG -fPIC -std=gnu++2a -MD -MT src/formats/orc/apache-orc/c++/src/CMakeFiles/orc.dir/Adaptor.cc.o -MF src/formats/orc/apache-orc/c++/src/CMakeFiles/orc.dir/Adaptor.cc.o.d -o src/formats/orc/apache-orc/c++/src/CMakeFiles/orc.dir/Adaptor.cc.o -c ../src/formats/orc/apache-orc/c++/src/Adaptor.cc
In file included from ../src/formats/orc/apache-orc/c++/src/Adaptor.cc:19:
src/formats/orc/apache-orc/c++/src/Adaptor.hh:134:11: error: ISO C++11 requires whitespace after the macro name [-Werror]
  134 |   #define std::isnan(XXX) isnan(XXX)
      |           ^~~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:162:11: error: ISO C++11 requires whitespace after the macro name [-Werror]
  162 |   #define std::mutex pthread_mutex_t
      |           ^~~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:162: error: "std" redefined [-Werror]
  162 |   #define std::mutex pthread_mutex_t
      | 
src/formats/orc/apache-orc/c++/src/Adaptor.hh:134: note: this is the location of the previous definition
  134 |   #define std::isnan(XXX) isnan(XXX)
      | 
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:11: error: ISO C++11 requires whitespace after the macro name [-Werror]
  163 |   #define std::lock_guard<std::mutex> LockORC
      |           ^~~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163: error: "std" redefined [-Werror]
  163 |   #define std::lock_guard<std::mutex> LockORC
      | 
src/formats/orc/apache-orc/c++/src/Adaptor.hh:162: note: this is the location of the previous definition
  162 |   #define std::mutex pthread_mutex_t
      | 
../src/formats/orc/apache-orc/c++/src/Adaptor.cc:64:2: error: #error ("pread() undefined: unknown environment")
   64 | #error("pread() undefined: unknown environment")
      |  ^~~~~
In file included from ../src/formats/orc/apache-orc/c++/src/Adaptor.cc:19:
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:16: error: ‘lock_guard’ in namespace ‘::’ does not name a template type
  163 |   #define std::lock_guard<std::mutex> LockORC
      |                ^~~~~~~~~~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:173:3: note: in expansion of macro ‘std’
  173 |   std::string to_string(double val);
      |   ^~~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:16: error: ‘lock_guard’ in namespace ‘::’ does not name a template type
  163 |   #define std::lock_guard<std::mutex> LockORC
      |                ^~~~~~~~~~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:174:3: note: in expansion of macro ‘std’
  174 |   std::string to_string(int64_t val);
      |   ^~~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:14: error: expected identifier before ‘::’ token
  163 |   #define std::lock_guard<std::mutex> LockORC
      |              ^~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:16: error: ‘lock_guard’ in namespace ‘::’ does not name a template type
  163 |   #define std::lock_guard<std::mutex> LockORC
      |                ^~~~~~~~~~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:14: error: expected identifier before ‘::’ token
  163 |   #define std::lock_guard<std::mutex> LockORC
      |              ^~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:16: error: ‘lock_guard’ in namespace ‘::’ does not name a template type
  163 |   #define std::lock_guard<std::mutex> LockORC
      |                ^~~~~~~~~~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:14: error: expected identifier before ‘::’ token
  163 |   #define std::lock_guard<std::mutex> LockORC
      |              ^~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:16: error: ‘lock_guard’ in namespace ‘::’ does not name a template type
  163 |   #define std::lock_guard<std::mutex> LockORC
      |                ^~~~~~~~~~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:14: error: expected identifier before ‘::’ token
  163 |   #define std::lock_guard<std::mutex> LockORC
      |              ^~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:16: error: ‘lock_guard’ in namespace ‘::’ does not name a template type
  163 |   #define std::lock_guard<std::mutex> LockORC
      |                ^~~~~~~~~~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:14: error: expected identifier before ‘::’ token
  163 |   #define std::lock_guard<std::mutex> LockORC
      |              ^~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:16: error: ‘lock_guard’ in namespace ‘::’ does not name a template type
  163 |   #define std::lock_guard<std::mutex> LockORC
      |                ^~~~~~~~~~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:14: error: expected identifier before ‘::’ token
  163 |   #define std::lock_guard<std::mutex> LockORC
      |              ^~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:16: error: ‘lock_guard’ in namespace ‘::’ does not name a template type
  163 |   #define std::lock_guard<std::mutex> LockORC
      |                ^~~~~~~~~~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:14: error: expected identifier before ‘::’ token
  163 |   #define std::lock_guard<std::mutex> LockORC
      |              ^~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:16: error: ‘lock_guard’ in namespace ‘::’ does not name a template type
  163 |   #define std::lock_guard<std::mutex> LockORC
      |                ^~~~~~~~~~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:14: error: expected identifier before ‘::’ token
  163 |   #define std::lock_guard<std::mutex> LockORC
      |              ^~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:16: error: ‘lock_guard’ in namespace ‘::’ does not name a template type
  163 |   #define std::lock_guard<std::mutex> LockORC
      |                ^~~~~~~~~~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:14: error: expected identifier before ‘::’ token
  163 |   #define std::lock_guard<std::mutex> LockORC
      |              ^~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:16: error: ‘lock_guard’ in namespace ‘::’ does not name a template type
  163 |   #define std::lock_guard<std::mutex> LockORC
      |                ^~~~~~~~~~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:14: error: expected identifier before ‘::’ token
  163 |   #define std::lock_guard<std::mutex> LockORC
      |              ^~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:16: error: ‘lock_guard’ in namespace ‘::’ does not name a template type
  163 |   #define std::lock_guard<std::mutex> LockORC
      |                ^~~~~~~~~~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:14: error: expected identifier before ‘::’ token
  163 |   #define std::lock_guard<std::mutex> LockORC
      |              ^~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:16: error: ‘lock_guard’ in namespace ‘::’ does not name a template type
  163 |   #define std::lock_guard<std::mutex> LockORC
      |                ^~~~~~~~~~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:14: error: expected identifier before ‘::’ token
  163 |   #define std::lock_guard<std::mutex> LockORC
      |              ^~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:16: error: ‘lock_guard’ in namespace ‘::’ does not name a template type
  163 |   #define std::lock_guard<std::mutex> LockORC
      |                ^~~~~~~~~~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:14: error: expected identifier before ‘::’ token
  163 |   #define std::lock_guard<std::mutex> LockORC
      |              ^~
src/formats/orc/apache-orc/c++/src/Adaptor.hh:163:16: error: ‘lock_guard’ in namespace ‘::’ does not name a template type
  163 |   #define std::lock_guard<std::mutex> LockORC
      |                ^~~~~~~~~~

### StarRocks version (Required)
arm_neon-adaptation-patch

**Comment by kevincai** [comment]
it is related to your patch. cmake in https://github.com/StarRocks/starrocks/blob/main/be/src/formats/orc/apache-orc/c%2B%2B/src/CMakeLists.txt will do a simple compiling to check if the libstdc++ has the standard stl headers such as mutex, thread.

your change breaks the link, causes the cmake think these stl libraries are not available.
