### ISSUE TITLE
Support for ARM NEON

### ISSUE THREAD

**Issue by robd003** [StarRocks/starrocks#46174]
## Feature request

**Is your feature request related to a problem? Please describe.**
I'd rather use AWS Graviton3 / Graviton4 instances than x86_64 instances because it's a more efficient use of capital. (You save 30% - 40% and have the same, if not better, level of performance)

**Describe the solution you'd like**
Support ARM NEON optimization extensions

**Describe alternatives you've considered**
Look into using [SIMDe](https://github.com/simd-everywhere/simde) to help port avx2 instructions to ARM NEON

**Additional context**
Not being tied to a single processor architecture would be a good idea in general.

**Comment by imay** [comment]
@robd003 we have done some optimization for the AWS graviton chip. You can try version 3.2.7 and 3.3.0 to experience it. According to our newest test, the performance can be the same as X86 chip.
