### ISSUE TITLE
Support for funnel functions

### ISSUE THREAD

**Issue by JasonDung** [StarRocks/starrocks#4639]
Funnel analysis scenario needs to use funnel function, currently can only use left Join to complete, such performance is very slow, can you provide a function similar to the following link?

https://github.com/ClickHouse/ClickHouse/blob/21.8/src/AggregateFunctions/AggregateFunctionWindowFunnel.h

**Comment by Dshadowzh** [comment]
Thanks, we'll add this feature soon.

**Comment by JasonDung** [comment]
Thank you very much and look forward to the implementation of this feature :)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "StarRocks/starrocks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月31日(星期四) 晚上6:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [StarRocks/starrocks] Support for funnel functions (Issue #4639)





 
Thanks, we'll add this feature soon.

**Comment by Dshadowzh** [comment]
This feature has finished. We'll release it in v2.3
