### ISSUE TITLE
After the first refresh of hive external partition table, there is no data in the query, and there is data in the second query

### ISSUE THREAD

**Issue by zhaizhenhua** [StarRocks/starrocks#4640]
## General Question

A hive external table is created in starrocks. After the partition data of hive table is updated, the partition corresponding to the external table is refreshed, and the refresh has prompted success. There is no data in the partition corresponding to the external table queried for the first time. Data can be queried the second time. What are the possible reasons for this situation?

**Comment by stephen-shelby** [comment]
@zhaizhenhua hi, before you update the hive partition, do you have any data in the partition?

**Comment by zhaizhenhua** [comment]
the partition don't have any data.

**Comment by stephen-shelby** [comment]
you means that only an empty partition was added on the hive side?

**Comment by stephen-shelby** [comment]
There are two more questions: Did you specify a partition when executing refresh? In addition, when refresh this partition, have you performed other queries on this table?

**Comment by zhaizhenhua** [comment]
1、 Hive table partition data updated in the past 30 days, including yesterday.

2、Refresh all 30 partitions in starRocks.

3、After the refresh is complete, do not query the external table and import the data directly into the starRocks internal table. No data can be queried in the starRocks internal table.

4, if the external table first query, then import data from the external table into the internal table, the internal table can query data.

**Comment by stephen-shelby** [comment]
Could you reproduce this case? 
I mainly want to know how long it has not been queried before you execute the query, mainly to see if there is a cache.

**Comment by zhaizhenhua** [comment]
This situation has always existed and is not accidental. Our previous scheme was to refresh the metadata of the external table, and then insert it into the internal table of starrocks immediately. There was no error but no data. Now our solution is to refresh the metadata of the external table, query it again, and then insert it into the internal table of starrocks. The problem is solved. I'm not sure whether there will be some delay in refreshing the metadata of the external table.

Another example is that we used the hive external table directly to use the data in hive. Every time the hive table data is updated, we will refresh the metadata, but it often happens that starrocks cannot access the hive external table partition. Finally, it has to be changed to internal table.

**Comment by stephen-shelby** [comment]
If you just add an new partition in hive, you could execute 'refresh external table table_name' without partition.
If your partition data in hive is updated, you could execute 'refresh external table table_name partition(XXX)'
and our automatic incremental synchronization cache feature will release at branch-2.2, you may try to use it. thks

**Comment by stephen-shelby** [comment]
If you still have some questions, you can join our community wechat group and we could have some in-depth discussions.
