### ISSUE TITLE
[Enhancement] simplify JAVA_OPTS in `start_fe.sh`

### ISSUE THREAD

**Issue by mingmxu** [StarRocks/starrocks#46481]
## Enhancement

The existing logic is complex to decide which JAVA_OPS configuration is used eventually, see the code [here](https://github.com/StarRocks/starrocks/blob/522c03c6016d9fecc5b45f15f29d88a29df15463/bin/start_fe.sh#L111-L131). It would be better to simply it as below:
* if `JAVA_OPTS` is provided, use it;
* if not, use the default defined [here](https://github.com/StarRocks/starrocks/blob/522c03c6016d9fecc5b45f15f29d88a29df15463/bin/start_fe.sh#L127C7-L127C24), --It can be moved to fe configuration for attention; 

cc @dengliu @chaoyli @kevincai

**Comment by kevincai** [comment]
the complication is introduced by the compatibility consideration if the user is upgraded from an old jdk version and then upgrade to the new one.

Ideally, if the user only provides JAVA_OPTS, it will be used as the final one, and if no JAVA_OPTS provided, the default one will be used.

**Comment by dengliu** [comment]
There are currently three places where JAVA_OPTS can be configured, which is confusing and increases the risk of mistakes. 
According to our research, even when it is Java 11 environment, we need to config `JAVA_OPTS_FOR_JDK_9` cc @mingmxu  

Can we refactor the Helm chart to consolidate JAVA_OPTS into a single location in the values.yaml file?

![image](https://github.com/StarRocks/starrocks/assets/5108773/3bedcbd1-cf83-41ba-96e0-57bf3bca1329)

https://github.com/StarRocks/starrocks-kubernetes-operator/blob/main/helm-charts/charts/kube-starrocks/values.yaml#L374-L376

**Comment by kevincai** [comment]
no. you can just clean all of the JAVA_OPTS_FOR_JDK9/JAVA_OPTS_FOR_JDK_11 all over the places and just keep the JAVA_OPTS in one place, that will take effect.

**Comment by dengliu** [comment]
@kevincai Doesn't it make sense to remove `JAVA_OPTS_FOR_JDK_9` and `JAVA_OPTS_FOR_JDK_11` from the default base values.yaml file?
They are misleading.

**Comment by kevincai** [comment]
> @kevincai Doesn't it make sense to remove `JAVA_OPTS_FOR_JDK_9` and `JAVA_OPTS_FOR_JDK_11` from the default base values.yaml file? They are misleading.

ah, you are talking about the `values.yaml` for the helm chart installation. Yes, both can be removed from the default values.yaml

@yandongxiao

**Comment by kevincai** [comment]
close this issue, as the PR merged in the operator repo.
