### ISSUE TITLE
[Doc] create analyze permission

### ISSUE THREAD

**Issue by eshishki** [StarRocks/starrocks#46519]
Please document privileges required to issue _create analyze_ statements.

**Comment by DorianZheng** [comment]
https://docs.starrocks.io/docs/using_starrocks/Cost_based_optimizer/#customize-an-automatic-collection-task
> You must have the INSERT and SELECT privileges on the coreesponding table to perform the ANALYZE TABLE operation.

Hey @eshishki. I think this is the required privileges. I will close this issue and feel free to re-open it if you find any exception
