### ISSUE TITLE
[BUG, DOC]  Written property, but it's FE property.

### ISSUE THREAD

**Issue by amirjonr** [StarRocks/starrocks#46586]
### Steps to reproduce the behavior (Required)
in docs: https://github.com/StarRocks/starrocks/blob/main/docs/en/using_starrocks/Cost_based_optimizer.md#automatic-collection-1
When I try create analyze table tb_name(clmn) PROPERTIES ("statistic_collect_interval_sec" = "84600") i got invalid property statistic_collect_interval_sec error;

However, data changes in Hudi tables cannot be perceived and StarRocks periodically collects statistics based on the check interval and collection interval you specified. You can specify the following properties when you create an Analyze job:

    statistic_collect_interval_sec

### Expected behavior (Required)
However, data changes in Hudi tables cannot be perceived and StarRocks periodically collects statistics based on the check interval and collection interval you specified. You can specify the following FE properties when you create an Analyze job:

    statistic_collect_interval_sec

### Real behavior (Required)
However, data changes in Hudi tables cannot be perceived and StarRocks periodically collects statistics based on the check interval and collection interval you specified. You can specify the following properties when you create an Analyze job:

    statistic_collect_interval_sec
### StarRocks version (Required)
 - Latest 3.2

**Comment by Dshadowzh** [comment]
Thanks for reporting, we'll fix it
