### ISSUE TITLE
[Feature] Support Common Restful Catalog Not Limit to Tabular

### ISSUE THREAD

**Issue by lianneli** [StarRocks/starrocks#46697]
## Feature request

**Is your feature request related to a problem? Please describe.**
We try to use a common catalog project in share_data mode instead of HMS. I found many open source projects now support restful catalog, however, StarRocks not. 

**Describe the solution you'd like**
As documents said, the restful Api is only for Tabular, Could you make it more common that we can try other project? Or Support Customize Catalog Plugin?

**Describe alternatives you've considered**

**Additional context**

**Comment by zhaohehuhu** [comment]
I believe custom restful catalog should be supported. Is there a plan for it? I want be part of contributors for this feature.

**Comment by derekperkins** [comment]
While the docs use Tabular as a reference, I don't think there's anything that prevents you from using whatever REST catalog implementation you want. You can configure the url, credentials, etc.

<img width="1006" alt="image" src="https://github.com/StarRocks/starrocks/assets/3588778/60d49c47-b134-4dfd-a65b-de42c11001ea">


https://docs.starrocks.io/docs/3.3/data_source/catalog/iceberg_catalog/#tabular
