### ISSUE TITLE
Couldn't create class loader com.starrocks.udf.UDFClassLoader,java.lang.ExceptionInInitializerError when call udf

### ISSUE THREAD

**Issue by zhaojinchao95** [StarRocks/starrocks#46762]
### Steps to reproduce the behavior (Required)

```
CREATE FUNCTION udf_demo(string, string) 
RETURNS string
properties (
"symbol" = "com.xx.starrocks.udf.xx", 
"type" = "StarrocksJar",
"file" = "file:///xx/xx/xx/udf/xxx-1.0.0.jar"
);

select udf_demo('e166c3391294E69cc4c620f594fe00d7', column4) from br_test limit 1;
```

### Expected behavior (Required)

Call udf successful

### Real behavior (Required)

`(HY000): Error: couldn't create class loader com.starrocks.udf.UDFClassLoader,java.lang.ExceptionInInitializerError[]  `

### StarRocks version (Required)

`2.5.8`

**Comment by hackeryang** [comment]
How did you fix this problem? I saw the issue is closed
