### ISSUE TITLE
[Bug] function spilt_part should not return null when delimiter is not matched

### ISSUE THREAD

**Issue by SaintBacchus** [StarRocks/starrocks#46774]
### Steps to reproduce the behavior (Required)
![img_v3_02bj_94a42be3-ddd3-48a0-a190-2dbdfd4c6d0g](https://github.com/StarRocks/starrocks/assets/7404824/59aaee7c-2222-4f68-a4e6-81e22fd67ca7)

```sql
select split_part("hello world", "|", 1);
```
### Expected behavior (Required)
return null 

### Real behavior (Required)
samw with `substring_index ` and return `hello world`

### StarRocks version (Required)
main

**Comment by stdpain** [comment]
closed via https://github.com/StarRocks/starrocks/pull/56967
