### ISSUE TITLE
[3.2.6] CN coredump in force spill in shared-data mode

### ISSUE THREAD

**Issue by FanHui0225** [StarRocks/starrocks#46814]
### Steps to reproduce the behavior (Required)
query_id:e4a2d887-2491-11ef-83df-fa163eaed88d, fragment_instance:e4a2d887-2491-11ef-83df-fa163eaed89c
tracker:process consumption: 2832623632
tracker:query_pool consumption: 613968
tracker:query_pool/connector_scan consumption: 0
tracker:load consumption: 0
tracker:metadata consumption: 254565554
tracker:tablet_metadata consumption: 10319839
tracker:rowset_metadata consumption: 0
tracker:segment_metadata consumption: 28984731
tracker:column_metadata consumption: 215260984
tracker:tablet_schema consumption: 10319839
tracker:segment_zonemap consumption: 26111720
tracker:short_key_index consumption: 18778
tracker:column_zonemap_index consumption: 64308408
tracker:ordinal_index consumption: 58521376
tracker:bitmap_index consumption: 0
tracker:bloom_filter_index consumption: 0
tracker:compaction consumption: 0
tracker:schema_change consumption: 0
tracker:column_pool consumption: 0
tracker:page_cache consumption: 0
tracker:update consumption: 8804477
tracker:chunk_allocator consumption: 519914168
tracker:clone consumption: 0
tracker:consistency consumption: 0
tracker:datacache consumption: 756324404
tracker:replication consumption: 0
*** Aborted at 1717739449 (unix time) try “date -d @1717739449” if you are using GNU date ***
PC: @ 0x6263ffd starrocks::spill::UnorderedMemTable::append_selective()
*** SIGSEGV (@0xfffffffffffffff0) received by PID 28 (TID 0x7f993634e640) from PID 18446744073709551600; stack trace: ***
@ 0x7fb5eda google::(anonymous namespace)::FailureSignalHandler()
@ 0x7f999f0d0520 (unknown)
@ 0x6263ffd starrocks::spill::UnorderedMemTable::append_selective()
@ 0x6005db4 ZN9starrocks5spill24PartitionedSpillerWriter22process_partition_dataIZNS1_5spillIRNS0_14IOTaskExecutorERNS0_23ResourceMemTrackerGuardIJSt8weak_ptrINS_8pipeline12QueryContextEES7_INS0_7SpillerEEEEEEENS_6StatusEPNS_12RuntimeStateERKSt10shared_ptrINS_5ChunkEEOT_OT0_EUlPNS0_16SpilledPartitionERKSt6vectorIjSaIjEEiiE_EEvSM_SX_SO
@ 0x6008144 starrocks::spill::PartitionedSpillerWriter::spill<>()
@ 0x600853e starrocks::spill::Spiller::spill<>()
@ 0x60035b5 starrocks::HashJoiner::append_chunk_to_spill_buffer()
@ 0x635187a starrocks::pipeline::SpillableHashJoinBuildOperator::push_chunk()
@ 0x5f4b642 starrocks::pipeline::PipelineDriver::process()
@ 0x67eb3be starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
@ 0x6b7b90c starrocks::ThreadPool::dispatch_thread()
@ 0x6b74e1a starrocks::thread::supervise_thread()
@ 0x7f999f122ac3 (unknown)
@ 0x7f999f1b3a04 clone
@ 0x0 (unknown)
start time: Fri Jun 7 13:51:14 CST 2024

### StarRocks version (Required)
3.2.6

**Comment by silverbullet233** [comment]
could you provide more details about how to  reproduce this problem?
