### ISSUE TITLE
array_zip function, transform arrays to  row of array

### ISSUE THREAD

**Issue by jgchen** [StarRocks/starrocks#46818]
Do there has any function like zip in Trino or array_zip in Doris?
https://trino.io/docs/current/functions/array.html#zip

**Comment by wangsimo0** [comment]
no, if you are interested in this function, you are more than well come to contribute one. 
here is a map function which is similar to the zip function. however the data type is not exactly same. https://docs.starrocks.io/docs/sql-reference/sql-functions/map-functions/map_from_arrays/
