### ISSUE TITLE
Support custom zstd compression levels

### ISSUE THREAD

**Issue by derekperkins** [StarRocks/starrocks#46839]
## Feature request

**Is your feature request related to a problem? Please describe.**

I have large data that is very infrequently accessed with no latency requirements, so I want to compress it as much as possible. `ZSTD` is already an option, but there doesn't appear to be a way to set the compression level.

https://docs.starrocks.io/docs/table_design/data_compression/

**Describe the solution you'd like**

Similar to Clickhouse, AWS Athena, and other tools, support setting a compression level in parentheses after `ZSTD`, like `ZSTD(22)`. The supported levels are 1-22. It would also be useful to document what compression level is actually used, as it isn't clear. Clickhouse defaults to 1, Athena defaults to 3. What does StarRocks use?

```sql
CREATE TABLE `data_compression` (
  `id`      INT(11)     NOT NULL     COMMENT "",
  `name`    CHAR(200)   NULL         COMMENT ""
)
ENGINE=OLAP 
UNIQUE KEY(`id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id`)
PROPERTIES (
"compression" = "ZSTD(1-22)"
);
```

- https://clickhouse.com/docs/en/sql-reference/statements/create/table#zstd
- https://docs.aws.amazon.com/athena/latest/ug/compression-support-zstd-levels.html

**Comment by srlch** [comment]
https://github.com/StarRocks/starrocks/pull/46976

**Comment by srlch** [comment]
In the previous implementation, default level is 3.
