### ISSUE TITLE
run sql slow with order by in High concurrency

### ISSUE THREAD

**Issue by skypan** [StarRocks/starrocks#4687]
### Steps to reproduce the behavior (Required)

select
	serialnum,
	rowguid,
	pviguid,
	replaytime,
	rqsttitle,
	rqstperson,
	rqsttime,
	samenum,
	registerguid,
	isreplay,
	issendou,
	casetype,
	rqstsource,
	sponsordeptname,
	rqsttype,
	cstatus,
	ifnull(reminderNum, 0) reminderNum,
	rqstcontent,
	issecret,
	tFinishtime_bf,
	tfinishtime,
	split_part(ACCORDTYPE , '-', 1) acc1,
	split_part(ACCORDTYPE , '-', 2) acc2 ,
	split_part(ACCORDTYPE , '-', 3)acc3,
	split_part(ACCORDTYPE , '-', 4) acc4 ,
	split_part(ACCORDTYPE , '-', 5) acc5
from
	cns_cinfo_copy
where
	1 = 1
	and rqstdate  >= '2021-09-28'
	and rqstdate <= '2022-03-28'
	and (casetype in('10', '20', '30') )
	and (cstatus != '-1' )
order by
	rqsttime desc
limit 0,10

-- only one partitions
CREATE TABLE `cns_cinfo_copy3` (
`RQSTSTAMP` bigint(20) NOT NULL,
`ROWGUID` varchar(50)  NOT NULL,
`RQSTTIME` datetime NOT NULL,
  `TEMPCLIENGGUID` varchar(50) DEFAULT NULL COMMENT '附件guid',
  `WEBCLIENGGUID` varchar(50)  DEFAULT NULL COMMENT '外网用户上传cliengguid',
  `HANDLEMANYOUGUIDLIST` varchar(500)  DEFAULT NULL COMMENT '多部门处理guid',
  `HANDLEMANYOULIST` varchar(300)  DEFAULT NULL COMMENT '处理多部门名称',
  `ISSUPPLY` varchar(4)  DEFAULT NULL COMMENT '是否有补单',
  `ANSWERCONTENT` varchar(1500)  DEFAULT NULL,
  `KEYWORDTYPE` varchar(10)  DEFAULT NULL COMMENT '关键词类别',
  `KEYWORDTEXT` varchar(100)  DEFAULT NULL,
  `REVOKETIME` datetime DEFAULT NULL,
  `REVOKEREASONTYPE` varchar(20)  DEFAULT NULL,
  `REVOKEREASONTEXT` varchar(500)  DEFAULT NULL,
  `ISSENDOU` varchar(4)  DEFAULT NULL,
  `ISDIFFICULTCASE` varchar(4)  DEFAULT NULL,
  `REGISTERTIME` datetime DEFAULT NULL,
  `SENDOUTIME` datetime DEFAULT NULL,
  `FINISHTIME` datetime DEFAULT NULL,
  `FINISHTIME_BF` datetime DEFAULT NULL,
  `SENDOUTIME_BF` datetime DEFAULT NULL,
  `ABANDONTYPE` varchar(4) DEFAULT NULL,
  `ABANDONTEXT` varchar(200) DEFAULT NULL,
  `AREANAME` varchar(50) DEFAULT NULL,
  `TEMPOPINION` varchar(300) DEFAULT NULL,
  `SENDOUTYPE` varchar(8)  DEFAULT NULL,
  `CONTRACTGUID` varchar(50)  DEFAULT NULL,
  `ANSWERPERSON` varchar(50) DEFAULT NULL,
  `ISDIRECTFINISH` varchar(50) DEFAULT NULL,
  `SERIALNUM` varchar(50)  DEFAULT NULL,
  `RQSTPERSON` varchar(30)  DEFAULT NULL,
  `RQSTSEX` varchar(2)  DEFAULT NULL,
  `RQSTNUMBER` varchar(16)  DEFAULT NULL,
  `LINKNUMBER` varchar(25)  DEFAULT NULL,
  `RQSTAREA` varchar(100)  DEFAULT NULL,
  `RQSTAREACODE` varchar(32)  DEFAULT NULL,
  `RQSTADDRESS` varchar(200)  DEFAULT NULL,
  `RQSTTYPE` varchar(16)  DEFAULT NULL,
  `ACCORDTYPE` varchar(100) DEFAULT NULL,
  `ACCORDTYPECODE` varchar(16) DEFAULT NULL,
  `RQSTTITLE` varchar(400)  DEFAULT NULL,
  `RQSTCONTENT` varchar(2000) DEFAULT NULL,
  `RQSTSOURCE` varchar(8)  DEFAULT NULL,
  `ISIMPT` varchar(50) DEFAULT NULL,
  `ISSECRET` varchar(4)  DEFAULT NULL,
  `RQSTEMAIL` varchar(200)  DEFAULT NULL,
  `ISREPLAY` varchar(4)  DEFAULT NULL,
  `REPLAYTYPE` varchar(8)  DEFAULT NULL,
  `CSTATUS` varchar(16)  DEFAULT NULL,
  `PVIGUID` varchar(50)  DEFAULT NULL,
  `EVLSTYLE` varchar(16)  DEFAULT NULL,
  `EVLRESULT` varchar(16)  DEFAULT NULL,
  `ISABANDON` varchar(4)  DEFAULT NULL,
  `HANDLEOU` varchar(32)  DEFAULT NULL,
  `HANDLEOUGUID` varchar(50)  DEFAULT NULL,
  `HANDLEXIEOULIST` varchar(100)  DEFAULT NULL,
  `HANDLEXIEOUGUIDLIST` varchar(500)  DEFAULT NULL,
  `ANSWERTIME` datetime DEFAULT NULL,
  `AREACODE` varchar(50)  DEFAULT NULL,
  `RELKNOWTIME` datetime DEFAULT NULL,
  `ISRELKNOW` varchar(4)  DEFAULT NULL,
  `NOTES` varchar(1000)  DEFAULT NULL,
  `AGESTAGE` varchar(50)  DEFAULT NULL,
  `MANAGETYPE` varchar(50)  DEFAULT NULL,
  `REGISTERGUID` varchar(50)  DEFAULT NULL,
  `REGISTERNAME` varchar(100)  DEFAULT NULL,
  `CLIENGGUID` varchar(50)  DEFAULT NULL,
  `CHECKSTATUS` varchar(4)  DEFAULT NULL,
  `CKPERSON` varchar(100)  DEFAULT NULL,
  `CKPERSONGUID` varchar(50)  DEFAULT NULL,
  `DISTTIME` datetime DEFAULT NULL,
  `ISANSWER` varchar(4)  DEFAULT NULL,
  `ANSWEROU` varchar(500)  DEFAULT NULL,
  `WEBUSERGUID` varchar(50)  DEFAULT NULL,
  `REPLAYTIME` datetime DEFAULT NULL,
  `AUDITFINALGUID` varchar(50)  DEFAULT NULL,
  `AUDITFIRSTGUID` varchar(50)  DEFAULT NULL,
  `HANDLEAREALIST` varchar(500)  DEFAULT NULL,
  `HANDLEAREAGUIDLIST` varchar(500)  DEFAULT NULL,
  `LNGLAT` varchar(30)  DEFAULT NULL,
  `ABANDONTIME` datetime DEFAULT NULL,
  `SENDOUPERSONGUID` varchar(50) DEFAULT NULL,
  `ISENABLEADDTASK` varchar(5) DEFAULT NULL,
  `PERSONADDRESS` varchar(150) DEFAULT NULL,
  `OPERATEUSERNAME` varchar(50)  DEFAULT NULL,
  `OPERATEDATE` datetime DEFAULT NULL,
  `BELONGXIAQUCODE` varchar(50)  DEFAULT NULL,
  `ROW_ID` float DEFAULT NULL,
  `YEARFLAG` varchar(4)  DEFAULT NULL,
  `CLEARTIME` int(11) DEFAULT NULL,
  `WRONGLEVEL` varchar(8) DEFAULT NULL,
  `ANSWEROUGUID` varchar(500) DEFAULT NULL,
  `ISNOTJXKH` varchar(2) DEFAULT NULL,
  `WEBRQSTTIME` datetime DEFAULT NULL,
  `ABANDONOU` varchar(50)  DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `ISRELPROVIDE` varchar(50)  DEFAULT NULL,
  `ISRESULTSENDOU` varchar(50) DEFAULT NULL,
  `Isrecommend` varchar(50) DEFAULT NULL,
  `RecommendStatus` varchar(50) DEFAULT NULL,
  `REPLAYCONTENT` varchar(1000)  DEFAULT NULL,
  `ISCITYLEVEL` varchar(8)  DEFAULT NULL,
  `SESSIONID` varchar(100) DEFAULT NULL,
  `TENANTGUID` varchar(50) DEFAULT NULL,
  `isrepeated` varchar(4) DEFAULT NULL,
  `samenum` int(11) DEFAULT NULL,
  `samecguid` varchar(50) DEFAULT NULL,
  `repeatcstatus` varchar(4) DEFAULT NULL,
  `transferuserguid` varchar(500) DEFAULT NULL,
  `customerGuid` varchar(50) DEFAULT NULL,
  `UNIONCGUID` varchar(50) DEFAULT NULL,
  `ISFIRSTCINFO` varchar(5)  DEFAULT NULL COMMENT '是否源工单',
  `CASETYPE` varchar(50) DEFAULT NULL,
  `PARENTCGUID` varchar(50)  DEFAULT NULL COMMENT '父工单guid',
  `BACKFLAG` varchar(5)  DEFAULT NULL COMMENT '直接退回',
  `relationHistoryOrderInfo` varchar(2000) DEFAULT NULL,
  `satisfylabel` varchar(100) DEFAULT NULL COMMENT '不满意标签',
  `INTELIGUID` varchar(50)  DEFAULT NULL COMMENT '智能检索guid',
  `formtype` varchar(50) DEFAULT NULL,
  `satisfylabelname` varchar(200) DEFAULT NULL,
  `parenttguid` varchar(50) DEFAULT NULL,
  `callid` varchar(50)  DEFAULT NULL COMMENT '录音唯一标识',
  `ispublic` varchar(10)  DEFAULT NULL COMMENT '是否公开',
  `keywords` varchar(65533) NULL COMMENT "",
  `reflecttype` varchar(4) DEFAULT NULL,
  `questiontype` varchar(50) DEFAULT NULL,
  `ispush` varchar(4) DEFAULT NULL,
  `handleareaxieguidlist` varchar(300) DEFAULT NULL,
  `replaytime_bf` datetime DEFAULT NULL,
  `status` varchar(4) DEFAULT '0',
  `isvalid` varchar(4) DEFAULT NULL,
  `replayway` varchar(4) DEFAULT NULL,
  `sponsordeptname` varchar(50)  DEFAULT NULL COMMENT '当前处办部门',
  `reminderNum` varchar(50)  DEFAULT NULL COMMENT '催单次数',
  `depttype` varchar(50)  DEFAULT NULL COMMENT '分子平台标识',
  `tfinishtime_bf` datetime DEFAULT NULL,
  `tfinishtime` datetime DEFAULT NULL,
  `handlingou` varchar(100) DEFAULT NULL,
  `isoverseas` varchar(4) DEFAULT NULL,
  `ywxtCitySubmitAreaCode` varchar(50)  DEFAULT NULL COMMENT '业务系统区域编码',
  `issupervise` varchar(100) DEFAULT NULL COMMENT '督办类型',
  `warningtype` varchar(100) DEFAULT NULL COMMENT '预警类型',
  `isoldcinfo` varchar(4) DEFAULT NULL COMMENT '是否复核重派前工单',
  `checktime` varchar(100) DEFAULT NULL COMMENT '重派时间'
)
ENGINE=OLAP 
PRIMARY KEY(`RQSTSTAMP`,`ROWGUID`)
DISTRIBUTED BY HASH(`ROWGUID`) BUCKETS 32 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);

try one partitons and every day partions, run slow yet

### Expected behavior (Required)
run 200 tps in High concurrency
### Real behavior (Required)
run 5tps High concurrency
### StarRocks version (Required)
 the newest version:2.1.3

**Comment by Dshadowzh** [comment]
`order by` is a heavy operator and it's hard to get high concurrency.
