### ISSUE TITLE
The performance for Spark-Starrocks-Connector read a lot of data

### ISSUE THREAD

**Issue by Nanine527** [StarRocks/starrocks#469]
## General Question

1、如果使用spark （doris）读取，则会每次加载全量数据（2亿条数据），读取速度太慢：

      var dorisSparkDF=sparkSession.read.format("doris")
        .option("doris.fenodes", s"${dorisFe}:${port}")
        .option("doris.table.identifier", s"(${sql}) as tempViewName")
        .option("user", s"${userName}")
        .option("password", s"${password}")
        .load()
2、如果使用spark （jdbc）读取，返回小数据没问题，如果加载全量数据（2亿条数据），直接会报错；
      var dorisSparkDF = sparkSession.read
        .format("jdbc")
        .option("url", "jdbc:mysql://"+s"${dorisFe}:${port}"+"?characterEncoding=UTF-8")
        .option("dbtable", s"(${sql}) as tempViewName")
        .option("numPartitions",10)
        .option("fetchsize", 10000)
        .option("queryTimeout", 0)
        .option("user", s"${userName}")
        .option("password", s"${password}")
        .load()

3、建议：能不能使用 spark （doris）读取doris时，不需要加载全量数据，最好能按照传入的sql 加载数据？

**Comment by wyb** [comment]
You can add filter in dataframe.
