### ISSUE TITLE
hour() executed error

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#4698]
### Steps to reproduce the behavior (Required)
1. 
```
select hour('9999-03-31 24:00:00')
```
### Expected behavior (Required)
NULL
### Real behavior (Required)
0
### StarRocks version (Required)
```
+------------------------+
| current_version()      |
+------------------------+
| QA_TEST_MASTER f6f6228 |
+------------------------+
```

**Comment by laotan332** [comment]
This calculation is correct， we will trans '9999-03-31 24:00:00' to， 9999-03-31 00:00:00'，so it make correct
