### ISSUE TITLE
Selecting from unsupported types in a JDBC connection results in error

### ISSUE THREAD

**Issue by Grisgruis** [StarRocks/starrocks#47222]
When selecting from a JDBC connection (mariadb in my case) I cannot select from tables which has an unsupported type.

I cannot cast, because it wont let me select.

In Trino you have support for unsupported types: https://trino.io/docs/current/connector/mariadb.html#type-mapping-configuration-properties, I would expect something similar in this case, or at least a fallback to string.

#### In mariadb 

```
CREATE TABLE `database.splits` (
  `guid` char(36) NOT NULL,
  `amount` decimal(50,6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
```
```
INSERT INTO splits (guid, amount)
VALUES ('string', 50);
```

#### in Starrocks
```
create external CATALOG database
properties (
    "type"="jdbc",
    "user"="user",
    "password"="pw",
    "jdbc_uri"="url",
    "driver_url"="url/mysql-connector-j-8.0.32.jar",
    "driver_class"="com.mysql.jdbc.Driver"
);
```

### Expected behavior (Required)
`select guid from database.splits; -- should work`
`select CAST(amount AS DECIMAL64(10,2)) from database.splits; -- should work`

### Real behavior (Required)

```
select * from database.splits; -- error DECIMAL's precision should range from 1 to 38
select guid from database.splits; -- error DECIMAL's precision should range from 1 to 38
select amount from database.splits; -- error DECIMAL's precision should range from 1 to 38
select CAST(amount AS DECIMAL64(10,2)) from database.splits; -- error DECIMAL's precision should range from 1 to 38
```

### StarRocks version (Required)
`3.3.0-rc01-3b8cb0c`

**Comment by dirtysalt** [comment]
Could you try to set  session variable

> set large_decimal_underlying_type = "decimal"

by default, if decimal type specifier is out of range, we will report error.  But if you accept precision lost, you can set the above session variable.

check it out https://docs.starrocks.io/releasenotes/release-3.2/#others

> Added the session variable large_decimal_underlying_type = "panic"|"double"|"decimal" to set the rules to deal with DECIMAL type overflow. panic indicates returning an error immediately, double indicates converting the data to DOUBLE type, and decimal indicates converting the data to DECIMAL(38,s).

**Comment by Grisgruis** [comment]
Awesome, works:

```
set large_decimal_underlying_type = 'decimal';
select * from database.splits limit 50;
```
