### ISSUE TITLE
Remove directory be/src/storage/rowset/vectorized

### ISSUE THREAD

**Issue by sduzh** [StarRocks/starrocks#4735]
## Refactoring request

Move the files under `be/src/storage/rowset/vectorized/` to `the be/src/storage/rowset/` and remove the directory `be/src/storage/rowset/vectorized/`

**Comment by sduzh** [comment]
Better to change the namespace name from `starrocks::vectorized` to `starrocks` for these renamed files, but we can submit this renaming in a separate PR.

**Comment by MonsterChenzhuo** [comment]
@sduzh Can you assign this pr to me?
