### ISSUE TITLE
image starrocks/cn-ubuntu needs tag 3.3.0

### ISSUE THREAD

**Issue by lianneli** [StarRocks/starrocks#47404]
### Steps to reproduce the behavior (Required)
I want to try the new version 3.3.0, but there is no 3.3.0 tag for starrocks/cn-ubuntu.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by kevincai** [comment]
it's on the way.

**Comment by kevincai** [comment]
docker pull starrocks/cn-ubuntu:3.3.0

https://hub.docker.com/r/starrocks/cn-ubuntu/tags

**Comment by lianneli** [comment]
Aha，it comes! Thanks!
