### ISSUE TITLE
[Enhancement] All the load methods should support specifying esacped character for column_separator and row_delimiter

### ISSUE THREAD

**Issue by jaogoy** [StarRocks/starrocks#47430]
## Enhancement
Users can use `\t`, `\n` directly in all load methods' parameters for `column_separator` and `row_delimiter`.
* [ ] stream load #47302

It's not clear whether Broker Load, INSERT INTO, and Routine Load support escaped character for `column_separator` and `row_delimiter`

**Comment by wyb** [comment]
https://github.com/StarRocks/starrocks/pull/47302
