### ISSUE TITLE
Refactor: Split MemTable into different classes

### ISSUE THREAD

**Issue by sduzh** [StarRocks/starrocks#4764]
## Refactoring request

In the current implementation, tablets of PRIMARY_KEY/DUP_KEY/UNIQUE_KEY/AGGREGATE_KEY all share a common `MemTable` implementation, while each of these tablets has its own unique processing logic.
In order to handle these different logics, `MemTable` requires many conditional checks, resulting in a rather obscure implementation. 
In addition, in order to handle all the tablet types, many fields need to be defined in `MemTable`, even though many of them are not needed for some tablet, for example, the `MemTable::_aggregator ` field is useless when handling tablets of type DUP_KEY.
By splitting the current memtable into several different derived classes, each corresponding to a different type of tablet, the following gains can be achieved.
1.  better readability and maintainability
2. reduce the memory size of each specific memtable to reduce the memory usage during import

**Describe the solution you'd like**
```
class MemTable {
 ...
};

class MemTableForDupKey : public MemTable {
 ...
};

class MemTableForPrimaryKey : public MemTable {
  ...
};

class MemTableForAggregateKey : public MemTable {
 ...
};

std::unique_ptr<MemTable> create_memtable(KeysType key_type);

```

**Test Plan**
Add unit tests for each derived class of MemTable.

**Comment by ZeroLiu2018** [comment]
hi, sduzh, can i try to do it if you do not mind

**Comment by sduzh** [comment]
> 

Of course, feel free to do it.

**Comment by sduzh** [comment]
> hi, sduzh, can i try to do it if you do not mind

Of course, feel free to do it!

**Comment by decster** [comment]
This code is critical for data integrity and correctness, after refactoring, it needs to be carefully reviewed and thoroughly tested, and I don't think the existing UTs can cover most cases, before check-in this PR, please add more UTs(like this one: #4466) to make sure it's correctness.

**Comment by decster** [comment]
It happens multiple times, someone changes code in memtable and introduce new bugs

**Comment by ZeroLiu2018** [comment]
hi, I am very sorry, I can not complete the issue，because my compute always failed to build ut ....，it seems my computer  limited by memory. Sorry... 😞

**Comment by markjenny** [comment]
I would like to try this issue, can I be assigned to try it out?

**Comment by markjenny** [comment]
I'm so sorry I don't have enough time to contribute to this project, please cancel this issue assignment.
