### ISSUE TITLE
issue on async materialized view refresh

### ISSUE THREAD

**Issue by cj1201** [StarRocks/starrocks#47719]
版本：3.2.8
描述：
异步物化视图和基表不在同一个库下时，truncate基表，物化视图数据不会删除。

**Comment by cj1201** [comment]
该bug有计划哪个版本修复吗？谢谢

**Comment by cj1201** [comment]
这个bug请问有修复计划吗

**Comment by crossoverJie** [comment]
@kevincai @LiShuMing I'm interested in fixing this issue, please assign it to me. Thanks

**Comment by kevincai** [comment]
@crossoverJie issue assigned to you
