### ISSUE TITLE
When the drop database xxx force is executed, the storage directory is preserved

### ISSUE THREAD

**Issue by yesengh** [StarRocks/starrocks#47843]
### Steps to reproduce the behavior (Required)
drop database xxx force
![a40c24fc5d6e449f557479ea16565fe](https://github.com/StarRocks/starrocks/assets/43601935/975886ce-95de-4bd2-9687-8da65bc89c50)

### Expected behavior (Required)
Recursively delete the directory corresponding to the HDFS file system

### Real behavior (Required)
The table data in the corresponding HDFS file system is deleted, but the folder is retained
![65f2c97b0ae7a9ee4c6a411fdebce84](https://github.com/StarRocks/starrocks/assets/43601935/c7ee6e7d-3425-421b-ac4f-007018641110)

### StarRocks version (Required)
Use HDFS for shared-data 3.2.8

**Comment by kevincai** [comment]
please check if there is any files left under the directory.

It is a little bit different between HDFS and OBJECT storage. For object storage, when all the files are cleaned, the directory will be gone (because there is no directory at all), but for HDFS, directories are in namenode meta as well. Currently there is no explicit clean of such directories.

**Comment by yesengh** [comment]
**The table data in the corresponding HDFS file system is deleted**
![image](https://github.com/StarRocks/starrocks/assets/43601935/eabc4e9b-7562-442f-948a-20981b002eab)

_So it's clear that the corresponding folder Use HDFS for shared-data 3.2.8 will not be deleted, right?_

**Comment by kevincai** [comment]
> **The table data in the corresponding HDFS file system is deleted** ![image](https://private-user-images.githubusercontent.com/43601935/346063118-eabc4e9b-7562-442f-948a-20981b002eab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMTkwOTksIm5iZiI6MTcyMDIxODc5OSwicGF0aCI6Ii80MzYwMTkzNS8zNDYwNjMxMTgtZWFiYzRlOWItNzU2Mi00NDJmLTk0OGEtMjA5ODFiMDAyZWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDIyMzMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZjE0ZDkwM2ZjNjBhMWI2YWI0MmEzZmEzODYwNDhhYjY1NmFhZGQyZjc3ZjM2ZDNlZWMxYjAxNmU1YWViM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X9x-QSdDknKCQsXmMS0fwPH97g-W1lHhLqVa3EIcHAA)
> 
> _So it's clear that the corresponding folder Use HDFS for shared-data 3.2.8 will not be deleted, right?_

Yes, and it is expected for now when using HDFS as its remote storage.

**Comment by tracymacding** [comment]
@yesengh Kevin is right, db dir can not be deleted for now, maybe you can remove it manually

**Comment by yesengh** [comment]
OK, we can manually clean up this kind of low frequency problem, thank you.
