### ISSUE TITLE
Support iceberg timetravel/branch/tag

### ISSUE THREAD

**Issue by stephen-shelby** [StarRocks/starrocks#47846]
- [x] https://github.com/StarRocks/starrocks/pull/48061
- [x] https://github.com/StarRocks/starrocks/pull/47997
- [x] https://github.com/StarRocks/starrocks/pull/48063
- [x] https://github.com/StarRocks/starrocks/pull/47867
- [x] https://github.com/StarRocks/starrocks/pull/47847

## Feature request

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Management

- [ ]  Create/drop branch/tag
- [ ]  Write a table based on the branch
- [ ]  fast_forward branch to main
- [ ]  cherrypick_snapshot
- [ ]  Expire snapshot based on the ref options
- [ ] Auto expire snapshot(optional)

Query
- [ ]  Query with branch/tag
- [ ]  Query with version/timestamp
- [ ]  Query table snapshots/refs

**Describe alternatives you've considered**

**Additional context**

**Comment by maver1ck** [comment]
Hi @stephen-shelby 
Are you planning to add any documentation for new features ?
