### ISSUE TITLE
[Question] can we add label to CN node, when run query special label to run task on matched nodes

### ISSUE THREAD

**Issue by liunaijie** [StarRocks/starrocks#47953]
hi, team. the slack invite link is not work, so i open an bug for this.

in this article https://docs.starrocks.io/docs/administration/management/resource_management/be_label/, mentioned we can add label to BE nodes, then when create table we can add label to the table properties. 

In this case, i think the query about one table will only run on the matched node, as data are only store on them.

So on the Storage-compute separation mode, can we add label to those CN node, let the query/task only run those matched node.

**Comment by tracymacding** [comment]
No, I think you'd better try multi warehouse in cloud native mode ：）

**Comment by liunaijie** [comment]
> No, I think you'd better try multi warehouse in cloud native mode ：）

Hi, i think multiple warehouse is not a good idea. 
We want use an signle warehourse in campany, and use some thing like label to do the resouce isolation for different teams.

**Comment by liunaijie** [comment]
> No, I think you'd better try multi warehouse in cloud native mode ：）

@tracymacding hi, is there any multi warehouse related document i can refer, thanks.
