### ISSUE TITLE
Can't drop broker

### ISSUE THREAD

**Issue by long2ice** [StarRocks/starrocks#4801]
I want drop invalid broker, but return `Syntax error`
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/13377178/161415314-169c1ec8-b873-495c-8e28-a81d8d67d304.png">, and why there can two same name brokers?

### Steps to reproduce the behavior (Required)
1. `alter system drop broker broker1`

### Expected behavior (Required)
Drop the invalid broker
### Real behavior (Required)
return Syntax error
### StarRocks version (Required)
 - 2.1.3 0881cb2

**Comment by imay** [comment]
You should execute this command like 
```
ALTER SYSTEM DROP BROKER broker_name "host:port"[,"host:port"...];
```
You can refer to https://docs.starrocks.com/en-us/main/sql-reference/sql-statements/Administration/ALTER%20SYSTEM

**Comment by long2ice** [comment]
Thanks!
