### ISSUE TITLE
starrocks branch-3.2 be compile failed，because this issue code merge

### ISSUE THREAD

**Issue by ypcthenry** [StarRocks/starrocks#48043]
[[BugFix] Bump simdjson to 3.9.4 and Fix struct field columns inconsistent when loading from bad json (backport](https://github.com/StarRocks/starrocks/commit/30acfe0a66c24004b74a6f383493c4b0a670c00c) https://github.com/StarRocks/starrocks/pull/47775[) (](https://github.com/StarRocks/starrocks/commit/30acfe0a66c24004b74a6f383493c4b0a670c00c)https://github.com/StarRocks/starrocks/pull/47895[)](https://github.com/StarRocks/starrocks/commit/30acfe0a66c24004b74a6f383493c4b0a670c00c)

compile failed information：
<img width="670" alt="image" src="https://github.com/StarRocks/starrocks/assets/3361949/12037ea5-8577-4e9d-8432-804f15482b27">

**Comment by kevincai** [comment]
have you tried pulling the latest `starrocks/dev-env-<centos7|ubuntu>:3.2-latest` docker image to recompile the code?

**Comment by kevincai** [comment]
have compiled on my own, it works with no issue

commitId: 2f78de099c24bb7dee4d1cd9671a2315541b443a (#48054)
starrocks/dev-env-centos7:3.2-latest sha256:41e9a55be8aa3ebb1518c63b5d797458d7432759dca3276d7011fab731ff50a2

**Comment by kevincai** [comment]
close as done.
