### ISSUE TITLE
In special cases, using non-VARCHAR type parameters to call substring will cause BE to crash.

### ISSUE THREAD

**Issue by chenminghua8** [StarRocks/starrocks#48141]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE t (
day datetime
) ENGINE=OLAP
PRIMARY KEY(day)
PARTITION BY RANGE(cast(substr(day, 1, 10) as datetime))
(
PARTITION p201704 VALUES LESS THAN ("20170501"),
PARTITION p201705 VALUES LESS THAN ("20170601"),
PARTITION p201706 VALUES LESS THAN ("20170701")
)
DISTRIBUTED BY HASH(day) BUCKETS 10
PROPERTIES (
"replication_num"="1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
2. INSERT INTO t VALUES("20170601");

### Expected behavior (Required)
Returns an error when calling the substr function with the wrong argument type.

### Real behavior (Required)
BE service process crashes.

### StarRocks version (Required)
2.5
3.0
3.1
3.2
3.3

**Comment by chenminghua8** [comment]
I want to add a check that columns[0] must be a BinaryColumn in the StringFunctions::substring method. This will prevent BE crashes when passing exception types to the StringFunctions::substring method.

**Comment by Astralidea** [comment]
Thanks for your feedback. I think you can just restrict this type of table creation from being supported on FE.

**Comment by chenminghua8** [comment]
One problem is to validate such illegal table statements. Another problem is that StringFunctions::substring allows non-BinaryColumn to be passed in without validation, causing BE to crash. This case is just one of the abnormal calls to substring. There are other abnormal calls to substring method, so substring method should be validated to avoid BE crash.

**Comment by chenminghua8** [comment]
@Astralidea Please help review the code.
