### ISSUE TITLE
Adjust dependencies on third-party projects with security vulnerabilities to avoid introducing security vulnerabilities

### ISSUE THREAD

**Issue by chenminghua8** [StarRocks/starrocks#48179]
## Enhancement
Remove the dependency on log4g 1.x and keep the dependency on log4g 2.19.

![image](https://github.com/StarRocks/starrocks/assets/771299/01269b2b-6518-4749-b15d-e15d10c2d9f4)

**Comment by chenminghua8** [comment]
log4j1.2.7 is a third-party dependency package introduced by hudi-common. log4j2.19.0 is API-compatible with log4j1.2, so this dependency is unnecessary.

**Comment by chenminghua8** [comment]
StarRocks 3.2.7 started to upgrade hudi-common to version 0.14.1. Hadoop in hudi-common 0.14.1 depended on log4j 1.2.17, so the dependency of log4j 1.2.17 was reintroduced.
I used StarRocks3.2.7 and StarRocks3.2.8 for packaging tests. If no modifications are made, the log4j1.2.17.jar package will be included in lib.
The dependency tree is as follows:
![image](https://github.com/user-attachments/assets/802c3ff1-e012-4a00-a105-1c163df51a89)

**Comment by kevincai** [comment]
yes. even with this modification, there is no way to withdraw the versions that have already released.

**Comment by chenminghua8** [comment]
The main branch has fixed this issue, so I think this issue can be closed.

**Comment by kevincai** [comment]
close this issue for now, may worth consider backport #46327 to branch-3.2 in future.

**Comment by kevincai** [comment]
@chenminghua8 let's fix this in branch-3.2 instead of backport the main branch fixes. Can you help do it?

**Comment by kevincai** [comment]
Fixed in #48123
