### ISSUE TITLE
BE crash with coalesce function

### ISSUE THREAD

**Issue by wangruin** [StarRocks/starrocks#4821]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `tpcds_100g_catalog_returns` (
  `cr_item_sk` int(11) NOT NULL COMMENT "",
  `cr_order_number` int(11) NOT NULL COMMENT "",
  `cr_returned_date_sk` int(11) NULL COMMENT "",
  `cr_returned_time_sk` int(11) NULL COMMENT "",
  `cr_refunded_customer_sk` int(11) NULL COMMENT "",
  `cr_refunded_cdemo_sk` int(11) NULL COMMENT "",
  `cr_refunded_hdemo_sk` int(11) NULL COMMENT "",
  `cr_refunded_addr_sk` int(11) NULL COMMENT "",
  `cr_returning_customer_sk` int(11) NULL COMMENT "",
  `cr_returning_cdemo_sk` int(11) NULL COMMENT "",
  `cr_returning_hdemo_sk` int(11) NULL COMMENT "",
  `cr_returning_addr_sk` int(11) NULL COMMENT "",
  `cr_call_center_sk` int(11) NULL COMMENT "",
  `cr_catalog_page_sk` int(11) NULL COMMENT "",
  `cr_ship_mode_sk` int(11) NULL COMMENT "",
  `cr_warehouse_sk` int(11) NULL COMMENT "",
  `cr_reason_sk` int(11) NULL COMMENT "",
  `cr_return_quantity` int(11) NULL COMMENT "",
  `cr_return_amount` decimal64(7, 2) NULL COMMENT "",
  `cr_return_tax` decimal64(7, 2) NULL COMMENT "",
  `cr_return_amt_inc_tax` decimal64(7, 2) NULL COMMENT "",
  `cr_fee` decimal64(7, 2) NULL COMMENT "",
  `cr_return_ship_cost` decimal64(7, 2) NULL COMMENT "",
  `cr_refunded_cash` decimal64(7, 2) NULL COMMENT "",
  `cr_reversed_charge` decimal64(7, 2) NULL COMMENT "",
  `cr_store_credit` decimal64(7, 2) NULL COMMENT "",
  `cr_net_loss` decimal64(7, 2) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`cr_item_sk`, `cr_order_number`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`cr_item_sk`, `cr_order_number`) BUCKETS 5
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
2.  CREATE TABLE `colocate_table_1` (
  `k1` date NOT NULL COMMENT "",
  `k2` int(11) NOT NULL COMMENT "",
  `v1` int(11) SUM NOT NULL COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`k1`, `k2`)
COMMENT "OLAP"
PARTITION BY RANGE(`k1`)
(PARTITION p1 VALUES [('0000-01-01'), ('2019-05-31')),
PARTITION p2 VALUES [('2019-05-31'), ('2019-06-30')))
DISTRIBUTED BY HASH(`k2`) BUCKETS 8
PROPERTIES (
"replication_num" = "3",
"colocate_with" = "group1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
3. select   ref_0.cr_return_amt_inc_tax as c0 from   tpcds_100g_catalog_returns as ref_0
 inner join colocate_table_1 as ref_1 on (ref_0.cr_refunded_cdemo_sk = ref_1.k2) where   (
 strright(       cast(         case           when (ref_0.cr_store_credit <= ref_0.cr_store_credit)           or (false) then case             when (ref_0.cr_catalog_page_sk is not NULL)
           or (true) then strleft(               cast(cast(null as VARCHAR) as VARCHAR),
         cast(ref_0.cr_warehouse_sk as INT)             )             else strleft(
    cast(cast(null as VARCHAR) as VARCHAR),               cast(ref_0.cr_warehouse_sk as INT)
           )           end           else case             when (ref_0.cr_catalog_page_sk is not NULL)             or (true) then strleft(               cast(cast(null as VARCHAR) as VARCHAR),               cast(ref_0.cr_warehouse_sk as INT)             )             else strleft(
              cast(cast(null as VARCHAR) as VARCHAR),               cast(ref_0.cr_warehouse_sk as INT)             )           end         end as VARCHAR       ),       cast(unix_timestamp() as INT)     ) > substring(       cast(         cast(           coalesce(             space(               cast(ref_0.cr_returning_addr_sk as INT)             ),             cast(null as VARCHAR)           ) as VARCHAR         ) as VARCHAR       ),       cast(         locate(
       cast(             cast(               coalesce(                 case
when false then cast(null as VARCHAR)                   else cast(null as VARCHAR)
     end,                 case                   when cast(null as VARCHAR) < cast(null as VARCHAR) then cast(null as VARCHAR)                   else cast(null as VARCHAR)
end               ) as VARCHAR             ) as VARCHAR           ),           cast(cast(null
as VARCHAR) as VARCHAR)         ) as INT       ),       cast(ref_0.cr_refunded_hdemo_sk as INT)     )   )   or (ref_0.cr_reversed_charge < ref_0.cr_net_loss) limit   68;

### Expected behavior (Required)
Query returns correctly

### Real behavior (Required)
```
start time: Wed Apr 6 11:40:08 CST 2022
tcmalloc: large alloc 8037801984 bytes == 0x118b0000 @  0x550790b 0x57a7356 0x57a3133 0x1f739b8 0x56f54d5 0x3417a71 0x3417e2b 0x3418035 0x340a9b5 0x30e70b6 0x30c100e 0x19eef50 0x30e6de5 0x2c5b1f4 0x30a0b7e 0x19eefe4 0x23a5330 0x2808969 0x2808cce 0x26aed97 0x1ec6f10 0x3d12547
tcmalloc: large alloc 8028749824 bytes == 0x1f12b0000 @  0x550790b 0x57a7356 0x57a3133 0x1f739b8 0x56f54d5 0x3417a71 0x3417e2b 0x3418035 0x340a9b5 0x30e70b6 0x30c100e 0x19eef50 0x30e6de5 0x2c5b1f4 0x30a0b7e 0x19eefe4 0x23a5330 0x2808969 0x2808cce 0x26aed97 0x1ec6f10 0x3d12547
tcmalloc: large alloc 8037801984 bytes == 0x3d0440000 @  0x550790b 0x57a7356 0x57a3133 0x1f739b8 0x56f54d5 0x2389b13 0x30c2292 0x19eef50 0x30e6de5 0x2c5b1f4 0x30a0b7e 0x19eefe4 0x23a5330 0x2808969 0x2808cce 0x26aed97 0x1ec6f10 0x3d12547
tcmalloc: large alloc 8028749824 bytes == (nil) @  0x550790b 0x57a7356 0x57a3133 0x1f739b8 0x56f54d5 0x2389b13 0x30c2292 0x19eef50 0x30e6de5 0x2c5b1f4 0x30a0b7e 0x19eefe4 0x23a5330 0x2808969 0x2808cce 0x26aed97 0x1ec6f10 0x3d12547
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
*** Aborted at 1649219146 (unix time) try "date -d @1649219146" if you are using GNU date ***
PC: @     0x7f9da1d95337 __GI_raise
*** SIGABRT (@0x3e8000257a3) received by PID 153507 (TID 0x7f9d75faa700) from PID 153507; stack trace: ***
    @     0x7f9da284a5f0 (unknown)
    @     0x7f9da1d95337 __GI_raise
    @     0x7f9da1d96a28 __GI_abort
    @          0x187c851 _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold
    @          0x56f4f86 __cxxabiv1::__terminate()
    @          0x56f4ff1 std::terminate()
    @          0x56f5144 __cxa_throw
    @          0x187c758 _Znwm.cold
    @          0x19e47c7 starrocks::vectorized::ColumnFactory<>::clone_shared()
    @          0x2389b13 starrocks::vectorized::ColumnFactory<>::clone()
    @          0x30c2292 starrocks::vectorized::VectorizedCoalesceExpr<>::evaluate()
    @          0x19eef50 starrocks::ExprContext::evaluate()
    @          0x30e6de5 starrocks::vectorized::VectorizedFunctionCallExpr::evaluate()
    @          0x2c5b1f4 starrocks::vectorized::VectorizedBinaryPredicate<>::evaluate()
    @          0x30a0b7e starrocks::vectorized::VectorizedOrCompoundPredicate::evaluate()
    @          0x19eefe4 starrocks::ExprContext::evaluate()
    @          0x23a5330 starrocks::ExecNode::eval_conjuncts()
    @          0x2808969 starrocks::pipeline::OlapChunkSource::_read_chunk_from_storage()
    @          0x2808cce starrocks::pipeline::OlapChunkSource::buffer_next_batch_chunks_blocking()
    @          0x26aed97 _ZNSt17_Function_handlerIFvvEZN9starrocks8pipeline12ScanOperator18_trigger_next_scanEPNS1_12RuntimeStateEiEUlvE0_E9_M_invokeERKSt9_Any_data
    @          0x1ec6f10 starrocks::PriorityThreadPool::work_thread()
    @          0x3d12547 thread_proxy
    @     0x7f9da2842e65 start_thread
    @     0x7f9da1e5d88d __clone
    @                0x0 (unknown)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
branch-2.2 release https://github.com/StarRocks/starrocks/commit/88eb86af21a47b62b39ec9bebd0c077a9f003afa

**Comment by stdpain** [comment]
fixed by https://github.com/StarRocks/starrocks/pull/4368
