### ISSUE TITLE
Iceberg thread pool will not use the value of fe config `iceberg_worker_num_threads` when config `enable_iceberg_custom_worker_thread` is set true

### ISSUE THREAD

**Issue by Xiangakun** [StarRocks/starrocks#48220]
### Steps to reproduce the behavior (Required)
1. set enable_iceberg_custom_worker_thread = true in fe.cnf, and keep config iceberg_worker_num_threads with default value 64
2.  create a iceberg catalog iceberg_catalog_test;
3.  set catalog iceberg_catalog_test;
4. show schemas;
5. Then jstack the fe process and see the thread pool `iceberg-worker-pool-xxx`
### Expected behavior (Required)
step 5, the thread pool `iceberg-worker-pool-xxx` should have totally 64 threads

### Real behavior (Required)
step 5, the thread pool `iceberg-worker-pool-xxx` with totally thread numbers equals the cpu vcore numbers.

### StarRocks version (Required)
3.1.10

 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by stephen-shelby** [comment]
do you restart frontend node?

**Comment by stephen-shelby** [comment]
please fix this issue in the branch-3.1. thx
