### ISSUE TITLE
Iceberg v1 Table Throws "Unknown Error" when "table-uuid" field in the table metadata JSON file is omitted

### ISSUE THREAD

**Issue by abfisher0417** [StarRocks/starrocks#48235]
### Steps to reproduce the behavior (Required)
1. Create an Iceberg v1 table using Spark or another tool and ensure it's registered in the catalog
2. When the current table metadata JSON file omits the [`table-uuid` field](https://iceberg.apache.org/spec/#table-metadata-fields), which is optional in Iceberg v1 spec, the table cannot be queried. NOTE: We are using BigQuery BigLake Managed Tables (BLMT) which stores BigQuery tables in Iceberg format on GCS.

```
➜  metadata cat v1720710382.metadata.json | jq
{
  "table-uuid": "3ce34c73-ed76-44bf-bc9b-983b5967fae3", -- If an Iceberg writer doesn't write this optional field, the table can't be queried in SR
  "current-schema-id": 0,
  "current-snapshot-id": 6997067474947719000,
  "default-spec-id": 0,
  "format-version": 1,
  "last-column-id": 24,
  "last-updated-ms": 1720710382287,
  "location": "gs://bucket/prefix/table",
...
}
```

### Expected behavior (Required)
```
mysql> select count(*) from catalog.db.table;
+-----------+
| count(*)  |
+-----------+
| 452268533 |
+-----------+
1 row in set (6.86 sec)
```

### Real behavior (Required)
```
mysql> select count(*) from catalog.db.table;
ERROR 1064 (HY000): Unknown error
```

### StarRocks version (Required)
3.2.8-759cc78

**Comment by DorianZheng** [comment]
@abfisher0417 Hi, Andrew. I will close this issue since it's been fixed. Feel free to re-open it if you find it's not working as expected.
