### ISSUE TITLE
Persist the primary key index to object storage. The syntax for this feature is not detailed in the document. Please provide additional information

### ISSUE THREAD

**Issue by zhbdesign** [StarRocks/starrocks#48254]
## Enhancement
Persist the primary key index to object storage. The syntax for this feature is not detailed in the document. Please provide additional information

**Comment by tracymacding** [comment]
It will be released in 3.3.1, so, please be patient :)

**Comment by zhbdesign** [comment]
> It will be released in 3.3.1, so, please be patient :)

"persistent_index_type" = "CLOUD_NATIVE"，已经通过代码找到配置

**Comment by Mywaying** [comment]
大佬，3.3.0 是不是也可以，刚试了一下 CLOUD_NATIVE，可以成功，持久化的路径在哪里呢

**Comment by Mywaying** [comment]
> > It will be released in 3.3.1, so, please be patient :)
> 
> "persistent_index_type" = "CLOUD_NATIVE"，已经通过代码找到配置

大佬，3.3.0 是不是也可以，刚试了一下 CLOUD_NATIVE，可以成功，持久化的路径在哪里呢

**Comment by zhbdesign** [comment]
> > > It will be released in 3.3.1, so, please be patient :)
> > 
> > 
> > "persistent_index_type" = "CLOUD_NATIVE"，已经通过代码找到配置
> 
> 大佬，3.3.0 是不是也可以，刚试了一下 CLOUD_NATIVE，可以成功，持久化的路径在哪里呢

我用的3.3-latest的镜像跑的是可以的，路径在data目录下，索引文件后缀是sst

**Comment by Mywaying** [comment]
> > > > It will be released in 3.3.1, so, please be patient :)
> > > 
> > > 
> > > "persistent_index_type" = "CLOUD_NATIVE"，已经通过代码找到配置
> > 
> > 
> > 大佬，3.3.0 是不是也可以，刚试了一下 CLOUD_NATIVE，可以成功，持久化的路径在哪里呢
> 
> 我用的3.3-latest的镜像跑的是可以的，路径在data目录下，索引文件后缀是sst

3.3.0 貌似有bug
https://github.com/StarRocks/starrocks/pull/44081#issue-2242942116
![Uploading image.png…]()
