### ISSUE TITLE
fe.internal.log shall be print to stdout when log_console is enabled

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks#48261]
### Steps to reproduce the behavior (Required)
currently when  log_console is enabled, `fe.internal.log` is still written to disk
![image](https://github.com/user-attachments/assets/d93ef537-f91f-46e8-9a6c-1f62d5b79762)

### Expected behavior
fe.internal.log shall be print to stdout when log_console is enabled

### Real behavior 
currently when  log_console is enabled, `fe.internal.log` is still written to disk

### StarRocks version
 - 3.2

**Comment by kevincai** [comment]
as a quick workaround, you can set 
`internal_log_modules = somejunkname` in fe.conf to disable the internal log write to internal.log, and will fall back to SYSLOG.

**Comment by dengliu** [comment]
Thanks @kevincai . It works!
