### ISSUE TITLE
array 数据类型，做聚合，能实现吗？

### ISSUE THREAD

**Issue by BigData-YC** [StarRocks/starrocks#4827]
或者是array数据类型转string ，再做聚合操作，能实现吗？？？

CREATE TABLE `test` (
  `id` int(11) NOT NULL COMMENT "主键",
  `age` int(11) NULL COMMENT "年龄",
  `citys` ARRAY<VARCHAR(30)> NULL COMMENT "城市"
)

SELECT group_concat(case (citys as string))
FROM test
GROUP BY age

**Comment by imay** [comment]
This will be supported in version 2.2. StarRocks will support array_agg() which a aggregate some arrays in one array.
