### ISSUE TITLE
`information_schema.partitions` view is empty when partitioned table is present

### ISSUE THREAD

**Issue by j-bennet** [StarRocks/starrocks#48463]
`information_schema.partitions` view is supposed to contain information on table partitions:

https://docs.starrocks.io/docs/reference/information_schema/partitions/

However, it's empty when a partitioned table is created (see steps).

### Steps to reproduce the behavior (Required)

SQL taken from the documentation here:

https://docs.starrocks.io/docs/3.0/table_design/Data_distribution/#partitioning-methods

```sql
CREATE TABLE site_access (
    event_day DATETIME NOT NULL,
    site_id INT DEFAULT '10',
    city_code VARCHAR(100),
    user_name VARCHAR(32) DEFAULT '',
    pv BIGINT DEFAULT '0'
)
DUPLICATE KEY(event_day, site_id, city_code, user_name)
PARTITION BY date_trunc('day', event_day)
DISTRIBUTED BY HASH(event_day, site_id);

INSERT INTO site_access VALUES 
("2023-02-26 20:12:04",002,"New York","Sam Smith",1),
("2023-02-27 21:06:54",001,"Los Angeles","Taylor Swift",1);

select * from information_schema.partitions;
```

### Expected behavior (Required)

There should be two partitions listed.

### Real behavior (Required)

Empty result is returned from `SELECT`.

### StarRocks version (Required)

 - You can get the StarRocks version by executing SQL `select current_version()`
 - 3.3.0-19a3f66

**Comment by starrocks-xupeng** [comment]
if you want to check partition info, you should use `information_schema.partitions_meta`
