### ISSUE TITLE
Stream Load transaction interface does not generate a label.

### ISSUE THREAD

**Issue by jkim650** [StarRocks/starrocks#48465]
### Steps to reproduce the behavior (Required)
1. `CREATE DATABASE IF NOT EXISTS test_db;`
2. `CREATE TABLE IF NOT EXISTS test_db.test_table (id INT NOT NULL) ENGINE=OLAP PROPERTIES ("replication_num" = "1");`
3. `curl --location-trusted -uroot: -H "Expect: 100-continue" -H "db: test_db" -H "table: test_table" -XPOST http://localhost:8030/api/transaction/begin -v`

### Expected behavior (Required)
Starrocks returns `"Status": "OK"` with a generated `"Label"` as documented in https://docs.starrocks.io/docs/loading/Stream_Load_transaction_interface/#precautions.

### Real behavior (Required)
Starrocks returned `"Status": "FAILED"` with `empty label` message.
```
{
  "Status": "FAILED",
  "Message": "class com.starrocks.common.UserException: empty label."
}
```

### StarRocks version (Required)
 - 3.2

**Comment by tracymacding** [comment]
3.2.x?

**Comment by banmoy** [comment]
This should be a bug, and I will fix it later. Could you first specify the label explicitly as a workaround?

**Comment by chaoyli** [comment]
3.2.4 @tracymacding

**Comment by jkim650** [comment]
> This should be a bug, and I will fix it later. Could you first specify the label explicitly as a workaround?

Sure. Thanks.

**Comment by banmoy** [comment]
@jkim650 I checks the current implementation of transaction stream load again, and it actually relies on the user provided label at begin. The behavior is as expected. So I will fix the wrong document description.
