### ISSUE TITLE
Adding metrics and audit log for resource group to improve observability【Moderate】

### ISSUE THREAD

**Issue by Dshadowzh** [StarRocks/starrocks#4847]
# Requirement Description

Adding metrics and audit log for resource group to improve observability. 
1. Add metrics for resource group. for example, add cpu_cost, mem_usage, concurency, fuse_time in per-resource group level. 
2. Add more information to display which resource group does the query run, and whether it's fused in the audit log .

# Mentor
@laotan332 

# Registration procedure

**Step 1.** Add a comment when you sign up. The comment can be a brief self-introduction and reason for signing up, including what you do, what you're good at, what you're interested in and your technology stack, and how familiar you are with StarRocks. Example:

> I pick! My name is Johnny. I am from StarRocks and I have been working on database kernel development for 1 year. I am interested in OLAP, good at C++ programming, and have been using StarRocks for 6 months. I chose to solve this issue because I am familiar with execution engine.

**Step 2.** On your WeChat, add the StarRocks community assistant "**_StarRocks-1_**" as a WeChat friend and leave your GitHub ID. The assistant will invite you to a WeChat group based on the issue you picked.

**Step 3.** The mentor will communicate with all the participants who picked this issue and assign the task to the best match. 

# Before you start
1. Read the StarRocks [GitHub workflow](https://github.com/StarRocks/community/blob/main/Contributors/guide/workflow.md) carefully, which provides the configurations of BE and FE and describes how to submit a pull request.
2. To learn more about StarRocks, read [StarRocks documentation](https://github.com/StarRocks/docs/blob/main/TOC.md).

# Pull request requirements

1. After you complete code development, upload the code to the StarRocks code repo as a pull request (PR).

  - PR title format: **[SR GeekCamp] + PR title**
  - Labels ：[Geek Camp 2022/feature]
2. After you submit your PR, comment on the status of your PR submission as requested under the Pinned Issue [[StarRocks geek Camp 2022] ](https://github.com/StarRocks/starrocks/issues/4008)page.

  - Comment format: **"I have finished Issue #" + PR link id**

**Comment by wuqiao** [comment]
@only2yangcao

**Comment by only2yangcao** [comment]
I am YangCao from shopline, I have been working in big data for 4 years and am very interested in OLAP. I have used OLAP engines such as kylin, presto, and doris, and have been using starrocks for 2 months. I am very happy to be in charge of the research and development of this issue, and hope to work closely with the starrocks community in the next few years.
