### ISSUE TITLE
print queryProfileStr into fe.audit.log

### ISSUE THREAD

**Issue by dyp12** [StarRocks/starrocks#48484]
## Enhancement
fe just save the latest 500 queryInfo.
but In the production environment, every second there are many query, the query information we need can easily expire
I have an idea，print queryProfileStr  into fe.audit.log, collect through by plugin

**Comment by kevincai** [comment]
check about the `enable_collect_query_detail_info`, https://docs.starrocks.io/docs/3.2/administration/management/FE_configuration/#enable_collect_query_detail_info

this allows the query profile logged into fe.profile.log

**Comment by murphyatwork** [comment]
yeah, profile is too large to be put into audit, it's already into the fe.profile.log
