### ISSUE TITLE
Need to add build arch info when showing FE/BE version

### ISSUE THREAD

**Issue by nshangyiming** [StarRocks/starrocks#48575]
- [x] https://github.com/StarRocks/starrocks/pull/48613
- [x] https://github.com/StarRocks/starrocks/pull/48614
- [x] https://github.com/StarRocks/starrocks/pull/48572

## Feature request

**Is your feature request related to a problem? Please describe.**

User can rely on this info to determin whether it's the right package to run on current host.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kevincai** [comment]
Actually user will get a `exec format error` when running an incorrect arch package before the binary itself can tell the arch info.

**Comment by nshangyiming** [comment]
@kevincai i know that, this is just some prevention methods to avoid the situation you mentioned as much as possible.
