### ISSUE TITLE
Zero width assertion Support

### ISSUE THREAD

**Issue by jxzdoing** [StarRocks/starrocks#4865]
Zero-width assertions are our most common feature, used to extract matching text from a string. It is a form of regular expression used to find something that comes before or after (but does not include) something, and has four forms, as follows:
(? = XXX)- matches the first part of a word ending in XXX.
(?< = XXX)- matches the second half of words beginning with XXX.
(? ! XXX) - example: \ d {3} (? ! \d) Matches three digits, which cannot be followed by a number.
(? <! XXX) - example: (?<! [A-z])\d{7} matches seven digits that are not preceded by a lowercase letter.

It is supported in Hive，This feature is expected to be supported in Doris soon.

**Comment by Dshadowzh** [comment]
Thanks for advising, would you like to contribute this feature?

**Comment by jxzdoing** [comment]
I‘d love to，but As i know，the engine of regular expression is written by C or C++(The reference is Google's package)，I'm not familiar with C or C++, so I'm afraid I can't implement this feature.

**Comment by jxzdoing** [comment]
> Thanks for advising, would you like to contribute this feature?

I‘d love to，but As i know，the engine of regular expression is written by C or C++(The reference is Google's package)，I'm not familiar with C or C++, so I'm afraid I can't implement this feature.

**Comment by jxzdoing** [comment]
may i ask is the feature has completed？

**Comment by stdpain** [comment]
I'm working on it. and found the solution. could you provide the function name reference? @jxzdoing

**Comment by jxzdoing** [comment]
> I'm working on it. and found the solution. could you provide the function name reference? @jxzdoing

No function name, just a way of writing regular expressions. It's the same way that regular expressions are written.

`select "abc" regexp("(?=xxxx)")`

**Comment by stdpain** [comment]
maybe it's not a good idea. we prefer a function name

**Comment by stdpain** [comment]
@Dshadowzh @wangsimo0

**Comment by jxzdoing** [comment]
> maybe it's not a good idea. we prefer a function name

it's also not function name in hive, example as follows：
![image](https://user-images.githubusercontent.com/16585537/230582432-05cd3a97-7817-4394-b257-f6de2b7261e4.png)

it's more like a kind of "Syntactic sugar", starrocks's syntax parser convert this kind of writing to normal regular expression then execute it

**Comment by stdpain** [comment]
We may prioritize support "zero width assertion" (look-around assertions) via functions
