### ISSUE TITLE
[bug]stream load in agg table with bitmap type failed

### ISSUE THREAD

**Issue by aaawuanjun** [StarRocks/starrocks#4879]
### Steps to reproduce the behavior
1. create database and table
> create database bitmapdb;
> CREATE TABLE `tbl_tag_bitmapagg` (
>   `tagname` varchar(65533) NOT NULL COMMENT "标签名称",
>   `tagvalue` varchar(65533) NOT NULL COMMENT "标签值",
>   `userid` bitmap BITMAP_UNION NOT NULL COMMENT "访问用户id"
> ) ENGINE=OLAP
> AGGREGATE KEY(`tagname`, `tagvalue`)
> COMMENT "OLAP"
> DISTRIBUTED BY HASH(`tagname`) BUCKETS 1
> PROPERTIES (
> "replication_num" = "1",
> "in_memory" = "false",
> "storage_format" = "DEFAULT"
> );

2. json data(simpeData content)

> {
>     "tagname": "持有产品", "tagvalue": "保险", "userid": 12
> }

3. stream load data
curl --http0.9 --location-trusted -u root:123 -H "columns:c1,c2,c3,tagname=c1,tagvalue=c2,userid=to_bitmap(c3)" -H "label:bitmap123" -H "format: json" -H "jsonpaths: [\"$.tagname\",\"$.tagvalue\",\"$.userid\"]" -T simpleData http://127.0.0.1:8030/api/bitmapdb/tbl_tag_bitmapagg/_stream_load

### Expected behavior
stream load data to agg table success

### Real behavior
be core dump
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/35732071/162189141-94fc6941-ccc2-4ebd-b04e-4f59b634d8d1.png">

be.WARNING and be.INFO
> F0407 19:21:26.552070 40809 types.h:82] Check failed: len >= 1 (-1 vs. 1)

### StarRocks version 
2.1.1

**Comment by aaawuanjun** [comment]
oK, CAN U give the Correct posture of stream load, i will try on anther env.

**Comment by rickif** [comment]
I just use the case and version you provide but the crash do not occur.So I wonder whether the test case or software version is correct.
