### ISSUE TITLE
开箱盲查以及SQL解析能否优化

### ISSUE THREAD

**Issue by wangfuxu** [StarRocks/starrocks#48870]
![1721873105008](https://github.com/user-attachments/assets/4a86765b-ebd7-4931-817d-2bfe4d2d1743)
数据一致，配置一致情况下，同样的sql在sr和doris盲查速度对比，版本sr3.3.0 ，doris2.1.

SQL解析问题：
不能对where条件的类型自动转换，比如where UserId = '123',不能自动推断为where UserId = 123

还有就是select字段起别名后查询会不一致，比如select   sum(order)  as order ....where order > 12。查询出来的结果也是不对劲的，需要换成 select   sum(order)  as order1 ....where order1> 12，原表有的字段名不能被用来起别名

**Comment by kevincai** [comment]
please continue update your findings in one single issue for the same topic. #48664

**Comment by chenminghua8** [comment]
@wangfuxu 能否将测试语句及测试数据发出来以便把问题复现并分析？

**Comment by wangfuxu** [comment]
> @wangfuxu 能否将测试语句及测试数据发出来以便把问题复现并分析？通常简单的查询测试StarRocks的响应为0.02-0.05秒，1.4秒确实不正常。

所有我说了是开箱盲测。。。
