### ISSUE TITLE
存算分离缓存盘主键存储能否优化清理策略

### ISSUE THREAD

**Issue by wangfuxu** [StarRocks/starrocks#48954]
缓存盘一定时间膨胀后，磁盘的主键缓存占比+数据缓存占比会逼近90%（数据存储占比我设置的66，还不是80），根据生产环境反馈，在缓存到达90%时，cn节点会自动重启。
现在不得不手动定时清理主键缓存，有点笨拙和一定风险。

![image](https://github.com/user-attachments/assets/fddc8d95-89ac-49ca-aa04-2d2af358d7ac)

手动清理的时候cpu也会直线下降

**Comment by tracymacding** [comment]
We will release cloud native pk index in future version (after 3.3.2) which pk index can be persisted into object storage. I think this can be the best solution, I suggest you try this :)
