### ISSUE TITLE
In shared data mode, when the Partitioned Prefix feature is enabled, the S3 storage path of the table is displayed incorrectly

### ISSUE THREAD

**Issue by seanmeng2022** [StarRocks/starrocks#48995]
### Steps to reproduce the behavior (Required)
1. 
CREATE STORAGE VOLUME s3_volume
TYPE = S3
LOCATIONS = ("s3://xxxx")
PROPERTIES
(
    "aws.s3.region" = "us-east-1",
    "aws.s3.endpoint" = "https://s3.us-east-1.amazonaws.com",
    "aws.s3.use_aws_sdk_default_behavior" = "false",
    "aws.s3.use_instance_profile" = "false",
    "aws.s3.access_key" = "xxxxxxxxx",
    "aws.s3.secret_key" = "xxxxxxxxx",
    "aws.s3.enable_partitioned_prefix" = "true", 
    "aws.s3.num_partitioned_prefix" = "1024"
);

2.
Insert Data

3.
show proc  "/dbs/tpcds100";

### Expected behavior (Required)
| TableId | TableName | StoragePath |
| --- | --- | --- |
| 16942 | partition_name | s3://starrocks-volume/133/9d829e5c-3a3f-44a1-8be8-f2719941138c/db16172/16942 |
| 16435 | date_dim | s3://starrocks-volume/23/9d829e5c-3a3f-44a1-8be8-f2719941138c/db16172/16435 |
| 16431 | inventory | s3://starrocks-volume/24/9d829e5c-3a3f-44a1-8be8-f2719941138c/db16172/16431 |
| 16947 | web_site | s3://starrocks-volume/232/9d829e5c-3a3f-44a1-8be8-f2719941138c/db16172/16947 |

### Real behavior (Required)
| TableId | TableName | StoragePath |
| --- | --- | --- |
| 16942 | partition_name | s3://starrocks-volume/19d829e5c-3a3f-44a1-8be8-f2719941138c/db16172/16942 |
| 16435 | date_dim | s3://starrocks-volume/9d829e5c-3a3f-44a1-8be8-f2719941138c/db16172/16435 |
| 16431 | inventory | s3://starrocks-volume/9d829e5c-3a3f-44a1-8be8-f2719941138c/db16172/16431 |
| 16947 | web_site | s3://starrocks-volume/9d829e5c-3a3f-44a1-8be8-f2719941138c/db16172/16947 |

### StarRocks version (Required)
 - 3.2.9

**Comment by kevincai** [comment]
For a certain table, its data can be spread to several prefixes, the prefix is determined down to partition level. It makes no way to have a determined prefix for a table.

Will add the path prefix info down to partition level, so the storagePath info can be shown correctly for the partition.

**Comment by kevincai** [comment]
Actually the information ca be retrieved from `information_schema.partitions_meta`, try following sql

```sql
SELECT * FROM information_schema.partitions_meta WHERE table_name = 'partition_name' 
```

There is a column named `STORAGE_PATH`, it will provide you the actual storage path used in a partitioned_prefix enabled storage volume scenario.
