### ISSUE TITLE
flink-connector-starrocks  support for Flink 1.19

### ISSUE THREAD

**Issue by mozhou-tech** [StarRocks/starrocks#49118]
flink-connector-starrocks  support for Flink 1.19

## Feature request

**Is your feature request related to a problem? Please describe.**
flink-connector-starrocks  support for Flink 1.19

https://mvnrepository.com/artifact/com.starrocks/flink-connector-starrocks

**Describe the solution you'd like**
no

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by Dshadowzh** [comment]
It better to move this issue into https://github.com/StarRocks/starrocks-connector-for-apache-flink

**Comment by Dshadowzh** [comment]
https://github.com/StarRocks/starrocks-connector-for-apache-flink/pull/379
