### ISSUE TITLE
BE crash when turn on enable_filter_unused_columns_in_scan_stage

### ISSUE THREAD

**Issue by wangruin** [StarRocks/starrocks#4916]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `metrics_detail` (
  `tags_id` int(11) NULL COMMENT "",
  `timestamp` datetime NULL COMMENT "",
  `value` double SUM NULL COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`tags_id`, `timestamp`)
COMMENT "OLAP"
PARTITION BY RANGE(`timestamp`)
(PARTITION p20200704 VALUES [('0000-01-01 00:00:00'), ('2020-07-05 00:00:00')))
DISTRIBUTED BY HASH(`tags_id`) BUCKETS 32
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
2. select     subq_0.c0 as c0,    subq_0.c0 as c1 from    (select           case when ref_0.tags_id <= ref_0.tags_id then ref_0.timestamp else ref_0.timestamp end
           as c0       from          sqlsmith.metrics_detail as ref_0       where ref_0.value is NULL) as subq_0 where (subq_0.c0 is not NULL)    or (cast(nullif(cast(nullif(case when cast(null as DOUBLE) > cast(null as DOUBLE) then e() else e() end           ,         positive(           cast(case when cast(null as VARCHAR) <> cast(null as VARCHAR) then cast(null as DOUBLE) else cast(null as DOUBLE) end              as DOUBLE))) as DOUBLE),       sqrt(         cast(cast(null as DOUBLE) as DOUBLE))) as DOUBLE) <= cast(null as DOUBLE)) limit 93;

### Expected behavior (Required)
Query returns correctly

### Real behavior (Required)
```
start time: Fri Apr 8 15:47:27 CST 2022
*** Aborted at 1649404150 (unix time) try "date -d @1649404150" if you are using GNU date ***
PC: @          0x1aebd6b starrocks::vectorized::SegmentIterator::_finish_late_materialization()
*** SIGSEGV (@0xb9) received by PID 14340 (TID 0x7fdf589d8700) from PID 185; stack trace: ***
    @     0x7fdf6e20c5f0 (unknown)
    @          0x1aebd6b starrocks::vectorized::SegmentIterator::_finish_late_materialization()
    @          0x1af2b8d starrocks::vectorized::SegmentIterator::_do_get_next()
    @          0x1af5961 starrocks::vectorized::SegmentIterator::do_get_next()
    @          0x1b52ed2 starrocks::vectorized::ProjectionIterator::do_get_next()
    @          0x1e9f3aa starrocks::SegmentIteratorWrapper::do_get_next()
    @          0x1b7cb7b starrocks::vectorized::TimedChunkIterator::do_get_next()
    @          0x1b7706e starrocks::vectorized::TabletReader::do_get_next()
    @          0x1b52ed2 starrocks::vectorized::ProjectionIterator::do_get_next()
    @          0x2797e34 starrocks::vectorized::TabletScanner::get_chunk()
    @          0x24ca115 starrocks::vectorized::OlapScanNode::_scanner_thread()
    @          0x1ec99f0 starrocks::PriorityThreadPool::work_thread()
    @          0x3d20187 thread_proxy
    @     0x7fdf6e204e65 start_thread
    @     0x7fdf6d81f88d __clone
    @                0x0 (unknown)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
branch-2.2 release 46db7d9

**Comment by laotan332** [comment]
set enable_filter_unused_columns_in_scan_stage = true;

**Comment by wangruin** [comment]
1. CREATE TABLE `primary_table` (
  `k1` datetime NOT NULL COMMENT "",
  `k2` varchar(65533) NOT NULL COMMENT "",
  `k3` varchar(65533) NOT NULL COMMENT "",
  `k4` boolean NOT NULL COMMENT "",
  `v1` tinyint(4) NOT NULL COMMENT "",
  `v2` smallint(6) NOT NULL COMMENT "",
  `v3` int(11) NOT NULL COMMENT "",
  `v4` double NOT NULL COMMENT "",
  `v5` decimal128(27, 9) NOT NULL COMMENT ""
) ENGINE=OLAP
PRIMARY KEY(`k1`, `k2`, `k3`, `k4`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`) BUCKETS 3
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
2. select   subq_0.c3 as c0,   subq_0.c7 as c1 from   (     select       ref_0.v1 as c0,       ref_0.v2 as c1,       ref_0.v1 as c2,       ref_0.k1 as c3,       ref_0.v5 as c4,       ref_0.v4 as c5,       ref_0.k2 as c6,       case         when (true)         and (           (             (ref_0.k3 = ref_0.k3)             or (ref_0.v5 >= ref_0.v5)           )
 and (ref_0.v5 <= ref_0.v4)         ) then ref_0.k1         else ref_0.k1       end as c7,       1 as c8,       ref_0.v5 as c9     from       primary_table as ref_0     where       ref_0.v2 is not NULL   ) as subq_0 where   pi() < subq_0.c5
limit   30;

```
*** Aborted at 1650014309 (unix time) try "date -d @1650014309" if you are using GNU date ***
PC: @          0x1af4a5b starrocks::vectorized::SegmentIterator::_finish_late_materialization()
*** SIGSEGV (@0xb8) received by PID 195380 (TID 0x7f88fdbac700) from PID 184; stack trace: ***
    @     0x7f89294355f0 (unknown)
    @          0x1af4a5b starrocks::vectorized::SegmentIterator::_finish_late_materialization()
    @          0x1afb86d starrocks::vectorized::SegmentIterator::_do_get_next()
    @          0x1afe6f1 starrocks::vectorized::SegmentIterator::do_get_next()
    @          0x1b5bc42 starrocks::vectorized::ProjectionIterator::do_get_next()
    @          0x1ea9fca starrocks::SegmentIteratorWrapper::do_get_next()
    @          0x1b8594b starrocks::vectorized::TimedChunkIterator::do_get_next()
    @          0x1b7fe3e starrocks::vectorized::TabletReader::do_get_next()
    @          0x2834c8c starrocks::pipeline::OlapChunkSource::_read_chunk_from_storage()
    @          0x283529e starrocks::pipeline::OlapChunkSource::buffer_next_batch_chunks_blocking()
    @          0x26d5d27 _ZNSt17_Function_handlerIFvvEZN9starrocks8pipeline12ScanOperator18_trigger_next_scanEPNS1_12RuntimeStateEiEUlvE0_E9_M_invokeERKSt9_Any_data
    @          0x1ed4850 starrocks::PriorityThreadPool::work_thread()
    @          0x3d40187 thread_proxy
    @     0x7f892942de65 start_thread
    @     0x7f8928a4888d __clone
    @                0x0 (unknown)
```

**Comment by wangruin** [comment]
1. CREATE TABLE `test_cross_join_20` (
  `id_int` int(11) NOT NULL COMMENT "",
  `id_double` double NOT NULL COMMENT "",
  `id_varchar` varchar(100) NOT NULL COMMENT "",
  `id_datetime` datetime NOT NULL COMMENT "",
  `id_decimal` decimal128(20, 3) NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`id_int`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id_int`) BUCKETS 1
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
2. select   subq_0.c3 as c0,   subq_0.c3 as c1 from   (     select       ref_0.id_decimal as c0,       pi() as c1,       ref_0.id_double as c2,       ref_0.id_varchar as c3,       ref_0.id_double as c4,       ref_0.id_int as c5     from   test_cross_join_20 as ref_0     where       ref_0.id_int <> 70   ) as subq_0 where   subq_0.c4 is NULL;

```
*** Aborted at 1650109779 (unix time) try "date -d @1650109779" if you are using GNU date ***
PC: @          0x1af0beb starrocks::vectorized::SegmentIterator::_finish_late_materialization()
*** SIGSEGV (@0xba) received by PID 30994 (TID 0x7f254a1ac700) from PID 186; stack trace: ***
    @     0x7f2575bdc5f0 (unknown)
    @          0x1af0beb starrocks::vectorized::SegmentIterator::_finish_late_materialization()
    @          0x1af79fd starrocks::vectorized::SegmentIterator::_do_get_next()
    @          0x1afa881 starrocks::vectorized::SegmentIterator::do_get_next()
    @          0x1b57fc2 starrocks::vectorized::ProjectionIterator::do_get_next()
    @          0x1ea666a starrocks::SegmentIteratorWrapper::do_get_next()
    @          0x1b81d0b starrocks::vectorized::TimedChunkIterator::do_get_next()
    @          0x1b7c1fe starrocks::vectorized::TabletReader::do_get_next()
    @          0x28307fc starrocks::pipeline::OlapChunkSource::_read_chunk_from_storage()
    @          0x2830e0e starrocks::pipeline::OlapChunkSource::buffer_next_batch_chunks_blocking()
    @          0x26cb1c7 _ZNSt17_Function_handlerIFvvEZN9starrocks8pipeline12ScanOperator18_trigger_next_scanEPNS1_12RuntimeStateEiEUlvE0_E9_M_invokeERKSt9_Any_data
    @          0x1ecd900 starrocks::PriorityThreadPool::work_thread()
    @          0x3d48187 thread_proxy
    @     0x7f2575bd4e65 start_thread
    @     0x7f25751ef88d __clone
    @                0x0 (unknown)
```

branch-2.2 release 2f51014
