### ISSUE TITLE
transmit chunk rpc failed when turn on resource_group

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#4932]
### Steps to reproduce the behavior (Required)
```
1. load 1t data for tpch
2. turn on resource_group
3. excute query sql concurrently
```
### Expected behavior (Required)
`query ok`
### Real behavior (Required)
`ERROR 1064 (HY000) at line 1: transmit chunk rpc failed`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`890a1cca`

**Comment by stdpain** [comment]
closed by #5072
