### ISSUE TITLE
run ssb Q4.1 failed  with hive external table, if hive table don't has  column stats info

### ISSUE THREAD

**Issue by sandflee** [StarRocks/starrocks#4942]
### Steps to reproduce the behavior (Required)
1. generate ssb benchmark data with factor == 1 and add it to hive table with text format,  customer table format is: 
```
CREATE TABLE if not exists CUSTOMER
(
  C_CUSTKEY      INTEGER ,
  C_NAME         VARCHAR(25) ,
  C_ADDRESS      VARCHAR(25) ,
  C_CITY         VARCHAR(10) ,
  C_NATION       VARCHAR(15) ,
  C_REGION       VARCHAR(12) ,
  C_PHONE        VARCHAR(15) ,
  C_MKTSEGMENT   VARCHAR(10)
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' STORED AS TEXTFILE;
 ```
2. using trino to create parquet data from the original  text data,   with column stats collect disabled
trino-cli-361 --server xx --catalog xx  --schema $database --debug --user=xx  --session="bm_hive.collect_column_statistics_on_write=false" --execute "create table if not exists $table WITH (format = 'parquet') as select * from xx.$table;"
3. create starrocks external hive table, like:

```
CREATE TABLE if not exists customer
(
  c_custkey      INTEGER ,
  c_name         VARCHAR(25) ,
  c_address      VARCHAR(25) ,
  c_city         VARCHAR(10) ,
  c_nation       VARCHAR(15) ,
  c_region       VARCHAR(12) ,
  c_phone        VARCHAR(15) ,
  c_mktsegment   VARCHAR(10)
)
ENGINE=HIVE
PROPERTIES (
  "resource" = "hive_xx",
  "database" = "ssb_1g",
  "table" = "customer"
);
```
5.   query Q4.1 :
mysql -h 127.0.0.1 -P9030 -uroot -Dxxx < queries.origin/Q4.1.sql

### Expected behavior (Required)
normal output with few seconds

### Real behavior (Required)
after a few minutes: query failed with the output:
ERROR 1064 (HY000) at line 3: Memory of query_pool exceed limit.  Used: 144923839488, Limit: 147658580950. Mem usage has exceed the limit of query pool

### StarRocks version (Required)
2.1.3 0881cb2

### other info
1. if enable  columns stats , every thing  works fine even using a larger data with factor 1000.
and here is the explain info ,
[1g.plan.stats.log](https://github.com/StarRocks/starrocks/files/8459034/1g.plan.stats.log)
[1g.plan.notstats.log](https://github.com/StarRocks/starrocks/files/8459033/1g.plan.notstats.log)

**Comment by DorianZheng** [comment]
this issue is not reproducible under branch-2.2
