### ISSUE TITLE
Build starrocks failed in version-3.1.14

### ISSUE THREAD

**Issue by xiangran0327** [StarRocks/starrocks#49440]
### StarRocks version (Required)
3.1.14

### Real behavior (Required)
Build starrocks failed. Below is a screenshot of the error.

<img width="1280" alt="build_error" src="https://github.com/user-attachments/assets/914125e6-6a1a-40db-a238-161f3bc458f9">
The error occurs in /starrocks/be/src/common/daemon. cpp, line 187.

**Comment by kevincai** [comment]
@xiangran0327 which dev-env image tag are you using?

**Comment by xiangran0327** [comment]
> @xiangran0327您使用哪个 dev-env 图像标签？

starrocks/dev-env-centos7:3.1.5 in docker hub

**Comment by xiangran0327** [comment]
> @xiangran0327 which dev-env image tag are you using?

starrocks/dev-env-centos7:3.1.5 in docker hub

**Comment by kevincai** [comment]
> > @xiangran0327 which dev-env image tag are you using?
> 
> starrocks/dev-env-centos7:3.1.5 in docker hub

please use the corresponding tag for the build. use `starrocks/dev-env-centos7:3.1.14` for source code `3.1.14`

**Comment by xiangran0327** [comment]
> > > @xiangran0327 which dev-env image tag are you using?
> > 
> > 
> > starrocks/dev-env-centos7:3.1.5 in docker hub
> 
> please use the corresponding tag for the build. use `starrocks/dev-env-centos7:3.1.14` for source code `3.1.14`

Build successfully with starrocks/dev-env-centos7:3.1.14. Thanks!
