### ISSUE TITLE
Is there a bug in multiplying numbers?

### ISSUE THREAD

**Issue by ClareGuoBin** [StarRocks/starrocks#49533]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Expected behavior (Required)
Give me the correct data instead of null when 55.021556532820414780 * 10.000000000000000000.

When 10 has 17 decimal places, it is normal, but 18 decimal places is abnormal
<img width="664" alt="image" src="https://github.com/user-attachments/assets/37d17682-5a20-4a36-8270-b91a37ce166e">

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - +-------------------+
| current_version() |
+-------------------+
| 2.5.10 9feb716    |
+-------------------+

**Comment by LiShuMing** [comment]
This may be caused by decimal overflow because decimal in Starrocks only supports 38 precision(256 precision is not supported yet).

You may cast to double(either one) to let this case walk aroud.

**Comment by ClareGuoBin** [comment]
thank you for reply. i know it's because of decimal overflow. But I think the result of this multiplication should not be handled as out of precision, because one of the factors of this multiplication happens to have a 0 at the end.
