### ISSUE TITLE
start be and show error while loading shared libraries: libbfd-2.38-system.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by LuWei-HUST** [StarRocks/starrocks#50226]
### Steps to reproduce the behavior (Required)
1. sudo ./be/bin/start_be.sh --daemon

### Expected behavior (Required)
be start

### Real behavior (Required)
be.out: error while loading shared libraries: libbfd-2.38-system.so: cannot open shared object file: No such file or directory

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - StarRocks-3.1.14

**Comment by kevincai** [comment]
try to install `libbinutils` in your system.

**Comment by dbj-incom** [comment]
installing libbinutils does not fix this issue.

However, I noticed the latest version is `libbfd-2.42-system.so`

So the version mismatch might be the cause of the problem.

**Comment by kevincai** [comment]
which operating system are you on? try run `lld be/lib/starrocks_be' and paste the output here.

**Comment by dbj-incom** [comment]
I created a symbolic link to point to the newer version of the library, and this workaround resolved the issue for me:

sudo ln -s /usr/lib/x86_64-linux-gnu/libbfd-2.42-system.so /usr/lib/x86_64-linux-gnu/libbfd-2.38-system.so

**Comment by kevincai** [comment]
shall not run it on ubuntu 20.04, not supported.

**Comment by LuWei-HUST** [comment]
3.2.9可以跑，不管了

**Comment by kevincai** [comment]
close for now.

**Comment by Physis21** [comment]
> sudo ln -s /usr/lib/x86_64-linux-gnu/libbfd-2.42-system.so /usr/lib/x86_64-linux-gnu/libbfd-2.38-system.so

This worked for me, thank you so much!
