### ISSUE TITLE
[BUG] a bug of be crash 

### ISSUE THREAD

**Issue by guoxiaolongzte** [StarRocks/starrocks#50304]
### Steps to reproduce the behavior (Required)
**query:**
select avg(ctr)
from
(
    select  recall_nid
    from
    (
        select  userid,
                trigger_id,
                read_duration,
                b.news_id as recall_nid,
                score,
                row_number() over(partition by userid, trigger_id order by score desc) as score_rn
        from
        (
            select  userid,
                    newsid,
                    read_duration,
                    rn
            from
            (
                select  userid,
                        newsid,
                        read_duration,
                        row_number() over(partition by userid order by read_duration desc) as rn
                from ai_alg_feature.dw_feednews_feature_wide_table_hi
                where day >= '2024-08-22' and day <= '2024-08-23' and service = 'SL-old' and read_duration > 0 and article_type = 3
                -- and userid in ('860032040425011', '860032040516694')
            ) t1
            where rn <= 30
        ) a
        join
        (
            select  key as trigger_id,
                    value news_id,
                    score
            from ai_browser_info.da_sl_item_sim_result_hourly
            where day = '2024-08-26' and hour = '13' and category = 'itemCF_video'
        ) b
        on a.newsid = b.trigger_id
    ) c
    where score_rn < 3
) tmp1
join
(
    select  newsid, count(*) as exp_cnt,
            sum(clicked) as clk_cnt,
            sum(clicked) /  count(*) as ctr
    from ai_alg_feature.dw_feednews_feature_wide_table_hi
    where day = '2024-08-24' and service = 'SL-old' 
    group by newsid
) tmp2
on tmp1.recall_nid = tmp2.newsid;

### Real behavior (Required)
be crash
*** Aborted at 1724738198 (unix time) try "date -d @1724738198" if you are using GNU date ***
PC: @          0x34936cb _ZN14pdqsort_detail12pdqsort_loopIN9__gnu_cxx17__normal_iteratorIPN9starrocks17InlinePermuteItemIdEESt6vectorIS5_SaIS5_EEEEZNS3_L19sort_and_tie_helperIZNS3_12ColumnSorter8do_visitIdEENS3_6StatusERKNS3_21FixedLengthColumnBaseIT_EEEUlRKS5_SL_E_S9_EESE_RKSt6atomicIbEPKNS3_6ColumnEbRT0_RS7_IhSaIhEESG_St4pairIiiEbmPmEUlSG_SU_E0_Lb0EEEvSG_SG_SU_ib
*** SIGSEGV (@0x7efdeb2fb000) received by PID 309852 (TID 0x7f0adc36f700) from PID 18446744073360355328; stack trace: ***
    @          0x6227bc2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f0b879705e9 PosixSignals::chained_handler()
    @     0x7f0b8797103e JVM_handle_linux_signal
    @     0x7f0b861725e0 (unknown)
    @          0x34936cb _ZN14pdqsort_detail12pdqsort_loopIN9__gnu_cxx17__normal_iteratorIPN9starrocks17InlinePermuteItemIdEESt6vectorIS5_SaIS5_EEEEZNS3_L19sort_and_tie_helperIZNS3_12ColumnSorter8do_visitIdEENS3_6StatusERKNS3_21FixedLengthColumnBaseIT_EEEUlRKS5_SL_E_S9_EESE_RKSt6atomicIbEPKNS3_6ColumnEbRT0_RS7_IhSaIhEESG_St4pairIiiEbmPmEUlSG_SU_E0_Lb0EEEvSG_SG_SU_ib
    @          0x34d0c78 starrocks::ColumnSorter::do_visit<>()
    @          0x34d0f96 starrocks::ColumnVisitorAdapter<>::visit()
    @          0x290aa0f starrocks::ColumnFactory<>::accept()
    @          0x34c85af starrocks::ColumnVisitorAdapter<>::visit()
    @          0x31acc8c starrocks::ColumnFactory<>::accept()
    @          0x34542b6 starrocks::sort_and_tie_column()
    @          0x3454c3b starrocks::sort_and_tie_columns()
    @          0x33e6e67 starrocks::ChunksSorterFullSort::_partial_sort()
    @          0x33e7381 starrocks::ChunksSorterFullSort::update()
    @          0x35973a6 starrocks::pipeline::PartitionSortSinkOperator::push_chunk()
    @          0x35dbfa4 starrocks::pipeline::PipelineDriver::process()
    @          0x35cdb5e starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x2bd294c starrocks::ThreadPool::dispatch_thread()
    @          0x2bcc5ca starrocks::Thread::supervise_thread()
    @     0x7f0b8616ae25 start_thread
    @     0x7f0b85e9834d __clone
    @                0x0 (unknown)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 **- version: 3.2.5**

**Comment by stdpain** [comment]
dup with https://github.com/StarRocks/starrocks/issues/30758

**Comment by stdpain** [comment]
missed cp to 3.2 will be fixed in next release 
https://github.com/StarRocks/starrocks/pull/51846
