### ISSUE TITLE
docker run starRocks，FE service query port is NOT alive yet 

### ISSUE THREAD

**Issue by LinMingQiang** [StarRocks/starrocks#50443]
relation to  : https://github.com/StarRocks/starrocks/issues/29990

With the same step to run container.

1. docker pull starrocks/allin1-ubuntu:latest

2.  docker run -p 9030:9030 -p 8030:8030 -p 8040:8040 --security-opt seccomp=unconfined -itd --name quickstart starrocks/allin1-ubuntu

3. docker exec -it quickstart mysql -P 9030 -h 127.0.0.1 -u root --prompt="StarRocks > "
->  ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:9030' (111)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by kevincai** [comment]
please attach logs under /opt/data/starrocks/fe/log/, specifically the `fe.out` and the `fe.log`

**Comment by LinMingQiang** [comment]
<img width="1254" alt="image" src="https://github.com/user-attachments/assets/615fbfb1-29d3-4945-92a6-27263c6b128b">

**Comment by LinMingQiang** [comment]
<img width="575" alt="image" src="https://github.com/user-attachments/assets/0c9c76df-dc08-488b-a4fe-d0601af03d63">

**Comment by LinMingQiang** [comment]
It can be started normally, It is caused by insufficient memory of the container.
