### ISSUE TITLE
Cannot start fe in Mac environment.

### ISSUE THREAD

**Issue by LinMingQiang** [StarRocks/starrocks#50505]
Mac env  exec start_fe.sh :  

commond : 
 ```
./bin/start_fe.sh

or 

bash ./bin/start_fe.sh

or 

sh ./bin/start_fe.sh
```

ERR msg : 
```
bin/start_fe.sh: line 228: syntax error near unexpected token `>'
bin/start_fe.sh: line 228: `    exec &>> $LOG_FILE'
```

### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by kevincai** [comment]
Good catch. it is a bash4 feature, not portable on bash3.

B.t.w., starrocks frontend/backend is not tested to run on mac os natively, it may or may not fail.
