### ISSUE TITLE
Window function not suppor bitmap ？

### ISSUE THREAD

**Issue by daxiongll** [StarRocks/starrocks#5065]
The requirement of multi-day retention is a common requirement. If you can use the window function to implement it, it will be very simple, but it is not supported at present.
![image](https://user-images.githubusercontent.com/29703785/163267404-4d5e17df-98d6-454d-b844-6ee42ecbebce.png)

**Comment by kangkaisen** [comment]
@daxiongll Hi， could you send your full SQL, and explain how do you use window function do multi-day retention, thanks.

**Comment by wangsimo0** [comment]
Hi, we support retention funciton now, will this be helpful? https://docs.starrocks.com/en-us/main/sql-reference/sql-functions/aggregate-functions/retention

**Comment by daxiongll** [comment]
> Hi, we support retention funciton now, will this be helpful? https://docs.starrocks.com/en-us/main/sql-reference/sql-functions/aggregate-functions/retention

yes，we useing the   retention funciton now!!!
