### ISSUE TITLE
Is there any way to shrink the BE cluster to a single node?

### ISSUE THREAD

**Issue by glenmock** [StarRocks/starrocks#50681]
**Is there any way to shrink the BE cluster to a single node?**

exec sql:

**ALTER SYSTEM DECOMMISSION backend "10.441.50.13:9050";**

error: 
**SQL 错误 [1064] [42000]: Unexpected exception: It will cause insufficient BE number if these BEs are decommissioned because the table _statistics_.column_statistics requires 3 replicas.**

cluster info:
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=Generator content="Microsoft Excel">

</head>
<body>

BackendId | IP | HeartbeatPort | BePort | HttpPort | BrpcPort | LastStartTime | LastHeartbeat | Alive | SystemDecommissioned | ClusterDecommissioned | TabletNum | DataUsedCapacity | AvailCapacity | TotalCapacity | UsedPct | MaxDiskUsedPct | ErrMsg | Version | Status | DataTotalCapacity | DataUsedPct | CpuCores | NumRunningQueries | MemUsedPct | CpuUsedPct
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
10007 | 10.441.50.13 | 9050 | 9060 | 8040 | 8060 | 2024-9-2 15:52 | 2024-9-4 11:32 | TRUE | FALSE | FALSE | 72 | 296.714 MB | 31.991 GB | 39.980 GB | 19.98% | 19.98% |   | 3.1.4-0c4b2a3 | {"lastSuccessReportTabletsTime":"2024-09-04 11:32:18"} | 32.280 GB | 0.90% | 8 | 0 | 4.94% | 0.00%
10006 | 10.441.50.14 | 9050 | 9060 | 8040 | 8060 | 2024-9-2 15:52 | 2024-9-4 11:32 | TRUE | FALSE | FALSE | 68 | 514.842 MB | 14.965 GB | 46.969 GB | 68.14% | 68.14% |   | 3.1.4-0c4b2a3 | {"lastSuccessReportTabletsTime":"2024-09-04 11:32:17"} | 15.468 GB | 3.25% | 4 | 0 | 3.42% | 0.00%
10005 | 10.441.50.15 | 9050 | 9060 | 8040 | 8060 | 2024-9-2 15:52 | 2024-9-4 11:32 | TRUE | FALSE | FALSE | 72 | 296.642 MB | 37.252 GB | 46.969 GB | 20.69% | 20.69% |   | 3.1.4-0c4b2a3 | {"lastSuccessReportTabletsTime":"2024-09-04 11:32:12"} | 37.541 GB | 0.77% | 4 | 0 | 3.99% | 0.00%

</body>

</html>

**Comment by kevincai** [comment]
have to change all existing tables's replication_num from 3 to 1, and then shrink the cluster nodes.
