### ISSUE TITLE
cloud_native_hdfs_url is invalid

### ISSUE THREAD

**Issue by snownarrow** [StarRocks/starrocks#50769]
### Steps to reproduce the behavior (Required)
![image](https://github.com/user-attachments/assets/a9d6155f-b27e-4f90-b562-09edf5b512f0)
![image](https://github.com/user-attachments/assets/1aa54064-d013-4bec-a330-30a14f1b4df2)
### Expected behavior (Required)
在3.3.0版本fe配置使用cloud_native_hdfs_url = hdfs://172.16.12.15:8020/user/starrocks， fe节点可以正常启动，通过3.3.0初始化后再升级到3.3.2版本也是正常的
但是直接使用3.3.2版本进行初始化部署，fe配置使用cloud_native_hdfs_url = hdfs://172.16.12.15:8020/user/starrocks则会抛出异常，看代码3.3.2版本对存储配置进行了有效性判断，加了一个端口的判断，hdfs类型的url中带了端口就会抛异常，不带端口则可以正常运行，这个判断应该是不合适的，我不是开发者，我猜这个判断应该是需要从uri.getPort() != -1 ,改成 uri.getPort() == -1
### Real behavior (Required)
cloud_native_hdfs_url 需要支持端口配置，例如hdfs://172.16.12.15:8020/user/starrocks

### StarRocks version (Required)
3.3.2

**Comment by kevincai** [comment]
confirmed to be an issue. will fix it.
