### ISSUE TITLE
Does StarRocks have plans to support JSON Index?

### ISSUE THREAD

**Issue by INNOCENT-BOY** [StarRocks/starrocks#50774]
## Feature request

**Is your feature request related to a problem? Please describe.**

We are big data team from Cisco. We have some semi-structure data. We use pinot to store those data and add json index to increate query performance. So we want to use StarRocks as next-generation olap-engine. So we wonder whether and when SR to support JSON Index.

**Comment by INNOCENT-BOY** [comment]
Thanks for you quick reply. Does sr release 3.3.0 have this feature?

**Comment by wangsimo0** [comment]
yeah sure, I recommend you test with v3.3.3, it has some new enhancements.

**Comment by INNOCENT-BOY** [comment]
Thanks

**Comment by INNOCENT-BOY** [comment]
By the way, if we want to increase query performance as such sql: where a > 20, Which type of index is more appropriate to use?
