### ISSUE TITLE
SR使用 UDTF 函数，创建成功，执行失败。异常： errorCode=2001 errorMessage:Channel inactive error!, host: unknown

### ISSUE THREAD

**Issue by Msimplehub** [StarRocks/starrocks#50770]
环境：Docker image :starrocks/allin1-ubuntu:3.1-latest

be.out:
*** Aborted at 1725549595 (unix time) try "date -d @1725549595" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0xe) received by PID 21467 (TID 0xffff14c09580) from PID 14; stack trace: ***
    @          0x7816810 google::(anonymous namespace)::FailureSignalHandler()
    @     0xffffa9c264e8 os::Linux::chained_handler()
    @     0xffffa9c2c084 JVM_handle_linux_signal
    @     0xffffa9c1f38c signalHandler()
    @     0xffffaa3b27a0 ([vdso]+0x79f)
    @     0xffffa962a550 AccessInternal::PostRuntimeDispatch<>::oop_access_barrier()
    @     0xffffa9966be4 jni_GetStringUTFChars
    @          0x6561c74 starrocks::JVMFunctionHelper::sliceVal()
    @          0x656cf24 starrocks::append_jvalue()
    @          0x6016a34 starrocks::JavaUDTFFunction::process()
    @          0x5ff5040 starrocks::pipeline::TableFunctionOperator::_process_table_function()
    @          0x5ff65a0 starrocks::pipeline::TableFunctionOperator::pull_chunk()
    @          0x5be7354 starrocks::pipeline::PipelineDriver::process()
    @          0x632bce8 starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x66415ac starrocks::ThreadPool::dispatch_thread()
    @          0x663a92c starrocks::Thread::supervise_thread()
    @     0xffffa8f3d5c8 (unknown)
    @     0xffffa8fa5edc (unknown)
start time: Thu Sep  5 23:19:57 CST 2024, server uptime:  23:19:57 up 5 days,  6:24,  0 users,  load average: 3.20, 3.34, 3.17

**Comment by stdpain** [comment]
closed by https://github.com/StarRocks/starrocks/pull/50615
