### ISSUE TITLE
Incorrect Query Result In Prepare Statement

### ISSUE THREAD

**Issue by ShaoxunLi** [StarRocks/starrocks#50956]
### Steps to reproduce the behavior (Required)

![image](https://github.com/user-attachments/assets/2e4b4576-f518-437c-93e7-1e1337ce6e8e)

### Expected behavior (Required)
return 1, 2, 3

### Real behavior (Required)
return 3, 3, 3

**Comment by ShaoxunLi** [comment]
I've been using the prepare function recently and found some problems. I'd like to discuss them with the relevant developers.
How can I contact them?

**Comment by awesomeleo** [comment]
I meet the same issue.
@Jay-ju   @decster  @packy92  @murphyatwork  @liubotao  Could anyone help  to fix it？ Thanks.

**Comment by awesomeleo** [comment]
> I meet the same issue. @Jay-ju @decster @packy92 @murphyatwork @liubotao Could anyone help to fix it？ Thanks.

Maybe Sr treat '?' as the same column name?

**Comment by ShaoxunLi** [comment]
> > I meet the same issue. @Jay-ju @decster @packy92 @murphyatwork @liubotao Could anyone help to fix it？ Thanks.
> 
> Maybe Sr treat '?' as the same column name?

yes, i have found this cause by debugging
