### ISSUE TITLE
Backup rename timeout error

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks#50989]
### Steps to reproduce the behavior (Required)
Error: Fail to rename file
Source: s3a://sss_879158/020000000000011c5944ad1dbbcfc5f88c123e81e2cc1fba_0.dat.part
Target: s3a://sss8/020000000000011c5944ad1dbbcfc5f88c123e81e2cc1fba_0.dat.9ace0c9794abda71dcc52a3162c26232
Message: Fail to copy from src to target, msg: curlCode: 28, Timeout was reached

### Expected behavior (Required)
No error.
Potential fix could be using checksum to check ensure the integrity of the uploaded file
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by srlch** [comment]
https://github.com/StarRocks/starrocks/pull/48860 introduce a individual param to adjust the rename timeout, will try to optimize this problem ASAP.

**Comment by kevincai** [comment]
fixed in https://github.com/StarRocks/starrocks/pull/52394, rename op is removed if the backup repository is an S3-compatible storage.
