### ISSUE TITLE
StarRocks FE频繁出现无leader状态

### ISSUE THREAD

**Issue by huoarter** [StarRocks/starrocks#50999]
目前发现以下这几个版本，一直有个bug就是，部署集群过一晚上之后，show frontends就没有leader的，所有fe都显示为follower。 但集群似乎一直可用
https://forum.mirrorship.cn/t/topic/13777

### StarRocks version (Required)
3.3.0/3.3.2/3.3.3

**Comment by gengjun-git** [comment]
Do you still have this problem in your environment?

**Comment by huoarter** [comment]
> Do you still have this problem in your environment?
Yes! 
I found that show frontends displays only follower states, while show proc '/frontends' can show the leader role.
