### ISSUE TITLE
Typo Error

### ISSUE THREAD

**Issue by dekexu** [StarRocks/starrocks#50993]
### Steps to reproduce the behavior (Required)
Typo Error , change LIMMIT to LIMIT
### Expected behavior (Required)
LIMMIT
### Real behavior (Required)
LIMIT
### StarRocks version (Required)
https://github.com/StarRocks/starrocks/blob/4b057ba03ce5e4d00e45aa078cb3d8519b529b17/docs/zh/sql-reference/sql-statements/table_bucket_part_index/SELECT.md?plain=1#L464

**Comment by kevincai** [comment]
@EsoragotoSpirit
