### ISSUE TITLE
materialized view update

### ISSUE THREAD

**Issue by linweifeng** [StarRocks/starrocks#51107]
现在的 case 如下：每天有一个事实表 t，记为 date(分区字段), pid(分桶字段), play_cnt

现在我们要统计pid 的最大播放次数。select max(play_cnt) from t where pid = 1;

在表上做一个物化视图:select max(play_cnt) from t group by pid;（物化视图是没有分区的，只有分桶。）

理论上，上一次物化视图的结果跟新增的分区可以直接计算出新的物化视图，但是目前观测结果不是，而是每次全量重算。(使用命令 show materialized views，看last_refresh_base_refresh_partitions是显示全部分区，而last_refresh_duration 这个执行时间随着分区数量不断上升而上升)

**Comment by wangsimo0** [comment]
if you only calculate max you can use sync mv. pls refer to the document.
