### ISSUE TITLE
Where does the starcache binary come from that starrocks compilation relies on?

### ISSUE THREAD

**Issue by loong-hy** [StarRocks/starrocks#51151]
Hello developers, I compiled starrocks on loongarch, which depends on starcache, for X86 and ARM, and downloaded the compiled binaries. I use starrocks repository inside starcache, but compiling starrocks gives me an error.

The error message is as follows:

`
In file included from /home/beckhuang/starrocks-3.3.2-for-toolset10/be/src/block_cache/block_cache.h:20,
                 from /home/beckhuang/starrocks-3.3.2-for-toolset10/be/src/common/daemon.cpp:39:
/home/beckhuang/starrocks-3.3.2-for-toolset10/be/src/block_cache/kv_cache.h:33:36: error: ‘ObjectHandle’ in namespace ‘starrocks::starcache’ does not name a type
   33 | using DataCacheHandle = starcache::ObjectHandle;
      |                                    ^~~~~~~~~~~~
/home/beckhuang/starrocks-3.3.2-for-toolset10/be/src/block_cache/kv_cache.h:34:37: error: ‘CacheMetrics’ in namespace ‘starrocks::starcache’ does not name a type
   34 | using DataCacheMetrics = starcache::CacheMetrics;
      |                                     ^~~~~~~~~~~~
/home/beckhuang/starrocks-3.3.2-for-toolset10/be/src/block_cache/kv_cache.h:35:36: error: ‘CacheStatus’ in namespace ‘starrocks::starcache’ does not name a type
   35 | using DataCacheStatus = starcache::CacheStatus;
      |                                    ^~~~~~~~~~~
/home/beckhuang/starrocks-3.3.2-for-toolset10/be/src/block_cache/kv_cache.h:57:33: error: ‘DataCacheHandle’ has not been declared
   57 |                                 DataCacheHandle* handle, WriteCacheOptions* options) = 0;
      |                                 ^~~~~~~~~~~~~~~
/home/beckhuang/starrocks-3.3.2-for-toolset10/be/src/block_cache/kv_cache.h:64:56: error: ‘DataCacheHandle’ has not been declared
   64 |     virtual Status read_object(const std::string& key, DataCacheHandle* handle, ReadCacheOptions* options) = 0;
      |                                                        ^~~~~~~~~~~~~~~
/home/beckhuang/starrocks-3.3.2-for-toolset10/be/src/block_cache/kv_cache.h:75:19: error: ‘DataCacheMetrics’ does not name a type; did you mean ‘TDataCacheMetrics’?
   75 |     virtual const DataCacheMetrics cache_metrics(int level) = 0;
      |                   ^~~~~~~~~~~~~~~~
      |                   TDataCacheMetrics
In file included from /home/beckhuang/starrocks-3.3.2-for-toolset10/be/src/common/daemon.cpp:39:
/home/beckhuang/starrocks-3.3.2-for-toolset10/be/src/block_cache/block_cache.h:47:25: error: ‘DataCacheHandle’ has not been declared
   47 |                         DataCacheHandle* handle, WriteCacheOptions* options = nullptr);
      |                         ^~~~~~~~~~~~~~~
/home/beckhuang/starrocks-3.3.2-for-toolset10/be/src/block_cache/block_cache.h:60:51: error: ‘DataCacheHandle’ has not been declared
   60 |     Status read_object(const CacheKey& cache_key, DataCacheHandle* handle, ReadCacheOptions* options = nullptr);
      |                                                   ^~~~~~~~~~~~~~~
/home/beckhuang/starrocks-3.3.2-for-toolset10/be/src/block_cache/block_cache.h:78:11: error: ‘DataCacheMetrics’ does not name a type; did you mean ‘TDataCacheMetrics’?
   78 |     const DataCacheMetrics cache_metrics(int level = 0) const;

`

**Comment by kevincai** [comment]
if you compiling source code on v3.3.2, try to use the docker image `starrocks/dev-env-centos7:3.3.2`

**Comment by loong-hy** [comment]
> if you compiling source code on v3.3.2, try to use the docker image `starrocks/dev-env-centos7:3.3.2`

I'm compiling on a new architecture (loongarch) , so I need the starcache source for local compilation。

**Comment by kevincai** [comment]
The source code is not open sourced. you can disable the starcache build with `--without-starcache`

**Comment by loong-hy** [comment]
> The source code is not open sourced. you can disable the starcache build with `--without-starcache`

Hi, I've already done this. How much performance is lost in various operations with cache disabled?

**Comment by kevincai** [comment]
to shared-nothing cluster using the internal table, it won't be any performance lost. the cache is only used in shared-data mode internal table or external catalog query.

**Comment by loong-hy** [comment]
> to shared-nothing cluster using the internal table, it won't be any performance lost. the cache is only used in shared-data mode internal table or external catalog query.

Thanks
