### ISSUE TITLE
BACKUP出错

### ISSUE THREAD

**Issue by 1396689323** [StarRocks/starrocks#5123]
### 备份操作
BACKUP SNAPSHOT test.update_detail
TO hdfs_repo1
ON(update_detail)
PROPERTIES ("type" = "full","timeout" = "3600");

### Expected behavior (Required)
我备份的是一个更新模型的空表
![c0bb34ac123113474df1734fcaa4167](https://user-images.githubusercontent.com/96398822/163555181-64ffbcde-c5fd-4690-8ff4-1dc0ec263901.png)
出现报错
![image](https://user-images.githubusercontent.com/96398822/163555331-481f18f2-1a88-492e-a0bb-6ceb15cd2ea6.png)
帮忙看下是什么问题

### StarRocks version (Required)
 - starrocks2.1

**Comment by jaogoy** [comment]
@meegoo Can you have a look to find the reason?

**Comment by meegoo** [comment]
@1396689323  backup destination file already have exists?
