### ISSUE TITLE
请问下starrocks fe 的yaSSL 1.7.5 缓冲区溢出漏洞怎么处理

### ISSUE THREAD

**Issue by yogboot** [StarRocks/starrocks#51267]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by kevincai** [comment]
yaSSL is not used in StarRocks project

**Comment by yogboot** [comment]
这个是漏洞厂商扫描fe出来的
![image](https://github.com/user-attachments/assets/650cc876-af1e-4434-97e8-7879882ae1b8)
好像是fe里的mysql连接版本是5.1.0，不知道是不是跟版本信息有关

**Comment by yogboot** [comment]
ok,thanks
