### ISSUE TITLE
存算分离版本主键表添加bitmap 类型 发生错误

### ISSUE THREAD

**Issue by caiHX97** [StarRocks/starrocks#51269]
CREATE TABLE test.`test_bitmap` (
 `id` bigint    not null  ,
  `r1_bitmap` bitmap NULL
) ENGINE=OLAP
PRIMARY KEY(`id`)
COMMENT ""
DISTRIBUTED BY HASH(`id`)
PROPERTIES (
"enable_persistent_index" = "true"
);

alter table test.test_bitmap add column `r2_bitmap` bitmap NULL;

存算分离执行上述sql 发生错误

**Comment by kevincai** [comment]
duplicate to #51285
