### ISSUE TITLE
starrocks dialect doesn't return the correct value of the id with autoincrement

### ISSUE THREAD

**Issue by domingoscisci** [StarRocks/starrocks#51472]
Hi everybody,
I've been struggling for several days with the following problem: I have created a `Country` class with a primary key set to autoincrement. When I create an instance of the class, add it to the session, and insert the values into the database, the instance's `id` is set to `'0'`. In the database, the `id` value is correct (e.g., `'1'`). Why isn't the correct `id` being returned? I've also tried using `session.commit()`, but nothing changes.
Can someone help me? Am I missing something?
Best,
Domingo

### Steps to reproduce the behavior (Required)
```python
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, create_engine
from sqlalchemy.orm import Session
from sqlalchemy_utils import create_database

Base = declarative_base()

class Country(Base):
  __tablename__ = "dim_country"

  id_country    = Column(Integer(), primary_key=True, autoincrement=True)
  country_code  = Column(Integer())
  country_label = Column(String(255))

  def __repr__(self) -> str:
    return (
      f"Country(id_country={self.id_country}, "
      f"country_code={self.country_code}, "
      f"country_label={self.country_label})"
    )

engine = create_engine(
  "starrocks://<user>@<server_ip>:9030/test",
  echo=True
)

create_database(engine.url)

Base.metadata.create_all(engine)

session = Session(bind=engine)

Country1 = Country(
  country_code = 39,
  country_label = "Italy"
)
session.add(Country1)

session.flush()

session_id = Country1.id_country # the result is 0

db_id = session.query(Country).first().id_country # the result is 1

session_id == db_id # False, should be true
```

### Expected behavior (Required)

`session_id` should be equal to `db_id`

### Real behavior (Required)

`session_id` is `0`,  `db_id` is (correctly) equal to `1`

### StarRocks version (Required)
DB: `3.1.15-5625961`
Python library: `1.0.6`
SQLAlchemy: `1.4.54`

**Comment by srlch** [comment]
@domingoscisci Hi, currently, sr does not support return the allocated Id value by SQLAlchemy API. We can only get the id using `session.query(Country).first().id_country`

**Comment by domingoscisci** [comment]
@srlch thanks for your quick reply! I suspected as much, but wanted to be sure. Thank you.
