### ISSUE TITLE
Failed to run starrocks be ubuntu build on ubuntu 18.04

### ISSUE THREAD

**Issue by bayueqiankong** [StarRocks/starrocks#51584]
版本[starrocks-3.3.3]be服务启动失败
运行./be/bin/start_be.sh --daemon后，
查看be.out文件:/media/hdd1/temp/database/starrocks/be/lib/starrocks_be: error while loading shared libraries: libbfd-2.38-system.so: cannot open shared object file: No such file or directory

系统ubuntu18.04
缺少这个“libbfd-2.38-system.so”链接库文件，需要怎么补？

**Comment by rohitrs1983** [comment]
@bayueqiankong please install libbinutils on your system

**Comment by bayueqiankong** [comment]
运行 sudo apt-get install binutils-dev
显示 binutils-dev is already the newest version (2.30-21ubuntu1~18.04.9).
libbinutils 已安装，但仍然不是目标版本，怎么更新到指定版本？

**Comment by kevincai** [comment]
Basically you can't run the binary on ubuntu 18.04 where it was built from ubuntu 22.04.

You can try following ways:
* upgrade your operating system to ubuntu 22.04,
* or run the starrocks in docker env with host OS remaining in 18.04,
* or rebuild from source code on ubuntu 18.04,
* or give a try to run centos7 binary on ubuntu 18.04.
