### ISSUE TITLE
get_applied_rowsets failed, tablet updates is in error state

### ISSUE THREAD

**Issue by chen131311** [StarRocks/starrocks#51795]
### Steps to reproduce the behavior (Required)

StarRocks partial column updates,inserts into a large amount of data, tablet internal error occurs, and the table cannot be queried.

mysql> select * from users_10010_v4_high_v2 where user_id =892391026; ERROR 1064 (HY000): get_applied_rowsets failed, tablet updates is in error state: tablet:18849 actual row size changed after compaction 215171486 -> 186981271tablet:18849 #version:3 [1 2.1@2 2.1] #pending:0 backend:[10.201.2.188](http://10.201.2.188/)

### StarRocks version (Required)
 - StarRocks-3.3.2
 - StarRocks-3.3.3

**Comment by sevev** [comment]
can you send me the be log file?

**Comment by sevev** [comment]
https://github.com/StarRocks/starrocks/pull/51486
