### ISSUE TITLE
聚合函数argMin，argMax支持；Primary Key的物化视图支持；物化视图select sum(a), min(a) from table 支持

### ISSUE THREAD

**Issue by harryhan1989** [StarRocks/starrocks#5180]
## Enhancement
以下3点需求全部基于对股票数据基于时间线实时合成bar数据的需求：
1、argMin, argMax 聚合函数支持
1、Primary Key模式下支持物化视图
2、物化视图支持基于同一个字段的多次聚合，看官方文档“select sum(a), min(a) from table”这个描述的支持

**Comment by jaogoy** [comment]
It's really hard to support Materialize View on Primary Key model, we will think about it later.
About the other two categories, we will put them into plan.

If you can summit some PRs about those features, it's really really great.
