### ISSUE TITLE
Ensure that the data column size of the const column does not exceed 1 to avoid additional computational overhead

### ISSUE THREAD

**Issue by silverbullet233** [StarRocks/starrocks#5186]

**Comment by zombee0** [comment]
I am interested in this issue, and want more details, like where?

**Comment by silverbullet233** [comment]
@zombee0 First of all, please forgive my late reply.

Let me introduce the background to you. UnaryFunction needs to unpack first when processing ConstColumn, and then calculate after getting the data column.(you can look at the implementation and use of the `UnpackConstColumnUnaryFunction`)

Currently we do not strictly check the size of the data column when creating const column, which means that its size may exceed 1. This can lead to unnecessary computations after unpacking. In fact, only the first element of the data column is meaningful, and none of the following should be used.

Back to this issue, we can add DCHECK to the constructor of ConstColumn to check the size of the data column, and we need to sort out all the functions that may return const column to ensure that their data column size does not exceed 1. Typically, ConstColumns are created with `ColumnBuilder::build` and `ConstColumn::create`, you can see where they are used.

If you have any other questions, plz feel free to contact me, I'm very willing to help you solve this issue.

**Comment by zombee0** [comment]
thank you so much，I see what your mean，and i will try to solve this issue

**Comment by zombee0** [comment]
> @zombee0 First of all, please forgive my late reply.
> 
> Let me introduce the background to you. UnaryFunction needs to unpack first when processing ConstColumn, and then calculate after getting the data column.(you can look at the implementation and use of the `UnpackConstColumnUnaryFunction`)
> 
> Currently we do not strictly check the size of the data column when creating const column, which means that its size may exceed 1. This can lead to unnecessary computations after unpacking. In fact, only the first element of the data column is meaningful, and none of the following should be used.
> 
> Back to this issue, we can add DCHECK to the constructor of ConstColumn to check the size of the data column, and we need to sort out all the functions that may return const column to ensure that their data column size does not exceed 1. Typically, ConstColumns are created with `ColumnBuilder::build` and `ConstColumn::create`, you can see where they are used.
> 
> If you have any other questions, plz feel free to contact me, I'm very willing to help you solve this issue.

hi, I had read the code, there are several places where Use the ConstColumn::create with data column that size is more than 1, and ColumnBuilder::build usually used as ColumnBuilder::build(is_all_const(columns)), I can fixed these all by add resize() in ConstColumn Constructor function. Should I analysis the situation one by one on the ConstColumn's data column?

**Comment by zombee0** [comment]
If analysis the ConstColumn's data column one by one, the functions that call ColumnBuilder::build should consider the args's constant attribution first and add a new constant branch.
