### ISSUE TITLE
Unstable result of var_samp decimal function

### ISSUE THREAD

**Issue by yongbingwang** [StarRocks/starrocks#5188]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
 CREATE TABLE `duplicate_table_with_null` ( `k1`  date, `k2`  datetime, `k3`  char(20), `k4`  varchar(20), `k5`  boolean, `k6`  tinyint, `k7`  smallint, `k8`  int, `k9`  bigint, `k10` largeint, `k11` float, `k12` double, `k13` decimal(27,9) ) ENGINE=OLAP DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`) COMMENT "OLAP" DISTRIBUTED BY HASH(`k1`, `k2`, `k3`) BUCKETS 3 PROPERTIES ( "replication_num" = "1", "storage_format" = "v2" );
```
2. INSERT INTO '....'
curl --location-trusted -u root: -T /home/disk1/jenkins/workspace/branch_release/StarRocksTest/lib/../common/data/basic_types_data -XPUT -H label:stream_load_1edb10a4_bd82_11ec_a3b3_00163e0e489a -H column_separator:	 http://xxx:8234/api/test_aggregation_1eda2658_bd82_11ec_a3b3_00163e0e489a/duplicate_table_with_null/_stream_load

3. SELECT  '....'
```
select var_samp(cast(k13 as decimal128)) from duplicate_table_with_null;
```
### Expected behavior (Required)
0.965317670
### Real behavior (Required)
The result is `0.965317669`, but a few minutes later ,the result changed into `0.965317670`.
```
mysql> select var_samp(cast(k13 as decimal128)) from duplicate_table_with_null
    -> ;
+------------------------------------------+
| var_samp(CAST(k13 AS DECIMAL128(38,38))) |
+------------------------------------------+
|                              0.965317669 |
+------------------------------------------+
1 row in set (0.00 sec)

mysql> select var_samp(cast(k13 as decimal128)) from duplicate_table_with_null;
+------------------------------------------+
| var_samp(CAST(k13 AS DECIMAL128(38,38))) |
+------------------------------------------+
|                              0.965317670 |
+------------------------------------------+
1 row in set (0.01 sec)
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 2f51014

**Comment by mofeiatwork** [comment]
According to the `var_samp` algorithm, the result is unstable, depends on the order of input data.

The precision of decimal would lose during the computation of variance, but the order is not determined. 

![image](https://user-images.githubusercontent.com/96611012/173829655-f9378d16-aaab-4f28-8fba-20f36dc20a49.png)
