### ISSUE TITLE
Iceberg catalog - Query specific snapshot

### ISSUE THREAD

**Issue by dorsegal** [StarRocks/starrocks#51881]
## Feature request

**Is your feature request related to a problem? Please describe.**

I have an Iceberg table that gets data from kafka. hance I get a lot of commits per day and every commits create a snapshot.
I created MV on Iceberg table and I see on logs on Iceberg Rest server that Starrocks is asking for all snapshots

`GET /iceberg/v1/main%7Craw/namespaces/db/tables/table?snapshots=all HTTP/1.1" 200 20159`

I can have a lot of snapshots and don't need to get all the information for all of them. it causes high memory on Starrocks CN and Nessie Rest catalog.

**Describe the solution you'd like**

Would like to control getting only latest or specific snapshot.

Perhaps doing it on the create catalog or support doing it in the query itself.
 
**Describe alternatives you've considered**

**Additional context**

**Comment by stephen-shelby** [comment]
thanks for your issue. this is iceberg spec default behavior. ref: https://github.com/apache/iceberg/blob/main/open-api/rest-catalog-open-api.yaml#L935. If you set the snapshotMode to `refs`, and it will still access to all snapshots of main branch default. so I think there is currently no way to solve this problem.
