### ISSUE TITLE
3.3.4 starrocks 查询kudu表时间问题

### ISSUE THREAD

**Issue by SQLMaestroPro** [StarRocks/starrocks#51918]
In one word，only by following the SQL below can the data retrieval, statistics, and display be correct.only by following the SQL below can the data retrieval, statistics, and display be correct.（只有按照如下SQL，才能取数、统计和显示 都正确）

select id,
       hours_sub(createtime, 8)  -- notes: display needs -8 hours（显示正确需要 -8小时）
from kudu_hive_catalog.db_noah.kudu_login a
where a.createtime >= '2024-10-11'  -- notes：>= not needs to process （大于等于却不需要处理）
  and a.createtime < hours_add('2024-10-12', 8) -- notes：< needs +8 hours （小于的话 需要＋8小时）

The reason is that StarRocks is in the Shanghai time zone, while Kudu is in the UTC 0 time zone. 
However, in order to achieve the correct result, the processing is not consistent.

 The requirement is: from the user's perspective, the time handling should be unified (for example, adding or subtracting 8 hours to all), or the best approach would be for StarRocks to handle everything, so that when querying Kudu, users don't need to do anything with the time fields (whether in the SELECT clause or WHERE clause).（
原因是 starrocks是 上海时区，kudu是UTC 0时区，但是为了达到一个正确的结果，处理上不统一； 诉求是：对用户来说，处理时间字段能统一（比如全部都加或者减8小时）或者最好的方式是StarRocks处理好一切，查询kudu时，时间字段（不论在select子句还是where子句）用户什么都不用处理）

**Comment by predator4ann** [comment]
@SQLMaestroPro Thanks for the feedback, I have reproduced the problem and will fix it in these two days.
