### ISSUE TITLE
can't use unnest in create view/create table/insert into

### ISSUE THREAD

**Issue by olayying** [StarRocks/starrocks#5194]
### Steps to reproduce the behavior (Required)
1. CREATE VIEW test AS
SELECT *
FROM (SELECT ['1', '2'] k) a, unnest(k)
2. INSERT INTO a AS  
SELECT *
FROM (SELECT ['1', '2'] k) a, unnest(k)
3. CREATE TABLE a AS
SELECT *
FROM (SELECT ['1', '2'] k) a, unnest(k)

### Real behavior (Required)
[42000][1064] Unresolved table reference 'unnest'

### StarRocks version (Required)
2.1.2 0782ad7

**Comment by imay** [comment]
@kangkaisen PTAL

**Comment by kangkaisen** [comment]
@olayying you could try 2.2 branch or main branch
