### ISSUE TITLE
Trino dialect supports using SELECT DISTINCT with aggregate functions or GROUP BY

### ISSUE THREAD

**Issue by LZGH** [StarRocks/starrocks#51955]
## Feature request

**Is your feature request related to a problem? Please describe.**

There will be an error message when executing sql:select distinct lock_type from sys.fe_locks group by lock_type.
cannot combine SELECT DISTINCT with aggregate functions or GROUP BY.

**Describe the solution you'd like**

Supports the same syntax as trino

**Describe alternatives you've considered**

**Additional context**

**Comment by wangsimo0** [comment]
your feature request is same as https://github.com/StarRocks/starrocks/issues/51714. pls refer to this issue for any updates
