### ISSUE TITLE
Why can only one column be created at a time when creating an index

### ISSUE THREAD

**Issue by HelloSrauker** [StarRocks/starrocks#5200]
I read the official documents.I found that the syntax supports creating multiple column indexes at once

CREATE INDEX index_name ON table_name **(column [, ...],)** [USING BITMAP] [COMMENT'balabala'];

but infact, Errors will be reported in actual use :"index can only apply to a single column"

Why this design，I want an explanation，this a bug or someting?
(I use starrocks v2.1.0)

thank you : )

**Comment by jaogoy** [comment]
We may enhance the grammar in the future
