### ISSUE TITLE
stddev_samp(decimalv2)/var_samp(decimalv2)/variance_samp(decimalv2)/stddev(decimalv2)/var_pop(decimalv2)/std(decimalv2)/variance(decimalv2)/variance_pop(decimalv2) function executed error

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#5209]
### Steps to reproduce the behavior (Required)

1. 
```
CREATE TABLE `duplicate_table_with_null` ( `k1`  date, `k2`  datetime, `k3`  char(20), `k4`  varchar(20), `k5`  boolean, `k6`  tinyint, `k7`  smallint, `k8`  int, `k9`  bigint, `k10` largeint, `k11` float, `k12` double, `k13` decimal(27,9) ) ENGINE=OLAP DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`) COMMENT "OLAP" DISTRIBUTED BY HASH(`k1`, `k2`, `k3`) BUCKETS 3 PROPERTIES ( "replication_num" = "1", "storage_format" = "v2" );
```
2. 
```
curl --location-trusted -u root: -T /home/disk1/jenkins/workspace/branch_release/StarRocksTest/lib/../common/data/basic_types_data -XPUT -H label:stream_load_89df374e_bee1_11ec_9ffc_00163e0e489a -H column_separator:	 http://xxx:8234/api/test_aggregation_89ddba54_bee1_11ec_9ffc_00163e0e489a/duplicate_table_with_null/_stream_load
```
3. 
```
select stddev_samp(k13) from duplicate_table_with_null;
select var_samp(k13) from duplicate_table_with_null;
select variance_samp(k13) from duplicate_table_with_null;
select stddev(k13) from duplicate_table_with_null;
select stddev_pop(k13) from duplicate_table_with_null;
select std(k13) from duplicate_table_with_null;
select variance(k13) from duplicate_table_with_null;
select variance_pop(k13) from duplicate_table_with_null;
select var_pop(k13) from duplicate_table_with_null;


### Expected behavior (Required)
retrun correct result
### Real behavior (Required)
```
mysql> select stddev_samp(k13) from duplicate_table_with_null;
ERROR 1064 (HY000): Invalid agg function plan: stddev_samp
mysql> select var_samp(k13) from duplicate_table_with_null;
ERROR 1064 (HY000): Invalid agg function plan: var_samp
mysql> select variance_samp(k13) from duplicate_table_with_null;
ERROR 1064 (HY000): Invalid agg function plan: variance_samp
mysql> select stddev(k13) from duplicate_table_with_null;
ERROR 1064 (HY000): Invalid agg function plan: stddev
mysql> select stddev_pop(k13) from duplicate_table_with_null;
ERROR 1064 (HY000): Invalid agg function plan: stddev_pop
mysql> select std(k13) from duplicate_table_with_null;
ERROR 1064 (HY000): Invalid agg function plan: std
mysql> select variance(k13) from duplicate_table_with_null;
ERROR 1064 (HY000): Invalid agg function plan: variance
mysql> select variance(k13) from duplicate_table_with_null;
ERROR 1064 (HY000): Invalid agg function plan: variance
mysql> select variance_pop(k13) from duplicate_table_with_null;
ERROR 1064 (HY000): Invalid agg function plan: variance_pop
mysql> select var_pop(k13) from duplicate_table_with_null;
ERROR 1064 (HY000): Invalid agg function plan: var_pop
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.2
5e1777e

**Comment by mofeiatwork** [comment]
Since decimalV2 is deprecated, and this bug has been exists for a long time, we decide to leave it alone.
