### ISSUE TITLE
starrocks docker images

### ISSUE THREAD

**Issue by harryhan1989** [StarRocks/starrocks#5214]
[starrokcs docker images](https://hub.docker.com/repository/docker/harryhan1989/starrokcs)
上面提供了starrokcs多个版本的容器，容器编译方法托管在github上，
提供了开发环境使用docker-compose 案例，以及高可用部署模式案例

**Comment by jaogoy** [comment]
What's the purpose?

@wanpengfei-git what's our current state?

**Comment by harryhan1989** [comment]
企业级k8s方式部署需求很多
