### ISSUE TITLE
After overwriting the hive partition table, an error is reported in the hive appearance query

### ISSUE THREAD

**Issue by huoyue-git** [StarRocks/starrocks#5223]
### Steps to reproduce the behavior (Required)
1. hive enviroment
 create table hive_tbl_test_insert_overwrite_tbl(
         col_tinyint tinyint comment "column tinyint"
        ,col_smallint smallint comment "column smallint"
        ,col_int int comment "column int"
        ,col_integer integer comment "column integer"
        ,col_bigint bigint comment "column bigint"
        ,col_float float comment "column float"
        ,col_double double comment "column double"
        ,col_double_precision double precision comment "column double precision"
        ,col_decimal decimal comment "column decimal"
        ,col_timestamp timestamp comment "column timestamp"
        ,col_date date comment "column date"
        ,col_string string comment "column string"
        ,col_varchar varchar(100) comment "column varchar"
        ,col_binary binary comment "column binary"
        ,col_char char(100) comment "column char"
        ,col_boolean boolean comment "column boolean"
        )
        partitioned by (par_col int)
        clustered by(col_int) sorted by(col_int) into 32 buckets
        row format delimited fields terminated by ','
        stored as orc
        tblproperties("orc.compress"="none");
insert into hive_tbl_test_insert_overwrite_tbl  partition (par_col=1) values (3,3,3,3,3,3.001,30.1,310.1,3110.3,'2021-10-03 12:10:23','2021-10-30','hello world','hi','1110001010101011001001','nihao',true);

create table hive_tbl_test_insert_overwrite_tbl2(
         col_tinyint tinyint comment "column tinyint"
        ,col_smallint smallint comment "column smallint"
        ,col_int int comment "column int"
        ,col_integer integer comment "column integer"
        ,col_bigint bigint comment "column bigint"
        ,col_float float comment "column float"
        ,col_double double comment "column double"
        ,col_double_precision double precision comment "column double precision"
        ,col_decimal decimal comment "column decimal"
        ,col_timestamp timestamp comment "column timestamp"
        ,col_date date comment "column date"
        ,col_string string comment "column string"
        ,col_varchar varchar(100) comment "column varchar"
        ,col_binary binary comment "column binary"
        ,col_char char(100) comment "column char"
        ,col_boolean boolean comment "column boolean"
        )
        partitioned by (par_col int)
        clustered by(col_int) sorted by(col_int) into 32 buckets
        row format delimited fields terminated by ','
        stored as orc
        tblproperties("orc.compress"="none");

insert into hive_tbl_test_insert_overwrite_tbl2  partition (par_col=1) values (1,1,1,1,1,1.001,10.1,110.1,1110.1,'2021-10-01 12:10:23','2021-10-30','hello world','hi','1110001010101011001001','nihao',true);
insert into hive_tbl_test_insert_overwrite_tbl2  partition (par_col=2) values (2,2,2,2,2,2.001,20.1,210.1,2110.2,'2021-10-02 12:10:23','2021-10-30','hello world','hi','1110001010101011001001','nihao',true);

2. starrocks enviroment
create external table ex_hive_tbl_insert_overwrite (
                col_tinyint tinyint comment "column tinyint"
                ,par_col int
                ,col_smallint smallint comment "column smallint"
                ,col_int int comment "column int"
                ,col_integer integer comment "column integer"
                ,col_bigint bigint comment "column bigint"
                ,col_float float comment "column float"
                ,col_double double comment "column double"
                ,col_double_precision double comment "column double precision"
                ,col_decimal decimal comment "column decimal"
                ,col_timestamp datetime comment "column timestamp"
                ,col_date date comment "column date"
                ,col_string varchar(1000) comment "column string"
                ,col_varchar varchar(100) comment "column varchar"
                ,col_binary varchar(1000) comment "column binary"
                ,col_char char(100) comment "column char"
                ,col_boolean boolean comment "column boolean"
            )
            ENGINE=hive
            properties (
                "resource" = "hive_resource_hy",
                "table" = "hive_tbl_test_insert_overwrite_tbl",
                "database" = "hive_test_hy");

3. hive enviroment
insert overwrite table hive_tbl_test_insert_overwrite_tbl select * from hive_tbl_test_insert_overwrite_tbl2;
4.starrocks envitoment
select * from ex_hive_tbl_insert_overwrite;

### Expected behavior (Required)
结果正确，无报错
### Real behavior (Required)
ERROR 1064 (HY000): HdfsOrcScanner::do_open failed. reason = Failed to read hdfs://emr-header-1.cluster-49155:9000/user/hive/warehouse/hive_test_hy.db/hive_tbl_test_insert_overwrite_tbl/par_col=1/000006_0: IO error: fail to hdfsPreadFully hdfs://emr-header-1.cluster-49155:9000/user/hive/warehouse/hive_test_hy.db/hive_tbl_test_insert_overwrite_tbl/par_col=1/000006_0: error=Error(255): Unknown error 255, root_cause=EOFException: End of file reached before reading fully.

Before insert overwrite
![image](https://user-images.githubusercontent.com/91584973/163805284-e1517e94-acf6-4eab-8126-174fe7410030.png)

After insert overwrite
![image](https://user-images.githubusercontent.com/91584973/163805357-8a570064-97c9-4abe-aa33-4c7f8f118df0.png)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+------------------------+
| current_version()      |
+------------------------+
| QA_TEST_MASTER b7a7e39 |
+------------------------+
1 row in set (0.01 sec)

**Comment by stephen-shelby** [comment]
I could reproduce this case when I use hive 3.1.2. but I use 2.X version hive can't execute insert overwrite ddl successfully.
error as follow:
![image](https://user-images.githubusercontent.com/91597003/163990778-3feee489-ba28-40ce-82e0-4af2c32a23db.png)

The main reason for this issue is that this insert overwrite ddl generate two AlterPartitionEvents on partition (par_col = 1) in hive metastore. In both events, `before` and `after` only modify `transient_lastDdlTime` params. we should ignore the `transient_lastDdlTime` params when processing the alterXXevent. So fe couldn't find any modification in partition(par_col=1). When querying the file with length 0 and reading the file_length not equal 0, an exception will be thrown.

**Comment by stephen-shelby** [comment]
I don't think users will use this kind of SQL to insert overwrite partition tables. 
And you can execute refresh external table with partition that abnormal. then you will get a correct result.

**Comment by stephen-shelby** [comment]
the file is 00006_0 before executing insert overwrite. And file is 00001 after ddl.

**Comment by huoyue-git** [comment]
Confirm the problem after communication, it is an unconventional operation and close it
