### ISSUE TITLE
Can't run the docker image allin, beservice core dumped

### ISSUE THREAD

**Issue by CharlieBytesX** [StarRocks/starrocks#52256]
### Steps to reproduce the behavior (Required)
run the docker container from the quickstart

![image](https://github.com/user-attachments/assets/4a0b5d4f-3892-4cc8-a878-69a340da7d9c)

![image](https://github.com/user-attachments/assets/8dabc4ac-c0ee-4b20-ac96-6b02bd23bcd4)

### Expected behavior (Required)
beservice starts

### Real behavior (Required)
beservice does't start and little error message info
2024-10-23 16:28:26,887 INFO exited: beservice (terminated by SIGILL (core dumped); not expected)

### StarRocks version (Required)
 - latest image

**Comment by stdpain** [comment]
```
terminated by SIGILL (core dumped); 
```
https://docs.starrocks.io/docs/deployment/deployment_prerequisites/#cpu

AVX2 instructions is required
