### ISSUE TITLE
When starrocks queries the catalog hive orc table, null filtering fails. Procedure

### ISSUE THREAD

**Issue by mozhou1991** [StarRocks/starrocks#52409]
### Steps to reproduce the behavior (Required)
1.  CREATE TABLE `sr_test_01`(
  `shop_id` string, 
  `tenant_id` string, 
  `sdp_instorage_time` string, 
  `shop_code` string, 
  `shop_status` string)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.orc.OrcSerde' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat'
TBLPROPERTIES (
  'STATS_GENERATED_VIA_STATS_TASK'='workaround for potential lack of HIVE-12730', 
  'auto.purge'='false', 
  'presto_query_id'='20241028_070959_69625_gyxmk', 
  'presto_version'='430', 
  'transient_lastDdlTime'='1730099399')                   <<create table by trino>>
2. ORC数据文件上传不了,  数据内容为:
    +---------+-----------+--------------------+-----------+-------------+
    | shop_id | tenant_id | sdp_instorage_time | shop_code | shop_status |
    +---------+-----------+--------------------+-----------+-------------+
    | 149     | t00002    | 20190412164622976  | CKGHI        |                     |
    | NULL    | a025      | 20201113154652758  | SCORE       | NULL           |
    +---------+-----------+--------------------+-----------+-------------+

3. select shop_id, (shop_id is null) as flag from sr_test_01 where sdp_instorage_time='20201113154652758' ;
    select shop_id, (shop_id is null) as flag from sr_test_01 where sdp_instorage_time='20201113154652758' and shop_id is null;

###Description
![1730165311649](https://github.com/user-attachments/assets/e8952a29-459f-4771-8040-b6319fd89397)

### StarRocks version (Required)
 SR Version:  3.3.4

**Comment by Smith-Cruise** [comment]
I will track it

**Comment by Smith-Cruise** [comment]
It's upstream orc sdk's bug

**Comment by Smith-Cruise** [comment]
fixed in https://github.com/StarRocks/starrocks/pull/52555
