### ISSUE TITLE
2.2 UDAF java

### ISSUE THREAD

**Issue by zhangchunyang19890123** [StarRocks/starrocks#5263]
After compiling branch-2.2, it still can't be adjusted. There are three functions, one can and two can't work. The error information is as follows:
![image](https://user-images.githubusercontent.com/94664833/163952048-e6794a1a-ba1f-41f3-bebf-a0fb61025803.png)
![image](https://user-images.githubusercontent.com/94664833/163952178-dba49de1-d0ea-4d95-842a-b76b2b246648.png)
![image](https://user-images.githubusercontent.com/94664833/163952461-c3d418e8-1361-4168-8d5a-8fe255c0281b.png)

**Comment by imay** [comment]
@stdpain PTAL
