### ISSUE TITLE
new aws s3 client take 18 second after restart be

### ISSUE THREAD

**Issue by hongli-my** [StarRocks/starrocks#5288]
after restart be, first iceberg external table sql take 18s,    find be stuck at send metadata request by tcpdump.
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/8597823/164109628-e7c1608b-fac4-43b8-a537-fcd12c998ef4.png">

### Steps to reproduce the behavior (Required)
1.  create hive/iceberg  external table and data on  cos(tencent s3 storage)
2.  restart be 
3.  tcpdump  network ,

### Expected behavior (Required)
no reuqest to `169.254.169.254`
### StarRocks version (Required)
 -  main
 - branch-2.2

**Comment by dirtysalt** [comment]
Yes, It's because in `aws::ClientConfiguration` ctor, it requests ec2-metadata

```cpp
ClientConfiguration::ClientConfiguration()
{
    setLegacyClientConfigurationParameters(*this);
    retryStrategy = InitRetryStrategy();

    if (region.empty() &&
        Aws::Utils::StringUtils::ToLower(Aws::Environment::GetEnv("AWS_EC2_METADATA_DISABLED").c_str()) != "true")
    {
        auto client = Aws::Internal::GetEC2MetadataClient();
        if (client)
        {
            region = client->GetCurrentRegion();
        }
    }
    if (!region.empty())
    {
        return;
    }
    region = Aws::String(Aws::Region::US_EAST_1);
}
```

We can solev this problem by. `export AWS_EC2_METADATA_DISABLED=true `

And I see in `be/bin/start_be.sh`, we have code to export variables from be.conf

```
export_env_from_conf $STARROCKS_HOME/conf/be.conf
```

**Comment by dirtysalt** [comment]
Looks like we don't need this functionality at all. We can disable it by default.
