### ISSUE TITLE
添加 List 分区语法说明是错误的

### ISSUE THREAD

**Issue by dq1201** [StarRocks/starrocks#52952]
### Steps to reproduce the behavior (Required)
文档链接：https://docs.starrocks.io/zh/docs/sql-reference/sql-statements/table_bucket_part_index/ALTER_TABLE/#%E6%93%8D%E4%BD%9C-partition-%E7%9B%B8%E5%85%B3%E8%AF%AD%E6%B3%95
添加 List 分区语法说明是错误的

### Expected behavior (Required)
![image](https://github.com/user-attachments/assets/e6b44375-9bc2-4b6e-b2e5-5004c5076513)
### Real behavior (Required)
![image](https://github.com/user-attachments/assets/14fe87c0-8a27-46a2-8f2a-e633de4b3457)
可以看下以下的示例：
![image](https://github.com/user-attachments/assets/e39a5bff-f15e-43fa-a0fa-dfc94ef512bd)

### StarRocks version (Required)
3.1.X+

**Comment by Dshadowzh** [comment]
@dq1201  Could you create a pr to fix it?
