### ISSUE TITLE
MySQL Client authentication failed when use kerberos to connect

### ISSUE THREAD

**Issue by stephen-shelby** [StarRocks/starrocks#5307]
### Real behavior (Required)
User exception log:
![image](https://user-images.githubusercontent.com/91597003/164168231-48da43a1-04b2-4d57-9ef9-e695842a5327.png)
Fe has no related log.

Here are the troubleshooting steps
step 1: 
- turn on mysql client kerberos log.
   export AUTHENTICATION_KERBEROS_CLIENT_LOG=5
   you will see the debug log in normal as follow :
   
![image](https://user-images.githubusercontent.com/91597003/164168558-479ab79f-937d-4cde-b45d-3358e2d4910c.png)

When user turn on the mysql client debug log, No related log is displayed on the mysql client.  
I download the same MySQL client through the Oracle address provided by the user. And I reproduce the user case.
Through debugging fe, mysql client also use native_password to auth after build handshake.  The kerberos_authentication should be used in normal. 
**The main way to solve the problem is that add `--plugin-dir` to point to kerberos plugin path when execute connection command.**

step 2:
After step 1, user exception log as follow:
![image](https://user-images.githubusercontent.com/91597003/164170236-8384c5a4-7dda-46e0-b732-93c18ff1465d.png)

main cause : User doesn't create kerberos user when connect to fe.

step 3:
After step 2, user exception log as follow:
![image](https://user-images.githubusercontent.com/91597003/164170546-5f4ef4d1-8d7a-4e0a-a49a-d72ef0e300eb.png)

main cause :  There are some error when mysql client get fe ticket from kdc by using tgt. 
The user used the wrong FE principal . It can work normally after being modified to the correct principal. 

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by jaogoy** [comment]
@stephen-shelby Is there no any problem?

**Comment by stephen-shelby** [comment]
> @stephen-shelby Is there no any problem?

yep
