### ISSUE TITLE
BE crashed when exec query

### ISSUE THREAD

**Issue by long2ice** [StarRocks/starrocks#5311]
The be log:
```
Error to read file: /root/StarRocks/be/storage/.testfile, error: End of file: EOF trying to read 4096 bytes at offset 0
store read/write test file occur IO Error. path=/root/StarRocks/be/storage
meet too many error disks, process exit. max_ratio_allowed=0%, error_disk_count=1, total_disk_count=1
```
### Steps to reproduce the behavior (Required)
Just exec query with load much data

### Expected behavior (Required)
Return data success
### Real behavior (Required)
BE crashed
### StarRocks version (Required)
 - 2.1.3 0881cb2

**Comment by jaogoy** [comment]
@long2ice Have you pushed any PR to solve this issue? or just closed it without any fix?
