### ISSUE TITLE
kudu catalog can't cast field type when join 

### ISSUE THREAD

**Issue by MadBeeDo** [StarRocks/starrocks#53424]
### Steps to reproduce the behavior (Required)
![image](https://github.com/user-attachments/assets/054495ed-637e-4de7-b250-02eb082884e8)

Create a table with a field type bigint in kudu,and create kudu catalog.Run like this:
with a as (
    select
        '0' as fielda
),
b as (
    select
        cast(id as string) as fielda
    from
        kudu_yqz.test111.join1
)
select
    *
from
    a
    inner join b on a.fielda = b.fielda
limit
    10;

Then report an error:
ERROR 1064 (HY000): id's type isn't [Type: string, Type: varchar], it's int64

but in default catalog,no error.

### StarRocks version (Required)
 3.3.5-6d81f75

**Comment by predator4ann** [comment]
@MadBeeDo Thanks to the feedback, there was a problem with type judgment during predicate conversion, we will fix it in the next two days.

**Comment by MadBeeDo** [comment]
@predator4ann this patch didn't compact to any versions. Is there any plan?

**Comment by predator4ann** [comment]
@smartlxh Could you please help review the backport pr? Thanks.
https://github.com/StarRocks/starrocks/pull/53743

**Comment by predator4ann** [comment]
> [@predator4ann](https://github.com/predator4ann) this patch didn't compact to any versions. Is there any plan?

@MadBeeDo 3.5 is already available, but the backport of 3.3 and 3.4 was not successful. We will handle it in the near future.

**Comment by MadBeeDo** [comment]
> > [@predator4ann](https://github.com/predator4ann) this patch didn't compact to any versions. Is there any plan?
> 
> [@MadBeeDo](https://github.com/MadBeeDo) 3.5 is already available, but the backport of 3.3 and 3.4 was not successful. We will handle it in the near future.

@predator4ann  ok thandks.
I noticed that the implementation of 3.5 is different from 3.3 and 3.4. Are the effects of these two the same? If they are the same,I can  directly upgrade to version 3.5

**Comment by predator4ann** [comment]
> > > [@predator4ann](https://github.com/predator4ann) this patch didn't compact to any versions. Is there any plan?
> > 
> > 
> > [@MadBeeDo](https://github.com/MadBeeDo) 3.5 is already available, but the backport of 3.3 and 3.4 was not successful. We will handle it in the near future.
> 
> [@predator4ann](https://github.com/predator4ann) ok thandks. I noticed that the implementation of 3.5 is different from 3.3 and 3.4. Are the effects of these two the same? If they are the same,I can directly upgrade to version 3.5

@MadBeeDo Could you please let me know where the implementation differs between 3.5 and 3.4? Does it refer to the Kudu Catalog?

**Comment by MadBeeDo** [comment]
> > > > [@predator4ann](https://github.com/predator4ann) this patch didn't compact to any versions. Is there any plan?
> > > 
> > > 
> > > [@MadBeeDo](https://github.com/MadBeeDo) 3.5 is already available, but the backport of 3.3 and 3.4 was not successful. We will handle it in the near future.
> > 
> > 
> > [@predator4ann](https://github.com/predator4ann) ok thandks. I noticed that the implementation of 3.5 is different from 3.3 and 3.4. Are the effects of these two the same? If they are the same,I can directly upgrade to version 3.5
> 
> [@MadBeeDo](https://github.com/MadBeeDo) Could you please let me know where the implementation differs between 3.5 and 3.4? Does it refer to the Kudu Catalog?

In KuduPredicateConverter.java, within the getLiteral method:

In versions 3.3 and 3.4, the check for illegal casts is at line 205, using:
      operator instanceof CastOperator  

In version 3.5, this check is relocated to lines 170–173 to handle Illegal cast.

**Comment by predator4ann** [comment]
@MadBeeDo Backporting to 3.4 has been successful, maybe you can refer to it.
