### ISSUE TITLE
Too many compaction configurations

### ISSUE THREAD

**Issue by sduzh** [StarRocks/starrocks#5363]
## Enhancement

There are more than 30 configurations related to compaction defined in the `config.h`, which is too much. We should delete unnecessary configuration items.

**Comment by xiaoyong-z** [comment]
# delete the following compaction configurations
the original number of compaction configurations is 31, now is 22

# 3. add `max_base_compaction_num_singleton_deltas` to the new compaction framework 
CONF_mInt64(max_base_compaction_num_singleton_deltas, "100");

# 7. unused configurations, remove
CONF_mInt32(base_compaction_write_mbytes_per_sec, "5");

# 12. unused configurations, remove
CONF_mInt64(cumulative_compaction_budgeted_bytes, "104857600");

# merge three trace threshold into one, the default value is 60
# 19、
CONF_mInt32(base_compaction_trace_threshold, "120");
# 20、
CONF_mInt32(cumulative_compaction_trace_threshold, "60");
# 20、
CONF_mInt32(update_compaction_trace_threshold, "20");


# 22. use max_compaction_concurrency != 0 to replace it
CONF_mBool(enable_compaction, "true");

# 24. use max_compaction_concurrency to replace it
CONF_mInt32(max_compaction_task_num, "4");


# 25. use cumulative_compaction_num_threads_per_disk to replace it
CONF_mInt32(max_cumulative_compaction_task, "-1");

# 26. use base_compaction_num_threads_per_disk to replace it
CONF_mInt32(max_base_compaction_task, "1");

# 30. remove precent limit
CONF_Int32(compaction_max_memory_limit_percent, "100");

**Comment by jaogoy** [comment]
@xiaoyong-z summit a docs issue to TW, and write an article about what's change to users, reference to https://docs.starrocks.com/zh-cn/main/administration/Configuration

**Comment by xiaoyong-z** [comment]
> @xiaoyong-z summit a docs issue to TW, and write an article about what's change to users, reference to https://docs.starrocks.com/zh-cn/main/administration/Configuration

https://github.com/StarRocks/docs.zh-cn/issues/907
