### ISSUE TITLE
Request to Publish Version 1.2.0 of Python Client on PyPI

### ISSUE THREAD

**Issue by zhangbc97** [StarRocks/starrocks#53682]
Hello StarRocks Team,

I noticed that version 1.2.0 of the StarRocks Python client was merged into the master branch two weeks ago. It would be greatly appreciated if this version could be published on PyPI to facilitate easier installation and updates.

Thank you for considering this request.

**Comment by miomiocat** [comment]
Thank you for your advise.  
The new version has just been released, see https://pypi.org/manage/project/starrocks/release/1.2.0/
