### ISSUE TITLE
[Build-bug] Build sr using docker

### ISSUE THREAD

**Issue by xuhaiL** [StarRocks/starrocks#53713]
I used docker to build the source code based on version 2.5.22 and found that 'be' would not start, I have made a post and did not get a solution

https://forum.mirrorship.cn/t/topic/16245

build image with 
starrocks/dev-env-ubuntu:2.5.22 imageId:4d030159caf7
starrocks/dev-env-ubuntu:2.5-latest imageId: d209181a9300

run `BUILD_TYPE=release ./build.sh`, build success

```shell
bash start_be.sh 
# error
test/be/lib/starrocks_be: error while loading shared libraries: libbfd-2.38-system.so: cannot open shared object file: No such file or directory
```
![image](https://github.com/user-attachments/assets/5785ff03-e354-479a-baa0-03c186270a3a)

**Comment by kevincai** [comment]
if you are using dev-env-ubuntu to build the binary, you have to run it on ubuntu22.04.

This is related to https://github.com/StarRocks/starrocks/pull/50515 which the fix is not backported to earlier branches.

**Comment by xuhaiL** [comment]
> if you are using dev-env-ubuntu to build the binary, you have to run it on ubuntu22.04.
> 
> This is related to #50515 which the fix is not backported to earlier branches.

I'm going to build with ubuntu 22? That seems to defeat the purpose of using docker. If I merge #50515, can I build directly on ubuntu 20?

**Comment by xuhaiL** [comment]
> give a try.

There are still problems

**Comment by xuhaiL** [comment]
After updating this pr, the compiled be can not work in ubuntu 20, can work normally on ubuntu 22, is this the design? @rohitrs1983 @kevincai

**Comment by kevincai** [comment]
this has nothing to do with the  issue, it is just you build a binary with a newer glibc version and try to run it on a older glibc env.

https://www.lightofdawn.org/wiki/wiki.cgi/NewAppsOnOldGlibc

check this article for the difficulties you are facing.

**Comment by xuhaiL** [comment]
If so, all compiling and running will not work on ubuntu 20？

**Comment by kevincai** [comment]
you can build from ground in a ubuntu 20 env or using centos binary to give a try. The centos binary is built with a very old glibc version

**Comment by xuhaiL** [comment]
> you can build from ground in a ubuntu 20 env or using centos binary to give a try. The centos binary is built with a very old glibc version

ok, thk
