### ISSUE TITLE
Can support alluxio file system

### ISSUE THREAD

**Issue by ylhh353** [StarRocks/starrocks#53873]
Can support alluxio file system, we use alluxio agent other file system formats, because flink also supports alluxio protocol, we create paimon table is stored through alluxio, hive bin metadata is also alluxio format. starrocks does not support alluxio. Hope to support alluxio

**Comment by kevincai** [comment]
you can setup alluxio fs just as a compatible hadoop filesystem, the similar way to use hdfs. properly setup the core-site.xml on fe and be nodes
