### ISSUE TITLE
truncate table tbl partition(px)扩展

### ISSUE THREAD

**Issue by yadianxk** [StarRocks/starrocks#5387]
目前对表truncate分区，分区数量可变，但必须全部指定，建议支持对日期分期的表允许指定开头和结束分区后truncate区间内的所有分区。
如
truncate table tbl partition (p20220101,…,p20210105) =
truncate table tbl partition (p20220101, p20220102, p20220103, p20220104, p20210105)

**Comment by jaogoy** [comment]
Good for usability.
Can you summit a PR to solve this requirement?
