### ISSUE TITLE
incomplete support for role management

### ISSUE THREAD

**Issue by padmejin** [StarRocks/starrocks#5389]
Currently starrocks's role management has some obvious bugs or bad designs.

### Steps to reproduce the behavior (Required)
1. CREATE ROLE 'somerole'
2. DROP ROLE 'somerole'
3. SHOW GRANTS FOR 'somerole'

### Expected behavior (Required)
1. Create role successfully.
2. Drop role successfully.
3. Report an error with message suggesting user does not exist.

### Real behavior (Required)
1. Create failed, role name must come without quote.
```sql
mysql> create role 'somerole';
ERROR 1064 (HY000): Syntax error in line 1:
create role 'somerole'
            ^
Encountered: STRING LITERAL
Expected: IDENTIFIER

mysql> create role somerole;
Query OK, 0 rows affected (0.03 sec)
```
2. Drop failed, role name must come without quote.
```
mysql> drop role 'somerole';
ERROR 1064 (HY000): Syntax error in line 1:
drop role 'somerole'
          ^
Encountered: STRING LITERAL
Expected: IDENTIFIER

mysql> drop role somerole;
Query OK, 0 rows affected (0.01 sec)
```
3. Report no error yet show an empty table.
```
mysql> show grants for 'somerole';
+--------------------------------+----------+------------+-------------------+-------------+---------------+------------+---------------+
| UserIdentity                   | Password | AuthPlugin | UserForAuthPlugin | GlobalPrivs | DatabasePrivs | TablePrivs | ResourcePrivs |
+--------------------------------+----------+------------+-------------------+-------------+---------------+------------+---------------+
| 'default_cluster:somerole'@'%' | NULL     | NULL       | NULL              | NULL        | NULL          | NULL       | NULL          |
+--------------------------------+----------+------------+-------------------+-------------+---------------+------------+---------------+
1 row in set (0.00 sec)
```

### StarRocks version (Required)
main

**Comment by lvchenyang-maker** [comment]
![image](https://user-images.githubusercontent.com/57162397/169263307-46a1dd74-4e13-4ec9-b9be-5cf5ae108597.png)

**Comment by lvchenyang-maker** [comment]
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/57162397/169272587-31647f60-31c8-4a2b-9608-dc4b89492cbe.png">
