### ISSUE TITLE
The metadata is growing rapidly

### ISSUE THREAD

**Issue by zxf216** [StarRocks/starrocks#53957]
### Steps to reproduce the behavior (Required)

1. Create a materialized view with the base table partitioned by the RANGE type, and there are a total of 132 partitions.
2. Refresh all partitions every 30 seconds.
3. It is found that the metadata has been growing at a rate of several hundred megabytes per day.

### Expected behavior (Required)

- Although the materialized view is refreshed frequently, it is expected that the metadata data will not increase.

### Real behavior (Required)

1. After checking the Image file, it was found that the property "idToStorageCacheInfo" in the PartitionInfo object contains a large number of objects.
2. It is suspected that it was not cleaned up when deleting old partitions: com.starrocks.catalog.PartitionInfo#dropPartition.

### StarRocks version (Required)
 - 3.3.5

**Comment by kevincai** [comment]
fixed in https://github.com/StarRocks/starrocks/pull/51864

The fix is included in v3.3.6

**Comment by zxf216** [comment]
Okay. Thank you very much.
