### ISSUE TITLE
baidu/palo仓库改名为StarRocks / starrocks吗

### ISSUE THREAD

**Issue by ChPi** [StarRocks/starrocks#54]
baidu/palo我看说明

> 下载说明
> Palo 发行版为基于 Apache Doris 官方 Release 版本的 3 位迭代版本(tags)。包括快速的 Bug 修复和新功能更新。

是改了名字为StarRocks / starrocks吗？

**Comment by WesZhang100** [comment]
百度Palo的开源是Apache Doris。 这个StarRocks是DorisDB的完全开源。
百度Palo有两个分支一个是开源的Apache Doris，另一个是DorisDB。

**Comment by imay** [comment]
StarRocks has nothing to do with baidu/palo.

**Comment by Whojohn** [comment]
# 1. Apache Doris 的关系？
## 1.1 Apache Doris 还能毕业吗？

ps： 根本不敢用啊，要凉啊。
