### ISSUE TITLE
FE config `enable_cloud_native_persistent_index_by_default` failed to take effect while FE leader changed

### ISSUE THREAD

**Issue by wxl24life** [StarRocks/starrocks#54215]
### Steps to reproduce the behavior (Required)
0. create some old version cluster, such as 3.2.x, upgrade to 3.3.x to use cloud native pk index
1. admin set frontend config ("enable_cloud_native_persistent_index_by_default" = "true")
2. roll restart 3 FE node
3. create pk table on newly selected LEADER
```sql
CREATE TABLE orders1 (
    order_id bigint NOT NULL,
    dt date NOT NULL,
    user_id INT NOT NULL,
    good_id INT NOT NULL,
    cnt int NOT NULL,
    revenue int NOT NULL
)
PRIMARY KEY (order_id)
DISTRIBUTED BY HASH (order_id)
;
show create table orders1;
```

### Expected behavior (Required)

`show create table` should have `persistent_index_type` property set to `CLOUD_NATIVE`

### Real behavior (Required)

`show create table` showed `persistent_index_type` property was set to `LOCAL`

### StarRocks version (Required)
 - 3.3.6

**Comment by wxl24life** [comment]
@kevincai please assign this to me, thanks

**Comment by wxl24life** [comment]
This bug is related to #52387

**Comment by luohaha** [comment]
https://github.com/StarRocks/starrocks/pull/54240

**Comment by wxl24life** [comment]
right now, as a workaround manner, users can `set global enable_cloud_native_persistent_index_by_default = true`
