### ISSUE TITLE
Failed to execute the simplest query

### ISSUE THREAD

**Issue by xlxie** [StarRocks/starrocks#543]
I deployed an official pre-build (v 1.18.2), it worked well. When I tried to build branch v1.19 from source code, it could not execute the simplest query.

### Steps to reproduce the behavior (Required)
select 1;

### Expected behavior (Required)
It works.

### Real behavior (Required)

I got this error msg: ERROR 1064 (HY000): there is no scanNode Backend.

I checked be.out and found:
start time: Fri Oct 1 21:46:50 CST 2021
src/tcmalloc.cc:332] Attempt to free invalid pointer 0x681ba40
*** Aborted at 1633096016 (unix time) try "date -d @1633096016" if you are using GNU date ***
PC: @     0x7fabc817d8af __GI_raise
*** SIGABRT (@0x1436380000c4bc) received by PID 50364 (TID 0x7fab7ad67700) from PID 50364; stack trace: ***
    @          0x323b2e2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fabc8e4a5d0 (unknown)
    @     0x7fabc817d8af __GI_raise
    @     0x7fabc817f4aa __GI_abort
    @          0x14e4004 _ZN8tcmalloc3LogENS_7LogModeEPKciNS_7LogItemES3_S3_S3_.cold
    @          0x49e7699 (anonymous namespace)::InvalidFree()
    @          0x1b30129 std::basic_string<>::reserve()
    @          0x2ab3729 starrocks::MysqlResultWriter::process_chunk()
    @          0x2ab4d97 starrocks::MysqlResultWriter::append_chunk()
    @          0x2a95caa starrocks::ResultSink::send_chunk()
    @          0x1a6c5b9 starrocks::PlanFragmentExecutor::_open_internal_vectorized()
    @          0x1a6d079 starrocks::PlanFragmentExecutor::open()
    @          0x1a02cef starrocks::FragmentExecState::execute()
    @          0x1a03f10 starrocks::FragmentMgr::exec_actual()
    @          0x1a0917c std::_Function_handler<>::_M_invoke()
    @          0x1b55444 starrocks::ThreadPool::dispatch_thread()
    @          0x1b638e5 starrocks::Thread::supervise_thread()
    @     0x7fabc8e406ca start_thread
    @     0x7fabc824fedf __GI___clone
    @                0x0 (unknown)

### StarRocks version (Required)
- branch v1.19, commit id: 38c5e52478d234751c189614997df8f9bb7d4a07

Some info about my env:
- Linux h33k11406.sqa.nu8 4.19.91-007.ali4000.alios7.x86_64 #1 SMP Wed Apr 8 16:17:43 CST 2020 x86_64 x86_64 x86_64 GNU/Linux
- gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)

**Comment by imay** [comment]
Looks like issue #233 

Could you please build StarRocks with our [dev-docker](https://hub.docker.com/repository/docker/starrocks/dev-env) to reproduce this problem?

**Comment by xlxie** [comment]
> Looks like issue #233
> 
> Could you please build StarRocks with our [dev-docker](https://hub.docker.com/repository/docker/starrocks/dev-env) to reproduce this problem?

Thanks for your feedback.

I tried the dev-docker and it worked. 

I am going to close this issue and if possible, please provide a detailed build manual for the developers. Thanks!
