### ISSUE TITLE
About DBT adapter

### ISSUE THREAD

**Issue by long2ice** [StarRocks/starrocks#5432]
Hello, we intend to make StarRocks worked with dbt, I found that you plan to support dbt mentioned in https://github.com/StarRocks/starrocks/issues/1244, what's going on now? If it doesn't get released soon, we plan to write one ourselves.

**Comment by Dshadowzh** [comment]
It is still in the design phase. If you have interest in this adapter, maybe we can work together.

**Comment by Dshadowzh** [comment]
https://github.com/StarRocks/dbt-starrocks
