### ISSUE TITLE
为什么 linux 基金会搜索不到 starrocks 呢，什么情况

### ISSUE THREAD

**Issue by digyear** [StarRocks/starrocks#54348]
## Feature request
![Screenshot_20241225_234921_Edge](https://github.com/user-attachments/assets/948e9435-8288-4c96-b442-e903da3ea8b4)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alvin-celerdata** [comment]
You can visit this site https://www.linuxfoundation.org/projects, and choose "AI, ML, Data and Analytics".
And then you scroll down and you will see
![image](https://github.com/user-attachments/assets/fb7bd733-b373-44f3-b482-5c1888299e04)
