### ISSUE TITLE
`TabletManager::get_partition_related_tablets` can be deleted

### ISSUE THREAD

**Issue by imay** [StarRocks/starrocks#5435]
`TabletManager::get_partition_related_tablets` is not used anywhere.
This function can be deleted.

You need to delete function locates in

```
be/src/storage/tablet_manager.cpp
be/src/storage/tablet_manager.h
```

**Comment by shyamrox** [comment]
I'll take this one too.

**Comment by shyamrox** [comment]
This is submitted on Pull Request: https://github.com/StarRocks/starrocks/pull/5510
