### ISSUE TITLE
timer in function is not used, can be removed

### ISSUE THREAD

**Issue by imay** [StarRocks/starrocks#5446]
timer is not used in `StorageEngine::get_all_data_dir_info`.
You should remove `timer` related code in `StorageEngine::get_all_data_dir_info` which locates at be/src/storage/storage_engine.cpp.

**Comment by shyamrox** [comment]
I'll take this one - Submitting pull request shortly.

**Comment by shyamrox** [comment]
Submitted Pull Request: https://github.com/StarRocks/starrocks/pull/5510
Please review :)
