### ISSUE TITLE
Drop database failed sometimes after `routine load`.

### ISSUE THREAD

**Issue by yongbingwang** [StarRocks/starrocks#5448]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
CREATE TABLE `abnormal_date` (
                                `k1` date,
                                `k2` datetime
                              ) ENGINE=OLAP
                              AGGREGATE KEY(`k1`, `k2`)
                              COMMENT "OLAP"
                              DISTRIBUTED BY HASH(`k1`, `k2`) BUCKETS 3
                              PROPERTIES (
                                "replication_num" = "1",
                                "storage_format" = "v2"
                              );
```
2.  ROUTINE LOAD'....'
```
CREATE ROUTINE LOAD strict_mode_95db866a_c346_11ec_8ab6_00163e0e489a on abnormal_date COLUMNS (k1,k2),COLUMNS TERMINATED BY '\t' PROPERTIES ("desired_concurrent_number"="1","max_error_number"="1000","max_batch_interval"="5","strict_mode"="true") FROM KAFKA ("kafka_broker_list"="xxx:9092","kafka_topic"="data-for-abnormal-date","kafka_partitions"="0,1,2,3,4","kafka_offsets"="OFFSET_BEGINNING,OFFSET_BEGINNING,OFFSET_BEGINNING,OFFSET_BEGINNING,OFFSET_BEGINNING");
```
3. Drop database '....'
```
drop database routine_load_95da4af2_c346_11ec_8ab6_00163e0e489a
execute sql error and messages: (1064, 'There are still some transactions in the COMMITTED state waiting to be completed. The database [default_cluster:routine_load_95da4af2_c346_11ec_8ab6_00163e0e489a] cannot be dropped. If you want to forcibly drop(cannot be recovered), please use "DROP database FORCE".'), and time is: 2022-04-24 04:47:48
```
### Expected behavior (Required)
drop database correctly.
### Real behavior (Required)
execute sql error and messages: (1064, 'There are still some transactions in the COMMITTED state waiting to be completed. The database [default_cluster:routine_load_79305082_c27d_11ec_bba4_00163e0e489a] cannot be dropped. If you want to forcibly drop(cannot be recovered), please use "DROP database FORCE".'), and time is: 2022-04-23 04:48:11
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by rickif** [comment]
Since the routine load job is scheduled in background, it would report this error when the drop database operation and the routine load job transaction are simultaneous.
It does not denote any problem of the system and would be OK to retry later.
