### ISSUE TITLE
Support path analysis function

### ISSUE THREAD

**Issue by YangWei1997** [StarRocks/starrocks#5460]
## Feature request

**problem describe**
A set of real-time written log event data contains event numbers, event types, and event time, requires custom match rules (such as: 5 minutes, event type A occurrence 3 after the event type B occurs at least 2 times. Rule It will be changed dynamically.), The output alarm is satisfied.

**Describe the solution**
Using FlinkCep, it is necessary to deal with the dynamic changes of rules and require secondary development.

**Describe alternatives you've considered**
 In real time through Flink data, it is stored in the clickhouse in real time, and whether to meet the rules through the path analysis function (sequencematch).

**Additional context**

**Comment by Dshadowzh** [comment]
There is a window funnel function WIP. https://github.com/StarRocks/starrocks/pull/4985 https://github.com/StarRocks/starrocks/pull/5290
Can you implement path analysis with funnel function? Or you can give a sample to describe how do you use sequencematch function?
