### ISSUE TITLE
Support dbt starrock client?

### ISSUE THREAD

**Issue by dawsongzhao** [StarRocks/starrocks#5463]
## Feature request

**Is your feature request related to a problem? Please describe.**
We use DBT as a data warehouse development tool, and we are also using starrocks. Does starrocks have a plan to support DBT?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Dshadowzh** [comment]
Not yet, but it's WIP. We want to support it in this Q2. 
Would you like to add some description about what function you want to use in DBT with StarRocks?

**Comment by dataders** [comment]
@Dshadowzh have you seen https://github.com/qiulin/dbt-doris yet? Also, hello! I can help with dbt integration if you ever want. Feel free to reach out to me via email or linkedin and we can discuss the dbt intergration
