### ISSUE TITLE
starrocks external table for Greenplum 

### ISSUE THREAD

**Issue by shubifeng** [StarRocks/starrocks#5494]
## Feature request

load data from greenplum to starrocks ( external table)

**Comment by stdpain** [comment]
@shubifeng  It seems greenplum support JDBC protocol. We could create a JDBC or MySQL external table for GP

**Comment by shubifeng** [comment]
GP and MySql  不太一样哦，GP有 instance-->db-->schema-->table ，mysql有 instance-->db-->table。套用mysql外表，结构上就不能通用。

**Comment by stdpain** [comment]
> GP and MySql 不太一样哦，GP有 instance-->db-->schema-->table ，mysql有 instance-->db-->table。套用mysql外表，结构上就不能通用。@[stdpain](https://github.com/stdpain)

@silverbullet233 I remember that our JDBC Extensions can access GP through the JDBC protocol
