### ISSUE TITLE
Failed to call frontend service, host: unknown

### ISSUE THREAD

**Issue by yongbingwang** [StarRocks/starrocks#5549]
update cluster from 2.2 to 2.1.5
### Steps to reproduce the behavior (Required)
1.use information_schema.
2.select.
```
select column_type,column_name,srs_id from columns where table_schema='information_schema' and table_name='columns' and data_type='bigint' limit 1;
```
### Expected behavior (Required)
```
mysql> select column_type,column_name,srs_id                               from columns where table_schema='information_schema' and table_name='columns' and data_type='bigint' limit 1;
+-------------+------------------+--------+
| column_type | column_name      | srs_id |
+-------------+------------------+--------+
| bigint(20)  | ORDINAL_POSITION |   NULL |
+-------------+------------------+--------+
1 row in set (0.97 sec)
```
### Real behavior (Required)
ERROR 1064 (HY000): failed to call frontend service, host: unknown
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - BRANCH_RELEASE 2a5c43f

**Comment by kangkaisen** [comment]
Should be same reason with https://github.com/StarRocks/starrocks/issues/5550
