### ISSUE TITLE
Failed to deploy one BE and one FE node using CTL

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#5562]
### Steps to reproduce the behavior (Required)

premise
SSH mutual trust

1. vim test04.yaml
global:
    user: "starrocks"
    ssh_port: 22

fe_servers:
  - host: 192.168.88.83
    ssh_port: 22
    http_port: 8030
    rpc_port: 9020
    query_port: 9030
    edit_log_port: 9010
    deploy_dir: /opt/starrocks/fe
    meta_dir: /data/starrocks/fe/meta
    log_dir: /data/starrocks/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_level: "INFO"
      sys_log_delete_age: "1d"
be_servers:
  - host: 192.168.88.83
    ssh_port: 22
    be_port: 9060
    webserver_port: 8040
    heartbeat_service_port: 9050
    brpc_port: 8060
    deploy_dir : /opt/starrocks/be
    storage_dir: /data/starrocks/be/storage
    log_dir: /data/starrocks/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
2. Execute on the deployment machine：
./sr-ctl-without-debug cluster deploy test04 v2.0.1 test04.yaml

### Expected behavior (Required)
deploy success
### Real behavior (Required)
deploy failed
![image](https://user-images.githubusercontent.com/57162397/165441814-7a5c8195-3f2d-4696-a43f-77f7db84af47.png)

**Comment by wangtianyi2004** [comment]
@lvchenyang-maker  hello Lv, could you pls raise the pr on the project [GitHub - wangtianyi2004/starrocks-controller](https://github.com/wangtianyi2004/starrocks-controller)

**Comment by wangtianyi2004** [comment]
the yaml file you input query_port: 9030
but the snapshot pic feQueryPort is 9031.
I guess the same issue with https://github.com/StarRocks/starrocks/issues/5569

fixed
