### ISSUE TITLE
CTL deployment with one FE and three BE becomes one FE and one BE ，and fails

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#5569]
### Steps to reproduce the behavior (Required)
premise
SSH mutual trust

vim test04.yaml
global:
    user: "starrocks"
    ssh_port: 22

fe_servers:
  - host: 192.168.88.83
    ssh_port: 22
    http_port: 8031
    rpc_port: 9021
    query_port: 9031
    edit_log_port: 9011
    deploy_dir: /opt/starrocks04/fe
    meta_dir: /data/starrocks04/fe/meta
    log_dir: /data/starrocks04/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_level: "INFO"
      sys_log_delete_age: "1d"

be_servers:
  - host: 192.168.88.84
    ssh_port: 22
    be_port: 9061
    webserver_port: 8041
    heartbeat_service_port: 9051
    brpc_port: 8061
    deploy_dir : /opt/starrocks04/be
    storage_dir: /data/starrocks04/be/storage
    log_dir: /data/starrocks04/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
be_servers:
  - host: 192.168.88.83
    ssh_port: 22
    be_port: 9061
    webserver_port: 8041
    heartbeat_service_port: 9051
    brpc_port: 8061
    deploy_dir : /opt/starrocks04/be
    storage_dir: /data/starrocks04/be/storage
    log_dir: /data/starrocks04/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
be_servers:
  - host: 192.168.88.85
    ssh_port: 22
    be_port: 9061
    webserver_port: 8041
    heartbeat_service_port: 9051
    brpc_port: 8061
    deploy_dir : /opt/starrocks04/be
    storage_dir: /data/starrocks04/be/storage
    log_dir: /data/starrocks04/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
Execute on the deployment machine：
./sr-ctl-without-debug cluster deploy test04 v2.0.1 test04.yaml
Expected behavior (Required)
deploy success

Real behavior (Required)
deploy failed
![image](https://user-images.githubusercontent.com/57162397/165458995-4f8463da-c4e3-4d5f-89b6-14653ce3c113.png)

**Comment by wangtianyi2004** [comment]
the yaml file is not correct. 
pls delete the line ahead host: 192.168.88.83 & host: 192.168.88.85
---------------------------------------------------
priority_networks: 192.168.88.0/24
config:
create_tablet_worker_count: 3
be_servers:                      <<<<<<<<<<<<<<<<<<<<<<<<<< DELETE THIS LINE
host: 192.168.88.83
ssh_port: 22
be_port: 9061
webserver_port: 8041
heartbeat_service_port: 9051
brpc_port: 8061
deploy_dir : /opt/starrocks04/be
storage_dir: /data/starrocks04/be/storage
log_dir: /data/starrocks04/be/log
priority_networks: 192.168.88.0/24
config:
create_tablet_worker_count: 3
be_servers:                 <<<<<<<<<<<<<<<<<<<<<<<<<< DELETE THIS LINE
