### ISSUE TITLE
FE start failed with error: pid file is already locked

### ISSUE THREAD

**Issue by yongbingwang** [StarRocks/starrocks#5580]
### Steps to reproduce the behavior (Required)
![CInVGvKbUb](https://user-images.githubusercontent.com/86867342/165471854-317adb96-aecf-46b0-b68c-c0c86c7f793c.jpg)
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - cf45893

**Comment by frZheng** [comment]
rm -rf fe.pid 
rm -rf doris-meta/process.lock 
restart start_fe.sh

**Comment by xudalei1977** [comment]
How to resovle it? I met the same error when dpeloying starrocks 3.5.1 on kuburnetes.
