### ISSUE TITLE
hive external table on s3 

### ISSUE THREAD

**Issue by chen131311** [StarRocks/starrocks#5586]
## General Question

StarRocks-2.1.3

hive external table on s3

ERROR 1064 (HY000): fail to connect hdfs namenode, name=s3a://******/, err=error=Error(255): Unknown error 255, root_cause=ClassNotFoundException: com.amazonaws.AmazonClientException

![image](https://user-images.githubusercontent.com/42530494/165490127-bc271cf5-6bea-4961-bd6f-8283d97080b2.png)

**Comment by imay** [comment]
@chen131311 You can try version 2.2

**Comment by chen131311** [comment]
@imay  thanks,StarRocks-2.2.0-rc01 works.
