### ISSUE TITLE
Returned 'Socket is closed by peer'  when set fe config.

### ISSUE THREAD

**Issue by yongbingwang** [StarRocks/starrocks#5655]
### Steps to reproduce the behavior (Required)
1. build a cluster with 3 fe (fe1, fe2, fe3).
2. connect to fe1 and execute the command;
```
admin set frontend config ("enable_decimal_v3" = "true");
```
3. restart fe2
4. execute the command again on fe1
```
admin set frontend config ("enable_decimal_v3" = "true");
```

### Expected behavior (Required)
set ok.
### Real behavior (Required)
=>{'status': False, 'msg': (1064, 'set config failed: set config for fe[xxx.xxx.xxx.202] failed: Socket is closed by peer.set config for fe[xxx.xxx.xxx.200] failed: Socket is closed by peer.')}
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - all

**Comment by gengjun-git** [comment]
The reason is that frontendPool returned a broker conn

**Comment by gengjun-git** [comment]
But verifying whether the underlying tcp link is ALIVE or not must send data, and it would be very resource intensive to do so every time. So leave it to the upper layer
