### ISSUE TITLE
convert_tz result is wrong when Daylight saving time and Winter time

### ISSUE THREAD

**Issue by aaawuanjun** [StarRocks/starrocks#5678]
## timezone
America/Port-au-Prince
Chile/Continental
America/Santiago

## CASE
sql1:
> SELECT CONVERT_TZ('2022-11-20 11:59:59','Asia/Shanghai','Chile/Continental');

sql2:
> SELECT CONVERT_TZ('2022-04-28 11:59:59','Asia/Shanghai','Chile/Continental');

### Expected behavior

> sql1: 2022-11-20 00:59:59
> sql2: 2022-04-27 23:59:59

### Real behavior
MySQL [(none)]> SELECT CONVERT_TZ('2022-11-20 11:59:59','Asia/Shanghai','Chile/Continental');
+-------------------------------------------------------------------------+
| convert_tz('2022-11-20 11:59:59', 'Asia/Shanghai', 'Chile/Continental') |
+-------------------------------------------------------------------------+
| 2022-11-20 00:59:59                                                     |
+-------------------------------------------------------------------------+
1 row in set (0.00 sec)

MySQL [(none)]> SELECT CONVERT_TZ('2022-04-28 11:59:59','Asia/Shanghai','Chile/Continental');
+-------------------------------------------------------------------------+
| convert_tz('2022-04-28 11:59:59', 'Asia/Shanghai', 'Chile/Continental') |
+-------------------------------------------------------------------------+
| 2022-04-28 00:59:59                                                     |
+-------------------------------------------------------------------------+
1 row in set (0.01 sec)

MySQL [(none)]> select current_version();
+-------------------+
| current_version() |
+-------------------+
| 1.19.5 a356769    |
+-------------------+
1 row in set (0.00 sec)

## FPY
the new version 2.2.x also has this problem

**Comment by stdpain** [comment]
please check your timezone file:

cp /usr/share/zoneinfo/America/Santiago /usr/share/zoneinfo/Chile/Continental

**Comment by aaawuanjun** [comment]
mysql> SELECT CONVERT_TZ('2022-04-28 11:59:59','Asia/Shanghai','America/Santiago');
+------------------------------------------------------------------------+
| convert_tz('2022-04-28 11:59:59', 'Asia/Shanghai', 'America/Santiago') |
+------------------------------------------------------------------------+
| 2022-04-28 00:59:59                                                    |
+------------------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> select current_version();
+--------------------+
| current_version()  |
+--------------------+
| 2.2.0-RC01 f233d21 |
+--------------------+
1 row in set (0.00 sec)

mysql> quit
Bye
[root@centos xxx]# cp /usr/share/zoneinfo/America/Santiago /usr/share/zoneinfo/Chile/Continental
cp: "/usr/share/zoneinfo/America/Santiago" 与"/usr/share/zoneinfo/Chile/Continental" 为同一文件
[root@centos xxx]# diff /usr/share/zoneinfo/America/Santiago /usr/share/zoneinfo/Chile/Continental
[root@centos xxx]# 

the two file is the same

**Comment by aaawuanjun** [comment]
1、when I update tzdata by yum command

> yum install tzdata

from version '2016j-1.el7' to '2022a-1.el7'
we need upgrade all fe and be

before upgrade:
![image](https://user-images.githubusercontent.com/35732071/165903727-9c98b5e2-6970-435c-b8b1-b9cce883e48e.png)
after upgrade:
![image](https://user-images.githubusercontent.com/35732071/165903774-30127a90-421c-4816-9bef-89e4505bf32d.png)

2、and then, sometimes, it is right, sometimes it is wrong
![image](https://user-images.githubusercontent.com/35732071/165903494-995a36a1-8977-4929-851a-1ae90606045c.png)

3、stop be in order, and find the error be node
the result resumes ok

4、restart the error be node
result resumes ok,
