### ISSUE TITLE
make segment iterator scan full chunk in each time

### ISSUE THREAD

**Issue by xiaoyong-z** [StarRocks/starrocks#5699]
## Enhancement
In each call to `_do_get_next`,  segment iterators will return a result chunk with all of its element passing the predicates _filter. To acheive this, we will continue to read more data(by `_read`) and filter them (by `_filter`), until we reach the chunk_capacity. However, when the chunk is nearly full, such as it already contains 4095 rows(capacity is 4096),  wo only fetch one more row in `_read`, and check it throught `_filter` function, when there are a number of rows unsatisfied the predicates, the scan speed will degrade a log.
```c++
  while ((chunk_start < chunk_capacity) & _range_iter.has_more()) {
      RETURN_IF_ERROR(_read(chunk, rowid, chunk_capacity - chunk start));
      chunk->check_or_die();
      size_t next_start = chunk->num_rows();

      if (has_predicate) {
          next_start = _filter(chunk, rowid, chunk_start, next_start);
          chunk->check_or_die();
      }
      chunk_start = next_start;
      DCHECK_EQ(chunk_start, chunk->num_rows());
  }
```

**Comment by xiaoyong-z** [comment]
To solve this problem, i make the `_read` scan full rows(4096 rows, `chunk_capacity`) in each time, and _filter them in batch, this may lead to  the chunk contains more than 4096 rows after `_filter`. We will save these overflow rows in `_overflow_read_chunk` chunk and reload them in next `do_get_next`

**Comment by xiaoyong-z** [comment]
# Performance 
## Generate data script
```python
import random
import radar
from tqdm import tqdm
def tiny_generator():
    return str(random.randint(-128,127))

def smallint_generator():
    return str(random.randint(-32768, 32767))

def bigint_generator():
    return str(random.randint(-9223372036854775808, 9223372036854775807))

def int_generator():
    return str(random.randint(-2147483648, 2147483647))

def datetime_generator():
    return radar.random_datetime().strftime("%Y-%m-%d")

numbers = 500000000
with open("/data/xiaoyongzhao/output/8501/8501-4.csv",'w') as f2: 
    for i in tqdm(range(numbers)):
        key1 = int_generator()
        key2 = str(i % 10000000)
        key3 = str(i % 1000000)
        key4 = str(i % 100000)
        key5 = str(i % 10000)
        key6 = str(i % 1000)
        key7 = str(i % 100)
        key8 = str(i % 10)
        key9 = str(smallint_generator())
        key10 = str(i % 100000000)
        key11 = datetime_generator()
        key12 = datetime_generator()
        key13 = datetime_generator()
        value1 = bigint_generator()
        value2 = bigint_generator()
        value3 = bigint_generator()
        value4 = bigint_generator()
        update_time = datetime_generator()
        line = key1 + ',' + key2 + ',' + key3 + ',' + key4 + ',' + key5 + ',' + key6 + ',' + key7 + ',' + key8 + ',' + key9 + ',' + key10 + ',' + key11 + ',' + key12 + ',' + key13 + ',' + value1 + ',' + value2 + ',' + value3 + ',' + value4 + ',' + update_time
        f2.write(line + '\n')
f2.close()
```

## table
```
CREATE TABLE `table8501noindex` (
  `key1` int NOT NULL COMMENT "",
  `key2` varchar(20) NOT NULL COMMENT "",
  `key3` varchar(20) NOT NULL COMMENT "",
  `key4` varchar(20) NOT NULL COMMENT "",
  `key5` varchar(20) NOT NULL COMMENT "",
  `key6` varchar(20) NOT NULL COMMENT "",
  `key7` varchar(20) NOT NULL COMMENT "",
  `key8` varchar(20) NOT NULL COMMENT "",
  `key9` varchar(20) NOT NULL COMMENT "",
  `key10` varchar(20) NOT NULL DEFAULT "baishan" COMMENT "",
  `key11` datetime NOT NULL COMMENT "",
  `key12` datetime NOT NULL COMMENT "",
  `key13` datetime NOT NULL COMMENT "",
  `value1` bigint NULL COMMENT "",
  `value2` bigint NULL COMMENT "",
  `value3` bigint NULL COMMENT "",
  `value4` bigint NULL DEFAULT "0" COMMENT "",
  `update_time` datetime REPLACE NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`key1`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`key1`) BUCKETS 1
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "V2"
);
```

**Comment by xiaoyong-z** [comment]
# Each test is select count(*) from table where (key x) == '1'

<div class="okr-block-clipboard" data-okr="%7B%22okrDelta%22%3A%5B%7B%22lineType%22%3A%22unsupport%22%2C%22lineOptions%22%3A%7B%7D%2C%22lineContent%22%3A%5B%5D%7D%5D%2C%22businessKey%22%3A%22lark-doc%22%7D"></div><div data-zone-id="0" data-line-index="0" style="white-space: pre;">

SSD Test without bloom filter | Before | After Optimization
-- | -- | --
key2 | 16.90s | 16.25
key3 | 16.42s | 15.67s
key4 | 32.10s | 30.61s
key5 | 19.60s | 18.80s
key6 | 6.83s | 6.80s
key7 | 5.95s | 4.99s
key8 | 12.36s | 10.69s
key9 | 26.54s | 25.30s

</div>

<div class="okr-block-clipboard" data-okr="%7B%22okrDelta%22%3A%5B%7B%22lineType%22%3A%22unsupport%22%2C%22lineOptions%22%3A%7B%7D%2C%22lineContent%22%3A%5B%5D%7D%5D%2C%22businessKey%22%3A%22lark-doc%22%7D"></div><div data-zone-id="0" data-line-index="0" style="white-space: pre;">

SSDTest with bloom filter | Before | After Optimization
-- | -- | --
key2 | 1.17s | 1.14s
key3 | 1.21s | 1.20s
key4 | 2.15s | 2.09s
key5 | 16.18s | 15.52s
key6 | 7.96s | 6.84s
key7 | 6.52s | 4.91s
key8 | 12.33s | 10.60s
key9, | 2.81s | 2.71s

</div>

<div class="okr-block-clipboard" data-okr="%7B%22okrDelta%22%3A%5B%7B%22lineType%22%3A%22unsupport%22%2C%22lineOptions%22%3A%7B%7D%2C%22lineContent%22%3A%5B%5D%7D%5D%2C%22businessKey%22%3A%22lark-doc%22%7D"></div><div data-zone-id="0" data-line-index="0" style="white-space: pre;">

HDDTest without bloom filter | Before | After Optimization
-- | -- | --
key2 | 25.12s | 23.98s
key3 | 24.20s | 23.01s
key4 | 48.67s | 45.80s
key5 | 28.84s | 27.40s
key6 | 8.87s | 8.77s
key7 | 6.45s | 6.48s
key8 | 14.28s | 13.92s
key9 | 43.02s | 40.70s

</div>

<div class="okr-block-clipboard" data-okr="%7B%22okrDelta%22%3A%5B%7B%22lineType%22%3A%22unsupport%22%2C%22lineOptions%22%3A%7B%7D%2C%22lineContent%22%3A%5B%5D%7D%5D%2C%22businessKey%22%3A%22lark-doc%22%7D"></div><div data-zone-id="0" data-line-index="0" style="white-space: pre;">

HDDTest with bloom filter | Before | After optimization
-- | -- | --
key2 | 1.83s | 1.84s
key3 | 1.97s | 1.93s
key4 | 3.39s | 3.25s
key5 | 24.31s | 22.85s
key6 | 9.11s | 9.04s
key7 | 6.92s | 6.64s
key8 | 11.00s | 10.58s
key9 | 4.21s | 4.07s
key7, key8, key9 | 8.35s | 8.37s

</div>

**Comment by stdpain** [comment]
Could you set scanner thread number to 1 and run the test ? which may have a clearer effect
