### ISSUE TITLE
Support Rename view

### ISSUE THREAD

**Issue by ss892714028** [StarRocks/starrocks#5705]
## Feature request

**Is your feature request related to a problem? Please describe.**

I would like StarRocks to support rename view w/o deleting and recreating it. 

**Describe the solution you'd like**

A function to rename a already created view, something like [this](https://docs.starrocks.com/en-us/main/sql-reference/sql-statements/data-definition/ALTER%20TABLE#example) but for view would be ok.

**Describe alternatives you've considered**

None
**Additional context**

None

**Comment by motto1314** [comment]
True enough. When executing the SQL:
```
alter table my_second_dbt_model rename my_second_dbt_model_1
```
is ERROR:
```
ERROR 1064 (HY000): Do not support alter non-OLAP table[my_second_dbt_model]
```
