### ISSUE TITLE
Support Common Table Expression (CTE) with CREATE AS

### ISSUE THREAD

**Issue by ss892714028** [StarRocks/starrocks#5706]
## Feature request
**Is your feature request related to a problem? Please describe.**

Support CTE to simplify SQL scripts.

**Describe the solution you'd like**

Maybe support something like this...
```
create view
    test1.temp_view
as (
    with source_data as ( ...
```
**Describe alternatives you've considered**

None
**Additional context**

None

**Comment by motto1314** [comment]
And maybe support something like this...
```
create table
    test1.temp_table
as (
    with source_data as ( ...
```

As for `VIEW`, I think we can consider not supporting it

**Comment by motto1314** [comment]
like this:

```
create table `dbt_test`.`my_first_dbt_model__dbt_tmp`
PROPERTIES (
    "replication_num" = "1"
)
as 
with source_data as (
    select 1 as id
    union all
    select null as id
)
select *
from source_data
```
ERROR:
```
ERROR 1064 (HY000): Syntax error in line 8:
with source_data as (
^
Encountered: WITH
Expected

```

--------------------------------------------

and like this:
```
create table `dbt_test`.`my_first_dbt_model__dbt_tmp`
PROPERTIES (
    "replication_num" = "1"
)
as 
select *
from (
    select 1 as id
    union all
    select null as id
) source_data
```

ERROR:
```
ERROR 1064 (HY000): Unknown error
```

**Comment by HangyuanLiu** [comment]
Has support CTE use in ctas / create view /insert in branch2.2 and master branch
