### ISSUE TITLE
cluster display command should display leader

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#5748]
### Steps to reproduce the behavior (Required)
The premise
./main-0505-2 cluster deploy test123 v2.0.1 test123.yaml
The cluster has been deployed

1. Execute on the deployment machine：
```
./main-0505-2 cluster display test123
```

### Expected behavior (Required)
cluster display command should display leader
### Real behavior (Required)
cluster display command did not show leader
![image](https://user-images.githubusercontent.com/57162397/166893544-9975ded5-0d15-45b2-b69c-794e3aa408ae.png)

**Comment by wangtianyi2004** [comment]
![image](https://user-images.githubusercontent.com/16875363/168457881-175cf01b-40f0-43fd-b6bf-c3cfe8a9b611.png)

**Comment by wangtianyi2004** [comment]
fixed
