### ISSUE TITLE
Table is null although stream load at the Fe which is not master returned success.

### ISSUE THREAD

**Issue by yongbingwang** [StarRocks/starrocks#5812]
### Steps to reproduce the behavior (Required)
1. load data with stream_load at one Fe which is not master.
2. when the stream_load return success, execute query at the FE which ran stream load task before.
### Expected behavior (Required)
Execute query correctly. Because stream load returned success.
### Real behavior (Required)
Table is null, must wait for metadata synchronization.
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - all

**Comment by gengjun-git** [comment]
you can send sync cmd to sync the meta from master.
