### ISSUE TITLE
Wrong result of function `round`.

### ISSUE THREAD

**Issue by yongbingwang** [StarRocks/starrocks#5828]
### Steps to reproduce the behavior (Required)
```
mysql> SELECT round(-0.4, 0);
+----------------+
| round(-0.4, 0) |
+----------------+
|             -0 |
+----------------+
1 row in set (0.00 sec)
```
### Expected behavior (Required)
0
### Real behavior (Required)
-0
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - BRANCH_RELEASE e0ded14

**Comment by liuyehcf** [comment]
This is the nature behavior of std::round

**Comment by liuyehcf** [comment]
This problem canbe reproduced in branch main by the following sql. The second value `1-1` is a const expression, which will lead to math the double version of round

```sql
SELECT round(-0.4, 1-1);
```

**Comment by liuyehcf** [comment]
This issue can be closed directly

**Comment by liuyehcf** [comment]
version < 2.2, round is implemented in double type
version >=2.2 round is implemented in decimalV3 type
