### ISSUE TITLE
Compiling StarRocks supports docker

### ISSUE THREAD

**Issue by tianyouyangying** [StarRocks/starrocks#59]
目前发现只能在真实环境编译，真实环境依赖关系比较复杂，搭建编译环境成为一件比较头痛的事情，希望可以做一个docker版本的编译环境，能够更加的让小伙伴们都参与到源代码修改上来。

**Comment by kangkaisen** [comment]
感谢反馈，这个我们正在搞。

**Comment by dixingxing0** [comment]
> Any progress for this? @kangkaisen thanks

+1

**Comment by waittttting** [comment]
we will release a image soon

**Comment by daviddone** [comment]
+1 we need too

**Comment by imay** [comment]
Our develop environment docker is [Here](https://hub.docker.com/repository/docker/starrocks/dev-env)
