### ISSUE TITLE
Data types page can't be accessed

### ISSUE THREAD

**Issue by wangxujin1221** [StarRocks/starrocks#5909]

**Comment by Dshadowzh** [comment]
Hi, could you send more information about this issue? The steps to reproduce the behavior is needed, And it's better to describe it in English.

**Comment by wangxujin1221** [comment]
> 
The url below can't be accessed.
https://docs.starrocks.com/zh-cn/main/sql-reference/sql-statements/data-types/

**Comment by jaogoy** [comment]
It's a directory, not a file page.
You should visit page: https://docs.starrocks.com/zh-cn/main/sql-reference/sql-statements/data-types/BIGINT 
We will add some summary pages to describe Data Type categories, function categories, etc.
(But you still should use file page/url to visit them)

Can you tell me how did you visit the documentation website?

> > 
> 
> The url below can't be accessed. https://docs.starrocks.com/zh-cn/main/sql-reference/sql-statements/data-types/

**Comment by wangxujin1221** [comment]
> It's a directory, not a file page. You should visit page: https://docs.starrocks.com/zh-cn/main/sql-reference/sql-statements/data-types/BIGINT We will add some summary pages to describe Data Type categories, function categories, etc. (But you still should use file page/url to visit them)
> 
> Can you tell me how did you visit the documentation website?
> 
> > > 
> > 
> > 
> > The url below can't be accessed. https://docs.starrocks.com/zh-cn/main/sql-reference/sql-statements/data-types/

谢谢！我是通过“快速开始->表创建->字段类型”跳转的，里面的超链接指向的地址有点问题
![image](https://user-images.githubusercontent.com/38022823/169523342-43c9076c-c4fd-4f4d-8a37-0b5ae09ab900.png)
