### ISSUE TITLE
be crash when enable_resource_group turn on

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#5989]
### Steps to reproduce the behavior (Required)
1. `prepare data for tpch 1g`
2. ```
select count(*) from (
select
  s_acctbal,
  s_name,
  n_name,
  p_partkey,
  p_mfgr,
  s_address,
  s_phone,
  s_comment
from
  part,
  supplier,
  partsupp,
  nation,
  region
where
  p_partkey = ps_partkey
  and s_suppkey = ps_suppkey
  and p_size = 15
  and p_type like '%BRASS'
  and s_nationkey = n_nationkey
  and n_regionkey = r_regionkey
  and r_name = 'EUROPE'
  and ps_supplycost = ( 
    select
      min(ps_supplycost)
    from
      partsupp,
      supplier,
      nation,
      region
    where
      p_partkey = ps_partkey
      and s_suppkey = ps_suppkey
      and s_nationkey = n_nationkey
      and n_regionkey = r_regionkey
      and r_name = 'EUROPE'
  )
order by
  s_acctbal desc,
  n_name,
  s_name,
  p_partkey
) as t1;
```

### Expected behavior (Required)
```
+----------+
| count(*) |
+----------+
|      460 |
+----------+
```
### Real behavior (Required)
```
*** Aborted at 1652272598 (unix time) try "date -d @1652272598" if you are using GNU date ***
PC: @          0x281fb0e starrocks::pipeline::QuerySharedDriverQueueWithoutLock::take()
*** SIGSEGV (@0x332f302e) received by PID 3390 (TID 0x7f43bf6bb700) from PID 858730542; stack trace: ***
    @          0x3eddd32 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f44638fd630 (unknown)
    @          0x281fb0e starrocks::pipeline::QuerySharedDriverQueueWithoutLock::take()
    @          0x281e0e7 starrocks::pipeline::DriverQueueWithWorkGroup::take()
    @          0x281c337 starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x20b8879 starrocks::ThreadPool::dispatch_thread()
    @          0x20b442a starrocks::Thread::supervise_thread()
    @     0x7f44638f5ea5 start_thread
    @     0x7f4462f108dd __clone
    @                0x0 (unknown)
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE d2809f5 |
+----------------------+
```

**Comment by mofeiatwork** [comment]
Fixed by #5979
