### ISSUE TITLE
Function split_part  not support "-1" index 

### ISSUE THREAD

**Issue by 311709000529** [StarRocks/starrocks#5992]
### PostgreSQL
![middle_img_v2_2eda0ea8-9621-4805-8477-f826843b977g](https://user-images.githubusercontent.com/37820087/167975467-d9464f5e-1407-4250-bc32-92de0deb3905.jpg)
### StarRocks
![middle_img_v2_c3c12e22-18d5-4a41-b6b2-6a428c51e39g](https://user-images.githubusercontent.com/37820087/167975499-4d7a4b09-f31c-4a28-adc6-23d8c915d611.jpg)

**Comment by wangsimo0** [comment]
@tomscut hi could you please reply to this issue so I can assign it to you?

**Comment by tomscut** [comment]
Hi @wangsimo0 , please assign this to me. Thank you.

**Comment by lilyzhoupeijie** [comment]
Hi @kateshaowanjou , can you assign this to me？ I will have a try, Thank you.

**Comment by kateshaowanjou** [comment]
Hi @lilyzhoupeijie, are you still working on it？ If you have any questions, feel free to join WeChat for discussion:https://ma3you.com/articles_qrcode_show/b12e90J.png?le_time=220907203008013206

**Comment by leoyy0316** [comment]
hi @kateshaowanjou , can you assign this to me？
