### ISSUE TITLE
Replace OLAPStatus with Status

### ISSUE THREAD

**Issue by sduzh** [StarRocks/starrocks#60]
[Status](https://github.com/StarRocks/starrocks/blob/main/be/src/common/status.h) is used in StarRocks to report success and various kinds of errors, but some legacy code still using the deprecated [OLAPStatus](https://github.com/StarRocks/starrocks/search?q=OLAPStatus) as the return value, should replace them with `Status` and remove `OLAPStatus` finally.

**Comment by PuneetDabral** [comment]
sir can i ..please assign it to me ..so i can do my first contribution here ....thanku

**Comment by sduzh** [comment]
> sir can i ..please assign it to me ..so i can do my first contribution here ....but i need your support ....!!

Welcome to contribute! feel free to ask me questions.

**Comment by PuneetDabral** [comment]
sir can you please tell me the step by step!!procedure (sorry to disturb you i am new in open source )

**Comment by sduzh** [comment]
> sir can you please tell me the step by step!!procedure (sorry to disturb you i am new in open source )

1. Create a fork of this repo
2. [Cone](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository-from-github/cloning-a-repository) your fork of this repository from GitHub to your local computer 
3. Create a topic branch on your local computer
4. Make commits
5. `./run_ut.sh --be --run` to make sure all the tests are passed
6. Push your changes to a topic branch in your fork of the repository
7. [Submit a pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)

**Comment by PuneetDabral** [comment]
sir i can only change the word  OLAPStatus to Status....and my branch name is topic am i write ...sir

**Comment by sduzh** [comment]
> sir i can only change the word OLAPStatus to Status....and my branch name is topic am i write ...sir

I'm afraid not. If you modify the return type of a function, you need to modify the implementation of the function to replace the OLAPStatus values with the appropriate Status values, e.g. replace `OLAP_SUCCESS` with `Status::OK()`, replace `OLAP_ERR_INPUT_PARAMETER_ERROR` with `Status ::InvalidArgument()`, and you also need to change all the places where this function is called.

As for the branch name, maybe you can just name it `replace-OLAPStatus-with-Status` or something alike.

**Comment by PuneetDabral** [comment]
sir i am totally confuse ...but i will start..are you in discord on any other where i can discuss about this

**Comment by sduzh** [comment]
> sir i am totally confuse ...but i will start..are you in discord on any other where i can discuss about this

I don't have a discord account ... we can discuss this on Github now.

**Comment by PuneetDabral** [comment]
ok sir i clone it to my local device and create a branch in topic name
