### ISSUE TITLE
query es and be crashes when resource group is enabled.

### ISSUE THREAD

**Issue by dirtysalt** [StarRocks/starrocks#6008]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

create es table

```
create external table es_null_fields (`id_date` datetime NULL ) engine=ELASTICSEARCH properties ("hosts" = "http://172.26.92.141:9200", "user" = "root", "password" = "root", "index" = "datey", "type" = "doc");
```

and enable pipeline & resource group.

```
set global enable_pipeline_engine = true;
set global enable_resource_group = true;
```

and run query, and be crashes

```
select * from es_null_fields;
```

### Expected behavior (Required)

Return results.

### Real behavior (Required)

BE crashes, and BE.INFO has log

```
F0512 13:32:48.502014 168269 pipeline_driver.cpp:360] Check failed: _workgroup != nullptr
```

### StarRocks version (Required)

main

**Comment by jaogoy** [comment]
@dirtysalt @mofeiatwork shell we cherry pick it into v2.2?

**Comment by dirtysalt** [comment]
> @dirtysalt @mofeiatwork shell we cherry pick it into v2.2?

@jaogoy I guess here is no harm to cherry pick it into v2.2? What do you @mofeiatwork think?

**Comment by mofeiatwork** [comment]
> > @dirtysalt @mofeiatwork shell we cherry pick it into v2.2?
> 
> @jaogoy I guess here is no harm to cherry pick it into v2.2? What do you @mofeiatwork think?

It has been done through #5986
