### ISSUE TITLE
Fe lib miss jar package in 2.2-rc02

### ISSUE THREAD

**Issue by stephen-shelby** [StarRocks/starrocks#6072]
### Steps to reproduce the behavior (Required)
select hive external table which file system based on aws

### Expected behavior (Required)
normal result
### Real behavior (Required)
![image](https://user-images.githubusercontent.com/91597003/168408447-b79b67d2-87bd-42df-a2bc-a7bcec7a2df8.png)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.2-rc02

$FE/lib miss aws-java-sdk-bundle-1.11.563.jar.

**Comment by gengjun-git** [comment]
The size of jar aws-java-sdk-bundle-1.11.563.jar is too large, so we have removed this jar when we packaged. Because this feature is not used by every user. Users can download this jar from https://starrocks.com/zh-CN/download/community if needed.

**Comment by stephen-shelby** [comment]
gengjun-git: The jar aws-java-sdk-bundle-1.11.563.jar has been introduced in org.apache.hadoop/hadoop-aws. But to save the release package size, we have remove this jar, because it is too large. Users can download the jar from https://starrocks.com/zh-CN/download/community.
