### ISSUE TITLE
Support long text type STRING with a maximum length of 2GB

### ISSUE THREAD

**Issue by penfree** [StarRocks/starrocks#620]
## Feature request
Support long text type STRING with a maximum length of 2GB

apache doris has already implemented this feature。https://github.com/apache/incubator-doris/pull/6391

**Comment by winfys** [comment]
+1

**Comment by Dshadowzh** [comment]
We attempted to fix this issue simply to support long string like apache/incubator-doris#6391,  but found that compaction for big strings is easy to oom. We'll optimize the compaction first and then implement this feature.

**Comment by SaintBacchus** [comment]
@Dshadowzh when will these `String Type` release?

**Comment by penfree** [comment]
> We attempted to fix this issue simply to support long string like [apache/incubator-doris#6391](https://github.com/apache/incubator-doris/pull/6391), but found that compaction for big strings is easy to oom. We'll optimize the compaction first and then implement this feature.

@Dshadowzh  is there any update?

**Comment by imay** [comment]
> @Dshadowzh is there any update?

We are going to support big string very soon. Then We will create an another issue to track it.
And welcome to comment

**Comment by penfree** [comment]
> > @Dshadowzh is there any update?
> 
> We are going to support big string very soon. Then We will create an another issue to track it. And welcome to comment

Thanks, Really looking forward to!

**Comment by penfree** [comment]
> > @Dshadowzh is there any update?
> 
> We are going to support big string very soon. Then We will create an another issue to track it. And welcome to comment

mark, two months has past
