### ISSUE TITLE
为什么where条件里使用 or 过滤，索引将会失效？

### ISSUE THREAD

**Issue by HelloSrauker** [StarRocks/starrocks#6368]
比如我在 A表的 b,c两列建了索引。
此时我使用 select b,c from A where b = “123” and c =“234” ; 查看查询计划是能看到有走索引的记录的
如果加上OR条件 select b,c from A where b = “123” or c =“234” ; 看查询计划就完全不走索引了

我过了一下代码发现只要包含 复合关系(or,and,not) 条件的谓词语法树就不会下推到索引引擎了。
这是为啥呢？ 请教下是基于什么原因设计的呢？因为我记得mysql or是可以走索引的吧。
是因为性能考量还是代码复杂度等考量的呢？能否有什么方式让带or条件的情况下也能走索引查询呢?

请教下，谢谢

**Comment by kangkaisen** [comment]
我们只有or的是下推不到存储引擎，and 和 not 是可以的。 我们整个谓词的处理方式是基于 CNF （and 连接）的。
