### ISSUE TITLE
[Starrocks-2.2.0][Java UDTF] 一行转多列不支持

### ISSUE THREAD

**Issue by walkhan** [StarRocks/starrocks#6401]
描述:json数据如下：
[{"a1":147978405,"b1":100}]
最后解析成这样：
a1                    b1
147978405     100

看官网现在只支持返回多行单列，上面要返回多行多列。
不知道2.2.1是否可以支持

**Comment by jaogoy** [comment]
@walkhan json_each() will return multiple lines with two columns.
