### ISSUE TITLE
error happened when running `sh build.sh` at docker

### ISSUE THREAD

**Issue by shenxingwuying** [StarRocks/starrocks#644]
I pull the image starrocks/dev-env:main from hub.docker.com, and run `sh build.sh`, and happened an error when installing the output.

![image](https://user-images.githubusercontent.com/6360122/137176287-ca3495c6-5e2e-4567-b7d0-34510f482ab7.png)

The reason is that the image's thirdparty is prepared before, and some path do not match with the build.sh.

I moved the path in the docker instance and then run succeed.

Maybe you should fix it, like this.

thirdparty/vars-x86_64.sh:
```
-HADOOP_SOURCE="hadoop-3.3.0"
+HADOOP_SOURCE="hadoop"

-JDK_SOURCE="java-se-8u41-ri"
+JDK_SOURCE="open_jdk"
```
thirdparty/vars-aarch64.sh
```
-HADOOP_SOURCE="hadoop-3.3.0"
+HADOOP_SOURCE="hadoop"

-JDK_SOURCE="bisheng-jdk1.8.0_262"
+JDK_SOURCE="open_jdk"
```

**Comment by rickif** [comment]
Thanks for contributing.   
The xxx_SOURCE must be the same as the directory name in the compressed package.  
We have released a new docker image recently, in which we change the directory of thirdparty. Is the docker image you pulled the latest?

**Comment by shenxingwuying** [comment]
@rickif 
I'm very sorry.
I just know the issue, because my issue has closed before. I think job is finished. 
And I can go on the job? Or the job has been done by others?
