### ISSUE TITLE
Java version custom functions cannot be used across libraries

### ISSUE THREAD

**Issue by sym-liuyang** [StarRocks/starrocks#6446]
MySQL [test]> select retention_judge('1,1,1,1,1,1,1,1', 1, 3, 2, 0, 0);
ERROR 1064 (HY000): No matching function with signature: retention_judge(varchar(-1), tinyint(4), tinyint(4), tinyint(4), tinyint(4), tinyint(4)).
MySQL [test]> use bdc_dwd;
Database changed
MySQL [bdc_dwd]> select retention_judge('1,1,1,1,1,1,1,1', 1, 3, 2, 0, 0);
+---------------------------------------------------+
| retention_judge('1,1,1,1,1,1,1,1', 1, 3, 2, 0, 0)      |
+---------------------------------------------------+
|                                                                         1 |
+---------------------------------------------------+

**Comment by jaogoy** [comment]
Is the retention_judge() your own Java UDF?
Just change the database, the function works? And what's the meaning of your title?
