### ISSUE TITLE
need decimal256 support

### ISSUE THREAD

**Issue by cyclistX** [StarRocks/starrocks#6456]
## Feature request

**Is your feature request related to a problem? Please describe.**

Yes. We need 256-bit Decimal in our production env. This is common used for trading platform like cryptocurrency exchange and so on. Currently we cannot do any analysis or calculation on this type.<br>
**Describe the solution you'd like**

Support Decimal256 type.<br>
**Describe alternatives you've considered**

None.<br>
**Additional context**

 e.g. - Error: Value ''1.0008263127920818e+38'' is out of range. The type of 'amount_after_change' is DECIMAL128(38, 18).

**Comment by liulingtong** [comment]
i've met the same question
