### ISSUE TITLE
The Thrift interface of the Spark StarRocks Connector is abnormal

### ISSUE THREAD

**Issue by poack** [StarRocks/starrocks#6465]
### Problem description
When using Spark StarRocks Connector, I received an error: "Load StarRocks data failed, schema size of fetch data is wrong.", so I modified the source code and printed an error message, and found that "Select Schema" contained "fields in where". But the SELECT statement does not contain these fields. Here's an example:

### Steps to reproduce the behavior (Required)
1. CREATE TEMPORARY VIEW app_ad_state_online_entity_fc
 USING starrocks
 OPTIONS(
  "table.identifier" = "business.app_ad_state_online_entity_fc",
  "fenodes" = "$STARROCKS_FE_HOSTNAME:$STARROCKS_FE_RESTFUL_PORT",
  "user" = "$STARROCKS_USERNAME",
  "password" = "$STARROCKS_PASSWORD"
 );
select user_source from app_ad_state_online_entity_fc where   dt='${#date(0,0,0):yyyyMMdd#}' and hour_time='${#date(0,0,0):HH#}' limit 50
2. Modify the "RowBatch. Java"
<img width="827" alt="image" src="https://user-images.githubusercontent.com/64957787/169959545-09591bd0-d014-40fb-b2bb-4ca93c55db18.png">

### Expected behavior (Required)
100213984
100219792
......
### Real behavior (Required)
Contains: 'dt,hour_time,user_source', but the select statement only contains 'user_source'
.....schema is [Field{name='dt', type='DATE', comment='', precision=0, scale=0}, Field{name='hour_time', type='VARCHAR', comment='', precision=0, scale=0}, Field{name='user_source', type='VARCHAR', comment='', precision=0, scale=0}], fieldVectors is:[{}]
### StarRocks version (Required)
 - 2.1.6

**Comment by wyb** [comment]
https://github.com/StarRocks/starrocks/pull/8578
https://github.com/StarRocks/starrocks/pull/9437

fixed, you can try the latest version.
