### ISSUE TITLE
Refactor the chaotic code about type length 

### ISSUE THREAD

**Issue by mofeiatwork** [StarRocks/starrocks#6482]
## Refactoring request

**Is your refactoring request related to a problem? Please describe.**

Several requirements for type length:
- What's the default byte size of a type?
- What's the estimated byte size of a column, operator? 
- What's the relative-precise row length of an operator? 

However, current code is very chaotic:
- Default type size is defined at multiple places, and not consistent
- Default type size is a static value, could not be adaptive to the real size
- The estimated type size/row length is not so precise, which lead to more secondary problems

**Describe the solution you'd like**

Several steps need to be conducted to optimize this problem:
- [ ] Remove the redundant code for default type length, and try best to make it consistent
- [ ] Leverage the statistic of column size to estimate row-length/operator-width, and expose it to BE runtime
- [ ] Make the statistic more precise, which should be adaptive to the data and its distribution

**Describe alternatives you've considered**

**Additional context**

**Comment by ZiheLiu** [comment]
There are some trivial points:
- Scan node need two kinds of estimated row bytes:
    - **scanning row bytes**: including all the columns need to scan.
    - **output row bytes**: including only the columns scan node need to output. It will exclude some columns only used to filter data.
- When estimating the row bytes of scan node in planner, maybe we should exclude the inline project expressions, since they are actually not executed in scan node.
