### ISSUE TITLE
no error tablet id is reported when submitting publish task failed

### ISSUE THREAD

**Issue by rickif** [StarRocks/starrocks#6500]
https://github.com/StarRocks/starrocks/blob/599d99a394c6bf5ce8502aa4e1a6a54b348bfd6a/be/src/agent/task_worker_pool.cpp#L782-L809

When the `Status TaskWorkerPool::_publish_version_in_parallel` fails to submit task to the thread pool, the error status is returned directly without error tablet id assigned. 
While the FE check whether the transaction is successful according to the error table ids reported. So, the FE would wrongly treat this transaction as success.

### Expected behavior (Required)
The transaction returns failure.
### Real behavior (Required)
The transaction returns success while the publish is not executed.
### StarRocks version (Required)
main, 2.1, 2.2

**Comment by jaogoy** [comment]
Is the the prossibility of "fails to submit task to the thread pool" big or small.

**Comment by rickif** [comment]
> Is the the prossibility of "fails to submit task to the thread pool" big or small.

Well, this would happen in some extreme occasions:
1. 10 times attempt of submitting is failed.
2. `pthread_create()` returns error
@jaogoy
