### ISSUE TITLE
Unknow error with array type params

### ISSUE THREAD

**Issue by choury** [StarRocks/starrocks#6518]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `t2` (
  `c0` int(11) NULL COMMENT "",
  `c1` ARRAY<int(11)> NULL COMMENT "",
  `c2` ARRAY<int(11)> NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`c0`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`c0`) BUCKETS 1 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
2. select sum(if(array_overlap(c1, [1]), c0, null)) as q1, sum(if(array_overlap(c1, [1]), c0, null)) as q2 from t2;

### Real behavior (Required)
ERROR 1064 (HY000): Unknown error

### StarRocks version (Required)
2.2.0

**Comment by kangkaisen** [comment]
![image](https://user-images.githubusercontent.com/9894906/170223631-46c841d9-9bdc-4ff9-8427-00e22ab49414.png)
