### ISSUE TITLE
[Bug] the qps metric should be 0 when no query 

### ISSUE THREAD

**Issue by bigdata-kuxingseng** [StarRocks/starrocks#6539]
![3a1ba615daba9d2f12a1eefd18c187a](https://user-images.githubusercontent.com/69065042/170401632-b646a6ae-1ac4-4d99-ae4a-cfe79552762e.png)
![6417ffb95a0c41634cd62160d3e220c](https://user-images.githubusercontent.com/69065042/170401648-2d2fe23a-4c65-49d0-9d38-c307447b27a7.png)

**Comment by mofeiatwork** [comment]
fixed by https://github.com/StarRocks/starrocks/pull/6953
