### ISSUE TITLE
The limit statement makes the query slow when the sql condition has no hit data

### ISSUE THREAD

**Issue by only2yangcao** [StarRocks/starrocks#6561]
### Real behavior (Required)
![image](https://user-images.githubusercontent.com/16593449/170439890-d3b67538-4bfb-4559-811f-b83c326146a7.png)

profile comparison
![image](https://user-images.githubusercontent.com/16593449/170439953-33f676c2-a9dc-449b-822d-7e792a479301.png)

### StarRocks version (Required)
 2.1.1

**Comment by chaoyli** [comment]
@only2yangcao Have the problem been addressed?
