### ISSUE TITLE
数据库升级发现LastStartTime字段不更新

### ISSUE THREAD

**Issue by wuliLSF** [StarRocks/starrocks#6583]
### Steps to reproduce the behavior (Required)
升级数据库版本

### Real behavior (Required)
升级完成，但部分节点日期未更新
![图片](https://user-images.githubusercontent.com/45867247/170489035-78972a52-bda9-4a78-932b-0a0a6c90bbff.png)

### StarRocks version (Required)
v2.2.0

**Comment by waittttting** [comment]
https://github.com/StarRocks/starrocks/pull/10335
