### ISSUE TITLE
=Cancelled: LimitReach

### ISSUE THREAD

**Issue by bigdata-kuxingseng** [StarRocks/starrocks#6699]
background ：

FE:
2022-05-30 17:37:42,257 WARN (thrift-server-pool-9|152) [ReportHandler.putToQueue():195] the report queue size exceeds the limit: 100. current: 101

BE：
W0530 17:33:26.664580 24164 fragment_context.cpp:18] [Driver] Canceled, query_id=8ed76a4e-dffb-11ec-945d-1642cbb6fff3, instance_id=8ed76a4e-dffb-11ec-945d-1642cbb70007, reason=Cancelled: LimitReach

![image](https://user-images.githubusercontent.com/69065042/170964790-cddd4b7f-1b90-44e3-a124-6709a897832b.png)

**Comment by kangkaisen** [comment]
`reason=Cancelled: LimitReach`  this is the normal log, isn't the bug.
