### ISSUE TITLE
View can not query after alter db name

### ISSUE THREAD

**Issue by Youngwb** [StarRocks/starrocks#6706]
### Steps to reproduce the behavior (Required)
1. CREATE view:
```SQL
CREATE VIEW `revenue0` (supplier_no, total_revenue) COMMENT "VIEW" 
AS SELECT `l_suppkey` AS `supplier_no`, sum(`l_extendedprice` * (1 - `l_discount`)) AS `total_revenue` 
FROM `default_cluster:standard_sqlset_1629877528208`.`lineitem` 
WHERE (`l_shipdate` >= '1995-01-01') AND (`l_shipdate` < '1995-01-01' + INTERVAL '3' month) 
GROUP BY `l_suppkey`;
```
2. alter db name from standard_sqlset_1629877528208 to tpch
3. SELECT  * from revenue0;

### Expected behavior (Required)
query normal

### Real behavior (Required)
mysql> select * from revenue0;
ERROR 1064 (HY000): Unknown database 'default_cluster:standard_sqlset_1629877528208'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by Astralidea** [comment]
This is actually a known problem, but we don't have a good solution to solve this problem easily.
