### ISSUE TITLE
read duplicate data from iceberg external table

### ISSUE THREAD

**Issue by hongli-my** [StarRocks/starrocks#6767]
### Steps to reproduce the behavior (Required)
1.    create external iceberg table.
2.    iceberg table  property `read.split.target-size` is `128M`, default value.
3.   if  `data files` size large than `128M`  iceberg `palnFile` interface will return `duplicate data file`, and starrocks no process this case,      **this case work well on trino**

### StarRocks version (Required)
 -  all  branch

**Comment by hongli-my** [comment]
set  `read.split.target-size` large than `data file size` will avoid this case, but maybe need to  resolve it.

**Comment by caneGuy** [comment]
this has been fixed by https://github.com/StarRocks/starrocks/pull/4411

**Comment by caneGuy** [comment]
i will close this issue, reopen it if we have other problem
