### ISSUE TITLE
BE is down

### ISSUE THREAD

**Issue by skypan** [StarRocks/starrocks#6802]
### Steps to reproduce the behavior (Required)
streamload同时指定  `-H "partial_update:true" -H "columns:id,__op='delete'"`，run error and be will down
run sql `select current_version();`, and the tips is `Backend not found. Check if any backend is down or not`
out's data have upsert and delete
### Expected behavior (Required)
streamload support partialUpdate and delete at the same time
### Real behavior (Required)
run error
### StarRocks version (Required)
 2.2.0 671149f

**Comment by chaoyli** [comment]
https://github.com/StarRocks/starrocks/pull/6764
