### ISSUE TITLE
Wrong result of show resource group

### ISSUE THREAD

**Issue by mofeiatwork** [StarRocks/starrocks#6813]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'
![image](https://user-images.githubusercontent.com/96611012/171394636-6d20f4ec-9f3c-4b60-806e-a78315dd7025.png)

The `show resource group rg1` command accesses a non-existent resource group, which should report an error but not the empty result.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by huangfeng1993** [comment]
hello, I would be happy to take this issue.

**Comment by mofeiatwork** [comment]
> hello, I would be happy to take this issue.

Sure, you could submit a PR to fix it. And you could contact with me if any problems.
