### ISSUE TITLE
agg costs too much time and just uses 1~2 threads.

### ISSUE THREAD

**Issue by fzhedu** [StarRocks/starrocks#6858]
### Steps to reproduce the behavior (Required)

TPCH SF100 data and queries.

### Expected behavior (Required)
finished in several secondes.

### Real behavior (Required)
```
mysql> SELECT l_orderkey, sum(l_quantity) FROM lineitem where l_shipdate BETWEEN '1995-01-01' AND '1996-12-31' GROUP BY l_orderkey;
ERROR 1064 (HY000): Query exceeded time limit of 300 seconds
```

### StarRocks version (Required)

2.2.0

**Comment by fzhedu** [comment]
3 BE nodes with 1 FE, loading TPCH SF100 data, then run the SQL.

**Comment by mofeiatwork** [comment]
Wrap the SQL with a `select count(*) from (xxx)`, otherwise it would output a lot of data and it's expensive.
