### ISSUE TITLE
CompressionContextPool

### ISSUE THREAD

**Issue by xiaoyong-z** [StarRocks/starrocks#6870]
## Feature request
**Is your feature request related to a problem? Please describe.**

Previously, each time we perform an LZ4F or ZSTD compression, we need to create a LZ4F or ZSTD compression context. Each compression context's memory size is not small, they all allocate from the central cache of tcmalloc, not local thread cache. For tcmlloac, allocating memory from central cache needs to acquire the spinlock first. So when many threads create compression context together, they will compete to get the spinlock of tcmalloc's central cache, which will lead to the degration of total perform.

**Describe the solution you'd like**

Add a compressionContextPool to reuse the context.

**Describe alternatives you've considered**

**Additional context**

**Comment by imay** [comment]
@xiaoyong-z Excellent catch. Did you find how much memory this compress context would occupy?

**Comment by xiaoyong-z** [comment]
> @xiaoyong-z Excellent catch. Did you find how much memory this compress context would occupy?

For LZ4 compression context, it contains 3 parts
1. LZ4F_cctx_t: 184 Bytes
2. LZ4_stream_t: 16416 Bytes
3. tmpBuff: Not fixed, dependent on the compressed contents

For ZSTD compression context, it contains 4 parts
1. ZSTD_CCtx:  5072 Bytes
2. localDict: 40 Bytes + dictBuffer + cdict
3. PrefixDict: 24 Bytes + cdict
4. workspace

**Comment by trueeyu** [comment]
Is it possible to optimize this way ?: https://github.com/StarRocks/starrocks/issues/3713, reducing the memory usage of LZ4_stream_t

**Comment by trueeyu** [comment]
> Is it possible to optimize this way ?: #3713, reducing the memory usage of LZ4_stream_t

We have a problem with the algorithm for lz4's compressed memory estimation, which doesn't actually require that much memory。 

std::max(LZ4F_compressBound(len, &_s_preferences), LZ4F_compressFrameBound(len, &_s_preferences)); 

compressBound is fixed at 16K, and compressFrameBound is selected according to the actual maximum size. I see that other databases using lz4 generally do not allocate such a large amount of memory. To allocate such a large amount of memory, one is that the application memory efficiency is low, and the other is when shrinking, there will be overhead

**Comment by trueeyu** [comment]
In fact, for this Buf, applying for 16K at the beginning is also quite extravagant. It is best to apply on demand. If it is not enough, resize itHowever, in RoutineLoad, the amount of data imported at one time is relatively small, and there are many Tablets involved, one little rows in one segment. A scenario with many segments may occupy too much memory.
