### ISSUE TITLE
关于murmur_hash3_32 函数

### ISSUE THREAD

**Issue by wushuaidegit** [StarRocks/starrocks#6916]
用800W的数据，murmur_hash3_32(input)%10后，分成10份的数据相加之后的数据量，小于原本的数据量
SR版本2.2.0-RC02 2ab1482

**Comment by jaogoy** [comment]
你这里是指 count(*) 还是 count(distinct *)?
如果是后者，你这里800w 中的不重复值有多少？整体结果大概小了多少？32 位的hash会有一定的冲突率。

**Comment by wushuaidegit** [comment]
没有重复值，整体少了三分之一左右。
select count(distinct *) from table where murmur_hash3_32(col1)%10=0
select count(distinct *) from table where murmur_hash3_32(col1)%10=1
select count(distinct *) from table where murmur_hash3_32(col1)%10=2
...
我理解即使有冲突率，我这样的sql查出来数据也不应该少吧
