### ISSUE TITLE
[BUG] Some load parameters are lost after alter routine load

### ISSUE THREAD

**Issue by gengjun-git** [StarRocks/starrocks#6936]
### Steps to reproduce the behavior (Required)
1. create routine load
```
CREATE ROUTINE LOAD partsuppload ON partsupp
COLUMNS TERMINATED BY ",",
COLUMNS (a)
PROPERTIES
(
 "max_error_number"="10000",
 "desired_concurrent_number"="55",
 "strict_mode" = "false"
)
FROM KAFKA
(
 "kafka_broker_list"= "1.2.2.2",
 "kafka_topic" = "table1123",
 "property.group.id" = "group1",
 "property.kafka_default_offsets" = "OFFSET_END"
);
```

2. alter routine load
```
alter routine load for partsuppload COLUMNS TERMINATED BY "\t"
```

3. After master makes a new image and push it to other fes, restart all fe.

### Expected behavior (Required)
the columns should be reserved.

### Real behavior (Required)
the columns in routine load meta is lost.

### StarRocks version (Required)
 - all

**Comment by jaogoy** [comment]
Is this issue the same as another issue in which the metadata is lost after an alter operation and checkpoint?
