### ISSUE TITLE
what privileges should use in log  in the web ui in the port of 8030?

### ISSUE THREAD

**Issue by fjyulu** [StarRocks/starrocks#7059]
## General Question

Hi 
I have a question that after install the starrocks cluster, and the cluster is running ok, then I log in the mange page at port 8030, then there is an ui textfield of username and password in the middleup. I have create a new user of dev of cause with password, but it won't work, when I use the root, everything is fine.  Yes I googled and check the document. But I didn't find the right answer.

So my question is how can I log in the manage page use the user other than root?

Thanks

**Comment by imay** [comment]
It should work that you login with `dev` user and its password. However this user can only see what he was allowed.
So could you login with `dev` user? and could you paste some screenshot after login?

**Comment by fjyulu** [comment]
> 
thanks , It's about the privileges, now it's ok

**Comment by fjyulu** [comment]
> It should work that you login with `dev` user and its password. However this user can only see what he was allowed. So could you login with `dev` user? and could you paste some screenshot after login?

thanks , It's about the privileges, now it's ok
