### ISSUE TITLE
ESTable do not support HTTPS

### ISSUE THREAD

**Issue by decster** [StarRocks/starrocks#7160]
### Real behavior (Required)

`fetch es table [common_asset_info_Es] metadata failure: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by RowenWoo** [comment]
I will fix this issue in the last few days
