### ISSUE TITLE
Data hot and cold life cycle management

### ISSUE THREAD

**Issue by YangWei1997** [StarRocks/starrocks#7215]
## Enhancement
I hope to achieve data hot and cold cycle management when building tables in Starrocks.
specific requirement:
According to the sky zone, the data of the last month is stored in SSD, the data from one month to six months is stored in HDD, and the data after six months is automatically deleted.
My attempt:
I tried it through storage_cooldown_time and found that all partition data were transferred from SSD to HDD.
Other database solutions:
DORIS: dynamic_partition.create_history_partition = true, dynamic_partition.reserved_history_periods, dynamic_partition.history_num
ES: Index life cycle strategy

**Comment by imay** [comment]
Now you can achieve remove old partitions by `dynamic partition`. And starrocks can migrate data from SSD to HDD automatically. So I want to know what do you want more?

**Comment by wyb** [comment]
> My needs: Create a table with a day -to -day partition. The hot data is the next month, and the data is stored in SSD. The data from one month to six months is automatically stored in HDD, and the data after six months is automatically deleted. My attempt: CREATE TABLE test_01 ( ts DATETIME, message String ) PARTITION BY RANGE(ts)( START ("2022-06-13") END ("2022-06-25") EVERY (INTERVAL 1 day) ) DISTRIBUTED BY HASH(ts) BUCKETS 1 PROPERTIES( "storage_medium" = "SSD", "dynamic_partition.enable" = "true", "dynamic_partition.time_unit" = "DAY", "dynamic_partition.start" = "-180", "dynamic_partition.end" = "30", "dynamic_partition.prefix" = "p", "dynamic_partition.buckets" = "1", "replication_num" = "1" ); <img alt="image" width="1312" src="https://user-images.githubusercontent.com/50506546/173531808-aeb04e6e-f57f-4f51-8957-d7c1950a8bc5.png"> <img alt="image" width="1236" src="https://user-images.githubusercontent.com/50506546/173532023-5bef47d2-a14a-4ab3-a451-ed21654a5ad9.png"> I found that when the COOLDOWN time was reached, the data in the future partition also moved from SSD to HDD. This is hot data and should exist on SSD. Can you show the SQL that you realize this demand?

Currently, dynamic partition does not support automatic management of hot and cold data.
You can manually modify the partition storage cool down time.
```
alter table test_01 modify partition p20220615 set ("storage_cooldown_time" = "xxx");
...
alter table test_01 modify partition p20220624 set ("storage_cooldown_time" = "xxx");
```

This feature is very useful, we hope to support it later, are you interested in doing it with us?
