### ISSUE TITLE
Support ElasticSearch Connector

### ISSUE THREAD

**Issue by stephen-shelby** [StarRocks/starrocks#7272]
## Feature request

**Is your feature request related to a problem? Please describe.**

https://github.com/StarRocks/starrocks/issues/7268

**Describe the solution you'd like**

- provide user-defined ES External Catalog etc.
- we can query es table (index) under es external catalog without creating an [es external table](https://docs.starrocks.com/zh-cn/main/using_starrocks/External_table#elasticsearch-%E5%A4%96%E9%83%A8%E8%A1%A8).

**Describe alternatives you've considered**

**Additional context**

If you're interested in this feature. you may
- provide ES connector design doc
- refer to hive connector to implement `ConnectorMetadata` etc
- Improve or refactor EsRestClient (TBD)
- Hierarchical relationship.  StarRocks Table -> ES Index.

**Comment by RowenWoo** [comment]
pick elasticsearch-connector
