### ISSUE TITLE
[Enhancement] Print datasize column in human readable format in show tablet statement

### ISSUE THREAD

**Issue by zhuxt2015** [StarRocks/starrocks#7336]
## Enhancement
print datasize in human readable format  e.g. 1K 234M 2G
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/13765310/174006258-91dc2cc6-a85c-4b3d-b4c6-c6b97bf91999.png">

**Comment by jaogoy** [comment]
Good advice.
Could you submit a PR to improve it?

**Comment by zhuxt2015** [comment]
> Good advice. Could you submit a PR to improve it?

ok, I'll submit a PR
