### ISSUE TITLE
The FE role displayed on the web page is inconsistent with the mysql query result

### ISSUE THREAD

**Issue by tomscut** [StarRocks/starrocks#7372]
### Steps to reproduce the behavior (Required)
1. SHOW FRONTENDS;
2. Access http://xxx/ha

### Expected behavior (Required)
The FE role displayed on the web page is consistent with the mysql query result.

### Real behavior (Required)
Web UI
<img width="775" alt="image" src="https://user-images.githubusercontent.com/55134131/174065750-f8dea0f8-8f63-463c-8c76-97d5416d74d8.png">

Mysql Result
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/55134131/174065886-cf829d81-1235-4776-abe5-82d88444c4f8.png">

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by jaogoy** [comment]
It's a little confusing, you can look at the field "IsMaster".
MASTER is a kind of FOLLOWER.

We will try to unify them. Thanks for your issue.
