### ISSUE TITLE
[Bug]Be crash when executing connector standard query(tpcds 1G)

### ISSUE THREAD

**Issue by adzfolc** [StarRocks/starrocks#7391]
### Steps to reproduce the behavior (Required)
1. CREATE EXTERNAL CATALOG catalog_2 PROPERTIES("type"="hive", "hive.metastore.uris"="thrift://172.26.92.141:9083");
2. Build SR cluster
mysql> show backends;
+-----------+-----------------+---------------+---------------+--------+----------+----------+---------------------+---------------------+-------+----------------------+-----------------------+-----------+------------------+---------------+---------------+---------+----------------+--------+-------------------+--------------------------------------------------------+-------------------+-------------+----------+
| BackendId | Cluster         | IP            | HeartbeatPort | BePort | HttpPort | BrpcPort | LastStartTime       | LastHeartbeat       | Alive | SystemDecommissioned | ClusterDecommissioned | TabletNum | DataUsedCapacity | AvailCapacity | TotalCapacity | UsedPct | MaxDiskUsedPct | ErrMsg | Version           | Status                                                 | DataTotalCapacity | DataUsedPct | CpuCores |
+-----------+-----------------+---------------+---------------+--------+----------+----------+---------------------+---------------------+-------+----------------------+-----------------------+-----------+------------------+---------------+---------------+---------+----------------+--------+-------------------+--------------------------------------------------------+-------------------+-------------+----------+
| 10003     | default_cluster | 172.26.92.139 | 22229         | 22227  | 22228    | 22230    | 2022-06-17 10:10:21 | 2022-06-17 10:21:52 | true  | false                | false                 | 3         | .000             | 564.274 GB    | 1.968 TB      | 72.01 % | 72.01 %        |        | UNKNOWN-d8d14a8f1 | {"lastSuccessReportTabletsTime":"2022-06-17 10:21:22"} | 564.274 GB        | 0.00 %      | 104      |
| 10044     | default_cluster | 172.26.92.139 | 23229         | 23227  | 23228    | 23230    | 2022-06-17 10:10:31 | 2022-06-17 10:21:52 | true  | false                | false                 | 0         | .000             | 564.273 GB    | 1.968 TB      | 72.01 % | 72.01 %        |        | UNKNOWN-d8d14a8f1 | {"lastSuccessReportTabletsTime":"2022-06-17 10:21:32"} | 564.273 GB        | 0.00 %      | 104      |
| 10045     | default_cluster | 172.26.92.139 | 24229         | 24227  | 24228    | 24230    | 2022-06-17 10:21:52 | 2022-06-17 10:21:52 | true  | false                | false                 | 3         | .000             | 564.273 GB    | 1.968 TB      | 72.01 % | 72.01 %        |        | UNKNOWN-d8d14a8f1 | {"lastSuccessReportTabletsTime":"2022-06-17 10:21:52"} | 564.273 GB        | 0.00 %      | 104      |
+-----------+-----------------+---------------+---------------+--------+----------+----------+---------------------+---------------------+-------+----------------------+-----------------------+-----------+------------------+---------------+---------------+---------+----------------+--------+-------------------+--------------------------------------------------------+-------------------+-------------+----------+
3. select  substr(r_reason_desc,1,20) ,avg(ws_quantity) ,avg(wr_refunded_cash) ,avg(wr_fee) from web_sales, web_returns, web_page, hive_catalog.tpcds_1g_csv.customer_demographics cd1, hive_catalog.tpcds_1g_csv.customer_demographics cd2, hive_catalog.tpcds_1g_csv.customer_address, hive_catalog.tpcds_1g_csv.date_dim, hive_catalog.tpcds_1g_csv.reason where ws_web_page_sk = wp_web_page_sk and ws_item_sk = wr_item_sk and ws_order_number = wr_order_number and ws_sold_date_sk = d_date_sk and d_year = 2000 and cd1.cd_demo_sk = wr_refunded_cdemo_sk and cd2.cd_demo_sk = wr_returning_cdemo_sk and ca_address_sk = wr_refunded_addr_sk and r_reason_sk = wr_reason_sk and ( ( cd1.cd_marital_status = 'M' and cd1.cd_marital_status = cd2.cd_marital_status and cd1.cd_education_status = 'Advanced Degree' and cd1.cd_education_status = cd2.cd_education_status and ws_sales_price between 100.00 and 150.00 ) or ( cd1.cd_marital_status = 'S' and cd1.cd_marital_status = cd2.cd_marital_status and cd1.cd_education_status = 'College' and cd1.cd_education_status = cd2.cd_education_status and ws_sales_price between 50.00 and 100.00 ) or ( cd1.cd_marital_status = 'W' and cd1.cd_marital_status = cd2.cd_marital_status and cd1.cd_education_status = '2 yr Degree' and cd1.cd_education_status = cd2.cd_education_status and ws_sales_price between 150.00 and 200.00 ) ) and ( ( ca_country = 'United States' and ca_state in ('IN', 'OH', 'NJ') and ws_net_profit between 100 and 200 ) or ( ca_country = 'United States' and ca_state in ('WI', 'CT', 'KY') and ws_net_profit between 150 and 300 ) or ( ca_country = 'United States' and ca_state in ('LA', 'IA', 'AR') and ws_net_profit between 50 and 250 ) ) group by r_reason_desc order by substr(r_reason_desc,1,20) ,avg(ws_quantity) ,avg(wr_refunded_cash) ,avg(wr_fee) limit 100;
5. ERROR 1064 (HY000): rpc failed, host: 172.26.92.139

### Expected behavior (Required)
Query execution successfully
### Real behavior (Required)
ERROR 1064 (HY000): rpc failed, host: 172.26.92.139

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN d8d14a8f1 |
+-------------------+
1 row in set (0.01 sec)
branch-2.3

**Comment by adzfolc** [comment]
be.out

start time: Fri Jun 17 09:08:42 CST 2022
log4j:WARN No appenders could be found for logger (org.apache.hadoop.fs.FileSystem).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
*** Aborted at 1655428915 (unix time) try "date -d @1655428915" if you are using GNU date ***
PC: @          0x25d06a2 starrocks::connector::HiveDataSource::_init_scanner()
*** SIGSEGV (@0x10) received by PID 51521 (TID 0x7ff7358c7700) from PID 16; stack trace: ***
    @          0x4c9c812 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7ff7d7ccce9b os::Linux::chained_handler()
    @     0x7ff7d7cd190c JVM_handle_linux_signal
    @     0x7ff7d7cc4858 signalHandler()
    @     0x7ff7d71ac630 (unknown)
    @          0x25d06a2 starrocks::connector::HiveDataSource::_init_scanner()
    @          0x25d2c93 starrocks::connector::HiveDataSource::open()
    @          0x2b26996 starrocks::pipeline::ConnectorChunkSource::prepare()
    @          0x2b17601 starrocks::pipeline::ScanOperator::_pickup_morsel()
    @          0x2b1783d starrocks::pipeline::ScanOperator::_try_to_trigger_next_scan()
    @          0x2b1798d starrocks::pipeline::ScanOperator::pull_chunk()
    @          0x2b5e22a starrocks::pipeline::PipelineDriver::process()
    @          0x2b52384 starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x3f45fe9 starrocks::ThreadPool::dispatch_thread()
    @          0x3f4130a starrocks::Thread::supervise_thread()
    @     0x7ff7d71a4ea5 start_thread
    @     0x7ff7d5c6ab0d __clone
    @                0x0 (unknown)

**Comment by caneGuy** [comment]
I can not reproduce this issue and will resolve this if we can reproduce
