### ISSUE TITLE
Rename OlapMeta to KVStore

### ISSUE THREAD

**Issue by sduzh** [StarRocks/starrocks#74]
https://github.com/StarRocks/starrocks/blob/dbb993b476f3964ea8d06811b36716e6b5b3c0ff/be/src/storage/olap_meta.h#L45
The class `OlapMeta` is a thin wrapper on RocksDB to provides key-value storage interfaces, the `OlapMeta` is somehow inaccurate, suggest renaming it to `KVStore`.

**Comment by Narcasserun** [comment]
Can you assign this task to me? As my first time at starrocks

**Comment by Narcasserun** [comment]
Sorry, brother, I'm not good at C + + writing. I can leave this contribution opportunity to others. Thank you. I'm actually good at Java, go, etc

**Comment by BanBuDu0** [comment]
hi, can this issues assign to me, I think I can solve this, my first contribution coming with your support!

**Comment by BanBuDu0** [comment]
thinks, i got it, i will do it right now, and does it have a deadline? I am now working as an intern in a company and only have night time.

**Comment by sduzh** [comment]
> thinks, i got it, i will do it right now, and does it have a deadline? I am now working as an intern in a company and only have night time.

No deadline, feel free to arrange your time.

**Comment by BanBuDu0** [comment]
hi, when I do the step 5 in https://github.com/StarRocks/starrocks/issues/60#issuecomment-914927067 .
 I run cmd `sh ./run-ut.sh --be --run` in my Debian 9 linux 4.14.
I got error `./run-ut.sh: 19: set: Illegal option -o pipefail`
need help!!
thinks a lot

**Comment by sduzh** [comment]
> hi, when I do the step 5 in [#60 (comment)](https://github.com/StarRocks/starrocks/issues/60#issuecomment-914927067) .
> I run cmd `sh ./run-ut.sh --be --run` in my Debian 9 linux 4.14.
> I got error `./run-ut.sh: 19: set: Illegal option -o pipefail`
> need help!!
> thanks a lot

The test script  `./run_ut.sh` has not been tested on the Debian platform and may have some compatibility issues, you can submit your pull request directly, the CI will run the unit tests compatibility.

As for the script problem, you can create a new issue about it.
