### ISSUE TITLE
[sqlancer] empty json path

### ISSUE THREAD

**Issue by dulong41** [StarRocks/starrocks#7422]
### Steps to reproduce the behavior (Required)
DROP DATABASE IF EXISTS w10;
CREATE DATABASE w10;
USE w10;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DATETIME NULL ,c_0_1 TINYINT NOT NULL ,c_0_2 ARRAY<INT> NULL ,c_0_3 DATETIME NULL ,c_0_4 BOOLEAN NOT NULL ,c_0_5 VARCHAR(41) NOT NULL ,c_0_6 ARRAY<INT> NOT NULL ) UNIQUE KEY (c_0_0,c_0_1) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 337 day)) DISTRIBUTED BY HASH (c_0_0,c_0_1) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DATE NULL ,c_1_1 TINYINT NULL ,c_1_2 BOOLEAN NULL ,c_1_3 DECIMAL(22, 5)  NOT NULL ,c_1_4 ARRAY<STRING> NOT NULL ,c_1_5 INT NOT NULL ,c_1_6 CHAR(21) NOT NULL ,c_1_7 VARCHAR(51) NULL ,c_1_8 DOUBLE NOT NULL ) UNIQUE KEY (c_1_0,c_1_1,c_1_2) PARTITION BY RANGE(c_1_0) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 398 day)) DISTRIBUTED BY HASH (c_1_2,c_1_0,c_1_1) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t2 (c_2_0 DATETIME NOT NULL ,c_2_1 DECIMAL(9, 5)  NULL ) DUPLICATE KEY (c_2_0) PARTITION BY RANGE(c_2_0) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 146 day)) DISTRIBUTED BY HASH (c_2_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t3 (c_3_0 BOOLEAN NOT NULL ,c_3_1 DATE NOT NULL ,c_3_2 DATE NOT NULL ,c_3_3 DATETIME NULL ,c_3_4 VARCHAR(31) NULL ,c_3_5 DECIMAL(4, 0)  NULL ,c_3_6 INT NOT NULL ,c_3_7 DECIMAL(1, 0)  NULL ,c_3_8 BOOLEAN NULL ,c_3_9 CHAR(1) NULL ,c_3_10 BOOLEAN NOT NULL ,c_3_11 DECIMAL(15, 2)  NOT NULL ,c_3_12 ARRAY<INT> NULL ,c_3_13 BOOLEAN NULL ,c_3_14 DATETIME NOT NULL ,c_3_15 ARRAY<STRING> NULL ,c_3_16 BOOLEAN NULL ) DUPLICATE KEY (c_3_0,c_3_1,c_3_2,c_3_3,c_3_4,c_3_5,c_3_6,c_3_7,c_3_8,c_3_9,c_3_10,c_3_11) PARTITION BY RANGE(c_3_3) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 208 day)) DISTRIBUTED BY HASH (c_3_9,c_3_5,c_3_0,c_3_2,c_3_8) BUCKETS 3 properties("replication_num"="3") ;
INSERT INTO t3 VALUES (true, '2010-01-04', '2010-01-08', '2010-01-30 08:00:14', 'x', 6979, 11, 7, true, '', false, 30734877076.44, [-1146175370, -1146175370, -407636212, -407636212, -407636212, -918253013, -918253013], true, '2010-01-21 08:00:14', ["pHd", "MLbQ1Bs", "Q", "2c"], NULL);
INSERT INTO t1 VALUES ('2010-01-18', 5, true, 175407784196.83297, ["haXPj", "TTLy", "cm", "", "wWNT7jEe", "G68Cr", "QzLZedZQK"], 8, 'kSWG', '', 0.4741146204517179), (NULL, 3, false, 414730388118.29405, ["o02x7wZRw", "n", "tIU", "jEJ0"], 1, '', 'V', 0.5795270162001552);
INSERT INTO t2 VALUES ('2010-01-04 08:00:14', 0.01182), ('2010-01-29 08:00:14', 0.08384);
INSERT INTO t0 VALUES ('2010-01-29 08:00:14', 2, [-1768129766, 1368827244, 975350574, 182567953, -89628059, -150153064, 1174164220, 182567953, -1781796717, 141480710, 983752951, 1961562292, -781745358, 141480710], '2010-01-10 08:00:14', false, 'vS', [-1139005039, -208894807, 1204223119, -208894807, 2001284225, 2001284225, -1635319041]);
INSERT INTO t3 VALUES (false, '2010-01-03', '2010-01-04', '2010-01-08 08:00:14', 'IiPQX9', 194, 17, 0, true, '', true, 14791849558.67, [-1146175370, 714226351, -1768129766, 176939292], true, '2010-01-15 08:00:14', ["CsvH", "Puv", "44", "y7goRJn", "a", "LB", "V", "IT", "", "REUM1H5", "nVXsNlu", "T"], NULL), (true, '2010-01-08', '2010-01-05', '2010-01-31 08:00:14', 'gccP', 1978, 24, 5, false, '', true, 90629107488.78, [1266456260, -993986416, -918253013, -1677244875], true, '2010-01-15 08:00:14', [], false), (true, '2010-01-12', '2010-01-24', '2010-01-16 08:00:14', 'e', 562, 21, 8, true, '', false, 99635616474.09, [-813181052, 1047029664, 1624056355, 811971774, -1386468615, -1386468615, -361733768], true, '2010-01-19 08:00:14', ["vhUt", "", ""], true);
TRUNCATE TABLE t3;
SELECT subt0.c_0_0 FROM  (SELECT t0_129.c_0_0, t0_129.c_0_1, t0_129.c_0_3, t0_129.c_0_4, t0_129.c_0_5 FROM t0 AS t0_129 WHERE JSON_EXISTS(parse_json('{"h": 0.8827607517980669, "j": "fNj", "WR": null, "OtgWn6": null, "m": "ZGS8W", "QALW": 1966652135}'), '') ) subt0 LEFT SEMI JOIN (SELECT t3_132.c_3_0, t3_132.c_3_1, t3_132.c_3_2, t3_132.c_3_3, t3_132.c_3_4, t3_132.c_3_5, t3_132.c_3_6, t3_132.c_3_7, t3_132.c_3_8, t3_132.c_3_9, t3_132.c_3_10, t3_132.c_3_11, t3_132.c_3_13, t3_132.c_3_14, t3_132.c_3_16 FROM t3 AS t3_132 WHERE (t3_132.c_3_1) IN ('1969-12-26', NULL) ) subt3 ON subt0.c_0_0 = subt3.c_3_4 AND subt0.c_0_0 != subt3.c_3_4;

### Expected behavior (Required)
no error

### Real behavior (Required)
--java.lang.AssertionError: SELECT subt0.c_0_0 FROM  (SELECT t0_129.c_0_0, t0_129.c_0_1, t0_129.c_0_3, t0_129.c_0_4, t0_129.c_0_5 FROM t0 AS t0_129 WHERE JSON_EXISTS(parse_json('{"h": 0.8827607517980669, "j": "fNj", "WR": null, "OtgWn6": null, "m": "ZGS8W", "QALW": 1966652135}'), '') ) subt0 LEFT SEMI JOIN (SELECT t3_132.c_3_0, t3_132.c_3_1, t3_132.c_3_2, t3_132.c_3_3, t3_132.c_3_4, t3_132.c_3_5, t3_132.c_3_6, t3_132.c_3_7, t3_132.c_3_8, t3_132.c_3_9, t3_132.c_3_10, t3_132.c_3_11, t3_132.c_3_13, t3_132.c_3_14, t3_132.c_3_16 FROM t3 AS t3_132 WHERE (t3_132.c_3_1) IN ('1969-12-26', NULL) ) subt3 ON subt0.c_0_0 = subt3.c_3_4 AND subt0.c_0_0 != subt3.c_3_4;
--	at sqlancer.common.query.QueryAdapter.checkException(QueryAdapter.java:98)
--	at sqlancer.common.query.QueryAdapter.executeAndGet(QueryAdapter.java:128)
--	at sqlancer.ComparatorHelper.getResultSetFirstColumnAsString(ComparatorHelper.java:54)
--	at sqlancer.starrocks.oracle.tlp.StarRocksTLPWhereOracle.check(StarRocksTLPWhereOracle.java:26)
--	at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:55)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:326)
--	at sqlancer.Main$2.run(Main.java:521)
--	at sqlancer.Main$2.runThread(Main.java:498)
--	at sqlancer.Main$2.run(Main.java:488)
--	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
--	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
--	at java.lang.Thread.run(Thread.java:748)
--Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Empty json path
--	at sun.reflect.GeneratedConstructorAccessor5.newInstance(Unknown Source)
--	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
--	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
--	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
--	at com.mysql.jdbc.Util.getInstance(Util.java:408)
--	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
--	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
--	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
--	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
--	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
--	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2497)
--	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2455)
--	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1369)
--	at sqlancer.common.query.QueryAdapter.executeAndGet(QueryAdapter.java:118)
--	... 10 more
---- Time: 2022/06/17 10:22:17
-- Database: w10
-- Database version: 5.1.0
-- seed value: 1655432455592
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+------------------------+
| current_version()      |
+------------------------+
| BRANCH_RELEASE 0d94ad8 |
+------------------------+
1 row in set (0.01 sec)

**Comment by kangkaisen** [comment]
not a bug.
