### ISSUE TITLE
[Enhancement] Integrate delta_writer_commit span into load_channel span

### ISSUE THREAD

**Issue by decster** [StarRocks/starrocks#7434]
## Enhancement
Currently, delta_writer_commit span runs in tablet_writer_add_chunk rpc handler, which is in bthread environment, and aync_delta_writer is used, so thread may get switched, as a result delta_writer_commit didn't `catch` load_channel span automatically, so we need to set delta_writer_commit span's parent explicitly.

**Comment by zombee0** [comment]
@decster 
Hello, i am interested in this and read the related code. Now, tabletschannel will generate several async write tasks, and wait the WriteCallback destroy->WriteContext destroy->count_down_latch become 0，it counts the time of this thread but not include the bthread of async_delta_writer. Do you mean these bthread time should be counted? and
I can not understand "as a result delta_writer_commit didn't catch load_channel span automatically, so we need to set delta_writer_commit span's parent explicitly."
thank you!

**Comment by decster** [comment]
![Screenshot from 2022-06-25 09-23-59](https://user-images.githubusercontent.com/193300/175753008-cf1137f3-445d-45e4-a072-3fd73f56b38a.png)
From the screenshot, you can see that delta_write_commit span is not integrated into txn span, the purpose of this issue is to integrate it, but since delta_write_commit is in bthread context, so using auto thread local context will not going to work, so we probably need to pass traceparent down to delta_write_commit and set delta_write_commit's parent manually.

**Comment by zombee0** [comment]
Thank you so much! I think I got something and 
How or where can I get the screenshot? I will try it and get better understanding.
