### ISSUE TITLE
Support JSON type in MySQL external table

### ISSUE THREAD

**Issue by wuliLSF** [StarRocks/starrocks#7483]
### Steps to reproduce the behavior (Required)
CREATE EXTERNAL TABLE t(
  `ids` json not null
) ENGINE=MYSQL 
COMMENT "MYSQL"
PROPERTIES (
"host" = "xxx",
"port" = "3306",
"user" = "xxx",
"password" = "xxx",
"database" = "xxx",
"table" = "t"
);

### Expected behavior (Required)
[1]

### Real behavior (Required)
ERROR 1064 (HY000): mysql row data parse error, column_data_type=27

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.2.1 147f178

**Comment by mofeiatwork** [comment]
We have no explicit support for MySQL JSON type, that needs some development in the future.

**Comment by k4124k** [comment]
same error on 2.2.2

**Comment by michael1991** [comment]
same error on 3.5.0 with PostgreSQL, meanwhile Doris treat json as string without exception.
@murphyatwork Can we support json or treat as string directly to avoid exception, we sincerely hope to use cloud native StarRocks !

**Comment by murphyatwork** [comment]
> same error on 3.5.0 with PostgreSQL, meanwhile Doris treat json as string without exception. [@murphyatwork](https://github.com/murphyatwork) Can we support json or treat as string directly to avoid exception, we sincerely hope to use cloud native StarRocks !

sounds like a good idea if it's a json string

**Comment by michael1991** [comment]
> > same error on 3.5.0 with PostgreSQL, meanwhile Doris treat json as string without exception. [@murphyatwork](https://github.com/murphyatwork) Can we support json or treat as string directly to avoid exception, we sincerely hope to use cloud native StarRocks !
> 
> sounds like a good idea if it's a json string

Good news, thanks in advance!
