### ISSUE TITLE
ctas task succeed after drop table

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#7492]
### Steps to reproduce the behavior (Required)
```
1. create ctas task
2. drop table
3. check task
```

### Expected behavior (Required)
`task failed`
### Real behavior (Required)
`task succeed`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.3-RELEASE b202d93 |
+----------------------------+
```

**Comment by Astralidea** [comment]
This does not need to be repaired. At present, our ctas does not guarantee a relatively strong consistency. We will wait until users have this demand.
