### ISSUE TITLE
transmit chunk rpc failed:c6b47b76-f096-11ec-b589-00163e14c865

### ISSUE THREAD

**Issue by huoyue-git** [StarRocks/starrocks#7511]
### Steps to reproduce the behavior (Required)
1. create table 
CREATE EXTERNAL TABLE `hive_ssb_100g_orc_customer` (
  `c_custkey` int(11) NULL COMMENT "",
  `c_name` varchar(26) NULL COMMENT "",
  `c_address` varchar(41) NULL COMMENT "",
  `c_city` varchar(11) NULL COMMENT "",
  `c_nation` varchar(16) NULL COMMENT "",
  `c_region` varchar(13) NULL COMMENT "",
  `c_phone` varchar(16) NULL COMMENT "",
  `c_mktsegment` varchar(11) NULL COMMENT ""
) ENGINE=HIVE
COMMENT "PARTITION BY ()"
PROPERTIES (
"database" = "ssb_orc",
"table" = "customer",
"resource" = "hive_resource_emr",
"hive.metastore.uris"  =  "thrift://172.26.194.238:9083"
);

CREATE TABLE `test_cross_join_30` (
  `id_int` int(11) NOT NULL COMMENT "",
  `id_double` double NOT NULL COMMENT "",
  `id_varchar` varchar(100) NOT NULL COMMENT "",
  `id_datetime` datetime NOT NULL COMMENT "",
  `id_decimal` decimal128(20, 3) NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`id_int`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id_int`) BUCKETS 1
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);

2. select '...'
use sqlsmith

select  
  ref_1.id_varchar as c0, 
  ref_0.c_phone as c1, 
  esquery(
    cast(ref_0.c_phone as VARCHAR),
    cast(ref_0.c_nation as VARCHAR)) as c2
from 
  sqlsmith.hive_ssb_100g_orc_customer as ref_0
    right join sqlsmith.test_cross_join_30 as ref_1
    on (ref_0.c_nation = ref_1.id_varchar )
where 39 <= ref_0.c_custkey
limit 93;

```
*** Aborted at 1655729091 (unix time) try "date -d @1655729091" if you are using GNU date ***
PC: @     0x7f0d54215894 __memmove_ssse3_back
*** SIGSEGV (@0x0) received by PID 12865 (TID 0x7f0d239a1700) from PID 0; stack trace: ***
    @          0x3f6dad2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f0d55678655 os::Linux::chained_handler()
    @     0x7f0d5567d481 JVM_handle_linux_signal
    @     0x7f0d55670678 signalHandler()
    @     0x7f0d54ba5630 (unknown)
    @     0x7f0d54215894 __memmove_ssse3_back
    @          0x19fc3e1 starrocks::vectorized::BinaryColumnBase<>::filter_range()
    @          0x24b90ea starrocks::vectorized::NullableColumn::filter_range()
    @          0x24a9eb6 starrocks::vectorized::Chunk::filter()
    @          0x344feff starrocks::vectorized::HdfsOrcScanner::do_get_next()
    @          0x3449f14 starrocks::vectorized::HdfsScanner::get_next()
    @          0x34018a7 starrocks::connector::HiveDataSource::get_next()
    @          0x2846dd4 starrocks::pipeline::ConnectorChunkSource::_read_chunk()
    @          0x2846f10 starrocks::pipeline::ConnectorChunkSource::buffer_next_batch_chunks_blocking()
    @          0x2841b38 _ZNSt17_Function_handlerIFvvEZN9starrocks8pipeline12ScanOperator18_trigger_next_scanEPNS1_12RuntimeStateEiEUlvE0_E9_M_invokeERKSt9_Any_data
    @          0x1fa2f70 starrocks::PriorityThreadPool::work_thread()
    @          0x3f09107 thread_proxy
    @     0x7f0d54b9dea5 start_thread
    @     0x7f0d541b88dd __clone
    @                0x0 (unknown)
```
### Real behavior (Required)
ERROR 1064 (HY000): transmit chunk rpc failed:c6b47b76-f096-11ec-b589-00163e14c865
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.3-RELEASE f2708fa |
+----------------------------+
1 row in set (0.00 sec)

**Comment by dirtysalt** [comment]
@huoyue-git I can not reproduce this case in my local env. Probably fixed by this PR: https://github.com/StarRocks/starrocks/pull/7436
