### ISSUE TITLE
sqlsmith_master_release:transmit chunk rpc failed:67d8ae86-f0a0-11ec-858b-00163e0025d1

### ISSUE THREAD

**Issue by huoyue-git** [StarRocks/starrocks#7517]
### Steps to reproduce the behavior (Required)
1. SELECT '...'
use sqlsmith;
select
  ref_0.c_customer_id as c0,
  ref_0.c_login as c1,
  ref_0.c_last_review_date as c2,
  e() as c3,
  ref_0.c_customer_id as c4,
  ref_0.c_birth_country as c5,
  ref_0.c_birth_day as c6,
  ref_0.c_last_name as c7,
  minute(
    cast(case when ref_0.c_current_hdemo_sk <> ref_0.c_birth_day then case when cast(null as DOUBLE) <> cast(null as DOUBLE) then cast(coalesce(cast(coalesce(cast(null as DATETIME),
            cast(null as DATETIME)) as DATETIME),
          cast(null as DATETIME)) as DATETIME) else cast(coalesce(cast(coalesce(cast(null as DATETIME),
            cast(null as DATETIME)) as DATETIME),
          cast(null as DATETIME)) as DATETIME) end
         else case when cast(null as DOUBLE) <> cast(null as DOUBLE) then cast(coalesce(cast(coalesce(cast(null as DATETIME),
            cast(null as DATETIME)) as DATETIME),
          cast(null as DATETIME)) as DATETIME) else cast(coalesce(cast(coalesce(cast(null as DATETIME),
            cast(null as DATETIME)) as DATETIME),
          cast(null as DATETIME)) as DATETIME) end
         end
       as DATETIME)) as c8,
  ref_0.c_salutation as c9,

    max(
      cast(ref_0.c_current_cdemo_sk as INT)) over (partition by ref_0.c_current_addr_sk,ref_0.c_current_hdemo_sk,ref_0.c_last_review_date order by ref_0.c_birth_year,ref_0.c_salutation) as c10,
  ref_0.c_birth_country as c11,
  ref_0.c_customer_sk as c12,
  tan(
    cast(cast(coalesce(case when ref_0.c_current_cdemo_sk < ref_0.c_birth_year then cast(nullif(
            max(
              cast(cast(null as DOUBLE) as DOUBLE)) over (partition by ref_0.c_customer_sk order by ref_0.c_email_address),
          e()) as DOUBLE) else cast(nullif(
            max(
              cast(cast(null as DOUBLE) as DOUBLE)) over (partition by ref_0.c_customer_sk order by ref_0.c_email_address),
          e()) as DOUBLE) end
        ,
      random()) as DOUBLE) as DOUBLE)) as c13,
  ref_0.c_birth_country as c14,
  ref_0.c_customer_id as c15,

    avg(
      cast(ref_0.c_birth_day as INT)) over (partition by ref_0.c_birth_country order by ref_0.c_login,ref_0.c_first_shipto_date_sk,ref_0.c_current_cdemo_sk) as c16,
  ref_0.c_email_address as c17,
  ref_0.c_login as c18,
  ref_0.c_first_name as c19,
  ref_0.c_last_review_date as c20,
  ref_0.c_current_hdemo_sk as c21,
  ref_0.c_birth_day as c22,
  ref_0.c_last_name as c23,
  ref_0.c_birth_month as c24
from
  sqlsmith.tpcds_100g_customer as ref_0
where ref_0.c_login is NULL
limit 87;

### Real behavior (Required)
transmit chunk rpc failed:67d8ae86-f0a0-11ec-858b-00163e0025d1
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.3-RELEASE f2708fa |
+----------------------------+
1 row in set (0.00 sec)

**Comment by ZiheLiu** [comment]
This is because another following sql  caused BE#0 crashed, then the above sql would throw the error "transmit chunk rpc failed", when the BE#1 sent chunks to BE#1.

```sql
select     ref_0.d_year as c0,    ref_0.d_month as c1,         max(       cast(ref_0.d_datekey as INT)) over (partition by ref_0.d_datekey order by ref_0.d_year) as c2,    unix_timestamp() as c3,    pi() as c4,    cast(coalesce(ref_0.d_lastdayinmonthfl,     ref_0.d_daynuminmonth) as INT) as c5,    ref_0.d_lastdayinmonthfl as c6,    ref_0.d_year as c7,    ref_0.d_year as c8 from    sqlsmith.hive_ssb_100g_orc_dates as ref_0 where (ref_0.d_date <= ref_0.d_month)    and (ref_0.d_datekey is NULL) limit 102;
```

The core stack is the same as #7666.
```
*** SIGSEGV (@0x28) received by PID 12646 (TID 0x7f7fbcafc700) from PID 40; stack trace: ***
    @          0x3fee4c2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f8041091655 os::Linux::chained_handler()
    @     0x7f8041096481 JVM_handle_linux_signal
    @     0x7f8041089678 signalHandler()
    @     0x7f80405be630 (unknown)
    @          0x1b3d948 starrocks::vectorized::BinaryColumnBase<>::append_selective()
    @          0x25fc068 starrocks::vectorized::NullableColumn::append_selective()
    @          0x25e9b2a starrocks::vectorized::Chunk::append_selective()
    @          0x35b3ac0 starrocks::pipeline::ExchangeSinkOperator::Channel::add_rows_selective()
    @          0x35b53dd starrocks::pipeline::ExchangeSinkOperator::push_chunk()
    @          0x29b4797 starrocks::pipeline::PipelineDriver::process()
    @          0x29a9b94 starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x2251c69 starrocks::ThreadPool::dispatch_thread()
    @          0x224d81a starrocks::Thread::supervise_thread()
    @     0x7f80405b6ea5 start_thread
    @     0x7f803fbd18dd __clone
    @                0x0 (unknown)
```
