### ISSUE TITLE
flink exactly once  problem

### ISSUE THREAD

**Issue by zck573693104** [StarRocks/starrocks#7534]
1. In practice, there are always data peaks or troughs, which directly lead to the task often memory overflow, so there is no way to ensure the use of this function in production, right?
2. At peak times, when there are more data entries, there are also import exceptions and the task hangs afterwards.
I wonder if the community has any suggestions for optimisation in subsequent versions based on the above two issues?

**Comment by jaogoy** [comment]
@zck573693104 you can try v2.4 and later, there is a new implementation of flink connector to load data using tranactional interface of stream load.
