### ISSUE TITLE
Starrocks queries

### ISSUE THREAD

**Issue by sridhard** [StarRocks/starrocks#7576]
Hi,

1. can we use starrocks on ubuntu? Should we build from source or can we use the release from https://starrocks.com/download/community?hsLang=en (StarRocks-2.2.0.tar.gz)
2. Should we use oracle-jdk? or open-jdk

Thanks

**Comment by imay** [comment]
@sridhard 
1. Yes you can run starrocks on ubuntu, and you don't need to build yourself. you can use the binary directly.
2. both are OK. just make sure use JDK not JRE.
