### ISSUE TITLE
Invalid Cluster ID

### ISSUE THREAD

**Issue by sridhard** [StarRocks/starrocks#7604]
Hi,

I have configured starrocks BE and FE. I changed some nodes for BE and FE and after that FE started successfully. But in be.Warning logs has a "Invalid cluster ID, ignore" error. So BE was not connecting to FE. Cluster ID in BE logs matched the cluster ID of FE (SHOW PROC '/frontends'\G)

So I deleted all data and started from the beginning and it started working.

When we deploy in production we cannot delete all the data and start again. 

By mistake I have not saved BE logs. Can you please tell me how can we debug this invalid cluster ID issue. I was not able to find cluster ID in any configs.

**Comment by imay** [comment]
The cluster id of BE come from FE. When one BE is added to a cluster, then the Leader FE of that cluster will send heartbeat to the BE. And the cluster id is contain in the heartbeat request. If the BE is new and it doesn't have cluster id, it will accept the first cluster id it receive and store it. Then if the BE receive heartbeat from other cluster Leader FE, it will recognize that the cluster id is not the same with it stores, it will report "Invalid cluster id". 
So the problem you meet is that the BE was add to different clusters. And you did the right thing to make it work normal.

When the cluster is in production, the BE should not be added to another cluster. So I think you won't encounter this problem again.

**Comment by sridhard** [comment]
ok.thanks
