### ISSUE TITLE
BE DECOMMISSION ERROR

### ISSUE THREAD

**Issue by mklzl** [StarRocks/starrocks#7607]
### Steps to reproduce the behavior (Required)
1. CREATE NEW CLUSTER (3FE + 3BE)

    
![image](https://user-images.githubusercontent.com/36362816/174927725-c5fcf3a6-3453-4638-a455-50cdfc75cc0a.png)

    

2.  DECOMMISSION BE

    ```` alter system decommission backend "192.168.1.241:9056";````

3. SHOW BACKENDS( after  10min, 0 databases, 0 tables, 0 data) 

    
![image](https://user-images.githubusercontent.com/36362816/174927778-ff271695-d20a-4e0d-b062-e39331c08071.png)

### Expected behavior (Required)

    192.168.1.241 BE has been decommissioned

### Real behavior (Required)

    192.168.1.241 has been exist

### StarRocks version (Required)
 - 2.2.1-147f178

**Comment by chaoyli** [comment]
@mklzl Could you give me a more detailed message?
