### ISSUE TITLE
User authorization bug

### ISSUE THREAD

**Issue by zck573693104** [StarRocks/starrocks#7634]
### Steps to reproduce the behavior (Required)
1.CREATE USER test_readOnly IDENTIFIED BY '123456';
2.GRANT SELECT_PRIV ON ods.test_view TO 'test_readOnly ';

### Expected behavior (Required)
Visible only  ods.test_view
### Real behavior (Required)
information_schema and  ods.test_view 
### StarRocks version (Required)
2.2.1 147f178

**Comment by jaogoy** [comment]
Can you explain much clearer? I can't understand.

**Comment by zck573693104** [comment]
> 

A new user has been created with read-only view privileges, but sees all the tables in the information_schema database
