### ISSUE TITLE
Add a fragment instance delivery time metric in profile

### ISSUE THREAD

**Issue by satanson** [StarRocks/starrocks#7639]
## Enhancement

In SR MPP schedule mechanism,  it is time-consuming to delivery the fragment instances of a query to BEs if the query has lots of Fragments and Fragment Instances. so we can add a instance delivery time metric for queries, this metric has the same lifetime as the QueryContext, so it can be put inside the QueryContext. the value of the metric will be the time duration from the first-arrival time of the instances till the last-arrival time of the instances. 

In BE, we can update the metric at these locations as follow:

```
// pipeline execution engine
be/src/exec/pipeline/fragment_executor.cpp
120:    LOG(INFO) << "Prepare(): query_id=" << print_id(query_id)

// non-pipeline execution engine
be/src/runtime/plan_fragment_executor.cpp
69:    LOG(INFO) << "Prepare(): query_id=" << print_id(_query_id)
```

In FE, when we merge fragment instance delivery times from BEs, wo can choose the maximum of delivery times as the final value of the profile.

Some knowledge on SR MPP scheduling is required to solve this issue, we can discuss together.

**Comment by dirtysalt** [comment]
looking forward to this feature.

**Comment by SzyWilliam** [comment]
@satanson Hi, I'm new to the StarRocks Community. I'm wondering if this issue is still open?

**Comment by satanson** [comment]
@SzyWilliam 
At the time that this issue is created, fragment instance delivery is quite a problem, now delivery is optimized by this PR https://github.com/StarRocks/starrocks/pull/8976, so it is not a pain point now, it is should be closed now.
