### ISSUE TITLE
Failed to join tables

### ISSUE THREAD

**Issue by sridhard** [StarRocks/starrocks#7644]
### Steps to reproduce the behavior (Required)
I have 2 tables. users and products. Users has 5.5 million records and products has 13 million records. Now I am joining these 2 tables using below query:
select * from users join products on users.id=products.user_id limit 100;

Above query fails in starrocks with the below error:
ERROR 1064 (HY000): Memory of Fragment 6f6e78ac-f20d-11ec-9085-029e3f8ecb72 exceed limit.  Used: 2137565025, Limit: 2147483648

I have loaded the same data in mysql and also in clickhouse.
mysql return result in 0.45 seconds. clickhouse return results in 2.05 seconds.

Hardware: 
clickhouse 1 node , aws Ec2 c5a.2x large, 8C 16GB memory
starrocks: 1 FE aws Ec2 c5a.xlarge 4C 8G. 1 BE aws Ec2 c5a.2xlarge 8C 16G

As per starrocks docs, join performance should be better in starrocks. But i am not able to join large tables.

### Expected behavior (Required)
Join should be success

### Real behavior (Required)
Join failed

### StarRocks version (Required)
2.2.0 671149f

**Comment by imay** [comment]
You'd better to give StarRocks more memory through `set exec_mem_limit = 4294967296` and try execute again.
And you test query only return 100 rows. MySQL nested-loop-join only fetch 100 rows. Clickhouse and starrocks use hash-join which will read the right tables in the memory which is time consuming.

I suggest you run a production query to test performance. 
such as 
`select sum(yyy) from users join products on users.id=products.user_id group by xxx limit 100;`

**Comment by sridhard** [comment]
@imay thanks a lot for quick reply.

We want to use starrocks for analytics. Also we have some queries like
1. Find list of users who have not purchased any product
2. get the video watch time at video level for each user

these kind of queries will return list of rows and we want to show these details to the admin.
For these kind of usecases can we use starrocks? will it have better or same performance as mysql?
