### ISSUE TITLE
Primary key model with CDC

### ISSUE THREAD

**Issue by sridhard** [StarRocks/starrocks#7661]
Hi,

We want to use CDC to stream data to starrocks from mysql. For this primary key model is the correct fit and this is suggested in starrocks docs also. 

But when I try to delete the data in table starrocks gives "primary key tablet do not support delete statement yet". There are already issues #4361 and PR #4500 for this.

1. What is the alternative way to handle CDC deletes?
2. When is the primary-key model delete feature is planned to release?

Thanks

**Comment by Dshadowzh** [comment]
1. You can check this document https://docs.starrocks.com/en-us/main/loading/Flink_cdc_load.
2. Delete statement for the primary key is about to be released in version 2.3, which may be published in the next two weeks.

**Comment by sridhard** [comment]
ok..thanks
