### ISSUE TITLE
Can we list frontends or backends in order when using `show frontends;` command?

### ISSUE THREAD

**Issue by jaogoy** [StarRocks/starrocks#7677]
## Enhancement

Currently, the list order will change, and I don't know the order rule.

There are two ways to improve the order:
1. List FEs or BEs with a fixed order, no matter a node leaves or joins in;
2. We can add `order by IP;` sub statement to sort FEs or BEs as we like.

**Comment by chaoyli** [comment]
https://github.com/StarRocks/starrocks/pull/7731/files
