### ISSUE TITLE
String data type length problem

### ISSUE THREAD

**Issue by Mile-Z** [StarRocks/starrocks#7704]
Starrocks has a maximum length of 65533 bytes for the variable-length string. It is recommended to adjust it to an unlimited length like hive. Reasons: 1. Medical data sometimes have family history or disease course records of some patients, and the string cannot be saved at all. 2. If the column is changed to a row, it may also exceed the limit. The data storage of the big data engine should not be so short, so that companies with large text storage requirements have no way to produce. welcome, thanks

### Expected behavior (Required)
The string just like hive.

### Real behavior (Required)
The string just like hive.

### StarRocks version (Required)
All version

**Comment by jaogoy** [comment]
So, what's the length of you P95 string field.
StarRocks now support 1MB length string, but it's still in experimental.

**Comment by Mile-Z** [comment]
Characters have more than one hundred thousand words

**Comment by Mile-Z** [comment]
Hello, I hope to develop it as soon as possible. Like hive's string, it can store 2g. If the column change is some large text, it will be exceeded all at once, such as the family history of the medical industry and other data. Now we are unavailable, waiting for starrocks development

**Comment by alberttwong** [comment]
updating this to the latest info.

the length of string type in SR can only maximum to 1MB, it’s a known issue.
one workaround is, you can use the JSON type, its maximum data length is 16MB

**Comment by alberttwong** [comment]
another variant of the same problem. 

```
Hi all. We have noticed an issue when reading a large string column from parquet file with select from files statement in SR. The value of a string is more than 1048576 bytes and SR reads this value as empty string. We have compared reading the same file with in memory DuckDB and there are no issues with empty string when compared with SR. Has anyone faced the same issue and knows how to solve it?
```
