### ISSUE TITLE
【Connector】catalog creation using the wrong IP address succeeded

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#7705]
### Steps to reproduce the behavior (Required)
1. CREATE 
```
CREATE EXTERNAL CATALOG hive_catalogtyK9SY comment "auicwmsYRF6zIto8" PROPERTIES("type"="hive", "hive.metastore.uris"="thrift://172.26.92.a:9002");
```
![image](https://user-images.githubusercontent.com/57162397/175263070-337915e3-afc1-4a93-9039-c5a981b2acd3.png)

### Expected behavior (Required)
ERROR 1064 (HY000): Unexpected exception: Invalid host of URI in hive.metastore.uris URI: thrift://IP:port
### Real behavior (Required)
create success 
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.3-RELEASE 5e27644 |
+----------------------------+
```

**Comment by DorianZheng** [comment]
![image](https://user-images.githubusercontent.com/8065637/175269130-ae117d2c-9daa-4019-8752-9b92cf920e43.png)

Even when perform `show databases` on the wrong catalog returns success
