### ISSUE TITLE
resource group big_query_scan_rows_limit didn't worked  when use limit 

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#7707]
### Steps to reproduce the behavior (Required)
```
create resource group rg2
to
    (user='root')
with (
    'cpu_core_limit' = '4',
    'mem_limit' = '10%',
    'concurrency_limit' = '2',
    'type' = 'normal',
    'big_query_scan_rows_limit' = '2'
);
select * from lineitem limit 3;
```
### Expected behavior (Required)
`ERROR 1064 (HY000): exceed big query scan_rows limit: current is 3 but limit is 2`
### Real behavior (Required)
`query ok`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.3-RELEASE 26f8840 |
+----------------------------+
```

**Comment by mofeiatwork** [comment]
https://github.com/StarRocks/starrocks/issues/8028
