### ISSUE TITLE
Starrocks Support Pulsar

### ISSUE THREAD

**Issue by zengguan** [StarRocks/starrocks#7893]
Can we support Pulsar just like Kafka?

**Comment by minchowang** [comment]
We need it too.

**Comment by chen9t** [comment]
> Of course, we will support pulsar later.

@imay Any progress?

We already have this feature and would be pleasure to contribute to community. Is it OK for us to contribute this?

**Comment by minchowang** [comment]
> > Of course, we will support pulsar later.
> 
> @imay Any progress?
> 
> We already have this feature and would be pleasure to contribute to community. Is it OK for us to contribute this?

Wow~, we very much look forward to this feature push to the community.

**Comment by chen9t** [comment]
Will update usage guide here and let's discuss it first...

**Comment by chen9t** [comment]
Pulsar routine load 基于现有 Kafka routine load 框架开发，对齐所有 Kafka routine load 已有的功能。详见: [Routine Load](https://docs.starrocks.com/zh-cn/main/loading/RoutineLoad#routine-load)。

但在某些 Pulsar 语义上有所不同，具体表现在 `CREATE ROUTINE LOAD` 和 `SHOW ROUTINE LOAD` 上:

## CREATE ROUTINE LOAD
以从一个本地 Pulsar 集群导入 CSV 数据为例：
```
CREATE ROUTINE LOAD load_test.routine_wiki_edit_1589191587 ON routine_wiki_edit
COLUMNS TERMINATED BY ",",
ROWS TERMINATED BY "\n",
COLUMNS (event_time, channel, user, is_anonymous, is_minor, is_new, is_robot, is_unpatrolled, delta, added, deleted)
WHERE event_time > "2022-01-01 00:00:00",
PROPERTIES
(
  "desired_concurrent_number" = "1",
  "max_batch_interval" = "15000",
  "max_error_number" = "1000"
)
FROM PULSAR
(
  "pulsar_service_url" = "pulsar://localhost:6650",
  "pulsar_topic" = "starrocks-load",
  "pulsar_subscription" = "starrocks-load-test",
  "pulsar_partitions" = "starrocks-load-partition-0,starrocks-load-partition-1",
  "pulsar_initial_positions" = "POSITION_EARLIEST,POSITION_LATEST",
  "property.pulsar_default_initial_position" = "POSITION_EARLIEST/POSITION_LATEST",
  "property.auth.token" = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUJzdWIiOiJqaXV0aWFuY2hlbiJ9.lulGngOC72vE70OW54zcbyw7XdKSOxET94WT_hIqD5Y"
);
```
`FROM` 子句之前的参数语义和 Kafka routine load 相同。
主要区别在与 `FROM` 子句之后的 data_source_properties。
### pulsar_service_url (必填)
```
Pulsar 的连接信息，格式为 ip:port 或 service:port。示例：

"pulsar_service_url" = "pulsar://localhost:6650"
```
### pulsar_topic (必填)
```
指定要订阅的 Pulsar 的 topic。示例：

"pulsar_topic" = "my_topic"
```
### pulsar_subscription (选填)
```
指定要订阅的 Pulsar 的 subscription。示例：

"pulsar_subscription" = "my_subscription"
```
### pulsar_partitions/pulsar_initial_positions (选填)
```
指定需要订阅的 pulsar partition，以及对应的每个 partition 的起始 position。

如果不指定 pulsar_partitions，则会自动展开 topic 下所有  partition 进行消费。

Position 的有效值为：
1. POSITION_EARLIEST: 从有数据的位置开始订阅。对应 Pulsar API 中的 SubscriptionInitialPosition.Earliest；
2. POSITION_LATEST: 从末尾开始订阅。对应 Pulsar API 中的 SubscriptionInitialPosition.Latest。

如果 pulsar_initial_positions 和 property.pulsar_default_initial_position 都没有指定，则 subscription 建立后收到的第一条数据的 position 订阅 topic 下的所有 partition。示例：

"pulsar_partitions" = "my-partition-0,my-partition-1,my-partition-2,my-partition-3",
"pulsar_initial_positions" = "POSITION_EARLIEST,POSITION_EARLIEST,POSITION_LATEST,POSITION_LATEST"
注意：上述属性设置，每设置一个分区需要设置对应分区的偏移量。
```
### property (选填)
指定自定义 Pulsar 参数。
功能等同于 ClientConfiguration 和 ConsumerConfiguration 中的 setXXX 函数。
目前支持两个参数，后续根据需求陆续添加。
#### property.pulsar_default_initial_position
指定 partition 默认的初始消费位置。
仅在 pulsar_positions 未指定时生效。有效值与 pulsar_positions 一致。示例：
```
"property.pulsar_default_initial_position" = "POSITION_EARLIEST"
```
#### property.auth.token
指定用来做认证的 token，为一个字符串。示例:
```
"property.auth.token" = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUJzdWIiOiJqaXV0aWFuY2hlbiJ9.lulGngOC72vE70OW54zcbyw7XdKSOxET94WT_hIqD"
```

**Comment by vampireDuke07** [comment]
Very Nice Bro! Our business scenario is looking forward to this feature. When will it be available

**Comment by vampireDuke07** [comment]
> Pulsar routine load 基于现有 Kafka routine load 框架开发，对齐所有 Kafka routine load 已有的功能。详见: [Routine Load](https://docs.starrocks.com/zh-cn/main/loading/RoutineLoad#routine-load)。
> 
> 但在某些 Pulsar 语义上有所不同，具体表现在 `CREATE ROUTINE LOAD` 和 `SHOW ROUTINE LOAD` 上:
> 
> ## CREATE ROUTINE LOAD
> 以从一个本地 Pulsar 集群导入 CSV 数据为例：
> 
> ```
> CREATE ROUTINE LOAD load_test.routine_wiki_edit_1589191587 ON routine_wiki_edit
> COLUMNS TERMINATED BY ",",
> ROWS TERMINATED BY "\n",
> COLUMNS (event_time, channel, user, is_anonymous, is_minor, is_new, is_robot, is_unpatrolled, delta, added, deleted)
> WHERE event_time > "2022-01-01 00:00:00",
> PROPERTIES
> (
>   "desired_concurrent_number" = "1",
>   "max_batch_interval" = "15000",
>   "max_error_number" = "1000"
> )
> FROM PULSAR
> (
>   "pulsar_service_url" = "pulsar://localhost:6650",
>   "pulsar_topic" = "starrocks-load",
>   "pulsar_subscription" = "starrocks-load-test",
>   "pulsar_partitions" = "starrocks-load-partition-0,starrocks-load-partition-1",
>   "pulsar_initial_positions" = "POSITION_EARLIEST,POSITION_LATEST",
>   "property.pulsar_default_initial_position" = "POSITION_EARLIEST/POSITION_LATEST",
>   "property.auth.token" = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUJzdWIiOiJqaXV0aWFuY2hlbiJ9.lulGngOC72vE70OW54zcbyw7XdKSOxET94WT_hIqD5Y"
> );
> ```
> 
> `FROM` 子句之前的参数语义和 Kafka routine load 相同。 主要区别在与 `FROM` 子句之后的 data_source_properties。
> 
> ### pulsar_service_url (必填)
> ```
> Pulsar 的连接信息，格式为 ip:port 或 service:port。示例：
> 
> "pulsar_service_url" = "pulsar://localhost:6650"
> ```
> 
> ### pulsar_topic (必填)
> ```
> 指定要订阅的 Pulsar 的 topic。示例：
> 
> "pulsar_topic" = "my_topic"
> ```
> 
> ### pulsar_subscription (选填)
> ```
> 指定要订阅的 Pulsar 的 subscription。示例：
> 
> "pulsar_subscription" = "my_subscription"
> ```
> 
> ### pulsar_partitions/pulsar_initial_positions (选填)
> ```
> 指定需要订阅的 pulsar partition，以及对应的每个 partition 的起始 position。
> 
> 如果不指定 pulsar_partitions，则会自动展开 topic 下所有  partition 进行消费。
> 
> Position 的有效值为：
> 1. POSITION_EARLIEST: 从有数据的位置开始订阅。对应 Pulsar API 中的 SubscriptionInitialPosition.Earliest；
> 2. POSITION_LATEST: 从末尾开始订阅。对应 Pulsar API 中的 SubscriptionInitialPosition.Latest。
> 
> 如果 pulsar_initial_positions 和 property.pulsar_default_initial_position 都没有指定，则 subscription 建立后收到的第一条数据的 position 订阅 topic 下的所有 partition。示例：
> 
> "pulsar_partitions" = "my-partition-0,my-partition-1,my-partition-2,my-partition-3",
> "pulsar_initial_positions" = "POSITION_EARLIEST,POSITION_EARLIEST,POSITION_LATEST,POSITION_LATEST"
> 注意：上述属性设置，每设置一个分区需要设置对应分区的偏移量。
> ```
> 
> ### property (选填)
> 指定自定义 Pulsar 参数。 功能等同于 ClientConfiguration 和 ConsumerConfiguration 中的 setXXX 函数。 目前支持两个参数，后续根据需求陆续添加。
> 
> #### property.pulsar_default_initial_position
> 指定 partition 默认的初始消费位置。 仅在 pulsar_positions 未指定时生效。有效值与 pulsar_positions 一致。示例：
> 
> ```
> "property.pulsar_default_initial_position" = "POSITION_EARLIEST"
> ```
> 
> #### property.auth.token
> 指定用来做认证的 token，为一个字符串。示例:
> 
> ```
> "property.auth.token" = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUJzdWIiOiJqaXV0aWFuY2hlbiJ9.lulGngOC72vE70OW54zcbyw7XdKSOxET94WT_hIqD"
> ```
> 
> ## SHOW ROUTINE LOAD
> TBD

and the Namespace?

**Comment by chen9t** [comment]
Namespace is part of the topic:
```
"pulsar_topic" = "persistent://tenant/namespace/topic-name"
```
Updated in the guide.

**Comment by chen9t** [comment]
# Routine Load for Pulsar design

## 整体思路

Pulsar routine load 整体沿用 Kafka routine load 的逻辑框架:

1. FE 通过 JobScheduler 将一个导入作业拆分成若干个 Task。每个 Task 负责导入指定的一部分数据。Task 被 TaskScheduler 分配到指定的 BE 上执行;
2. 在 BE 上，一个 Task 被视为一个普通的导入任务，通过 Stream Load 的导入机制进行导入。导入完成后，向 FE 汇报;
3. FE 中的 JobScheduler 根据汇报结果，继续生成后续新的 Task，或者对失败的 Task 进行重试;
4. 整个 Routine Load 作业通过不断地产生新的 Task，来完成数据不间断的导入。

### Pulsar 的主要差异点

Kafka routine load 主要通过在 progress 中记录被消费分区的 offset 来保证每轮 task 的连续性，同时在每次 commit 的时候将 offset 记录到 edit log 中，保证 exactly once 语义。对每个 partition offset 的记录与更新存在于 routine load job 的整个生命周期中。

Pulsar 中对应的概念为 MessageId，但是一个 MessageId 由多个元素组成，无法准确地从消费完的 MessageId 中推导出下一个可消费的位置，因此无法将 Kafka 的 offset 概念直接套用到 Pulsar 的 MessageId 上。所以选择直接依赖 subscription 的 cursor 在 broker 端自动记录消费进度，在 task info 中不再为 partition 指定 offset。仅在 create/alter 任务的时候，可让用户指定 initial position，指明下一轮消费从 latest/earliest 位置开始消费。

## FE 侧设计

FE 侧的主要工作分为以下几部分:

1. 解析用户输入，生成 routine load job instance，由 RoutineLoadScheduler 进行调度；
2. 将 job 拆分成 task 后放到 TaskScheduler 的 TaskQueue 上，等待下发；
3. TaskScheduler 不断检查 queue 上的 task，选择符合条件的 task 进行下发。

这里主要是逻辑相关的工作，将 Kafka 的相关逻辑根据 Pulsar 做一遍实现。以下是几个主要的数据结构，主要关注差异点:

### PulsarRoutineLoadJob

<img width="593" alt="PulsarRoutineLoadJob" src="https://user-images.githubusercontent.com/6762627/178760452-c17eafe6-0f99-41fc-9336-25461379a496.png">


### PulsarTaskInfo

<img width="458" alt="PulsarTaskInfo" src="https://user-images.githubusercontent.com/6762627/178760655-0f2160a7-544a-4d93-983f-e51ea1cb7937.png">


PulsarTaskInfo 通过 `readyToExecute()` 来感知 MQ 中是否有数据可消费，如果有再做任务的调度，在 Pulsar 中是通过获取 partition 的 backlog num 来实现的。不过该接口获取到的信息并不准确，因此可能会有误调度的情况。

### PulsarProgress

<img width="506" alt="PulsarProgress" src="https://user-images.githubusercontent.com/6762627/178760708-e4e1077d-48cd-46b2-9c5a-70e210524fe0.png">


* `partitionToBacklogNum` 为临时状态，仅用来记录当前消费的进度
* `partitionToInitialPositions` 可为空。仅当用户指定/修改消费位置的时候有值。因此需要随着 PulsarProgress 数据结构记录到 edit log 中，从而在重启的时候可以恢复状态。所以在 FeMetaVersion 中需要增加一个值，保持对旧版元数据的兼容。

### FE 与 BE 的通信

增加 `TPulsarLoadInfo` 数据结构，用来传递 TaskInfo:

```c++
struct TPulsarLoadInfo {
    1: required string service_url;
    2: required string topic;
    3: required string subscription;
    4: required list<string> partitions;
    5: optional map<string, i64> initial_positions;
    6: optional map<string, string> properties;
}
```

## BE 侧设计

BE 通过 `RoutineLoadTaskExecutor::submit_task` 提交任务，解析出 Pulsar 相关的数据结构后调用 `RoutineLoadTaskExecutor::exec_task` 开始执行任务。

### 数据消费

数据消费流程与 Kafka 保持一致，为每个 partition 创建出一个 consumer，一轮消费完成并 commit txn 后进行一次 cumulative acknowledge。

#### Consumer pool

创建 consumer 时沿用 consumer pool 的概念，从而可以复用之前已经创建出来的 consumer。

#### Consumer group

沿用 consumer group 概念，一个 routine load task 的 consumer 归在一个 group 下进行 group consume。

但是 Pulsar 单个 consumer 在消费多个 parition 的时候，无法做 cumulative acknowledge。因此这里限制了该 task 中 partition 的数量要 <= config::max_consumer_num_per_group，如果不满足，返回 `InternalError` 并做相关提示。

#### group consume

Consumer group 中，为每个 Pulsar consumer 开启一个线程，消费对应 partition 的数据，并将消费到的数据  append 到 group 的 `TimedBlockingQueue` 上。

Consumer group 的主线程持续从 queue 上获取数据，并 append 到 plan fragment 的 pipe 上进行数据的写入。中间碰到任何情况下的 eos 或 left_time <= 0 或 left_bytes <= 0 则退出消费。

### BE 与 FE 的通信

增加 `TPulsarRLTaskProgress` 数据结构，用来传递 progress:

```c++
struct TPulsarRLTaskProgress {
    1: required map<string,i64> partitionBacklogNum
}
```

随着 `TRLTaskTxnCommitAttachment` 带回 FE，主要用来传递本次消费完成后，相关 partition 的 backlog num 还有多少。用来更新 `PulsarRoutineLoadJob` 下的 progress 数据结构，从而可以在 show routine load 的时候展示消费进度。

由于这里调用的 Pulsar 接口无法准确反映实时的 backlog num 数据，所以该值仅作为参考。

**Comment by jaogoy** [comment]
@chen9t Aboult `pulsar_service_url`, is it a single url , or a list of node urls?

**Comment by chen9t** [comment]
> @chen9t Aboult `pulsar_service_url`, is it a single url , or a list of node urls?

Sorry I missed this message.

Multiple service urls is not tested before. This info is passed into pulsar C++ `Client(const std::string& serviceUrl)` API, so whether multiple service url is supported here depends on the API.
