### ISSUE TITLE
对已经存在的表的字段，追加或者修改字段描述功能

### ISSUE THREAD

**Issue by allenzhg** [StarRocks/starrocks#7931]
## Feature request

**Is your feature request related to a problem? Please describe.**
现在我已经建好的表，不能再修改这个表的字段的描述信息

**Describe the solution you'd like**
我想功能DDL语句对其修改字段的描述，

**Describe alternatives you've considered**
目前只能通过重建表，代价太大。

**Additional context**
![image](https://user-images.githubusercontent.com/20509543/176107982-08564668-b32d-45a4-a660-ca9342bb297d.png)

**Comment by chaoyli** [comment]
It's a good improvement for StarRocks. I will arrange person to do it @allenzhg
