### ISSUE TITLE
How to understand the gap of data capacity between `SHOW DATA` and `SHOW BACKENDS`

### ISSUE THREAD

**Issue by usharerose** [StarRocks/starrocks#8043]
## General Question
It seems that the values of data size/capacity are different between executing `SHOW DATA` and `SHOW BACKENDS`. Could the team give me a hand on
- if I want to monitor the disk usage of tables, which one is reliable (or others) ?
- how to understand this behavior?
- anything I missed which could be the root cause?

### StarRocks version
2.2.1

### Deployment
1 FE and 3 BEs, each of them is running as a Docker container. The path of each BE container's storage is also mounted on host machine individually

### Reproduction
- access StarRocks through MySQL client
  - collect `Size` by `SHOW DATA`
    - list all existing databases by `SHOW DATABASES`
    - switch to each of databases and execute `SHOW DATA`, store the value of column `Size` of the row `Total`
    - sum all of above `Total` as all existing data's size, aliasing as `show_data_size` 
  - collect `DataUsedCapacity` by `SHOW BACKENDS`
    - execute `SHOW BACKENDS`, store the value of column `DataUsedCapacity` of each record
    - sum all of above `DataUsedCapacity`, aliasing as `show_backends_size`
- access to the host machine
  - collect disk usage by `du`
    - assume the paths of mounted data folders are
      - `/home/ubuntu/starrocks/storage`
      - `/home/ubuntu/starrocks/storage1`
      - `/home/ubuntu/starrocks/storage2`
    - execute `du -h --max-depth 1 /home/ubuntu/starrocks/storage /home/ubuntu/starrocks/storage1 /home/ubuntu/starrocks/storage2`
    - get the disk usage of their `data` folder, sum them, aliasing as `du_size`

### Behavior
- `show_data_size`: around 39G
- `show_backends_size`: around 58G
- `du_size`: around 60G
The difference between `du_size` and `show_backends_size` should be due to the accuracy of demonstration. But the difference from `show_data_size` is a bit huge.

### Attachment
- result summary of `SHOW DATA`
```
mysql> SHOW DATABASES;
+---------------------+
| Database            |
+---------------------+
| _statistics_        |
...
| information_schema  |
...
+---------------------+
12 rows in set (0.19 sec)
```

| table name/alias | Size |
|---|---|
| table1 | 4.157 GB |
| table2 | 18.330 GB |
| table3 | 651.017 MB |
| table4 | 348.307 MB |
| table5 | 487.727 KB |
| table6 | 228.508 MB |
| table7 | 3.849 GB |
| table8 | 99.671 MB |
| table9 | 11.123 GB |
| table10 | 20.894 MB |
| _statistics_ | 703.104 KB |
| information_schema | 0.00 |
| TOTAL | ~ 38.81 GB |

- `SHOW BACKENDS` illustration
```
mysql> SHOW BACKENDS\G
*************************** 1. row ***************************
            BackendId: 12097
              Cluster: default_cluster
                   IP: 172.20.0.5
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2022-04-19 07:46:59
        LastHeartbeat: 2022-06-29 10:47:58
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
            TabletNum: 33083
     DataUsedCapacity: 23.539 GB
        AvailCapacity: 265.871 GB
        TotalCapacity: 484.643 GB
              UsedPct: 45.14 %
       MaxDiskUsedPct: 45.14 %
               ErrMsg:
              Version: 2.2.1-147f178
               Status: {"lastSuccessReportTabletsTime":"2022-06-29 10:47:26"}
    DataTotalCapacity: 289.411 GB
          DataUsedPct: 8.13 %
             CpuCores: 16
*************************** 2. row ***************************
            BackendId: 10002
              Cluster: default_cluster
                   IP: 172.20.0.4
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2022-04-14 10:33:57
        LastHeartbeat: 2022-06-29 10:47:58
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
            TabletNum: 32806
     DataUsedCapacity: 11.526 GB
        AvailCapacity: 265.871 GB
        TotalCapacity: 484.643 GB
              UsedPct: 45.14 %
       MaxDiskUsedPct: 45.14 %
               ErrMsg:
              Version: 2.2.1-147f178
               Status: {"lastSuccessReportTabletsTime":"2022-06-29 10:47:26"}
    DataTotalCapacity: 277.398 GB
          DataUsedPct: 4.16 %
             CpuCores: 16
*************************** 3. row ***************************
            BackendId: 12062
              Cluster: default_cluster
                   IP: 172.20.0.6
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2022-04-19 07:46:49
        LastHeartbeat: 2022-06-29 10:47:58
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
            TabletNum: 32772
     DataUsedCapacity: 23.465 GB
        AvailCapacity: 265.871 GB
        TotalCapacity: 484.643 GB
              UsedPct: 45.14 %
       MaxDiskUsedPct: 45.14 %
               ErrMsg:
              Version: 2.2.1-147f178
               Status: {"lastSuccessReportTabletsTime":"2022-06-29 10:47:25"}
    DataTotalCapacity: 289.337 GB
          DataUsedPct: 8.11 %
             CpuCores: 16
3 rows in set (0.18 sec)
```

- `du` illustration
```
> du -h --max-depth 1 ./starrocks/storage ./starrocks/storage1 ./starrocks/storage2
4.0K	./starrocks/storage/snapshot
64K	./starrocks/storage/error_log
4.0K	./starrocks/storage/tmp
172M	./starrocks/storage/meta
12G	./starrocks/storage/data
814M	./starrocks/storage/trash
13G	./starrocks/storage
4.0K	./starrocks/storage1/snapshot
16K	./starrocks/storage1/error_log
4.0K	./starrocks/storage1/tmp
173M	./starrocks/storage1/meta
24G	./starrocks/storage1/data
995M	./starrocks/storage1/trash
25G	./starrocks/storage1
4.0K	./starrocks/storage2/snapshot
12K	./starrocks/storage2/error_log
4.0K	./starrocks/storage2/tmp
172M	./starrocks/storage2/meta
24G	./starrocks/storage2/data
1.5G	./starrocks/storage2/trash
26G	./starrocks/storage2
```

**Comment by chaoyli** [comment]
It is caused by the data GC schedule. The tablet has been dropped and will still be in the data directory before GC is scheduled. `show data` only collect the valid data size. `show backends` collect all the capacity of the disk. @usharerose

**Comment by usharerose** [comment]
> It is caused by the data GC schedule. The tablet has been dropped and will still be in the data directory before GC is scheduled. `show data` only collect the valid data size. `show backends` collect all the capacity of the disk. @usharerose

@chaoyli Thanks for your explanation! If I understand correctly, that is why `show backends`'s result which shows the real capacity on disk can match `du` one but not `show data` which describe **logical** size I guess?

I have following questions.
- What would impact on garbage collection schedule?
  According to [official documents](https://docs.starrocks.com/zh-cn/main/administration/Configuration#be-%E9%85%8D%E7%BD%AE%E9%A1%B9), there are several BE configurations related to trash/garbage.
  - `trash_file_expire_time_sec`: I think this one would impact on the files under `storage/trash` only?
  - `max_garbage_sweep_interval` & `min_garbage_sweep_interval`: are they related configurations about garbage collection schedule you mentioned?
    - If positive, my current StarRocks works with default configurations (default max interval is `3600`). And the disk usage stats are still as same as several hours ago which garbage should have been swept. Why?
- Based on StarRocks data file system design, any approaches to get real disk usage stat on table granularity?

**Comment by usharerose** [comment]
Hi, @imay . Thanks for your reply! And please allow me to explain the context better ~

The gap I found from results is between 
- executing command `SHOW DATA` on each database, which around 38.81 GB totally
- executing `du` on each `storage/data` directory, which around 60G totally
```
12G	./starrocks/storage/data
24G	./starrocks/storage1/data
24G	./starrocks/storage2/data
```
, and not the directory `storage/trash`
(you can check from the post of this issue for more details)

> It is caused by the data GC schedule. The tablet has been dropped and will still be in the data directory before GC is scheduled. show data only collect the valid data size. show backends collect all the capacity of the disk. @usharerose

According to @chaoyli 's explanation, seems it is caused by the tablets dropped logically still being in `storage/data` directory. If those were handled by garbage collection thread, `max_garbage_sweep_interval` & `min_garbage_sweep_interval` should be the correct one influence on `storage/data` instead of  `trash_file_expire_time_sec`.
Then why I found no huge change on `storage/data`'s disk usage after far more than 1 hour when the default value of `max_garbage_sweep_interval` is `3600` only?

**Comment by usharerose** [comment]
Hi, @chaoyli @imay . Observed that both `storage/trash` & `storage/data` have no change on disk usage which should have reached the GC interval. Any suggestions (including the previous comment)?
