### ISSUE TITLE
[Enhancement] Integrate osquery

### ISSUE THREAD

**Issue by decster** [StarRocks/starrocks#8134]
## Enhancement
osquery is a tool to query os related information as tables. If we can integrate it into SR be, in theory, we can query the whole cluster and using sql expressions to filter/aggrate/join those data sources.  For example:

```
select filename from file where directory = <BE_PATH> and filename like 'core.%';

```

**Comment by imay** [comment]
very Interesting project.
I think we can support some table function to integrate osquery in starrocks.
