### ISSUE TITLE
error when concurrency dml & ddl execution on primary table with persistent index true

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#8144]
### Steps to reproduce the behavior (Required)
1. create primary table;
2. stream load with upsert mode;
3. stream load with delete mode;
4. update table set where;
5. delete from table where;
6. insert into table select from table;
7. truncate table;
8. select table
9. alter table;

query error when step 2-9 execute concurrently:
```
mysql> select * from primary_200cols_3rep limit 1;
ERROR 1064 (HY000): get_applied_rowsets failed, tablet updates is in error state: tablet:40091206 _apply_rowset_commit error: load primary index failed: IO error: cannot read fully
/root/starrocks/be/src/storage/persistent_index.cpp:1072 read_file->read_at_fully(offset, buff.data(), buff.size())
/root/starrocks/be/src/storage/persistent_index.cpp:1021 _load(index_meta) tablet:40091206 #version:882 [874.1 1703.1@880 1704] pending: rowsets:13
  423 [seg:1 row:3249 del:275 bytes:76496241 compaction:-10568054]
  445 [seg:1 row:26
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+--------------------+
| current_version()  |
+--------------------+
| 2.3.0-0629 e9bc0d7 |
+--------------------+
1 row in set (0.05 sec)
```

**Comment by sevev** [comment]
May be it is related with this pr https://github.com/StarRocks/starrocks/pull/8161
