### ISSUE TITLE
error when concurrency dml & dql execution on primary table

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#8148]
### Steps to reproduce the behavior (Required)
1. create primary table;
2. stream load with upsert mode;
3. stream load with delete mode;
4. update table set where;
5. delete from table where;
6. insert into table select from table;
7. truncate table;
8. select table

query error when step 2-8 execute concurrently:
```
Fri Jul 1 11:35:26 CST 2022
max(k38)        min(v45)
2022-06-14      A activity nothing team star clear world pull eight certain south magazin
Fri Jul 1 11:35:29 CST 2022
ERROR 1064 (HY000) at line 1: get_applied_rowsets(version 3) failed tablet:40111968 #version:1 [6 6@0 6] #pending:0
Fri Jul 1 11:35:32 CST 2022
max(k38)        min(v47)
2022-06-14      1970-01-01 16:02:21
```

### Expected behavior (Required)
query returned right result

### Real behavior (Required)
ERROR 1064 (HY000) at line 1: get_applied_rowsets(version 3) failed tablet:40111968 #version:1 [6 6@0 6] #pending:0

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+--------------------+
| current_version()  |
+--------------------+
| 2.3.0-0630 b89ba7c |
+--------------------+
1 row in set (0.06 sec)
```

**Comment by chaoyli** [comment]
[#10694](https://github.com/StarRocks/starrocks/pull/10694)
