### ISSUE TITLE
动态修改hive外表连接Metastore的用户

### ISSUE THREAD

**Issue by NorthSeaWang** [StarRocks/starrocks#8150]
【版本】2.1
目前配置hive外表连接hive Metastore的用户，只能在fe/conf/hadoop-env中指定一个。
如果在生产中，希望同时访问其他用户的hive资源，就非常不方便。希望可以动态指定

**Comment by wangyouzhuo** [comment]
你们有一个sr同时访问多个hadoop集群的场景么

**Comment by NorthSeaWang** [comment]
目前还没有。主要是同一个hadoop集群中，会对不同用户做权限控制。这种情况下sr想切换访问用户时，比较麻烦
