### ISSUE TITLE
fail to drop materialized view

### ISSUE THREAD

**Issue by wangsimo0** [StarRocks/starrocks#8182]
### Steps to reproduce the behavior (Required)
drop materialized view like:

`drop MATERIALIZED view test from test;`

it returns 

ERROR 1064 (HY000): mismatched input 'from' expecting {<EOF>, ';'}

### Expected behavior (Required)

`Query OK, 0 rows affected (0.00 sec)`

### StarRocks version (Required)
branch-2.3

**Comment by jaogoy** [comment]
Can we create two MVs with the same name in different tables?
For that there isn't a table name specified in `create MV statement` directly.
`CREATE MATERIALIZED VIEW [MV name] as [query]`

**Comment by ABingHuang** [comment]
drop MATERIALIZED view mv1 from test;
this sql is an old sql grammar, which will be discarded.
if you want to drop rollup, you can use alter table test drop rollup mv1;
