### ISSUE TITLE
Add a Predicate cache to speedup ScanOperators

### ISSUE THREAD

**Issue by satanson** [StarRocks/starrocks#8193]
## Feature request

StarRocks users like to define bloom-filter/bitmap indexes on some columns of OlapTable to speedup filtering row ordinals, but we can support a Predicate Cache(PC) that holds results generated by predicates applied to some columns, thus when we evaluated predicate on some columns, Predicate cache is probed at first, in situation of hitting cache, the cost of disk IO and predicate evaluation is saved.

**Describe the solution you'd like**

The CacheKey of PC may be formed from stringified predicate, tablet Id and latest version; the  CacheValue of  PC may be encoded as a roaring bitmap.

**Describe alternatives you've considered**

**Additional context**

Any guy wants to work on this feature can discuss with me.

**Comment by jiahui-97** [comment]
How PC work? Is there an example?
What code should I look at to get started with this job?

**Comment by kangkaisen** [comment]
@jiahui-97 Hi, thanks you very much. but this issue is a little hard. could you try anther easy issue as your first contribution to StarRocks.
