### ISSUE TITLE
V2.3 Release Plan

### ISSUE THREAD

**Issue by wangyouzhuo** [StarRocks/starrocks#8207]
**New Features**

- The **Primary Key model** supports the full DELETE WHERE syntax
- The **Primary Key** model supports persistent primary key indexes to prevent excessive memory consumption
- When a Routine Load job is executed, and a **global dictionary** is built to optimize queries on low-cardinality columns, the global dictionary can be updated, thus improving query performance.
- Stream Load provides **a transaction interface that supports splitting the execution of "sending data" and "submitting transaction"**, enabling two-phase commit of transactions tha stream data by Apache Flink® and improve loading performance with highly concurrency.
- The **CREATE TABLE AS SELECT** statement can be executed asynchronously and write results to a new table.
- Support the following **resource group-related features**:
  - Monitor resource groups: You can view a query in which resource group from the audit log and call API operations to obtain the monitoring metrics of resource groups.
  - Limit the consumption of large queries on CPU, memory, or I/O resources: You can route queries to resource groups by matching classifiers or configure session variables to directly specify resource groups for queries.
 - StarRocks provides **JDBC external tables** to query Oracle, PostgreSQL, MySQL, SQLServer, Clickhouse, and other databases. StarRocks also supports predicate pushdown when performing queries.
 - [Preview] A new Data Source Connector framework support user-defined **external catalogs**. You can use the external catalogs to directly analyze Hive without creating any external tables.
 - Add the following functions：
  - window_funnel
  - ntile
  - bitmap_union_count
  - week
 - Add the **EXECUTE AS** statement. After you use the GRANT statement to impersonate a specific user identity to perform operations, you can use the EXECUTE AS statement to switch the execution context of the current session to this user.

**Improvements**

- The compaction mechanism can merge large metadata more quickly. This prevents metadata squeezing and excessive disk usage that can occur shortly after frequent data updates.
- The performance of loading Parquet files and compressed files is optimized.
- The mechanism of creating materialized views is optimized. After the optimization, materialized views can be created at a speed up to 10 times higher than before.
- The performance of the following operators is optimized:
  - TopN and sort operators
  - Equivalence comparison operators that contain functions can use Zone Map indexes when these operators are pushed down to scan operators.
- Optimize the Apache Hive™ external tables. 
  - When Apache Hive™ Table is stored as Parquet, ORC, or CSV format, StarRocks can sync the **schema changes** like ADD COLUMN and REPLACE COLUMN when users perform REFRESH statement.
  -  Hive resources' **hive.metastore.uris** can be modified.
- Optimize the Elasticsearch external tables: Sniffing the addresses of the data nodes in an Elasticsearch cluster can be disabled.
- When the sum() function calculates numeric strings, implicit conversion is performed.
- Optimize the **GRANT** statements.
  - Use the GRANT statement to grant a role to a user, or to grant user_a the privilege to perform operations as user_b.
  - Use the REVOKE statement to revoke a role from a user, or to revoke the privilege that allows user_a to perform operations as user_b.
- The **8year, month, and day functions** support the DATE data type.

**Others**
- StarGo, a cluster management tool, can deploy, start, upgrade, and roll back clusters and manage multiple clusters. 
- StarRocks clusters can be quickly deployed on AWS by using CloudFormation.

**Comment by wangyouzhuo** [comment]
> 

The 2.3 RC version is ready to release now, and the 2.3 formal version will be released after 2 weeks in this month

**Comment by cj1201** [comment]
能支持delete 删除条件子查询吗

**Comment by leoyy0316** [comment]
expect better

**Comment by hoojunev** [comment]
is the primaryKey model support update table in plan list of V2.3 release?

**Comment by hoojunev** [comment]
@wangyouzhuo  Does the primaryKey model support update table in plan list of V2.3 release?
