### ISSUE TITLE
Support GlobalRuntimeFilter for intersect node

### ISSUE THREAD

**Issue by Seaven** [StarRocks/starrocks#831]

**Comment by dirtysalt** [comment]
I got the idea. The intersect node looks like

```
      Intersect
    /     |         \
A      B       C
```

So theoretically we can generate runtime filter on A, and push that RF down to B, C. 

But right now we have some limitations of runtime filter, the major one is our global runtime filter only supports one equal predicates (we can improve that later). And for intersect node, in many real scenario, there should be not only one columns. So our global runtime filter is quite limited.

I decide to close this issue right now. And maybe we can bright it back when we support multi equal predicates global runtime filter.
