### ISSUE TITLE
是否可以增加单独的修改表comment和字段comment的语法

### ISSUE THREAD

**Issue by zxb2503** [StarRocks/starrocks#8389]
目前版本2.1.8 ，想要修改字段的comment信息，只能通过modify column 来执行
执行alter table yyf_tcodepay_allhis_his_sr modify column `pay_channel` tinyint(4) NULL COMMENT " 支付通道  (1.支付宝, 17开放平台扫码)"; 其实只有comment有变动，查看show alter table column;好像表所有的tablet都要变更一遍，比较耗费时间，是否可以增加单独的修改表和字段comment的语法
![d4d6b527dceb2aaf83d89ed54312f93](https://user-images.githubusercontent.com/76046810/177708748-96d4e80f-5e63-4332-8337-ec050df2e81d.png)

**Comment by chengqiZ** [comment]
i have the same question, how to modify table comment ?

**Comment by mumugoah** [comment]
I have the same issue，require table comment update
