### ISSUE TITLE
FE运行一段时间后，CPU占用一直100%

### ISSUE THREAD

**Issue by luqiyeyaner** [StarRocks/starrocks#8393]
fe节点运行一段时间，莫名就会CPU30%左右，FE三节点部署，两个从节点均是30%，重启无法解决，只有重启FE主节点，重新选举后，CPU才能降下来，连续运行一段时间又会出问题，现在主要是测试在用，总数据量500W左右，没有查询压力。
版本2.2.2，已经升级2.3.0-rc1，问题依旧
TOP命令截图：
![image](https://user-images.githubusercontent.com/5086796/177721037-a63f1368-68ce-4555-a1c9-cb9237d2ff47.png)
top -H -p 截图：
![image](https://user-images.githubusercontent.com/5086796/177721135-bfc47144-b06e-4589-8643-6b1d19730e25.png)
jstack截图
![image](https://user-images.githubusercontent.com/5086796/177721173-61ec8904-3417-488b-9b23-10587b66d546.png)
出问题的时候，一直在进行GC，如图
![image](https://user-images.githubusercontent.com/5086796/177721288-796697ed-c0ae-4a2e-b37f-bebfa43e7fe2.png)

**Comment by gengjun-git** [comment]
30% ~ 50% occupied cpu for master fe is normal, because there is several daemon threads like tablet health check, job scheduler.

**Comment by luqiyeyaner** [comment]
不是主节点，主节点占用cpu很低，主要是两个从节点，刚启动很低，什么都不做，运行一天后，两个从节点的replayer线程耗CPU厉害，重启无法解决，当重启主节点进行重新选主后，CPU恢复正常，再次运行又有问题，当出问题的时候，newSize一直在进行GC

**Comment by luqiyeyaner** [comment]
> 30% ~ 50% occupied cpu for master fe is normal, because there is several daemon threads like tablet health check, job scheduler.

不是主节点，主节点占用cpu很低，主要是两个从节点，刚启动很低，什么都不做，运行一天后，两个从节点的replayer线程耗CPU厉害，重启无法解决，当重启主节点进行重新选主后，CPU恢复正常，再次运行又有问题，当出问题的时候，newSize一直在进行GC

**Comment by gengjun-git** [comment]
18810663282 can you contact me on wechat?

**Comment by gengjun-git** [comment]
The replayer thread occupied too much cpu. We will optimize it.
