### ISSUE TITLE
add new function about row to column

### ISSUE THREAD

**Issue by Mile-Z** [StarRocks/starrocks#8409]
It is recommended to add a function that supports row to column and can deduplicate,he original group_concat function does not support deduplication,thanks

**Comment by trueeyu** [comment]
can use `array_join` + `array_distinct` + `array_agg` ?

**Comment by Mile-Z** [comment]
Array de duplication does not guarantee the order. I need the order of field aggregation.thanks

**Comment by imay** [comment]
> Array de duplication does not guarantee the order. I need the order of field aggregation.thanks

array_sort can sort the array.

**Comment by Mile-Z** [comment]
The order I'm talking about is not its internal size order, but the position of each field before row to column should correspond to other columns one by one, just like the data in the figure below. The data of each column after row to column conversion and de duplication should correspond to
![image](https://user-images.githubusercontent.com/91326053/177919413-ad750c8a-2da6-46d0-bc58-ce9f81e665fd.png)

**Comment by trueeyu** [comment]
I understand what you mean, we should support it in the future
