### ISSUE TITLE
2.2.2版本访问视图提示用户基表无权限

### ISSUE THREAD

**Issue by zxb2503** [StarRocks/starrocks#8419]
从2.1.8 升级到了2.2.2 遇到一个问题，有一个视图是基于原表进行的脱敏处理，视图的查询权限已授予用户，升级后查询视图提示没有原表的查询权限

![900e2d5b1fecb46b06f857336007cb7](https://user-images.githubusercontent.com/76046810/177929987-e828156b-230e-4cc0-a324-2f039dbf6ccb.png)

**Comment by wangkunk** [comment]
遇到同样问题 2.2版本都有
