### ISSUE TITLE
sql似乎不支持正则捕获

### ISSUE THREAD

**Issue by Allaitian** [StarRocks/starrocks#8429]
## General Question

执行SQL：select regexp_extract('Aqwe','(?<=A).*',0) ;
返回结果：ERROR 1064 (HY000): Invalid regex expression: (?<=A).*:

**Comment by jaogoy** [comment]
Yes, StarRocks doesn't support it yet.
Any scenarios to use such functionality?

**Comment by josh7** [comment]
我们遇到这样的场景，
SELECT regexp_extract('本金1599.96元,收益54.46元', ? ,0);
正则这样写'(?<=收益 )[.\d]+(?= 元)'就可以了，但是在starrock里取不到，要怎么写呢

**Comment by josh7** [comment]
@jaogoy 
能支持吗

**Comment by Allaitian** [comment]
@jaogoy 业务当中需要从一个字符串中取数字，解决方法是有，需要多绕一下，没有捕获来的直接。
