### ISSUE TITLE
About task_worker_pool.cpp warning log

### ISSUE THREAD

**Issue by zhaoawd** [StarRocks/starrocks#8570]
## General Question
I found the warning log judge statement changed in the commit abd4f78ccf8cd719183f15274ae507a84f631489, at the
687 line. It changed from !status.ok() to status->ok(). In my log, the commit successed, but be.WARNING prints belows:
![image](https://user-images.githubusercontent.com/3120566/178398680-441cddcc-7060-4b79-ab9d-9faf970c8b82.png)

**Comment by imay** [comment]
@zhaoawd you are right, would you like to fix this typo?

**Comment by zhaoawd** [comment]
Ok, I will fix this typo.
