### ISSUE TITLE
time_functions from_unixtime does not support HH:mm:ss or HHmmss  format

### ISSUE THREAD

**Issue by dm520** [StarRocks/starrocks#8616]
### Steps to reproduce the behavior (Required)
time_functions from_unixtime does not support HH:mm:ss or HHmmss  format

select from_unixtime(1196440219, 'HHmmss');
select from_unixtime(1196440219, 'HH:mm:ss');

### Expected behavior (Required)
select from_unixtime(1196440219, 'HHmmss');
003019

select from_unixtime(1196440219, 'HH:mm:ss');
00:30:19

### Real behavior (Required)
HHmmss
HH:mm:ss

### StarRocks version (Required)

2.1.6 d44c230

**Comment by dm520** [comment]
This can be achieved in the following ways
     select from_unixtime(1196440219, '%H%i%s');
     select from_unixtime(1196440219, '%H:%i:%s');
but  I still hope to fix this bug  in 

https://github.com/StarRocks/starrocks/blob/fe451f0a4ffa167c32dc08466f5adf7c27e0fc03/be/src/exprs/vectorized/time_functions.cpp

**Comment by kangkaisen** [comment]
which isn't bug. we don't support 'HHmmss' and 'HH:mm:ss' like mysql
