### ISSUE TITLE
[Bug] there is an duplicate refresh task after creating new materialized view

### ISSUE THREAD

**Issue by ABingHuang** [StarRocks/starrocks#8651]
### Steps to reproduce the behavior (Required)
1. create table and materialized view

CREATE TABLE tbl1
(
k1 date,
k2 int,
v1 int sum
)
PARTITION BY RANGE(k1)
(
    PARTITION p1 values less than('2022-02-01'),
    PARTITION p2 values less than('2022-03-01')
)
DISTRIBUTED BY HASH(k2) BUCKETS 3
PROPERTIES('replication_num' = '1');

CREATE MATERIALIZED VIEW mv1_partition_by_column
distributed by hash(k2)
refresh async  EVERY(INTERVAL 1 HOUR)
PROPERTIES('replication_num' = '1')
as select k2, sum(v1) as total from tbl1
group by k2;

2. query related task run for this materialized view

select * from information_schema.task_runs order by create_time desc;

### Expected behavior (Required)

there is only one refresh task for this async refresh type materialized view

### Real behavior (Required)
there are two task run after creating new materialized view
![image](https://user-images.githubusercontent.com/101158374/178736293-fe67e1ca-ced6-4c7e-bfe7-73a09755f21a.png)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main

**Comment by QingdongZeng3** [comment]
Please assign this issue to me.

**Comment by caneGuy** [comment]
> Please assign this issue to me.

cool
