### ISSUE TITLE
Please keep the NOTICE file of the Apache Doris project

### ISSUE THREAD

**Issue by moonming** [StarRocks/starrocks#87]
Hello, I am Ming Wen, Mentor of Apache Doris(Incubating), Member of Apache Software Foundation.
StarRocks is forked from Apache Doris(Incubating), so you need to follow the Apache 2.0 License and keep the complete NOTICE file.

**Comment by imay** [comment]
Hi, @moonming the NOTICE file's content is included in [APACHE-LICENSE-2.0.txt](https://github.com/StarRocks/starrocks/blob/main/APACHE-LICENSE-2.0.txt). 
Please check.

**Comment by CalvinKirs** [comment]
You misunderstood, you can refer to this https://www.apache.org/licenses/LICENSE-2.0.html#redistribution, Article 4

**Comment by imay** [comment]
> You misunderstood, you can refer to this https://www.apache.org/licenses/LICENSE-2.0.html#redistribution, Article 4

I think that we have provided "readable copy" in our source, which is compliant with the License requirements.

**Comment by decster** [comment]
@imay They mean NOTICE file should remain in a NOTICE file, not in the LICENSE file

**Comment by decster** [comment]
like this:https://github.com/apache/incubator-doris/blob/master/NOTICE.txt

**Comment by decster** [comment]
@moonming @CalvinKirs  Thanks for pointing this out.

**Comment by xiaoxiaopan118** [comment]
I thins you'd better notice the starrocks 90% code is from Apache Doris,
https://github.com/apache/incubator-doris
Thanks!
