### ISSUE TITLE
Hive external table huawei OBS

### ISSUE THREAD

**Issue by wangsan1988** [StarRocks/starrocks#8721]
## General Question

StarRocks Hive external table  location at huawei OBS, seem not support 。
![image](https://user-images.githubusercontent.com/30817233/179142469-cc76e980-875b-46e3-8f13-0b74f54a71a5.png)

hive表，location在华为云obs，在starrocks创建外部表后，查询时，报错。
[42000][1064] com.starrocks.common.DdlException: get partition detail failed: com.starrocks.common.DdlException: get hive partition meta data failed: No FileSystem for scheme “obs”
目前是不支持这种场景吗？
谢谢

**Comment by jaogoy** [comment]
StarRocks doesn't supported OBS yet.

**Comment by Dshadowzh** [comment]
Broker load using OBS is supported(https://github.com/StarRocks/starrocks/pull/1182) but external table is not yet.
