### ISSUE TITLE
Parquet decode min/max crashes when type mismatch

### ISSUE THREAD

**Issue by dirtysalt** [StarRocks/starrocks#8848]
### Steps to reproduce the behavior (Required)

create hive table like following

```
create table t (
  id int;
)
```

but putting parqurt file with `id  varchar` onto hdfs, and create table in SR like

```
create table t (
id int
)
```

and run query like 'select * from t where id > 10`

### Expected behavior (Required)

query ok

### Real behavior (Required)

BE crashes

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

**Comment by jaogoy** [comment]
@dirtysalt Maybe you can describe the operation more clear.
Did the BE crash when loading data from parquet file, or when selecting data from parquet file through external file?

**Comment by dirtysalt** [comment]
I update brief procedure.

BE crashes when quering data from parquet file.
