### ISSUE TITLE
String长度太短，没办法存大数据

### ISSUE THREAD

**Issue by Mile-Z** [StarRocks/starrocks#8897]
starrock类型的字符串最大长度 65533 字节，在UTF-8下只能存两万多个字，强烈建议将它修改成像hive一样能存2g，医疗行业有很多家族史这种大文本，或者经常有列转行的操作，很容易超出，目前很多业务已经不可用，希望能够尽快添加，感谢，上个月已经提出过这个issue！

**Comment by mofeiatwork** [comment]
Replied in previous issue.
