### ISSUE TITLE
Pagling query (page number at the tail) is very slow

### ISSUE THREAD

**Issue by YangWei1997** [StarRocks/starrocks#8996]
## Enhancement
# demand
Pagling query to SR million -level tables

Table DDL:
```
create table dwd_bolean_sa_event_standard_detail_ri_test
(
   event_ts DATETIME,
   src_id STRING,
   src_type STRING,
   src_name STRING,
   asset_name STRING,
   event_level Int,
   event_level_cn String,
   attack_chain String,
   event_type Int,
   event_type_cn String,
   event_name String,
   event_desc String,
   l7_pact String,
   src_ip String,
   dst_ip String,
   src_port Int,
   dst_port Int
)ENGINE = OLAP
-- DUPLICATE KEY(event_ts)
PARTITION BY RANGE(event_ts)(
    START ("2022-06-01") END ("2022-06-30") EVERY (INTERVAL 1 day)
)
DISTRIBUTED BY HASH(event_ts) BUCKETS 32
PROPERTIES(
    "dynamic_partition.enable" = "true",
    "dynamic_partition.time_unit" = "DAY",
    "dynamic_partition.start" = "-180",
    "dynamic_partition.end" = "30",
    "dynamic_partition.prefix" = "p",
    "dynamic_partition.buckets" = "32",
    "replication_num" = "1" 
);
```

# The amount of data
349w
<img width="782" alt="image" src="https://user-images.githubusercontent.com/50506546/180162185-76a1f7b4-ed40-410f-917f-d23a1ecb998f.png">

# Query SQL
`
select * from dwd_bolean_sa_event_standard_detail_ri_test dbsesdrt limit 1000000, 1000010;
`
<img width="916" alt="image" src="https://user-images.githubusercontent.com/50506546/180163604-557cce9a-6b3b-4694-847e-5eeb2bc5b19a.png">

# result
Either report an error or a few minutes to make results

# The same SQL query in CK
The response is very fast
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/50506546/180164547-9f73a8df-25a1-4a33-b1d6-905e84b3d118.png">

# solution
Is there a solution in this pagination query? Is there a solution in SR?

**Comment by kangkaisen** [comment]
@YangWei1997 Hi，I think the reason maybe is CK only return 200 rows, not the 1000010 rows. you could ensure this point, thanks.
