### ISSUE TITLE
[BUG][BE] Stream load json data error message is not clear

### ISSUE THREAD

**Issue by zhuxt2015** [StarRocks/starrocks#9012]
### Steps to reproduce the behavior (Required)
1. Use Stream load 79M json file
2. one success and another failed

### Expected behavior (Required)
The data is imported normally
### Real behavior (Required)
<img width="919" alt="image" src="https://user-images.githubusercontent.com/13765310/180204200-3e58bf76-7c6f-464f-94b4-bd959d322c88.png">
<img width="421" alt="image" src="https://user-images.githubusercontent.com/13765310/180204228-b95e894b-b2a8-4c47-9f9f-af6574b1b696.png">

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

2.3.0-RC03 a792b15

**Comment by rickif** [comment]
@zhuxt2015 Do you mind uploading the test data file? So I could reproduce the problem.

**Comment by zhuxt2015** [comment]
check out be code,  It should be caused by a single json body too large, please reponse `ErrorURL` , notice the user that there is an error in json.
<img width="835" alt="image" src="https://user-images.githubusercontent.com/13765310/180208441-3afe01c0-73d4-4412-8c19-01d2b3310ada.png">

**Comment by rickif** [comment]
This error is expected to return when the payload in ndjson format is beyond 4GB. So, maybe there's something wrong here.
https://github.com/simdjson/simdjson/blob/master/doc/basics.md
![image](https://user-images.githubusercontent.com/16649269/180210111-87b9d7d7-cdde-4138-8421-6b3b8b41e5fb.png)

**Comment by zhuxt2015** [comment]
I find the max json by this command.
```
awk '{if(length(max) < length()) max=$0} END{print max}' jab > large_json
```
[large_json.zip](https://github.com/StarRocks/starrocks/files/9159164/large_json.zip)

**Comment by rickif** [comment]
> I find the max json by this command.
> 
> ```
> awk '{if(length(max) < length()) max=$0} END{print max}' jab > large_json
> ```
> 
> [large_json.zip](https://github.com/StarRocks/starrocks/files/9159164/large_json.zip)

I've done a some test. It seems that the simdjson parser cannot parse this and reports incorrect error message. I'll investigate this. 
```
#include "simdjson.h"
#include <iostream>
using namespace simdjson;

int main(void) {
    ondemand::parser parser;
    padded_string data = padded_string::load("large_json");

    ondemand::document_stream stream = parser.iterate_many(data);
    for (auto itr = stream.begin(); itr != stream.end(); ++itr) {
        auto doc = *itr;
        simdjson::ondemand::object obj = doc.get_object();
        std:: cout << obj << std::endl;
    }
}
```

**Comment by rickif** [comment]
![image](https://user-images.githubusercontent.com/16649269/180213961-c4a5e943-96c6-4cfa-9c28-1ed2aa18db81.png)
