### ISSUE TITLE
Backends with same host only can choose one

### ISSUE THREAD

**Issue by zddr** [StarRocks/starrocks#9050]
## Enhancement
<img width="870" alt="image" src="https://user-images.githubusercontent.com/17589039/180379652-fcdc84af-b51e-4d80-81aa-ba5d0d3658c1.png">

<img width="817" alt="image" src="https://user-images.githubusercontent.com/17589039/180379768-0bc7ca93-6f67-430b-8355-e908dd9a0156.png">

<img width="818" alt="image" src="https://user-images.githubusercontent.com/17589039/180379479-cbac48fa-7588-4473-a53b-f5fcda0ac64b.png">

The be of the same host is not selected at the same time. Should it only be used as an optimization option? When the be node is insufficient, I think different be of the same host should also be selected

**Comment by imay** [comment]
This is a feature. If this physical node is down, all replica in these two backends will loss. So we let the replica balencer not arrange the same replica in the nodes with the same IP.

**Comment by zddr** [comment]
我的思路如下：

1.fe.conf增加一个是否允许同一host选择多台be的开关
2.现有逻辑是同一host下的不同be随机挑选一个用来分配.
改动点:把随机挑选剩下的节点存起来作为候补节点
3.现有逻辑是如果数量不够会直接返回分配失败，
改动点:如果数量不够，在打开开关的情况下，从候补节点中选择，选择的顺序是每个host依次挑出一个be。
例如候补节点如下：host1_be1,host1_be2
    host2_be1,host2_be2,host2_be3
那么候补节点的选择顺序为host1_be1,host2_be1,host1_be2,host2_be2,host2_be3

**Comment by chaoyli** [comment]
We want to add a pseudo-distributed cluster to the test clone. The pseudo-distributed cluster is used for the unit test/integration test. On the production cluster, I suggest changing the replication num. Because the availability of the cluster is the same for one replication/two replication. One node down, all replicas are lost. So change the replication_num to one, is ok

**Comment by chaoyli** [comment]
@zddr

**Comment by zddr** [comment]
ok,I got it,thx

**Comment by chaoyli** [comment]
We can arrange to add a pseudo-distributed cluster, do you have interest? @zddr You can add my WeChat(chaoy-li)

**Comment by LiShuMing** [comment]
I also had the same problem. @chaoyli  Maybe we can just use a session config to resolve this quickly?
