### ISSUE TITLE
the query performance  is bad with concurrency case

### ISSUE THREAD

**Issue by GeorgeHon** [StarRocks/starrocks#9223]
## General Question
hi, can someone help do some query tuning? the query performance  is bad with concurrency. with test data(only have 900 rows)   the query sql is
```SQL
select roleid, instance_uuid instance_id, max(rolename) rolename, max(occupation) as occupation, 
    max(teamid) as teamid, max(result) as result, max(fight) as fight, max(assist) as assist, max(`kill`) as `kill`, 
    max(bekill) as bekill, max(damage) as damage, max(hurt) as hurt, max(heal) as heal, max(prescore) as prescore, 
    max(changed) as changed, max(score) as score, max(deathcount) as death_count, max(start_time) as start_time, 
    max(end_time) as end_time
from playback_result_000
where instance_uuid in ( '6E91ac960001' , '6E8e9fb60004' )
    and roleid in ('429496729615','429496729623','429496729629','429496729646')
group by roleid,instance_id
order by roleid
```
the create table sql:
 ```sql
CREATE TABLE `playback_result_000` (
  `version` tinyint(4) NOT NULL COMMENT "",
  `par_dt` date NOT NULL COMMENT "",
  `roleid` varchar(128) NOT NULL COMMENT "",
  `instance_uuid` varchar(128) NOT NULL COMMENT "",
  `playback_type` tinyint(4) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `gameid` int(11) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `logtime` datetime REPLACE_IF_NOT_NULL NULL COMMENT "",
  `userid` varchar(128) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `rolename` varchar(128) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `os` int(11) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `serverid` int(11) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `platform` varchar(128) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `mediaid` varchar(128) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `md5` varchar(128) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `language` varchar(128) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `udid` varchar(128) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `templateid` bigint(20) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `teamid` varchar(128) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `occupation` varchar(128) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `fight` bigint(20) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `start_time` datetime REPLACE_IF_NOT_NULL NULL COMMENT "",
  `end_time` datetime REPLACE_IF_NOT_NULL NULL COMMENT "",
  `result_time` datetime REPLACE_IF_NOT_NULL NULL COMMENT "",
  `result` int(11) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `kill` bigint(20) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `assist` bigint(20) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `bekill` bigint(20) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `damage` bigint(20) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `hurt` bigint(20) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `heal` bigint(20) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `deathcount` bigint(20) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `time` bigint(20) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `prescore` varchar(128) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `changed` bigint(20) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `score` varchar(128) REPLACE_IF_NOT_NULL NULL COMMENT "",
  `scoretype` varchar(255) REPLACE_IF_NOT_NULL NULL COMMENT ""
) ENGINE=OLAP 
AGGREGATE KEY(`version`, `par_dt`, `roleid`, `instance_uuid`)
PARTITION BY RANGE(`version`)
(PARTITION p0 VALUES [("0"), ("1")))
DISTRIBUTED BY HASH(`roleid`) BUCKETS 70 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "par_dt, roleid, instance_uuid",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
```

this is the profile 

Query:
  Summary:
     - Query ID: f1cb3f50-0c96-11ed-bd43-525400e72cf1
     - Start Time: 2022-07-26 11:56:35
     - End Time: 2022-07-26 11:56:35
     - Total: 28ms
     - Query Type: Query
     - Query State: EOF
     - StarRocks Version: 2.2.2
     - User: default_cluster:user_behavior
     - Default Db: default_cluster:user_behaviors
     - Sql Statement: select roleid, instance_uuid instance_id, max(rolename) rolename, max(occupation) as occupation, max(teamid) as teamid, max(result) as result, max(fight) as fight, max(assist) as assist, max(`kill`) as `kill`, max(bekill) as bekill, max(damage) as damage, max(hurt) as hurt, max(heal) as heal, max(prescore) as prescore, max(changed) as changed, max(score) as score, max(deathcount) as death_count, max(start_time) as start_time, max(end_time) as end_time from playback_result_000 where instance_uuid in ( '6E91ac960001' , '6E8e9fb60004' )
and roleid in ('429496729615','429496729623','429496729629','429496729646')
 group by roleid,instance_id order by roleid
     - QueryCpuCost: 0
     - QueryMemCost: 0.000
  Execution Profile f1cb3f50-0c96-11ed-bd43-525400e72cf1:(Active: 9.63ms[9063780ns], % non-child: 100.00%)
    Fragment 0:
      Instance f1cb3f50-0c96-11ed-bd43-525400e72cf6 (host=TNetworkAddress(hostname:10.14.227.201, port:9060)):(Active: 5.444ms[5444878ns], % non-child: 0.64%)
         - AverageThreadTokens: 0.00
         - MemoryLimit: 16.00 GB
         - PeakMemoryUsage: 593.77 KB
         - RowsProduced: 6
        DataBufferSender (dst_fragment_instance_id=f1cb3f50-0c96-11ed-bd43-525400e72cf6):
           - AppendChunkTime: 8.45us
             - ResultRendTime: 24.566us
             - TupleConvertTime: 5.99us
           - NumSentRows: 6
        EXCHANGE_NODE (id=3):(Active: 5.387ms[5387129ns], % non-child: 59.44%)
           - BytesPassThrough: 0.00 
           - BytesReceived: 1007.00 B
           - DecompressChunkTime: 5.931us
           - DeserializeChunkTime: 183.4us
           - MergeSortedChunks: 165.180us
           - PeakMemoryUsage: 0.00 
           - ReceiverProcessTotalTime: 213.891us
           - RequestReceived: 4
           - RowsReturned: 6
           - RowsReturnedRate: 1.113K /sec
           - SenderTotalTime: 213.240us
           - SenderWaitLockTime: 371ns
    Fragment 1:
      Instance f1cb3f50-0c96-11ed-bd43-525400e72cf5 (host=TNetworkAddress(hostname:10.14.227.201, port:9060)):(Active: 2.95ms[2095504ns], % non-child: 0.00%)
         - AverageThreadTokens: 0.00
         - MemoryLimit: 16.00 GB
         - PeakMemoryUsage: 4.26 MB
         - RowsProduced: 2
        DataStreamSender (dst_id=3, dst_fragments=[f1cb3f500c9611ed-bd43525400e72cf6]):(Active: 186.901us[186901ns], % non-child: 2.06%)
           - PartType: UNPARTITIONED
           - BytesSent: 294.00 B
           - CompressTime: 3.626us
           - IgnoreRows: 0
           - OverallThroughput: 1.5001535415649414 MB/sec
           - SendRequestTime: 28.494us
           - SerializeChunkTime: 3.947us
           - ShuffleDispatchTime: 0ns
           - ShuffleHashTime: 0ns
           - UncompressedBytes: 544.00 B
           - WaitResponseTime: 122.260us
        SORT_NODE (id=2):(Active: 2.457ms[2457838ns], % non-child: 7.50%)
           - SortKeys: 3: roleid ASC
           - SortType: All
           - BuildingTime: 712ns
           - ChunksSorter: 72.445us
           - MergingTime: 0ns
           - OutputTime: 9.958us
           - PeakMemoryUsage: 16.45 KB
           - RowsReturned: 2
           - RowsReturnedRate: 813
           - SortingTime: 621ns
          AGGREGATION_NODE (id=1):(Active: 1.778ms[1778121ns], % non-child: 3.31%)
             - GroupingKeys: 3: roleid, 4: instance_uuid
             - AggregateFunctions: max(9: rolename), max(19: occupation), max(18: teamid), max(24: result), max(20: fight), max(26: assist), max(25: kill), max(27: bekill), max(28: damage), max(29: hurt), max(30: heal), max(33: prescore), max(34: changed), max(35: score), max(31: deathcount), max(21: start_time), max(22: end_time)
             - AggComputeTime: 19.25us
             - ExprComputeTime: 9.628us
             - ExprReleaseTime: 1.433us
             - GetResultsTime: 62.878us
             - HashTableSize: 2
             - InputRowCount: 2
             - PassThroughRowCount: 0
             - PeakMemoryUsage: 4.11 KB
             - ResultAggAppendTime: 2.405us
             - ResultGroupByAppendTime: 411ns
             - ResultIteratorTime: 9.458us
             - RowsReturned: 0
             - RowsReturnedRate: 0
             - StreamingTime: 0ns
            OLAP_SCAN_NODE (id=0):(Active: 1.478ms[1478077ns], % non-child: 10.49%)
               - Table: playback_result_000
               - Rollup: playback_result_000
               - Predicates: 4: instance_uuid IN ('6E91ac960001', '6E8e9fb60004'), 3: roleid IN ('429496729615', '429496729623', '429496729629', '429496729646')
               - BytesRead: 356.00 B
               - IOTaskCount : 1
               - NumDiskAccess: 0
               - PeakMemoryUsage: 0.00 
               - RowsRead: 2
               - RowsReturned: 2
               - RowsReturnedRate: 1.353K /sec
               - ScanConcurrency : 1
               - ScanTime: 607.892us
               - ScannerThreadsInvoluntaryContextSwitches: 0
               - ScannerThreadsTotalWallClockTime: 0ns
                 - MaterializeTupleTime(*): 0ns
                 - ScannerThreadsSysTime: 0ns
                 - ScannerThreadsUserTime: 0ns
               - ScannerThreadsVoluntaryContextSwitches: 0
               - TabletCount : 1
               - TotalRawReadTime(*): 0ns
               - TotalReadThroughput: 0.0 /sec
              SCAN:(Active: 526.859us[526859ns], % non-child: 5.81%)
                 - CachedPagesNum: 0
                 - CompressedBytesRead: 3.97 KB
                 - CreateSegmentIter: 76.874us
                 - DictDecode: 1.542us
                 - IOTime: 33.832us
                 - LateMaterialize: 97.683us
                 - PushdownPredicates: 2
                 - RawRowsRead: 8
                 - ReadPagesNum: 49
                 - SegmentInit: 204.73us
                   - BitmapIndexFilter: 0ns
                   - BitmapIndexFilterRows: 0
                   - BloomFilterFilterRows: 0
                   - SegmentZoneMapFilterRows: 0
                   - ShortKeyFilterRows: 0
                   - ZoneMapIndexFilterRows: 0
                 - SegmentRead: 22.131us
                   - BlockFetch: 2.836us
                   - BlockFetchCount: 1
                   - BlockSeek: 14.708us
                   - BlockSeekCount: 1
                   - ChunkCopy: 631ns
                   - DecompressT: 0ns
                   - DelVecFilterRows: 0
                   - IndexLoad: 0ns
                   - PredFilter: 662ns
                   - PredFilterRows: 6
                   - RowsetsReadCount: 2
                   - SegmentsReadCount: 1
                   - TotalColumnsDataPageCount: 21
                 - UncompressedBytesRead: 2.73 KB
      Instance f1cb3f50-0c96-11ed-bd43-525400e72cf2 (host=TNetworkAddress(hostname:10.14.227.202, port:9060)):(Active: 1.954ms[1954100ns], % non-child: 0.00%)
         - AverageThreadTokens: 0.00
         - MemoryLimit: 16.00 GB
         - PeakMemoryUsage: 4.27 MB
         - RowsProduced: 2
        DataStreamSender (dst_id=3, dst_fragments=[f1cb3f500c9611ed-bd43525400e72cf6]):(Active: 392.384us[392384ns], % non-child: 4.33%)
           - PartType: UNPARTITIONED
           - BytesSent: 297.00 B
           - CompressTime: 5.209us
           - IgnoreRows: 0
           - OverallThroughput: 739.1708984375 KB/sec
           - SendRequestTime: 53.50us
           - SerializeChunkTime: 7.183us
           - ShuffleDispatchTime: 0ns
           - ShuffleHashTime: 0ns
           - UncompressedBytes: 556.00 B
           - WaitResponseTime: 279.363us
        SORT_NODE (id=2):(Active: 2.9ms[2009835ns], % non-child: 6.53%)
           - SortKeys: 3: roleid ASC
           - SortType: All
           - BuildingTime: 1.12us
           - ChunksSorter: 92.733us
           - MergingTime: 0ns
           - OutputTime: 12.493us
           - PeakMemoryUsage: 16.46 KB
           - RowsReturned: 2
           - RowsReturnedRate: 995
           - SortingTime: 1.423us
          AGGREGATION_NODE (id=1):(Active: 1.417ms[1417686ns], % non-child: 2.69%)
             - GroupingKeys: 3: roleid, 4: instance_uuid
             - AggregateFunctions: max(9: rolename), max(19: occupation), max(18: teamid), max(24: result), max(20: fight), max(26: assist), max(25: kill), max(27: bekill), max(28: damage), max(29: hurt), max(30: heal), max(33: prescore), max(34: changed), max(35: score), max(31: deathcount), max(21: start_time), max(22: end_time)
             - AggComputeTime: 29.936us
             - ExprComputeTime: 10.760us
             - ExprReleaseTime: 1.843us
             - GetResultsTime: 57.67us
             - HashTableSize: 2
             - InputRowCount: 2
             - PassThroughRowCount: 0
             - PeakMemoryUsage: 4.11 KB
             - ResultAggAppendTime: 4.258us
             - ResultGroupByAppendTime: 1.92us
             - ResultIteratorTime: 8.146us
             - RowsReturned: 0
             - RowsReturnedRate: 0
             - StreamingTime: 0ns
            OLAP_SCAN_NODE (id=0):(Active: 1.174ms[1174139ns], % non-child: 8.25%)
               - Table: playback_result_000
               - Rollup: playback_result_000
               - Predicates: 4: instance_uuid IN ('6E91ac960001', '6E8e9fb60004'), 3: roleid IN ('429496729615', '429496729623', '429496729629', '429496729646')
               - BytesRead: 368.00 B
               - IOTaskCount : 1
               - NumDiskAccess: 0
               - PeakMemoryUsage: 0.00 
               - RowsRead: 2
               - RowsReturned: 2
               - RowsReturnedRate: 1.703K /sec
               - ScanConcurrency : 1
               - ScanTime: 477.555us
               - ScannerThreadsInvoluntaryContextSwitches: 0
               - ScannerThreadsTotalWallClockTime: 0ns
                 - MaterializeTupleTime(*): 0ns
                 - ScannerThreadsSysTime: 0ns
                 - ScannerThreadsUserTime: 0ns
               - ScannerThreadsVoluntaryContextSwitches: 0
               - TabletCount : 1
               - TotalRawReadTime(*): 0ns
               - TotalReadThroughput: 0.0 /sec
              SCAN:(Active: 426.648us[426648ns], % non-child: 4.71%)
                 - CachedPagesNum: 0
                 - CompressedBytesRead: 5.42 KB
                 - CreateSegmentIter: 54.271us
                 - DictDecode: 1.142us
                 - IOTime: 33.838us
                 - LateMaterialize: 81.553us
                 - PushdownPredicates: 2
                 - RawRowsRead: 22
                 - ReadPagesNum: 49
                 - SegmentInit: 141.104us
                   - BitmapIndexFilter: 0ns
                   - BitmapIndexFilterRows: 0
                   - BloomFilterFilterRows: 0
                   - SegmentZoneMapFilterRows: 0
                   - ShortKeyFilterRows: 0
                   - ZoneMapIndexFilterRows: 0
                 - SegmentRead: 13.876us
                   - BlockFetch: 1.112us
                   - BlockFetchCount: 1
                   - BlockSeek: 9.318us
                   - BlockSeekCount: 1
                   - ChunkCopy: 361ns
                   - DecompressT: 4.869us
                   - DelVecFilterRows: 0
                   - IndexLoad: 0ns
                   - PredFilter: 291ns
                   - PredFilterRows: 20
                   - RowsetsReadCount: 2
                   - SegmentsReadCount: 1
                   - TotalColumnsDataPageCount: 21
                 - UncompressedBytesRead: 4.30 KB
      Instance f1cb3f50-0c96-11ed-bd43-525400e72cf3 (host=TNetworkAddress(hostname:10.14.227.203, port:9060)):(Active: 1.740ms[1740790ns], % non-child: 0.00%)
         - AverageThreadTokens: 0.00
         - MemoryLimit: 16.00 GB
         - PeakMemoryUsage: 4.26 MB
         - RowsProduced: 1
        DataStreamSender (dst_id=3, dst_fragments=[f1cb3f500c9611ed-bd43525400e72cf6]):(Active: 267.411us[267411ns], % non-child: 2.95%)
           - PartType: UNPARTITIONED
           - BytesSent: 209.00 B
           - CompressTime: 2.976us
           - IgnoreRows: 0
           - OverallThroughput: 763.25 KB/sec
           - SendRequestTime: 25.17us
           - SerializeChunkTime: 4.128us
           - ShuffleDispatchTime: 0ns
           - ShuffleHashTime: 0ns
           - UncompressedBytes: 382.00 B
           - WaitResponseTime: 194.324us
        SORT_NODE (id=2):(Active: 1.804ms[1804089ns], % non-child: 4.96%)
           - SortKeys: 3: roleid ASC
           - SortType: All
           - BuildingTime: 751ns
           - ChunksSorter: 89.729us
           - MergingTime: 0ns
           - OutputTime: 10.251us
           - PeakMemoryUsage: 16.25 KB
           - RowsReturned: 1
           - RowsReturnedRate: 554
           - SortingTime: 531ns
          AGGREGATION_NODE (id=1):(Active: 1.354ms[1354577ns], % non-child: 2.24%)
             - GroupingKeys: 3: roleid, 4: instance_uuid
             - AggregateFunctions: max(9: rolename), max(19: occupation), max(18: teamid), max(24: result), max(20: fight), max(26: assist), max(25: kill), max(27: bekill), max(28: damage), max(29: hurt), max(30: heal), max(33: prescore), max(34: changed), max(35: score), max(31: deathcount), max(21: start_time), max(22: end_time)
             - AggComputeTime: 20.378us
             - ExprComputeTime: 8.967us
             - ExprReleaseTime: 1.994us
             - GetResultsTime: 51.627us
             - HashTableSize: 1
             - InputRowCount: 1
             - PassThroughRowCount: 0
             - PeakMemoryUsage: 4.06 KB
             - ResultAggAppendTime: 1.984us
             - ResultGroupByAppendTime: 411ns
             - ResultIteratorTime: 19.336us
             - RowsReturned: 0
             - RowsReturnedRate: 0
             - StreamingTime: 0ns
            OLAP_SCAN_NODE (id=0):(Active: 1.151ms[1151136ns], % non-child: 7.62%)
               - Table: playback_result_000
               - Rollup: playback_result_000
               - Predicates: 4: instance_uuid IN ('6E91ac960001', '6E8e9fb60004'), 3: roleid IN ('429496729615', '429496729623', '429496729629', '429496729646')
               - BytesRead: 189.00 B
               - IOTaskCount : 1
               - NumDiskAccess: 0
               - PeakMemoryUsage: 0.00 
               - RowsRead: 1
               - RowsReturned: 1
               - RowsReturnedRate: 868
               - ScanConcurrency : 1
               - ScanTime: 510.466us
               - ScannerThreadsInvoluntaryContextSwitches: 0
               - ScannerThreadsTotalWallClockTime: 0ns
                 - MaterializeTupleTime(*): 0ns
                 - ScannerThreadsSysTime: 0ns
                 - ScannerThreadsUserTime: 0ns
               - ScannerThreadsVoluntaryContextSwitches: 0
               - TabletCount : 1
               - TotalRawReadTime(*): 0ns
               - TotalReadThroughput: 0.0 /sec
              SCAN:(Active: 460.732us[460732ns], % non-child: 5.08%)
                 - CachedPagesNum: 0
                 - CompressedBytesRead: 4.76 KB
                 - CreateSegmentIter: 54.863us
                 - DictDecode: 842ns
                 - IOTime: 40.925us
                 - LateMaterialize: 85.249us
                 - PushdownPredicates: 2
                 - RawRowsRead: 15
                 - ReadPagesNum: 49
                 - SegmentInit: 164.558us
                   - BitmapIndexFilter: 0ns
                   - BitmapIndexFilterRows: 0
                   - BloomFilterFilterRows: 0
                   - SegmentZoneMapFilterRows: 0
                   - ShortKeyFilterRows: 0
                   - ZoneMapIndexFilterRows: 0
                 - SegmentRead: 17.603us
                   - BlockFetch: 1.122us
                   - BlockFetchCount: 1
                   - BlockSeek: 12.854us
                   - BlockSeekCount: 1
                   - ChunkCopy: 341ns
                   - DecompressT: 9.358us
                   - DelVecFilterRows: 0
                   - IndexLoad: 0ns
                   - PredFilter: 271ns
                   - PredFilterRows: 14
                   - RowsetsReadCount: 2
                   - SegmentsReadCount: 1
                   - TotalColumnsDataPageCount: 21
                 - UncompressedBytesRead: 3.60 KB
      Instance f1cb3f50-0c96-11ed-bd43-525400e72cf4 (host=TNetworkAddress(hostname:10.14.224.240, port:29060)):(Active: 1.233ms[1233143ns], % non-child: 0.00%)
         - AverageThreadTokens: 0.00
         - MemoryLimit: 16.00 GB
         - PeakMemoryUsage: 4.26 MB
         - RowsProduced: 1
        DataStreamSender (dst_id=3, dst_fragments=[f1cb3f500c9611ed-bd43525400e72cf6]):(Active: 402.359us[402359ns], % non-child: 4.44%)
           - PartType: UNPARTITIONED
           - BytesSent: 207.00 B
           - CompressTime: 3.482us
           - IgnoreRows: 0
           - OverallThroughput: 502.4072265625 KB/sec
           - SendRequestTime: 35.798us
           - SerializeChunkTime: 4.528us
           - ShuffleDispatchTime: 0ns
           - ShuffleHashTime: 0ns
           - UncompressedBytes: 376.00 B
           - WaitResponseTime: 334.411us
        SORT_NODE (id=2):(Active: 1.62ms[1062583ns], % non-child: 3.33%)
           - SortKeys: 3: roleid ASC
           - SortType: All
           - BuildingTime: 664ns
           - ChunksSorter: 42.952us
           - MergingTime: 0ns
           - OutputTime: 8.489us
           - PeakMemoryUsage: 16.25 KB
           - RowsReturned: 1
           - RowsReturnedRate: 941
           - SortingTime: 587ns
          AGGREGATION_NODE (id=1):(Active: 761.134us[761134ns], % non-child: 1.08%)
             - GroupingKeys: 3: roleid, 4: instance_uuid
             - AggregateFunctions: max(9: rolename), max(19: occupation), max(18: teamid), max(24: result), max(20: fight), max(26: assist), max(25: kill), max(27: bekill), max(28: damage), max(29: hurt), max(30: heal), max(33: prescore), max(34: changed), max(35: score), max(31: deathcount), max(21: start_time), max(22: end_time)
             - AggComputeTime: 14.211us
             - ExprComputeTime: 6.963us
             - ExprReleaseTime: 929ns
             - GetResultsTime: 23.68us
             - HashTableSize: 1
             - InputRowCount: 1
             - PassThroughRowCount: 0
             - PeakMemoryUsage: 4.06 KB
             - ResultAggAppendTime: 2.267us
             - ResultGroupByAppendTime: 401ns
             - ResultIteratorTime: 7.157us
             - RowsReturned: 0
             - RowsReturnedRate: 0
             - StreamingTime: 0ns
            OLAP_SCAN_NODE (id=0):(Active: 662.931us[662931ns], % non-child: 4.30%)
               - Table: playback_result_000
               - Rollup: playback_result_000
               - Predicates: 4: instance_uuid IN ('6E91ac960001', '6E8e9fb60004'), 3: roleid IN ('429496729615', '429496729623', '429496729629', '429496729646')
               - BytesRead: 183.00 B
               - IOTaskCount : 1
               - NumDiskAccess: 0
               - PeakMemoryUsage: 0.00 
               - RowsRead: 1
               - RowsReturned: 1
               - RowsReturnedRate: 1.508K /sec
               - ScanConcurrency : 1
               - ScanTime: 318.856us
               - ScannerThreadsInvoluntaryContextSwitches: 0
               - ScannerThreadsTotalWallClockTime: 0ns
                 - MaterializeTupleTime(*): 0ns
                 - ScannerThreadsSysTime: 0ns
                 - ScannerThreadsUserTime: 0ns
               - ScannerThreadsVoluntaryContextSwitches: 0
               - TabletCount : 1
               - TotalRawReadTime(*): 0ns
               - TotalReadThroughput: 0.0 /sec
              SCAN:(Active: 273.286us[273286ns], % non-child: 3.02%)
                 - CachedPagesNum: 0
                 - CompressedBytesRead: 3.49 KB
                 - CreateSegmentIter: 41.495us
                 - DictDecode: 1.11us
                 - IOTime: 23.957us
                 - LateMaterialize: 51.914us
                 - PushdownPredicates: 2
                 - RawRowsRead: 2
                 - ReadPagesNum: 49
                 - SegmentInit: 101.400us
                   - BitmapIndexFilter: 0ns
                   - BitmapIndexFilterRows: 0
                   - BloomFilterFilterRows: 0
                   - SegmentZoneMapFilterRows: 0
                   - ShortKeyFilterRows: 0
                   - ZoneMapIndexFilterRows: 0
                 - SegmentRead: 11.142us
                   - BlockFetch: 1.79us
                   - BlockFetchCount: 1
                   - BlockSeek: 6.856us
                   - BlockSeekCount: 1
                   - ChunkCopy: 337ns
                   - DecompressT: 0ns
                   - DelVecFilterRows: 0
                   - IndexLoad: 0ns
                   - PredFilter: 376ns
                   - PredFilterRows: 1
                   - RowsetsReadCount: 2
                   - SegmentsReadCount: 1
                   - TotalColumnsDataPageCount: 21
                 - UncompressedBytesRead: 2.26 KB

**Comment by jaogoy** [comment]
@liuyehcf Can you help him?

**Comment by liuyehcf** [comment]
Please provide the following information, thanks.
* What's the value of session variable `parallel_fragment_exec_instance_num`? 
* how much is the query concurrency?
* Specifications of the machine, and how many of them?
