### ISSUE TITLE
Need add get_json_object function to compatible with Hive Function

### ISSUE THREAD

**Issue by xuzifu666** [StarRocks/starrocks#9289]
## Feature request

**Is your feature request related to a problem? Please describe.**

we would meet a error as no such function when we use hive external table function such as get_json_object，to compatible with get_json_object of hive, we need add get_json_object function and it would implement ability of get_json_string. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xuzifu666** [comment]
we would meet a error as no such function when we use hive external function such as get_json_object，to compatible with get_json_object of hive, we need add get_json_object function and it would implement ability of get_json_string.

**Comment by imay** [comment]
@wangsimo0 PTAL

**Comment by wangsimo0** [comment]
LGTM
