### ISSUE TITLE
使用hive catalog和hive外表报URL using bad/illegal format or missing URL错后，所有be节点挂掉

### ISSUE THREAD

**Issue by shogunpeng** [StarRocks/starrocks#9298]
**sr版本2.3.0 release**
![image](https://user-images.githubusercontent.com/30425698/181245678-c4504371-c218-47d5-9165-f2dbad785085.png)

创建了hive catalog，core-site,hdfs-site等配置文件都已配好，export JAVA_HOME也加进了start_be.sh里。在交互界面简单的查了下hive表，返回rpc failed错误，然后全部be节点都挂掉！
下面是be节点报错日志截图，报错日志只有这两行：
![image](https://user-images.githubusercontent.com/30425698/181245741-0ee58137-59cc-4479-9be4-d8edcc249e32.png)

试了下不通过hive catalog查询，而是单独建一张hive外表，也是一样的问题。简单select，然后返回rpc failed错误，然后全部be节点都挂掉！
![image](https://user-images.githubusercontent.com/30425698/181245792-9fef74c5-503a-4d85-9a9f-e6556394bad9.png)

**Comment by DorianZheng** [comment]
could you post be.out and coredump file?

**Comment by shogunpeng** [comment]
> 

![企业微信截图_16589756943174](https://user-images.githubusercontent.com/30425698/181407906-af2775ee-f8c4-4aa0-85a2-455639d4bd3b.png)

**Comment by DorianZheng** [comment]
which version of JDK you are using, Is it JDK8?

**Comment by shogunpeng** [comment]
> which version of JDK you are using, Is it JDK8? It seems you didn't setup java environment correctly

jkd8，我是参考这个帖子（https://forum.starrocks.com/t/topic/3084）在start_be.sh里加了export java_home，因为不加的话，会报env ‘JAVA_HOME’ is not set的错，不过我刚刚看了下start_be.sh，应该是加错位置了，应该加在73行前面
![image](https://user-images.githubusercontent.com/30425698/181415637-f48fc5de-6b27-49cc-8554-0c124948691e.png)

**Comment by DorianZheng** [comment]
Is your issue solved after move statement `export JAVA_HOME` to LOC73.

**Comment by DorianZheng** [comment]
next time if you encounter any issues, you could ask us on forum directly: https://forum.starrocks.com/

**Comment by shogunpeng** [comment]
> next time if you encounter any issues, you could ask us on forum directly: https://forum.starrocks.com/

之前在论坛里有发表过关于这问题的帖子(https://forum.starrocks.com/t/topic/3236/2)，不过一直没人回复。
