### ISSUE TITLE
create materialized view finished but table status is not nomal

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#9323]
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `duplicate_table_with_null` ( `k1`  date, `k2`  datetime, `k3`  char(20), `k4`  varchar(20), `k5`  boolean, `k6`  tinyint, `k7`  smallint, `k8`  int, `k9`  bigint, `k10` largeint, `k11` float, `k12` double, `k13` decimal(27,9) ) ENGINE=OLAP DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`) COMMENT "OLAP" DISTRIBUTED BY HASH(`k1`, `k2`, `k3`) BUCKETS 3 PROPERTIES ( "replication_num" = "3", "storage_format" = "v2" );
INSERT INTO duplicate_table_with_null 
                                  VALUES 
                                    ('2020-10-22','2020-10-23 12:12:12','k3','k4',0,1,2,3,4,5,1.1,1.12,2.889);
```
```
CREATE MATERIALIZED VIEW mv1
                             AS
                             SELECT
                               k6,
                               k7,
                               k8,
                               k9,
                               k10,
                               k11,
                               k12,
                               k13
                             FROM duplicate_table_with_null;
```
wait create materialized view finished
`ALTER TABLE duplicate_table_with_null MODIFY COLUMN k7 VARCHAR(20);`

### Expected behavior (Required)
`alter table succeed`
### Real behavior (Required)
`Table[duplicate_table_with_null]'s state is not NORMAL. Do not allow doing ALTER ops`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 10dfc5a |
+----------------------+

**Comment by Astralidea** [comment]
This is not very easy to repair, the repair cost is high, and it affects the stability, so it will not be repaired for the time being.
