### ISSUE TITLE
Resource isolation

### ISSUE THREAD

**Issue by pzj6868** [StarRocks/starrocks#9335]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE 'SET GLOBAL enable_pipeline_engine = true;SET  GLOBAL enable_resource_group = true;'

### Expected behavior (Required)
User cannot set enable_pipeline_engine and enable_resource_group to false.
### Real behavior (Required)
However, you can temporarily change the value to false in your connection session.
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.2.1

**Comment by mofeiatwork** [comment]
It's the expected behavior, since these two functionalities could be disabled through switches.
