### ISSUE TITLE
[Bug] Aggregator crash in pipeline engine

### ISSUE THREAD

**Issue by trueeyu** [StarRocks/starrocks#9360]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Real behavior (Required)

![image](https://user-images.githubusercontent.com/11428742/181703008-f5073b3e-95f2-4081-a5c8-811ca5ec93fa.png)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.3.0

**Comment by jaogoy** [comment]
@trueeyu Could you add more information to describe the detail situation?

**Comment by stdpain** [comment]
dup #9519
