### ISSUE TITLE
varchar（1048576）still too small，Does not meet business needs

### ISSUE THREAD

**Issue by Mile-Z** [StarRocks/starrocks#9362]
It is recommended to change the size of varchar to about 100mb. In our hospital data, there are often large texts or column changes. 1mb is easy to exceed, and basically only about 3w patients can be stored.Knowing that the string is too large will affect the vectorized execution, but if this is changed to optional, there is no such problem. Users can specify when building the table according to their own business needs.

**Comment by mofeiatwork** [comment]
Change the limitation is easy, but keep the performance is hard. So there's no plan to change this limitation recently, until we find an optimized approach to store such a large string.

**Comment by Mile-Z** [comment]
> Change the limitation is easy, but keep the performance is hard. So there's no plan to change this limitation recently, until we find an optimized approach to store such a large string.

I know what you mean, but what I want to say is not that Starrocks is restricted to creating tables, but that users can define them themselves. There are not many scenarios used for this requirement. For example, when I create a varchar, I can choose varchar (1mb) or varchar (10mb). If I do not specify the default length of 65535, instead of 65535 like strings, it will not affect performance.
