### ISSUE TITLE
It should report error to create a table with a field of type `array<JSON>`

### ISSUE THREAD

**Issue by jaogoy** [StarRocks/starrocks#9429]
## Enhancement

Currently, we can create a table with a filed of type `array<JSON>` successfully.
By, it reports error `Error 1064: Column count doesn't match value count` to insert into values.

```SQL
create table array_table_error (
    id int,
    b1 array<JSON>
)
DUPLICATE KEY (id)
DISTRIBUTED by hash(id) BUCKETS 2;

insert into array_table
values(10, ['{"a":1}', '{"b":2}']);
```

**Comment by mofeiatwork** [comment]
`insert into array_table
values(10, [parse_json('{"a":1}'), parse_json('{"b":2}')]);
`

Above SQL could works.

**Comment by jaogoy** [comment]
Yes, it's supported. at least v2.2 supports this feature.
