### ISSUE TITLE
[sync materialized view]create task failed when refresh by year/quarter/month/week

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#9446]
### Steps to reproduce the behavior (Required)
CREATE TABLE t1 (
                  col1 date,
                  col2 double,
                  col3 varchar(20)
                ) ENGINE=OLAP
                DUPLICATE KEY(col1)
                COMMENT "OLAP"
                DISTRIBUTED BY HASH(col1) BUCKETS 3
                PROPERTIES (
                "replication_num" = "3"
                );
CREATE MATERIALIZED VIEW mv1
DISTRIBUTED BY HASH(col1) BUCKETS 10
REFRESH ASYNC START('2050-12-31') EVERY(INTERVAL 1 YEAR)
AS SELECT col1, col2
FROM t1;

### Expected behavior (Required)
`query ok`
### Real behavior (Required)
`ERROR 1064 (HY000): Can not get TimeUnit from UnitIdentifier description: YEAR`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE c3faf63 |
+----------------------+
```

**Comment by zddr** [comment]
LGTM
