### ISSUE TITLE
Error query result

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#9496]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
CREATE TABLE `aggregate_table_with_null2` ( `k1` date, `k2` datetime, `k3` char(20), `k4` varchar(20), `k5` boolean, `v1` bigint sum, `v2` bigint sum, `v3` bigint sum, `v4` bigint max, `v5` largeint max, `v6` float min, `v7` double min, `v8` decimal(27,9) sum ) ENGINE=OLAP AGGREGATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`) COMMENT "OLAP" DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3 PROPERTIES ( "replication_num" = "3", "storage_format" = "v2" );
```
2. INSERT INTO '....'
```
curl --location-trusted -u root: -T /home/disk4/lvchenyang/code/StarRocksTest/lib/../common/data/basic_types_data -XPUT -H label:stream_load_16 http://ip:port/api/lcy/aggregate_table_with_null2/_stream_load

LOAD LABEL lcy.aggregate_table_with_null2 (DATA INFILE("hdfs://ip:port/user/nose-ut-data/data") INTO TABLE `aggregate_table_with_null2` (k1,k2,k3,k4,k5,v1,v2,v3,v4,v5,v6,v7,v8) ) WITH RESOURCE test_spark_resource_8beb613a_1232_11ed_8b93_00163e0e550b PROPERTIES("timeout"="300","max_filter_ratio"="0.5");
```
3. SELECT  '....'
```
select count(*),count(k1) from aggregate_table_with_null;
select count(*) from aggregate_table_with_null where k1 is null;
```
![image](https://user-images.githubusercontent.com/57162397/182386320-3626220f-b7af-47fc-9c2e-5af0fe23a949.png)

### Expected behavior (Required)
The query result is consistent with the actual one 2
### Real behavior (Required)
Error query result
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 12c19a2 |
+----------------------+
```

**Comment by LiShuMing** [comment]
@lvchenyang-maker hi, Is there a live mysql environment to reproduce it? or can you

**Comment by lvchenyang-maker** [comment]
@LiShuMing Environmental information has been sent to your feishu
![image](https://user-images.githubusercontent.com/57162397/182513123-1e050df7-fef0-4b13-9ce3-710c962872d1.png)

**Comment by LiShuMing** [comment]
It's a bit  strange.  Maybe it's a broker load problem. I will call DW to look at it .

**Comment by LiShuMing** [comment]
The problem is not related with  query engine's`predicate` because table's number count  is not right for the `aggregate table` when it's loaded twice by using the same data.

And this problem only occurs when the data is loaded by `spark broker`.  Please @xiaoyong-z look at this.

![dKBN7LhWlc](https://user-images.githubusercontent.com/5104975/182745681-37cb5cf8-978f-4790-90eb-3e63e3f099e4.jpg)

![6aOPPe8UuV](https://user-images.githubusercontent.com/5104975/182745690-af2ea2a7-a3b4-4021-be54-425574be541e.jpg)

**Comment by xiaoyong-z** [comment]
Test https://github.com/StarRocks/StarRocksTest/commit/a3cd9f212745e909f48e65245a7d0fe7f0123330

**Comment by xiaoyong-z** [comment]
branch-2.4 cherry-pick https://github.com/StarRocks/starrocks/pull/11118
