### ISSUE TITLE
[BugFix] shouldn't close file system when broker encounters excecption

### ISSUE THREAD

**Issue by xiaoyong-z** [StarRocks/starrocks#9506]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE A
2. start load broker on some files(load A)
3. start load broker on some files(load B)
4. delete some files by load B

### Expected behavior (Required)
load B abort,
load A success

### Real behavior (Required)
load B abort,
load A also abort

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
all version

**Comment by yongbingwang** [comment]
https://github.com/StarRocks/starrocks/pull/9537
