### ISSUE TITLE
support IF NOT EXISTS option for ADD COLUMN

### ISSUE THREAD

**Issue by usharerose** [StarRocks/starrocks#9512]
## Feature request

**Describe the solution you'd like**
Add the option `IF NOT EXISTS` for the action `ADD COLUMN` when `ALTER TABLE`.
Currently would meet the error when add an existing column.

**Comment by imay** [comment]
@usharerose Could you do this feature?

**Comment by usharerose** [comment]
> @usharerose Could you do this feature?

Hi, @imay . Apologize for replying too late. I have no experience on both StarRocks's tech stack and database related development. Do we have any guideline or sample pull requests as tutorial?
