### ISSUE TITLE
insert into olap external table fail

### ISSUE THREAD

**Issue by even986025158** [StarRocks/starrocks#9538]
### Steps to reproduce the behavior (Required)
1. create olap table in target cluster
CREATE TABLE `starrocks02_target_table` (
  `event_time` datetime NOT NULL COMMENT "datetime of event",
  `event_type` int(11) NOT NULL COMMENT "type of event",
  `user_id` int(11) NULL COMMENT "id of user",
  `channel` int(11) NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`event_time`, `event_type`, `user_id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`user_id`) BUCKETS 10 
PROPERTIES (
"replication_num" = "1"
);

2. create olap external table in source cluster
CREATE EXTERNAL TABLE external_starrocks_table(
    event_time DATETIME NOT NULL COMMENT "datetime of event",
    event_type INT NOT NULL COMMENT "type of event",
    user_id INT COMMENT "id of user",
	channel INT COMMENT ""
)
ENGINE=olap
DISTRIBUTED BY HASH(user_id) BUCKETS 10
PROPERTIES
(
    "host" = "x.x.x.x",
    "port" = "9020",
    "user" = "root",
    "password" = "",
    "database" = "test",
    "table" = "starrocks02_target_table"
);

3. insert into external_starrocks_table
insert into external_starrocks_table values('2021-11-10',27,1001,01),('2021-11-10',27,1001,01),('2021-11-11',31,1002,02);

### Expected behavior (Required)
insert into success!
### Real behavior (Required)
ERROR 1064 (HY000): data cannot be inserted into table with empty partition.Use `SHOW PARTITIONS FROM external_starrocks_table` to see the currently partitions of this table. 
<img width="1446" alt="截屏2022-08-03 19 34 28" src="https://user-images.githubusercontent.com/39552698/182598813-1123249e-8840-4d02-b0ff-91c639ee3ec6.png">

### StarRocks version (Required)
source cluster  2.0.5
target cluster   2.2.2

**Comment by howrocks** [comment]
You should use remote starrocks's rpc_port to create the external table;  it's not convenient currently, we will improve it.
