### ISSUE TITLE
[sync materialized view]create mv successed by mv

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#9543]
### Steps to reproduce the behavior (Required)
```
CREATE TABLE t1
(a BIGINT,
b BIGINT,
c BIGINT,
d BIGINT,
e BIGINT,
f BIGINT)
DUPLICATE KEY(a)
DISTRIBUTED BY HASH(a) BUCKETS 10
PROPERTIES ("replication_num" = "1");

CREATE MATERIALIZED VIEW mv1
DISTRIBUTED BY HASH(a) BUCKETS 10
REFRESH ASYNC
AS SELECT a, b, c
FROM t1;

CREATE MATERIALIZED VIEW mv2
DISTRIBUTED BY HASH(a) BUCKETS 10
REFRESH ASYNC
AS SELECT a, b, c
FROM mv1;
```

### Expected behavior (Required)
`execute failed`
### Real behavior (Required)
`Query OK, 0 rows affected (0.00 sec)`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 12c19a2 |
+----------------------+

**Comment by QingdongZeng3** [comment]
Please assign this issue to me
