### ISSUE TITLE
行专列内存溢出问题咨询

### ISSUE THREAD

**Issue by linjiuqiu** [StarRocks/starrocks#9557]
咨询下SR有对行转列有什么优化的方式吗，
当前有个场景需要转换200个列，跑起来就内存溢出了，只能减少到50个左右跑，同资源的情况下spark可以跑得出来
系统环境环境：5*BE  64G16U， SPARK集群 100U 300G内存 

SQL如下：
 select 
                  a.cus_id, 
                  max(a.c1), 
                  max(a.c2), 
                  max(a.c3), 
                  max(a.c4), 
                  max(a.c5), 
                  max(a.c6), 
                  max(a.c7), 
                  max(a.c8), 
                  max(a.c9), 
                  max(
                    ifnull(a.lastbuydate, '2017-12-31')
                  ), 
                  max(
                    case when c.label_name = '000000' then c.label_value1 when c.label_name != '000000' 
                    and b.label_name = '000000' then b.label_value when c.label_name is null 
                    and b.label_name = '000000' then b.label_value else 0 end
                  ) as 000000, 
                  max(
                    case when c.label_name = '111111' then c.label_value1 when c.label_name != '111111' 
                    and b.label_name = '111111' then b.label_value when c.label_name is null 
                    and b.label_name = '111111' then b.label_value else 0 end
                  ) as 111111, 
                  max(
                    case when c.label_name = '222222' then c.label_value1 when c.label_name != '222222' 
                    and b.label_name = '222222' then b.label_value when c.label_name is null 
                    and b.label_name = '222222' then b.label_value else 0 end
                  ) as 222222, 
                  max(
                    case when c.label_name = '666666' then c.label_value1 when c.label_name != '666666' 
                    and b.label_name = '666666' then b.label_value when c.label_name is null 
                    and b.label_name = '666666' then b.label_value else 0 end
                  ) as 666666, 
                  max(
                    case when c.label_name = '777777' then c.label_value1 when c.label_name != '777777' 
                    and b.label_name = '777777' then b.label_value when c.label_name is null 
                    and b.label_name = '777777' then b.label_value else 0 end
                  ) as 777777, 
              中间省略。。。一个200来个
                  max(
                    case when c.label_name = '888888' then c.label_value1 when c.label_name != '888888' 
                    and b.label_name = '888888' then b.label_value when c.label_name is null 
                    and b.label_name = '888888' then b.label_value else 0 end
                  ) as 888888, 
                  max(
                  ABS(( murmur_hash3_32(a.cus_id)+ murmur_hash3_32('2022-07-30')) % 10) etl_date
                from 
                     t_userprofile.CONSUMER a 
                    left join t_userprofile.customer_label  b on a.cus_id = b.cus_id 
                    left join (
                   select 
                            m.label_name, 
                            m.label_value1, 
                            t.curcusid cus_id 
                        from 
                            ljq82.userprofile_customer_label_back  m 
                            inner join ljq82.userprofile_customer_label_back_enddate  n on m.label_name = n.label_name 
                            inner join t_dtl.CUSTOMER_DF t on m.cus_id = t.cus_id 
                        where 
                            n.enddate >= '2022-07-30'
--                             and t.status_id = '5'
                    ) c on a.cus_id = c.cus_id 
                    left join (
                        select 
                            d1.label_name,
                            d1.label_value,
                            d1.cus_id
                        from 
                            ljq82.userprofile_customer_label_questionnaire  d1
                        inner join (
                            select 
                                cus_id,
                                label_name,
                                max(etl_date) etl_date 
                            from 
                                ljq82.userprofile_customer_label_questionnaire
                            group by cus_id,label_name
                        ) d2 
                        on d1.cus_id = d2.cus_id and 
                            d1.label_name = d2.label_name and 
                            d1.etl_date = d2.etl_date
                    ) d 
               on a.cus_id = d.cus_id
                group by a.cus_id  
表大小
 t_userprofile.CONSUMER 9e
 t_userprofile.customer_label  1.5e
 ljq82.userprofile_customer_label_back  270w
 ljq82.userprofile_customer_label_back_enddate 12 
 t_dtl.CUSTOMER_DF 9000w
ljq82.userprofile_customer_label_questionnaire  31w
>

**Comment by imay** [comment]
Can you paste the error message?

**Comment by linjiuqiu** [comment]
> 
![image](https://user-images.githubusercontent.com/67308950/182781650-efde6120-e1d4-4844-ba12-597469fabf68.png)

THIS

**Comment by trueeyu** [comment]
can you send me one plan. 

```
explain costs xxxx;
```

**Comment by trueeyu** [comment]
Or contact me with wechat? my id is  `lxhhust350@qq.com`
