### ISSUE TITLE
审计日志中的sql有时候会变成多行，影响日志收集

### ISSUE THREAD

**Issue by undeadwing** [StarRocks/starrocks#957]
你好，我们在使用中遇到以下问题，可能是个bug，在这里反馈一下
![iHaier20211029-141630](https://user-images.githubusercontent.com/29139460/139385132-afcd6470-8064-418a-a57e-761581a3e678.png)
用户在使用dbever工具查询数据时，有的语句在审计日志中会变成多行，有的则是一行，多行的会影响日志采集

**Comment by Dshadowzh** [comment]
Could you reproduce this problem with an exact SQL?   Does it cause by Windows \r\n?

**Comment by Seaven** [comment]
如果你的sql里有注释(--, /*)的话，就会打印多行，打成一行会导致有的注释(--)可能会截断sql，导致audit log提取出来的sql不能重新执行

**Comment by jaogoy** [comment]
@undeadwing So, what form do you prefer if there are come comments (with --, /*)
