### ISSUE TITLE
Unknown system variable 'transaction_isolation'

### ISSUE THREAD

**Issue by Astralidea** [StarRocks/starrocks#9585]
### Steps to reproduce the behavior (Required)
1. set fe config mysql_sever_version = 8.0.23
2. use jdbc to connect sr

### Expected behavior (Required)
connect ok
### Real behavior (Required)
Unknown system variable 'transaction_isolation'
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.4

**Comment by mofeiatwork** [comment]
I'm afraid many works to be done to be compatible with MySQL 8.0.
