### ISSUE TITLE
Aggregate function window_ Funnel adds a mode

### ISSUE THREAD

**Issue by sym-liuyang** [StarRocks/starrocks#9595]
现有事件链的筛选模式，类型为INT。取值范围：0，1，2。

需求 ： 针对 0 模式的情况下，相同 time （DATETIME类型）不算转化。

场景 ： 计算用户买了又买的场景，如果是现有的模式，用户只购买一次商品，转化率会是100%。

**Comment by Dshadowzh** [comment]
Do you mean `strict_increase` mode in clickhouse ?
