### ISSUE TITLE
Support approximate nearest neighbor search

### ISSUE THREAD

**Issue by decster** [StarRocks/starrocks#9688]
## Feature request

Similarity search function like feature in ES:
https://www.elastic.co/blog/introducing-approximate-nearest-neighbor-search-in-elasticsearch-8-0

e.g. user profile use case, user can search a collection of users and do analysis on this collection of user

```

with similar_users as (
    select b.id, b.age, b.city from user_profile a, user_profile b 
        where a.id = b.id and a.id = <userid> 
        order by similarity(a.embedding, b.embedding) desc 
        limit 1000)
select city, count(1), avg(age) from similar_users group by city

```

**Comment by jaogoy** [comment]
It's not only a function, it's the vectorized search. It needs index or other data structure to accelerate the search.
