### ISSUE TITLE
[Bug]regexp_replace function error

### ISSUE THREAD

**Issue by zhuxt2015** [StarRocks/starrocks#9724]
### Steps to reproduce the behavior (Required)
```SQL
1. SELECT regexp_replace('["奶酪/黄油/淡奶油"]', '[\"|\[|\]]', "");
2. SELECT regexp_replace('["奶酪/黄油/淡奶油"]', '[\"|\[]', "");
```

![image](https://user-images.githubusercontent.com/13765310/183404517-9e86772d-d98f-4b95-b176-884a60ab07c9.png)

### Expected behavior (Required)
return result is `奶酪/黄油/淡奶油`
### StarRocks version (Required)
 - 2.3.0

**Comment by jaogoy** [comment]
you could use either:
SELECT regexp_replace('["奶酪/黄油/淡奶油"]', '\\[|"|\\]', "");
SELECT regexp_replace('["奶酪/黄油/淡奶油"]', '[\\["\\]]', "");

We should make a clear and detialed documentation about `regexp_replace`
