### ISSUE TITLE
no delete vector found tablet error on primary table

### ISSUE THREAD

**Issue by tiannan-sr** [StarRocks/starrocks#9725]
### Steps to reproduce the behavior (Required)
1. create primary table;
2. stream load with upsert、delete mode;
3. insert、update、delete；
4. alter table；
5. select
6. truncate table

execute step 2-6 concurrently, error :
```
ERROR 1064 (HY000) at line 1: no delete vector found tablet:54038873 segment:2049 version:2503
ERROR 1064 (HY000) at line 1: Tablet is in error state, tablet_id: 53652251 actual row size changed after compaction 76 -> 80 tablet:53652251 #version:2 [191 191.1@1 191.1] pending: rowsets:1  186 [seg:1 row:80 del:0 bytes:1235908 compaction:32318524]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
main 81db90d
```

**Comment by decster** [comment]
may related to https://github.com/StarRocks/starrocks/issues/9192
