### ISSUE TITLE
Why do both MySQL 5 and MariaDB JDBC drivers report the error "Backend not found.  Check if any backend is down or not"?

### ISSUE THREAD

**Issue by chrisfw** [StarRocks/starrocks#9803]
## MySQL Protocol / JDBC Driver question
I am trying to connect to StarRocks using JDBC (on port 9030 on the FE node) via DBeaver and both the MySQL 5 and MariaDB JDBC drivers, yet both drivers report the error "Backend not found.  Check if any backend is down or not".  I am evaluating StarRocks for use by BI tools, so connecting via JDBC is essential.

![jdbc_error](https://user-images.githubusercontent.com/6135741/183721895-6dfb60a7-5bb4-4dca-b26e-e124a92b7bcc.png)

However, if I connect to the FE node with the mysql/mariadb client, both the FE and the BE node are online and available.
Any information that can assist me with resolving this question would be greatly appreciated.

```
MySQL [(none)]> SHOW PROC '/frontends'\G
*************************** 1. row ***************************
             Name: 10.1.6.210_9010_1660050945487
               IP: 10.1.6.210
      EditLogPort: 9010
         HttpPort: 8030
        QueryPort: 9030
          RpcPort: 9020
             Role: FOLLOWER
         IsMaster: true
        ClusterId: 662818014
             Join: true
            Alive: true
ReplayedJournalId: 4627
    LastHeartbeat: 2022-08-09 13:31:54
         IsHelper: true
           ErrMsg:
        StartTime: 2022-08-09 09:15:58
          Version: 2.3.0-a9bdb09
1 row in set (0.01 sec)


MySQL [(none)]> SHOW PROC '/backends'\G
*************************** 1. row ***************************
            BackendId: 10003
              Cluster: default_cluster
                   IP: 10.1.0.26
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2022-08-09 10:23:28
        LastHeartbeat: 2022-08-09 13:31:04
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
            TabletNum: 0
     DataUsedCapacity: .000
        AvailCapacity: 616.459 GB
        TotalCapacity: 625.062 GB
              UsedPct: 1.38 %
       MaxDiskUsedPct: 1.38 %
               ErrMsg:
              Version: 2.3.0-a9bdb09
               Status: {"lastSuccessReportTabletsTime":"2022-08-09 13:30:29"}
    DataTotalCapacity: 616.459 GB
          DataUsedPct: 0.00 %
             CpuCores: 8
1 row in set (0.00 sec)
```

**Comment by imay** [comment]
could you provide some FE log context in fe/log/fe.log which contains "Backend not found. Check if any backend is down or not"

**Comment by gengjun-git** [comment]
Are your be and fe the same version?

**Comment by gengjun-git** [comment]
Hello, I have tried both mysql8 and mysql5, all works. Can you show us the DBeaver config?

**Comment by chrisfw** [comment]
Hi @imay and @gengjun-git , it appears to occur because I only had one backend configured.  I didn't realize setting up multiple backends was required.  I tried to create a table using the mysql client and it gave me an error indicating I needed a minimum of 3 backends.  I set up an additional one and I am in the process of getting a new VM created so I can create a third for further testing. 
After I set up the second backend, my JDBC connection from DBeaver now connects successfully.

**Comment by gengjun-git** [comment]
You can set the property "replication_num" = "1" in create table sql, if you have only one backend.

**Comment by chrisfw** [comment]
@gengjun-git , thank you for that information, that is much appreciated.  I will give that a try.

**Comment by chrisfw** [comment]
@gengjun-git, when I try to execute the create table statement below, I now get a timeout every time indicating there are unfinished replicas.  Is there something else I need to configure or do differently to get this to work?  

```
mysql> CREATE TABLE FLHFLATHISTORY_2022 (
    -> LOGSEQ                                BIGINT   ,
    -> MAINACCOUNTNUMBER                     BIGINT   ,
    -> PREMISENUMBER                         BIGINT   ,
    -> TAXDISTRICT                           BIGINT    ,
    -> CIHIS_CUST                            BIGINT   ,
    -> CIHIS_DATE                            BIGINT    ,
    -> HISTORYDATE                           DATE         ,
    -> CIHIS_CODE                            INT    ,
    -> CIHIS_CODE_DESC                       VARCHAR(23) )
    -> DISTRIBUTED BY HASH (HISTORYDATE) BUCKETS 10
    -> PROPERTIES (  "replication_num" = "1"  );
ERROR 1064 (HY000): fail to create tablet: timed out. unfinished replicas(3/5): 139867(10.1.0.26) 139875(10.1.0.26) 139883(10.1.0.26)  timeout=5s
```

**Comment by imay** [comment]
Could you look at the BE's log?
When you login on the BE host(10.1.0.26), could you ping the FE host (10.1.6.210)?

**Comment by gengjun-git** [comment]
You can go the BE(10.1.0.26) log dir, and search the tablet related logs (`grep 139867  be.INFO`)

**Comment by chrisfw** [comment]
@imay and @gengjun-git , thanks for pointing me in the right direction.  I believe the port used for thrift related communication was not open on the BE server.  I turned firewalld off and then was able to successfully create the table.  Can you provide me or point me to a doc with the specific list of ports that need to be open on the FE and BE servers as I don't want to leave firewalld off?  I believe I had already opened the ones listed in the deployment instructions (9050 and 9020). 
```
org.apache.thrift.transport.TTransportException: java.net.NoRouteToHostException: No route to host
        at org.apache.thrift.transport.TSocket.open(TSocket.java:226) ~[libthrift-0.13.0.jar:0.13.0]
        at com.starrocks.common.GenericPool$ThriftClientFactory.create(GenericPool.java:131) ~[starrocks-fe.jar:?]
```

**Comment by gengjun-git** [comment]
The port in the fe host: 8030, 9020, 9030, 9010

**Comment by chrisfw** [comment]
@gengjun-git , thank you for following up!
Regards,
Chris
