### ISSUE TITLE
更新模型对不存在的记录进行删除操作疑似会发生死循环

### ISSUE THREAD

**Issue by sunke38** [StarRocks/starrocks#9807]
更新模型对不存在的记录进行删除操作疑似会发生死循环

### Steps to reproduce the behavior (Required)
对一个更新模型的空表进行删除记录操作，主键值并不存在

### Expected behavior (Required)
报错或effect row 返回0
### Real behavior (Required)
Be节点CPU占用飙升150%以上 内存80%以上。执行其他查询报内存空间不足。检查be.out发现在重复输出执行删除操作的日志，疑似发生死循环。
### StarRocks version (Required)
2.3.0

**Comment by chaoyli** [comment]
@sunke38 Could you give a case? I can reproduce it and fix it?

**Comment by sunke38** [comment]
> @sunke38 Could you give a case? I can reproduce it and fix it?

like

`DELETE FROM db1.table1 WHERE id = 1234` 
table1 is an empty table or record 1234 is not exisist

be.out like this

![微信图片_20220810112759](https://user-images.githubusercontent.com/22079420/183806468-72e04487-7cf1-434c-9eba-74cc87eaf99a.png)

it repeatly output same log. cpu and mem cost boost very high

**Comment by srlch** [comment]
@sunke38 
This problem may cause by compaction policy.

How to Repeat:
1. First we make a file which has 20 del statement.
![image](https://user-images.githubusercontent.com/111035020/200718074-89ff731c-d4f4-45da-b614-01fe54821120.png)

2. create a Unique Key Table.
![image](https://user-images.githubusercontent.com/111035020/200718247-b5b6cf91-7282-46bc-a477-652be18359f4.png)

3. execute source ./del for three time，and this is equivalent to executing the delete statement 60 times.
Immediately observe the log for a while and find that base compaction has not been triggered.

4. After a short period of time, execute a single delete statement, observe the log again and find that base compaction occurs, and the amount of occurrence is large. The predicate remove operation performed in the compaction basically includes 60 delete statements in the source del.
![image](https://user-images.githubusercontent.com/111035020/200719246-cc0ce5ac-6142-4f3a-a542-a12bc2a3bd59.png)

This phenomenon is intuitively like that a single delete statement caused a large number of compaction operations like an infinite loop, but in fact it is more like accumulating a lot of delete predicates before, and then this single delete statement just triggered the corresponding base compaction. A large number of delete predicates are processed in compaction, resulting in an increase in resource usage.
