### ISSUE TITLE
[Bug]Json array element can not insert into array column

### ISSUE THREAD

**Issue by zhuxt2015** [StarRocks/starrocks#9827]
### Steps to reproduce the behavior (Required)
1. 
```
CREATE TABLE `test_array` (
  `id` int(11) NULL COMMENT "",
  `a` ARRAY<varchar(65533)> NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id`) BUCKETS 10
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);
```
2. insert into test_array select 2, jsonObject -> '$.categoryMaterial' from test_json limit 1;
3. select 2, jsonObject -> '$.categoryMaterial' from test_json limit 1;
![image](https://user-images.githubusercontent.com/13765310/183834501-fc570ea7-4b7d-4aa6-af92-04be25f76478.png)

### Real behavior (Required)
![image](https://user-images.githubusercontent.com/13765310/183834558-d0af90b2-fe9a-41c5-a995-7f7baf3a7954.png)

### StarRocks version (Required)
 - 2.3.0

**Comment by kangkaisen** [comment]
Should be we don't support cast array json to array varchar.
