### ISSUE TITLE
UDF can not used in Hive external table when user in catalog

### ISSUE THREAD

**Issue by xuzifu666** [StarRocks/starrocks#9841]
### Steps to reproduce the behavior (Required)
when we use jdbc link such as mysql -uuser -ppassword -P9030 -hhost  -Dhive_catalog0.db，then create function as
```
mysql> CREATE FUNCTION MY_TEST_FUNC(string) 
    -> RETURNS string
    -> properties (
    ->     "symbol" = "com.test.starrocks.udfs.TestUDF", 
    ->     "type" = "StarrocksJar",
    ->     "file" = "http://host/udfs-1.0-SNAPSHOT.jar"
    -> );
ERROR 1064 (HY000): Unknown database ‘db’ 
```

### Expected behavior (Required)
udf can not used in Hive external table when user in catalog

### Real behavior (Required)
```
ERROR 1064 (HY000): Unknown database ‘db’ 
```

### StarRocks version (Required)
 - 2.3.0

**Comment by stephen-shelby** [comment]
Currently, external catalog does not support UDF :(
