### ISSUE TITLE
Connecting to StarRocks using PowerBI

### ISSUE THREAD

**Issue by chrisfw** [StarRocks/starrocks#9915]
### Steps to reproduce the behavior (Required)
1.  Use MySQL Data Source in PowerBI to connect to a StarRocks instance.  This requires installing the [Connector/NET 8.0.30](https://dev.mysql.com/downloads/connector/net/)  
Make sure to change Credential Type from Windows to Database when connecting to the data source

### Expected behavior (Required)
No errors generated when establishing connection
### Real behavior (Required)
Error occurs: An error happened whil reading data from the provider: 'Input string was not in correct format'  

![powerbi_error](https://user-images.githubusercontent.com/6135741/184180752-c8739f9d-0266-4941-acaf-18ecc17727e1.png)

**The interesting thing is you can get by this error by doing a refresh.**

### StarRocks version (Required)
```
+-------------------+
| current_version() |
+-------------------+
| 2.3.0 a9bdb09     |
+-------------------+
```

**Comment by wyb** [comment]
You can use Connector/NET **8.0.23** version.

**Comment by chrisfw** [comment]
@wyb , thank you, that worked!

Regards,
Chris
