### ISSUE TITLE
SR2.3.0 表名大小写区分问题

### ISSUE THREAD

**Issue by mozhou1991** [StarRocks/starrocks#9917]
![892008651e3ef7b5272046016104e79](https://user-images.githubusercontent.com/62421826/184273187-776f0879-02ff-4e43-bf18-f229a35e5e2c.jpg)

desc 不区分大小写，但是select的时候确区分，

![bd4a761ccfb9a4d8b80532de087bea3](https://user-images.githubusercontent.com/62421826/184273248-1207094e-6c7e-4a80-a2e0-6a4bee1688f3.png)

**Comment by feihengye** [comment]
mixed some materialized view logic, need a design to fix.

**Comment by feihengye** [comment]
design:
desc default only for table, like describe [table] <Table>.
user can use describe materialized view <MV>.
