### ISSUE TITLE
[Enhancement] Check storage_root_path config in be.conf

### ISSUE THREAD

**Issue by zhuxt2015** [StarRocks/starrocks#9965]
## Enhancement
![image](https://user-images.githubusercontent.com/13765310/184360429-cd761e84-a8a3-4e5c-b828-e90e4e2896db.png)
<img width="404" alt="image" src="https://user-images.githubusercontent.com/13765310/184362594-efed190a-8d02-4afa-823f-a85333e867e6.png">

The wrong path configuration(See Figure 1, The semicolon is incorrectly written as a comma) results in too many migration tasks and a large number of resources, The memory footprint of the be server continues to rise until it goes down

## Expected behivour
First, split the storage_root_path string use semicolon then get a array, the number of commas for each array element is 0 or 1, and more than 1 is a problem path.

**Comment by trueeyu** [comment]
The reason is that the path is parsed into property and ignored directly, resulting in one less disk and triggering a large number of Clone tasks
