### ISSUE TITLE
Finished query in sleep state for a very long time

### ISSUE THREAD

**Issue by dirtysalt** [StarRocks/starrocks#9997]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

Query any external table, such as tpcds-1g  query 85

> select  substr(r_reason_desc,1,20)        ,avg(ws_quantity)        ,avg(wr_refunded_cash)        ,avg(wr_fee)  from web_sales, web_returns, web_page, customer_demographics cd1,       customer_demographics cd2, customer_address, date_dim, reason   where ws_web_page_sk = wp_web_page_sk    and ws_item_sk = wr_item_sk    and ws_order_number = wr_order_number    and ws_sold_date_sk = d_date_sk and d_year = 2000    and cd1.cd_demo_sk = wr_refunded_cdemo_sk     and cd2.cd_demo_sk = wr_returning_cdemo_sk    and ca_address_sk = wr_refunded_addr_sk    and r_reason_sk = wr_reason_sk    and    (     (      cd1.cd_marital_status = 'M'      and      cd1.cd_marital_status = cd2.cd_marital_status      and      cd1.cd_education_status = 'Advanced Degree'      and       cd1.cd_education_status = cd2.cd_education_status      and      ws_sales_price between 100.00 and 150.00     )    or     (      cd1.cd_marital_status = 'S'      and      cd1.cd_marital_status = cd2.cd_marital_status      and      cd1.cd_education_status = 'College'       and      cd1.cd_education_status = cd2.cd_education_status      and      ws_sales_price between 50.00 and 100.00     )    or     (      cd1.cd_marital_status = 'W'      and      cd1.cd_marital_status = cd2.cd_marital_status      and      cd1.cd_education_status = '2 yr Degree'      and      cd1.cd_education_status = cd2.cd_education_status      and      ws_sales_price between 150.00 and 200.00     )    )    and    (     (      ca_country = 'United States'      and      ca_state in ('IN', 'OH', 'NJ')      and ws_net_profit between 100 and 200       )     or     (      ca_country = 'United States'      and      ca_state in ('WI', 'CT', 'KY')      and ws_net_profit between 150 and 300       )     or     (      ca_country = 'United States'      and      ca_state in ('LA', 'IA', 'AR')      and ws_net_profit between 50 and 250       )    ) group by r_reason_desc order by substr(r_reason_desc,1,20)         ,avg(ws_quantity)         ,avg(wr_refunded_cash)         ,avg(wr_fee) limit 100;

```
+------------------------------+------------------+-----------------------+-------------+
| substr(r_reason_desc, 1, 20) | avg(ws_quantity) | avg(wr_refunded_cash) | avg(wr_fee) |
+------------------------------+------------------+-----------------------+-------------+
| Gift exchange                |               76 |          464.36000000 |  8.62000000 |
| Not the product that         |               70 |          876.67000000 | 46.67000000 |
| Parts missing                |                7 |          129.42000000 | 38.65000000 |
| reason 23                    |               47 |          734.61000000 |  6.17000000 |
| reason 25                    |                5 |           48.94000000 | 53.14500000 |
| reason 28                    |                8 |          306.20000000 | 37.06000000 |
+------------------------------+------------------+-----------------------+-------------+
```

### Expected behavior (Required)

When query is finished, there is no query in `show processlist`

### Real behavior (Required)

![HQRZ8FMK3Q](https://user-images.githubusercontent.com/1081215/184594431-b1e0ad13-6ae1-42fb-b3b1-34748a2dc7d0.jpg)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

```
MySQL [default_catalog.tpcds_1g_orc_zlib]> select current_version();
+-------------------+
| current_version() |
+-------------------+
| ZHANGYAN 9646a4c  |
+-------------------+
1 row in set (0.03 sec)
```

**Comment by guangxuCheng** [comment]
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/16833559/191012598-b2984df0-5375-4307-9154-1dc6ad45a0a6.png">

@kangkaisen The UI of branch-2.4 is abnormal. This issue should also be fixed on branch-2.4.
